### ISSUE TITLE
[Form] Do not fail reverse transforming relative dates

### ISSUE THREAD

**Issue by trompette** [symfony/symfony#28703] opened 2018-10-03 11:44 UTC
**Description**  

Since [v2.8.46](https://github.com/symfony/symfony/releases/tag/v2.8.46), relative dates are not supported anymore by `DateTimeType`.

I am guessing this is because of the patches :
- bug #28466 [Form] fail reverse transforming invalid RFC 3339 dates
- bug #28372 [Form] Fix DateTimeType html5 input format

It would be great to introduce the feature again by adding a dedicated value of the `format` option, or anything better you can think of.

**Example**  

At @lrqdo, the relative dates are helping us simplify our Behat scenarios.

Here is an example of a Behat scenario failing on v2.8.46:

```gherkin
When I send a POST request to "/endpoint" with values:
  | distributionDate | +14 days |
Then the response code should be 200
  Failed asserting that 400 is identical to 200.
```

Here is the form type we wrote:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add(
        'distributionDate',
        DateTimeType::class,
        array(
            'widget' => 'single_text',
        )
    );
}
```

And here is the detailed error we get:

![image](https://user-images.githubusercontent.com/181746/46359058-a90e8680-c668-11e8-8f2c-5b3fae984558.png)

**Comment by trompette** [comment] 2018-10-03 12:51
I can try but I am not sure when exactly, maybe this friday.

**Comment by xabbuh** [comment] 2018-10-03 13:34
From my point of view this never has been a supported use case and only worked "accidentally".

**Comment by trompette** [comment] 2018-10-03 15:00
I tend to agree, and this is why I chose the "Feature Request" template when creating the issue. :wink: 

Even so, I think it would be nice if it was officially supported because it has proven useful in our Behat scenarios.

**Comment by xabbuh** [comment] 2018-10-03 15:13
Wouldn't the `DateIntervalType` better support your use case?

**Comment by trompette** [comment] 2018-10-03 15:35
I am not sure `DateIntervalType` will help since the `distributionDate` property of the `data_class` is actually a `\DateTime`.

Also, it looks like `DateIntervalType` has been added with https://github.com/symfony/symfony/commit/f7669bedbf03c22f2c9635b36c3b50dd33faee91 in Symfony 3.2.

**Comment by stof** [comment] 2018-10-03 15:37
but in this case, he was getting a date 14 days in the future, not an interval.

Anyway, I'm not sure exposing everything supported by PHP's DateTime constructor is something you want in your form (the day your product manager discovers it, they will ask you to support `demain` as well, not only `tomorrow`, for proper internationalization, and you will then suffer).

**Comment by xabbuh** [comment] 2018-10-03 16:42
@fidraj This sounds more like #28699. Can you explain you send this date (i.e. where does the formatting happen)?

**Comment by fidraj** [comment] 2018-10-03 17:01
@xabbuh It comes from our frontend React datepicker component. I can specify the library name later.

**Comment by darles** [comment] 2018-10-03 17:07
Have same issue as @fidraj after an update. We were using ISO8601 format (with timezone) and DateTimeType since Symfony 2.3 and now field is not valid. To fix this issue I need to rewrite all my forms and add format argument. Even more I was not able to use ISO8601 declaration in format argument without full intl support.

**Comment by xabbuh** [comment] 2018-10-03 17:07
@fidraj Thank you, that's really appreciated. Can you provide that information in #28699 then? I have reopened that issue in the meantime.

**Comment by horlyk** [comment] 2018-10-04 08:49
I've rolled back to 2.8.45 because of the same error.
->add('startDate', DateTimeType::class, [
                'widget' => 'single_text',
                'date_format' => 'd-m-Y H:i',
                'html5' => false,
                'label' => false,
            ])

And got an error:

Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[startDate] = 06-10-2018 10:00
Caused by:
Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "startDate": The date "06-10-2018 10:00" is not a valid date.
Caused by:
Symfony\Component\Form\Exception\TransformationFailedException
The date "06-10-2018 10:00" is not a valid date.

**Comment by xabbuh** [comment] 2018-10-04 08:52
@horlyk Thank you for the additional input. #28699 will not help you, right?

**Comment by xabbuh** [comment] 2018-10-04 09:50
@horlyk It's actually weird that your code ever used to work. The `date_format` option is only meant to be used when the `widget` option is not `single_text` as this is what is then passed to the nested `DateType` (see ). In your case, using the [`format`](https://symfony.com/doc/current/reference/forms/types/datetime.html#format) option is the way to go. Just be careful that the format is must use the [ICU syntax](http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax):

```php
->add('startDate', DateTimeType::class, [
    'widget' => 'single_text',
    'date_format' => 'dd-MM-yyyy HH:mm',
    'html5' => false,
    'label' => false,
])
```

I am still going to take a look into why this worked before.

**Comment by horlyk** [comment] 2018-10-04 10:10
> @horlyk It's actually weird that your code ever used to work.

Looking at my current project's code, I'm asking myself the same question :)

By the way, thanks for noticing date format. It helped, thanks!

**Comment by xabbuh** [comment] 2018-10-04 10:36
@horlyk I think we can improve DX here (#28721 is the first step in that direction)

**Comment by horlyk** [comment] 2018-10-04 12:02
@xabbuh great!

**Comment by trompette** [comment] 2018-10-05 10:36
For the record, I found a small trick to restore the previous behaviour.

The idea is to transform the relative date into an absolute date (with the expected format) by prepending a [view transformer](https://symfony.com/doc/2.8/form/data_transformers.html#about-model-and-view-transformers) on the form field:

```diff
 $builder->add(
-    'distributionDate',
-    DateTimeType::class,
-    array(
-        'widget' => 'single_text',
-    )
+    $builder
+       ->create('distributionDate', DateTimeType::class, array('widget' => 'single_text'))
+       ->addViewTransformer(new CallbackTransformer(
+            $tranform = function ($datetime) {
+                return $datetime;
+            },
+            $reverseTransform = function ($string) {
+                return date(
+                   DateTimeToHtml5LocalDateTimeTransformer::HTML5_FORMAT,
+                   strtotime($string)
+                );
+            }
+        ))
 );
```

Since I found a workaroud, feel free to close the issue if you think the "accidental" behaviour should not be officially supported. :slightly_smiling_face:

**Comment by RuSS-B** [comment] 2018-10-18 15:23
Hey guys! Looks like I'm not the only one who used DateTimeType incorrectly
It was a surprise for me when I jumped from 4.1.3 to 4.1.6 and got "This value is not valid."

@trompette's solution works perfectly by the way

**Comment by RuSS-B** [comment] 2018-10-18 15:50
Made a wrapper of it for this cases

```
<?php

namespace App\Form\Type;

use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToHtml5LocalDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DateTimeW3CType extends DateTimeType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $dateTransformer = new CallbackTransformer(
            function ($datetime) {
                return $datetime;
            },
            function ($string) {
                return date(
                    DateTimeToHtml5LocalDateTimeTransformer::HTML5_FORMAT,
                    strtotime($string)
                );
            }
        );

        $builder->addViewTransformer($dateTransformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);
        $resolver->setDefault('widget', 'single_text');
    }
}
```

**Comment by xabbuh** [comment] 2018-10-31 07:42
I am closing here as using relative dates has never been a supported use case and as @stof explained we better not want to support everything the `DateTime` constructor accepts. The other issues discussed here look like duplicates/variants of #28699 which has been fixed in the meantime.

**Closed by xabbuh** 2018-10-31 07:42 UTC
Labels: Bug, Form, Status: Needs Review
