### ISSUE TITLE
Log file not closed causing "failed to open stream: Too many open files" during functional tests

### ISSUE THREAD

**Issue by joanlouis** [symfony/symfony#26146] opened 2018-02-12 10:33 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

phpunit : 6.5.6
php 7.1.13
xdebug 2.6.0

when i run functional tests the log file is not closed and php end up with failed to open stream: Too many open files error.
lsof | grep '^php' | grep 'test.log$' | wc -l return  245 +

**Comment by nicolas-grekas** [comment] 2018-02-27 17:40
Can you spot where this should be fixed? Could you send a PR doing that (on branch 3.4 I suppose because the issue should exist on it too)

**Comment by nicolas-grekas** [comment] 2018-04-03 11:39
Status: Waiting Feedback

**Comment by joanlouis** [comment] 2018-04-03 12:15
i don't know very well symfony core and monolog but i can say that monolog open  and re-open the log file and never close it.

**Comment by xabbuh** [comment] 2018-07-06 08:57
@joanlouis Could you create a small example that allows to reproduce the issue so someone else could maybe work on a solution?

**Comment by OndraM** [comment] 2018-08-20 14:10
Hi, we twice came across the same issue after upgrade to latest Symfony, we also thought the cause is Monolog or Symfony, but after some debugging, we found the root cause was actually Guzzle, which used async client by default, and if some API request was called multiple times (~ hundreds of http requests), the connections were not closed (which is standard async client behavior), thus leading to this error, as the identifier of the open stream is saved to filesystem. 

So make sure this is not your case.

**Comment by xabbuh** [comment] 2018-08-20 14:36
I am closing here for now. We can consider to reopen when we have a reproducible example.

**Closed by xabbuh** 2018-08-20 14:36 UTC
Labels: Bug, Status: Waiting feedback

**Comment by torreytsui** [comment] 2019-07-18 14:24
@xabbuh 

Maybe the `\\Monolog\Handler\StreamHandler::close` is never called when it should be (e.g., when Kernel shutdown)?

I have run into this issue when I do a heavy Behat test with nearly 1000 test cases, each of them will reboot the Kernel.

With `lsof -p <PID> | wc -l`, I keep seeing log file get opened.

The issue is not significant on production as the the handle resource close automatically when the process die. However, it is visible when we do automated test where single process runs for many kernel cycles.

**Comment by torreytsui** [comment] 2019-07-18 14:40
@xabbuh @nicolas-grekas With above new finding, can we please reopen this issue?

**Comment by xabbuh** [comment] 2019-07-18 15:13
Can you create a small example application that allows us to reproduce the issue?

**Comment by torreytsui** [comment] 2019-07-18 21:09
Sure! Here you go.

https://github.com/torreytsui/symfony-too-many-open-files-replication

**Comment by leevigraham** [comment] 2020-07-03 06:30
@torreytsui did you manage to resolve this? We just ran into it as well.

**Comment by torreytsui** [comment] 2020-07-03 07:36
@leevigraham No, unfortunately. I have worked around the issue tho, if I remember correctly.

https://github.com/symfony/symfony/issues/26146#issuecomment-512838192

In the kernel shutdown, I close the resources.

I have not tested with the latest symfony version. I'm not sure if the issue still persist.

If you can try the example application above and it replicate the issue and give them more information, we can try to convince the core member to reopen this issue.

**Comment by andy-educake** [comment] 2020-11-23 09:58
We are seeing a similar issue (only with Behat tests). With 259 scenarios, it works fine. As soon as I added the 260th scenario I got the "too many open files" error on my local machine. Your workaround fixes the problem. As you say though, that is a bit of a hack. I wonder if the problem should be solved in the Monolog bundle? I will open a ticket there and see if we can work something out.
