### ISSUE TITLE
[DependencyInjection] Fatal error when using ExceptionInterface

### ISSUE THREAD

**Issue by YetiCGN** [symfony/symfony#44371] opened 2021-11-30 17:48 UTC
### Symfony version(s) affected

5.3.11, 5.4.0, 6.0.0

### Description

The `ExceptionInterface` extends both `Psr\Container\ContainerExceptionInterface` and `\Throwable`. The `ContainerExceptionInterface` itself extends `\Throwable` already since `psr/container` 1.1.0. This leads to the following error:

```
PHP Fatal error:  Class Symfony\Component\DependencyInjection\Exception\ExceptionInterface cannot implement previously implemented interface Throwable in ~/vendor/symfony/dependency-injection/Exception/ExceptionInterface.php on line 22
```

### How to reproduce

Run `vendor/bin/typo3cms` from TYPO3 10.4.21 with `symfony/dependency-injection` 5.3.11 and `psr/container` 1.1.2 installed. Unfortunately it doesn't give a stack trace.

### Possible Solution

Remove the redundant extension of `\Throwable` as the minimum version for `psr/container` is 1.1 anyway.

**Comment by YetiCGN** [comment] 2021-11-30 17:49
PhpStorm points it out as well:
![image](https://user-images.githubusercontent.com/447119/144100666-6b02e8e7-ec91-46f1-9903-a1a4bb849023.png)

**Comment by nicolas-grekas** [comment] 2021-11-30 17:49
Please send a PR :)

**Comment by YetiCGN** [comment] 2021-11-30 17:50
> Please send a PR :)

Coming up later today. 🙂

**Comment by derrabus** [comment] 2021-11-30 17:58
Duplicate of php-fig/container#30

Implementing a previously announced interface is fine since PHP 7.4, see https://3v4l.org/o7hOj.

**Closed as completed by derrabus** 2021-11-30 17:58 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by derrabus** [comment] 2021-11-30 18:04
… just for the record: If you use an earlier version of PHP, you should neither have Symfony 6.0.0 nor psr/container 1.1.2 installed. ☝🏻🤓

**Comment by YetiCGN** [comment] 2021-11-30 22:52
> … just for the record: If you use an earlier version of PHP, you should neither have Symfony 6.0.0 nor psr/container 1.1.2 installed. ☝🏻🤓

You're right, target server still has PHP 7.3 even though I requested an upgrade to 7.4 last week. 😬 Didn't know about that! Thanks.
