### ISSUE TITLE
MockResponse with empty body getContent(false) gives http_code 200, should be 0 or 204

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#35007] opened 2019-12-17 11:45 UTC
**Symfony version(s) affected**: 4.4.1

**Description**  

Perhaps I don't understand how the `MockResponse('')` is intended, but an empty http response is either status code 0 (timeout or some such) or status code 204 No Content.

* using `$response->getStatusCode()` always gives 200, which is always wrong, although should perhaps be possible to create if for some reason you create it that way in your API.
* using `$response->getContent(true)` gives TransportException, which is wrong if a 204 was intended.
* using `$response->getContent(false)` correctly gives an empty string (`''`)

**How to reproduce**  
```
$responses = [
    new MockResponse('', ['http_code' => 0]), // transfer problem
    new MockResponse('', ['http_code' => 204]), // intended no content
    new MockResponse(''), // probably should default to statuscode=204
];

$client = new MockHttpClient($responses);

// each of the responses incorrectly gives a 200 response
foreach ($response as $res) {
    $response = $client->request('GET', 'http://some/url');
    $this->assertEquals(200, $response->getStatuscode(), 'should be 0 or 204 instead!');
}
```

**Possible Solution**  
Change the order in the MockResponse constructor

```
$this->info = $info + ['http_code' => 200] + $this->info;
```

to

```
$this->info = ['http_code' => 200] + $info + $this->info;
```

Aside from this, in the ResponseTrait we have

line 144, this wil create a TransportException when no body. That seems fundamentally incorrect, as a 204 No Content is a real thing.
```
        if ('' === $content = $this->getContent($throw)) {
            throw new TransportException('Response body is empty.');
        }
```

line 249. This will trigger for http_code=0, why? At least for mocks this might be intended
```
        if (!$info['http_code']) {
            throw new TransportException('Invalid or missing HTTP status line.');
        }
```

**Additional Context**  

All I'm really looking for actually is a way to mock a transfer problem.. and in my code I use `$response->getContent(false)`, so the only thing I can think of is look at the statusCode of `0`

**Comment by nicolas-grekas** [comment] 2019-12-18 14:16
A mock response is yours to configure. The less logic it has the better. If you're not OK with 200 (which is still a fine code even when the body is empty btw), change it to what you need. Closing as this is the intended behavior. Thanks for submitting.

**Closed by nicolas-grekas** 2019-12-18 14:16 UTC
Labels: Bug, HttpClient, Status: Needs Review

**Comment by rbaarsma** [comment] 2019-12-18 16:26
@nicolas-grekas I agree, but how can I change it without writing my own MockResponse? It's impossible to overwrite the 'http_code' info option, because of this code:

```
$this->info = $info + ['http_code' => 200] + $this->info;
```

**Comment by nicolas-grekas** [comment] 2019-12-18 16:37
> $this->info = $info + ['http_code' => 200] + $this->info;

This line means that if you set `$info['http_code']`, your value is going to be used. That's because the `+` operator for arrays doesn't override existing keys, isn't it?

**Comment by rbaarsma** [comment] 2019-12-18 16:46
Okay I did some more testing, I'm not 100% why yet, but this does not work:

```
new MockResponse('', ['http_code' => 0]), // transfer problem
// status_code=200
```

it constructs fine with http_code=0, but later a new MockResponse is created from the request, instead of using the given MockResponse

If I change it to:
```
new MockResponse('', ['http_code' => 500]), // transfer problem
// statuscode=500 :+1:
```

it works as expected and gives a 500 status code.

Also the same problem is if I set the content, so that seems unrelated
```
new MockResponse('my content', ['http_code' => 0]), // transfer problem
// still statuscode=200
```

**Comment by rbaarsma** [comment] 2019-12-18 16:48
It's in this code:

```
        } else {
            $response = $this->responseFactory->current();
            $this->responseFactory->next();
        }

        return MockResponse::fromRequest($method, $url, $options, $response);
```

The `500` status code gets into the else, while the `0` statusCode gets into the return MockResponse::fromRequest(...) line

**Comment by nicolas-grekas** [comment] 2019-12-18 17:07
`0` is not a valid status code actually, did you try with 204?
`0` is the status reported when the status code is not known yet.
But once the headers arrive, a >= 100 status code is expected.
I think that's why `0` is not allowed: no real response can have it as a resulting code.

**Comment by rbaarsma** [comment] 2019-12-19 10:40
Okay I can live with `0` not being allowed (an error would be convenient perhaps), but my main question is: how can I Mock a transfer error? I want to ensure my application my application handles transfer errors correctly and as far as I know (when `$response->getContent(false)`) is used, it gives a `0` status_code (the default). Therefore this is a valid use-case for a MockResponse?

**Comment by nicolas-grekas** [comment] 2019-12-19 10:43
Did you try with a generator as a body, that throws between two yield?
https://symfony.com/doc/current/components/http_client.html#testing-http-clients-and-responses

![image](https://user-images.githubusercontent.com/243674/71167288-b8b9c100-2254-11ea-8b9f-cb5c517903b7.png)

**Comment by rbaarsma** [comment] 2019-12-19 12:00
You are right, that works :)

Not very intuitive, but testing both transfer error, OK response and 500 error is now this:

```
        $body = function () {
            yield '';
            yield 'OK';
        };

        $responses = [
            new MockResponse($body()),
            new MockResponse('NOK', ['http_code' => 500]),
        ];
```

Thanks for your help!

**Comment by NicoHaase** [comment] 2020-08-14 09:57
@nicolas-grekas I'd like to second this bug report. Using the following code, I would assume that the first request to the HTTP client returns an response with code 400:

```
$callback = function ($method, $url, $options) {
    return new MockResponse('[]', ['http_code' => 400]);
};

$mockedClient = new MockHttpClient($callback);
``` 

Against my expectation, the first request returns a response with code 200. Through debugging, I could follow to `\Symfony\Component\HttpClient\Response\MockResponse::writeRequest` which fetches the data from the mocked response properly (`$mock->getInfo()` returns the expected code 400), but merging it with the current state of the MockResponse is not done properly

**Comment by vasilvestre** [comment] 2020-09-04 07:26
> @nicolas-grekas I'd like to second this bug report. Using the following code, I would assume that the first request to the HTTP client returns an response with code 400:
> 
> ```
> $callback = function ($method, $url, $options) {
>     return new MockResponse('[]', ['http_code' => 400]);
> };
> 
> $mockedClient = new MockHttpClient($callback);
> ```
> 
> Against my expectation, the first request returns a response with code 200. Through debugging, I could follow to `\Symfony\Component\HttpClient\Response\MockResponse::writeRequest` which fetches the data from the mocked response properly (`$mock->getInfo()` returns the expected code 400), but merging it with the current state of the MockResponse is not done properly.
> 
> As a small, simplfied example for these lines:
> 
> ```
> $currentCode = ['http_code' => 200];
> $mockCode = ['http_code' => 400];
> 
> $currentCode += $mockCode;
> 
> var_dump($currentCode); // returns code 200 instead of 400
> ```
> 
> I would assume that using the `+=` is not valid here, as this will never carry over any info elements set within the mocked inner response to the mock response info array
> 
> I've checked this on Symfony 4.4.10, but the code from 5.1.3 looks the same

Hello, maybe you could create a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)

**Comment by NicoHaase** [comment] 2020-09-15 07:35
@vasilvestre well, now I'm sad: my reproducer at https://github.com/NicoHaase/symfony-35007-reproducer shows that everything is alright :( Need to look into this again as soon as I come across this again, but currently, I cannot reproduce the problem myself which I was confident of four weeks ago

**Comment by vasilvestre** [comment] 2020-09-15 07:37
> @vasilvestre well, now I'm sad: my reproducer at https://github.com/NicoHaase/symfony-35007-reproducer shows that everything is alright :( Need to look into this again as soon as I come across this again, but currently, I cannot reproduce the problem myself which I was confident of four weeks ago

Try to move code of your bug scope from your project to the reproducer and try to see when it does break

**Comment by nicolas-grekas** [comment] 2020-09-15 08:03
I missed the comments on this issue for many weeks since it is closed.
@NicoHaase your comment looks like it could deserve a separate issue, once you have a reproducer.

**Comment by NicoHaase** [comment] 2020-09-15 08:14
Sorry for disturbing this issue...

@vasilvestre sadly, I've found another way to resolve my initial problem, so my application does not contain any code to trigger the bug either.

@nicolas-grekas fair point, but I still have to find any way to reproduce first :P
