### ISSUE TITLE
RequestDataCollector error after login

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#19701] opened 2016-08-22 11:40 UTC
after upgrading SF to version 3.1.3 I'm getting error after login

**Notice: Array to string conversion**
RequestDataCollector.php at line 378

when I dump $controller in RequestDataCollector->parseController at first line in function:

![error](https://cloud.githubusercontent.com/assets/4276289/17853606/e87d3fba-686d-11e6-81b7-385dc30b99ea.png)

**Comment by jakzal** [comment] 2016-08-22 16:21
@poolerMF are you use you haven't modified the RequestDataCollector? v3.1.3 has a closing brace on line 378.

Can you check what's going on earlier in the parseController method where it [uses reflection with the array elements](https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L332). This code might throw an exception. The only scenario I can see that it reaches the end of the method with an array is when `is_callable` returns false [while handling that exception](https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L342-L352).

**Comment by poolerMF** [comment] 2016-08-22 17:53
@jakzal sorry, it's at line 378 after I applied dump ... so original error is at line 378

I figured out where was the error ... I didn't have method **loginCheckAction** in **SecurityController**
In latest SF version it worked without this method ... 

I think in my situation it should throw 500 Internal Server Error with message:

`The controller for URI "/?????" is not callable. Expected method "loginCheckAction" on class "......\SecurityController" ... `

**Comment by jakzal** [comment] 2016-08-25 13:11
@poolerMF I know what seems to be causing your problem but cannot reproduce it. Do you think you could isolate your problem in a fresh installation of Symfony?

**Comment by xabbuh** [comment] 2016-09-27 20:50
ping @poolerMF Any news on this? :)

**Comment by poolerMF** [comment] 2016-09-28 05:58
@xabbuh I reproduce project with error:
https://github.com/poolerMF/SF_19701

try to make login and you will see error ... uncomment some lines in SecurityController and everything will work

In latest SF version it worked without method loginCheckAction


I think, it should throw this exception:

```
The controller for URI "/?????" is not callable. Expected method "loginCheckAction"
on class "......\SecurityController" ... 
```


instead of this:
```
Array to string conversion
```

**Comment by jakzal** [comment] 2016-10-18 13:10
@poolerMF thanks to your work I was able to reproduce and fix the issue 🍺

**Closed** 2016-10-22 14:30 UTC
Labels: Bug, HttpKernel, Status: Needs Review
