### ISSUE TITLE
[RFC] Discussing the requirement of components, bridges and bundles in the 3.4 branch

### ISSUE THREAD

**Issue by stof** [symfony/symfony#22756] opened 2017-05-18 16:29 UTC
https://github.com/symfony/symfony/pull/22742 changed the constraints in the 3.4 branch to allow 4.0.x version of the other components. After that, I had a lengthy discussion with @nicolas-grekas on Slack challenging it. We now think it is time to share our thoughts outside the core team (and with core team members not connected at this time) to involve the whole community.

> Note: for the whole discussion, I will talk about components, but this also applies to bridges and bundles developed in the symfony/symfony repo. It is just shorter than repeating `components, bridges and bundles` all the time.

The whole point of this discussion is to decide how the requirements of the of inter-component dependencies should look like in the 3.4 branch. There is 3 possible options:

1. `^3.2`, not allowing any usage of 4.x dependencies
2. `^3.2 || ~4.0.0`, allowing only the 4.0.x versions of deps, but not 4.1+ (what #22742 did, and what we did for 2.8 as well)
3. `^3.2 || ^4.0`, allowing the whole 4.x releases, relying on the BC promise of 4.x

> Note: example above assume that the lowest bound of the existing 3.3 constraint is `3.2`. It can be something else for each requirement, so things should be adapted above accordingly.

The third option was rejected by @nicolas-grekas because it hurts our promise that the Symfony code will never trigger deprecations by itself (i.e. calling a non-deprecated API from your own code does not make Symfony call a deprecated API internally on its own), as it precisely relies on BC layers.

I'm arguing that we should stick with the first option, because of the way Composer works and because of our ecosystem change with Flex.

Regarding Composer, what you need to remember is how it chooses the installed version: it always selects the highest version available which matches your constraints. So if you require `^3.2 || ~4.0.0`, it will always try to use a 4.0.x release first. This has 2 drawbacks:

- 4.0 brings BC breaks (this is why it is named 4)
- 4.0.x is not a LTS version, meaning it will go unmaintained much before 3.4

Regarding the ecosystem change, the big difference is what Symfony users will tell Composer when they want to use our 3.4 LTS version (because they have not yet migrated their code to 4.x APIs for instance):

- in the symfony-standard way, they would tell "Give me Symfony 3.4" (i.e. `composer require symfony/symfony ^3.4`), and they would get the 3.4 version of the whole Symfony code
- in the flex way, they would tell "Give me FrameworkBundle 3.4" (i.e. `composer require symfony/framework-bundle ^3.4`), and they would *expect* to get 3.4 version of Symfony. But the options above may break this assumption.

What is important to remember is that people using `symfony/framework-bundle` as a dependency actually spend most of their time interacting with transitive dependencies brought in by FrameworkBundle:

- they write route definitions (`symfony/router`)
- they write controllers (`symfony/http-kernel`)
- they handle requests and responses in their controller (`symfony/http-foundation`)
- they write service definitions (`symfony/dependency-injection`)
- they trigger or listen to events (`symfony/event-dispatcher`)
- ...

If we go with the option 2, a new Symfony 3.4 project would automatically get the 4.0 version of all the components I listed just above (and a few others), until another rule forbids to use version 4. and this is very bad, because it means people will *not* receive BC layers anymore, which basically breaks our BC promise.

> Note: FrameworkBundle is not the only package having mandatory requirements on other Symfony packages, but it was the best example for this case as it is the entry point of using Symfony in Flex.

This could also affect external projects relying on Symfony components, as they could also be relying on transitive deps (`symfony/http-kernel` bringing in `symfony/http-foundation`).

> Note: Things can become even worse if `symfony/framework-bundle` removes the explicit require on `symfony/http-foundation` and relies on `symfony/http-kernel` bring it to the user instead, as bring in 4.0.x for HttpKernel then allows bring in any 4.x version for HttpFoundation, which goes to option 3.

I only see 2 ways to avoid this issue:

- stick to option 1, meaning that a dependency between Symfony components cannot require a higher major version than the current one (allowing *lower* major versions of them is fine, and 4.x components should actually all allow 3.4 version of their deps as the 3.4 version will have all the features they need)
- teach people to never rely on transitive deps for the packages they directly use in their project, which means that the Symfony skeleton should list much more packages by default (duplicating the FrameworkBundle deps without allowing 4.0.x).

Due to the effect on DX, I strongly suggest sticking to option 1. But the call is now on the community, to decide about option 1, 2 or 3 above.

Note that for *dev* requirements, we should allow bringing in 4.0 versions, unless we also have a conflict rule forbidding them, because this helps ensuring that users don't end up in non-working cases (as optional deps cannot be enforced to stay on 3.x if we don't have conflict rules forbidding them, as we don't control the requirement bringing them in).

**Comment by iltar** [comment] 2017-05-18 18:41
I believe option 1 would be the best suited with the least headache-spaghetti-dependencies. If I understand it right, you will use either 3.x or 4.x, but not a mix of both. This is fine for me, I don't see why someone should even be using 2 different minor versions of Symfony.

**Comment by theofidry** [comment] 2017-05-18 18:45
Maybe we could allow a kind of vote for each option. I'm gonna write a message for each option so that people can add reactions to it :)

React to this message for the first option:

>^3.2, not allowing any usage of 4.x dependencies

**Comment by theofidry** [comment] 2017-05-18 18:46
>^3.2 || ~4.0.0, allowing only the 4.0.x versions of deps, but not 4.1+ (what #22742 did, and what we did for 2.8 as well)

**Comment by theofidry** [comment] 2017-05-18 18:46
>^3.2 || ^4.0, allowing the whole 4.x releases, relying on the BC promise of 4.x

**Comment by nicolas-grekas** [comment] 2017-05-18 19:03
I'm sorry but this topic is too complex to be just voted on into the wild, especially when the discussion did not really happen yet.

**Comment by theofidry** [comment] 2017-05-18 19:05
the vote doesn't prevent you to debate and you can always change your vote after seeing more discussions

**Comment by nicolas-grekas** [comment] 2017-05-18 19:39
1. Not allowing 4.0 dependencies creates a synchronization effect that does not fit with the fact that components are standalone. If one wants to use eg Yaml 4 but is blocked with FrameworkBundle 3, is see absolutely no reason to forbid it if it just works. That disqualifies option 1 to me.
2. Allowing 4.0.0 was chosen when we prepared 3.0 because it allows clear forward path, that we know worked in the past (and was well thought also at that time)
3. I think we might try this option - at least we can wonder what would happen if we were to allow 3.* on 2.8

The problem Stof describes existed already when we worked on 3.0. The issue is that more people will experience it with Flex.

But to me, there is a 4th option (which does not conflict with 2. nor 3.): create a special package that forces a synchronized version for all components. By requiring this special package as 3.4, one would force all Symfony components to be 3.4.*. This would be done only by mean of conflict rules, so that this packahe itself does not install *any* other package transitively. But whenever you need one, either directly or transitively, this packahe would enforce that you only get one matching the constraint that you expressed there. WDYT of this idea?

**Comment by theofidry** [comment] 2017-05-18 22:36
After your comment, I'm leaning more on the second option. The reason why I don't think 1. is so much of an issue is because even as standalone, it's usually easy to upgrade components together.

However your idea looks like a good compromise, but I'm curious on how you would do it, and how maintainable it would be.

**Comment by xabbuh** [comment] 2017-05-19 07:00
I am in favour of the third option.

> The third option was rejected by @nicolas-grekas because it hurts our promise that the Symfony code will never trigger deprecations by itself (i.e. calling a non-deprecated API from your own code does not make Symfony call a deprecated API internally on its own), as it precisely relies on BC layers.

IMO this is not an issue. We already have this when you use, for example, Symfony 3.2. When something got deprecated in 3.3 (or will be deprecated in 3.4), we do not update any 3.2 either. So what we should guarantee is that you can use components with the same version without us triggering deprecations, but that's not something we will promise when you mix different releases.

**Comment by jvasseur** [comment] 2017-05-19 07:58
Maybe we could go for option 1 for bundles to prevent getting 4.0 components when requiring them (and maybe adding conflict rules for optional dependencies).

And use option 2 or 3 for components to allow more flexibility for them.

**Comment by stof** [comment] 2017-05-19 08:06
@jvasseur I don't think we should have a different rule for bundles or components. Both can have transitive deps, and the issue is exactly the same in both cases for people relying on the transitive deps

**Comment by stof** [comment] 2017-05-19 10:14
another argument for option 1: supporting 4.x actually require extra checks in 3.4 for our BC layers: https://github.com/symfony/symfony/pull/22774

**Comment by nicolas-grekas** [comment] 2017-05-19 10:50
#22769 makes me think option 3 should be the way to go

**Comment by sstok** [comment] 2017-05-21 09:19
I have a very simple opinion about this: 

> That what you use yourself, you restrict (when you depend on package A directly, you define it in
> your own composer.json, even when another package already installs it).

For two reasons:

1. If your remove the head dependency (B), which installed (A) that also depend on your application doesn't break.
2. (B) could increase the version constraints thus pulling in a newer versions that is not compatible with your package/application.

> If I have *my* component (A) with a dependency on component (B), and component (B) is already installed by another component (C) that (A) also depends on. I still define the requirement of (B) explicitly to prevent breakage when I know my component (A) is not compatible (yet) with a newer version of (B), and (C) may/will at any point increase the version constraints.

Of course this level of strictness is not always required, if you follow development closely **and** there is a good BC promise in place. But for example Doctrine ORM has a more flexible BC promise then Symfony, so allowing boundless installation of a newer Doctrine ORM version (by relying on a another dependency) will eventually break in the future.

With Symfony Flex however enforcing this will become harder as many component will be installed without a restriction in the root package (like we have now for symfony/symfony). And defining all of these? 😅 (you may not even know you are affected).

I like the idea of @jvasseur about using conflicts, but more as an meta-package like `symfony/symfony-version-restriction:3.3` which forbids any major upgrade, or a tool that updates your root composer file with explicit packages and constraints (to better control your own stability, maybe Flex can even do this?).

In the end it all comes down to who carries the responsibility, Symfony's code *is* compatible and can use a newer version. But the code of the application is possibly not, IMO it's the responsibility of the root package to protect the version constraints of packages the root package uses itself.

**Comment by derrabus** [comment] 2017-05-25 13:05
If all components should be able to stand on their own, it should imho be possible to migrate them more or less independently.

I've had a Sliex project for instance, where some components were migrated from 2.8 to 3, other were not because third party packages had compatibility issues with Symfony 3. Should such a project be pinned to Symfony 2.8 just because some third party library is a bit behind? I don't think so and that disqualifies option 1 for me.

Now option 2. That would mean that an LTS version locks you in on a version that's going to run out of support. Meh.

So option 3 looks best for me atm. That would mean that as the maintenance of 3.4 LTS goes on, compatibility fixes for newer 4.x components need to be applied sometimes, otherwise the issues of option 2 will come up later.

But there's another hidden problem here: What if a component A that in version 4.0 is compatible with component B in version 3.4 suddenly drops that support with release 4.1? This has happened to us in the project I've mentioned earlier for the migration from 3.1 to 3.2. And I don't have an easy solution to this. Maintaining a compat layer for 3.4 components in 4.0 might be too much effort (depending on the differences).

**Comment by xabbuh** [comment] 2017-05-25 13:11
@derrabus The last issue you mention should not happen because of our BC promise (what's working in 4.0 must still work in 4.1). Do you remember what actually was causing issues for you?

**Comment by derrabus** [comment] 2017-05-25 13:25
@xabbuh Yes, the project was pinned to EventDispatcher 2.8 (because Guzzle 3 🙄) and WebProfilerBundle decided to not accept this anymore:

https://github.com/symfony/web-profiler-bundle/compare/3.1...3.2#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by xabbuh** [comment] 2017-05-25 13:29
But that's something Composer is solving to you by not updating a package version of the new version's requirements could not be fulfilled.

**Comment by derrabus** [comment] 2017-05-25 14:05
@xabbuh Exactly, but composer's "solution" is to leave me with a version that's running out of support pretty soon.

**Comment by theofidry** [comment] 2017-05-25 14:15
@derrabus Composer does what it's expected to do: if you want to upgrade, update your code to be able to update/remove the problematic dependency.

**Comment by nicolas-grekas** [comment] 2017-05-25 15:22
It looks like we are converging on option 3. + option 4.

See #22885 and #22769 for option 3.
See #22916 for option 4.

**Comment by derrabus** [comment] 2017-05-25 16:16
@theofidry Sure, I'm not blaming anyone for anything, least of all composer. And I'm not complaining. The issue has been dealt with, so I'm not asking for support either.

All I'm saying is, if Symfony allows/encourages users to mix LTS packages with recent ones, problems like the one I've mentioned might emerge. @xabbuh said, that this must not happen because of the BC promise, I gave him an example where it actually did happen. That's all. 😇

**Closed** 2017-05-25 23:28 UTC
Labels: RFC
