### ISSUE TITLE
The UrlType renders an <input type = "text" /> instead of an <input type = "url" />

### ISSUE THREAD

**Issue by iraldoad** [symfony/symfony#30635] opened 2019-03-22 02:42 UTC
**Symfony version(s) affected**: 3.4.22

**Description**  
The Url Type renders an <input type = "text" /> instead of an <input type = "url" /> so this field is not validated in Google Chrome.

**Comment by xabbuh** [comment] 2019-03-22 07:18
Which Symfony version do you use? How is your form configured?

**Comment by ro0NL** [comment] 2019-03-22 08:59
Related to #29691?

**Comment by iraldoad** [comment] 2019-03-24 03:30
Hi. Sorry for the delay when responding. This is the field:

```php
$builder->add('url', UrlType::class, [
                'default_protocol' => 'https',
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'https://domain.com',
                    'pattern' => '^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$'
                ]
            ])
```
As you can see I had to add a pattern to validate the url. This is the HTML:
```html
<input type="text" name="entity[url]" class="form-control" placeholder="https://domain.com" pattern="^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$" inputmode="url">
```

**Comment by iraldoad** [comment] 2019-03-24 03:33
![Anotación 2019-03-23 223230](https://user-images.githubusercontent.com/15159678/54874562-9ecd7980-4dbb-11e9-9f89-aa46b15d95f6.jpg)

**Comment by ro0NL** [comment] 2019-03-24 09:54
#29926 is released in 3.4.22, looks like you received a bugfix :sweat_smile: 

(because of default_protocol the input should allow for protocol-less values, hence type text in this case)

**Comment by xabbuh** [comment] 2019-03-24 13:37
As @ro0NL explained this is the expected behaviour. So I'm going to close here. Thank you for understanding.

**Closed by xabbuh** 2019-03-24 13:37 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback

**Comment by iraldoad** [comment] 2019-03-24 20:28
As I understand, if I remove the default protocol option should I render the input to url type?

**Comment by xabbuh** [comment] 2019-03-24 21:10
If you remove the option, the type will be rendered as a url input type.

**Comment by iraldoad** [comment] 2019-03-24 21:17
Well no, it continues to be rendered in the same way.

**Comment by xabbuh** [comment] 2019-03-24 21:21
Can you create a example application that allows to reproduce your problem?

**Comment by iraldoad** [comment] 2019-03-25 01:46
I have created a project but I have not been able to prove it. Use the crud generator and do not open the form page. Initially he sent me the following error **"Maximum function nesting level of '256' reached, aborting! stackoverflow"**. Afterwards no longer.
This is the link: [https://github.com/iraldoad/my_project.git](https://github.com/iraldoad/my_project.git)

**Comment by xabbuh** [comment] 2019-03-25 11:22
When adding the `url` type in the `buildForm()` method of your custom `UrlType`, you do not reference the`UrlType` from the Form component, but again add your own `UrlType` which creates a recursion (see https://github.com/iraldoad/my_project/pull/1). And then you need to explicitly set `default_protocol` to `null` as its default value is `http` (I have corrected by comment above):

```php
```

**Comment by iraldoad** [comment] 2019-03-26 01:53
Great. Ok thanks.

**Comment by lmlsna** [comment] 2019-04-27 00:15
So the default behavior is to render `type="text"` instead of `type="url"` on a `UrlType` unless a we explicitly declare a null default_protocol? Why?
