### ISSUE TITLE
[PhpUnitBridge] PHPUnit 8 incompatibility

### ISSUE THREAD

**Issue by evertharmeling** [symfony/symfony#30071] opened 2019-02-04 10:18 UTC
**Symfony version(s) affected**: 4.2.x (but probably all `PHP<7.0` compatible versions too)

**Description**  
Using the `symfony/testpack`, `symfony/phpunit-bridge` and setting the `phpunit` version on `8.0`. When creating a test which extends `Symfony\Bundle\FrameworkBundle\Test\KernelTestCase` it will throw the following error:
```
PHP Fatal error:  Declaration of Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::tearDown() must be compatible with PHPUnit\Framework\TestCase::tearDown(): void in /projects/phpunit-8/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 24
```

**How to reproduce**  

https://github.com/evertharmeling/symfony-phpunit-8

Using the 'reproducer' project:
* Run `composer install` in project root.
* Run `vendor/bin/simple-phpunit` in project root.

**Possible Solution**  

* Restricting the `phpunit/phpunit` version to `<8.0`

**Additional context**  

Somewhat related https://github.com/symfony/symfony/issues/14736. Because this could solve for support on `phpunit >=8.0`

**Comment by alexander-schranz** [comment] 2019-02-05 22:21
Another solution could be using [class_alias](http://php.net/manual/de/function.class-alias.php): see https://github.com/symfony/symfony/pull/30084

**Comment by evertharmeling** [comment] 2019-02-18 09:44
https://github.com/symfony/symfony/pull/30124

**Comment by xabbuh** [comment] 2019-02-18 10:07
I think we can close here now that the related PRs were merged.

**Closed by xabbuh** 2019-02-18 10:07 UTC
Labels: FrameworkBundle, PhpUnitBridge

**Comment by mente** [comment] 2019-02-19 08:50
Wasn't #30124 merged only into 3.4 branch only? This bug report is about 4.2

**Comment by xabbuh** [comment] 2019-02-19 08:54
We regularly merge lower branches up into branches for all still maintained Symfony versions. So the bugfix will also be part of the next 4.2 patch release.

**Comment by alexander-schranz** [comment] 2019-02-19 08:55
@mente all fixes for 3.4 will also be part of the 4.2 release.

**Comment by garak** [comment] 2019-03-06 18:52
What about other Symfony tests?
For example, https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Test/FormIntegrationTestCase.php is still missing the `void` return type, so extending it to test a form is not working.
Doing a quick search (just a `grep -r 'function setUp()' vendor/symfony/ | grep Test`), I can find 208 occurrences of `setUp` method, all without `void` return type.

**Comment by nicolas-grekas** [comment] 2019-03-06 18:56
@garak There should be two distinct approaches. One for `Test` namespaces, another for the internal `Tests` ones. Would you mind sending a PR for the first case, following what's been done for KernelTestCase?

**Comment by garak** [comment] 2019-03-07 08:54
@nicolas-grekas I'd be glad to propose a PR, but I'm afraid I'm a bit lost... I tried to search in related issues and PRs and only found something related to `tearDown`, nothing about `setUp`.
Can you point me in the right direction? Thanks

**Comment by nicolas-grekas** [comment] 2019-03-07 09:19
I think the same strategy as https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Test/KernelShutdownOnTearDownTrait.php could work for `setUp` too. I didn't have a better look so can't be more specific sorry.

**Comment by garak** [comment] 2019-03-07 10:07
But in this case the content of `setUp` is not the same, duplicating it with `eval` looks a bit cumbersome to me. What if a target a PR to 4.2 branch instead?

**Comment by nicolas-grekas** [comment] 2019-03-07 10:10
Adding `void` on 4.2 would immediately break all CI that don't use phpunit8 yet. No go.

**Comment by StevenCarre** [comment] 2019-05-03 14:31
How can I restrict oh-unit version to <8.0?

**Comment by evertharmeling** [comment] 2019-05-03 14:39
@StevenCarre when using `PhpUnitBridge` with https://github.com/evertharmeling/symfony-phpunit-8/blob/master/phpunit.xml.dist#L14

**Comment by StevenCarre** [comment] 2019-05-03 14:45
thank you. Can you tell me where this file is located please?

**Comment by evertharmeling** [comment] 2019-05-03 14:53
You can place the xml configuration file where you want, but you have to point to the configuration file when running `(simple-)phpunit`, like `bin/simple-phpunit -c /path/to/phpunit.xml.dist`.

See https://phpunit.readthedocs.io/en/8.1/textui.html and https://phpunit.readthedocs.io/en/8.1/configuration.html

**Comment by mrtnzagustin** [comment] 2020-03-05 15:54
Hi there, i have a problem when executing ./vendor/bin/simple-phpunit in a docker testing stage container. Each time i make a build, test are slow cause simple-phpunit dowload phpunit. How can i download it with other command to mantain it in cac

**Comment by nicolas-grekas** [comment] 2020-03-05 15:55
you should run `./vendor/bin/simple-phpunit install` just after `composer install`, when building the image.

**Comment by mrtnzagustin** [comment] 2020-03-06 13:12
@nicolas-grekas , thanks. I've installed phpunit with that command. The problem is when i run `RUN ./vendor/bin/simple-phpunit` after the installation, load of fixtures, etc. The output is:

![image](https://user-images.githubusercontent.com/12588882/76085921-c77d5d80-5f91-11ea-8076-7745dc8773d9.png)

**Comment by mrtnzagustin** [comment] 2020-03-06 15:37
In addition, trying setting version in phpunit.xml.dist, and the `./vendor/bin/simple-phpunit install` dont use that version. When the test are executed with `./vendor/bin/simple-phpunit`, the script install the version in the file.

**Comment by mrtnzagustin** [comment] 2020-03-06 16:11
The problem vanish when i use a single line to copy the entire app and just one composer install:
```Dockerfile
RUN composer install
COPY [".", "/var/www/"]
RUN ./vendor/bin/simple-phpunit install

# Crea la base de datos y la carga con fixtures
RUN php bin/console doctrine:database:create --env=test --no-debug
RUN php bin/console doctrine:schema:update --env=test --force --no-debug
RUN php bin/console hautelook:fixtures:load --env=test

# Ejecuta testing
RUN ./vendor/bin/simple-phpunit
```
but error in test execution when i do this:
```Dockerfile
# Copia solo dependencias y las instala
COPY composer.json composer.json
COPY composer.lock composer.lock
COPY symfony.lock symfony.lock
RUN composer install --prefer-dist --no-scripts --no-autoloader && rm -rf /root/.composer
RUN ./vendor/bin/simple-phpunit install 

# Copia el codigo fuente a donde corresponde dentro del contenedor
COPY [".", "/var/www/"]

# Finish composer
RUN composer dump-autoload --no-scripts --optimize

# Crea la base de datos y la carga con fixtures
RUN php bin/console doctrine:database:create --env=test --no-debug
RUN php bin/console doctrine:schema:update --env=test --force --no-debug
RUN php bin/console hautelook:fixtures:load --env=test

# Ejecuta testing
RUN ./vendor/bin/simple-phpunit
```

**Comment by enriquerene** [comment] 2020-10-28 13:00
I replaced `function setUp ()` by `function setUp (): void` and worked for me (PHPUnit 8, Synfony 5.1).

**Comment by StevenCarre** [comment] 2021-06-14 14:25
@enriquerene one year later thanks, it worked for me too. Cheers
