### ISSUE TITLE
Kernel version for 3.0.4 is named "3.0.4-DEV"

### ISSUE THREAD

**Issue by manuelkiessling** [symfony/symfony#18514] opened 2016-04-12 09:00 UTC
Introduced with c2f6078d014e24171fd168c19f58da8917e328ce. Is this on purpose? 3.0.3 lacked the `-DEV` part. I assumed that the 3.x.x release branch is stable.

**Comment by stloyd** [comment] 2016-04-12 09:01
Duplicate of #18380.

**Comment by javiereguiluz** [comment] 2016-04-12 09:01
@manuelkiessling there was a bug with the release tool, causing the version constranits not to be updated. This is fixed now and upcoming releases (e.g. 2.8.5) will have the correct versions again.

For now, yes, you've installed 2.8.4 stable.

**Closed by javiereguiluz** 2016-04-12 09:01 UTC
