### ISSUE TITLE
Allow more arguments to ParameterBag::has()

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#42370] opened 2021-08-04 12:02 UTC
I suggest allowing more than one argument to `ParameterBag::has()`, the same way `isset()` works.

For example:

    isset($_POST['requiredParam1'], $_POST['requiredParam2'], $_POST['requiredParam3'])

Must now be written as:

    $request->request->has('requiredParam1') && $request->request->has('requiredParam2') && $request->request->has('requiredParam3')

A shorter and cleaner syntax, backwards compatible, would be:

    $request->request->has('requiredParam1', 'requiredParam2', 'requiredParam3')

The method should return false as soon as a parameter doesn't exist, without checking the remaining ones.

**Comment by derrabus** [comment] 2021-08-04 12:08
Duplicate of #42125

**Closed as completed by derrabus** 2021-08-04 12:08 UTC
Labels: HttpFoundation
