### ISSUE TITLE
Segfault in symfony/cache PhpFilesTrait with php 7.4.1 (opcache)

### ISSUE THREAD

**Issue by lewbor** [symfony/symfony#35292] opened 2020-01-10 04:28 UTC
**Symfony version(s) affected**: 4.4

**Description**  
Threre is a problem with symfony/cache PhpFilesTrait with php 7.4.1: PhpFilesTrait use opcache_invalidate() and opcache_compile_file() functions that cause a segfault in php 7.4.1

**Possible Solution**  
Dont use opcache_compile_file() with php 7.4.0 and 7.4.1. May be it will fixed in latest versions..

**Additional context**

**Comment by nicolas-grekas** [comment] 2020-01-17 11:18
Can you try again with 7.4.2? If it fails, can you open a PHP bug report?

**Comment by liarco** [comment] 2020-01-24 20:00
> Can you try again with 7.4.2? If it fails, can you open a PHP bug report?

I don't have enough experience to understand the root causes, but I started experiencing random segfaults with the following environment:

- Kubernetes `1.15.5`
- custom `php:7.2-apache` docker image with `opcache` enabled and other performance tweaks from https://symfony.com/doc/current/performance.html
- Symfony `4.3.10`
- PHP `7.4.1`

I found out that the errors were not exactly *random*, they were appearing on specific routes _(even some from EasyAdminBundle, but not all entities)_. It was also happening right after the cache size was over a certain limit (`~25M` in my case). Clearing opcache with `opcache_reset()` was solving the problem temporarily.

After some investigations I found that PHP `7.4.2` has some bugfixes related to `opcache` and segmentation faults: https://www.php.net/ChangeLog-7.php#7.4.2

So I updated my containers to test it and it seams to work... at least I'm now reaching `36.6M+` of cache size and no errors.

Can this help?

**Comment by nicolas-grekas** [comment] 2020-01-24 20:12
Sure, this means we can close the issue :)

**Closed** 2020-01-26 09:20 UTC
Labels: Cache, Status: Waiting feedback

**Comment by tristanbes** [comment] 2020-01-27 12:39
Well,

@nicolas-grekas // @xabbuh I hate to bring this bad news, but we are mumltiple users that have been experiencing the segfault when using PHP 7.4.1 or even 7.4.2

I posted on Symfony slack at least 3 other person (including @javiereguiluz ) is experiencing this.

<img width="793" alt="Slack___general___Symfony_Devs" src="https://user-images.githubusercontent.com/346010/73175251-048c3f80-410a-11ea-986c-ad0621580872.png">

I've been experiencing this with` PHP7.4.1` && `PHP7.4.2` using `SF 4.4.2` or `4.4.3` with opcache enabled (but no preload)

It's been happening form 2 completely different applications (one with EasyAdminBundle, one without).

Since then, we've blocked the 7.4 upgrade PR, and reverted to PHP7.3 for the other application.

<img width="510" alt="Slack___general___Symfony_Devs" src="https://user-images.githubusercontent.com/346010/73175397-5c2aab00-410a-11ea-9b21-e5aaa8273d66.png">

**Comment by nicolas-grekas** [comment] 2020-01-27 12:43
Then you should open a php bug report.

**Comment by tristanbes** [comment] 2020-01-27 12:46
That's why I didn't want to report that in an official way :D I don't know how to report a proper bug case that doens't look like "hey this is happening, i don't know how, i don't know when, good luck, bye ;)"

**Comment by nicolas-grekas** [comment] 2020-01-27 12:48
Providing a reproducer will help them for sure.

**Comment by Nightbr** [comment] 2020-02-20 11:13
Hey,

we have same issue (`docker php-fpm 7.4.1`). Here is our debug logs if it can helps:

It occurs only when we make some changes in the code so it's clearly linked to the cache refresh. PHP-FPM crashed `error child 16 exited on signal 11 (SIGSEGV)`. After that, we need to restart php-fpm to get it works again. It works well on each query as long as we don't change any line of code. 

_We try to disable XDEBUG, bug still occured (every php smoke test begin by disabling xdebug :laughing: )._

We try to disable OPCACHE, No more crashed :tada: @liarco  seems you're right & it comes from a real opcache issue.

Now we have upgraded php-fpm to `7.4.2` & it seems to work fine so far. 

Here is my opcache config:

```
opcache.enable=1
opcache.memory_consumption=256
opcache.use_cwd=0
opcache.max_file_size=0
opcache.max_accelerated_files=30000
opcache.validate_timestamps=1
opcache.revalidate_freq=0
```
