### ISSUE TITLE
Container App_KernelDevDebugContainer.xml is no longer dumped

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#39240] opened 2020-11-30 12:46 UTC
**Symfony version(s) affected**: Symfony 5.2.0

**Description**  
It appears the container xml file is no longer dumped when using 
`bin/console cache:clear` nor `bin/console cache:warmup`

**How to reproduce**  

<img width="1091" alt="app_yprox___srv_app_admin" src="https://user-images.githubusercontent.com/346010/100611836-3ebe0300-3312-11eb-9431-c7dc2db0a2ce.png">

**Possible Solution**  
The workaround is to lint the container using `bin/console lint:container`. This way, the `App_KernelDevDebugContainer.xml` file is created.

**Comment by ondrejmirtes** [comment] 2020-11-30 12:51
PHPStan needs the XML version of the container in order to do its job, so I'd like to know what's the replacement command to generate the XML, thanks!

**Comment by chalasr** [comment] 2020-11-30 13:28
I cannot reproduce on a fresh install of Symfony 5.2 (container is properly dumped at cache:clear).
Can you provide a reproducer? The debug container is dumped by [ContainerBuilderDebugDumpPass](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php) which is registered here: https://github.com/symfony/symfony/blob/6440b70b3124036b44f6b7af5e9d23e9226f2dc0/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L167

**Comment by tristanbes** [comment] 2020-11-30 13:50
For a moment, i thought it was related to MacOS Big Sur / VirtualBox and some obscure NFS problem. But I remembered that the Github Actions (unbutu) failed too:

![try_warming_up_the_cache_·_Yproximite_yProx_327f14e](https://user-images.githubusercontent.com/346010/100617324-a24c2e80-331a-11eb-9e48-adc330e03734.png).

it's weird since my colleague who runs on debian host/vm does not have this issue at all;

<img width="977" alt="Slack___Hugo_Alliaume___Yproximite___53_new_items" src="https://user-images.githubusercontent.com/346010/100617591-03740200-331b-11eb-946c-818d053fd113.png">

I'll try to isolate the variance, especially if you cannot reproduce on a fresh install. Sorry if it's a false positive but failing on dev + CI was enough for me to create the issue especially when only deps was upgraded.

**Comment by dmaicher** [comment] 2020-11-30 14:01
I can reproduce it on the second run of `cache:clear` as described in this issue: https://github.com/symfony/symfony/issues/39232

**Comment by tristanbes** [comment] 2020-11-30 14:16
That makes sense @dmaicher since the cache is already cleared before on the CI 👍

**Comment by khonkisz** [comment] 2020-12-02 07:54
Same problem here

**Comment by chalasr** [comment] 2020-12-15 09:11
Fixed in #39360

**Closed as completed by chalasr** 2020-12-15 09:11 UTC
Labels: Bug, Status: Needs Review
