### ISSUE TITLE
Env variables don't pass the configuration

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#22594] opened 2017-05-01 10:56 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

If you have a configuration node with a non-string type, e.g. `IntegerNode`, and pass an env variable, even though the env variable will be resolved in an integer, the value won't pass the validation and throw an error when booting.

e.g.:

```yaml
parameters:
    int_val_param: '%env(INT_ENV_VAL)%'

app:
    int_val: '%int_val_param%'
```

or:

```yaml
app:
    int_val: '%env(INT_ENV_VAL)%'
```

with:

```php
// Configuration file

public function getConfigTreeBuilder()
{
    $treeBuilder = new TreeBuilder();

    $treeBuilder->root('app')
        ->children()
            ->integerNode('int_val')
            ->isRequired()
            ->end()
        ->end()
    ;

    return $treeBuilder;
}
```

will throw:

```
  [Symfony\Component\DependencyInjection\Exception\EnvParameterException]
  Incompatible use of dynamic environment variables "INT_ENV_VAL" found in parameters.

  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]
  Invalid type for path "app.int_val". Expected int, but got 'string'.
```

Issue reproduced on the repo: https://github.com/theofidry/symfony-22594

**Comment by ro0NL** [comment] 2017-05-01 12:04
Related to #22151 i guess :)

**Comment by nicolas-grekas** [comment] 2017-05-01 12:10
Yep, that's the same topic. This is not a bug, the exception says it perfectly: this is just not supported yet.
Thus, this is a feature request. If one wants to work on typed env vars, please do.

**Comment by nicolas-grekas** [comment] 2017-05-01 12:11
Closing as duplicate.

**Closed by nicolas-grekas** 2017-05-01 12:11 UTC

**Comment by theofidry** [comment] 2017-05-01 14:06
Isn't it slightly different? #22151 is more about being able to cast the env value whereas here it's about allowing a string in the case of an env var for a non-string node. #22151 would be a way to fix this issue of course, but we could think of a simpler fix: don't throw a type exception when encountering an env string.
