### ISSUE TITLE
Improve a confusing error about fragments/hinclude/templating

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#31393] opened 2019-05-06 11:09 UTC
**Symfony version(s) affected**: all

**Description**  
I'm updating a Symfony app to 4.2 + Flex. I'm converting the old app/config/config.yml into the new config/packages/*.yaml

When browsing the app, I saw this error:

![image](https://user-images.githubusercontent.com/73419/57221522-defd5a00-6fff-11e9-9a08-a42a53fd215f.png)

I had this in `config/packages/framework.yaml`:

```yaml
framework:
    # ...

    fragments:
        enabled: true
        path: '...'
```

There's no other config option to enable/disable "hinclude" specifically ... so I didn't know what to do.

Then, luckily, I remembered that I had deleted this when doing the config file conversion:

```yaml
framework:
    # ...
    templating:
        engines: ['twig']
```

Adding that solved the problem. But we should improve the error message, because it's very confusing and doesn't help find the solution. Thanks!

**Comment by Zowac** [comment] 2019-05-07 17:58
Hi,
I taking this if nobody work on it :)

**Comment by fabpot** [comment] 2019-05-08 05:51
@Zowac Thanks for volunteering. I've investigating the error myself (as I have access to the project where @javiereguiluz has the error). You won't be able to improve the message as the current one cannot be changed (it is generic) and the circumstancies when this happens are "rare" (and should never happen on a project using Flex). So, I'm closing the issue.

**Comment by wtorsi** [comment] 2019-08-17 06:55
@fabpot the problem still exists in 4.3.
As i see, the origin of the problem is that TwigBundle adds `ExtensionPass` before `FragmentRendererPass` in FrameworkBundle. 
So, for those who have this kind of Exception, the dirty solution can be adding `ExtensionPass` again in your `Kernel` but with the high priority.

```
...
use Symfony\Bundle\TwigBundle\DependencyInjection\Compiler\ExtensionPass;

class Kernel extends BaseKernel
{
...
    protected function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new ExtensionPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 1);
    }
...
}
```

**Comment by javiereguiluz** [comment] 2019-09-27 10:01
Let's reopen so we can investigate this further. Thanks.

**Comment by xabbuh** [comment] 2019-10-01 08:01
@manu-sparheld Could you please create a small example application that allows to reproduce this?

**Comment by manu-sparheld** [comment] 2019-10-01 09:01
@xabbuh  Yes. Will push it soon

**Comment by javiereguiluz** [comment] 2019-10-01 10:01
@xabbuh I've reproduced it in 4.3: https://github.com/javiereguiluz/reproduce_31393_issue

I uncommented `fragments: true` in `config/packages/framework.yaml` and the error happens. It's explained in detail here: https://github.com/javiereguiluz/reproduce_31393_issue/blob/7bd3dd465b78b3d3cd836768413e5d1fed960cc5/config/packages/framework.yaml#L18

**Comment by mehlichmeyer** [comment] 2020-01-23 11:14
@javiereguiluz what's the status here? I am available to look into this if need be.

**Comment by manu-sparheld** [comment] 2020-01-23 11:18
it got fixed => https://goo.gl/fb/xgvUiZ

**Closed** 2020-02-14 07:32 UTC
Labels: DX, Status: Waiting feedback, good first issue
