### ISSUE TITLE
[HttpClient] chunk content empty when the response is not 200

### ISSUE THREAD

**Issue by roromix** [symfony/symfony#41379] opened 2021-05-22 07:13 UTC
**Symfony version(s) affected**: 5.2.9

**Description**
When a stream response status code isn't 200 `$chunk->getContent()` is empty

**How to reproduce**
```php
    public function sendRequest(): self
    {
        $responses = $this->client->request('POST', self::RESOURCE_BASE_URL.'/'.self::RESOURCE_PATH, [
            'json' => array_merge(
                $this->getAuthParams(),
                $this->getResourceParams()
            )
        ]);

        foreach ($this->client->stream($responses) as $response => $chunk) {

            $infos = $chunk->getInformationalStatus();
            $contentID = $infos['headers']['Content-ID'] ?? null;

            switch ($contentID) {
                case null:
                case '<jsonInfos>':
                    $this->setResponse($chunk->getContent(), $responses->getStatusCode());
                    break;
                case '<label>':
                    $this->label = $chunk->getContent();
                    break;
            }
        }

        return $this;
    }
```

**Possible Solution**
I don't know ;) Sorry

**Additional context**
Profiler Request:
```
https://ws.colissimo.fr/sls-ws/SlsServiceWSRest/2.0/generateLabel
[▼
  "json" => [▼
    "contractNumber" => "*******"
    "password" => "*******"
    "outputFormat" => [▼
      "x" => 0
      "y" => 0
      "outputPrintingType" => "PDF_A4_300dpi"
    ]
    "letter" => [▼
      "service" => [▶]
      "parcel" => [▶]
      "sender" => [▶]
      "addressee" => [▶]
    ]
  ]
]
```
Profiler Response:
```
[▼
  "info" => [▼
    "header_size" => 355
    "request_size" => 815
    "total_time" => 0.55399
    "namelookup_time" => 0.347956
    "connect_time" => 0.367625
    "pretransfer_time" => 0.415925
    "size_upload" => 606.0
    "size_download" => 380.0
    "speed_download" => 687.0
    "speed_upload" => 1095.0
    "upload_content_length" => 606.0
    "starttransfer_time" => 0.553737
    "primary_ip" => "***.***.**.***"
    "primary_port" => 443
    "local_ip" => "***.**.*.*"
    "local_port" => 52064
    "http_version" => 2
    "protocol" => 2
    "scheme" => "HTTPS"
    "appconnect_time_us" => 415762
    "connect_time_us" => 367625
    "namelookup_time_us" => 347956
    "pretransfer_time_us" => 415925
    "starttransfer_time_us" => 553737
    "total_time_us" => 553990
    "start_time" => 1621664418.8334
    "pause_handler" => Closure(float $duration) {#803 ▶}
    "debug" => "Due to a bug in curl 7.64.0, the debug log is disabled; use another version to work around the issue."
  ]
  "response_headers" => [▼
    b"HTTP/1.1 400 Mauvaise Requête"
    "Date: Sat, 22 May 2021 06:20:20 GMT"
    "Server: Apache"
    "Vary: User-Agent"
    "Access-Control-Allow-Origin: *"
    "P3P: policyref="/w3c/p3p.xml", CP="NOI DSP COR NID CUR ADM DEV OUR BUS""
    "Connection: close"
    "Transfer-Encoding: chunked"
    "Content-Type: multipart/mixed; boundary="uuid:8ad061cd-3186-46a6-8216-d48bf476c95c";charset=UTF-8"
  ]
  "response_content" => [▼
    """
      --uuid:8ad061cd-3186-46a6-8216-d48bf476c95c
      Content-Type: application/json;charset=UTF-8
      Content-Transfer-Encoding: binary
      Content-ID: <jsonInfos>
      
      {"messages":[{"id":"30204","type":"ERROR","messageContent":"Le numéro / libellé de voie du destinataire n'a pas été transmis"}],"labelXmlV2Reponse":null,"labelV2Response":null}
      --uuid:8ad061cd-3186-46a6-8216-d48bf476c95c--
      """
  ]
]
```

When i have a 200 response, it return me 2 chunks : JSON and PDF File Content.

**Comment by nicolas-grekas** [comment] 2021-05-22 08:23
I suspect the reason is that you don't deal with all possibilities appropariately.
From the doc, a working control loop might look like this:
```php
foreach ($client->stream($responses) as $response => $chunk) {
    try {
        if ($chunk->isTimeout()) {
            // ... decide what to do when a timeout occurs
            // if you want to stop a response that timed out, don't miss
            // calling $response->cancel() or the destructor of the response
            // will try to complete it one more time
        } elseif ($chunk->isFirst()) {
            // if you want to check the status code, you must do it when the
            // first chunk arrived, using $response->getStatusCode();
            // not doing so might trigger an HttpExceptionInterface
        } elseif ($chunk->isLast()) {
            // ... do something with $response
        }
    } catch (TransportExceptionInterface $e) {
        // ...
    }
}
```

Eg I don't know why you call `getInformationalStatus();`? Is that because the server sends `100 Continue` while uploading?

**Comment by roromix** [comment] 2021-05-22 08:55
@nicolas-grekas 
### In case of 200 response
`getInformationalStatus();` return the headers described in the response content for the current chunk :
I control the chunk has header Content-ID = `<jsonInfos>` for use JSON response and Content-ID = `<label>` for use Document Data.

2 chunk received :
```
--uuid:e090ed69-ffe2-4c15-b584-1e6eb3cf7460
Content-Type: application/json;charset=UTF-8
Content-Transfer-Encoding: binary
Content-ID: <jsonInfos>

{"messages":[{"id":"0","type":"INFOS","messageContent":"La requête a été traitée avec succès","replacementValues":[]}],"labelXmlV2Reponse":null,"labelV2Response":{"parcelNumber":"6A************","parcelNumberPartner":"*************************","pdfUrl":null,"fields":{"field":[{"key":"NETWORK_NAME","value":""},{"key":"PARTNER_NAME","value":""},{"key":"PARTNER_CAB","value":""},{"key":"CN23_THERMIQUE","value":""}],"customField":[{"key":"NETWORK_NAME","value":""},{"key":"PARTNER_NAME","value":""},{"key":"PARTNER_CAB","value":""},{"key":"CN23_THERMIQUE","value":""}]}}}
--uuid:e090ed69-ffe2-4c15-b584-1e6eb3cf7460
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary
Content-ID: <label>

***DOCUMENT DATA***

--uuid:e090ed69-ffe2-4c15-b584-1e6eb3cf7460--
```
The first chunk `getContent()` return
```
{"messages":[{"id":"0","type":"INFOS","messageContent":"La requête a été traitée avec succès","replacementValues":[]}],"labelXmlV2Reponse":null,"labelV2Response":{"parcelNumber":"6A************","parcelNumberPartner":"*************************","pdfUrl":null,"fields":{"field":[{"key":"NETWORK_NAME","value":""},{"key":"PARTNER_NAME","value":""},{"key":"PARTNER_CAB","value":""},{"key":"CN23_THERMIQUE","value":""}],"customField":[{"key":"NETWORK_NAME","value":""},{"key":"PARTNER_NAME","value":""},{"key":"PARTNER_CAB","value":""},{"key":"CN23_THERMIQUE","value":""}]}}}
```
The second chunk `getContent()` return
```
***DOCUMENT DATA***
```

Stream work fine.

### In case of 400 response
1 chunk received :
```
      --uuid:8ad061cd-3186-46a6-8216-d48bf476c95c
      Content-Type: application/json;charset=UTF-8
      Content-Transfer-Encoding: binary
      Content-ID: <jsonInfos>
      
      {"messages":[{"id":"30204","type":"ERROR","messageContent":"Le numéro / libellé de voie du destinataire n'a pas été transmis"}],"labelXmlV2Reponse":null,"labelV2Response":null}
      --uuid:8ad061cd-3186-46a6-8216-d48bf476c95c--
```

But  `getInformationalStatus();` return null, and `getContent();` return ''

`getInformationalStatus();` should return an array contain headers
```
      Content-Type: application/json;charset=UTF-8
      Content-Transfer-Encoding: binary
      Content-ID: <jsonInfos>
```
`getContent();` should return
```
{"messages":[{"id":"30204","type":"ERROR","messageContent":"Le numéro / libellé de voie du destinataire n'a pas été transmis"}],"labelXmlV2Reponse":null,"labelV2Response":null}
```

**Comment by nicolas-grekas** [comment] 2021-05-22 09:38
Sorry but that doesn't make any sense to me.
`getInformationalStatus()` is for retrieving headers bound to a 1xx request, so I don't get how it could return anything for a 200.

Can you please create a reproducing script that I could run locally to get the behavior your observe?

**Comment by roromix** [comment] 2021-05-22 13:58
> Sorry but that doesn't make any sense to me.
> `getInformationalStatus()` is for retrieving headers bound to a 1xx request, so I don't get how it could return anything for a 200.
> 
> Can you please create a reproducing script that I could run locally to get the behavior your observe?

Reproducing script for 400 response (for 200 response, you need valid credentials)

```
$jsonInfos = null;
$label = null;

$responses = $httpClient->request('POST', 'https://ws.colissimo.fr/sls-ws/SlsServiceWSRest/2.0/generateLabel', [
  "json" => [
    "contractNumber" => "123456",
    "password" => "Password",
    "outputFormat" => [
      "x" => 0,
      "y" => 0,
      "outputPrintingType" => "PDF_A4_300dpi",
    ],
    "letter" => [
      "service" => [
        "productCode" => "DOM",
        "depositDate" => "2021-05-26",
        "orderNumber" => "2021",
        "commercialName" => "commercialName",
      ],
      "parcel" => [
        "weight" => 0.1,
      ],
      "sender" => [
        "senderParcelRef" => "2021",
        "address" => [
          "companyName" => "CompanyName",
          "line2" => "42 rue des lilas",
          "countryCode" => "FR",
          "city" => "Paris",
          "zipCode" => "75000",
        ],
      ],
      "addressee" => [
        "addresseeParcelRef" => "2021",
        "address" => [
          "firstName" => "FirstName",
          "lastName" => "LastName",
          "line2" => "42 rue des roses",
          "countryCode" => "FR",
          "city" => "Marseille",
          "zipCode" => "13000",
        ]
      ]
    ]
  ]
]);

// There is chunked content in the 400 response
dump($responses->getContent(false));

foreach ($httpClient->stream($responses) as $chunk) {

    // But isn't readeable by chunk
    $infos = $chunk->getInformationalStatus();
    dump($infos);
    dump($chunk->getContent());
    $contentID = $infos['headers']['Content-ID'] ?? null;

    switch ($contentID) {
        case '<jsonInfos>':
            $jsonInfos = \json_decode($chunk->getContent());
            break;
        case '<label>':
            $label = $chunk->getContent();
            break;
    }
}

dd($jsonInfos, $label);
```

**Comment by stof** [comment] 2021-05-22 14:46
This is not a full reproducing script, as it does not even instantiate `$httpClient`. Trying to run that script, we would be getting a PHP fatal error, not a reproduction of your problem.

**Comment by nicolas-grekas** [comment] 2021-05-22 15:15
I think there is something you're missing @roromix because even calling `json_decode($chunk->getContent())` doesn't make sense, as chunks are partial data, not the full json body.

This looks like a support issue, I'm therefore closing.

Please reach the community on Slack or other support channels.

If I might give you a last suggestion, it would be to not use `$client->stream()`, since for now, none of your examples require using it. (at least you didn't describe why you need streaming while your example doesn't expect nor handle it.)

**Comment by nicolas-grekas** [comment] 2021-05-22 15:15
Oh,of course, please read the doc twice , that might help :)

**Closed as completed by nicolas-grekas** 2021-05-22 15:15 UTC
Labels: Bug, Status: Needs Review, HttpClient

**Comment by stof** [comment] 2021-05-22 15:27
Looking at your dumped response, it looks like the `Content-ID` that you try to get is not a HTTP header at all. It is a mime header for one of the parts of the `multipart/mixed` body.

HTTP chunks are **not** about decoding `multipart/mixed` into separate mime parts. That totally different.
What you need in your case is a mime parser applied on the whole content of your response.

Side note: `symfony/mime` does not provide a mime parser. It represents an object-oriented representation of the mime message (which could be used as the output of a parser though) and the serialization logic to turn them into a mime string.

**Comment by roromix** [comment] 2021-05-22 19:07
@nicolas-grekas and @stof : Thanks you for your explanations 👍 

Finally, I have developed an appropriate Parser inspired by h4cc/multipart
