### ISSUE TITLE
AccessDeniedHttpException in FramentListener leads to status 500 instead of 403

### ISSUE THREAD

**Issue by dbu** [symfony/symfony#11663] opened 2014-08-13 09:57 UTC
when the AccessDeniedHttpException is thrown in [FragmentListener](https://github.com/symfony/symfony/blob/3baea1f370aa963d0db1191898330d8b5907bb05/src/Symfony/Component/HttpKernel/EventListener/FragmentListener.php#L93) i get a status 500 page, instead of a 403 page.

**Comment by cameronjacobson** [comment] 2015-03-15 03:57
The only thing that looks suspect to me is `handleException` method in `src/Symfony/Component/HttpKernel/HttpKernel.php`.  Except it's a 403 error, which would prevent the `else` clause from setting `statusCode` to 500.  Unless something else is changing status code in-between I don't see anything that raises flags that this may be caused by the symfony package directly.

**Comment by jakzal** [comment] 2015-05-14 17:35
@dbu I just tried to reproduce this issue and I'm not experiencing the same behaviour (Symfony 2.6). Since I'm second person who can't reproduce it, please re-create your issue on a fork of Symfony SE and provide instructions how to trigger the error.

**Comment by dbu** [comment] 2015-05-15 09:48
sorry for not following up on this. i now tried this again and something very basic seems amiss.
@jakzal can you try these steps?

```
composer.phar create-project symfony/framework-standard-edition my_project_name
# say no to demo bundle, no need for a database
cd my_project_name
app/console server:run
```

Then open http://127.0.0.1:8000/app.php/_fragment?_path=_format%3Dhtml%26_locale%3Den%26_controller%3DAppBundle%253ADefault%253Aindex in a browser. You get a response with status 403, but the content is the fragment output.

You can also try `curl -XPUT -v http://127.0.0.1:8000/app.php/_fragment?_path=_format%3Dhtml%26_locale%3Den%26_controller%3DAppBundle%253ADefault%253Aindex` - same result. I debugged that `FragmentListener::validateRequest` indeed throws exceptions, but then the ExceptionListener sets a response that contains the fragment, meaning the controller is indeed executed.

**Comment by dbu** [comment] 2015-05-15 09:52
so indeed, the issue i originally encountered is no longer, but the new behaviour is even worse.

i did not test this over a network, so maybe its a problem of one place implicitly trusting localhost, but as i get a 403 status on my response, something seems really off.

**Comment by dbu** [comment] 2015-05-15 10:58
Sorry for not following up on this. i now tried this again. the problem is in symfony 2.3. can you try these steps?

```
composer.phar create-project symfony/framework-standard-edition fragment_issue 2.3
# say no to demo bundle, no need for a database
cd fragment_issue
app/console server:run
```

Then try to send a request with a non-safe method: `curl -XPUT -v http://127.0.0.1:8000/app.php/_fragment?_path=_format%3Dhtml%26_locale%3Den%26_controller%3DAcme%253ADemoBundle%253ADemo%253Aindex`

The problem also exists with symfony 2.5 but that is already past its support period.

**Comment by jakzal** [comment] 2015-05-15 11:08
@dbu yept, that did the job. Thanks, I'll be looking into this!

**Comment by xabbuh** [comment] 2016-10-18 11:46
Closing as this issue isn't present in any maintained release.

**Closed by xabbuh** 2016-10-18 11:46 UTC
Labels: Bug, HttpKernel, Status: Needs Review
