### ISSUE TITLE
RequestPayloadValueResolver should catch invalid values of backed enums

### ISSUE THREAD

**Issue by stollr** [symfony/symfony#58208] opened 2024-09-09 08:59 UTC
### Description

If a controller argument is attributed with `MapQueryString` and the class contains a property, which is a backed enum, the `BackedEnumNormalizer` is used to [denormalize][1] the value. If a user submits an invalid value for the enum, a `ValueError` is catched and an `Symfony\Component\Serializer\Exception\InvalidArgumentException` is rethrown.

But this exception is never catched and thus resulting in a 500 internal server error response.

I suggest catching this exception in the [`RequestPayloadValueResolver`][2] and throw an HttpException
 with a 422 or 400 status code (or with the `validationFailedStatusCode` defined in the attribute), because this is a client error.

What do you think?

[1]: https://github.com/symfony/symfony/blob/b19a1083154bc77c01a5fede4f9037f36ac9831d/src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php#L76
[2]: https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php

**Comment by derrabus** [comment] 2024-09-09 09:09
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by stollr** [comment] 2024-09-09 10:23
I have added a reproducer at https://github.com/stollr/symfony_issue_58208. The [`ReproducerController`](https://github.com/stollr/symfony_issue_58208/blob/main/src/Controller/ReproducerController.php) contains anything you need to reproduce the issue.

Open http://127.0.0.1:8000/?engineType=diesl to see the error.

**Comment by Jean-Beru** [comment] 2024-10-11 10:45
It seems to be the same issue as mentioned in #52705, right?

**Comment by stollr** [comment] 2024-10-11 15:59
As `[MapRequestPayload]` and `[MapQueryString]` are both handled by the `RequestPayloadValueResolver` it has indeed the same source.

**Comment by xabbuh** [comment] 2024-10-13 14:01
Let's close this one as a duplicate of #52705 then.

**Closed as not planned by xabbuh** 2024-10-13 14:01 UTC
Labels: Bug, HttpKernel, Status: Needs Review, Status: Waiting feedback
