### ISSUE TITLE
symfony/translation v4.4.31 does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by HenkPoley** [symfony/symfony#43215] opened 2021-09-28 09:16 UTC
**Symfony version(s) affected**: "symfony/translation": "v4.4.31" and composer.phar 2.1.8 on Windows

**Description**
When I install symfony/translation v4.4.30 I have no issues.

When I install symfony/translation v4.4.31 I get lots of `Class Symfony\Component\Translation\Exception\<ClassName> located in <project>/vendor/symfony/translation\<ClassName>.php does not comply with psr-4 autoloading standard. Skipping.`

Furthermore I of course get errors that these classes cannot be loaded when they are used (in vendor php code).

**How to reproduce**
Composer.json with:

```
    "require": {
        "symfony/translation": "v4.4.31"
    },
```

Just in case, tested with PHP 7.2.34, 7.3.29, 7.4.23, 8.0.10 on Windows (and not WSL).

**Possible Solution**

**Additional context**

**Comment by frenchcomp** [comment] 2021-09-28 09:24
To complete this issue, I have also an error in my IC tests 
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Translation\Formatter\MessageFormatter" not found

And in the vendor folder of Symfony/Translation, i have only tests files.

**Comment by derrabus** [comment] 2021-09-28 09:24
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:24 UTC
Labels: Bug, Status: Needs Review
