### ISSUE TITLE
Block "javascript" missing in profiler after twig updated

### ISSUE THREAD

**Issue by uLow** [symfony/symfony#21487] opened 2017-02-01 11:48 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

Hi there!
After running `composer update`, twig got update from 1.31 to 2.1, that caused error below, when running profiler:
```
“
Block "javascript" on template "@WebProfiler/Profiler/base.html.twig" does not exist.
500 Internal Server Error - Twig_Error_Runtime
”
Stack Trace
in vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base.html.twig at line 17   -
        {% endblock %}
    </head>
    <body>
        {% block body '' %}
    </body>
</html>
```

**Comment by stof** [comment] 2017-02-01 11:54
which version of Symfony are you using exactly ?

**Comment by stof** [comment] 2017-02-01 11:56
and on which page of the profiler is it happening exactly ?

**Comment by uLow** [comment] 2017-02-01 12:58
> which version of Symfony are you using exactly ?
$ composer show symfony/symfony
name: symfony/symfony
descrip.: The Symfony PHP framework
keywords: framework
versions: * v3.2.2
type: library

> and on which page of the profiler is it happening exactly ?
/_profiler/3e47b5?panel=block

**Comment by stof** [comment] 2017-02-01 14:24
what is this panel ? It is not a core panel

**Comment by xabbuh** [comment] 2017-02-01 14:35
This seems to be an issue of SonataBlockBundle: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/Resources/views/Profiler/block.html.twig#L116

Please report this issue in their repository. I am closing here as this is not a bug in Symfony. Thank you for understanding.

**Closed by xabbuh** 2017-02-01 14:35 UTC
