### ISSUE TITLE
[config] null value converted to true on boolean Processor parsing 

### ISSUE THREAD

**Issue by exteon** [symfony/symfony#44906] opened 2022-01-04 15:16 UTC
### Symfony version(s) affected

6.0.2

### Description

null value for boolean key defined with `TreeBuilder` is not rejected as invalid and converted to `true`

### How to reproduce

```php
    use Symfony\Component\Config\Definition\Builder\TreeBuilder;
    use Symfony\Component\Config\Definition\ConfigurationInterface;
    use Symfony\Component\Config\Definition\Processor;
    use Symfony\Component\Yaml\Yaml;

    require_once(__DIR__ . '/vendor/autoload.php');

    $yaml1 = <<<END
bkey: null
END;

    $treeBuilder = new TreeBuilder('test');
    $treeBuilder
        ->getRootNode()
        ->children()
            ->booleanNode('bkey')
        ->end();

    $processor = new Processor();
    $config = new class implements ConfigurationInterface {

        public function getConfigTreeBuilder(): TreeBuilder
        {
            global $treeBuilder;
            return $treeBuilder;
        }
    };
    $parsed1 = Yaml::parse($yaml1);
    var_dump($processor->processConfiguration($config, [$parsed1]));
```

### Possible Solution

I don't know yet (new to using the config component) on the policy regarding nulls in the context of merging multiple partial configurations; I also couldn't find in the documentation a statement of policy regarding this case.

I see only the following possibilities:

- `null` is treated as **unset** upon merging (i.e. `true` + `null` = `true`, `false` + `null` = `false`) and a final `null` remains `null` if node value is not required, config is rejected as incomplete if value is required. _This seems the most intuitive to me_
- `null` is rejected as an invalid value
- `null` is authoritative on merge (i.e. `true` + `null` = `null`); final `null` is converted to `false`. _I find this most counterintuitive_

In either case, `null` resulting to `true` is definitely a bug here.

**Comment by yceruto** [comment] 2022-01-05 02:49
It's defined this way since 11 years ago:
https://github.com/symfony/symfony/blob/137aa3ba3c73e823e8259352beaae66d25f13def/src/Symfony/Component/Config/Definition/Builder/BooleanNodeDefinition.php#L31

However, you can change this default behavior by setting your own equivalent value this way:
```php
$treeBuilder
    ->getRootNode()
    ->children()
        ->booleanNode('bkey')
            ->treatNullLike(null)
        ->end()
    ->end();
```
and then you will get the expected `InvalidTypeException` if null is set.

Closing as this is not a bug. Thanks for reporting!

**Closed as completed by yceruto** 2022-01-05 02:49 UTC
Labels: Bug, Config, Status: Needs Review

**Comment by exteon** [comment] 2022-01-05 08:21
Is see, thanks, maybe it would be useful if this is documented, especially since the yaml config dumper really dumps null default values, thus these 2 behaviors combined can silently trigger unwanted (maybe even unsafe) behavior. You use a dumped config that hiddenly turns every switch on, the ones that don't have defaults set, at least. That's what happened to me.
