### ISSUE TITLE
debug:config command not taking into account prepended configs

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#14014] opened 2015-03-22 09:21 UTC
Hi,

I have a bundle which uses PrependExtensionInterface to change configuration of other bundles as explained here http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html

Altough the prepended configs are taken into account without problem in the application, the "php app/console debug:config" command shows the configuration as if no values were prepended. 

Tested in the stable 2.6 release.

**Comment by aitboudad** [comment] 2015-03-22 10:06
Duplicate of #12438 and fixed in #13886.

**Closed by aitboudad** 2015-03-22 10:06 UTC
