### ISSUE TITLE
Null environment variable cast to empty string

### ISSUE THREAD

**Issue by fmarchalemisys** [symfony/symfony#50815] opened 2023-06-29 06:56 UTC
### Symfony version(s) affected

6.3.1

### Description

The following code used to work with symfony 6.3.0 but not with 6.3.1.

In `services.yaml`:

```yaml
parameters:
    env(HTTP_UNIQUEID): ~
```

In a service:

```php
    public function __construct(
        #[Autowire('%env(string:HTTP_UNIQUEID)%')] ?string $xRequestId
    ) {
        // symfony 6.3.0: $xRequestId is null
        // symfony 6.3.1: $xRequestId is ""
        $this->xRequestId = $xRequestId ?? $this->generateSafeUnpredictableId();
    }
```

With symfony 6.3.1, the `$xRequestId` is the empty string. It defeats the call to `generateSafeUnpredictableId()`.

This issues was introduced by this change: https://github.com/symfony/dependency-injection/commit/6c3c271943ec6ea1a0233f14dd5f1586c9fe77f4#diff-0ebfb024d710d87ccb36098690a9aa8ec4cea8bae635a2c5f95813e3ceba3dabR184

This is a big BC break for a minor version change.

### How to reproduce

In `services.yaml`:

```yaml
parameters:
    env(HTTP_UNIQUEID): ~
```

In a service:

```php
    public function __construct(
        #[Autowire('%env(string:HTTP_UNIQUEID)%')] ?string $xRequestId
    ) {
        // symfony 6.3.0: $xRequestId is null
        // symfony 6.3.1: $xRequestId is ""
        $this->xRequestId = $xRequestId ?? $this->generateSafeUnpredictableId();
        // $this->xRequestId is the very predictable empty string!
    }
```

### Possible Solution

Replace 

```php
if (!\in_array($prefix, ['string', 'bool', 'not', 'int', 'float'], true)) {
    return null;
}
```

with

```
return null;
```

when `$env` is null in `EnvVarProcessor.php`.

### Additional Context

Apache with the unique_id module generates a unique id for each request it processes. The unique id is stored in `HTTP_UNIQUEID`.

When the unique_id module is not enabled or caddy is used instead of apache, there are no `HTTP_UNIQUEID`. It must be generated on the fly by the service.

As a quick patch, I simply check if the env var is the empty string but this is a big BC break that's not easy to spot.

**Comment by fancyweb** [comment] 2023-06-29 07:33
Thanks for reporting the issue with detailed info.

The problem is that the reported "bug" is precisely the fix we merged in https://github.com/symfony/symfony/pull/50517 :sweat_smile: Basically, some people expect the cast to be applied, and others don't.

`%env(SOME_VAR)%` will also return `''` now because the `string` prefix is applied by default btw.

I agree it causes unexpected behavior changes on 5.4, especially for the `string` prefix I guess.

Let's maybe revert it and reapply it on 6.4? What do you think @nicolas-grekas?

**Comment by nicolas-grekas** [comment] 2023-06-29 07:57
> %env(SOME_VAR)% will also return '' now because the string prefix is applied by default btw.

maybe we can change that? when there's no explicit prefix, we keep null?

**Comment by fmarchalemisys** [comment] 2023-06-29 07:58
Is it possible to explicitly declare a nullable string like this:

```php
#[Autowire('%env(?string:HTTP_UNIQUEID)%')] ?string $xRequestId
```

It's still a BC break but, at least, nullable can be allowed or not.

BTW, what happened to https://github.com/symfony/symfony/pull/29767 that introduced the `nullable:` prefix in 2019?

**Comment by MatTheCat** [comment] 2023-06-29 09:29
> what happened to https://github.com/symfony/symfony/pull/29767 that introduced the `nullable:` prefix in 2019?

See #30504

**Comment by ndench** [comment] 2023-07-03 01:32
IMHO, I think that if someone declares the variable like this, then they expect it to come through as nullable:

```
parameters:
    env(HTTP_UNIQUEID): ~
```

If they want it to default to empty string, they can always declare it like this instead:

```
parameters:
    env(HTTP_UNIQUEID): ''
```

**Comment by nicolas-grekas** [comment] 2023-07-03 12:58
Use `#[Autowire('%env(HTTP_UNIQUEID)%')]` and it should work after #50837 is released (by the end of the month.)

**Closed as completed by nicolas-grekas** 2023-07-03 12:58 UTC
Labels: DependencyInjection, Bug, Status: Needs Review
