### ISSUE TITLE
streaming a template which uses the session fails

### ISSUE THREAD

**Issue by Nemo64** [symfony/symfony#17888] opened 2016-02-22 15:14 UTC
I tried to stream a template for a change but had Problem with the Session.
I best show a little example:

```PHP
public function someAction (Request $request) {
    $request->getSession()->start(); // ensure the session is started
    return $this->stream('template.html.twig');
}
```

```twig
<html>
    <head>
        <title>Title</title>
    </head>
    {% flush %}
    <body>
        {{ app.session.flashBag.all|length }}{# accessing the session now fails #}
    </body>
</html>
```

This results into a `RuntimeException`:

```
[1/2] RuntimeException: Failed to start the session because headers have already been sent by "" at line 0.   -
```

I'm using Symfony 2.7.9 with PHP 7.0.2-4+deb.sury.org~trusty+1.

**Comment by backbone87** [comment] 2016-02-22 16:57
afaik, this is expected behavior, because the session gets written out and closed when the streaming begins. i also dont know why you would stream html-templates. html pages are not large enough most of the time, to benefit from streaming.

**Comment by Nemo64** [comment] 2016-02-22 17:05
Ahh I see. Makes sense to not block the session while streaming huge files.

My Idea was to to output parts of the template already while i still create the view of a more complicated form in the hopes to make the site feel a little faster.

If it isn't intended for html templates to be streamed, why is `$this->stream` there? Even the `@Template` Annotation allows for streaming.

**Comment by Tobion** [comment] 2016-02-22 22:43
Closing as duplicate of #6036
In theory only reading the session does not require it to be restarted. This would solve your problem as well.

**Closed by Tobion** 2016-02-22 22:43 UTC

**Comment by Nemo64** [comment] 2016-02-22 23:02
@Tobion Not really since the flashbag removes it's entries after reading. I therefor need an open session.

**Comment by backbone87** [comment] 2016-02-22 23:08
@Nemo64 the nature of xml/sgml/html/etc usually makes such formats not well suited for streamed processing, at least how it is used in the browser. but there are dataformats like for example CSV that are very well suited for streaming and streamed processing. you can generate CSVs with twig as well (though i must admit using php for CSV is probably better).

also most modern html forms use JS and most js-candy can only be initialized after the html page was fully loaded making the form unuseable or at least less useable when the browser does rendering of partially received html data. this defeats the purpose of streaming for faster access.

**Comment by HeahDude** [comment] 2016-02-22 23:13
Hi @Nemo64, a `StreamedResponse` send headers once before using a callable for sending content only.

So you may try to pass flashes as a view variable when rendering to solve your issue :
```php
public function someAction (Request $request) {
    $request->getSession()->start(); // ensure the session is started
    return $this->stream('template.html.twig', array('flashes' => $request->getSession()->getFlashBag()->all());
}
```
Then :
```twig
<html>
    <head>
        <title>Title</title>
    </head>
    {% flush %}
    <body>
        {{ flashes|length }}{# you should get them #}
    </body>
</html>
```

**Comment by Nemo64** [comment] 2016-02-22 23:19
@backbone87 it isn't well suited, yes, but browser are still capable of streaming them. I think it would make perfekt sense to stream at least the html `<head>` so that the browser can download some Resources already, even if the page is not visible yet.

Also, using Web-Components for example, it is possible to use JavaScript efficiently before the Dom is loaded. If a page is composed of multiple sections, like a one-pager, it would also make sense to use sub-request to start processing lower parts much later

@HeahDude Yes, that would work. but I couldn't use it in a layout then. I'd have to put this in every action which wouldn't be very nice, would it. ;)

**Comment by HeahDude** [comment] 2016-02-22 23:25
@Nemo64 You should in that case create a global controller like this :
```php
class BaseStreamingController extends \Symfony\Bundle\FrameworkBundle\Controller\Controller
{
    public function streamToRoute($request, $route, array $vars = array())
    {
        $vars['flashes'] = $request->getSession()->getFlashBag()->all();

        return $this->stream($route, $vars);
    }
}

class SomeController extends BaseStreamingController
{
    public function someAction (Request $request) {
        return $this->streamToRoute($request, 'template.html.twig', array(
            'some_view_var' => 'If you need it',
        );
    }
}
