### ISSUE TITLE
Bootstrap 4 Templates renders checkboxes and radio fields wrong

### ISSUE THREAD

**Issue by ufeldmann** [symfony/symfony#26521] opened 2018-03-14 10:34 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

Currently the theme bootstrap_4_layout.html.twig renders checkboxes like that

```html
<div class="form-check">
    <label class="form-check-label">
        <input type="checkbox" id="defaultCheck1" name="anyname" class="form-check-input" value="1"> Default checkbox
    </label>
</div>
```

But the bootstrap 4 documentation has the following structure

```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Default checkbox
  </label>
</div>
```

The same logic for radio buttons

**Comment by javiereguiluz** [comment] 2018-03-14 15:57
Two quick questions: 1) are you using the latest improved Bootstrap 4 theme (https://symfony.com/blog/new-in-symfony-4-1-improved-bootstrap-4-form-theme)? 2) If you are using it, even if the generated HTML is different from Bootstrap recommendation, would that be a problem for apps? I mean: is it non-valid HTML or something like that? I say this because given that we made these changes for accessibility reasons, so if they are not broken or invalid in some bad way, we may need to keep them. Thanks!

**Comment by ostrolucky** [comment] 2018-03-14 22:47
duplicate of https://github.com/symfony/symfony/issues/26461

**Closed** 2018-03-15 08:43 UTC
Labels: Bug, Form, Status: Needs Review
