### ISSUE TITLE
[DOMCrawler][CssSelector] Css selector not working when used in DomCrawler

### ISSUE THREAD

**Issue by dfernandezm** [symfony/symfony#15769] opened 2015-09-12 16:36 UTC
Hi, I am trying to use the following code:

`$subCrawler->filter('td div.iaconbox a[title*="magnet"]')->extract("href");`

And I get an empty array. I tried with Chrome on the resulting DOM and the selector is correct. I tried removing the double quotes as well. I am using Symfony 2.6.1 and CssSelector / DomCrawler 2.6.1.

Is this selector supported? Any guidance is much appreciated.

Thank you

**Comment by javiereguiluz** [comment] 2015-09-12 17:29
Shouldnt you use the following instead?

```php
$subCrawler->filter('td div.iaconbox a[title="magnet"]')->attr("href");
```

**Comment by WouterJ** [comment] 2015-09-12 18:44
@javiereguiluz `[title="magnet"]` and `[title*="magnet"]` are different (`===` vs `false !== strpos(...)`).

@dfernandezm I think something is going wrong with `$subCrawler`, can you please show some more code? The CssSelector component does support the `*=` selector (it has some tests for it). I've tested it locally on a Symfony 2.6 app with `DOMXpath` and the CssSelector component and it returned the correct element (https://gist.github.com/WouterJ/a839d73c01d3fe4edd36).

**Comment by dfernandezm** [comment] 2015-09-12 22:38
Sorry guys, it happened to be a nasty bug in the code. The selector works as expected.

**Comment by WouterJ** [comment] 2015-09-12 22:43
@dfernandezm good to hear you fixed the bug! Can you please click the close button (which is next to the comment button), as the issue is fixed now?

**Closed** 2015-09-12 22:46 UTC
