### ISSUE TITLE
xliff extension in translation update command

### ISSUE THREAD

**Issue by chapterjason** [symfony/symfony#22440] opened 2017-04-14 19:58 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.7

I tried to convert my translation file from `json` format to `xliff`.
I used the following command `translation:update en --output-format xliff` and got the following error:
```
 [ERROR] Wrong output format

         Supported formats are: php, xlf, po, mo, yml, ts, csv, ini, json, res.
```
I know `xlf === xliff` but its annoying to refactor the extension.

I also found out that in the `xliff` file the `trans-unit` `id` is a bit confusing `(3b59784ea795cb0dccda26ec97f5f297)?` if you compare it to the best practise example. [http://symfony.com/doc/current/best_practices/i18n.html](http://symfony.com/doc/current/best_practices/i18n.html)

What I like in `json` is that I can create path like this:
```
{
  "acme": {
    "entity": {
      "keyword": "Keyword",
   }
}
```
Having something like this in xliff would be awesome!
I could imagine something like this
```
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="en" datatype="plaintext" original="file.ext">
    <body>
      <group id="acme">
        <group id="entity">
          <trans-unit id="keyword">
            <source>keyword</source>
            <target>Keyword</target>
          </trans-unit>
        </group>
      </group>
    </body>
  </file>
</xliff>
```

**Comment by mvrhov** [comment] 2017-04-15 12:32
The problem is that the way xliff is used in symfony is wrong. The correct format is supposed to be.

```xml
<trans-unit id="some.id, might be equal to resname" resname="email.confirmed.anonymously" approved="yes">
    <source>%email% has been confirmed.</source>
    <target state="translated">%email% je bil potrjen.</target>
</trans-unit>
```

**Comment by aitboudad** [comment] 2017-04-15 18:31
@chapterjason Is there any concrete reason for using `xliff` instead of the default `xlf` extension ?

**Comment by aitboudad** [comment] 2017-04-15 19:00
@chapterjason by the way you can use a custom dump to achieve your goal

```yml
#services.yml
app.translation.dumper.xliff:
    class: AppBundle\Translation\XliffFileDumper
    tags:
        - { name: translation.dumper, alias: xliff }
```

```php
<?php

namespace AppBundle\Translation;

use Symfony\Component\Translation\Dumper\XliffFileDumper as BaseXliffFileDumper;

class XliffFileDumper extends BaseXliffFileDumper
{
    protected function getExtension()
    {
        return 'xliff';
    }
}
```

**Comment by javiereguiluz** [comment] 2017-04-18 08:23
@aitboudad  `xliff` is a popular alternative to `xlf`. Do you think it could make sense to support `xliff` as a synonym? At least internally, changing `xliff` to `xlf` without the user noticing?

**Comment by aitboudad** [comment] 2017-04-18 10:10
Since https://github.com/symfony/symfony/commit/2cb6260d072c28cb991082ea8a8822085d68d846 the `xliff` is not recommended anymore but I couldn't find the reason :).
Anyway It make sense to me and I'll try to find a better solution.

@mvrhov can you open a issue with more details ?

**Comment by stof** [comment] 2017-04-18 10:24
@aitboudad `.xlf` is the official extension for XLIFF files. This is why the default extension changed

**Comment by chapterjason** [comment] 2017-04-18 10:38
@stof @aitboudad yeah now it makes sense for me.

But what about the `id` hash and the "`group - path`"?

After I read @mvrhov comment I think there is something not fully implemented and there is something missing, specially for `xliff`

**Comment by aitboudad** [comment] 2017-04-18 10:52
PR welcomed :) both of them (id hash and the "group - path") can be implemented easily by adding custom option to the dumper see for example https://github.com/symfony/symfony/pull/14630.

**Comment by chapterjason** [comment] 2017-04-20 07:52
As I working on a PR [https://github.com/chapterjason/symfony/commit/416d851044424aa2bacd9f04cc04131ebbb0fc03](https://github.com/chapterjason/symfony/commit/416d851044424aa2bacd9f04cc04131ebbb0fc03) I realized that ID has to be unique.

**The problem**
I get the following as result. You can see that a group with id `bar` exists twice, as group under `foo` and as group in the main tree. I realized the uniqueness as I tried to load the file.
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="fr-FR" target-language="en-US" datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
      <group id="foo">
        <group id="bar">         <!-- bar as id -->
          <trans-unit id="value" resname="value">
            <source>value</source>
            <target></target>
          </trans-unit>
          <trans-unit id="key" resname="key">
            <source>key</source>
            <target>value</target>
          </trans-unit>
        </group>
      </group>
      <group id="bar">         <!-- bar as id -->
        <trans-unit id="key" resname="key">
          <source>key</source>
          <target></target>
        </trans-unit>
        <trans-unit id="value" resname="value">
          <source>value</source>
          <target>value</target>
        </trans-unit>
      </group>
      <trans-unit id="key" resname="key">
        <source>key</source>
        <target></target>
      </trans-unit>
      <trans-unit id="value" resname="value">
        <source>value</source>
        <target>value</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```
My next idea was to set the `id's` like the tree, but I think it's a bit overwhelmed.
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="fr-FR" target-language="en-US" datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
      <group id="foo">
        <group id="foo.bar">   <!-- "bar not as id" => foo.bar -->
          <trans-unit id="foo.bar.value" resname="value">
            <source>value</source>
            <target></target>
          </trans-unit>
          <trans-unit id="foo.bar.key" resname="key">
            <source>key</source>
            <target>value</target>
          </trans-unit>
        </group>
      </group>
      <group id="bar">       <!-- bar as id but unique -->
        <trans-unit id="bar.key" resname="key">
          <source>key</source>
          <target></target>
        </trans-unit>
        <trans-unit id="bar.value" resname="value">
          <source>value</source>
          <target>value</target>
        </trans-unit>
      </group>
      <trans-unit id="key" resname="key">
        <source>key</source>
        <target></target>
      </trans-unit>
      <trans-unit id="value" resname="value">
        <source>value</source>
        <target>value</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

Any suggestions?

**Comment by javiereguiluz** [comment] 2019-07-08 07:21
Closing because we didn't receive more comments about this from the community, so it looks like it's not annoying to most of our users, who are used to use the official `.xlf` extension. Thanks.

**Closed by javiereguiluz** 2019-07-08 07:21 UTC
Labels: Translator
