### ISSUE TITLE
[Form] delete_empty & checkbox

### ISSUE THREAD

**Issue by piotrantosik** [symfony/symfony#13747] opened 2015-02-20 09:25 UTC
I try to delete empty rows using delete_empty option. My forms:

``` php
$builder->add('tests', 'collection', [
                    'type' => new TestFormType(),
                    'allow_add' => true,
                    'allow_delete' => true,
                    'by_reference' => false,
                    'cascade_validation' => true,
                    'delete_empty' => true,
                    'options' => [
                        'required' => false,
                    ],
                ]);
```

TestFormType:

``` php
$builder
            ->add('desc', 'text', [])
            ->add('check', 'checkbox', [
                'required' => false,
            ])
```

Without checkbox on subform all works fine. But symfony allways convert checkbox data to true/false and ResizeFormListener (src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php) don't delete empty row.

**Comment by WouterJ** [comment] 2015-03-20 16:54
Looking at [this code](https://github.com/symfony/Form/blob/17f94751073b2aebd5620acb17ba515ac623eb09/Form.php#L753-757), if the `desc` field is empty, isn't the form type already considered to be empty?

**Comment by piotrantosik** [comment] 2015-03-23 16:11
no, first child  in iteration - `desc` is empty, but next child form - `check` is transformed to false and isEmpty on the form return false.
Maybe I set up sandbox with example form?

**Comment by WouterJ** [comment] 2015-03-23 16:41
I can confirm that checkbox is never seen as empty. However, it will be very hard to be able to define the empty value for a checkbox. If it's default is checked, will empty be checked or not checked? If a collection only has one entry type: collection. Would all items which are unchecked be seen as empty?

**Comment by artursvonda** [comment] 2018-07-30 09:14
How about giving option to users to decide if form data is considered empty? Through `empty_check_callback` option (or something along those lines). Gives escape hatch to power users.

**Comment by yceruto** [comment] 2018-07-30 12:13
Since 3.4 the `delete_empty` option already accepts a callable function where we can determine whether the form row is empty or not. It's also well documented: http://symfony.com/doc/current/reference/forms/types/collection.html#delete-empty

I think this can be closed here as resolved by https://github.com/symfony/symfony/pull/20496

**Closed** 2018-07-30 12:23 UTC
Labels: Bug, Form, Status: Needs Review
