### ISSUE TITLE
[DI] Bug with sharing of non-public service

### ISSUE THREAD

**Issue by mikemirten** [symfony/symfony#23979] opened 2017-08-24 20:04 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6
| PHP version | 7.1

If service declared as non-public it stops to be shared, means for every consumer of such a service a new one will be instantiated. Explicit ```shared: true``` makes no difference. With ```public: true``` works as expected (shared by default).

Behaviour has been noticed for compiled ContainerBuilder, but not dumped.

**Comment by Nek-** [comment] 2017-08-25 08:15
Hello,

Here is a reproducer that show there is no problem. I used Symfony 3.3.6 to make my test.

```bash
$ composer show
symfony/symfony                      v3.3.6  The Symfony PHP framework
```

```php
<?php

namespace GlobalNamespace\Foobar {
    class NewLine {
        public function __construct()
        {
            echo "I'm new line and i'm used everywhere";
            $this->hello();
        }

        public function hello()
        {
            echo "\n";
        }
    }
}

namespace GlobalNamespace\Foo {
    class Stof {

        private $nl;

        public function __construct(\GlobalNamespace\Foobar\Newline $newline)
        {
            $this->nl = $newline;
        }

        public function hello()
        {
            echo "You missed something line 150, please change it !";
            $this->nl->hello();
        }
    }
}

namespace GlobalNamespace\Bar {
    class Fabpot {

        private $nl;

        public function __construct(\GlobalNamespace\Foobar\Newline $newline)
        {
            $this->nl = $newline;
        }

        public function hello()
        {
            echo "[MERGED] Thanks for your contribution !";
            $this->nl->hello();
        }
    }
}

namespace Swagg {

    require 'vendor/autoload.php';

    use GlobalNamespace\Bar\Fabpot;
    use GlobalNamespace\Foo\Stof;
    use GlobalNamespace\Foobar\NewLine;
    use Symfony\Component\DependencyInjection\ContainerBuilder;


    $container = new ContainerBuilder();

    $container->register('nl', NewLine::class)->setPublic(false);
    $container->autowire('stof', Stof::class)->setPublic(true);
    $container->autowire('fabpot', Fabpot::class)->setPublic(true);

    $container->compile();

    $container->get('stof')->hello();
    $container->get('fabpot')->hello();
}
```

Output:
```
$ php test.php
I'm new line and i'm used everywhere
You missed something line 150, please change it !
[MERGED] Thanks for your contribution !
```

Status: Reviewed

**Comment by Nek-** [comment] 2017-08-25 08:32
I found a bug anyway. Let's take the previous code with the following usage:

```php
    $container = new ContainerBuilder();

    $container->register('nl', NewLine::class)->setPublic(false)->setShared(false);
    $container->autowire('stof', Stof::class)->setPublic(true);
    $container->autowire('fabpot', Fabpot::class)->setPublic(true);

    $container->compile();

    $container->get('stof')->hello();
    $container->get('fabpot')->hello();
```

Output:
```
$ php test.php
I'm new line and i'm used everywhere
You missed something line 150, please change it !
[MERGED] Thanks for your contribution !
```
Also, the spl hash is the same. Of course. But I asked that the instance is not shared. Here is the issue. If I set it public the issue is the same, but it works when I call it from the outside:

```php
    $container = new ContainerBuilder();

    $container->register('nl', NewLine::class)->setPublic(true)->setShared(false);
    $container->autowire('stof', Stof::class)->setPublic(true);
    $container->autowire('fabpot', Fabpot::class)->setPublic(true);

    $container->compile();

    $container->get('stof')->hello();   // instanciates "NewLine"
    $container->get('fabpot')->hello(); // reuse the existing instance
    $container->get('nl')->hello();     // instanciates "NewLine" again
```

**Comment by mikemirten** [comment] 2017-08-25 15:56
Cannot reproduce it with an "artificial" test, works fine, but with real project there is still an issue. I going to continue to work with it.

**Comment by Nek-** [comment] 2017-08-26 16:21
I did it for you @mikemeier :). See my last post. The issue is real.

**Comment by ro0NL** [comment] 2017-08-30 07:46
@Nek-  isnt that autowiring kicking in? Creating a new `NewLine` service, as it doesnt know about the `nl` service :thinking: 

I'd say no issue then :)

**Comment by Nek-** [comment] 2017-08-30 08:27
@ro0NL the autowiring doesn't instantiate many times the service as expected. (As I understand you describe the inverse case, which would make eventually sense but would still remain an issue)

The case here in a nutshell:
1. I register `NewLine` as public service that should not be shared
2. I call 2 services autowired that should generate 2 instantiations of `NewLine` service as it's not shared, **but it fails and instantiate only once**
3. I get the `NewLine` service with the container directly and get the expected behavior: a new instance

**Comment by stof** [comment] 2017-08-30 09:14
@Nek- your autowiring issue is that your non-shared service is **not** registered for the class name as id. So it is not the one used by the autowiring (actually, it may be the one being used due to the BC layer, as you use 3.3 and not master. We may have a weird thing in the BC layer). The autowiring may be creating a new service for Newline (and services created there are shared).

**Comment by stof** [comment] 2017-08-30 09:16
@Nek- can you dump `$container->getCompiler()->getLog()` after the compilation of the container in your test ?

**Comment by Nek-** [comment] 2017-08-30 09:46
Here is the output:

```bash
$ php test.php
I'm new line and i'm used everywhere
You missed something line 150, please change it !
[MERGED] Thanks for your contribution !
I'm new line and i'm used everywhere

array(3) {
  [0]=>
  string(143) "Symfony\Component\DependencyInjection\Compiler\AutowirePass: Type "GlobalNamespace\Foobar\Newline" has been auto-registered for service "stof"."
  [1]=>
  string(147) "Symfony\Component\DependencyInjection\Compiler\RemovePrivateAliasesPass: Removed service "Psr\Container\ContainerInterface"; reason: private alias."
  [2]=>
  string(171) "Symfony\Component\DependencyInjection\Compiler\RemovePrivateAliasesPass: Removed service "Symfony\Component\DependencyInjection\ContainerInterface"; reason: private alias."
}
```

<details>
<summary>Click me to see the code that generates this output</summary>

```php
<?php
namespace GlobalNamespace\Foobar {
    class NewLine {
        public function __construct()
        {
            echo "I'm new line and i'm used everywhere";
            $this->hello();
        }

        public function hello()
        {
            echo "\n";
        }
    }
}

namespace GlobalNamespace\Foo {
    class Stof {

        private $nl;

        public function __construct(\GlobalNamespace\Foobar\Newline $newline)
        {
            $this->nl = $newline;
        }

        public function hello()
        {
            echo "You missed something line 150, please change it !";
            $this->nl->hello();
        }
    }
}

namespace GlobalNamespace\Bar {
    class Fabpot {

        private $nl;

        public function __construct(\GlobalNamespace\Foobar\Newline $newline)
        {
            $this->nl = $newline;
        }

        public function hello()
        {
            echo "[MERGED] Thanks for your contribution !";
            $this->nl->hello();
        }
    }
}

namespace GlobalNamespace {

    require 'vendor/autoload.php';

    use GlobalNamespace\Bar\Fabpot;
    use GlobalNamespace\Foo\Stof;
    use GlobalNamespace\Foobar\NewLine;
    use Symfony\Component\DependencyInjection\ContainerBuilder;


    $container = new ContainerBuilder();

    $container->register('nl', NewLine::class)->setPublic(true)->setShared(false);
    $container->autowire('stof', Stof::class)->setPublic(true);
    $container->autowire('fabpot', Fabpot::class)->setPublic(true);

    $container->compile();

    $container->get('stof')->hello();
    $container->get('fabpot')->hello();
    $container->get('nl')->hello();

    var_dump($container->getCompiler()->getLog());
}

```
</details>

**Comment by nicolas-grekas** [comment] 2017-11-02 21:55
https://github.com/symfony/symfony/pull/24671 to the rescue? Can you try setting the parameter? And upgrade to beta2 of course.

**Comment by nicolas-grekas** [comment] 2017-11-26 20:33
Closing as this should be fixed, as suggested. Please report back if not.

**Closed by nicolas-grekas** 2017-11-26 20:33 UTC
Labels: Bug, DependencyInjection
