### ISSUE TITLE
Issue with symfony/var-exporter v6.4.6 causing "Ignore on Proxies_CG_\App\Entity\Customer::__setInitialized() cannot be added" error

### ISSUE THREAD

**Issue by ferhado** [symfony/symfony#54507] opened 2024-04-06 04:18 UTC
### Symfony version(s) affected

6.4.6

### Description

After updating to version v6.4.6 of the symfony/var-exporter package, I encountered an error message stating "Ignore on Proxies_CG_\App\Entity\Customer::__setInitialized() cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set"." This error occurs during the execution of my Symfony application and impacts its functionality.

### How to reproduce

Update Symfony application dependencies using composer update.
Run the application and observe the error message.

### Possible Solution

Rolling back to version v6.4.4 of symfony/var-exporter resolves the issue, indicating that the problem is specific to version v6.4.6. A possible solution could involve investigating the changes made between versions v6.4.4 and v6.4.6 to identify and address the root cause of the issue.

### Additional Context

The error occurs consistently after updating to version v6.4.6 of symfony/var-exporter, impacting the functionality of Symfony applications. Further investigation into the changes made in this version may provide insights into resolving the issue.

**Comment by xabbuh** [comment] 2024-04-06 07:36
duplicate of https://github.com/symfony/symfony/issues/54477

**Closed as not planned** 2024-04-06 07:36 UTC
Labels: Bug, Status: Needs Review
