### ISSUE TITLE
[Console] InvalidArgumentException on run command with -e=prod

### ISSUE THREAD

**Issue by zzenmate** [symfony/symfony#27325] opened 2018-05-21 09:29 UTC
**Symfony version(s) affected**: 2.8.39
PHP Version: 7.1.17

**Description**  
[InvalidArgumentException]           
When I run the console command: php bin/console **-e=dev** , I get an error:                                                          
The file "/path_to_project/project/app/config/config_=dev.yml" does not exist. 
But when I do this through: php bin/console **--env=dev,** everything is ok 

**How to reproduce**  

php bin/console -e=dev

**Comment by chalasr** [comment] 2018-05-21 09:59
Duplicate of https://github.com/symfony/symfony/issues/26378. 
That's by design, only `-edev` or `-e dev` are (no separator or space separator for short options, as specified by [docopt](http://docopt.org/)).

**Closed by chalasr** 2018-05-21 09:59 UTC
