### ISSUE TITLE
[Form] can't add a violation with a callback constraint because of wrong path

### ISSUE THREAD

**Issue by walva** [symfony/symfony#36287] opened 2020-03-31 11:52 UTC
**Symfony version(s) affected**: 5.0.6

**Description**  
I cannot add an error/a violation with Validator callback in a form created in a Controller with the createFormBuilder method.

When I had a violation with the callback using the method `atPath`, a prefix `"data."` is automatically added. Unfortunately, that prefix breaks the path

**How to reproduce**  
The reproduced is hosted in this repository: https://github.com/SulivanDotEu/callback-validator-build-violation-bug-reproducer
In the reproduced, I use 2 ways to add errors to the form:

- ✅ add error manually with `$field->addError(new FormError('error message'));`
- ❌add error with a Callback constraint

Only one way is working.

- git clone
- composer install
- php bin/console server:start
- navigate to https://127.0.0.1:8000/form
- check the the controller App\Controller\FormController located in src/Controller/FormControllers

**Possible Solution**  
The method ExecutionContextInterface::atPath($path) append the $path variable to a prefix which is "data." in this case. It breaks the path to the concrete field.
I think the `$context` given to the callback method is wrongly initialized with a base property path: "data.". If the property path is empty, it would work.

**Additional context**  
all additional context is available in the reproduced readme (including a screenshot).
I'm available on Symfony Devs slack: @walva

**Comment by SulivanDotEu** [comment] 2020-03-31 11:53
related issue: https://github.com/symfony/symfony/issues/25401

**Comment by HeahDude** [comment] 2020-04-08 20:00
Hello @walva this is indeed a duplicate of #25401. Use the "real" path of your data structure is the way to go to get the expected behavior. You don't have to deal with `data` or `children` as the form will do the making properly.

Thanks for the reproducer, try to change this line:
```diff
-    ->atPath("[games].children[$customerId].children[$gameId].data")
+    ->atPath("[games][$customerId][$gameId]")
```

I think we should close here as well as there is nothing to fix.

**Closed** 2020-04-09 07:40 UTC
Labels: Bug, Form, Status: Needs Review, Validator

**Comment by walva** [comment] 2020-04-10 08:11
I just pushed the fix in the repo. It worked like a charm. I really thank you for the time you spend on my issue. It was actually very simple and understandable.
