### ISSUE TITLE
RequestContext ignores headers, query and request

### ISSUE THREAD

**Issue by ReSpawN** [symfony/symfony#30252] opened 2019-02-15 10:41 UTC
**Symfony version(s) affected**: 4.2.3

```
symfony/routing                     v4.2.3  Symfony Routing Component
symfony/http-foundation             v4.2.3  Symfony HttpFoundation Component
symfony/http-kernel                 v4.2.3  Symfony HttpKernel Component
symfony/expression-language         v4.2.3  Symfony ExpressionLanguage Component
sensio/framework-extra-bundle       v5.2.4  This bundle provides a way to configure your controllers with annotations

  Symfony
  Version                 4.2.3
  End of maintenance      07/2019
  End of life             01/2020
```

**Description**  
When using conditional matching for a specific route, the complete query, request and header ParameterBag is being ignored, ergo empty. The following has no adoption for these parameters whatsoever. 

The underneath is from `vendor/symfony/routing/Matcher/UrlMatcher.php`.

    /**
     * @internal
     */
    protected function createRequest($pathinfo)
    {
        if (!class_exists('Symfony\Component\HttpFoundation\Request')) {
            return null;
        }

        return Request::create($this->context->getScheme().'://'.$this->context->getHost().$this->context->getBaseUrl().$pathinfo, $this->context->getMethod(), $this->context->getParameters(), [], [], [
            'SCRIPT_FILENAME' => $this->context->getBaseUrl(),
            'SCRIPT_NAME' => $this->context->getBaseUrl(),
        ]);
    }

In result, I am not able to the following:

```
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/** @Route("/api", name="api-") */
class TestController extends Controller
{

	/**
	 * @Route(
	 *     "/test",
	 *     name="test", 
	 *     condition="request.headers.has('x-api-version') and request.headers.get('x-api-version') === '101'"
	 * )
	 */
	public function index()
	{
		return $this->json(['success' => true]);
	}

}

```

Various iterations of the above, with lets say "matching" or "==" has no result. Debugged the cache via `checkCondition` and all ParameterBags are empty.

**How to reproduce**  
The above is enough to reproduce.

**Additional context**  
I think it has something to do with the RequestContext not being filled properly.
Also a StackOverflow question has been created: https://stackoverflow.com/questions/54687908/conditional-routing-in-symfony-4

**Comment by nicolas-grekas** [comment] 2019-02-24 16:47
Did it ever work? If not, that'd be a new feature. Would you like to give it a try?

**Comment by eborges78** [comment] 2019-02-27 15:33
Hello, I tried to reproduce the bug but it works perfectly on my side.
Do you have more information to reproduce this bug?

**Comment by dimabory** [comment] 2019-03-04 16:21
I couldn't reproduce as well.

**Comment by xabbuh** [comment] 2019-03-04 16:55
I ma closing here then. However, we can consider to reopen once we are able to reproduce. Thank you for understanding.

**Closed by xabbuh** 2019-03-04 16:55 UTC
Labels: Bug, Routing, Status: Waiting feedback, Unconfirmed
