### ISSUE TITLE
Better support for GLB files

### ISSUE THREAD

**Issue by Sergiobop** [symfony/symfony#52611] opened 2023-11-16 12:43 UTC
### Symfony version(s) affected

All

### Description

I'm trying to upload a valid .glb file, and there are some problems:
- Using the method ->getMimeType() always returns 'application/octet-stream' instead of 'model/gltf-binary'
- Using the method ->extension() always returns 'bin' instead of 'glb'

In the [Mime types](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Mime/MimeTypes.php), i can find these keys in the map and the reverse map so it should work:
```
        'glb' => ['model/gltf-binary'],
        'gltf' => ['model/gltf+json'],
```

### How to reproduce

Try to upload a valid GLB and use ->extension() method.

For example:
[Duck.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb)

[BrainStem.glb](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/BrainStem/glTF-Binary/BrainStem.glb)

### Additional Context

You can check the GLB files that i mention are valid here: [GLTF VALIDATOR](https://github.khronos.org/glTF-Validator/)

Doing something like this:
```
$fileToUpload = $request->file('file');
dd($fileToUpload->extension(), $fileToUpload->getClientOriginalExtension());
```

Displays "bin", "glb"

**Comment by gencoglutugrul** [comment] 2023-12-09 14:07
I tried to reproduce this in Symfony 6.4, unfortunately I couldn't. Please provide more details, like how look like your setup, what is your symfony version etc. 

Here is how my endpoint looks like;
```php
public function indexAction(Request $request): Response
{
    $fileToUpload = $request->files->get('file');

    return new Response(
        $fileToUpload->getMimeType()
    );
}
```

I made the request with the following command;
```
curl --location --request POST 'https://localhost/test' \
--form 'file=@"./Duck.glb"'
```
I got the following result;
```
model/gltf-binary
``` 

#SymfonyHackDay

**Comment by sstok** [comment] 2023-12-24 19:58
The mime-type is resolved by PHP, which uses the systems 'magic' file for mime-types. 
If this is not up-to-date you get 'application/octet-stream' as default.

See https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L115-L119

**Comment by xabbuh** [comment] 2023-12-30 08:38
I am closing here as explained before. Thank you for understanding.

**Closed as not planned by xabbuh** 2023-12-30 08:38 UTC
Labels: Bug, HttpFoundation, Unconfirmed, Status: Needs Review, Mime
