### ISSUE TITLE
Error when Check if we need to send extra expire info headers

### ISSUE THREAD

**Issue by iboukhatem** [symfony/symfony#42308] opened 2021-07-28 12:21 UTC
**Symfony version(s) affected**: all

**Description**
in the file "symfony/http-foundation/Response.php" `public function prepare` ligne 314, when the http protol version is '1.0', the second comparaison causes a bug if `$headers->get('Cache-Control')` returns null and not string, 

**How to reproduce**
run on http 1.0

**Possible Solution**
pass a default value to `$headers->get('Cache-Control', '')`

**Additional context**

**Comment by derrabus** [comment] 2021-07-28 12:56
Duplicate of #42290

**Closed as completed by derrabus** 2021-07-28 12:56 UTC
Labels: Bug, HttpFoundation, Status: Needs Review
