### ISSUE TITLE
Strange behaviour of service container

### ISSUE THREAD

**Issue by videni** [symfony/symfony#17944] opened 2016-02-28 02:12 UTC
When we create a lazy load service , It is supposed to pass initializer to  staticProxyConstructor of a proxy  instead of  its constructor.  I have no idea why this happened, please check this [link.](https://github.com/Sylius/Sylius/issues/4335)

**Comment by xabbuh** [comment] 2016-02-28 07:34
Currently, you have to stick to ProxyManager v1.x when using Symfony (see #17919 for the PR that will fix this). I am closing here as a duplicate of #17676 though.

**Closed by xabbuh** 2016-02-28 07:34 UTC
