### ISSUE TITLE
Exception occured while flushing email queue while not using SwiftMail

### ISSUE THREAD

**Issue by dialogik** [symfony/symfony#23209] opened 2017-06-16 10:05 UTC
I am constantly getting an error (v3.1.5)

> `app.ERROR: Exception occurred while flushing email queue: Expected response code 220 but got code "", with message "" [] []`

while I am not using any email function at all. Why does the application try to flush the email queue then?

**Comment by xabbuh** [comment] 2017-06-19 07:40
Please note that Symfony 3.1 is not supported anymore. Do you experience the same issue on Symfony 3.2 or higher? Can you debug where this log entry is coming from?

**Comment by rammstein06** [comment] 2017-07-03 13:57
Same error.
symfony v3.3.2
swiftmailer v5.4.8
> app.ERROR: Exception occurred while flushing email queue: Expected response code 220 but got code "", with message "" [] []

app/config/config.yml
    mailer_transport: sendmail

**Comment by jakzal** [comment] 2017-10-23 13:19
> No bug anymore for me.

Thanks! It looks like it was misconfiguration anyway (otherwise we'd have more reports like this one). Closing.

**Closed by jakzal** 2017-10-23 13:19 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback

**Comment by dialogik** [comment] 2017-10-23 16:08
No misconfiguration on my side: I didn‘t use swiftmailer at all and used default config for mail settings.

**Comment by xabbuh** [comment] 2017-10-23 16:18
@dialogik The default config uses Swiftmailer (see https://github.com/symfony/symfony-standard/blob/3.3/app/config/config.yml#L64-L69). If it's not related to Swiftmailer in your case, you would need to provide more information which show that the error is related to Symfony and not caused by the library you use to send mails.

**Comment by dialogik** [comment] 2017-10-24 10:29
@xabbuh Follow my logic:

* I am using the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
* I did not make any modifications to the Swiftmailer configuration in `app/config/config.yml`
* I do not use any mail functions at all, e.g. by calling the Swiftmailer service
* Despite the before mentioned points, my app tries to flush the email queue

Thus: In my opinion there is no error on Swiftmail, but on Symfony, as it tries to flush the email queue without any necessity or instruction to do so.

**Comment by jakzal** [comment] 2017-10-24 10:47
Following your steps @dialogik doesn't yield the same results for me. 

The spool won't do anything if there's no messages (see https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/MemorySpool.php#L78), so something in your app must be sending a message. Otherwise, please provide a full app based on a fresh standard edition project that would help to reproduce the problem.

**Comment by Barh** [comment] 2018-12-01 16:10
At the moment solved a problem it:

1. Updated Symfony to version **4.2** and "symfony/swiftmailer-bundle" up to **3.2.4**
2. Adjusted SwiftMailer so, _**config/packages/swiftmailer.yaml**_:
```
swiftmailer:
    ...
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool/'
```
3. I send letters separate team, for example: 
 `php bin/console swiftmailer:spool:send --message-limit=500`

Without paragraph 1, did not allow me to send more than 1 letter, gave an error message.

Perhaps, will work also without paragraph 2.
