### ISSUE TITLE
[Form] Conflict between empty Placeholder value and false value in ChoiceType

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#17677] opened 2016-02-04 08:15 UTC
Using Symfony 2.8.2 or 3.0.2.
You can reproduce the problem with this simple statement:

```php
$builder->add('participation', ChoiceType::class, array(
     'choices' => [ 'yes' => true, 'no' => false ],
    'placeholder' => 'Select a value',
    'empty_data' => null,
    'choices_as_values' => true,
));
```

Expected result:

```html
<select name="filter[participation]" id="filter_participation">
    <option value="">Select a value</option>
    <option value="1">Yes</option>
    <option selected="selected" value="0">No</option>
</select>
```

Actual result:

```html
<select name="filter[participation]" id="filter_participation">
    <option value="1">Yes</option>
    <option selected="selected" value="">No</option>
</select>
```
Dump of choiceList:

![boolean_choice_dump](https://cloud.githubusercontent.com/assets/652505/12809461/ab8548c8-cb1f-11e5-974b-d38b5dd6c519.png)

As you can see, the placeholder is not rendered. If I add a new empty value in 'choices', I got an empty value in the view plus the placeholder value.

**Comment by HeahDude** [comment] 2016-02-11 07:52
Hi @raziel057, the workaround is to use `choice_value` option as below :

$builder->add('participation', ChoiceType::class, array(
    'choices' => [ 'yes' => true, 'no' => false ],
    'choice_value' => function ($choice) {
         return false === $choice ? '0' : (string) $choice;
    },
    'placeholder' => 'Select a value',
    'empty_data' => null,
    'choices_as_values' => true,
));

see #17759  for my proposal to fix it.

**Comment by HeahDude** [comment] 2016-02-11 07:53
Bug confirmed.
Status: reviewed

**Comment by raziel057** [comment] 2016-02-11 08:10
@HeahDude Yes in fact, to avoid to use this workarround in all my fields, I created a custom BooleanType with a DataTransformer to be able to use it like this:

```php
$builder->add('interpretation', PtcBooleanType::class, array(
    'label' => 'enabled',
    'required' => false,
));
```

```php
namespace PTC\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use PTC\CoreBundle\Form\DataTransformer\StringToBooleanTransformer;

class PtcBooleanType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new StringToBooleanTransformer('1', '0'));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => array(
                'yes' => '1',
                'no' => '0',
            ),
        ));

        $resolver->addAllowedValues('multiple', false);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return ChoiceType::class;
    }
}
```
With a String to Boolean Transformer:

```php
<?php
namespace PTC\CoreBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class StringToBooleanTransformer implements DataTransformerInterface
{
    /**
     * @var string
     */
    private $trueValue;

    /**
     * @var string
     */
    private $falseValue;

    /**
     * @param string $trueValue
     * @param string $falseValue
     */
    public function __construct($trueValue, $falseValue)
    {
        $this->trueValue = $trueValue;
        $this->falseValue = $falseValue;
    }

    /**
     * {@inheritDoc}
     */
    public function transform($value)
    {
        if (null === $value) {
             return null;
        }

        if (!is_bool($value)) {
            throw new TransformationFailedException('Expected a Boolean.');
        }

        return true === $value ? $this->trueValue : $this->falseValue;
    }

    /**
     * {@inheritDoc}
     */
    public function reverseTransform($value)
    {
        if (null === $value) {
            return null;
        }

        if (!is_string($value)) {
            throw new TransformationFailedException('Expected a string.');
        }

        return $this->trueValue === $value;
    }
}
```

**Comment by xabbuh** [comment] 2016-02-11 08:21
closing here as a duplicate of #17292

**Closed by xabbuh** 2016-02-11 08:21 UTC
Labels: Bug, Form, Status: Reviewed
