### ISSUE TITLE
[HttpKernel] _route_params can be empty

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#20667] opened 2016-11-28 09:46 UTC
Looking at the web profiler in Silex I saw

>**Notice**: Undefined offset: 1 in **/srv/http/tronatic-studio.com/vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php** on line **280**
>
>**Warning**: Invalid argument supplied for foreach() in **/srv/http/tronatic-studio.com/vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php** on line **280**

under **Route Parameters**.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L280

The matching route didn't have any parameter.

Don't know why https://github.com/symfony/symfony/commit/2e404d07021d4c01f9ca831a7bb222efc15bed70 introduced this.

Dumping `$data->getRawData()` shows
```
array(1) { [0]=> array(1) { [0]=> array(0) { } } } 
```

**Comment by javiereguiluz** [comment] 2016-11-28 09:56
@MatTheCat thanks for reporting this issue. I think this is a duplicate of #20650 which was fixed yesterday by #20652.  I'm closing this as "fixed", but if you still have problems, please reopen it. Thanks!

**Closed by javiereguiluz** 2016-11-28 09:56 UTC

**Comment by MatTheCat** [comment] 2016-11-28 10:03
Woops I searched for `HttpKernel` and `RequestDataCollector` but found nothing, sorry for the noise.
