### ISSUE TITLE
[DI] Track tagged PHP source files

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#41437] opened 2021-05-28 13:17 UTC
In 4.4 i noticed the container isnt always refreshed.

Given eg.

```xml
<argument key="$somes" type="tagged_iterator" tag="some" default-priority-method="getPriority"/>
```

Updating the actual priorities in code for matching services requires a hard refresh. I tend to believe it also affects php8 attributes, recently added. Correct me if im wrong though.

Could we enable resource tracking for those services having config in code?

**Comment by stof** [comment] 2021-05-28 13:32
duplicate of https://github.com/symfony/symfony/issues/39988 (actually, your cases describes a subset of the previous report as it focuses on a specific usage)

**Closed as completed by stof** 2021-05-28 13:32 UTC
Labels: DependencyInjection
