### ISSUE TITLE
[Translation] %parameters% are not replaced when file is first dumped as `+intl-icu`and then read

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#35328] opened 2020-01-13 19:15 UTC
**Symfony version(s) affected**: 4.4

**Description**  
We have a FileDumper that converts `messages.en.yml` to `messages.en.php` files. Since 4.4 this file became `message+intl-icu.en.php` with the same content.

Upon reading these `+incl-icu.php` files, the `%placeholder%` are no longer replaced with the correct value.

Spoke with @yceruto in https://github.com/symfony/symfony/issues/35264#issuecomment-572999199 and he suggested this is a different issue.

**How to reproduce**  
See commits on https://github.com/ruudk/symfony-translation-bug-poc/commits/master

**Possible Solution**  
The FileDumper should not just add `+intl-icu` to files.

**Comment by yceruto** [comment] 2020-01-14 15:57
Hi @ruudk, I'll check your reproducer at some point this week. Thank you for opening this issue.

**Comment by nicwortel** [comment] 2020-01-15 10:08
@yceruto I came here through #35264 because we are experiencing a similar issue. I wonder if _this_ issue is really a bug though. The ICU message format is a different format than Symfony's one. Where Symfony's format uses percentage signs for placeholders (`%placeholder%`), [ICU uses brackets](https://symfony.com/doc/current/translation/message_format.html#message-placeholders) (`{placeholder}`). So I guess it's expected that `%placeholder%` doesn't work in a `+intl-icu` file.

Having said that, I do believe that #34797 that was released with Symfony 4.4.2 and 5.0.2 is a breaking change for use cases where translation files are created that don't exist yet. In our situation, we use https://github.com/php-translation/symfony-bundle to download translations from [Loco](https://localise.biz/) and dump them to (gitignored) XLIFF files during our build process. Using symfony/translation v4.4.1, the files dumped are `messages.en.xlf`, `messages.nl.xlf`, etc. After updating to symfony/translation v4.4.2, the dumped file names are suddenly changed to `messages+intl-icu.en.xlf`, `messages+intl-icu.nl.xlf`, etc.

So the assumption in #34797 is that the translation files already exist and the decision between intl-icu or the "old" format is based entirely on the existance of those files. Whenever that is not the case (for example when using https://github.com/php-translation/symfony-bundle to download translations from an external source, adding a new language, etc.), this breaks with the previous behaviour in v4.4.1.

**Comment by yceruto** [comment] 2020-01-15 13:39
@nicwortel I can confirm what you said. Let's revert https://github.com/symfony/symfony/pull/34797 in the meantime. see https://github.com/symfony/symfony/pull/35351

**Comment by yceruto** [comment] 2020-01-15 13:43
> The ICU message format is a different format than Symfony's one. Where Symfony's format uses percentage signs for placeholders (%placeholder%), ICU uses brackets ({placeholder}). So I guess it's expected that %placeholder% doesn't work in a +intl-icu file.

Let's close because we can do nothing here. Thank you @ruudk and @nicwortel.

**Closed by yceruto** 2020-01-15 13:43 UTC
Labels: Bug, Status: Needs Review, Translator

**Comment by XWB** [comment] 2020-01-20 18:43
I'm having exactly the same issue as @nicwortel

**Comment by michaelKaefer** [comment] 2020-03-10 12:21
I tried and searched for more than 1.5 hours to find this.. It was really a pain not knowing why it did not work. At least an error would be cool. Can you reopen this issue?

**Comment by ruudk** [comment] 2020-03-10 12:25
Why? This has been fixed with another release.

**Comment by michaelKaefer** [comment] 2020-03-10 12:27
@ruudk Ah, I didn't know. How could I have seen this on my own?

**Comment by ruudk** [comment] 2020-03-10 12:28
No worries. This PR reverted the broken behaviour: https://github.com/symfony/symfony/pull/35351

**Comment by xoniq** [comment] 2023-07-07 09:09
As of 2023 this is still an issue. On a new project.

**Comment by Nek-** [comment] 2024-04-12 09:05
Oh my. I'm having a headache for some minutes/hours. Removing `+intl-icu` suffix after the filename was fixing the issue. 😬 

- Symfony 7.0
- New project setup with symfony cli
- Translation files generated with the Symfony commands 

However, this looks more like an issue of the documentation that is highlighting `%var%` instead of `{var}` as suggested here: https://symfony.com/doc/current/reference/formats/message_format.html
