### ISSUE TITLE
[Validator] Add constraint on unique elements collection(Assert\Unique)

### ISSUE THREAD

**Issue by zzenmate** [symfony/symfony#26535] opened 2018-03-14 21:14 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

What about add constraint on unique elements collection?
I think it will be named as Assert\UniqueCollection.
It is partly linked with https://github.com/symfony/symfony/issues/9888
What do you think? I'd be happy to send a PR after it's discussed.

**Comment by ostrolucky** [comment] 2018-03-15 22:51
Another duplicate of Another duplicate of https://github.com/symfony/symfony/issues/9888 Do you think you can implement it in a way it would be in line with proposal?

**Comment by xabbuh** [comment] 2018-09-24 09:38
closing here as this feature request is included in #9888

**Closed by xabbuh** 2018-09-24 09:38 UTC
Labels: Feature, Validator
