### ISSUE TITLE
syntax error, unexpected 'echo' (T_ECHO), expecting identifier in appDevDebugProjectContainer.php

### ISSUE THREAD

**Issue by atienzacd** [symfony/symfony#29189] opened 2018-11-12 14:46 UTC
**Symfony version(s) affected**: 3.3.10

**Description**  
I'm getting an error that whenever I use composer install, composer update, or manually php bin/console cache:clear I get this error:
`PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO), expecting identifier (T_STRING) in /var/www/proxyapi/var/cache/dev/appDevDebugProjectContainer.php on line 7830`

**Additional context**  
Here is the content of my [composer show](https://pastebin.com/XUWxiCiS)

The error line is on the declaration of the function echo. Here is the content before and after the line:

```
public function close()
    {
        $this->initializer5be94dee10d91398815883 && ($this->initializer5be94dee10d91398815883->__invoke($valueHolder5be94dee10d87064319339, $this, 'close', array(), $this->initializer5be94dee10d91398815883) || 1) && $this->valueHolder5be94dee10d87064319339 = $valueHolder5be94dee10d87064319339;

        return $this->valueHolder5be94dee10d87064319339->close();
    }

    /**
     * {@inheritDoc}
     */
    public function echo()
    {
        $this->initializer5be94dee10d91398815883 && ($this->initializer5be94dee10d91398815883->__invoke($valueHolder5be94dee10d87064319339, $this, 'echo', array(), $this->initializer5be94dee10d91398815883) || 1) && $this->valueHolder5be94dee10d87064319339 = $valueHolder5be94dee10d87064319339;

        return $this->valueHolder5be94dee10d87064319339->echo();
    }

    /**
     * {@inheritDoc}
     */
    public function psetex()
    {
        $this->initializer5be94dee10d91398815883 && ($this->initializer5be94dee10d91398815883->__invoke($valueHolder5be94dee10d87064319339, $this, 'psetex', array(), $this->initializer5be94dee10d91398815883) || 1) && $this->valueHolder5be94dee10d87064319339 = $valueHolder5be94dee10d87064319339;

        return $this->valueHolder5be94dee10d87064319339->psetex();
    }

```

**Comment by stof** [comment] 2018-11-12 15:59
this looks like an issue related to ProxyManager, as that part is the source code of a generated proxy class.

**Comment by nicolas-grekas** [comment] 2018-11-12 16:58
Closing for one of these 3 reasons (I'll let you check which one is the correct one ;) ):
- 3.3 is not maintained anymore, please upgrade
- the issue is in ProxyManager (ie wrong repo)
- you're using PHP5, but using reserved keywords as method names is allowed since PHP7 only, see https://3v4l.org/0oevR

(third option would be my guess.)

**Closed by nicolas-grekas** 2018-11-12 16:58 UTC
