### ISSUE TITLE
[Router] Using multiple conditions with included routes ignores the second condition

### ISSUE THREAD

**Issue by digilist** [symfony/symfony#35947] opened 2020-03-03 21:06 UTC
**Symfony version(s) affected**: 5.0, 4.4 (probably more, I just tested these two)

**Description**  
Consider the following route configuration that is split into two files:
routes.yaml:
```yaml
main:
    resource: routes/main.yaml
    condition: 'request.query.get("name") === "world"'
```

routes/main.yaml
```yaml
hello_world:
    path: /
    controller: \App\Controller\HelloControllers
    condition: 'request.query.get("foo") === "bar"'
```

I would expect that both conditions are checked and that the controller is only called for a request with `?name=world&foo=bar`. But the controller is actually called without checking the condition in `second.yml` - a request with `?name=world` already succeeds.

When the condition in `main.yml` is removed the "inner" condition is checked correctly and the `foo` query parameter is checked.

To summarize:

| Request                                            | Expected             | Actual               | Result |
|----------------------------------------------------|----------------------|----------------------|--------|
| `?name=world&foo=bar`                              | Controller is called | Controller is called | ✅      |
| `?name=world`                                      | 404                  | Controller is called | ❌      |
| `?foo=bar`                                         | 404                  | 404                  | ✅      |
| `?name=world` without the condition in routes.yaml | 404                  | 404                  | ✅      |

**How to reproduce**  
Add some routes with the configuration shown above. The controller does not even have to exist, because the controller is only loaded after checking the conditions and seeing the error page is the same as having a controller.

**Possible Solution**  
None yet :(

**Additional context**  
For me it looks like the URL matcher considers only the "outer" condition when there are multiple conditions and ignores the "inner" one. I did not expect this and it took some time to debug this. I would rather expect that the inner condition overwrites the outer one or that both conditions are combined with an AND.

As included routes inherit properties from the including configuration (e.g. defaults and name_prefix), I would expect a combination here with AND. If combining the conditions is not possible then I would rather expect, that the inner one overrides the outer one and not the other way around.

**Comment by nicolas-grekas** [comment] 2020-03-10 09:10
That's expected to me: there can be only one condition, so that one replaces the other.

**Comment by digilist** [comment] 2020-03-10 09:43
But shouldn't it be the other way around? That the more specific route definition replaces the "broader" one?

**Comment by nicolas-grekas** [comment] 2020-03-10 10:01
The issue is that "most specific" is relative: when you import the routes from a bundle, the most specific side is the importing one.

**Comment by Tobion** [comment] 2020-03-10 23:59
I can confirm @nicolas-grekas statement. This also applies to other conditions like schemes and methods.

**Comment by nicolas-grekas** [comment] 2020-03-13 11:49
Closing as explained.

**Closed by nicolas-grekas** 2020-03-13 11:49 UTC
Labels: Bug, Routing, Status: Needs Review

**Comment by digilist** [comment] 2020-03-15 22:15
Thank you, with this explanation it makes sense.
