### ISSUE TITLE
Type validator validates against a different type when submitted data is unchanged from entity

### ISSUE THREAD

**Issue by leigh-ols** [symfony/symfony#32151] opened 2019-06-24 11:36 UTC
**Symfony version(s) affected**: 4.3.*

**Description**  

When submitting data to a form with a field value that already matches the value in the Entity. Type validation fails.

**How to reproduce**  
Entity:

Trying to update an entity, and submitting a field with a value that is unchanged results in a type error. What am I doing wrong?

Entity:
```
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
...
class User implements UserInterface
{
...

    /**
     * @ORM\Column(type="bigint", nullable=true)
     * @Groups({"default", "listing"})
     * @Assert\Type("integer")
     */
    private $recordQuota;

...
```

FormType:
```
<?php

namespace App\Form;

...

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
...
            ->add('recordQuota', IntegerType::class)
        ;
    }

...
}
```

Controller:
```
...
    /**
     * @Route("/api/user/{id}", name="editUser")
     * @Method({"PUT", "PATCH"})
     * @Rest\View()
     */
    public function updateAction(Request $request, User $user)
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
...
```

Submit `user[recordQuota] = 1000`. If updated Entity already has `user[recordQuota] == 1000` submission will fail with type validation error "This value should be of type Integer.". If submitting `user[recordQuota] = 999`. Submission will succeed and Entity will be updated.

Removing the type constraints from the form and the entity has the reverse behavior... The form will submit if the field is unchanged. But will fail with "This value should be of type String" if the value is altered.

Is this a bug or something I'm doing wrong?

**Comment by andrew-demb** [comment] 2019-06-24 12:08
Doctrine puts string value for `bigint` field in your entity after map from DB row.
It's the reason, why unchanged entity leads to validation issue.

I can't answer, where should be a fix for this.

**Comment by xabbuh** [comment] 2019-06-24 14:33
As @andrew-demb says Doctrine maps the `bigint` type to a `string` (see also https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#doctrine-mapping-types). You will need to adapt your validation rules accordingly as currently they do not match what gets back from the database. I am closing here as there is nothing to fix in the Symfony code. Thank you for understanding.

**Closed by xabbuh** 2019-06-24 14:33 UTC
Labels: Bug, Form, Status: Needs Review, Validator

**Comment by leigh-ols** [comment] 2019-06-24 15:33
You don't think this kind of thing needs documenting somewhere?

It is surely the kind of thing that anyone using a bigint is going to run into. And also the kind of thing most people would expect to 'just work'.

'adapt your validation rules accordingly' is also a little vague. Could you perhaps point me in a more specific direction? Many thanks.

**Comment by xabbuh** [comment] 2019-06-24 16:18
Well, if your type is `string`, the `Type` constraint needs to be configured accordingly:

```php
@Assert\Type("string")
```

**Comment by stof** [comment] 2019-06-24 16:49
DBAL maps bigint to a string, because a database bigint does not fit in a 32-bit integer (and they decided to avoid changing the mapping depending on whether PHP is compiled in 32 bits or 64 bits mode).
this is done to avoid having a bigint (which is an exact value in the DB) overflowing to a PHP float (which is not an exact number anymore).

**Comment by leigh-ols** [comment] 2019-06-25 07:52
Using @Assert\Type("string") results in the same as removing the type constraints as mentioned in the original issue "This value should be of type string" when the value is updated.

Having it set as integer will work when updating but fail when passing in an unchanged value.

Having it set as string will work when passing in an unchanged value but fail when updating.

**Comment by xabbuh** [comment] 2019-06-25 08:05
This comes from the fact that you are using the `IntegerType` here which will automatically map an integer to your entity data. You could remove the type constraint and ensure that the type is valid by having a dedicated setter method which only accepts strings (or type casts integers to strings).

But you can also change your form type so that it only maps strings to your model. If you are already using Symfony 4.3, you can use the `NumberType` setting its `input` option to `string`. Otherwise you can add a model transformer to your field that does the type cast.

**Comment by leigh-ols** [comment] 2019-06-25 09:59
"This comes from the fact that you are using the IntegerType here "

When I changed the Assert\Type("string") I removed the UserType IntegerType::class along with it.

It looks like this:

```
...
    /**
     * @ORM\Column(type="bigint", nullable=true)
     * @Groups({"default", "listing"})
     * @Assert\Type("string")
     */
    private $recordQuota;
...
```

```
...
$builder->add('recordQuota');
...
```

The error still persists exactly as described in the original issue.
Set it to assert string (or no assert at all), and it wont allow update. Set it to assert integer, and it will fail when the submitted value is unchanged.

"you can use the NumberType setting its input option to string"

I'll give this a try. Thanks.

**Comment by leigh-ols** [comment] 2019-06-25 14:42
Using `->add('recordQuota', NumberType::class, ['input' => 'string'])` with no `@Asserts\Type` results in `Unable to transform data for property path "recordQuota": Expected a numeric string.` Regardless of if the submitted value is altered or not.

This issue has been closed as not a bug, but to me this still looks like a bug, acts like a bug and smells like a bug.

I can't come up with any combination of validation at all that will allow submission of bigint's in a Symfony form.

Either it fails every time, it fails when the data isn't altered, or it fails when the data is altered.

**Comment by xabbuh** [comment] 2019-06-25 15:18
> Using `->add('recordQuota', NumberType::class, ['input' => 'string'])` with no `@Asserts\Type` results in `Unable to transform data for property path "recordQuota": Expected a numeric string.` Regardless of if the submitted value is altered or not.

@leigh-ols Can you create an example application with this that allows to reproduce?

**Comment by leigh-ols** [comment] 2019-06-26 09:10
So in making the example App at first I couldn't reproduce the issue, then I enabled auto-mapping and eureka.
It seems to be a quirk/bug in validator auto-mapping support for doctrine being enabled:

```
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
            App\Entity\: []
```

type=bigint gets mapped to @AssertType("string")

But this results in a field that can never be validated, regardless of changing the fields individual validation settings.

* `NumberType::class` => "This value should be of type string"
* `NumberType::class, ['input' => string]` => "Unable to transform data for property path "testBigInt": Expected a numeric string."
* `No type` => "This value should be of type string" when submitting changes
* `@AssertType("integer")` => "This value should be of type integer" when submitting unchanged.


Should auto-mapping `@Assert\Type` be overwritten when manually provided?


Here is the sample project:
https://github.com/leigh-ols/symfony-32151

**Comment by xabbuh** [comment] 2019-06-26 09:33
@leigh-ols You have type hints on your `getTestBigInt()` and `setTestBigInt()` which implicitly lead to type casts from `string` to `int` and vice versa. That means that initially your object is populated by Doctrine with the value being a `string`. Then, when the form is populated it's cast to an `int` because of the return type declaration. So after the form is mapped back to your entity the type of the property now is an `int`. Changing the type hints to `string` should help with it.

**Comment by leigh-ols** [comment] 2019-06-26 09:50
@xabbuh Thanks... That does get around the issue. 
However I believe those getters/setters were generated automatically with `make:entity`.

**Comment by xabbuh** [comment] 2019-06-26 09:54
If that's the case, it would be nice if you could open an issue in [their repository](https://github.com/symfony/maker-bundle) as that would indeed require a bugfix in the MakerBundle then.

**Comment by leigh-ols** [comment] 2019-06-26 10:05
Thank you for all of your assistance on this one. 
My issue in debugging it was with the new auto_mapping feature. Which I haven't used before, and had forgotten I had enabled!

**Comment by xabbuh** [comment] 2019-06-26 10:06
You're welcome. :)
