### ISSUE TITLE
[DI] Unable to resolve env()

### ISSUE THREAD

**Issue by olvlvl** [symfony/symfony#21420] opened 2017-01-26 16:16 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

Hi,

I'm trying to use the new `env()` placeholder introduced with https://github.com/symfony/symfony/pull/19681, but I can't get it to work. I installed `symfony/dependency-injection|config|yaml`, and I followed [Setting up the Container with Configuration Files](https://symfony.com/doc/current/components/dependency_injection.html#setting-up-the-container-with-configuration-files).

This is my script—mostly copy/pasted from the documentation:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__));
$loader->load('services.yml');

var_dump(getenv('NAME'));
var_dump($container->getParameter('test'));
```

This is my `services.yml` file:

```yml
parameters:
  test: '%env(NAME)%'
```

And this is the output of the command `NAME=madonna php test.php`:

```raw
/Volumes/GIT/olvlvl/test-di-env/test.php:13:
string(7) "madonna"
/Volumes/GIT/olvlvl/test-di-env/test.php:14:
string(11) "%env(NAME)%"
```

I also read [How to Set external Parameters in the Service Container](http://symfony.com/doc/current/configuration/external_parameters.html) but it doesn't give more information, so I'm not sure what's wrong.

Here is the package list:

```
symfony/config               v3.2.2 Symfony Config Component
symfony/dependency-injection v3.2.2 Symfony DependencyInjection Component
symfony/filesystem           v3.2.2 Symfony Filesystem Component
symfony/yaml                 v3.2.2 Symfony Yaml Component
```

Can you help?

**Comment by stof** [comment] 2017-01-26 16:19
This is because your container is not compiled, so parameters are not resolved yet

**Comment by olvlvl** [comment] 2017-01-26 16:39
Thanks for you answer @stof, I added the following line:

```php
$container->compile();

var_dump(getenv('NAME'));
var_dump($container->getParameter('test'));
```

Now I get the following result:

```
/Volumes/GIT/olvlvl/test-di-env/test.php:15:
string(7) "madonna"
/Volumes/GIT/olvlvl/test-di-env/test.php:16:
string(41) "env_NAME_812dcc3cc5cf425ee641becdc595f9f4"
```

Still no "madonna" is sight :(

**Comment by stof** [comment] 2017-01-26 16:40
@nicolas-grekas do you have any idea here ?

**Comment by chalasr** [comment] 2017-01-26 17:50
@olvlvl Here is what you need:

```php
var_dump($container->resolveEnvPlaceholders($container->getParameter('test'), true));
```

**Comment by chalasr** [comment] 2017-01-26 17:53
> Also, the documentation says nothing about compilation requirement :(

In the doc you pasted, there is no usage of the container yet. Compilation phase is the next chapter https://symfony.com/doc/current/components/dependency_injection.html#learn-more

**Comment by HeahDude** [comment] 2017-01-26 21:03
In such cases using `SYMFONY__` vars should do the trick as they would be resolved at this point, right? (ref https://github.com/symfony/symfony/pull/20100#issuecomment-250686060).

**Comment by chalasr** [comment] 2017-01-26 21:22
@HeahDude It seems the intention is to experiment the new feature, both being not about the same usage (there's apparently no need for setting a value at compile time here). But sure it would work as well.

**Comment by HeahDude** [comment] 2017-01-26 21:56
>(there's apparently no need for setting a value at compile time here)

There is apparently the need to get one :D, so this experiment is pointing a limitation that makes me think, maybe, we should not deprecate one of the other way.

What about some method like `$container->getResolvedParameter('test', true)` then? Or just adding a second argument to `getParameter`?

**Comment by chalasr** [comment] 2017-01-27 21:15
> this experiment is pointing a limitation

You're right but that's by design and, unfortunately, it is far from being the only one.
For instance, take the following parameters:

```yaml
parameters:
    foo: "%env(BAR)%"
```

Then, assuming the `BAR` environment variable is set to `bar_val`, try to fetch it from a controller (frozen container):

```php
public function indexAction() {
    dump($this->getParameter('env(BAR)')); 
}
```

> InvalidArgumentException: The parameter "env(bar)" must be defined.

But:

```php
public function indexAction() {
    dump($this->getParameter('foo')); 
}
```

> bar_val

... You can see another one by running `debug:container --parameter "env(BAR)"` then `debug:container --parameters|grep "env(BAR)"`, both gives different outputs but _never_ the actual value of the env var.

Most of these issues have been pointed out already (#20688, #20696, #20695) without success.

**Comment by nicolas-grekas** [comment] 2017-01-30 08:47
See #21460

**Comment by olvlvl** [comment] 2017-01-30 10:26
If I dump the compiled container, and use it instead it's working fine:

```php
<?php

use Symfony\Component\DependencyInjection\Dumper\PhpDumper;

file_put_contents('di.php', (new PhpDumper($container))->dump());

require 'di.php';

$container = new ProjectServiceContainer;

var_dump($container->getParameter('test'));
// madonna
```

**Comment by nicolas-grekas** [comment] 2017-01-30 10:42
And does it work also when using #21460 - then doing `$container->compile(true)`?

**Comment by olvlvl** [comment] 2017-01-30 10:47
Yes, it does, but now I have `madonna` hard coded in the DI dump:

```php
    /**
     * Gets the default parameters.
     *
     * @return array An array of the default parameters
     */
    protected function getDefaultParameters()
    {
        return array(
            'test' => 'madonna',
        );
    }
```

I'd rather not have sensitive data written anywhere in the application files.

**Comment by nicolas-grekas** [comment] 2017-01-30 10:58
It's either compile(true) + *no* dump
or compile() + dump.
But compile(true) + no dump will inline, that's the meaning of the "true" :)
Can you try compile(true) + *no* dump?

**Comment by olvlvl** [comment] 2017-01-30 11:33
compile(true) + no dump is working too.

**Comment by wersoo** [comment] 2017-02-04 21:57
@olvlvl, I've temporary solved it in a very dirty way like that:
```php
$this->container = new ContainerBuilder();
$loader = new YamlFileLoader($this->container, new FileLocator(APP_ROOT . 'resources'));
$loader->load('config.yml');

$bag = $this->container->getParameterBag();
if ($bag instanceof EnvPlaceholderParameterBag) {
    // temporary fix for https://github.com/symfony/symfony/issues/21420
    $bagCopy = clone $bag;
    $bagCopy->resolve();
    $envPlaceholders = $bagCopy->getEnvPlaceholders();
    foreach ($envPlaceholders as $env => $value) {
        $envPlaceholders[$env] = [getenv($env) ?: $value];
    }

    $refProperty = new \ReflectionProperty($bag, 'envPlaceholders');
    $refProperty->setAccessible(true);
    $refProperty->setValue($bag, $envPlaceholders);
}

$this->container->compile();
```

**Comment by olvlvl** [comment] 2017-02-05 07:35
Thanks @wersoo, but I'm fine with the latest changes of @nicolas-grekas.

**Comment by javiereguiluz** [comment] 2017-02-17 15:32
Closing it as fixed by #21460.

**Closed by javiereguiluz** 2017-02-17 15:32 UTC
Labels: Bug, DependencyInjection

**Comment by dueddel** [comment] 2019-01-14 16:30
> And does it work also when using #21460 - then doing `$container->compile(true)`?

`$container->compile(true)` did it for me. Thanks.

**Comment by oleg-andreyev** [comment] 2019-12-09 14:29
Trying to upgrade our huge project from 2.8 to 3.4 (latest) and currently experiencing a similar issue:

```yaml
parameters:
    env(SITE_HOST_OVERRIDE): 'foo'
```

```php
if ($overrideHost = $container->getParameter('SITE_HOST_OVERRIDE')) {
...
}
```

I expect that `overrideHost` will be `foo`, but instead, I get an exception `The parameter "SITE_HOST_OVERRIDE" must be defined.` and when I change it to `env(SITE_HOST_OVERRIDE)` it's working.

What is the expected behavior?

**Comment by jperovic** [comment] 2021-10-26 17:54
> And does it work also when using #21460 - then doing `$container->compile(true)`?

Boy, this has blown me away! I spent the whole afternoon going through the internals of container builder, before the compilation phase, trying to figure out how it does the resolution. 

And Google was not kind either. Any "inject ENV variables in <command/service>", point to the docs for the full Symfony app, and this is not :) 

Thanks a bunch, @nicolas-grekas!

**Comment by stof** [comment] 2021-10-26 17:58
> I expect that `overrideHost` will be `foo`, but instead, I get an exception `The parameter "SITE_HOST_OVERRIDE" must be defined.` and when I change it to `env(SITE_HOST_OVERRIDE)` it's working.
> 
> What is the expected behavior?

The expected behavior is the error here. There is no `SITE_HOST_OVERRIDE` parameter defined in your snippet.

**Comment by yanis-git** [comment] 2024-03-05 12:50
> Thanks for your answer @stof, I added the following line:
> 
> ```
> $container->compile();
> 
> var_dump(getenv('NAME'));
> var_dump($container->getParameter('test'));
> ```
> 
> Now I get the following result:
> 
> ```
> /Volumes/GIT/olvlvl/test-di-env/test.php:15:
> string(7) "madonna"
> /Volumes/GIT/olvlvl/test-di-env/test.php:16:
> string(41) "env_NAME_812dcc3cc5cf425ee641becdc595f9f4"
> ```
> 
> Still no "madonna" is sight :(
> 
> Also, the documentation says nothing about compilation requirement :(

for who have this issue with env not injected.

you should provide true to the container compilation like following

```
$container->compile(resolveEnvPlaceholders: true);
```
