### ISSUE TITLE
[DomCrawler] Unreachable field "#player-4-grade" - because of the dashes?

### ISSUE THREAD

**Issue by bkuhl** [symfony/symfony#15854] opened 2015-09-21 03:25 UTC
I am using Laravel 5's test helpers and am not able to select a form field in my unit test where the id is `player-4-grade`.  

```html
<select id="player-4-grade" name="player[4][grade]"></select>
```
**Stack trace**
```
1) PlayerRegistrationTest::canRegisterWithoutGroup
InvalidArgumentException: Unreachable field "player-4-grade"

/path/to/project/vendor/symfony/dom-crawler/FormFieldRegistry.php:94
/path/to/project/vendor/symfony/dom-crawler/FormFieldRegistry.php:131
/path/to/project/vendor/symfony/dom-crawler/Form.php:76
/path/to/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:961
/path/to/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:941
/path/to/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:928
/path/to/project/tests/phpunit/Guardian/PlayerRegistrationTest.php:142
```

When adding debug code to [`DomCrawler.FormFieldRegistry.get()`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DomCrawler/FormFieldRegistry.php#L82) (debug code seen below) I see the output:

```
false
array:2 [
  0 => "_token"
  1 => "player"
]
```

**Debug code**

```php
    public function &get($name)
    {
        $segments = $this->getSegments($name);
        $target = &$this->fields;
        while ($segments) {
            $path = array_shift($segments);

            if ($path == 'player-4-grade') {
                dd(array_key_exists($path, $target), array_keys($target));
            }

            if (!array_key_exists($path, $target)) {
                throw new \InvalidArgumentException(sprintf('Unreachable field "%s"', $path));
            }
            $target = &$target[$path];
        }

        return $target;
    }
```

## Selecting by name
When trying to select by name I get another error...

```
1) PlayerRegistrationTest::canRegisterWithoutGroup
Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <number "4" at 9> found.

/path/to/vendor/symfony/css-selector/Exception/SyntaxErrorException.php:34
/path/to/vendor/symfony/css-selector/Parser/TokenStream.php:168
/path/to/vendor/symfony/css-selector/Parser/Parser.php:338
/path/to/vendor/symfony/css-selector/Parser/Parser.php:207
/p/ath/to/vendor/symfony/css-selector/Parser/Parser.php:140
/path/to/vendor/symfony/css-selector/Parser/Parser.php:116
/path/to/vendor/symfony/css-selector/Parser/Parser.php:51
/path/to/vendor/symfony/css-selector/XPath/Translator.php:297
/path/to/vendor/symfony/css-selector/XPath/Translator.php:123
/path/to/vendor/symfony/css-selector/CssSelector.php:98
/path/to/vendor/symfony/dom-crawler/Crawler.php:697
/path/to/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:1031
/path/to/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:1011
/path/to/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:994
/path/to/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:903
/path/to/tests/phpunit/Guardian/PlayerRegistrationTest.php:140
```

The only `player` form fields on this page are array POSTS (e.g. - `name="player[X][shirtSize]"`) so it appears the nested naming structure is messing with things.  **Is there a different way that I can attempt to select this field?**

**Comment by stof** [comment] 2015-09-21 08:35
fields are accessed by name in the DomCrawler field registry, not by id. this is why ``player-4-grade`` is not reachable.

Regarding your selection by name, what is the CSS string you are trying to convert to XPath when getting this exception ?

**Comment by bkuhl** [comment] 2015-09-23 02:50
The CSS selector being passed to CssSelector.php:98 is `*#player[1][shirtSize], *[name='player[1][shirtSize]']`

**Comment by alexislefebvre** [comment] 2015-09-23 12:30
Can you please add the full code of the test to see how you select then set the value of the `<select>`?

**Comment by stof** [comment] 2015-09-23 14:13
``*#player[1][shirtSize]`` is an invalid CSS selector. the question is where it is coming from

**Comment by bkuhl** [comment] 2015-09-23 14:18
I expected this was a symfony bug, but it sounds like you're suggesting it's a Laravel issue.  This selector is generated by Laravel's CrawlerTrait:  https://github.com/laravel/framework/blob/b83830a551/src/Illuminate/Foundation/Testing/CrawlerTrait.php#L1044

**Comment by stof** [comment] 2015-09-23 14:22
Well, laravel has the proper escaping in place to avoid generating it wrong: https://github.com/laravel/framework/blob/b83830a551d79310ce03b2b9c835be71bae5f1d0/src/Illuminate/Foundation/Testing/CrawlerTrait.php#L1064
However, this is only included in the code since 21 days: https://github.com/laravel/framework/pull/10128
So they already fixed the bug in Laravel.

**Comment by engoyan** [comment] 2015-09-23 21:39
@stof this might help:

```
Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <number "6" at 11> found.

/home/vagrant/Code/cook/vendor/symfony/css-selector/Exception/SyntaxErrorException.php:34
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/TokenStream.php:168
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/Parser.php:338
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/Parser.php:207
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/Parser.php:140
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/Parser.php:116
/home/vagrant/Code/cook/vendor/symfony/css-selector/Parser/Parser.php:51
/home/vagrant/Code/cook/vendor/symfony/css-selector/XPath/Translator.php:299
/home/vagrant/Code/cook/vendor/symfony/css-selector/XPath/Translator.php:124
```

On ```Translator.php:299``` css selector is ```*#schedule[6][end], *[name='schedule[6][end]']```. I'm not familiar with tokenizer but there might be an issue (```symfony/css-selector/Parser/Parser.php:49```). Or, possibly, down the stream..

**Comment by stof** [comment] 2015-09-24 10:20
@engoyan the issue is that if you have a ``[`` in the id, it must be escaped (see the fix done in Laravel in my previous comment).
In your query, this is looking for an element with a ``schedule`` id and a ``6`` attribute. but such attribute name is invalid (it is not an identifier). an identifier cannot start with a number.

So there is no issue in the CssSelector component, just an invalid input.

**Comment by alexislefebvre** [comment] 2015-09-24 12:19
@engoyan: you have to check that the version of Laravel you use integrates the commit that stof linked. It that's not the case, you'll have to upgrade your installation before retesting.

**Comment by xabbuh** [comment] 2015-09-30 11:20
Closing as this seems to be a Laravel issue that has already been fixed.

@engoyan Feel free to reopen if you disagree and can provide some steps to still reproduce your issue on a Laravel edition that contains the fix.

**Closed by xabbuh** 2015-09-30 11:20 UTC
Labels: CssSelector, DomCrawler
