### ISSUE TITLE
How can I remove proxies field in symfony json ?

### ISSUE THREAD

**Issue by caiaffa** [symfony/symfony#36949] opened 2020-05-24 21:45 UTC
My code:
`public function findAll(): JsonResponse
    {
        $products = $this->productRepository->findAll();
        
        return $this->json((
            new ApiJsonResponse(ApiJsonResponse::TYPE_SUCCESS, $products)
        ));
    }`

return:
`"productType": {
        "id": 1,
        "name": "product type 1",
        "active": true,
        "__initializer__": null,
        "__cloner__": null,
        "__isInitialized__": true
      }`

I'm using sumfony 5 and I wanted to remove it globally

Thanks!

**Comment by Nek-** [comment] 2020-05-24 22:01
Hello,

This non-issue is more related to Doctrine than Symfony. Also Doctrine generates proxies by design. You can change this behavior but it's not trivial.

Please use google to look around how to do it, and StackOverflow to get some help.

Here is just a bug tracker and what you describe it is:
- not a bug
- not related to Symfony

Please close this issue. I hope I helped.

**Comment by caiaffa** [comment] 2020-05-24 22:08
> Hello,
> 
> This non-issue is more related to Doctrine than Symfony. Also Doctrine generates proxies by design. You can change this behavior but it's not trivial.
> 
> Please use google to look around how to do it, and StackOverflow to get some help.
> 
> Here is just a bug tracker and what you describe it is:
> 
> * not a bug
> * not related to Symfony
> 
> Please close this issue. I hope I helped.

@Nek- 

I searched on google but the only answer that was obtained to put the values ​​excluded from the serializer

**Comment by stof** [comment] 2020-05-24 22:58
Well, `$this->json()` is either using the serializer component, in which case this is solved by configuring the serializer to exclude them, or does a simple `json_encode()` on the data, in which case the solution is to implement `JsonSerializable`

**Closed by stof** 2020-05-24 22:58 UTC
