### ISSUE TITLE
[DomCrawler] Terrible perfomance

### ISSUE THREAD

**Issue by icaine** [symfony/symfony#12298] opened 2014-10-23 09:49 UTC
When trying to parse info from some website i discovered that DomCrawler is terribly slow and unoptimized. With a few little changes i improved performance more than 150+ times (11500 ms -> 65 ms). 

The main culprit is
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DomCrawler/Crawler.php#L862
because creation of DOMXPath is damn expensive.

I quick fixed it by (i know its very very dirty)
```
    private function createDOMXPath(\DOMDocument $document, array $prefixes = [])
    {
        static $domxpath;
        if (empty($domxpath)) {
            $domxpath = new \DOMXPath($document);
            foreach ($prefixes as $prefix) {
                $namespace = $this->discoverNamespace($domxpath, $prefix);
                if (null !== $namespace) {
                    $domxpath->registerNamespace($prefix, $namespace);
                }
            }
        }

        return $domxpath;
    }
```

Another performance improvements (cca 200 ms in my environment) can be gained if results from CssSelector::toXPath($selector) at
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DomCrawler/Crawler.php#L675
are cached.

**Comment by ConneXNL** [comment] 2015-01-15 12:46
Came across the same issue. I am waiting 15 minutes to update 500+ doctrine records from a HTML table.

**Comment by ConneXNL** [comment] 2015-03-19 15:30
Any update on this? With the changes I mentioned above, I increased speed from minutes to seconds.

**Comment by javiereguiluz** [comment] 2015-03-19 15:38
@ConneXNL apparently @stof and @jakzal raised some valid concerns that haven't been solved yet.

**Comment by GromNaN** [comment] 2015-03-19 15:54
The DomDocument should be wrapped into an object that also contain the DomXPath.
Something like this : https://github.com/LExpress/Welldom/blob/master/src/Welldom/Document.php#L112

**Comment by jakzal** [comment] 2015-03-19 19:22
@icaine would you mind publishing the html page you're pasting somewhere? I'd love to profile your script.

**Comment by icaine** [comment] 2015-03-19 20:17
@jakzal unfortunatelly i abandoned the project.. But its not hard to simulate similar use case, just find any website with some structural data and hundreds of records (tv program, eshop, etc) and try extract some info..

**Comment by stof** [comment] 2015-03-20 08:56
The hard part is that the Crawler class is currently mutable, allowing to add more content in it. this means it is possible to have nodes belong to multiple documents in the same crawler. This makes any optimisation much harder.
And the fact that it extends SplObjectStorage instead of wrapping it means that the Crawler exposes methods which allow messing with the internal state directly, which makes things even worse.

I see 2 main use cases for the crawler:

- creating it for an HTML (or XML) content
- creating it from an list of nodes coming from an existing crawler (with any of the DOM traversal methods).

The following API for the crawler would make things much simpler.

```php
class Crawler
{
    public function __construct(\DomDocument $document, array $nodes = array())
    {
        $this->document = $document

        // Validate that all DomElement are for this DomDocument and store them in the internal storage
    }

    public static function fromHtml($html, $charset = 'UTF-8')
    {
        $document = //... Load the HTML (see existing code)

        return new self($document, array($document->documentElement));
    }
}
```

Looking at the existing constructor, it may even be possible to preserve BC for most cases if we deprecate the possibility to use nodes from multiple documents (which would make such optimizations much easier)

**Comment by salaman** [comment] 2015-03-21 20:09
I have a huge (~24MB) HTML file of horribly nested tables to parse. Everything was working acceptably during dev runs with much smaller test files, so I assumed the processing time would scale linearly when I eventually fed it the entire file, but it ended up being unacceptably slow.

Using @icaine's edit, the processing time decreased a completely insane amount and actually made it usable.

I profiled both runs with xhprof (using the huge data file but limiting parsing to a few tables, since the slow run would probably take hours):

Code | Function calls | Wall time (s) | CPU time (s) | Memory (b) | Peak memory (b)
------------ | ------------- | ------------- | ------------- | ------------- | -------------
Normal DomCrawler | 53345 | 505.799 | 503.594 | 16,272,720 | 89,225,312
Patched DomCrawler | 52873 | 3.502 | 3.426 | 16,272,992  | 89,225,928
Difference | -472 | -502.296 | -500.167 | 272 | 616

Most of the time is spent in `Symfony\Component\DomCrawler\Crawler::discoverNamespace` on the slow run.

As you can see, for my data, the edit makes my parser run in about 0.7% of the time, which is stellar.

I'd love to see this (at least partially) addressed in master.

**Comment by jakzal** [comment] 2015-03-21 20:20
@salaman I'll be looking into this on Monday. Would you mind sending me the file and crawler queries you used to jakub AT zalas DOT pl? It would save me some time.

Btw, since namespace discovery is not always needed, if it's causing the issue we could make it possible to disable this feature.

**Comment by salaman** [comment] 2015-03-21 20:33
@jakzal Sure thing, I'll clean up the file a bit since it's sort of integrated into a larger parser package and send it over so it can be used by itself.

**Comment by jakzal** [comment] 2015-03-21 23:53
@salaman thanks. It was really helpful.

**Closed** 2015-03-23 07:00 UTC
Labels: DomCrawler

**Comment by ConneXNL** [comment] 2015-04-23 15:00
In what way was this fixed? I still have terrible performance without the changes listed above.

**Comment by jakzal** [comment] 2015-04-23 16:48
@ConneXNL if you provide a script reproducing your issue, I'll be happy to look into it. The current issue was related to a namespace discovery logic.

**Comment by scheb** [comment] 2016-07-24 18:05
Just ran into that issue when iterating over a list of XML nodes and doing a bunch of XPath queries on each list item. Sample document was ~2,5MB.

The filterRelativeXPath() creates a sub-crawler for each XPath query. Then, when the query is executed on the sub-crawler, it has to execute the very slow discoverNamespace() method, because the namespace cache ($namespace attribute of the Crawler class) is not copied over to the sub-crawler. By changing the createSubCrawler() method to this, I was able to boost performance significantly:

```php
private function createSubCrawler($nodes)
{
    $crawler = new static($nodes, $this->uri, $this->baseHref);
    $crawler->namespaces = $this->namespaces; // Added this line

    return $crawler;
}
```

It works for me use-case, but I don't know what implications this could have for other use-cases.

**Comment by jakzal** [comment] 2016-07-24 20:11
@scheb could you please provide the script and the document that exhibit the issue?

**Comment by scheb** [comment] 2016-07-25 08:37
Here's a script to reproduce:

```php
<?php
include __DIR__ . '/vendor/autoload.php';

use Symfony\Component\DomCrawler\Crawler;

$xmlRaw = file_get_contents('http://api.elsevier.com/content/article/PII:S0370269312002560?httpAccept=text/xml');

$crawler = new Crawler();
$crawler->addXmlContent($xmlRaw);
$crawler->registerNamespace("ce", "http://www.elsevier.com/xml/common/dtd");

$nodes = $crawler->filterXPath('//ce:author-group/ce:affiliation');
$nodes->each(function (Crawler $crawler) {
    $startTime = microtime(true);
    $crawler->filterXPath('//ce:textfn')->extract(array('_text'));
    echo microtime(true) - $startTime . " sec\n";

    $startTime = microtime(true);
    $crawler->filterXPath('//ce:label')->extract(array('_text'));
    echo microtime(true) - $startTime . " sec\n";
});
```

**Comment by javiereguiluz** [comment] 2016-07-25 09:05
@scheb I've tested the change that you propose:

```diff
    private function createSubCrawler($nodes)
    {
        $crawler = new static($nodes, $this->uri, $this->baseHref);
        $crawler->isHtml = $this->isHtml;
        $crawler->document = $this->document;
+       $crawler->namespaces = $this->namespaces;

        return $crawler;
    }
```

And the performance improvement is astonishing:

![comparison](https://cloud.githubusercontent.com/assets/73419/17095999/934bc0ce-5257-11e6-9254-f2a3e866bf0f.png)

Now @jakzal and others will evaluate if this change is appropriate. Thanks!

**Comment by stof** [comment] 2016-07-25 09:34
@javiereguiluz the change is totally legitimate. I opened a PR already to apply it.
