### ISSUE TITLE
[Proposal] Create an official ruleset of Symfony2 codestyle for PHP_CodeSniffer

### ISSUE THREAD

**Issue by FractalizeR** [symfony/symfony#13952] opened 2015-03-17 15:25 UTC
Symfony2 became so great, I believe its practices were widely adopted. Symfony code style is widely used today. I think there is a need to create an official ruleset for PHP_CodeSniffer (widely used code style checker tool) for Symfony2.

PHP_CodeSniffer is easily integrated into other tools (like PHPStorm), but using Symfony2 codestyle in it is not so easy. To set it up you need to pull some code style repository with Symfony2 code style, then copy files into your existing installation or use fork of PHPCS in your project (which is not always desired).

There is an issue in [PHP_CodeSniffer] (https://github.com/squizlabs/PHP_CodeSniffer/issues/516#issuecomment-82364356) about this and I think the general trend is for this ruleset to be provided by Symfony team rather than somebody else.

**Comment by TomasVotruba** [comment] 2015-03-17 15:34
:+1:

**Comment by javiereguiluz** [comment] 2015-03-17 15:42
@FractalizeR I like your proposal. However, keep in mind that in the Symfony community, most developers use [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) instead of PHP_CodeSniffer, so I'm not sure if this proposal will attract enough support ... but I wish it does :+1:

**Comment by cordoval** [comment] 2015-03-17 15:43
yeah php-cs-fixer has already a built-in sf configuration by default

**Comment by aik099** [comment] 2015-03-17 16:15
:+1: it's always better to see the error highlighted in PhpStorm, then just witness what phpcs-fixer changed after the fact.

**Comment by FractalizeR** [comment] 2015-03-17 16:46
@javiereguiluz I am not yet a member of Symfony's developer community. I actually use Laravel today. But I dislike Laravel's official coding style and I prefer Symfony's one. 

Also, there is no native support for  PHP CS Fixer inside PHPStorm yet (you can try to make one via something like File Watchers, but it will not be convenient).

So, I think it would be better to create PHPCS ruleset to enable people, not using PHPCSFixer to benefit from Symfony's style.

**Comment by javiereguiluz** [comment] 2015-03-17 16:54
@FractalizeR I agree with you and I wish this gets achieved. Let's wait for someone in the community to offer himself/herself to do this.

**Comment by EmanueleMinotto** [comment] 2015-03-17 17:36
I think it's a great proposal, but the ruleset is really hard to be defined, for example if the `rulesets/naming.xml/ShortVariable` is the predefined value (3) most doctrine entities should be rewritten if them have an `$id` attribute, considering this: should the ruleset be something like [Symfony Best Practices](http://symfony.com/doc/current/best_practices/index.html) (then with common and RAD practices) or something based on best practices?

PHPMD & PHPCS rules: http://edorian.github.io/php-coding-standard-generator/

**Comment by FractalizeR** [comment] 2015-03-17 17:55
@EmanueleMinotto Do you mean PHPMD or PHPCodeSniffer? They are two different tools and I mean PHPCodeSniffer ;)

**Comment by EmanueleMinotto** [comment] 2015-03-17 18:17
@FractalizeR hehe sorry, I added PHPMD but this discussion is only about PHPCS

With only PHPCS the problem is the same, consider these rules for a `\Vendor\DemoBundle\DependencyInjection\Configuration::getConfigTreeBuilder`, how could them be configured?

 * Generic.Files.LineLength
 * Generic.WhiteSpace.ScopeIndent

I'm not fighting against the purpose, I'm just discussing about problems and possible solutions, for example a solution could be the comments `// @codingStandardsIgnoreStart` and `// @codingStandardsIgnoreEnd` but imo isn't a great solution

**Comment by rande** [comment] 2015-03-17 19:21
For information, we are maintaining this repository: https://github.com/ekino/Symfony2-coding-standard

**Comment by FractalizeR** [comment] 2015-03-17 21:02
@rande There are millions of repos with Symfony code standard already on GitHub. And none of them is official ;) And none of them is merged into PHP_CodeSniffer core, which is the sole purpose of this issue.

**Comment by pborreli** [comment] 2015-03-17 21:22
:+1: for iterating on ekino/Symfony2-coding-standard to make it fully compliant then asking @fabpot when it's ready, imo

**Comment by FractalizeR** [comment] 2015-03-18 07:31
@EmanueleMinotto I see no good in php class name spanning several lines. You have `uses` for that. Import class name and your line would not be big. Please note, that Symfony2 coding style currently [inherits](http://symfony.com/doc/current/contributing/code/standards.html) from [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md), which means, that line length limit is 80/120 even now. PHPCS could check for that easily.

**Comment by nicoschoenmaker** [comment] 2015-03-27 08:28
@FractalizeR isn't the deeper problem here that it would have to be merged into the core of PHP_CodeSniffer? A Symfony standard should be under the Symfony organisation, just like the Doctrine bundle is under the doctrine organisation.

Ideally you would have a symfony/code-sniffer package that would require a PHP_CodeSniffer composer [plugin](https://getcomposer.org/doc/articles/plugins.md), and you would include the standard in that way.

(This would make it an issue for PHP_CodeSniffer, though.)

**Comment by aik099** [comment] 2015-03-27 08:40
> @FractalizeR isn't the deeper problem here that it would have to be merged into the core of PHP_CodeSniffer?

@nicoschoenmaker , it won't be merged into PHP_CodeSniffer ever. @gsherwood specifically told (in some other task), that this won't happen because that way he need to ensure that standard is always up to date and running with all the latest changes to PHP_CodeSniffer.

**Comment by fabpot** [comment] 2015-10-05 12:03
Closing as it's not related to symfony/symfony.

**Closed by fabpot** 2015-10-05 12:03 UTC

**Comment by Kwadz** [comment] 2018-01-08 10:24
Where this issue is now followed please?

**Comment by TomasVotruba** [comment] 2018-01-08 10:51
Symfony uses "symfony" set from https://github.com/friendsofphp/php-cs-fixer

**Comment by Kwadz** [comment] 2018-01-08 11:01
@TomasVotruba, I understood the goal of this issue is to be able to see the errors highlighted directly in IDEs like PhpStorm, if I am not wrong only PHP_CodeSniffer allows that.

**Comment by TomasVotruba** [comment] 2018-01-08 14:58
CodeSniffer features are very limited compared to combination with PHP CS Fixer or EasyCodingStandard.

Why do you need to highlight errors that a tool fixes for you?

**Comment by aik099** [comment] 2018-01-08 15:39
> CodeSniffer features are very limited compared to combination with PHP CS Fixer or EasyCodingStandard.

That depends on used ruleset. I personally peffer to write code correctly styled in the 1st place instead of writing it without style and running fixed to fix standard violations.

> Why do you need to highlight errors that a tool fixes for you?

Because PHPStorm highlights errors inline for its own inspections (e.g. calling method with more parameters, then in declaration) and for stuff PHP_CodeSniffer finds as well.

As PhpStorm offers integration with PHP_CodeSniffer and not PHP-CS-Fixer using PHP_CodeSniffer standard is preferred. With PHP-CS-Fixer, if I'm not mistaken, you need to switch to another window to run fixing.

**Comment by TomasVotruba** [comment] 2018-01-08 17:32
For me it's easier to run :

```php
vendor/bin/ecs fix src
```

before commiting, rather than:

- setup PHPStorm, 
- see what it highlights, 
- read caretuflly each message,
- open Sniff classes, when the message it not clear to me,
- fix all of that manually,
- be limited only to PHP_CodeSniffer

And for each project doing the same redundant work. I have better things to do :)

**Comment by aik099** [comment] 2018-01-08 18:54
We're bit off track here 😉 .

The part of showing errors in PhpStorm was purely my interpretation (see https://github.com/symfony/symfony/issues/13952#issuecomment-82439773) of @FractalizeR question in the issue.

That unfortunately mislead @Kwadz in https://github.com/symfony/symfony/issues/13952#issuecomment-355937078 comment into thinking that error highlighting in PhpStorm is all this issue is about.

This issue is about checking (maybe fixing) and not showing errors. In there I agree with @TomasVotruba , that there are CLI tools available other, but that's not PHP_CodeSniffer.

**Comment by TomasVotruba** [comment] 2018-01-08 19:27
@aik099 I was reactig to the question in title + one after issue was closed.

> ...there are CLI tools available other, but that's not PHP_CodeSniffer.

It is PHP_CodeSniffer as well. All 3 of them actually ;)

```bash
vendor/bin/phpcbf # PHP_CodeSniffer fixing bin
vendor/bin/phpcs # PHP CS FIxer
vendor/bin/ecs --fix # EasyCodingStandard
```
