### ISSUE TITLE
[2.7] Some parameters are not loaded

### ISSUE THREAD

**Issue by Azenet** [symfony/symfony#15238] opened 2015-07-08 14:38 UTC
Hi,

I used to have (with Symfony 2.6) parameters in app/config/config.yml in this form :
```
...
parameters:
    my-parameter: 123
```
I was able to access these using `ContainerInterface->getParameter('my-parameter');`, however this now throws an InvalidArgumentException with the message "The parameter "my-parameter" must be defined." starting from Symfony 2.7.
There's no trace of this change in the change log nor in the UPGRADE-2.7.md file, is this a bug or is this new behavior intended ?

Thanks.

**Comment by javiereguiluz** [comment] 2015-07-08 14:50
Does the error remain if you use this other config?

```yaml
# ...
parameters:
   'my-parameter': 123
```

**Comment by Azenet** [comment] 2015-07-08 14:51
@javiereguiluz Yes, the error remains.

**Comment by xabbuh** [comment] 2015-07-08 19:18
@Azenet Could you fork the the Symfony Standard Edition an make the minimum set of needed changes to reproduce your issue?

**Comment by Azenet** [comment] 2015-07-08 21:32
@xabbuh done here: https://github.com/Azenet/symfony-standard/commit/0f6c5d5000c3fc6f8e4739628133bc3ee3a4ffd3

**Comment by xabbuh** [comment] 2015-07-08 21:55
@Azenet Thank you for providing the fork. I can confirm that this does not work with Symfony 2.7. It even does not work with Symfony 2.6.9.

**Comment by xabbuh** [comment] 2015-07-08 22:02
Okay, I had a closer look at this and the "issue" simply is that you define the `parameters` key twice (the first occurrence is on line 8 when the `locale` parameter is defined). This is due to a bug with how the Yaml component handled duplicated keys (in contrary to the specs) which was only merged into the `2.5` branch (see #10902). So I'm going to close here.

**Comment by xabbuh** [comment] 2015-07-08 22:03
by the way, see also https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.5.md#yaml-component

**Closed by xabbuh** 2015-07-08 22:02 UTC

**Comment by Azenet** [comment] 2015-07-08 22:15
@xabbuh Thanks, I missed this change.
