### ISSUE TITLE
You have requested a non-existent service "debug.error_handler_configurator".

### ISSUE THREAD

**Issue by TheNerka** [symfony/symfony#50504] opened 2023-05-31 12:18 UTC
### Symfony version(s) affected

6.3.0

### Description

after upgrade symfony from 6.2 to 6.3 calls cache clear got error:

You have requested a non-existent service "debug.error_handler_configurator".

### How to reproduce

upgrade from 6.2 to 6.3

**Comment by stloyd** [comment] 2023-05-31 12:20
Duplicate of https://github.com/symfony/symfony/issues/50491

**Comment by xabbuh** [comment] 2023-05-31 12:24
Does #50498 fix this?

**Closed as completed** 2023-05-31 12:29 UTC
Labels: Bug, Status: Needs Review

**Comment by OleksiiBulba** [comment] 2023-06-14 18:38
Hello! Is there any possible workaround to fix this error message before the fix will be released?

**Comment by stof** [comment] 2023-06-14 18:42
@OleksiiBulba you can use the dev version of the package.

Alternatively, you could remove the old cache (the one generated by the old version of Symfony) with `rm -rf var/cache/prod/*`

**Comment by OleksiiBulba** [comment] 2023-06-14 20:13
Thanks @stof, updating to the dev package and downgrading back to release helped (I did it before seeing your answer) :)
