### ISSUE TITLE
[AssetMapper] compile command failing after update

### ISSUE THREAD

**Issue by BeyerJC** [symfony/symfony#54099] opened 2024-02-28 12:27 UTC
### Symfony version(s) affected

6.4.4

### Description

`php bin/console asset-map:compile` is failing after updating the version to 6.4.4.  It executes successfully on version 6.4.3 without any code changes.

The error is
```
In JavaScriptImportPathCompiler.php line 119:
                                                                                                                                      
  Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned  
                                                                                                                                      
```

### How to reproduce

I will try to create a reproducer once i found the file causing the problem.

### Additional Context

I have some assets that arent available anymore and throwing warnings on compile. I will check if this is related to the problem and report back.

`{"message":"Unable to find asset \"../images/bg-pattern.png\" referenced in`

**Comment by xabbuh** [comment] 2024-02-28 12:41
duplicate of #54078

**Closed as not planned by xabbuh** 2024-02-28 12:41 UTC
Labels: Bug, Status: Needs Review, AssetMapper
