### ISSUE TITLE
Extreme performance drop when upgrading to 2.6.8

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#14771] opened 2015-05-28 12:25 UTC
Hi,

After our latest vendor upgrade we have experienced a very long execution time on our CI server. After digging into it I found the following:

Symfony 2.6.5, Win 7 x64, dev mode:
```
Total time 	755 ms
Initialization time 	480 ms
```

```
composer update symfony/symfony

//...

- Removing symfony/symfony (v2.6.5)
- Installing symfony/symfony (v2.6.8)
```
(no other vendors were updated)

Symfony 2.6.8, Win 7 x64, dev mode:
```
Total time     9622 ms
Initialization time     9405 ms
```

- problem present on linux as well
- php error log empty
- dev log seems normal
- prod mode is unaffected

Any help would be much appreciated.

**Comment by jakzal** [comment] 2015-05-28 16:18
Closing as a duplicate of #14768

**Closed by jakzal** 2015-05-28 16:18 UTC
