### ISSUE TITLE
FormError->serialize throws exception "Serialization of 'SimpleXMLElement' is not allowed"

### ISSUE THREAD

**Issue by Karthons** [symfony/symfony#24537] opened 2017-10-12 14:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

When I want to serialize a formError, an exception is thrown: "Serialization of 'SimpleXMLElement' is not allowed".
 The cause seems to be th ein $this->cause.

Steps to reproduce:
* Create a form
* Catch form errors
* Try to serialize an object of type Symfony\Component\Form\FormError

**Comment by alexmarucci** [comment] 2017-10-28 19:59
Thank you @Karthons for creating this bug report!

I just created a fresh 3.3.10 project and I have followed the steps in your description above. 
When trying to call the serialize function of the FormError's object I have got the same exception.

I reproduced the bug in the "feature/form_serialization_bug" branch of https://github.com/alexmarucci/symfony-standard/

Status: Reviewed

**Comment by xabbuh** [comment] 2017-11-02 14:33
One possible solution could be to throw an exception in the `FormError` constructor if `$cause` is not serialisable.

**Comment by ogizanagi** [comment] 2017-11-02 15:34
We store the violation as the cause, which is not serializable, so this cannot be a solution.
The issue is that this very same constraint has the form instance as `$root`, which itself has a reference to the `ValidationListener` -> `Validator` -> `LazyLoadingMetadataFactory` -> `XmlFileLoader` (IIRC). Last one holds a `\SimpleXMLElement[]|null $classes` property. 

Not sure what would be the proper solution here appart from ignoring the cause if it's not serializable itself.

**Comment by alexmarucci** [comment] 2017-11-02 15:49
How about make violation implement serializable and ignore the $root parameter when serialize / unserialize ?

**Comment by alexmarucci** [comment] 2017-11-02 20:43
Also if I try to get rid of the $cause and when I try to unserialize I've got an exception. 
(" Warning: Class __PHP_Incomplete_Class has no unserializer ").
So I have to set allowed_classes => true in order to make it work properly. I think that's because $cause is a Violation class;

Regarding the Implementation of the Serializable in the ConstraintViolation and ignoring the $root parameter, that's fix the problem, Although when unserialize the FormError $cause is an instance of ConstraintViolation but $root is null. That's might be a problem.

**Comment by Simperfit** [comment] 2017-12-05 06:16
@alexmarucci Do you want to provide a PR with what @ogizanagi said ?

**Comment by alexmarucci** [comment] 2017-12-05 16:55
@Simperfit Affermative. I will do it later on.

**Comment by nicolas-grekas** [comment] 2018-11-24 16:56
I'm closing here as won't fix: serializing is not a primary use case of the FormError class. As identified in ##25386, you could use either Serializer or VarDumper to serialize FormError instances if you need to.

**Closed by nicolas-grekas** 2018-11-24 16:56 UTC
Labels: Bug, Form, Status: Reviewed
