### ISSUE TITLE
YAML parser: No Escaping of single quotes before newline?

### ISSUE THREAD

**Issue by dbankmann** [symfony/symfony#25379] opened 2017-12-07 15:53 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  |  dcf3a9dfac146a0e10757a91de0b541fcd79de4f

Hi, with the following yaml file
```
key:
    fields:
        title: 'bla. Users''
            Guide'
```
I get the  Malformed inline YAML string exception. The file should be valid yaml though.

**Comment by Simperfit** [comment] 2017-12-08 10:07
I can reproduce this, @dbacc Do you want to provide a PR to fix this behaviour ?

**Comment by xabbuh** [comment] 2017-12-08 10:17
I suggest to not invent any time here. I have a pending patch for #25239 locally which will probably fix this issue too.

**Comment by Simperfit** [comment] 2017-12-08 10:18
Ok @xabbuh thanks ;)

**Comment by Simperfit** [comment] 2019-04-29 06:49
@xabbuh can we close this ?

**Comment by xabbuh** [comment] 2019-04-29 07:39
@Simperfit It would still be good to have this fixed (and if it were by only throwing a more meaningful error when we detect a quoted string that spans multiple lines).

**Comment by Simperfit** [comment] 2019-04-29 17:26
I've done the error since I do not know how to parse this to make it work, maybe this could be a good thing to do in a other hackathon with multiple people ? (I think to do it I need that someone explain me how it works entirely :p).

**Comment by xabbuh** [comment] 2019-09-21 10:00
Can you confirm that #33658 will solve this issue?

**Closed** 2019-09-23 14:35 UTC
Labels: Bug, Status: Needs Review, Yaml
