### ISSUE TITLE
Problème symfony of session "hasBeenStarted"

### ISSUE THREAD

**Issue by crownbackend** [symfony/symfony#27767] opened 2018-06-29 08:21 UTC
Symfony 4.1.0 

Hello when I deploy my symfony application on my production server it does not work it shows me an error that is the following :

`Attempted to call an undefined method named "hasBeenStarted" of class "Symfony\Component\HttpFoundation\Session\Session".`

Please can you help me to find a solution I must make the project today
I am under symfony 7.2.7
cordially

**Comment by nicolas-grekas** [comment] 2018-06-29 08:22
Thanks for the report, I'm closing as duplicate of #27726, see there for reasons why.

**Closed by nicolas-grekas** 2018-06-29 08:22 UTC
