### ISSUE TITLE
[form] error when submitting empty value in for using model choice list

### ISSUE THREAD

**Issue by piogrek** [symfony/symfony#14583] opened 2015-05-07 22:51 UTC
I think that's happening only on propel + postgres after @webmozart removed empty/null checks from ChoiceToValueTransformer in https://github.com/symfony/symfony/commit/1d89922782922fe3bcacb09f91e8c3c992d29d3f

ModelChoiceList->getChoicesForValues allows to create Propel query with empty string values which are not accepted, so I'm getting:
```
Unable to execute SELECT statement [SELECT (...) FROM twilio_number WHERE twilio_number.id IN (:p1)] [wrapped: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""]
```

the code below (for propel bridge) seems to do the trick, but I'm not sure if I can create PR for the Propel1Bridge repository. Will appreciate any help.

```
class ModelChoiceList extends ObjectChoiceList

    public function getChoicesForValues(array $values)
    {
        if (empty($values) || empty($first = reset($values))) {
            return array();
        }
```

**Comment by Tobion** [comment] 2015-05-08 00:28
Fixed in #14465 I guess.

**Comment by piogrek** [comment] 2015-05-08 07:07
It was fixed partially. but in our case exception happens in ModelChoiceList , before the null/empty check in ChoiceToValueTransformer. 

still not fixed, but I can't re-open this ticket now

**Comment by mbartok** [comment] 2015-05-10 12:17
Same error after submitting optional entity form field type with empty_value with doctrine on Symfony 2.7 (e60f715). Related issues are #14393 and #14465, but non of fixes seems to fix this issue.

Field definition:

```php
$builder->add('dealer', 'entity', array(
    'label' => 'useraccount.label.dealer',
    'class' => 'MyAppBundle:Subject',
    'choice_label' => 'label',
    'empty_value' => '',
    'multiple' => false,
    'required' => false
));
```

After submitting empty value i get this error:

>SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""

It seems like Symfony is trying to find Subject entity using empty string as id for dealer field:

>DBALException: An exception occurred while executing 'SELECT ... FROM subject s0_ WHERE s0_.id IN (?)' with params [""]:

**Comment by piogrek** [comment] 2015-05-10 12:29
Seems to be the same problem, but fix needs to be done either in ChoiceToValueTransformer (for both model and entity lists) or separately in bridge ChoiceList classes

**Comment by madmis** [comment] 2015-05-29 20:25
+1
ChoiceToValueTransformer
Form
```
$builder->add('country', 'entity', [
            'class' => 'AppBundle\Entity\Country',
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('c')
                    ->orderBy('c.name', 'ASC');
            },
        ]);
```
If in this case i try save empty value, i have error
```
An exception occurred while executing 'SELECT c0_.id AS id0, c0_.iso_code AS iso_code1, c0_.name AS name2, c0_.slug AS slug3 FROM country c0_ WHERE c0_.id IN (?) ORDER BY c0_.name ASC' with params [""]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
```

If set  *'empty_data' => 0,*
```
$builder->add('country', 'entity', [
            'class' => 'AppBundle\Entity\Country',
            'empty_data' => 0,
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('c')
                    ->orderBy('c.name', 'ASC');
            },
        ]);
```
worked without errors

Symfony version 2.7.0-DEV

**Comment by tmeliberty** [comment] 2015-06-01 08:51
@madmis by trying this workaround I get an TransformationFailureException "The choice "0" does not exist or is not unique" and it break my form validation

Symfony 2.7.0 LTS

**Comment by althaus** [comment] 2015-06-01 14:19
This happens for me with the  `placeholder` option:

```
$builder->add('category', null, array(
            'label' => _('Category'),
            'order_by' => 'title',
            'placeholder' => _('none'),
        ));
```

**Comment by webmozart** [comment] 2015-06-11 15:53
This bug is fixed for Doctrine in #14950.

**Comment by althaus** [comment] 2015-06-12 07:34
That fix solves my issue... although it feels somehow hacky to just filter any non-integers from the values. Shouldn't it be fixed somehow related to `empty_data` as this is the cause of the empty string?

**Closed** 2015-06-12 15:09 UTC
Labels: BC Break, Form

**Comment by garak** [comment] 2016-02-03 14:21
I just found this issue since I'm getting exactly this problem, but with `guid` type. I think that `guid` should be added to the array of types to check.
So, instead of `array('integer', 'bigint', 'smallint')`, it should be `array('integer', 'bigint', 'smallint', 'guid')`

**Comment by maryo** [comment] 2017-08-03 22:50
I have almost the same problem. I am using ramsey/uuid-doctrine package with Postgres. It uses a different doctrine type - https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidType.php named `uuid`, not `guid`. Doctrine maps it to `guid` Postgres type OFC but `$metadata->getTypeOfField($identifier)` returns `uuid`. A solution would be to check the native types instead.

`$databasePlatform = $qb->getEntityManager()->getConnection()->getDatabasePlatform();
        $identifierMapping = $metadata->getFieldMapping($identifier);
        Type::getType($metadata->getTypeOfField($identifier))->getSQLDeclaration($identifierMapping, $databasePlatform) === $databasePlatform->getGuidTypeDeclarationSQL($identifierMapping)`

That's not very nice but it works.

@webmozart 
But actually why can't we filter out empty strings in all cases? Or at least skip `array('')` which covers entity type when both multiple and required is set to false (the values is an empty array in case when multiple is set true)? Or can we? Is there a case where empty string is not an empty choice?
