### ISSUE TITLE
Email Validator... again

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#21531] opened 2017-02-04 16:24 UTC
Recently, I stumbled upon this article about validating emails:

https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

We know that validating emails is a complex topic and depending on a lot of factors, people want something stricter than just checking for `@` or something simpler than an email being "right".

Lots of issues have being creating along the years here about this issue (I wanted to list them all here for reference, but there are just too many of them :)).

What's interesting I think (and I don't remember it being mentioned before but I might be wrong), is how HTML5 actually validates emails:

https://www.w3.org/TR/html5/forms.html#valid-e-mail-address

Would it be a good middle ground that we could offer as a third alternative to our users?

**Comment by lyrixx** [comment] 2017-02-04 16:27
(sorry, miss click on my mobile phone)

**Comment by nicolas-grekas** [comment] 2017-02-04 16:36
That was my first "contrib" to SF ever ;)
https://github.com/symfony/symfony/issues/1581#issuecomment-23407467

See also #18177

**Comment by javiereguiluz** [comment] 2017-02-04 18:56
I'd say is a duplicate of #18177 😊

**Comment by iltar** [comment] 2017-02-05 15:27
Basically you want the most bogus and obvious mistakes filtered, values that possibly can't ever be an email address or are common typos. Sure you can have fancy quoted values in your email, but that is more often a typo than a real email.

**Comment by robfrawley** [comment] 2017-02-05 17:19
@iltar I disagree. **Over restricting** is _more_ of a concern than **under restricting**. Under restricting may cause bad input, _but it never impacts users_. Over restricting may remove bad input, _but it always impacts users_. 

For example, my name is "Robert Frawley 2nd". I can't count the number of times, even on government websites where I am legally required to provide my full legal name, that no suffix field is provided and it doesn't accept "Frawley 2nd" as my last name. Or, a suffix field is provided and it only accepts "||", "III", or other roman numerals, and not "2nd". This is an example of programmers over restricting fields.

**Comment by iltar** [comment] 2017-02-05 17:43
@robfrawley "Under restricting may cause bad input, but it never impacts users" Until someone changes his email to `@*..com` and thinks it's updated

**Comment by robfrawley** [comment] 2017-02-05 17:46
@iltar Is someone thinks that's their e-mail, they have more pressing issues. ;-)

**Comment by iltar** [comment] 2017-02-05 17:53
@robfrawley They don't think that's their email, it's simply a typo. You can call them "dumb" and what not for making those mistakes, but that's because nothing is telling them it's wrong. I see this come by quite often and is a real issue in our customer portal. We use a background queue system to send out emails so it's not truly validated till seconds or minutes (depending on queue size) till we get an error in our system.

That's why I need a validator that tells the customer "you made a typo, fix it" one way or another.

**Comment by robfrawley** [comment] 2017-02-05 17:56
I was making a light-hearted joke, not calling anyone "dumb". The issue is, _typos_ don't always translate to _mistakes_. The default metric for e-mail validation should be "validity" and not "did someone make a typo", IMHO.

**Comment by iltar** [comment] 2017-02-05 18:37
And what I'm pointing at, is that often enough a user fills in `foo@bar..com` or makes a stupid typo and does `foo@@bar.com`. It happens...

**Comment by LordWeedlle** [comment] 2017-03-23 12:31
@iltar anyway `foo@@bar.com` passes SF2 basic regex validation `i@am@not.an.address` also does.

Just see there: http://sandbox.onlinephpfunctions.com/code/fba5c99b28216f43dfc854d238c510684e9ee377

I know it would be pretty hard to make a regex perfectly matching only valid mail but there we just accept wrong mails so we should do something to improve it imo.

**Comment by Vinorcola** [comment] 2017-05-10 13:29
I think the best validation would be the one that doesn't make your e-mail sender throw an exception (or crash). The only thing you don't want is your server returning 500 because of bad input. If you want stricter validation, this become business logic linked to you application.

So ideally, the validation should depend on the library that actually send the e-mails. For example, if the project use SwiftMailer, then the validator should use the validation function of SwiftMailer; idem for PHPMailer, etc.

I don't know if this can be done anyway. It would imply that e-mail libraries implement a standard interface for that purpose...

It doesn't matter if `foo@@bar.com` or `i@am@not.an.address` pass validation. Your application should send an e-mail to validate the e-mail adddress. Furthemore, do you consider `some.one@somewhe.re` a valid address? Some would say it is valid since you can create a such e-mail address. But is this address really used right now? Can you consider it valid if it is not used?

**Closed** 2017-12-11 20:06 UTC
Labels: Validator
