### ISSUE TITLE
Syntax error in vendor/symfony/routing/Matcher/Dumper/PhpMatcherTrait.php:87

### ISSUE THREAD

**Issue by sjadema** [symfony/symfony#29804] opened 2019-01-06 19:40 UTC
**Symfony version(s) affected**: 4.2.2

**Description**  
There is an empty place between 2 `,`-s. The error occurs in `$hasTrailingSlash, , $condition`. This worked for me in `4.2.1` and there is a change 20 days ago. Something might went wrong porting the commits.

When i remove the `, ,` part, it works again.

**How to reproduce**  
Don't know exactly, for me it happened when i tried to access a route.

**Possible Solution**  
Remove the `, ,` part.

**Additional context**  
Since a screenshot would contain sensitive information, here is the stack trace;

```
ErrorException:
Notice: Undefined offset: 6

  at vendor/symfony/routing/Matcher/Dumper/PhpMatcherTrait.php:87
  at srcApp_KernelDevDebugContainerUrlMatcher->doMatch('/user/', array(), array())
     (vendor/symfony/routing/Matcher/Dumper/PhpMatcherTrait.php:35)
  at srcApp_KernelDevDebugContainerUrlMatcher->match('/user/')
     (vendor/symfony/routing/Matcher/UrlMatcher.php:107)
  at Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(object(Request))
     (vendor/symfony/routing/Router.php:262)
  at Symfony\Component\Routing\Router->matchRequest(object(Request))
     (vendor/symfony/http-kernel/EventListener/RouterListener.php:115)
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:111)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(EventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:212)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:44)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:145)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
     (vendor/symfony/http-kernel/HttpKernel.php:126)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

**Comment by gulaandrij** [comment] 2019-01-07 09:23
same for me

**Comment by xabbuh** [comment] 2019-01-07 10:17
Any chance one of you can create an example application that allows to reproduce the issue?

**Comment by nicolas-grekas** [comment] 2019-01-07 10:19
Does the issue persist if you clear the cache? (eg `rm -rf var/cache`)

**Comment by gulaandrij** [comment] 2019-01-07 10:21
> Does the issue persist if you clear the cache? (eg `rm -rf var/cache`)

no, after remove cache folder - all fine

**Comment by wallish** [comment] 2019-01-07 11:03
I got the same issue and it worked after removing var/cache

**Comment by sjadema** [comment] 2019-01-07 21:06
> Does the issue persist if you clear the cache? (eg `rm -rf var/cache`)

This fixed my problem as well. Strange, i tried clearing the cache multiple times using the `cache:clear` command. Maybe that failed as well because of this. I still think it's an issue though.

**Comment by QuentinCurtet** [comment] 2019-01-08 09:06
Same for me, but removing the cache folder doesn't fix this.
Th problem appears when i update the symfony version from 4.2.1 to 4.2.2

**Comment by valeriu-a** [comment] 2019-01-08 16:30
Same here. Fixed by removing one comma between `$hasTrailingSlash, , $condition` and cleared cache using the Symfony console.

**Comment by spipu** [comment] 2019-01-09 08:06
Hi,

The pb is that between 4.2.1 and 4.2.2, the cache of the static routes has change, from 5 to 6 values per definition.
If you upgrade to 4.2.2 and if you do not clean your caches, you will have an error.

never forget to clean your caches after upgrading your app ;)

**Comment by xabbuh** [comment] 2019-01-09 08:13
closing here as the solution seems to be to remove the cache

**Closed by xabbuh** 2019-01-09 08:13 UTC
Labels: Bug, Routing, Status: Waiting feedback

**Comment by spipu** [comment] 2019-01-09 08:17
warning: removing your var/cache folder is not enough if you store your cache in another place, like redis. Do not forget to clean all your cache storages ;)
