### ISSUE TITLE
Error: Nesting level too deep - recursive dependency? on array_unique function

### ISSUE THREAD

**Issue by redjanym** [symfony/symfony#18174] opened 2016-03-15 11:50 UTC
Hello, i just upgraded from Symfony 2.5 to Symfony 2.7 and i'm having this issue. On:
```php
$tags = new ArrayCollection(
       array_unique(array_merge($interests->toArray(), $skills->toArray()))
);
```
i get the error **Error: Nesting level too deep - recursive dependency?**  every time i call the array_unique function for removing duplicates out of an array of objects.
I changed the xdebug.max_nesting_level from 100 to 2000, restarted the services and also disabled xdebug but i still get the same error. 

Any idea? 
Thanks

**Comment by javiereguiluz** [comment] 2016-03-15 11:58
@redjanym thanks for reporting this issue.

In order to help you, we'll need more information about the error. Ideally, you could fork the Symfony Standard Edition, add the minimum amount of code to reproduce this issue and then share the link with us.

**Comment by redjanym** [comment] 2016-03-15 13:07
Thank you @javiereguiluz for replay. I will do it asap.

**Comment by javiereguiluz** [comment] 2016-04-01 07:39
@redjanym any news about this? Did you finally manage to fix this? Thanks!

**Comment by xabbuh** [comment] 2016-04-01 08:00
Without further information this doesn't look like an issue in Symfony, but rather seems related to the object graph of your domain objects/entities.

**Comment by redjanym** [comment] 2016-04-01 08:13
Sorry for the delay but i was doing several tests. I am using Gedmo Translatable behavior with Personal Translation Table and i discovered that if i set the Locale value to one different from EN(where Gedmo goes to select the translated value) i get the Error of Nesting level too deep but i don't have this problem with Locale = EN(the default one).

**Comment by javiereguiluz** [comment] 2016-04-01 08:17
@redjanym thanks for the info. I think we can close this issue then because it doesn't look like a Symfony bug. Please open an issue in the https://github.com/Atlantic18/DoctrineExtensions repository and see if they can fix it. Thank you!

**Closed by javiereguiluz** 2016-04-01 08:17 UTC
