### ISSUE TITLE
[Bug] Property "domain" does not exist in class "App\Entity\MyEntity"

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#31873] opened 2019-06-05 13:56 UTC
**Symfony version(s) affected**: 4.3.0

**Description**  
In one of my forms I receive this error:

> Property "domain" does not exist in class "App\Entity\MyEntity"

Obviously it doesn't exist as the property is actually `$domains`.

So I have a method `addDomain` and a method `removeDomain`.

The problem is caused by the validation `auto_mapping`: if I disable it, the problem disappears

```yaml
framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

```

**Comment by xabbuh** [comment] 2019-06-05 14:08
This looks like a duplicate of #31796. So I am going to close here. Thank you for understanding.

**Closed** 2019-06-05 14:08 UTC
Labels: Bug, DoctrineBridge, Status: Needs Review
