### ISSUE TITLE
[Form] problem if child name is "parent"

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#22567] opened 2017-04-28 08:19 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes

if there is child with name parent and I want to know if FormView has parent FormView, then it is impossible to find it

FormView should have new method isParent

**Comment by ro0NL** [comment] 2017-04-28 10:29
Related to #19492, duplicates #18882

**Comment by javiereguiluz** [comment] 2017-04-28 14:45
@poolerMF thanks for reporting this issue ... but we must close it because it's a duplicate of #18882.

**Closed by javiereguiluz** 2017-04-28 14:45 UTC
