### ISSUE TITLE
HttpFoundation's Response::isNotModified(..) has misleading name

### ISSUE THREAD

**Issue by heidemn** [symfony/symfony#13678] opened 2015-02-13 08:41 UTC
The function internally calls setNotModified() if a 304 response can be sent.
But from the function name, I would expect a getter without side-effects, and I would expect to use it like this:

```php
if($response->isNotModified($request))
    $response->setNotModified();
```

Maybe you could change this behavior in the next major release? (In this case, renaming the isNotModified function would be useful, otherwise this would be a "silent" compatibility break.)

**Comment by jeremyFreeAgent** [comment] 2015-02-13 18:08
Even if `isNotModified` returns a value, it is not a getter. The aim of that method is to validate that the request cache header match the response cache header and update the response (304 and no content) if needed.

The common use case is:
```
if ($response->isNotModified($request)) {
    return $response;
}
```

Perhaps the name `isNotModified` is questionable but the behaviour of the function help you to not set yourself the code to 304 and the content to null.

See more info here : http://symfony.com/doc/current/book/http_cache.html

**Comment by heidemn** [comment] 2015-02-13 18:23
Thanks for your response.
Yes I know what the function does, and it works well. I just thought the name is misleading and could be changed in the next major version.

**Comment by iltar** [comment] 2015-02-14 12:20
Too be honest, a negation in an 'isser' check is confusing. I'm sure it has a use-case, but `isModified` looks better. I also agree with @heidemn regarding the side effect but I have too little knowledge of this part to actually propose a different solution.

**Comment by stof** [comment] 2015-08-01 20:05
@iltar the issue is that it is not a isser

**Comment by javiereguiluz** [comment] 2016-02-13 15:18
Closing it because this proposal didn't receive enough support from the community or the Symfony Core team. In any case, thanks @heidemn for proposing a way to improve Symfony.

**Closed by javiereguiluz** 2016-02-13 15:18 UTC
Labels: Enhancement, HttpFoundation
