### ISSUE TITLE
Problem when installing symfony webapp

### ISSUE THREAD

**Issue by cosminsandu** [symfony/symfony#54144] opened 2024-03-04 10:51 UTC
### Symfony version(s) affected

6.4.*

### Description

When I try to install symfony 
> symfony new my_project_directory --version="6.4.*" --webapp

i get the following error :

Script importmap:require returned with error code 1
!!
!!  In ErrorChunk.php line 56:
!!
!!    SSL certificate problem: certificate has expired for "https://data.jsdelivr.com/v1/packages/npm/@hotwired/stimulus/resolved?specifier=%5E3.0.0".
!!
!!
!!  In CurlResponse.php line 315:
!!
!!    SSL certificate problem: certificate has expired for "https://data.jsdelivr.com/v1/packages/npm/@hotwired/stimulus/resolved?specifier=%5E3.0.0".
!!
![image](https://github.com/symfony/symfony/assets/3448525/fa4b57ab-d6f0-4626-94c1-1793f5be7eb8)

### How to reproduce

just run:
> symfony new my_project_directory --version="6.4.*" --webapp
or 
> composer create-project symfony/skeleton:"6.4.*" my_project_directory
> cd my_project_directory
> composer require webapp

### Additional Context

OS: windows but I don't think is related to Windows settings!

**Comment by derrabus** [comment] 2024-03-04 10:56
I can't reproduce this issue. Moving to support.

**Closed as completed** 2024-03-04 10:56 UTC
Labels: Bug, Status: Needs Review
