### ISSUE TITLE
[Serializer] Can't deserialize array of objects with composer install --no-dev

### ISSUE THREAD

**Issue by Sajito** [symfony/symfony#39356] opened 2020-12-07 08:46 UTC
**Symfony version(s) affected**: 5.1.9

**Description**  
I don't know how to describe this bug without code, so here only the tl;dr. The results of the symfony serializer differ between `composer install` and `composer install --no-dev`.

**How to reproduce**  
Consider the following code:

```php
class Entry 
{
  public DateTimeInterface $dateTime;
}

class EntryData
{
  /**
   * @var Entry[]
   */
  public array $entries;
}

$entryDataJson = '{"entries": [ { "dateTime": "2020-12-07T06:30:14.666Z" } ] }';

$result = $serializer->deserialize($entryDataJson, EntryData::class, 'json');
```

When having everything installed running `composer install` then a var_dump on $result will look like this:

```
object(App\Model\EntryData)[685]
  public array 'entries' => 
    array (size=1)
      0 => 
        object(App\Model\Entry)[719]
          public DateTimeInterface 'dateTime' => 
            object(DateTimeImmutable)[721]
              ...
```

Now run `composer install --no-dev` and run the code again. The result will now look like this:
```
object(App\Model\EntryData)[685]
  public array 'entries' => 
    array (size=1)
      0 => 
        array (size=1)
          'dateTime' => string '2020-12-07T06:30:14.666Z' (length=24)
```

As you can see using the Serializer with `composer install` will correctly deserialize the array of `Entry`-objects. When using `composer install --no-dev` you'll get a simple key-value based array instead. That is because in the symfony serializer the package `phpdocumentor/reflection-docblock` is listed in `require-dev`, not in `require`. That leads to the PhpDocExtrator not being used with `--no-dev`.
There is no Exception or anything, because in the `FrameworkExtension` in `registerPropertyInfoConfiguration` the PhpDocExtrator is simply not registered, if the `phpDocumentor\Reflection\DocBlockFactoryInterface` doesn't exist.

**Possible Solution**  
Either move `phpdocumentor/reflection-docblock` from `require-dev` to `require` in composer.json. Or throw an exception (or at least a warning) if it's not installed along the symfony serializer.
IMO the dependency should be moved to `require`, because it actually affects the results.

**Comment by Nyholm** [comment] 2020-12-07 12:01
Hey. 

Thank you. 
It seams like the serializer is being built with different normalizers depending on if you use dev environments or not. 
Could you double check how you create the `$serializer` object?

**Comment by Sajito** [comment] 2020-12-07 12:40
Hey.
The `$serializer` object is coming from dependency injection, not created by myself.
I was going to provide a reproducer and during that process I found out what is leading to my problem.

In my project `vimeo/psalm` is used and required in `require-dev`. `vimeo/psalm` has a dependency which then again has a dependency on `phpdocumentor/reflection-docblock`, leading to that package being present. Logically when using `composer install --no-dev` both packages are not present.

Having the `phpdocumentor/reflection-docblock` package present automatically and silently enables the PhpDocExtrator. While it's cool to have things just working, when everything needed is present, this feels kind of wrong.

**Comment by Nyholm** [comment] 2020-12-07 12:48
> The $serializer object is coming from dependency injection, not created by myself.

Yes, I figured. But it is still created. =)

> I was going to provide a reproducer and during that process I found out what is leading to my problem.

Awesome. 

Tip: It might be easier for you to create a reproducer if you look on your two serializers and see what normalizers are defined.

**Comment by Sajito** [comment] 2020-12-07 13:02
Here is the reproducer: https://github.com/Sajito/symfony_issue_39356
I made a commit for every change I made with the "initial commit" representing the bare "composer create-project" files.

Run `composer install` and call the project on `/`. You'll see the data deserialized into it's correct objects. Now run `composer install --no-dev`. Then you'll see the array is not deserialized into it's objects anymore.

There is no changed config, this is only triggered by the presence of `phpdocumentor/reflection-docblock`.

**Comment by Haehnchen** [comment] 2020-12-08 13:07
we had the same issue today. resolved by adding https://packagist.org/packages/symfony/serializer-pack -> `composer require symfony/serializer-pack` because its including `reflection-docblock`

```
    "symfony/serializer": "^4.4",
+ "symfony/serializer-pack": "^1.0"
```

I have no idea how to improve this to give more hints about this silent dependency, but personally i was looking inside:

- Suggest: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Serializer/composer.json#L50 (no hint; also on the other suggestion)
- Logging

**Closed as completed** 2021-02-25 16:13 UTC
Labels: Serializer, Bug, Status: Needs Review, Status: Waiting feedback
