### ISSUE TITLE
Too many Routes ?

### ISSUE THREAD

**Issue by AntoineLemaire** [symfony/symfony#16343] opened 2015-10-26 08:54 UTC
Is there a limit with the number of routes we can create ?

My application is using [JMSI18nRoutingBundle](https://github.com/schmittjoh/JMSI18nRoutingBundle), and we have more than 30 locales. 

JMS create in `app/cache/prod/appProdUrlGenerator.php` all routes for each locales in `$declaredRoutes`

I opened a ticket an issue on JMSI18nRoutingBundle ([link](https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/171)), but it seems the issue is the same in symfony without JMSI18nRoutingBundle.

I just try to create a basic project, with 20 controllers, and foreach of them, on function with 2000 routes.

```
    /**
     * @Route("/1", name="homepage1")
     * @Route("/2", name="homepage2")
     * @Route("/3", name="homepage3")
    [...]
     * @Route("/2000", name="homepage2000")
     */
    public function indexAction(Request $request)
    {
        echo $this->generateUrl('homepage1');
        exit;
    }
```

When number of routes approaches 32 760, `echo $this->generateUrl('homepage1');` is failing :

```
Unable to generate a URL for the named route "homepage1" as such route does not exist.
```

**Comment by Tobion** [comment] 2015-10-26 10:15
Please provide a fork of symfony-standard that reproduces the problem

**Comment by AntoineLemaire** [comment] 2015-10-26 10:45
As asked : https://github.com/AntoineLemaire/symfony-standard/commits/2.8

![Image of Issue]
(http://i.imgur.com/1W36BtE.png)

**Comment by jelte** [comment] 2015-10-30 00:21
Just checked this a bit, and it seems weird to say the least.
when you check appDevUrlGenerator.php and `dump` the `self::$declaredRoutes` you only got 7265 routes in there.
Seems you're hitting some limit in php arrays, when I split the `self::$declaredRoutes` up into blocks of 5000 it works. 

Check https://github.com/symfony/symfony/pull/16386

**Comment by JHGitty** [comment] 2015-11-02 02:37
Known PHP issue for PHP5.6+ but it is only fixed in PHP7+.
https://bugs.php.net/bug.php?id=68057

 [2015-03-23 17:51 UTC] bwoebi@php.net
Fixing this is an ABI break (**so not really possible for 5.6.x**). It's **fixed in master (PHP 7+)** though.

**Comment by Pierstoval** [comment] 2015-11-02 08:40
As a potential issue, can the cached urlGenerator retrieve the routes using php5.5 generators instead of saving all datas in an array? Maybe it would save some memory? If it's not fixed in php5.6 maybe it could be a nice idea :confused: ?

**Comment by SoboLAN** [comment] 2015-11-02 13:46
I can reproduce the bug mentioned by @JHGitty , which is probably the cause for your issue.

So basically you can't have arrays with more than 2^15 elements in PHP 5.6. That seems like a really **critical** bug to me because I think 2^15 is very small in 2015...

**Comment by mvrhov** [comment] 2015-11-02 14:07
Well they marked it as won't fix. So the author has two choices. downgrade to 5.5, or upgrade to upcoming 7.0. IMO, it's rare for one to have that many routes.
@Pierstoval: That won't work. AS sf 2.3 requires php 5.3

**Comment by AntoineLemaire** [comment] 2015-11-02 14:20
@mvrhov Yep, I'm waiting for 7.0 and I'll see with it.
For us, a other way to "fix" this problem pending, is to split our application with other server, and divide locales on each one, 15 for one, 15 for the other, so number of route does not exceed 20 000

**Comment by SoboLAN** [comment] 2015-11-02 14:24
@AntoineLemaire That huge number of routes does seem excessive, I'm sure that in 99.9999% of situations, they can be significantly reduced.

Why don't you have the locale as a route parameter ? Something like `/my/route/{locale}` .

**Comment by jelte** [comment] 2015-11-02 14:45
@AntoineLemaire I've updated my fix (https://github.com/symfony/symfony/pull/16386) for this so it has a slightly different behaviour in php 5.6 in the case you have a large number of routes.
Hopefully someone approves it and it gets merged.

**Closed** 2015-11-25 12:21 UTC
Labels: Routing
