### ISSUE TITLE
[PhpunitBridge] Simple PHPunit incorrectly marks tests as passed in PHP 5.6+

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#21161] opened 2017-01-04 16:27 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1 (probably any?)

Example: 

 * Incorrectly passing job in PHP 5.6: https://travis-ci.org/symfony-cmf/sonata-phpcr-admin-integration-bundle/jobs/188865130
 * Correctly failing job in PHP 5.5: https://travis-ci.org/symfony-cmf/sonata-phpcr-admin-integration-bundle/jobs/188865129

Both jobs run the same test suite and have the same errors reported. This is probably related to PHPunit 5.3.x (incorrect) instead of PHPunit 4.8.x (correct).

**Comment by xabbuh** [comment] 2017-01-11 19:18
@wouterj Did you maybe find out what is the cause for this behaviour?

**Comment by wouterj** [comment] 2017-01-11 19:56
Didn't digg into this.

This is an exception thrown in a PHPunit test listener. I think that'll make people able to recreate this behaviour and maybe find out what it is. It's happend a couple times in the CMF builds now, so I think it's a consistent bug.

**Comment by nicolas-grekas** [comment] 2017-01-23 10:00
The behavior is the same whe using the native phpunit (v5.7 tested).
If I comment all calls to `markTestSuiteSkipped` in `vendor/symfony-cmf/testing/src/Phpunit/DatabaseTestListener.php`, then the errors are reported as expected.

Closing as "not a bug" on Symfony - might be one in phpunit or DatabaseTestListener thought.

**Closed by nicolas-grekas** 2017-01-23 10:00 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review
