### ISSUE TITLE
What is the idiomatic way to inject a private third-party service into a WebTestCase in 3.4/4.0?

### ISSUE THREAD

**Issue by manuelkiessling** [symfony/symfony#24543] opened 2017-10-13 08:27 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-DEV

Up until 3.3, I would often make use of container services from within my WebTestCases, like this:

```
$um = $container->get('fos_user.user_manager');
$user = $um->findUserByEmail('johndoe@example.com');
```

However, `fos_user.user_manager` is a private service, and 3.4 deprecates retrieving those through the container.

The easy way out is to alias the service to make it public in `services.yml`, like this:

```
fos_user.user_manager.public:
    alias: fos_user.user_manager
    public: true
```

but that doesn't feel like the right thing to do.

I tried to get setter injection working, but this seems to be limited to classes within the container, and doesn't seem to work for `WebTestCase` classes.

Is there a general/idiomatic approach to access private services from within WebTestCase classes?

**Comment by weaverryan** [comment] 2017-10-15 13:54
Actually, this is currently the way to do this (so good find), though you should do this only in config_test.yml so that the public service is only accessible where you need it.

It *does* make me wonder if it’s possible (and also a good idea) to somehow DI the test classes, so you can autowiring them like normal. This public alias thing is a pain, and this type of thing looks very valid to do.

**Comment by nicolas-grekas** [comment] 2017-10-15 17:03
I propose to add a new after removing pass that would turn private services back to public ones. This pass would be enabled only in test environment. WDYT?

**Comment by nicolas-grekas** [comment] 2017-10-15 19:56
The new idiomatic way could also be to leverage #24257, and turn some services public in the kernel, something like:
```
public function process(ContainerBuilder $container)
{
    if ('test' === $this->getEnvironment()) {
        $container->getDefinition('fos_user.user_manager')->setPublic(true);
        // etc. for all required services in tests
    }
}
```

**Comment by weaverryan** [comment] 2017-10-16 23:41
I don’t know if it should be a legit concern, but making all services public in test makes the envs quite different, and I worry about surprises due to this... but it’s also the nicest solution. 

To throw more ideas around:

- configure a service locator in the test env: users could just add their services to it as needed. We would document fetching this service locator from the container to get the services you need. The pro is that the service ids could be the same as in the real world, and slightly less config 

- a mixture of above and your idea: in the test env only, add a service locator that has a reference to all services. Like above, the user would fetch the locator service (e.g. test_service_accessor) and then fetch services like normal

**Comment by nicolas-grekas** [comment] 2017-10-16 23:56
> configure a service locator in the test env

I think that's exactly the same as my proposal just above (turning some service public in the kernel-pass).

**Comment by manuelkiessling** [comment] 2017-10-17 06:36
I'm curious: Is bringing autowiring (like it happens within the container) something that should be extended to WebTestCases? This way, no workarounds whatsoever would be neccessary - automatic (setter) injection of dependencies would become available in test code classes exactly like it is available in application code classes.

**Comment by stof** [comment] 2017-10-17 07:24
Well, actually, `fos_user.user_manager` is meant to stay public, but I have not yet updated this bundle for new changes...

@manuelkiessling test cases are not something happening inside the app. PHPUnit is calling the kernel, not the opposite.

**Comment by chrisguitarguy** [comment] 2017-11-02 22:49
> I propose to add a new after removing pass that would turn private services back to public ones. This pass would be enabled only in test environment. WDYT?

I did this recently when trying to upgrade to the 3.4 beta. It works, but I got very concerned that I'd be effectively missing any deprecation warnings in my tests.

Meaning the process of upgrading to 3.4, fixing deprecations, then going 4.X later would not effectively work.

**Comment by nicolas-grekas** [comment] 2017-11-03 07:23
@chrisguitarguy aliasing instead of turning public?

**Comment by nicolas-grekas** [comment] 2017-11-03 07:25
Or unconditionally turn public btw. There is no real downside to making more services public if you know they're in use somewhere in your code.

**Comment by chrisguitarguy** [comment] 2017-11-03 13:54
> aliasing instead of turning public?

Oh, that's a good idea!

> Or unconditionally turn public btw. There is no real downside to making more services public if you know they're in use somewhere in your code.

In this case, I was making the service public just for tests.

For some older apps, things that have been Symfony ~2.5 through 3.3, there service will have to be made public due to the formerly "proper" use of the container in controllers.

**Comment by theofidry** [comment] 2017-11-04 17:16
@nicolas-grekas I think the current configuration very painful as a maintainer still. I don't think you should need to worry about this issue when upgrading, so I would be 👍 to not make services private by default for the `test` environment which would be good enough for about 90% of the cases and document the idiomatic way to do it for the rest

**Comment by nicolas-grekas** [comment] 2017-11-04 17:19
@theofidry services must be private, or the default config just doesn't work as soon as a class is not autowireable (just try it.)
But there is something we could to: turn all private services back to public *after* removing passes.
That would also require disabling the inlining pass, which could be OK.
Someone should confirm this approach is viable on a real app.

**Comment by theofidry** [comment] 2017-11-04 18:34
I tried it there: https://github.com/nelmio/alice/pull/834.

TL:DR; I added a pass in the AppKernel to make _all_ services and aliases public. This is not a universal answer as if you have `$container->get('foo')` in a command for example, it can work fine in the tests by doing so but won't in production. In my case it was a library that doesn't use the container as a SL at all so it's actually fine.

**Comment by nicolas-grekas** [comment] 2017-11-26 14:53
So, after talking with several ppl having the same issue, we all agreed that doing the aliases as described *is* actually the best way to do this. There is a doc issue to put that there also (https://github.com/symfony/symfony-docs/issues/8097).
Note that aliasing should not be done in ~~`services.yaml`~~, but in `services_test.yaml`.
A consistent naming convention would help also, like prefixing the aliased service by `test.` when creating the alias.
I'm now closing as the question has been answered for 3.4/4.0.

**Closed by nicolas-grekas** 2017-11-26 14:53 UTC

**Comment by kaanbasal** [comment] 2017-12-13 14:41
I think the solution is not ideal in any way. We are not defining our services in config.yml and designing everything for not to be able to define it in config.yml/service.yml. So just only to use services in integration tests, we should add them?

For the sake of the decoupling, the best way as you say is also not viable. At least give users a proper example like, defining those services under each bundle with a separate services.yml (services_test.yml) and load that yml when testing.

To be more clear, we should be able to disable removing compiled services from container when needed and it should be configurable not hard-coded from a single point.

**Comment by derrabus** [comment] 2017-12-13 15:55
> We are not defining our services in config.yml

Just to clarify: By "we are not defining them" you mean, you use PSR-4 autodiscovery to define them? Otherwise, I'd be confused: Services that haven't been defined are not in the container because, well, they haven't been defined. 😉 

> So just only to use services in integration tests, we should add them?

No, the suggestion is that you in your test environment you add public aliases to your private (autodiscovered?) services to make them available in your integration tests.

> To be more clear, we should be able to disable removing compiled services from container when needed and it should be configurable from a single point, not hard-coded.

Since private services are not accessible via the `get()` method anyway, removing/inlining them does not change the external behavior of the container. So what would be the point of disabling that feature?

**Comment by derrabus** [comment] 2017-12-13 15:57
By the way, for people who don't like the public alias solution, I have drafted a solution that uses tags and a separate container for integration tests.

https://github.com/symfony/symfony-docs/issues/8097#issuecomment-348963302

Maybe, other people in this thread find this helpful as well.

**Comment by kaanbasal** [comment] 2017-12-13 16:50
> We are not defining our services in config.yml
Yes, we are using PSR-4 based service discovery, and on the higher levels of our application we are avoiding to define services one by one in services.yml. I hope this is clear now 😉

>No, the suggestion is that you in your test environment you add public aliases to your private (autodiscovered?) services to make them available in your integration tests.

Actually I checked all of the suggestions and the comment you sent and the problem is not always about your own services which you defined, autowired, or configured. The problem is 3rd party bundles. In integration test, you don't need to get only your own services to test or check if everything goes well but also you want to get other 3rd party bundles' services. In this case, if you want to use them in your integration test, how would you do it?

> Since private services are not accessible via the get() method anyway
Imo, this is actually bad idea not to have them in the test env as we should be able to get any service which we need. I was saying that should be configurable.

Thanks for the quick response btw 👍

**Comment by derrabus** [comment] 2017-12-13 17:18
> you want to get other 3rd party bundles' services

If the 3rd party bundle declares them public, you can use them straight away. If the bundle defines them as private, it is kinda odd to access them directly, but if you have to, it's the same as with your own.
* You can add a public alias to the third-party service to your test environment.
* You can add a compiler pass that sets the third-party service to public (not recommended).
* If you use my compiler pass from the linked comment, you can add the third-party services you want to access to the service locator.

**Comment by kaanbasal** [comment] 2017-12-13 17:25
All of the suggestions would work. But as I thought all of the suggestions require us to know which services we will use in tests. if they are distributed over bundles it gets more complicated.
Thanks for the answers, I will check if I can make it easy to work with 👍

**Comment by nicolas-grekas** [comment] 2018-03-12 19:16
Please check #26499

**Comment by theofidry** [comment] 2018-03-12 19:32
Well, that makes one less thing I wanted to talk about with you at the SfLive :P
