### ISSUE TITLE
[Proposal] Exception 'Entities passed to the choice field must be managed.' - Code works just fine without this being thrown maybe have switch to bypass

### ISSUE THREAD

**Issue by AntonioCS** [symfony/symfony#13964] opened 2015-03-18 15:36 UTC
I am currently using symfony2 forms to create a form with many forms inside them.
I save data in a way where I just get the data and do some internal validation (I am not using anything else from symfony2).

I have placed some caching and now I hit this exception:

```
throw new RuntimeException(
'Entities passed to the choice field must be managed. Maybe '.
'persist them in the entity manager?'
);
```
In file  symfony/src/Symfony/Bridge/Doctrine/Form/ChoiceList/EntityChoiceList.php.

I have changed the source code and removed this exception and the code works as it did before. The entities are not managed but everything works just as well.

Is there anyway to bypass this this exception via switch or something?

**Comment by jakzal** [comment] 2015-03-31 18:12
Are you caching doctrine entities? Have you re-registered them on the entity manager after fetching from cache?

**Comment by jakzal** [comment] 2015-03-31 18:26
Note that I don't know why this condition is there and it's not explained in the code. I expect that doctrine would throw an exception itself if non managed entities were used here. Perhaps @webmozart could tell us more.

**Comment by ZCJ** [comment] 2015-06-14 11:05
@AntonioCS  I am facing the same issue - I just upgraded to Symfony 2.7.1 and I got this issue. Were you able to get more feedback?

**Comment by sampart** [comment] 2015-06-25 12:00
@ZCJ I saw this problem when upgrading to Symfony 2.7.1 (from 2.6) as well.  Here's how I solved it: http://stackoverflow.com/questions/28625891/symfony-entity-field-manytomany-with-multiple-false-field-not-populated-co/31049706#31049706

**Comment by ZCJ** [comment] 2015-06-25 14:25
Thank you @sampart .. will try it check check.

**Comment by loiclavoie** [comment] 2015-09-02 16:23
This problem happen to me but I don't think by-passing is the solution.

In my case, the problem comes from having a nullable relation in doctrine, I do not know why, but doctrine return an empty Proxy object (for lazy loading) even when the data is set to null in database.
This cause an issue with the following tree:

1.in vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Form/ChoiceList/IdReader.php at line 103
2. in vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php at line 158
3. in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php at line 37
4.in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 1160

Basically, when "ChoiceToValueTransformer" is called, he passes the object as parameter. The object being a valid "instanceof" (because the proxy object inherit the real class object), cause the whole thing to be executed. The problem is, because the ID of the object is null (and all other information in the entity), it will not be contained within the entity manager and will throw the exception.

Bypassing the issue would only cause another problem a little later. The issue should either be solve by:
- force loading the proxy entity when recieved in the data transformer OR
- ignoring the Proxy object entirely if nullable=true in doctrine AND required=false in form info

If the proxy object cannot be loaded (->getId or the property needed return null), then the choice data should be set to the placeholder (null, empty_data, etc..)

I have no alternative solution to solve this problem at the moment, so if anyone have a recommandation, that would be appreciated.

**Comment by stof** [comment] 2015-09-02 17:16
@loiclavoie getting a proxy object when the relation is NULL in the database is wrong, and should not happen in the database. You should be getting ``null``. Initializing a proxy can never turned it back into null.

there is indeed a bug in Doctrine when tryign to read the id of uninitialized proxies though where it will fail to give their id: http://www.doctrine-project.org/jira/projects/DDC/issues/DDC-3886

**Comment by stof** [comment] 2015-09-02 17:19
@loiclavoie and your issue about proxies seems different than the issue reported above (proxies are managed)

**Comment by loiclavoie** [comment] 2015-09-02 17:30
@stof Actually, my message had two point: 
#1) Bypassing the whole thing seem wrong since this exception arise in many different case.
#2) Reporting the bug I had, and I wasn't sure if here was the appropriate place. I've just fixed it by creating my own DataTransformer and invalidating the default one in symfony for the field I needed. So, it's "fixed" without being fixed.

**Comment by HeahDude** [comment] 2016-02-05 06:26
Hi @loiclavoie, I think this issue has to do with the fact that by default `EntityType` maps post values with database id of the available options and the main refactoring of `ChoiceType` in #14050.
So you have to persist (no need to flush : `$entity = new Entity();`) before handling request and that's what this exception is telling you.

That is the expected behaviour.

Maybe you could use #17694 if it's merged in 2.7 to map the data you need and get it work the way you want by using :

```php
$builder->add('category', EntityType::class, array(
    'class' => Category::class,
    'choice_label' => 'name',
    'choice_value' => 'property', // $category->getProperty()
    // or
    'choice_value' => function (Category $c, $id, $index) {
        return 'some_prefix'.$c->getName();
    },
);
```

Should be closed IMO, especially if #17694 gets merged.

**Comment by webmozart** [comment] 2016-02-05 06:57
If you use in-memory entities only, why don't you pass them as choices to a regular ChoiceType instead?

**Closed** 2016-02-15 08:12 UTC
Labels: Doctrine, Form

**Comment by mgrundman** [comment] 2016-09-08 14:25
The problem is that $object is a \Doctrine\ORM\PersistentCollection and it cannot be managed itself. I solve this problem in the getIdValue function :

if( $object instanceof \Doctrine\ORM\PersistentCollection )
                foreach( $object as $item)
                        {       
                        if (!$this->om->contains($item) )
                                throw new RuntimeException( 
                                'Entities passed to the choice field must be managed. Maybe '.
                                'persist them in the entity manager?'
                                 );
                        }
        else
                if (!$this->om->contains($object)) 
                throw new RuntimeException(
                'Entities passed to the choice field must be managed. Maybe '.
                'persist them in the entity manager?'
                 );
