### ISSUE TITLE
[2.7][Form] #14465 introduced a new regression: empty required choice fields are not validated anymore

### ISSUE THREAD

**Issue by spackmat** [symfony/symfony#14607] opened 2015-05-11 14:16 UTC
Hi,

I implemented the fix from #14465 into the codebase of my Symfony 2.7.0-BETA1 based appication. Now, the non required filter form choice fields work again an do not provoke form errors, when they are empty.

But in the same time, all my required choice fields (representing non nullable database columns) do not validate anymore, when I submit them empty. Insteat I get an SQL error about the missing values for the non nullable fields. Removing the fix again resolves this.

See also my comment on the fix itself: https://github.com/symfony/symfony/pull/14465#commitcomment-11134487

**Comment by spackmat** [comment] 2015-05-14 08:50
Just updated to Symfony 2.7.0-BETA2 which has #14465 integrated: the problem still occurs. Sending empty form values for non nullable properties throws a SQL error instead of a form error.

**Comment by spackmat** [comment] 2015-05-30 21:07
Just updated to Symfony 2.7.0: the problem still occurs.

**Comment by webmozart** [comment] 2015-06-11 15:55
Hi @spackmat, thank you for reporting this issue! This bug was fixed for Doctrine in #14950. Apart from that, it's a duplicate of #14583, hence I'm closing it.

**Comment by spackmat** [comment] 2015-06-11 18:22
Hi @webmozart , I tried out the changes in #14950 , but the error still occurs, when I save a form with an empty choice for a non nullable field:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'otherentity_id' cannot be null`

I am also unsure, if this is really a duplicate of #14583 . I'm using MySQL with Doctrine, no Postgres.

**Comment by xabbuh** [comment] 2015-07-04 22:24
@spackmat Can you check if #15027 fixes your issue?

**Comment by spackmat** [comment] 2015-07-06 07:52
@xabbuh Hi, I inserted the changed lines from #15027. Doesn't fix the issue.

**Comment by xabbuh** [comment] 2015-07-09 06:52
@spackmat Looks like your issue is a bit different from #14583. Can you please provide some more information about how your scenario looks like to make it possible to reproduce your issue (or even provide a fork of the Symfony Standard Edition that reproduces it)?

**Comment by spackmat** [comment] 2015-07-09 07:49
I thought about this issue again after a while: I think the problem is, that the guessing taking place until Symfony 2.6 is broken in 2.7. In 2.6 a property of an Doctrine-Entity, that is not nullable, is considered as required by the Form. In 2.7, it's not anymore.

As a workaround, I could simply add explicit `NotNull` Asserts inside the model definition for all of those properties, but on the other hand, IMHO this BC break should be addressed.

My Scenario is dead simple:

a) Have a Doctrine-Entity with a non nullable property, in my case a simple one-to-many-connection:

```php
/**
 * @var \AppBundle\Entity\Otherentity
 *
 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Otherentity", inversedBy="myentity")
 * @ORM\JoinColumns({
 *   @ORM\JoinColumn(name="other_id", referencedColumnName="id", nullable=false)
 * })
 */
private $other;
```

b) Have a Form with an Entity-type for that field:

```php
$builder
    ->add('other', 'entity', array(
        'class' => 'AppBundle:Otherentity',
        'choice_label' => 'identifyingName',
        'label' => 'Other Entity',
        'required' => true,
        'invalid_message' => 'Please choose an Other Entity',
        'placeholder' => 'Please choose',
    ));
```

c) Submit the form with no chosen Other Entity (skipping the client side validation invoked by `'required' => true,`)

d) Symfony 2.6: You get a Form error about the missing value for the `other` field.

e) Symfony 2.7: You get a database error: "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'other_id' cannot be null"

f) Add a `* @Assert\NotNull()` Assert to the Entity from a) and you get a form error again.

**Closed** 2018-09-21 09:19 UTC
Labels: Form, Status: Reviewed
