### ISSUE TITLE
[Routing][TwigExtensions] Inconsistency of path dealing with boolean

### ISSUE THREAD

**Issue by Zzortell** [symfony/symfony#21409] opened 2017-01-25 17:47 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

Hello!

In Twig, the `path` function accepts `true` as a boolean argument and then outputs `"1"` in the url, which is then consistently proccessed by the Router, while when passing `false` it outputs `"false"` in the url, which is interpreted as a string and do not matches.

Is this intended, a bug or an inconsistency?

**Comment by ogizanagi** [comment] 2017-01-25 18:57
I can't reproduce the issue :/. 
Using a boolean as a route parameter will simply resolve to `"1"` in the url if `true` was provided, or `""` if `false` (`"0"` in case of a query parameter).

I.E, given the following `test` route: `"test/{foo}/bar`:

- `path('test', { foo: true, baz: true })` =>`/test/1/bar?baz=1`
- `path('test', { foo: true, baz: false })` =>`/test/1/bar?baz=0`
- `path('test', { foo: false, baz: false })` =>`/test//bar?baz=0`

**Comment by Zzortell** [comment] 2017-01-25 20:38
First, thank you for your answer.

Well, for me:
- `{{ path('api.approve_game', {'id': game.id, 'approved': 0}) }}` => `/api/approve_game/53/0`
- `{{ path('api.approve_game', {'id': game.id, 'approved': true}) }}` and `{{ path('api.approve_game', {'id': game.id, 'approved': 1}) }}` =>`/api/approve_game/53/1`

But `{{ path('api.approve_game', {'id': game.id, 'approved': false}) }}`  now throw this error:

> An exception has been thrown during the rendering of a template ("Parameter "approved" for route "api.approve_game" must match "[^/]++" ("" given) to generate a corresponding URL.")

My route:
```php
    /**
     * @Route("/approve_game/{id}/{approved}", name="api.approve_game")
     */
    public function approveGameAction(Request $request, Game $game, bool $approved)
```

So what's the hell?

**Comment by ogizanagi** [comment] 2017-01-25 20:44
`{{ path('api.approve_game', {'id': game.id, 'approved': false}) }}` 
is throwing because the default requirement for parameters is indeed `[^/]++` (see [route requirements](http://symfony.com/doc/current/routing/requirements.html). [Here is also mentionned the default value](http://symfony.com/doc/current/routing/slash_in_parameter.html#configure-the-route)). 
But as the exception message states, the given string was an empty one (`""`), which is the expected behavior described in my first comment :)

**Comment by robfrawley** [comment] 2017-01-25 23:00
@ogizanagi Is it truly *expected* behavior to treat conversion of `true` and `false` differently?

- `true` => `1`
- 'false' => `""`

That seems inconsistent to me, regardless of original implementation? Is there a good reason for this? Or would it be possible to make the behavior consistent in a future major version release?

**Comment by javiereguiluz** [comment] 2017-01-26 14:01
I agree. This looks inconsistent. Bad news is that fixing this will be a BC break. Should we:

* Keep doing `true` -> `1` ... but also do `false` -> `0`  ?
* Keep doing `false` -> `""` ... but also do `true` -> `""`  ?

**Comment by stof** [comment] 2017-01-26 14:06
Well, this is just the way casting a boolean to string works in PHP. The rule is not ``true`` => ``1`` but ``true`` => ``"1"``

**Comment by stof** [comment] 2017-01-26 14:08
And your issue is related to the fact that route placeholders are meant to be strings. Passing booleans there is supported only because casting is supported, but then it follows the PHP casting rules. If you don't want these casting rules, pass a string directly.

**Comment by robfrawley** [comment] 2017-01-26 15:21
I understand *why* it behaves this way, I simply disagree that is should *remain* working this way, moving forward.

**Comment by fabpot** [comment] 2017-01-26 15:52
As @stof said, those values are strings, nothing else. Passing a boolean there does not make sense in the first place.

**Comment by javiereguiluz** [comment] 2017-01-27 08:14
Given the comments above, I'm closing this as "won't fix" then. First, because this is in fact PHP's behavior, not Symfony's ... and second, because the solution is "simple": not passing boolean values as route placeholders because they are not supported (only strings and numeric values).

**Closed by javiereguiluz** 2017-01-27 08:14 UTC
Labels: Bug, Routing, Status: Needs Review, TwigBridge

**Comment by Zzortell** [comment] 2017-01-27 17:11
Thank you.
