### ISSUE TITLE
LINK method returns Not Implemented

### ISSUE THREAD

**Issue by pedroresende** [symfony/symfony#13478] opened 2015-01-21 10:33 UTC
Apparently there is a problem with the LINK method, when I try to curl it, I'll get
````
HTTP/1.1 501 Not Implemented
Host: 127.0.0.1:8000
Connection: close
Content-Type: text/html; charset=UTF-8
Content-Length: 495

<!doctype html><html><head><title>501 Not Implemented</title><style>
body { background-color: #fcfcfc; color: #333333; margin: 0; padding:0; }
h1 { font-size: 1.5em; font-weight: normal; background-color: #9999cc; min-height:2em; line-height:2em; border-bottom: 1px inset black; margin: 0; }
h1, p { padding-left: 10px; }
code.url { background-color: #eeeeee; font-family:monospace; padding:0 2px;}
</style>
</head><body><h1>Not Implemented</h1><p>Request method not supported.</p></body></html>
````
but the route is declared has you can see 

````
php app/console router:debug --env=prod | grep LINK
 layouts_id_link        LINK     ANY    ANY  /layouts/{id}     
 zones_id_link          LINK     ANY    ANY  /zones/{id}       
 blocks_id_link         LINK     ANY    ANY  /blocks/{id}      
 handlers_id_link       LINK     ANY    ANY /handlers/{id}  
````

All the other methods, POST, GET, PATCH, OPTIONS work correctly. I'm currently doing the request using

````
curl -i -X LINK http://127.0.0.1:8000/handlers/XX
````

After investigating a bit more, I've found the method is not implemented in https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L38

**Comment by jaytaph** [comment] 2015-01-21 11:00
I've quickly checked this, but it seems that I can use LINK without issues. 

Can you provide a stack-trace? I'm guessing some kind of (custom) listener is blocking the request.

**Comment by pedroresende** [comment] 2015-01-21 11:09
@jaytaph I would gladly provide it, however there is nothing added to dev.log

**Comment by jakzal** [comment] 2015-01-21 11:10
The message most likely comes from your web server, not Symfony. I'm closing this issue since this is not a bug. Feel free to reopen if you think otherwise. In which case, please provide code that would reproduce your issue.

Btw, the LINK method doesn't have a constant in the Request class, as it's not part of the official spec (it's only present in the draft).

**Closed by jakzal** 2015-01-21 11:10 UTC

**Comment by pedroresende** [comment] 2015-01-21 11:14
In this case the problem is related with internal Symfony's server, since I'm currently using

````
php app/console server:run
````

**Comment by jakzal** [comment] 2015-01-21 11:18
@pedroresende this command runs [PHP's built in server](http://php.net/manual/en/features.commandline.webserver.php), so the "issue" is there.

**Comment by pedroresende** [comment] 2015-01-21 11:32
@jakzal you're absolutely right, apparently the problem is in the PHP's build in server, 
sorry for wasting your time @jakzal and @jaytaph

**Comment by pedroresende** [comment] 2015-01-21 11:46
Just reported an php issue https://bugs.php.net/bug.php?id=68875&thanks=4
