### ISSUE TITLE
[HttpClient] AsyncResponse with cURL triggers "API function called from within callback"

### ISSUE THREAD

**Issue by glaubinix** [symfony/symfony#58224] opened 2024-09-10 14:55 UTC
### Symfony version(s) affected

6.4.11/7.1.4

### Description

There seems to be an issue with the AsyncResponse of the HttpClient if the response stream is used as body in a subsequent request.

The problem doesn't occur if the client doesn't return an `AsyncResponse` e.g. in the example below `$client` is just `$client = \Symfony\Component\HttpClient\HttpClient::create();`.

### How to reproduce

```php
$client = new \Symfony\Component\HttpClient\RetryableHttpClient(\Symfony\Component\HttpClient\HttpClient::create());
$response = $client->request('GET', 'https://example.com');
$response = $client->request('POST', 'https://example.com', ['body' => $response->toStream()]);
```
Similar error happens when calling `$response->getStatusCode()` after the POST request.

### Possible Solution

A workaround is to use two instances of the HTTP client. One for GET and one for POST.
```
$clientFrom = new \Symfony\Component\HttpClient\RetryableHttpClient(\Symfony\Component\HttpClient\HttpClient::create());
$clientTo = new \Symfony\Component\HttpClient\RetryableHttpClient(\Symfony\Component\HttpClient\HttpClient::create());
$response = $clientFrom->request('GET', 'https://example.com');
$response = $clientTo->request('POST', 'https://example.com', ['body' => $response->toStream()]);
```

### Additional Context

Full stack trace

```
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TransportException: API function called from within callback in vendor/symfony/http-client/Response/CurlResponse.php:292
Stack trace:
#0 vendor/symfony/http-client/Response/TransportResponseTrait.php(167): Symfony\Component\HttpClient\Response\CurlResponse::perform(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Array)
#1 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, 0.0)
#2 vendor/symfony/http-client/Response/ResponseStream.php(45): Generator->rewind()
#3 vendor/symfony/http-client/Response/AsyncResponse.php(256): Symfony\Component\HttpClient\Response\ResponseStream->rewind()
#4 vendor/symfony/http-client/Response/StreamWrapper.php(123): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, 0.0)
#5 [internal function]: Symfony\Component\HttpClient\Response\StreamWrapper->stream_read(8192)
#6 vendor/symfony/http-client/CurlHttpClient.php(339): curl_multi_exec(Object(CurlMultiHandle), 0)
#7 vendor/symfony/http-client/Response/AsyncResponse.php(256): Symfony\Component\HttpClient\CurlHttpClient->stream(Array, -0.0)
#8 vendor/symfony/http-client/Response/AsyncResponse.php(67): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, -0.0)
#9 vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#10 vendor/symfony/http-client/Response/AsyncResponse.php(184): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#11 [internal function]: Symfony\Component\HttpClient\Response\AsyncResponse->__destruct()
#12 {main}
  thrown in vendor/symfony/http-client/Response/CurlResponse.php on line 292

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: API function called from within callback in vendor/symfony/http-client/Response/CurlResponse.php:292
Stack trace:
#0 vendor/symfony/http-client/Response/TransportResponseTrait.php(167): Symfony\Component\HttpClient\Response\CurlResponse::perform(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Array)
#1 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, 0.0)
#2 vendor/symfony/http-client/Response/ResponseStream.php(45): Generator->rewind()
#3 vendor/symfony/http-client/Response/AsyncResponse.php(256): Symfony\Component\HttpClient\Response\ResponseStream->rewind()
#4 vendor/symfony/http-client/Response/StreamWrapper.php(123): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, 0.0)
#5 [internal function]: Symfony\Component\HttpClient\Response\StreamWrapper->stream_read(8192)
#6 vendor/symfony/http-client/CurlHttpClient.php(339): curl_multi_exec(Object(CurlMultiHandle), 0)
#7 vendor/symfony/http-client/Response/AsyncResponse.php(256): Symfony\Component\HttpClient\CurlHttpClient->stream(Array, -0.0)
#8 vendor/symfony/http-client/Response/AsyncResponse.php(67): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, -0.0)
#9 vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#10 vendor/symfony/http-client/Response/AsyncResponse.php(184): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#11 [internal function]: Symfony\Component\HttpClient\Response\AsyncResponse->__destruct()
#12 {main}
  thrown in vendor/symfony/http-client/Response/CurlResponse.php on line 292
```

**Comment by nicolas-grekas** [comment] 2024-09-11 09:50
I spent sometime on this and the conclusion is that this is not supported with any clients.
The reason is that the API for the input stream doesn't allow non-blocking reads.

You can work around the issue by using a php://temp stream like this:

```php
$buffer = fopen('php://temp', 'w+');
$from = $c->request('GET', 'http://localhost:8080/from.php', ['buffer' => $buffer]);

foreach ($c->stream($from) as $chunk) {
    // wait for $buffer to be populated
}

rewind($buffer);

$to = $c->request('PUT', 'http://localhost:8081/to.php', ['body' => $buffer]);
```

This will keep memory usage low at the cost of some temporary disk usage.

It might be possible to provide an API that'd allow piping a response into a request but this looks non-trivial task :)

(Note that I'd be surprised if Guzzle was capable of true streaming like you tried to achieve here, let me know if anyone has insights on the topic.)

Closing as won't fix therefor.

**Closed as not planned by nicolas-grekas** 2024-09-11 09:50 UTC
Labels: Bug, Status: Needs Review, HttpClient

**Comment by nicolas-grekas** [comment] 2024-09-11 14:01
> A workaround is to use two instances of the HTTP client. One for GET and one for POST.

Yes, that works indeed. Curl doesn't allow performing requests while in a curl callback for the same multi-handle, but when using different multi-handles, it works. Good catch, that's the way to go I'd say.

Making this possible with the same client instance might be too much work, including just for improving the error message.

At least we have this issue for history. And maybe one day someone will find the time to figure out a way around the current limitation.

Reproducer:
```
$clientFrom = new \Symfony\Component\HttpClient\CurlHttpClient();
$clientTo = new \Symfony\Component\HttpClient\CurlHttpClient();
$response = $clientFrom->request('GET', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg', [
    'on_progress' => function ($dlNow, $dlSize) { echo 'FROM: '.$dlNow . ' / ' . $dlSize . PHP_EOL; },
    'buffer' => false,
]);
$response = $clientTo->request('POST', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg', [
    'body' => $response->toStream(),
    'on_progress' => function ($dlNow, $dlSize, $info) { echo 'TO: '.$info['size_upload'] . PHP_EOL; },
    'buffer' => false,
]);

```

This shows also that when downloadung is faster than uploading, the activity list grows too much.

**Comment by glaubinix** [comment] 2024-09-11 14:06
Thank you for looking into it!
