### ISSUE TITLE
TraceableEventDispatcher breaks session handing in controller tests

### ISSUE THREAD

**Issue by DerManoMann** [symfony/symfony#14263] opened 2015-04-07 21:07 UTC
Hi there,

I am in the process of upgrading a Silex app and part of that is an upgrade of the sf components. With sf 2.6 I've run into a problem with the TraceableEventDispatcher.
Dispatcher version is v2.6.6

silex_upgrade/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/MockArraySessionStorage.php:134
silex_upgrade/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Session.php:199
silex_upgrade/vendor/silex/silex/src/Silex/Provider/SessionServiceProvider.php:93
silex_upgrade/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
silex_upgrade/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
silex_upgrade/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
silex_upgrade/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
silex_upgrade/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:112
silex_upgrade/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:126
silex_upgrade/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:66
silex_upgrade/vendor/silex/silex/src/Silex/Application.php:543
silex_upgrade/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/Client.php:81
silex_upgrade/vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php:327
silex_upgrade/php/tests/controllers/TestLookupController.php:20

**Comment by TomasVotruba** [comment] 2015-04-07 21:50
Hey,

it looks like you provided only list of files from bugtrace. 
More relevant would be actual exceptions message or error.

**Comment by DerManoMann** [comment] 2015-04-07 22:07
Good point.
LogicException: Cannot set session ID after the session has started.

**Comment by Tobion** [comment] 2015-04-07 23:07
Duplicate of #13450

**Closed by Tobion** 2015-04-07 23:07 UTC
