### ISSUE TITLE
Multiple forms and profiler

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#16178] opened 2015-10-08 21:02 UTC
Sometimes it is useful to create array of forms and render them in template separately with the same name ($form->getName()). But in this case Profiler will display only the last form in Panel, because FormDataCollector uses $form->getName() as index and the last form overrides previous forms.

Possible solution is to fix [this](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/DataCollector/FormDataCollector.php#L199) code to somethink like
```php
$name = $form->getName().'_'.uniqid();
$this->data['forms'][$name] = array();
```
In this case profiler will collect multiple forms correctly.

**Comment by jakzal** [comment] 2015-10-08 21:46
How do you handle forms created this way? Field names and ids in html would be duplicated. I'd rather create a form containing collection of other form types.

**Comment by zim32** [comment] 2015-10-08 21:51
I use this forms via javascript ajax submit to api controller, wich expects to see single form

**Comment by stof** [comment] 2015-10-09 07:58
But this does not change the fact that you have duplicate ids in your HTML, which can break many things (for instance in JS because browsers are optimizing things based on the fact that id are unique)

**Comment by zim32** [comment] 2015-10-09 08:48
Can i override in with attr in twig template? If I can, this is not a probem, otherwise I think it smells like bad design

**Comment by stof** [comment] 2015-10-09 09:16
@zim32 no. Ids are generating during ``->buildView()``

**Comment by zim32** [comment] 2015-10-09 09:18
Yeah. So this fact eliminates you question? )

**Comment by Rvanlaak** [comment] 2015-10-12 08:32
You can use `$forms[] = $container->get('form.factory')->createNamed('your_base_name'.uniqid())->buildView()` to create separate forms, and thereafter pass them to the view to let all of them appear in the profiler. But how will you handle the data on submit if you don't have the uniqid anymore?

**Comment by zim32** [comment] 2015-10-12 08:39
That's why i do not need unique form name. That's the main problem.

**Comment by rparsi** [comment] 2015-10-13 19:23
@zim32 The rest of us rely on Symfony to be built with standards in mind and not catering to specific weird business logic.  So no, it's not better to "fix" the profiler rather than your business logic.

My smartass comment aside, you can apply pseudo namespacing to your form name and element names.  As in

<form name='toplevelNamespace.something' id='toplevelNamespace.something' ...>

<input name='toplevelNamespace.something.blah' id='toplevelNamespace.something.blah' ... />

and process accordingly in your controller action.

**Comment by zim32** [comment] 2015-10-13 20:07
Ok, let me describe my case. I have many forms (of one type say A) is one page in controller A. I have separate controller B which submit the form of type A. I use javascript to select which form to submit and make POST request to controller C. How can I implement this without breaking profiler?

**Comment by rparsi** [comment] 2015-10-13 20:31
@zim32 Sorry your description is confusing.  What I get is you have several sub forms (regardless of whether or not a given child form is a Symfony2 form or generated by your Twig template) in a given page.  It also seems like you're using a frontend framework.

Does each sub form have a dedicated route, or are you trying to submit any child/sub form to the same controller action (php side)?

**Comment by zim32** [comment] 2015-10-13 20:45
What is sub forms? I just have many root forms. Just plain array of Form classes.

**Comment by rparsi** [comment] 2015-10-13 20:49
@zim32 I'll rephrase.  In the given page do you have multiple form tags, or 1 form tag whose elements represent the aggregate of several Form instances?  Regardless trying to make a one size fits all approach will lead to messy code.  In general each Form class should have it's own dedicated route.

**Comment by zim32** [comment] 2015-10-13 20:59
I have multiple form tags because i render each form just like ordinary form {{ form(forms[index])  }}

**Comment by rparsi** [comment] 2015-10-13 21:03
@zim32 Trying to make all of them use the same route for submit will lead to a big mess.

**Comment by zim32** [comment] 2015-10-13 21:05
Why?? They are all of the same type. I have array of absolutely identical forms and submit them to one route.

**Comment by rparsi** [comment] 2015-10-13 21:10
@zim32 It would only work if all the objects in forms[] are instances of the same class.  What you think of as a 'type' has no meaning in the backend/php side.

**Comment by javiereguiluz** [comment] 2016-01-26 13:55
After reading the discussion, I'm closing this issue as "won't fix".

@zim32 I'm not saying that you are doing it wrong. On the contrary, I love when people discover new ways to push Symfony to its limits. However, the web profiler only works for the regular use cases and I'm afraid that your use case is "too edgy" to consider it. I hope you understand it. Thanks!

**Closed by javiereguiluz** 2016-01-26 13:55 UTC
Labels: Form, WebProfilerBundle

**Comment by stof** [comment] 2016-01-26 14:17
Note that the issue is not only in the profiler: the root name also influences the ids generated for all inputs in the form. So when you reuse the same name for all forms, you also reuse the same ids, making your HTML invalid (and potentially breaking JS code as several DOM APIs are relying on the uniqueness of ids and will only consider one of the elements)
