### ISSUE TITLE
Symfony MakerBundle

### ISSUE THREAD

**Issue by getrealtec** [symfony/symfony#40533] opened 2021-03-21 21:51 UTC
**Symfony version(s) affected**: 
symfony/framework-bundle : v5.2.5
symfony/maker-bundle : v1.30.0
doctrine/orm : 2.8.2

**Description**
[ERROR] Only annotation mapping is supported by make:entity.
Standard installation. Symfony uses "annotation" by default. "annotation" is specified in the config files as well.

**How to reproduce**
```
Install Symfony : symfony new PROJECT_NAME
cd PROJECT_NAME
composer require orm
composer require symfony/maker-bundle --dev
bin/console make:entity MyEntity
```

**Possible Solution**
No solution in particular, the error should not be thrown.

**Additional context**
![image](https://user-images.githubusercontent.com/50683179/111921981-d7b58d00-8a6d-11eb-9cb2-cf66e8d90b4a.png)

**Comment by derrabus** [comment] 2021-03-22 01:05
Duplicate of symfony/maker-bundle#841

**Closed as completed by derrabus** 2021-03-22 01:05 UTC
Labels: Bug, Status: Needs Review
