### ISSUE TITLE
Symfony profiler does not work with x-forwarded-prefix header

### ISSUE THREAD

**Issue by Foxprodev** [symfony/symfony#40709] opened 2021-04-05 13:44 UTC
**Symfony version(s) affected**: 5.2.*

**Description**
Symfony profiler does not work with x-forwarded-prefix header. 

`An exception has been thrown during the rendering of a template ("No route found for "GET /prefix/_profiler/search_bar"").
`

Reason:
The url generated by Twig RoutingExtension contains baseUrl and the `render` function can't match this url.

[Profiler code ref](https://github.com/symfony/web-profiler-bundle/blob/c97712849f4f3e4ea0a1be7ff38fcefadaa55c47/Resources/views/Profiler/layout.html.twig#L111)

**How to reproduce**

1. Proxy requests from /prefix/_profiler to /_profiler and set x-forwarded-prefix=/prefix
2. Open /prefix/_profiler

**Possible Solution**
Maybe way to generate internal url or reference.

**Additional context**
#37734

**Comment by derrabus** [comment] 2021-04-05 15:11
Is it only the profiler bar that is affected? If you generate a URL using the router, is that URL correct or do you have the same problem there?

**Comment by Foxprodev** [comment] 2021-04-05 15:19
> Is it only the profiler bar that is affected? If you generate a URL using the router, is that URL correct or do you have the same problem there?

All Twig templates which use `render(path(*some route*))` affected 

All links generated by UrlGenerator works fine through proxy. Thats why x-forwarded-prefix was introduced

**Comment by derrabus** [comment] 2021-04-05 15:31
> All links generated by UrlGenerator works fine through proxy. Thats why x-forwarded-prefix was introduced

Understood, I just wanted to make sure that the header is detected properly in your app. That seems to be the case.

Do feel like you could provide a patch that solves your problem?

**Comment by Foxprodev** [comment] 2021-04-05 15:42
> Do feel like you could provide a patch that solves your problem?

I'm not this good at the symphony ecosystem, sorry. :disappointed: And I don't see a good clean solution.

Maybe Twig `render()` function should work like a AbstractController::forward? And TwigBridge should generate such references by route 
like `Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController::searchBarAction`

I think internal application references shouldn't be generated by UrlGenerator

**Comment by derrabus** [comment] 2021-04-05 16:04
> Maybe Twig `render()` function should work like a AbstractController::forward? And TwigBridge should generate such references by route
> like `Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController::searchBarAction`

`render()` can also take a controller reference instead of a URI. An there's a Twig function named `controller()` that you can use to create such a reference. Maybe this already does the trick.

> I think internal application references shouldn't be generated by UrlGenerator

I agree.

**Comment by Foxprodev** [comment] 2021-04-05 20:04
Okay. I'll give a try this week

**Comment by stof** [comment] 2021-04-13 10:01
I think the root cause of the issue is that the inline strategy has a different handling of URLs than other strategies, expecting the url to skip the base url, being only the internal path info instead. I think this will not only break the web profiler but also the ESI fallback when you deploy a site without an ESI-capable reverse proxy, when the app has a base URL.
So to me, the right fix is not to change the WebProfilerBundle usages, but to fix the implementation of the inline strategy.

**Comment by Foxprodev** [comment] 2021-04-13 10:09
> I think the root cause of the issue is that the inline strategy has a different handling of URLs than other strategies, expecting the url to skip the base url, being only the internal path info instead. I think this will not only break the web profiler but also the ESI fallback when you deploy a site without an ESI-capable reverse proxy, when the app has a base URL.
> So to me, the right fix is not to change the WebProfilerBundle usages, but to fix the implementation of the inline strategy.

But still, is there any reason not to use more declarative and precise controller reference in this render case? In my opinion it's more useful for internal references.

**Comment by Foxprodev** [comment] 2021-04-13 11:30
The prefix must be processed by the proxy, that's the main idea. That's why kernel or `SubRequestHandler` shouldn't process prefix. As for me URLs generated this way (with baseUrl) is not suitable for render references.

**Comment by stof** [comment] 2021-04-13 11:38
@Foxprodev the inline strategy is also used as the fallback of other strategies (which must use external references as they are received as requests from other systems). This means that the inline strategy should support the same kind of paths than the others.
Also, the documented usage is to use `path()` or `url()` in template, which generates URLs with the base url included. So the inline strategy documentation is also assuming that the path is the external one (which matters only when the base url is not empty, as they are the same otherwise)

**Comment by Foxprodev** [comment] 2021-04-13 11:58
@stof Why there is no difference between urls generated for users and for references?
Sorry for asking such annoying questions. As I said before I am not familiar with symfony ideology, just reading the code :smile:

**Comment by stof** [comment] 2021-04-13 12:57
@Foxprodev because for other strategies than the inline one, there is no difference. The ESI and SSI strategies are resolved by a reverse proxy, which is also a client as far as the symfony app is concerned

**Comment by derrabus** [comment] 2021-04-13 13:09
@stof You might be right that there are other mechanisms affected as well by this problem. However, I believe that @Foxprodev's changes are a good idea because they decouple the web profiler from URL generation/mapping and thus render the profiler itself more robust. I'd like to merge the PR.

**Closed as completed** 2021-04-13 14:18 UTC
Labels: Bug, WebProfilerBundle, Status: Reviewed
