### ISSUE TITLE
[symfony/var-exporter] Warning: Undefined array key 3 at &__get($name)

### ISSUE THREAD

**Issue by shakaran** [symfony/symfony#52826] opened 2023-11-30 14:41 UTC
### Symfony version(s) affected

7.0.0

### Description

Getting a field which is a oneToMany reach this part of code

https://github.com/symfony/var-exporter/blob/7.0/LazyGhostTrait.php#L112

Where is not checked with isset() if the key index exist or not properly, assuming always that it is present.

I am using PHP 8.2

### How to reproduce

I have a User class with that OneToMany

    #[Ignore]
    #[ORM\OneToMany(mappedBy: 'followingUser', targetEntity: Follower::class, fetch: 'EXTRA_LAZY', cascade: ['persist', 'remove'], orphanRemoval: true)]
    public null|Collection|array $followings = null;

### Possible Solution

Check the index at least with isset()

**Comment by stloyd** [comment] 2023-11-30 14:51
Seems like a duplicate of https://github.com/symfony/symfony/issues/52793 potentially covered by https://github.com/symfony/symfony/pull/52797

**Comment by xabbuh** [comment] 2023-11-30 16:49
closing in favour of #52793

**Closed as not planned by xabbuh** 2023-11-30 16:49 UTC
Labels: Bug, Status: Needs Review, VarExporter
