### ISSUE TITLE
Collection adder/remover name - English dependency

### ISSUE THREAD

**Issue by Ang3** [symfony/symfony#21569] opened 2017-02-08 16:56 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | ?
| RFC?             | yes
| Symfony version  | 3.2

The system detects automatically the name of an adder or remover of a collection by an ENGLISH logic I guess. It relates a dependency to a human langage and not PHP... Moreover, I suppose it forces an execution time by parsing words or something else.

For greater flexibility, it would be a good idea to let the developper what the developper has to do (understand and write its own HUMAN langage)... In my case, I have to use some specific French words for a collection, and my logic is broken by an english one. I think we would be able to set the adder and remover name in the annotation. By default, an english logic could be applyed, why not ?

**Comment by javiereguiluz** [comment] 2017-02-08 17:04
I agree with what you say. We all know that it's recommended to develop in English regardless of your language, but sometimes you just can't do that. Besides, even if you only develop in English, trying to "singularizy/pluralify" words is challenging because of the inconsistencies of languages developed by humans (we have been reported lots of issues related to StringUtil::singularify).

So, maybe we should make a decision about this and ... remove this "feature" ?

**Comment by stof** [comment] 2017-02-08 17:14
Well, the ``get`` and ``set`` prefixes for getters and setters are also English. so we already force you to mix languages.
We cannot support rules for all languages at the same time (it would be insane).
We cannot drop the support of English either, despite what @javiereguiluz asks. This would be a BC break, and this would make everyone hate Symfony when writing adders and removers (``removeItems`` to remove a single item ? I would be the first one to hate that). I don't think the existing issues are big enough to justify breaking all common cases where it works fine.

See #5013 discussing this topic of making these configurable though. It is quite stalled though (and there is not yet an explicit solution)

**Comment by Ang3** [comment] 2017-02-08 17:34
I agree with you @stof about English, but `get` and `set` doesn't relate to the attribute it self but an "object action". `add` and `remove` too : this is a convention I'm ok. However, the model logic relates to the developper and not to the framework.

Finally, we don't need to broke this rule @javiereguiluz . We could let the default behaviour. Just adding options in annotation by forcing the method name to begin by `add` or `remove`, like repositories by `find`. We have to separate the logic of the framework from the human one. I will follow the other issue, thank you for the link ! ;)

**Comment by javiereguiluz** [comment] 2017-02-22 12:12
Let's close this as a pseudo-duplicate of #5013.

**Closed by javiereguiluz** 2017-02-22 12:12 UTC
Labels: Feature, Form, PropertyAccess
