### ISSUE TITLE
[Secrets]: decryption fails on a different machine

### ISSUE THREAD

**Issue by abraovic** [symfony/symfony#44470] opened 2021-12-06 11:03 UTC
### Symfony version(s) affected

5.3

### Description

Hi,

I'm having problem decrypting the prod credentials on a different machine. I have generated prod keys using:
`php bin/console secrets:generate-keys --env=prod`
and put some values in the vault using: 
`php bin/console secrets:set VAR_NAME --env=prod`

When I run:
`php bin/console secrets:list --reveal --env=prod`
on the machine where value is set I get the proper value decoded. 

But if I run the same command on an other machine I get `******` value, which basically means it can no be decoded. If I try:
`php bin/console secrets:decrypt-to-local --force --env=prod`
it says:
```
[ERROR] Secret "VAR_NAME" cannot be revealed as the wrong decryption
         key was provided for "config/secrets/prod/".     
```
And I literally c/p the key.

I did tested that both `prod.decrypt.private.php` and `prod.encrypt.public.php` are the same on both machines. Also I did run:
`php -r 'echo base64_encode(require "config/secrets/prod/prod.decrypt.private.php");'`
and store an output into .env as described [here](https://symfony.com/doc/current/configuration/secrets.html#deploy-secrets-to-production) but it did not help.

And if I store that same value on the different machine, it can, also, not be decrypted on an original one.

The thing is, `dev`, `test` and `stage` environments works without problems. 

### How to reproduce

Unfortunately, this seems to be a specific problem (not sure if it is bug or I did something wrong). So the problem description describes a way to reproduce it.

**Comment by nicolas-grekas** [comment] 2021-12-19 15:06
I'm sorry but I've no idea why this happens.
I cannot reproduce the behavior on my machine so can't help.
I'm closing because this is very likely an issue on your side, although I can't anticipate which one :(

**Closed as completed by nicolas-grekas** 2021-12-19 15:06 UTC
Labels: Bug, Status: Needs Review
