### ISSUE TITLE
[Validator] ClassMetadata loading and inheritance

### ISSUE THREAD

**Issue by tomaskadlec** [symfony/symfony#24066] opened 2017-09-01 16:03 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

I have an issue with validator component. I have a base class and a child. Base class defines a property and a set of constaints. Child must redefine one of the constraints - it must modify its options.I am using StaticMethodLoader for both classes because I am in control and I can work with constraints. The problem is that I get two violations instead of one when validating child object. Constraint is validated twice - with child options first and then with base class options. I tried to investigate why but I still don't know why its happening. And I am a bit lost in all the loaders and caching.

However, the result is quite unexpected for me. I thought that validator honors inheritance.

Thanks for any help.

**Comment by ro0NL** [comment] 2017-09-01 16:52
It's the same problem as #15950 right?

**Comment by xabbuh** [comment] 2017-09-01 20:05
closing here as a duplicate of #15950

**Closed by xabbuh** 2017-09-01 20:05 UTC
Labels: Feature, Validator
