### ISSUE TITLE
Debug Toolbar Deprecated Logs

### ISSUE THREAD

**Issue by pdias** [symfony/symfony#15463] opened 2015-08-05 16:12 UTC
Hello,

I'm using Symfony 2.7.3, in the debug toolbar i see some deprecated calls.
But in the logs i can not see where these calls occurs.

![capture](https://cloud.githubusercontent.com/assets/1615884/9090862/aad1d812-3b94-11e5-9efd-199b364f0dd4.PNG)

It was previously possible.

![wdt_deprecated_log_panel](https://cloud.githubusercontent.com/assets/1615884/9090938/3ed575b4-3b95-11e5-9411-84323e64ea12.png)

Thanks,

Paulo Dias

**Comment by stof** [comment] 2015-08-05 16:43
the web profiler is still able to display this information. the issue is that the ErrorHandler does not log it anymore. See https://github.com/symfony/symfony/issues/14425

I'm quite sure I already explained this a few days ago, but I cannot find it anymore.
anyway, closing this issue as duplicate

**Closed by stof** 2015-08-05 16:43 UTC
