### ISSUE TITLE
Browser-kit paramters cast to string in 5.2 [BC break]

### ISSUE THREAD

**Issue by KartaviK** [symfony/symfony#39269] opened 2020-12-01 15:15 UTC
https://github.com/symfony/browser-kit/commit/1d033e7dccc9978dd7a2bde778d06ebbbf196392#diff-de5d8eb3f1d6537c947f70e0a4673779312a902c083739f472c709c037bcbc30R41

```php
        array_walk_recursive($parameters, static function (&$value) {
            $value = (string) $value;
        });
```

What reason was for this bc break change? I don't understand.
It make a batch of problems in testing and do not any profit

**Comment by stof** [comment] 2020-12-01 15:22
that's because parameters submitted by an actual browser are also always strings.

**Comment by jderusse** [comment] 2020-12-01 15:31
Duplicate of #38651

**Closed as completed by jderusse** 2020-12-01 15:31 UTC
Labels: BrowserKit, BC Break
