### ISSUE TITLE
config imports directive needs ignore_missing flag

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#16175] opened 2015-10-08 12:10 UTC
It is possible to add optional config files by adding an `ignore_errors` flag:
```yml
imports:
    - { resource: 'parameters.yml', ignore_errors: true }
```
(see: [How to Organize Configuration Files ](http://symfony.com/doc/current/cookbook/configuration/configuration_organization.html#global-configuration-files) )

Now, when the parameters.yml file exists, but there is a yml error in it, the user is not notified of the error. The error is silently ignored. That's not helpful.

It would be better to have an `ignore_missing` flag (like in Twig) that still reports errors in the config file if it exists.

I'd also recommend to deprecate the ignore_errors flag. Ignoring errors is never a good idea.

**Comment by iltar** [comment] 2015-10-08 14:13
I've tested this with my `config_dev.yml` which imports `config.yml`; It still gives me an error if present:
```
Unable to parse at line 103 (near "bundles:a") in {path}/app/config/config.yml (which is being imported from "{path}/app/config/config_dev.yml").
```

**Comment by jakzal** [comment] 2015-10-13 08:17
@iltar which Symfony version have you used? I've tried on both 2.3 latest and 2.7 latest, and the errors are hidden if you specify `ignore_errors` in the import.

Having `ignore_missing` seems like a better idea to me (I don't see much use for `ignore_errors`). Although, I still prefer to make sure all the files are present ;)

**Comment by iltar** [comment] 2015-10-13 08:27
I'm using 2.7, not sure if it was the latest. I'm testing it in my dev env because deployment in my case will fail if the warmup scripts can't run, such as cache clear.

I don't think this is a symfony issue but a user environment/configuration issue.

**Comment by xabbuh** [comment] 2015-10-19 21:53
@thomas-koch-comsolit Can you provide a failing test case?

**Comment by thkoch2001** [comment] 2015-10-21 04:11
@xabbuh: @thomas-koch-comsolit does not exist anymore... :-)

**Comment by xabbuh** [comment] 2015-10-21 05:08
Okay, closing for now then. Feel free to comment if you can reproduce this again.

**Closed by xabbuh** 2015-10-21 05:08 UTC
Labels: Config, Unconfirmed

**Comment by TomasVotruba** [comment] 2020-04-08 16:00
This is now (2020+) possible: https://symfony.com/blog/new-in-symfony-4-4-dependency-injection-improvements-part-1#ignore-errors-when-importing-files
