### ISSUE TITLE
[Form][2.7] In entity field type not set selected data

### ISSUE THREAD

**Issue by lensky84** [symfony/symfony#15586] opened 2015-08-21 13:08 UTC
Hello!

I have some field with type 'entity' with multiple select.
When I choose some values and submit form, those values stored in database but not selected when I open this form again.

I noticed that in class 'Symfony\Bridge\Twig\Extension\FormExtension' in method 'isSelectedChoice' uses 
in_array($choice->value, $selectedValue, true)
with check types of data. 

But in $choice->value I have value like a string type (example: "1") and in $selectedValue I have an array with values like an integer.
Example: [0 => 1]

and  check in_array($choice->value, $selectedValue, true) always return false.

I am looking why I have $choice->value like a string and found that in class 'Symfony\Component\Form\ChoiceList\ArrayChoiceList' in method 'flatten' we have next code
$choiceValue = (string) call_user_func($value, $choice);

which convert all values in type string.

I am looked how I could solve this problem but not found solution.

**Comment by sergionegri** [comment] 2015-08-21 13:12
Same issue here, it worked in 2.6.3 and stopped working when migrated to 2.7.3

**Comment by lensky84** [comment] 2015-09-08 07:59
Hello! Someone could help me?

**Comment by giovkanata** [comment] 2015-09-08 09:46
Same problem here after migration to 2.7.3.

**Comment by craue** [comment] 2015-09-08 10:44
Same here.

**Comment by giovkanata** [comment] 2015-09-09 11:38
For me the problem was resolved with the last update at 2.7.4 version.

**Comment by craue** [comment] 2015-09-09 12:21
Confirmed.

**Comment by xabbuh** [comment] 2015-09-09 12:26
closing then

@lensky84 please comment if you still experience the issue with Symfony 2.7.4.

**Closed by xabbuh** 2015-09-09 12:26 UTC
Labels: Form

**Comment by lensky84** [comment] 2015-09-10 06:17
Yes.. problem solved with Symfony 2.7.4. Thanks
