### ISSUE TITLE
Intermittent Slow Completion of SessionHandlerProxy::read

### ISSUE THREAD

**Issue by CaptainStiggz** [symfony/symfony#18863] opened 2016-05-25 00:00 UTC
Hi, I posted my question on StackOverflow, which I'll repeat here.

http://stackoverflow.com/questions/37425786/symfony2-intermittent-high-response-time-slow-sessionhandlerproxyread-compl

I'm seeing very strange behavior that coming from the Symfony2 Session manager component. In particular, the SessionHandlerProxy::read() function is occasionally very slow in my production environment.

`Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::read`

I'm using Apache2, on an Amazon EC2 running Ubuntu, with default Symfony2 session storage (not Redis, or something similar), though I'm wondering if I should be.

**Comment by javiereguiluz** [comment] 2016-05-26 09:49
@CaptainStiggz we'll need more information about what's going on when the app slows down. Are there any patterns when that happens or is it totally random? Can you reproduce the same error in your local or staging environments? Right now we're clueless, so it looks like an Amazon EC2 issue instead of a Symfony issue.

**Comment by CaptainStiggz** [comment] 2016-05-26 20:00
@javiereguiluz thanks for getting back to me! I haven't been able to detect any patterns, and it only happens maybe once every couple days, seemingly randomly. I have not seen the problem crop up in either my dev/staging environments yet. I'm going to try switching over to the PdoSessionHandler and see if that helps - it's probably better for the long term anyways.

**Comment by javiereguiluz** [comment] 2016-10-06 18:31
@CaptainStiggz did you experience the same problems again? If yes, could you give us more details about how to reproduce the error? Thanks!

**Comment by jakzal** [comment] 2016-10-12 14:36
This is most likely caused by something outside of Symfony's control (like filesystem). See a similar issue with the Redis handler: #14043

@CaptainStiggz we cannot help much until you provide more information, like steps to reproduce your issue, or results of blackfire profiling. Therefore I'm going to close this. We'll reopen as soon as there's enough details provided to confirm this is a bug.

**Closed by jakzal** 2016-10-12 14:36 UTC
Labels: HttpFoundation, Unconfirmed
