### ISSUE TITLE
Symfony 5.1.8, Web Profiler Bundle: /_wdt gives a 404 error

### ISSUE THREAD

**Issue by makssof** [symfony/symfony#39085] opened 2020-11-15 13:01 UTC
**Symfony version(s) affected**: 5.1.8
Nginx: 1.17

**Description**  

Toolbar's the /_wdt page gives a 404 error
![image](https://user-images.githubusercontent.com/6056515/99185555-03dd9c00-2764-11eb-94af-60654994fc4d.png)

**How to reproduce**  
symfony new --full projectname

**Comment by maxhelias** [comment] 2020-11-15 13:14
It's pretty light as information, did you check the nginx configuration and logs that were returned? Or the php stack trace if there is ?

**Comment by makssof** [comment] 2020-11-15 14:59
> It's pretty light as information, did you check the nginx configuration and logs that were returned? Or the php stack trace if there is ?

nginx_error.log
2020/11/15 18:57:21 [error] 19256#18464: *1 CreateFile() "c:/openserver/openserver/domains/otve/public/_wdt/4e0e1b" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: otve, request: "GET /_wdt/4e0e1b HTTP/1.1", host: "otve"

**Comment by YaFou** [comment] 2020-11-15 20:12
It seems that the Nginx configuration is incorrect. I think Nginx does not redirect all the requests to the `index.php` file. Can you check your configuration? Do other pages work?

**Comment by chalasr** [comment] 2020-11-15 20:15
Closing as this is not a bug in Symfony. Consider using [our support platforms instead](https://symfony.com/support).

**Closed as completed by chalasr** 2020-11-15 20:15 UTC
Labels: Bug, Status: Needs Review
