### ISSUE TITLE
[HttpFoundation] FlashbagAwareSessionInterface

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#41765] opened 2021-06-21 14:02 UTC
**Description**
The current `SessionInterface` does not contain the method `getFlashBag`. As the DI way has been deprecated it's difficult to get correctly the FlashBag. 

The workaround currently is

```php
// Returns SessionInterface without getFlashBag
$session = $request->getSession();

if (method_exists($session, 'getFlashBag') {
$session->getFlashBag()->fooo();
}
```

or asserting that is a actual Session object which makes decoration shitty

**Example**

Introduce an additional interface to access the method `getFlashBag` on the interface level and not implementation.

**Comment by COil** [comment] 2021-06-29 05:54
Agree, I do this, yes, this is a little frustrating :  

        // use Symfony\Component\HttpFoundation\Session\Session;
        /** @var Session $session */
        $session = $request->getSession();

**Comment by jderusse** [comment] 2021-06-29 06:13
wait.. nothing told that `$this->get('session')` returns an instance of `Session`. So, replacing `$this->get('session'); // returns mixed` by `$request->getSession() //returns SessionInterface` is absolutely identical. In both case you can't be sure that the returned object will be an instance of `Session` but in both case you can be confident enough, that in the context of your application you'll get an instance of Session.

This issue is not related to Session deprecation (has the behavior remains the same). And is a duplicate of: #39222, #20258, #11279, #10036, #5568, #39222

**Comment by shyim** [comment] 2021-06-29 07:44
But the deprecation will remove also `session.flash_bag` from the DI. So it's related for me :D .

**Comment by nicodemuz** [comment] 2021-08-12 14:20
Thumbs up! I'm also getting an error on Psalm for this:
```
ERROR: UndefinedInterfaceMethod - src/Helper/FlashMessageHelper.php:34:25 - Method Symfony\Component\HttpFoundation\Session\SessionInterface::getFlashBag does not exist (see https://psalm.dev/181)
        $this->session->getFlashBag()->add('success', $message);
```

**Comment by ruudk** [comment] 2022-01-11 09:46
What about creating a `WithFlashBag` interface that holds `public function getFlashBag();` that can used as an intersection type on PHP 8.1: `SessionInterface&WithFlashBag`

**Closed as completed** 2022-07-03 14:29 UTC
Labels: Feature, HttpFoundation
