### ISSUE TITLE
Use symbolic link for vendor directory

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/symfony#18052] opened 2016-03-08 05:53 UTC
To speed up my vagrant machine, I'm using a symlink to take away the vendor directory from the NFS synced folder exactly like explained [here](http://jeremybarthe.com/2015/02/02/speed-up-vagrant-environment-symfony2/)

I get the following symlink which is expected:
<img width="647" alt="screen shot 2016-03-08 at 4 51 55 pm" src="https://cloud.githubusercontent.com/assets/1480617/13593306/1f6ff240-e54e-11e5-89fe-7f1b9ff22c31.png">

However, this breaks because the wrong location of the app folder is guessed in `DebugClassLoader.php`

<img width="1002" alt="screen shot 2016-03-08 at 4 46 52 pm" src="https://cloud.githubusercontent.com/assets/1480617/13593278/eb686ebe-e54d-11e5-9800-b1844a05eed8.png">

It should have been `/var/www/SyVagrant/app` not `/tmp/vagrant-cache/app`...

Are we not able to use a symlink for vendor directory?

**Comment by peterrehm** [comment] 2016-03-09 06:46
The problem is most likely this setting in your composer.json

````yaml
    "autoload": {
        "psr-4": { "": "src/" },
        "files": [ "app/AppKernel.php" ]
    },
````

I am using rsync instead of NFS to avoid all those related issues, maybe one can help you in getting any further feedback on how to get this working. Eventually a symlink from /tmp/vagrant-cache/app/AppKernel.php to /var/www/SyVagrant/app/AppKernel.php might resolve your issue.

**Comment by weaverryan** [comment] 2016-03-12 12:03
I would *love* if this worked, but it's a shortcoming in Composer. Check out your `vendor/composer/autoload_psr4.php` file. It starts like this:

```php
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);
```

The problem is that `$baseDir`: if you autoload *any* of your own files (e.g. `app/AppKernel` or event `src`), then Composer looks in the directory above it for where those should live. If you've symlinked the vendor directory, then it looks in the wrong spot.

The number of files that we read in the `vendor/` directory causes 95% of the perf problems in vagrant (assuming you don't have NFS or use Vagrant's rsync as @peterrehm suggested - both of those completely remove the issue). If this symlinking *did* work, then it might help to have a completely cross-OS solution (since Windows I believe can't use NFS).

More info on this topic in general: https://github.com/composer/composer/issues/4590

I'm going to close this issue here - unfortunately it needs to be "fixed" in Composer. Though if it were solved, it would make using Symfony in Vagrant easier for some people.

**Closed by weaverryan** 2016-03-12 12:03 UTC
Labels: Bug, Debug, Status: Needs Review, Unconfirmed

**Comment by dugwood** [comment] 2017-09-04 16:07
Big bad workaround (don't do this at home!):
 - edit `app/autoload.php`
 - add `require __DIR__.'/AppKernel.php';` just before the `return $loader;`

This will load the local AppKernel, which will resolve the correct rootDir (using its own `__DIR__` in `getRootDir()`).

To me it's not composer's fault, it's because Symfony doesn't use `autoload.php`'s __DIR__, which is the good file to determine where your Symfony is located. Or it could be `app.php` or `bin/console` that could send the real symfony's path, not loading it from within composer.

**Comment by dugwood** [comment] 2017-09-04 16:11
For example, in `app.php`:
`$kernel = new AppKernel('prod', false);`
 => could be initialized with `__DIR__`, which would fix it... if your `web/app.php` is __not__ a symlink :-D

**Comment by dugwood** [comment] 2017-09-05 11:35
In fact if you build the `bootstrap.php.cache` file, and copy it locally, it should work fine.
