### ISSUE TITLE
Deprecation warnings for form options I'm not using.

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony#21154] opened 2017-01-04 08:43 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.12

I created a FormType that extends the `AbstractType`. I have only a `buildForm` method in it which adds some fields. There are some fields which are other custom form types of mine, but those also only have the `buildForm` method, and if they have the `configureOptions` method, it's only to set a `data_class`.

However, when opening the page which uses this form, I'm getting the warnings

>The form option "read_only" is deprecated since version 2.8 and will be removed in 3.0. Use "attr['readonly']" instead.
> The "cascade_validation" option is deprecated since version 2.8 and will be removed in 3.0. Use "constraints" with a Valid constraint instead.
>The form option "csrf_provider" is deprecated since version 2.8 and will be removed in 3.0. Use "csrf_token_manager" instead.

But I'm not using any of these options. I'm even using the correct one for `cascade_validations`. These are the options of one form field I'm adding

```
[
    'data' => new Address(),
    'validation_groups' => ['productPreliminaryDeliveryAddress'],
    'mapped' => false,
    'constraints' => [new Valid()],
    'label' => false,
]
```

As you can see I'm using the correct option for constraint. Where does that error come from and how can I supress it?

**Comment by HeahDude** [comment] 2017-01-04 11:28
Hello @tzfrs are you sure your forms are not using any types from third party bundles or do you use any form type extensions that might set these options?

**Comment by xabbuh** [comment] 2017-01-04 11:35
The profiler may help you and give you the trace of where the option is actually set

**Comment by tzfrs** [comment] 2017-01-04 12:23
@HeahDude, Yes, I'm sure. A type I'm using extending the AbstractType and including another FormType which is extending the AbstractType. When I remove the include of the second type I don't get any deprecation warnings.

When I add the sub form type again and comment everything out in that class I get the deprecation errors again.

This is the stack trace

```
FormType::Symfony\Component\Form\Extension\Core\Type\{closure}() (called from OptionsResolver.php at line 965)
OptionsResolver::offsetGet() (called from FormType.php at line 196)
FormType::Symfony\Component\Form\Extension\Core\Type\{closure}() (called from OptionsResolver.php at line 965)
OptionsResolver::offsetGet() (called from OptionsResolver.php at line 791)
OptionsResolver::resolve() (called from ResolvedFormType.php at line 156)
ResolvedFormType::createBuilder() (called from ResolvedTypeDataCollectorProxy.php at line 89)
ResolvedTypeDataCollectorProxy::createBuilder() (called from FormFactory.php at line 114)
FormFactory::createNamedBuilder() (called from FormBuilder.php at line 106)
FormBuilder::create() (called from FormBuilder.php at line 269)
FormBuilder::resolveChildren() (called from FormBuilder.php at line 215)
FormBuilder::getForm() (called from FormFactory.php at line 40)
FormFactory::create() (called from Controller.php at line 282)
Controller::createForm() (called from ProductController.php at line 83)
ProductController::showAction()
call_user_func_array() (called from HttpKernel.php at line 144)
HttpKernel::handleRaw() (called from HttpKernel.php at line 64)
HttpKernel::handle() (called from ContainerAwareHttpKernel.php at line 69)
ContainerAwareHttpKernel::handle() (called from Kernel.php at line 185)
Kernel::handle() (called from app_dev.php at line 31)
```

I searched my whole project for the option `read_only`, `csrf_provider` and `cascade_validation` and didn't find any in my code or a library I'm using. Only in the Symfony code.

**Comment by HeahDude** [comment] 2017-01-04 12:44
OK, can you please show the output of `composer show -i`?

**Comment by tzfrs** [comment] 2017-01-04 13:13
Sure, here it is

```
aptoma/twig-markdown                 2.0.0                         Twig extension to work with Markdown content
cocur/slugify                        v2.3                          Converts a string into a slug.
contentful/contentful                0.6.5-beta                    SDK for the Contentful Content Delivery API
contentful/contentful-bundle         dev-master a76429ccc5bb337fe8 A Symfony2 Bundle to integrate the Contentful CDA SDK
doctrine/annotations                 v1.2.7                        Docblock Annotations Parser
doctrine/cache                       v1.6.0                        Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.3.0                        Collections Abstraction library
doctrine/common                      v2.6.1                        Common Library for Doctrine projects
doctrine/data-fixtures               v1.2.2                        Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.5.5                        Database Abstraction Layer
doctrine/doctrine-bundle             1.6.4                         Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0                         Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    v2.2.1                        Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  v1.2.0                        Symfony DoctrineMigrationsBundle
doctrine/inflector                   v1.1.0                        Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5                         A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1                        Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  1.4.1                         Database Schema migrations using Doctrine DBAL
doctrine/orm                         v2.5.5                        Object-Relational-Mapper for PHP
guzzlehttp/guzzle                    6.2.2                         Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.3.0                         Guzzle promises library
guzzlehttp/psr7                      1.3.1                         PSR-7 message implementation
incenteev/composer-parameter-handler v2.1.2                        Composer script handling your ignored parameter file
ircmaxell/password-compat            v1.0.4                        A compatibility library for the proposed simplified password hashing algorithm: https://wiki.php.net/rfc/password_hash
jdorn/sql-formatter                  v1.2.17                       a PHP SQL highlighting library
kriswallsmith/assetic                v1.3.2                        Asset Management for PHP
leafo/scssphp                        v0.6.6                        scssphp is a compiler for SCSS written in PHP.
liip/functional-test-bundle          1.6.3                         This bundles provides additional functional test-cases for Symfony2 applications
mapudo/common                        v1.1.0                        Common repository to eliminate duplicate code over multiple projects
mapudo/guzzle-bundle                 v1.0.0                        Integrates Guzzle into Symfony project and adds support for middleware
michelf/php-markdown                 1.6.0                         PHP Markdown
monolog/monolog                      1.21.0                        Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                    1.5.4                         Create deep copies (clones) of your objects
ocramius/package-versions            1.1.1                         Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager               2.0.3                         A library providing utilities to generate, instantiate and generally operate with Object Proxies
paragonie/random_compat              v2.0.2                        PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common      1.0                           Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    3.1.1                         With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          0.2                           
phpspec/prophecy                     v1.6.1                        Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            4.0.1                         Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            1.4.1                         FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1                         Simple template engine.
phpunit/php-timer                    1.0.8                         Utility class for timing
phpunit/php-token-stream             1.4.8                         Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      5.5.6                         The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         3.3.1                         Mock Object library for PHPUnit
psr/http-message                     1.0.1                         Common interface for HTTP messages
psr/log                              1.0.2                         Common interface for logging libraries
sebastian/code-unit-reverse-lookup   1.0.0                         Looks up which function or method a line of code belongs to
sebastian/comparator                 1.2.0                         Provides the functionality to compare PHP values for equality
sebastian/diff                       1.4.1                         Diff implementation
sebastian/environment                1.3.8                         Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   1.2.2                         Provides the functionality to export PHP variables for visualization
sebastian/global-state               1.1.1                         Snapshotting of global state
sebastian/object-enumerator          1.0.0                         Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context          1.0.2                         Provides functionality to recursively process PHP variables
sebastian/resource-operations        1.0.0                         Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.0                         Library that helps with managing the version number of Git-hosted PHP projects
sensio/distribution-bundle           v5.0.12                       Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.16                       This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.0.8                        This bundle generates code for you
sensiolabs/security-checker          v3.0.2                        A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.3                        Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.8.0                        Integrates Assetic into Symfony2
symfony/monolog-bundle               2.11.1                        Symfony MonologBundle
symfony/phpunit-bridge               v2.8.12                       Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.2.0                        Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu            v1.2.0                        Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.2.0                        Symfony polyfill for the Mbstring extension
symfony/polyfill-php54               v1.2.0                        Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55               v1.2.0                        Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56               v1.2.0                        Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.2.0                        Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.2.0                        Symfony utilities for portability of PHP codes
symfony/security-acl                 v3.0.0                        Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle           v2.3.11                       Symfony SwiftmailerBundle
symfony/symfony                      v2.8.12                       The Symfony PHP framework
twig/extensions                      v1.4.0                        Common additional features for Twig that do not directly belong in core
twig/twig                            v1.26.0                       Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.1.0                         Assertions to validate method input/output with nice error messages.
zendframework/zend-code              3.0.4                         provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager      3.0.1                         Trigger and listen to events within a PHP application
```

**Comment by tzfrs** [comment] 2017-01-04 13:20
No, it's one of mine and only extends the `AbstractType`. And when I put comments on every line of the file, I still get those deprecation warnings. I can suppress them, when I add the attributes and options manually, e.g.

`$builder->add('sub_type', SubType::class, ['attr' => ['readonly' => null]]`

If I do it like this I don't get the warnings, but this feels more like a workaround than a solution since I'm not setting the value at all.

**Comment by HeahDude** [comment] 2017-01-04 13:44
@tzfrs I could not trigger any deprecations on symfony 2.8.12.

Would you be able to fork symfony standard and add the minimum of code to reproduce your issue? Thanks!

**Comment by tzfrs** [comment] 2017-01-05 08:30
Hi, I may be able to do that on the weekend.

**Comment by tzfrs** [comment] 2017-02-02 07:33
Sorry for the late reply, I didn't come to fixing this sooner. I found the problem. I have a FormType A which gets a specific object passed to it. This FormType A adds another FormType B I created which also needs the same data, so I had the method like this

```
public function buildForm(FormBuilderInterface $builder, array $Options)
{
    $options['label'] = false;
    $options['mapped'] = false;
    $builder->add('foo', BarType::class, $options);
}
```

This led to the other FormType B reusing the options of the FormType A and somehow the deprecated settings were set. However it seems like it's okay if the Framework sets it, I get the deprecation warnings just if I use them.

So, after changing the code to

```
public function buildForm(FormBuilderInterface $builder, array $Options)
{
    $builder->add('foo', BarType::class, [
        'mapped' => false,
        'label' => false,
        'data' => $options['data'],
    ]);
}
```

it works without problems. Maybe there's a better way to use the same object in two forms where one is called from within the other? If yes, I would be pleased to hear suggestions.

**Comment by javiereguiluz** [comment] 2017-02-02 07:35
Thanks for posting more details. I'm closing this because you say it's working now. But if other people have suggestions about doing this better, they can add new comments. Thanks!

**Closed by javiereguiluz** 2017-02-02 07:35 UTC
Labels: Bug, Form, Unconfirmed

**Comment by HeahDude** [comment] 2017-02-02 09:22
Thanks @tzfrs for the feedback. You solved it the right way I think, you were passing resolved options to resolve them again, but the resolved options were triggering deprecations in the process.

I don't see another way to solve this, but be aware that this usage has a limitation, you can't use the same type you're defining in the class. I mean your sample code could not live in the `BarType` itself but another.
