### ISSUE TITLE
Using services.yaml AND services.xml -> problem autowiring

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#33360] opened 2019-08-27 12:08 UTC
**Symfony version(s) affected**: 4.3.4

**Description**  
I am using `services.yaml` (from the new setup) and `services.xml` from the legacy project.
Both should work well together, but when clearing the cache I get the following error:

_In DefinitionErrorExceptionPass.php line 54:_
**Cannot autowire service "App\EventListener\SendAusgehendeEmailnachrichtListener": argument "$mailerUsername" of method "__construct()" is type-hinted "string", you should configure its value explicitly.**

But its definied explicitely by an env var:
```xml
<argument key="$mailerUsername">%env(MAILER_USERNAME)%</argument>
```

**How to reproduce**  
**services.yaml**
```yaml
# services.yaml
parameters:
    container.autowiring.strict_mode: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Scripts,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```

**services.xml**
```xml
<?xml version="1.0" ?>
<container xmlns="http://symfony.com/schema/dic/services"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd"
>

  <services>
    <defaults autowire="true" autoconfigure="true" public="false" />

    <service id="App\EventListener\SendAusgehendeEmailnachrichtListener">
      <argument key="$om" type="service" id="Doctrine\Common\Persistence\ObjectManager" />
      <argument key="$factory" type="service" id="App\Mail\AusgehendeEmailnachrichtMessageFactory" />
      <argument key="$mailer" type="service" id="mailer" />
      <argument key="$requestStack" type="service" id="request_stack" />
      <argument key="$mailerUsername">%env(MAILER_USERNAME)%</argument>
      <argument key="$mailerPassword">%env(MAILER_PASSWORD)%</argument>
      <argument key="$logger" type="service" id="logger" />
    </service>
    
  </services>
</container>
```

I cann fix it by defining it manually:
```diff
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
+        bind:
+           $mailerUsername: '%env(MAILER_USERNAME)%'

# ...
```

**Comment by stof** [comment] 2019-08-27 12:20
the issue is that you define your service twice: once explicitly in the services.xml file, and once in the services.yaml file with your `App\` resource. I suspect that your YAML file is processed after the XML one, and so the YAML definition (which was not configuring the mailer username) wins over the XML one (which configures it)

**Comment by xabbuh** [comment] 2019-08-27 14:13
I am closing as explained there is no bug. Thank you for understanding.

**Closed by xabbuh** 2019-08-27 14:13 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
