### ISSUE TITLE
Cannot access the container from inside a controller

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#23200] opened 2017-06-15 15:51 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| Symfony version  | 3.3.2

I'm migrating my app from Symfony 2.8 to Symfony 3.3.

_NOTE: I'm not upgrading the 2.8 version, but installed a fresh project of Symfony 3.3 and moving all relvant files to it from the old 2.8 Symfony project._

From inside a controller of mine I have this:

    public function indexAction()
    {
        $email = new Email();

        $form = $this->createForm(GetStartedType::class, $email, [
            'action' => $this->generateUrl('get_started_end'),
            'method' => 'POST',
        ]);

        return [
            'form' => $form->createView(),
        ];
    }

But I receive this exception:

> Call to a member function get() on null

My controller extends `Symfony\Bundle\FrameworkBundle\Controller\Controller`:

    /**
     * {@inheritdoc}
     */
    class DefaultController extends Controller
    {
    ...
    }

So I have access to the container.

Putting some dumps around in the Symfony's code, I see that the container is correctly set:

    namespace Symfony\Component\DependencyInjection;
    
    /**
     * ContainerAware trait.
     *
     * @author Fabien Potencier <fabien@symfony.com>
     */
    trait ContainerAwareTrait
    {
        /**
         * @var ContainerInterface
         */
        protected $container;
    
        /**
         * Sets the container.
         *
         * @param ContainerInterface|null $container A ContainerInterface instance or null
         */
        public function setContainer(ContainerInterface $container = null)
        {
            dump('Here in the ContainerAwareTrait');
            dump(null === $container);
            $this->container = $container;
        }
    }

This dumps

    Here in the ContainerAwareTrait
    false

So the autowiring works well and sets the container.

But in the `ControllerTrait` I have this:

    trait ControllerTrait
    {
        /**
         * Generates a URL from the given parameters.
         *
         * @param string $route         The name of the route
         * @param mixed  $parameters    An array of parameters
         * @param int    $referenceType The type of reference (one of the constants in UrlGeneratorInterface)
         *
         * @return string The generated URL
         *
         * @see UrlGeneratorInterface
         */
        protected function generateUrl($route, $parameters = array(), $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
        {
            dump('Here in the ControllerTrait');
            die(dump(null === $this->container));
            return $this->container->get('router')->generate($route, $parameters, $referenceType);
        }
    
        ...

this is the dump:

    Here in the ControllerTrait
    true

**So here the `container` is `null` and this causes the error.**

**Anyone can help me solve this issue?**

**Why is the `container` null?**

If may help, this is the `services.yml` configuration (the default that cames with Symfony):

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

This issue is a copy and paste of a [Stackoverflow question I opened](https://stackoverflow.com/q/44571013/1399706).

**Comment by stof** [comment] 2017-06-15 16:07
Can you provide a reproducing case ?

**Comment by Aerendir** [comment] 2017-06-15 16:18
Reproducing case? How I could? Is an entire app!

More than the code of the controller I cannot give... It is a lot of code!

Maybe you know some fine details I can check other than the involved traits (`ContainerAwareTrait` and `ControllerTrait`)...

**Comment by stof** [comment] 2017-06-15 16:26
Well, if you cannot recreate the issue in a project you can share with us (create a new Symfony 3.3 project and add the code needing to reproduce the issue), we don't have any way to debug the issue as we don't have access to your app (you are the first one reporting this issue, so you probably have something special in the way you use Symfony).

**Comment by Aerendir** [comment] 2017-06-15 18:28
But to recreate the issue I should already know which the cause is, and this is exactly what I'm trying to understand! o.O

How can I reproduce something of which I don't know the cause?

Just because is something specific to my way of using Symfony (that, anyway, is the "normal" way of using it, relying on its built-in functionalities) is something that I cannot reproduce in a fresh installation of the framework.

For this reason I were asking for some suggestions on how to debug the issue.

For example, I will do the following two things:
1. Disable the autowiring at all to understand if the cause is the autowiring itself or not;
2. Enabling the autowiring again and dump the class assigned ID, both in `ContainerAwareTrait` and 
 in `ControllerTrait` to understand if the autowired class is the same I'm using in my controller;

I'm asking for this kind of advice, that can help me debug the issue in _my_ project, with _my_ way of using Symfony, also to understand if it really is a bug to fix or if it is a mistake of mine.

**Comment by Aerendir** [comment] 2017-06-15 18:35
**TEST 1: Disable the autowiring**
_Expected result: the controller works as expected._

To disable the autowiring functionality on controllers I did this in my `services.yml`:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests,EventListener,Validator,Twig}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    #AppBundle\Controller\:
    #    resource: '../../src/AppBundle/Controller'
    #    public: true
    #    tags: ['controller.service_arguments']

```

1. I added the `AppBundle/Controller` folder to the `exclude` of `AppBundle\` node;
2. Commented all the section related to `AppBundle\Controllers`.

**RESULT: The controller worked as expected showing the page. The Exception is gone away.**
**CONCLUSION: The problem is somthing related to the autowire functionality.**

**Comment by Aerendir** [comment] 2017-06-15 19:03
TEST 2: Skipped

**TEST 3: Try to explicitly call the `setContainer` method on the controllers**
_Expected result: The controller action works as expected_

With this configuration in `services.yml`:

```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,EventListener,Validator,Twig}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
```

The issue is resolved: the controller shows the page and no exception is thrown.

So the problem, I think, is with the tag `controller.service_arguments`: this should call automatically the `setContainer` method on controllers that implements the `ContainerAwareInterface`, doesn't it?

It doesn't, but I don't know if this is the right behavior or not.

**Comment by vincentpazeller** [comment] 2017-06-16 09:24
I just upgraded from 3.2.x to v3.3.0 and I encountered that exact same problem. Adding 
```
calls:
        - [setContainer, ["@service_container"]]
```

Fixed the problem immediately (thanks for the trick). So I guess there is something broken in the service_container automatic injection

Best Regards

**Comment by xabbuh** [comment] 2017-06-16 09:57
@vincentpazeller Are you able to provide a small reproducer?

**Comment by Aerendir** [comment] 2017-06-16 11:12
@xabbuh On my side, I'm not able to provide it. Maybe is the default behavior with any new Symfony 3.3 installation... Did you try (I have t ask, forgive me!)...

**Comment by ogizanagi** [comment] 2017-06-16 11:45
I did try with both symfony-demo and a fresh install using `symfony new`, but I'm unable to reproduce the issue on my side.

**Comment by vincentpazeller** [comment] 2017-06-16 11:57
I just created a dummy new project and, unfortunately, I could not reproduce the problem easily (this works well with the new project)... I am sorry, I don't have much time to assign to this issue...

**Comment by Aerendir** [comment] 2017-06-16 11:59
So, the correct behavior would be to automatically inject the container into controllers tagged as `controller.service_arguments`, is it?

**Comment by vincentpazeller** [comment] 2017-06-16 12:15
Yes, thats right. The problem was that the Controller's container property was null and when invoking the get method on it, an exception was triggered...

**Comment by Aerendir** [comment] 2017-06-16 13:48
@vincentpazeller yes, and this is not the correct behavior... I'll investigate deeper ASAP... Maybe I'll discover the problem... Fingers crossed...

**Comment by nicolas-grekas** [comment] 2017-06-16 13:57
There is a misunderstanding here: `controller.service_arguments` does NOT mean "inject the container".
The things that trigger automatic injection of the container are implementing the `ContainerAwareInterface` or implementing the `ServiceSubscriberInterface` one basically.

**Comment by ogizanagi** [comment] 2017-06-16 13:58
I may have found the issue and reproduced it in https://github.com/ogizanagi/sf-issue-23200.
See https://travis-ci.org/ogizanagi/sf-issue-23200
The issue happen when using the `service:method` notation from routing: https://github.com/ogizanagi/sf-issue-23200/commit/c19c0eeb87f87a6eb54e551a1fc33cc1ed4ad39f, while it works perfectly when using the `a:b:c` (`AppBundle:Default:index`) one.

Do you think it's related to your issue?

I can suggest [a fix](https://github.com/symfony/symfony/compare/master...ogizanagi:fix/base_controller_required_call) to allow autowiring to properly add the `setContainer` method call by marking it as `@required` but I'm not sure it really make sense. If you're using your controller as a service, you'll probably avoid extending the base `Controller` and inject the container, or you'll rely on the new `AbstractController`, in which the method call is already required.

**Comment by Aerendir** [comment] 2017-06-16 15:35
@nicolas-grekas , my controllers extend `Symfony\Bundle\FrameworkBundle\Controller\Controller` that implements `Symfony\Component\DependencyInjection\ContainerAwareInterface`, so the autowired injection could happen... Doesn't it?

@ogizanagi I'll investigate if this is my case and I'll tell you...

**Comment by Aerendir** [comment] 2017-06-16 15:42
@ogizanagi 

My `routing.yml` file is this:

```yaml
app:
    resource: '@AppBundle/Controller/'
    type: annotation
```

And the annotations on controller are these:

```php
    /**
     * This has to be the last method, as it is the most generic of all.Fix.
     *
     * @Route("/", name="page_homepage")
     * @Template()
     */
    public function indexAction()
    {
        $email = new Email();

        $form = $this->createForm(GetStartedType::class, $email, [
            'action' => $this->generateUrl('get_started_end'),
            'method' => 'POST',
        ]);

        return [
            'form' => $form->createView(),
        ];
    }
```

So, I think it's not the same as the reproduction you provided...

Anyway you hit the point and demonstrated that a bug exists...

Maybe that the routing mechanism does something that in concrete creates the same sistuation you reproduced...

**Comment by Aerendir** [comment] 2017-06-16 15:44
Thinkin abstractly, the autowiring functionality does exactly this: `controller:method`, where the controller part becomes also the service ID.

So maybe that the two problems are related...

**Comment by ogizanagi** [comment] 2017-06-16 17:06
If you're using annotations, the `_controller` param in the route will be [resolved to use the `class::method` notation](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/Routing/AnnotatedRouteControllerLoader.php#L47). Usually, it'll simply use the `new` operator to create an instance, but in the framework and using the default config suggested by the defaults provided in the standard-edition, it happens you've got a service named after the FQCN, so it'll reuse the instance in the container. 

But there is no autowiring here expected to inject the container: the service definition won't be added a `setContainer` method call. It's a runtime injection performed by the FrameworkBundle [ControllerResolver](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L62-L64) based on a `instanceof ContainerAwareInterface` check (and still works on my side :/).

**Comment by Aerendir** [comment] 2017-06-16 17:30
So, the behavior I'm experiencing is right? It works as expected? Have I to explicitly set the container? Also if in the documentation is stated that this should be automatically done?

**Comment by ogizanagi** [comment] 2017-06-16 17:42
No. I'm not saying the behavior you're experiencing is right. I'm still in troubles identifying/reproducing your issue. 

I'm only expressing facts. You talk a lot about "autowired injection of the container":
> my controllers extend Symfony\Bundle\FrameworkBundle\Controller\Controller that implements Symfony\Component\DependencyInjection\ContainerAwareInterface, so the autowired injection could happen... Doesn't it?

I'm just saying there isn't any container autowiring expected currently by extending `Controller` or implementing `ContainerAwareInterface`. This is only runtime injection, once the controller is resolved. 
Autowired injection is made by using the `AbstractController` which implements `ServiceSubscriberInterface`, hence a `setContainer` method call is added to the service definition with a specific PSR-11 container instance containing services described in `ServiceSubscriberInterface::getSubscribedServices()`.

Hope it's a bit clearer.

**Comment by Aerendir** [comment] 2017-06-16 18:17
Really more more clear!!!

Then I'll try to extends such `AbstractController` to see if the error goes away...

**Comment by trappar** [comment] 2017-06-17 00:00
I'm getting this same issue I think. I'm trying to switch to autowiring and I'm using essentially the symfony standard services.yml. When one of my controllers extends `\Symfony\Bundle\FrameworkBundle\Controller\Controller` I get a null container in the controller. When it extends `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` I get a container, but no ability to use it directly obviously, which breaks my code. I'm not ready at this point to switch over to injecting services into action methods through the method parameters, so this is a real problem. This also doesn't seem like this should be an issue according to [this doc](http://symfony.com/doc/current/service_container/3.3-di-changes.html).

**Comment by trappar** [comment] 2017-06-17 00:17
I have determined that in my case this was caused by using the `JMSDiExtraBundle`. Unregistering that bundle from my kernel fixed the issue. It appears that this was because that bundle was taking over control of instantiating controllers. Specifically [the `instantiateController` method](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/HttpKernel/ControllerResolver.php#L76-L90) which does not inject the container if the controller is a service.

@Aerendir: Are you also using this bundle in your project?

**Comment by Aerendir** [comment] 2017-06-17 10:38
@trappar for your first problem (you cannot access the services in the container) maybe that setting them all to `public: true` may solve the problem, then you'll can refactor the code to make less use of direct access to the container and when ready set them again as private (`public: false`).

For your second question: yes, I use the `JMSDiExtraBundle` only in develoment as it is required by `JMSTranslationsBundle`: as I manage translations only on development, I don't use it in production, but I didn't tested the behavior in production (and for really good reasons! :P)

**Comment by bogdaniel** [comment] 2017-06-18 17:43
@Aerendir the problem is from that JMSDiExtraBundle. Tried using it yesterday because of the JMSTranslationBundle .. and i found out it breaks the container. Your getting get() null because i think it won't load the container. Didn't try to stay longer on it because i only wanted to test out the translation bundle.

**Comment by xabbuh** [comment] 2017-06-20 17:06
I think I was able to reproduce the issue. Can you please check if #23239 fixes it for you?

**Comment by robfrawley** [comment] 2017-06-20 20:30
It resolved the issue for me in an older project I'd upgraded to latest Symfony (with this patch)!

**Comment by Aerendir** [comment] 2017-06-22 08:00
@xabbuh , this didn't solved my issue, instead.

Going deeper, I've tried to put a simple `die(dump('here it is))` at the beginning of the method `ControllerResolver::createController()` and it is never intercepted... As if the method is never called...

Can this depend by the fact I'm using `JMSDiExtraBundle` and `JMSTranslationBundle`? Removing both of them (plus removing `JMSAopBundle`) I now receive an error in Twig about an invalid resource provided.

This means for me that the problem is actually `JMS*Bundle`s as they do somthing that broke the autowiring functionality.

Because if I receive an error in Twig, this means the controller is correctly created, and the controller set as the routes and all other short methods can work regularly...

So the problem, is in JMS bundles...

**Comment by xabbuh** [comment] 2017-06-22 08:14
@Aerendir Yes, that PR indeed does not tackle any issues related to JSMDiExtraBundle. If they are replacing the core controller resolver, it's likely that something needs to be changed over there.

**Comment by stof** [comment] 2017-06-22 08:29
Yeah, JMSDiExtraBundle replaces the controller resolver, and their own implementation may not support all new features added in the Symfony core one.

**Comment by trappar** [comment] 2017-06-22 19:14
Also see my comment saying this 5 days ago :P

**Comment by xabbuh** [comment] 2017-07-03 14:55
closing here as this should be fixed by #23239

**Closed by xabbuh** 2017-07-03 14:55 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback

**Comment by Aerendir** [comment] 2017-07-04 12:10
@xabbuh Yes, ok... If the problem will persist also after the update, I'll repost here... Thank you!

**Comment by LearnForInterest** [comment] 2018-05-31 00:56
i encounter the very same prob out of nowhere . did not upgrade or do any maneuver pf any kind.... solved inmmediately by adding 
        calls:
            - [setContainer, ["@service_container"]]
thx a lot

**Comment by xabbuh** [comment] 2018-05-31 08:55
Please open a new issue with a reproducable example as comments on closed issues are likely to get lost.

**Comment by william-greatcontent** [comment] 2018-10-23 22:50
Hello, I am having a similar issue with Symfony 3.4, but not with the controller, with a custom validator I created. Here is my question in StackOverflow.

https://stackoverflow.com/questions/52933580/this-getcontainer-is-returning-null-in-symfony-3-x

I am desperately seeking some help on this topic as I am stuck for last 2 days and the whole project is in halt. Any help will be very much appreciated. Thank you in advance.

**Comment by trappar** [comment] 2018-10-23 23:07
@william-greatcontent I believe your comment here is off topic, but I went ahead and answered it on SO for you.
