### ISSUE TITLE
Several validators generate a server error if they receive an array

### ISSUE THREAD

**Issue by -Jerry-** [symfony/symfony#17758] opened 2016-02-11 01:27 UTC
If you validate a form field with, for instance, `Symfony\Component\Validator\Constraints\Length` and submit the form with the value of the field as an array, the `LengthValidator` will throw an `UnexpectedTypeException`, generating a 500 response, instead of adding a violation to the form field.

I tried to work around this issue by adding a `Type` constraint, but the `Length` constraint seems to be validated first. I also believe that most of the constraints that are affected (see the bottom of this issue) should implicitly validate the type as well. Having to add `Constraints\Type("File")` to an already existing `Constraints\File` seems counter-intuitive to me.

To reproduce this, consider the following form type:

``` php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\Extension\Core\Type as FormType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints;

class TestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('test', FormType\TextType::class, array(
                'constraints'   => array(
                    new Constraints\NotBlank(),
                    new Constraints\Length(5),
                ),
            ))
        ;
    }
}
```

If you submit the following request, you will receive an error page:

```
POST / HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded
Content-Length: 19

test[test][foo]=bar
```

This is due to the following piece of code which is present in `Symfony\Component\Validator\Constraints\LengthValidator`:

``` php
    public function validate($value, Constraint $constraint)
    {
        // [...]
        if (!is_scalar($value) && !(is_object($value) && method_exists($value, '__toString'))) {
            throw new UnexpectedTypeException($value, 'string');
        }
        // [...]
    }
```

Similar checks seem to be present in the following constraints:
`Country`, `Currency`, `DateTime`, `Date`, `Email`, `File`, `Iban`, `Ip`, `Isbn`, `Issn`, `Language`, `Length`, `Locale`, `Regex`, `Time`, `Url`, `Uuid`

**Comment by iltar** [comment] 2016-02-11 09:22
If you send the data as an array instead of the value you expect it to be, that means something has been changed and it cannot be mapped back either way. If you modify your forms client side and send them incorrectly, you should be notified of this. If your visitor does this, they deserve no less than a 500 error for messing around with things they shouldn't do.

**Comment by jakzal** [comment] 2016-02-11 12:47
@-Jerry- what would you expect to happen instead of the currently thrown `UnexpectedTypeException`?

**Comment by -Jerry-** [comment] 2016-02-11 13:44
@iltar I think Symfony should be able to handle manipulated requests like these. 500 is an _Internal Server Error_, but this is clearly not a server error because it is triggered by a specially crafted request from a client. You might argue that this is a bug in my form because I didn't check the type of the field, but explicitly adding a `Type` constraint doesn't help, either.

@jakzal I expected the validator to just fail validation for the selected field. If I add a `Length` constraint, clearly the intention is for users to specify a value that can have a length. (You could argue that arrays have a length, but we have the `Count` constraint for that.) For the other validators, it's more obvious: An array is obviously not a date, an e-mail, a file, a URL, ..., so if I want to validate the value as one of these, it should fail validation if the user specifies an array.

**Comment by xabbuh** [comment] 2016-02-12 16:21
Couldn't we handle this in the Form layer when the request data is bound?

**Comment by lordjancso** [comment] 2017-05-23 06:00
Is there any news on this one? I'm having the same annoying problems with validator. I expected Type validator will help, but unfortunately not.
Do we have any workaround until a proper solution? @-Jerry- how did you manage this in the past year? :)

**Comment by apfelbox** [comment] 2017-05-23 14:44
To me it would make sense that a validator never throws, but instead always adds a validation constraint.

An error 500 is a crash of the application. The application should never crash. Core functionality of the framework that directly works with user provided data should be robust in a way, that the app will never crash just by manipulating the data on the client side.

wdyt?

**Comment by xabbuh** [comment] 2017-05-23 15:27
I tend to agree that this is not something that should happen. Especially, given the fact that this part of the framework is precisely about validating the user's input.

**Comment by xabbuh** [comment] 2017-06-21 15:12
closing as a duplicate of #14943

**Closed by xabbuh** 2017-06-21 15:12 UTC
Labels: Bug, Status: Needs Review, Validator
