### ISSUE TITLE
Very slow download speed from symfony installation file

### ISSUE THREAD

**Issue by gundamftw** [symfony/symfony#34826] opened 2019-12-05 06:55 UTC
I have download and run the setup file to install symfony, but the download speed in the installer is very slow. It starts out at 40 KB/s, and 12 minutes in it has dropped to 24 KB/s.

https://symfony.com/download

**Comment by javiereguiluz** [comment] 2019-12-05 12:22
Thanks for reporting this issue. However, I can't reproduce. In my case, the 8 MB of the Symfony CLI takes 3 seconds to download:

![symfony-download](https://user-images.githubusercontent.com/73419/70234906-0537d380-1762-11ea-9e8a-0d7b829af2f5.gif)

As you can see in the output of the command, we download the Symfony CLI packages directly from GitHub:

![github-download](https://user-images.githubusercontent.com/73419/70234936-154fb300-1762-11ea-9e5b-37bb7f2d6cb8.png)

Maybe there was some momentary issue with GitHub network? Maybe your network (or your company, etc.) has throttled GitHub downloads somehow?

We're closing for now as "probably a temporary thing" ... but we'll reopen this if we get more reports from other users. Thanks!

**Closed by javiereguiluz** 2019-12-05 12:22 UTC
