### ISSUE TITLE
Nullable nested field in OptionsResolver will fail if provided with null

### ISSUE THREAD

**Issue by hubertnnn** [symfony/symfony#39569] opened 2020-12-18 17:43 UTC
**Symfony version(s) affected**: 4.4.15

**Description**  
When defining an options resolver that contains a nullable nested field, 
it will error out when providing null as a value.

**How to reproduce**  
```
        $structure = new OptionsResolver();
        $structure->setDefined(['price']);
        $structure->setAllowedTypes('price', ['array', 'null']);
        $structure->setDefaults([
            'price' => function (OptionsResolver $priceResolver) {
                $priceResolver->setDefined(['amount', 'currency']);
                $priceResolver->setRequired(['amount', 'currency']);
                $priceResolver->setAllowedTypes('amount', 'integer');
                $priceResolver->setAllowedTypes('currency', 'string');
            },
        ]);

        $data = [
            'price' => [
                'amount' => 1,
                'currency' => 'USD',
            ],
        ];
        dump($structure->resolve($data)); // Works fine

        $data = [
            'price' => null,
        ];
        dump($structure->resolve($data)); // Throws exception:
        // The nested option "price" with value null is expected to be of type array, but is of type "NULL".
```

**Comment by yceruto** [comment] 2020-12-19 17:57
By definition, a nested option must be an array. It's documented here:

> The fact that an option is defined as nested means that you must pass an array of values to resolve it at runtime.
https://symfony.com/doc/current/components/options_resolver.html#nested-options

You should pass an empty array instead.

Closing as this is not a bug. Thanks for reporting!

**Closed as completed by yceruto** 2020-12-19 17:57 UTC
Labels: Bug, OptionsResolver, Status: Needs Review

**Comment by hubertnnn** [comment] 2021-01-22 09:22
I still think that its a bug. 
Its extremely limiting to only allow empty arrays.
There is a difference between a null and an empty array.

Even if I use an empty array then how should I do my example, where both amount and currency are required if price is provided?
If I set both fields as required then I am not allowed to send an empty array.
If I make them both optional and change it from empty array to null in post-processing then:
- I am normalizing input in 2 different places (OptionsResolver and PostProcessor)
- Nothing prevents user from sending only amount without currency, or only currency, so the whole purpose of using OptionsResolver is pointless.

**Comment by yceruto** [comment] 2021-01-22 13:19
@hubertnnn the `OptionsResolver` component is not designed to work directly with post-processing, that's the `Form` component used for.

It's about "options" only. The fact you're defining `amount` and `currency` options as required means you must provide them always (regardless of whether the price option is null or not) in the same way as the `amount` option expects an integer value always, they are inviolable constraints.

Btw, this statement `$structure->setAllowedTypes('price', ['array', 'null'])` doesn't work (for null) upon define it as nested option. That's why we add a note in the documentation.

**Comment by hubertnnn** [comment] 2021-01-25 09:41
Ok, since it looks like this bug won't get fixed, I will share a workaround I found with help of stackoverflow.
I hope it helps anyone coming here from google with the same problem.

```
        $structure = new OptionsResolver();
        $structure->setDefined(['price']);
        $structure->setAllowedTypes('price', ['array', 'null']);
        $structure->setDefaults([
            'price' => null,
        ]);
        $structure->setAllowedValues('price', function (&$price) {
            if (null === $price) {
                return true;
            }

            $priceResolver = new OptionsResolver();
            $priceResolver->setDefined(['amount', 'currency']);
            $priceResolver->setRequired(['amount', 'currency']);
            $priceResolver->setAllowedTypes('amount', 'integer');
            $priceResolver->setAllowedTypes('currency', 'string');

            $price = $priceResolver->resolve($price);
            return true;
        });
```

The only limitation of this workaround is that the exception will not contain the full path to invalid field, just its name.
