### ISSUE TITLE
DbalLogger normalizeParams is somehow modifying the params passed to the actual update query

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#25921] opened 2018-01-25 05:27 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

First off everything I know about PHP pass by value etc means what I'm reporting should not be possible. The DbalLogger is modifying the parameters that are being submitted with an update.

Here's the situation I have an entity with a property of type array (I've tested json and json_array) all suffered from the same behaviour. I traced this down via xdebug and PhpStorm but don't believe it...

Given the property updated with values:

```
Array (
    [0] => Array (
            [id-q7cwkksmr] => Array (
                    [id] => id-q7cwkksmr
                    [x] => 114.5
                    [y] => 698
                    [width] => 77
                    [height] => 23
                    [property] => Contract-Buyers-Bobby Tables-Full Name
                )
        )
)
```

Once the logger gets through with it the params submitted for update end up being:

```
Array (
    [0] => Array (
            [id-q7cwkksmr] => Array (
                    [id] => id-q7cwkksmr
                    [x] => 114.5
                    [y] => 698
                    [width] => 77
                    [height] => 23
                    [property] => Contract-Buyers-Bobby Tables-F [...]
                )
        )
)
```

Note the [...]

This is because on line 90 of DbaLogger it tests that the parameters are longer than self::MAX_STRING_LENGTH (value of 32).  This makes sense for logging. The only way I can think of solving this is the normalizeParams needs to work on a copy of the params. This would cause an increase in memory usage.

Thoughts? I can submit a PR but wanted to report the issue first.

I'm actually quite confused by this since arrays should be passed by value so I don't know why this is happening other than this code is somehow modifying the original array...

With some dirty debugging if I comment out lines 1044-1047 of the DBAL [Connection,](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L1054) the behaviour goes away.

**Comment by derrabus** [comment] 2018-01-25 10:55
Can you provide a small repository that reproduces the bug?

**Comment by gnat42** [comment] 2018-01-26 00:06
Not yet - for whatever reason a very simple example doesn't do this - which is what I would expect. I just can't see why its happening for me. If this happened all the time *everyone* would be filing a bug.

**Comment by bdecarne** [comment] 2018-02-12 16:17
Hi,

I was confronted to this "bug". It happened because my array contains references. Please check your array, it seems to have the following structure :

```
array (
    [0] => array (
            [id-q7cwkksmr] => & array (
                    [id] => id-q7cwkksmr
                    [x] => 114.5
                    [y] => 698
                    [width] => 77
                    [height] => 23
                    [property] => Contract-Buyers-Bobby Tables-Full Name
                )
        )
)
```

**Comment by gnat42** [comment] 2018-02-12 16:38
how can I tell that it has references? I can see your structure there. I know I do process the array in a for loop using references but why that results in this behaviour I don't know. I would love to know how to reproduce it.

**Comment by bdecarne** [comment] 2018-02-13 16:07
Using the **dump** function from Symfony VarDumper Component, you can easily see references : 

![image](https://user-images.githubusercontent.com/1277131/36159930-3cec737e-10e0-11e8-83ac-760e63104533.png)

Just do : 
```
dump($params)
```

**Comment by xabbuh** [comment] 2018-02-21 08:51
Closing here for now. We can consider to reopen if we have a reproducable project.

**Closed by xabbuh** 2018-02-21 08:51 UTC
Labels: Status: Waiting feedback, Unconfirmed
