### ISSUE TITLE
[PhpUnitBridge] Invalid expected deprecations

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#21982] opened 2017-03-12 22:56 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6 (possibly earlier)

From https://symfony.com/doc/current/components/phpunit_bridge.html#write-assertions-about-deprecations:

```php
/**
 * @group legacy
 * @expectedDeprecation This "%s" method is deprecated.
 * @expectedDeprecation The second argument of the "%s" method is deprecated.
 */
public function testDeprecatedCode()
{
    @trigger_error('This "Foo" method is deprecated.', E_USER_DEPRECATED);
    @trigger_error('The second argument of the "Bar" method is deprecated.', E_USER_DEPRECATED);
}
```

However if you write:

```php
/**
 * @group legacy
 * @expectedDeprecation Wrong message
 */
public function testDeprecatedCode()
{
    @trigger_error('This "Foo" method is deprecated.', E_USER_DEPRECATED);
    @trigger_error('The second argument of the "Bar" method is deprecated.', E_USER_DEPRECATED);
}
```

You won't get any error.

[demo](https://github.com/theofidry/phpunitbridge-demo0)

![screen shot 2017-03-12 at 22 56 53](https://cloud.githubusercontent.com/assets/5175937/23836888/4076f0e6-0777-11e7-8c0f-816efc48e31c.png)

Were you would expect 2 remaining deprecation notices, not 1.

**Comment by xabbuh** [comment] 2017-03-13 10:49
When running the `phpunit` script provided by PHPUnit, you need to manually take care of registering the `SymfonyTestListener` which will handle the `@expectedDeprecation` annotation. The `DeprecationErrorHandler` (which registers itself through Composer's autoloading) is only about dealing with silenced deprecations and checking for the special `legacy` group when it detects deprecations. It does not deal in any way with the `@expectedDeprecation` annotation (thus it does not care about the actual message being emitted by the tested code).

I am closing here as this is the intended behaviour.

**Closed by xabbuh** 2017-03-13 10:49 UTC
