### ISSUE TITLE
Is it possible to make xdebug.file_link_format work from a VM

### ISSUE THREAD

**Issue by dupuchba** [symfony/symfony#14340] opened 2015-04-13 16:35 UTC
Hi all,

I am actually using vagrant @work and I just discover the magic with `xdebug.file_link_format` which work well outside my vagrant.

Here is my problem, when I trie to click on the debug tool bar on my controller name to be redirected IDE, It open my IDE but with my vagrant's path like this : 

![capture_d ecran_2015-04-13_a_18_33_18](https://cloud.githubusercontent.com/assets/911705/7120209/b4621c8a-e20b-11e4-83b9-75301cc44386.png)

It seems quite normal to me, as I am using a VM. 

My question : 
> Is there a way to rewrite the path that I give to my ide ?

**Comment by stof** [comment] 2015-04-13 16:37
AFAIK, no

**Comment by dupuchba** [comment] 2015-04-15 06:27
Maybe @nicolas-grekas has an answer :-) ?

**Comment by nicolas-grekas** [comment] 2015-04-15 06:42
Using ini_set in your front controller?

**Comment by dupuchba** [comment] 2015-04-15 07:38
yes, a little too much IMO
What about modifying `src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/request.html.twig` by adding a configurable option ?

**Comment by derrabus** [comment] 2015-04-16 08:27
Maybe path mapping is rather a problem that JetBrains should solve. For remote debugging, they have solved this already, so maybe it's not a hard thing for them to extend this feature to those links.

**Comment by dupuchba** [comment] 2015-04-16 08:31
@derrabus I use phpstorm but the problem is the same with sublime text or any other IDE

**Comment by derrabus** [comment] 2015-04-16 08:58
@dupuchba Sure, and you use Symfony, but the problem is the same with Wordpress or Zend Framework.

My point is that this mapping is something very specific to your development environment. Another developer of your team probably needs different path mapping settings. This is why I'd rather implement such a feature into the IDE than into an application framework.

**Comment by BlueM** [comment] 2015-04-19 12:18
According to your screenshot, you are on OS X. In that case, a pretty simple solution is to use a custom URL scheme which acts as a wrapper around a URL using `xdebug.file_link_format` (or which will do whatevery you want). The most simple way to implement the wrapper code is an AppleScript bundle (maybe 20 lines of code, plus a few lines in Info.plist), but in case you’re familiar with Cocoa, you can also use that.
This approach is of course not as fast as the direct link (takes 2 or 3 seconds longer), but works well, and I’ve done this myself when I worked on a project inside a Vagrant VM a few years ago. The only restriction is that you must be able to set `xdebug.file_link_format` inside the VM to make it use your custom URL scheme.

**Comment by dupuchba** [comment] 2015-04-20 08:24
@BlueM Ty for the solution but IMO that's more an "hack" than a real solution for my problem (my co-workers have exactly the same issue on ubuntu).

**Comment by nicolas-grekas** [comment] 2015-05-22 23:41
Maybe with the Remote Call plugin?
https://plugins.jetbrains.com/plugin/6027?pr=phpStorm

**Comment by vincecore** [comment] 2015-05-23 19:53
I made a bundle with a quick fix, it's not a good solution but works for now. I only tested it with the symfony IDE configuration, not with the xdebug feature.

https://github.com/vincecore/IdeLinkBundle

**Comment by hacfi** [comment] 2015-05-24 07:37
Using [LinCastor](https://onflapp.wordpress.com/lincastor/) on OS X I added a schema called `pstormv` (v for vagrant) and use the following shell script:

``` sh
#!/bin/sh

REGEX="^url=file://(.*)&line=(.*)$"

if [[ $URL_QUERY =~ $REGEX ]]; then
    osascript -e "tell application \"PhpStorm\" to activate"
    /usr/local/bin/pstorm "${BASH_REMATCH[1]/\/var\/www\/current/\/Users\/me\/src\/project}:${BASH_REMATCH[2]}"
    exit 0
fi

exit 1
```

My project at `/Users/me/src/project/` is mounted at `/var/www/current` in the vm.

**Comment by nicolas-grekas** [comment] 2015-05-27 22:55
For Ubuntu this is the same: a few tweaks to the `/usr/local/bin/xdebug-urlhandler` as defined in http://blog.lyrixx.info/2013/02/05/how-to-open-a-file-with-sublime-text-from-your-browser.html allow mapping vm paths to host's paths.

**Comment by fabpot** [comment] 2015-10-05 12:00
Closing as some solutions have been proposed here. We might want to add a small cookbook entry in the documentation though.

**Closed by fabpot** 2015-10-05 12:00 UTC

**Comment by nicolas-grekas** [comment] 2016-09-01 12:16
See #19807 for a Symfony-inside solution that is coming to 3.2

**Comment by nicolas-grekas** [comment] 2017-01-04 10:48
Note that IDEs can also do this on their own:
PhpStorm: https://www.jetbrains.com/help/phpstorm/2016.3/deployment-mappings-tab.html
Netbeans: http://forums.netbeans.org/ptopic53513.html
Eclipse PDT: http://www.eclipse.org/pdt/help/html/adding_a_server_path_map.htm
Sublime Text: https://github.com/martomo/SublimeTextXdebug#features

List copy/pasted from https://bugs.xdebug.org/view.php?id=1344
