### ISSUE TITLE
ResetInterface not working

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#46485] opened 2022-05-28 10:04 UTC
### Symfony version(s) affected

6.1.0

### Description

I created an example service, basically:

```php
<?php declare(strict_types=1);

namespace App\Reset;

use Psr\Log\LoggerInterface;
use Symfony\Contracts\Service\ResetInterface;

final class TestReset implements ResetInterface
{
	public function __construct (
		private readonly LoggerInterface $logger,
	)
	{

	}

	public function reset ()
	{
		dd("RESET CALLED");
		$this->logger->critical("TEST RESET RUN");
	}
}
```

To test a reset.

Then I start a message consumer, dispatch 2 messages and see that the reset is not called.
If I modify this line https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpKernel/DependencyInjection/ResettableServicePass.php#L38 to be:

```php
$services[$id] = new Reference($id, ContainerInterface::IGNORE_ON_UNINITIALIZED_REFERENCE);
if ("App\Reset\TestReset" === $id)
{
	$services[$id] =  new Reference($id, ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE);
}
```

Then everything works?

### How to reproduce

See error description. The reset is just never called.
Error reproducer here: https://github.com/apfelbox/symfony-reproduce-46485

### Additional Context

I dumped the `ServicesResetter`. 

The `$resettableServices` do not include my service, even if in `$resetMethods` the method + service id is included.

I noticed that my `TestReset` service was initially removed as being "unused" (which probably is a bug in itself, because it clearly is used as a services resetter?), but even defining it as public doesn't solve the issue.

**Comment by alexander-schranz** [comment] 2022-05-30 15:30
Nice reproducer 👍 ,

I think the behaviour is expected. You only need to reset something when the service was really used. So the service definition looks correctly:

![Bildschirmfoto 2022-05-30 um 17 14 25](https://user-images.githubusercontent.com/1698337/171022040-11c34d46-7558-412c-9d61-beee03a6efb3.png)

Injected is only the service which are used:

![Bildschirmfoto 2022-05-30 um 17 14 37](https://user-images.githubusercontent.com/1698337/171022082-d8a13b75-c870-43a3-a17c-991ef85c1ecb.png)

That is what the `IGNORE_ON_UNINITIALIZED_REFERENCE` means.

If you are using the service e.g.:

```diff
diff --git a/src/Message/TestMessageHandler.php b/src/Message/TestMessageHandler.php
index b1a9acf..c7ce8bd 100644
--- a/src/Message/TestMessageHandler.php
+++ b/src/Message/TestMessageHandler.php
@@ -2,6 +2,7 @@

 namespace App\Message;

+use App\Reset\TestReset;
 use Symfony\Component\Console\Input\ArgvInput;
 use Symfony\Component\Console\Output\ConsoleOutput;
 use Symfony\Component\Console\Style\SymfonyStyle;
@@ -10,6 +11,9 @@ use Symfony\Component\Messenger\Attribute\AsMessageHandler;
 #[AsMessageHandler]
 final class TestMessageHandler
 {
+    public function __construct(TestReset $testReset)
+    {}
+
        public function __invoke (TestMessage $message)
        {
                $output = new SymfonyStyle(new ArgvInput(), new ConsoleOutput());

```

The service is correct injected and so called: 

![Bildschirmfoto 2022-05-30 um 17 29 45](https://user-images.githubusercontent.com/1698337/171023715-b8438a83-5cbb-4b0c-8622-7dfdfd9ec2f7.png)

**Comment by apfelbox** [comment] 2022-05-30 21:33
Hi @alexander-schranz,

thanks for your response.
However I am not sure whether it applies here: I also could reproduce this issue when adding something else in this class.

But also symfony can't know whether my class is just using side effects symfony (and the service container) doesn't know about.
In this regard the services resetter is like an event listener: if it is registered (= uses the interface or is explicitly tagged) it must be called regardless of whether it is using other services or not.

**Comment by alexander-schranz** [comment] 2022-05-30 21:50
@apfelbox I think that is not how the service resetter is working, the `kernel.reset` and ResetInterface is not a event listener / subscriber.

And instancing all services to reset them even if they not really have something to reset would be bad for performance of an application.

You should implementing the `ResetInterface` on the service doing what you want to reset, not try to create a service around to reset or something like that. Keep in mind a service called by the service resetter does not require to implement the ResetInterface so you can add `kernel.reset` tag with the `method: otherMethod` tag property to the service you want to call a method on.

Example:

<img width="1156" alt="Bildschirmfoto 2022-05-30 um 23 49 43" src="https://user-images.githubusercontent.com/1698337/171062288-ac295164-045f-4fb8-9927-7268ae47adcc.png">

Still if you want to call something everytime you could decorate the `services_resetter` service or create a event subscriber on `kernel.terminate` or another event which matches your usecase.

**Comment by derrabus** [comment] 2022-05-30 21:53
@alexander-schranz is right.

A container reset is meant to restore all services to their initial state. Services ideally should not have state, but if they do, this mechanism gives you the possibility to erase that state.

Resettable services are services that **can be reset**, and explicitly not event listeners that reset something else. A service that wasn't used does not need to be reset because it must still have its initial state. And a service that cannot be used (because it's private and not wired anywhere) won't need to be reset ever.

I'm closing this issue since everything you describe works as designed. Whatever you're trying to do here, the kernel reset does not seem to be the right tool for it.

**Closed as not planned by derrabus** 2022-05-30 21:53 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by apfelbox** [comment] 2022-06-03 10:58
Hi @derrabus @alexander-schranz,

initially I had the interface on a "valid" service but it wasn't called as well. That's the whole reason why I created the reproducer in the first place.
I probably didn't clear the cache properly enough for it to work. Need to check that again.

Thanks for both of your explanations. Makes sense for this to be optimized like this – even if it isn't obvious at all what is happening.

Thanks 🙌

**Comment by derrabus** [comment] 2022-06-03 11:01
> it isn't obvious at all what is happening.

If you feel like this should be documented better, feel free to contribute the piece of documentation that would've helped you to the symfony-docs repository.
