### ISSUE TITLE
Single id is not allowed on composite primary key in entity 

### ISSUE THREAD

**Issue by maykino** [symfony/symfony#24659] opened 2017-10-22 05:49 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.1.10

Hello, the following entity generates the error "Single id is not allowed on composite primary key in entity ListingBundle\Entity\EbayListing" during php bin/console doctrine:schema:update --force

```php
class EbayListing
{


    /**
     * @var int
     *
     * @ORM\Column(name="listing_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */ 

    protected $id;

    /**
    * @var string
    *
    * @ORM\Column(name="item_id", type="string", length=20, nullable=true)
    */ 
    protected $itemId;
```
However when protected $itemId; is changed to protected $item; everything works fine.

**Comment by dmaicher** [comment] 2017-10-22 16:08
I cannot reproduce the issue with the snippet you provided. Works just fine for me.

Can you create a small example project to reproduce this?

**Comment by iltar** [comment] 2017-10-22 17:57
This does not look like an issue related to Symfony. I recommend to head to https://symfony.com/support so you can ask if it's working as intended. If not, you should probably verify if this is intended behavior in https://github.com/doctrine/doctrine2.

**Comment by javiereguiluz** [comment] 2017-10-23 07:19
Let's close this issue temporarily and if we can confirm it's a Symfony bug, we'll reopen it. Thanks!

**Closed by javiereguiluz** 2017-10-23 07:19 UTC

**Comment by BenMorel** [comment] 2018-08-13 10:02
See doctrine/doctrine2#6333
