### ISSUE TITLE
[Validator] hardtype variable with assert

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#50497] opened 2023-05-31 09:55 UTC
### Symfony version(s) affected

6.2

### Description

Hardtype in Validator has priority over asserts.
Is this normal, or is it a problem and the opposite should be happening?

In my case, ```#[Assert\Type('string')]``` should throw an error first to only have a list of ```ConstraintViolation``` no?
If this is the right behavior, add in the documentation to not hardtype variable in DTO is something possible ?

### How to reproduce

Create a class 
```php
class ClassA
{
    #[Assert\Type('string')]
    #[Assert\Length(max: 20)]
    public string $varA;
}
```

Send a json request to a route which contains this code : 
```php
$payload = $this->serializer->deserialize(data: $request->getContent(), type: ClassA::class, format: 'json');
$errors  = $this->validator->validate($payload);
```

Here is the content of the JSON to send : 
```json
{
    "varA": 0
}
```

And this is the exception I have :

![image](https://github.com/symfony/symfony/assets/16165438/6930bb7e-a6fc-4eba-9df5-169add764ca1)

**Comment by xabbuh** [comment] 2023-05-31 11:04
Using the `Type` constraint usually does not make sense in combination with native type-hints. Then, it's probably also a good idea to leverage [group sequences](https://symfony.com/doc/current/validation/sequence_provider.html) to only apply all other constraints when the `Type` constraints succeed:

```php
class ClassA
{
    #[Assert\Type('string'), groups: 'type']
    #[Assert\Length(max: 20)]
    public $varA;
}
```

And validate like this:

```php
$payload = $this->serializer->deserialize(data: $request->getContent(), type: ClassA::class, format: 'json');
$errors  = $this->validator->validate($payload, new GroupSequence(['type', 'ClassA']));
```

**Comment by ro0NL** [comment] 2023-05-31 17:09
using `#[MapRequestPayload]` should handle the errors well, see https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects

> Is this normal, or is it a problem

not really, and not really :)

**Comment by mathroc** [comment] 2023-07-18 13:51
> > Is this normal, or is it a problem
> 
> not really, and not really :)

I think it's normal. The validation happens on the object, so it has to first be initialized, and the native types have to be respected. So in the example from @AurelienPillevesse the exception is thrown in the deserializon step, before anything related to the validation has even started

**Comment by xabbuh** [comment] 2023-07-19 11:49
closing here as this is not a bug as explained before

**Closed as not planned by xabbuh** 2023-07-19 11:49 UTC
Labels: Validator, Bug, Status: Works for me
