### ISSUE TITLE
Upgrade to 5.2.4. gives Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners

### ISSUE THREAD

**Issue by parijke** [symfony/symfony#40365] opened 2021-03-04 19:36 UTC
**Symfony version(s) affected**:
5.2.4

**Description**
Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners

**How to reproduce**
Downgrading to 5.2.3. the error disappears

**Additional context**
```
[2021-03-04T20:30:49.646533+01:00] request.CRITICAL: Exception thrown when handling an exception (ErrorException: Notice: Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners at /app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php line 64) {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners at /app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64)"} []
```

**Comment by jderusse** [comment] 2021-03-04 19:49
could you please provide a reproducer ?

**Comment by mynameisbogdan** [comment] 2021-03-04 20:49
@jderusse seems related to #40042. Reverting this PR seems to fix building the container.

**Comment by parijke** [comment] 2021-03-05 08:18
@jderusse would love to, but no idea how. I just upgraded my dev env to 5.2.4 and the first call this error happened. Rolled back to 5.2.3 and the error's gone. I have no clue where or how to isolate this/

**Comment by stof** [comment] 2021-03-05 08:57
@parijke at least providing a stack trace could help.

**Comment by parijke** [comment] 2021-03-05 09:04
ok going to try that

**Comment by parijke** [comment] 2021-03-05 09:08
```

[3/3] ErrorException
--
ErrorException: Notice: Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners    at /app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64   at Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('loadClassMetadata', object(LoadClassMetadataEventArgs))      (/app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:245)   at Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(object(ClassMetadata), null, false, array())      (/app/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:306)   at Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('App\\Entity\\service')      (/app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:81)   at Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata('App\\Entity\\service')      (/app/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:184)   at Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('App\\Entity\\service')      (/app/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaValidator.php:117)   at Doctrine\ORM\Tools\SchemaValidator->validateClass(object(ClassMetadata))      (/app/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php:80)   at Doctrine\Bundle\DoctrineBundle\DataCollector\DoctrineDataCollector->collect(object(Request), object(Response), object(ErrorException))      (/app/vendor/symfony/http-kernel/Profiler/Profiler.php:161)   at Symfony\Component\HttpKernel\Profiler\Profiler->collect(object(Request), object(Response), object(ErrorException))      (/app/vendor/symfony/http-kernel/EventListener/ProfilerListener.php:90)   at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))      (/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)   at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))      (/app/vendor/symfony/event-dispatcher/EventDispatcher.php:230)   at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(ResponseEvent))      (/app/vendor/symfony/event-dispatcher/EventDispatcher.php:59)   at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')      (/app/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)   at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')      (/app/vendor/symfony/http-kernel/HttpKernel.php:190)   at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(Response), object(Request), 2)      (/app/vendor/symfony/http-kernel/HttpKernel.php:178)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)      (/app/vendor/symfony/http-kernel/HttpKernel.php:79)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2, false)      (/app/vendor/symfony/http-kernel/EventListener/ErrorListener.php:60)   at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))      (/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)   at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))      (/app/vendor/symfony/event-dispatcher/EventDispatcher.php:230)   at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))      (/app/vendor/symfony/event-dispatcher/EventDispatcher.php:59)   at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')      (/app/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)   at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')      (/app/vendor/symfony/http-kernel/HttpKernel.php:218)   at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(ErrorException), object(Request), 1)      (/app/vendor/symfony/http-kernel/HttpKernel.php:111)   at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(ErrorException), object(Request))      (/app/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:127)   at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(object(ErrorException))      (/app/vendor/symfony/error-handler/ErrorHandler.php:607)   at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(ErrorException))


```

**Comment by parijke** [comment] 2021-03-05 09:12
```
In ContainerAwareEventManager.php line 64:
                                                                                            
  [ErrorException]                                                                          
  Notice: Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners  
                                                                                            

Exception trace:
  at /app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:245
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /app/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:306
 Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:81
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /app/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:184
 Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:288
 Doctrine\ORM\EntityManager->getClassMetadata() at /app/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php:39
 Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository->__construct() at /app/src/Repository/InsurancePolicyRepository.php:19
 App\Repository\InsurancePolicyRepository->__construct() at /app/var/cache/dev/Container5kxhpbd/getInsurancePolicyRepositoryService.php:27
 Container5kxhpbd\getInsurancePolicyRepositoryService::do() at /app/var/cache/dev/Container5kxhpbd/App_KernelDevDebugContainer.php:577
 Container5kxhpbd\App_KernelDevDebugContainer->load() at /app/var/cache/dev/Container5kxhpbd/getCancelledPoliciesToStoppedCommandService.php:23
 Container5kxhpbd\getCancelledPoliciesToStoppedCommandService::do() at /app/var/cache/dev/Container5kxhpbd/App_KernelDevDebugContainer.php:577
 Container5kxhpbd\App_KernelDevDebugContainer->load() at /app/vendor/symfony/dependency-injection/Container.php:441
 Symfony\Component\DependencyInjection\Container->getService() at /app/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:42
 Symfony\Component\DependencyInjection\Argument\ServiceLocator->get() at /app/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php:45
 Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get() at /app/vendor/symfony/console/Application.php:551
 Symfony\Component\Console\Application->has() at /app/vendor/symfony/console/Application.php:747
 Symfony\Component\Console\Application->all() at /app/vendor/symfony/framework-bundle/Console/Application.php:142
 Symfony\Bundle\FrameworkBundle\Console\Application->all() at /app/vendor/symfony/console/Descriptor/ApplicationDescription.php:91
 Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication() at /app/vendor/symfony/console/Descriptor/ApplicationDescription.php:68
 Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands() at /app/vendor/symfony/console/Descriptor/TextDescriptor.php:200
 Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication() at /app/vendor/symfony/console/Descriptor/Descriptor.php:55
 Symfony\Component\Console\Descriptor\Descriptor->describe() at /app/vendor/symfony/console/Helper/DescriptorHelper.php:65
 Symfony\Component\Console\Helper\DescriptorHelper->describe() at /app/vendor/symfony/console/Command/ListCommand.php:70
 Symfony\Component\Console\Command\ListCommand->execute() at /app/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:99
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /app/bin/console:42

list [--raw] [--format FORMAT] [--] [<namespace>]
```

**Comment by michanismus** [comment] 2021-03-05 11:04
Same here after upgrade to 5.2.4.
I am using api platform.

EDIT:
The Api Platform route config is causing the error for me.

config/routes/api_platform.yaml

```
api_platform:
    resource: .
    type: api_platform
    prefix: /api/v1
```

Error is gone when api_platform route config is removed.

EDIT 2:

Stack trace:

```
Symfony\Component\Config\Exception\LoaderLoadException:
Notice: Undefined index: _service_doctrine.orm.default_listeners.attach_entity_listeners in . (which is being imported from "/srv/htdocs/j+h/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

  at /srv/htdocs/j+h/vendor/symfony/config/Loader/FileLoader.php:173
  at Symfony\Component\Config\Loader\FileLoader->doImport()
     (/srv/htdocs/j+h/vendor/symfony/config/Loader/FileLoader.php:97)
  at Symfony\Component\Config\Loader\FileLoader->import()
     (/srv/htdocs/j+h/vendor/symfony/routing/Loader/YamlFileLoader.php:196)
  at Symfony\Component\Routing\Loader\YamlFileLoader->parseImport()
     (/srv/htdocs/j+h/vendor/symfony/routing/Loader/YamlFileLoader.php:90)
  at Symfony\Component\Routing\Loader\YamlFileLoader->load()
     (/srv/htdocs/j+h/vendor/symfony/config/Loader/FileLoader.php:158)
  at Symfony\Component\Config\Loader\FileLoader->doImport()
     (/srv/htdocs/j+h/vendor/symfony/config/Loader/FileLoader.php:86)
  at Symfony\Component\Config\Loader\FileLoader->import()
     (/srv/htdocs/j+h/vendor/symfony/routing/Loader/Configurator/RoutingConfigurator.php:43)
  at Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator->import()
     (/srv/htdocs/j+h/src/Mic/Core/Kernel.php:58)
  at Mic\Core\Kernel->configureRoutes()
     (/srv/htdocs/j+h/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:196)
  at Mic\Core\Kernel->loadRoutes()
     (/srv/htdocs/j+h/vendor/symfony/routing/Loader/ObjectLoader.php:62)
  at Symfony\Component\Routing\Loader\ObjectLoader->load()
     (/srv/htdocs/j+h/vendor/symfony/config/Loader/DelegatingLoader.php:40)
  at Symfony\Component\Config\Loader\DelegatingLoader->load()
     (/srv/htdocs/j+h/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php:69)
  at Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load()
     (/srv/htdocs/j+h/vendor/symfony/framework-bundle/Routing/Router.php:68)
  at Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection()
     (/srv/htdocs/j+h/vendor/symfony/routing/Router.php:358)
  at Symfony\Component\Routing\Router->getMatcherDumperInstance()
     (/srv/htdocs/j+h/vendor/symfony/routing/Router.php:289)
  at Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}()
     (/srv/htdocs/j+h/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php:39)
  at Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache()
     (/srv/htdocs/j+h/vendor/symfony/routing/Router.php:297)
  at Symfony\Component\Routing\Router->getMatcher()
     (/srv/htdocs/j+h/vendor/symfony/routing/Router.php:251)
  at Symfony\Component\Routing\Router->matchRequest()
     (/srv/htdocs/j+h/vendor/symfony/http-kernel/EventListener/RouterListener.php:112)
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
     (/srv/htdocs/j+h/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/srv/htdocs/j+h/vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/srv/htdocs/j+h/vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/srv/htdocs/j+h/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/srv/htdocs/j+h/vendor/symfony/http-kernel/HttpKernel.php:133)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/srv/htdocs/j+h/vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/srv/htdocs/j+h/vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/srv/htdocs/j+h/src/Mic/Core/HttpKernel.php:57)
  at Mic\Core\HttpKernel->handle()
     (/srv/htdocs/j+h/public/index.php:28)     
```

**Comment by jderusse** [comment] 2021-03-05 11:58
If you can't provide a reproducer, could you please call `dump($this);` at the beginning of the `dispatch` method, and post me the output

**Comment by michanismus** [comment] 2021-03-05 12:31
I added a try and catch block to ContainerAwareEventManager line 63 (for loop).

dump($eventName)
```
ContainerAwareEventManager.php on line 67:
"loadClassMetadata"
```

dump($this->listeners[$eventName])
```
ContainerAwareEventManager.php on line 67:
array:7 [▼
  "000000005866ad03000000006566f644" => Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber {#788 ▶}
  "000000005866acee000000006566f644" => Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber {#761 ▶}
  "000000005866ace0000000006566f644" => Mic\Core\Framework\DataAbstractionLayer\Subscriber\TimestampableSubscriber {#759 ▶}
  "000000005866acd3000000006566f644" => Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener {#708 ▶}
  "000000005866aa72000000006566f644" => Doctrine\ORM\Tools\ResolveTargetEntityListener {#1125 ▶}
  "000000005866aa70000000006566f644" => Sonata\Doctrine\Mapper\ORM\DoctrineORMMapper {#1127 ▶}
  "_service_doctrine.orm.default_listeners.attach_entity_listeners" => "doctrine.orm.default_listeners.attach_entity_listeners"
]
```

dump($this->methods[$eventName])
```
ContainerAwareEventManager.php on line 67:
array:6 [▼
  "000000005866ad03000000006566f644" => "loadClassMetadata"
  "000000005866acee000000006566f644" => "loadClassMetadata"
  "000000005866ace0000000006566f644" => "loadClassMetadata"
  "000000005866acd3000000006566f644" => "loadClassMetadata"
  "000000005866aa72000000006566f644" => "loadClassMetadata"
  "000000005866aa70000000006566f644" => "loadClassMetadata"
]
```

Of course, there is no $hash "_service_doctrine.orm.default_listeners.attach_entity_listeners"...
```
$listener->{$this->methods[$eventName][$hash]}($eventArgs);
```

**Comment by michanismus** [comment] 2021-03-05 12:51
@jderusse When I remove all event subscribers for `Doctrine\ORM\Events::loadClassMetadata` event everything works fine.
Could you try to add an event subscriber for `loadClassMetadata` to reproduce the error?

@parijke Do you use event subscribers for `loadClassMetadata`?

**Comment by jderusse** [comment] 2021-03-05 13:00
That's weird, the listener `_service_doctrine.orm.default_listeners.attach_entity_listeners` is a string and should be initialized, when the dispatcher calls `initializeListeners`. In this method, the listener is converted into an object AND the `method` is populated.
Could you please dig into it, and check the output of dump after and before calling this method?
```
    public function dispatchEvent($eventName, EventArgs $eventArgs = null)
    {
        if (!$this->initializedSubscribers) {
dump($this->listeners);
            $this->initializeSubscribers();
dump($this->listeners);
        }
        if (!isset($this->listeners[$eventName])) {
            return;
        }

        $eventArgs = null === $eventArgs ? EventArgs::getEmptyInstance() : $eventArgs;

        if (!isset($this->initialized[$eventName])) {
dump($this->listeners);
            $this->initializeListeners($eventName);
        }

        foreach ($this->listeners[$eventName] as $hash => $listener) {
            $listener->{$this->methods[$eventName][$hash]}($eventArgs);
        }
    }
```

**Comment by michanismus** [comment] 2021-03-05 13:05
The results:

dump 1:
```
ContainerAwareEventManager.php on line 62:
array:8 [▼
  "loadClassMetadata" => array:4 [▼
    "0000000038dc7af20000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber {#787 ▶}
    "0000000038dc7b190000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber {#760 ▶}
    "0000000038dc7b170000000033181976" => Mic\Core\Framework\DataAbstractionLayer\Subscriber\TimestampableSubscriber {#758 ▶}
    "0000000038dc7b250000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener {#708 ▶}
  ]
  "postConnect" => array:1 [▶]
  "postLoad" => array:2 [▶]
  "postPersist" => array:1 [▶]
  "postRemove" => array:1 [▶]
  "postUpdate" => array:1 [▶]
  "prePersist" => array:2 [▶]
  "preUpdate" => array:2 [▶]
]
```

dump 2:

```
ContainerAwareEventManager.php on line 62:
array:11 [▼
  "loadClassMetadata" => array:7 [▼
    "0000000038dc7af20000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber {#787 ▶}
    "0000000038dc7b190000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber {#760 ▶}
    "0000000038dc7b170000000033181976" => Mic\Core\Framework\DataAbstractionLayer\Subscriber\TimestampableSubscriber {#758 ▶}
    "0000000038dc7b250000000033181976" => Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener {#708 ▶}
    "0000000038dc7d740000000033181976" => Doctrine\ORM\Tools\ResolveTargetEntityListener {#1173 ▶}
    "0000000038dc7d760000000033181976" => Sonata\Doctrine\Mapper\ORM\DoctrineORMMapper {#1175 ▶}
    "_service_doctrine.orm.default_listeners.attach_entity_listeners" => "doctrine.orm.default_listeners.attach_entity_listeners"
  ]
  "postConnect" => array:1 [▶]
  "postLoad" => array:4 [▶]
  "postPersist" => array:3 [▶]
  "postRemove" => array:2 [▶]
  "postUpdate" => array:3 [▶]
  "prePersist" => array:3 [▶]
  "preUpdate" => array:3 [▶]
  "postGenerateSchema" => array:2 [▶]
  "onSchemaCreateTable" => array:1 [▶]
  "onClassMetadataNotFound" => array:1 [▶]
]
```

dump 3 was not called at all:

```
        if (!isset($this->initialized[$eventName])) {
dump($this->listeners);
            $this->initializeListeners($eventName);
        }
```

**Comment by reypm** [comment] 2021-03-05 13:07
@jderusse I can confirm I am running into the same issue with SF 4.4.20 I had to downgrade to 4.4.18, was trying to provide a reproducer but was having some issues with it and @michanismus beat me by opening the issue

**Comment by michanismus** [comment] 2021-03-05 13:12
My Code:
```
    public function dispatchEvent($eventName, EventArgs $eventArgs = null)
    {
        if (!$this->initializedSubscribers) {
dump($eventName, $this->listeners);
            $this->initializeSubscribers();
dump($eventName, $this->listeners);
        }
        if (!isset($this->listeners[$eventName])) {
            return;
        }

        $eventArgs = null === $eventArgs ? EventArgs::getEmptyInstance() : $eventArgs;

        if (!isset($this->initialized[$eventName])) {
dump($eventName, $this->listeners);
            $this->initializeListeners($eventName);
        }
```

The Output:

```
ContainerAwareEventManager.php on line 62:
"loadClassMetadata"

ContainerAwareEventManager.php on line 62:
array:8 [▼
  "loadClassMetadata" => array:4 [▼
    "00000000275a099c000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber {#787 ▶}
    "00000000275a0877000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber {#760 ▶}
    "00000000275a0879000000004751e577" => Mic\Core\Framework\DataAbstractionLayer\Subscriber\TimestampableSubscriber {#758 ▶}
    "00000000275a084b000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener {#708 ▶}
  ]
  "postConnect" => array:1 [▶]
  "postLoad" => array:2 [▶]
  "postPersist" => array:1 [▶]
  "postRemove" => array:1 [▶]
  "postUpdate" => array:1 [▶]
  "prePersist" => array:2 [▶]
  "preUpdate" => array:2 [▶]
]

ContainerAwareEventManager.php on line 62:
"postConnect"

ContainerAwareEventManager.php on line 62:
array:11 [▼
  "loadClassMetadata" => array:7 [▼
    "00000000275a099c000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber {#787 ▶}
    "00000000275a0877000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber {#760 ▶}
    "00000000275a0879000000004751e577" => Mic\Core\Framework\DataAbstractionLayer\Subscriber\TimestampableSubscriber {#758 ▶}
    "00000000275a084b000000004751e577" => Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener {#708 ▶}
    "00000000275a0e18000000004751e577" => Doctrine\ORM\Tools\ResolveTargetEntityListener {#1175 ▶}
    "00000000275a0e16000000004751e577" => Sonata\Doctrine\Mapper\ORM\DoctrineORMMapper {#1177 ▶}
    "_service_doctrine.orm.default_listeners.attach_entity_listeners" => "doctrine.orm.default_listeners.attach_entity_listeners"
  ]
  "postConnect" => array:1 [▶]
  "postLoad" => array:4 [▶]
  "postPersist" => array:3 [▶]
  "postRemove" => array:2 [▶]
  "postUpdate" => array:3 [▶]
  "prePersist" => array:3 [▶]
  "preUpdate" => array:3 [▶]
  "postGenerateSchema" => array:2 [▶]
  "onSchemaCreateTable" => array:1 [▶]
  "onClassMetadataNotFound" => array:1 [▶]
]
```

Line 62 is this block:
```
        if (!isset($this->initialized[$eventName])) {
dump($eventName, $this->listeners);
            $this->initializeListeners($eventName);
        }
```

The first two dump() calls are never called...

**Comment by parijke** [comment] 2021-03-06 08:00
> @jderusse When I remove all event subscribers for `Doctrine\ORM\Events::loadClassMetadata` event everything works fine.
> Could you try to add an event subscriber for `loadClassMetadata` to reproduce the error?
> 
> @parijke Do you use event subscribers for `loadClassMetadata`?

@michanismus not myself, but VichUploadBundle does I think (which I use)

**Comment by jderusse** [comment] 2021-03-06 09:24
I'm sorry, i don't see how the current implementation fail :-(

Please provide a reproducer or debug this classe and send a PR.

Hint: this class should convert a `string` listener into an object and fill the `methods` array at the same time. But for some reasons, this is not performed.

**Comment by parijke** [comment] 2021-03-06 10:12
My skills fail to do that at the moment... Sorry, I have to rely on others who can

**Comment by michanismus** [comment] 2021-03-06 16:47
@jderusse 

Here is the bugfix, sorry, I do not have the time to create a PR. Replace the function `initializeSubscribers`.
You simple merged uninitialized listeners with initialized without a check.

```
    private function initializeSubscribers()
    {
        $this->initializedSubscribers = true;

        $eventListeners = $this->listeners;
        // reset eventListener to respect priority: EventSubscribers have a higher priority
        $this->listeners = [];
        foreach ($this->subscribers as $id => $subscriber) {
            if (\is_string($subscriber)) {
                parent::addEventSubscriber($this->subscribers[$id] = $this->container->get($subscriber));
            }
        }
        foreach ($eventListeners as $event => $listeners) {
            if (!isset($this->listeners[$event])) {
                $this->listeners[$event] = [];
            }
            foreach ($listeners as $hash => $listener) {
                if (\is_string($listener)) {
                    $listener = $this->container->get($listener);
                    $hash = $this->getHash($listener);

                    $this->methods[$event][$hash] = $this->getMethod($listener, $event);
                }

                $this->listeners[$event][$hash] = $listener;
            }
        }
        $this->subscribers = [];
    }
```

**Comment by parijke** [comment] 2021-03-07 11:29
If replaced with this, the error's gone

**Comment by fliespl** [comment] 2021-03-07 13:37
The same happens on 4.4.20 as well.

**Comment by fliespl** [comment] 2021-03-07 22:36
In our case problem involved (during cache clear):
- CacheWarmer running getRouteCollection
- call to $meta = $this->metadataFactory->getMetadataFor($class);
- loadClassMetadata subscriber
- one of the routes was instantiated due to some logic and it autowire to ServiceEntityRepository - removing autowiring to this service from __construct - fixed it.

Seems like it's connected with ServiceEntityRepository & something else according to mine and @parijke stack trace. 

Still unable to provide minimum reproducer on clean sf instance. Something else must be in the mix here.

**Comment by parijke** [comment] 2021-03-08 12:48
My problem is solved. It appears to be triggered in my case by an invalid targetEntity (service::class). Replaced the targetEntity by Service::class solved my issue.

**Comment by michanismus** [comment] 2021-03-09 13:42
@jderusse Here is a reproducer:

https://github.com/michanismus/eventsmanager-reproducer

Error appears when an listener added by subscriber triggers an `loadClassMetadata`.
Then there is a nested call for the event. 

https://github.com/symfony/doctrine-bridge/blob/9e2c53f3e8f8a6ccecd80de5c2c8b71beeca7fc8/ContainerAwareEventManager.php#L180

To fix that the line 180 has to be replaced with:

```
// $this->listeners[$event] += $listeners;
foreach ($listeners as $listener) {
    $this->addEventListener($event, $listener);
}
```

Edit:

```
composer install
bin/console doc:mig:mig
```

Request the TestController route `/`.

**Closed as completed** 2021-03-10 07:34 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback

**Comment by michanismus** [comment] 2021-03-11 08:00
No merge for 5.2? :(

**Comment by xabbuh** [comment] 2021-03-11 10:10
We regularly merge lower branches up into all still maintained branches. So this will also land in 5.2.
