### ISSUE TITLE
Use form validation_group in embedded form

### ISSUE THREAD

**Issue by apoberez** [symfony/symfony#17302] opened 2016-01-08 08:27 UTC
I have embedded form type with validation group which is important for parent form, but according to this http://symfony.com/doc/current/reference/forms/types/form.html#cascade-validation it's not considered. Is there some way to force it's usage?

```
CurrencyBundle\Entity\Price:
    constraints:
        - CurrencyBundle\Validator\Constraints\OptionalPrice:
            groups: [Optional]
    properties:
        value:
            - NotBlank:
                groups: [Default]
            - Type:
                groups: [Default, Optional]
                type: numeric
            - Range:
                groups: [Default, Optional]
                min: 0
        currency:
            - NotBlank:
                groups: [Default]
            - Currency:
                groups: [Default, Optional]

RFPBundle\Entity\Request:
    properties:
        requestProducts:
            - Valid: ~

RFPBundle\Entity\RequestProduct:
    properties:
        requestProductItems:
            - Valid: ~

RFPBundle\Entity\RequestProductItem:
    properties:
        price:
            - Valid: ~


class RequestProductItemType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'price',
                PriceType::NAME,
                [
                    'currency_empty_value' => null,
                    'label' => 'rfp.requestproductitem.price.label',
                    'validation_groups' => ['Optional'],
                ]
            );
}
```

**Comment by jakzal** [comment] 2016-01-08 18:27
If I understood your report correctly this is a duplicate of #3622.

The group is always propagated to the cascaded object with the `Valid` constraint. See https://github.com/symfony/symfony/issues/9650#issuecomment-55465073 and https://github.com/symfony/symfony/issues/9650#issuecomment-59475670

**Closed by jakzal** 2016-01-08 18:27 UTC
