### ISSUE TITLE
HTTP Cache - Etag validator : The Response::isNotModified() method return always false

### ISSUE THREAD

**Issue by CarolineDirat** [symfony/symfony#38815] opened 2020-10-26 08:50 UTC
**Symfony version(s) affected**: 5.1.*

**Description**  
$response->isNotModified($request) return always false because of of added quotation marks in $response->getEtag()

**Indeed**: 
- **$response->getETag()** return '"etag"' (with **added quotation marks**)
- **$request->getETags()** return [ 0 => 'etag'] (etag values without quotation marks)

So, in [$response->isNotModified($request)](https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/HttpFoundation/Response.php):
at the line 1094:
 **in_array($this->getEtag(), $etags) is always false**
```
public function isNotModified(Request $request): bool
    {
        if (!$request->isMethodCacheable()) {
            return false;
        }

        $notModified = false;
        $lastModified = $this->headers->get('Last-Modified');
        $modifiedSince = $request->headers->get('If-Modified-Since');

        if ($etags = $request->getETags()) {
            $notModified = \in_array($this->getEtag(), $etags) || \in_array('*', $etags);
        }

        if ($modifiedSince && $lastModified) {
            $notModified = strtotime($modifiedSince) >= strtotime($lastModified) && (!$etags || $notModified);
        }

        if ($notModified) {
            $this->setNotModified();
        }

        return $notModified;
    }
```
Then $response->isNotModified($request) cannot be true, even if the answer has not been modified.

**How to reproduce**  
```
if ($response->isNotModified($request)) {
       return $response; // can't happen, even if etag is ok
}
```

**Comment by CarolineDirat** [comment] 2020-10-27 11:08
Mea Culpa, problem solved [by passing ``true as the second argument to the setEtag() method](https://symfony.com/doc/current/http_cache/validation.html#validation-with-the-etag-header).
`$response->setEtag($phone->computeEtag(), true) `

Sorry...

**Comment by nicolas-grekas** [comment] 2020-11-28 12:56
@CarolineDirat would you like sending a PR to fix this?

**Comment by nicolas-grekas** [comment] 2020-12-09 14:52
I don't reproduce the issue:
1. I call `$response->setEtag('abcdef');`
2. this sends an etag with `"abcdef"` to the browser
3. I refresh the page, and the browser send it with `If-None-Match: "abcdef"` as expected
4. `$response->isNotModified($request)` matches and leads to a 304 as expected.

Please provide us with more details about when this happens.
It's maybe an issue with your webserver/reverse proxy?

**Comment by jderusse** [comment] 2020-12-09 15:51
I reproduced the double escape bug on a demo project with symfony cli:

```php
class TestController extends AbstractController
{
    /**
     * @Route("/test", name="test")
     */
    public function index(Request $request): Response
    {
        var_dump($request->headers->get('if-none-match'));
        var_dump($request->headers->get('if-none-match')[0]);
        var_dump($request->headers->get('if-none-match')[1]);
        var_dump($request->headers->get('if-none-match')[2]);
    }
}
```
```shell
$ curl 127.1:8000/test -H 'if-none-match: hello'
string(5) "hello"
string(1) "h"
string(1) "e"
string(1) "l"

$ curl 127.1:8000/test -H 'if-none-match: "hello"'
string(9) "\"hello\""
string(1) "\"
string(1) """
string(1) "h"
```

I don't know if it's expected or a bug in symfony cli.

**Comment by nicolas-grekas** [comment] 2020-12-09 16:31
> curl 127.1:8000/test -H 'if-none-match: hello'

this one is expected to fail: the client are supposed to send back the etag as-is, including the double quotes

> curl 127.1:8000/test -H 'if-none-match: "hello"'

this one should work. As discussed on Slack, this apparently happens with the symfony binary when php-fpm is *not* used.

I'm closing here since things have been resolved.
@jderusse please open an issue on https://github.com/symfony/cli

**Closed as completed by nicolas-grekas** 2020-12-09 16:31 UTC
Labels: Bug, HttpFoundation, Status: Waiting feedback, Help wanted

**Comment by jderusse** [comment] 2020-12-09 16:49
PR opened https://github.com/symfony/cli/issues/377
