### ISSUE TITLE
2.8 : cache clear won't work anymore

### ISSUE THREAD

**Issue by MisterGrouik** [symfony/symfony#16800] opened 2015-12-02 09:53 UTC
Hi everyone,

cache:clear won't run up correctly anymore. It can't delete dev_old/annotations/(some_folder). I think it's because the filename length in (some_folder) is too long now compared to the 2.7 Symfony version. I'm running on Windows 7.

Look at the filename for example: 5b5b435d53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c65722474656d706c6174654d616e61676572405b416e6e6f745d5d5b315d.doctrinecache.data

If I try to rename this file by removing some char, cache:clear works again (actually, it goes farther then it bugs on another file which has the same problem)

Does someone have a solution ?

Regards

**Comment by WouterJ** [comment] 2015-12-02 10:19
The problem is with the DoctrineCacheBundle generating too long filepaths for Windows (and cache:clear renaming dev to dev_old, making the path 4 characters longer). See https://github.com/symfony/symfony/pull/15547 for a solution

**Comment by MisterGrouik** [comment] 2015-12-02 10:29
How can I apply this update via composer without modifying manually the files you updated ?

**Comment by cfhay** [comment] 2015-12-04 21:12
Yes, `file_exists()` and other functions on Windows will stop working when the string is too long (260 bytes I think). However, an absolute path can be prefixed to work correctly. So let's say, the DIRECTORY_SEPARATOR is `\`, and the string starts with a letter, followed by a colon, then `\\?\` could be prepended to fix the problem.

So:

```php
/* @var $file \SplFileObject */
$fileName = (string)$file;
if(DIRECTORY_SEPARATOR === '\\' && $fileName[1] === ':'){
    $fileName = '\\\\?\\'.$fileName;
}
//... unlink($fileName);
```

**Comment by francoispluchino** [comment] 2015-12-05 10:39
Duplicate with #16783.

**Comment by xabbuh** [comment] 2015-12-05 11:25
Closing in favour of #16783.

**Closed by xabbuh** 2015-12-05 11:25 UTC

**Comment by althaus** [comment] 2015-12-07 15:04
For people like me looking for a quick solution: Run composer update so that the updated doctrine/cache version 1.5.2 gets installed and replace `CacheClearCommand.php` from #16783. That brought me back to work.

**Comment by WouterJ** [comment] 2015-12-07 15:42
You can also remove the `dev_old` and `dev` directories in the filesystem. An update to PHP 5.6 should also help (as both use different Window filesystem API version, which is capable of handling longer file paths IIRC).

**Comment by Tobion** [comment] 2015-12-07 15:51
@WouterJ Neither PHP 5.6 nor PHP 7 helps here. I tested it.

**Comment by althaus** [comment] 2015-12-07 18:04
@WouterJ No fan of deleting the folders manually all the time. ;-)

**Comment by Dominik321321** [comment] 2016-02-19 09:51
i faced same problem, atlast i used .Long Path Tool., it was work for me
