### ISSUE TITLE
An extra *on the beginning of the annotation block will make the routing fail

### ISSUE THREAD

**Issue by empiricalx** [symfony/symfony#25028] opened 2017-11-19 11:46 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.10

This will fail, routing won't be read

```
/***
 * @Route( "route", name="name")
 */ 
```

This will work

```
/**
 * @Route( "route", name="name")`
 */
```
 

One additional asterisk will make your controller unreadable, the question is why?
Why is taking into consideration the number of asterisk on the annotations block? 
I spend hours troubleshooting this problem, to later realized that the only difference was the amount of asterisk on the beginning of the annotation section/block.

**Comment by iltar** [comment] 2017-11-19 12:09
Can you use 3 backticks: `, to format the example properly? My best guess based on what you've posted here, means it reads `/***` as a comment: `/*` + 2 `**`. A docblock is `/**`, which is a different type in the tokenizer and this is the only location where annotations work.

**Comment by javiereguiluz** [comment] 2017-11-19 12:34
@iltar I updated the description.

**Comment by nicolas-grekas** [comment] 2017-11-19 13:56
PHP docblocks must start with two stars. Less and more and it's a regular comment.
Closing as that's not a bug, but the behavior of the PHP engine.

**Closed by nicolas-grekas** 2017-11-19 13:56 UTC

**Comment by empiricalx** [comment] 2017-11-20 22:10
Thank you for the information, I was under the impression that was a feature that was exclusive for phpDocumentor and not symfony.
