### ISSUE TITLE
NativeSessionStorage->loadSession() empty $_SESSION with PdoSessionHandler and pgsql

### ISSUE THREAD

**Issue by chielorenz** [symfony/symfony#14569] opened 2015-05-06 15:11 UTC
When using PdoSessionHandler with pgsql as argument the session has always empty attributes when I reload the page.

NativeSessionStorage:

```
protected function loadSession(array &$session = null)
{
    if (null === $session) {
        $session = &$_SESSION;
    }
    ...
}
```

Where `$_SESSION` is always empty.

This behavior is not present if I use `mysql` as `session.handler.pdo` argument or let php manages session via files.

**Comment by Tobion** [comment] 2015-05-06 18:08
Which symfony version? Which PHP version? Posgres version? What is you table schema?
Might be related to data being saved as blob via `\PDO::PARAM_LOB`. Can you try to fix the PDO query for that?

**Comment by chielorenz** [comment] 2015-05-07 11:09
Hi Tobion: 
    
    Symfony v2.6.5
    PHP v5.6.2
    Posgres v9.4.1.0

Table schema:

        Column     |          Type          | Modifiers | Storage  | Stats target | Description 
    ---------------+------------------------+-----------+----------+--------------+-------------
     sess_id       | character varying(128) | not null  | extended |              | 
     sess_data     | bytea                  | not null  | extended |              | 
     sess_time     | integer                | not null  | plain    |              | 
     sess_lifetime | integer                | not null  | plain    |              | 
    Indexes:
        "sessions_pkey" PRIMARY KEY, btree (sess_id)

The query looks ok, binding `:data` to bytea via `\PDO::PARAM_LOB` seems to work. 

I think the problem is not in the input/output from the database but perhaps between the reading and writing: when i add an attribute it is correctly written on the database, only when the page is reloaded the attribute gets lost.

Maybe something related to AttributeBag not correctly initialize?

**Comment by Tobion** [comment] 2015-05-07 11:51
might be related to #12954. can you try to debug the problem? it's hard for others to reproduce since it depends alot on environment.

**Comment by chielorenz** [comment] 2015-05-07 16:27
I think I got it, you were right about the blob. From [PostgreSql 9.0 changelog](http://www.postgresql.org/docs/9.0/static/release-9-0.html):
> bytea output now appears in hex format by default

But PdoSessionHandler->doRead() handles the resource as an 'escape' resource. With: `ALTER DATABASE myDb SET bytea_output = 'escape';` it works just fine.

PdoSessionHandler should be able to manage the new PostgreSql bytea configuration by default.

**Comment by Tobion** [comment] 2015-05-08 01:03
I cannot find any logic about this in doctrine/dbal. So they do not seem to normalize that either. Seems fishy, so how is it working there?
I guess it would be better to transform the hex string back to a binary string with `hex2bin` (PHP 5.4) or `pack`. But how do we now if the returned string is in hex format... I feel like this normalization should be done by PDO since we also only insert a binary string and not a hex string.

**Comment by chielorenz** [comment] 2015-05-08 17:00
From [PostgreSql documentation](http://www.postgresql.org/docs/9.0/static/datatype-binary.html):
    
    Both "escape" and "hex" format are always accepted on input 
and:

    In "hex" format the entire string is preceded by the sequence \x (to distinguish it from the "escape" format)`

It's a reading only problem, something like this may fix it:

    private function doRead($sessionId)
    {
        ...
       $resource = stream_get_contents($sessionRows[0][0]);

        if(substr( $resource, 0, 1 ) === 'x')
            $resource = hex2bin(substr($resource, 1, strlen($resource)));

        return is_resource($sessionRows[0][0]) ? $resource : $sessionRows[0][0];
    }

But as you say maybe PDO should take care of this issue.

**Comment by jrobeson** [comment] 2015-05-08 21:58
even if it is a PDO issue, it still does need to work in the meantime before it gets fixed by PHP.

**Comment by nicolas-grekas** [comment] 2017-12-09 12:07
I'm closing because this is old, nobody else complained, and I just tested with recent pgsql+php and didn't reproduce the issue.
Please provide a reproducer if you still gave it.
Here is mine:
```php
<?php

header('Content-Type: text/plain; charset=utf8');
error_reporting(-1);
require './vendor/autoload.php';

$pdo = new PDO('pgsql:host=localhost;port=5432;dbname=symfony;user=symfony;password=symfony');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$session = new Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler($pdo);

session_set_save_handler($session);

session_start();

print_r($_SESSION);

echo $_SESSION['next'] = mt_rand();
```

**Closed by nicolas-grekas** 2017-12-09 12:07 UTC
Labels: HttpFoundation
