### ISSUE TITLE
Form extending type error

### ISSUE THREAD

**Issue by portey** [symfony/symfony#17938] opened 2016-02-26 18:23 UTC
Hi, I'am trying to refactor [my bundle](https://github.com/Youshido/UploadableBundle) for uploadable form type and have error with it rendering, twig can't find block for its row.

The problem is in `Symfony\Component\Form\AbstractRendererEngine`, recursion for method  `loadResourceForBlockNameHierarchy()` not work correct in line 174.  The problem is with form type extending. 

To repeat this, just add `UploadableFileType:class` type from my bundle to your form (branch dev-master).

**Comment by xabbuh** [comment] 2016-02-27 20:30
Can you please provide some code that makes it possible to reproduce your issue?

**Comment by portey** [comment] 2016-02-27 23:05
@xabbuh , yes, here is the code that reproduces it
https://github.com/portey/bundle-debug

I also detected, that it can be my bug, because I had named my form type same as parent type, but in symfony2 everything was good. So, if you think it's my bug, then you can close this issue, and I'll rename my type.

**Comment by HeahDude** [comment] 2016-02-28 00:37
Hi @portey, I think you should try to implement [`FormTypeInterface::getBlockPrefix()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormTypeInterface.php#L86), in your `FileType`, so there is no more conflict.

**Comment by portey** [comment] 2016-02-28 01:11
@HeahDude , thanks. 
That's easier solution, than rename type.

**Comment by xabbuh** [comment] 2016-02-28 07:49
@portey In your code, the form type doesn't have a parent form type. Did you make any changes that made the problem go away? You can also take a look at the explanations in https://github.com/symfony/symfony/issues/17009#issuecomment-164679212 and https://github.com/symfony/symfony/issues/16899#issuecomment-164678889. Maybe they do help you too to better understand this (I honestly still don't completely understand it).

**Comment by HeahDude** [comment] 2016-02-28 18:40
@portey, Don't forget to update your service definition as well, by removing the form type alias.

Anyone upgrading to symfony 3 should read carefully [2.7 upgrade file](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.7.md#form) and [2.8 upgrade file](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form) form sections.

If it's working as expected after you upgraded, you can close this issue.

**Comment by HeahDude** [comment] 2016-02-28 18:44
[Line to change in your service definition](https://github.com/Youshido/UploadableBundle/blob/master/Resources/config/services.yml#L35)

Status: Reviewed

**Comment by HeahDude** [comment] 2016-03-07 11:13
@portey any news ?

**Comment by xabbuh** [comment] 2016-03-07 11:46
I am closing here for now due to the lack of feedback.

@portey We can consider to reopen when you can provide more details for your issue. So feel free to leave a comment in that case.

**Closed by xabbuh** 2016-03-07 11:46 UTC
Labels: Bug, Form, Status: Reviewed, Unconfirmed
