### ISSUE TITLE
Translations dont work on twig files for me

### ISSUE THREAD

**Issue by UtechtDustin** [symfony/symfony#37496] opened 2020-07-05 11:14 UTC
**Symfony version(s) affected**: 5.2-dev

**Description**  
The translation using the  `trans` filter dont work on twig files.
It will returns the translation key.

**How to reproduce**  
I setup a new project and followed the instructions of the [documentation](https://symfony.com/doc/current/translation.html).
I changed the default and fallback loclae in the  `translation.yaml` config to `de`.
I created a trabnslations file called `messages.de.yaml`.
On my Twig template i have as example `{{ 'menu.topnav.language.german'|trans }}` and on my translation file
```
menu:
  topnav:
    language:
      english: 'Englisch'
      german: 'Deutsch'
```
But the translation on the twig template dont work.
On controllers the translation works as excepted using the `TranslatorInterface` e.g. `die($translator->trans('menu.topnav.language.german'));` will output `Deutsch`.

I also have installed the `symfony/translation` package. The composer.lock contains this:
```
{
            "name": "symfony/translation",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/translation.git",
                "reference": "a0485e88a72439c04c86e21e19e3f8540cc5898c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/translation/zipball/a0485e88a72439c04c86e21e19e3f8540cc5898c",
                "reference": "a0485e88a72439c04c86e21e19e3f8540cc5898c",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "symfony/polyfill-mbstring": "~1.0",
                "symfony/polyfill-php80": "^1.15",
                "symfony/translation-contracts": "^2"
            },
            "conflict": {
                "symfony/config": "<4.4",
                "symfony/dependency-injection": "<5.0",
                "symfony/http-kernel": "<5.0",
                "symfony/twig-bundle": "<5.0",
                "symfony/yaml": "<4.4"
            },
            "provide": {
                "symfony/translation-implementation": "2.0"
            },
            "require-dev": {
                "psr/log": "~1.0",
                "symfony/config": "^4.4|^5.0",
                "symfony/console": "^4.4|^5.0",
                "symfony/dependency-injection": "^5.0",
                "symfony/finder": "^4.4|^5.0",
                "symfony/http-kernel": "^5.0",
                "symfony/intl": "^4.4|^5.0",
                "symfony/service-contracts": "^1.1.2|^2",
                "symfony/yaml": "^4.4|^5.0"
            },
            "suggest": {
                "psr/log-implementation": "To use logging capability in translator",
                "symfony/config": "",
                "symfony/yaml": ""
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "5.2-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\Translation\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Fabien Potencier",
                    "email": "fabien@symfony.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony Translation Component",
            "homepage": "https://symfony.com",
            "time": "2020-06-30T17:42:41+00:00"
        }
```

My translation.yaml:
```
framework:
    default_locale: de
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de
```

**Comment by xabbuh** [comment] 2020-07-05 14:55
Can you create a small example application that allows to reproduce your issue?

**Comment by UtechtDustin** [comment] 2020-07-05 15:00
Is a new application which just have some templates and a login.


I could figure out with xdebug that i always run in that if
https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Contracts/Translation/TranslatorTrait.php#L51

Which makes sense because i dont use the arguments parameter and also not the count parameter of the trans filter.

**Comment by xabbuh** [comment] 2020-07-05 16:00
Status: Reviewed

**Comment by xabbuh** [comment] 2020-07-05 16:03
looks like this should already be fixed by #37472

**Comment by UtechtDustin** [comment] 2020-07-05 16:05
Thank you for helping debugging it @xabbuh !

**Comment by xabbuh** [comment] 2020-07-05 16:09
@fabpot @nicolas-grekas https://packagist.org/packages/symfony/twig-bundle#dev-master does not reference the latest commit (it references symfony/twig-bundle@bd852d4fbc0e7bad31e64f0203724c8d3f7ff76b while it should be  symfony/twig-bundle@e5067e5f7ecb50df3f5d161f8f62f9672ce0cad5).

**Comment by nicolas-grekas** [comment] 2020-07-05 16:31
Thanks for the ping, should be ok now.

**Comment by UtechtDustin** [comment] 2020-07-05 16:36
@nicolas-grekas Thank you :-)

**Closed** 2020-07-05 16:38 UTC
Labels: Bug, Status: Reviewed
