### ISSUE TITLE
PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "MainBundle" from namespace "MainBundle". Did you forget a "use" statement for another namespace? in /opt/lampp/htdocs/Mrigl/app/AppKernel.php:19

### ISSUE THREAD

**Issue by Abdelmonem-BEN-NACEUR** [symfony/symfony#23547] opened 2017-07-17 13:12 UTC
hi everybody , i had this error after starting new projet in symfony 2.8 and after the following command : php app/console doctrine:generate:entity
![28268939-19a17baa-6af8-11e7-88ac-361cc0b7fef1](https://user-images.githubusercontent.com/30234640/28269416-f1e2524a-6af9-11e7-8d6e-597ec26aedb5.png)

**Comment by xabbuh** [comment] 2017-07-17 15:40
This is a duplicate of #23504 which in turns is a duplicate of sensiolabs/SensioGeneratorBundle#555. Please take a look at the steps described there to solve your issue.

**Closed by xabbuh** 2017-07-17 15:40 UTC

**Comment by Abdelmonem-BEN-NACEUR** [comment] 2017-07-17 22:10
It seems, it's a problem with the symfony version.
All work well with version 3.2.8 :)

**Comment by Abdelmonem-BEN-NACEUR** [comment] 2017-07-18 00:46
If you are getting a bundle not found error in Symfony, in composer.json, modify the psr-4 section under autoload section like this.

"autoload": {
    "psr-4": {
        "": "src/"
    },
},
the execute the following command
composer dump-autoload
