### ISSUE TITLE
How to clear Symfony apcu cache by tags

### ISSUE THREAD

**Issue by Garnethouse** [symfony/symfony#25548] opened 2017-12-19 11:05 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I set cache item and this works well
```php
$cache = new ApcuAdapter('my_namespace', 3600, '2');
$cacheItem = $cache->getItem('cache_item_id');

if (!$cacheItem->isHit()) {
    $cacheData = $someClass->getDataForCache();
    $cacheItem->set($cacheData);
    $cacheItem->tag('test_tag');
    $cache->save($cacheItem);
}
```
But clear cache by tag not working ([Symfony cache component - Cache Invalidation](http://symfony.com/doc/3.3/components/cache/cache_invalidation.html))
```php
$cache = new TagAwareAdapter(new ApcuAdapter('cache_item_id'));
$invalidate = $cache->invalidateTags(['test_tag']); // true
```
That is
```php
$cacheItem->isHit() // true
```
What am I doing wrong?

**Comment by dmaicher** [comment] 2017-12-19 18:51
You need to save your item using the `TagAwareAdapter` as well:

```php
require_once 'vendor/autoload.php';

$cache = new \Symfony\Component\Cache\Adapter\ArrayAdapter();
$tagAwareCache = new \Symfony\Component\Cache\Adapter\TagAwareAdapter($cache);

$cacheItem = $tagAwareCache->getItem('cache_item_id');

if (!$cacheItem->isHit()) {
    $cacheItem->set([1, 2, 3]);
    $cacheItem->tag('test_tag');
    $tagAwareCache->save($cacheItem);
}

$cacheItem = $tagAwareCache->getItem('cache_item_id');

var_dump($cacheItem->isHit()); // ==> true

$tagAwareCache->invalidateTags(['test_tag']);

$cacheItem = $tagAwareCache->getItem('cache_item_id');

var_dump($cacheItem->isHit()); // ==> false
```

So imho not a bug on Symfony and this issue can be closed? Or do you think the documentation needs to be more clear?

**Comment by nicolas-grekas** [comment] 2017-12-23 10:06
Closing as this is not a bug. PR welcome on the doc of course to improve things.
For support questions, please use http://symfony.com/support

**Closed by nicolas-grekas** 2017-12-23 10:06 UTC
Labels: Cache

**Comment by Garnethouse** [comment] 2018-01-15 09:27
Working but new problem. Cache hit only for one page load. 

i.e this code working in method which is called 30 times. first time isHit() = false, rest 29 times is true. If page reload the situation repeats itself.

so the cache is not stored in memory for long

help please, @nicolas-grekas @dmaicher

**Comment by Garnethouse** [comment] 2018-01-15 12:29
this was my mistake, 
Thank you very much for your help
