### ISSUE TITLE
out of memory exception while creating container

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#25821] opened 2018-01-17 12:48 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes? (seems to work with 3.3.14)
| RFC?             | no
| Symfony version  | 3.4.3
| php version | 7.0.19-1

how to reproduce:
```sh
composer.phar create-project symfony/skeleton tryFailure 3.4.5
cd tryFailure
composer.phar require orm-pack symfony/validator symfony/form
composer.phar require cubetools/cube-custom-field-bundle:dev-withNewerSymfony_WIP 
# command reports an error
bin/console cache:clear --no-warmup
bin/console cache:warmup
# reports memory overflow
```

after doing following changes, the containter is created in short time:
```patch
--- a/vendor/cubetools/cube-custom-field-bundle/src/Utils/CustomFieldRepoService.php
+++ b/vendor/cubetools/cube-custom-field-bundle/src/Utils/CustomFieldRepoService.php
@@ -14,10 +16,10 @@ class CustomFieldRepoService
     private $configReader;
     private $em;
 
-    public function __construct(ConfigReader $configReader, EntityManagerInterface $em)
+    public function __construct(ConfigReader $configReader)//, EntityManagerInterface $em)
     {
         $this->configReader = $configReader;
-        $this->em = $em;
+        //$this->em = $em;
     }
 
     /**
```

But `EntityManagerInterface` is used in several places... Why does this one block?

It looks like building the container gets into a long (endless?) loop, always allocating more memory.

Is there a workaround?

**Comment by chalasr** [comment] 2018-01-23 15:58
We won't be able to help without [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html).

**Comment by SimonHeimberg** [comment] 2018-01-23 18:27
@chalasr Does this mean instead writing of the instructions (`composer.phar create-project symfony/skeleton tryFailure 3.4.5
; ...`) I shall create a repo (which contains the result)?

**Comment by xabbuh** [comment] 2018-01-23 18:42
At least with the steps you described in the issue description we cannot help you as the package there is not publicly available.

By the way, how much RAM is available when building the container in your environment?

**Comment by javiereguiluz** [comment] 2018-01-23 18:43
@SimonHeimberg if you can reproduce this bug just by running some commands, please share them. If you need some code to trigger this error, yes, you have to create a repo with the minimum possible code that triggers the error. Thanks!

**Comment by SimonHeimberg** [comment] 2018-01-23 20:10
cubetools/cube-custom-field-bundle is a public repo.
Anyway. Here is the repo: https://github.com/SimonHeimberg/symfonyIssue25821

`composer install` will report a failure message.
`bin/console cache:clear --no-warmup` reports no failure.
`bin/console cache:warmup` reports an error:
`PHP Fatal error:  Out of memory (allocated 12576620544) (tried to allocate 32768 bytes) in /home/myUser/src/symfonyIssue25821/var/cache/dev/ContainerHid8fge/getDoctrine_Orm_DefaultEntityManagerService.php on line 50`

The process used 12GB Memory (swap+ram) before dying. And it always used one cpu for 100%. (The system has 1GB Ram + 11 GB Swap).

To work around the problem, the patch shown in the description is applied (do not inject EntityManagerInterface in `vendor/cubetools/cube-custom-fieds-bundle/src/Utils/CustomFieldRepoService.php`). Then the cache is warmed immediately (after cache:clear).

**Comment by SimonHeimberg** [comment] 2018-01-26 13:06
the problem is fixed in the bundle now.
Using `\Doctrine\Common\Pesistance\ManagerRegistry` instead of `\Doctrine\ORM\EntityManager` did the trick. In the demo repo, there is the branch `working` with the working version.

But it is still unclear why there is endless loop running `cache:warmup` when using `EntityManager` in the bundle. The bug is still in symfony.

**Comment by nicolas-grekas** [comment] 2018-01-30 10:27
I cannot reproduce the issue, I get this error instead:

> Cannot autowire service "CubeTools\CubeCustomFieldsBundle\Utils\CustomFieldRepoService": argument "$em" of method "__construct()" references interface "Doctrine\ORM\EntityManagerInterface" but no such service exists. It cannot be auto-registered because it is from a different root namespace. Did you create a class that implements this interface?                                                         

steps done:
- git clone git@github.com:SimonHeimberg/symfonyIssue25821.git
- cd symfonyIssue25821
- composer install

**Comment by nicolas-grekas** [comment] 2018-01-30 10:35
But this reproduces:
- composer create-project symfony/skeleton tryFailure 3.4
- cd tryFailure
- composer require orm-pack symfony/validator symfony/form
- composer req cubetools/cube-custom-fields-bundle:dev-withNewerSymfony_WIP
- (then again) bin/console cache:clear

this triggers a segfault btw, ping @jpauli if you want to have a look

**Comment by nicolas-grekas** [comment] 2018-01-30 10:37
I someone wants to find where this loops, please do :)

**Comment by Simperfit** [comment] 2018-02-15 13:46
I can confirm this bug.
I'll give it a try, but it seems obscur ATM.

**Comment by nicolas-grekas** [comment] 2018-09-07 14:42
Should be confirmed again once #28388 is merged.

**Comment by xabbuh** [comment] 2018-11-14 11:16
This still seems to be an issue.

**Comment by nicolas-grekas** [comment] 2018-11-19 14:07
Can someone please check if  #29247 fixes the issue?

**Comment by nicolas-grekas** [comment] 2018-11-20 16:45
The reproducer doesn't work anymore as the target branch has been deleted.
I'm closing, hoping this has been solved. Please resubmit if not, with the reproducer again.

**Closed by nicolas-grekas** 2018-11-20 16:45 UTC
Labels: Bug, DependencyInjection, Status: Reviewed
