### ISSUE TITLE
CollectionType Validation Group

### ISSUE THREAD

**Issue by ychakroun** [symfony/symfony#31441] opened 2019-05-09 08:56 UTC
**Symfony version(s) affected**: 4.2.x

**Description**  
I try to add some validation groups test in Form CollectionType instance but this doesn't work, but when i remove the groups, the validation work very fine.
I already test the same think in 3.4.7 and it's work with and without groups validation.

**How to reproduce**  
```php
  /**
    * Sticker
    *
    * @ORM\Table(name="sticker")
    * @ORM\Entity(repositoryClass="App\Repository\StickerRepository")
    */
    class Sticker 
    {
       /**
         * @var \Doctrine\Common\Collections\Collection
         *
         * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="sticker", cascade={"persist", "remove"}, orphanRemoval=true)
         * @ORM\OrderBy({"position"="ASC"})
         * @Assert\Valid()
         */
        private $links;
    }
```

```php
/**
 * Link
 *
 * @ORM\Table(name="link")
 * @ORM\Entity(repositoryClass="App\Repository\LinkRepository")
 */
    class Link
    {

    /**
     * @var mixed
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     * @Assert\NotBlank()
     *
     * @ORM\Column(name="title", type="string")
     */
    private $title;

    /**
     * @var bool
     *
     * @ORM\Column(name="external", type="boolean")
     */
    private $external;

    /**
     *
     * @var string|null
     *
     * @Assert\NotBlank(groups={"isExternal"})
     * @ORM\Column(name="url", type="text", nullable=true)
     */
    private $url;

    /**
     * @var \App\Entity\Sticker|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Sticker", inversedBy="links")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="sticker_id", referencedColumnName="id", nullable=true)
     * })
     */
    private $sticker;
}
```

And this is the forms

```php
class StickerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('links', CollectionType::class, [
                'entry_type' => LinkType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'delete_empty' => true,
                'attr' => [
                    'class' => 'collection',
                ],
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sticker::class,
        ]);
    }
}
```

```php
class LinkType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre du menu:',
                'attr' => [
                    'input-group' => 'true',
                ],
            ])
            ->add('external', ChoiceType::class, [
                'label' => false,
                'expanded' => true,
                'choices' => [
                    'Lien interne' => false,
                    'Lien externe' => true,
                ],
                'choice_attr' => [
                    'class' => 'link-type',
                ],
                'label_attr' => [
                    'class' => 'btn-group btn-group-toggle',
                    'data-toggle' => 'buttons',
                ]
            ])
            ->add('url', UrlType::class, [
                'label' => 'SAISISSEZ L\'URL EXTERNE',
                'attr' => ['placeholder' => 'https://'],
            ])
            ->add('position', HiddenType::class, [
                'attr' => [
                    'class' => 'my-position',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Link::class,
            'cascade_validation' => true,
            'validation_groups' => function (FormInterface $form) {
                /** @var Link $link */
                $link = $form->getData();
                $groups = ['Default'];
                if ($link->getExternal()) {
                    $groups[] = 'isExternal';
                } else {
                    $groups[] = 'isInternal';
                }

                return $groups;
            },
        ]);
    }
}
```

**Possible Solution**  

**Additional context**  
![Zs1oB](https://user-images.githubusercontent.com/6637237/57440868-127ef500-7249-11e9-8fc2-a926a9b7ce36.png)

**Comment by ychakroun** [comment] 2019-05-16 09:42
Does anyone has the same problem?

**Comment by xabbuh** [comment] 2019-05-16 11:51
I am not sure I fully understand the issue. Could you create a small example application that allows to reproduce and play around with?

**Comment by ychakroun** [comment] 2019-05-16 12:58
Hello @xabbuh 
I just create simple exemple with two pages https://github.com/ychakroun/symfony-collection-type-issue
The first page is with Collection Type, and it's not working,
The second is the same, but without CollectionType, and it's work.

Thanks you for your help ^^

**Comment by ychakroun** [comment] 2019-05-17 11:53
@xabbuh the exemple is ok?

**Comment by DonCallisto** [comment] 2019-05-20 09:05
I've took a look at this past weekend and if I'm not mistaken, this seems to be a bug.
Didn't had the chance to tackle in a proper way though.

**Comment by xabbuh** [comment] 2019-05-20 09:08
Thank you for the application. I think I understand your issue now. I am sorry though that I have to tell you that the behaviour you observe is expected. The `validation_groups` option is only taken into account for the root form (see https://symfony.com/doc/current/reference/forms/types/form.html#validation-groups). This means that the form data is validated only by taking into account the constraints from the `Default` group.

One way to solve it can be a callback constraint on the `Link` class which decides which constraints to apply based on the object's data.

**Comment by DonCallisto** [comment] 2019-05-20 09:35
> The validation_groups option is only taken into account for the root form

So this means that root form constraint is "passed down" to its child during validation process? (e.g. if we have `Foo` and `Bar` on root form, also child forms will be validated with `Foo` and `Bar` or only with `Default`?)

This seems not to be fitting to me as you're suggesting to change entity (let's say class, in order to not be bounded to entity concept) just to adapt it to form behaviour? It should be a no-go or am I missing something here?

**Comment by xabbuh** [comment] 2019-05-20 09:59
> So this means that root form constraint is "passed down" to its child during validation process? (e.g. if we have `Foo` and `Bar` on root form, also child forms will be validated with `Foo` and `Bar` or only with `Default`?)

Not the constraint, but the groups in which validation happens should be the same for all forms of the tree.

> Moreover this seems not to be fitting to me as you're suggesting to change entity (let's say class, in order to not be bounded to entity concept) just to adapt it to form behaviour? It should be a no-go or am I missing something here?

To understand what is going on here I would leave out the whole form thing for a while. What you have after form submission is an object graph which needs to be validated. Validation starts with a root object and that the entry point where you need to decide which groups to take into account.

Since there may be different objects of the same class that have different data you cannot take one of these (deeper nested) objects to decide which groups to use (there may be two objects of that said class which would require different groups which then contradict each other).

**Comment by DonCallisto** [comment] 2019-05-20 10:02
Thanks for explaining the topic this way.
Now is clear to me that's not a bug but a consistant behaviour.

**Comment by xabbuh** [comment] 2019-05-21 06:08
So I am closing here since there is no bug.

**Closed by xabbuh** 2019-05-21 06:08 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback, Validator
