### ISSUE TITLE
[Messenger] multiple custom middleware on my bus

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#39922] opened 2021-01-21 14:31 UTC
**Symfony version(s) affected**: 4.4.17

**Description**  
I put two middleware on my messenger bus and when i try it with xdebug i enter juste one middleware and not in the second !

**How to reproduce**  
```yaml
            messenger.bus.events:
                default_middleware: false
                middleware:
                    - 'App\Bundle1\Middleware\Middleware1'
                    - 'App\Bundle2\Middleware\Middleware2'
```

And here is the content of the middleware to test

```php

class Middleware1 implements MiddlewareInterface
{

    public function __construct()
    {
    }

    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        return $stack->next()->handle($envelope, $stack);
    }

}
```

On my debug console, they are well declared. 

a quick example : [example](https://github.com/xfifix/middleware-exemple)

**Comment by OskarStark** [comment] 2021-01-21 15:29
Could you setup a small reproducer repository?

**Comment by xfifix** [comment] 2021-01-21 16:17
i have just a small controller who dispatch an event and with the xdebug I look if I go to the functions handle. I go juste in the first middleware of fist list.

**Comment by YaFou** [comment] 2021-01-21 18:06
I can't reproduce your issue @xfifix. Can you provide a small reproducer?

**Comment by xfifix** [comment] 2021-01-21 20:13
Sorry i missing an information of my projet, the two middleware aren't the same bundle.

the purpose of all this is to intercept all the events to possibly translate them into another event.

tomorrow I will try to give you an example of code.

**Comment by xfifix** [comment] 2021-01-22 07:28
a quick example : https://github.com/xfifix/middleware-exemple

**Comment by jderusse** [comment] 2021-01-22 12:13
hmm. I'm not able to reproduce the issue with. https://github.com/xfifix/middleware-exemple
What I've done:
- clone the project
- composer install
- added `dump(__CLASS__);`  in both middleware
- ran the project (`symfony server`)
- call the `Controller1` (https://127.0.0.1:8000/test)
- observe in profiler (https://127.0.0.1:8000/_profiler/latest?panel=dump) the 2 dumps, showing that both middlewares have been called

**Comment by xfifix** [comment] 2021-01-22 12:21
Thanks for your feedback.

**Comment by jderusse** [comment] 2021-01-22 12:55
Closing the issue as it works as expected.
Don't hesitate to reopen the issue if you can reproduce the failure.

**Closed as completed by jderusse** 2021-01-22 12:55 UTC
Labels: Bug, Status: Needs Review, Messenger

**Comment by xfifix** [comment] 2021-01-25 07:13
so my problem is after when I dispatch in my middleware.. 

In my middleware i use a mapping to translate an event to an other event who are dispath in an public bus.. And my public bus do the same but in the private Bus ... i try to do an ACL for my Bundle. 

it's clear ?
