### ISSUE TITLE
Fix exception with psr/container:^1.1.0

### ISSUE THREAD

**Issue by tinogo** [symfony/symfony#40383] opened 2021-03-05 16:38 UTC
**Symfony version(s) affected**: 5.2.3 and 5.2.4

**Description**
After the update of the package `psr/container` to version 1.1.0 I'm getting the following exception:

```php
Compile Error: Class Symfony\Component\DependencyInjection\Exception\ExceptionInterface cannot implement previously implemented interface Throwable
```

**How to reproduce**
* Update the `psr/container` to version 1.1.0
* Run the code associated with Symfony's DI container

**Possible Solution**
Extend `composer.json` with:

```json
{
    "conflict": {
        "psr/container": "^1.1"
    }
}
```
or 
```json
{
    "require": {
        "psr/container": "~1.0.0"
    }
}
```

or change the `Symfony\Component\DependencyInjection\Exception\ExceptionInterface` to not extend the `Throwable` interface anymore.

Or reach out to the PHP-FIG guys and ask them to drop the 1.1.0 tag entirely...

https://github.com/php-fig/container/issues/30

**Additional context**

![grafik](https://user-images.githubusercontent.com/3515498/110144885-23fb9e80-7dd9-11eb-9deb-e6fc247a86fa.png)

Observed on an XAMPP with PHP 7.2.14.

**Comment by axzx** [comment] 2021-03-05 16:44
branch 4.4 affected too

**Comment by ricohumme** [comment] 2021-03-05 16:44
I encountered this issue just now as well. 
The ContainerExceptionInterface already implements \Throwable.
I also noticed this will work in PHP 7.4 but breaks in PHP 7.3

**Comment by xabbuh** [comment] 2021-03-05 17:02
closing as a duplicate of #40382

**Closed as completed by xabbuh** 2021-03-05 17:02 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by supryantowp** [comment] 2021-12-16 09:34
I also got the same error like this. but I'm using pimcore version 6.5 and I don't know how to fix it. please help me please i've been almost a week
