### ISSUE TITLE
Autobinding to controllers failed

### ISSUE THREAD

**Issue by MathieuMindid** [symfony/symfony#28077] opened 2018-07-27 11:07 UTC
**Symfony version(s) affected**: 4.1.2

**Description**  
Since i update from 4.1.1 to 4.1.2, default binding from controllers failed : 

Controller "App\Controller\Admin\KitController::edit()" requires that you provide a value for the "$customDir" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

custom_dir is defined in env, i try to rollback to 4.1.1 and it works.

**How to reproduce**  
service.yml
```
services:
    # default configuration for services in *this* file
    _defaults:
        bind:
            $customDir: '%custom_dir%'
```
Controller : 

```
public function edit($customDir) {
// ... 
}
```

**Comment by stof** [comment] 2018-07-27 11:38
Closing as duplicate of https://github.com/symfony/symfony/issues/28041 which has already been fixed in the dev version

**Comment by MathieuMindid** [comment] 2018-07-27 11:47
I try https://github.com/symfony/symfony/pull/28052 but it didnt fix this problems.

**Comment by nicolas-grekas** [comment] 2018-07-29 15:51
> I try #28052 but it didnt fix this problems.

I just tried myself: i get the error with v4.1.2, but once I update http-kernel to 4.1@dev, it works.

**Closed by nicolas-grekas** 2018-07-29 15:51 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Status: Waiting feedback, Unconfirmed
