### ISSUE TITLE
Router concat host on url generation with absolute_path setted if router.request_context.host setted too

### ISSUE THREAD

**Issue by cirovargas** [symfony/symfony#21971] opened 2017-03-10 21:52 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.9

Facts:

I configured in my parameter.yml the router variables: host and scheme

```
router.request_context.host: mydomain11.com
router.request_context.scheme: http
```

I want to generate a route link to email from another host so I do this:

```
$mylink = 'http: //mydomain22.com'.$this-> generateUrl (' my_route ',array(), UrlGeneratorInterface :: ABSOLUTE_PATH)
```

I know the right thing is set the host in context (but it is not the case here)

The bug is that even i need an absolute path, if the current host is different from the configured in the parameters the router concat the host:

Symfony\Component\Routing\Generator\UrlGenerator
```
if ($routeHost !== $host) {
                    $host = $routeHost;
                    if (self::ABSOLUTE_URL !== $referenceType) {
                        $referenceType = self::NETWORK_PATH;
                    }
                }
```

Whenever i want to generate an absolute path the router should ignore any host parameter

That's right? If no i can do a pull request

**Comment by jakzal** [comment] 2017-03-10 23:27
I don't really follow what you're trying to do.

First thing to realise is that the request context is only used in command line. It doesn't impact web requests at all. See [Configuring the request context globally](http://symfony.com/doc/current/console/request_context.html#configuring-the-request-context-globally).

Furthermore, I don't really understand why you're appending an absolute path, which already contains the domain, to the domain:

> ```
> $mylink = 'http: //mydomain22.com'.$this-> generateUrl (' my_route ',array(), UrlGeneratorInterface :: ABSOLUTE_PATH)
> ```

Based on the configuration you provided, and assuming you're in the command line context, what value do you expect to be assigned in the `$myLink` variable?

**Comment by Tobion** [comment] 2017-03-23 22:41
Closing as the behavior to automatically add the host when it doesn't match is a feature and not a bug. Changing this would be a bc break. Why not just change (or remove the host config) from the route? Then i wouldn't try to adjust the host.

**Closed by Tobion** 2017-03-23 22:41 UTC
Labels: Routing, Unconfirmed

**Comment by cirovargas** [comment] 2017-03-24 17:01
I ask for a absolute path and the component returns a URL is not a bug?

**Comment by Tobion** [comment] 2017-03-25 01:35
It's even documented: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php#L63

**Comment by cirovargas** [comment] 2017-05-12 19:10
but my route dont requires the host

i've removed from parameters.yml:

```
router.request_context.host: mydomain11.com
router.request_context.scheme: http
```

but the router continues concat the requested route to the generated route


my app runs on mydomain1.com, i want to generate a link sended in a mail with domain test.com

test.com is a user domain, i dont know whatis

how i can do that?

**Comment by xabbuh** [comment] 2017-05-15 10:38
To be honest I do not understand your issue description. Can you maybe upload a small example project that illustrates what you are trying to do and where your approach fails?

**Comment by benjaminrau** [comment] 2017-12-12 12:49
h2. About
I am not sure if i understand the issue right but i stumpled over this post when i searched for existing tickets for my issue - which sounds quite similar.

If context::$host is empty, fx if you generate url from a command, then the $hostTokens are not replaced because this foreach loop is nested inside a condition which checks if host is set.

This means that although you have set default host for this route its not going to be replaced because host is empty.

h2. Code
\Symfony\Component\Routing\Generator\UrlGenerator::doGenerate (Symfony/Component/Routing/Generator/UrlGenerator.php:201)
```
if ($host = $this->context->getHost()) {
// Some not relevant code comes here...
// But then, still inside this if clause
    if ($routeHost !== $host) {
            $host = $routeHost;
            if (self::ABSOLUTE_URL !== $referenceType) {
                 $referenceType = self::NETWORK_PATH;
            }
     }
}
```

h2. Actual result
```
$url = $router->generate($type, $params, UrlGeneratorInterface::ABSOLUTE_URL); // $url = "/route/to/target"
```

h2. Workaround for expected result
If you set a host (no matter what) the relevant code will be reached and thus the default value for host used.

```
$router->getContext()->setHost("whatever");
$url = $router->generate($type, $params, UrlGeneratorInterface::ABSOLUTE_URL); // $url = "http://my.fallback.host/route/to/target"
```
