### ISSUE TITLE
Can't set form field to NULL value in 2.7.0-BETA1

### ISSUE THREAD

**Issue by userfriendly** [symfony/symfony#14486] opened 2015-04-27 16:30 UTC
Something that used to work before I upgraded to 2.7 doesn't anymore: setting a NULL value in a dropdown field. I've created a test bundle demonstrating the problem:

https://github.com/userfriendly/form-field-null-test-bundle

Have a look at the README and the code, and if you're not seeing anything obvious, install the bundle in a test project using Symfony 2.7 - I'm hoping it's something I'm doing wrong, but I think the code is correct according to the documentation, and it worked in earlier Symfony versions.

Add an employee with a vendor. Then add an employee without a vendor. If all works as intended (or rather, as not intended) you should get an error message for the latter, saying "This value is not valid."

The idea here is that I want to be able to create an employee instance without a vendor, i.e. the form should allow setting that field to NULL.

The mapping explicitly allows the entity property to be nullable, the setter accepts NULL as a parameter, and the form field is configured as 'required' => false. Is there something more needed to get this working in 2.7, or is this a bug?

Tested on Symfony 2.7.0-BETA1

**Comment by Tobion** [comment] 2015-04-27 19:54
Duplicate of #14393

**Closed by Tobion** 2015-04-27 19:54 UTC

**Comment by userfriendly** [comment] 2015-04-27 20:07
Thanks! :)
