### ISSUE TITLE
[String] grapheme_stripos() and grapheme_strpos() needs third argument

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#38246] opened 2020-09-20 10:30 UTC
**Symfony version(s) affected**: 5.1

**Description**  
When running a test on PHP 8, which works on PHP 7.4:
https://github.com/sonata-project/dev-kit/pull/1033/checks?check_run_id=1134015497

We got the following error:
1) App\Tests\Github\Domain\Value\RepositoryTest::throwsExceptionIfValueContainSlashButAtEnd
Failed asserting that exception of type "ValueError" matches expected exception "InvalidArgumentException". Message was: "grapheme_strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack)" at
/home/runner/work/dev-kit/dev-kit/vendor/symfony/string/UnicodeString.php:311
/home/runner/work/dev-kit/dev-kit/src/Github/Domain/Value/Repository.php:41
/home/runner/work/dev-kit/dev-kit/tests/Github/Domain/Value/RepositoryTest.php:48

I guess sth like https://github.com/symfony/symfony/commit/db4b1df0629d7d203594efc94b2f6a5c1f338ff0 is needed?

I get this error when doing:
```php
$repository = 'vendor/';

[$username, $name] = u($repository)->split('/');
```

cc @nicolas-grekas

**Comment by derrabus** [comment] 2020-09-21 10:15
This looks like exception parsing gone wrong again. I'll look into it.

**Comment by stof** [comment] 2020-09-21 10:22
@derrabus the PR https://github.com/symfony/symfony/pull/38144 added some try/catch, but we have lots of other places using `grapheme_substr`

**Comment by derrabus** [comment] 2020-09-21 20:13
@OskarStark I cannot reproduce the error locally. The `dev-kit` testsuite passes on my local php 8 installation. Does the environment you're testing in have `ext-intl`? Maybe it's a problem with the polyfill.

**Comment by OskarStark** [comment] 2020-09-22 05:01
How can I support you? You can see our composer.json here: https://github.com/sonata-project/dev-kit

**Comment by derrabus** [comment] 2020-09-22 07:31
> How can I support you?

By answering my question. 🙃

> Does the environment you're testing in have `ext-intl`?

**Comment by OskarStark** [comment] 2020-09-22 07:46
Strange now the build passes .... 🤔 
https://github.com/sonata-project/dev-kit/pull/1033

**Comment by derrabus** [comment] 2020-09-22 08:06
All right. Shall we close the issue then and you reopen if you can reproduce the problem again?

**Closed** 2020-10-01 14:30 UTC
Labels: Bug, Status: Needs Review, String
