### ISSUE TITLE
[Translator] TranslatorInterface deprectated but no fallback provided for setLocale

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#33422] opened 2019-09-02 11:52 UTC
Hello,
viewing the documentation for the translation service, it states:

> Setting the locale using $request->setLocale() in the controller is too late to affect the translator. Either set the locale via a listener (like above), the URL (see next) or call setLocale() directly on the translator service.
> 
> https://symfony.com/doc/current/translation/locale.html

But the old `Symfony\Component\Translation\TranslatorInterface` is marked as deprecated with note:
> @deprecated since Symfony 4.2, use Symfony\Contracts\Translation\TranslatorInterface instead

The problem now is `Symfony\Contracts\Translation\TranslatorInterface` does not implement `setLocale` and `getLocale` and I cannot find information on how to set it manually.

**Comment by stof** [comment] 2019-09-02 12:54
There is a LocaleAwareInterface defining these methods, and implemented by services needing the locale (the Symfony Translator implementation implements it, but we don't require every TranslatorInterface implementation to implement the LocaleAwareInterface)

**Comment by javiereguiluz** [comment] 2019-09-02 15:08
@stof thanks for the insights! I haven't looked into this ... but *"a translator interface implementation which is not aware of the locale"* looks strange. How does the translator translates if it's not aware of the locale?

**Comment by stof** [comment] 2019-09-02 15:19
it may not have mutators to set it (because it may read it from elsewhere).
Also, a service in which you inject a translator may not need to get access to its locale changing behaviors.

**Comment by xabbuh** [comment] 2019-09-03 07:15
I am closing here as explained by @stof. PR welcome if you think the upgrade files can be improved.

**Closed by xabbuh** 2019-09-03 07:15 UTC
Labels: Translator

**Comment by Amunak** [comment] 2019-09-09 12:14
> it may not have mutators to set it (because it may read it from elsewhere).

Certainly, but it still needs to know the locale, and therefore could (and probably should) have at least a `getLocale` method implemented.

> Also, a service in which you inject a translator may not need to get access to its locale changing behaviors.

Again, not necessarily locale changing, but locale reading would be greatly useful.

Currently the new Translator Contract doesn't specify a getter for locale. That makes stuff that involves internationalization in some way, just not with translations specifically, hard.

Consider that you are loading translated files into your application for some reason - say, terms and conditions from PDF files - and to do so, you need to know the locale. The "correct" locale you are looking for is in the Translator, because it's the same locale you use to serve content to the user (you don't care about locale from Request which may differ), and now there's no easy way to get it without referencing Symfony's implementation of Translator directly.

Hence I think that Symfony\Contracts\Translation\TranslatorInterface should still also require `getLocale(): string` to be implemented. As it stands the contracts are heading in a direction where they'll be so abstract that they're essentially useless.

**Comment by nicolas-grekas** [comment] 2019-09-09 12:25
The locale is not necessarily present inside the translator: e.g. an identity translator wouldn't need any, and the `trans()` method accepts a $locale argument so it can be provided explicitly also.
I think it's fine not having `getLocale()`, and the solution then is to require a locale next to where the translator is injected (+ always pass the locale explicitly to not rely on any default of the translator if you're even more strict)

**Comment by Amunak** [comment] 2019-09-09 12:56
While an identity translator (or any other translator depending on external resources to get the locale) doesn't need to have a locale *property* (and thus a mutator would make little sense or may be impossible to implement), it still needs an accessor for locale for its own purposes (when `trans()`'s `$locale` is null), and thus it can "proxy" that locale outside, complying with the theorethical `getLocale()` accessor.

As long as the `$locale` argument for `trans()` is optional, that holds true.

> I think it's fine not having getLocale(), and the solution then is to require a locale next to where the translator is injected (+ always pass the locale explicitly to not rely on any default of the translator if you're even more strict)

The issue is that currently there is no "source of truth" for locale. The framework (and optionally user listeners/subscribers) are used to guess, modify and eventually set locale for the current request. Up until now this was always set on Translator, or by some proxy (like having a listener on request, getting it from users' preferences or such, setting it on the Request object and then making Symfony take that and set it on Translator), and thus could be used as a canonical getter for the "correct" locale.

Currently this is not possible, and there is no single source off the "correct" locale. And while you're right that setting the locale explicitly is technically a solution, it's a piss poor one, in my opinion. The reason why Translator uses locale primarily from "other sources" is so that we don't have to detect and set it with each `trans()` call, so it's clearly not the intended use case.

----

I guess alternatively it would be fine to decouple this behavior from Translator entirely, and have a different, separate service "take care" of it, serving purpose as this "source of correct locale" for Translators and any other services that require locale. But it would be harder to implement, and likely not necessary: I would argue that wanting to get a "correct" locale is a pretty common issue, whereas needing a whole separate service only for getting a single property isn't all that useful.

**Comment by nicolas-grekas** [comment] 2019-09-09 14:12
Please send a PR on branch 4.4, adding the method as an annotation on the class (to not break BC)
That'll allow others to contribute to the discussion with actual code. That's always easy :)

**Comment by stof** [comment] 2019-09-09 15:18
`getLocale` does not allow the translator to know the locale. It allows code *consuming* the translator to know it. That's totally different. The translator can perfectly know the current locale without having a way to tell others what it is.
