### ISSUE TITLE
Web Profiler logs missing messages when setting the translation domain to false

### ISSUE THREAD

**Issue by tonynelson19** [symfony/symfony#21110] opened 2016-12-30 15:49 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 3.2.1

If you use a `false` translation domain to disable a translation, the web profiler displays the string as missing a translation. This commonly happens inside forms when using the `translation_domain` and `choices_translation_domain` options, but can also happen when translating directly inside Twig.

The following can recreate the issue on a new Symfony project.

```php
{{ "Hello World!"|trans({}, false) }}
```
![profiler](https://cloud.githubusercontent.com/assets/210409/21567787/9006e85a-ce74-11e6-8337-d6a66e0b639a.png)

![translation-messages](https://cloud.githubusercontent.com/assets/210409/21567802/b19a90fc-ce74-11e6-866b-3c47a6f00324.png)

![log-messages](https://cloud.githubusercontent.com/assets/210409/21567800/ac605a22-ce74-11e6-8852-9f4fd897b8c4.png)

This can be fixed by adding the following condition to the top of [`DataCollectorTranslator::collectMessage`](https://github.com/symfony/translation/blob/master/DataCollectorTranslator.php#L131) to prevent the web profiler from collecting the disabled translation.

```php
if (false === $domain) {
    return;
}
```

The same fix can be added to the top of [`LoggingTranslator::log`](https://github.com/symfony/translation/blob/master/LoggingTranslator.php#L121) to prevent a "Translation not found." warning from be logged.

**Comment by xabbuh** [comment] 2016-12-30 21:22
`false` is not a valid value for the translation domain (it must be a string). If you do not want a string to be translated at all, you should actually should not call `trans()` at all.

**Comment by tonynelson19** [comment] 2016-12-30 22:08
According to [New in Symfony 2.7: Form and Validator Updates](http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates):

> The values of the choice_translation_domain option can be true (reuse the current translation domain), false (disable translation), null (uses the parent translation domain or the default domain) and a string which represents the exact translation domain to use.

**Comment by xabbuh** [comment] 2016-12-30 22:11
That's when you are using the Form component, but your example uses the `trans` filter directly.

**Comment by tonynelson19** [comment] 2016-12-30 22:24
My example was the simplest way to recreate the issue. I mentioned the form component in the description. No methods use the same underlying translator.

**Comment by xabbuh** [comment] 2016-12-30 22:26
Well, I am not able to reproduce your issue using a form. Do you have a custom form theme?

**Comment by tonynelson19** [comment] 2016-12-30 23:09
Symfony's [theme](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig) works around this issue by wrapping all calls to `trans()` in the following logic:

```twig
{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}
```

This logic exists 9 times in the theme. Remembering to add it to custom form themes can be a challenge, and some third party or legacy themes might not apply the logic correctly. However, the logic could be removed entirely by applying my proposed changes.

Would you be more open to this change if the issue was labeled a DX improvement rather than a bug?

**Comment by xabbuh** [comment] 2016-12-31 10:38
Even then, we couldn't make the change to the interface as that would mean a BC break. Do, no, I do not see another solution than using form themes for this.

**Comment by tonynelson19** [comment] 2016-12-31 12:01
How exactly is it a BC break?

**Comment by xabbuh** [comment] 2016-12-31 12:11
Because all implementations of the interface would need to be updated to still work even when they get passed a boolean value instead of a string.

**Comment by tonynelson19** [comment] 2016-12-31 12:38
This wouldn't break any Symfony implementations that I'm aware of.

If you're concerned about breaking third party implementations, would you like me to create a different issue about how there currently is not any logic to prevent users from using non-string values for domains when adding translations resources? The translation ID is cast to a string in [some](https://github.com/symfony/translation/blob/master/Translator.php#L195) [places](https://github.com/symfony/translation/blob/master/Translator.php#L211), but aside from checking for a (`null` domain)[https://github.com/symfony/translation/blob/master/Translator.php#L125], other scalar types are allowed.

**Comment by xabbuh** [comment] 2016-12-31 12:43
The `TranslationInterface` is one of our extension points in the Translation component and its documentation is clear on that all implementations can expect the domain to be either a string or `null`: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/TranslatorInterface.php#L26 So we have no way to influence what other implementations out there are doing inside `trans()`.

**Comment by tonynelson19** [comment] 2016-12-31 12:57
Which is why my request was to modify [`DataCollectorTranslator::collectMessage`](https://github.com/symfony/translation/blob/master/DataCollectorTranslator.php#L131) and [`LoggingTranslator::log`](https://github.com/symfony/translation/blob/master/LoggingTranslator.php#L121), not [`TranslatorInterface::trans`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/TranslatorInterface.php#L33).

I just want to improve the developer experience.

**Comment by xabbuh** [comment] 2016-12-31 13:01
But being able to pass `false` as the message domain to `LoggingTranslator::log()` means that you must have passed `false` to `trans()` before. This could be caught inside the `LoggingTranslator` before it forwards the `trans()` call to the decorated translator. However, to do that you must know upfront whether or not the current translator instance is a `LoggingTranslator` or another implementation of the `TranslatorInterface`. Currently, I do not see how we could solve that issue.

**Comment by tonynelson19** [comment] 2016-12-31 13:31
Since the `TranslationInterface`'s documentation makes it clear that all implementations can expect either a string or `null`, couldn't the `LoggingTranslator` and `DataCollectorTranslator` implementations safely ignore any domains that aren't either strings or `null` in their respective `log` and `collectMessage` methods, or should they throw an `InvalidArgumentException`?

**Comment by xabbuh** [comment] 2016-12-31 13:48
The `log()` method is only called internally by the `LoggingTranslator` when one of its methods given by the interface is called. This still means that you will have to ensure that the translator you are using actually is the `LoggingTranslator` before calling any of its method with `false` as the message domain.

**Comment by tonynelson19** [comment] 2016-12-31 14:05
Then shouldn't any implementations of `TranslationInterface` inside the `Symfony\Component\Translation` namespace throw an `InvalidArgumentException` if you call either `trans()` or `transChoice()` with `false` as the message domain? 

Right now it seems like using a `false` domain is both not supported and yet not unsupported, allowing developers to use it due to lack of strict type checking.

**Comment by xabbuh** [comment] 2016-12-31 14:15
Well, we could avoid logging if the domain is `false`. But I am not sure if that's worth the effort. If we did that change, you would never notice that you'd better update your form theme.

**Comment by javiereguiluz** [comment] 2017-02-23 08:39
I agree with @tonynelson19 and I'm trying to fix this in #21726.

**Comment by curry684** [comment] 2018-09-04 20:52
As the proposed fix did not get merged, nor a consensus on that it should be fixed, this issue should likely also be closed. If anything we now do have the option to make the interface "correct" in 4.x (or even 5.x) as we now have a base PHP version supporting nullable type hinting.

**Comment by xabbuh** [comment] 2018-11-13 13:03
I am closing here as the dicsussion in the related PR didn't reach a consensus.

**Closed by xabbuh** 2018-11-13 13:03 UTC
Labels: Bug, DX, Status: Reviewed, Translator
