### ISSUE TITLE
Symfony isn't updating the project when a file is changed

### ISSUE THREAD

**Issue by giancarloandroid** [symfony/symfony#22641] opened 2017-05-05 00:01 UTC
**Bug report?** 
Yes

**Symfony version**
3.3.0-BETA1

**Description**
Symfony isn't updating the project files.

**Pictures:**

**index.html.twig:** 
![selecao_738](https://cloud.githubusercontent.com/assets/8602136/25728393/27258366-3105-11e7-9140-3c8368550d47.png)

**http://192.168.50.4:8081:** 
![selecao_739](https://cloud.githubusercontent.com/assets/8602136/25728435/6b8b0346-3105-11e7-804d-931dce0335e0.png)

**Comment by mvrhov** [comment] 2017-05-05 06:31
I'm running beta and it works as expected. But I'm running php-fpm and nginx
Looking at the url I'd say that you are running embedded webserver. so maybe the embedded server is acting up or you are not running in dev mode or Opcache is acting up..

**Comment by javiereguiluz** [comment] 2017-05-05 06:38
I can't reproduce either:

```bash
$ symfony new reproduce_22641 3.3.0-beta1
```

Then I start the local web server, and it works as expected:

![issue-22641](https://cloud.githubusercontent.com/assets/73419/25735812/3372d678-316e-11e7-8ec1-64c9840ad383.png)

**Comment by mvrhov** [comment] 2017-05-05 08:53
Or maybe he's on MAC or using some virtualization technology where he has a drive mapped somehow and that virtualization layer is lying to the OS that the file is saved but its still in cache somewhere.

**Comment by stof** [comment] 2017-05-05 09:37
Or maybe he's running the app in the prod environment, which would then require clearing the cache when editing the template

**Comment by javiereguiluz** [comment] 2017-05-05 09:46
@giancarloandroid I'm closing this issue because it's likely not a Symfony bug. I'd try @stof's suggestion first and then @mvrhov's idea about caches.

If the error persist, please reopen this issue and create a "bug reproducer" as explained here: https://symfony.com/doc/current/contributing/code/reproducer.html

Thanks!

**Closed by javiereguiluz** 2017-05-05 09:46 UTC

**Comment by mvrhov** [comment] 2017-05-05 11:09
> Or maybe he's running the app in the prod environment, 

That's what I've written too just  a bit differently :)

**Comment by giancarloandroid** [comment] 2017-05-05 12:38
Thank you all, I was thinking that could be some cache!

**Comment by meotimdihia** [comment] 2017-05-06 09:50
I am trouble with this problem too , and i sure it relate twig's problem - because its still work, when i try to print variable in controller.

This is my twig configuration , Dev environment.

```yaml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    auto_reload:               true
    optimizations:             -1
```

i am using Homestead ( Windows, smb file sharing).

**Comment by javiereguiluz** [comment] 2017-05-06 09:53
@meotimdihia your `twig.debug` and `twig.auto_reload` options look OK, so it must be a cache issue "somewhere" (homestead? the host OS? the virtualized OS? ...?)

**Comment by meotimdihia** [comment] 2017-05-06 10:01
@javiereguiluz 
I tried to ssh in Homestead VM , and see Twig file was changed. 
This problem can be solve by disable twig cache, but performance will decreases dramatically.

**Comment by meotimdihia** [comment] 2017-05-07 01:13
i just checked again. And found out its SMB folder sharing problem. After switched to default sharing, everything is ok.
But now i must deal with slow sharing problem.

**Comment by meotimdihia** [comment] 2017-05-07 09:32
Finally, i found out this problem. 
Reason is Windows time wasn't synchronized. It seems Microsoft time server down.

![](https://i.gyazo.com/93fb86d56dd7b5d97683763182ae7554.png)

hence , my Windows time always run faster than Virtualbox time -> Symfony saved cached file time in future time.
This problem happen when folder sharing type is Rsync or SMB  in my case.

**Comment by javiereguiluz** [comment] 2017-05-07 14:31
@meotimdihia thanks for sharing the details of your solution! The unsynchronized time server looks like a truly hard-to-debug issue :(

**Comment by giancarloandroid** [comment] 2017-05-08 22:38
I changed the file `app.php` to run with development enviroment.

**File:**
[app.php](https://github.com/symfony/symfony-standard/blob/master/web/app.php)

Line 11:

`$kernel = new AppKernel('prod', false);`

changed to: 

`$kernel = new AppKernel('dev', true);`

And I fixed the Vagrant file on the project.

Thank you all!

**Comment by PulzWave** [comment] 2024-11-18 12:21
I had this problem as well. To maybe help others searching about this matter, for me it was related to a time sync issue as well.

I have found a good workaround by disabling a certain PHPStorm feature.

(Tools --> Deployment --> Options)
![image](https://github.com/user-attachments/assets/aaeda50f-f8e3-4bf6-9609-9d0e8b3bba6e)

This way, I avoid time syncs to be an issue here because the target deployment server will always be leading.
