### ISSUE TITLE
Web Profiler is broken in Symfony 4.4.13 with PHP 7.1.25

### ISSUE THREAD

**Issue by Harry-Dunne** [symfony/symfony#38057] opened 2020-09-04 09:10 UTC
**Symfony version(s) affected**: 4.4.13

**Description**  

An exception is raised when you browse the welcome page of a freshly installed symfony 4.4 project. The welcome page briefly appears and is replaced by an error page displaying this exception:

> Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given

**How to reproduce**  

Install a fresh project:

     symfony new my_project --version=4.4 --full

Run the server:

    symfony server:start

Browse the homepage http://127.0.0.1:8000/

**Possible Solution**  

I found a workaround by downgrading doctrine/doctrine-bundle:

In composer.json, replace:

        "doctrine/doctrine-bundle": "^2.1",

by:

        "doctrine/doctrine-bundle": "2.1.0",

Run `composer update` ; Weirdly it removes symfony/web-profiler-bundle. You have to install it again by running `composer req symfony/web-profiler-bundle`

**Comment by ro0NL** [comment] 2020-09-04 12:29
Unable to reproduce, fresh install shows welcome page; `Welcome to Symfony 4.4.13`

Can you find out if any of the answers in https://github.com/symfony/symfony/search?q=Sensio%5CBundle%5CFrameworkExtraBundle%5CRequest%5CParamConverter%5CDoctrineParamConverter%3A%3A__construct%28%29+must+be+an+instance+of+Doctrine%5CCommon%5CPersistence%5CManagerRegistry+or+null%2C+instance+of+Doctrine%5CBundle%5CDoctrineBundle%5CRegistry+given&type=Issues helps?

**Comment by Harry-Dunne** [comment] 2020-09-04 13:03
> Can you find out if any of the answers in https://github.com/symfony/symfony/search?q=Sensio%5CBundle%5CFrameworkExtraBundle%5CRequest%5CParamConverter%5CDoctrineParamConverter%3A%3A__construct%28%29+must+be+an+instance+of+Doctrine%5CCommon%5CPersistence%5CManagerRegistry+or+null%2C+instance+of+Doctrine%5CBundle%5CDoctrineBundle%5CRegistry+given&type=Issues helps?

Sadly, no. sensio/framework-extra-bundle >=5.6.0 requires PHP >= 7.2.5, and I'm stuck with PHP 7.1.25...

**Comment by xabbuh** [comment] 2020-09-04 13:32
There is nothing we can do about that in Symfony. Please open an issue in the SensioFrameworkExtraBundle repository to ask if a patch fixing this in a release that is compatible with PHP 7.1 can be made. I am therefore closing here. Thank you for understanding.

**Closed by xabbuh** 2020-09-04 13:32 UTC
Labels: Bug, Status: Needs Review

**Comment by Harry-Dunne** [comment] 2020-09-04 13:45
Ok, I'll do that. But if a fresh Symfony 4.4 project doesn't work with PHP 7.1, it's a major BC break IMHO...

**Comment by fabpot** [comment] 2020-09-05 14:10
I've just released v5.5.7 which should fix this issue.
