### ISSUE TITLE
ProfilerListener mutate response onKernelResponse

### ISSUE THREAD

**Issue by Helo3615** [symfony/symfony#44605] opened 2021-12-14 07:56 UTC
### Symfony version(s) affected

5.4

### Description

My controller call a repository to remove an item.

**Controller :**
```
    public function __invoke(int $id): JsonResponse
    {
       // Checking authorization and existance of item

        $this->items->remove($item);

        return new JsonResponse();
    }
```
**Repository :**
```
    public function remove(Item $item)
    {
        $this->cloneQueryBuilder()->getEntityManager()->remove($item);
        $this->cloneQueryBuilder()->getEntityManager()->flush();
    }
```
**Problem :** At the very end the response is not the same (type "text" instead of "json" for exemple) because it is mutate after the controller's return.

After looking for every listener that happen after the return I found `\Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse` being guilty.
I have to remove these lines to make it work : 

```
        if (!$profile = $this->profiler->collect($request, $event->getResponse(), $exception)) {
            return;
        }

        $this->profiles[$request] = $profile;

```

Thank you for your help 

### How to reproduce

The context is very broad, I don't think that is easily reproducible. 
But if you have any idea on why it is happening I will be glad to add informations.

### Additional Context

**Composer.json :**

```
{
    "name": "",
    "type": "project",
    "require": {
        "php": "^7.3",
        "aws/aws-sdk-php-symfony": "^2.1",
        "beberlei/doctrineextensions": "^1.2",
        "doctrine/doctrine-bundle": "^2.5",
        "doctrine/doctrine-migrations-bundle": "^2.0",
        "doctrine/orm": "^2.10",
        "doctrine/persistence": "^2.2",
        "egulias/email-validator": "^3.1",
        "firebase/php-jwt": "^5.0",
        "knplabs/dictionary-bundle": "^3.2",
        "nmure/encryptor": "~1.0.0",
        "oro/doctrine-extensions": "^1.3",
        "ramsey/uuid": "^3.8",
        "scienta/doctrine-json-functions": "^4.0",
        "sensio/framework-extra-bundle": "^5.2",
        "stof/doctrine-extensions-bundle": "^1.3",
        "swaggest/json-schema": "^0.12.25",
        "symfony/amqp-messenger": "^5.4",
        "symfony/cache": "^5.4",
        "symfony/dependency-injection": "^5.4",
        "symfony/doctrine-messenger": "^5.4",
        "symfony/form": "^5.4",
        "symfony/http-client": "^5.4",
        "symfony/mailer": "^5.4",
        "symfony/messenger": "^5.4",
        "symfony/monolog-bundle": "^3.7",
        "symfony/serializer": "^5.4",
        "symfony/symfony": "^5.4",
        "symfony/twig-bundle": "^5.4",
        "symfony/validator": "^5.4",
        "tuxxydos/knplabs-rad-user": "dev-master",
        "webmozart/assert": "^1.4"
    },
    "require-dev": {
        "behat/behat": "^3.5",
        "behat/mink": "dev-master",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.1",
        "friends-of-behat/mink-extension": "^2.5",
        "friends-of-behat/symfony-extension": "^2.2",
        "galbar/jsonpath": "dev-master",
        "guzzlehttp/guzzle": "^6.3",
        "hautelook/alice-bundle": "^2.9",
        "phpspec/phpspec": "^6.0",
        "phpunit/phpunit": "^9.5",
        "slevomat/coding-standard": "^6.0",
        "symfony/debug-bundle": "^5.4",
        "symfony/profiler-pack": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "Application\\": "src/Application",
            "Domain\\": "src/Domain",
            "Infrastructure\\": "src/Infrastructure"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "": "features/bootstrap/"
        }
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^5.4.*"
        }
    }
}

```

**Comment by derrabus** [comment] 2021-12-14 08:43
I'm moving this to support because without a reproducer this bug ticket is not actionable.

**Closed as completed** 2021-12-14 08:43 UTC
Labels: Bug, Status: Needs Review
