### ISSUE TITLE
[Console][Supervisor] Environment variables are loaded from .env.local.php; ignoring env

### ISSUE THREAD

**Issue by darthf1** [symfony/symfony#34189] opened 2019-10-30 14:02 UTC
**Symfony version(s) affected**: 4.3.5

**Description**
I'm using SF with Messenger in a Docker container. The `messenger:consume` command is run through supervisor as per the [docs](https://symfony.com/doc/current/messenger.html#supervisor-configuration)

Using Flex I have generated a `.env.local.php` from my `.env`. These are mostly DEV values and won't work in production. In production, the real values are presented in the `ENV`. E.g. for database connection this works; it ignores the `DATABASE_URL` value in `.env.local.php` and connects with the value presented in the `ENV`.

When I `exec` into the docker image and run `bin/console messenger:consume` manually it works; the result is:
```
[OK] Consuming messages from transports "async".
```

But when that command is ran through supervisor, the result is: 
```
In PDOConnection.php line 27:

  SQLSTATE[08006] [7] could not translate host name "db" to address: Name or
  service not known

messenger:consume [-l|--limit LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [-
-] <command> [<receivers>...]
```

Host name `db` is part of the `DATABASE_URL` value in `.env.local.php`

`supervisor/messenger.conf`:
```
[program:messenger-consume]
command=/srv/api/bin/console messenger:consume --time-limit=3600
user=root
numprocs=2
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
```

Edit:
After giving this more thought (getting new insights from writing this issue), I found that supervisor is running in it's own environment. Then it seems logical why this 'issue' is arising and isn't a Symfony issue at all. I guess the docs could be updated? Haven't found a solution yet but when I have, I'll try a PR.

**Comment by stof** [comment] 2019-10-30 15:01
Note that `.env.local.php` is not meant to be committed in the repo (same than `.env.local`). It is meant to dump an optimized loading of `.env` and `.env.local`, and so should live by the same rules than `.env.local`.

**Comment by darthf1** [comment] 2019-10-30 15:10
@stof  Thanks for your comment. Yes, only .env is commited in the repo. The issue is that running a Symfony console command (or any command/action for that matter) through supervisor will be executed in a new environment. Therefore if you are using SF, running console commands through supervisor and relying on environment variables it won't work.

**Comment by mu4ddi3** [comment] 2020-06-30 09:50
I confirm that this problem still exist.
Currently using `Symfony 4.4.7`
I have `.env` commited to git with dummy-data and `.env.local` on server with real-data.
After configuring supervisor like in provided docs page, variables are grabbed from `.env` file and it is obviously wrong.

**Comment by nicolas-grekas** [comment] 2020-08-31 20:54
I'm closing because the issue is in the edited description: the env var needs to be set also in the supervisor's context.

**Closed by nicolas-grekas** 2020-08-31 20:54 UTC
Labels: Bug, Console, Status: Needs Review
