### ISSUE TITLE
Super slow after upgrade to flex project structure

### ISSUE THREAD

**Issue by pesseyjulien** [symfony/symfony#40261] opened 2021-02-20 14:50 UTC
Hi,

I have followed the following doc : https://symfony.com/doc/current/setup/flex.html#upgrade-to-flex

I have fixed all deprecation/bug/etc, but now my app is super slow, like painfully slow !

Below, same request, the fastest one made on the same code but using the old structure :

![sf-bundle](https://user-images.githubusercontent.com/10850944/108599663-c86df180-7392-11eb-8fbd-f89157e262e1.jpg)
![sf-flex](https://user-images.githubusercontent.com/10850944/108599661-c73cc480-7392-11eb-8f96-5f03677ef7e4.jpg)

What could be explaining the more than 2s difference ?!

I tried the following : https://symfony.com/doc/current/performance.html
But nothing works !

Interesting fact, it's faster running locally in dev mode ! 

And yes, on the screens, the 'APP_ENV' is set to 'prod', it's running in testing env.

Thanks in advance for your help,
Julien

**Comment by xabbuh** [comment] 2021-02-20 15:11
If you think this is a Symfony issue, please create a small example application that allows us to reproduce it.

**Comment by pesseyjulien** [comment] 2021-02-20 16:30
Well maybe you could take a look at the repo if I add you ?

Do you know why it's slower in prod than dev ? Isn't kinda weird ?

All I did is changed the project structure, how could it affects speed ?

Thanks,
Julien

**Comment by nicolas-grekas** [comment] 2021-02-20 16:58
Please try using [a profiler](https://blackfire.io/) to know.

I'm closing here as this is likely an issue on your side - not a bug in Symfony.

Let us know if you spot a bug of course.

**Closed as completed by nicolas-grekas** 2021-02-20 16:58 UTC
Labels: Status: Waiting feedback

**Comment by pesseyjulien** [comment] 2021-02-20 17:27
Like I said, I only change the project structure to meet the last standard : symfony/flex

The code is still the same, so how could it my from my side ? And even if it's, I'm trying hard to find out where it's coming from and only seeking help, this is why I tagged this with 'question' rather than 'bug',

Only trying to get some help but you are only sending me away, like not even trying..

I was hoping for some more from the community, but well. I guess it's not always up to one's hope !

If you don't want people to ask questions, juste closed the issue section !

Thanks for nothing I guess,
Julien

**Comment by pesseyjulien** [comment] 2021-02-20 17:34
![Capture d’écran 2021-02-20 à 18 34 45](https://user-images.githubusercontent.com/10850944/108603820-60c3a080-73aa-11eb-85f4-6ebbf80e0868.jpg)

**Comment by nicolas-grekas** [comment] 2021-02-20 17:42
The performance issue you're experimenting has not been reported by others, that's why I think this is not a bug in Symfony.
I'm sorry blackfire doesn't work for you.
Without a performance profile, playing a guessing game can take ages to solve. Of course, nobody but you can conduct this profile.
Maybe xdebug could help?
We use this issue tracker for bug reports and features tracking.
For support requests, please use eg Slack.

**Comment by pesseyjulien** [comment] 2021-02-20 17:50
Alright, thanks.

Didn't know there was a slack, will try it !

I guess it's a server issue, using heroku for production, as on my machine it's running fine.

**Comment by pesseyjulien** [comment] 2021-02-20 18:21
Well 99$ for blackfire as it's not local..kinda expensive for debugging purpose.

I managed to get some info using Newrelic

![Capture d’écran 2021-02-20 à 19 20 14](https://user-images.githubusercontent.com/10850944/108604876-cc107100-73b0-11eb-9667-e336192a657f.jpg)

Any idea what is 'Remainder' ?

**Comment by chalasr** [comment] 2021-02-20 18:25
Hello,

We use Github issues for tracking bugs and feature requests. 
If you are looking for support, you should use one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

Thanks.
