### ISSUE TITLE
[DI] Default autowiring settings are lost for a Controller when arguments are explicitly set, and the controller doesn't extends the FrameworkBundle Controller class

### ISSUE THREAD

**Issue by magarzon** [symfony/symfony#24124] opened 2017-09-07 10:46 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

When a controller has a dependency to a parameter instead of a service, you have to explicitly set that arguments this way:

```yaml
services:
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: [controller.service_arguments]

    AppBundle\Controller\AdminController:
        arguments:
            $adminEmail: 'manager@example.com'
```
The issue is that when doing this, if the controller doesn't extend FrameworkBundle Controller class, it lost all default configuration, as in this example, AdminController doesn't have `controller.service_arguments` tag nor `public: true` setting anymore, and you must explicitly set also.

**Comment by javiereguiluz** [comment] 2017-09-07 14:21
@magarzon thanks for reporting this issue. However, I'm afraid I cannot reproduce this error. I have some apps suing this config and they work as expected.

Is the AdminController a regular Symfony controller or is it managed by some bundle such as Sonata?

**Comment by magarzon** [comment] 2017-09-07 22:13
I got the example from Symfony documentation, not actual project, but I have found why it happens in my project and why not in yours: my controllers doesn't extends from FrameworkBundle Controller class.

I have tested, extending one of the controller from that class, and its default configuration is not reset.

**Comment by magarzon** [comment] 2017-09-07 23:48
More tests, more info:

As I said, if the controller doesn't extends from Framework Controller class, it lost all default configuration when an argument is explicitly set. (it doesn't show when execute debug:container --tag=controller.service_arguments, for example )

But even if it extends from base controller, but an argument it's explicitly set, the ControllerResolver class fail to instantiate the controller because it's not in the methodMap field of the container where this class try to get the controller/service, as other controllers are.

This doesn't happen with a normal service, if you create a service and explicitly set an argument, the service is correctly instantiated, so this issue it's only with the controllers

**Comment by magarzon** [comment] 2017-09-08 01:12
And eventually I found the root of the problem (unfortunately I don't have time nor a deep knowledge in this Symfony code to fix it):

1) When the container load the configuration in services.yml, it first create a definition for each Controller based on the defaults for all Controllers that we have set in the service.yml (public = true, tag controller.service_arguments). But when it founds the explicit definition for the argument in AdminController (in the example), it overwrites the previous definition for AdminController, with defaults values of public = false, no tags.

2) If AdminController extends from Framework controller class, the controller.service_arguments is re-added by the compiler pass that handles the autoconfigure feature (ResolveInstanceofConditionalsPass) that set some defaults values to classes that extends from some specific framework classes. That's the reason why if the controller extends from Framework controller calls it has the controller.service_arguments tag, but not if it doesn't extend

3) Anyway, in both cases (subclass or not), as stated in point 1, the default definition for the controller is overwritten, and although the tag is re-added if the class extends from the framework class (point 2), the parameter public remains set to false. And then, there is another compiler pass that removes "unused" services, that is, services that ARE PRIVATE AND NOT REFERENCED, but as the Controller are only "used" at runtime (that is, there are no other services that have them as a dependency), and the definition for this particular controller has been overwritten and set to private, is removed, and then the ControllerResolver can't find the services, try to instantiate (new $class) and it fails, because the controller has a dependency in a value.

**Comment by nicolas-grekas** [comment] 2017-09-08 09:14
@magarzon this is not a bug, this is just the way it works:
each new service declaration replaces any previous one that had the same id.

**Comment by magarzon** [comment] 2017-09-08 11:47
@nicolas-grecas I disagree, according to this link https://symfony.com/doc/current/service_container.html#services-manually-wire-args you can set a parameter to a service and "symfony takes care of the rest". In fact, you don't have to define other dependencies, for example. But this, that works for other services, doesn't work for controllers, so or either is a bug, or this documentation should be changed to say that you can't do it with controllers

**Comment by nicolas-grekas** [comment] 2017-09-08 11:52
The doc doesn't tell about additional options (public: true & tags: [controller.service_arguments]).
The logic is just as I described, which means these are *not* borrowed from the 1st to the 2nd declaration (neither does the doc suggest this happens.)
If you can think of a way to make that easier to get, I invite you to open a doc PR.

**Comment by magarzon** [comment] 2017-09-08 12:19
The doc suggest that you can inject a parameter to a service. If you do in a controller, you break it. If you think that this it's ok without any warning...

**Comment by nicolas-grekas** [comment] 2017-09-08 12:27
I'm sure something confused you, I'm trying to explain you the low level stuff so maybe you can help fix the doc and save a few hours to another you that would end up in the same situation :)

So, to be able to inject a service as a parameter to your controller's actions, that controller need to be tagged with "controller.service_arguments". Here, in your second definition, you define a service, but this service doesn't have this tag set. So it doesn't work.

**Comment by javiereguiluz** [comment] 2017-09-08 12:37
I think both of you are right :)  This definitely needs at least some additional clarification in the docs.

**Comment by chalasr** [comment] 2017-09-08 16:43
Closing as explained.

**Closed by chalasr** 2017-09-08 16:43 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Unconfirmed
