### ISSUE TITLE
[Validator][FunctionalTest] Length constraint's default message is different before/after call request method on WebTestCase's Client

### ISSUE THREAD

**Issue by pawel-k-coll** [symfony/symfony#19010] opened 2016-06-09 13:23 UTC
Hello,
I'm writing functional tests (file `ProductTest.php` below) to test validation and found that `Length`'s constraint error message is different before calling `Client`'s (`Symfony\Bundle\FrameworkBundle\Client`) `request` method and after doing this.

Message before call `request` on `Client` is `This value is too long. It should have 9 character or less.|This value is too long. It should have 9 characters or less.` (`testValidationWithoutClient` in `ProductTest.php`),
but after call `request` on `Client` the message is `This value is too long. It should have 9 characters or less.`. (`testValidationWithClient` in `ProductTest.php`)

Why this message is different after call `request` on `Client` and why message is wrong before call `request` on `Client`?

I tested it in empty Symfony (standard edition) `v2.7.14` and `v3.1.0` versions with default framework configuration.

Source files:
- `src/AppBundle/Resources/config/validation.yml`

``` yaml
AppBundle\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 1
          max: 9
```
- `src/AppBundle/Entity/Product.php`

``` php
<?php

namespace AppBundle\Entity;

class Product
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
}
```
- `tests/AppBundle/Entity/ProductTest`

``` php
<?php

namespace Tests\AppBundle\Entity;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use AppBundle\Entity\Product;

class ProductTest extends WebTestCase
{
    /**
     * @var ValidatorInterface
     */
    private $validator;

    public function setUp()
    {
        self::bootKernel();

        $this->validator = self::$kernel
            ->getContainer()
            ->get("validator");
    }

    public function testValidationWithoutClient()
    {
        $productEntity = new Product();

        $productEntity->setName("AbcAbcAbcAbcAbcAbcAbcAbcAbcAbc");

        $errors = $this
            ->validator
            ->validate($productEntity);

        $this->assertSame("This value is too long. It should have 9 characters or less.", $errors->get(0)->getMessage());
    }

    public function testValidationWithClient()
    {
        $client = self::createClient();

        $client->request("GET", "/");

        $productEntity = new Product();

        $productEntity->setName("AbcAbcAbcAbcAbcAbcAbcAbcAbcAbc");

        $errors = $this
            ->validator
            ->validate($productEntity);

        $this->assertSame("This value is too long. It should have 9 characters or less.", $errors->get(0)->getMessage());
    }
}
```

`php -v`

```
PHP 7.0.7-4+deb.sury.org~wily+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

`OS`

```
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
```

**Comment by jakzal** [comment] 2016-06-29 16:00
First of all, thank you for this detailed but report! It's very helpful.

However, I've tried to reproduce this bug [on a fresh Symfony installation](https://github.com/symfony/symfony-standard/compare/2.7...jakzal:issue19010?expand=0), but both your [tests are passing](https://travis-ci.org/jakzal/symfony-standard/builds/141118360) on all PHP versions starting from 5.3 up to 7.0. 

Would you mind modifying my branch to reproduce this issue? It's got travis configured.

**Comment by pawel-k-coll** [comment] 2016-06-30 08:50
Thank you for your answer.

I'm afraid i can't modify code to reproduce this issue because it's looks like this depends of environment.
I've done some checks on different OSes (all 64bit, i can paste more details if you want):

Locally installed:
Windows 8.1 - fail
Ubuntu 16.04 (mine and my coworkers also) - fail

Vagrant:
Debian 7 - success
Ubuntu 14.04 - success

Can you test this issue on your locally installed OS?

**Comment by jakzal** [comment] 2016-06-30 08:57
> Can you test this issue on your locally installed OS?

I did. It passes on both OS X and my docker setup (based on default php image, various versions).

**Comment by pawel-k-coll** [comment] 2016-06-30 09:57
Now i'm also have Ubuntu 16.04 with default PHP (7.0.4) and tests fail, but i can only provide screenshot to prove it.

Can this issue be related to the system's language, timezone or is it just configuration of php/xdebug/other-extension and other software?

**Comment by jakzal** [comment] 2016-06-30 14:24
@pawel-k-coll perhaps. Could you list your language, timezone and loaded php extensions please? 

Unless I get a reproducible scenario I won't be able to help much.

**Comment by pawel-k-coll** [comment] 2016-07-08 07:30
Below are dumps from my locally installed Ubuntu (test fail) and Ubuntu in Vagrant (test success), hope it helps.

**Locally installed Ubuntu 16.04:**
`locale` result:
```
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

`php -i | grep date.timezone` result:
```
date.timezone => no value => no value
```

`php -m` result:
```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Ubuntu 16.04 in Vagrant:**
`locale` result:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```
`php -i | grep date.timezone` result
```
date.timezone => UTC => UTC
```
`php -m` result:
```
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

**Comment by pawel-k-coll** [comment] 2016-07-08 09:20
Done, but still fail. This also fail on locally installed Windows 8.1 so, IMO, this can be related to PHP/Symfony configuration not OS.

**Comment by xabbuh** [comment] 2017-01-13 18:39
I am closing this issue as we won't be able to fix something in the code as long as we are unable to reproduce it.

@pawel-k-coll Feel free to comment with further information on how to reproduce your issue and we can consider to reopen.

**Closed by xabbuh** 2017-01-13 18:39 UTC
Labels: Bug, Status: Needs Review, Unconfirmed, Validator
