### ISSUE TITLE
[2.7] Deprecated Message in XMLFileLoader

### ISSUE THREAD

**Issue by Gladhon** [symfony/symfony#14845] opened 2015-06-03 10:10 UTC
I get an error if i try to install symfony2.7 via composer

 trigger_error('Symfony\\Component\\DependencyInjection\\Definition::setFactoryMethod(getRepository) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead.', 16384) /Symfony/Component/DependencyInjection/Definition.php:137

It seems that the XMLFileLoader on 2.7 is not updated. In the master, the problem seem to be solved.

https://github.com/symfony/DependencyInjection/blob/2.7/Loader/XmlFileLoader.php#L150

**Comment by stof** [comment] 2015-06-03 10:15
The XmlFileLoader uses the old API if you use the deprecated configuration in the XML.

**Comment by xabbuh** [comment] 2015-06-03 11:39
Closing as a duplicate of #14687 which will be fixed by #14798.

**Closed by xabbuh** 2015-06-03 11:39 UTC

**Comment by Gladhon** [comment] 2015-06-03 11:42
I see, thx
