### ISSUE TITLE
[Form][Twig] form_theme in the view doesn't select the correct theme

### ISSUE THREAD

**Issue by coudenysj** [symfony/symfony#15162] opened 2015-07-01 12:14 UTC
I have multiple form themes in a project, but I'm struggling with the "selection" process of the correct theme.

In my `config.yml` file I've registered all themes (without this, the `form_theme` selection is ignored al together):
```yml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        asset_version: %asset_version%
    form_themes:
        - form_div_layout.html.twig
        - bootstrap_3_horizontal_layout.html.twig
        - common/form/forms.html.twig
        - SyliusWebBundle:Common:forms.html.twig
        - SyliusResourceBundle::forms.html.twig
```

In the twig views, I use `{% form_theme form 'common/form/forms.html.twig' %}` and `{% form_theme form 'SyliusWebBundle:Backend:forms.html.twig' %}` to select the correct theme, but this is not working.

**Comment by stof** [comment] 2015-07-01 12:27
Themes registered are **all** used (Symfony will search the block in all of them until it finds the necessary block). ``{% form_theme form '...' %}`` is not about selecting a theme. It is about registering one more theme just for this form (but the themes registered globally will still be used as fallback in case your theme does not define theming for all blocks but other themes do)

**Comment by coudenysj** [comment] 2015-07-01 12:38
Thanks @stof for replying.

What you say makes sense, but when I remove the Sylius themes from the list the `form_theme` does not use the requested theme.

I'm using `{% form_theme form 'SyliusWebBundle:Backend:forms.html.twig' %}`, added a syntax error in the template file, removed my cache dir and still the default bootstrap theme is being used.

**Comment by stof** [comment] 2015-07-03 08:17
Well,  the issue is that ``SyliusWebBundle:Backend:forms.html.twig`` is not a proper form theme. It does not define any blocks. so rendering is forced to fallback to global themes to find something
If it is intended to be a form theme, there is a bug in Sylius.

**Comment by coudenysj** [comment] 2015-07-03 08:24
So the problem lies in the fact that [SyliusWebBundle:Backend:forms.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/forms.html.twig) includes [SyliusWebBundle:Common:forms.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig) and [SyliusResourceBundle::forms.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Resources/views/forms.html.twig) rather that containing the blocks itself?

**Comment by stof** [comment] 2015-07-03 08:34
yeah. If they want to combine other form themes, they should use ``{% use %}`` to import their blocks rather than ``{% include %}`` (which includes the output of the template)

**Comment by stof** [comment] 2015-07-03 08:34
however, this would also require changing the other templates a bit to be traitable

**Comment by javiereguiluz** [comment] 2016-02-07 20:30
Closing it because this doesn't look like a Symfony bug.

**Closed by javiereguiluz** 2016-02-07 20:30 UTC
Labels: Form
