### ISSUE TITLE
Stopwatch - Stop() called before Start() Exception in app_dev.php

### ISSUE THREAD

**Issue by QuantumRevenger** [symfony/symfony#18842] opened 2016-05-22 20:35 UTC
```php
/**
     * Stops the last started event period.
     *
     * @throws \LogicException When start wasn't called before stopping
     *
     * @return StopwatchEvent The event
     *
     * @throws \LogicException When stop() is called without a matching call to start()
     */
    public function stop()
    {
        if (!count($this->started)) {
            throw new \LogicException('stop() called but start() has not been called before.');
        }

        $this->periods[] = new StopwatchPeriod(array_pop($this->started), $this->getNow());

        return $this;
    }
```

**Comment by xabbuh** [comment] 2016-05-22 21:42
Please explain what exactly your problem is.

**Comment by QuantumRevenger** [comment] 2016-05-23 03:00
Everytime I run XDebug, Connect Firefox Developer Edition, then execute debugging the session breaks due to an exception being thrown. (own in-house)  software. 

This is a fresh copy of Symfony Standard 3.0.6

@throws \LogicException When start wasn't called before stopping

When requesting route / [homepage] via app_dev.php 

Whilst not mission critical to the end user, it becomes a painful experience when debugging the application.

**Comment by stof** [comment] 2016-06-01 14:46
the question is why you are calling ``stop()`` on an event which is not started. The exception being thrown in this case makes perfect sense.

We cannot do anything for you without a reproducing testcase.

**Comment by QuantumRevenger** [comment] 2016-06-01 16:53
The thing is, I am not calling stop() and this is the problem. It is throwing an exception even when using a blank / fresh copy of Symfony 3.0.6 Standard. It happens in any application I develop.

I am using the latest plugin for PHP Storm, and Xdebug with PHP 7.0.7

To recreate the bug, all you have to do is start a copy of Symfony 3.0.6 Standard with Xdebug and PHP 7 it will hit a breakpoint and throw at this exception. Note, I am calling from app_dev.php (haven't tried against app.php) but it makes development a pain at times.

**Comment by xabbuh** [comment] 2016-06-01 17:54
I cannot reproduce your issue. Can you please show the full stack trace for the exception you get?

**Comment by fabpot** [comment] 2016-06-21 14:51
Closing as there is no feedback.

**Closed by fabpot** 2016-06-21 14:51 UTC
Labels: Bug, Status: Needs Review, Unconfirmed

**Comment by igormukhingmailcom** [comment] 2019-03-14 11:36
Just had same issue on API endpoint.
Issue appeared for unknown reason (nothing was changed) and was persistent (not disappeared).

Disabling xDebug at php.ini helped...
Thanks @QuantumRevenger for idea.

```php
Uncaught PHP Exception LogicException: "stop() called but start() has not been called before." at vendor/symfony/symfony/src/Symfony/Component/Stopwatch/StopwatchEvent.php line 103 {"exception":"[object] (LogicException(code: 0): stop() called but start() has not been called before. at vendor/symfony/symfony/src/Symfony/Component/Stopwatch/StopwatchEvent.php:103)"} []
```
