### ISSUE TITLE
[Cache] [BC] cache namespace changed after minor update

### ISSUE THREAD

**Issue by eminjk** [symfony/symfony#57366] opened 2024-06-10 21:14 UTC
### Symfony version(s) affected

7.1.0

### Description

In my project, multiple instances are connected to the same cache server (Redis) and share the same data under the same namespace due to `framework.cache.prefix_seed` config.

During the execution of canary deployments, mostly related to transition to Symfony 7.1, it was observed that new instances completely missed the cache. Upon inspection of Redis, an additional set of keys containing different prefix (namespace) was identified. 

This issue appears to have been introduced in #52948.

[src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php](https://github.com/symfony/symfony/pull/52948/files#diff-3569dde6f3d6129291e06bf19c39c073cb730023bb188f0569836ccc6308e0a7)

There is also PR related to this matter (#57302), but I believe that note about BC might not be enough keeping in mind the Backward Compatibility Promise.

### How to reproduce

store the cache  using `symfony/cache`  `7.0` and try to retrieve it using `7.1`

### Possible Solution

revert the previous hash algorithm or introduce the possibility to force cache namespace through the configuration

**Comment by nicolas-grekas** [comment] 2024-06-11 12:45
Thanks for the issue. I'm closing as duplicate of #57302

**Closed as not planned by nicolas-grekas** 2024-06-11 12:45 UTC
Labels: Bug, Status: Needs Review, Cache
