### ISSUE TITLE
Annotation is used in DocBlock comment even though it is not used to annotate class

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#12870] opened 2014-12-05 16:54 UTC
Hello,

[`AnnotationClassLoader`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php) class has DocBlock comment that describes usage of `@Route` annotation.
However the DocBlock contains the `@Route` text which means, that `AnnotationClassLoader` is using the annotation (ie. it is a controller action?). In this case `@Route` is not meant to be effective annotation.

~~I don't know if there is any way how to escape annotations when they are not meant as annotations.~~
But you can use `@IgnoreAnnotation("Route")` to tell `AnnotationReader` to ignore `@Route` as an annotation.

I guess that `AnnotationReader` automatically ignores *undefined* annotations, but the problem is in the file of fore-mentioned [`AnnotationClassLoader`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php) class. It contains `use Symfony\Component\Routing\Route` statement which causes that `AnnotationReader` thinks that `@Route` is `Symfony\Component\Routing\Route` class, which is not an annotation class.

It all results in this error:
```
[Doctrine\Common\Annotations\AnnotationException]                                                                                                                                             
  [Semantical Error] The class "Symfony\Component\Routing\Route" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then you need to add @Annotation to the _class_ doc comment of "Symfony\Component\Routing\Route". If it is indeed no annotation, then you need to add @IgnoreAnnotation("Route") to the _class_ doc comment of class Symfony\Component\Routing\Loader\AnnotationClassLoader.
```

As a test case you can try this:
```php
$ref = new \ReflectionClass('Symfony\Component\Routing\Loader\AnnotationClassLoader');
$annotationReader = new \Doctrine\Common\Annotations\AnnotationReader();
$annotationReader->getClassAnnotations($ref);
```

The only solution I know about is to add `@IgnoreAnnotation(...)` to all DocBlocks where annotations are not meant as annotations.

**Comment by Tobion** [comment] 2015-01-16 04:37
@sustmi why would you read annotations from the AnnotationClassLoader? I don't why you would encouter this issue.

**Comment by fabpot** [comment] 2015-02-10 13:43
Closing as it looks like a misusage.

**Closed by fabpot** 2015-02-10 13:43 UTC
Labels: Routing

**Comment by alekitto** [comment] 2015-09-25 11:15
I encountered this issue trying to use JMSDiExtraBundle and extending `AnnotationClassLoader`.

```
use JMS\DiExtraBundle\Annotation as DI;
use Symfony\Component\Routing\Loader\AnnotationClassLoader;

/**
 * @DI\Service(id="foo.routing_loader")
 * @DI\Tag("routing.loader")
 */
class FooRoutingLoader extends AnnotationClassLoader
{
...
```

The annotation reader tries to read all the annotations in the class hierarchy and throws an `AnnotationException` when encounters an unescaped `@Route` annotation (used for doc).
`@IgnoreAnnotation` does not work as it is not valid for parent classes.

Now i am forced to not use annotations.
Am i doing something wrong?

**Comment by emudojo** [comment] 2019-08-26 03:11
I will say this has to be re-opened, the following packages together will cause the exception to appear again for no good reason, I'll say documentation blocks should be escaped

 "symfony/symfony": "3.4.3",
 "doctrine/doctrine-bundle": "1.11.2",
  "doctrine/annotations": "1.7.0",

**Comment by xabbuh** [comment] 2019-08-26 05:37
@emudojo Please open a new issue and provide some steps to reproduce if you think you stumbled upon a bug.

**Comment by steady-daddy** [comment] 2020-10-04 10:23
I faced the same issue. It turned out that I was using an incorrect Routing bundle. I was using:
`use Symfony\Component\Routing\Route;` 
I changed it to:
`use Symfony\Component\Routing\Annotation\Route;`
and it worked for me.
