### ISSUE TITLE
[PHPUnit Bridge] PHPUnit crashes: Class 'Symfony\Bridge\PhpUnit\TextUI\Command' not found

### ISSUE THREAD

**Issue by Inari-Whitebear** [symfony/symfony#31751] opened 2019-05-30 19:39 UTC
**Symfony version(s) affected**: 4.3.0

**Description**  
Running PHPUnit crashes.

```
PS E:\Dev\web\phpunit-test> ./vendor/bin/simple-phpunit
INFO: Could not find files for the given pattern(s).
PHP Fatal error:  Uncaught Error: Class 'Symfony\Bridge\PhpUnit\TextUI\Command' not found in E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4\phpunit:17
Stack trace:
#0 E:\Dev\Web\phpunit-test\vendor\symfony\phpunit-bridge\bin\simple-phpunit.php(258): include()
#1 E:\Dev\Web\phpunit-test\vendor\symfony\phpunit-bridge\bin\simple-phpunit(13): require('E:\\Dev\\Web\\phpu...')
#2 {main}
  thrown in E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4\phpunit on line 17
```

**How to reproduce**  
Create project from website skeleton. Install PHPUnit bridge, run simple-phpunit.

**Comment by nicolas-grekas** [comment] 2019-06-04 13:44
I cannot reproduce.

**Comment by nicolas-grekas** [comment] 2019-06-04 13:46
Closing as duplicate of #31750

**Closed by nicolas-grekas** 2019-06-04 13:46 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review
