### ISSUE TITLE
PSR-11 not implemented correctly

### ISSUE THREAD

**Issue by delboy1978uk** [symfony/symfony#34263] opened 2019-11-06 15:43 UTC
**Symfony version(s) affected**:
https://github.com/symfony/dependency-injection latest

**Description**  
https://www.php-fig.org/psr/psr-11/

PSR-11 interface docblock says:
     * @throws NotFoundExceptionInterface  No entry was found for **this** identifier.
     * @throws ContainerExceptionInterface Error while retrieving the entry.

The Symfony Exceptions only appear to throw the NotFoundExceptionInterface

**Possible Solution** 
try and catch in the get() method, throw the correct Exception if anything is caught

**Comment by nicolas-grekas** [comment] 2019-11-06 15:47
`interface NotFoundExceptionInterface extends ContainerExceptionInterface` so this might still be considered compliant to me.
How did you spot this?

**Comment by delboy1978uk** [comment] 2019-11-06 16:35
Chatting in ##php about containers :-P 
Yeah, actually I suppose technically you are correct, but if any other exception is thrown whilst trying to fetch a valid container item, we are supposed to throw a ContainerExceptionInterface, but the docblock says `* @throws \Exception                        if an exception has been thrown when the service has been resolved`, and it's that part that needs sorting.

**Comment by nicolas-grekas** [comment] 2019-11-06 16:53
Since PSR-11 has `has()`, it is trivial to ensure that id exists or not.
If one writes code that relies on a try/catch to do control flow, I'd say this code is fragile and we don't need to help it work - that would be tight coupling to edgy behavior to me.

**Comment by delboy1978uk** [comment] 2019-11-06 16:56
This is about Exceptions thrown for container keys where `has()` will return true. For instance of some Factory throws an `InvalidArgumentException`, we are supposed to catch that and throw an Exception implementing `ContainerExceptionInterface`

**Comment by stof** [comment] 2019-11-07 09:39
Well, exception thrown by the DI component itself (detecting a circular reference for instance) are implementing the PSR-11 interface.

We are indeed not catching exceptions thrown by the code of services themselves. But I'm fine with that for 2 reasons:

- wrapping all instantiations in a try/catch would add overhead
- it would actually make debugging harder by hiding the original exception

Thus, I'm not sure PSR-11 intended to force intercepting all exceptions coming from the code referenced in the container here.

**Comment by delboy1978uk** [comment] 2019-11-07 10:01
If this package is never meant to be used in isolation from Symfony, then I guess that's fine, but if we want to use this in another non-Symfony project that expects the correct PSR-11 behaviour, then that's not fine. I guess that's your call.

**Comment by delboy1978uk** [comment] 2019-11-07 10:03
>     * it would actually make debugging harder by hiding the original exception
There's nothing stopping us create an exception class that contains the original exception

**Comment by nicolas-grekas** [comment] 2019-11-07 10:12
> Thus, I'm not sure PSR-11 intended to force intercepting all exceptions coming from the code referenced in the container here.

I agree with this interpretation. All is compliant to me here.

I'm closing because we're not going to wrap all exceptions, so the issue is resolved here.
Thanks for raising the point.

**Closed by nicolas-grekas** 2019-11-07 10:12 UTC
Labels: DependencyInjection

**Comment by delboy1978uk** [comment] 2019-11-07 10:46
Correct, there's no forcing anyone, other than the NotFoundException, but we SHOULD throw a ContainerExceptionInterface. So I guess it is compliant, just not 100%.

> Exceptions directly thrown by the container SHOULD implement the Psr\Container\ContainerExceptionInterface.
> 
> A call to the get method with a non-existing id MUST throw a Psr\Container\NotFoundExceptionInterface.

**Comment by jvasseur** [comment] 2019-11-07 11:01
> Exceptions directly thrown by the container SHOULD implement the Psr\Container\ContainerExceptionInterface.

Personally I'm interpreting the "directly" as "any exception throw by the container code should implement the interface" meaning we don't need to catch any exception throw by a factory.

**Comment by delboy1978uk** [comment] 2019-11-07 11:06
I suppose so, factory exceptions would be inderect. Ok cheers guys!
