### ISSUE TITLE
Big slowdown since Symfony 3.2

### ISSUE THREAD

**Issue by gadelat** [symfony/symfony#21558] opened 2017-02-07 17:20 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

Here is our build performance.
![screenshot from 2017-01-31 10 54 08](https://cloud.githubusercontent.com/assets/496233/22702619/9d87addc-ed61-11e6-9ab3-4ecfac2a753e.png)

After upgrade to Symfony 3.2, automated tests suite take 2x longer to finish.

I tracked it down to this PR https://github.com/symfony/symfony/pull/21381

**Comment by nicolas-grekas** [comment] 2017-02-07 17:21
Does #21556 fix your issue?

**Comment by gadelat** [comment] 2017-02-07 17:30
Sorry, did not realize this is dupe of https://github.com/symfony/symfony/issues/21549

Yes, https://github.com/symfony/symfony/pull/21556 does fix the issue

Do you have a recommendation how to fix this temporarily until the new release with this fixed comes?

**Comment by nicolas-grekas** [comment] 2017-02-07 17:45
Alias `annotation_reader` to a bootstrapping cached reader that uses ArrayCache?

**Comment by nicolas-grekas** [comment] 2017-02-08 12:46
closing as duplicate of #21549 then, thanks

**Closed by nicolas-grekas** 2017-02-08 12:46 UTC
