### ISSUE TITLE
symfony/serializer Versioning

### ISSUE THREAD

**Issue by gmuehl** [symfony/symfony#37096] opened 2020-06-04 10:39 UTC
**Description**  
Implement **'since'** and **'until'** of JMS Serializer for versioning 

**Example**  

```
    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     *
     * @SerializedName("dummy_rest")
     * @SerializedGroup({"dummies"})
     *
     * @Since("1.20")
     * @Until("1.30")
     */
    private $dummy;
```

**Comment by ro0NL** [comment] 2020-06-04 11:03
see https://github.com/symfony/symfony/pull/35617

**Comment by xabbuh** [comment] 2020-06-04 11:07
closing as a duplicate of #30848 then

**Closed by xabbuh** 2020-06-04 11:07 UTC
Labels: Feature, Serializer
