### ISSUE TITLE
"php-http/httplug" package is not installed

### ISSUE THREAD

**Issue by rpayanm** [symfony/symfony#42020] opened 2021-07-07 17:29 UTC
**Description**
I installed this library:
https://symfony.com/doc/4.4/http_client.html
I am using it, but when I run this code:
```
use Symfony\Component\HttpClient\HttplugClient;

$httpClient = new HttplugClient();
```
I got this error:
```
You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/httplug" package is not installed. Try running "composer require php-http/httplug".
```

Here the output of `composer show | egrep "symfony|php-http`
```
php-http/httplug                         2.2.0         HTTPlug, the HTTP cl...
php-http/message-factory                 v1.0.2        Factory interfaces f...
php-http/promise                         1.1.0         Promise used for asy...
symfony-cmf/routing                      2.3.3         Extends the Symfony ...
symfony/console                          v4.4.25       Eases the creation o...
symfony/css-selector                     v5.3.0        Converts CSS selecto...
symfony/debug                            v4.4.25       Provides tools to ea...
symfony/dependency-injection             v4.4.25       Allows you to standa...
symfony/deprecation-contracts            v2.4.0        A generic function a...
symfony/error-handler                    v4.4.25       Provides tools to ma...
symfony/event-dispatcher                 v4.4.25       Provides tools that ...
symfony/event-dispatcher-contracts       v1.1.9        Generic abstractions...
symfony/filesystem                       v4.4.26       Provides basic utili...
symfony/finder                           v5.3.0        Finds files and dire...
symfony/http-client                      v4.4.26       Provides powerful me...
symfony/http-client-contracts            v2.4.0        Generic abstractions...
symfony/http-foundation                  v4.4.25       Defines an object-or...
symfony/http-kernel                      v4.4.25       Provides a structure...
symfony/mime                             v5.3.0        Allows manipulating ...
symfony/polyfill-ctype                   v1.23.0       Symfony polyfill for...
symfony/polyfill-iconv                   v1.23.0       Symfony polyfill for...
symfony/polyfill-intl-idn                v1.23.0       Symfony polyfill for...
symfony/polyfill-intl-normalizer         v1.23.0       Symfony polyfill for...
symfony/polyfill-mbstring                v1.23.0       Symfony polyfill for...
symfony/polyfill-php72                   v1.23.0       Symfony polyfill bac...
symfony/polyfill-php73                   v1.23.0       Symfony polyfill bac...
symfony/polyfill-php80                   v1.23.0       Symfony polyfill bac...
symfony/process                          v4.4.25       Executes commands in...
symfony/psr-http-message-bridge          v2.1.0        PSR HTTP message bridge
symfony/routing                          v4.4.25       Maps an HTTP request...
symfony/serializer                       v4.4.25       Handles serializing ...
symfony/service-contracts                v2.4.0        Generic abstractions...
symfony/translation                      v4.4.25       Provides tools to in...
symfony/translation-contracts            v2.4.0        Generic abstractions...
symfony/validator                        v4.4.25       Provides tools to va...
symfony/var-dumper                       v5.3.0        Provides mechanisms ...
symfony/yaml                             v4.4.25       Loads and dumps YAML...
```
I have installed `"nyholm/psr7": "^1.3",` as well.

**Comment by stof** [comment] 2021-07-07 18:03
Can you give the full error (i.e. not only the error message but also the location and stack trace) ?

Also, it would be great if you could build a full reproducer for the issue.

**Comment by rpayanm** [comment] 2021-07-07 18:18
I am using it on a Drupal site:

```
The website encountered an unexpected error. Please try again later.

LogicException: You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/httplug" package is not installed. Try running "composer require php-http/httplug". in include() (line 44 of /app/vendor/symfony/http-client/HttplugClient.php).

Composer\Autoload\includeFile('/app/vendor/composer/../symfony/http-client/HttplugClient.php') (Line: 322)
Composer\Autoload\ClassLoader->loadClass('Symfony\Component\HttpClient\HttplugClient')
spl_autoload_call('Symfony\Component\HttpClient\HttplugClient') (Line: 105)
Drupal\liv_mf_entrata_connection\Service\EntrataApiService->doRequest('liv_mf_entrata_connection.get_property_units', 86400, 'POST', '/propertyunits', Array, 1) (Line: 279)
Drupal\liv_mf_entrata_connection\Service\EntrataApiService->getPropertyUnits(1) (Line: 62)
Drupal\liv_mf_floor_plans\Form\FloorPlansForm->__construct(Object, Object, Object, Object, Object) (Line: 74)
Drupal\liv_mf_floor_plans\Form\FloorPlansForm::create(Object) (Line: 28)
Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition('\Drupal\liv_mf_floor_plans\Form\FloorPlansForm') (Line: 193)
Drupal\Core\Form\FormBuilder->getFormId('\Drupal\liv_mf_floor_plans\Form\FloorPlansForm', Object) (Line: 227)
Drupal\Core\Form\FormBuilder->buildForm('\Drupal\liv_mf_floor_plans\Form\FloorPlansForm', Object) (Line: 219)
Drupal\Core\Form\FormBuilder->getForm('\Drupal\liv_mf_floor_plans\Form\FloorPlansForm') (Line: 50)
Drupal\liv_mf_floor_plans\Plugin\Block\FloorPlansBlock->build() (Line: 192)
Drupal\block_field\Plugin\Field\FieldFormatter\BlockFieldFormatter->preRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 786)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 377)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 88)
__TwigTemplate_b92b8ea716ceb0bb746c8ce7a20146e2d991f19a948d4f5a77b73edcbc1f91e8->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('core/themes/classy/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 61)
__TwigTemplate_9eca65d5c3a283ab1c193eedf95c51a366acb5e7ece3cb66eb4ac0d1b6185047->block_content(Array, Array) (Line: 182)
Twig\Template->displayBlock('content', Array, Array) (Line: 58)
__TwigTemplate_91facee3818c80ac1ddf762dd63838d3d0152624273056a07fca70657e60e046->block_paragraph(Array, Array) (Line: 182)
Twig\Template->displayBlock('paragraph', Array, Array) (Line: 46)
__TwigTemplate_91facee3818c80ac1ddf762dd63838d3d0152624273056a07fca70657e60e046->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array, Array) (Line: 47)
__TwigTemplate_9eca65d5c3a283ab1c193eedf95c51a366acb5e7ece3cb66eb4ac0d1b6185047->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('themes/custom/liv_mf/templates/paragraphs/paragraph--block--default.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('paragraph', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 207)
__TwigTemplate_85ecf734f9a10e8eb822cb2e8c9e5b513a188cd2af1d6c61c4f9a11ee9c9cf4b->block_content(Array, Array) (Line: 182)
Twig\Template->displayBlock('content', Array, Array) (Line: 142)
__TwigTemplate_85ecf734f9a10e8eb822cb2e8c9e5b513a188cd2af1d6c61c4f9a11ee9c9cf4b->block_paragraph(Array, Array) (Line: 182)
Twig\Template->displayBlock('paragraph', Array, Array) (Line: 123)
__TwigTemplate_85ecf734f9a10e8eb822cb2e8c9e5b513a188cd2af1d6c61c4f9a11ee9c9cf4b->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('themes/custom/liv_mf/templates/paragraphs/paragraph--content-row--default.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('paragraph', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 68)
__TwigTemplate_b92b8ea716ceb0bb746c8ce7a20146e2d991f19a948d4f5a77b73edcbc1f91e8->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('core/themes/classy/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 449)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 110)
__TwigTemplate_009aa3633c55e5e881018e1f6bffd876f29e671ea1c4905568f48092fcd64151->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('core/themes/classy/templates/content/node.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 578)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 716)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

```

**Comment by rpayanm** [comment] 2021-07-07 18:21
It is odd the path `/app/vendor/composer/...` I have the vendor folder at the root of my project:
![image](https://user-images.githubusercontent.com/6087454/124809856-fb2a1800-df36-11eb-9151-dd39f17b1003.png)

EDIT: I'm sorry, I am working with docker and it is correct the path, that is how is in the docker image.

**Comment by Taluu** [comment] 2021-07-08 12:29
Why are you using the http-plug client without installing the http-plug package ? It's here only for interoperability : https://symfony.com/doc/4.4/http_client.html#interoperability

You will probably want to use the `HttpClient` instead.

**Comment by stof** [comment] 2021-07-08 13:03
@Taluu the weird thing is that the composer package list shows httplug as being installed (see the first one in the list).

**Comment by nicolas-grekas** [comment] 2021-07-08 13:07
That's likely because the package is listed as a dev-dep.

**Comment by nicolas-grekas** [comment] 2021-07-11 18:59
Closing as duplicate of #41672
Please see there for the reason why and the discussion around that behavior.

**Closed as completed by nicolas-grekas** 2021-07-11 18:59 UTC
Labels: Bug, Status: Needs Review, HttpClient

**Comment by nicolas-grekas** [comment] 2021-07-11 19:01
Oh, I might have closed too fast.
Please submit a reproducer and I'll reopen :)
