### ISSUE TITLE
Autoloading broken with 4.4.31/5.3.8

### ISSUE THREAD

**Issue by yann-eugone** [symfony/symfony#43212] opened 2021-09-28 09:05 UTC
**Symfony version(s) affected**: 4.4.31, 5.3.8

**Description**
First encountered an error after `composer update` with
```
Class "Symfony\Component\Translation\Command\TranslationPullCommand" 
used for service "console.command.translation_pull" cannot be found.   
```

Then I figured out that classes seems to have been moved to wrong places.

**How to reproduce**
Please consider compare from 
- `symfony/translation` : https://github.com/symfony/translation/compare/v5.3.7...v5.3.8
- `symfony/messenger` : https://github.com/symfony/messenger/compare/v5.3.7...v5.3.8
- `symfony/mailer` : https://github.com/symfony/mailer/compare/v5.3.4...v5.3.8
- `symfony/notifier` : https://github.com/symfony/notifier/compare/v5.3.4...v5.3.8

**Comment by ghost** [comment] 2021-09-28 09:16
Same here. Autoloading breaks after running composer update.

**Comment by drupol** [comment] 2021-09-28 09:19
Same issue: https://pastebin.com/bEK51cD3

**Comment by hhamon** [comment] 2021-09-28 09:19
Experiencing similar issue as well:

```
Executing script cache:clear --no-warmup [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 255
!!  PHP Warning:  Module 'blackfire' already loaded in Unknown on line 0
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#92794
!!    #message: """
!!      Attempted to load interface "MiddlewareInterface" from namespace "Symfony\Component\Messenger\Middleware".\n
!!      Did you forget a "use" statement for "Sentry\SentryBundle\Tracing\Doctrine\DBAL\Compatibility\MiddlewareInterface"?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php"
!!    #line: 26
!!    trace: {
!!      ./vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php:26 { …}
!!      ./vendor/symfony/error-handler/DebugClassLoader.php:349 { …}
!!      Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
!!      ./vendor/symfony/doctrine-bridge/Messenger/DoctrineTransactionMiddleware.php:25 { …}
!!      ./vendor/symfony/error-handler/DebugClassLoader.php:349 { …}
!!      Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
!!      spl_autoload_call() {}
!!      ./vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php:976 { …}
!!      ./vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php:79 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:744 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:545 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:786 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:125 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:167 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:56 { …}
!!      ./vendor/autoload_runtime.php:35 { …}
!!      ./bin/console:11 {
!!        › 
!!        › require_once dirname(__DIR__) . '/vendor/autoload_runtime.php';
!!        › 
!!        arguments: {
!!          "/home/hhamon/Code/tal-rebuild/vendor/autoload_runtime.php"
!!        }
!!      }
!!    }
!!  }
!!  2021-09-28T09:12:15+00:00 [critical] Uncaught Error: Interface 'Symfony\Component\Messenger\Middleware\MiddlewareInterface' not found
!!  
Script @auto-scripts was called via post-install-cmd   
```

The `Symfony\Component\Messenger\Middleware` namespace doesn't have a `MiddlewareInterface`...

**Comment by yann-eugone** [comment] 2021-09-28 09:27
While everyone is working on a bugfix release for this, you can skip this version with a `conflict` instruction in your `composer.json`

```
{
    "conflict": {
        "symfony/translation": "v5.3.8",
        "symfony/mailer": "v5.3.8",
        "symfony/notifier": "v5.3.8",
        "symfony/messenger": "v5.3.8"
    }
}
```

**Comment by gjuric** [comment] 2021-09-28 09:28
Mailer is also problematic.

**Comment by icanhazstring** [comment] 2021-09-28 09:28
Someone pointed out this commit as possible problem?https://github.com/symfony/messenger/commit/2c472d5c36f599786229d2b6effa7201891a81f0

**Comment by drupol** [comment] 2021-09-28 09:29
I think this is indeed a part of the issue.

**Comment by Bilge** [comment] 2021-09-28 09:31
How did automated tests not catch this? 🤔

**Comment by drupol** [comment] 2021-09-28 09:32
The problematic commits are:

- symfony/messenger: https://github.com/symfony/messenger/commit/2c472d5c36f599786229d2b6effa7201891a81f0
- symfony/translation: https://github.com/symfony/translation/commit/89b162f3d885bae57a79f83df2fc0c4228c117ba
- symfony/mailer: https://github.com/symfony/mailer/commit/ea6c7db7e5f67acb4efb910ed2dd8c7787a61c74
- symfony/notifier: https://github.com/symfony/notifier/commit/250211d3a5404196827e0427033dfbe21d6042dd

**Comment by jvasseur** [comment] 2021-09-28 09:33
Those commits doesn't have this problem in the main repo, it looks like there is a problem in the subtree split process.

**Comment by szepczynski** [comment] 2021-09-28 09:35
I got issue also with symfony/notifier, the full conflict that works:

```
    "conflict": {
        "symfony/symfony": "*",
        "symfony/translation": "v5.3.8",
        "symfony/messenger": "v5.3.8",
        "symfony/mailer": "v5.3.8",
        "symfony/notifier": "v5.3.8"
    },
```

**Comment by williamdes** [comment] 2021-09-28 09:44
```json
    "conflict": {
        "symfony/symfony": "*",
        "symfony/translation": "v4.4.31",
        "symfony/messenger": "v4.4.31",
        "symfony/mailer": "v4.4.31",
        "symfony/notifier": "v4.4.31"
    },
```
On old Laravel projects...
Seems like some quality checks are missing..

**Comment by javiereguiluz** [comment] 2021-09-28 09:44
Update: thanks for reporting this issue. We're aware of it and we think we found the cause. We're working on a fix and we hope to fix this very soon. Thanks!

**Comment by jokaorgua** [comment] 2021-09-28 10:12
don't you think that 5.3.8 tag should be removed from the list of releases until the issue will be fixed to decrease the bug effect?

**Comment by javiereguiluz** [comment] 2021-09-28 10:12
This issue affects to Messenger, Mailer, Notifier and Translator (all of them have bridges). We've fixed the problem and we're force pushing those four repositories, so this should be fixed in just a few minutes.

~If things go as expected, there's no need to remove the 4.4.31 and 5.3.8 releases or re-release them. They will work again when the repositories are re-pushed.~

**Comment by gander** [comment] 2021-09-28 10:13
> don't you think that 5.3.8 tag should be removed from the list of releases until the issue will be fixed to decrease the bug effect?

Same as **_v4.4.31_**

**Comment by jokaorgua** [comment] 2021-09-28 10:16
@javiereguiluz were the tests added to cover this situation in the future?

**Comment by javiereguiluz** [comment] 2021-09-28 10:19
Sadly, PHPUnit/Symfony tests don't matter in this case. It was a bug related to the release process (the actual splitting of the Symfony monorepo into hundreds of stand-alone packages and pushing them to GitHub).

**Comment by javiereguiluz** [comment] 2021-09-28 10:20
Update: apparently, the four faulty components (Messenger, Mailer, Notifier and Translator) have been fixed and we're starting a new release process. Hopefully this will be fully fixed in just a few minutes. Thanks!

**Comment by Bilge** [comment] 2021-09-28 10:23
@javiereguiluz I think we understand the current tests do not cover this, and perhaps even the current testing approach could not cover this, but without fully understanding the problem I would nevertheless tend to assume it would still be *possible* to write a test to cover this, even if it requires a new testing approach to cover component integration.

Aside, what exactly was the problem here? It seems a select few know the details but they have not been shared with the rest of us at this time, and I think it would be interesting to know; maybe even a formal post-mortem is warranted?

**Comment by gander** [comment] 2021-09-28 10:23
```json
    "conflict": {
        "symfony/symfony": "*",
        "symfony/translation": "v5.3.8 || v4.4.31",
        "symfony/mailer": "v5.3.8 || v4.4.31",
        "symfony/notifier": "v5.3.8 || v4.4.31",
        "symfony/messenger": "v5.3.8 || v4.4.31"
    }
```

**Comment by javiereguiluz** [comment] 2021-09-28 10:25
The new 4.4.* version has been released. Please, run `composer update` again if you use that branch.

The 5.3.* version will follow very soon.

**Comment by Messhias** [comment] 2021-09-28 10:26
> The new 4.4.* version has been released. Please, run `composer update` again if you use that branch.
> 
> The 5.3.* version will follow very soon.

Didn't worked out:
<img width="1417" alt="Screenshot 2021-09-28 at 11 25 53" src="https://user-images.githubusercontent.com/1161283/135070240-ce9540d4-ca93-4576-8cba-eb773e7099ba.png">

**Comment by kylekatarnls** [comment] 2021-09-28 10:28
4.4.32 and 5.3.9 are intended to fix it, which is your exact version?

**Comment by javiereguiluz** [comment] 2021-09-28 10:28
Please note that the most recent 4.4 version is 4.4.32 (https://github.com/symfony/symfony/releases/tag/v4.4.32) but Composer/Packagist cahce might still install 4.4.31 for you.

**Comment by acardielf** [comment] 2021-09-28 10:28
It works!

![imagen](https://user-images.githubusercontent.com/1655777/135070586-d6068d2f-c215-451f-ac82-33259c6b25f3.png)

**Comment by PhilETaylor** [comment] 2021-09-28 10:29
Doesnt work for me.

I note in @ancafe he doesnt have `symfony/mailer`?

<img width="796" alt="Screenshot 2021-09-28 at 11 28 41" src="https://user-images.githubusercontent.com/400092/135070606-0ab9ce5b-9d98-4078-b1af-07e8bac255f3.png">

**Comment by Messhias** [comment] 2021-09-28 10:29
After delete `composer.lock` and the vendor folder it worked.

So everyone: don't just run composer update. That the steps:

1 - delete vendor folder.
2 - delete `composer.lock` file.
3 - run composer update.

And they worked out. 



> The new 4.4.* version has been released. Please, run `composer update` again if you use that branch.
> 
> The 5.3.* version will follow very soon.



> 4.4.32 and 5.3.9 are intended to fix it, which is your exact version?

**Comment by javiereguiluz** [comment] 2021-09-28 10:29
Final? update: this seems to have been fixed. Please update to get the latest versions:

* https://github.com/symfony/symfony/releases/tag/v4.4.32
* https://github.com/symfony/symfony/releases/tag/v5.3.9


If there's some persisting cache issues, you can try running `composer clear-cache` or even removing the entire `vendor/` directory and installing dependencies again. But that shouldn't be necessary for most people.

**Comment by sinnbeck** [comment] 2021-09-28 10:30
I had to clear composer cache with  `composer clearcache` to get it working

**Comment by kolydart** [comment] 2021-09-28 10:30
Working for me! THANKS!

**Comment by BoGnY** [comment] 2021-09-28 10:31
v5.3.9 fix the problem!

thanks!

**Comment by bastihilger** [comment] 2021-09-28 10:31
Works for me - thank you for reacting so quickly.

**Comment by RSickenberg** [comment] 2021-09-28 10:31
Working, please use `composer cc` to make it works, no need to redownload the internet a second time.

Thanks @javiereguiluz for fixing this quickly!

**Comment by javiereguiluz** [comment] 2021-09-28 10:32
Thanks should go to Fabien and Nicolas who actually worked on fixing this problem! (and Alexander and others from the Core Team for alerting us early and for managing all the duplicated issue reports) And thanks to all the community for the quick reportings and all your feedback during the resolution process.

**Comment by volkv** [comment] 2021-09-28 10:35
That was unexpected and painful lol

**Comment by acantepie** [comment] 2021-09-28 10:36
I am stuck with symfony 5.3.8, and dunno why. Composer wont dl 5.3.9. I have tried all command above

**Comment by volkv** [comment] 2021-09-28 10:38
> I am stuck with symfony 5.3.8, and dunno why. Composer wont dl 5.3.9. I have tried all command above

`composer cc && composer update` worked for me

**Comment by phil-davis** [comment] 2021-09-28 10:38
Note: https://symfony.com/blog/symfony-4-4-32-released

The "list of changes" has just an empty bullet-point. That will be confusing for readers. I guess the blog post is auto-generated.

**Comment by nicolas-grekas** [comment] 2021-09-28 10:39
Use composer 2 if possible for faster updates (then no need for `composer cc`)

**Comment by oachoor** [comment] 2021-09-28 10:39
Works, except for `symfony/notifier` which still throwing:
```
Invalid handler service "chatter.messenger.chat_handler": class or interface "Symfony\Component\Notifier\Message\ChatMessage" "declared in your tag attribute "handles"" not found.
```

**Comment by rtwent** [comment] 2021-09-28 10:41
Api-platform while `composer update` fails with "* does not comply with psr-4 autoloading standard. Skipping.". It attempts to install `symfony/translation (v5.3.8)`

**Comment by fabpot** [comment] 2021-09-28 10:42
Fixed now

**Closed as completed by fabpot** 2021-09-28 10:42 UTC
Labels: Bug, Translation, Status: Reviewed, Messenger, Mailer

**Comment by acantepie** [comment] 2021-09-28 10:44
Working only with composer 2 for me :
```
composer self-update --2 
composer cc && composer update 
```

**Comment by ARB-aarontolentino** [comment] 2021-09-28 10:45
Fixed now at  5.3.9. thanks @fabpot

**Comment by fabpot** [comment] 2021-09-28 10:46
`composer up` should be enough with Composer 2.
If you are still using Composer 1, you might need to run `composer clear-cache` and remove the `vendor` directory before running `composer up` again.

**Comment by wouterj** [comment] 2021-09-28 10:47
But really, if you're still using Composer 1 consider upgrading to Composer 2 using `composer self-update --2` first.

It makes fixing issues quicker, it makes downloading anything quicker and it saves the planet a bit better than Composer 1.

**Comment by simonberger** [comment] 2021-09-28 10:48
There is no new release of symfony/translation for v4.4 yet.

**Comment by fabpot** [comment] 2021-09-28 10:48
There is no need for new releases. I've removed the broken tag, which is enough (as there were no changes still the last tag).

**Comment by fabpot** [comment] 2021-09-28 10:49
There are new releases for components that have changed since the last release though.
Again, if you follow my instructions above, that should be enough.

**Comment by WifiAccessPoint** [comment] 2021-09-28 10:49
I have the same issue as @rtwent

**Comment by phil-davis** [comment] 2021-09-28 10:51
I am still getting:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading symfony/translation (v4.4.30 => v4.4.31)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading symfony/translation (v4.4.30 => v4.4.31): Extracting archive
Generating optimized autoload files
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationDumperPassTest located in ./lib/composer/symfony/translation/TranslationDumperPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\CsvFileDumper located in ./lib/composer/symfony/translation/CsvFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\IntervalTest located in ./lib/composer/symfony/translation/IntervalTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\XliffFileLoader located in ./lib/composer/symfony/translation/XliffFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IcuResFileDumperTest located in ./lib/composer/symfony/translation/IcuResFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
...
```

Am I supposed to see `symfony/translation` 4.4.32 soon, or is 4.4.31 supposed to disappear, or?

**Comment by nam89vn-tda** [comment] 2021-09-28 10:52
@fabpot 
![image](https://user-images.githubusercontent.com/71623219/135073774-4dc9bb8a-8737-4ae1-ba72-9d2f0af73e05.png)

**Comment by simonberger** [comment] 2021-09-28 10:52
I can work around the issue and just conflicted the 4.4.31 releases, but keep in mind there are a lot of proxy solutions out there not using packagist directly. I am not sure artifactory will ever forget the release or at least it will take some time.

**Comment by phprus** [comment] 2021-09-28 10:53
Symfony version: 4.4.30:

```
$ composer --version
Composer version 2.0.13 2021-04-27 13:11:08

$ rm -rf vendor

$ composer clear-cache
...

$ composer up
...
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Interface 'Symfony\Component\Translation\Formatter\MessageFormatterInterface' not found in /Users/phprus/.../vendor/symfony/translation/MessageFormatter.php on line 25
!!  PHP Fatal error:  Interface 'Symfony\Component\Translation\Formatter\MessageFormatterInterface' not found in /Users/phprus/.../vendor/symfony/translation/MessageFormatter.php on line 25
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#6440
!!    #message: """
!!      Attempted to load interface "MessageFormatterInterface" from namespace "Symfony\Component\Translation\Formatter".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/translation/MessageFormatter.php"
!!    #line: 25
!!  }
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by dathwa** [comment] 2021-09-28 10:54
Still getting this error on the octobercms platform. Tried composer cc, tried deleting venor and composer.lock, then composer update. still seeing `Downloading symfony/translation (v4.4.31)   `

**Comment by javiereguiluz** [comment] 2021-09-28 10:54
We're locking this issue because the problem was solved. If you still have issues, you can ask in the #support channel of https://symfony.com/slack or in the [Symfony Discussions](https://github.com/symfony/symfony/discussions) at GitHub

-----

### Problem

There was a temporary problem related to class autoloading of some Symfony components. The problem is now fully fixed.

### Solution

If you use Composer 2, run `composer update` in your project

If you use Composer 1, run `composer clear-cache` and `composer update`
If it doesn't work, remove the contents of the `vendor/` directory and run `composer install`
If it still doesn't work, consider upgrading to Composer 2 (you only have to run this command: `composer self-update --2`)

**Comment by fabpot** [comment] 2021-09-28 11:00
I've just created the missing tags to ensure a smoother upgrade for everyone. So, a "simple" `composer up` should work everywhere now.

**Comment by mstaack** [comment] 2021-09-28 11:22
all working again, thanks 👍🏼

**Comment by dmlogic** [comment] 2021-09-28 11:34
Thank you for the speedy fix everyone. We found this problem via Carbon and all working fine again now

**Comment by gh0sthx** [comment] 2021-09-28 12:17
Has V4.4.31 been deleted？ I cant find this version

**Comment by derrabus** [comment] 2021-09-28 12:30
Yes, the broken packages have been removed from packagist.

**Comment by gh0sthx** [comment] 2021-09-29 01:16
Why is arrayLoader.php file missing from V4.4.31?
