### ISSUE TITLE
DateTime Validator accepts invalid date string 

### ISSUE THREAD

**Issue by jbfewo** [symfony/symfony#25573] opened 2017-12-21 12:10 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.2.1

I used `'constraints' => new DateTime(['format' => 'd.m.Y'])` on a `FormType\HiddenType::class,`  which accepts **12.12.201** as valid input but `new DateTime('12.12.201')` throws an exception.

**Comment by xabbuh** [comment] 2017-12-21 12:54
Why should the date be invalid? And by the way, the `DateTimeValidator` makes use of the `createFromFormat()` method of the `DateTime` class which handles this case quite fine: https://3v4l.org/7GRHY

**Comment by jbfewo** [comment] 2017-12-22 22:08
Ok, its right DateTime::createFromFormat() works fine, but new DateTime('12.12.201') throws an exception. I'm not sure if this is intended behavior or a php bug.

My assumption straight from the docs was, that I could pass a validated string to the DateTime constructor.

**Comment by xabbuh** [comment] 2017-12-23 09:28
That's intended. PHP doesn't know anything about the format that you used for the validation constraint. So I am closing here as this is not a bug. But please feel free to open an issue in the documentation repository if you think that the docs could be improved.

**Closed by xabbuh** 2017-12-23 09:28 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback, Unconfirmed, Validator
