### ISSUE TITLE
[3.0] [Forms] Update children after SUBMIT event

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#10070] opened 2014-01-19 02:34 UTC
It's not always practical to use the `FormEvents::PRE_SUBMIT` hook to update data in a form. For example a Date field type could be submitted as an array or string depending on it's options. In these cases it's more practical to use the `FormEvents::SUBMIT` hook to modify the normalised data (`DateTime`). 

When the modified normalised data is set back on the form the forms `viewData` is not updated to reflect the new normalised value. When the form is rendered in the browser the submitted viewData is displayed not the result of `normToView()` which is what I expected.

Original discussion with @bschussek: http://stackoverflow.com/questions/21085784/symfony2-daterange-custom-type

**Comment by xabbuh** [comment] 2017-12-14 21:15
I am closing here as the observed behaviour is not a bug and it's probably not going to be changed in the future.

**Closed by xabbuh** 2017-12-14 21:15 UTC
Labels: Feature, Form, Status: Needs Review
