### ISSUE TITLE
Regression - PropertyAccess no longer works with classes + dynamically added properties

### ISSUE THREAD

**Issue by onehorsetown** [symfony/symfony#37615] opened 2020-07-20 16:03 UTC
**Symfony version(s) affected**: x.y.z

**Description**  
In version 5.0.10, one could use a `PropertyAssessor` to fetch properties that were dynamically added to a class instance.  In version 5.1.0, this functionality was removed/broken.

**How to reproduce**  

```
class Person  {
    public function __construct(string $name) {
        $this->name = $name;
    }
}

$accessor = PropertyAccess::createPropertyAccessor();

$person = new Person("Joe Consumer");

/* 
  The following works correctly in version 5.0.10.
  In versions 5.1.0 - 5.1.2 it throws an exception: "Can't get a way to read the property "name" in class..." 
*/
$name = $accessor->getValue($person, 'name');  
```

**Possible Solution**  
One solution is to declare the property in the class definition, but this does not solve the issue for dynamically added properties.

Underlying regression is here:

https://github.com/symfony/symfony/blob/367aa1df6caa2c739a58165ead81e7fe50e6599e/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L438

The `Person` class in this example is not an instanceof `\stdClass`.

**Additional context**  

Same issue reported when writing to a class instance:  #37026

**Comment by gerryvdm** [comment] 2021-02-17 14:01
Status: Reviewed

Experiencing the same problem, we were using property-access to read out results from the PHP SOAP client, which might include SoapVar objects.

As a temporary work-around for our use-case (might not always be appropriate), I am now doing json_decode(json_encode($soapResult)).

**Comment by xabbuh** [comment] 2021-02-26 08:27
Fixed by #37622? If not, can you please create a small example application that allows to reproduce?

**Comment by gerryvdm** [comment] 2021-02-26 08:58
@xabbuh That fix seems to have been reverted.

**Comment by Voetloos** [comment] 2021-03-18 23:33
Any updates on this? @xabbuh @gerryvdm

**Comment by kschnekenburger** [comment] 2021-12-02 09:53
Hi,
I have a same issue since 5.4, can you have a solution or i tried to push PR ?

**Comment by nicolas-grekas** [comment] 2021-12-02 10:00
Please send a PR if you can yes! Don't miss adding test cases :pray:

**Comment by kschnekenburger** [comment] 2021-12-02 10:05
Thanks for anwser @nicolas-grekas but, this PR is not suffisant ?
https://github.com/symfony/symfony/pull/37622/commits/47bd0180d17cbaa3409de909020901820d89b047#diff-dfb05643a203ab1fe4371836643686b0540a3298b6e96b14b98d7768442fb3e8

**Comment by nicolas-grekas** [comment] 2021-12-02 10:08
This PR is already merged, but you're the one saying that the issue still exists on 5.4 :)

**Comment by xabbuh** [comment] 2021-12-02 10:12
@kevcomparadise That particular commit was reverted as it seems to cause a regression. So it looks like a potential bugfix would also have to take https://github.com/symfony/symfony/pull/37622#issuecomment-683392308 into account.

**Comment by kschnekenburger** [comment] 2021-12-02 13:24
> Please send a PR if you can yes! Don't miss adding test cases pray

Done
https://github.com/symfony/symfony/pull/44419

**Closed** 2021-12-11 14:44 UTC
Labels: Bug, PropertyAccess, Status: Reviewed
