### ISSUE TITLE
The configuration of packages in the application is ignored after they are applied inside `prependExtension` the bundle

### ISSUE THREAD

**Issue by tebaly** [symfony/symfony#54840] opened 2024-05-04 12:40 UTC
### Symfony version(s) affected

6.4,7

### Description

```php

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class SomeBundle extends AbstractBundle
{
// ...
    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/packages/vich_uploader.yaml');
```

After this, any changes to the root of the application in which the bundle is installed are ignored. Although it is declared that the settings in ../config/packages in the application should overwrite all changes made by the bundle. 

After commenting the lines `$container->import('.` inside the bundle, the application settings are made as expected

### How to reproduce

Combine public function prependExtension and $container->import('../config/packages/...);

### Additional Context

Perhaps this is related specifically to `vich_uploader`

**Comment by xabbuh** [comment] 2024-05-04 14:35
Can you create a small example application that allows to reproduce your issue?

**Comment by yceruto** [comment] 2024-05-04 16:56
I confirm this issue, and the reason is that `$container->import()` appends the config instead of prepending it, making it the preferred config in the stack, even over the app config (which is loaded earlier).

That's why we recently discouraged using `$container->import()` in `prependExtension` https://github.com/symfony/symfony-docs/pull/19739.

But don't be sad 😄, you can use it starting with Symfony 7.1 https://github.com/symfony/symfony/pull/52843. Meanwhile, for previous Symfony versions, I've backported that feature into this package https://github.com/yceruto/micro-symfony, which fixes this issue. Otherwise, you can always use `$builder->prependExtensionConfig()` instead, with the actual limitations.

Related to https://github.com/symfony/symfony/issues/52789

Closing as this is an expected limitation prior to 7.1 and fixed in 7.1. Thanks for reporting!

**Closed as completed by yceruto** 2024-05-04 16:56 UTC
Labels: DependencyInjection, Bug, Status: Needs Review, Status: Waiting feedback

**Comment by tebaly** [comment] 2024-05-05 09:47
> you can always use `$builder->prependExtensionConfig()` instead

@yceruto @xabbuh  It seems to me that this method is also a bug. When trying to add a field that is not yet in the application configuration file (../configs/liip_imagine.yaml), it produces an error like

> Warning: Undefined array key "resolvers" 

```php
    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $builder->prependExtensionConfig('liip_imagine', [
            'resolvers' => //...
```

`../configs/liip_imagine.yaml`
```yaml
liip_imagine: ~
```

**Comment by xabbuh** [comment] 2024-05-05 10:41
Can you create a small example application that allows to reproduce your issue?
