### ISSUE TITLE
[3.0][DX] Logout dosn't include /app_dev.php/

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#17029] opened 2015-12-16 13:46 UTC
Hi!

When logging out with developer toolbar link it dosn't work, mainly because the link goes to prod envirenment instead of dev (app_dev.php/)

The project I'm working on:
https://bitbucket.org/Richardh87/messenger/overview

**Comment by stof** [comment] 2015-12-16 14:03
which logout link are you talking about ?

**Comment by javiereguiluz** [comment] 2015-12-16 14:04
@stof I think he refers to this one: http://symfony.com/blog/new-in-symfony-2-8-dx-improvements#added-a-logout-shortcut-in-the-toolbar

**Comment by Richard87** [comment] 2015-12-16 14:06
Yup
![image](https://cloud.githubusercontent.com/assets/5749715/11842833/8f114470-a406-11e5-9467-74d952a5d38a.png)

**Comment by javiereguiluz** [comment] 2015-12-16 14:10
@Richard87 we get the logout URL directly from Symfony. See: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php#L87-L94

Using the Symfony Demo app I can't reproduce the error:

![logout_url](https://cloud.githubusercontent.com/assets/73419/11842948/1b0821c4-a407-11e5-97aa-26545b2f514e.png)

**Comment by stof** [comment] 2015-12-16 14:11
This would mean there is a bug in the LogoutUrlGenerator (and maybe also in older versions of Symfony), as this is what generates this URL. But the code looks correct in it.

@Richard87 can you try to use ``{{ logout_path('your_firewall_name') }}`` in a Twig template to see if there is the same issue ?
and are you configuring the firewall logout with a path or with a route name in your config ?

**Comment by Richard87** [comment] 2015-12-16 14:13
Hi!

I got this response:

    An exception has been thrown during the rendering of a template ("No LogoutListener found for firewall key "your_firewall_name".") in :inbox:inbox.html.twig at line 28.

:/

**Comment by javiereguiluz** [comment] 2015-12-16 14:13
@stof he is using a path: https://bitbucket.org/Richardh87/messenger/src/cd71e92a74d18814488ee242e02afd5e1b1fba47/app/config/security.yml?at=master&fileviewer=file-view-default#security.yml-29

**Comment by Richard87** [comment] 2015-12-16 14:15
Sorry, That was my stupid mistake (i didn't change 'your_firewall_name_here' :-1: 

Anyway, with the firewalls name 'main' in place, it creates a logout url, but without app_dev.php

**Comment by Richard87** [comment] 2015-12-16 14:17
What is the alternative to using a path?

**Comment by javiereguiluz** [comment] 2015-12-16 14:17
You can define an URL. Just change `/logout` by `logout` and define an empty `logout` route somewhere (in `app/config/routing.yml` for instance)

**Comment by Richard87** [comment] 2015-12-16 14:19
what do you mean?

I have also have a logout route in my default controller(annotated)

**Comment by javiereguiluz** [comment] 2015-12-16 14:22
@Richard87 there is no need to create a controller, just the route. Here you can find more information: http://symfony.com/doc/current/book/security.html#logging-out

**Comment by Richard87** [comment] 2015-12-16 14:26
I removed the controller, and added the route to `app/config/routing.yml`, but still same results...

**Comment by Richard87** [comment] 2015-12-16 14:29
alright, renaming the logout path to logout instead of /logout solved the issue (using the route name instead of absolute url for all others with the same problem)

**Comment by Richard87** [comment] 2015-12-16 14:30
Also, thanks every body for the help :) You guys rock :dancers:

**Comment by stof** [comment] 2015-12-16 14:56
Well, this still means we have a bug in the LogoutUrlGenerator when using a path rather than a route name.
So I'm reopening the issue, even though we found a workaround for @Richard87

**Comment by stof** [comment] 2015-12-16 14:58
@Richard87 can you check whether ``{{ logout_url('main') }}`` (this will generate the absolute URL to the logout rather than the absolute path) works fine for you or no when using the ``/logout`` in the config (i.e. with the config you had when facing your issue) ? This will help narrowing down the bug we have

**Comment by Richard87** [comment] 2015-12-16 14:59
I tried that, and it did not work.

`{{ logout_url('main') }}` produced a URL without app_dev.php

**Comment by Richard87** [comment] 2015-12-16 15:04
Just tried it again, and it works as expected :+1:

**Comment by Richard87** [comment] 2015-12-16 15:09
Also, `logout_url('main')` does work, while `logout_path('main')` does not with
`path:   /logout`

**Comment by stof** [comment] 2015-12-16 15:15
Well, I don't understand. Is ``logout_url('main')`` working or no ? You posted 2 comments saying the opposite

**Comment by Richard87** [comment] 2015-12-16 15:18
`logout_url('main')` works

**Comment by stof** [comment] 2015-12-17 13:06
Here we go. I found the bug. See the 2 PRs linked just above

**Comment by Richard87** [comment] 2015-12-17 20:17
Cool! I'll test them out :+1:

**Comment by Richard87** [comment] 2015-12-17 20:31
Alright, I can confirm it works ;) Thanks :+1:

**Comment by xabbuh** [comment] 2015-12-18 07:12
reopening here until the fixes have been merged to give other people the possibility to find this issue easily (see #17060)

**Closed** 2015-12-18 09:31 UTC
