### ISSUE TITLE
[4.2.7] Fatal on required symfony/validator without symfony/translation

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony#31165] opened 2019-04-18 12:59 UTC
**Symfony version(s) affected**: 4.2.7

**Description**  
Application crashes on trying to import `Symfony\Component\Translation\TranslatorInterface` for `Symfony\Component\Validator\Util\LegacyTranslatorProxy`

```
In LegacyTranslatorProxy.php line 21:
                                                                                                     
  Attempted to load interface "TranslatorInterface" from namespace "Symfony\Component\Translation".  
  Did you forget a "use" statement for "Symfony\Contracts\Translation\TranslatorInterface"?          
                                                                                                     
```

**How to reproduce**  

```bash
composer create-project symfony/skeleton issue-translation-component
cd issue-translation-component/
composer req framework-bundle validator
composer u

bin/console cache:clear
```

**Possible Solution**  

**Additional context**  

I can avoid the problem, if I require `symfony/translator` package to app

**Comment by stof** [comment] 2019-04-18 13:02
Duplicate of #31152 which is fixed in #31156

**Closed** 2019-04-18 13:03 UTC
