### ISSUE TITLE
Improve VarDumper to use it as a value exporter

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18149] opened 2016-03-13 09:56 UTC
### Problem

In Symfony this need is very common: _"given an arbitrary variable, return its best possible representation as a string"_.

Today we solve this problem at least in 6 different ways across different bundles and components:
- [x] [ValueExporter class](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php) (in `Symfony\Component\HttpKernel\DataCollector\Util`) used mostly in DataCollectors.
- [x] [sanitizeContext()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L163) method in LoggerDataCollector (`Symfony\Component\HttpKernel\DataCollector`)
- [x] [getStringRepresentation()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php#L98) method in DebugAccessDecisionManager class.
- [x] [getListenerInfo()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L305) in `TraceableEventDispatcher`
- [ ] [formatValue()](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php#L207), [formatParameter](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php#L227) and [formatCallable](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php#L427) in FrameworkBundle's Console descriptors.
- [ ] [formatValue()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L986) method in OptionsResolver component.
- [ ] [varToString()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Exception/FileLoaderLoadException.php#L68) method in FileLoaderLoadException class (`Symfony/Component/Config/Exception`)

We "can't" use VarDumper because we need a pure value exporter which doesn't add CSS/JS code or other advanced stuff.
### Solution

Improve VarDumper to export variables in the simplest way possible so we can replace the existing code and get the exact same results.

**Comment by nicolas-grekas** [comment] 2016-03-13 10:00
@javiereguiluz do you need html or text output? Because if you need pure-text output, it's already implemented: just use the CliDumper with colors off. See e.g. VarDumperTestTrait who does exactly that.

**Comment by WouterJ** [comment] 2016-03-13 10:15
@nicolas-grekas but it still requires you to open a file stream, read the stream, etc. Ideally, I would like to have a new entry point using an export class or the like (so we have dumpers and exporters). This way, you would do:
```php
$exporter = new Exporter();
$exportValue = $exporter->export($someVariable);
```

**Comment by javiereguiluz** [comment] 2016-03-13 10:21
Here are some of the use cases that need to be covered:

1) Simple array of values formatted like this:

![](https://cloud.githubusercontent.com/assets/73419/13603450/98a87e54-e53d-11e5-87d9-ca2a954f81a3.png)

2) Simple variables of lots of types: strings, integers, objects, Doctrine objects, etc. (for Doctrine objects we display the `id` if available,; if not, the `__toString()` method; otherwise, the object hash):

![](https://cloud.githubusercontent.com/assets/73419/13497960/2b39f57a-e158-11e5-84c1-815e4ec90d27.png)

**Comment by nicolas-grekas** [comment] 2016-03-13 10:26
I looked at each formatter linked above. formatCallable should be excluded imho, it's really tailored to specific context. For the other ones, we'd need an inventory of expected behaviors. E.g. afaik all listed use cases represent only the class name of objects. For arrays, most generate a recursive representation, but at least generates a simple `array`.
The question is: is there a one size fits all representation output? Why shouldn't we color the representation? The profiler panels would look better don't you think?
Once we have a "specification" for all of this, it should be quite easy to use VarDumper's primitives to write a tailored dumper/helper.

**Comment by javiereguiluz** [comment] 2016-03-13 10:33
@nicolas-grekas I agree. We need to find a format that fits all (each of them will need to make concessions).

About the colors ... it will probably be better. But we'll need a "light" color scheme because the default "dark" scheme doesn't fit the design of the profiler. Thanks!

**Comment by WouterJ** [comment] 2016-03-13 11:10
I think using HtmlDumper for the profiler would make things very nice (Especially when using objects as values, which is done in the CMF project a lot). It seems like varToString in the DataCollector class is used for 2 things: "Serializing" it to save in the profiler storage and for displaying it in the profiler.

I think "serializing" should be replaced with real serialize and displaying should be replaced by using the HtmlDumper with the light theme.

**Comment by nicolas-grekas** [comment] 2016-03-13 11:32
Shapes good :-) To get precise control over what is put in the profile, we could VarCloner as serializer.

**Comment by Koc** [comment] 2016-03-14 09:55
some of this formatters using for logs, and easy to read logs without html

**Comment by HeahDude** [comment] 2016-04-05 16:29
I am actually facing the need to use `ValueExporter` as a standalone class in #18411, since `webmozart/assert` also use a [similar function](https://github.com/webmozart/assert/blob/master/src/Assert.php#L849) but is not as "advanced" as the `ValueExporter` and less similar though to other outputs in symfony core.

I tried to move the logic the the `VarDumper` but I did not find a way to make it fit.

From my point of view the need is not the same, `VarDumper`:

 - calls dumpers which use cloners and casters to display a deep profile of a value

 - the need to dump a value happens while debugging to check something, once done you remove the "dump" call from your code (from my experience).

 - dumps use output stream

In contrary the `ValueExporter`:

 - exports the php value by making it humanly readable in the desired format (e.g a string)

 - can be used permanently as part of log messages, profile messages, exceptions messages ...

So I ended up with only new files in `VarDumper` and a class named `Symfony\Component\VarDumper\ValueExporter`, hence I moved it in its own component.

I don't know if this is the way symfony deciders want to explore this when I read comments above, but while working on this I tried to implement the flexibility of the `VarDumper` component, allowing to use a custom exporter (default `ValueToStringExporter` is the equivalent of the current `ValueExporter`), and/or custom formatters used to handle specific types.

Should I submit a PR so anyone can review this approach or simple point my branch for anyone interested ? Thanks.

**Comment by stof** [comment] 2016-04-05 17:33
> I think "serializing" should be replaced with real serialize

won't work as not all variables are serializable (PDO instances, closures...)

**Comment by HeahDude** [comment] 2016-04-05 17:48
I've added a formatter for callable just now :) I guess I can send that PR, feel free to close it if that's not suit as you wish.

**Comment by javiereguiluz** [comment] 2016-12-07 08:08
@wouterj @nicolas-grekas after your work integrating VarDumper in the Profiler, I'd say we can close this as "fixed". Or do you plan to add the VarDumper features to the remaining components (OptionResolver, Config, etc.) ?

**Closed** 2017-01-28 08:04 UTC
Labels: Feature, VarDumper
