### ISSUE TITLE
[Intl] Translations for TimezoneType Field Type

### ISSUE THREAD

**Issue by enekochan** [symfony/symfony#16106] opened 2015-10-04 13:13 UTC
The TimezoneType Field Type uses `\DateTimeZone::listIdentifiers()` to get the texts that are shown in the generated `select` HTML tag. Of course these are in perfect english. I've added all the texts needed to translate it in my AppBundle YAML translation files and configured the form like this so it gets translated with them:

```php
class ProfileFormType extends AbstractType
{
...
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $constraint = new UserPassword();

        $this->buildUserForm($builder, $options);

        $builder
            ->add('timezone', 'timezone', array(
                'label' => 'form.timezone.label',
                'translation_domain' => 'AppBundle',
                'choice_translation_domain' => true,
            ))
        ;
    }
...
}
```

@javiereguiluz suggested me that those texts may be could be included in the Intl component like other resource bundles as Currrency, Regions, etc. If the community thinks this could be a new feature I would be glad to do the Spanish translations and could try to do the PR itself.

**Comment by Rvanlaak** [comment] 2015-10-12 08:22
Doesn't `Intl::getRegionBundle()->getCountryName($locale);` already allow you to do these translations via the ICU data? You can also take a look at the [`LanguageBundleInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/ResourceBundle/LanguageBundle.php).

**Comment by enekochan** [comment] 2015-10-12 10:48
The RegionBundle gives country name translations but this issue is related to timezone translations ("Europe/Madrid", "America/Argentina/Ushuaia", etc.). Not the same ;)

**Comment by javiereguiluz** [comment] 2015-10-12 10:49
If we provide translations for countries/regions, locales, etc.  it could make sense to translate this information too.

**Comment by stof** [comment] 2015-10-12 12:56
@javiereguiluz we expose the ICU data for countries and locales. We don't maintain the translation ourselves. And timezone translations are not provided in ICU/CLDR AFAIK

**Comment by javiereguiluz** [comment] 2015-10-12 13:05
I know nothing about ICU/CLDR ... but on its website (http://site.icu-project.org/design/formatting/timezone/icu-4-8-time-zone-names) it says that timezone names were added as "tech preview" in ICU 4.8. I'm not sure if this serves us in any way.

**Comment by Tobion** [comment] 2015-10-12 13:21
Duplicate of #13662

**Comment by enekochan** [comment] 2015-10-14 09:26
@Tobion I've tried the 3v4l.org snipet from #13662 butit does not translate the timezone continent, country and city/island/whatever names. That's what I'm talking about here. It translates the timezone description thougth which is nice :) Here is an example with spanish https://3v4l.org/PGreu If you look at the timezone array you can see "America/Panama" and what I'm willing to get for that timezone is "América/Panamá" (look at the accent marks at the end).

**Comment by Tobion** [comment] 2015-12-22 17:10
The values from `\DateTimeZone::listIdentifiers()`, e.g. `America/Panama` are the IDs. These should not be translated as it does not make sense to translate IDs which would then not be valid anymore. Neither Drupal nor http://unicode.org/repos/cldr/trunk/common/main/es.xml has translations for them.

If you need translations, then just do not display the IDs but the names, e.g. "Central European Standard Time". But as many timezone ids map to the same name, it will not be that concrete anymore, e.g. "Europe/Berlin" vs "Europe/Amsterdam". This is why I suggested to group them by region, name or abbr in #13662. Closing as duplicate.

**Closed by Tobion** 2015-12-22 17:10 UTC
Labels: Form, Intl
