### ISSUE TITLE
https://github.com/symfony/dependency-injection repo broken

### ISSUE THREAD

**Issue by CJCShadowsan** [symfony/symfony#35911] opened 2020-02-29 22:05 UTC
**Symfony version(s) affected**: latest

**Description**  
https://github.com/symfony/dependency-injection is broken - cannot git clone this repository

**How to reproduce**  

`git clone https://github.com/symfony/dependency-injection`

**Possible Solution**  

**Additional context**  

```
git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
fatal: pack has bad object at offset 529234: inflate returned -5
fatal: index-pack failed

git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
error: inflate: data stream error (incorrect data check)
fatal: pack has bad object at offset 657443: inflate returned -3
fatal: index-pack failed
```

**Comment by sabruss** [comment] 2020-03-01 00:03
i cannot reproduce that issue, it works for me

```cmd
git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 29828 (delta 19), reused 24 (delta 2), pack-reused 29784
Receiving objects: 100% (29828/29828), 8.92 MiB | 969.00 KiB/s, done.
Resolving deltas: 100% (23962/23962), done.
```

**Comment by mhujer** [comment] 2020-03-01 08:45
@CJCShadowsan works fine for me as well. 

Maybe try upgrading your git to the latest version.

**Comment by nicolas-grekas** [comment] 2020-03-01 09:07
Closing as this is not an issue with the code.

**Closed by nicolas-grekas** 2020-03-01 09:07 UTC
Labels: Bug, Status: Needs Review

**Comment by CJCShadowsan** [comment] 2020-03-01 10:18
Just an extra note on this...:

```
vagrant@drupalvm:~$ git --version
git version 2.17.1

vagrant@drupalvm:~$ git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
error: inflate: data stream error (incorrect data check)
fatal: pack has bad object at offset 109319: inflate returned -3
fatal: index-pack failed
```

```
 ⚡ root@DESKTOP-4L00TV6  /mnt/c/Users/chris  git --version
git version 1.8.3.1
 ⚡ root@DESKTOP-4L00TV6  /mnt/c/Users/chris   git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 29828 (delta 19), reused 24 (delta 2), pack-reused 29784
Receiving objects: 100% (29828/29828), 8.92 MiB | 5.23 MiB/s, done.
Resolving deltas: 100% (23962/23962), done.
Checking out files: 100% (611/611), done.
```

Could someone verify?

**Comment by CJCShadowsan** [comment] 2020-03-01 10:21
Also with latest git:

```
vagrant@drupalvm:~$ git --version
git version 2.25.1
vagrant@drupalvm:~$ git clone https://github.com/symfony/dependency-injection.git
Cloning into 'dependency-injection'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (42/42), done.
error: inflate: data stream error (invalid bit length repeat)
fatal: pack has bad object at offset 1002810: inflate returned -3
fatal: index-pack failed
```

**Comment by WeirdeQL** [comment] 2021-04-16 01:57
I also met this problem, do not know how to solve it...

**Comment by stof** [comment] 2021-04-16 10:21
not being able to clone a github repo is something that you should report to the github support, not to the symfony team. We are not managing the git server.
