### ISSUE TITLE
[Dotenv] Quoting values with $ does not work as expected

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#26056] opened 2018-02-05 15:33 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

When I have following values in `.env`:
```
PASSHASH1=$2y$10$kmIn2NJp1tUL0bALk.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa
PASSHASH2='$2y$10$kmIn2NJp1tUL0bALk.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa'
PASSHASH3="$2y$10$kmIn2NJp1tUL0bALk.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa"
```

And I load them with this code:
```php
<?php declare(strict_types = 1);

use Symfony\Component\Dotenv\Dotenv;

require_once 'vendor/autoload.php';

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

var_dump(getenv('PASSHASH1'));
var_dump(getenv('PASSHASH2'));
var_dump(getenv('PASSHASH3'));
```

The output is:
```
string(42) "$2y$10.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa"
string(60) "$2y$10$kmIn2NJp1tUL0bALk.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa"
string(42) "$2y$10.X/h.gjZ2b/6wQA72iYsa2PwpnRj544S/tPa"
```

The 1 and 3 are "broken". Only the variant quoted with `'` works as expected. Quotes `"` are used [in an example](http://symfony.com/doc/current/configuration/external_parameters.html#environment-variables) in documentation, so they should work as well. The non-quoted variant should throw an exception instead of silently changing the value.

I'm using PHP 7.1.12 + Windows 10, but the Dotenv uses PHP to parse the file, so it should not matter.

**Comment by mhujer** [comment] 2018-02-05 15:34
It probably has something to do with command embedding using `$` sign.

This `.env` file:
```
TEST_DOLLAR1=$A$B$C
TEST_DOLLAR2='$A$B$C'
TEST_DOLLAR3="$A$B$C"
```

Provides those values in PHP:
```
string(0) ""
string(6) "$A$B$C"
string(0) ""
```

**Comment by nicolas-grekas** [comment] 2018-02-05 15:36
Hello, this is expected: `.env` is not a Symfony specific standard, but borrows from the `sh` shell.
You should be able to `source .env` on Linux boxes and not require Dotenv.
On `sh`, `$FOO` or `"$FOO"`reference another variable, which is what your 1 & 3 variants do.
Closing as this is not a bug but normal behavior.

**Closed by nicolas-grekas** 2018-02-05 15:36 UTC

**Comment by mhujer** [comment] 2018-02-05 15:44
@nicolas-grekas thanks for the explanation!

Just a quick question, it means that the [default recipe for Doctrine](https://github.com/symfony/recipes/blob/a92c928bb014aaa4b2028255136311c76cfb7d3d/doctrine/doctrine-bundle/1.6/manifest.json#L13) would break if the DB user has a `$` in the password? Is there a reason for not changing the quotes to to `'`?

And similarly [in the documentation](http://symfony.com/doc/current/configuration/external_parameters.html#environment-variables).

**Comment by javiereguiluz** [comment] 2018-02-05 15:48
@mhujer yes ... we updated docs recently to mention this: https://symfony.com/doc/current/doctrine.html#configuring-the-database

**Comment by stof** [comment] 2018-02-05 17:22
@nicolas-grekas does Dotenv supports single quotes properly ? If yes, it might be an option here.

**Comment by nicolas-grekas** [comment] 2018-02-05 17:23
it does, see above report, the singly quoted string is the one that works in this case

**Comment by stof** [comment] 2018-02-05 17:55
then we should indeed update the Doctrine recipe to use single quotes. People are more like to put a `$` there because of the password containing one than because of nesting env vars IMO (and people nesting env vars will generally know they need to use double quotes or no quotes for that to work)

**Comment by nicolas-grekas** [comment] 2018-02-05 18:04
Agreed, here we are: https://github.com/symfony/recipes/pull/361

**Comment by trappar** [comment] 2018-04-16 18:40
Shouldn't the Symfony docs also encourage the use of single quotes by default? Currently the [dotenv component documentation](https://symfony.com/doc/current/components/dotenv.html) makes no mention of quoting values. This is a major gotcha, and I feel like there should be warnings scattered throughout the documentation about it where using the .env file is mentioned.
