### ISSUE TITLE
[Mailer] BCC doesn't work with AWS SES

### ISSUE THREAD

**Issue by Pixelshaped** [symfony/symfony#36333] opened 2020-04-03 13:26 UTC
**Symfony version(s) affected**: 4.4.7

**Description**  
I was able to send emails to the to() address, but bcc() seems ignored.
Using templated emails.
The URL I use for the DSN is one of type:
MAILER_DSN=ses://ACCESS_KEY:SECRET_KEY@default?region=eu-west-1

**How to reproduce**  
```
$email = (new TemplatedEmail())
            ->from(new Address('emailFROM@email.com', 'nameFROM'))
            ->to(new Address('emailTO@email.com', 'nameTO'))
            ->bcc(new Address('emailBCC@email.com', 'nameBCC'))
            ->subject($subject)
            ->htmlTemplate($template)
            ->context($context);

$mailer->send($email);
```

- Email received at emailTO@email.com
- Email not received at emailBCC@email.com

Nothing more than that. Upon debugging, it seems that when the message is converted to raw the bcc is not present in the headers.

**Comment by FlaverSaver** [comment] 2020-04-06 07:41
The same problem also occurs with SendmailTransport. The cause can be found here: https://github.com/symfony/mime/blob/2aad3728327b3b1fd8137004528129673dec1e09/Message.php#L96
The BCC is removed in all cases.

**Comment by Pixelshaped** [comment] 2020-04-06 08:37
> The same problem also occurs with SendmailTransport. The cause can be found here: https://github.com/symfony/mime/blob/2aad3728327b3b1fd8137004528129673dec1e09/Message.php#L96
> The BCC is removed in all cases.

The commentary really makes it look like it's a voluntary omission. Is there any other way to add BCCs ? The issue made me double my API calls (not a big deal in my case but still)

**Comment by hyde1** [comment] 2020-04-19 16:48
Hello, same problem here.
I think that both `SesHttpTransport` and `SesApiTransport` should read the recipients from the Enveloppe when sed

**Comment by hyde1** [comment] 2020-04-19 16:52
Hello, same problem here.
`SesApiTransport` is reading recipients from the Enveloppe when sending messages without attachement.
But `SesHttpTransport` and `SesApiTransport` with not attachement are both sending the raw message and without reading the Enveloppe, where all recipients are present...
I think it should use the `Destination` parameter of the `SendRawEmail` action by reading the Eveloppe recipients before sending the request.

**Comment by akondas** [comment] 2020-06-05 07:55
The problem is with `AbstractHttpTransport` which uses `SentMessage` class to send e-mail. All comes down to one method: `Symfony\Component\Mime\Message::getPreparedHeaders`
```php
        // remove the Bcc field which should NOT be part of the sent message
        $headers->remove('Bcc');
```

This should be changed to use `Email` class like `AbstractApiTransport`, I could fix it, but I don't know if we can do it this way :thinking:, maybe I will suggest PR to show you what I mean?

**Comment by joey-beech-it** [comment] 2020-10-06 10:49
Same issue here, all Bcc's are removed and not send. Any status update?

**Comment by fabpot** [comment] 2020-10-06 10:52
I'm not using AWS SES, so someone needs to investigate this issue and submit a patch to fix it. I will then more than happy to review it and merge it.

**Comment by frans-beech-it** [comment] 2021-01-06 15:47
Did some more digging. 

The `BCC` is removed from the header in general for all transports here https://github.com/ehymel/symfony/blob/35b7e1cb9a9c3fafe0c68386fae13721ea05aa82/src/Symfony/Component/Mime/Message.php#L99

But when using `sendmail` the `bcc` header is needed and stripped by `sendmail` for instance.

If we look at the swiftmail implementation you see `BCC` is only removed for SMTP see https://github.com/swiftmailer/swiftmailer/blob/59935da5e9d4c7ae801bb393d638dac2515498c9/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L203

@fabpot would that also be a proper solution for `symfony/mailer`?

**Comment by jderusse** [comment] 2021-01-06 23:16
SES issue will be fixed by #39743 You can use `ses+api` as a workaround. Or bump to symfony 5.2 + install `async-aws/ses`

**Comment by jderusse** [comment] 2021-01-06 23:29
Regarding the sendmail issue, could somebody test this PR #39744 ? 

/cc @frans-beech-it

**Closed** 2021-01-12 11:30 UTC
Labels: Bug, Mailer, Status: Needs Review

**Comment by frans-beech-it** [comment] 2021-01-12 12:05
@nicolas-grekas @jderusse should we create a new issue for the sendmail transport issue?
