### ISSUE TITLE
Property-info not guessing right datetime

### ISSUE THREAD

**Issue by erethilclaw** [symfony/symfony#30083] opened 2019-02-05 16:27 UTC
Symfony 4.2

I'm using serialize in symfony 4.2 to decode a json and save an entity to the database, the problem are the datetime, when i deserialize symfony gives me an error that expects an datetime object and string was given.

I checked all the "use" statements in my control, as well all the config with the property-info to let symfony recognize all the fields of the json and figure out what it is.

in framework.yaml

```yaml
property_info:
            enabled: true
```

my controler

```php
/**
* @Route("admin/newPost", name="newPost", methods={"POST"})
*/
public function newPost( Request $request){
    /** @var  Serializer $serializer */
    $serializer = $this->get('serializer');
    $post = $serializer->deserialize($request->getContent(), 
    Post::class, 'json');

    $em = $this->getDoctrine()->getManager();
    $em->persist($post);
    $em->flush();

    return $this->json($post);
}
```

the Json I'm passing

```json
    {
     "title": "A third blog post!",
     "published_at": "2018-07-01 12:00:00",
     "content": "Hello there!",
     "author": "Piotr Jura",
     "slug": "a-third-blog-post"
     }
```

with deserialize method should convert the "published_at" to a datetime for save into database, but gives me the error: "Expected argument of type "DateTiemInterface","string" given at property path "published_at".

Thanks for your time

**Comment by xabbuh** [comment] 2019-02-05 18:55
What is the exact error and stack trace you get? What does your `Post` class look like?

**Comment by xabbuh** [comment] 2019-02-05 20:43
Please show the full stack trace.

**Comment by erethilclaw** [comment] 2019-02-05 21:18
Don't know what do you mean, if you refer to apache logs, error and acces, don't output any error, php.ini configured to show them.

**Comment by erethilclaw** [comment] 2019-02-05 21:32
Is the error in the symfony profiler, the unique part i missed is overlight this part in my controller:

 $post = $serializer->deserialize($request->getContent(), 
    Post::class, 'json');

**Comment by xabbuh** [comment] 2019-02-05 22:50
I was able to reproduce. In fact, the issue is not that the PropertyInfo component does not extract the property type, but that the attribute name in your JSON payload does not match the name of the property in the class.

If you change the JSON to the following, it will work as expected:

```json
{
    "title": "A third blog post!",
    "publishedAt": "2018-07-01 12:00:00",
    "content": "Hello there!",
    "author": "Piotr Jura",
    "slug": "a-third-blog-post"
}
```

Alternatively, you make use of the `CamelCaseToSnakeCaseNameConverter` class that converts attribute names from camel case to snake case.

I am closing here as the behaviour is expected and there is nothing to fix.

**Closed by xabbuh** 2019-02-05 22:50 UTC
Labels: Bug, PropertyInfo, Serializer, Status: Waiting feedback

**Comment by erethilclaw** [comment] 2019-02-05 23:02
I'll be damm... thanks mate.
