### ISSUE TITLE
Process::fromShellCommandline with "find .. -exec"

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#30791] opened 2019-03-31 08:47 UTC
**Symfony version(s) affected**: 4.2.4

**Description**  
```php
        $process = Process::fromShellCommandline( 'find . -name "*.yml" ! -path "*/vendor/*" -exec vendor/bin/yaml-lint {} \;');
        $process->run();
```

I would like to make this command work, but it seems that the `-exec` is considered as some kind of special keyword by the Process component, or similar..?

using the very same command directly from the bash works as expected.

I am using this process in a symfony/console app and getting the following error

```php
In LintCommand.php line 27:

  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "find . -name "*.yml" ! -path "*/vendor/*" -exec vendor/bin/yam
  l-lint {} \;" failed.

  Exit Code: 1(General error)

  Working directory: C:\xampp7.3\htdocs\linter

  Output:
  ================


  Error Output:
  ================
  find: missing argument to `-exec'
```

is this a bug, or do I used it wrong?

**Comment by nicolas-grekas** [comment] 2019-03-31 09:06
This must be some compat issue with `cmd.com`: `find . -name "*.yml" ! -path "*/vendor/*" -exec vendor/bin/yaml-lint {} \;` looks like a Unix-style line while you're running it on Windows. `fromShellCommandline` is not portable (because it's not possible to make it portable: each shell has its own syntax - eg escaping the `;` with `\` doesn't work on Windows afaik).

What you should do instead is:
```php
$process = new Process(['find', '.', '-name', '*.yml', '!', '-path', '*/vendor/*', '-exec', 'vendor/bin/yaml-lint {} ;']);
$process->run();
```

(you'll maybe have to split the last part also, I don't remember how `find` work here:
`$process = new Process(['find', '.', '-name', '*.yml', '!', '-path', '*/vendor/*', '-exec', 'vendor/bin/yaml-lint', '{}', ';']);`

**Comment by nicolas-grekas** [comment] 2019-03-31 09:07
I'm closing as this is not a bug report, please use any options listed on https://symfony.com/support to get more help.

**Closed by nicolas-grekas** 2019-03-31 09:07 UTC
