### ISSUE TITLE
Deprecation Notice Symfony\Component\HttpClient\ScopingHttpClient

### ISSUE THREAD

**Issue by robbertstevens** [symfony/symfony#40996] opened 2021-04-30 08:12 UTC
**Symfony version(s) affected**: 5.2.*

**Description**
When I have run a console command I get the message

> User Deprecated: Class "Symfony\Component\HttpClient\ScopingHttpClient" should implement method "Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options)": Returns a new instance of the client with new default options.

When I look in the `Symfony\Component\HttpClient\ScopingHttpClient` class it indeed doesn't have the `::withOptions` method.

**How to reproduce**
I think you can reproduce it by requiring the `symfony/http-client@5.2.6` package

**Possible Solution**
I guess it's adding this method

**Additional context**
-

**Comment by nicolas-grekas** [comment] 2021-04-30 08:14
Duplicate of #40975

**Closed as completed by nicolas-grekas** 2021-04-30 08:14 UTC
Labels: Bug, Status: Needs Review, HttpClient
