### ISSUE TITLE
Symfony 3.1 EventListener method executed two times?

### ISSUE THREAD

**Issue by manzerbredes** [symfony/symfony#19239] opened 2016-06-30 06:07 UTC
Hello I made a EventListener to do things before send a response to the request. So this is my EventListener:

```php
namespace AppBundle\EventListener;

use Symfony\Component\HttpKernel\Event\FilterControllerEvent;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\ORM\EntityManager;

class RequestListener {

    private $em;
    private $session;

    public function __construct(EntityManager $em, Session $session) {
        $this->em = $em;
        $this->session = $session;
    }

    public function onKernelController(FilterControllerEvent $event) {
        $repo=$this->em->getRepository("AppBundle:FlashMessage");
        $repo->addFlashMessage("test","content");
    }

}
```

And add it to my services:

```xml
<services>
    <service id="app.request.listener" class="AppBundle\EventListener\RequestListener">
        <argument type="service" id="doctrine.orm.entity_manager"/>
        <argument type="service" id="session" /> 
        <tag name="kernel.event_listener" event="kernel.controller" />
    </service>
</services>
```

Every things work fine. But too fine ! In fact, on each request from my web browser, two entries are made in my database table (the method onKernelController seem to be executed two times on each request). So why two entry is created on each request ?

```
$ php bin/console debug:event-dispatcher| grep -i AppBundle give me:
  #1      AppBundle\EventListener\RequestListener::onKernelController()          0
```

**Comment by iltar** [comment] 2016-06-30 06:23
`kernel.controller` is fired for every controller action, this includes sub-requests, which are usually done via twig: `render(controller('...'))`.

However, this looks more like a support question to me, please use one of the support channels listed on the website: http://symfony.com/support as this issue tracker is not for support.

**Comment by javiereguiluz** [comment] 2016-06-30 07:32
@manzerbredes this is probably caused by the reason gave by @iltar. Therefore, I'm closing this issue  because it looks like a support question. If you confirm that this is a Symfony bug, please reopen this issue so we can fix it. Thanks!

**Closed by javiereguiluz** 2016-06-30 07:32 UTC
