### ISSUE TITLE
Cryptic error when autowiring fails on arguments before manually defined arguments

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#25349] opened 2017-12-06 09:54 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

When you define no arguments, autowiring will give you a very precise error. However, if you manually define arguments that come after that using named arguments, the error will become extremely cryptic.

Given the following PHP:
```php
namespace Hostnet;

interface TestInterface {}

class TestOne implements TestInterface {}
class TestTwo implements TestInterface {}

class TestDependency {}

class TestClass
{
    public function __construct(
        TestOne $testOne, 
        TestInterface $testTwo, 
        TestDependency $testDependency
    ) {}
}
```

Using this configuration (100% autowiring):
```yml
services:
    Hostnet\TestClass: ~
    Hostnet\TestOne: ~
    Hostnet\TestTwo: ~
    Hostnet\TestDependency:
        public: true
```
I will get the descriptive error:
```
AutowiringFailedException

Cannot autowire service "Hostnet\TestClass": argument "$testTwo" of 
method "__construct()" references interface "Hostnet\TestInterface" but 
no such service exists. You should maybe alias this interface to one of 
these existing services: "Hostnet\TestOne", "Hostnet\TestTwo".
```

When I manually wire 1 argument that's positioned _after_ the dependency that will fail (last argument in this case):
```yml
services:
    Hostnet\TestClass:
        $testDependency: '@Hostnet\TestDependency'
    Hostnet\TestOne: ~
    Hostnet\TestTwo: ~
    Hostnet\TestDependency:
        public: true
```

This results in a crpytic error:
```
RuntimeException

Invalid constructor argument 3 for service "Hostnet\TestClass": argument 1 
must be defined before. Check your service definition.
```

**Comment by sroze** [comment] 2017-12-06 11:43
We have done a lot of DX improvements (and continue to do) on Symfony 3.4 regarding these messages. Here is what I have with 3.4 with your example:
```
Cannot autowire service "App\TestClass": argument "$testTwo" of method "__construct()" references interface "App\TestInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "App\TestOne", "App\TestTwo".
```

**Comment by nicolas-grekas** [comment] 2017-12-06 11:45
Yep, same as @sroze : duplicate of #23606, improved in 3.4 already.

**Comment by iltar** [comment] 2017-12-06 12:21
Hmm it's a bit of a hassle atm due to still being on 3.3 (3.4.2 or 3.4.3 earliest I think), the developer on slack that had this issue was indeed on 3.3 as well. Shall I close this issue in that case as it won't be fixed for 3.3 and 3.4 is released?

**Comment by nicolas-grekas** [comment] 2017-12-06 12:22
Yep, won't be fixed on 3.3, that's not a bug :)

**Closed by nicolas-grekas** 2017-12-06 12:22 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
