### ISSUE TITLE
ContainerAwareTrait introduces a circular reference

### ISSUE THREAD

**Issue by chx** [symfony/symfony#46209] opened 2022-04-28 21:29 UTC
### Symfony version(s) affected

all

### Description

https://github.com/symfony/symfony/issues/41025 got too long and confusing.

`ContainerAwareTrait` introduces a circular reference.

### How to reproduce

```
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Definition;
use Symfony\Component\DependencyInjection\Reference;

require_once './vendor/autoload.php';

class service {
  use \Symfony\Component\DependencyInjection\ContainerAwareTrait;
}

$container = new ContainerBuilder();
$definition = new Definition();
$definition->setClass(service::class);
$definition->addMethodCall('setContainer', [new Reference('service_container')]);
$definition->setPublic(TRUE);
$container->setDefinition('test', $definition);
$container->compile();
var_export($container);
?>
```
this blows up.

That's all.

### Possible Solution

Hide the container in a closure. Service references are already stored in proxy closures, this is nothing new. Instead of storing the container, store this:

```
<?php

namespace Symfony\Component\DependencyInjection;

class ContainerHider implements ContainerInterface {
  protected $hide;
  function __construct($container) {
    $this->hide = fn () => $container;
  }
  function get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE)
  {
    return ($this->hide)()->get($id, $invalidBehavior);
  }
  function getParameter($name)
  {
    return ($this->hide)()->getParameter($name);
  }
  function has($id)
  {
    return ($this->hide)()->has($id);
  }
  function hasParameter($name)
  {
    return ($this->hide)()->hasParameter($name);
  }
  function initialized($id)
  {
    return ($this->hide)()->initialized($id);
  }
  function set($id, $service)
  {
    ($this->hide)()->set($id, $service);
  }
  function setParameter($name, $value)
  {
    ($this->hide)()->setParameter($name, $value);
  }
}
?>
```
### Additional Context

This manifests with twig but Twig is not necessary as the reproduction code shows.

**Comment by stof** [comment] 2022-04-29 10:10
This is not something we can solve. By design, the container stores a reference to all shared services. So if you inject the container into a service, this creates a circular object graph.

Note that *any* circular object graph will blow up `var_export`. That's not specific to ContainerAwareTrait.
But that does not mean that such circular object graphs are bugs.

**Comment by n0rbyt3** [comment] 2022-04-30 16:19
It's also a bad practise to inject the whole container into a service. Either inject the required services directly or use service locators if you need some services on demand: https://symfony.com/doc/current/service_container/service_subscribers_locators.html#including-services

**Comment by chalasr** [comment] 2022-04-30 16:42
Closing as explained.

**Closed as completed by chalasr** 2022-04-30 16:42 UTC
Labels: DependencyInjection, Bug, Status: Needs Review
