### ISSUE TITLE
[PhpunitBridge] installs non-stable releases from phpunit repo

### ISSUE THREAD

**Issue by pscheit** [symfony/symfony#28791] opened 2018-10-09 14:49 UTC
**Symfony version(s) affected**: all

**Description**  
The phpunit bridge sets the COMPOSER_ROOT_VERSION to 6.5.99 (.e.g) and will then install dev versions as well - and not stable versions.

**How to reproduce**  
delete vendor/bin/.phpunit and use simple-phpunit again. It will install the latest commit in phpunit repo (e.g. branch 6.5)

**Possible Solution**  
I'm not 100% sure: use prefer-stable: true and minimium-compability: stable in the composer.json from phpunit?

Thank you

Best regards
Philipp

**Comment by greg0ire** [comment] 2019-04-06 19:53
I cannot reproduce, do you maybe have a global composer.json specifying a high minimum-compat?

**Comment by xabbuh** [comment] 2019-04-11 14:46
Closing here for now. We can reopen once we are able to reproduce.

**Closed by xabbuh** 2019-04-11 14:46 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by stof** [comment] 2019-04-11 15:22
This was solved when changing the way to install PHPUnit in the bridge in https://github.com/symfony/symfony/pull/29265 (in November 2018). Before that PR, we were indeed always using the dev version, as we were getting the github branch.
