### ISSUE TITLE
[Twig] Creating new projects on PHP 7.1 not possible

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony#39734] opened 2021-01-06 08:40 UTC
**Symfony version(s) affected**: 4.4 / Twig v2

**Description**  
When bootstrapping a new project using PHP 7.1 through `composer create-project symfony/website-skeleton`, there' a incompatibility: `twig/extra-bundle` is installed in v3.2.0 and `twig/twig` in v2.13.1.

Building the container calls `registerUndefinedTokenParserCallback` in `Twig\Extra\TwigExtraBundle\DependencyInjection\Compiler\MissingExtensionSuggestorPass`, but this method is not available in Twig v2.

```
!!  08:33:00 CRITICAL  [php] Uncaught Error: Call to undefined method Twig\Environment::registerUndefinedTokenParserCallback() ["exception" => Error { …}]
!!  
!!  In srcApp_KernelDevDebugContainer.php line 1546:
!!                                                                                                                     
!!    Attempted to call an undefined method named "registerUndefinedTokenParserCallback" of class "Twig\Environment".  
!!    Did you mean to call e.g. "registerUndefinedFilterCallback" or "registerUndefinedFunctionCallback"?              
!!                                                                                                                     
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by derrabus** [comment] 2021-01-06 08:47
This sounds like a Twig bug to me.

**Comment by fabpot** [comment] 2021-01-06 08:49
There was a bug (fixed now in 3.2.1), so you must explicitly require `twig/extra-bundle` v2

**Closed as completed by fabpot** 2021-01-06 08:49 UTC
Labels: Bug, TwigBundle, Status: Needs Review

**Comment by NicoHaase** [comment] 2021-01-06 08:52
What do you mean by "fixed now"? I ran `composer create-project symfony/website-skeleton` about 20 minutes ago, and it did not run properly. As this is a documented way to start a new project, this still looks like a bug to me

**Comment by fabpot** [comment] 2021-01-06 09:07
I've just tried and it installed Twig 3 and Twig extra bundle 3 as well. How did you get Twig 2 with a brand new project?
In any case, I think I'm just going to remove the version from Packagist, there is no other way to fix it properly as the issue is in the composer.json constraints. Having a new version of 3 means that the problem is gone but Composer can still install the package with the constraint issue.

**Comment by NicoHaase** [comment] 2021-01-06 09:08
...just for nit-picking: did you really install Twig v3 on PHP 7.1? This should not be possible, as this is not marked as compatible

**Comment by fabpot** [comment] 2021-01-06 09:11
Understood now... I tried with PHP 7.4 :)

**Comment by NicoHaase** [comment] 2021-01-06 09:12
Thanks for checking again :) Also, is there any chance to check for such bugs before merging them, or is this too complicated?

**Comment by fabpot** [comment] 2021-01-06 09:15
If I had a magic trick to avoid bugs, I would sell it for a lot of money :)

**Comment by NicoHaase** [comment] 2021-01-06 09:57
I've checked this once again, and starting a project is possible again. Thanks for your quick response and your overall great work!
