### ISSUE TITLE
Replace DIC services with mocks in tests

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#29109] opened 2018-11-06 15:19 UTC
**Description**  
Since 4.1 we can access private services in tests but we cannot substitute any services with mocks, as may be required by some testing strategies.

**Example**  
```php
self::$container->set('foo', new MockedFoo());
```

>Symfony\Component\DependencyInjection\Exception\InvalidArgumentException : The "foo" service is private, you cannot replace it.
vendor\symfony\dependency-injection\Container.php:163
vendor\symfony\framework-bundle\Test\TestContainer.php:86

**Comment by unkind** [comment] 2018-11-06 15:48
You can achieve the same with proper configuration by using suffixes with env names.

**Comment by Bilge** [comment] 2018-11-06 15:51
Not sure what you mean by that exactly, but if you're referring to env configs (e.g. `services_test.yaml`), that implies the same mock must be used for all tests, which is not good enough. Each test should be able to discretely configure a mock to suit its requirements.

**Comment by nicolas-grekas** [comment] 2018-11-06 19:11
> Each test should be able to discretely configure a mock to suit its requirements.

That requirement is actually incompatible with having an optimized container; that's why it doesn't work. Private services can be inlined, and any reference to them are optimized out. As the message suggests, you should make the service public if you really want to do this.

Closing as there is no bug here. Thanks for reporting.

**Closed by nicolas-grekas** 2018-11-06 19:11 UTC

**Comment by Bilge** [comment] 2018-11-06 19:14
But I only want it to be public, or more accurately: replaceable, in tests.

**Comment by TiMESPLiNTER** [comment] 2019-10-17 13:08
@nicolas-grekas solution works like a charm. :heart:

**Comment by bcastagna** [comment] 2019-11-16 04:01
But it's really cumbersome to make an alias for every service we want to mock..... Isn't there a way to make all services in container public for testing purposes ? 
For example I want to mock translator.default service to verify if the call to the service is effectively made with the expected string in my service's unit test.

**Comment by Rubinum** [comment] 2020-12-07 10:42
@bcastagna You can change the service.yaml in your project to replace your services with a mocked one from your tests or if you want them to be public, you can set it there too. 
When you excecute tests, you can define a `service_test.yaml` that only applies on your testing environment. You have to make sure your application has been set to this environment during tests, if you diverge from the standard.  In that case you can make every service public or replace it with a better one for your tests.

Example: I have a controller action where the Finder Component of Symfony searches in a specific directory on the mashine for some config files. In tests, these directories may not exists because my application is bound to another app on the same mashine. To build better and more independent tests, I want to mock that Finder and replace it with a Finder, that has been modified so that the directory is one in the tests folders. 

service_test.yaml
```
services:
    Symfony\Component\Finder\Finder:
        public: true
        shared: false
```

MyTest.php
```
class MyTest extends WebTestCase {
    public function testMyControllerAction(): void
    {
        $this->client->getContainer()->set('Symfony\Component\Finder\Finder', new ModifiedTestFinder());
         // do some assertions
    }
}
```

ModifiedTestFinder.php
```
use Symfony\Component\Finder\Finder;

class ModifiedTestFinder extends Finder
{
    public function getIterator()
    {
        return new \ArrayIterator([new \SplFileInfo(__DIR__.'/../tenantTemplateTestDirectory')]);
    }
}
```

Alternatively, you can overwrite the Symfony Finder for all tests.

service_test.yaml
```
services:
    Symfony\Component\Finder\Finder:
        class: 'App\Tests\ModifiedTestFinder'
```

But be aware, that modifying the container during tests can lead to unexpected behavior during excecution of your tests. This can lead to a diverged behavior between prod and test environment, if you are not careful. It depends on how good you manage your tests.

**Comment by nobYsDarling** [comment] 2021-09-27 09:21
>     public function testMyControllerAction(): void
>     {
>         $this->client->getContainer()->set('Symfony\Component\Finder\Finder', new ModifiedTestFinder());
>          // do some assertions
>     }

This won't work as the container ist frozen/initialized. *at least in Symfony 4.4

**Comment by BafS** [comment] 2023-01-18 11:38
Good new, it is happening: https://github.com/symfony/symfony/pull/48938, we can probably close this 4+ years old issue.

**Comment by Bilge** [comment] 2023-01-18 11:43
...but it _is_ closed... and has been for almost 5 years...

Nevertheless, thanks for bringing it to my attention 👍🏻

**Comment by BafS** [comment] 2023-01-18 12:47
Oh right, the purple color made me think it was still open, sorry
