### ISSUE TITLE
[Profiler][Forms] Adding to form after ->createForm() leads to an exception in Profiler

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#20872] opened 2016-12-11 22:35 UTC
I have a controller with the following code:
```php
$form = $this
    ->createForm(SurveyType::class, $survey)
    ->add('submit', SubmitType::class, [
        'label' => 'Create',
    ]);
```

When I go to the profiler, it throws an exception `Key "type_class" for array with keys "id, name, view_vars, children" does not exist in @WebProfiler/Collector/form.html.twig at line 460.`

So adding elements to the created form (not form builder) leads to this problem.

Btw, is it a bad practice to add buttons (specific for controller action) in such a manner? I know that a can use inherit_data for the `SurveyType`, but it does not allow to have DATA events, which I do use in this particular case.

**Comment by javiereguiluz** [comment] 2016-12-12 07:33
@vudaltsov thanks for reporting this issue. It looks like a duplicate of #20823 which has already been fixed in the 3.2 branch and it will be available in the upcoming 3.2.1.

Regarding the question about buttons, the Symfony Best Practices book mentions this in http://symfony.com/doc/current/best_practices/forms.html#form-button-configuration  and you can always ask others in the support channels shown in https://symfony.com/support  Thanks!

**Closed by javiereguiluz** 2016-12-12 07:33 UTC
Labels: Form, WebProfilerBundle
