### ISSUE TITLE
Controllers in Symfony 2.6.0 slower than 2.5.x?

### ISSUE THREAD

**Issue by YetiCGN** [symfony/symfony#12790] opened 2014-12-01 10:52 UTC
Upgrading to Symfony 2.6.0 I experience slower delivery of every page in our project. The drag is always around 100 ms, which is a lot more than the same call takes with 2.5.7. 

The profiler shows the "controller" section as the only difference. Apart from a 203 ms to 305 ms difference there is also a memory increase from 6 to 19 MB.

Before I go into debugging our own code and stripping it down to a minimum working example: Is anybody else experiencing this or might have a clue what could cause this?

**Comment by YetiCGN** [comment] 2015-02-05 10:49
Little side note, in Symfony 2.6.4 with Doctrine DBAL 2.5.1 the performance is "back" to 2.5.7 levels. I have not yet begun to dig into the reasons for this.

Thanks for all your feedback! I will leave this open in case I have a spare weekend sometime in the future to get to the bottom of this.

**Comment by fabpot** [comment] 2015-02-05 11:01
@YetiCGN Thanks for the feedback. I'm going to close it now and feel free to reopen when you have more information. Thanks.

**Comment by bdujon** [comment] 2015-02-15 10:01
i have the same performance problem and reverted back to 2.5.x
Doctrine DBAL 2.5.1 didn't change anything
The performance problem is actually noticable too on a simple login page without any db call.
For me it s not 100ms slower but it s about 2 time slower (exemple 3000ms become 6000ms...) when there is db call and 1.5 time slower on the login page

**Comment by jakzal** [comment] 2015-02-15 13:04
@bdujon we can't do much without your help. Would you be able to provide either of the following:
* a (preferably simplified) code to demonstrate the problem?
* a [blackfire](http://blackfire.io) profile (or a profile coming from any other profiling tool)?

**Comment by bdujon** [comment] 2015-04-05 15:14
@jakzal sorry for the late answer for me the solution is just to not use sf2 > 2.5.x.
I just tried to reproduce it with the new symfony installer and i reproduce it on /demo/hello/World of the AcmeDemoBundle. I thought it was coming from doctrine but it s not even that.
symfony 2.5.10 : 267ms / 13.8mb
symfony 2.6.6 : 535ms / 14mb
sf 2.6.x just seems 2 time slower than sf 2.5.x
i get that on windows 8 with php build in webserver on dev environment

i cant use blackfire as i m on windows.

**Comment by jakzal** [comment] 2015-04-05 17:01
@bdujon since you managed to reproduce it, if you put the code in a public repo I'll have a look.

**Comment by nicolas-grekas** [comment] 2015-04-05 17:01
@bdujon can you confirm this is in prod env (not debug)?

**Comment by jakzal** [comment] 2015-04-05 17:02
wait, are you saying it's slower on the demo without any changes?

**Comment by WouterJ** [comment] 2015-04-05 20:25
On my Windows 8 PC, things are a little bit slower in production (a fresh installation with just AcmeDemoBundle registration and routing moved to prod), but not as dramatic as @bdujon:

* 2.5.10 `/demo/hello/World`: 269 ms
* 2.6.6 `/demo/hello/World`: 304 ms

**Comment by jakzal** [comment] 2015-04-05 20:40
OS X, PHP 5.5.14, prod mode:
* 2.5.10 - 63.5ms, 7.94MB
* 2.6.6 - 67ms, 8.33MB

**Comment by bdujon** [comment] 2015-04-05 21:23
i m sorry i can't reproduce it on AcmeDemoBundle anymore. Now the timer are the same ... (i guess i got tricked by my laptop cpu that must have changed its speed while testing on different page.. each time ... ! )
But i reproduce it each time on a complex page with the timer going from 1000ms on 2.5 to 3000ms on 2.6.
I ll try to narrow it down.

The problem was never on prod environment but only on dev environment.

**Comment by bdujon** [comment] 2015-04-05 21:51
ok i think i found it. It s at least coming from the choice type form render.
Here s a simple exemple to reproduce it
controller :
```php
public function listAction(Request $request)
    {
        $form = $this->createFormBuilder()
            ->add('list', 'choice', ['choices' => range(0,10000)])
            ->getForm();
        return ['form' => $form->createView()];
    }
```
view :
```twig
{% block content %}
    {{ form_row(form.list) }}
{% endblock %}
```
This takes 570ms with sf 2.5 and 2500ms with sf 2.6 on dev env.

**Comment by bdujon** [comment] 2015-04-06 14:00
it s because of https://github.com/symfony/symfony/pull/10887
sf 2.6 add a new feature, logging unknow translation. So for a 10000 string loop i had 10000 warning in the debug log.
I m not sure if the performance impact (2000ms) justify these 10000 logs since i dont know enough sf2 logging system.
So i just have to add 
```yaml
# app/config/config.yml
translator:
    logging:    false
```
i can live with that :)

**Comment by aitboudad** [comment] 2015-04-06 14:22
@bdujon the issue has been solved by #13651 can you test with 2.7 ? 
```patch
-       ->add('list', 'choice', ['choices' => range(0,10000)])
+       ->add('list', 'choice', ['choices' => range(0,10000), 'choice_translation_domain' => false])
```

**Comment by bdujon** [comment] 2015-04-06 14:49
@aitboudad i got 800ms with 'choice_translation_domain' => false. So i d say that fix it in a much better way than disabling globaly the translation log, thanks ! (now i want to use 2.7 with the fancy translation/twig debugbar :) ).
There is still 300 more ms than in 2.5 but i guess it s coming from other new features like the twig logger which add 10000 lines for showing the rendering of the form. 300ms for these 10000 lines seems fine so maybe there is really a performance problem with the translation warning logger ?

But there is another problem and maybe that has nothing to do with it but when i remove 'choice_translation_domain' to get the default behavior the debug bar goes into 404.

**Comment by aitboudad** [comment] 2015-04-06 15:01
@bdujon nice, I'd say without translation warning logger I think it's difficult to detect those calls.
  
>But there is another problem and maybe that has nothing to do with it but when i remove 'choice_translation_domain' to get the default behavior the debug bar goes into 404.

I'll check it :)

can I close this issue ?

**Comment by bdujon** [comment] 2015-04-06 15:22
Yes you can close it.

Thanks everyone for your help :)

**Closed** 2015-04-06 15:23 UTC
Labels: BC Break, Critical
