### ISSUE TITLE
The DI reports class is not here instead of file is broken

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#35484] opened 2020-01-27 17:04 UTC
**Symfony version(s) affected**: 4.4.3

**Description**  
When I ran `bin/console` I got the following error:

```
In FileLoader.php line 208:
  Expected to find class "AppBundle\XXXXer\Command\Fixtures\GenerateXXXXCommand" in file "/home/rio/rio/server/backend/src/XXXXer/Command/Fixtures/GenerateXXXXComm  
  and.php" while importing services from resource "../../../src/XXXXer/*", but it was not found! Check the namespace prefix used with the resource.                     
```

It took me some time to found my error: I missed the last `}` of the file. So the file was not valid.

Could we improve the message to reflect the file is broken instead of this missleading info?

**Comment by nicolas-grekas** [comment] 2020-01-27 19:10
Duplicate of #35445

**Closed by nicolas-grekas** 2020-01-27 19:10 UTC
