### ISSUE TITLE
Wrong version in web debug toolbar symfony 2.8.28

### ISSUE THREAD

**Issue by guldil** [symfony/symfony#24547] opened 2017-10-13 11:36 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.28

I update a project to latest version 2.8.28 with composer but in the web debugger it still show 2.8.24.

I cleared cache, i removed vendor, i tried a lot a things...

![image](https://user-images.githubusercontent.com/5718040/31544422-0986e77e-b01b-11e7-9a70-314f0b90b3bf.png)

if i go in my vendor/symfony folder, i see 2.8.28 changelog : 

![image](https://user-images.githubusercontent.com/5718040/31544508-6e26b97a-b01b-11e7-82fa-884d8ab9c473.png)

it's just cosmetic ?

**Comment by javiereguiluz** [comment] 2017-10-13 11:39
In the source code of 2.8.28, the version number is correct: https://github.com/symfony/symfony/blob/v2.8.28/src/Symfony/Component/HttpKernel/Kernel.php#L62

The web profiler takes the value directly from it, so if you are seeing a different number, I'd say that it could be caused by some cache (maybe OPcache?)

**Comment by guldil** [comment] 2017-10-13 11:56
i reboot my VM, clear opcache, still stuck at 2.8.24...

**Comment by yceruto** [comment] 2017-10-13 12:46
@guldil do you have tried `composer dump-autoload` to regenerate the autoload file?

**Comment by guldil** [comment] 2017-10-13 12:54
@yceruto i tried, composer dump-autoload, composer update, still 2.8.24.

i'll try to push source to another server.

**Comment by guldil** [comment] 2017-10-13 15:04
same problem on another VM with Apache2, Kernel.php is up to date, not the Debug WebToolBar :

![image](https://user-images.githubusercontent.com/5718040/31552737-972fbc6e-b038-11e7-85ad-086e66472eb9.png)

**Comment by javiereguiluz** [comment] 2017-10-13 15:16
If you see the profiler template, we just output the value collected for the Symfony version without any manipulation: https://github.com/symfony/symfony/blob/d04c0ea45b9a8cd8fa44414754e5abb719eb1fc4/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/config.html.twig#L29

The version is collected here, which just takes the `Kernel::VERSION` value without any manipulation: https://github.com/symfony/symfony/blob/d04c0ea45b9a8cd8fa44414754e5abb719eb1fc4/src/Symfony/Component/HttpKernel/DataCollector/ConfigDataCollector.php#L61

Please debug the config data collector to see if it's collecting the right information. Thanks!

**Comment by guldil** [comment] 2017-10-13 15:32
var_dump show 2.8.24...

**Comment by guldil** [comment] 2017-10-13 15:37
I found it, it's in boostrap.php.cache : 

`const VERSION ='2.8.24';
const VERSION_ID = 20824;
const MAJOR_VERSION = 2;
const MINOR_VERSION = 8;
const RELEASE_VERSION = 24;
const EXTRA_VERSION ='';
const END_OF_MAINTENANCE ='11/2018';
const END_OF_LIFE ='11/2019';
public function __construct($environment, $debug)`

**Comment by dmaicher** [comment] 2017-10-13 16:11
the boostrap.php.cache file should be regenerated after composer update/install?

**Comment by guldil** [comment] 2017-10-13 16:15
ok it's working now.

 I remove boostrap.php.cache and created a new one with distribution-bundle. Then i have to fix my "console" "app.php" and "app_dev.php". It was an old upgrade Symfony 2.3 project to 2.8 ...

This issue help me : https://github.com/sensiolabs/SensioDistributionBundle/issues/302

So it's not a bug, just a problem with upgrade to 2.8...

**Comment by dmaicher** [comment] 2017-10-13 16:16
Ok :+1: can you close the issue then?

**Closed** 2017-10-13 17:09 UTC
Labels: Bug, Status: Needs Review, Unconfirmed, WebProfilerBundle
