### ISSUE TITLE
[OptionsResolver] Closures are not resolved anymore when passed as a user option

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#13610] opened 2015-02-06 13:54 UTC
Considering this code:

```php
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

$resolver = new OptionsResolver();
$resolver->setDefaults([
    'foo' => 1,
    'bar' => null,
]);

$options = $resolver->resolve([
    'bar' => function (Options $options) {
        return $options['foo'];
    }
]);
var_dump($options);
```

Result **before** 2.6:

```
array (size=2)
  'foo' => int 1
  'bar' => int 1
```

Result **after** 2.6:

```
array (size=2)
  'foo' => int 1
  'bar' => 
    object(Closure)[2242]
```

I know Closure resolution is made for default options depending on others but sometimes it could be useful to reuse a default option.

**Comment by Tobion** [comment] 2015-02-06 15:16
Duplicate of #12332

**Comment by 4rthem** [comment] 2015-02-06 17:12
Sorry! I filtered by the `OptionsResolver` label which is missing on that issue.

**Closed** 2015-02-08 07:18 UTC
