### ISSUE TITLE
[DI][Autowiring] Extending the Router gives an error from autowiring because of 2 ContainerInterface deps

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#27822] opened 2018-07-03 12:26 UTC
**Symfony version(s) affected**: 4.1 (for sure) and maybe 3.4 and upper 

**Description**  
Autowire seems confused when having 2 references to `ContainerInterface` 

**How to reproduce**  
Extends the Framework `Router` class
```php
namespace App\Service;

use Symfony\Bundle\FrameworkBundle\Routing\Router;

class AdminRouter extends Router
{
}
```

The result will be: 

```
The service ".service_locator.G69Xsbl.App\Service\AdminRouter" 
has a dependency on a non-existent service "Symfony\Component\Config\Loader\LoaderInterface".
```

**Possible Solution**  
Explicitly pass the reference to the `ContainerInterface` fixes the issue: 

```yml
App\Service\AdminRouter:
    arguments:
        $container: '@service_container'
        $parameters: '@service_container'
        $resource: 'resource'
        $options: []
```

**Additional context**  
For reference the `Router` from the `FrameworkBundle` signature looks like: 

```php 
public function __construct(
    ContainerInterface $container, 
    $resource, 
    array $options = array(), 
    RequestContext $context = null, 
    ContainerInterface $parameters = null, 
    LoggerInterface $logger = null)
```

Thanks to Cerad on stackoverflow who [gave the solution](https://stackoverflow.com/a/51154332/318071) and took the time to reproduce it

**Comment by nicolas-grekas** [comment] 2018-07-03 12:58
The issue is actually the error message: `Router` implement `ServiceSubscriberInterface` so it gets a smaller localor. If you need more services in your child class, you need to override `getSubscriberServices()`, see https://symfony.com/doc/current/service_container/service_subscribers_locators.html

**Comment by nicolas-grekas** [comment] 2018-07-03 13:01
How do you declare your router as a service btw?

**Comment by nicolas-grekas** [comment] 2018-07-03 13:13
```php
public static function getSubscribedServices()
{
   return array_merge(parent::getSubscribedServices() + array(.. your services));
}
```

**Comment by ahundiak** [comment] 2018-07-03 13:21
The following service definition triggers the error:

    App\Service\AdminRouter:
        arguments:
            $resource: 'resource'

No attempt is being made to inject additional services.  Seems like it should work.  The AdminRouter itself it not being used anywhere though I guess autoconfigure is probably picking it up.

**Comment by tristanbes** [comment] 2018-07-03 13:30
@nicolas-grekas: After a discussion on slack, i've tried what you recommended:

```php
<?php

namespace Foo\Bundle\Admin\SiteRoutingBundle\Routing;

use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Foo\Bundle\Common\CoreBundle\Manager\SiteManagerInterface;

class AdminSiteRouter extends Router
{
    protected $container;
    protected $siteManager;
    protected $useSiteHost = true;

   
    public function generate($name, $parameters = [], $referenceType = self::ABSOLUTE_URL)
    {
        $this->container->get('Foo\Bundle\Common\CoreBundle\Manager\SiteManagerInterface')->bar();
        
        // some code
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedServices()
    {
        return array_merge(parent::getSubscribedServices(), [
            SiteManagerInterface::class,
        ]);
    }
}
```

```yaml
    Foo\Bundle\Admin\SiteRoutingBundle\Routing\AdminSiteRouter:
        arguments:
            $resource: '%site_routing_file_path%'
            $options: []
```

Still gives: 

```
 The service ".service_locator.I8lg7qA.Foo\Bundle\Admin\SiteRoutingBundle\Routing\AdminSiteRouter" has a dependency on a non-existent service "Symfony\Component\Config\Loader\LoaderInterface".
```

**Comment by stof** [comment] 2018-07-03 15:48
Why are you making your own service extend the Symfony router class btw ? You still don't configure all the routes in it.

And `Symfony\Component\Config\Loader\LoaderInterface` is indeed not autowirable to find the routing loader (which is expected, as we also have loaders in other components). The core router service does not rely on autowiring to build the service locator.

**Comment by tristanbes** [comment] 2018-07-04 09:47
@stof: The use case is the following:

We have 2 application in a Symfony project (2 Kernels).
One for the backoffice, and one for the frontoffice.

Sometimes, we want to be able to generate URL's for the front withing the backoffice.

To do so: we need to load the `routing.yml` inside the front config directory ('%site_routing_file_path%') and we need to hook into the `generate` function to change the hostname [it's a multi-tenant application] and apply other modifications.

The [full code is available here](https://gist.github.com/tristanbes/844d8d2f58696361b229cbd200c42cb2) if that helps you understand why this class extends the Symfony `Router`

**Comment by nicolas-grekas** [comment] 2018-07-04 15:07
Error message improved in #27822.
The rest is configuration, no bug here.

**Comment by tristanbes** [comment] 2018-07-04 15:16
Unless I made a mistake (sorry If I have) I tried what you told me to on slack and it gave the same error.

Guess I gotta trust you about the configuration problem because this this is not my expertise area.

**Comment by nicolas-grekas** [comment] 2018-07-04 15:21
Yep, I didn't notice but my first config was incomplete. You need to add this tag also on the service:
```yaml
tags:
    - {name: container.service_subscriber, id: routing.loader}
```

this will bind the internal "routing.loader" to the main "routing.loader"

**Comment by nicolas-grekas** [comment] 2018-07-13 14:16
Closing as explained.

**Closed by nicolas-grekas** 2018-07-13 14:16 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
