### ISSUE TITLE
Cannot test sending email from command with assertEmailCount()

### ISSUE THREAD

**Issue by epitre** [symfony/symfony#43828] opened 2021-10-29 12:52 UTC
### Symfony version(s) affected

5.3.9

### Description

I use a command to send an email.

I wrote a PHPUnit test for that with CommandTester as explained here : https://symfony.com/doc/current/console.html#testing-commands

The test fails on the email count.

### How to reproduce

1. Write a command that send an email
2. Write a test that assert how many emails are sent

Test  example :
```
<?php

namespace CircularX\Common\Tests\Service;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class CommandTest extends KernelTestCase
{
    public function testEmail()
    {
        $kernel = static::createKernel();
        $application = new Application($kernel);

        $command = $application->find('app:send-email');
        $container = $application->getKernel()->getContainer();
        $commandTester = new CommandTester($command);
        $commandTester->execute([]);

        // the output of the command in the console
        $output = $commandTester->getDisplay();
        $this->assertEmailCount(1); // will say that no emails are sent 

    }
}
```

### Possible Solution

it seems that there is 2 different MessageEvents object.
One when the command is running.
Another one when the assertEmailCount is called.

**Comment by adrienfr** [comment] 2021-10-29 13:29
Can you try with `$commandTester->execute(['command' => $command->getName()]);`?

**Comment by epitre** [comment] 2021-10-29 16:46
@adrienfr I tried, but the problem is still here :'(

**Comment by niamzor** [comment] 2021-11-05 08:36
Hi!

I was able to reproduce the bug.
I created a reproduction project [here](https://github.com/phillylovepark/symfony-skeleton/tree/43828_testing_email) on the `43828_testing_email` branch.
There are 2 tests:
* one for the `MailService` where the assertion is working
* one for the `SendMailCommand` where the assertion is not working

Status: Reviewed

**Comment by epitre** [comment] 2021-11-05 11:37
thank you so much @phillylovepark

**Comment by a1812** [comment] 2021-11-08 00:04
replace   
$kernel = static::createKernel();  to  $kernel = self::bootKernel();  and should work

```php

//        $kernel = static::createKernel();
        $kernel = self::bootKernel();

        $application = new Application($kernel);

        $command = $application->find('app:send-mail');
        $commandTester = new CommandTester($command);
        $commandTester->execute([]);

        $this->assertEmailCount(1);
```

**Comment by a1812** [comment] 2021-11-11 00:14
@epitre you checked?

**Comment by xabbuh** [comment] 2021-11-13 11:41
Closing with the solution given in https://github.com/symfony/symfony/issues/43828#issuecomment-962707654. If that change doesn't help, please provide a new example that allows to reproduce and we can consider to reopen.

**Comment by epitre** [comment] 2021-11-17 08:37
Hello @a1812 and @xabbuh 
I just came back from a looong week-end ^^

So, I did test your solution, and it did not work.

@xabbuh Can you reopen the issue, as it is still here.

**Comment by niamzor** [comment] 2021-11-17 08:38
I can confirm that the above fix is working on the reproduction project.

Is it worth updating the doc ? As it uses the `static::createKernel()` method https://symfony.com/doc/current/console.html#testing-commands

**Comment by epitre** [comment] 2021-11-17 08:44
:thinking:

**Comment by epitre** [comment] 2021-11-17 16:20
@phillylovepark I just tried it with your example project, and it did not work for me. 
I can see the email, but the test fails the same.

Could you check again, please ?

**Comment by niamzor** [comment] 2021-11-17 17:36
Have you tried the suggested fix ? I just pushed it in the latest commit of the [reproduction repository](https://github.com/phillylovepark/symfony-skeleton/tree/43828_testing_email). 

Try to execute the `testExecute()` method from the `App\Tests\Command\SendMailCommandTest`. It works for me.

**Comment by epitre** [comment] 2021-11-17 22:31
Indeed, it works, but what I don't understand, is that you are still using static...
https://github.com/phillylovepark/symfony-skeleton/blob/43828_testing_email/tests/Command/SendMailCommandTest.php#L13

**Comment by epitre** [comment] 2021-11-17 22:32
OMG !
I did not realize that I have to replace create by boot :face_palm:

**Comment by epitre** [comment] 2021-11-17 22:50
I can now confirm it works.
I created a PR to make the change in the symfony docs : https://github.com/symfony/symfony-docs/pull/16118

**Comment by epitre** [comment] 2021-11-17 22:50
@xabbuh Do you want to close it ?

**Comment by xabbuh** [comment] 2021-11-19 10:26
Thanks to everyone involved here in helping each other and to also improve the documentation. 😍 Closing here now then.

**Closed as completed by xabbuh** 2021-11-19 10:26 UTC
Labels: Bug, Status: Reviewed, Status: Waiting feedback, Mailer
