### ISSUE TITLE
[Messenger] Usecase for Doctrine middlewares

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#32436] opened 2019-07-08 14:39 UTC
This is a follow on discussion that I had with @weaverryan on Slack.

Messenger comes with some optional [Doctrine related middle-wares](https://github.com/symfony/symfony/tree/4.4/src/Symfony/Bridge/Doctrine/Messenger). It seems to me, unless i'm missing something, that all of these do not make sense as middlewares, and would be better suited as EventListeners for consumption purposes.

I've reimplemented 3 of these for my project as EventListeners in my project, as they are unusable as middleware.

Let's have a look.

#### `DoctrineClearEntityManagerMiddleware`
Automatically Clears the EntityManager in an effort to prevent memory leaks.

I can't imagine a use-case where this would be beneficial when dispatching messages. Messages are most likely dispatched in a request context, in which case you really don't want your Entity Manager cleared as all your entities will become un managed, which will just result in errors or unintended consequences when the EntityManager is eventually flushed.

However, clearing the EntityManager **is** obviously beneficial when consume messages, to prevent memory leaks in a long running process.

It seems this middleware should be a Listener on consumption, listening on some combination `WorkerMessageHandledEvent`/`WorkerMessageFailedEvent`/`WorkerMessageReceivedEvent`

#### `DoctrineTransactionMiddleware`
Automatically calls EntityManager `flush`.

Again, exactly the same as above really. 
1. As the developer, I want to be in control of calling when flush in a request context.
2. This middleware will not work at all and will throw an exception if you are dispatching messages during an existing `flush` i.e. subscribing to various doctrine events. (yes, you could debate here if this is a good idea or not).

It seems this middleware should be a EventListener, listening on  `WorkerMessageHandledEvent`.

#### `DoctrineCloseConnectionMiddleware`
Closes the database connection.

More of the same really. This seems better suited to a long running background processes, i.e the consumer.

#### `DoctrinePingConnectionMiddleware`
Checks the database connection is alive, reconnecting and resetting the entity manger if not.

More of the same really. This seems better suited to a long running background processes, i.e the consumer.

**Comment by weaverryan** [comment] 2019-07-08 18:25
@Koc can you comment about DoctrineClearEntityManagerMiddleware - it also doesn't make sense to me. At the very least, I think it should only clear on "received" messages (which is what the original issue #29662 mentioned)

*DoctrineTransactionMiddleware* I think the idea here is you (for example with an event bus) have 4 handlers for 1 message and (as a design pattern) each handler does some work, but does not flush. The flush is then done at the end with the middleware. Also (probably more important), all 4 handlers are wrapped in the same transaction and are rolled back together. 

*DoctrineCloseConnectionMiddleware* & *DoctrinePingConnectionMiddleware* I agree again with @bendavies about these. I believe what we're trying to accomplish with these is to (A) close the connection between message handling to avoid having many open connections to the database that are doing nothing and (B) in case the connection was closed by the database server (e.g. "MySQL gone away"), re-open the connection. It seems these are better suited as event listeners on the worker. Ping @insidestyles (from PR #31061)

**Comment by insidestyles** [comment] 2019-07-09 04:55
@Koc I agreed with @bendavies about DoctrineTrasactionMiddleware. I prefer keeping it as middleware. To me,  as listeners the other 3 middlewares do their jobs  too, so no objection. Would you please consider just about the component's definition: middleware vs listener. Are those middlewares  more related to the events like WorkerMessageHandledEvent or the whole process of the component? For example, with WorkerMessageHandlerEvent, I think about listeners like: trackHandledMessages, ... In your case we have to set up close connection listener to 2 events WorkerMessageHandlerEvent, WorkerMessageFailedEvent ...

**Comment by Koc** [comment] 2019-07-15 08:55
Indeed some of current middlewares could be transformed into event listeners (`DoctrineClearEntityManagerMiddleware`, `DoctrineCloseConnectionMiddleware`, `DoctrinePingConnectionMiddleware`). But we should provide possibility to enable/disable and configure this listeners.

```
# config/packages/messenger.yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction: ['custom']
```

So maybe we need new node, like `event_listeners`. IMHO this adds more complexity than benefits.

**Comment by bendavies** [comment] 2019-07-15 10:31
can they all be converted to event listeners in 4.3? in 4.3 they are still experimental right so no BC break?

**Comment by weaverryan** [comment] 2019-07-15 13:24
> can they all be converted to event listeners in 4.3?

Even experimental, we don't break BC on the patch releases - only minor releases (and hopefully we can really minimize the BC breaks for 4.4).

> Indeed some of current middlewares could be transformed into event listeners (DoctrineClearEntityManagerMiddleware, DoctrineCloseConnectionMiddleware, DoctrinePingConnectionMiddleware). But we should provide possibility to enable/disable and configure this listeners.

@Koc you said "could be transformed". Is it "could be" or do you agree that it's a "should be" (and that they don't make much sense as middlewares)? Just making sure we're not missing some perspective that you have. From my perspective, these more or less don't work at all as middlewares.

> So maybe we need new node, like event_listeners. IMHO this adds more complexity than benefits

Indeed, the config for this could get ugly. But, is there a use-case for enabling these for some buses and disabling for others? The 3 questionable middleware - clear, close & ping only makes sense in the context of "async workers" and they serve only to make things more reliable. 

Cheers!

**Comment by Koc** [comment] 2019-07-15 18:08
> Is it "could be" or do you agree that it's a "should be"

to be honest - I'm not sure. Lets ask @sroze / @nicolas-grekas what they think about.

> The 3 questionable middleware - clear, close & ping only makes sense in the context of "async workers" and they serve only to make things more reliable.

`DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.

`DoctrineCloseConnectionMiddleware` and `DoctrinePingConnectionMiddleware` actual for async handling.

**Comment by bendavies** [comment] 2019-07-15 21:52
> `DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.
I don't agree with that really, for the reasons laid out in my OP.

**Comment by insidestyles** [comment] 2019-07-18 14:35
> > `DoctrineClearEntityManagerMiddleware` makes sense for sync handling too: prevent memory leak when handle large amount of commands + prevent side effects like flushing outdated entities state.
> 
> I don't agree with that really, for the reasons laid out in my OP.
IMO
For nginx/php-fpm: no sense
For swoole/reactphp: yes

**Comment by B-Galati** [comment] 2019-07-19 19:51
See PR #32614 that add a new worker event that could help

**Comment by B-Galati** [comment] 2019-07-19 19:56
When I tried messenger for the the 1st time with an async transport I was not expecting my message to trigger alll my Middlewares. I was expecting them to be called only at the moment the message is consumed. Does it make sense?

**Comment by B-Galati** [comment] 2019-07-19 20:17
Would it make sense to change the workflow of Messenger?
Like:
Message dispatched -> sender -> receiver -> Middlewares -> handler.

Managing everything with a Middlewares is perhaps overkill? Why one would one would not want to use the HandleMessageMiddleware for example? 

Messenger is a message bus library but it feels like PSR-15 sometimes.

**Comment by maks-rafalko** [comment] 2019-07-23 16:00
After upgrading to 4.3 we got a very weird error because of `DoctrineCloseConnectionMiddleware`, unfortunately.

We have a code that dispatches messages on `postPersist()`, in a opened transaction, and this middleware breaks EntityManager with the following error message: `There is no active transaction`

```php
public function postPersist(LifecycleEventArgs $eventArgs): void
{
    // ...
    $this->messageBus->dispatch(new SomeMessage());
    // ...
}
```

So, the flow is the following

```
START TRANSACTION
INSERT INTO ...
dispatch to MessageBus
close connection (from DoctrineCloseConnectionMiddleware)
ROLL BACK <---------  this is because Entity Manager is closed while transaction was not yet commited
```

We have to disable this middleware as it is too dangerous and does not look right.

**Comment by Koc** [comment] 2019-07-23 20:22
I think that you have configured wrong priorities for middlewares. Can you share your config?

**Comment by maks-rafalko** [comment] 2019-07-23 20:28
@Koc sure

```yaml
framework:
    messenger:
        failure_transport: failed
        serializer:
            default_serializer: messenger.transport.symfony_serializer
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
        transports:
            failed:
                dsn: 'doctrine://default?queue_name=failed'
            notification:
                dsn: enqueue://default?topic[name]=%env(NOTIFICATION_QUEUE)%&queue[name]=%env(NOTIFICATION_QUEUE)%
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
        routing:
            'Core\Message\Notification\ApiNotificationInterface': notification
            'Core\Message\Notification\EmailNotificationInterface': notification

```

**Comment by Koc** [comment] 2019-07-23 20:52
This is strange. Personally I don't using close connection middleware, but my app using pretty similar clear entity manager middleware. My config looks like

```yaml
framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                default_middleware: false
                middleware:
                    - App\Common\Infrastructure\Messenger\ProcessMonologHandlersMiddleware
                    - validation
                    - # try locate close connection here
                    - App\Common\Infrastructure\Messenger\DoctrineClearEntityManagerMiddleware
                    - App\Common\Infrastructure\Messenger\DispatchDomainEventsMiddleware
                    - doctrine_ping_connection
                    - doctrine_transaction
                    - send_message
                    - handle_message
```

Will try test it with close connection also.

**Comment by insidestyles** [comment] 2019-07-24 05:30
@maks-rafalko The configuration should be
>middleware:
>                     - doctrine_ping_connection
>                     - send_message
>                     - handle_message
>                     - doctrine_close_connection

I don't remember if we can configure after/before middlewares

**Comment by insidestyles** [comment] 2019-07-24 06:38
@maks-rafalko IC, it does not work in your case (. The middleware works in the bus context (working process is put in the bus cycle). In your case, the bus is put in the working process. The solutions may be using different buses.

**Comment by maks-rafalko** [comment] 2019-07-24 06:58
@insidestyles you are right.

So, when I use the code from the [documentation](https://symfony.com/doc/current/messenger.html#middleware-for-doctrine), it literally says the following:

```yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
                    - doctrine_ping_connection
                    - doctrine_close_connection
```

which resolves to the next middleware stack (8 middlewares, including default):

```
add_bus_name_stamp_middleware
dispatch_after_current_bus
failed_message_processing_middleware

doctrine_transaction
doctrine_ping_connection
doctrine_close_connection

send_message
handle_message
```

and [this does not work](https://github.com/symfony/symfony/issues/32436#issuecomment-514274275). I would at least suggest to update the documentation, saying for example to disable default middlewares (`defaulte_middleware: false`) and to order them differently:


```yaml
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
                    - doctrine_ping_connection
                    - send_message
                    - handle_message
                    - doctrine_close_connection
```

But even with this config, when `doctrine_close_connection` middleware is the last one, when I have a `sync` transport and the message is being handled **immediately** during the opened transaction, EntityManager's connection is being closed after it, leading to `ROLLBACK`

So, anyway, the current state of the doc with suggested `doctrine_close_connection` is quite dangerous.

**Comment by insidestyles** [comment] 2019-07-24 07:12
@maks-rafalko see the order of middlewares in @Koc 's comment. I don't use doctrine_close_connection in Sync. I thought you called bus command in another bus or process. The close connection is put in finnally block, so it should be called firstly

**Comment by weaverryan** [comment] 2019-09-05 15:56
Question: Why not automatically/always perform some sensible doctrine-related actions at the beginning and end of handling each message in the work?

A) worker is about to start looking for a message
B) ping all open connections
C) clear all entity managers
D) find & handle the message
E) (optionally? configurable?) close all open connections

(B) & (C) seem sensible to me in all situations. Or am I missing something? We could add 2 new event listeners into core that just handle this automatically for users.

**Comment by mareksuscak** [comment] 2019-09-11 21:05
Encoutered the same issue as @maks-rafalko and I also followed messenger's setup guide. It's just confusing.

**Comment by maks-rafalko** [comment] 2019-09-11 21:42
It runs in both contexts, that's why we are using 2 different message buses, one for the sender, one for the receiver (worker).

And only worker context has `doctrine_ping_connection`

```yaml
buses:
  messenger.bus.default:
    middleware:
      - ...
      # Override the bus name that should receive and handle messages (bus name:  consumer.bus)
      - App\Messenger\Middleware\AddConsumerBusNameStampMiddleware

  consumer.bus:
    middleware:
      - ...
      - doctrine_ping_connection
```

To make it work, we've added another middleware that overrides consumer bus name so that worker can use different bus (not a default one `messenger.bus.default`). It looks like a workaround, but this is what we came up with, also discussed it with @weaverryan on the slack

```php
final class AddConsumerBusNameStampMiddleware implements MiddlewareInterface
{
    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        $envelope = $envelope->with(new BusNameStamp('consumer.bus'));

        return $stack->next()->handle($envelope, $stack);
    }
}
```

**Comment by mareksuscak** [comment] 2019-09-11 22:00
> It runs in both contexts, that's why we are using 2 different message buses, one for the sender, one for the receiver (worker).

Middleware only run [on message dispatch](https://github.com/symfony/messenger/blob/ec100a635df61aa89ed4daac8ca07425d7289e51/MessageBus.php#L80), no? Worker class [doesn't seem to run middleware chain](https://github.com/symfony/messenger/blob/ec100a635df61aa89ed4daac8ca07425d7289e51/Worker.php#L83-L178).

**Comment by weaverryan** [comment] 2019-09-16 15:46
The fact that people are working around this by creating 2 different buses (one to send the message and another to receive) helps to prove the point that the `doctrine_ping_connection` (at least) should not be a middleware and instead should be something that is done in the Worker. And then... why not *always* do it in the worker automatically?

**Comment by mareksuscak** [comment] 2019-09-16 15:54
I agree that this workaround is a suboptimal solution. But we also have a few message handlers that wouldn't work correctly when wrapped in a transaction because we need those partial results immediately.

**Comment by jvasseur** [comment] 2019-09-16 18:03
I think the problem is that the middlewares defined before the `send_message` middleware are executed both on the sender side and on the receiver side. Logically the sending side should execute all middlewares until the `send_message` middleware and stop here (that's how it currently work) and the receiving side should start where the sending side stopped: juste after the `send_message` middleware. 

By doing this we could easily chose which middleware is executed on which side by placing them before or after the `send_message` middleware.

**Comment by weaverryan** [comment] 2019-09-18 13:43
> Logically the sending side should execute all middlewares until the send_message middleware and stop here (that's how it currently work) and the receiving side should start where the sending side stopped: just after the send_message middleware.

That's correct... and logical. But I think it also doesn't solve the problem completely. For example, for "sync" messages, the "ping doctrine connection" would still do its work... which doesn't make sense.

So my vote is still to attempt to turn "ping Doctrine connection" (and maybe "close connection"... but I'm trying to focus only on "ping" right now for simplicity) into an event listener that's done on a worker event... and do it *always* for *all* open connections (if that's possible).

> @mareksuscak  Handler lifecycle hooks might be a solution here

I wasn't sure what you meant by this?

**Comment by LPodolski** [comment] 2019-10-02 19:51
@bendavies @weaverryan 

actually you can use Middleware and still have this logic inside of middleware, working on my project I was in need of doctrine clear, but it was executed also when dispatching, so in middleware I target only when receiving message using stamp for that:

`


    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        try {
            $entityManager = $this->managerRegistry->getManager();
        } catch (\InvalidArgumentException $e) {
            throw new UnrecoverableMessageHandlingException($e->getMessage(), 0, $e);
        }

        try {
            return $stack->next()->handle($envelope, $stack);
        } finally {
            if (null !== $envelope->last(ReceivedStamp::class)) {
                $entityManager->clear();
            }
        }
    }
`

albove code is part of middleware, very similar to: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Messenger/DoctrineClearEntityManagerMiddleware.php

only one major difference is that it is executed only when receiving message by checking

`
if (null !== $envelope->last(ReceivedStamp::class)) {
`

**Comment by weaverryan** [comment] 2019-10-17 13:19
@LPodolski I was wondering if we should do that EXACT same thing in the core middleware as a way to fix this - only clear, ping and close if the ReceivedStamp is present. I would love to see someone create a PR for this to continue the discussion. Heck, if the middleware worked like this, I would want them to be enabled by default (but that's another discussion)

**Comment by jrjohnson** [comment] 2019-10-21 19:01
We hit this hard in production when using messages to trigger our search index to be updated in `postPersist`. Using `doctrine_close_connection` throws `There is no active transaction` because the connection is closed on `dispatch`. After reading this thread I understand why this is called here, but I think `dispatch` is always going to be called synchronously so this middleware will never make sense.  For now I've converted to a two bus (read/write) pattern.

**Comment by B-Galati** [comment] 2019-10-21 19:50
Middlewares should not be called when dispatching messages to an Async transport. That's counter intuitive IMHO.

**Comment by weaverryan** [comment] 2019-10-22 13:03
> Middlewares should not be called when dispatching messages to an Async transport. That's counter intuitive IMHO.

This is a fair opinion, but this concept is *fundamental* to Messenger and won't change.

**Comment by weaverryan** [comment] 2019-10-22 13:31
See #34066 for a fix that I hope will please everyone :)

**Comment by B-Galati** [comment] 2019-10-22 15:22
> See #34066 for a fix that I hope will please everyone :)

@weaverryan makes sense for these :+1: 

For the doctrine transaction middleware, it can be used sync or async.
It does not make sense to me to start a transaction when dispatching a message that will be handled asynchronously but it makes sense if the message is handled synchronously.

Is there any solution to handle this use case?

**Closed** 2019-10-22 15:22 UTC
Labels: Bug, Messenger, Status: Needs Review

**Comment by weaverryan** [comment] 2019-10-22 15:58
> It does not make sense to me to start a transaction when dispatching a message that will be handled asynchronously but it makes sense if the message is handled synchronously.
> Is there any solution to handle this use case?

Hmm, I see your point. But does it cause any issue to start the transaction unnecessarily? For an async message, you would start the transaction, then the message would be "sent", then you would close it. That's maybe not ideal, but I'm not sure if it's a real issue. And I don't know if there is any solution - before the `SendMessageMiddleware` is called, we don't know whether or not the message *will* be sent (and thus whether or not to start the transaction).

**Comment by B-Galati** [comment] 2019-10-22 16:17
> Hmm, I see your point. But does it cause any issue to start the transaction unnecessarily? 

Yes that's basically a waste of resources: unused db connection, starting the transaction then cleaning everything.

The middleware could have an argument so that if we know the bus is plugged to an async transport then one can configure it to behave accordingly.

**Comment by weaverryan** [comment] 2019-10-22 16:42
> The middleware could have an argument so that if we know the bus is plugged to an async transport then one can configure it to behave accordingly.

Middleware are tied to a bus, not a specific transport (a bus could send to many different transports), unfortunately. But I see your point. It's not too important to me personally (I don't rely on the middleware for my transactions), but it could be fixed if someone is motivated. You would basically need to re-use/share the logic from `SendMessageMiddleware::getSenders()` so that, in a middleware before `SendMessageMiddleware`, you could determine whether or not the message *will* be sent.
