### ISSUE TITLE
[Translator] First occurence in yml not read

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#14297] opened 2015-04-10 08:08 UTC
Over the last few months occasionally a quite weird bug occurs. Seems to be occurring since the `2.6` branch, but don't tested that yet. Will make a reproducible test case later on.

```twig
{{ 'step'|trans({'%step%': stepNo}) }}
```

__Not working__
```yml
step: Schritt %step%
to_step: Zu Schritt %step% »
```
__Working__
```yml
stub: - empty -
step: Schritt %step%
to_step: Zu Schritt %step% »
```
The first translation occurrence in the yml file is not read, so the fallback message is shown. Clearing the cache does not solve it, putting a "stub" translation on top of the file does solve it.

**Comment by aitboudad** [comment] 2015-04-10 09:52
I'll look into it

**Comment by aitboudad** [comment] 2015-04-10 10:19
I can't reproduce your issue in both 2.6-dev and 2.7-dev.
can you make the changes in a fork of Symfony Standard Edition to reproduce it?

**Comment by iltar** [comment] 2015-04-11 09:02
I'm running symfony 2.6 and I don't think I have this issue. I can check next Monday if it's really the case when I update to the latest patch version.

**Comment by Rvanlaak** [comment] 2015-04-14 09:06
Tried to narrow this down, but did not resolve it completely yet. It has something to do with the initial caching of the translation catalogs, because after restarting Apache on the PROD environment the key is read properly.

Will work on debugging this later on.

**Comment by aitboudad** [comment] 2015-04-29 21:42
Closing as there is no feedback. @Rvanlaak Feel free to reopen if you have more details.

**Closed by aitboudad** 2015-04-29 21:42 UTC
Labels: Translator, Unconfirmed, Yaml

**Comment by Rvanlaak** [comment] 2015-04-30 07:04
:+1:

**Comment by Rvanlaak** [comment] 2015-09-15 12:16
Found some more info about this while I was writing a `JsonExporter`, the first character of the result file was the following:

    [\ufeff](http://www.fileformat.info/info/unicode/char/FEFF/index.htm)

So the [UTF BOM](http://www.unicode.org/faq/utf_bom.html#bom1) character seems to mess up the translation key here. PHPStorm does not seem to properly format this.
