### ISSUE TITLE
Error new symfony 3.3.3

### ISSUE THREAD

**Issue by Dumbeldor** [symfony/symfony#23407] opened 2017-07-05 10:14 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

I have this error when scaffolding new symfony project (3.3.3):

![capture du 2017-07-05 12-13-18](https://user-images.githubusercontent.com/3883583/27860125-6e23675a-617b-11e7-8517-7637fe8b18a9.png)

Thank you !

**Comment by syrm** [comment] 2017-07-05 10:17
Nice testing Symfony team, nice...

**Comment by nicolas-grekas** [comment] 2017-07-05 10:26
Duplicate of #23382, fixed in #23378.

@syrm, I think we need less sarcasm. We only do our best, your help is welcomed to go to the next step.

**Closed by nicolas-grekas** 2017-07-05 10:26 UTC

**Comment by syrm** [comment] 2017-07-05 11:57
You're right, i'm sorry. But let a bug like that in a release is not acceptable.

**Comment by fabpot** [comment] 2017-07-05 12:04
@syrm Wow, I suppose you should start helping us being more professional then.

You can start today by helping us test dev branches on your projects so that you can spot issues and report them before releases. You could probably also help us fix bugs; good news for you, there are many reported by other users that need some love. You would be more than welcome. We need help as any other Open-Source project. So many people using Symfony without helping is unacceptable as well.

**Comment by syrm** [comment] 2017-07-05 12:21
I understand your point of view. But i have other project to do. And Symfony is supported by Sensio it's Sensio's job to avoid problem like that.

**Comment by fabpot** [comment] 2017-07-05 12:21
@syrm Then, buy a support package from SensioLabs.

**Comment by syrm** [comment] 2017-07-05 12:22
Clap clap.

**Comment by fabpot** [comment] 2017-07-05 12:24
@syrm I think you understand nothing about Open-Source, that's really a shame. I spent 12 years of my life, days and night, and all I get is that kind of comments. Thank you very much.
