### ISSUE TITLE
[Routing] Simplify compiled regular expressions

### ISSUE THREAD

**Issue by gerryvdm** [symfony/symfony#13900] opened 2015-03-11 14:26 UTC
It caught my attention that the RouteCompiler uses the `?P<tokenName>` syntax for route tokens in the compiled regex. However, since PHP 5.2.2 you can use the alternative syntax `?<tokenName>`.

Would changing the compiled output not simplify the regular expression and make it more readable?

**Comment by stof** [comment] 2015-03-11 14:48
@gerryvdm the issue is that supporting the ``?<>`` notation rather than ``?P<>`` notation does not actually depend on the PHP version but on the PCRE version being used when compiling PHP. In the past, we were using this notation, and we changed it when some people complain about it not working on some distributions using their (older) system PCRE rather than the one bundled in PHP.

And I don't think it will simplify the regular expression anyway: it is exactly the same for the regex engine AFAIK (and regarding readability, users would normally never need to read this regex)

**Comment by fabpot** [comment] 2015-03-11 17:06
Closing for the reasons given by @stof. I'm pretty sure we hit the problem he mentioned as some point.

**Closed by fabpot** 2015-03-11 17:06 UTC
Labels: Routing
