### ISSUE TITLE
[Serializer] It always returns an instance of DateTimeImmutable for date fields

### ISSUE THREAD

**Issue by twisted1919** [symfony/symfony#59093] opened 2024-12-04 17:05 UTC
### Symfony version(s) affected

7.2

### Description

After upgrading from 7.1 to 7.2, using API-Platform as well, when sending a payload that contains a `date` field in the format of `Y-m-d` it is converted into a `DateTimeImmutable` object. which seems to be a new behavior. 

Because of this, we're getting errors like:
```
Could not convert PHP value of type DateTimeImmutable to type Doctrine\\DBAL\\Types\\DateType. Expected one of the following types: null, DateTime
```

### How to reproduce

Define an entity with a date column like:
```php
#[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
#[Assert\Type(\DateTimeInterface::class)]
private ?\DateTimeInterface $deadline = null;
```
And send a payload like `{"deadline": "2024-12-04"}`

**Comment by xabbuh** [comment] 2024-12-04 19:55
Can you create a small example application that allows to reproduce your issue?

**Comment by twisted1919** [comment] 2024-12-05 06:34
@xabbuh - it would be very difficult, sorry, the app I am talking about is just huge and my time for it is very limited. I'll try to use the 7.1 serializer version and if that works, then it means something introduced in 7.2 broke things. I'll let you know about this today.

**Comment by twisted1919** [comment] 2024-12-05 06:50
@xabbuh - okay, so I discovered it is not the serializer, but it is actually doctrine's dbal.
I've upgraded that as well from 3.9 to 4.2 and it seems this pull request https://github.com/doctrine/dbal/pull/6161 made stricter checks for datetime objects.

However, shouldn't symfony take care of the conversion or at least give us an option/attribute to decide whether a property should be deserialized as DateTime or DateTimeImmutable?

Currently my workaround this problem is to simply convert the value to a DateTime inside the setter method of the property.

**Comment by xabbuh** [comment] 2024-12-05 08:39
> However, shouldn't symfony take care of the conversion or at least give us an option/attribute to decide whether a property should be deserialized as DateTime or DateTimeImmutable?

Symfony does that based on the type-information it can deduce from your code. In your case the solution is to change the types from `DateTimeInterface` to `DateTime` as that's what your application actually requires here as you find out.

Thus, I am closing here as that’s not a bug in the Symfony code. Thank you for understanding.

**Closed as not planned by xabbuh** 2024-12-05 08:39 UTC
Labels: Serializer, Bug, Status: Needs Review, Status: Waiting feedback

**Comment by twisted1919** [comment] 2024-12-05 15:53
@xabbuh - You should know that I tried that before I posted here, and it does not work.

**Comment by xabbuh** [comment] 2024-12-05 15:59
Please create a small example application then that allows to reproduce it.

**Comment by aleblanc** [comment] 2024-12-13 10:25
Hello, 

I encountered the same issue when migrating to ORM 3 / DBAL 4. I simply replaced:

`private ?\DateTimeInterface $date = null;`

With:

`private ?\DateTime $date = null;`

And now the serializer correctly returns a DateTime instead of a DateTimeImmutable.

**Comment by stof** [comment] 2024-12-13 10:42
The Serializer component will indeed prefer using `DateTimeImmutable` over `DateTime` whne being asked for `DateTimeInterface`.
The issue here is that the `*_MUTABLE` types of DBAL 4 are **not** compatible with `DateTimeInterface`. They require `DateTime` specifically (in DBAL 3, they support `DateTimeImmutable` but trigger deprecation warnings). Defining your property type in sync with the ORM expectation is indeed the right solution here (btw, if you use phpstan, the phpstan-doctrine extension should be able to report such mismatch)

**Comment by aleblanc** [comment] 2024-12-13 13:02
Thank you for the information @stof, but in my case, it was about converting a JSON into a DTO object (not directly an Entity).

`$test = $serializer->deserialize($request->getContent(), TestDto::class, JsonEncoder::FORMAT);`

The parameter of my DTO object was then passed to the entity, which caused an error because it was passing a DateTimeImmutable.

**Comment by stof** [comment] 2024-12-13 13:11
@aleblanc if your entity expects a DateTime and not a DateTimeInterface, either also expect a DateTime in your DTO or perform the necessary conversion between them. In any case, this is not an issue in Symfony (btw, that's the kind of issues that static analysis is very good at preventing)
