### ISSUE TITLE
Single quote and slashes bug

### ISSUE THREAD

**Issue by cirovargas** [symfony/symfony#18207] opened 2016-03-17 01:40 UTC
I'm customizing the crud generator in symfony and came across the following problem:

Trying to compare strings with single quote:

    {% if data.filterWidget == 'FormFilterTypes\TextFilterType' %}

In the data.filterWidget have the same string but this returns false to me.

Escaping with doble slashes it's ok, but it seems a fault when compared to the PHP core.

     {% if data.filterWidget == 'FormFilterTypes\\TextFilterType' %} {# with var data.filterWidget with doble slashes too #}

**Comment by stof** [comment] 2016-03-17 18:07
There is no symfony bug here. Backslashes must always be escaped in Twig to represent them in string literals. you need to understand that your Twig template is not written in PHP, but in Twig, which is a different language.

**Comment by javiereguiluz** [comment] 2016-03-18 14:08
@cirovargas thanks for creating this issue. As @stof explained, although this behavior looks like an error, it's in fact the expected behavior of Twig.

The docs about backslashes inside strings (http://twig.sensiolabs.org/doc/templates.html#literals) could explain things better, so I've created a pull request in Twig repository to improve this (https://github.com/twigphp/Twig/pull/2005).

I'm closing this issue as "fixed" then. Thanks!

**Closed by javiereguiluz** 2016-03-18 14:08 UTC
