### ISSUE TITLE
ACL Memory Leak

### ISSUE THREAD

**Issue by KaipiYann** [symfony/symfony#2376] opened 2011-10-10 20:00 UTC
Hi everybody,

Since I didn't get any answer to my post in Symfony Dev Group, Hugo H told me to post here the following memory leak problem.

I have made **a very simple batch command that you can find at the end**  so you can test and check if I missed something or not.

**What does this batch ?**
It takes a very simple object (created only for testing purpose) :

```php
class TestDomainObject implements DomainObjectInterface
{
	protected $id = 0;
	
	public function __construct(){
		
	}

	public function setId($id){
		$this->id = $id;
	}
	public function getObjectIdentifier() {
		return strtoupper("TESTDO_".$this->id);
	}
	
	public function getId() {
		return $this->id;
	}
}
```

Then make a simple ACL creation with one ACE :

```php
protected function testUpdateACL($id)
{
    	$this->testDomainObject->setId($id);
    	$objectIdentity = ObjectIdentity::fromDomainObject($this->testDomainObject);
    	$acl = $this->aclProvider->createAcl($objectIdentity);
	$adminIdentity = new RoleSecurityIdentity("ROLE_ADMIN");
        $acl->insertObjectAce($adminIdentity, MaskBuilder::MASK_VIEW);
        $this->aclProvider->updateAcl($acl);
}
```

And Iterate  30000 times on this update :

```php
for($i=0; $i<30000; $i++) {
	$this->testUpdateACL($i);
	if (($i % 2000) == 0) {
		$output->write("Iteration =".$i." Memory = ".memory_get_usage().PHP_EOL);
	}
}
```

Then just run the test taking care of no-debug option in env prod :

```php
app/console --no-debug --env="prod" acl:leak
```

**Result :**
Iteration =0 Memory = 30336888
Iteration =2000 Memory = 41741288
Iteration =4000 Memory = 57838048
Iteration =6000 Memory = 73056744
Iteration =8000 Memory = 89967144
Iteration =10000 Memory = 105108416
Iteration =12000 Memory = 119921520
Iteration =14000 Memory = 134733504
Iteration =16000 Memory = 153898744
Iteration =18000 Memory = 169364552
Iteration =20000 Memory = 184178000
Iteration =22000 Memory = 198991480
Iteration =24000 Memory = 213802848
Iteration =26000 Memory = 228772712
Iteration =28000 Memory = 243585680

Did I missed something or is it an ACL problem with use of DBAL ? 
Thks
Y

## LeakAclCommand.php

```php
<?php
namespace FSC\CoreBundle\Command;
use Symfony\Component\Security\Acl\Permission\MaskBuilder;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Acl\Domain\RoleSecurityIdentity;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;


class LeakAclCommand extends ContainerAwareCommand
{
	private $testDomainObject;
	private $aclProvider;
	
    /**
     * @see Command
     */ 
	protected function configure()
    {
    	
        $this->setName('acl:leak')
       		->setDescription("Test memory leak on ACL");
    }

    /**
     * @see Command
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
		try
		{
			$this->aclProvider = $this->getContainer()->get('security.acl.provider');
			$this->testDomainObject = new TestDomainObject();
			for($i=0; $i<30000; $i++) {
				$this->testUpdateACL($i);
				if (($i % 2000) == 0) {
					$output->write("Iteration =".$i." Memory = ".memory_get_usage().PHP_EOL);
				}
			}
			$output->write('Test Done'. PHP_EOL);
		}
		catch (\Exception $e)
		{
		    $output->write(PHP_EOL.'Caught a Exception. (' . $e->getMessage() . ')' . PHP_EOL);
		} 
        
    }
    
	protected function testUpdateACL($id)
    {
    	$this->testDomainObject->setId($id);
    	$objectIdentity = ObjectIdentity::fromDomainObject($this->testDomainObject);
    	$acl = $this->aclProvider->createAcl($objectIdentity);
		$adminIdentity = new RoleSecurityIdentity("ROLE_ADMIN");
        $acl->insertObjectAce($adminIdentity, MaskBuilder::MASK_VIEW);
        $this->aclProvider->updateAcl($acl);
    }
}

use Symfony\Component\Security\Acl\Model\DomainObjectInterface;

class TestDomainObject implements DomainObjectInterface
{
	protected $id = 0;
	
	public function __construct(){
		
	}

	public function setId($id){
		$this->id = $id;
	}
	public function getObjectIdentifier() {
		return strtoupper("TESTDO_".$this->id);
	}
	
	public function getId() {
		return $this->id;
	}
}
```

**Comment by loconox** [comment] 2015-01-28 10:39
I'm encountering the same issue. Any updates ?

**Comment by bilougit** [comment] 2015-06-24 14:57
I'm encountering the same problem here, where are we on this? is it fixed?
@adrienbrault I've tried your workaround but didn't work
symfony2.3

**Comment by ewgRa** [comment] 2015-09-03 20:14
symfony-standard fork with this command https://github.com/ewgRa/symfony-standard/tree/reproduce-issue-2376
Also added truncate acl tables to command, to able rerun command without manual truncate.

After clone run: 
mysql -e "create database symfony"
php app/console init:acl

**Comment by ewgRa** [comment] 2015-09-03 23:10
Solution from @RGustBardon works, but it is kind of dirty.

It must be enough to free MutableAclProvider::propertyChanges, AclProvider::loadedAces and AclProvider::loadedAcls, but problem is that this is not enough. Also we need clean Acl::objectAces, that can have some side effects and make this solution dirty.

When we free only first three properties, Acl::__destruct not called, because Acl::insertAce create Entry, that take this Acl as constructor argument. And Acl store this Entry in self.

        $aces[$index] = new Entry(null, $this, $sid, $strategy, $mask, $granting, false, false);
        $this->$property = $aces;

This is why Acl::__destruct not called, even if nobody refers on it outside.


I will check this theory later more carefully and try to find best solution.

**Comment by ewgRa** [comment] 2015-09-04 07:52
Seems I right. I add another command that reproduce destruct work.

app/console --no-debug --env="prod" acl:destruct-check

It shows that Acl objects destructed only at the end of script, even there is no refers "outside" this class.

**Comment by ewgRa** [comment] 2015-09-10 19:54
PR for this problem ^^^^. When it will be finished somehow, problem of this issue can be done by call releaseMemory at provider.

**Comment by fabpot** [comment] 2015-10-05 10:27
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.

**Closed by fabpot** 2015-10-05 10:27 UTC
Labels: Acl, Bug, Enhancement
