### ISSUE TITLE
Cannot use redirectToRoute() since 4.0

### ISSUE THREAD

**Issue by xchopin** [symfony/symfony#25351] opened 2017-12-06 09:58 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

Hi, sorry if the question looks silly but I am stucked for hours since the 4.0 version of Symfony.
In my `AuthController` I am trying to redirect the user to the homepage by using `$this->redirectToRoute('home')` but I get the following error :  <br>
``` The "router" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. ``` 

with these details : 
```

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
The "router" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

  at vendor/symfony/dependency-injection/Container.php:252
  at Symfony\Component\DependencyInjection\Container->get('router')
     (vendor/symfony/framework-bundle/Controller/ControllerTrait.php:73)
  at Symfony\Bundle\FrameworkBundle\Controller\Controller->generateUrl('home', array())
     (vendor/symfony/framework-bundle/Controller/ControllerTrait.php:110)
  at Symfony\Bundle\FrameworkBundle\Controller\Controller->redirectToRoute('home')
     (src/Controller/AuthController.php:33)
  at App\Controller\AuthController->login()
  at call_user_func_array(array(object(AuthController), 'login'), array())
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:190)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:30)
``` 

I installed the framework extra bundle, and of course extended my class to `Controller`.

It worked well before I upgraded to this new version.

Any ideas please ? :( 

Thank you

**Comment by xabbuh** [comment] 2017-12-06 10:01
Do you by chance use BeSimpleI18nRoutingBundle or JMSI18nRoutingBundle? It looks like this could be a duplicate of #25328.

**Comment by xchopin** [comment] 2017-12-06 10:01
Yes I am using JMSI18n, thanks for the link

**Comment by xabbuh** [comment] 2017-12-06 10:04
Thanks for confirming. Closing then.

**Closed by xabbuh** 2017-12-06 10:04 UTC
