### ISSUE TITLE
Issue related to release of phpunit 9.6.14

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#52851] opened 2023-12-01 13:59 UTC
### Symfony version(s) affected

6.3.8

### Description

Since phpunit 9.6.14 I have an issue when running vendor/bin/simple-phpunit.

I created ticket for this in PHPunit repo but it was suggested to report it here.
https://github.com/sebastianbergmann/phpunit/issues/5594

#### Current behavior

Just run phpunit from symfony bridge.

### How to reproduce

```
vendor/bin/simple-phpunit
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.6-0"
Installing phpunit/phpunit (9.6.14)
Plugins have been disabled.
  - Installing phpunit/phpunit (9.6.14): Extracting archive
Created project in X:\...\vendor\bin\.phpunit\phpunit-9.6-0
phpspec/prophecy is not required in your composer.json and has not been removed
composer.json has been updated
composer.json has been updated
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required package "symfony/phpunit-bridge" is not present in the lock file.
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r
```

**Comment by fancyweb** [comment] 2023-12-01 14:00
Duplicate of https://github.com/symfony/symfony/issues/52844

**Closed as not planned by fancyweb** 2023-12-01 14:00 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review
