### ISSUE TITLE
possible BC break in 2.8.18

### ISSUE THREAD

**Issue by craigh** [symfony/symfony#21949] opened 2017-03-09 14:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 2.8.18

continued/copied from #21931

I am having trouble with failing tests since upgrading from 2.8.17 -> 2.8.18

2.18.17 -> [tests pass](https://travis-ci.org/zikula/core/jobs/206548605)

2.18.18 -> [tests fail](https://travis-ci.org/zikula/core/jobs/208185401)

[breaking commit](https://github.com/zikula/core/commit/6b265466a3c10226452200fac0bcf0c4bce3712a) was a simple vendor update

I believe we are correctly `require`-ing the [autoload file](https://github.com/zikula/core/blob/1.4/src/app/autoload.php#L19)

commits: https://github.com/zikula/core/commits/1.4

we have since added a phpunit dependency which wasn't previously included. This solved the `PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found...` error, but with that corrected, now two of our **_previously passing_** tests now [fail](https://travis-ci.org/zikula/core/jobs/208541407).

both failures are tests of a pseudo-entity type form type
1. https://github.com/zikula/core/blob/1.4/src/system/CategoriesModule/Tests/Form/Type/CategoriesTypeTest.php#L155
2. https://github.com/zikula/core/blob/1.4/src/system/CategoriesModule/Tests/Form/Type/CategoriesTypeTest.php#L219

since nothing else has changed I am very confused what to do and would very much appreciate your help. thanks in advance

**Comment by stof** [comment] 2017-03-09 15:21
@craigh use an uptodate version of PHPUnit. PHPUnit provides the namespaced classes in 4.8.35+ and 5.4.3+. Using the namespaced classes rather than the old names is because PHPUnit 6 removed the old classes

**Comment by craigh** [comment] 2017-03-09 18:20
@stof perhaps I don't understand your meaning. I believe we are using 4.8.35

ping @Guite

**Comment by nicolas-grekas** [comment] 2017-03-09 18:22
How are you sure that this is related in any way to the phpunit update? There are many other things that changed. Could be a BC break in forms, you relying on a fixed behavior, etc.
?

**Comment by craigh** [comment] 2017-03-09 19:09
@nicolas-grekas I feel I can be reasonably certain because nothing else changed besides the vendor update. If I revert the _other_ vendor changes, the problem still exists. These commits (see the list above) are sequential - so it worked _before_ updating to 2.8.18 and not after. I'm willing to consider other issues or possible mistakes I have made (I've made my fair share certainly).

**Comment by xabbuh** [comment] 2017-03-09 19:44
@craigh Seeing #21952 I double checked your failing tests and the cause for their failures is the same. To me that's something that needs to be fixed in your test suite (I submitted a PR in zikula/core#3487 that makes your builds green again). Even if your issue is older than #21952, I am going to close here as the other one contains a better description of the problem and clearly explains the root cause. Let's continue the discussion over there whether this is a regression or a misuse of the component.

**Closed by xabbuh** 2017-03-09 19:44 UTC

**Comment by craigh** [comment] 2017-03-09 20:02
thank you @xabbuh !
