### ISSUE TITLE
Updating Symfony to version 3.2.2 updates Twig to version 2.1.0 that requires PHP 7.

### ISSUE THREAD

**Issue by mariopr25** [symfony/symfony#21410] opened 2017-01-25 21:04 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

I have updated my Symfony project from version 3.2.0 to version 3.2.2 using "composer update", and it updates the version of Twig to 2.1.0 that requires PHP 7, but composer.json still displays "php": ">=5.5.9" as the PHP requirement. 

So After the update my project got errors like: "Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given" whose reason is expressions like: 
`public function __construct(string $name, $callable = null, array $options = array())`
in vendor/twig/twig/lib/Twig/Filter.php
That uses a new feature of PHP 7

To bypass this problem i executed: `composer require twig/twig 1.x` (after or before project update)

I think that this is a bug because i didn't read anything about this new Twig version and its related requirement of PHP 7 in this release notes or in composer.json.

Steps to reproduce:
1. create new Symfony-3.2 project: `symfony new my-project 3.2`
2. in project directory execute `composer update` or `composer update symfony/symfony --with-dependencies`
3. check installation of Twig 2.1.0 instead of 1.x one

Additional data:
Section "require" of my composer.json file, before i executed `composer require twig/twig 1.x`, was:
```
 "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^3.0",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/assetic-bundle": "^2.8",
        "knplabs/knp-paginator-bundle": "^2.5",
    },
```

and "composer info" displayed:
```
doctrine/annotations                 v1.3.1  Docblock Annotations Parser
doctrine/cache                       v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.4.0  Collections Abstraction library
doctrine/common                      v2.7.2  Common Library for Doctrine projects
doctrine/dbal                        v2.5.9  Database Abstraction Layer
doctrine/doctrine-bundle             1.6.6   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0   Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         v2.5.6  Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.2  Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
knplabs/knp-components               1.3.4   Knplabs component library
knplabs/knp-paginator-bundle         2.5.3   Paginator bundle for Symfony2 to automate pagination and simplify sorting and other features
kriswallsmith/assetic                v1.4.0  Asset Management for PHP
monolog/monolog                      1.22.0  Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat              v2.0.4  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                            1.0.1   Common interface for caching libraries
psr/log                              1.0.2   Common interface for logging libraries
sensio/distribution-bundle           v5.0.18 Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.19 This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.2  This bundle generates code for you
sensiolabs/security-checker          v4.0.0  A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.5  Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle               v3.0.3  Symfony MonologBundle
symfony/phpunit-bridge               v3.2.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu            v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.3.0  Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.4.2  Symfony SwiftmailerBundle
symfony/symfony                      v3.2.2  The Symfony PHP framework
twig/twig                            v2.1.0  Twig, the flexible, fast, and secure template language for PHP
```
`symfony new mi-project 3.2` install Symfony-3.2.2 with twig 1.x correctly (some days ago it still installed Symfony-3.2.1 but Symfony-3.2.2  had already been released  )

**Comment by robfrawley** [comment] 2017-01-25 22:56
I ran through the reproduction steps @mariopr25 outlined, and I ran into a slightly different but equally concerning issue on PHP 7: Composer *correctly* upgrades `twig/twig` to the `2.x` series, but while calling the cache warm composer script, a fatal error is thrown:

```
[RuntimeException]                                                                                                                                                                           
An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                    
PHP Fatal error:  Cannot redeclare twig_get_attribute() in /home/rmf/repositories/composer/my-project/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1561                              
PHP Stack trace:                                                                                                                                                                             
PHP   1. {main}() /home/rmf/repositories/composer/my-project/bin/console:0                                                                                                                   
PHP   2. Symfony\Component\Console\Application->run() /home/rmf/repositories/composer/my-project/bin/console:28                                                                              
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120     
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:68         
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:116        
PHP   6. Symfony\Component\DependencyInjection\Container->get() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:496            
PHP   7. appDevDebugProjectContainer->getCacheWarmerService() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310  
PHP   8. Symfony\Component\DependencyInjection\Container->get() /home/rmf/repositories/composer/my-project/var/cache/dev/appDevDebugProjectContainer.php:414                                 
PHP   9. appDevDebugProjectContainer->getTwigService() /home/rmf/repositories/composer/my-project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310         
PHP  10. Twig_Environment->__construct() /home/rmf/repositories/composer/my-project/var/cache/dev/appDevDebugProjectContainer.php:3150                                                       
PHP  11. spl_autoload_call() /home/rmf/repositories/composer/my-project/vendor/twig/twig/lib/Twig/Environment.php:106                                                                        
PHP  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /home/rmf/repositories/composer/my-project/vendor/twig/twig/lib/Twig/Environment.php:106
```

The following steps are all that is required to reproduce:

```
symfony new my-project 3.2
cd my-project
composer update
```

With that said, I could not reproduce the original issue @mariopr25 mentioned when running PHP `5.6.29`. When executing the above reproduction steps, it does not result in `twig/twig` being upgraded to `2.x` using PHP `5.6.29`. Instead, this is the (expected) result:

```
doctrine/annotations                 v1.3.1  Docblock Annotations Parser
doctrine/cache                       v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.4.0  Collections Abstraction library
doctrine/common                      v2.7.2  Common Library for Doctrine projects
doctrine/dbal                        v2.5.10 Database Abstraction Layer
doctrine/doctrine-bundle             1.6.7   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0   Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         v2.5.6  Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.2  Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
monolog/monolog                      1.22.0  Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat              v2.0.4  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                            1.0.1   Common interface for caching libraries
psr/log                              1.0.2   Common interface for logging libraries
sensio/distribution-bundle           v5.0.18 Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.19 This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.2  This bundle generates code for you
sensiolabs/security-checker          v4.0.0  A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.5  Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               v3.0.3  Symfony MonologBundle
symfony/phpunit-bridge               v3.2.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu            v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.3.0  Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.4.2  Symfony SwiftmailerBundle
symfony/symfony                      v3.2.2  The Symfony PHP framework
twig/twig                            v1.31.0 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by chalasr** [comment] 2017-01-25 22:58
> I have updated my Symfony project from version 3.2.0 to version 3.2.2 using "composer update", and it updates the version of Twig to 2.1.0 that requires PHP 7, but composer.json still displays "php": ">=5.5.9" as the PHP requirement.

The `>=5.5.9` allows installation of symfony/symfony with PHP 5.5.9+, PHP 7+ included.

> check installation of Twig 2.1.0 instead of 1.x one

> create new Symfony-3.2 project: symfony new my-project 3.2
in project directory execute composer update or composer update symfony/symfony --with-dependencies
check installation of Twig 2.1.0 instead of 1.x one

There's nothing wrong in having Twig 2.1.0 installed since it is the last stable version 
Problem is that your platform should not allow installing it because of its PHP 7+ requirement
.
Also I'm not able to reproduce your issue too, running `composer update` from `symfony/symfony:3.2.1` on a PHP 5.6 environment (debian) properly installs Twig 1.31.0.
It looks like composer consider your platform is on PHP7+.

**Comment by xabbuh** [comment] 2017-01-26 07:39
It looks like you ran `composer upgrade` on a machine that had PHP 7 while you are using PHP 5 on your server. If you have different PHP versions during development than on your server, you can use Composer's `config.platform.php` option to tell Composer which PHP version to consider.

**Comment by chalasr** [comment] 2017-01-26 14:10
Or maybe the config.platform.php is set to 7.0?

Btw, see https://getcomposer.org/doc/06-config.md#platform for the documentation of this config option.

**Comment by javiereguiluz** [comment] 2017-01-26 14:11
To bring in some more details:

* When we build the packages used by the Symfony Installer, we always respect the minimum PHP version advertised by Symfony. So, if you do `symfony new my_project` ... you'll get Symfony 3.2 and it will work with PHP 5.5.
* However, just after creating the project, we remove a Composer config called `config.platform.php`
* We do that so when you do a `composer update` you'll get the best package versions for your machine (either PHP 5 or PHP 7 depending on your PHP)
* As explained by @xabbuh, the problem is when you update in a machine with different PHP versions.

The solution is to add this `config.platform.php` config in your `composer.json` and set the absolute minimum PHP version where the project should work. Here is an example: https://github.com/symfony/symfony-standard/blob/3.2/composer.json#L46-L50

**Comment by stof** [comment] 2017-01-26 14:14
Closing this because there is no issue in Symfony, but a misunderstanding of how composer works, and solutions have been given above

**Closed by stof** 2017-01-26 14:14 UTC

**Comment by mariopr25** [comment] 2017-01-29 20:22
> It looks like you ran composer upgrade on a machine that had PHP 7 while you are using PHP 5 on your server

Yes, That was the problem. I Have PHP 5 and PHP 7 in my machine and PHP5 in server. In my machine Apache is using PHP5 but cli uses PHP7.
