### ISSUE TITLE
Inconsistent behavior of FileUpload in Form

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#27524] opened 2018-06-06 14:14 UTC
To upload a file, [the documentation shows this code](https://symfony.com/doc/current/controller/upload_file.html):

```php
class ProductController extends Controller
{
    /**
     * @Route("/product/new", name="app_product_new")
     */
    public function new(Request $request)
    {
        ...
        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $product->getBrochure();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('brochures_directory'),
                $fileName
            );

            ...
        }

        ...
    }
}
```

But this code has an inconsistent behaviour.

In fact, if someone tries to upload a file that exceeds the limit for the file size set in the `php.ini`, an error is thrown:

> FileNotFoundException: The file "" does not exist

**This error is thrown by `$file->guessExtension()`.**

Nor the `Form` nor any other parts of the code, intercept the fact that the file is too big until we try to move it.

And so, in the end, we came up with an error that has nothing to do with the real problem (the file is too big).

This forced me to debug for about 40 minutes with a lot of try-and-fail until I understood the problem was a too big file.

And I was lucky: I'm refactoring some old code that use `UploadedFile::getClientOriginalExtension()`, so I knew I had to try with such method.

**The problem, anyway, is that the `Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser` uses the content of the file to guess the extension, but if the file is too big such content is not available.**

So there is a sort of circular reference:

1. The file is too big and so is not available to PHP;
2. To move the file, we need the guessed extension, but this is not guessable as the file doesn't exist: we get a really generic `FileException` "The file "" does not exist";
3. The only way to get the real `IniSizeFileException` is calling `UploadedFile::move()`
4. But we cannot call `UploadedFile::move()` (and get the real exception) because we first get the generic error caused by the guessing of the exception.

Finally, I don't know if this is a documentation issue or is a tricky bug of the framework: I'm starting writing here to get some feedback and to make you aware of the problem.

**POSSIBLE SOLUTIONS**

1. Suggest using the unsafe `UploadedFile::getClientOriginalExtension()`
2. Find a way to intercept earlier the error (maybe moving the file to the `sys_get_temp_dir()` dir) when calling `UploadedFile::guessExtension()` (maybe only if the "file too big" exception is thrown during guessing)

**MORE PROBLEMS NOT SHOWN IN THE DOCS**

Apart from what I said until now, there is another problem in the docs:

How to handle a "file too big" exception?

As the `Form` component cannot intercept this error (because a call to `move_uploaded_file` is required to get the exception thrown), once it happen, how do we show it to the end user?

The documentation should show a way to manually set the error in the form field, so on successive load of the page it is shown near the upload field.

Cross posted in https://github.com/symfony/symfony-docs/issues/9885

**Comment by xabbuh** [comment] 2018-06-07 08:15
Since we can detect if uploading the file led to an error, we should rather fix the code instead so that the form is not valid in those cases IMO (the `$_FILES` array contains an `error` key for each uploaded file, see http://php.net/manual/en/features.file-upload.errors.php).

**Comment by Aerendir** [comment] 2018-06-07 12:29
@xabbuh , for sure, if the form can be invalidated on those kind of errors it would be the best!

The errors of which you are speaking are also [used in `UploadedFile::move()` method](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L222-L237):

```php
    /**
     * Moves the file to a new location.
     *
     * @param string $directory The destination folder
     * @param string $name      The new file name
     *
     * @return File A File object representing the new file
     *
     * @throws FileException if, for any reason, the file could not have been moved
     */
    public function move($directory, $name = null)
    {
        if ($this->isValid()) {
            if ($this->test) {
                return parent::move($directory, $name);
            }

            $target = $this->getTargetFile($directory, $name);

            set_error_handler(function ($type, $msg) use (&$error) { $error = $msg; });
            $moved = move_uploaded_file($this->getPathname(), $target);
            restore_error_handler();
            if (!$moved) {
                throw new FileException(sprintf('Could not move the file "%s" to "%s" (%s)', $this->getPathname(), $target, strip_tags($error)));
            }

            @chmod($target, 0666 & ~umask());

            return $target;
        }

        switch ($this->error) {
            case UPLOAD_ERR_INI_SIZE:
                throw new IniSizeFileException($this->getErrorMessage());
            case UPLOAD_ERR_FORM_SIZE:
                throw new FormSizeFileException($this->getErrorMessage());
            case UPLOAD_ERR_PARTIAL:
                throw new PartialFileException($this->getErrorMessage());
            case UPLOAD_ERR_NO_FILE:
                throw new NoFileException($this->getErrorMessage());
            case UPLOAD_ERR_CANT_WRITE:
                throw new CannotWriteFileException($this->getErrorMessage());
            case UPLOAD_ERR_NO_TMP_DIR:
                throw new NoTmpDirFileException($this->getErrorMessage());
            case UPLOAD_ERR_EXTENSION:
                throw new ExtensionFileException($this->getErrorMessage());
        }

        throw new FileException($this->getErrorMessage());
    }
```

If it is possible to intercept earlier when using the `UploadedFile` in a form this is way more useful!

Currently I have to use this really messy code:

```php
# MyController.php

...
    public function myAction() {
        if ($form->isSubmitted() && $form->isValid()) {
            // The uploading of the logo throws an error if the file is too big
            // See LogoTrait::uploadLogo()
            try {
                // Some information are alredy set in the Entity by the form handling
                $storeManager->updateStore($domain->getStore());

                $this->getDoctrine()->getManager()->flush();
            } catch (IniSizeFileException $e) {
                $form->get('uploadingLogo')->addError(new FormError('File troppo grande'));

                return $this->render('App/store/store_edit_profile.html.twig', ['form' => $form->createView(), 'store' => $domain->getStore()]);
            }
    ...
    }
...

and this is the code I use to manage the file:

```php
        // Here we are forced to use UploadingLogo::getClientOriginalExtension()
        // See https://github.com/symfony/symfony-docs/issues/9885
        $logoExtTmp      = strtolower($this->getUploadingLogo()->getClientOriginalExtension());
        $logoFileNameTmp = $logoName . '.' . $logoExtTmp;
        $logoPathTmp     = sys_get_temp_dir() . '/' . $logoFileNameTmp;

        // Try to move the uploading logo to the tmp directory (this throws an exception if an error occurs)
        $this->getUploadingLogo()->move(sys_get_temp_dir(), $logoFileNameTmp);
        $logoFile = new File($logoPathTmp);

        // Now we can safely guess the real extension of the file
        $logoFileName = $logoName . '.' . $logoFile->guessExtension();
```

Really verbose and intricate!

**Comment by stof** [comment] 2018-06-07 13:10
I'm quite sure the FileType was checking file errors to report them as form errors in the past. but I was not able to find this logic anymore. So maybe some refactoring lost it.

**Comment by keichinger** [comment] 2018-06-22 08:15
Not sure about the `FileType`, though the `File` assertion does perform such checks: https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Validator/Constraints/FileValidator.php#L53

We were running into the very same issue where the `MimeTypeGuesser` was causing an exception since the file was too big.

**Comment by iflorespaz** [comment] 2018-11-11 04:18
Hello Guys,
I worked in a symfony project with version 4.1.7 and the process to upload files works perfectly,I just did a code example for version 4.1.7, see here.
`            $file = $request->files->get('upload_system')['photo'];
            move_uploaded_file($file->getpathName(), $this->getParameter('kernel.project_dir').'/public/'.$file->getClientOriginalName());`
Take into account that the code shown is only for testing purpose :)

and I tested the same code in symfony v4.2.0-BETA1, see the code:
`            $file = $request->files->get('upload_system')['photo'];
            move_uploaded_file($file->getpathName(), $this->getParameter('kernel.project_dir').'/public/'.$file->getClientOriginalName());`
but now I get a 500 error message: " FileNotFoundException - The file "/private/tmp/phpsfKNSO" does not exist", see screenshot.
<img width="1260" alt="captura de pantalla 2018-11-10 a la s 23 14 18" src="https://user-images.githubusercontent.com/26859617/48309020-70eb4500-e53e-11e8-9c2b-b009e180fc37.png">
I did a lot of tests and honestly I think we have a bug uploading files in 4.2-dev version.
My tests were done on MACOS with php 7.2.11 .

Please help me!

Best regards,
Isaac Flores

**Comment by iflorespaz** [comment] 2018-11-27 03:29
The issue has been fixed in the 4.2.0-RC1 version.
Thanks symfony Team!!!

**Comment by xabbuh** [comment] 2019-04-06 13:45
see #30895

**Closed** 2019-04-06 18:01 UTC
Labels: Bug, Form, Status: Reviewed, ⭐️ EUFOSSA Hackathon

**Comment by laudirbispo** [comment] 2019-05-30 14:59
You can fix this fault until something is done by changing line 77 of the UploadedFile classes, set the second parameter to false! parent :: __ construct ($ path, false);

**Comment by xabbuh** [comment] 2019-05-30 17:53
Changing a file from a third-party package never is a good idea. This issue has been fixed in the linked pull request. If you still think, there is a bug, please open a new issue with some description on how to reproduce it.
