### ISSUE TITLE
Php7.4 - Forms and typed properties

### ISSUE THREAD

**Issue by adpeyre** [symfony/symfony#36350] opened 2020-04-05 12:43 UTC
**Description**  
Take into account uninitialized values in forms as null.

Currently, if I define a non nullable property (because it can't be null), forms with a new entity don't work because forms want access to an uninitialized attribute.

Of course, I can set my attribute as nullable but for my opininion, it's not a good solution because this property won't be never null excepted when I'm initializing a new entity and in this case, it's a right behaviour to set the property before trying access to it.

What do you think about that ?

**Example**  
``` php
class Article {
     * @ORM\ManyToOne(targetEntity="App\Entity\Station", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    public Station $station;
}
```

``` php
$article = new Article();
$form = $this->createForm(ArticleType::class, $article);
```

**Comment by HeahDude** [comment] 2020-04-05 14:15
Hello @adpeyre, this is a duplicate of #36051.

We don't want to add support in the component for fragile code that may break outside of its scope.
We improved the exception message instead, and added a proper exception class in master.
See #36311 for an attempt to improve it again.

**Closed** 2020-04-05 14:18 UTC
Labels: Form
