### ISSUE TITLE
StopwatchPeriod::$isFinder

### ISSUE THREAD

**Issue by rgutknec** [symfony/symfony#29347] opened 2018-11-27 09:11 UTC
**Symfony version(s) affected**: 4.1.8

**Description**  
Uncaught ErrorException when trying to output a simple template with encore installed

**How to reproduce**  
```
composer require symfony/maker-bundle symfony/profiler-pack --dev
composer require annotations symfony/twig-bundle
php bin/console make:controller DefaultController
composer require encore
yarn install
yarn encore dev
```

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="home_index")
     */
    public function index()
    {
        return $this->render('default/index.html.twig');
    }
}
```

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
{% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
{% block javascripts %}
        {{ encore_entry_script_tags('app') }}
{% endblock %}
    </body>
</html>
```

```
{% extends 'base.html.twig' %}

{% block body %}
home_index
{% endblock %}

```

**Possible Solution**  

**Additional context**  

```
[Tue Nov 27 10:03:01.327741 2018] [proxy_fcgi:error] [pid 950:tid 140692995176192] [client 127.0.0.1:48736] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: Notice: Undefined property: Symfony\\Component\\Stopwatch\\StopwatchPeriod::$isFinder in /home/u01/workspace/p003/vendor/symfony/debug/DebugClassLoader.php:138\nStack trace:
#0 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')
#1 /home/u01/workspace/p003/vendor/symfony/debug/ExceptionHandler.php(166): spl_autoload_call('Symfony\\\\Compone...')
#2 /home/u01/workspace/p003/vendor/symfony/debug/ExceptionHandler.php(122): Symfony\\Component\\Debug\\ExceptionHandler->sendPhpResponse(Object(ErrorException))
#3 /home/u01/workspace/p003/vendor/symfony/debug/ErrorHandler.php(556): Symfony\\Component\\Debug\\ExceptionHandler->handle(Object(ErrorException))
#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(ErrorException))
#5 {main}
  thrown in /home/u01/workspace/p003/vendor/symfony/debug/DebugClassLoader.php on line 138
```

**Comment by xabbuh** [comment] 2018-11-27 10:00
Can you create a small example application that allows to reproduce your issue?

**Comment by rgutknec** [comment] 2018-11-27 10:04
These are the only command lines and files I edited, otherwise can you tell me how I should transmit it to you, thanks.

**Comment by xabbuh** [comment] 2018-11-27 10:07
You can create a GitHub repository and push everything there. That would help a lot. :)

**Comment by rgutknec** [comment] 2018-11-27 10:12
done at https://github.com/rgutknec/p003.git

**Comment by nicolas-grekas** [comment] 2018-11-27 11:02
@rgutknec thanks for the reproducer, I have the same behavior. This is a complete nonsense, but here is a workaround: #29349. Disabling OPcache also works around the issue BTW.
ping @nikic @jpauli in case you want to have a look.

**Comment by nikic** [comment] 2018-11-27 11:09
Yeah, that looks like an opcache optimization bug. Which PHP version does this affect?

**Comment by rgutknec** [comment] 2018-11-27 11:11
ok, I disabled  OPcache, on Ubuntu by the following :

```
cd /etc/php/7.2/mods-available/
vi opcache.ini
opcache.enable=0
```
Works now with this workaround.
Should I close this issue then, and follow #29349 ?

**Comment by Sozialarchiv** [comment] 2018-11-27 12:37
I can conform the problem on Windows 7/Apache/ PHP 7.2.11

Disabling OPcache seems to work as workaround.

**Comment by nicolas-grekas** [comment] 2018-11-27 12:46
Fixed in #29349. Thanks for the help.

**Closed by nicolas-grekas** 2018-11-27 12:46 UTC
Labels: Bug, Debug, Status: Needs Review, Status: Waiting feedback

**Comment by iammichiel** [comment] 2018-11-29 10:35
This behaviour is confirmed on 7.1.(24 and 16) versions as well. Disabling opcache is a nice workaround for local development. However, deploying to production without opcache is quite crazy. 

Any chance to release a 4.1.9 version with this fix? This currently breaks all projects using the `webprofiler` or `orm` package aliases.

**Comment by OlegZavrazhin** [comment] 2018-12-19 13:44
In case if someone has this issue (it's also available) in docker, might be fixed by the following:

the fast way

`docker exec -it [container-name] bash
vi /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini /*if vim is not available run apt install vim*/
opcache.enable=0
kill -USR2 1`

the more correct way (subjectively) - add the creation of `/usr/local/etc/php/conf.d/opcache-recommended.ini` with `opcache.enable=0` to Dockerfile

**Comment by xabbuh** [comment] 2018-12-19 13:46
I would rather update the Debug component instead of disabling Opcache.
