### ISSUE TITLE
Undefined environment variables cause composer symfony-cmd scripts to crash

### ISSUE THREAD

**Issue by davethegr8** [symfony/symfony#26573] opened 2018-03-16 20:38 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I _think_ this is a symfony bug, but I'm not totally sure exactly where the root cause is. I know it's _somewhere_ in the ecosystem, but I can't definitively say where.

I discovered that having undefined environment variables in the twig package config will cause the symfony `clear:cache` command to fail out. And I suspect that this would be the cause for other packages and commands.

This script, which only adds one environment variable, can reproduce the issue.

```
set -x

composer create-project symfony/website-skeleton my-project
cd my-project

echo "" >> config/packages/twig.yaml
echo "    globals:" >> config/packages/twig.yaml
echo "        will_crash: '%env(WILL_CRASH)%'" >> config/packages/twig.yaml

composer update
```

The final output of composer is this:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In EnvVarProcessor.php line 76:
!!                                                 
!!    Environment variable not found: "WILL_CRASH".  
!!                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!
```

Why is this important? Not all environment variables are defined all the time, especially in CI/CD systems. Variables used to build a system are different from ones used to run the system and vice versa. There should be enough flexibility so that having differences does not create blocking issues.

**Comment by iltar** [comment] 2018-03-17 10:27
If you're not 100% sure if it will be assigned at a given time, define a default value:

```yaml
parameters:
    env(WILL_CRASH): ~
```

I'm not sure if your issue is an actual bug, but this is how you fix your issue.

**Comment by blackandred** [comment] 2018-03-28 10:53
I think that it is a very bad idea to not validate the env variables.
I would even vaildate the .env if there are variables from .env.dist just to cancel the deployment to production system in case that eg. mail account details are not filled up, it's better to see it on deployment stage, not on running stage

**Comment by xabbuh** [comment] 2018-03-29 08:27
I don't see what we need to do here. If your code (or the code of your vendor libraries) requires the environment variables to be defined, it seems logical to me that the code fails. If the code still executes without them having valid values, defining default values as explained by @iltar is the way to go. I am closing here but please feel free to comment if you do not agree.

**Closed by xabbuh** 2018-03-29 08:27 UTC
Labels: Bug, Status: Needs Review

**Comment by davethegr8** [comment] 2018-03-29 19:17
I definitely disagree with notabug/wontfix because this has a severe side effect, with little/no documentation about how/why it happens, and the error thrown does not clearly identify where it came from (only where the error was thrown) or how to fix the problem.

Ideally undefined environment variables wouldn't cause issues, since in practical usage they work as empty strings. (example: `echo $UNDEFINED` would print an empty line from the shell, so the assumption is it'll be handled gracefully.)

But I can also understand why that behavior wouldn't be desired (fail fast and make problems obvious) but it'd still be nice if the error thrown was more descriptive of the actual problem. (example: `Environment variable not found: "WILL_CRASH" defined in config/packages/twig.yaml line 15`)

But the method @iltar outlined is also fine, and at minimum I'd hope this issue can serve as documentation on how to work through this problem for whomever comes next (so they don't have to read through all the source like me heh).

**Comment by iltar** [comment] 2018-03-30 06:18
I think that clearing up the error would be a good thing either way, would you be willing to make a PR for that? Otherwise you could make an issue to improve the error message (unless @xabbuh wants to re-open this instead).

**Comment by nesl247** [comment] 2018-09-13 19:57
I agree with @davethegr8 that undefined environment variables should not break anything, as the default value should be an empty string, or the default of the type when processed `%env(float:SOME_ENV)%` would be `0.0` IMO as a default value.

While it is nice to fail fast, the issue is an annoyance during docker image building. In order to have the cache be built in the image, I need to have environment variables. These variables will 100% change when the image is deployed, as we use a single image for every stage of QA (local, development, staging, production).

I've currently resorted to copying `.env.dist` to `.env`, build the cache, and then remove `.env` when I'm building the cache in docker. This is an ugly workaround though considering the nature of environment variables as previously explained.

**Comment by rvitaliy** [comment] 2020-05-22 15:48
are there any evolution on this problem?
it would be handy to be able to tell `bin/console cache: warmup` to ignore the errors generated by EnvVarProcessor.php. As @nesl247 says we only need to generate the cache during the build of the image, the variables will be injected later in the container.

**Comment by blackandred** [comment] 2020-05-22 18:55
In docker I always provide default values in Dockerfile. So those are visible as "to configure" when deploying on production and on build stage the Dockerfile is not failing.

**Comment by aiesoftware** [comment] 2020-06-13 11:01
I overcame this issue by setting an initial value to be used at build time. At runtime Symfony will get the actual value from the environment:

```
parameters:
  env(MY_VAR): 'dummy-build-time-value-overridden-at-runtime'

services:
  AppBundle\Foo:
    class: AppBundle\Foo
    arguments:
      - '%env(MY_VAR)%'
```

To quote the Symfony docs:

_To avoid undefined variable errors, you can define default values for these variables using the syntax env(VARIABLE_NAME): VARIABLE_VALUE_

**Comment by rvitaliy** [comment] 2020-06-15 13:54
@aiesoftware 
I dislike this solution because i want that my production container throw error if one of my env parameter is not setted properly.
So during build i want that symfony container ignore env values validation but on production env parameter MUST be setted propery.

for now my solution is to provide fake & syntax valid (int/string/etc..) env parameter during the build.
it's suboptimal but ok...

**Comment by math3usmartins** [comment] 2021-09-10 05:40
I think `cache:warmup --ignore-missing-env-vars` would help at least in some cases. I don't like long names either, but explicitness is good in this case.

**use case: build**

```
cache:warmup --ignore-missing-env-vars
```

p.s. no need to print any warnings in this case.

**use  case: deployment**

```
cache:warmup 
```

in this case it would be great to actually fail the warmup if a given env var was not found. the app is expected to be broken anyway. so it's great that the framework can help with preventing us from deploying a broken app.

p.s. if a given env var can be simply null/empty, then it can simply have a default value, like:

```yaml
parameters:
    env(MYVAR): ~
```
