### ISSUE TITLE
[WebProfiler] Sidebar hover bug on small window

### ISSUE THREAD

**Issue by norkunas** [symfony/symfony#18405] opened 2016-04-01 12:59 UTC
Browser Chrome 49.0.2623.110
OS Windows
SF 2.8

![image](https://cloud.githubusercontent.com/assets/2722872/14206901/288178de-f81f-11e5-90d6-2958038e47aa.png)

**Comment by javiereguiluz** [comment] 2016-04-01 13:26
I can't reproduce it:

![webprofiler_responsive](https://cloud.githubusercontent.com/assets/73419/14208120/0ee1de60-f81e-11e5-88c0-9a4bcf7a16a9.gif)

The sidebar menu should collapse automatically on small screens. This feature was implemented by @hason in #15818.

**Comment by norkunas** [comment] 2016-04-01 13:56
@javiereguiluz you didn't hover on sidebar

**Comment by norkunas** [comment] 2016-04-01 14:00
Also looking at your gif my eye caught this
![image](https://cloud.githubusercontent.com/assets/2722872/14209076/1ebfd690-f82b-11e5-8aa6-8f4b0674404c.png)
So if you hover on the sidebar i think you'll see what i see

**Comment by javiereguiluz** [comment] 2016-04-01 14:11
@norkunas I'm sorry. You are right. This should be fixed in #18407.

**Closed** 2016-04-01 15:18 UTC
Labels: Bug, Status: Reviewed, WebProfilerBundle
