### ISSUE TITLE
[Cache] Weird out of memory error where cache file is missing

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#32521] opened 2019-07-12 13:45 UTC
**Symfony version(s) affected**: 3.4+

**Description**  
Weird out of memory error where cache file is missing

**How to reproduce**  
Not sure, see below.

**Additional context**  
```
mmap() failed: [12] Cannot allocate memory
[PHP Warning:  Uncaught ErrorException: include(/home/circleci/api-platform/core/tests/Fixtures/app/var/cache/test/pools/xPMxMSz2th/C/R/iI7euN4OxW-zn9IcjAug): failed to open stream: No such file or directory in /home/circleci/api-platform/core/vendor/symfony/cache/Traits/PhpFilesTrait.php:114
Stack trace:
#0 /home/circleci/api-platform/core/vendor/symfony/cache/Traits/PhpFilesTrait.php(114): Symfony\Component\Cache\Adapter\PhpFilesAdapter::Symfony\Component\Cache\Adapter\{closure}(2, 'include(/home/c...', '/home/circleci/...', 114, Array)
#1 /home/circleci/api-platform/core/vendor/symfony/cache/Traits/PhpFilesTrait.php(114): include()
#2 /home/circleci/api-platform/core/vendor/symfony/cache/Traits/AbstractAdapterTrait.php(51): Symfony\Component\Cache\Adapter\PhpFilesAdapter->doFetch(Array)
#3 /home/circleci/api-platform/core/vendor/symfony/cache/Adapter/TraceableAdapter.php(77): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem('DoctrineNamespa...')
#4 /home/circleci/api-platform/core/vendor/symfony/cache/DoctrinePro in /home/circleci/api-platform/core/vendor/symfony/cache/Traits/PhpFilesTrait.php on line 114]
[PHP Fatal error:  Out of memory (allocated 55050240) (tried to allocate 5664790229566204359 bytes) in /home/circleci/api-platform/core/vendor/symfony/cache/Traits/PhpFilesTrait.php on line 114]
Exited with code 255
```

https://circleci.com/gh/api-platform/core/14655?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://github.com/symfony/symfony/blob/v4.3.2/src/Symfony/Component/Cache/Traits/PhpFilesTrait.php#L114

**Comment by teohhanhui** [comment] 2019-07-12 14:05
I SSH'ed in and this is what I got:

    $ ~/api-platform/core$ ls -la tests/Fixtures/app/var/cache/test/pools/xPMxMSz2th
    total 8
    drwxr-xr-x  2 circleci circleci 4096 Jul 12 13:55 .
    drwxr-xr-x 24 circleci circleci 4096 Jul 12 13:55 ..

Weird...

**Comment by teohhanhui** [comment] 2019-07-12 14:22
Sorry, I'm not sure what's going on here. It seems like the system has run out of memory indeed.

**Comment by teohhanhui** [comment] 2019-07-12 14:27
If I do this at https://github.com/symfony/symfony/blob/v4.3.2/src/Symfony/Component/Cache/Traits/PhpFilesTrait.php#L114:

```php
if ('/home/circleci/api-platform/core/tests/Fixtures/app/var/cache/test/pools/xPMxMSz2th/C/R/iI7euN4OxW-zn9IcjAug' === $file) { var_dump(memory_get_usage()); die; }
```

I get:

> int(66591136)

So it's the `include` call that causes the OOM.

**Comment by dunglas** [comment] 2019-07-12 14:44
Same issue here:

https://travis-ci.org/api-platform/demo/builds/556975954?utm_source=github_status&utm_medium=notification
https://github.com/api-platform/demo/pull/127

**Comment by teohhanhui** [comment] 2019-07-12 15:03
I'm only able to reproduce with PHP 7.3.7, but not 7.3.6 (both from official Docker `php` image, `alpine` variant).

**Comment by nicolas-grekas** [comment] 2019-07-15 08:27
The stack trace is strange: L51 in AbstractAdapterTrait is wrapped in a try/catch, how can the ErrorException be uncaught? If confirmed, this looks a lot like a PHP bug. Can you reduce this to a PHP script and open a PHP bug report? Or maybe look at existing reports?

**Comment by dushyant-cimpress** [comment] 2019-07-15 08:58
@nicolas, is there any work-around for this at the moment?

**Comment by xabbuh** [comment] 2019-07-15 09:11
@dushyant-cimpress according to https://github.com/symfony/symfony/issues/32521#issuecomment-510920639 downgrading PHP is a workaround at the moment.

**Comment by dushyant-cimpress** [comment] 2019-07-15 09:15
@xabb, thank you. is this issue also with 7.2.20?

**Comment by xabbuh** [comment] 2019-07-15 09:22
I don't know. If you are on 7.2.20 and are affected by this, I'd try to go back to 7.2.19 if that changes anything.

**Comment by dushyant-cimpress** [comment] 2019-07-15 10:44
@teohhanhui, any workaround for this issue other than downgrading PHP ?

**Comment by kiler129** [comment] 2019-07-15 22:11
There's a bug in PHP 7.3.0 up to 7.3.7:
- https://bugs.php.net/bug.php?id=78280
- https://bugs.php.net/bug.php?id=78010

This ticket looks like a presentation of that bug. Switching minors may change the location of that bug. Try disabling gc and see if that helps.

**Comment by biji** [comment] 2019-07-18 06:48
I think this is related:

https://github.com/symfony/symfony/issues/28197

**Comment by teohhanhui** [comment] 2019-07-18 11:23
The workaround is to use `pcov` for computing code coverage, instead of `phpdbg`. It's better and faster anyway!

**Comment by teohhanhui** [comment] 2019-07-18 11:26
@nicolas-grekas

> The stack trace is strange: L51 in AbstractAdapterTrait is wrapped in a try/catch, how can the ErrorException be uncaught? If confirmed, this looks a lot like a PHP bug.

Yeah, because PHP died. Haha...

**Comment by nicolas-grekas** [comment] 2019-07-18 13:36
OK, closing then thanks for investigating.

**Closed by nicolas-grekas** 2019-07-18 13:36 UTC
Labels: Bug, Cache, Status: Needs Review
