### ISSUE TITLE
Deserialize from JSON : wrong attribute type

### ISSUE THREAD

**Issue by Bankalstep** [symfony/symfony#32167] opened 2019-06-25 10:28 UTC
**Symfony version(s) affected**:  4.2.9

**Description**  

When deserializing a JSON object, I got the following error : 

"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"The type of the \"period\" attribute for class \"App\\Entity\\Invoice\" must be one of \"int\" (\"string\" given).","class":"Symfony\\Component\\Serializer\\Exception\\NotNormalizableValueException","trace" 

[...]

(I can post the whole thing if needed)

My guess is that the deserializer should find back the type of the attributes as it usually does.

**A bit of code**

I have my entity which looks like this (this is only a sample of it, with the concerned attribute) : 

```
class Invoice
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var int|null
     *
     * @ORM\Column(name="period", type="integer", nullable=true)
     */
    private $period;

...

}
```

What Im doing to populate my database : 

```
// My JSON string from the array I just constructed
$result= GuzzleHttp\json_encode($result);

// Going into the deserializer
$invoiceDetail = $serializer->deserialize($result, 'App\Entity\Invoice', 'json');
```

I have pretty much the same thing going for another entity where everything works (the entity may differ but the process is exactly the same).

I found a workaround, where I need to adjust the type of my attribute to 'string' instead of 'integer', in the doctrine annotation, like so : 
    ` * @ORM\Column(name="period", type="**string**", nullable=true)`

If I do that, the JSON is getting deserialized, and my entity gets inserted in my database as it should (where the 'period' column is of **integer** type)

**Additional context**  

To make this easier to understand I'm attaching a screenshot of what is supposed to go on :

First the array that I will be feeding to the deserializer, then the json encoded array, and then (if I'm using my workaround), what I should have when deserialized (notice 'period' attribute is an int there) :

![image](https://user-images.githubusercontent.com/22743397/60090942-ca0d8f00-9743-11e9-96a8-a9ec983f3f98.png)

Sorry if Im unclear, can't do much more at the moment.
Thanks

**Comment by andreyserdjuk** [comment] 2019-07-10 21:46
Serializer's (especially AbstractObjectNormalizer::denormalize()) behavior is right because it does not know that this string is actually integer could be. It does not do coercive type conversion (like PHP). 
1. Context option 
```php
\Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::DISABLE_TYPE_ENFORCEMENT 
```
allows to set string value to integer field of object but its a bit dirty approach.
2. Also you can add "string" annotation but as a result you will have raw string in property:
```php
    /**
     * @var int|string|null
     */
    private $period;
```
3. Also you can implement custom denormalizer converts string to int. Just override denormalize() method.

**Comment by nicolas-grekas** [comment] 2019-07-30 16:48
Closing as @andreyserdjuk gave the answer I think.

**Closed by nicolas-grekas** 2019-07-30 16:48 UTC
Labels: Bug, Serializer, Status: Needs Review

**Comment by Guervyl** [comment] 2022-04-29 10:15
I just got this error during tests. The problem is `\Symfony\Bundle\FrameworkBundle\Test\WebTestCase` is sendeing integer as string and there is no way to send integer. How should I make sure the field accept string without custom normalizer in the entity. I tried everything and I just can't figure out how does it know the field should be an integer. I changed the column to `string`, `@var string`, `@Assert\Type(type='string')` and it still not working.
