### ISSUE TITLE
Duplicated validation in FOSUser Bundle

### ISSUE THREAD

**Issue by mikecpl** [symfony/symfony#20449] opened 2016-11-08 15:59 UTC
I tried to add a new custom validation to the password property of my User object in two different ways: in validation.xml and assert. In both cases the property was validated by the FOSUser's validation and my custom validation, so I got two error messages if it is common in the two validations (e.g.: the default minLength=2, in my case the minLength=8).

I am using Symfony 2.7 and the newest FOSUser.

**Comment by stof** [comment] 2016-11-08 16:11
All FOSUserBundle validation rules are in custom groups. If you don't want them to run, you should change the validation groups being run, so that they don't run (but be careful that this will not let you disable a single rule, as we don't use separate groups for each rule).
If you don't disable the validation groups of the bundle, your own constraint will indeed be applied together with the bundle constraint, not in replacement of the bundle constraints

**Comment by javiereguiluz** [comment] 2016-11-08 16:18
@mikecpl I'm afraid I need to close this issue. First because it seems related to FOSUserBundle rather than Symfony, so it should probably be reported in https://github.com/FriendsOfSymfony/FOSUserBundle

Second, because in the GitHub repository we only deal with feature requests and bugs. For this kind of questions about using Symfony when we don't know yet if they are an actual error, it's better to use our support channels: https://symfony.com/support  This prevents issues from piling up in this repository. I hope you understand it. Thanks!

**Comment by fagyikaa** [comment] 2016-11-09 09:47
@javiereguiluz Well actually this question is a symfgony one, in general related to inheritance.  I think it would be logical that if we use the same assert on a field of the child class then it overwrites the old one and not validates for both. If somebody want to change the properties of an existing assert on a field, e.g. set the minlength to 8 instead of 2 and change the message it would make sense that the child class's assert comes into play and not both (only in the case the two asserts are the same). Why does symfony check the length according to the original value defined in the parent bundle too if we explicitly say that we want it to be something else?

**Comment by javiereguiluz** [comment] 2016-11-09 09:53
@fagyikaa OK, I'm reopening your issue then. In order to confirm the bug and solve it we need you to please make it reproducible. These would be the steps to follow:

1. Create an empty Symfony project or fork the Symfony Standard Edition (https://github.com/symfony/symfony-standard)
2. Add the minimal code needed to reproduce your issue
3. Push your code somewhere (a branch in the fork, a new repo, etc.) and send us the GitHub URL so we can fetch it and reproduce the bug.

Thank you!

**Comment by mikecpl** [comment] 2016-11-09 12:56
@javiereguiluz I have reproduced the issue here: https://github.com/mikecpl/symfony-standard.

I have added my custom validation in xml (UserBundle/Resources/config/validation.xml) and if you fill the registration form (on '/register' url) with 1 character long password, you can see two error messages.
If I define the plainPassword property in my User class and put the Length assert on it, then the result is same.

**Comment by xabbuh** [comment] 2016-11-11 08:45
The point is that if we change the current behaviour, we may break existing applications. People out there may rely on the fact that constraints added in child classes will always be added and do not replace constraints configured for the base class. This will probably not work well with the built-in constraints, but as one can add arbitrary custom constraints one can probably come up with some kind of constraints where it might make sense to simply add them in child classes.

So I suggest to close here to not break BC. You can still solve your issue by adding your constraint to another validation group and duplicate the ones provided by FOSUserBundle that you want to keep and then only validate the constraints in your newly created group.

@symfony/deciders What do you think?

**Comment by stof** [comment] 2016-11-11 10:24
IMO, we should not change things. Forcing to drop inherited constraints when you add constraint in the child class would be a big WTF IMO (and people will probably not even see that some of the validation stops running after they add a constraint in the child class).

**Comment by HeahDude** [comment] 2016-11-11 14:23
Yeah we should not break BC here, validation groups have always been the way to go.

Note that default the group `Default` is an alias for the class and inherited one, if you only want the current class constraint to be run, explicit de the group name using the target short class name:
```php
class SomeParent { ... }

class SomeChild extends SomeParent { ... }

class SomeChildType extends AbstractType
{
    // ...
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => SomeChild::class,
                // By default, this will validate both "SomeParent" and "SomeChild" groups:
                'validation_groups' => ['Default'], //  groups
                // You can override the groups this will validate only "SomeChild" group:
                'validation_groups' => ['SomeChild'],
                // ...
```

**Comment by fabpot** [comment] 2016-11-11 15:39
Consensus is clear here so I'm closing this issue.

**Closed by fabpot** 2016-11-11 15:39 UTC
Labels: Bug, Status: Needs Review, Unconfirmed, Validator

**Comment by sergiobelya** [comment] 2019-03-27 17:19
See also https://github.com/symfony/symfony/issues/3224
