### ISSUE TITLE
Issue with validator service on unique entities in collections

### ISSUE THREAD

**Issue by liamsorsby** [symfony/symfony#17884] opened 2016-02-22 14:07 UTC
We seem to be having an issue with the validator service when using collections and the validator to check for unique entities.

The validator will correctly find any issues before persisting the entity to the doctrine manager.

The validator seems to check the data in the current database but doesn't check the data that is going to be saved.

For instance if title is a unique entity and in my collection I am adding two new collections to the database both with the title abc it will not throw an error with the validator but will try to add them both causing an internal server error.

We are adding clientside checks but wasn't sure if this was a bug in the validator service.

**Comment by iltar** [comment] 2016-02-22 14:57
You could put a constraint on your collection which specifies that the titles have to be unique. This is not a bug in the unique entity constraint afaik as it only checks the database.

**Comment by liamsorsby** [comment] 2016-02-22 15:04
@iltar The constraint is on the collection. However as the data is duplicated. I imagine that the database is only checked a single time for performance reasons so on the second insert the database will fail.
When the entity is persisted it wouldn't invalidate as you said it only checks the database. So on the second insert the insert will fail but it would have already passed on the constraint.
Would it not be feasable to do a check on the unique entity data through the constraint prior to inserting as well as checking the database?

**Comment by xabbuh** [comment] 2016-02-22 18:49
The constraint doesn't know that there is another object containing the same data somewhere in your object graph. And as all validation happens before any of your data is written to the database it cannot catch this kind of error, but you have to implement that yourself as a separate constraint on the collection.

**Comment by liamsorsby** [comment] 2016-02-22 22:33
@xabbuh should this not be implemented into the unique constraint to check data to be persisted aswel.

To me it wouldn't seem to make sense that the unique constraint would fail to check all data with itself and the database before being persisted as there would be nothing benificial that could be gained by not adding the check to the constraint.

Would it be feasible to create a PR on the unique constraint to add this feature in? Or would this not be generic enough to resolve any specific problem?

**Comment by xabbuh** [comment] 2016-02-27 08:03
@liamsorsby I don't see how you would implement it in the unique constraint. But if you have an idea, feel free to submit a pull request.

**Comment by liamsorsby** [comment] 2016-02-28 09:27
@xabbuh I may be wrong but isn't the unique constraint to be checked against the data in the form of an array. If so then couldn't I just do an array search on that data? To be honest I've not actually had a look at the unique constraint to be honest. But I will certainly give it a go.

**Comment by xabbuh** [comment] 2016-02-28 09:35
@liamsorsby The unique entity constraint checks that there is no existing entity in your database that already contains the same value(s) for a particular property (or a set of properties).

**Comment by iltar** [comment] 2016-02-28 10:10
What you probably want is something like this:

```php
class FooData
{
   /**
    * @Assert\Unique(fields={"username"})
    * @var MyUser[]
    */
    private $myUsers = [];
}
```

As opposing to the unique entity constraint -which checks just that one field in the database- you want a constraint that checks all the fields in all items of the collection for that constraint.

**Comment by liamsorsby** [comment] 2016-02-28 10:31
@iltar would this be instead of the unique entity check Or alongside the unique entity check? Is the unique entity check designed so it doesn't check for unique data in the array collection before persisting?

**Comment by iltar** [comment] 2016-02-28 10:35
@liamsorsby in theory you can make the unique constraint do this (but requires a PR)

**Comment by poolerMF** [comment] 2016-07-21 15:35
my solution for checking same item in collection:

**CollectionSameItem.php**

    /**
     * @Annotation
     * @Target({"CLASS", "ANNOTATION"})
     */
    class CollectionSameItem extends Constraint
    {
        const ERROR_PATH_FORM = 'form';
        const ERROR_PATH_FIELD = 'field';
    
        public $message = 'Item already exists in collection "%collectionName%" .'; // %variable%
        public $variable;               // property access for specific variable
        public $toString;               // property access of item
        public $collection;             // property access for collection
        public $errorPath = 'form';     // "form" or "field" or "form,field"
    
        public function __construct($options = null)
        {
            parent::__construct($options);
    
            if (null === $this->collection) {
                throw new MissingOptionsException(sprintf('Option collection" must be given for constraint %s', __CLASS__));
            }
    
            if (!$this->toString) {
                $this->toString = $this->variable;
            }
        }
    
        /**
         * {@inheritdoc}
         */
        public function getTargets()
        {
            return self::CLASS_CONSTRAINT;
        }
    }


**CollectionSameItemValidator.php**

    class CollectionSameItemValidator extends ConstraintValidator
    {
    
        public function validate($value, Constraint $constraint)
        {
            if (null === $value) {
                return;
            }
    
            $accessor = new PropertyAccessor();
            $value = $accessor->getValue($value, $constraint->collection);
    
            if (!is_array($value) && !$value instanceof \Countable) {
                throw new UnexpectedTypeException($value, 'array or \Countable');
            }
    
            if (count($value)) {
                $repeatedItems = [];
                $existedItems = [];
    
                $itemIndex = 0;
                foreach ($value as $item) {
                    if ($constraint->variable) {
                        $variable = $accessor->getValue($item, $constraint->variable);
                    } else {
                        $variable = $item;
                    }
                    if (in_array($variable, $existedItems)) {
                        if (!in_array($variable, $repeatedItems)) {
                            $repeatedItems[] = [
                                'itemIndex' => $itemIndex,
                                'item' => $item
                            ];
                        }
                    } else {
                        $existedItems[] = $variable;
                    }
                    $itemIndex++;
                }
    
                foreach ($repeatedItems as $item) {
                    $value = null;
                    if($constraint->toString) {
                        $value = $accessor->getValue($item['item'], $constraint->toString);
                    }
    
                    foreach (array_unique(array_map('trim', explode(',', $constraint->errorPath))) as $path) {
                        $this->addViolation(trim($path), $constraint, $item, $value);
                    }
                }
            }
        }
    
        private function addViolation($path, $constraint, $row, $value = null)
        {
            $atPath = null;
    
            if ($path == CollectionSameItem::ERROR_PATH_FIELD && $constraint->errorForm) {
                $atPath = sprintf('%s[%d].%s', $constraint->collection, $row['itemIndex'], $constraint->variable);
            }
    
            $violation = $this->context->buildViolation($constraint->message)
                ->setParameter('%collectionName%', $constraint->collection)
                ->atPath($atPath);
    
            if($value) {
                $violation->setParameter('%variable%', $value);
            }
    
            $violation->addViolation();
        }
    }


Example of usage:
Entity *Project* has more users (Project->getUsers())
Entity *User* has variables firstName, secondName .. method getFullName()

example1:

    DemoBundle\Entity\Project:
        constraints:
            - DemoBundle\Validator\CollectionSameItem:
                variable: firstName
                collection: users
                toString: getFullName
                errorPath: "form,field"
                message: User "%variable%" already exist in project

message -> User "Firstname Secondname" already exist in project


example2:

    DemoBundle\Entity\Project:
        constraints:
            - DemoBundle\Validator\CollectionSameItem:
                collection: users
                errorPath: "field"
                message: This user already exist this project

message -> This user already exist this project

**Comment by Seb33300** [comment] 2017-03-17 09:33
Looking for something like this too.

**Comment by ostrolucky** [comment] 2017-12-17 01:34
Duplicity of https://github.com/symfony/symfony/issues/9888. Linked issue contains proposal for Unique constraint.

**Comment by fabpot** [comment] 2017-12-18 16:19
Closing as a duplicate then.

**Closed by fabpot** 2017-12-18 16:19 UTC
Labels: Validator
