### ISSUE TITLE
phpunit bridge not compatible with phpunit 6

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#21555] opened 2017-02-07 16:02 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

The symfony phpunit bridge does not work with phpunit version 6 which is namespaced. So for example 
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bootstrap.php#L16 will just be skipped.

**Comment by julienfalque** [comment] 2017-02-07 16:15
Duplicate of #21125

**Closed** 2017-02-07 16:28 UTC
