### ISSUE TITLE
Symfony 3.4 +One of listeners must count and slice given target

### ISSUE THREAD

**Issue by parthiv2585** [symfony/symfony#25375] opened 2017-12-07 13:09 UTC
I have Upgrade 2.8 to 3.4 and i have get below error.

![screenshot-2017-12-7 one of listeners must count and slice given target 500 internal server error 1](https://user-images.githubusercontent.com/3072019/33716899-e214c722-db7d-11e7-83ad-d42482c5a9be.png)

My Composer.json

```
"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.4.*",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "incenteev/composer-parameter-handler": "^2.0",
        "propel/propel": "2.0.*@dev",
        "propel/propel-bundle": "~3.0@dev",
        "knplabs/knp-paginator-bundle": "^2.6",        
        "symfony/security-acl": "^3.0",
        "twig/twig": "^1.0||^2.0"
    },
```

Please help me to fixed issue.

**Comment by xabbuh** [comment] 2017-12-07 13:22
I am sorry, but I am closing your issue as the problem is not related to Symfony, but to the KNP Paginator component (which is used by the KnpPaginatorBundle). This component is not part of the Symfony core and they have [their own repository](https://github.com/KnpLabs/knp-components).

**Closed by xabbuh** 2017-12-07 13:22 UTC
