### ISSUE TITLE
Problem with the local SSL certificate

### ISSUE THREAD

**Issue by PittacusW** [symfony/symfony#39206] opened 2020-11-27 21:52 UTC
I'm using symfony/http-client v4.4. I'm trying to send a request to a website that requires authentication with a .pem file. In order to do so, I include the 'local_cert' param when creating the instance of http-client like this: 

HttpClient::create(['local_cert' => $this->certificate]);

This works perfectly well on my local server, but when I try it on the production server, I get an Exception: "Problem with the local SSL certificate". The .pem file being used is the same in development and production, and the php can read the file in the production server.

**Comment by nicolas-grekas** [comment] 2020-11-28 12:18
I suppose the certificate chain is different on the server.
I'm closing because this is a configuration issue, not a bug in HttpClient.
Please use eg Slack or stackoverflow to find a solution.

**Closed as completed by nicolas-grekas** 2020-11-28 12:18 UTC
Labels: Bug, Status: Needs Review, HttpClient
