### ISSUE TITLE
An uploaded file must be an array or an instance of UploadedFile

### ISSUE THREAD

**Issue by n-for-all** [symfony/symfony#25202] opened 2017-11-29 07:59 UTC
https://github.com/symfony/symfony/blob/1cada24000ccfc76033bd216f07fb8cc5382bf7a/src/Symfony/Component/HttpFoundation/FileBag.php#L49

"An uploaded file must be an array or an instance of UploadedFile"

Where is the check for null?, if the $value is null, why don't you ignore the request, currently the forms doesn't work if you don't submit a file.

and why is this approach of throwing an exception on every error?, if the $value is not an array and not an uploadeded file, whats the harm of ignoring the value and continue?

**Comment by sroze** [comment] 2017-11-29 08:34
> if the $value is not an array and not an uploadeded file, whats the harm of ignoring the value and continue?

Skipping it would introduce a lot of WTFs for developers in case of typo or misusage. Throwing an exception ensures that we respect this convention and that the bag [knows how to convert the objects](https://github.com/symfony/symfony/blob/1cada24000ccfc76033bd216f07fb8cc5382bf7a/src/Symfony/Component/HttpFoundation/FileBag.php#L72-L97). 

If you use `set` with a `null` value, that's probably that you want to remove the file? Then you can use the `remove` method.

**Comment by n-for-all** [comment] 2017-11-29 08:44
Actually not skipping it would introduce a lot of WTFs for developers, a return statement should replace the exception there, currently a simple form can't submit with an empty file field.

If you use set with a null value, that's probably that you want to remove the file? Then you can use the remove method.

i am not setting anything in the request, i am submitting a simple html form where files are not required, unless i listen to KernelRequest event, check the files and remove the empty files, the request fails with the exception above.

**Comment by xabbuh** [comment] 2017-11-29 11:02
Could you create a small example project that allows to reproduce your issue? To me this looks weird as no one reported this behaviour and I am convinced that there are a lot of projects out there where file upload forms are not required. Maybe you hit some weird edge case.

**Comment by Simperfit** [comment] 2017-12-11 07:01
Could you do the following, so we could get a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by n-for-all** [comment] 2017-12-11 08:12
Here you go:
http://symfony-icu090792703.codeanyapp.com/

And this is the controller:

https://codeanywhere.com/editor/#P8Ap4SrXMntU8YEAnj82dRIVn47iGGxrwOY8tP3GlchfiBdITq1ZgBty1BCCU51k

just click submit on the form and you will see the error.

**Comment by Simperfit** [comment] 2017-12-11 08:33
Thanks we will look at it!

**Comment by xabbuh** [comment] 2017-12-11 08:35
@n-for-all Can we see the code anywhere too?

**Comment by xabbuh** [comment] 2017-12-11 08:41
By the way, your example application uses Symfony 3.0.4 which dropped support long time ago. Are you able to reproduce the issue with Symfony 3.3 or higher?

**Comment by n-for-all** [comment] 2017-12-11 10:06
https://codeanywhere.com/editor/#P8Ap4SrXMntU8YEAnj82dRIVn47iGGxrwOY8tP3GlchfiBdITq1ZgBty1BCCU51k

i didn't modify or edit any of symfony's settings or code, i only added the html form which contains the file input in (test.html.twig) and the above controller.

The container is a new container on codeanywhere that installs with symfony framework, not sure why codeanywhere installs version 3.0.4 and not the latest, though the issue exists also on the latest symfony.

**Comment by xabbuh** [comment] 2017-12-11 11:11
I am sorry, but I do not see any code there as codeanywhere asked me to create an account.

**Comment by n-for-all** [comment] 2017-12-11 11:17
yes well, they require to create an account to share, though creating an account is free, if you don't want to create an account, below is a screenshot of the controller:

![image](https://user-images.githubusercontent.com/171367/33828644-6328004e-de86-11e7-8a87-88a705da11b6.png)

**Comment by xabbuh** [comment] 2017-12-11 12:39
If you want to perform a subrequest, you will need to call the `Request::duplicate()` method instead of manually trying to create the request. You can take a look at the `forward()` method from the `ControllerTrait` to get some inspiration. I am closing here as this is not a bug.

**Closed by xabbuh** 2017-12-11 12:39 UTC
Labels: Bug, Form, HttpFoundation, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by n-for-all** [comment] 2017-12-11 13:15
duplicating the request without params throws internal server error, i just changed the code to the below:

![image](https://user-images.githubusercontent.com/171367/33832438-98f283de-de95-11e7-8d3a-18b07fc31494.png)

if i use $request->duplicate(null, null, null, null, $request->files->all(), null), it throws the same error.

"An uploaded file must be an array or an instance of UploadedFile"

how do you duplicate a request?

**Comment by xabbuh** [comment] 2017-12-11 13:41
I am sorry, but we do not use GitHub for support. I suggest you ask for me help on one of the [support channels](https://symfony.com/support).

**Comment by n-for-all** [comment] 2017-12-11 13:46
i am not asking for support, i just did what you asked me to do which doesn't work, so instead of ignoring the issue and rushing to close it, Please look into it and propose a solution if you don't want to solve it.

Thanks.

**Comment by xabbuh** [comment] 2017-12-11 14:05
I cannot tell you more than that you using `Request::duplicate()` is the way to go. Without more information I guess that if calling this method leads to an internal server error in your code, there must be something wrong in how you call the method. However, that's just guessing without seeing the real underlying error (you would have to look into the logs for it). And if that error proves to be a fault of Symfony's code, we will of course reopen here and try hard to fix it in core. But I really doubt that.
