### ISSUE TITLE
[RFC] Introduce Query component

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony#46802] opened 2022-06-29 12:32 UTC
### Description

C#'s LINQ allows to query your collections in an SQL way. This is something that is native to the C# language. If you never heard about LINQ in C#, [here is an article explaining it a bit](https://docs.microsoft.com/en-us/dotnet/csharp/linq/write-linq-queries). To summarize, you can see this as "Doctrine for in-memory collections".

Having something like C#'s LINQ would be great for PHP developers. Indeed, there is nothing in the PHP ecosystem that offers you to do this kind of thing.

Having to go through different object collections and object trees can become long and tedious at times. But also very verbose. Numerous calls to SPL methods to manipulate arrays, callback passes, etc. can be very time-consuming and hard to understand at first sight.

In addition, some cases can be complicated to manage:

- Operations done only in some cases on collections can lead to complex and numerous `if`/`else`
- Filtering a collection of objects by comparing the value of a property of an object with the value of a property of one of its ancestors
- To have an object-oriented approach to object collections management
- Error management sometimes blurred and "old-fashioned" with calls to SPL methods
- Simply, to have a pleasant and fluid developer experience in the management of object trees.

All these issues have been at the center of thoughts during the development of this proposal. By offering a query-builder approach to query our collections, this allows great flexibility. The internal use of the ExpressionLanguage allows a great power to write `where` clauses, but also a strong extensibility by having the possibility to register custom functions globally for `where` clauses. People who are comfortable with SQL syntax, DQL and Doctrine's QueryBuilder will be familiar with this component, allowing a quick use immediately.

Offering this library within Symfony could be a real plus for the whole community. As there is no real equivalent in PHP, this component would be a real breakthrough for us by offering a robust and modern approach to manipulating objects in memory. This approach is also simplistic and minimal for optimal performance.

### What about collections without objects and mixed collection?

After a few discussion with @Jean-Beru, we thought it was not necessary to handle mixed collections and scalar collections. The complexity brought into the component code to handle these cases was really growing. The management of scalar collections will be much more efficient with the classical SPL methods and the use of the Query component does not bring a real improvement of the DX. For collections of nested arrays, it is the same. At a time when DTO and VO are becoming more and more common, managing "objects" in the form of associative arrays brings too much complexity to the component code compared to the real added value.

The management of mixed collections was quickly discarded. Most operations and modifiers would have a too complex and undefined behavior in these cases. Here is an example: how should the `max` operation (returning the max value of a given field of objects in a collection) behave if the elements of the collection can be scalars, objects, etc.? There is no ideal answer, hence the limitation of the component to collections of objects.

### Feasibility & features

The fully working library is available [at this address](https://github.com/alexandre-daubois/symfony-query) if you need to have a better idea of what it looks like. Also, you can play with it by cloning the repository and editing `TestCommand`. This library is already well-tested and each modifier and operation is covered.

All available features are described in the README of the repository. If it is something that sounds good for you, I'll take care to create the pull-request to introduce this as a Symfony component :+1: 

### Example

```php
use Symfony\Component\Query\Query;
use Symfony\Component\Query\QueryOrder;

$cities = [
    new City('Lyon', [
        new Person([
            new Child('Hubert', age: 30),
            new Child('Aleksandr', age: 18),
            new Child('Alexandre', age: 26),
            new Child('Alex', age: 25),
        ], height: 181),
        new Person([
            new Child('Fabien', age: 23),
            new Child('Nicolas', age: 8),
        ], height: 176),
        new Person([
            new Child('Alexis', age: 33),
            new Child('Pierre', age: 5),
        ], height: 185)
    ], minimalAge: 21),
    new City('Paris', [
        new Person([
            new Child('Will', age: 33),
            new Child('Alix', age: 32),
            new Child('Alan', age: 45),
        ], height: 185)
    ], minimalAge: 45)
];

// Register the function globally for all queries
Query::registerWhereFunction(ExpressionFunction::fromPhp('strtoupper'));

$query = (new Query())
    ->from($cities, 'city')
    ->where('strtoupper(city.name) contains "LYON"')
    ->selectMany('persons', 'person')
        ->where('person.height > 180')
        ->selectMany('children', 'child')
            ->where('child.age > city.minimalAge');

if (true === $shuffle) {
    $query->orderBy(QueryOrder::Shuffle);
}

$names = $query->concat(', ', 'name');
// $names = "Hubert, Alex, Alexandre, Alexis"
```

**Comment by stof** [comment] 2022-06-29 12:47
Why using ExpressionLanguage for the where rather than using PHP code ? LINQ is using C# callables (when using the method syntax rather than the declarative syntax, which cannot be reproduced in PHP as the PHP interpreter does not support hooking custom DSLs).

I see several advantages to using PHP code directly:
- you have access to all features of PHP, without the need to register custom expression functions
- you avoid the overhead of parsing expressions
- you avoid the need of managing a global registry of functions (a global state is a pain to manage in the full-stack framework, and makes the component harder to use in libraries that have no control of that global state)
- by using PHP code, you get support for all tooling (static analysers, IDEs, etc...) instead of having to re-develop tooling for that component

**Comment by derrabus** [comment] 2022-06-29 12:56
How would such a component help when working with other Symfony components? Which components could leverage this kind of queries?

**Comment by alexandre-daubois** [comment] 2022-06-29 16:05
@stof definitely. That's a choice I "had" to make at the beginning of the development. At first I found it was better for DX but your arguments definitely convinced me. It will allow to suppress the ExpressionLanguage dependency. That's definitely something I'm able to do now that the lib is stable enough and test-covered.

The RFC example would become something like this:

```php
$query = (new Query())
    ->from($cities, 'city')
    ->where(fn($city) => 'LYON' === strtoupper($city))
    ->selectMany('persons')
        ->where(fn($person) => $person->height > 180)
        ->selectMany('children', 'child')
            ->where(function($child, QueryContextEnvironment $env) {
                return $child->age > $env->get('city')->minimalAge;
            });
```
___

@derrabus More than offering some object-oriented API (like Uid component) for collection management, the first one I think of is use in conjunction with the Serializer component. Deserializing objects from JSON or XML files can sometimes result in collections of hundreds (or even thousands) of objects. The existence and use of Query would make it possible to quickly sort and filter among these results and to clean up these collections.
We could also think of HttpClient. When sending multiple request, this could definitely be used to filter responses based on pretty anything (status code, response content and so on).

**Comment by GromNaN** [comment] 2022-06-30 07:15
Doctrine has the "in-memory collection" to work on arrays, namely [doctrine/collections](https://packagist.org/packages/doctrine/collections) ([doc](https://www.doctrine-project.org/projects/doctrine-collections/en/1.6/index.html)). It might be better to capitalize on the existing component.

**Comment by alexandre-daubois** [comment] 2022-06-30 08:32
@GromNaN I wasn't aware of the existence of this library, thanks for the knowledge! It reinforces the decision not to deal with scalar arrays in Query, I'm sure `doctrine/collections` does that very well :smile:

There are some things that Query offers that `doctrine/collections` doesn't seem to offer from what I've seen in the documentation though. I'm thinking of some core features of Query:

- A SQL-like syntax allowing easy use by developers used to that syntax. They will already be familiar with it
- The ability to go down object trees and reference ancestors in `where` clauses using context, as shown in the example. This kind of operation is widely used in SQL queries, and I could not find an equivalent in the documentation of `doctrine/collections`.
- Being able to perform operations on a given field. It seems tricky to do this with `doctrine/collections` where it is pretty straightforward to get, for instance, the max/min/average value of a given field on a filtered collection of objects.

Being specialized in objects collections is a real plus for me, and will definitely allow us to go further in collections management.
It seems to me that DX is more fluid and meaningful with Query, especially when we come to go down into the different fields of the objects. Although chained calls to `filter` are possible in `doctrine/collections`, the code can quickly become verbose and it can be complex to keep track after each call.

**Comment by fabpot** [comment] 2022-06-30 08:54
From the use cases that were mentioned, I'm wondering why would not be able to filter directly with Doctrine or GraphQL, ... Having "everything" in memory and then filtering seems like something we would want to avoid as much as possible.

It made me think about some other use cases and I think there is one: the finder. The current API is confusing and difficult to use for more advanced queries. Having something like what you propose might be of great help.

**Comment by alexandre-daubois** [comment] 2022-06-30 09:17
@fabpot I agree with you.

I also think there can be many projects that don't necessarily want to use Doctrine or GraphQL internally to manage their collections on sometimes minimalist projects with a minimum of dependencies. This is where the lightness of Query is a real advantage. The code is relatively concise and the only real dependency is PropertyAccess.

I'm thinking **in particular** of CLI applications (and even more of single-command applications) that can be created with the Console component. Used in conjunction with Query, processing large collections locally on the machine can be a real pleasure. The Query component seems to me really adapted to CLI applications and to the use of the Console component. We often encounter commands created for heavy and long tasks (files processing, API calls, deserialization of these calls, etc.), managing many collections of objects.

The same goes for Finder, indeed! Using Query in the internal workings of Finder could be a great idea too, to see how well it can be done.

**Comment by staabm** [comment] 2022-06-30 10:33
in case its helpfull: there is already a LINQ implementation in PHP: https://github.com/TimeToogo/Pinq

maybe it can help for inspiration of implementation detail decisions.

**Comment by alexandre-daubois** [comment] 2022-06-30 10:44
Thank you for sharing this @staabm, looks a lot like `doctrine/collections` and seems also great for arrays manipulation! This is definitely helpful to have this kind of reference for ideas of feature and improvements :+1:

**Comment by Wirone** [comment] 2022-06-30 11:11
But if there's already library* for that, is it actually needed to have it in Symfony ecosystem? 🤔 There was [Matthias' tweet](https://twitter.com/matthiasnoback/status/1540264968419004419) about that few days ago and I feel this RFC fits perfectly into this trend. 

\* I assume @alexandre-daubois did not do proper research before implementing this, because googling "php linq" gives a bunch of results, [Packagist](https://packagist.org/?query=linq) too...

**Comment by alexandre-daubois** [comment] 2022-06-30 11:22
@Wirone that's true there are a lot of libraries out there doing (some kind of) this job. From the few I saw listed by your Packagist link, they seem to be perfect for arrays of scalars and basic operations on object collections.

However, I couldn't find a library doing this job **especially for objects trees** (but I could definitely be wrong!). This is the whole point of Query, which discards scalar and mixed collections in profit of going further on **object collections/trees management**. I gave a few examples about it on my response above on how Query goes further on this side: https://github.com/symfony/symfony/issues/46802#issuecomment-1170927976

Maybe the naming is wrong and it should be named `ObjectQuery`, which would be less ambiguous!

**Comment by lyrixx** [comment] 2022-06-30 12:23
@alexandre-daubois I understood you use this lib in a CLI context, and you use it to process "large collection", but I don't understand how it can really work.

The `source` is stored as an [array](https://github.com/alexandre-daubois/symfony-query/blob/69860d7b20b299daa96e555c4b178f70b53e8cba/src/Query/Query.php#L46). So you need to fetch the data first, and store it in the memory.

Let's say I want to parse a CSV file of 1Gb (it's the use case, isn't?) I have to hydrate all lines into objects, and store all that collection in a array, right? So my script will consume more than 1Gb 😬. That does not scale, and to me, it does not work.

I agree with @fabpot, having "everything" in memory is a bad idea to me.

**If** we accept this RFC, the component must deal with iterators and not an array. Like the internals of the Finder.

---

I have another question, where does come from the `name` in your example:
```php
$names = $query->concat(', ', 'name');
```
I would expect a `child.name`, is it a typo ?

**Comment by alexandre-daubois** [comment] 2022-06-30 12:30
@lyrixx You're right! That's a :+1: for me to deal with iterators instead of arrays. I would definitely do this change!

Regarding your second question, nope, it is not a typo. In fact, `selectMany` makes you go one level lower. The query state **is one level deeper**. Updating the "query state" allows to write your query with clear separate calls (and modify it conditionally for instance), instead of having to do everything in one big call.

So when you call `concat` with `'name'`, the query already knows that you are at the `child` level. The second argument of `concat` is `$field`. The `alias` you pass to `from` and `selectMany` are used in the `where` clause, in order to fetch some ancestors and do assertions with them :slightly_smiling_face:

**Comment by kbond** [comment] 2022-06-30 12:54
This is interesting! I have hacked on my own (I think) similar concept. In my version, the `Query` can be built manually with php but also with a *query factory*. One such *factory* is a `RequestQueryFactory` that builds it based on a Symfony `Request`'s query string (with an *allow list* of allowed filters/sorts). Useful for data tables.

The created Query can be used on an *in-memory* collection or *transformed* into 3rd party query builders (ie a `Finder` instance or Doctrine query builder). This avoids the in-memory problem @fabpot mentioned.

**Comment by Toflar** [comment] 2022-06-30 17:17
Honestly, I think there is already such a language. It's called SQL. And people tend to forget that we have one of the best databases with in-memory support shipped with PHP right away: SQLite.
I didn't do any performance checks or fiddled around with it with e.g. the `Finder` component but I suppose it would be pretty fast searching for things like `WHERE size>:size AND dateCreated>=:date AND name LIKE :name`.

The question is whether inserting etc. is worth it. But maybe one could build a collection around it.
I did a quick test and it would work:

```php
<?php

include_once 'vendor/autoload.php';

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Types;

class SQLiteCollection
{
    private const TABLE = 'collection';

    private Connection $collection;

    public function __construct(private array $columns, private array $data) {
        $this->collection = DriverManager::getConnection(['url' => 'sqlite:///:memory:']);
        $this->createTable();
        foreach ($data as $value) {
            $this->add($value);
        }
    }

    public function getData(): array
    {
        return $this->data;
    }

    private function createTable(): void
    {
        $table = new Table(self::TABLE);
        foreach ($this->columns as $name => $definition) {
            $table->addColumn($name, $definition['type']);
            $table->addIndex([$name]);
        }

        $this->collection->createSchemaManager()->createTable($table);
    }

    private function add(mixed $value): self
    {
        $data = [];
        foreach ($this->columns as $column => $definition) {
            $data[$column] = $definition['extractor']($value);
        }

        $this->collection->insert(self::TABLE, $data);

        return $this;
    }

    public function filter(string $query, array $parameters): self
    {
        $stmt = $this->collection->prepare('SELECT * FROM ' . self::TABLE . ' WHERE ' . $query);

        return new self($this->columns, $stmt->executeQuery($parameters)->fetchAllAssociative());
    }
}

$values = [
    ['name' => 'foobar', 'size' => 300],
    ['name' => 'foobaz', 'size' => 150],
];

$collection = new SQLiteCollection([
        'name' => [
            'type' => Types::STRING,
            'extractor' => function($data) { return $data['name']; },
        ],
        'size' => [
            'type' => Types::INTEGER,
            'extractor' => function($data) { return $data['size']; },
        ],
    ],
    $values
);

$filteredCollection = $collection->filter('size < 200 AND name LIKE :name', ['name' => '%baz']);

var_dump($filteredCollection->getData());
```

To run it, run `composer req doctrine/dbal`.

Of course it's super basic, lacks a ton of logic (e.g. it just returns what's extracted instead of the whole data) but I just wanted to add my thoughts here. What I'm trying to say is that building a tool for that use case sounds great but building your own filter logic while everybody already knows SQL is probably not what we need 🤔

**Comment by fabpot** [comment] 2022-06-30 17:20
@Toflar But again, you need to load everything before doing your SQL. When using Finder, that's not the case. That's exactly what we want to avoid, loading everything **before** filtering.
Anyway, I think I'm :-1: on adding this to Symfony as is.

**Comment by Toflar** [comment] 2022-06-30 17:23
Yes, for the Finder, that's totally true. I was talking about the general logic of having a collection. And I also don't think it belongs to Symfony to be honest. It should be developed as a standalone library. Which means it can still become a component in the future if it proves to be super valuable for the whole Symfony ecoystem.

**Comment by lyrixx** [comment] 2022-06-30 18:05
I agree with @fabpot. That's why I'm closing this RFC.

Thanks for the discussion and the hard work 👍🏼

**Closed as completed by lyrixx** 2022-06-30 18:05 UTC
Labels: RFC
