### ISSUE TITLE
Problem processing a configuration from multiple files

### ISSUE THREAD

**Issue by damijank** [symfony/symfony#25889] opened 2018-01-22 16:04 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.13

There is a problem **processing** (_not_ loading) a configuration with the same root across **multiple** YAML files. Some array indices turn numeric opposed to as defined in the YAML file.

Configuration definition:
```PHP
$treeBuilder = new TreeBuilder();
$rootNode = $treeBuilder->root('work');
$rootNode
    ->children()
        ->arrayNode('entities')
            ->arrayPrototype()
                ->children()
                    ->arrayNode('tasks')
                        ->arrayPrototype()
                            ->children()
                                ->enumNode('type')->values(['auto', 'manual'])
                                    ->isRequired()->cannotBeEmpty()
                                    ->defaultValue('auto')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ->end();
```

If I define for example all configurations in one YAML file, all goes fine:

```YAML
work:
    entities:
        video:
            tasks:
                preview:
                    type: manual
                process:
                    type: auto
        image:
            tasks:
                import:
                    type: auto
                upload:
                    type: manual
        article:
            tasks:
                edit:
                    type: manual
                publish:
                    type: manual
```
But, if I break down configurations across multiple files, only the configuration from the first file is processed correctly. Again, the *read* is okay, the `$configs` param passed to `WorkExtension#load` has everything loaded correctly. Only after **processing**, the "unified" config is faulty like this:

Two YAML config files:

```YAML
# loaded as first file
work:
    entities:
        video:
            tasks:
                preview:
                    type: manual
                process:
                    type: auto
```
```YAML
# loaded second
work:
    entities:
        image:
            tasks:
                import:
                    type: auto
                upload:
                    type: manual
        article:
            tasks:
                edit:
                    type: manual
                publish:
                    type: manual
```

... the input `$configs` is fine:
```

Array (
    [0] => Array (
        [entities] => Array (
            [video] => Array (
                [tasks] => Array (
                    [preview] => Array (
                        [type] => manual )
                    [process] => Array (
                        [type] => auto ) ) )
        )
    )
    [1] => Array (
        [entities] => Array (
            [image] => Array (
                [tasks] => Array (
                    [import] => Array (
                        [type] => auto )
                    [upload] => Array (
                        [type] => manual ) ) )
            [article] => Array (
                [tasks] => Array (
                    [edit] => Array (
                        [type] => manual )
                    [publish] => Array (
                        [type] => manual ) ) )
        )
    )
)
```

but the resulting `$config` looks like this:

```
Array (
    [entities] => Array (
        [video] => Array (
            [tasks] => Array (
                [preview] => Array (
                    [type] => manual )
                [process] => Array (
                    [type] => auto ) ) )
        [0] => Array (
            [tasks] => Array (
                [import] => Array (
                    [type] => auto )
                [upload] => Array (
                    [type] => manual ) ) )
        [1] => Array (
            [tasks] => Array (
                [edit] => Array (
                    [type] => manual )
                [publish] => Array (
                    [type] => manual ) ) )
    )
)
```

If I reverse the load order (by renaming the files accordingly) then the `image` and `article` indices would be fine in the resulting configuration, but the `video` would have turned into index `0`.

I pretty sure I'm not doing anything wrong here.

**Comment by damijank** [comment] 2018-02-13 16:31
Does this need any further clarification or is it just at the lower end of priority? I could try to make a PR...

**Comment by xabbuh** [comment] 2018-02-14 09:35
@damijank a PR would be welcome :)

**Comment by stof** [comment] 2018-02-14 11:20
if you want a prototyped node to behave like a map rather than like a list, you need to call `useAttributeAsKey(...)` on this node in your Configuration class. This call has 2 effects:

- it tells the configuration processor that merging multiple configs must be done using the algorithm for maps (matching keys), not for lists (appending elements)
- it allows defining which attribute will contain the key in XML (as XML cannot create a map natively, as opposed to YAML or PHP)

The fact that keys are preserved for list nodes when merging is not needed is something that I consider as a bug since years (but very hard to change without breaking BC), as it means that mistakes in the definition of the Configuration class will be discovered only when trying to merge multiple configs.

Note that for prototyped nodes having a map behavior, you will also generally want to use `normalizeKeys(false)` to keep keys exactly the same than in the input instead of normalizing dashes to underscores (which is something we want for normal nodes to have better support for YAML and XML, but which we often don't expect for maps)

**Comment by nicolas-grekas** [comment] 2018-04-03 11:38
Closing as this seems to be the expected behavior.

**Closed by nicolas-grekas** 2018-04-03 11:38 UTC
Labels: Config, Status: Needs Review
