### ISSUE TITLE
Config checker doesn`t say to fix permissions in var/sessions

### ISSUE THREAD

**Issue by Lisennk** [symfony/symfony#19632] opened 2016-08-16 14:01 UTC
I'm using latest version of Symfony and after i installed the framework, i visit config.php page and saw, that i don't have correct permissions on `var/logs` and `var/cache`. After i executed:
```
sudo chmod -R 777 logs
sudo chmod -R 777 cache
```
Symfony config checker was OK, but site was still broken. Then i executed this command:
```
 sudo chmod -R 777 sessions
```
And everything started to work.

So, i think, symfony config checker must check the `sessions` dir permissions too, not only `logs` and `cache`.

PS: sorry for poor English, i working on it.

**Comment by ro0NL** [comment] 2016-08-16 14:10
Good catch. However, having the `var/sessions` directory is optional, it depends on how your setup is [configured](https://github.com/symfony/symfony-standard/blob/05bca699ef631d03d4b114b4366ad0c180b55ecb/app/config/config.yml#L30).

I think this is a documentation issue, as `config.php` doesnt know the path, it can by any or none maybe. This is different for the logs+cache directories, they are there by design.

> site was still broken

Did you get a clear exception at least on what went wrong?

**Comment by jameshalsall** [comment] 2016-08-16 14:34
Another problem here would be detecting the web user, as the permissions need to be set for both the CLI user and the web user. You can detect the web user automatically I guess, but it would have to work from both the CLI and the web requirements checker.

**Comment by ro0NL** [comment] 2016-08-16 14:40
There's a separate tool for that; `bin/symfony_requirements` which executes the same checks.

Agree on you, for checking the requirements as documented;

> One important Symfony requirement is that the var directory must be writable both by the web server and the command line user.

**Comment by javiereguiluz** [comment] 2016-08-29 07:07
@Lisennk I agree that this should be checked better. However, this should be fixed in the "Symfony Standard" repository instead of the Symfony one. Thankfully @ro0NL opened an issue in that repository (https://github.com/symfony/symfony-standard/issues/987) so I'm closing this issue then. Thanks!

**Closed by javiereguiluz** 2016-08-29 07:07 UTC
Labels: Bug, Status: Needs Review
