### ISSUE TITLE
Choice function in SymfonyStyle class 

### ISSUE THREAD

**Issue by RonanSauvage** [symfony/symfony#24250] opened 2017-09-19 08:22 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

Hello,

I'm not sure this is really a bug but the console running is surprising. 

The context is, i propose to my users to select one value from array to backup database. So, I've one array like this : [ '2017-08-08-17-15-06-name', '2017-08-07-17-15-01-name', '2017-08-08-17-15-10-name', '2017-08-08-17-15-14-name']

When I use "choice" function from SymfonyStyle class (http://symfony.com/blog/new-in-symfony-2-8-console-style-guide) (http://api.symfony.com/3.3/Symfony/Component/Console/Style/SymfonyStyle.html#method_choice), I get this output : 

`[0] 2017-08-08-17-15-06-name
[1] 2017-08-07-17-15-01-name
[2] 2017-08-06-17-15-10-name
[3] 2017-08-05-17-15-14-name`

That OK. 

If my user press '1', the selected value is 2017-08-07-17-15-01-name => Good. 

But, if my user press '2', the selected value is 2017-08-08-17-15-06-name 

I've seen the array_flip (line 238 from SymfonyStyle class) but i'm not sure this is the problem. 

Of course in my case, this is a big problem. 

I've tried to reproduce this in virgin context. With  : 

> $values = array ('1112', '15412', '6541244', '15888', '225451', '355425');
$choiceqQuestion = new ChoiceQuestion("Quel script voulez-vous exécuter ou dans quel répertoire souhaitez-vous vous rendre ?", $values);
$chx = $io->askQuestion($choiceqQuestion);
var_dump($chx)

The result is : 

> Quel script voulez-vous exécuter ou dans quel répertoire souhaitez-vous vous rendre ?:
  [0] 1112
  [1] 15412
  [2] 6541244
  [3] 15888
  [4] 225451
  [5] 355425

 > 2
225451
 
>string(6) "225451"

This running makes me think of this function autocomplete the input to select output. 

Thanks

**Comment by xabbuh** [comment] 2017-09-20 09:59
Thanks for reporting this issue. However, since we already have one ticket for this bug I am closing this one as a duplicate of #21789.

**Closed by xabbuh** 2017-09-20 09:59 UTC
Labels: Bug, Console, Status: Needs Review
