### ISSUE TITLE
Process->isSuccessFul() is true with php (null) errors

### ISSUE THREAD

**Issue by robbeman** [symfony/symfony#21892] opened 2017-03-06 11:25 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.2

When executing a command which throws a null error the isSuccessFul() method of Symfony\Component\Process\Process returns true.

For example, when executing the following command:
```php
class FailingCronCommand extends ContainerAwareCommand
{

  protected function configure()
  {
    $this->setName('command:fail');
  }

  protected function execute(InputInterface $input, OutputInterface $output)
  {
    $testNull = null;
    // throw new \Exception('FAIL');
    if ($testNull->getName() === null) {
      // never gets here because $testNull is null and trying getName() throws an error
    }
  }
}
```
using the following code:
```php
/**
 * $console contains the full path to bin/console
 * @var Symfony\Component\Process\Process $process
 */
$process = new Process('php ' .self::$console. ' command:fail');
$process->run();
$process->isSuccessful(); // returns true
$process->getExitCode(); // returns 0 (OK)
$process->getErrorOutput();
/**
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getName() on null
**/
```

When throwing a custom exception in `command:fail` the process I get the following output:
```php
$process->isSuccessful(); // returns false
$process->getExitCode(); // returns 1 (general error)
```

I also tried setting the "suppress_errors" option to false, but that did not seem to make any difference.

**Comment by stof** [comment] 2017-03-06 11:37
the Process component is not responsible for this. The issue is the console component returning a success exit code when catching a fatal error.

**Comment by stof** [comment] 2017-03-06 11:37
Closing as duplicate of https://github.com/symfony/symfony/issues/20775

**Closed by stof** 2017-03-06 11:37 UTC
Labels: Bug, Console, Status: Needs Review
