### ISSUE TITLE
Mime email attachment breaks for http/https file

### ISSUE THREAD

**Issue by deguif** [symfony/symfony#38064] opened 2020-09-04 15:34 UTC
**Symfony version(s) affected**: 4.4.11

**Description**  
Since version 4.4.11 a http/https file path can't be used anymore as attachement to a mime email.
Here is the commit that introduced this breaking: #36304

**Possible Solution**  
Revert #36304

**Comment by fabpot** [comment] 2020-09-07 05:28
duplicate of #38047

**Closed by fabpot** 2020-09-07 05:28 UTC
Labels: Bug, Status: Needs Review
