### ISSUE TITLE
Get Entity from request

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#27789] opened 2018-07-01 10:47 UTC
**Symfony version(s) affected**: 3.4.11

**Description**  
Get Entity from request

**How to reproduce**  
```
    public function paymentsAction(User $user)
    {
        $payments = $this->request->get('user');
        dump($payments);
     
        return $this->redirectToRoute('users');
    }
```
Dump context:
```
User {#754 ▼
  -id: "2"
  -email: ""
  -balance: "0.00"
  -role: "user"
```

**Comment by iltar** [comment] 2018-07-01 18:52
Heya, what are you actually reporting? Because this is intended behavior.

**Comment by allfreelancers** [comment] 2018-07-01 19:19
@iltar parameter $user must be isolated from the request parameters

**Comment by iltar** [comment] 2018-07-01 19:33
The `$user` parameter is in the request attributes: `$request->attributes->get('user')`. The method you use is a "look everywhere" method, it will check post, get and attributes. If you want to only get the query parameters, use `$request->query->get('user')`. There are several more properties you can access: 

https://github.com/symfony/http-foundation/blob/d85b832168512c2c11236ceebe7c04e3f1d4eb37/Request.php#L69-L116

**Comment by allfreelancers** [comment] 2018-07-02 05:36
Post parameters dont pass in ``` $request->query``` method

**Comment by iltar** [comment] 2018-07-02 07:19
That's correct. For the full documentation, please refer to: https://symfony.com/doc/current/introduction/http_fundamentals.html

If you have any questions about Symfony, feel free to join us at [slack](https://symfony.com/slack-invite) (or another community channel: https://symfony.com/community)

**Comment by javiereguiluz** [comment] 2018-07-02 09:06
@allfreelancers POST params are in `$request->request`, GET params are in `$request->query`, etc. You can find more information in the URLs given by @iltar. And we can of course help you more in Slack or any other support channel. So, let's close this for now. Thanks!

**Closed by javiereguiluz** 2018-07-02 09:06 UTC
