### ISSUE TITLE
update 3.2->3.3 bc break: decoration of validator.validator_factory service is not working

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#24222] opened 2017-09-15 15:07 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.9

I do have a decorator service over `validator.validator_factory`, as described in [documentation](https://symfony.com/doc/current/service_container/service_decoration.html). It is not working for now, because:

1. `\Symfony\Component\DependencyInjection\Compiler\DecoratorServicePass` is removing original service, renaming it to `my_service_name.inner` and set alias from `my_service_name` to `validator.validator_factory`.

2. After that `\Symfony\Component\Validator\DependencyInjection\AddConstraintValidatorsPass` is invoked, and tries to locate original service `validator.validator_factory` which can not be found anymore.

As a result, validator factory built with wrong dependencies.

**Comment by xabbuh** [comment] 2017-09-15 15:25
Can you confirm that the change from #24223 applied on the compiler pass in your code base solves the issue?

**Comment by Strate** [comment] 2017-09-18 08:58
@xabbuh thank you for participating, but, unfortunatelly, that fix does not help.

Changing `getDefinition` to `findDefinition` forces `AddConstraintValidatorsPass` to find _decorator_ service, not a _decorated_ service. As a result, compiler pass replaces argument on a decorator (custom class, which expects to original service as a first argument), not on original service.

**Comment by stof** [comment] 2017-09-18 10:11
The issue is that the AddConstraintValidatorPass is registered as `TYPE_BEFORE_REMOVING`, which runs after the decoration.

Btw, this can also cause other bugs, because it also runs after optimizations while it is adding new links in the graph, which may forbid some optimizations already applied.
@fabpot you are the one moving it later in https://github.com/symfony/symfony/pull/20116. Why was it done ?

**Comment by Strate** [comment] 2017-09-18 13:13
@stof I am also ofter register my passes as `TYPE_BEFORE_REMOVING`, because I am ofter experience an issue, when service tries to collect other services before they appears in container.

For example, I have own "autowire" pass, which registers new services in `TYPE_BEFORE_OPTIMIZATION` stage, and, depends on bundles order, collecting by tags pass runs before "autowiring" pass.

So, maybe we could have `TYPE_COLLECT_TAGS` stage?

**Comment by Strate** [comment] 2017-09-21 21:07
So, currently I solved the issue by writing custom CompilerPass, which performs decoration on `TYPE_BEFORE_REMOVING` stage (my bundle registered after FrameworkBundle, so it helps). Btw, issue still exists.

**Comment by stof** [comment] 2017-09-26 12:43
@Strate if you add new references after the optimizations, you may break your container entirely due to optimizations being wrong.

What you should do is register your "autowire" pass creating new services with a priority higher than 0, so that it runs at the beginning of TYPE_BEFORE_OPTIMIZATION stage.

**Comment by Strate** [comment] 2017-09-26 14:34
@stof default \Symfony\Component\DependencyInjection\Compiler\AutowirePass is registered in TYPE_OPTIMIZE stage, is it okay?

Btw, I think we need to document it.

**Comment by xabbuh** [comment] 2017-10-11 11:27
@fabpot Can you answer @stof's question from https://github.com/symfony/symfony/issues/24222#issuecomment-330178067? :)

**Comment by fabpot** [comment] 2017-10-11 13:47
@xabbuh @stof I don't remember, sorry.

**Closed** 2019-02-07 08:55 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review, Validator
