### ISSUE TITLE
Debug TraceEventDispatcher missing event and listener information

### ISSUE THREAD

**Issue by dspiegel** [symfony/symfony#20208] opened 2016-10-11 22:13 UTC
Some where between Merge to 2.8 and 3.1, someone made changes to TraceEventDispatcher.php file. The sprintf command was removed and replaced with _{event}_ and _{listener}_ in message. Like they are some how going to magically change.

**Previous (3.0.9)**
   ```
  *FILE: ./symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php
 267   :                    $this->logger->debug(sprintf('Notified event "%s" to listener "%s".', $eventName, $info['pretty']));
```

**Current (3.1.5)**
```
FILE: ./symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php
 267   :                    $this->logger->debug('Notified event "{event}" to listener "{listener}".', array('event' => $eventName, 'listener' => $info['pretty']));
```

**OUTPUT 3.0.9**: 
`Notified event "kernel.request" to listener "Dst\AuthBundle\EventListener\RequestListener::onKernelRequest".`

**OUTPUT 3.1.5**:
`Notified event "{event}" to listener "{listener}". `

**Comment by javiereguiluz** [comment] 2016-10-12 06:34
@dspiegel at first this change looks idiotic ... but the reasoning is: this allows to group similar log messages that only differ in some variable values. If this were an error message, in the server you'd see just 1 message `Notified event "{event}" to listener "{listener}".` and then 300 different pairs of variables ... instead of 300 similar error messages.

In any case, because of some internal Symfony details, this should be fixed in another repository. I opened an issue about this a few days ago: https://github.com/symfony/symfony-standard/issues/981  That's why I'm going to close this issue as a duplicate.

---

Lastly, in my opinion the problem is that Symfony (as any other framework) generates log files optimized for machines instead of humans. But in the `dev` environment you probably want more readable log files. That's why I published a few weeks ago [this project](https://github.com/EasyCorp/easy-log-handler) to make Symfony logs human-readable.

**Closed by javiereguiluz** 2016-10-12 06:34 UTC
