### ISSUE TITLE
EntityManager Service Auto Wiring

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#17850] opened 2016-02-19 10:37 UTC
Hi,

I am trying to use the new [auto wiring feature](http://symfony.com/blog/new-in-symfony-2-8-service-auto-wiring) to automatically load the entity manager to my service:

```yaml
my_test_service.test:
      class: MyTestBundle\Service\TestService
      autowire: true
```

```php
use Doctrine\ORM\EntityManager;
class TestService
{
    public function __construct(EntityManager $em)
    {
    }
}
```

Result is:

```
RuntimeException in AutowirePass.php line 231: Unable to autowire argument
of type "Doctrine\ORM\EntityManager" for the service "my_test_service.test".
```

Any idea?

Thanks

Seb

**Comment by Tobion** [comment] 2016-02-19 11:48
You probably want to typehint `EntityManagerInterface`

**Comment by Seb33300** [comment] 2016-02-19 12:33
Same error:

> Unable to autowire argument of type "Doctrine\ORM\EntityManagerInterface" for the service

**Comment by iltar** [comment] 2016-02-19 15:56
You want an entity manager but of which connection? For which Entity? This is nearly impossible to determine if you have more than 1 entity manager.

**Comment by maryo** [comment] 2016-02-19 16:10
Exactly. But I guess it should autowire the default one if there is only one in the application. Otherwise you'd have to specify autowiring_types. But looks it is not possible to specify autowiring types for services you "don't own".

I created an issue for this few days ago
https://github.com/symfony/symfony/issues/17783

What do you think @Tobion ?

**Comment by Seb33300** [comment] 2016-02-19 16:14
Actually, I am passing manually the entity manager service with:
```
my_test_service.test:
      class: MyTestBundle\Service\TestService
      arguments:
          em: "@doctrine.orm.entity_manager"
```

I only want to do that by auto wiring.

**Comment by maryo** [comment] 2016-02-19 16:17
@Seb33300 
So you want to autowire all arguments **EXCEPT** the entity manager? Then you should read this issue at least from this position:

https://github.com/symfony/symfony/issues/17724#issuecomment-183301207

**Comment by Seb33300** [comment] 2016-02-19 16:42
No, I also like to autowire the `@doctrine.orm.entity_manager` service but, if I remove it from the arguments array, I have the error quoted in my first post.

**Comment by maryo** [comment] 2016-02-19 19:22
OK. I see. The named argument confused me since the name is ignored. But I just tested it and it worked fine for both EntityManager and EntityManagerInterface typehints using

```json
{
    "name": "symfony/symfony",
    "version": "v3.0.2",
    "reference": "18c3d4f356931a5b6a4afb0cc679a2c58931c795"
}
```

So you either have more than one entitymanager registered so it cannot guess which one to inject which is not a bug or something strange happened :).

**Comment by Seb33300** [comment] 2016-02-19 20:20
Hmmm... Strange. I will try it on a clean install.
I am on a Symfony 2.8

**Comment by Seb33300** [comment] 2016-02-23 10:24
@maryo can you tell me what you add in your services.yml to make it works?

I am not able to make it works even on Symfony 3. Maybe I am doing something wrong with typehints.

**Comment by Seb33300** [comment] 2016-02-23 10:54
OK, the problem was that I had multiple multiple Entity Manager defined on the project...
Another developer added it and I was not aware.

Now, I have another problem trying to autowire the `@validator` (`Symfony\Component\Validator\Validator\RecursiveValidator`)

> Unable to autowire argument of type "Symfony\Component\Validator\Context\ExecutionContextFactoryInterface" for the service "autowired.Symfony\Component\Validator\Validator\RecursiveValidator"

**Comment by Tobion** [comment] 2016-02-24 15:28
Closing as entity manager wiring is solved.

**Comment by Seb33300** [comment] 2016-02-29 09:51
Any way to make auto wiring the default entity manager ?
Or to choose the one to be "auto wired" when we have multiple entity managers ?

**Comment by TomasVotruba** [comment] 2016-07-17 12:18
I have same issue with just raw DoctrineBundle installatio, so I suppose single entity manager.

**Comment by TomasVotruba** [comment] 2016-07-17 12:18
Ping @tobion, reopen please

**Comment by maryo** [comment] 2016-07-17 12:36
@TomasVotruba 
It's better to dump your configuration and recheck all the registered services. It does not take so long.
BTW probably you can use this workarround when you need more than one entity manager registered
https://github.com/symfony/symfony/pull/18040#issuecomment-199573489

**Comment by TomasVotruba** [comment] 2016-07-20 13:51
I confirm this work for symfony-standard with:

- Symfony 3.0
- Symfony 3.1

I probably got issue somewhere else.

Can be closed. Thank you.

**Closed** 2016-07-20 17:52 UTC
Labels: DependencyInjection

**Comment by cluis13915** [comment] 2018-11-28 17:51
Similar issue here !!! I got a circular reference for service `doctrine.orm.default_entity_manager`. In a first service (`\AppBundle\Handler\MyService`), I'm injecting `\Doctrine\Common\Persistence\ManagerRegistry`. Then, in another service (which implements `\Doctrine\Common\EventSubscriber`), I'm injecting my `\AppBundle\Handler\MyService`.

So I decided to not inject the `ManagerRegistry`, but the `\Doctrine\ORM\EntityManagerInterface`. This results in apparently an infinite loop, because running `php bin/console` never ends. Checking process manager, `php` is consuming 100% of the processor.

Any idea ?  Thanks and sorry for my bad English.

**Comment by TomasVotruba** [comment] 2018-11-28 18:35
Hi, could you provide full code for your classes? It might be easier to spot it

**Comment by TomasVotruba** [comment] 2018-11-30 17:40
> Currently, to solve my problem, I am doing in AnalisisEventoSubscriber what CompanyProvider do for me (get company record from DB using company_code parameter).

Well, that's the only solution :+1: . Without that you can't avoid circular dependency.

You shouldn't inject anything that uses Doctrine to Doctrine EventSubscribers.

**Comment by cluis13915** [comment] 2018-11-30 17:49
Haha thanks !!!  I'll keep it in mind from now on.
