### ISSUE TITLE
[WebProfilerBundle] Issue after upgrade to 4.0.5

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#26382] opened 2018-03-02 17:52 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 4.0.5

I have a [typeahead.js](https://twitter.github.io/typeahead.js/) on a page. After upgrading to 4.0.5 it stops working. Looks like problem in this lines: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L524-L529

**Comment by nicolas-grekas** [comment] 2018-03-02 17:53
Confirmed, see #26364 (duplicate of #26380 also)

**Closed by nicolas-grekas** 2018-03-02 17:53 UTC

**Comment by stof** [comment] 2018-03-02 18:10
@nicolas-grekas if this breaks the JS of the *app* (and not only the display of the toolbar), we should really not wait 1 month before releasing a fix for it.
