### ISSUE TITLE
Add support for Gmail sending through the API

### ISSUE THREAD

**Issue by mchojrin** [symfony/symfony#46033] opened 2022-04-13 15:14 UTC
Just read that Gmail is going to drop support for "less secure applications" as of May 2022 and noticed the current Mailer implementation doesn't allow sending through Gmail using a different mechanism than that of SMTP.

I just coded a little script to try out how to do this following [this tutorial](https://rapidapi.com/blog/gmail-api-php/) but I'm not sure how I'd go about integrating it into Symfony mailer.

**Comment by wehostadm** [comment] 2022-04-16 09:39
@mchojrin Totally agree with this feature, I will have the same problem when Gmail will drop the "less secure applications" option.

Hope that another solution will be integrated in this bundle before May 2022.

Thanks :)

**Comment by stof** [comment] 2022-04-16 10:59
The issue is not really about using the API instead of using SMTP. Gmail is not dropping SMTP in May 2022.

The actual need is to implement the OAuth2 authentication. This has been discussed in https://github.com/symfony/symfony/issues/35528 but nobody has started the work on it yet AFAIK.

**Comment by fabpot** [comment] 2022-04-16 13:51
Closing as a duplicate for #35528

**Closed as completed by fabpot** 2022-04-16 13:51 UTC
Labels: Feature, Mailer
