### ISSUE TITLE
EventDispatcher overwrite priority of EventSubscriber listeners 

### ISSUE THREAD

**Issue by Pheetbag** [symfony/symfony#34149] opened 2019-10-27 23:02 UTC
**Symfony version(s) affected**: 3.4.31

**Description**  
The EventDispatcher component overwrite the priority of the EventSubscriber listeners of a certain event when they are pointing to the same callable. 

For example if you have an 'example.create' event, and you set an array of listeners for that event, with two callables in it, but the method where those callables are pointing is the same, the EventDispatcher component will register both callables but, will take the priority of the first one and use it for the other. Here you can see what is in the getSubscribedEvents() and what the debug:event-dispatcher output:

**ExampleEventSubscriber::getSubscribedEvents() content**

    public static function getSubscribedEvents(): array
    {
        return [
            'example.create' => [
                ['eventCallable', 11],
                ['eventCallable', -5]
            ]
        ];
    }

**php bin/console debug:event-dispatcher output**

```
"example.create" event
----------------------

 ------- --------------------------------------------------------------------- ----------
  Order   Callable                                                              Priority
 ------- --------------------------------------------------------------------- ----------
  #1      AppBundle\EventSubscriber\ExampleEventSubscriber::eventCallable()   11
  #2      AppBundle\EventSubscriber\ExampleEventSubscriber::eventCallable()   11
 ------- --------------------------------------------------------------------- ----------
```

**How to reproduce**  
Create an EventSubscriber, and add at least two listeners to one event, using the multiple callable syntax, point the callables to the same method, and set different priorities for each of them. 

    public static function getSubscribedEvents(): array
    {
        return [
            'example.create' => [
                ['eventCallable', 11],
                ['eventCallable', -5]
            ]
        ];
    }

Use the `php bin/console debug:event-dispatcher` to check the priorities the event dispatcher is taking in count and you will see the problem.

**Comment by dmaicher** [comment] 2019-10-28 14:53
Can confirm that the displayed priority is always the highest one. 

I checked it a bit and I don't see any way of fixing it :cry: 

The issue is within `EventDispatcherInterface::getListenerPriority` that is used by the debug command to print the information. There is no way to distinguish the two registered listeners when we want to retrieve the priority. The callable is the same for both. 

But on the other hand my question: does it make sense to have different priorities for the same callback? The order does not matter since its the same method that is called, right?

**Comment by Pheetbag** [comment] 2019-10-28 15:14
@dmaicher  Yeah! i check that too, and saw that solving the problem will require a major refactor in the dispatcher, but anyway i consider that i should be taken in count for the future (the next major version?).

Regarding your question, in most cases it doesnt matter, but remember that the priority is taken in count for the ordering of all listeners for a certain event (doesnt matter the origin of it) so for example if you want to execute a callback1 in EventSubscriber1 before another callback2 in EventSubscriber2, and then you want to execute again callback1 but after callback2 (maybe some post-update task) then priorities for the same callback is important, because that is what allows you to change the order of the callings regarding other callbacks in other subscribers. 

Im using the "same callback, different priority" for a different subject, using a wrapper around the EventSubscriber to tell symfony "hey! send all callings to this proxy method" and then i take care of calling the real callback inside a try-catch, in such a case the priority is even more important. I implemented a little fix, appending an unique number at the end of each method i return to the EventDispatcher, and then capture all callings with a __call() and redirect them to the real method.

**Comment by Pheetbag** [comment] 2019-10-28 15:39
@dmaicher Now i am starting to question, up to what degree does the EventDispatcher relies on `EventDispatcherInterface::getListenerPriority` for the ordering of callbacks priorities? is it only for debug cases like printing those priorities in the console?

**Comment by dmaicher** [comment] 2019-10-28 15:42
@Pheetbag yes indeed afaik its only used for debug purposes.

See https://github.com/symfony/symfony/compare/3.4...dmaicher:issue-34149?expand=1

The registration is done with correct priorities.

**Comment by nicolas-grekas** [comment] 2019-12-02 10:52
I think this is not common enough to trigger the big refacto that looks required to fix this behavior.
Especially because there is an easy workaround: create two separate methods.
I'm therefore closing, thanks for reporting.

**Closed by nicolas-grekas** 2019-12-02 10:52 UTC
Labels: Bug, EventDispatcher, Status: Needs Review
