### ISSUE TITLE
CurrencyType allows any value

### ISSUE THREAD

**Issue by n-sviridenko** [symfony/symfony#23234] opened 2017-06-20 13:24 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.0

Hello,

The `CurrencyType` isn't working the same way like in symfony 3.1.

In 3.1 `CurrencyType` choises weren't lazy loaded but now it is. There is a problem:

[`Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer`](https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L46):

```php
public function reverseTransform($value)
{
    if (null !== $value && !is_string($value)) {
        throw new TransformationFailedException('Expected a string or null.');
    }

    $choices = $this->choiceList->getChoicesForValues(array((string) $value));

    if (1 !== count($choices)) {
        if (null === $value || '' === $value) {
            return;
        }

        throw new TransformationFailedException(sprintf('The choice "%s" does not exist or is not unique', $value));
    }

    return current($choices);
}
```

`$choices = $this->choiceList->getChoicesForValues(array((string) $value));`

In `3.1` the value of `$choices` equals to `[]` is `$value` isn't present in the list of choices. For example if we use `CurrencyType` and we'll pass 'blablabla' as `$value`, it will return `[]`.

In `3.1` `$this->choiceList` is [`Symfony\Component\Form\ChoiceList\ArrayChoiceList`](https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L138):

```php
public function getChoicesForValues(array $values)
{
    $choices = array();

    foreach ($values as $i => $givenValue) {
        if (array_key_exists($givenValue, $this->choices)) {
            $choices[$i] = $this->choices[$givenValue];
        }
    }

    return $choices;
}
```

`if (array_key_exists($givenValue, $this->choices)) {` checks whether the 'blablabla' is present in the list of currencies.

So the behaviour in `3.1` is fine. But.. Let's take a look on `3.2.0`:

`$this->choiceList` in [`Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L46) is [`Symfony\Component\Form\ChoiceList\LazyChoiceList`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/ChoiceList/LazyChoiceList.php) that calls the following function in [`Symfony\Component\Form\Extension\Core\Type\CurrencyType`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Extension/Core/Type/CurrencyType.php#L78-L92) in this case:

```php
public function loadChoicesForValues(array $values, $value = null)
{
    // Optimize
    if (empty($values)) {
        return array();
    }

    // If no callable is set, values are the same as choices
    if (null === $value) {
        return $values;
    }

    return $this->loadChoiceList($value)->getChoicesForValues($values);
}
```

But `if (null === $value) {` happens because [`Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L46) did his best to prevent this (there is no a second parameter):

remember `$choices = $this->choiceList->getChoicesForValues(array((string) $value));`.

That's all. Is it a normal behaviour? How to deal with it with minimal loses?

Thank you.

**Comment by xabbuh** [comment] 2017-06-20 15:29
I am not sure if I understand your issue. Can you provide a small example that makes it possible to reproduce it?

**Comment by n-sviridenko** [comment] 2017-06-20 15:33
@xabbuh, try the following code:

```php
$form = $this->createForm(CurrencyType::class);
$form->submit('?');

// true
dump($form->isValid());
```

**Comment by n-sviridenko** [comment] 2017-06-22 05:37
@xabbuh is there some news? I just need to understand is it bug or not to fix my business logic.

**Comment by n-sviridenko** [comment] 2017-07-02 14:50
ping @xabbuh

**Comment by xabbuh** [comment] 2017-07-12 17:54
@n-sviridenko Sorry for the delay. What you experience is indeed an issue (see #20916). However, since we already have one issue to keep track of this I am going to close this one as a duplicate of #20916. Thank you for understanding.

**Closed by xabbuh** 2017-07-12 17:54 UTC
Labels: Bug, Form, Status: Needs Review

**Comment by n-sviridenko** [comment] 2017-07-12 17:56
@xabbuh thank you for the feedback
