### ISSUE TITLE
Symfony 3.1.x@rc incompatible with phpunit 5.3.*

### ISSUE THREAD

**Issue by pedroresende** [symfony/symfony#18903] opened 2016-05-28 01:36 UTC
Unable to install Symfony 3.1.x with phpunit 5.3.*

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.3.0 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpunit/phpunit 5.3.1 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpunit/phpunit 5.3.2 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpunit/phpunit 5.3.3 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpunit/phpunit 5.3.4 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpspec/prophecy 1.4.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.3.1 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.4.1 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.5.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.6.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony[v3.1.0-RC1].
    - phpdocumentor/reflection-docblock 2.0.1 conflicts with symfony/symfony[v3.1.0-RC1].
    - phpdocumentor/reflection-docblock 2.0.2 conflicts with symfony/symfony[v3.1.0-RC1].
    - phpdocumentor/reflection-docblock 2.0.3 conflicts with symfony/symfony[v3.1.0-RC1].
    - phpdocumentor/reflection-docblock 2.0.4 conflicts with symfony/symfony[v3.1.0-RC1].
    - Installation request for symfony/symfony 3.1.x@rc -> satisfiable by symfony/symfony[v3.1.0-RC1].
    - Installation request for phpunit/phpunit 5.3.* -> satisfiable by phpunit/phpunit[5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4].
```

**Comment by WouterJ** [comment] 2016-05-28 07:26
You shouldn't require PHPunit as a dev dependency (and you've proofed with this issue again why you shouldn't).

Download the `phpunit.phar` and put it in a directory that's in your `$PATH`.

**Comment by sstok** [comment] 2016-05-28 07:41
This caused by Prophecy https://github.com/phpspec/prophecy/issues/272

**Comment by iltar** [comment] 2016-05-28 10:47
Even though I agree with @WouterJ here, it will prevent a lot of people from updating, we're facing the same issue.

Even when using the phar, the issue will occur when code hits the incompatibility if the tested code is using the phar code (already autoloaded) instead of the production dep.

**Comment by nicolas-grekas** [comment] 2016-05-28 10:54
It's a prophecy issue, not a Symfony one.

**Comment by 1ed** [comment] 2016-05-30 12:52
See https://github.com/symfony/symfony/pull/17531/files#r51572907 ... the conflict is really required?

**Comment by scaytrase** [comment] 2016-05-30 13:23
The problem with symfony (for me) is that my `http-kernel` dependency has upgraded to 3.1 and `framework-bundle` has stuck on 3.0.6 which leads to failing tests due to deprecations

**Comment by dunglas** [comment] 2016-05-31 17:13
See https://github.com/phpspec/prophecy/pull/275.

**Comment by stof** [comment] 2016-05-31 17:17
I'm closing this issue as it is not a Symfony issue. Please subscribe to the Prophecy issue if you want to follow resolution (there is a button in the right column of the github UI to subscribe to an issue)

**Closed by stof** 2016-05-31 17:17 UTC
Labels: Bug, Status: Needs Review
