### ISSUE TITLE
symfony/routing 6.3.5 to 6.4.0 is not BC compatible (for us)

### ISSUE THREAD

**Issue by alcohol** [symfony/symfony#52816] opened 2023-11-30 09:43 UTC
### Symfony version(s) affected

6.4.0

### Description

Updating from 6.3.5 to 6.4.0 is a breaking change for us.

### How to reproduce

Unclear why. I've looked over the changelog and the diff between 6.3.5 and 6.4.0. Unfortunately it seems the biggest change is also the culprit, so this will take some investigating.

Currently we have a lot of controllers that look like:

```php
<?php

use Symfony\Component\Routing\Annotation\Route;

#[Route(name: 'prefix_')]
class Controller
{
    #[Route(path: '/method', name: 'suffix')]
    public function someMethod() {}
}
```

When upgrading from symfony/routing 6.3.5 to 6.4.0 we get the following exception:

```
Symfony\Component\Routing\Exception\RouteNotFoundException:
Target route "prefix_suffix for alias "Controller::someMethod" does not exist.

  at vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php:72
  at Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper->getCompiledAliases()
     (vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php:115)
  at Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper->generateDeclaredRoutes()
     (vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php:98)
  at Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper->dump()
     (vendor/symfony/routing/Router.php:303)
  at Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}(object(ResourceCheckerConfigCache))
     (vendor/symfony/config/ResourceCheckerConfigCacheFactory.php:36)
  at Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache('/srv/var/cache/nl/local/url_generating_routes.php', object(Closure))
     (vendor/symfony/routing/Router.php:299)
  at Symfony\Component\Routing\Router->getGenerator()
     (vendor/symfony/routing/Router.php:221)
  at Symfony\Component\Routing\Router->generate('prefix_suffix', array(), 1)
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:109)
```

### Additional Context

The controller in question extends an `abstract class Controller`, which implements `ServiceSubscriberInterface`.

**Comment by xabbuh** [comment] 2023-11-30 09:50
This looks similar to (or even the same as) #52802.

**Comment by alcohol** [comment] 2023-11-30 09:51
Ah, probably! The routes are i18n routes indeed. And looking at `url_generating_routes.php` they're all indexed using their i18n suffix (they reference their canonical but it is not in that file).

**Comment by derrabus** [comment] 2023-11-30 10:21
Closing as duplicate of #52802 then.

**Closed as not planned by derrabus** 2023-11-30 10:21 UTC
Labels: Bug, Routing, Status: Needs Review

**Comment by alcohol** [comment] 2023-11-30 10:25
Any chance I can test the fix with a 6.x branch? https://github.com/symfony/symfony/commit/ce95b8763a168756e4e050a39ae7ca5258a2bde0 only seems to be in 5.4 right now.

**Comment by derrabus** [comment] 2023-11-30 10:33
I've just merged it up to 6.4.

**Comment by alcohol** [comment] 2023-11-30 11:54
Thanks!

**Comment by alcohol** [comment] 2023-11-30 11:55
Can confirm that fixed it. Cheers
