### ISSUE TITLE
adding UniqueEntity Validation to other Constraints trows error in PHPUnit

### ISSUE THREAD

**Issue by andrejsramko** [symfony/symfony#12931] opened 2014-12-10 09:33 UTC
I use some PHPUnit Validation Test cases for Registration of Users. 

Initialization of the Validator looks like this (see also [this link](https://github.com/symfony/Validator/blob/master/README.md#usage)):

```
$this->validator = Validation::createValidatorBuilder()->enableAnnotationMapping()->getValidator();
$errors = $this->validator->validate($user, array(0 => 'registration'));
```

as soon as I add UniqueEntity constraint to my User entity
```@UniqueEntity(fields={"usernameCanonical"}, errorPath="username", message="fos_user.username.already_used", groups={"registration", "profile"})```

I get following error when I run the test:
> Fatal error: Class 'doctrine.orm.validator.unique' not found in mypath\symfony\src\Symfony\Component\Validator\ConstraintValidatorFactory.php on line 33

Maybe I could initialize the Validator separately somehow with
```
$this->validator = $kernel->getContainer()->get('doctrine.orm.validator.unique');
```
but then I would have to test the entity constraint after constraint, and couldn't do it in one line with 
```
$errors = $this->validator->validate($user, array(0 => 'registration'));
```

is this a bug or am I doing wrong something?

**Comment by fabpot** [comment] 2015-02-10 13:59
Closing as there is no feedback from the reporter.

**Closed by fabpot** 2015-02-10 13:59 UTC
Labels: Doctrine, Validator

**Comment by gnat42** [comment] 2015-05-26 16:47
So I have the same issue. I've created a repository with a form type test that fails as described here. you can find it at https://www.github.com/gnat42/unique-validator running phpunit -c app will result in an error.
```
PHP Fatal error:  Class 'doctrine.orm.validator.unique' not found in /home/gnat/Projects/Web/uniqueValidator/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorFactory.php on line 46
```

**Comment by jakzal** [comment] 2015-05-26 17:13
@gnat42 this is not a bug. Unique validator is not automatically registered by the form component, as it's implemented in a separate package (doctrine bridge). You need to either register it on the validator factory yourself, or access the validator registered in the container.

**Comment by gnat42** [comment] 2015-05-26 17:16
@jakzal I figured as much but can't seem to find any documentation on how to accomplish that are there any?

**Comment by webdevilopers** [comment] 2015-10-21 12:55
I have a similar Fatal Error for a class name when using the validator from this tutorial by @KnpLabs asked by @dextervip:
**PHP Fatal error: Class 'unique_event_date' not found **

Tutorial: https://knpuniversity.com/screencast/question-answer-day/custom-validation-property-path

The example uses custom annotations. When writing the test I use the same validator config:
```php
$this->validator = Validation::createValidatorBuilder()->enableAnnotationMapping()->getValidator();
```

The service for the alias:
```yml
# src/KnpU/QADayBundle/Resources/config/services.yml
services:
    unique_event_date_validator:
        class: KnpU\QADayBundle\Validator\UniqueEventDateValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: unique_event_date
```

The validation constraint:
```php
// src/KnpU/QADayBundle/Validator/UniqueEventDate.php
namespace KnpU\QADayBundle\Validator;

use Symfony\Component\Validator\Constraint;

/** @Annotation */
class UniqueEventDate extends Constraint
{
    public function validatedBy()
    {
        return 'unique_event_date';
    }

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }
}
```

Does this relate to the same issue? Like @gnat42 I don't understand how to:
`You need to either register it on the validator factory yourself, or access the validator registered in the container.` as @jakzal mentions

**Comment by xabbuh** [comment] 2015-10-21 21:43
@webdevilopers You need to ensure that you use the `ConstraintValidatorFactory` class from the FrameworkBundle instead the one from the Validator component.

**Comment by gnat42** [comment] 2015-10-22 15:29
@xabbuh So how is this done inside unit tests? The documentation shows this as the method to get a validator. 

```php
$validator = Validation::createValidatorBuilder()
            ->enableAnnotationMapping()
            ->getValidator();
```

So how do you ensure you use the proper factory? That code returns a ValidatorBuilder() but that's not the ConstraintValidatorFactory.

Really this should just be some information on how to run unit tests with the UniqueEntity constraint. Once someone can point out how this is supposed to work I can commit to providing a PR against the docs.

**Comment by stof** [comment] 2015-10-22 15:41
@gnat42 call ``setConstraintValidatorFactory`` on the builder, to set the instance you want

**Comment by webdevilopers** [comment] 2015-10-23 06:30
The following solution worked for me:
```php
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class EventControllerTest extends KernelTestCase
{
    /**
     * @var \Doctrine\ORM\EntityManager
     */
    private $entityManager;

    /**
     * {@inheritDoc}
     */
    public function setUp()
    {
        self::bootKernel();

        $this->entityManager = static::$kernel->getContainer()
            ->get('doctrine')
            ->getManager();

        $this->validator = static::$kernel->getContainer()->get('validator');
    }

    private function getKernel()
    {
        $kernel = $this->createKerel();
        $kernel->boot();

        return $kernel;
    }
}
```

Getting the validator directly from the container.

**Comment by placid2000** [comment] 2015-12-23 10:32
Just had the same issue. @webdevilopers solution worked for me too. Thank you

**Comment by placid2000** [comment] 2015-12-23 10:34
Just had the same issue. @webdevilopers solution worked for me too. Thank you

**Comment by Badlapje** [comment] 2016-05-04 07:23
running in to the same issue, documentation needs to be adjusted here... it's a pain in the ass working with unit tests in Symfony so far, and it really should not be.

**Comment by xabbuh** [comment] 2016-05-04 08:48
@Badlapje Please open an issue on the docs repo if you feel that there is something we should improve.

**Comment by nimasdj** [comment] 2019-10-16 18:52
> @webdevilopers You need to ensure that you use the `ConstraintValidatorFactory` class from the FrameworkBundle instead of the one from the Validator component.

reading here https://stackoverflow.com/questions/40601866/how-to-configure-dependencies-on-custom-validator-with-symfony-components

I tried to use `ConstraintValidatorFactory` as you suggested, instead of creating a factory as that answer suggests, I did not find the file within framework-bundle folders, please give a `use` line that I can call it. 

Btw, why UniqueEntity is not independent from framework like a component as I am getting 'doctrine.orm.validator.unique' not found error? I have to add that I have both bundle and doctrine bridge installed.

**Comment by damienfa** [comment] 2022-10-06 03:48
@nimasdj , exact same issue here… And we're in 2022, with Symfony 6.1. The stackoverflow solution doesn't work anymore.

I try to do a simple unit test but I am getting the 'doctrine.orm.validator.unique' not found … 

My Entity  class "Person" has an `#[UniqueEntity('uniqueId')]` attribute. It works everywhere in the app, but with unit-test it fails with the : _Error: Class "doctrine.orm.validator.unique" not found_  🤷🏻‍♂️

My code : 
 
```
 class MyTest extends KernelTestCase
{
    public function setUp(): void
    {
        self::bootKernel();
        $this->validator = Validation::createValidatorBuilder()->enableAnnotationMapping()->getValidator();
    }

    protected function oneTest()
    {
        $P = new Person();
        $P->setUniqueId(1234);
        $this->assertCount(0, $this->validator->validate($P));
    }
}
```
