### ISSUE TITLE
choice_value and choice_label problem

### ISSUE THREAD

**Issue by petforsberg** [symfony/symfony#21587] opened 2017-02-11 18:15 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | #  **yes**
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | **3.2**

Seems like a common issue: http://stackoverflow.com/questions/38055465/symfony3-missing-argument-2-for-commonbundle-controller-closure

Here's the doc: http://symfony.com/blog/new-in-symfony-2-7-choice-form-type-refactorization#dynamic-generation-of-choice-names-and-values

and the code from it:

    'choice_value' => function ($allChoices, $currentChoiceKey) {
        ...
    },

I noticed the same issue with **choice_value** when working with the Doctrine's ArrayCollection - this code works:

```
'choice_value' => function($value)
    {
        ...
    }
```

while this one will bring the error like a given one (**_"Warning: Missing argument 2 for CommonBundle\Controller\DefaultController::CommonBundle\Controller{closure}()"_**)

```
'choice_value' => function($value, $key)
    {
        ...
    }
```

Notice extra $key var. What I get by $value is ArrayCollection - i.e. all the values (choices) available. But I want to have a key, so that I could access only a single value from the whole collection. Do I need to do a work-around hooks by making some $i(terator) global and increment it in the closure?

The same applies to **choice_label**.

**Comment by xabbuh** [comment] 2017-02-13 17:55
I might be wrong, but this looks like an error in the blog post (and in the documentation) to me. The `choice_value` callback is called with the current choice as the only argument.

ping @HeahDude

**Comment by HeahDude** [comment] 2017-02-13 23:10
Hey @petforsberg, sorry for the late answer. Yes this is expected and I have to link https://github.com/symfony/symfony-docs/pull/6393 again (see specially https://github.com/symfony/symfony-docs/pull/6393).

However, `choice_label` should work as expected and take three arguments: the choice, the index (maybe original label) and the string value.

Good news is that finishing this PR is one of my priorities :).

**Comment by xabbuh** [comment] 2017-02-15 10:26
Closing in favour of symfony/symfony-docs#6393.

**Closed by xabbuh** 2017-02-15 10:26 UTC
Labels: Form, Status: Waiting feedback

**Comment by petforsberg** [comment] 2017-02-22 15:58
Thanks. I've just downloaded the newest (3.2.4) Symfony 3.

choice_label doesn't work quite correct yet, however... 

First of all, for a reason I get only the last element of ArrayCollection as first argument (choice), i.e. when I have 2 elements with indexes 0 and 1, I get two times "1" index. When I have 4 elements with 0,1,2,3 indexes, I get four times "3" element... and so on.

choice_value also doesn't provide expected object, as here: http://symfony.com/doc/current/reference/forms/types/choice.html#advanced-example-with-objects

(in the example in docs, it supposed to be Category). Instead, I get the whole ArrayCollection! ;)

So in short, it doesn't work.

Maybe I'll talk a little bit about my model:

I created a QuestionType form type, which is related to Question entity. Question has 1-to-many relation to Answers (so it holds $answer field, which is ArrayCollection). When I retrieve the related data from the Doctrine's Entity in the QuestionType class like this:

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $choices = $builder->getData()->getAnswers();
        $builder->add('answers', ChoiceType::class, array('choices' => $choices,
```

and put the $choices (being ArrayCollection) as 'choices' option, I get this strange behavior, like described. Attempting to convert ArrayCollection to array doesn't help either.

**Comment by xabbuh** [comment] 2017-02-22 16:45
Are you sure that `$choices` really is an instance of `ArrayCollection` (i.e. `$builder->getData()->getAnswers()` does not return an array)?

**Comment by HeahDude** [comment] 2017-02-24 01:34
@petforsberg Could you please try to fork symfony standard edition and add some code to reproduce your issue?

**Comment by petforsberg** [comment] 2017-02-24 17:44
It was ArrayCollection. But I tried with array, too, the same effect.

Why to fork Symfony? It's sufficient to create a regular empty SF project, I guess. ;)

**Comment by xabbuh** [comment] 2017-02-25 10:55
Well, if you want someone to look into what you consider to be a bug, it's always good to make the life for contributors as easy as possible. And one of the things you can do is to create a ready to use example that suffers from the issue you experience. Otherwise, one may do something a bit different than you did in your project and will not be able to reproduce your issue.

**Comment by petforsberg** [comment] 2017-02-25 12:21
Xabbuh, I understand all of this, don't worry ;)
What I don't understand however, is this: what is an advantage of forking Symfony itself, whilst only a regular symfony app, with clear seperation from the Symfony itself, should suffice?
So, I'll create one as soon as I have just a bit of time to make it as easy for you as possible to reproduce it.
Ok? ;)

**Comment by xabbuh** [comment] 2017-02-25 12:42
Then I misunderstood you. Usually it's easier to fork the Symfony Standard Edition. But if you have an existing application that you can share and that suffers from the issue, that's fine too of course (as long as one is able to easily reproduce your issue with it).

**Comment by petforsberg** [comment] 2017-02-28 12:22
Thanks for your time.

Here is the code: [https://github.com/petforsberg/form-issue](https://github.com/petforsberg/form-issue
)

It does what I described above. Please run it in the dev mode and look specifacally what shows up in the dump section in the Symfony's dev toolbar. You may also want to add extra dumps, or uncomment existing ones.
Feel free to fork or add to code anything you want.

Take a special look at the form type, where I added some dumps and comments: https://github.com/petforsberg/form-issue/blob/master/src/AppBundle/Form/QuestionType.php

To your convience, everything runs at one root page of the project.

**Comment by xabbuh** [comment] 2017-02-28 14:52
In fact, the example you have does not make much sense IMO. First, the callback for the `choice_value()` option is called four times (once for every configured answer). Then, you bind your `Question` object to the `QuestionType`. However, the question itself has a collection of answers. So the choice type will search for the value matching the `ArrayCollection`. The `ChoiceType` only makes sense if need to select one answer from a given set to be assigned to your question. But in your case the available choices and the data of your question are the same.

**Comment by petforsberg** [comment] 2017-02-28 16:28
I'm not sure if I get you correctly.

> First, the callback for the choice_value() option is called four times (once for every configured answer)
Well, that's pretty obvious why it is so: because there are 4 answers ;) And what I understood from the docs, it should be called for each answer.

Question holds the Answers collection - in the $answers field. There's no question about why, I guess - it's clear.

So, the form should reflect the Question - and I use the only field in the question form type: 'answers', which should be bound to the $answers field in the Question, right?
And this is how it is.

Let's talk about a real world design: a poll. Poll contains questions. Each question have number of _related_ answers. I can't see more sensible model design, than just making a relation between Question and Answers here, and hence the Question holding the $answers.

How would you, say, create a form with use of Sonata Admin for a user in this case? The most intuitive approach is to create everything on the same page: you click "Add Question", and then click "Add" under the Answers area in the Sonata's form, because there's no sense to split Question and Answers into two distinct forms (although this is how the "code" is designed).

So this is the real world need. But I'm not sure where you see no sense.

Do you expect that a form should contain only Answer objects in this case, and no Question at all?

**Comment by HeahDude** [comment] 2017-02-28 22:06
Hey @petforsberg, thanks for providing us this fork. After checking it, the behavior is still expected to me.

In order to work the `choices` option must be an array, so using:
```php
$choices = $builder->getData()->getAnswersArray();
```
[here](https://github.com/petforsberg/form-issue/blob/master/src/AppBundle/Form/QuestionType.php#L33) is the way to go.

But calling that the [returned array](https://github.com/petforsberg/form-issue/blob/master/src/AppBundle/Model/Question.php#L69) is a map of `'label' => 'id'` which is valid, labels are defined by default and values too using ids.
But then you can't expect to get an instance of `Answer` as first choice argument in callable options, you get an id instead. Same when calling `$form->get('answers')->getData()` an array of ids is returned. If that's what you want no need for options.

What you can do is to use a simple array of `Answer` objects as choices by defining:
```php
$choices = $builder->getData()->getAnswers()->toArray();
```
But be careful, the `choice_value` callable is used as view transformer which means that when initializing, the form will set the data of the `answers` field by calling `$data->getAnswers()` with returns an `ArrayCollection` of `Answer` objects, ok, but is the field is not multiple the data (as choice) is passed to the callable to be transformed as a value in the view and preselect the choice input.

To prevent the getter to be called you have two ways:
 - set the `mapped` option to `false`,
 - explicitly set the `data` option to null, or a string id (choice value) or an array of string ids (depending on the multiple options).

However, if there is only one object in the collection and the field is not multiple you need a model transformer to return the only value from the collection and vice versa, IMHO you should go for something like:
```php
$answersField =  $builder->create('answers', ChoiceType::class, array(
    'choices' => $choices,
    'expanded' => $this->expanded,
    'multiple' => $this->multiple,
    'choice_value' => 'answerId',
    'choice_label' => 'answerText',
)->addModelTransformer(new CallbackTransformer(
        function ($data) {
            return $this->multiple ? $data : $data[0];
        },
        function ($value) {
            return new ArrayCollection((array) $value);
        },
)); 
$builder->add($answersField);
```

Is that more clear now for you?

**Comment by petforsberg** [comment] 2017-03-06 16:06
Hello, thanks for your time.

Well, yes, I see your point. I have nested model (object in object, and the former is actually another nested object, as it's basically ArrayCollection containing Answers), but Symfony forms rather work with array (and possibly with use of Data Transformer). This is what I had actually in mind when creating mentioned getAnswersArray().

Thanks for the solutions, probably most simple (and therefore the best one) would be the first one.
