### ISSUE TITLE
 Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.

### ISSUE THREAD

**Issue by nikolinmajmari** [symfony/symfony#43222] opened 2021-09-28 09:27 UTC
**Symfony version(s) affected**: 5.3.8
![Capture](https://user-images.githubusercontent.com/51003589/135061194-ea151864-77d9-4035-9981-14b84e46a506.PNG)

**Description**
 I just created a new symfony 5.3.8 project using php 8.0.10 , composer 2.1.3.  Then the program is not executed  and this errorr is shown 

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In RegisterListenersPass.php line 143:
!!
!!    Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

**Comment by icanhazstring** [comment] 2021-09-28 09:27
Duplicate to #43212

**Comment by derrabus** [comment] 2021-09-28 09:28
Duplicate of #43212

**Closed as completed** 2021-09-28 09:28 UTC
Labels: Bug, Status: Needs Review
