### ISSUE TITLE
With 3.2.4 I can't inject AnnotationReader anymore

### ISSUE THREAD

**Issue by lbayerl** [symfony/symfony#21648] opened 2017-02-17 11:47 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.4

Trying to inject `AnnotationReader $reader` in a service with `arguments: ['@annotation_reader'] worked fine in Symfony 3.2.3 but since upgrading to 3.2.4 it fails with:

```
construct() must be an instance of Doctrine\Common\Annotations\AnnotationReader, instance of Doctrine\Common\Annotations\CachedReader given
```

Might be worth mentioning that I am trying to inject it in an EventListener:

```yml
    request_cache_listener:
        class: MyCompany\MyBundle\EventListener\MyRequestListener
        arguments: ['@annotation_reader']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
```

This is probably caused by: https://github.com/symfony/symfony/pull/21556

**Comment by lbayerl** [comment] 2017-02-17 11:49
This is probably caused by: https://github.com/symfony/symfony/pull/21556

**Comment by nicolas-grekas** [comment] 2017-02-17 12:00
That's a bug in your type hints: you should type hint against the interface, not against the implementation.
`Reader` is the interface - and there are two implemetations: `AnnotationReader` and `CachedReader`.

**Comment by stof** [comment] 2017-02-17 12:00
you should typehint the Doctrine interface (i.e. ``\Doctrine\Common\Annotations\Reader``), not the Doctrine implementation. Otherwise, you forbid using the cached implementation.

Btw, 3.2.2 and older were also using the cached version. Using the uncached implementation is a bug introduced in 3.2.3 (and with a huge impact on performance)

**Comment by stof** [comment] 2017-02-17 12:01
closing this issue because the actual issue is not in Symfony (and we will not reintroduce the performance regression for people starting to rely on the bug introduced in a single release)

**Closed by stof** 2017-02-17 12:01 UTC

**Comment by lbayerl** [comment] 2017-02-17 12:58
thanks, got it.
