### ISSUE TITLE
How to use choices_as_values in the future

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony#21406] opened 2017-01-25 15:20 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.12

I stumbled upon a bug on my web app. Let's assume I have the following array

```
// First element
Key = key_1
Value = value

// Second element
Key = key_2
Value = value
```

Ok, but now to my problem. Symfony wants the values that are displayed to the user, to be the key of the array, and the values used for the option elements should be the values in the array.

I think you already saw the problem. It's in no way possible to have two elements with the same value in a select box, because the flipped array will just overwrite the key.

There are two points which make me understand the condition

* The value of the array is used for the `<option value=""` therefore, using value for value makes sense
* It doesn't really make sense to have the same displayed value twice, because the user cannot distinguish those two

However, the second point is no valid, because (just if it's true, if not, ignore it) it doesn't make sense in my opinion to just forbid the user from doing somethig, right?

So currently I can just use `choices_as_values`, but the documentation says, that for Symfony 3.0 the default behavior is 

`'choices' => array('Male' => 'm', 'Female' => 'f'),`

as you can read [here](http://symfony.com/doc/2.8/reference/forms/types/choice.html#choices-as-values)

So as soon as I upgrade my code won't work anymore correctly

Is there a reason why this have been removed? Is it an error in the documentation? Is there a way to code it like needed?

**Comment by tzfrs** [comment] 2017-01-25 15:31
What I noticed is, that I could build it like this

```
'choices' => $choices,
'choice_label' => function ($value) {
return $value;
},
```

However, why would I need to go that approach just to display my choices as they are given?

**Comment by stof** [comment] 2017-01-25 15:34
there is a second solution: use ``choice_label`` to provide a callable returning labels, allowing you to have what you want as keys in the choices array (your callable with receive the choice value as first argument and the array key as second argument).

The main reason to stop passing choices as keys is because it forces to select only strings or integers (as they are the only valid keys in PHP). Choosing between boolean or float values was a huge pain in 2.7 actually.

On a side note, the choice is not always used as the HTML value. This is controlled by the ``choice_value`` option of the form (the default callable indeed uses the choice itself when all choices are castable as string, but it would use an incremented index otherwise).

**Comment by tzfrs** [comment] 2017-01-25 15:36
Hey, seems like we were writing at the same time. Yeah, I found out about the `choice_label` function, was just wondering why I would need to use it if I just want to use the array as it is. But the explanation with bools etc, made sense. Thanks.

**Comment by stof** [comment] 2017-01-25 15:58
and note that you will need to use it only when you actually have several choices with the same label (that the user cannot distinguish, so leading to bad UX). So for most cases, using labels as keys works fine (and contrary to choices, labels are fine with being restricted to strings by PHP)

**Comment by tzfrs** [comment] 2017-01-25 15:59
Yeah thanks, I just had this use case which required it, but you're right, it shouldn't even come to this.

**Comment by tzfrs** [comment] 2017-01-31 09:30
Hey @stof, sadly had to reopen the issue. While it worked, that the labes were now displayed properly, the values were mixed up. The form didn't use my IDs as value, but instead counted it up from 0.

So if we imagine again I got this array

```
// First element
Key = key_1
Value = value

// Second element
Key = key_2
Value = value
```

Then my desired selectbox would be

```
<select>
    `<option value="key_1">value</option>
    `<option value="key_2">value</option>
</select>
```

However, it looks like this

```
<select>
    `<option value="0">value</option>
    `<option value="1">value</option>
</select>
```

If I use `choice_value`

```
choice_value => function ($value) {
    print $value // value (I expected key_1 and key_2 here)
}
```

The value is the exact same property as the `label`. I don't have access to the key for the given choice.

**Comment by tzfrs** [comment] 2017-01-31 09:59
I solved this issue now with a little hack. I added the identifier into the label string, so it reads like

```
// First element
Key = key_1
Value = (ID: 1) value

// Second element
Key = key_2
Value = (ID: 2) value
```

Now I can flip the choices array, and use choice_label and choice_value

```
$choiceDefaultOptions = [
                'choices' => array_flip($choices),
                'choice_label' => function ($key, $value) {
                    return preg_replace('#^\(ID: \d+\)\s+#', '', $value);
                },
                'choice_value' => function ($key) {
                    return $key;
                },
                'mapped' => false,
                'label' => false,
            ];
```

And yes, I know, that the error lies somewhere else, in the design how the values of the select box can be created, but is there a different way?

**Comment by stof** [comment] 2017-01-31 10:27
What are your choices ? I cannot help you understand why it switches to incremented values if I have fake data (as it depends on the data)

**Comment by HeahDude** [comment] 2017-01-31 10:28
Hi @tzfrs, let me try to recap why there is no bug here.

In symfony 2.7 and before, you could define you choices array with:
```php
'choices' => [
    'some value' => 'Label 1',
    'another value' => 'Label 2',
]
```

But the problem is a value can be anything from the model and using object would imply to create a choice list object to handle this case. So to solve this more easily an option `choices_as_values` has been introduced in order to flip the array.

Because labels are always strings and value can be anything. To keep BC values (choices) are used (when possible) as string values for the corresponding html attribute of each choice in the view.

If too values are the same (what happened to you), incrementing integers are used instead to avoid conflict. You can then use `choice_value` option to transform each choice to a string or `choice_label` to transform each choice and its value to a label:
```php
'choices' => [
    'Label 1' => $object1,
     'Label 2' => $object2,
],
'choices_as_values' => true,
'choice_value' => ($choice) {
    // $choice === $object1 | $object2 | null
    return $choice->toString();
},
'choice_label' => function ($choice, $key) {
    // $choice === $object1 | $object2
    // $key === 'Label 1' | 'Label 2';
    return 'Label of '.$choice->toString();
}
```

So indeed, you can return two labels that are the same, but this is not very useful (how to choose then?), however your choices array must contain unique values (ensured in core otherwise fallback on integers) and `choice_value` must return unique results (which is the dev's responsibility since there is no check for it) otherwise the code might break anytime, because it won't be able to distinguish them.

**Comment by xabbuh** [comment] 2018-09-23 11:32
closing as explained

**Closed by xabbuh** 2018-09-23 11:32 UTC
Labels: Form
