### ISSUE TITLE
Translator is not translating form errors

### ISSUE THREAD

**Issue by nimasdj** [symfony/symfony#33979] opened 2019-10-14 04:36 UTC
Translator is not translating form errors, isn't it a bug? I am using current version.

for symfony standalone translation component I use:

```php
$translator = new Translator('fr_FR');
$translator->addLoader('php', new \Symfony\Component\Translation\Loader\PhpFileLoader());
$translator->addResource('php', ROOT.'/translations/messages.fr.php', 'fr_FR');
$twig->addExtension(new TranslationExtension($translator));
```
It is working fine to translate symfony form labels. To translate symfony form constraint errors I use:
```php
->add('firstname', TextType::class, [
    'constraints' => [new Assert\Length(['min' => 3,
    'minMessage' => 'name.short',
])
```
and in messages.fr.php

I have

```php
return [
    // ...
    'name.short' => 'Name is short',
];
```
other form labels are in this catalog too. labels are translated fine but for form error, I get name.short instead of its value. What mistake I did? Is it looking for another place to find the translation catalog?

EDIT: for twig I use this without cache parameter,
```php
$twig = new \Twig\Environment($loader, [
'strict_variables' => true,
'optimizations' => -1,
'debug' => true,
]);
```
and it seems no twig cache is set, for standalone symfony form and validator I did not set any cache, for sure I checked directories, no cache is set. What else should I check?

EDIT2:

I used this too:

```php
$translator = new Translator('fr_FR');
$translator->addLoader('php', new \Symfony\Component\Translation\Loader\PhpFileLoader());
$translator->addResource('php', ROOT.'/translations/validators.fr.php', 'fr_FR');
$translator->addResource('php', ROOT.'/translations/messages.fr.php', 'fr_FR');
$twig->addExtension(new TranslationExtension($translator));
```
and in translations/validators.fr.php I have a returning array with element name.shor like above, but still doesn't work.

**Comment by stof** [comment] 2019-10-14 15:03
please also show how you are initializing the form and validator components. Your snippets are not a reproducing case.

**Comment by nimasdj** [comment] 2019-10-14 15:53
Hi Christophe,

Here it is what I use. Did I do any mistake or is it a bug?
```
$appVariableReflection = new \ReflectionClass('\Symfony\Bridge\Twig\AppVariable');
$vendorTwigBridgeDirectory = dirname($appVariableReflection->getFileName());
$loader = new \Twig\Loader\FilesystemLoader([
    'themes',
    $vendorTwigBridgeDirectory.'/Resources/views/Form',
]);

$twig = new \Twig\Environment($loader, [
    //'cache' => 'includes/twig/cache',
    'strict_variables' => true,
    'optimizations' => -1,
    'debug' => true,
]);

$defaultFormTheme = 'bootstrap_4_horizontal_layout.html.twig';

$csrfGenerator = new UriSafeTokenGenerator();
$csrfStorage = new NativeSessionTokenStorage();
$csrfManager = new CsrfTokenManager($csrfGenerator, $csrfStorage);

$formEngine = new TwigRendererEngine([$defaultFormTheme], $twig);
$twig->addRuntimeLoader(new FactoryRuntimeLoader([
    FormRenderer::class => function () use ($formEngine, $csrfManager) {
        return new FormRenderer($formEngine, $csrfManager);
    },
]));
$twig->addExtension(new FormExtension());

$translator = new Translator('fr_FR');
$translator->addLoader('php', new \Symfony\Component\Translation\Loader\PhpFileLoader());
$translator->addResource('php', ROOT.'/translations/validators.fr.php', 'fr_FR');
$translator->addResource('php', ROOT.'/translations/messages.fr.php', 'fr_FR');
$twig->addExtension(new TranslationExtension($translator));

$formFactory = Forms::createFormFactoryBuilder()
    ->addExtension(new CsrfExtension($csrfManager))
    ->addExtension(new ValidatorExtension(Validation::createValidator()))
    ->addExtension(new HttpFoundationExtension())
    ->getFormFactory();

$form = $formFactory->createBuilder()
    ->add('firstname', TextType::class, [
            'constraints' => [new Assert\Length(['min' => 3, 
                                                                       'minMessage' => 'name.short',
                                                                     ])
                                      ],
       ])
    ->add('lastname', TextType::class)
    ->getForm();

$form->handleRequest(Request::createFromGlobals());

if ($form->isSubmitted() && $form->isValid()) {

    $data = $form->getData();
    var_dump($data);

} 

echo $twig->render('signup.html', 
['form' => $form->createView(),
 'title' => 'title',
]);

```

**Comment by stof** [comment] 2019-10-14 16:04
your validator and form components are not configured to use your translator. So they will fallback to using an identity translator. Apply this patch:

```diff
+ use Symfony\Component\Form\Extension\Core\CoreExtension;

+ $validator = Validation::createValidatorBuilder()
+    ->setTranslator($translator)
+    ->getValidator();
+
 $formFactory = Forms::createFormFactoryBuilder()
+    ->addExtension(new CoreExtension($translator))
     ->addExtension(new CsrfExtension($csrfManager))
-    ->addExtension(new ValidatorExtension(Validation::createValidator()))
+    ->addExtension(new ValidatorExtension($validator))
```

**Comment by stof** [comment] 2019-10-14 16:06
Note that configuring the translator for the Form CoreExtension is meaningful if you want to benefit from the translated error messages for the few built-in form error messages (for failed file uploads for instance). But then, you would also need to register the resource to load translations available in the Form component (and you might also want to load the translations available in the validator component btw)

**Comment by nimasdj** [comment] 2019-10-14 16:13
Thanks, the message is translated but there is still a pill 'ERROR' next to it, but if no way to remove it or edit it, I don't care. That's fine.

**Comment by xabbuh** [comment] 2019-10-14 16:26
> the message is translated but there is still a pill 'ERROR' next to it

I am not sure I understand what you mean with that. Can you explain this in more detail?

**Comment by nimasdj** [comment] 2019-10-14 16:27
@stof May I ask you a question just here?
As about this: https://stackoverflow.com/questions/58378279/how-to-pass-non-field-specific-form-error-message-to-twig
If I am not using Response class and just twig rendering, I think just this line:
`$form->addError(new FormError('wrong pass'));`
is enough to call in the place where authentication failed, and no need to pass
`'form.errors' => array('wrong pass');`
within the render parameters? right?

**Comment by nimasdj** [comment] 2019-10-14 16:34
As about 'ERROR' pill, I meant this: https://imgur.com/tCrTG81

**Comment by nimasdj** [comment] 2019-10-15 13:33
@stof my custom translator form validator works fine and I get translated form errors. But because of this
` ->addExtension(new CoreExtension($translator))`

I am getting

```
TypeError: Argument 1 passed to Symfony\Component\Form\Extension\Core\CoreExtension::__construct() must be an instance of Symfony\Component\PropertyAccess\PropertyAccessorInterface or null, instance of Symfony\Component\Translation\Translator given, called in signup.php on line 27 and defined in /vendor/symfony/form/Extension/Core/CoreExtension.php:39 Stack trace: #0 /signup.php(27): Symfony\Component\Form\Extension\Core\CoreExtension->__construct(Object(Symfony\Component\Translation\Translator)) #1 {main}

Error 0: Argument 1 passed to Symfony\Component\Form\Extension\Core\CoreExtension::__construct() must be an instance of Symfony\Component\PropertyAccess\PropertyAccessorInterface or null, instance of Symfony\Component\Translation\Translator given, called in /signup.php on line 27
```

It seem you should not pass $translator instance to CoreExtension? What changes should we do?

**Comment by xabbuh** [comment] 2019-10-15 13:42
@nimasdj The translator must be the third argument: `new CoreExtension(null, null, $translator)`

**Comment by nimasdj** [comment] 2019-10-15 16:16
I have this in template
```
    <div class="col">
      {{ form_row(form.privacyRead, {'required': false}) }}
    </div>
```
and this in controller

```
    ->add('privacyRead', CheckboxType::class, ['constraints' => [new Assert\IsTrue(['message' => 'privacy.notchecked'])],
     ]) 
```

But I get the error printed twice as here is the output html:

```
    <div class="col">
      <div class="form-group row"><div class="col-sm-2"></div><div class="col-sm-10"><div class="form-check">        <input type="checkbox"             id="form_privacyRead" name="form[privacyRead]" class="form-check-input is-invalid" value="1" />
        <label class="form-check-label" for="form_privacyRead">I agree Privacy Policy<span class="invalid-feedback d-block"><span class="d-block">
                    <span class="form-error-icon badge badge-danger text-uppercase">Error</span> <span class="form-error-message">privacy.notchecked</span>
                </span></span></label></div><span class="invalid-feedback d-block"><span class="d-block">
                    <span class="form-error-icon badge badge-danger text-uppercase">Error</span> <span class="form-error-message">privacy.notchecked</span>
                </span></span></div></div>
    </div>
```

It seems something is wrong in `bootstrap_4_horizontal_layout.html.twig` template? or I did any mistake?
(PS. Of course that required:false option is intentionally for testing validator only.)

**Comment by xabbuh** [comment] 2019-10-16 21:00
I am closing here as it turns out that there isn't any issue to fix on the code side.
For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Closed by xabbuh** 2019-10-16 21:00 UTC
Labels: Bug, Form, Status: Needs Review, Translator
