### ISSUE TITLE
[WebProfiler] Display the priority on event section

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#15441] opened 2015-08-03 12:37 UTC
The current web profiler displays all the dispatched listeners ordered by its executions. Some times I need to attach a listener in a specific priority in order to be dispatched before or after another listener. Would be good if the web profiler displays the listener priorities also. That way I don't need to inspect the source code of that listener to see which priority was assigned to it.

**Comment by iltar** [comment] 2015-08-03 12:39
I like this suggestion! Isn't this already available via a command though?

**Comment by tsantos84** [comment] 2015-08-03 12:57
As far as I know the command debug:event-dispatch displays the execution order and not the priority assigned to the listeners. It would still be nice to put the real priority in web profiler.

**Comment by stof** [comment] 2015-08-03 12:59
this is because there is no way to get the priority of registered listeners currently. see #11263.

anyway, closing as duplicate of #11915

**Closed by stof** 2015-08-03 12:59 UTC
