### ISSUE TITLE
Unexpected guard condition invocation

### ISSUE THREAD

**Issue by dannykopping** [symfony/symfony#33105] opened 2019-08-10 12:34 UTC
**Symfony version(s) affected**: 4.3.3 (`symfony/worklow` _only_)

**Description**  
When adding a guard clause for a particular transition, it appears to be invoked when it shouldn't be.

**How to reproduce**  
https://gist.github.com/dannykopping/fa036f5f8d28b957ebf69af4d568a80b

I am using the example as laid out in the documentation, and I have tried to follow the docs as closely as possible; this issue seems to violate the "principle of least surprise" for me.

Here I am simply applying the `to_review` transition, and setting up a guard condition for the `publish` transition. I am not applying the `publish` transition at all, but still the guard function gets hit.

**Possible Solution**  
Possibly do not invoke the `guard.%s` event for _all_ transitions on every transition. Future transitions have nothing to do with the current one, and guarding against future conditions seems unnecessary - from what I can see. It'll create the need to manually check which transition is being executed in each guard clause (even *specific ones* i.e. `guard.publish`) which is very counter-intuitive.

**Additional context**  
The logs from the above:

```
test.php:96:
string(17) "setting: reviewed"
test.php:114:
string(21) "attempting transition"
test.php:114:
array(2) {
  'current' =>
  string(8) "reviewed"
  'transition' =>
  string(7) "publish"
}
test.php:178:
array(3) {
  [0] =>
  string(78) "Leaving "draft" for subject of class "BlogPost" in workflow "blog_publishing"."
  [1] =>
  string(85) "Transition "to_review" for subject of class "BlogPost" in workflow "blog_publishing"."
  [2] =>
  string(82) "Entering "reviewed" for subject of class "BlogPost" in workflow "blog_publishing"."
}
```

**Comment by dannykopping** [comment] 2019-08-10 12:52
It appears to be caused by the following chain:

`announce -> getEnabledTransitions -> buildTransitionBlockerListForTransition-> guardTransition`

Announcing a transition should probably not trigger a guard in this way

**Comment by dannykopping** [comment] 2019-08-10 13:14
I've fixed the test to expose this issue: https://github.com/symfony/workflow/commit/dbc3ec8d48b57950a181e15b6c595a110b7e360c
Please let me know if I'm on the right track here or if I'm missing the point entirely?

**Comment by xabbuh** [comment] 2019-08-12 08:55
After a transition is applied the announce event is fire which will announce all the transitions that are available now. But to be able to build this list the workflow needs to check which transitions are applicable now so the guard event will be dispatched for all transitions configured for the new place. So this is actually not a bug (if you added a transition from `c` to `a` for example instead, the event would also not have been dispatched).

**Comment by xabbuh** [comment] 2019-08-12 14:59
closing as explained

**Closed by xabbuh** 2019-08-12 14:59 UTC
Labels: Bug, Status: Needs Review, Workflow

**Comment by dannykopping** [comment] 2019-08-12 16:49
This is a pretty unsatisfactory explanation for me since it really violates the expectation using what I would consider to be a fairly common use-case; however if you guys feel it's not a bug then I have no choice but to accept this explanation.

**Comment by lyrixx** [comment] 2019-08-12 16:55
@dannykopping What exception are you talking about?

**Comment by lyrixx** [comment] 2019-08-12 16:56
And could you explain what is the issue?

**Comment by dannykopping** [comment] 2019-08-12 16:59
Not an exception, an expectation. I'm not sure how much context you need - I've described as much as possible in my bug report.

It seems unreasonable for a guard event handler for an *unrelated* transition to be triggered on every transition.

**Comment by xabbuh** [comment] 2019-08-12 17:20
> It seems unreasonable for a guard event handler for an unrelated transition to be triggered on every transition.

Note that this is not the case for every transition, but only if a transition is applied that ends in a place where the transition the guard event listener is attached to starts.
