### ISSUE TITLE
New Services xsd version

### ISSUE THREAD

**Issue by Gladhon** [symfony/symfony#15097] opened 2015-06-25 09:27 UTC
On Sf2.7 the same schemaLocation is used as before:
http://symfony.com/schema/dic/services/services-1.0.xsd

But there is an old schema, the new one is only in the DependencyInjection Component.

I think it would be a good idea to make a new version services-1.1.xsd and publish it under symfony.com

**Comment by WouterJ** [comment] 2015-06-28 11:02
Symfony internally doesn't use the file provided by the URL.

For the `http://symfony.com/schema/dic/services` namespace, it transforms the schema location to `path/to/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd` (which means the schema file shipped with the Symfony installation is used).

For extensions, it replaces the namespace in the schema location with the path returned by `Extension#getXsdValidationBasePath()`. E.g. `http://symfony.com/schema/dic/symfony/symfony-1.0.xsd` is transformed into `@FrameworkBundle/DependencyInjection/../Resources/config/schema/symfony-1.0.xsd`.

**Comment by Gladhon** [comment] 2015-06-29 06:58
yes, I just think it could be nice, if symfony-xml's can be validated as common

**Comment by fabpot** [comment] 2015-10-05 13:38
duplicate of #11266

**Closed by fabpot** 2015-10-05 13:38 UTC
Labels: DependencyInjection
