### ISSUE TITLE
[Form] getData() returns NULL in embedded forms

### ISSUE THREAD

**Issue by pou4ever** [symfony/symfony#28741] opened 2018-10-05 15:40 UTC
**Symfony version(s) affected**: 3.4.15

**Description**  
When i put 'allow_add' => true on my CollectionType, i can't get data in my eventlistener (pre_set_data) because data is null. But when i change 'allow_add' => false the data is not null i have my object. 
But i need of my object and i must add a new element... 

The same issue : https://github.com/symfony/symfony/issues/5694

**Possible Solution**  
Get object data when the allow_add is true.

**Comment by xabbuh** [comment] 2018-10-05 15:57
Can you create a small example application that allows to reproduce your issue?

**Comment by pou4ever** [comment] 2018-10-09 07:33
@xabbuh have you a idea ? how i can solved this issue ?

**Comment by xabbuh** [comment] 2018-10-09 08:16
I didn't find some time yet to have a look at your example application.

**Comment by HeahDude** [comment] 2018-10-09 19:37
Hello @pou4ever. thank you for reporting this.

At first glance, I would say this is not a bug. The listener is run for each entry when initializing the form, entries do include an empty form for the prototype when `allow_add` is true, indeed.

The workaround is to use the [`prototype_data`](https://symfony.com/doc/current/reference/forms/types/collection.html#prototype-data), so the form can use it to prepopulate the prototype field or to handle a null value in the listener.

I don't think there is anything we can fix here.

**Comment by pou4ever** [comment] 2018-10-10 08:43
@HeahDude Exactly !!! I have forget the prototype, i just put the condition... it's worked ;) Thank

**Comment by xabbuh** [comment] 2018-10-10 09:16
👍 great, I am closing here then, thanks for the feedback

**Closed by xabbuh** 2018-10-10 09:16 UTC
Labels: Bug, Form, Status: Needs Review

**Comment by Itaelle** [comment] 2018-11-14 16:47
Hey guys, thanks for the `prototype_data` tip!
But if you just want to push the data of the current row in the collection you can't... You can only give to your child form, some data from the parent, not his inner actual data. Bummer.

**Comment by HeahDude** [comment] 2018-11-14 19:34
A prototype should not be mapped to actual data, but helps initializing a new entry in the collection.

What do you mean exactly? Do you have some example or reproducer for the behavior you describe?

**Comment by HeahDude** [comment] 2018-11-14 19:35
(if you do please open an other issue, as this one is not a bug, and is closed already, thanks!)
