### ISSUE TITLE
Unable to clear cache with warmup

### ISSUE THREAD

**Issue by hulvat** [symfony/symfony#49583] opened 2023-03-02 14:49 UTC
### Symfony version(s) affected

5.4.21

### Description

Unable to clear cache with warmup
```

C:\www\epback> php .\bin\console cache:clear --no-warmup

 // Clearing the cache for the dev environment with debug true
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


PS C:\www\epback> php .\bin\console cache:clear            

 // Clearing the cache for the dev environment with debug true

14:48:07 CRITICAL  [php] Uncaught Error: assert($error !== false) ["exception" => AssertionError { …}]

In ConnectionFailed.php line 22:

  assert($error !== false)  


cache:clear [--no-warmup] [--no-optional-warmers]
```

### How to reproduce

C:\www\epback> php .\bin\console cache:clear --no-warmup

 // Clearing the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

PS C:\www\epback> php .\bin\console cache:clear            

 // Clearing the cache for the dev environment with debug true

14:48:07 CRITICAL  [php] Uncaught Error: assert($error !== false) ["exception" => AssertionError { …}]

In ConnectionFailed.php line 22:

  assert($error !== false)  

cache:clear [--no-warmup] [--no-optional-warmers]

### Additional Context

it occurs only when APP_ENV is set to dev APP_ENV=dev

**Comment by MatTheCat** [comment] 2023-03-02 16:33
Looks like this is caused by DBAL’s OCI8 driver. Do you get a warning if you remove the `@` from `oci_pconnect` and `oci_connect` calls in your `Doctrine\DBAL\Driver\OCI8\Driver` class?

**Comment by hulvat** [comment] 2023-03-03 12:22
Thank you for advice
I removed @ and this is the result
PS C:\www\epback> php .\bin\console cache:clear                    

 // Clearing the cache for the dev environment with debug true
In FileLoader.php line 174:

  Warning: oci_connect(): OCIEnvNlsCreate() failed. There is something wrong with your system - please check that PATH includes the directory with   
  Oracle Instant Client libraries in . (which is being imported from "C:\www\epback\config/routes/api_platform.yaml"). Make sure there is a loader   
  supporting the "api_platform" type.


In Driver.php line 38:

  Warning: oci_connect(): OCIEnvNlsCreate() failed. There is something wrong with your system - please check that PATH includes the directory with   
  Oracle Instant Client libraries


cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by MatTheCat** [comment] 2023-03-03 13:37
Okay so it seems you have an issue with your environment ([good luck with that](https://stackoverflow.com/a/29116600/465233) :sweat_smile:) but you indeed found a bug: `oci_error` should not return `false` in your case. Could you [open an issue on php/php-src](https://github.com/php/php-src/issues/new?assignees=&labels=Bug%2CStatus%3A+Needs+Triage&template=bug_report.yml)?

I don’t think anything can be done Symfony side.

**Comment by xabbuh** [comment] 2023-03-10 09:34
closing here for the reasons given by @MatTheCat

**Closed as not planned by xabbuh** 2023-03-10 09:34 UTC
Labels: Bug, Status: Needs Review
