### ISSUE TITLE
Deprecation callstack line number in profiler off by one

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#16640] opened 2015-11-23 17:04 UTC
I'm using `symfony-demo` as an upgrade example for a tutorial, and I noticed that the deprecation are off by one entry. Well, maybe not *off* but it doesn't read quite right:

<img width="697" alt="screen shot 2015-11-23 at 12 00 19 pm" src="https://cloud.githubusercontent.com/assets/121003/11343434/0fc66d96-91da-11e5-98ad-d743ddae0510.png">

In fact, line 89 should refer to `ResourceCheckerConfigCache::isFresh()` - there is no line 89 in ` BCResourceInterfaceChecker`. And `ResourceCheckerConfigCache` doesn't do anything on line 45 - it's actually `ResourceCheckerConfigCacheFactory` that does work on line 45.

Thoughts @javiereguiluz?

**Comment by stof** [comment] 2015-11-23 18:34
@nicolas-grekas can you check this as well ? The issue is either in the display or in the data being sent (or in a misunderstanding between them)

**Comment by nicolas-grekas** [comment] 2015-11-24 12:11
the issue is in the template, thus for @javiereguiluz : php stack trace gives what has been call in this file on that line. `Called from foobar at line 89` should be something like "Calling foobar at line 89". This is a common bizarre thing of PHP. If you wan to display it this way (which is perfectly fine), then the logic should associate file+line to the previous class+type+function in the stack.

**Comment by javiereguiluz** [comment] 2015-11-29 10:00
We can close this issue because it was fixed in #16658. Thanks.

**Closed** 2015-11-29 10:00 UTC
