### ISSUE TITLE
Problems decorating the "event_dispatcher" service

### ISSUE THREAD

**Issue by momocode-de** [symfony/symfony#48130] opened 2022-11-06 21:15 UTC
### Symfony version(s) affected

6.1.0

### Description

I want to decorate the "event_dispatcher" service and ran into a problem. If I use the exact function signatures of the `EventDispatcherInterface`, it will result in this error:

```
App\MyDispatcher::addListener(): Argument #2 ($listener) must be of type callable, array given, called in /var/www/html/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php on line 59
```

I have seen that the function signatures in the `EventDispatcher` are different. On the `addListener` function the `$listener` parameter is from type `callable|array`:

```
public function addListener(string $eventName, callable|array $listener, int $priority = 0)
```

But in the `EventDispatcherInterface` the "array" is missing:

```
public function addListener(string $eventName, callable $listener, int $priority = 0);
```

To fix the error, I could now simply take the signature of the `EventDispatcher` to my decoration, but then phpstan starts to complain, because the signature of the `EventDispatcherInterface` is different. Should the signatures of `EventDispatcher` and `EventDispatcherInterface` not match?

If that's correct that they don't match, is there any way to decorate the "event_dispatcher" cleanly without phpstan complaining and without including ignore rules?

### How to reproduce

1. Create a new symfony project:
```
composer create-project symfony/skeleton:"6.1.*" my-directory
```

2. Create the file `my-directory/src/MyDispatcher.php` with the following content:

```
<?php

declare(strict_types=1);

namespace App;

use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

#[AsDecorator(decorates: 'event_dispatcher', priority: 500)]
class MyDispatcher implements EventDispatcherInterface
{
    public function __construct(
        private readonly EventDispatcherInterface $innerDispatcher
    ) {
    }

    public function dispatch(object $event, string $eventName = null): object
    {
        return $this->innerDispatcher->dispatch($event, $eventName);
    }

    public function addListener(string $eventName, callable $listener, int $priority = 0)
    {
        $this->innerDispatcher->addListener($eventName, $listener, $priority);
    }

    public function addSubscriber(EventSubscriberInterface $subscriber)
    {
        $this->innerDispatcher->addSubscriber($subscriber);
    }

    public function removeListener(string $eventName, callable $listener)
    {
        $this->innerDispatcher->removeListener($eventName, $listener);
    }

    public function removeSubscriber(EventSubscriberInterface $subscriber)
    {
        $this->innerDispatcher->removeSubscriber($subscriber);
    }

    public function getListeners(string $eventName = null): array
    {
        return $this->innerDispatcher->getListeners($eventName);
    }

    public function getListenerPriority(string $eventName, callable $listener): ?int
    {
        return $this->innerDispatcher->getListenerPriority($eventName, $listener);
    }

    public function hasListeners(string $eventName = null): bool
    {
        return $this->innerDispatcher->hasListeners($eventName);
    }
}
```

The function signatures were created by PHPStorm based on the interface and all functions simply call the inner dispatcher function.

3. Execute the command `bin/console debug:container`

4. This error occurs:

```
App\MyDispatcher::addListener(): Argument #2 ($listener) must be of type callable, array given, called in /var/www/html/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php on line 59
```

**Comment by derrabus** [comment] 2022-11-06 21:30
> ```
> App\MyDispatcher::addListener(): Argument #2 ($listener) must be of type callable, array given, called in /var/www/html/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php on line 59
> ```
> 
> I have seen that the function signatures in the `EventDispatcher` are different. On the `addListener` function the `$listener` parameter is from type `callable|array`:

Yes. The event dispatcher understands a… flavor of callable that isn't exactly a callable. But that's kind-of an internal feature.

> To fix the error, I could now simply take the signature of the `EventDispatcher` to my decoration,

Yes. Or not decorate the dispatcher at all. It's not really meant to be decorated.

> but then phpstan starts to complain, because the signature of the `EventDispatcherInterface` is different. Should the signatures of `EventDispatcher` and `EventDispatcherInterface` not match?

`EventDispatcher` correctly implements `EventDispatcherInterface`. The problem is rather that the framework violates `EventDispatcherInterface` when calling the `addListener()` method with non-callables.

> If that's correct that they don't match, is there any way to decorate the "event_dispatcher" cleanly without phpstan complaining and without including ignore rules?

No.

**Comment by MatTheCat** [comment] 2022-11-06 22:21
It's weird because the `TraceableEventDispatcher` just forwards the call to `addListener` 🤔 why would it need to change its signature?

**Comment by j4nr6n** [comment] 2022-12-21 05:05
@derrabus 
> Or not decorate the dispatcher at all. It's not really meant to be decorated.

That's rather unfortunate. SymfonyCasts recently released a series in which the `EventDispatcher` is decorated. :grimacing:
Also, the Event Dispatcher component ships with two(?) classes that decorate `EventDispatcher`.

@MatTheCat It seems the only reason `TraceableEventDispatcher` and `ImmutableDispatcher` need to change the signature is because they decorate `EventDispatcher`.

For `addListener`, `removeListener` and `getListenerPriority` all three(?) built in event dispatchers have the same type-hints (`callable|array`). `EventDispatcherInterface` seems to be the only place where the method signatures don't match.

**Comment by derrabus** [comment] 2022-12-21 07:34
Those array-pseudo-callables (however we want to call them) are a hack and if someone finds a way to get rid of them, I'd happily review and merge a PR. Until then, widening the type to `callable|array` is unfortunately the way to go if you decorate the framework's dispatcher. 😢

**Comment by MatTheCat** [comment] 2022-12-21 08:03
@derrabus you got me curious! Is https://github.com/symfony/symfony/pull/31984#discussion_r292192250 the rationale behind this?

**Comment by nicolas-grekas** [comment] 2022-12-21 09:15
@MatTheCat check #23008 and #20953. I called those "high-order listeners" at the time and the name is still accurate.

I'm closing here because LSP allows type widening so there is nothing wrong with the current design.
You never decorate an abstract instance but a real one.

**Closed as completed by nicolas-grekas** 2022-12-21 09:15 UTC
Labels: Bug, EventDispatcher, Status: Needs Review

**Comment by derrabus** [comment] 2022-12-21 14:51
> @derrabus you got me curious! Is [#31984 (comment)](https://github.com/symfony/symfony/pull/31984#discussion_r292192250) the rationale behind this?

No, the framework uses pseudo-callables like `[fn () => $theRealService, 'someMethod']`. This array would not pass a `callable` type-hint, but `EventDispatcher` knows what to do with it.
