### ISSUE TITLE
[Symfony\Component\Filesystem\Exception\IOException] Problem clearing cache 2.8.8

### ISSUE THREAD

**Issue by matudelatower** [symfony/symfony#19363] opened 2016-07-14 19:30 UTC
im have this problem when i try to run `clear:cache` command.

in my cache folder it creates folder de~/ and doesnt can remove, only using `rm -rf app/cache/de~/` command

im using `symfony 2.8.8` in `PHP 5.6.23-2+deb.sury.org~trusty+1 (cli)`

<img width="1280" alt="captura de pantalla 2016-07-14 a las 4 20 51 p m" src="https://cloud.githubusercontent.com/assets/5694115/16852849/2f473466-49e0-11e6-8e5e-12b0ff825e3e.png">

**Comment by iltar** [comment] 2016-07-14 20:59
Almost looks like it was created under the wrong permissions. Can you try to remove the whole directory and run c:c a few times and  see if this issue persists?

**Comment by matudelatower** [comment] 2016-07-15 13:42
@iltar yes, it persist!

**Comment by sh4ka** [comment] 2016-07-15 14:29
I do not think this is a Symfony related problem and can be closed. It is an OS problem.

**Comment by matudelatower** [comment] 2016-07-15 16:26
@sh4ka but this did not happen before

**Comment by jameshalsall** [comment] 2016-07-18 21:43
Try running this snippet: https://gist.github.com/jameshalsall/27d0ee568994e57fc554 

I have this as a bash file in my path that I can just run on symfony projects, it will delete the cache and logs folders and set the permission bits correctly so that you don't have permission problems when they're created again.

**Comment by matudelatower** [comment] 2016-07-18 21:53
@jameshalsall yes, i try it, but the system does not support `chmod +a`

**Comment by matudelatower** [comment] 2016-07-18 21:55
I have also modified the `app/console` file with `umask(0002);`

**Comment by jameshalsall** [comment] 2016-07-19 21:17
Does your OS support FACL?

**Comment by yurii-mysak** [comment] 2016-08-04 11:35
Have the same issues with annotations instead of twig. Using symfony 3.1.2 . I set 777 permissions for cache directory during machine provision, so that composer scripts should have enough rights to clear the cache and it works for prod.

**Comment by yurii-mysak** [comment] 2016-08-04 12:17
And it also looks like that this is what is responsible for this behaviour: https://github.com/doctrine/common/issues/430 .
I tried renaming some of the long filenames and the error switched to another folder: 
`/var/www/html/var/cache/de~/annotations/fd` -> `var/www/html/var/cache/de~/annotations/44`
for example. So it looks like command is able to process the first folder, but then fails on the second one, as there is also a very long filename (256 characters including extension). 

I am using docker containers on vagrant with VirtualBox and I suspect that the `vboxsf` might have some FILE_NAME or PATH_NAME limitations.

**Comment by yurii-mysak** [comment] 2016-08-04 14:30
It is definitely cache filename generation issue in Doctrine, I went `Doctrine\Common\Cache\FilesystemCache` and changed extension to reduce filename and it allowed me to clear cache. 

Doctine Cache uses SHA-256 to generate filenames. Check `Doctrine\Common\Cache\FileCache` `getFilename($id)` method. There they have checks for the filename length, which should work but in some cases it turns out they actually do not, so I am almost sure it is a Doctrine Cache bug.

Posted an issue: https://github.com/doctrine/cache/issues/176

**Comment by sh4ka** [comment] 2016-08-04 14:37
Nice, do you think this is no longer a Symfony problem? This could be closed?

**Comment by yurii-mysak** [comment] 2016-08-04 15:00
Symfony uses `file_exists` in `Symfony\Component\Filesystem\Filesystem`, which does not remove a file if it's name is longer than 255 characters. And when cache:clear executes - it passes long file names, often around 280 characters, because it's an absolute filename. Probably most of it can also be covered with using relative path with `file_exists`? Not sure, how it will behave.

Not 100% sure now it is only Doctrine problem.

**Comment by sh4ka** [comment] 2016-08-04 15:05
Related: https://github.com/symfony/symfony/issues/19429

**Comment by jameshalsall** [comment] 2016-08-04 15:13
You could also set your `umask` to 000 in `bin/console` and `web/app_dev.php` / `web/app.php`, and then do `chmod -R 777 var/cache/* var/logs/*` until it's fixed

**Comment by yurii-mysak** [comment] 2016-08-04 18:15
@sh4ka until it's fixed - yeah, no real option there for me.

@jameshalsall Unfortunately, it does not work or help in this case as it's not a permissions issue.

**Comment by colejarczyk** [comment] 2016-11-06 18:33
I had the same problem as @matudelatower. I solved it by commenting lines 176,177 in method "remove" of class Symfony/Component/Filesystem/Filesystem.php
```
//$error = error_get_last();
//throw new IOException(sprintf('Failed to remove directory "%s": %s.', $file, $error['message']));
```
I know this is not a real solution but a quick fix to run `php app/console cache:clear` and, in my case, command to install sylius.

I've got this error on Debian 8.5 and Symfony 2.8.12, both running using Vagrant + Virtualbox. I'm using shared folders. To reproduce this error please remove completely cache folder (rm -rf) and run `php app/console cache:clear`.

Maybe this information will be useful in fixing this issue. I've changed code to generate folder name with plus (+) instead of tilde (~) to see it in PhpStorm. When I run `ls -la` in the console I see the directory `app/cache/de+/doctrine` is empty but in PhpStorm in the Project tab I still see files and folders:

- app/cache/de+/doctrine/cache
- app/cache/de+/doctrine/orm
- app/cache/de+/doctrine/PHPCRProxies

I used `scandir` to see what php is seeing in the folder just before throwing an exception:
```
array(2) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
}
```
This is strange I don't understand what is a cause.

**Comment by jameshalsall** [comment] 2016-11-06 19:43
Do those folders have executable permissions?

**Comment by jameshalsall** [comment] 2016-11-07 18:20
What if you check for other processes that may have those files open?

**Comment by colejarczyk** [comment] 2016-11-07 19:44
I don't quite understand. Why and what exactly should I check?

The fact I cannot remove `doctrine` directory is correct because it's not empty.

**Comment by jameshalsall** [comment] 2016-11-08 09:15
What matters more is the permissions on those files (which look okay from the folders you listed) and whether any of those files it's trying to delete are being used by another process.

In the latter case, you'd usually get something along the lines of "device or resource busy" but not necessarily.

Can you post the contents of `app/cache/de~`?

**Comment by yurii-mysak** [comment] 2016-11-08 11:27
It's definitely not the permissions issue, as I commented before. The issue is within too long filenames generated, which `file_exists` function cannot process. Tested it with hardcoding shorter names and everything worked nice. Also recently issue started to reproduce not only for symfony dev environment but also for prod.

**Comment by colejarczyk** [comment] 2016-11-11 15:27
I also think it's not related to the permissions. I had many problems with them in the past and never seen such a problem. I even stopped nginx and php-fpm with no success.

Here is output of the `tree` command
[directory_list.txt](https://github.com/symfony/symfony/files/586068/directory_list.txt)

I sure don't understand what is happening. Event `rm -rf` on this directory throws `rm: cannot remove ‘doctrine/’: Directory not empty`. Here is a screen shot to show this situation.
![zrzut ekranu z 2016-11-11 16-26-22](https://cloud.githubusercontent.com/assets/3582562/20219905/ab5e83de-a82b-11e6-8f4a-3d67b992beaa.png)

@jameshalsall do you need more information?

**Comment by jameshalsall** [comment] 2016-11-11 16:43
I will try and replicate this problem base on @yurii-mysak's info around file names being too long, seems very odd though.

**Comment by jameshalsall** [comment] 2016-11-11 16:44
@colejarczyk actually, what happens if you exclude the directory in PhpStorm (right click -> mark as -> excluded), can you remove it on the command line then?

**Comment by colejarczyk** [comment] 2016-11-11 21:40
The "de~" directory is not shown in PhpStorm at all. To see content I changed directory name to "de". I have marked as excluded both `cache` and `de~` and result is still the same.

If I change cache directory to "/dev/shm/sylius/", problem disappears.

**Comment by evillemez** [comment] 2016-11-13 22:26
I have this problem in 2.7.  I recently switched from an OSX host with an Ubuntu 14.04 guest via virtualbox+vagrant to an Ubuntu 16.04 host.  Everything else stayed the same.  I hadn't seen a situation like this before, but it showed up after I moved to a new host OS.

I looked through the various linked issues in this thread. I tried hacking the file extension used by the Doctrine `FilesystemCache`, even tried changing the hash algo used used in the Doctine `FileCache` to generate shorter file names - none of that worked.

Eventually I overrode the `AppKernel::getCacheDir` method to return a short path local to the VM (`/tmp/sfx`)... and then no problems.  Obviously not a great solution, and now I have to hack around that to ensure that behavior on production systems doesn't change...

Anyway, I don't really understand what's going on, but this worked for me enough to clear my caches and run my tests, and I was starting to get pretty desperate so... there it is.

**Comment by sh4ka** [comment] 2016-11-23 15:35
Hi @evillemez try this please and let me know if it helps:
$ sudo setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx var/cache var/logs
$ sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx var/cache var/logs
Good luck.

**Comment by evillemez** [comment] 2016-11-23 18:38
@sh4ka "Operation not supported".

I think I actually figured out what the issue is, though.  At least partially.  I'm using `vagrant`, and unbeknown to me, the sync method for the filesystem was changed from `nfs` to whatever the default implementation is.

Previous attempts to change the ownership and permissions on files in the project directory would execute without error - but upon further investigation I could see that the ownership and permissions hadn't actually been changed.  It's a known behavior, but I didn't realize it was relevant in my particular case.  The solution to that is to ensure that owner/group permissions are specified properly in the `vagrantfile`, which in my case I set like this:

```ruby
config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "www-data", mount_options: ['dmode=775', 'fmode=775']
```

This allows the cache to build properly if it doesn't exist, when running tests, commands, or hitting app routes in the browser.  That said, the `cache:clear` command still fails in the same way.  I have to resort to `rm -rf` twice, oddly:

```
vagrant@vagrant:/vagrant/server$ rm -rf app/cache/*
rm: cannot remove ‘app/cache/tes~/annotations’: Directory not empty
rm: cannot remove ‘app/cache/tes~/assetic’: Directory not empty
rm: cannot remove ‘app/cache/tes~/doctrine’: Directory not empty
vagrant@vagrant:/vagrant/server$ rm -rf app/cache/*
vagrant@vagrant:/vagrant/server$
```

The cache will build fine, it's just the weird directory removal issue that kills the `cache:clear` command, which then kills running the app afterwards because the cache doesn't get rebuilt properly.

Anyway, all that to say that I'm reasonably confident in declaring this is an environment issue, not a Symfony issue.  But, I'm still not sure how to fully resolve it such that it doesn't affect the Symfony workflow.

**Comment by xabbuh** [comment] 2016-11-25 09:55
@evillemez You could override the `getCacheDir()` method in your application kernel and let Symfony write the cache outside of your shared folder.

**Comment by jameshalsall** [comment] 2016-11-25 16:20
@xabbuh's recommendation is actually a good idea anyway on a shared filesystem. Symfony reads a lot from the cache directory so moving that to someone like `/tmp` which is native to the VM will give better performance.

**Comment by pixeltreiber** [comment] 2016-12-03 12:03
Perhaps it's that problem: [https://www.virtualbox.org/ticket/8761](https://www.virtualbox.org/ticket/8761) I also had that problem on cache clear using virtualbox shared folders. There can be a silent error when you delete files. So when the folder should be removed it fails as there are still files inside. In the past I did a small patch that checked after delete of the file again if file still exists. If it was still there I deleted again. I did that in a loop, but the second delete always worked.
But as that was an ugly fix I switched to nfs or SMB for shared folders.

**Comment by evillemez** [comment] 2016-12-03 18:05
@pixeltreiber Interesting - that does look like it could be it, or at least part of it.  I didn't run into this until recently probably because I switched vagrant from nfs to shared folders.  Apparently nfs can't be used with encrypted home directories, which is a bummer.

Also interesting, I saw @lsmith77 tweet about this happening in a Docker context a couple days ago.  Don't know any more details about the environment though, maybe VirtualBox was still involved somewhere.

@xabbuh @jameshalsall I did that initially and thought I was having the same problem.  I was wrong though, I was having typical permissions issues, not a big deal.  You're both right that approach seems to be the easiest way around the issue right now, at least in my situation.  My `AppKernel.php` right now looks like this:

```php
    public function getCacheDir()
    {
        if (in_array($this->getEnvironment(), ['test','dev'])) {
            return '/tmp/sfcache/'.$this->getEnvironment();
        }
        
        return parent::getCacheDir();
    }
```

Problem goes away in `test`/`dev` but persists as expected in `prod`.

**Comment by almasry** [comment] 2017-03-28 22:40
+1

**Comment by xabbuh** [comment] 2017-04-14 09:35
So I am going to close here as the problem seems to come from how VMs deal with mapped paths. Please comment if you can still reproduce the issue when not using any virtual machine.

**Closed by xabbuh** 2017-04-14 09:35 UTC
Labels: Unconfirmed

**Comment by tomjowitt** [comment] 2018-01-08 01:53
We just had the same issue (non-VM EC2 instance):

```Jan 08 12:36:54 ip-xxx-xx-x-xx prod.log: [2018-01-08 01:36:54] console.ERROR: Error thrown while running command "cache:clear --env=prod --no-debug --no-warmup". Message: "Cannot rename "/var/symfony/cache" to "/var/symfony/cach~"." {"error":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/var/symfony/cache\" to \"/var/symfony/cach~\". at /var/www/site.com/versions/4000/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:291)","command":"cache:clear --env=prod --no-debug --no-warmup","message":"Cannot rename \"/var/symfony/cache\" to \"/var/symfony/cach~\"."} []``` 

This application has been running for over a year with no issues so it's strange this started happening this week.

What is the significance of replacing the last character of the cache with "~"?

**Comment by shkkmo** [comment] 2018-03-08 04:38
I opened a ticket with VirtualBox related to this:
https://www.virtualbox.org/ticket/17605

**Comment by locopump** [comment] 2020-05-09 05:37
I solve this problem by putting permissions on themes and vendor folders:
chmod -Rf 777 vendor themes
or
chmod -Rf 777 vendor
chmod -Rf 777 themes
also you can use 775
