### ISSUE TITLE
[PHP 7.1] Latest master is crashing in ArgumentResolver

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#19677] opened 2016-08-19 19:11 UTC
RuntimeException in ArgumentResolver.php line 77: Controller "AppBundle\Controller\DefaultController::indexAction()" requires that you provide a value for the "$request" argument (because there is no default value or because there is a non optional argument after this one).

**Comment by dunglas** [comment] 2016-08-19 23:25
Can you post a code snippet to reproduce the problem?

**Comment by mvrhov** [comment] 2016-08-20 05:22
No need. use symfony-standard master and composer update

**Comment by wouterj** [comment] 2016-08-20 08:51
I can't reproduce this on PHP 7.1.0-beta2 on Windows.

Status: works for me

**Comment by mvrhov** [comment] 2016-08-20 15:49
I have beta3.

**Comment by wouterj** [comment] 2016-08-20 16:00
status: reviewed

I can reproduce this with PHP 7.1-beta3. However, this is probably a bug in PHP, as it's working as expected in all PHP versions except 7.1-beta3?

**Comment by mvrhov** [comment] 2016-08-20 16:14
It might be. I have no crash if I switch back to 7.0. However symfony might do something that's not allowed anymore.

**Comment by wouterj** [comment] 2016-08-20 16:18
The problem is that in PHP 7.1-beta3, `ReflectionParameter::getType()` is returning a FQCN (with leading `\`), while we're `===` comparing it with `Request::class`, which does not include the leading `\`.

Reported the bug at PHP, to see if this can be reverted or at least more explicitely documented: https://bugs.php.net/bug.php?id=72906

**Comment by dunglas** [comment] 2016-08-20 16:20
The API Platform test suite also fail for other reasons with the latest 7.1 (it was green before the beta 3). PHP even segfault. The last beta looks buggy, I think we should only allow failure for 7.1 until it becomes more stable.

**Comment by mvrhov** [comment] 2016-08-20 16:25
Take a look at the last comment from @nikic in php/php-src#2068 The BC seems intentional to support nullable types.

**Comment by wouterj** [comment] 2016-08-20 16:55
The feature will be reverted in PHP: https://bugs.php.net/bug.php?id=72906#1471710916

For now, please downgrade your PHP version to PHP 7.1.0-beta2 or PHP 7.0.9. This issue can be closed.

**Comment by mvrhov** [comment] 2016-08-20 19:01
> while we're === comparing it with Request::class, which does not include the leading

I'm going to take just this one out of the context as it probably should be solved in 3.2. The new nullable types would probably need to be supported in argumetresolver and through the framework as I imagine a lot of ppl will now use them.  That's the main reason I'm even running the betas.

**Comment by iltar** [comment] 2016-08-20 19:36
This class should probably receive a compatibility update for the nullable: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/ControllerMetadata/ArgumentMetadataFactory.php

My guess is that it should give a default value with null, meaning `hasDefaultValue()` should do more than checking just return `$parameter->isDefaultValueAvailable();`. However, I expect PHP to keep this backwards compatible in 7.1.

**Comment by wouterj** [comment] 2016-08-20 21:13
@iltar thing is, `ReflectionType#__toString()` will [prefix the FQCN with `?` when the class is nullable](https://github.com/php/php-src/blob/master/ext/reflection/php_reflection.c#L3040-L3054). So the `===` check doesn't not make much sense anymore. I'm not sure if they are going to revert only the `\` change, or also the `?` change. If both are reverted, there is no work to do in Symfony. If only `\` is reverted, support for `?Symfony\Component\HttpFoundation\Request` should be added (e.g. `rtrim($parameter->getType(), '?')`).

This also applies to other places using `ReflectionType#__toString()`.

**Comment by iltar** [comment] 2016-08-20 21:30
I will try to find a 7.1-beta3 monday if I can so I can build a patch for it (please do remind me if you can)

**Comment by mvrhov** [comment] 2016-08-21 05:14
This took unexpected turn. It seems that I wasn't clear enough. If they do revert the patch there is nothing to do from the symfony side, you are correct.
What I meant when I quoted the part of message is it would still be nice if symfony would support nullable types in 3.2 in "all" resolvers. e.g. `?Foo $foo`  woudn't throw exception but null would be injected if necessary.

**Comment by wouterj** [comment] 2016-08-21 06:47
Everything has been reverted: https://github.com/php/php-src/commit/8855a2ce76e8bfba1d2eea1345c765fde7a9a441 this can now be closed

**Comment by iltar** [comment] 2016-08-21 08:11
@mvrhov can you open a new issue for that? I think this is something that has to be merged into 3.1 and 3.2.

**Comment by trowski** [comment] 2016-08-21 14:49
As noted by @wouterj, I've reverted the changes so that `ReflectionType::__toString()` is now identical to 7.0, including *not* prepending a `?` for nullable types. The method is now just an alias of `ReflectionNamedType::getName()`. 

`ReflectionType::__toString()` should be discouraged for code generation going forward, as it seems there's just not a way to add type features in a BC way. My attempt to incorporate nullable types in a way that would allow for even more complex types such as `callable(?\Type\Name, ?bool)` just caused too many problems. Instead of relying on `__toString()`, use the other `ReflectionType` methods and `ReflectionNamedType::getName()` to build syntax-valid code that supports nullable types.

**Comment by wouterj** [comment] 2016-08-28 22:02
@symfony/deciders this can be closed

**Closed** 2016-08-28 22:35 UTC
Labels: Status: Reviewed

**Comment by teohhanhui** [comment] 2016-09-05 06:51
Note that the revert commit has been reverted: https://github.com/php/php-src/commit/f4e68a3968429757719c600ce16913ab09539f0d

This should be reopened. And we should add tests for this.

**Comment by iltar** [comment] 2016-09-05 06:53
@teohhanhui #19811 #19784

**Comment by wouterj** [comment] 2016-09-05 06:55
Only the `?` nullable prefix is added back, the `\` is still reverted (which was the bug reported in this issue)

**Comment by teohhanhui** [comment] 2016-09-05 06:59
PropertyInfo needs fixing too (`ReflectionExtractor`). Is there already a PR for that?

**Comment by dunglas** [comment] 2016-09-05 07:33
@teohhanhui PropertyInfo doesn't need a fix. It is already compatible with 7.1 because it uses `ReflectionParameter::allowsNull`: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L164-L166

**Comment by dunglas** [comment] 2016-09-05 07:36
@teohhanhui but it indeed needs an update for the return type.

**Comment by teohhanhui** [comment] 2016-09-05 07:36
@dunglas Please take a look at #19853
