### ISSUE TITLE
[Messenger] Autoload problem on PHP 8.1 without serializer component

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#44081] opened 2021-11-16 14:20 UTC
### Symfony version(s) affected

5.3+

### Description

Building the container using messenger without serializer causes:

```
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait" not found while loading "Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer".
```

### How to reproduce

Issue is demonstrated with this [Github Action run](https://github.com/zenstruck/messenger-test/actions/runs/1467219016).

### Additional Context

Looks similar to https://github.com/symfony/symfony/issues/41796 and https://github.com/symfony/symfony/issues/32395.

**Comment by derrabus** [comment] 2021-11-16 15:06
`ClassExistenceResource` should not error if a watched class uses an undefined trait, imho. Looks like this has to be fixed in the Config component.

**Comment by nicolas-grekas** [comment] 2021-11-17 09:12
I'm not sure the issue is in Config.
But I'm pretty sure the service should be unregistered when its deps are missing.

**Comment by nicolas-grekas** [comment] 2021-11-17 09:30
(PR welcome ;) )

**Comment by nicolas-grekas** [comment] 2021-11-17 09:35
Re-reading #32395, the issue was in php-src
Since only 8.1 is failing, it might be that the issue reappeared there?
@derrabus would you be able to investigate maybe?

**Comment by nicolas-grekas** [comment] 2021-11-17 12:00
I just gave it a try, and missing traits are turned into unrecoverable fatal errors since PHP 7.4:
https://3v4l.org/VeEUF

Dunno if @nikic can do something about it?

Anyway, we have only one solution here, which is to conditionally remove the definition.
@kbond ok to send a PR after you'd confirm that this would fix your issue?

**Comment by kbond** [comment] 2021-11-17 13:17
> I just gave it a try, and missing traits are turned into unrecoverable fatal errors since PHP 7.4

Strange we are seeing the issue on 8.1 only, no?

> ok to send a PR after you'd confirm that this would fix your issue

Yes, will do.

**Closed as completed** 2021-11-17 16:54 UTC
Labels: Bug, Config, Status: Needs Review, Messenger

**Comment by nikic** [comment] 2021-11-17 16:59
> I just gave it a try, and missing traits are turned into unrecoverable fatal errors since PHP 7.4: https://3v4l.org/VeEUF
> 
> Dunno if @nikic can do something about it?

We should be able to allow exceptions during trait loading. A bit odd that it's supported for parents and interfaces but not traits.
