### ISSUE TITLE
4.1.1 'Simple service testing' on private services not working after DI changes

### ISSUE THREAD

**Issue by jifer** [symfony/symfony#27741] opened 2018-06-27 13:05 UTC
**Symfony version(s) affected**: 4.1.1

**Description**  
This commit made for last SF version `4.1.1` breaks feature brought to in version `4.1.0`.
`Simple service testing` doesn't work anymore. https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing

https://github.com/symfony/symfony/commit/6764d4e01272b922f6f3c9ab2e3dee2fd19acd43#diff-ce4ed09b11d8fa531159e96df52124f3

**How to reproduce**  
```
        // class TestX extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase\WebTestCase
        $client = self::createClient();
        $container = $client->getContainer();
        // Or any private service
        $em = $container->get(EntityManagerInterface::class);
```

**Comment by nicolas-grekas** [comment] 2018-06-27 13:09
Thank for the report. We broke this in #27501 because we had no choice and the affected would be young enough that people (you...) could still do something about it. Sorry about that.
The way to go is to use `self::getContainer()` instead of `$client->getContainer()` now.
I'm going to update the blog post.

**Comment by jifer** [comment] 2018-06-27 13:32
Thank you for fast reply

**Comment by jifer** [comment] 2018-06-27 13:47
I have to apologise, but this also doesn't work as intended. Indeed entity manager started to work, but not other services

> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
>  The "Core\Interfaces\Api\UserApiInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

```
bin/console debug:container 'Core\Interfaces\Api\UserApiInterface'

 // This service is an alias for the service LTTSIntegration\Api\UserApi

Information for Service "LTTSIntegration\Api\UserApi"
=====================================================

 ---------------- -----------------------------
  Option           Value
 ---------------- -----------------------------
  Service ID       LTTSIntegration\Api\UserApi
  Class            LTTSIntegration\Api\UserApi
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
 ---------------- -----------------------------```

**Comment by nicolas-grekas** [comment] 2018-06-27 14:12
Did it work before? Would you be able to provide a reproducer, ie a repository we could clone to reproduce the issue?

**Comment by nicolas-grekas** [comment] 2018-06-27 14:37
Oh, yes, that's expected behavior: the dump:container shows what's *possible* to use, while the test container gives access to what's effectively used only (because we must clean up unused services to have things work).
Closing therefor, thanks for submitting.

**Closed by nicolas-grekas** 2018-06-27 14:37 UTC
Labels: Bug, DependencyInjection, HttpKernel, Status: Needs Review

**Comment by jifer** [comment] 2018-06-27 14:59
Great... So in our workflow, where we create `commands` & `handlers` first and not using them anywhere we can't create test for them, because everything will fail? We have to create dummy object where we will set new `CommandClass` as type hint just to be able to test it?
Also consider this scenario: we create `ServiceX`, unittest for it and we are using this service in `ControllerX`. After some time we decide to remove usage of `ServiceX` in `ControllerX`. Now when we will run all our unittests we will get errors each time. Not because something is wrong with our service, but because it is not used in application anywhere. Whats more error will say that service is not defined/aliased when it is not true, as I defined alias in `services.yaml`. This service IS defined, so phpUnit should be able to use it - now it is not, because service is not used anywhere.

unittest should not depend on what is used in application but on what is defined and allowed to use.

**Comment by nicolas-grekas** [comment] 2018-06-27 15:03
There are so many valid reasons for this...

If you want to test unused services, you can and should alias them in your `config_test.yaml` file (or equivalent file configuring the "test" environment.) I'd recommend using a `test.*` prefix in front of their real service name as a convention, and making them public of course.

**Comment by jifer** [comment] 2018-06-27 15:08
```
bin/console debug:container 'Core\Interfaces\Api\UserApiInterface'

 // This service is an alias for the service LTTSIntegration\Api\UserApi
```
There IS alias and we run tests in `ENV=test` and unittest fails to load above service as long as it is not typeHinted somewhere in the app. This is the reason why I still commenting on this topic. I still think this is not proper behavior. Especially if all of this worked in `4.1.0` and stopped in `4.1.1`

**Comment by nicolas-grekas** [comment] 2018-06-27 15:21
The alias must be public, otherwise it's removed.

**Comment by lukey78** [comment] 2018-08-16 20:32
+1 I also think this is wrong behaviour, because it breaks Test-driven-development. Building service classes, then testing them, and then start using them inside other services or controllers is a good pattern, but does not work this way. And because it's not in the docs, users scratch their heads why this (good!) feature seems to be not working.

**Comment by jdaviaud** [comment] 2018-10-10 12:35
I was trying to use the Private Services update done in this article : 
https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing

So i suppose that i have the same problem than you, trying to make it works for 2 hours now ...
Could be good to add it to the article that it was rollbacked and not available for now

We still have to declare manually each tested service as public again for tests then ?

**Comment by BonBonSlick** [comment] 2019-01-24 20:07
I still got issue when loading fixtures in tests

services_test.xml
```
  <service id="RoleFactoryInterface"
             alias="App\Factory\RoleFactoryInterface"
             public="true"
    />
    <service id="UserFactoryInterface"
             alias="App\Factory\UserFactoryInterface"
             public="true"
    />
    <service id="RoleFixtures"
             alias="App\DataFixtures\RoleFixtures"
             public="true"
    />
    <service id="UserFixtures"
             alias="App\DataFixtures\UserFixtures"
             public="true"
    />

// in tests setUp(){}

  $userFactory  = $container->get(UserFactoryInterface::class);
    $userFixtures = new UserFixtures($userFactory);
    $userFixtures->setContainer($container);
    $loader->addFixture($userFixtures);

    dump(static::$container->has(UserFactoryInterface::class)); // true
    dump(static::$container->has('RoleFactoryInterface')); // true
    die;
```

Error
`ArgumentCountError: Too few arguments to function App\DataFixtures\RoleFixtures::__construct(), 0 passed in /var/www/test/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php on line 193 and exactly 1 expected`

**Comment by xabbuh** [comment] 2019-01-25 09:47
@BonBonSlick Please open new issues if you think you discovered a bug with some steps that allow to reproduce them.

**Comment by BonBonSlick** [comment] 2019-01-26 18:52
@xabbuh Not sure if this is bug. Kind of redirection loop as you can see, Maybe there is should be some specific nginx or symfony configs.  https://github.com/symfony/symfony/issues/8257 have not tested it yet.

**Comment by xabbuh** [comment] 2019-01-26 19:42
What I just mean is that we would need some more insight into actual problems to understand what could be improved. And that better fits in a new issue to not get lost. If you think that's something for the documentation, I'd appreciate a new issue in the docs repository.
