### ISSUE TITLE
UrlGenerator generates network path instead of absolute URL

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#38130] opened 2020-09-09 14:00 UTC
**Symfony version(s) affected**: 4.4

**Description**  

If the route host does not match the current host, the `UrlGenerator` overwrites the host and – unless the reference type is `ABSOLUTE_URL` – sets the reference type to `NETWORK_PATH`.

https://github.com/symfony/symfony/blob/afd4027c11d707912ba2740a157a65ed2042f0ed/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L264-L270

However, if a scheme is given, I would expect the reference type to be set to `ABSOLUTE_URL` instead. Using a protocol-relative URL is an anti-pattern (see https://www.paulirish.com/2010/the-protocol-relative-url/), therefore the scheme should be added if available.

If you agree, I would generate a pull request.

**Comment by Tobion** [comment] 2020-09-09 14:44
The idea is that the URL generator expends the URL only as much as needed to comply with the desired URL. If the scheme is the same, it does not need to add the scheme. Changing this would be a bc break. Why don't you explicitly pass the the ABSOLUTE_URL constant if you want an absolute URL?

> Using a protocol-relative URL is an anti-pattern

This is not true at all. The anti-pattern is serving both http and https at the same time. Not protocal relative URLs.

**Comment by aschempp** [comment] 2020-09-10 07:55
> The anti-pattern is serving both http and https at the same time

I don't think thats the point of the antipattern, but what's said in https://www.paulirish.com/2010/the-protocol-relative-url/

> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.

If Symfony **knows** https is supported (in `$requiredSchemes`), it should always use HTTPS to make sure requests/links are always secure. Even if the current site is served through HTTP, all assets and next links should point to the secure site.

**Comment by Tobion** [comment] 2020-09-10 08:10
If the site is served through http and required schemes is https, the scheme will be added to the URL automatically. So can you clarify what this issue is about? Please create a failing test case if there is a bug.

**Comment by aschempp** [comment] 2020-09-10 08:13
It is not a bug, it's a "security feature". If the site is served through http and required schemes is `['https', 'http']`, the network path will be used but `https` should be used.

**Comment by leofeyer** [comment] 2020-09-10 08:22
No, in this case, the UrlGenerator will use `https`:

https://github.com/symfony/symfony/blob/afd4027c11d707912ba2740a157a65ed2042f0ed/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L234-L239

**Comment by leofeyer** [comment] 2020-09-10 08:23
@Tobion The issue is that the UrlGenerator ignores the given scheme. If i provide host and scheme, I would expect to get an absolute URL with the given host and scheme. Instead, I get a network path.

**Comment by Tobion** [comment] 2020-09-10 08:32
If you allow both `['https', 'http']` why should it use https? If you want https, then only specify https. Or if you expected an absolute URL then also ask for an absolute url using the reference type param, instead of asking for an absolute path which is the default.
That's how it is intented to be used and has been like this ever since. I still don't see the problem.

**Comment by aschempp** [comment] 2020-09-10 08:38
> If you allow both ['https', 'http'] why should it use https

Because

> https://www.paulirish.com/2010/the-protocol-relative-url/
> If the asset you need is available on SSL, then always use the https:// asset.

---

> If you want https, then only specify https

In our case ([Contao CMS](https://github.com/contao/contao)), we do specify https. We (currently) use path URLs by default, but Symfony (correctly) adds the host if it does not match the current one (in a multi-domain setup). It does not add the protocol though, even if HTTPS it's the only allowed protocol.

**Comment by Tobion** [comment] 2020-09-10 08:46
>  It does not add the protocol though, even if HTTPS it's the only allowed protocol.

If only https is allowed and the current scheme is not https, the scheme WILL be added to the URL.

**Comment by aschempp** [comment] 2020-09-10 09:55
I *know* all of that, and I understand how it currently works. I just *think* Symfony should **force HTTPS** if possible, same as it automatically secures cookies for example (https://symfony.com/blog/new-in-symfony-4-2-auto-secure-cookies). If you don't think Symfony should have that "security feature" by default, feel free to close the issue 😊

**Comment by Tobion** [comment] 2020-09-10 09:57
If you are on https and use protocal relative urls, it the same thing as use absolute urls with https. It does not change anything for security. So I'm closing.

**Closed by Tobion** 2020-09-10 09:57 UTC
Labels: Bug, HttpFoundation, Status: Needs Review
