### ISSUE TITLE
WebProfilerBundle - Dependency on symfony/stopwatch missing

### ISSUE THREAD

**Issue by ThePatzen** [symfony/symfony#25350] opened 2017-12-06 09:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 4.0.1

Hi!

When installing Symfony4 with Web-ProfilerBundle the Performance Window throws an error in Template
_vendor\symfony\web-profiler-bundle\Resources\views\Collector\time.html.twig line 80_

> Key "__section__" does not exist as the array is empty.

This is caused because **symfony/stopwatch** was not required. (Dependency missing)

Best Regards,
David!

**Comment by nicolas-grekas** [comment] 2017-12-29 08:52
Hello thanks for your report. This is not a bug, but follows the policy we have for optional dependencies:
the `time.html.twig` template is not enabled by `WebProfilerBundle`, but by `FrameworkBundle`, so that it's not a *requirement* of `WebProfilerBundle`. Same reasoning applies to  `FrameworkBundle`: `time.html.twig` is not always enabled especially when `WebProfilerBundle` is not installed.
`time.html.twig` could be in a separate bridge, but this would add complexity if the reasoning were to be applied on every places where this happens for other features.

Instead of requiring web-profiler-bundle directly, you can use https://github.com/symfony/profiler-pack/blob/master/composer.json (or just run `composer require profiler` if you're using Flex).

Closing as there is not bug.

**Closed by nicolas-grekas** 2017-12-29 08:52 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle
