### ISSUE TITLE
Debug toolbar is gone

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#36836] opened 2020-05-16 13:05 UTC
**Symfony version(s) affected**: 4.4.9-dev, 5.0.9-dev, 5.1.0-RC1

**Description**  
I'm testing my pet projects with Symfony 5.1 since the BETA1 release. I've upgraded them to RC1 today and the first thing I've noticed in each of them is that the debug toolbar is not displayed anymore. I can still access the `/_profiler/` route, though. Rolling back to BETA1 solves the issue for me.

Update: The issue also happens on 4.4/5.0 if I switch to the latest dev packages.

**How to reproduce**  
```sh
symfony new --full --version=next my_project
cd my_project
symfony serve
```

**Possible Solution**  
Display the toolbar again. 😃

**Comment by derrabus** [comment] 2020-05-16 13:50
The issue seems to go away if I revert #36789.

cc @marcw

**Comment by COil** [comment] 2020-05-16 17:42
I confirm, it's in 5.1 RC1 too.

**Comment by ovrflo** [comment] 2020-05-16 18:11
Yep. I was just debugging this as well. The debug led me here.
I fixed it locally by changing the WebDebugToolbar priority to Profiler+1.

While I didn't quite have the issue fixed in #36789, I did know that because of the priorities we had in the past, some things might escape the profiler. That is a legitimate bug and should be fixed.

A better solution than reverting would be to update the Profiler listener priority, though right now I'm wondering if anything else would be broken by changing the toolbar's priority.

**Comment by derrabus** [comment] 2020-05-16 18:33
Status: Reviewed

**Comment by derrabus** [comment] 2020-05-16 18:34
I guess, @carsonbot won't let me update my own review status. ;-)

**Comment by derrabus** [comment] 2020-05-16 18:38
> A better solution than reverting would be to update the Profiler listener priority,

I was searching for a quick fix, so I proposed a revert. If you've found a combination of priorities that works, feel free to submit a PR. I'd be happy to close mine then. 😃 

> though right now I'm wondering if anything else would be broken by changing the toolbar's priority.

Yeah, that's what I thought as well. Fiddling with listener priorities is always a dangerous thing to do.

**Comment by marcw** [comment] 2020-05-17 12:19
Sorry for introducing this regression! I created an issue for my original problem.

**Closed** 2020-05-18 07:50 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle
