### ISSUE TITLE
[symfony / polyfill-mbstring] Requires at least PHP ">=7.1" but uses "??=" that was introduced in PHP7.4

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#39790] opened 2021-01-11 18:48 UTC
This causes issues with static analysis code (Psalm).

https://github.com/symfony/polyfill-mbstring/blob/main/bootstrap80.php#L125

This is the commit that caused the issue: https://github.com/symfony/polyfill-mbstring/commit/11d0d87a1d1ef6a3d8158fcb756387786490cd08#diff-a97bb9776f637d300bee07c901a6ca59a2378845f507441b74939327606fc0f6R125

**Comment by stof** [comment] 2021-01-11 19:06
Duplicate of https://github.com/symfony/symfony/issues/39766 and https://github.com/symfony/polyfill/issues/326

**Closed as completed by stof** 2021-01-11 19:06 UTC
Labels: Bug, Status: Needs Review

**Comment by Aerendir** [comment] 2021-01-11 19:08
Sorry
