### ISSUE TITLE
[Messenger] Message informations for handling

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#30342] opened 2019-02-22 11:36 UTC
**Description**  
Allow to specifying a "message name" which define the type of message that can be handled.

**Example**  

Simple use-case where my main message can be extended:

```php
<?php 

use App\Messenger\MessageInterface;

class RandomMessage implements MessageInterface
{
    protected $name = 'test'

    // getter
}
```

The RandomMessage children:

```php
<?php 

class NewRandomMessage extends RandomMessage
{
    protected $name = 'newTest'

    // getter
}
```

Now the handler:

```php
<?php

use App\Messenger\MessageInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class RandomHandler implements MessageHandlerInterface
{
    public static function getHandledMessage(): string
    {
        return 'newTest';
    }

    public function __invoke(MessageInterface $message): void 
    {
        /** $message NewRandomMessage */
        if ($message->getName() !== static::getHandledMessage()) {
            return;
        }
    }
}
```

This method (the name should be improved but for me, that's like the `EventSusbscriberInterface` one) can ease the process when a message can be extended, once handled, the message keep the same type in the Handler but the developer can indicate that only this type of message can be handled, this allow to use `switch` in the same handler in order to keep a small amount of handlers. 

The `MessageInterface::getName()` is just for demonstration purpose (it can be a constant or anything else that can be called). 

Thanks for the feedback. 

**EDIT: Example for a new interface**

Here's the new interface that can be added in order to allow this approach: 

```php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Messenger\Handler;

interface MessageListenerInterface extends MessageHandlerInterface
{
    /**
     * Returns the name of the message to be handled.
     *
     * It returns a string which contain the name of the message:
     *
     *     return Message::NAME;
     *
     * Or:
     *
     *     return 'test';
     *
     * The `__invoke` method of the handler can use a defined interface.
     */
    public static function getHandledMessage(): string;
}
```

**Comment by Guikingone** [comment] 2019-02-22 13:20
**22/02/2019 - 14:20:** Example added for a new interface.

**Comment by sroze** [comment] 2019-04-06 12:59
Could you explain why it would be a good thing? What's your use-case? We are moving way from these "names" (think about the changes with the FormType, EventDispatcher, etc...) so I'm not convinced we should do this, to be honest.

**Comment by brunowowk** [comment] 2019-04-19 03:44
Yeah, I guess the whole ecosystem (also the language) is moving towards strict typing, so instead of relying on a message name you should probably rely on its type like so:

```
if (!$message instanceof NewRandomMessage) {
   return;
}
```

**Comment by Tobion** [comment] 2019-05-30 18:28
Closing due to missing feedback. I think this issue might be about handling messages based on the contents of the message. In this case it's a duplicate of #29056

**Closed by Tobion** 2019-05-30 18:28 UTC
Labels: Feature, Messenger
