### ISSUE TITLE
[httpFoundation] Request::getPreferredFormat() - Submit form, force to download render page with IE7 or IE 11 (with strategy GPO to emulate IE7)

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#34857] opened 2019-12-06 13:38 UTC
**Symfony version(s) affected**: 4.4.1
php 7.2.25 or 7.2.9

**Description**  
If you try to submit form with bad value, like a empty value with the Assert\NotBlank when you submit the form, **only** on IE 11 (with strategy GPO to emulate IE7) or IE 7 the render page is forced to download.

On chrome , EDGE, Firefox the render is correct with the message "This value should not be blank."

**The same code and apache config with symfony 4.3.x work correctly**

**How to reproduce**  

You can try  https://github.com/thewalkingcoder/symf44.git

Is a fresh symfony 4.4.1 --full install, with very very simple Entity, form and template.

**Additional context** 

ex IE 11
![image](https://user-images.githubusercontent.com/10476280/70325715-e8b79c00-1832-11ea-84e9-db644a39ff40.png)

ex : chrome
![image](https://user-images.githubusercontent.com/10476280/70325790-1dc3ee80-1833-11ea-9f29-5d3f79ce9816.png) 

I try multiple tests

**linux apache/php 7.2.25** 

with alias http://symf44.local
chrome, firefox, edge -> ok
IE 7 -> fail

no alias like http://localhost/myapp/public
chrome, firefox, edge -> ok
IE 7 -> ok

**symfony server**
 with alias http://symf44.local with reverse proxy
chrome, firefox, edge -> ok
IE 7 -> fail

no alias like http://localhost:8080
chrome, firefox, edge -> ok
IE 7 -> ok

**windows xp with Uwamp beurk !!  **
 with alias
chrome, firefox -> ok
IE 7 -> fail

no alias like http://localhost/myapp/public
chrome, firefox -> ok
IE 7 -> fail

I try to change or remove .htaccess (provide to apache-pack) same result
I try to change Constraint NotBlank annotation to php style or YAML same result

**Comment by xabbuh** [comment] 2019-12-06 13:45
Can you please check if different headers are sent when the page is accessed using Internet Explorer?

**Comment by thewalkingcoder** [comment] 2019-12-06 13:49
How to ?

**Comment by chr-hertel** [comment] 2019-12-06 14:07
@thewalkingcoder can you reproduce with IE11 on this installation of your repository?
https://46fb472b.ngrok.io

**Comment by thewalkingcoder** [comment] 2019-12-06 14:10
Is ok on your test website

**Comment by chr-hertel** [comment] 2019-12-06 14:13
it's a ngrok tunnel to my local symfony server... 🤔 
cannot reproduce the problem with IE11 either

**Comment by thewalkingcoder** [comment] 2019-12-06 14:14
I understand who use IE 11 in 2019, except my company ^^

**Comment by thewalkingcoder** [comment] 2019-12-06 14:25
very strange if i force enctype in the form like 

```
 {{ form_start(form, {'attr': { 'enctype' : 'multipart/form-data'} }) }}
```
i don't have the bugs on IE 11, but normally default enctype is application/x-www-form-urlencoded

**Comment by thewalkingcoder** [comment] 2019-12-06 15:35
ok i found the difference between Content-type in symfony 4.3 or symfony 4.4

If you dump Content-Type on Symfony\Component\HttpFoundation\Response

Symfony 4.3 with IE11 after submit form

![image](https://user-images.githubusercontent.com/10476280/70334616-0cd0a880-1846-11ea-8031-b862fddc1839.png)

Symfony 4.4 with IE11 after submit form

![image](https://user-images.githubusercontent.com/10476280/70334665-2245d280-1846-11ea-826f-b25e4ca3a251.png)

I think the mistake is here
 How to fix that ? I'm not sure it's the expected behavior

**Comment by thewalkingcoder** [comment] 2019-12-09 09:37
With symfony 4.4 the Content-type is determinate with

```
$format = $request->getPreferredFormat();

```
instead symfony 4.3
```
$format = $request->getRequestFormat();
```
After read the PR #32348 i understand the need, but with IE 11 (strategy GPO to emulate IE7) 

Accept Header return 
```
'application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*'
```
without text/html

The result is ``` $this->preferredFormat //return 'form' ```  and the "Content-type" headers was "application/x-www-form-urlencoded" and force to download page...

I can fix the problem with a CustomControllerTrait  if i set all Response/render with Content-Type :  text/html

I'm not sure symfony fix this for a deprecated browser...

@dunglas a idea ?

**Comment by yceruto** [comment] 2019-12-10 15:10
Fixed in https://github.com/symfony/symfony/pull/34921

**Closed** 2019-12-11 00:19 UTC
Labels: Status: Waiting feedback
