### ISSUE TITLE
[Serializer] Unable to deserialize into existing Doctrine entities

### ISSUE THREAD

**Issue by bwegrzyn** [symfony/symfony#15627] opened 2015-08-26 23:43 UTC
Doctrine entities are sometimes wrapped in Proxy objects, and the `instantiateObject` method does not handle them transparently.

For example, an entity `MyBundle\Entity\User` might have a class name of `Proxies\__CG__\MyBundle\Entity\User`. When this occurs, the `instantiateObject` method does not detect that it is in fact the same entity, and attempts to create a new one. 

The Security component uses `ClassUtils::getRealClass()` to get around this issue.

I believe the issue is with the following line of code:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L250

**Comment by iltar** [comment] 2015-08-27 07:58
The actual class is located in doctrine. See: https://github.com/symfony/security-acl/pull/3/files#diff-f95db4a0923d2b083e7c0d2d111c722eR46

**Comment by dunglas** [comment] 2015-08-27 09:19
@iltar the same code is also present in Symfony: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Util/ClassUtils.php#L55-L63

Btw we also have the same code in API Platform for the same reason (Doctrine): https://github.com/dunglas/DunglasApiBundle/blob/dcfee7f57e0fba8d85db214f2993bcf37a910209/Util/ClassInfoTrait.php#L30-L33

I'm not fond of adding `class_exists('Doctrine\Common\Util\ClassUtils')` everywhere but it's the easier way to fix this bug. What do you think @symfony/deciders?

**Comment by iltar** [comment] 2015-08-27 09:31
@dunglas I'm actually moving it from there to the ACL, because it's not used anywhere in the security component _but_ the ACL.

My idea was to create an injectable class that arranges this. The doctrine bridge can hook in on that and create a custom implementation that can resolve proxy names to entity names, which would make it re-usable here.

Once in the doctrine bridge, the doctrine bundle can add a "resolver" of some sort to the resolver service (`ClassNameResolver`?). This way there is a default service available in Symfony to handle this.

**Comment by dunglas** [comment] 2015-08-27 09:37
@iltar Potentially I think that this problem can also occurs when using @Ocramius' Proxy Manager.

**Comment by Ocramius** [comment] 2015-08-27 10:12
If the proxy class exists, then you should be actually able to deserialize back into into a proxy. Why do you want a cast?

**Comment by bwegrzyn** [comment] 2015-08-27 13:34
@dunglas I actually found this issue while using DunglasApiBundle. ItemNormalizer successfully overrides the class name to deserialize when it finds the object via `@id`, but when the object is found by the ResourceController, and passed in via `object_to_populate` it fails because of this bug in the serializer component.

I think you got rid of the controller after beta 3 so I'm not sure if this still applies, but that's how I stumbled across this.

@Ocramius The idea is to deserialize back in to the proxy. The serializer does not handle this correctly because the proxy class name does not match the expected class name, and thus it tries to create a new object. The serializer is unaware that a proxy exists.

**Comment by Ocramius** [comment] 2015-08-27 13:47
> The serializer is unaware that a proxy exists.

It should stay like that. Is there a test case for this?

Basically:

```php
$this->assertSame(get_class($proxy), get_class($serializer->unserialize($serializer->serialize($proxy))));
```

**Comment by Ocramius** [comment] 2015-08-27 13:53
Refs:

 - [`ProxyLogicTest`](https://github.com/doctrine/common/blob/ff72726b0876638fa7db2f28b0f26e3f1f6656ca/tests/Doctrine/Tests/Common/Proxy/ProxyLogicTest.php#L379-L504)
 - [`NullObjectFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/NullObjectFunctionalTest.php#L61-L75)
 - [`NullObjectFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/NullObjectFunctionalTest.php#L234-L238)
 - [`LazyLoadingGhostFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/LazyLoadingGhostFunctionalTest.php#L108-L128)
 - [`LazyLoadingGhostFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/LazyLoadingGhostFunctionalTest.php#L108-L128)
 - [`LazyLoadingGhostFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/LazyLoadingGhostFunctionalTest.php#L866-L873)
 - [`LazyLoadingValueHolderFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/LazyLoadingValueHolderFunctionalTest.php#L71-L92)
 - [`LazyLoadingValueHolderFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/LazyLoadingValueHolderFunctionalTest.php#L452-L459)
 - [`AccessInterceptorValueHolderFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/AccessInterceptorValueHolderFunctionalTest.php#L142-L159)
 - [`AccessInterceptorValueHolderFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/AccessInterceptorValueHolderFunctionalTest.php#L452-L457)
 - [`AccessInterceptorScopeLocalizerFunctionalTest`](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php#L147-L164)

**Comment by dunglas** [comment] 2015-08-27 20:31
Probably that simply changing https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L250 by `$context['object_to_populate']  instanceof $class` will fix the problem.

@bwegrzyn can you provide a snippet we can use to reproduce the problem (ideally a failing unit test)?

**Comment by bwegrzyn** [comment] 2015-08-27 21:34
I do not have a failing test ready, but the following will fail provided that `$entity` is wrapped in a proxy object, which I believe happens if you do not eagerly load all relations on it.

````php

$manager = $this->get('doctrine')->getManager();
$serializer = $this->get('serializer');

// `User` entity is loaded from repository without eagerly loading relations
$repository = $manager->getRepository('MyBundle:User');

// $entity is instance of Proxies\__CG__\MyBundle\User
$entity = $repository->find(1);

// Deserialize json in to existing $entity
$deserializedEntity = $serializer->deserialize(
    '{"name":"bwegrzyn"}',
    'MyBundle\\Entity\\User',
    'json',
    ['object_to_populate' => $entity]
);

// Observe that $deserializedEntity !== $entity and is missing properties that were loaded from the database

**Closed** 2016-02-21 16:53 UTC
Labels: Serializer
