### ISSUE TITLE
[Messenger] messenger:setup-transports command broken

### ISSUE THREAD

**Issue by janklan** [symfony/symfony#56873] opened 2024-05-22 02:41 UTC
### Symfony version(s) affected

[v6.4.7](https://github.com/symfony/doctrine-messenger/releases/tag/v6.4.7)  and probably [v7.1.0-RC1](https://github.com/symfony/doctrine-messenger/releases/tag/v7.1.0-RC1)  [v7.1.0-BETA1](https://github.com/symfony/doctrine-messenger/releases/tag/v7.1.0-BETA1) [v7.0.7](https://github.com/symfony/doctrine-messenger/releases/tag/v7.0.7) [v5.4.39](https://github.com/symfony/doctrine-messenger/releases/tag/v5.4.39) as they also include this change

### Description

https://github.com/symfony/doctrine-messenger/commit/43b8a9923c7faa7a6a6948b61d6dab2a1b77a415 broke the `messenger:setup-transports` command, because the argument is not always just a string:

`Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(): Argument #1 ($tableName) must be of type string, Doctrine\DBAL\Schema\Sequence given`

This is the stack trace in my app, you can see there is a `listSequences` call that produces things other than table names:

```
#0 [internal function]: Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection->Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(Object(Doctrine\DBAL\Schema\Sequence))
#1 /srv/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(377): array_filter(Array, Object(Closure))
#2 /srv/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(193): Doctrine\DBAL\Schema\AbstractSchemaManager->filterAssetNames(Array)
#3 /srv/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1648): Doctrine\DBAL\Schema\AbstractSchemaManager->listSequences()
#4 /srv/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1663): Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema()
#5 /srv/app/vendor/symfony/doctrine-messenger/Transport/Connection.php(545): Doctrine\DBAL\Schema\AbstractSchemaManager->introspectSchema()
#6 /srv/app/vendor/symfony/doctrine-messenger/Transport/Connection.php(309): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection->updateSchema()
#7 /srv/app/vendor/symfony/doctrine-messenger/Transport/PostgreSqlConnection.php(97): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection->setup()
#8 /srv/app/vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(77): Symfony\Component\Messenger\Bridge\Doctrine\Transport\PostgreSqlConnection->setup()
#9 /srv/app/vendor/symfony/messenger/Command/SetupTransportsCommand.php(83): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport->setup()
#10 /srv/app/vendor/symfony/console/Command/Command.php(326): Symfony\Component\Messenger\Command\SetupTransportsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/app/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(126): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Messenger\Command\SetupTransportsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /srv/app/vendor/symfony/console/Application.php(324): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Symfony\Component\Messenger\Command\SetupTransportsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /srv/app/vendor/symfony/console/Application.php(175): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /srv/app/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/app/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
```

### How to reproduce

1. Run `messenger:setup-transports` when using Doctrine and PostgreSQL as the messenger transport

### Possible Solution

Relax the argument type to mixed, return false on non-string values.

### Additional Context

A workaround for now is to add the offending version of `symfony/doctrine-messenger` into composer.json conflicts section to avoid its installation.

**Comment by xabbuh** [comment] 2024-05-22 05:20
duplicate of #54769

**Closed as not planned by xabbuh** 2024-05-22 05:20 UTC
Labels: Bug, Status: Needs Review

**Comment by janklan** [comment] 2024-05-22 05:27
Sorry, I did look for an existing ticket to avoid creating a duplicate, but didn't find it
