### ISSUE TITLE
[String] Add `kebab` and `pascal` method similar to `snake` and `camel`.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#48883] opened 2023-01-05 11:51 UTC
### Description

There is
```
kebab-case
snake_case
camelCase
PascalCase
```

But Symfony/string only provide a `snake` and a `camel` method.
What do you think about adding two `kebab` and `pascal` methods ?

Basically,
kebab would be a snake case with `str_replace('_', '-')`
pascal would be ucfirst°camel

Even if it's easy to implements on our side, I feel like a correctly named method would be better.

**Comment by benjaminfunk** [comment] 2023-01-05 13:08
work in progress: https://github.com/symfony/symfony/issues/48780

**Comment by derrabus** [comment] 2023-01-06 09:03
Closing as duplicate of #48780.

**Closed as not planned by derrabus** 2023-01-06 09:03 UTC
Labels: String
