### ISSUE TITLE
[symfony/mailjet-mailer] Unable to send an email via API: Message-ID header cannot be customized

### ISSUE THREAD

**Issue by fdyckhoff** [symfony/symfony#44000] opened 2021-11-10 18:52 UTC
### Symfony version(s) affected

5.2.12

### Description

The mailer is unable to send an email, when using die Mailjet API transport and when trying to customize the Message-ID header. When using "Message-ID" no mail can be sent. Changing it to "Message-Id" will send the mail, but the header is ignored.

The Mailjet API returns a 400 response for header "Message-ID". 

```
array:1 [
  "Messages" => array:1 [
    0 => array:2 [
      "Status" => "error"
      "Errors" => array:1 [
        0 => array:5 [
          "ErrorIdentifier" => "XXX"
          "ErrorCode" => "send-0011"
          "StatusCode" => 400
          "ErrorMessage" => "Header cannot be customized using the "Headers" collection. Please use the dedicated property to set this header."
          "ErrorRelatedTo" => array:1 [
            0 => "Headers["Message-ID"]"
          ]
        ]
      ]
    ]
  ]
]
```

Furthermore this error response is not properly converted to a HttpTransportException. A php notice is dispatched because the "Message" key does not exist in the `$result` array.

```
throw new HttpTransportException('Unable to send an email: '.$result['Message'].sprintf(' (code %d).', $statusCode), $response);
```

### How to reproduce

1. Set MAILER_DSN=mailjet+api://PUBLIC_KEY:PRIVATE_KEY@default 
2. Add a header to your mail message: `$headers->addHeader('Message-ID', $messageId);`
3. Try sending the message. It will not be sent. ([ERROR] Notice: Undefined index: Message)
4. Change header key to "Message-Id"
5. Try sending the message. It will be sent, but the header is ignored. No error / warning is logged.

### Possible Solution

- Fix exception message for HttpTransportException
- Add "Message-ID" header to FORBIDDEN_HEADERS (or check for uppercase/lowercase variants)
- Log warning, when forbidden header is used 
- Add mailjet specific headers as properties to message object

How to convert MJ specific headers (suggestion)
- X-MJ-CustomID to "CustomID" property
- X-Mailjet-Campaign to "CustomCampaign" property
- X-Mailjet-TrackOpen to "TrackOpens" property
- X-Mailjet-TrackClick to "TrackClicks" property

### Additional Context

Further reading:
- List of invalid headers: https://dev.mailjet.com/email/guides/send-api-v31/#add-email-headers
- How to add "CustomID": https://dev.mailjet.com/email/guides/send-api-v31/#tag-email-messages
- List of available properties (and their relating header): https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send

**Comment by xabbuh** [comment] 2021-11-11 15:00
Thanks for investigating and for reporting this issue @fdyckhoff. Would you like to give this a try?

**Comment by alexandre-castelain** [comment] 2021-12-22 12:15
Hello !

I had the same kind of issue but with the header "from". I configured the Mailer component with a global "from" parameter, following the [documentation](https://symfony.com/doc/current/mailer.html#configuring-emails-globally)

```
array:1 [▼
  "Messages" => array:1 [▼
    0 => array:2 [▼
      "Status" => "error"
      "Errors" => array:1 [▼
        0 => array:5 [▼
          "ErrorIdentifier" => "xxx"
          "ErrorCode" => "send-0011"
          "StatusCode" => 400
          "ErrorMessage" => "Header cannot be customized using the "Headers" collection. Please use the dedicated property to set this header."
          "ErrorRelatedTo" => array:1 [▼
            0 => "Headers["from"]"
          ]
        ]
      ]
    ]
  ]
]
```

I would like to make the fix but I'm not quite sure what is the correct fix. I can see in the FORBIDDEN_HEADERS constant that the "from" key is already present but with an uppercase letter. Should we ignore the case during the header comparison ?

The problem is, some headers would be ignored and we could have some problem. (Like the "from" one)

So, maybe we could force some headers in the body of the message ?

**Comment by fabpot** [comment] 2022-02-05 10:08
Someone using Mailjet has to work on a PR. Mailer providers are maintained by their users.

**Comment by fabpot** [comment] 2022-07-27 15:46
Closing as nobody cares. I would happily review a PR.
The headers are case insensitive.

**Closed as completed by fabpot** 2022-07-27 15:46 UTC
Labels: Bug, Status: Needs Review, Mailer
