### ISSUE TITLE
symfony/console have not Symfony\Contracts\Service\ResetInterface

### ISSUE THREAD

**Issue by Axent96** [symfony/symfony#35506] opened 2020-01-29 10:12 UTC
**Symfony version(s) affected**: 4.4.3

**Description**  
Uncaught Error: Interface 'Symfony\Contracts\Service\ResetInterface' not found in /srv/vendor/symfony/console/Application.php on line 66

**How to reproduce**  
composer require symfony/console:4.4.3

**Additional context**  
PHP 7.4.2, Composer version 1.9.2

**Comment by lyrixx** [comment] 2020-01-29 16:36
Hello @Axent96 

I tried to reproduce your issue and everything works for me.

I checked and the [composer.json](https://github.com/symfony/symfony/blob/v4.4.3/src/Symfony/Component/Console/composer.json#L22) require `symfony/service-contracts`

I also check on [packagist](https://packagist.org/packages/symfony/console#v4.4.3), and the deps is present.

Could you try to re-install your vendor ? `composer install`

I'm closing this issue because nothing is wrong here.

If it still does not work, please give us a full reproducer (`composer.json` + `composer.lock` + a PHP file)

**Closed by lyrixx** 2020-01-29 16:36 UTC
Labels: Bug, Console, Status: Needs Review
