### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by dodwina** [symfony/symfony#26723] opened 2018-03-31 00:25 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  |3.1

**Expected Behavior**

to be connect to project to my localhost

**Actual Behavior**

Why have i a infinite loop on languages?

> Maximum function nesting level of '256' reached, aborting! 
> in vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php at line 60   -
> 
> protected function normalize($data)
>     {
>         if (null === $data || is_scalar($data)) {
>             if (is_float($data)) {
>                 if (is_infinite($data)) {
>                     return ($data > 0 ? '' : '-') . 'INF';
> 
> > _at is_scalar (array('message' => 'Translation not found.', 'context' => array('id' => 'Se connecter / S'inscrire ', 'domain' => 'messages', 'locale' => 'fr'), 'level' => '300', 'level_name' => 'WARNING', 'channel' => 'translation', 'datetime' => object(DateTime), 'extra' => array())) 
> > in vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php at line 60   + 
> > at NormalizerFormatter ->normalize (array('message' => 'Translation not found.', 'context' => array('id' => 'Se connecter / S'inscrire ', 'domain' => 'messages', 'locale' => 'fr'), 'level' => '300', 'level_name' => 'WARNING', 'channel' => 'translation', 'datetime' => object(DateTime), 'extra' => array())) 
> > in vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php at line 43   + 
> > at NormalizerFormatter ->format (array('message' => 'Translation not found.', 'context' => array('id' => 'Se connecter / S'inscrire ', 'domain' => 'messages', 'locale' => 'fr'), 'level' => '300', 'level_name' => 'WARNING', 'channel' => 'translation', 'datetime' => object(DateTime), 'extra' => array())) 
> > in vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php at line 68   + 
> > at LineFormatter ->format (array('message' => 'Translation not found.', 'context' => array('id' => 'Se connecter / S'inscrire ', 'domain' => 'messages', 'locale' => 'fr'), 'level' => '300', 'level_name' => 'WARNING', 'channel' => 'translation', 'datetime' => object(DateTime), 'extra' => array())) 
> > in vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php at line 35   + 
> > at AbstractProcessingHandler ->handle (array('message' => 'Translation not found.', 'context' => array('id' => 'Se connecter / S'inscrire ', 'domain' => 'messages', 'locale' => 'fr'), 'level' => '300', 'level_name' => 'WARNING', 'channel' => 'translation', 'datetime' => object(DateTime), 'extra' => array())) 
> > in vendor/monolog/monolog/src/Monolog/Logger.php at line 337   +

etc...

 ** Steps to Reproduce the Problem_**

1-i 'm working on a symfony project

config.yml------

```yaml
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
```

translations repo ----- with 3 folders  in  app > Resources >Translations

2-i see this error
3-then i connected xdebug with phpstorm to resolve this issue. ( already installed without connection with ide)
-> so i edit php.ini with this lines:
[xdebug]
zend_extension="/Applications/MAMP/bin/php/php7.2.1/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=10000
xdebug.max_nesting_level = 10000
environment

It did not solve the problem because it affects translations

**Comment by xabbuh** [comment] 2018-03-31 07:02
First, please update your Symfony version. Support for Symfony 3.1 was dropped long time ago and the issue might be fixed in a more recent version. The same may apply for other dependencies. If that does not help, please also show the new error message after you increased the maximum nesting level of function calls in Xdebug and best also provide a small example application that allows to reproduce your issue.

**Comment by dodwina** [comment] 2018-04-10 22:50
I have update 3.3 but same issue.
xdebug.max_nesting_level = 10000

[capture d ecran 2018-04-11 a 00 45 21](https://user-images.githubusercontent.com/26679638/38587582-50709aec-3d22-11e8-806e-e7fe2aa2c508.png)

**Comment by curry684** [comment] 2018-04-10 23:11
It would appear that, while loading translations, an error is logged which translates to a corrupt translation, thereby causing the infinite loop.

The issue is likely highy dependent on your translation files, so my recommendation would be to [create a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) so the problem is isolated and researchable.

**Comment by xabbuh** [comment] 2018-04-26 06:18
@dodwina Can you provide an example project that allows to reproduce your issue?

**Comment by xabbuh** [comment] 2018-05-14 08:26
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed by xabbuh** 2018-05-14 08:26 UTC
Labels: Status: Waiting feedback

**Comment by yassinechabli** [comment] 2019-04-11 13:38
i go the same error, but it's resolved when i try to clear the cache manually by deleting the cache dir .
