### ISSUE TITLE
Database locking with PDOSessionHandler

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#15020] opened 2015-06-17 14:55 UTC
When my site gets a lot of traffic, I will get a lot of errors like this

request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction" at /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php line 336 

The problem is that I have the lock_mode set to 0 so there shouldn't be any transactions involved in my sessions.

**Comment by Tobion** [comment] 2015-06-18 02:45
Auto commit will create a transaction of a single statement. This means also a single statement will create locks and thus possibility to timeout. The chances are just smaller. How much percent of the sessions timeout when you say "alot of errors"?
Also what mysql table schema and storage engine do you use? What do you expect us to do when you create this issue? Do you have an idea? The only thing possible would be to retry the statment, as the error even says. But considering your timeout setting is probably many seconds already, it will not really help as no user is going to wait that long anyway.

**Comment by Tobion** [comment] 2015-06-18 02:48
Closing as duplicate of #13411

**Closed by Tobion** 2015-06-18 02:48 UTC

**Comment by Tobion** [comment] 2015-06-18 02:52
What you could try is the decrease the gc probability. Deleting old session rows can have negative impact on concurrency. #13956

**Comment by stevenmusumeche** [comment] 2015-06-19 17:45
@Tobion thanks for the explaination.  I am using InnoDB with the schema listed on the most recent cookbook page.  The issue is that MySQL fills up all 800 connections with sessions trying to be written and my site becomes completely unavailable since it can't connect to MySQL. 

I was able to see what transaction was causing the lock and it was the delete query `DELETE FROM symfony_sessions WHERE sess_lifetime + sess_time < 1434735443`.  When running a MySQL EXPLAIN on this query it shows that it cannot use any index which is why the query takes so long an causes the lock.

I believe this could be solved easily by creating a column on the table which contains the result of sess_lifetime + sess_time and added an index on it.  This would allow the query to run very quickly.

**Comment by Tobion** [comment] 2015-06-19 17:55
Already in progress: #13955

**Comment by stevenmusumeche** [comment] 2015-06-19 17:56
:+1:

**Comment by stevenmusumeche** [comment] 2015-06-20 16:52
@Tobion can the session clearing be completely disabled by setting `gc_probability` to 0? Then I could manually handle the clearing in a cronjob at a low traffic time of day.

**Comment by Tobion** [comment] 2015-06-20 18:46
Sure, I don't see why not.

**Comment by Tobion** [comment] 2015-06-20 18:55
You could also use the mysql event scheduler to do the job (when it's enabled).
