### ISSUE TITLE
[DI] Services that are inlined or added to a service locator appear in `removed-ids.php` while they are still in use

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#43245] opened 2021-09-29 11:41 UTC
**Symfony version(s) affected**: 5.3

**Description**
I'm trying to use the `removed-ids.php` file that is automatically generated by Symfony to optimize my DI configuration. Mostly, I want to know when services are defined that are not used and remove them.

I noticed that the file is not that useful as it contains a list of all service definitions that were removed from the container. But most of the time those services are actually inlined into other services or attached to service locators. 

That means that the file cannot be used to find unused services.

**Possible Solution**
One solution I have is to change the [ContainerBuilder::removeDefinition](https://github.com/symfony/symfony/blob/7244d83c4c782f3469755923ce314f8c797776ea/src/Symfony/Component/DependencyInjection/ContainerBuilder.php) method like this:
```diff
 /**
  * Removes a service definition.
  */
-public function removeDefinition(string $id)
+public function removeDefinition(string $id, bool $trackRemoval = true)
 {
     if (isset($this->definitions[$id])) {
         unset($this->definitions[$id]);
+        if ($trackRemoval) {
+            $this->removedIds[$id] = true;
+        }
     }
 }
```

This way, optimization passes like [`InlineServiceDefinitionsPass`](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php) can decide to track them as removal or not. 

But I'm not sure how that will work with services that are added to a service locator. I think that once they are added to a service locator they will turn up unused later and are removed. Not sure if it's possible to know that they were added to a service locator or not.

**Comment by stof** [comment] 2021-09-29 12:09
When a service gets inlined, that id is indeed removed from the final container (you cannot use `$container->has()` or `$container->get()` with that id, but the `get` methods can know that this id used to exist and can adjust the error message). There is nothing guaranteeing that a removed id is equivalent to an unused service.

**Comment by stof** [comment] 2021-09-29 12:17
I'm closing this as it is not a bug. You only have a different expectation about the content of that `removed-ids.php` file, and changing the content of that file would break the core feature using it.

**Closed as completed by stof** 2021-09-29 12:17 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by ruudk** [comment] 2021-09-29 12:54
> and changing the content of that file would break the core feature using it

What does that mean? What core is using this? I couldn't find it

edit: Found it: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1e319
