### ISSUE TITLE
URI parsing fails due to lack of host in parse_url

### ISSUE THREAD

**Issue by yonikok** [symfony/symfony#29630] opened 2018-12-17 14:07 UTC
**Symfony version(s) affected**: 4.3

**Description**  
URL parsing fails. For example:
`https://nova.laravel.com/password/reset`
This resolves correctly.
However `https://nova.laravel.com//password/reset` this results in a 404. Which could be seen as a user error.
But `https://nova.laravel.com//foobar/password/reset` also resolves, however incorrectly. Clearly signaling it as a bug.

**How to reproduce**  
Go to `https://nova.laravel.com//foobar/password/reset`. Or in any Laravel/Symfony project add an extra `/` after the host.

**Possible Solution**  
I added a possible solution in this PR.
https://github.com/symfony/symfony/pull/29631

**Comment by nicolas-grekas** [comment] 2018-12-17 15:46
Duplicate of #29478

**Closed by nicolas-grekas** 2018-12-17 15:46 UTC
