### ISSUE TITLE
Psalm reports undefined class UnitEnum on PHP 8.0

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#45609] opened 2022-03-02 10:33 UTC
### Symfony version(s) affected

5.4.5

### Description

The following type of errors showed up after upgrading to Symfony 5.4.5:

```
message: Docblock-defined class, interface or enum named UnitEnum does not exist
type: UndefinedDocblockClass
snippet: $this->parameterBag->get('kernel.project_dir')
```

### How to reproduce

symfony new test
cd test
composer require vimeo/psalm

create a file with the following content:
```
<?php

namespace App;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class MyClass {
  public function __construct(ParameterBagInterface $parameterBag) {
    $this->parameterBag->get('kernel.project_dir');
  }
}
```

php vendor/vimeo/psalm/psalm

### Possible Solution

- Add UnitEnum polyfill
- remove UnitEnum from docblocks

### Additional Context

https://github.com/vimeo/psalm/issues/7738

**Comment by nicolas-grekas** [comment] 2022-03-02 10:56
Removing the type-hint from the docblock wouldn't make sense.
Adding a polyfill for those interfaces has been quickly discussed in https://github.com/symfony/polyfill/issues/379 but could be reconsidered with new arguments.
Ignoring the error is also fine. SA tools have limitations, they're not omnipotent.

**Comment by guillaumesmo** [comment] 2022-03-02 11:25
The error can indeed be suppressed by adding the following in the psalm config

```
    <issueHandlers>
        <UndefinedDocblockClass>
            <errorLevel type="suppress">
                <referencedClass name="UnitEnum" />
            </errorLevel>
        </UndefinedDocblockClass>
    </issueHandlers>
```

**Comment by derrabus** [comment] 2022-03-02 12:17
Let's close this issue. It's not a bug because your reproducer code will work perfectly fine on PHP 8.0. If you think that this error should not be reported, please open a Psalm issue.

**Closed as completed by derrabus** 2022-03-02 12:17 UTC
Labels: Bug, Status: Needs Review

**Comment by emancypage** [comment] 2022-03-04 10:38
As Symfony 5.4.* requires PHP 7.2.5 or higher (minimum is 7.2.5) why force users to use 8.0? 
In my opinion it should be fixed on Symfony side to be able to use min. PHP 7.2.5 version with Psalm.
