### ISSUE TITLE
Cache clear, cannot declare class

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#25576] opened 2017-12-21 14:39 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.14

Hey,
I've been seeing a strange thing where the clear cache command cannot declare classes on it's first execution if there is no previous cache.

On the first execution it will always fail with something like 
`
PHP Fatal error:  Cannot declare class EnhancedProxy_84f26540d03882f66a8da2bedf47ccf4f27752f4\__CG__\TaskBundle\Controller\SupervisionController, because the name is already in use in /home/kai/public_html/washeroo/var/cache/tes_/jms_diextra/lookup_method_classes/TaskBundle-Controller-SupervisionController.php on line 11
14:33:41 CRITICAL  [php] Fatal Compile Error: Cannot declare class EnhancedProxy_84f26540d03882f66a8da2bedf47ccf4f27752f4\__CG__\TaskBundle\Controller\SupervisionController, because the name is already in use ["exception" => Symfony\Component\Debug\Exception\FatalErrorException { …}] []
`
On any subsequent run of the clean cache command it will be successful though.
I'm not exactly sure if it is a bug in the clear cache command or if the jms_diextra bundle is causing it.

Another thing is that the class it seems to have an issue with doesn't have a method that's annotates the lookup_method from jms_diextra but its parent class does.

**Comment by xabbuh** [comment] 2017-12-22 15:37
Can you provide steps that allow to reproduce your issue?

**Comment by enima-web** [comment] 2017-12-22 17:38
composer create-project symfony/skeleton sf-app 3.4

```
> Installing symfony/skeleton (v3.4.0)
>   - Installing symfony/skeleton (v3.4.0): Loading from cache
> Created project in sf-34
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 25 installs, 0 updates, 0 removals
>   - Installing symfony/flex (v1.0.52): Loading from cache
>   - Installing psr/log (1.0.2): Loading from cache
>   - Installing symfony/debug (v3.4.2): Loading from cache
>   - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
>   - Installing symfony/console (v3.4.2): Loading from cache
>   - Installing symfony/routing (v3.4.2): Loading from cache
>   - Installing paragonie/random_compat (v2.0.11): Loading from cache
>   - Installing symfony/polyfill-php70 (v1.6.0): Loading from cache
>   - Installing symfony/http-foundation (v3.4.2): Loading from cache
>   - Installing symfony/event-dispatcher (v3.4.2): Loading from cache
>   - Installing symfony/http-kernel (v3.4.2): Loading from cache
>   - Installing symfony/finder (v3.4.2): Loading from cache
>   - Installing symfony/filesystem (v3.4.2): Loading from cache
>   - Installing psr/container (1.0.0): Loading from cache
>   - Installing symfony/dependency-injection (v3.4.2): Loading from cache
>   - Installing symfony/config (v3.4.2): Loading from cache
>   - Installing symfony/class-loader (v3.4.2): Loading from cache
>   - Installing psr/simple-cache (1.0.0): Loading from cache
>   - Installing psr/cache (1.0.1): Loading from cache
>   - Installing symfony/polyfill-apcu (v1.6.0): Loading from cache
>   - Installing symfony/cache (v3.4.2): Loading from cache
>   - Installing symfony/framework-bundle (v3.4.2): Loading from cache
>   - Installing symfony/yaml (v3.4.2): Loading from cache
>   - Installing symfony/dotenv (v3.4.2): Loading from cache
> Writing lock file
> Generating autoload files
> Symfony operations: 4 recipes (134e6b96998d9d84b8590c084e9a4990)
>   - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
>   - Configuring symfony/framework-bundle (>=3.3): From github.com/symfony/recipes:master
>   - Configuring symfony/console (>=3.3): From github.com/symfony/recipes:master
>   - Configuring symfony/routing (>=3.3): From github.com/symfony/recipes:master
> Executing script cache:clear [OK]
> Executing script assets:install --symlink --relative public [OK]
```
cd sf-app

I create PagesController & edit routes.yaml file =>
PagesController :

```
<?php
namespace App\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
class PagesController
{
    public function index()
    {
        $number = mt_rand(0, 100);
        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
```
routes.yaml:

```
index:
    path: /
    defaults: { _controller: 'App\Controller\PagesController::index' }
```
composer require server

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]
I go to ==> localhost/sf-app/public/
```

All work well 👍

I go back to commande

composer require annotations

I get this ERROR

```
Using version ^5.1 for sensio/framework-extra-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.1.3): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 2 recipes (4b793e4e3b1f33d9f24faae67fbcedbc)
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
  - Configuring sensio/framework-extra-bundle (>=4.0): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Cannot declare interface Symfony\Component\EventDispatcher\EventSubscriberInterface, because the name is already in use in /e/wamp64/www/sf-app\vendor\symfony\event-dispatcher\EventSubscriberInterface.php on line 25
!!
!!  In sf-app\vendor\symfony\event-dispatcher\EventSubscriberInterface.php line 25:
!!
!!    Compile Error: Cannot declare interface Symfony\Component\EventDispatcher\E
!!    ventSubscriberInterface, because the name is already in use
!!
```

**Comment by nicolas-grekas** [comment] 2017-12-23 10:25
@enima-web this is not the same error - yours is tracked in #25550
Here, it's about a service lazy-proxy - might be subtly different - no need to post twice the reproducer (but thank you for it btw!)

**Comment by nicolas-grekas** [comment] 2017-12-23 18:52
@KDederichs the fact this in on branch 3.3 means this bug is unseen to me.
I'd be happy to try a reproducer you could provide. Thanks.

**Comment by Simperfit** [comment] 2017-12-27 08:43
@KDederichs Could you please help us reproducing the bug by providing a little project.

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by KDederichs** [comment] 2017-12-27 13:25
Hey sorry for the lack of replies, Christmas and such.
Here is a link with the minimum modification I needed to reproduce the bug:

https://github.com/KDederichs/symfony-standard/tree/issue_25576

It will occur when you do a `bin/console cache:clear` on a fresh cache or if you previously deleted the cache.

**Comment by alsar** [comment] 2017-12-27 14:06
It's some kind of incompatibility with `JMSDiExtraBundle`. If you disable the bundle the problem is gone.

**Comment by KDederichs** [comment] 2017-12-27 15:05
So it's their bug and not cache:clear related?

**Comment by nicolas-grekas** [comment] 2017-12-28 17:22
I managed to reproduce. As far as I tried correctly, the issue is not new to 3.3.14 specifically. On which version of Symfony did this work last? I would open an issue on JMS Di-extra instead, as I'm not sure the issue is on symfony/symfony's side.

**Comment by mvrhov** [comment] 2017-12-28 19:07
Oh, he's using JMS di-extra. IMO he should get rid of it.

**Comment by nicolas-grekas** [comment] 2018-01-04 09:24
Closing as this is an issue with JMS di-extra.

**Closed by nicolas-grekas** 2018-01-04 09:24 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback, Unconfirmed
