### ISSUE TITLE
Performance of cache warmup in project with huge interdependencies

### ISSUE THREAD

**Issue by mussbach** [symfony/symfony#34828] opened 2019-12-05 11:04 UTC
**Symfony version(s) affected**: > 3.4.18

**Description**  
Since Version 3.4.18 our cache warmup performance gets worse and worse (I am aware of https://github.com/symfony/symfony/issues/29336).
When I reset my current codebase to use symfony to 3.4.18 it is 4 Seconds, in 3.4.20 40s and in 3.4.35 the toolbar tells us a "Symfony initialization" time of 85,6s. 
When loading a page during development with xdebug it lasts hours.

I found out that `Symfony\Component\DependencyInjection\Dumper\PhpDumper::addCircularReferences` is called 38929953 times.

This is in first place a problem of our architecture in the legacy project but such a drop in performance hurts. In fact we cannot update.

Is there anything I could do in short terms? Is it possible to change the algorithm sort of like in 3.4.18?

**How to reproduce**  
Unfortunately not possible, as it possibly occurs as a problem only in big legacy projects. I am very willing to work on a solution and test stuff or provide PRs if someone has a clue

**Possible Solution**  
I dived a bit into the code but I have no suggestion yet. Perhaps some kind of better caching to avoid doublechecks.

**Comment by stof** [comment] 2019-12-05 14:40
Without any reproducing case about the kind of dependency graph leading to such bad performance, I fear that we won't be able to optimize it.

The algorithm was changed because the old algorithm was wrong (there was many cases where it would dump the wrong thing, leading to a broken compiled container). So reverting the change is not an option here. It would reintroduce all the bugs fixed by the refactoring.

**Comment by mussbach** [comment] 2019-12-05 14:43
I see. What would be the preferred way to provide such a dependency graph?

**Comment by flip111** [comment] 2019-12-11 02:21
@mussbach probably strip your app or unnessary logic (to still be able to reproduce the problem) and then rename symbols to anonymize your code

**Comment by nicolas-grekas** [comment] 2019-12-18 17:14
> addCircularReferences is called 38929953 times

Ouch!

We won't be able to do anything without a reproducer: understanding how the current logic could be improved while still ending up with the same computation result would need a service graph to work on.

Fixing your service graph looks like a good idea also.

It's one or another, sorry :)

**Comment by mussbach** [comment] 2019-12-18 22:34
I perfectly agree with you that we need to fix our service graph! We are working hard to fight it in our legacy codebase but it takes time and we definitely have much to do yet.

I tracked the reason somehow down why the graph exploded recently.

We have quite a lot of services (~200) that are partly interdependent and some of them are huge, some of them have parent services in common (e.g. FileService uses CoreService that has dependencies itself). We used setter injection for most of them. More recently we began to use DI as it should be. 

To be able to automatically use autowiring with every service I made the mistake to add `@required` to every setter that is used in DI, as otherwise these dependencies would not be set. This caused the graph explosion. 
I reverted that and we now we only require setterinjection when really necessary and use this performance issue as a tool to refactor our services and strip them down.
After that the cache creation time is bearable although slower than it was the refactoring in 3.4.19.

I do not know whether this issue is relevant at all and what to do with it (wontfix?), nevertheless I think it is important to keep in mind, that the current implementation of the `analyzeCircularReferences` may have performance issues, especially on old codebases. 

What kind of service graph could I provide that would serve you with the information you need?

**Comment by nicolas-grekas** [comment] 2019-12-18 22:54
Cool that you found a way around.
I'm closing the issue for now, waiting for more reports of the same kind before acting. Thanks for the details.

**Closed by nicolas-grekas** 2019-12-18 22:54 UTC
Labels: Performance, Status: Waiting feedback
