### ISSUE TITLE
 Performance metrics in the Symfony Profiler gone missing

### ISSUE THREAD

**Issue by sgurdiel** [symfony/symfony#42882] opened 2021-09-03 23:02 UTC
**Symfony version(s) affected**: 5.3.7

**Description**
When accesing the Performace metrics panel within the Symfony Profiler, the "Total execution time" and "Symfony initialization" widgets display "n/a" and the "Execution timeline" gant chart is empty.

**How to reproduce**
Environment var to enable debugging:
APP_DEBUG=true

**Possible Solution**
Require symfony/http-kernel version 5.3.6 instead.

**Additional context**
Check comments on the commit thats rised the bug https://github.com/symfony/http-kernel/commit/7ad80dee5ecadd342aea98169940f0450b18815b#commitcomment-55916313

**Comment by stof** [comment] 2021-09-03 23:23
Duplicate of #42804 which has already been fixed (the fix will be available in the 5.3.8 release)

**Closed as completed by stof** 2021-09-03 23:23 UTC
Labels: Bug, Status: Needs Review

**Comment by fabpot** [comment] 2021-09-07 11:03
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases
