### ISSUE TITLE
"[options] command [arguments]" should "command [options] [arguments]" in usage description

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#13536] opened 2015-01-27 15:09 UTC
if you execute

````
app/console
````

you get
![bildschirmfoto 2015-01-27 um 16 05 42](https://cloud.githubusercontent.com/assets/995707/5920676/a1aeb926-a63e-11e4-8390-c2e5956bcd7c.png)

`````
Usage:
 [options] command [arguments]
````
i think this wold be correct:
````
Usage:
 command [options] [arguments]
````
what do you think?

Best regards, Oskar

**Comment by kix** [comment] 2015-01-28 07:52
Duplicate of #13537

**Comment by stof** [comment] 2015-01-30 04:45
Closing as duplicate

**Closed by stof** 2015-01-30 04:45 UTC
