### ISSUE TITLE
YAML routing host overrides annotations

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#54211] opened 2024-03-08 20:51 UTC
### Symfony version(s) affected

6.4.3

### Description

Looking for a way to set the default hostname for routes, this [SO answer](https://stackoverflow.com/a/68128347/1041515) should be correct, but as [a comment notes](https://stackoverflow.com/questions/59410426/configure-a-default-host-for-routes-in-symfony-4#comment130995996_68128347), setting the host name in YAML clobbers any and all annotations parsed thereafter.

That is, YAML that defines an annotations/attributes resource must be parsed before the attributes:

```yaml
# config/routes/routes.yaml

controllers:
  resource:
    path: ../../src
    namespace: Foo\Bar
  type: attribute
  host: example.com
```

So it follows that logically that which is parsed later should override that which is declared earlier.

```php
#[Route(host: 'example.org')]
final class Foo extends AbstractController {}
```

Yet it does not: setting the host in YAML clobbers _all_ `Route()` attributes. Thus it appears impossible to set a default host since we are not in control of this parse order.

### How to reproduce

See above.

**Comment by smnandre** [comment] 2024-03-08 22:23
Probably not a bug as it is the [documented behaviour](https://symfony.com/doc/current/routing.html#sub-domain-routing).

> You can also set the host option when [importing routes](https://symfony.com/doc/current/routing.html#routing-route-groups) to make **all of them** require that host name.

Did you try with parameters in the host + defaults values ? (i did not tried but this seems a potential solution)

**Comment by derrabus** [comment] 2024-03-08 22:23
When importing routes, you can define settings that are applied to all imported routes. Yes, this is _not_ a default. It's an override for the whole route collection.

Closing as this is not a bug.

**Closed as not planned** 2024-03-08 22:23 UTC
Labels: Bug, Routing, Status: Needs Review

**Comment by Bilge** [comment] 2024-03-08 23:06
Well you don't need to close it, you could just convert it to a feature request.
