### ISSUE TITLE
RedisCache delete/clear not working anymore

### ISSUE THREAD

**Issue by wiseguy1394** [symfony/symfony#39280] opened 2020-12-02 08:43 UTC
**Symfony version(s) affected**: 5.2.0

**Description**  
Since updating to Symfony 5.2.0 the redis cache delete command seems to be not working anymore.
Also the command `bin/console cache:pool:clear [pool]` is not working for RedisCache-pools.

**How to reproduce**  
Redis Version 3.2.12
```php
namespace App\Cache;

use Symfony\Component\Cache\Adapter\AdapterInterface;

class TestCache
{
    /**
     * @var AdapterInterface
     */
    private $cache;
    
    public function __construct(AdapterInterface $adapter)
    {
        $this->cache = $adapter;
    }
    
    public function testCache():void
    {
        try {
            $cacheItem = $this->cache->getItem('testKey');
            $cacheItem->set(['testData']);
            $this->cache->save($cacheItem);
                
            dump($this->cache->hasItem('testKey')); // true

            $this->cache->deleteItem('testKey');

            dump($this->cache->hasItem('testKey')); // true
        } catch (\Psr\Cache\InvalidArgumentException $e) {
        }
   }
}
```

**Additional context**  
We found that there was the following change:
https://github.com/symfony/cache/commit/2cb6631f397ecbc16175e28f91710c598afa9d50

Because of CentOS 7 we are fixed to Redis Version 3.2.12-2.el7. The UNLINK Command is not available in this redis version and the following if-statement seems not to match.

**Comment by stof** [comment] 2020-12-02 09:56
@wiseguy1394 are you using the redis extension or predis ?

**Comment by wiseguy1394** [comment] 2020-12-02 09:57
@stof we are using redis extension.

**Comment by wiseguy1394** [comment] 2020-12-03 08:19
We downgraded to 5.1.9 and all works fine. The problem seems to be change in https://github.com/symfony/cache/commit/2cb6631f397ecbc16175e28f91710c598afa9d50

**Comment by nicolas-grekas** [comment] 2020-12-07 17:01
Which version of phpredis are you using?
I can't reproduce the issue with v5.3.2
You can run `php --ri redis` to figure out.

**Comment by jderusse** [comment] 2020-12-07 17:05
@nicolas-grekas redis version < 4 does not supports UNLINK  (see #39298)

edit: The comment of the issue says "Redis Version 3.2.12"

**Comment by nicolas-grekas** [comment] 2020-12-07 17:06
My question is about the version of the extension, not about the server :)

**Comment by wiseguy1394** [comment] 2020-12-07 17:06
@nicolas-grekas we are running the same version of phpredis, 5.3.2. And redis 3.2.12.

**Comment by nicolas-grekas** [comment] 2020-12-07 17:22
I just tested with phpredis v5.3.2 and redis-server v3.2.12 using `redis:3.2.12-stretch` as a base docker image and I don't reproduce the behavior. Can you help me reproduce the issue?

**Comment by wiseguy1394** [comment] 2020-12-07 17:40
I've done the following:
**Symfony 5.2.0
Redis 3.2.12
phpredis 5.3.2**

```php
<?php

namespace App\Command;

use Symfony\Component\Cache\Adapter\AdapterInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    protected static $defaultName = 'app:test:cache';

    /**
     * @var AdapterInterface
     */
    private $cache;

    public function __construct(AdapterInterface $cache)
    {
        parent::__construct();
        $this->cache = $cache;
    }

    protected function configure()
    {
        $this->setDescription('Check cache.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        try {
            dump(get_class($this->cache));
            $cacheItem = $this->cache->getItem('testKey');
            $cacheItem->set(['testData']);
            $this->cache->save($cacheItem);

            dump($this->cache->hasItem('testKey')); // true

            $this->cache->deleteItem('testKey');

            dump($this->cache->hasItem('testKey')); // true
        } catch (\Psr\Cache\InvalidArgumentException $e) {
        }

        return 0;
    }
}

```
When i run the command 
```sh
^ "Symfony\Component\Cache\Adapter\TagAwareAdapter"
^ true
^ true
```

I decorated the AdpaterInterface, don't know if it matters.

**Comment by jderusse** [comment] 2020-12-07 17:42
I reproduce the issue
```
php -v: 7.4.12
php --ri redis: 5.3.1
docker run --rm -ti --net host redis:3.2.12-stretch

symfony new --demo demo
bin/console make:command test
```

```php

    private $adapter;
    public function __construct(AdapterInterface $adapter, string $name = null)
    {
        parent::__construct($name);
        $this->adapter = $adapter;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        try {
            $cacheItem = $this->adapter->getItem('testKey');
            $cacheItem->set(['testData']);
            $this->adapter->save($cacheItem);

            dump($this->adapter->hasItem('testKey')); // true

            $this->adapter->deleteItem('testKey');

            dump($this->adapter->hasItem('testKey')); // true
        } catch (\Psr\Cache\InvalidArgumentException $e) {
        }
    }
```

**Comment by wiseguy1394** [comment] 2020-12-07 17:42
Docker:
PHP: erfmedien/php-fpm-v8js:latest
Redis: redis:3.2.12

**Comment by jderusse** [comment] 2020-12-07 18:00
note: in my case `$this->redis->unlink($ids);` does not throw an exception, but returned false ;-)

here: https://github.com/symfony/symfony/blob/9d40bd80f609fba8a329d22df20226fbf908ba14/src/Symfony/Component/Cache/Traits/RedisTrait.php#L411

**Comment by nicolas-grekas** [comment] 2020-12-08 11:06
Should be fixed now, thanks for the details.

**Closed as completed by nicolas-grekas** 2020-12-08 11:06 UTC
Labels: Bug, Status: Needs Review, Cache
