### ISSUE TITLE
TraceableEventDispatcher does not correctly replace the original prototype listener

### ISSUE THREAD

**Issue by taueres** [symfony/symfony#15476] opened 2015-08-06 10:32 UTC
### Assume this scenario
1. The symfony application registers a listener with "prototype" scope in the service container
2. The application uses `TraceableEventDispatcher`
3. The application is dispatching the event which is listened by the service defined in step 1
### What is problematic

`TraceableEventDispatcher` is trying to replace the original listener with the new `WrappedListener`.
The dispatcher correctly adds the new `WrappedListener`.
But it fails to remove the original listener.
### Actual Result

The listener's method is invoked twice:
- first call is in the `WrappedListener`
- second call is in the original listener
### Expected Result

Only one event is dispatched so only one invocation of the listener's method is expected.

**Comment by stof** [comment] 2015-08-06 10:56
Registering a listener in the prototyped scope is a bad idea already: the lazy-loading of the listener will load the object only once and then register it in the dispatcher directly. This means that using a narrower scope for the listener is technically equivalent to injecting a prototyped-scope service into a container-scoped one, which does not work. The difference is that the DI component cannot detect the invalid usage.

And the reason TraceableEventDispatcher fails to remove it is because it is receiving a different instance of the service when trying to remove it and so considers it is a different listener (which is the case).

We should actually forbid using a narrower scope for lazy-loaded references for listeners (and other places doing a similar pattern) as it simply does not work as expected by people.

Btw, what is your use case for putting this listener in the prototype scope ?

**Comment by taueres** [comment] 2015-08-06 12:33
The listener has a prototyped-scope dependency.
The container will not build when container-scoped services have prototyped-scope dependencies.

**Comment by stof** [comment] 2015-08-06 12:44
Well, what is the use case for making this dependency prototype-scoped then ?

**Comment by stof** [comment] 2015-08-06 12:45
note that in your case, the code is not working without giving you an error message, for the exact same error that injecting a prototyped scope service into a container-scoped one does not work (except we are currently able to detect such case early while we don't check it for listener)

**Comment by Jean85** [comment] 2015-08-06 12:57
I think we can assume that any prototype-scoped service could be refactorized to a non-prototype-scoped one; on the other hand, we will always have to wrestle with legacy code, so killing altogether the prototype functionality isn't an option.

That said, I think the scenario proposed by @taueres should be avoided at runtime, at least with one of this interventions:

 * `TraceableEventDispatcher` throws an exception if it can't remove a listener, so no duplicates
 * `TraceableEventDispatcher` throws an exception when used on a prototyope-scoped listener (dunno if this is feasible)
 * `WrappedListener` isn't added if the original listener hasn't been removed (dunno about it too)

Do you think there are other possible solutions?

**Comment by taueres** [comment] 2015-08-06 13:02
I've read the docs and I didn't find any warning about using prototyped-scoped listeners.
I think some references will be useful for the future.

**Comment by stof** [comment] 2015-08-06 13:07
The issue is that a listener is a dependency of the dispatcher, even if the container does not know about it.
None of the solution would work here properly IMO (at least not without making the TraceableEventDispatcher much more complex and aware of the container, which is not something we want).

Thus, the TraceableEventDispatcher is not the only place which could break because of this (injecting a narrower-scoped service into a wider-scoped service in any way working around the container validation will create nasty issues very hard to debug)

The proper fix would be to forbid using scoped services as listeners, by validating the scope when registering listeners (this is the right place to do it). However, this would mean that @taueres would still have to refactor their code.

**Comment by Algatux** [comment] 2015-08-06 13:38
@stof I think that if the original listener is not removed, it can't be unnoticed, at least an exception must be thrown.

**Comment by nicolas-grekas** [comment] 2017-07-28 14:55
Since scopes are deprecated, and give this issues dates from 2015, I think we can close it :)

**Comment by jakzal** [comment] 2017-10-25 10:28
Closing as this is a rather rare use case (given not many contributed to the discussion) and the prototype scope is being removed.

**Closed by jakzal** 2017-10-25 10:28 UTC
Labels: EventDispatcher
