### ISSUE TITLE
The "hasCacheableSupportsMethod()" method is deprecated, implement "getSupportedTypes()" instead

### ISSUE THREAD

**Issue by oojacoboo** [symfony/symfony#54689] opened 2024-04-22 06:52 UTC
### Symfony version(s) affected

6.4.x

### Description

It seems as though this deprecation notice is thrown every single time `getSupportedTypes` is called, and I assume this is called internally.

```php
    public function getSupportedTypes(?string $format): array
    {
        return ['object' => __CLASS__ === static::class || $this->hasCacheableSupportsMethod()];
    }

    /**
     * @deprecated since Symfony 6.3, use "getSupportedTypes()" instead
     */
    public function hasCacheableSupportsMethod(): bool
    {
        trigger_deprecation('symfony/serializer', '6.3', 'The "%s()" method is deprecated, implement "%s::getSupportedTypes()" instead.', __METHOD__, get_debug_type($this));

        return __CLASS__ === static::class;
    }
```

Upgrading to 7.0, where I see the call to `hasCacheableSupportsMethod` has been removed, isn't an option for us at the moment.  I realize maybe most people ignore these - not sure.  But deprecation errors are designed to halt our application and we prefer it that way.

I had to report a similar issue on the last major round of deprecations.  It'd be nice if testing around these could ensure that they are "silenceable" - like it can be accomplished, without forking the lib, that is.

### How to reproduce

https://github.com/symfony/serializer/blob/6.4/Normalizer/ObjectNormalizer.php

### Possible Solution

Remove the call to `hasCacheableSupportsMethod` and target 6.4.x

**Comment by xabbuh** [comment] 2024-04-22 06:57
Symfony 6.3 is not supported anymore. Do you still observe the same behaviour on 6.4? If so, please create a small example application that allows to reproduce it.

**Comment by oojacoboo** [comment] 2024-04-22 06:59
This is 6.4.  The deprecation error is mildly confusing.

**Comment by nicolas-grekas** [comment] 2024-04-22 07:12
The deprecation is triggered only if the class is overridden but the getSupportedTypes method is not implemented by child classes. Implementing this method is how you work around the deprecation.

**Comment by oojacoboo** [comment] 2024-04-22 07:23
> The deprecation is triggered only if the class is overridden but the getSupportedTypes method is not implemented by child classes. Implementing this method is how you work around the deprecation.

Why is forcing that to be implemented the proper implementation route?  I guess the deprecation error message could certainly be more explicit here.  If I'm not calling `hasCacheableSupportsMethod` directly, why throw a deprecation error?  That's something that should be sorted by Symfony internals.

Additionally, in 7.0, the implementation of `getSupportedTypes` is inherited and not required to be overridden.

**Comment by nicolas-grekas** [comment] 2024-04-22 07:27
The methods allow the serializer to know how to properly cache normalizers. Implementing the methods is how the implementations expose this info. getSupportedTypes is the replacement for hasCacheableSupportsMethod.
There is nothing more we can do internally since we cannot guess what child classes do.

**Comment by oojacoboo** [comment] 2024-04-22 07:31
Seems like it'd be abstract if child classes should implement it.  Anyway, thanks for the insight.

**Comment by chalasr** [comment] 2024-04-23 17:26
Closing as per https://github.com/symfony/symfony/issues/54689#issuecomment-2068674992

**Closed as completed by chalasr** 2024-04-23 17:26 UTC
Labels: Serializer, Bug, Status: Needs Review, Status: Waiting feedback
