### ISSUE TITLE
SYMFONY_DEPRECATIONS_HELPER has no affect when defined in phpunit.xml.dist.

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#28726] opened 2018-10-04 12:29 UTC
**Symfony version(s) affected**: 4.1.5

**Description**  

Adding `<env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />` to `phpunit.xml.dist` has no affect.

**How to reproduce**  

Install the symfony skeleteon
```
composer create-project symfony/skeleton:4.1.* bug_app
cd bug_app
composer require --dev "symfony/phpunit-bridge:*"
php bin/phpunit
```

Add `<env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />` to [phpunit.xml.dist](https://github.com/leevigraham/symonfy-phpunit-bridge/blob/master/phpunit.xml.dist#L18)  as per the [configuration docs](https://symfony.com/doc/current/components/phpunit_bridge.html#configuration). 

Create a new DeprecatedTest: https://github.com/leevigraham/symonfy-phpunit-bridge/blob/master/tests/DeprecatedTest.php

```
<?php

namespace App\Tests;

use PHPUnit\Framework\TestCase;

class DeprecatedTest extends TestCase
{
    public function testDeprecatedCode()
    {
        @trigger_error('This "Foo" method is deprecated.', E_USER_DEPRECATED);
        @trigger_error('The second argument of the "Bar" method is deprecated.', E_USER_DEPRECATED);
    }
}
```

Run `php bin/phpunit` again. Deprecation notices are shown.

Example Repo: https://github.com/leevigraham/symonfy-phpunit-bridge

**Additional context**  

Screenshot of issue:

![image](https://user-images.githubusercontent.com/25124/46473665-3fd37280-c824-11e8-8bff-ec6daa220da0.png)

Running `SYMFONY_DEPRECATIONS_HELPER=disabled php bin/phpunit` produces expected output:

![image](https://user-images.githubusercontent.com/25124/46473893-de5fd380-c824-11e8-9b58-d33b297e430a.png)

// @nicolas-grekas

**Comment by mark-gerarts** [comment] 2018-10-04 20:01
I'm guessing [this commit](https://github.com/symfony/recipes/commit/54939f7ae8b9bb5821fc1bcce2babfa43daca833#diff-bbc808450c0f3f12f5cec14fc21afc94) is part of the issue. A solution would be to revert this commit and move this functionality to `simple-phpunit`, where we could do something like

```
$deprecationsHelper = $getEnvVar('SYMFONY_DEPRECATIONS_HELPER', '999999');
putenv("SYMFONY_DEPRECATIONS_HELPER=$deprecationsHelper");
```

I'd be happy to open up a PR for this, if I'm thinking in the right direction :)

**Comment by nicolas-grekas** [comment] 2018-10-04 20:05
Duplicate of #28519? See there for some background at least.

**Comment by leevigraham** [comment] 2018-10-04 23:56
I don't think this is a duplicate of #28519. Any set value is not applied. 

@mark-gerarts could be on the right track… I don't see anywhere in code where the phpunit.xml is checked for `SYMFONY_DEPRECATIONS_HELPER` before setting up the `DeprecationErrorHandler` in `bin/.phpunit/phpunit-6.5/vendor/symfony/phpunit-bridge/bootstrap.php`

**Comment by nicolas-grekas** [comment] 2018-10-05 06:42
OK, understood. There are two ways to achieve what you'd like:
- edit the bin/phpunit file and set the value here. That's what I would recommend because it's very early in the bootstrapping process, as it should. This file is yours so you can and should edit it when needed.
- add `force="true"` to the phpunit.xml `<env>` tag.

**Comment by curry684** [comment] 2018-10-16 17:34
I found this issue today after being highly surprised that in a colleague's project the `disabled` value didn't appear to do anything (still got 50+ vendor deprecation notices we don't care about in that project right now). The project was on 4.1.6 and the linked issue was supposedly fixed in 4.1.5, so it's indeed still an issue to some extent. We did notice different behavior between `weak` and `weak_vendors` so it's not being ignored completely, just `disabled` seems to do the same as `weak` right now.

I don't think the workarounds above are really acceptable for a long term solution.

**Comment by leevigraham** [comment] 2018-10-16 23:20
> edit the bin/phpunit file and set the value here. That's what I would recommend because it's very early in the bootstrapping process, as it should. This file is yours so you can and should edit it when needed.

That's what I ended up doing.

**Comment by olia-bn** [comment] 2018-10-17 07:53
> We did notice different behavior between `weak` and `weak_vendors` so it's not being ignored completely

Memory played a trick on you, there was no difference between `weak`, `weak_vendors` and `disabled`.

**Comment by nicolas-grekas** [comment] 2018-11-09 18:18
fixed at the recipe level in https://github.com/symfony/recipes/pull/481

**Closed by nicolas-grekas** 2018-11-09 18:18 UTC
Labels: PhpUnitBridge
