### ISSUE TITLE
Validation Groups not taken into account with NotBlank Annotation when generating a form

### ISSUE THREAD

**Issue by rrajkomar** [symfony/symfony#15314] opened 2015-07-20 07:44 UTC
When creating a form type class with a default validation_group (using validation_groups key in default options array), I found that the specified group is not taken into account when generating the form for the NotBlank assert annotation (and most liekly the NotNull one as well).

When adding a NotBlank assert annotations to a model (or entity) class with a group application filter (groups attribute for the annotation) and generating a form view for this class (via a form type specifying the default validation group or another validation group), the Not Blank annotation is always processed before rendering the form and the field always ends up with a require="required" attribute.

The validation_groups options of the form type class should always be taken into account when generating a form. Right now it is not correctly processed and the generated form does not match the expected result ; the only way I found to fix this behaviour without going into the symfony core classes was to render each field using an attribute "required" => false when rendering the field using the form_(row|widget) twig tag.

**Comment by adamziel** [comment] 2015-07-23 00:05
AFAIK Validator component is completely separate from the form framework. The "required" attribute is explained in here:

http://symfony.com/doc/current/book/forms.html#field-type-options


Basically you either need to mark the whole form as "novalidate" if you are not interested in HTML5 validation, or set `"required" => false` on each individual field in your form Type class or in the twig template responsible for rendering your form.

**Comment by alterphp** [comment] 2015-07-27 13:37
I encounter the same issue with following entity property :

```php
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="string", length=255)
     * @Assert\Length(max=140, groups={"front.chat"})
     * @Assert\Length(max=255, groups={"admin.creation", "admin.edition"})
     */
    protected $content;
```

When rendering a form with __admin.creation__ validation group, it's automatically rendered with a __50__ maxlength HTML attribute's value. I tnink the Guesser is not aware of enabled validation group, so that it does not filter on active constraints...

**Comment by WouterJ** [comment] 2015-07-27 14:22
This is a duplicate of https://github.com/symfony/symfony/issues/2387, which was closed as duplicate of https://github.com/symfony/symfony/issues/7868

While fixing #7868, a way should be added to read the form options in the guesser, which will make the validator guesser aware of the `validator_group` option. At the moment, as you already showed, it isn't.

**Comment by jakzal** [comment] 2015-07-30 16:39
Closing as a duplicate.

**Closed by jakzal** 2015-07-30 16:39 UTC
