### ISSUE TITLE
InputOption VALUE_OPTIONAL does not use default value

### ISSUE THREAD

**Issue by jesse-hostnet** [symfony/symfony#29228] opened 2018-11-15 15:45 UTC
**Symfony version(s) affected**: `symfony/console`, (at least) 4.1

**Description**  
When not giving a value to an option with VALUE_OPTIONAL, one would expect the option to gain the default value; instead, the option value is `null`.

**How to reproduce**  
```php
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\NullOutput;

class CommandOptionDefaultValueTest extends TestCase
{
    public function testCommandDefaultValueForOptionalOptionValues()
    {
        self::assertSame(
            0,
            (new Command())->setName('test')
                ->addOption(
                    'option',
                    'o',
                    InputOption::VALUE_OPTIONAL,
                    'Optional option!',
                    'This should be the default value...'
                )
                ->setCode(function(InputInterface $input): int {
                    if ($input->getOption('option') === null) {
                        throw new \InvalidArgumentException(
                            '...but instead, the default became `null`!'
                        );
                    }
                    return 0;
                })
                ->run(new StringInput('--option'), new NullOutput())
        );
    }
}
```

**Possible Solution**  
Use the available default value when an optional value is not provided.

**Additional context**  
The current behaviour is potentially problematic, especially for options with a "true-ish" default value: When providing options such as `dry-run` or `only-validated` with a default value of `true`, one would expect that running: `command --dry-run` will make a dry run, and `command --only-validated` will only process the validated data.

This assumption is exceptionally easily made when the option explicitly declares its default value to be `true`.

What happens in reality, however, is the following:
- the option value is missing, thus becoming `null`
- the if-statement (eg. `if ($input->getOption('dry-run'))`) considers null to be false
- `command --dry-run` does not make a dry run
- hell breaks loose

Note: When not adding the option at all, the default value *is* used as expected.

**Comment by ro0NL** [comment] 2018-11-15 16:10
ref #21228

**Comment by stof** [comment] 2018-11-15 16:10
a `--dry-run` option is probably a VALUE_NONE option, not a VALUE_OPTIONAL, as it is a flag

**Comment by stof** [comment] 2018-11-15 16:14
btw, if you don't pass the option *at all*, `$input->getOption('dry-run')` returns the default value. So what you are asking is to make it impossible to distinguish the case of passing an option without value or not passing it, for VALUE_OPTIONAL. That's exactly what was fixed in the PR linked by @ro0NL.

I think the root cause here is a misunderstanding of the difference between VALUE_OPTIONAL and VALUE_NONE (VALUE_OPTIONAL are actually the less common options in my experience. Most cases are either VALUE_NONE or VALUE_REQUIRED)

**Comment by jesse-hostnet** [comment] 2018-11-15 16:52
> a `--dry-run` option is probably a VALUE_NONE option, not a VALUE_OPTIONAL, as it is a flag

This example could indeed be VALUE_NONE, if indeed it's always considered boolean. If it might have other values, ie. `--dry-run=only-on-monday`, VALUE_NONE would not be suitable.

I fully agree that my examples might have been overly simplistic.

> So what you are asking is to make it impossible to distinguish the case of passing an option without value or not passing it, for VALUE_OPTIONAL.

I think that's a misrepresentation of the issue: what I'm asking is simply to receive the default value when no value is provided.

In fact, I fully agree that there ought to be a way to distinguish between an empty option and a missing option. However, relying on the option value to figure out whether the option was empty or missing is, at least in my opinion, a misuse of the concept of default values.

In the current implementation, it is still impossible to distinguish between a missing- and empty option in the cases where the option has `null` as default value. Hence, the current implementation is not complete in its ability to distinguish between those input methods.

Besides being incomplete, it also causes the confusion mentioned in this issue.
If having a way to distinguish between missing and empty options is indeed important, I'd suggest a method in the spirit of `hasProvidedOption(string $name)`.

Additionally, the current implementation is rather counter-intuitive, since `isset($input->getOption('option'))` returns `false` when the option *is* provided, and true when it is *not*.

**Comment by ro0NL** [comment] 2018-11-15 17:00
> what I'm asking is simply to receive the default value when no value is provided

`$input->getOption('name') ?? $someDefault`?

Also i think you're confusing has/getOption vs. has/getParameterOption()

> Additionally, the current implementation is rather counter-intuitive, since isset($input->getOption('option')) returns false when the option is provided, and true when it is not.

That's why there are hassers, as null is a possible valid value.

**Comment by jesse-hostnet** [comment] 2018-11-15 18:29
> That's why there are hassers, as null is a possible valid value.

I might misunderstand what you're saying, but according to the docblock in `InputDefinition`, `hasOption` actually means `allowsOption`, while at the same time `hasParameterOption` states that it "Does not necessarily return the correct result for short options when multiple flags are combined in the same option."

Assuming these "hassers" *are* a good way to check if the option was given, there's no problem in distinguishing an empty option from a missing one.

> $input->getOption('name') ?? $someDefault?

I suppose I could use `$input->getOption('name') ?? $this->getDefinition()->getOption('name')->getDefault()`, but I'm of the opinion that such a solution would seriously impede the readability of my code.

Why should I need to redefine a default value in the middle of my command code, when I've also defined it in the option definition?

**Comment by ro0NL** [comment] 2018-11-15 18:53
I think you're looking for VALUE_REQUIRED then :) So you'll either get the default value or (non-empty) given value.

VALUE_OPTIONAL, as hinted by its name, allows for empty values (null) and can be explicitly given usimg  `cmd --option`

**Comment by chalasr** [comment] 2018-11-25 14:51
As explained, when defining an option as `VALUE_OPTIONAL` and passing that option with an empty value, it's expected that `getOption()` returns the empty value and not the default.
Forbidding empty values can be achieved by using mode `VALUE_REQUIRED` instead, as suggested by @ro0NL. 
Closing here as this is not a bug.

**Closed by chalasr** 2018-11-25 14:51 UTC
Labels: Bug, Console, Status: Needs Review
