### ISSUE TITLE
Label Hiding Problem In Symfony Form

### ISSUE THREAD

**Issue by rrpatil761** [symfony/symfony#19772] opened 2016-08-29 11:10 UTC
Following is code to generate form.

```php
 $builder->add(
            'hearAboutUs', 'choice', [
                'choices' => ['Online Search'=>'Online Search',
                    'Email'=> 'Email',
                    'My Company' => 'My Company',
                    'Colleague or Friend'=>'Colleague or Friend',
                    'Existing Client' =>'Existing Client',
                    'Direct Mail' => 'Direct Mail',
                    'Other'=> 'Other',],
                'label' => 'How did you hear about us?',
                'required' => true,
                'expanded'=> true,
                'multiple' => false,
            ]
        );
```

Above form's output looks like below, where label is not showing at all
![output](https://cloud.githubusercontent.com/assets/17875166/18049629/177eccea-6e07-11e6-9b32-3e70e8342114.png)
If I comment 'expanded'=> true then label will show but instead of radio it looks like choice box.

**Comment by rrpatil761** [comment] 2016-08-29 11:40
Any Update Please?

**Comment by wouterj** [comment] 2016-08-29 11:56
@rrpatil761 you posted this issue just an hour ago. Please be patient, the Symfony project is maintained mostly be volunteers.

If you want support to fix your problem quickly, consider paid support or one of the (again volunteer-run) other support channels on http://symfony.com/support

**Comment by rrpatil761** [comment] 2016-08-29 12:01
Thanks for the update :)

**Comment by dmaicher** [comment] 2016-08-29 17:33
Can you reproduce the issue on a clean symfony standard edition fork? https://github.com/symfony/symfony-standard

**Comment by HeahDude** [comment] 2016-08-29 17:54
Could you please show the code of your template generating this field?

**Comment by rohitpatil-tudip** [comment] 2016-08-30 06:31
Following is a code for view,
![view](https://cloud.githubusercontent.com/assets/13351853/18078390/e4a692c4-6ea8-11e6-8ef7-745e67e77a6d.png)
Following is a code for Entity,
![updatedentity](https://cloud.githubusercontent.com/assets/13351853/18078428/125ead96-6ea9-11e6-8cd8-17a76d1957db.png)
Following is output,
![label_missing](https://cloud.githubusercontent.com/assets/13351853/18078438/27b1f824-6ea9-11e6-8003-1afa377be529.png)

**Comment by HeahDude** [comment] 2016-08-31 09:33
What about @dmaicher question:
>Sure you have no custom form theming going on that could cause it?

?

**Comment by rohitpatil-tudip** [comment] 2016-08-31 15:53
For now, I have handled this using JQuery. On Form Load I am appending Label and for required I have handled this on the controller. But this is not proper solution, but by this way my problem solved.

**Comment by HeahDude** [comment] 2016-08-31 15:58
If your bug is not reproducible we can't help you :(

**Comment by jakzal** [comment] 2016-09-07 15:10
@rrpatil761 @rohitpatil-tudip any news on how to reproduce the problem? Otherwise we shall close this issue.

**Comment by xabbuh** [comment] 2016-09-27 20:32
Closing due to the lack of feedback.

**Closed by xabbuh** 2016-09-27 20:32 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed
