### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by wopl** [symfony/symfony#37264] opened 2020-06-13 09:25 UTC
I haven't touched an application for a while (running fine so far). Now I upgraded from Symfony 5.02 to 5.1.1.
My application is not starting anymore but gets Exception `Serialization of 'Closure' is not allowed`. It shows the error in public.index.php (line 25) (3rd / middle line below):

`$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);`
`$request = Request::createFromGlobals();`
`$response = $kernel->handle($request);`
`$response->send();`
`$kernel->terminate($request, $response);`

And within the logs a critical request: 
`Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at /Users/wopl/dev/wpt4/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 268`
`{
    "exception": {}
}`

Could s.o. guide me to find the root of this? Happy to provide more info, but my Symfony knowledge is quite limited. 
Thanks, Wolfram

**Comment by nicolas-grekas** [comment] 2020-06-13 09:59
I'm closing as duplicate of #37050
There is a question there, could you please answer it maybe?

**Closed by nicolas-grekas** 2020-06-13 09:59 UTC
