### ISSUE TITLE
[YAML] Question about array dumping

### ISSUE THREAD

**Issue by nerdstein** [symfony/symfony#16266] opened 2015-10-16 22:11 UTC
I have a YML file that I parse, which has the following syntax for an empty array:

`some_field: [ ]`

Upon dumping the same YML file, and not adjusting `some_field`, the value is dumped as:

`some_field: { }`

My understanding is that the `{ }` syntax is intended for objects, not arrays. As such, I isolated the code found in the `dumpArray` function which was introducing this behavior:

https://github.com/symfony/yaml/blob/2.8/Inline.php#L191

`return sprintf('{ %s }', implode(', ', $output));`

.... adjusted to ....

`return sprintf('[ %s ]', implode(', ', $output));`

... fixes this issue. 

Is there a reason why this is using the object-based syntax and not the array syntax?

**Comment by WouterJ** [comment] 2015-10-16 22:39
See https://github.com/symfony/symfony/pull/16267 for a fix. The problem was that the method filtered the array keys on whether it has only numeric keys (in which case a Yaml sequence should be dumped) or some string keys as well (in which case a Yaml mapping (`{}`) should be dumped). When an empty array was passed, the filter algorithm decided it always was a mapping. In the PR, I changed it to always consider it a sequence when an empty array is passed.

**Comment by nerdstein** [comment] 2015-10-16 22:42
@WouterJ, I am currently using 2.8. Will your patch also be applied to that version?

**Comment by xabbuh** [comment] 2015-10-18 12:22
This looks like a duplicate of #9870 to me.

**Closed** 2016-01-25 12:30 UTC
Labels: Yaml

**Comment by xabbuh** [comment] 2016-02-08 23:04
see #17728
