### ISSUE TITLE
[Cache] No exception is thrown when caching closure

### ISSUE THREAD

**Issue by k0nst1** [symfony/symfony#43895] opened 2021-11-03 07:23 UTC
### Symfony version(s) affected

4.4

### Description
When using the a Cache Pool (happens with CacheItemPoolInterface and CacheInterface) and trying to cache something with the that contains a closure, the marshaller tries to serialize it and runs into an exception. The exception is never handled or logged. 

### How to reproduce

Store something that contains a closure into the cache. In my case it was a getInfo() on a ResponseInterface.

### Possible Solution

Handle the exception or pass it down to the adapter so it can be seen.

**Comment by zeh-nagel** [comment] 2021-11-03 08:37
possible test case
```php
class CacheTest extends PHPUnit\Framework\TestCase
{
    public function testCacheWithClosure(): void
    {
        $fileSystemAdapter = new \Symfony\Component\Cache\Adapter\FilesystemAdapter();
        $cache = new \Symfony\Component\Cache\Psr16Cache($fileSystemAdapter);

        $cache->set('test', function () {
            return 'testValue';
        });

        $this->assertTrue($cache->has('test'));
        $this->assertSame('testValue', $cache->get('test'));
    }
}
```

exception is catched here: vendor/symfony/cache/Marshaller/DefaultMarshaller.php:49

**Comment by nicolas-grekas** [comment] 2021-11-03 08:58
Closing as duplicate of #41685
See #43148 also

**Closed as completed by nicolas-grekas** 2021-11-03 08:58 UTC
Labels: Bug, Status: Needs Review, Cache
