### ISSUE TITLE
You have requested a synthetic service ("request"). The DIC does not know how to construct this service.

### ISSUE THREAD

**Issue by SahnounM91** [symfony/symfony#19857] opened 2016-09-05 10:21 UTC
when I've install the phpexcel and update the composer this error is occurred, I tried to clear the cache but the error appeared again.

**Comment by hhamon** [comment] 2016-09-05 11:45
Same error for me.

**Comment by alexislefebvre** [comment] 2016-09-05 11:58
Here is a similar error I had with Symfony 2.8.10 : 

    [Mon Sep 05 13:50:05 2016] [error] [client …] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException' with message 'You have requested a synthetic service ("request"). The DIC does not know how to construct this service.' in /var/www/…/app/cache/prod/appProdProjectContainer.php:2194
    Stack trace:
    #0 /var/www/…/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(313): appProdProjectContainer->getRequestService()
    #1 /var/www/…/app/cache/prod/appProdProjectContainer.php(3677): Symfony\\Component\\DependencyInjection\\Container->get('request', 2)
    #2 /var/www/…/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(208): appProdProjectContainer->synchronizeRequestService()
    #3 /var/www/…/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(82): Symfony\\Component\\DependencyInjection\\Container->set('request', NUL in /var/www/…/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 95

Forcing the 2.8.9 version of Symfony in composer.json fixes the problem.

**Comment by alexislefebvre** [comment] 2016-09-05 12:42
It looks like it's a duplicate of https://github.com/symfony/symfony/issues/19840.

**Comment by jakzal** [comment] 2016-09-05 12:56
Closing as a duplicate.

**Closed by jakzal** 2016-09-05 12:56 UTC
