### ISSUE TITLE
symfony-messgaer from serialized data because its constructor requires parameter "content" to be present.

### ISSUE THREAD

**Issue by acodercat** [symfony/symfony#29902] opened 2019-01-16 09:16 UTC
**Symfony version(s) affected**: 4.2

**Description**  
use AQMP
symfony-messgaer f Cannot create an instance of App\Infrastructure\Message\SmsNotification from serialized data because its constructor requires parameter "content" to be present.

**How to reproduce**  
```php
class SmsNotification
{
    private $content;

    public function __construct(string $content)
    {
        $this->content = $content;
    }

}
```

**Comment by xabbuh** [comment] 2019-01-16 11:01
I guess you need a normalizer here that is able to determine that the content needs to be passed as a constructor argument.

**Comment by Koc** [comment] 2019-01-19 11:17
Looks like you forgot add getters for content property. Without this getters message serializes in empty json (`{}`) and cann't unserialize in future.

**Comment by devrck** [comment] 2019-01-23 10:46
Maybe https://symfony.com/doc/current/components/serializer.html#handling-constructor-arguments this can help?

**Comment by xabbuh** [comment] 2019-01-23 11:14
I am closing here as this rather looks like a configuration issue than a bug. Thank you for understanding.

@acodercat Please let us know if that doesn't solve it and best provide a few example steps to reproduce if you don't agree and we can consider to reopen.

**Closed by xabbuh** 2019-01-23 11:14 UTC
Labels: Bug, Messenger, Status: Needs Review
