### ISSUE TITLE
[HttpFoundation] Impossible to send a response without "Content-type" header

### ISSUE THREAD

**Issue by eugene-dounar** [symfony/symfony#12744] opened 2014-11-29 13:57 UTC
PR #11244 removes "Content-type" header for 204, 304 and informational responses. This makes PHP SAPI add a default "Content-type: text/html; charset=UTF-8" for every such request.

I believe this is confusing and not working as intended. 

We can fix this with a following hack in `sendHeaders()` but it only works on 5.4+:
```php
header_register_callback(function() {
    header_remove('Content-type');
});  
```

**Comment by fabpot** [comment] 2015-01-02 09:47
It looks like a PHP bug as #11244 fixes the Response headers according to the RFC.

**Comment by jakzal** [comment] 2016-03-11 10:40
@eugene-dounar this behaviour can be disabled in php.ini by setting [`default_mimetype`](http://php.net/manual/en/ini.core.php#ini.default-mimetype) to an empty value. At least this is what docs say. Setting it to an empty value will make PHP returns an empty `content-type` header (contrary to what documentations claims that it won't include the hader at all).

Anyway, closing here since this is a confirmed PHP bug: https://bugs.php.net/bug.php?id=70189.

**Closed by jakzal** 2016-03-11 10:40 UTC
Labels: Bug, HttpFoundation, Status: Needs Review, Unconfirmed
