### ISSUE TITLE
[DependencyInjection] Bad error message for unused bind under _defaults

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#27828] opened 2018-07-03 13:31 UTC
**Symfony version(s) affected**: 3.4

**How to reproduce**  

Bind a value beneath `_defaults` or `_instanceof`:

```yml
# config/services.yaml
services:
    _defaults:
        # ...
        bind:
            $variableName: 'someValue'
```

If this bind is not actually used, the error is attached to the last service that the rule was applied to. So, something like:

> Unused binding "$variableName" in service ".abstract.instanceof.App\Twig\AppExtension". 

A better error would be:

> You have a "bind" configured for an argument named $variableName. But, this argument was not found in any of the services it was applied to. The bind may be unused and can be removed. Or, the bind may have a typo.

**Comment by nicolas-grekas** [comment] 2018-07-03 20:01
See #27834 for the noisy `.abstract.instanceof.` prefix.

On the implementation side, here is an idea: in loaders, track changes to bindings as already do for e.g. "public". When no changes is recorded but bindings are found on a definition, it means they come from some "defaults". When changes were recorded for a definition, the binding was on the definition itself.

PR welcome :)

**Comment by Loupax** [comment] 2018-07-25 08:34
Not 100% sure it's related, if not I'll create a different issue.

This also happens when you bind a variable to a specific service. In my case where I inject my dependencies on the controller actions rather than the controller constructor what happens is the following:

services.yml:
```
App\Controller\UIController:
        bind:
            $displayCurrencies: '%display_currencies%'
```
UIController.php

```
namespace App\Controller;

final class UIController extends Controller{
    public function myAction(Request $request, $displayCurrencies){
      ...
    }
}
```

After the latest update I started getting the error mentioned on the issue, even the bound variable is actually used

**Comment by nicolas-grekas** [comment] 2018-07-25 08:36
@Loupax see #28041

**Comment by przemyslaw-bogusz** [comment] 2018-12-27 01:13
I have tried to implement the solution proposed by @nicolas-grekas and the problem is that in **YamlFileLoader**, both, binds from defaults and binds from a service are merged before being set on a definition: https://github.com/symfony/symfony/blob/3be04455967170f63a7aaa01da5600a1746b5153/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L551-L564
As I understand, in order to implement the solution, we would have to ignore the merge and set the binds in two passes in order to track a change. Regardless of the fact, if ignoring the merge is a good idea, this solution does not solve the problem completly. Please consider a following configuration:
```yaml
# config/services.yaml
services:
    _defaults:
        # ...
        bind:
            $defaultsVariable: 'defaultsValue'
    _instanceof:
        App\Controller\DefaultController:
            bind:
                $instanceVariable: 'instanceValue'
    App\Controller\DefaultController:
        bind:
            $serviceVariable: 'serviceValue'
```
In this case, a bind may come from three different places, and thus maybe it would be a good solution to offer three different error messages? This can be achieved by adding an extra parameter to **BoundArgument.** However, this either requires, either:
1. passing an extra parameter in **YamlFileLoader** when calling  **$definition->setBindings**, or
2. adding a property to **Definition** (e.g. bindOrigin) which could be set before calling **setBindings.**

Taking into account Symfony's performance, am I correct in assuming, that the first solution is better?

**Comment by Arkemlar** [comment] 2019-02-14 17:10
I just updated symfony:
`- Updating symfony/dependency-injection (v4.2.2 => v4.2.3): Loading from cache`
Before update I had no errors about unused default bindings, but after update they appeared.

**Comment by spackmat** [comment] 2019-02-15 12:54
@Arkemlar In my case (also updated to 4.2.3), the error is simply wrong, as the bound parameter is used by a service. In this case:

services.yaml:

    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: false
            bind:
                string $defaultLocale: '%kernel.default_locale%'
        App\EventSubscriber\:
            resource: ../src/EventSubscriber

In src/EventSubscriber/LocaleSubscriber.php:

    public function __construct($defaultLocale = 'de')

Solution was to chance the constructor signature to

    public function __construct(string $defaultLocale = 'de')

This way, the binding works again. Before 4.2.3 this was not a problem. Maybe this is helpful for your problem, too.

**Comment by przemyslaw-bogusz** [comment] 2019-02-21 00:49
@spackmat In your example you are binding by type and name, so the exception message is correct, because your initial configuration indicated, that you wanted to bind a certain value to an argument named `$defaultLocale`, but only when it was typehinted as `string`.

If you put just:
```yaml
bind:
    $defaultLocale: '%kernel.default_locale%'
```
in your configuration, it would also solve the problem as the value would be bound to any argument named `$defaultLocale`, regardless of its type.

@Arkemlar What's the service configuration in your case?

**Comment by spackmat** [comment] 2019-02-21 15:37
@przemyslaw-bogusz Sorry, my "wrong" was misleading. Of course there was an error in my code. It was meant from the point of view that before 4.2.3, it worked even with this kind of mistake.

**Closed** 2019-04-07 10:27 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, ⭐️ EUFOSSA Hackathon
