### ISSUE TITLE
Profiler time and timeline empty with symfony/http-kernel 5.3.7

### ISSUE THREAD

**Issue by jbonnier** [symfony/symfony#43089] opened 2021-09-18 17:06 UTC
**Symfony version(s) affected**: 5.3.7

**Description**

When updating symfony/http-kernel from 5.3.6 to 5.3.7 the profiler time and execution timeline are empty.

**How to reproduce**
```shell
symfony new --dir .
symfony composer require profiler symfony/http-kernel:5.3.6
symfony serve -d
```

Load the page: the profiler should be good.

```shell
symfony composer require symfony/http-kernel:5.3.7
```

Load the page: the profiler has no load time nor execution timeline.

**Additional context**

![image](https://user-images.githubusercontent.com/14863969/133896493-5b8576a6-56d6-48b7-95ab-a6b766d0584f.png)
![image](https://user-images.githubusercontent.com/14863969/133896499-18bc5ea7-0192-41b6-9deb-bc3d939680d4.png)

**Comment by derrabus** [comment] 2021-09-18 17:46
Duplicate of #42804

**Closed as completed** 2021-09-18 17:46 UTC
Labels: Bug, Status: Needs Review
