### ISSUE TITLE
[Twig] Namespaced paths mistaken for service name

### ISSUE THREAD

**Issue by numediaweb** [symfony/symfony#42157] opened 2021-07-16 13:08 UTC
**Symfony version(s) affected**: 5.2.11

**Description**
When I reference one of my bundle templates inside the `services.yaml` as a parameter: Symfony thinks it is a service!
This causes an error

**How to reproduce**
Following the docs on [bundle templates](https://symfony.com/doc/current/templates.html#bundle-templates), I have a template inside my bundle's `templates` folder that I can reference inside my controllers as `@myBundle/Email/Confirmation.html.twig`. Now, I want to reference this template as a parameter inside my services yaml file and pass it to my service:
```
# myBundle/config/services.yml
parameters:
    email_tpl.confirmation: '@myBundle/Email/Confirmation.html.twig'

services:
    myBundle\Mailer:
        arguments:
            - { confirmation: '%email_tpl.confirmation%'}
```

But this results in the error:

```
The service "myBundle\Mailer" has a dependency on a non-existent service "myBundle/Email/Confirmation.html.twig".
```

**Comment by stof** [comment] 2021-07-16 14:11
Can you share the stack trace of the exception ?

**Comment by numediaweb** [comment] 2021-07-16 16:25
@stof 
Here's the Stack Trace of the `ServiceNotFoundException`:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
The service "myBundle\Mailer" has a dependency on a non-existent service "myBundle/Email/Confirmation.html.twig".

  at /var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:90)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:40)
  at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process()
     (/var/www/project/vendor/symfony/dependency-injection/Compiler/Compiler.php:91)
  at Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
     (/var/www/project/vendor/symfony/dependency-injection/ContainerBuilder.php:736)
  at Symfony\Component\DependencyInjection\ContainerBuilder->compile()
     (/var/www/project/vendor/symfony/http-kernel/Kernel.php:541)
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (/var/www/project/vendor/symfony/http-kernel/Kernel.php:780)
  at Symfony\Component\HttpKernel\Kernel->preBoot()
     (/var/www/project/vendor/symfony/http-kernel/Kernel.php:183)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/var/www/project/public/index.php:20) 
```

**Comment by yceruto** [comment] 2021-07-18 15:22
https://symfony.com/doc/current/service_container.html
> If the value of a string argument starts with '@', you need to escape it by adding another '@' so Symfony doesn't consider it a service.

Closing here as this is not a bug, thanks for reporting!

**Closed as completed by yceruto** 2021-07-18 15:22 UTC
Labels: Bug, Status: Needs Review
