### ISSUE TITLE
[DebugClassLoader] Can't recover on a failed required file

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#32499] opened 2019-07-11 15:54 UTC
**Symfony version(s) affected**: all

**Description**  
In the `DebugClassLoader`, classes that are found by the wrapped class loader `findFile()` method are required (and not included like in the composer `ClassLoader` for example). That means that if the file is not found, the fatal error that is triggered is not recoverable.

So why would the wrapped class loader finds the file but the file doesn't actually exist? With Composer, it can happen if you dump your autoload files with the optimize option and if you delete a class file for example. The class will still be in the Composer class map.

What problem does it cause? When you do reflection on a class like this, it ends up with a fatal error instead of a `\ReflectionException`. In Symfony, that breaks the `AnnotationCacheWarmer` process that is supposed to ignore `\ReflectionException`s on classes that don't exist.

**Possible Solution**  
- Check if the file exists before requiring it in the `DebugClassLoader` : I guess it would be very bad for performance.
- Create a `SafeDebugClassLoader` that wraps the `DebugClassLoader` to check if the file exists, so we can enable it / disable it on demand?

@nicolas-grekas 🙏

**Comment by nicolas-grekas** [comment] 2019-07-11 16:13
Duplicate of https://github.com/symfony/symfony/issues/32395?

**Comment by fancyweb** [comment] 2019-07-11 16:15
Including the missing file would generate a warning that we could handle to throw a proper exception. But including instead of requiring would be a breaking change I guess.

+ somehow related : throwing an exception in a class loader behaves differently since PHP 7.3 (cf https://3v4l.org/OQPk9). I think that the `throwOnRequiredClass` method that is used in Symfony code is impacted and might now work correctly if a previous class loader threw an exception.

**Comment by fancyweb** [comment] 2019-07-11 16:18
> Duplicate of #32395?
https://github.com/symfony/symfony/issues/32395 looks related to my 2nd point about `throwOnRequiredClass` but not on the main one.

**Comment by nicolas-grekas** [comment] 2019-07-11 16:20
How does composer deal with the missing file case? I'm not sure we care actually: if you dump the classmap, you must resync it when needed.

**Comment by fancyweb** [comment] 2019-07-11 16:22
Composer includes the file. So it just produces a warning + the class is not found + a `\ReflectionException` is thrown at the end of all class loaders calls since the class was never found.

**Comment by nicolas-grekas** [comment] 2019-07-11 16:24
Let's do the same? Use include instead of require?

**Comment by fancyweb** [comment] 2019-07-11 16:31
That's the easiest way but that's a big change for userland isn't it? We might break some workflows.

However, doing it would resolve my bug in the `AnnotationCacheWarmer` since a `\ReflectionException` would be thrown by `PhpArrayAdapter::throwOnRequiredClass()` method and then get caught by the current catch block.

**Comment by nicolas-grekas** [comment] 2019-07-11 16:34
What would break?

**Comment by fancyweb** [comment] 2019-07-11 16:42
I guess that going from a fatal error to a warning could have side effects.
Probably not on 99.99% of projects though... So if you agree with this
solution, let’s go for it. I will open a PR as a bug fix.

**Comment by nicolas-grekas** [comment] 2019-07-11 16:57
Please do, thanks.

**Closed** 2019-07-12 04:52 UTC
Labels: Bug, Debug, Status: Needs Review
