### ISSUE TITLE
Template iheritance from parent bundle does not work.

### ISSUE THREAD

**Issue by rafrsr** [symfony/symfony#21752] opened 2017-02-24 17:47 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| Symfony version  | v3.2.4

After update to v3.2.4 the inheritance of templates from parent bundle does not work. Create a loop and the application crash.

e.g.

I have a bundle called AdminBundle, with 

````php 
  public function getParent()
    {
        return 'SonataAdminBundle';
    }
````

and override some templates:

`delete.html.twig:`
```jinja
{% extends '@SonataAdmin/CRUD/delete.html.twig' %}
````

The above code works fine before the update, with: "version": "v3.2.1", but not with current version.

**Comment by javiereguiluz** [comment] 2017-02-25 11:53
Does this worked before? It seems related to this well-known Symfony issue: #17557.

**Comment by rafrsr** [comment] 2017-02-25 15:45
I'm not sure that is related to that issue, in my case the override happen in other bundle and not in `app/Resources/...`. 

> Does this worked before?

Yes, is working fine at Symfony version 3.2.1, upgrade to any version > 3.2.1 (tested with: 3.2.2, 3.2.3, 3.2.4) and the override does not work any more doing a infinite loop.

I'm currently forcing version <= 3.2.1 of Symfony in my `composer.json`

**Comment by xabbuh** [comment] 2017-02-25 18:33
Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by laskos** [comment] 2017-02-25 18:49
I was able to reproduce it here:

https://github.com/laskos/symfony-standard/tree/sf-21752-reproduction

But the problem is, when i downgrade Symfony to `v3.2.1` the problem still presents.

**Comment by rafrsr** [comment] 2017-02-26 01:48
To reproduce:

- Execute the following command: `symfony new blog 3.2.1`
- Generate a bundle named: ParentBundle
- Generate a bundle named: ChildBundle

Modify the child bundle to extends from parent 

````php
public function getParent()
{
    return 'ParentBundle';
}
````
Modify the file 'index.html.twig' in ChildBundle to extend from parent

{% extends '@Parent/Default/index.html.twig' %}

`bin/console server:run`

Go to http://localhost:8000/ and can see "Hello World!"

- Now update to the latest Symfony version 3.2.4 and run `bin/console server:run` again, when try to access to http://localhost:8000/ the server does not respond

Another way to test this issue , is clearing the cache with `console cache:clear`, with symfony 3.2.1 the clear cache works fine, after update does not work any more.

**Comment by xabbuh** [comment] 2017-02-26 13:32
Thanks for the example. I looked into it and IMO that's the expected result. With `@Parent/Default/index.html.twig` you are referring to the `Default/index.html.twig` template from the ParentBundle. However, since ChildBundle extends ParentBundle the loader will look into ChildBundle first when searching for templates of ParentBundle. This is the only way to allow to override templates of a parent bundle in child bundles.

Before #19586 you were not able to actually override templates in child bundles using the Twig namespace syntax, but you experienced the same behaviour as reported here when using the Symfony syntax (see #17557).

Thus I am closing this issue as a duplicate of #17557.

**Closed by xabbuh** 2017-02-26 13:32 UTC

**Comment by rafrsr** [comment] 2017-02-27 14:55
I am confused, the issue #17557 is very old (Jan 2016) and the problem described here start with symfony version 3.2.2 and break backward compatibility of functionality described in the official documentation

http://symfony.com/doc/current/bundles/inheritance.html#overriding-resources-templates-routing-etc

doc:

> The overriding of resources only works when you refer to resources with the @FOSUserBundle/Resources/config/routing/security.xml method. If you refer to resources without using the @BundleName shortcut, they can't be overridden in this way.

And I using exactly this method to override a parent template:

`{% extends '@Parent/Default/index.html.twig' %}`

And this was working right up to version 3.2.1, something change?

**Comment by stof** [comment] 2017-02-27 15:33
@rafrsr overwriting the template from a ParentBundle means you **replace** what ``@Parent/Default/index.html.twig`` (otherwise, nothing is overwritten).

3.2.2 fixed a bug where the overwritten was broken when using the ``@Parent`` syntax (making it inconsistent with the ``ParentBundle:`` syntax and the documented behavior).

**Comment by xabbuh** [comment] 2017-02-27 15:41
@rafrsr Your quote from the documentation refers to loading arbitrary resources (like config files), but doesn't talk about templates by the way.

**Comment by rafrsr** [comment] 2017-02-28 01:01
@xabbuh the title of quoted documentation is **"Overriding Resources: Templates, Routing, etc"**, Then anybody reading this documentation assumes that a template is a resource, like routes and others. In the other hand `views` are always located inside `Resources` folder. It is therefore understood that a template can be referenced using the annotation `@FOSUserBundle` like any other resource. I don't need a example with each type of resource to understand this, and suppose the example using `../routing/security.xml ` is only a example of how override a resource, and logically should works for each type of resources including templates. Otherwise it must be specified, as explained with translations.

> Translation and validation files do not work in the same way as described above. ...

In the other hand, templates has inheritance, then the logic of anybody reading the above quoted documentation to override part of parent template is refer to the parent bundle using `@Parent` syntax and override the part of template needed. 

This logical and simple conclusion, works fine before v3.2.2.

@stof, My question is: exist any way **now** to override only part of a template from parent bundle ***without the need of override the entire template?*** Really is not practical the need of copy the entire template to only modify some block.

That is possible in any version of Symfony before v3.2.2, before fix the bug. 

- Is not a break of BC fix a bug but remove a "undesired", but very helpful feature,  to fix that bug?
- Fix this bug justify the big problem created removing inheritance of templates between child and parent bundle.

Including me, many developers has custom versions of some bundles and override only some part of templates. My concern is that it's not longer possible to do this, currently I'm forcing the use of 3.2.1 in projects using this feature  :(   ... and the bug never was a bug at least for me.

**Comment by yceruto** [comment] 2017-07-07 12:22
See https://github.com/symfony/symfony/issues/17557#issuecomment-313555650 for a workaround ;)
