### ISSUE TITLE
[Expression Language] Null coalescing operator doesn't work?

### ISSUE THREAD

**Issue by adamkiss** [symfony/symfony#54359] opened 2024-03-21 02:19 UTC
### Symfony version(s) affected

7.0

### Description

According to docs, we can use null-coalescing operator to provide fallback to potentially empty or even nonexistent variables. However I can't make it work, even in a simple file with nothing but Expression Language.

### How to reproduce

```php
$lang = new ExpressionLanguage();

$data = [
    'exists' => true,
];

$expression1 = 'notexists ?? "nope,"';
$expression2 = '(notexists ?? "nope,")';
$expression3 = '(notexists ?? false) ? "yes" : "no"';

foreach ([$expression1, $expression2, $expression3] as $exp) {
    try {
        var_dump($lang->evaluate($exp, $data));
    } catch (\Throwable $th) {
        echo('!');
    }
}
// expected: nope,nope,no
// actual: !!!
```

(In the reproduction I have suppressed the throws, but every evaluate fails with `Fatal error: Uncaught Symfony\Component\ExpressionLanguage\SyntaxError: Variable "notexists" is not valid around position …`

**Comment by MatTheCat** [comment] 2024-03-21 14:02
The problem is not the operator but the fact you cannot reference variables you haven’t passed in an expression. What is your use-case for doing so?

**Comment by adamkiss** [comment] 2024-03-21 16:37
@MatTheCat Acting on a variable hashmap

If it's not possible, I'll understand, but docs specifically mention this usecase: https://symfony.com/doc/current/components/expression_language.html#null-coalescing-operator

Right first example is `foo ?? "no"`, and the null-coalescing description is
> It returns the left hand-side **if it exists** and it's not null; otherwise it returns the right hand-side.

(emphasis mine)

**Comment by MatTheCat** [comment] 2024-03-21 16:45
Indeed, but looking at the code it seems this use-case was never intended (the example will only work if `foo` is `null`) :thinking: 

Maybe you could open an issue in symfony-docs? It seems also weird to have the null-coalescing operator documented [here](https://symfony.com/doc/current/components/expression_language.html#null-coalescing-operator) instead of [here](https://symfony.com/doc/current/reference/formats/expression_language.html#supported-operators).

**Comment by adamkiss** [comment] 2024-03-21 16:46
@MatTheCat I'm not using it as a part of Symfony, so I wasn't sure where to post it; Will post it in docs

**Comment by xabbuh** [comment] 2024-03-21 19:23
closing in favour of the docs issue

**Closed as completed by xabbuh** 2024-03-21 19:23 UTC
Labels: Bug, ExpressionLanguage, Status: Needs Review, Status: Waiting feedback

**Comment by adamkiss** [comment] 2024-03-21 20:16
@xabbuh I hoped for "that should work" tbh 😂
