### ISSUE TITLE
[Console] Command list becomes hard to read in certain conditions

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#21518] opened 2017-02-03 07:40 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x+ (possibly 2.7+)

I have an application where I have a very long command name and I have a pretty narrow console screen (1920 / 2) because I have it split screen. Whenever I use `app/console`, it looks like the screenshot I've attached.

This makes it really hard to read the descriptions.

![image](https://cloud.githubusercontent.com/assets/1754678/22583295/e6c68988-e9eb-11e6-9f9f-75ab03782f2a.png)

**Comment by javiereguiluz** [comment] 2017-02-03 08:17
I can't think of simple solution to this problem. Testing this in the Symfony Demo app, the problem is not that bad, but the long Doctrine command names makes it look worse than it should. But at the moment I can't think of a solution.

Other technologies solve this problem "easily": they use commands named with just 1 short word and they don't display descriptions:

![npm-command-listing](https://cloud.githubusercontent.com/assets/73419/22584222/84489d7c-e9f1-11e6-9df5-6566cde8b8bb.png)

**Comment by iltar** [comment] 2017-02-03 08:19
I'm not sure how the current rendering works, but it could be solved using a table as that would auto-wrap properly within a column?

**Comment by deltab** [comment] 2017-02-10 16:48
Wrapping would work for the second column, but the first column doesn't contain spaces.
Maybe give the first column a max width, and let longer commands overrun but break the line after:
```
 doctrine
  doctrine:cache:clear-collection-region
                                      Clear a second-level cache collection region.
  doctrine:cache:clear-entity-region  Clear a second-level cache entity region.
  doctrine:cache:clear-metadata       Clears all metadata cache for an entity manager
  doctrine:cache:clear-query          Clears all query cache for an entity manager
  doctrine:cache:clear-query-region   Clear a second-level cache query region.
  doctrine:cache:clear-result         Clears result cache for an entity manager
  doctrine:database:create            Creates the configured database
  doctrine:database:drop              Drops the configured database
  doctrine:database:import            Import SQL file(s) directly to Database.
```

**Comment by laskos** [comment] 2017-02-24 15:39
I think npm solution is much more cleaner, descriptions arent really useful in 95% of cases. The name of command explains operation well enough. Arguments (and eventually parameters) list would be more helpful and make list more cleaner. More detailed info could be provided using `bin/console command --help`.

**Comment by fabpot** [comment] 2018-02-21 06:17
I don't think we need to change what we are doing right now. Trying to come up with shorter name is probably much better. So, I'm closing now.

**Closed by fabpot** 2018-02-21 06:17 UTC
Labels: Console
