### ISSUE TITLE
Doctrine connection instantiated during cache:warmup

### ISSUE THREAD

**Issue by aequasi** [symfony/symfony#24927] opened 2017-11-11 20:17 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2?

Creating a ticket to follow up on #24865 

From @weaverryan 
> Tangentially related to this: thanks to the same lack of laziness in Doctrine, the Doctrine Connection object is also instantiated. This means that a DATABASE_URL environment variable must be available at cache:warmup time. It doesn't need to be valid (no connection is make), but it does need to be defined: https://user-images.githubusercontent.com/121003/32516437-56ceb114-c3d1-11e7-8249-597c514117c1.png

And from @nicolas-grekas 
> The only way around is using a real lazy proxy from proxy-manager, which has tighter integration with the DI component and is able to call a factory lazily.

**Comment by nicolas-grekas** [comment] 2017-11-11 22:25
Well, the description is misleading: the issue that remains has nothing to do with Doctrine, as there is nothing can to to improve the situation.

The issue is that when a service is instantiated, all it's arguments are needed (not a surprise :) )
When one of those arguments is an env var, then the env var must be defined, even if the service is not needed in the end.

As said previously, there is no way around I can thing of, except by using a lazy proxy from proxy-manager.

Thus, I don't think we need to track this: just use lazy=true + proxy-manager is you REALLY need that (ie setting a dummy env var is not possible for you.)

**Comment by bitgandtter** [comment] 2017-11-11 22:46
And if there is a way at least as you mention @nicolas-grekas and I quote
`using a lazy proxy from proxy-manager` 
should not be implemented so we don't need to use a fake environment just to make cache warm-up and by that composer pass?

**Comment by nicolas-grekas** [comment] 2017-11-19 17:56
Enabling lazy proxies requires ocramius/proxy-manager. This dependency is not part of the mandatory requirements for various reasons that are stronger than this issue...
I'm closing this issue as a duplicate of #25010, which describes the same issue in a more extensive way.

**Closed by nicolas-grekas** 2017-11-19 17:56 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review

**Comment by goetas** [comment] 2017-11-19 19:46
This can be solved by just setting 

```yml
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        server_version: 5.7 #in case you are using mysql 5.7
```

By setting `server_version`, doctrine does not need to initiate the connection

**Comment by nicolas-grekas** [comment] 2017-11-26 10:29
For reference I was wrong in the previous comment: this was specific to Doctrine (as discussed in #25010)
The solution happens to rely on some specific configuration, as @goetas noticed. It's been implemented as a recipe:
https://github.com/symfony/recipes/pull/258

**Comment by tecnocat** [comment] 2019-02-27 10:55
May be this help:

https://github.com/symfony/symfony/issues/25157#issuecomment-467811636
