### ISSUE TITLE
RequestMatcher dies on non-string request attribute

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#16529] opened 2015-11-12 05:11 UTC
Should there be an `is_string` / `__toString` check here?

https://github.com/symfony/symfony/blob/v2.7.6/src/Symfony/Component/HttpFoundation/RequestMatcher.php#L156-L160

**Comment by jukovantons** [comment] 2015-11-13 16:17
I've checked the related issues FOSHttpCacheBundle#249 and DunglasApiBundle#325, and there is still not enough information to get what exactly that bundles pass to RequestMatcher to make it die. RequestMatcher.php have not been changed significantly for a year, and it seems there are not much users encountered that bug. So please provide more information on how to trigger the bug using 3rd party bundles.

**Comment by javiereguiluz** [comment] 2016-02-12 07:05
Any news about this issue? Can we confirm it as a Symfony bug? Thanks!

**Comment by xabbuh** [comment] 2016-02-12 14:10
@teohhanhui Can you provide a failing test case for this?

**Comment by xabbuh** [comment] 2016-02-23 19:01
Closing because of the lack of feedback.

@teohhanhui Please let us know when you can provide some more information about how to reproduce your issue.

**Comment by teohhanhui** [comment] 2016-02-24 08:21
@xabbuh Please see #17800 (looks like you missed it)

**Comment by javiereguiluz** [comment] 2016-02-24 08:31
Let's reopen until the related pull request is merged.

**Comment by xabbuh** [comment] 2016-02-24 09:23
@teohhanhui Indeed, I missed that. Sorry for that. Next time, it would be the best to leave small comment linking to the PR though as sometimes notifications just get lost. :)

**Comment by teohhanhui** [comment] 2016-02-24 10:08
What do you think of the test case? Do you agree with @fabpot that only scalars should be stored as value in the Request `attributes` ParameterBag?

But indeed Symfony itself might store non-scalar values in `_controller`, e.g. https://github.com/symfony/http-kernel/blob/87fccbc6265834836cd9ef4d834f7dce498712e5/Tests/Controller/ControllerResolverTest.php#L30-L38

**Comment by teohhanhui** [comment] 2016-03-03 13:52
@fabpot https://github.com/symfony/symfony/pull/17800#issuecomment-191753027
> Philosophically, attributes should be scalars. Put another way, even if Symfony internals puts non-scalar in there, this is its responsibility. As a end user, you should not do that... or at least, this is not officially supported.

Are you saying that the user must not use a service as the `_controller` value? See dunglas/DunglasApiBundle#325 and FriendsOfSymfony/FOSHttpCacheBundle#249 - is the use case not supported?

**Comment by fabpot** [comment] 2016-03-03 13:54
No `_controller` is controlled by Symfony, so that's not a problem. I'm only talking about user-controlled attributes that are not standardized by Symfony itself.

**Comment by teohhanhui** [comment] 2016-03-03 14:01
So it's still a Symfony bug that needs to be fixed.

**Comment by teohhanhui** [comment] 2016-03-03 14:06
And there probably should be documentation to discourage putting non-scalar values in the Request `attributes` ParameterBag :smiley:

**Comment by fabpot** [comment] 2018-02-22 06:52
Closing this issue for the reasons I explained in the related close pull request.

**Closed by fabpot** 2018-02-22 06:52 UTC
Labels: Bug, HttpFoundation, Status: Needs Review
