### ISSUE TITLE
Memory leaks in PhpFilesAdapter.php in php7.4.5 with disabled cli opcache

### ISSUE THREAD

**Issue by ferrius** [symfony/symfony#36550] opened 2020-04-23 15:31 UTC
**Symfony version(s) affected**: 5.*/4.*

**Description**  
I found the php 7.4 bug about memory leaking while included not existent file (https://bugs.php.net/bug.php?id=79514). There are many includes in https://github.com/symfony/cache/blob/master/Adapter/PhpFilesAdapter.php that used in system cache as well and i faced with memory leaks and performance degradation in a long running jobs.

**Possible Solution**  
Maybe recommend in docs to enable cli opcahe or add is_file() check before including a file

**Comment by nicolas-grekas** [comment] 2020-04-23 15:43
Thanks for the report. I can reproduce the issue locally in 7.4.5, but not on 7.3.17. On 7.4.5, the performance is pathetic. This looks like a PHP bug to me, we should wait for it to be resolved before doing anything in Symfony.

**Comment by bytestream** [comment] 2020-05-04 20:31
I opened https://bugs.php.net/bug.php?id=79519 which sounds very similar to what @ferrius is experiencing. If you have a reproducer for this specific case I can get against 7.4.6-rc.1 because the test cases I came up with weren't resolved in the RC

**Comment by maks-rafalko** [comment] 2020-05-04 20:33
> This looks like a PHP bug to me, we should wait for it to be resolved before doing anything in Symfony.

btw, it has been fixed: https://github.com/php/php-src/pull/5445

**Comment by nicolas-grekas** [comment] 2020-05-04 21:14
Thanks for the notice, let's close here since there is a priori nothing to do in this repo.

**Closed by nicolas-grekas** 2020-05-04 21:14 UTC
Labels: Bug, Cache, Status: Needs Review
