### ISSUE TITLE
[Form] get all errors

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18421] opened 2016-04-03 18:20 UTC
[`FormInterface::getErrors()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormInterface.php#L109) return only the errors associated to the form and does not include the children ones by default. It is a behaviour that makes sense when rendering a form with sub-forms for example, besides being so for BC reasons.

However it may feel unnatural to a new comer and doesn't really makes sense in other contexts, like in a "REST" API (I'm quoting it as it doesn't need to be REST at all) or simply when you are used to use another form component: you tend to assume that `getErrors()` returns all errors. So my point is, this default behaviour may caught people by surprise. If you also consider relying on auto-completion, the auto-completion will auto-complete `getErrors()` without any parameter as they are optional. As the method name is clear, you might not dig into it deeper and check the whole signature.

Obviously this wouldn't be possible to change this default behaviour for BC reasons. However we could introduce a new method `getAllErrors()` which would call `getErrors(true)`. This would avoid any possible confusion and also make more obvious.

/cc @webmozart

**Comment by Tobion** [comment] 2016-04-05 11:57
Adding `getAllErrors` would be a BC break as well as you need to add it to the interface at some point. So I'm :-1: as the problem is too minor to make a breaking change.

**Comment by javiereguiluz** [comment] 2016-04-06 08:02
Apart from @Tobion comments, this new `getAllErrors()` method would make things more difficult to learn. If `getAllErrors()` returns all errors, what does `getErrors()` do?

If we could change anything, we could have `getParentErrors()` and `getChildrenErrors()` methods and then `getErrors()` would return both.

So I'm :-1: too.

**Comment by theofidry** [comment] 2016-04-06 08:53
>this new getAllErrors() method would make things more difficult to learn.

Why? It wouldn't change anything for a user using the Form in his view (I mean rendering the form via the Form component). Whilst this would help when you are not using your Form to render the view: if you return a response with all the errors, seems counter intuitive to have `getErrors(true)`: 

- Zend: `$form->getMessages()`
- Laravel: `$errors->all()` (you get a message bag)
- Aura: `$form->getMessages()`
...

In all above: it is the same behaviour: you get *all* the errors, not the ones of the form itself which exclude its children.

**Comment by Tobion** [comment] 2016-04-06 09:37
Closing as two members votes -1. I agree that the standard use-case is probably to get all errrors. But changing this at this point will only do more harm than good unless you find a solution that doesn't break BC.

**Closed by Tobion** 2016-04-06 09:37 UTC
Labels: Feature, Form

**Comment by theofidry** [comment] 2016-04-06 10:23
@Tobion `getAllErrors()` could be added to the `Form`, not the interface, while not being optimal this would avoid any BC break.
