### ISSUE TITLE
autowired service is loosing visibility (gets public)

### ISSUE THREAD

**Issue by mkingbe** [symfony/symfony#24768] opened 2017-10-31 12:01 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

If you load a service (autowired) in a Controller via dependency injection and try to use in a console command via ContainerAwareCommand, the service becomes public.
IMO it should not be available from ContainerAwareCommand event if is used in other place with dependency injection.

Not sure if this is the expected behavior or not as I didn't find any information regarding it.

**Comment by chalasr** [comment] 2017-10-31 12:13
A private service never becomes public, it's inlined and removed if referenced less than 2 times, kept private otherwise. 
If you are able to `get()` such service from the container, it means it has not been removed, and you should get a deprecation notice (should find it by looking at your logs or running the command with `-vvv`), it won't be `get()`able as of 4.0.

**Comment by nicolas-grekas** [comment] 2017-10-31 14:16
In fact, controllers are made public since #24126. This is a requirement, so no bug here.

**Comment by chalasr** [comment] 2017-10-31 15:34
This is about a service injected in a controller and `get()`ed from a container aware command, not the controller itself, right?

**Comment by mkingbe** [comment] 2017-11-01 07:45
@chalasr yes, I'm using get in a console command and I have the service injected in a controller.

**Comment by xabbuh** [comment] 2017-11-01 08:35
@mkingbe Can you please create a small example project that allows to reproduce your issue?

**Comment by mkingbe** [comment] 2017-11-01 09:52
@xabbuh https://github.com/mkingbe/symfony-24768/commit/693edcc276b994d7551952183c2a50bfea955e1a

**Comment by nicolas-grekas** [comment] 2017-11-01 10:02
This triggers a deprecation, isn't it?

**Comment by mkingbe** [comment] 2017-11-01 10:12
"User Deprecated: The "AppBundle\MyPrivateService" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop getting services directly from the container and use dependency injection instead."

However, you have access to it.

**Comment by nicolas-grekas** [comment] 2017-11-01 11:07
Yep, that's expected behavior on 3.4, fixed in 4.0.
Closing as such.

**Closed by nicolas-grekas** 2017-11-01 11:07 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Status: Waiting feedback, Unconfirmed
