### ISSUE TITLE
Embedded controller throws 404 for profiler

### ISSUE THREAD

**Issue by kristijanhusak** [symfony/symfony#14772] opened 2015-05-28 13:27 UTC
Hi,

I'm not sure if this issue is a duplicate, because i couldn't find any other that specifically points to this.

I am rendering two controllers into the view like this:
```twig
  {{ render(controller('WebBundle:Task:navTask')) }}
  {{ render(controller('WebBundle:Notification:navNotification')) }}
``` 

Everything works out fine, but for each render i get 1 or 2 errors in the console:
```
GET http://example.dev/_wdt/98002d 404 (Not Found)
```

Here's content of controller action:
```php
    public function navTaskAction()
    {
        return $this->render('WebBundle:Task:navTask.html.twig', [
            'navTasks' => 2
        ]);
    }
```

And view:
```twig
<div class="tasks">
  {{ navTasks }}
</div>
```

When I remove those, errors are gone.

It didn't bother me at first, but when i wanted to add 3rd render, it started to throw 404 alert for profiler, because it exceeds 5 calls. 

Probably the problem exists because token is not passed to the subrequests, which then throws 404 error. Just a guess. Is there a way to fix this, or am I doing something wrong?

**Comment by jakzal** [comment] 2015-05-28 16:19
Are you able to reproduce this issue on a clean symfony installation? Which Symfony version do you use?

**Comment by kristijanhusak** [comment] 2015-05-29 07:29
I haven't tried. I was using 2.6.6, and after the upgrade to 2.6.8, issue still exists. Project is pretty old, development was started when 2.3 was latest release, but symfony is properly updated.

I googled some solutions that include fixing apache htaccess/nginx to prevent these 404 errors. I am using vagrant with nginx, and in dev environment redirect app_dev.php to the index (root). Not sure if that can maybe cause this issue.

**Comment by jakzal** [comment] 2015-05-29 07:35
@kristijanhusak could you please try to reproduce it on a vanilla standard edition project? Without it we won't be able to fix this issue. We need to confirm it's really a bug, and not something specific to your project.

**Comment by kristijanhusak** [comment] 2015-05-29 07:54
@jakzal I will, thanks.

**Comment by Galosoft** [comment] 2015-06-22 13:12
I have the same issue in 2.7.* on clean symfony2 installation. 

I have tried both options in TWIG:

`{{ render(controller('MyBundleController:index')) }}`
`{{ render(path('my_route')) }}`

If I downgrade symfony2 to 2.6.* everything work fine for me!

**Comment by xabbuh** [comment] 2015-06-28 16:59
@Galosoft Can you provide a fork of the Standard Edition that show the issue?

**Comment by xabbuh** [comment] 2015-07-08 06:43
maybe related to #14995

**Comment by xabbuh** [comment] 2015-08-05 20:11
ping @kristijanhusak @Galosoft

**Comment by trq** [comment] 2015-09-03 06:52
I'm not able to reproduce using the following: https://github.com/symfony/symfony-standard/compare/2.7...trq:issues-14772

Status: Works for me

**Comment by javiereguiluz** [comment] 2015-09-03 08:56
I'm not able to reproduce it either. I used the Symfony Demo app and embedded a controller 3 consecutive times. The three sub-requests appear correctly in the profiler, each one with its own token (and each one points to a valid profile):

![profiler-subrequests-embeds](https://cloud.githubusercontent.com/assets/73419/9654323/49308bf6-522a-11e5-8f94-009d4d676931.png)

I'd say to close this issue and reopen it if a fork with the problem is provided.

**Comment by jakzal** [comment] 2015-09-03 09:01
@kristijanhusak @Galosoft feel free to reopen if you provide a fork with the problem reproduced.

**Closed** 2015-09-03 09:01 UTC
Labels: Status: Works for me, Unconfirmed
