### ISSUE TITLE
Improve the way commands are loaded/displayed

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#15689] opened 2015-09-04 09:04 UTC
Hi,
some days ago, I wanted to launch a debate about the console commands available in Standard edition.
## Actual status

For the record, we have 72 commands available when we install Symfony (71 if we remove the Symfony ACL component).

I don't think this need a screenshot, we can say the first contact with the console is undoubtely disturbing for a lot of newbies: 
- too much commands; 
- too much options 
- some weird duplicates ... (this point is already fixed in 3.0.X release)

Before release the new major in november, the deletion of all deprecated command is planned (no specific issue) and the new UI update is in progress (https://github.com/symfony/symfony/issues/14138).

Commands of Standard Edition come from Bundles:
- AsseticBundle
- DoctrineBundle
- SwiftMailerBundle
-  FrameworkBundle
- ...

They are autoloaded and registered without any intervention of developper. As @fabpot said, if we don't want the commands, we can uninstall the related bundle.
## Commands come from bundles

But theses bundles provide a lot of others useful things that make them required in Standard Edition:
- Compiler passes
- Event listeners
- Complete applications ? (like the WebProfiler)

So, I think remove some of theses bundles can't be an option.
## Survey about Symfony commands

Few days ago, I started to share a survey about the Symfony commands use. You can see the [complete results here](https://fr.surveymonkey.com/results/SM-WWZ7CFL2/)

Some easy conclusions according to the survey:
- Almost 15 commands are (mostly) never used
- 60% (~50 !) of theses commands are not used by a majority of developpers
# Some ideas

To improve the DX of the Symfony console, many strategies can be applied:
- Remove some commands;
- Move theses commands into "Extra" Bundles (debug-command-bundle, security-command-bundle, doctrine-command-bundle ...);
- Make some of theses command real console applications (yaml-linter, php-security-checker ...);
- Play with the `isEnabled()` function: only enable to most used command by default;
- Implement a "two levels" displaying of console like rails for instance: the first time we only see the categories of commands, then when we call a category (`php app/console doctrine`) the console returns all available commands in this category.
- ... and probably far better ideas you have :)

Of course, many strategies can be applied, and this issue is more about debate than suggest a pull request that remove everything :)

What do you think ?

**Comment by weaverryan** [comment] 2015-09-22 13:18
o/ @mickaelandrieu

There are a lot of commands. I'd be interested in the option of showing "two levels" - just the categories at first, then the full commands below that.

**Comment by mickaelandrieu** [comment] 2015-09-22 13:40
@weaverryan of course, if you 10 minutes you can install rails and play a little bit with their console: this is the kind of behavior I would love to see for Symfony :)

I know that some - not so used - commands come from Doctrine Bundle, but before open multiples issues I want to open debate on UX instead of: what commands should be removed ? They are all used, and they are some many cases for so many web applications !

**Comment by weaverryan** [comment] 2015-09-22 13:45
>
They are all used, and they are some many cases for so many web applications !

That makes it hard to remove commands :). If we organized them like you're suggesting, maybe the lesser-used commands are no longer a problem.

**Comment by mickaelandrieu** [comment] 2015-09-22 13:46
@weaverryan :+1:

**Comment by stof** [comment] 2015-09-22 13:54
Regarding the unused commands, here is some feedback about the first ones:

- ``orm:convert:mapping`` is not a function available in Symfony. This is available when using Doctrine standalone CLI (which requires configuring Doctrine separately, and is not done by DoctrineBundle). The command name in DoctrineBundle is ``doctrine:mapping:convert``. And this command is indeed rarely used (you will almost never switch from 1 mapping format to a different one)
- ``doctrine:cache:clear-(entity|collection)-region`` are related to the Doctrine second-level cache. this is a new feature in Doctrine, not yet widely used (especially given there is not a lot of doc about it). And even when you use it, you only need to clear your cache in rare cases (one case is when you change your schema to add new fields in a cached entity; another one is when you make updates without using doctrine but you should not use the SLC if you plan to do such updates). So it is logical they are rarely used (but they are needed for cases you need them as there is no UI to trigger the same maintenance actions). The same is also true for other ``doctrine:cache:clear-*`` commands, except you will probably need to clear things even less often as Doctrine tries to make the cache key change in all cases needing invalidation whenever possible.

> some weird duplicates

this is just because we don't display aliases in a nice way in the list. We should probably not display them the same way that canonical names of commands, but rather show than some names are aliases.

> Make some of theses command real console applications (yaml-linter, php-security-checker ...);

The security checker is actually already a standalone tool. It was added in SensioDistributionBundle to give it more visibility (and to get rid of this, you can really unregister the bundle from the kernel: it is the only feature provided in the kernel in the 5.0 version of the bundle. Other features are provided as composer hooks).
Getting rid of the ``generate:*`` commands works the same btw: SensioGeneratorBundle is only about providing these commands. We may discuss whether this bundle should be part of the SE or no though (but this bundle was added by people wanting to make it easier to start though)

The Yaml linter indeed may be better as a separate tool (I even suggested it in the PR adding it btw).
It would be much more difficult for ``twig:lint`` because the Twig linting involves getting a configured Twig_Environment, and this depends on your project.

> Implement a "two levels" displaying of console like rails for instance: the first time we only see the categories of commands, then when we call a category (php app/console doctrine) the console returns all available commands in this category.

``app/console doctrine`` would not be possible as it would be a BC break (this is calling the ``doctrine`` command, not the ``list`` command today). Thus, it is perfectly valid to register a ``doctrine`` and a ``doctrine:init`` commands at the same time.

We already have support for ``app/console list doctrine`` to show only commands in the ``doctrine`` namespace. The display of ``app/console list`` may be improved by hiding some commands from there (it may make it harder to discover commands though)

> Play with the ``isEnabled()`` function: only enable to most used command by default;

This would be hard: we would then have to add configuration settings to re-enable such commands, and we try to avoid adding too much configuration settings as people also need to understand them.
The goal of this method is currently well defined: disabling functions which cannot be used in your environment (needed as commands are discovered automatically, and we cannot remove the file when you don't have the router enabled for instance)

**Comment by mickaelandrieu** [comment] 2015-09-22 14:06
@stof thank you for the feedback.

You said:

> The display of app/console list may be improved by hiding some commands from there (it may make it harder to discover commands though)

To me, when we are looking for a command we already know what we want to do: this is why namespace (in this case) is intended for.

I you need to do stuff with your database but don't know which command to use, this is totaly "natural" to try something like ``app/console doctrine``. In Symfony, an exception is thrown in this case.

So, I don't think make all the list of available commands less "visible" is a problem :)

I also agree with you that some commands are to promote some useful tools or bundles, we need to discuss about theses command before 3.0.X release else the core team have to maintain them until EOF (2022 ?).

**Comment by ByScripts** [comment] 2015-10-22 08:36
On our actual project, we now have a lot of commands.

The problem is that 2 years ago we were pretty new Symfony and the time going on, we created a lot of inconsistency in command names.

Today I'm working on that and I'm updating the name of these commands, adding the old name as an alias.

The problem is that these aliases appears in the command list the same way that the "true" command name.

I think there should be 2 features to implements:

* When displaying a command list, show the aliases along the original command name
* Add the ability to create "hidden" aliases (for refactoring). This it would be possible to "rename" a command, without breaking some script which would use it.

**Comment by javiereguiluz** [comment] 2017-07-06 14:00
I'm closing this as "no longer needed to be fixed" because in the upcoming Symfony 4, we don't even have a console by default, so we'll have 0 commands initially (and the total number of commands will always be reasonable because you must install dependencies as you need them). Thanks!

**Closed by javiereguiluz** 2017-07-06 14:00 UTC
Labels: Console, Enhancement

**Comment by mickaelandrieu** [comment] 2017-07-06 15:10
:+1: one question - it's still not clear to me - when you are talking about Symfony 4, which repository(ies) do you have in mind?

**Comment by javiereguiluz** [comment] 2017-07-06 15:14
@mickaelandrieu this one: https://github.com/symfony/skeleton  It's not mandatory to use it, but it will be used by default (exactly the same as the Standard Edition and Symfony 3: it's not mandatory, but it's used by default).

**Comment by mickaelandrieu** [comment] 2017-07-06 15:20
Thanks for information :)
