### ISSUE TITLE
[WebProfilerBundle] ajax icon remains in red after success call

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#30449] opened 2019-03-05 10:59 UTC
Symfony version(s) affected: 3.0, 4.0

**Description**  
When interacting with the UI and producing a ajax call that results in error, the ajax icon changes to red. After fixing the error and producing another ajax call which results in success (without refreshing the whole page), the toolbar icon remains in red, instead of changing to grey.

**Possible Solution**  
Change the toolbar icon depending on the last request.

**Comment by ro0NL** [comment] 2019-03-05 11:51
> Change the toolbar icon depending on the last request.

Currently it's red if at least one request failed, that's a reasonable point of view IMHO.

**Comment by deverad** [comment] 2019-03-05 12:05
I don't think the best solution for the developer UX. More than once I thought the request still fails, but only after hovering over the icon you see that it actually succeeded. 

It that's the desired functionality by design, I will close the issue. Thanks

**Comment by ro0NL** [comment] 2019-03-05 12:07
We can discuss it :) just pointing out the reason behind the current approach.

Played with this situation a bit and i can only understand your request :)

little tip: you can pin the ajax block (click on the icon), then it's always grey and you see incoming requests on the fly.

**Comment by deverad** [comment] 2019-03-05 12:09
That's a nice touch.

**Comment by fabpot** [comment] 2020-08-16 19:47
Closing as there current behavior is the expected one.

**Closed by fabpot** 2020-08-16 19:47 UTC
Labels: WebProfilerBundle
