### ISSUE TITLE
Periods Handling in URL Parameters

### ISSUE THREAD

**Issue by WesDowney** [symfony/symfony#25541] opened 2017-12-18 16:45 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.2

We ran into a bug in the handling of periods in an API end point URL.

This query wouldn't work due to the period in faculty.position.  This is the expected behavior since this is how it works in production. 
`$response = $this->get('/sample?faculty.position=Teacher');`

This one should act similarly to the above but it actually handles it. I was thinking that both lines should be consistent on Symfony whether it handles periods or not.
`$response = $this->get('/sample', ['faculty.position' => 'Teacher']);`

We fixed this by using camelCase instead of using periods but I wanted to bring it up in case someone else encounters this. 

The actual call to Symfony is: 
`$this->client()->request($method, $uri, $parameters);` 
which is within Client.php in the framework.

**Comment by dmaicher** [comment] 2017-12-18 18:55
Interesting bug indeed.

```php
dump(\Symfony\Component\HttpFoundation\Request::create('?foo.bar=foo')->query)
```
==> 
```
array:1 [
  "foo_bar" => "foo"
]
```

Internally it uses http://php.net/manual/en/function.parse-str.php

> Because variables in PHP can't have dots and spaces in their names, those are converted to underscores.

**Comment by nicolas-grekas** [comment] 2017-12-18 18:57
yep, no something we want to fix imho

**Comment by sroze** [comment] 2017-12-19 11:20
> yep, no something we want to fix imho

Well... I think we should. Having dots in the query parameters is completely legitimate and works well with the "web-based" version (i.e. from `$_GET`). It just doesn't work when parsing the URI while calling `create($uri)` which looks weird.

**Comment by nicolas-grekas** [comment] 2017-12-19 12:23
In PHP, you cannot add dots to query params since v1.
I don't think this is a limitation of any kind: just use a naming scheme that is compatible with the way things work.
Fixing this would mean reimplementing parse_str in userland.
Better not IMHO.

**Comment by ro0NL** [comment] 2017-12-24 12:44
> Because variables in PHP can't have dots and spaces in their names, those are converted to underscores. Same applies to naming of respective key names in case of using this function with result parameter.

IMHO it doesnt make really sense when using the 2nd arg with parse_str (which is what SF does), yet this is how things work indeed.

> In PHP, you cannot add dots to query params since v1.

From a HTTP pov you can; https://3v4l.org/AEhLD

**Comment by maerlyn** [comment] 2017-12-26 10:07
Yes, from a http PoV it is certainly possible, just not in php. This is an old remnant of register_globals, some name mangling was neccessary to convert GPC input to something that conforms to the php variable naming scheme. With register_globals long behind us it is not technically neccessary, but still kept for BC reasons.

**Comment by javiereguiluz** [comment] 2017-12-28 11:28
@WesDowney even if what you reported is true, I'm 👎 on fixing it for the reasons given by Nicolas: this is not possible because of PHP, so we'd need to reimplement `parse_str()` inside Symfony. We can fix minor PHP issues or inconsistencies ... but we can't fix/change something so important.

I'm afraid I must close this as "won't fix" because of the downvotes from the Core Team members.

**Closed by javiereguiluz** 2017-12-28 11:28 UTC

**Comment by darrenoh** [comment] 2019-04-09 00:10
We often use Symfony to interact with third-party services for which we don’t get to define the query parameter names. This bug exists because parse_str() can be used to set variables in the current scope. We do not use parse_str to do this. It does not make sense to keep HTTP handling broken for an obsolete PHP behavior.

**Comment by drupol** [comment] 2020-06-11 18:56
Sorry to dig up such old topics but I encountered the issue while doing the [ecphp/cas-bundle](https://github.com/ecphp/cas-bundle) and working with API Platform.

I have found a pretty nice solution for us and I made a bundle out of it: https://github.com/loophp/unaltered-psr-http-message-bridge-bundle

Duplicate of #29664
