### ISSUE TITLE
The process has been signaled with signal "11"

### ISSUE THREAD

**Issue by xiangjihan** [symfony/symfony#20988] opened 2016-12-19 11:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.14~2.8.15
| PHP Version  | 7.1.0 by remi
| OS System    | Fedora 25 X64

It occured when I was update 2.8.14 to 2.8.15 with composer.
![qq 20161219191220](https://cloud.githubusercontent.com/assets/3070542/21311206/0eb66a2e-c621-11e6-807e-4dbfe921e67f.png)
Angone has ideas.

**Comment by Simperfit** [comment] 2016-12-26 08:06
@xiangjihan could you please add the -vvv part in order to see what happens directly ?

**Comment by xiangjihan** [comment] 2016-12-27 05:03
@Simperfit Hi,I  have other messages you.  Wait a minute I am testting.

**Comment by nicolas-grekas** [comment] 2017-01-16 13:07
signal "11" means segfault, means PHP bug, we can't do anything about it I think.

**Comment by fabpot** [comment] 2017-01-16 16:01
I had the same issue with non-final releases of PHP 7.1, but not anymore since 7.1.0 final. @xiangjihan Can you confirm?

**Comment by xiangjihan** [comment] 2017-01-19 01:54
@nicolas-grekas I think this is a Zend Engine with class_exists, but  I  do not know debug with the core dump file.

**Comment by xiangjihan** [comment] 2017-01-19 02:08
@fabpot It occured when I was using PHP7.1.0 by remi repo. Then I  degrade PHP to 7.0.14. Now I am ready to upgrade php to 7.1.1 by remi, And try again.

**Comment by chalasr** [comment] 2017-02-16 16:07
May be related to https://bugs.php.net/bug.php?id=73989 (first reported in #21349) which has been fixed

**Comment by javiereguiluz** [comment] 2017-02-25 18:26
@xiangjihan any news about this? Did it finally work?

**Comment by xabbuh** [comment] 2017-03-05 19:55
Closing here [because of](https://github.com/symfony/symfony/issues/20988#issuecomment-272857645):

> signal "11" means segfault, means PHP bug, we can't do anything about it I think.

**Closed by xabbuh** 2017-03-05 19:55 UTC
Labels: Bug, Process, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by muhammadtaqi** [comment] 2018-11-29 14:29
I faced this issue after installation of profiler package. SF 4.1 and PHP7.2

**Comment by fernandofreamunde** [comment] 2018-11-29 16:45
So I'm having this if I use the profiler in a new project, in ubuntu with php7.2 and SF 4.1.8

if I do not use the profiler there is no problem

**Comment by muhammadtaqi** [comment] 2018-11-29 18:15
> So I'm having this if I use the profiler in a new project, in ubuntu with php7.2 and SF 4.1.8
> 
> if I do not use the profiler there is no problem

and if you delete the `var/cache` folder , then it will run first time, bus as soon as the new cache folder created, again the same error.

**Comment by xabbuh** [comment] 2018-11-29 18:44
The 4.1.8 version of the Debug component triggers a PHP Opcode bug. Either downgrade the component to 4.1.7 for the moment or update to the development version of 4.1 to fix it.

**Comment by AurelienBarbier** [comment] 2018-11-30 09:32
I have many developpers with this issue. Downgrade to symfony/debug 4.1 doesn't resolve it.
They try to remove all symfony/debug-pack to test, but without any change. They can load a page once, but as they request another route, it's the same error again.

**Comment by jenyak** [comment] 2018-11-30 09:54
Downgrade to symfony/debug 4.1.7 did not help.  Disabling OPcache helped.

**Comment by AurelienBarbier** [comment] 2018-11-30 11:02
Thanks @jenyak I'll try it ! 
What I done which worked for my team was to clean app cache and vendors, delete composer.lock. Remove all requires-dev from composer.json except symfony/dotenv  and try a new composer install.
It's working by now, but it's not a long term solution at all.

**Comment by jsltopnode** [comment] 2018-11-30 16:03
I updated my PHP 7.2 (i'm using Ubuntu 16.04) and this error seems resolved.

**Comment by god1dog** [comment] 2018-11-30 16:13
I was helped by the update on 4.2

**Comment by fernandofreamunde** [comment] 2018-12-03 11:30
on ubuntu 18.04 I disabled opcache and now it works :)
for people with the same problem, I just did this:
`sudo mv /etc/php/7.2/cli/conf.d/10-opcache.ini /etc/php/7.2/cli/conf.d/10-opcache.bak`

will keep an eye to see when this is fixed tho :)

**Comment by Anan5a** [comment] 2018-12-26 17:38
## Anyone came here for this issue please disable ``` OPcache ```
Goto /etc/php/7.x/cli/php.ini
and search this lines
 ``` 
opcache.enable=1
...
opcache.enable_cli=0
```
and uncomment them and set ``` opcache.enable=0 ```
# This is confirmed ;)

**Comment by xabbuh** [comment] 2018-12-26 19:31
Disabling Opcache should not be the solution, but was only meant as a workaround. Did updating the Debug component not help?

**Comment by Anan5a** [comment] 2018-12-27 01:42
@xabbuh No. Updating didn't really worked. 
PHP 7.3.0-2
Xdebug installed.
Before installing Xdebug everything was working fine except the profier. The server signalled '7' everytime I tried to view profiler.  
After Xdebug installed, every request to the server resulted a signal '11' termination.
After disabling Opcache everything is back to normal.
So signal '11' is probably produced by (Xdebug+OPcache) 
``` Disabling OPcache on CLI is not any disadvantage ```

**Comment by TheFox** [comment] 2019-01-16 11:12
I also had this issue with PHP 7.3. Disabling OPcache helped. Thank you.

**Comment by nelson6e65** [comment] 2019-01-21 12:02
Thanks, @Anan5a 

`opcache.enable_cli=0`

> Disabling OPcache on CLI is not any disadvantage 

:+1:

**Comment by xabbuh** [comment] 2019-01-21 18:05
Looks like the same that was reported in https://github.com/symfony/symfony/issues/29579#issuecomment-455974710.

**Comment by armetiz** [comment] 2019-07-09 08:07
Same issue.

```
PHP 7.1.30 (cli) (built: Jul  2 2019 17:22:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.24.4~linux-x64-non_zts71, https://blackfire.io, by Blackfire
```

**Comment by dsentker** [comment] 2020-08-24 15:53
Same issue here (AWS Beanstalk)
```PHP 7.4.7 (cli) (built: Jul  2 2020 23:17:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies```
