### ISSUE TITLE
Domain required in Phpunit test when redirecting

### ISSUE THREAD

**Issue by c33s** [symfony/symfony#21189] opened 2017-01-07 02:14 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

- PHPUnit 5.7.4
- PHP 7.0.13
- Windows7x64
- Symfony 3.2.1

the following test, taken from https://symfony.com/doc/current/testing.html#working-with-the-test-client (scroll up to Useful Assertions), shows the example without domain:

```php
// Assert that the response is a redirect to /demo/contact
$this->assertTrue(
    $client->getResponse()->isRedirect('/demo/contact'),
    'response is a redirect to /demo/contact'
);
```

doing the same in my tests fails:

```php
    public function testPressRedirect()
    {
        $client = static::createClient();
        $client->request('GET', '/press');
        $this->assertTrue($client->getResponse()->isRedirect('/en/press')); //fails
    }
```

routing.yml

```yaml
_press_redirect:
    path: /press
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/press
        permanent: true
```

I have to include the domain and the protocol to make it work:

```php
    public function testPressRedirect()
    {
        $client = static::createClient();
        $client->request('GET', '/press');
        $this->assertTrue($client->getResponse()->isRedirect('http://localhost/en/press')); //works
    }
```

**Comment by xabbuh** [comment] 2017-01-08 12:23
I think this is something that needs to be clarified in the documentation instead.

**Comment by javiereguiluz** [comment] 2017-02-22 14:48
@xabbuh what's exactly the cause for this? I'd like to create the doc change you suggested, but I don't fully understand this. Thanks!

**Comment by xabbuh** [comment] 2017-02-22 17:21
@javiereguiluz In the example where we show how to pass the expected path to `isRedirect()` we should path the full URL instead.

**Comment by javiereguiluz** [comment] 2017-02-22 19:14
That's what I don't understand ... I've checked some of my tests and I don't use the absolute URL ... and they work 😕

**Comment by jakzal** [comment] 2017-02-22 19:28
It all depends on how you generate the url you later pass to the `RedirectResponse`. If you generated an absolute path, the redirect will be made to an absolute path.

**Comment by javiereguiluz** [comment] 2017-02-22 20:09
@jakzal it's all clear now! Thanks!

**Comment by yceruto** [comment] 2017-02-22 20:11
@javiereguiluz you can see an example here: https://github.com/symfony/symfony-demo/pull/481/files#diff-225f8fc4f30fb429a96063d2612368b3R77

**Comment by javiereguiluz** [comment] 2017-02-22 20:18
@c33s at the end this wasn't a Symfony bug but something that could be better documented. That's why I'm closing this and we're improving the docs at https://github.com/symfony/symfony-docs/pull/7521

Thank you all for your help!

**Closed by javiereguiluz** 2017-02-22 20:18 UTC
