### ISSUE TITLE
[Cache] Cannot redeclare class

### ISSUE THREAD

**Issue by zogs** [symfony/symfony#21520] opened 2017-02-03 08:55 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.x-dev

Hi,
After a simple upgrade from 3.2.* to 3.3.x-dev, the cache system does not work normally anymore. 
After upgrade, with a empty cache, the first HTTP request create the cache directory correctly. But the second fail inexorably. Returning exactly this error

`Compile Error: Cannot redeclare class Symfony\Bundle\SecurityBundle\Security\FirewallMap`

I'm pretty sure this looks like to a case-sensitive problem, as my system run on windows with a Vagrant VM hosting debian 8. And this is a frequent problem with that configuration !

I'm not enough confortable with symfony intern mechanism to find the issue myself tough...

**Comment by iltar** [comment] 2017-02-03 09:08
Have you removed the full cache? `rm -rf var/cache`

**Comment by zogs** [comment] 2017-02-03 09:10
Absolutly. Same problem occuring.

**Comment by zogs** [comment] 2017-02-03 09:34
Not sure if case-sensitive problem actually... The same problem persist even when i put the cache directory complely inside the debian file system...

**Comment by chalasr** [comment] 2017-02-03 09:35
Could you try to remove your `var/bootstrap.php.cache` and run `composer install` just after?

**Comment by zogs** [comment] 2017-02-03 09:45
- removing `var/bootstrap.php.cache`
- removing `composer.lock`
- removing `vendor/`
- run `composer install`

problem persist..

**Comment by zogs** [comment] 2017-02-03 10:09
Could this be related to the new Simple Cache system ?

**Comment by nicolas-grekas** [comment] 2017-02-03 10:22
How does this relate to Cache?
But FirewallMap.php changed recently. Can you open it and swap the order of the two classes declaration you'll find in it? Does it work better then?

**Comment by zogs** [comment] 2017-02-03 10:31
I dont know, i thought the problem came from the cache system, as it can be writed once, but not re-writed.

With your suggestion, the error message remains but changes from FirewallMap to _FirewallMap that can't be redeclare etc...

**Comment by javiereguiluz** [comment] 2017-02-03 12:08
Not sure if it's related, but in the Symfony Demo app we had the same problem, but with *"Cannot redeclare class Symfony\Component\HttpFoundation\Response"*. It was solved by #21184.

**Comment by chalasr** [comment] 2017-02-03 12:09
I can't reproduce the issue on OSX+debian with PHP7+.
So maybe this line should be removed indeed https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L116

**Comment by zogs** [comment] 2017-02-03 12:15
@chalasr Removing the line did the trick !

I'm running PHP 5.6 by the way...

**Comment by chalasr** [comment] 2017-02-03 12:20
@zogs Thanks for confirming, fixed in #21521.

@javiereguiluz Nice catch, thanks!

**Closed** 2017-02-03 14:51 UTC
