### ISSUE TITLE
Regression with bundles in 2.8.21 / 3.2.9 / 3.3.0

### ISSUE THREAD

**Issue by remicollet** [symfony/symfony#22984] opened 2017-05-31 08:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | reproduced with 2.8.21, 3.2.9 and  and 3.3.0

```
Invalid argument supplied for foreach()
In vendor/symfony/framework-bundle/Console/Application.php:141
```

More information, See https://github.com/doctrine/DoctrineCacheBundle/issues/111

This looks like a regression.

**Comment by sstok** [comment] 2017-05-31 09:25
It seems no bundles are returned by the method, does your getBundles method in AppKernel return an array/generator?

**Comment by remicollet** [comment] 2017-05-31 09:58
Sorry, but I'm not a symfony expert.

The "kernel" is in this case a mocked objects.
BTW, everything was ok with symfony 2.8.20

**Comment by stof** [comment] 2017-05-31 10:22
I'm closing this. As explained in the DoctrineCacheBundle issue, this is caused by a bad mock definition in their testsuite, which is not something for which we can guarantee compatibility.

**Closed by stof** 2017-05-31 10:22 UTC
