### ISSUE TITLE
MessageHandlerInterface not picking up message handlers

### ISSUE THREAD

**Issue by ricohumme** [symfony/symfony#35527] opened 2020-01-30 15:51 UTC
**Symfony version(s) affected**: ^4.4 currently (4.4.3), possibly ^5.0 as well

**Description**  
According to the documentation the message handler should be picked up by the application once it implements the MessageHandlerInterface. However, having done this, running `bin/console debug:messenger` did not show the message handler. 
After I manually tagged the message handler with the `messenger.message_handler` tag in my services.yaml, it showed up with `debug:messenger`
Am I missing a configuration of some sorts which is not documented?

**How to reproduce**  
Create a Message Handler class according to the documentation `https://symfony.com/doc/4.4/messenger.html#creating-a-message-handler`. Run `bin/console debug:messenger`. It will not show.

**Comment by micheh** [comment] 2020-01-30 17:37
Did you enable the `autoconfigure` Option in the `_defaults` section?
See https://symfony.com/doc/4.4/service_container.html#the-autoconfigure-option

**Comment by ricohumme** [comment] 2020-01-30 18:01
Hi,

Yes, this is set to true

**Comment by Tobion** [comment] 2020-01-31 04:15
Please provide the full code or a repo with the small app to reproduce the issue. E.g. what does `__invoke` of your handler look like?

**Comment by ricohumme** [comment] 2020-01-31 07:58
Hi,

My message object looks like:
```
class DataReviewMessage
{
    ... /** Lines with defined properties */

    public function __construct(int $reviewId, string $user, \DateTime $date)
    {
        $this->reviewId = $reviewId;
        $this->user = $user;
        $this->date = $date;
    }

    ... /** Getters */
}
```
Followed by the message handler:
```
use App\Core\Message\DataReviewMessage;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class DataReviewMessageHandler implements MessageHandlerInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function __invoke(DataReviewMessage $message)
    {
        // Doing stuff here
    }
}
```
And just for complete clarity, the _defaults of my services.yaml:
```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services;

```

Now, when I execute `bin/console debug:messenger` I get the following returned:
```
Messenger
=========
messenger.bus.default
---------------------                                                                                                                     
 [WARNING] No handled message found in bus "messenger.bus.default".                                                     
```
Now I add the following to my services.yaml:
```
    message_handlers:
        namespace: App\
        resource: '../src/*/MessageHandler'
        tags: ['messenger.message_handler']
```
Now when I rerun the command:
```
Messenger
=========

messenger.bus.default
---------------------

 The following messages can be dispatched:

 ----------------------------------------------------------------- 
  App\Core\Message\DataReviewMessage                               
      handled by App\Core\MessageHandler\DataReviewMessageHandler  
 ----------------------------------------------------------------- 

```

**Comment by jwillp** [comment] 2020-02-01 12:48
@ricohumme thank you for the code provided, 
Cannot reproduce on ^5.0, it works as intended. This might be specific to ^4.4

**Comment by Tobion** [comment] 2020-02-01 13:49
Closing as there does not seem to be a bug.
For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Closed by Tobion** 2020-02-01 13:49 UTC
Labels: Bug, Messenger, Status: Needs Review, Status: Waiting feedback

**Comment by peschee** [comment] 2020-02-22 10:56
I'm seeing the same issue in our application using Symfony `5.0.4`. 

Running `php bin/console debug:container App` and then selecting the handler gives:

```
Information for Service "App\MessageHandler\TestMailHandler"
============================================================

 ---------------- ------------------------------------
  Option           Value
 ---------------- ------------------------------------
  Service ID       App\MessageHandler\TestMailHandler
  Class            App\MessageHandler\TestMailHandler
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
 ---------------- ------------------------------------

 ! [NOTE] The "App\MessageHandler\TestMailHandler" service or alias has been removed or inlined when the container was
 !        compiled.
```

Running `bin/console debug:messenger` gives:

```
Messenger
=========

messenger.bus.default
---------------------

 The following messages can be dispatched:

 -----------------------------------------------------
  Symfony\Component\Mailer\Messenger\SendEmailMessage
      handled by mailer.messenger.message_handler
 -----------------------------------------------------
```

Autoconfiguration is enabled in `services.yml`:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

Any ideas / pointers on what this might be related to or where to look?

Adding this to `services.yml` solves the issue:

```
    App\MessageHandler\TestMailMessageHandler:
        tags: [messenger.message_handler]
```

but this means we have to do this for every handler introduced.

**Comment by geraintp** [comment] 2020-05-26 11:11
I had this exact problem but I'd typoed the handlers file name and omitted the 'handler' from the end so it didn't match the contained class name.

**Comment by ali-tit** [comment] 2021-01-18 23:12
Hi, 
thanks @ricohumme for your answer !

I did reproduce the same behavior with **Symfony 4.4** .
my config : 
  ` autowire & autoconfigure are false ( I manually build the container)`

  so even I did as the doc says : 
 ```
  $container->register(SmsNotificationHandler::class)
    ->addTag('messenger.message_handler', [
        // only needed if can't be guessed by type-hint
        'handles' => SmsNotification::class,
    ]);
```
**BUT NOO !!!**  you need to do it with yaml.

  you don't even need to  `implements MessageHandlerInterface` in your handler
