### ISSUE TITLE
Validate hostname length in Symfony\Component\HttpFoundation

### ISSUE THREAD

**Issue by cilefen** [symfony/symfony#12349] opened 2014-10-28 20:35 UTC
getHost() throws an exception for bad characters in hostnames but it does not if a hostname is longer than allowed in RFC http://www.ietf.org/rfc/rfc1035.txt (255 characters). Consider throwing an exception in that case also.

**Comment by stof** [comment] 2015-01-18 15:30
@xelaris strlen is not counting characters. It is counting bytes (which is why you should use mb_strlen when you want to know the number of characters in a UTF-8 string)

**Comment by xelaris** [comment] 2015-01-18 16:18
You are right @stof, my bad. Thank you for the clarification.
Although my explanation wasn't accurate, the conclusion "just checking `strlen($hostname) <== 255` would not fulfill the RFC." is still valid, because of the per label limit of 63 octets and the two octets required to encode the length of the last (empty) label and the length of the first label.

**Comment by phansys** [comment] 2015-01-26 16:52
Hi @cilefen. I'm working in #13522. I'm not a Drupal user, but I'd like to know how can I reproduce the issue mentioned here
Thank you!

**Comment by cilefen** [comment] 2015-01-26 17:02
@phansys That's great. This isn't a Drupal issue as far as I know, just enforcing the RFC. On the Drupal side, there are some length tests in the committed  patch: https://www.drupal.org/files/issues/port_http_host_header-2304949-106.patch

**Comment by mpdonadio** [comment] 2015-01-26 17:07
You can use the command line version of curl, and override the Host header.  I have this in a shell script:

```shell
#!/bin/bash

DOMAIN="localhost"
PORT="80"
URI="/foo/?"${RANDOM}
curl --verbose --header "Host: ${1}" http://${DOMAIN}:${PORT}${URI}
```

I can then run the script and use the first parameter to whatever I want the Host header to be.  For this issue, you would use something like "a.a.a.a ..." to get the proper number of octets and separators.  When validation fails in `::getHost()`, your app will throw an `\UnexpectedValueException` It should also be easy to add this to the test coverage for Request.

**Comment by phansys** [comment] 2015-01-26 17:17
Thank you @mpdonadio, I think [these tests](https://github.com/symfony/symfony/pull/13522/files#diff-ff258be5f9da1f743abc56d08e1affd3R1741) are enough.

**Comment by fabpot** [comment] 2015-02-10 16:45
Closing as there is nothingd to fix here. The code is not about validating the host name, but to ensure there are no dubous characters.

**Closed by fabpot** 2015-02-10 16:45 UTC
Labels: HttpFoundation

**Comment by jakzal** [comment] 2015-02-10 16:50
@fabpot but if I read the bug report correctly, we now allow dubious characters in long host names.
