### ISSUE TITLE
[Serializer] The `#[Ignore]` attribute in var-exporter breaks serialization with 'Ignore can only be added on methods beginning with "get", "is", "has" or "set" error' on `__setInitialized()`

### ISSUE THREAD

**Issue by viccherubini** [symfony/symfony#54502] opened 2024-04-05 17:41 UTC
### Symfony version(s) affected

7.0.6

### Description

The addition of the `#[Ignore]` attribute in the following files appears to have broken serializing entities with uninitialized child objects or collections:

- `var-exporter/Internal/LazyObjectTrait.php`
- `var-exporter/LazyGhostTrait.php`
- `var-exporter/LazyProxyTrait.php`

When loading and attempting to serialize a Doctrine entity with a child relationship, an exception related to the `#[Ignore]` attribute of the `__setInitialized()` method in the proxy class is thrown.

For example, the exception thrown in my application is:

```
Ignore on "Proxies\__CG__\App\Entity\Account::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".
```

### How to reproduce

My application has the following entity hierarchy:

```
Account
  - Users
  - Files
File
  - Account
  - User
```

When fetching a `File` entity (and only a `File` entity), attempting to serialize it (and thus including the `Account` and `User` entities) throws the exception outlined above:

**src/Controller/IndexController.php**
```php
<?php

namespace App\Controller;

use App\Repository\FileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\SerializerInterface;

class IndexController extends AbstractController
{

    #[Route('/files/{fileId}', name: 'view_file')]
    public function viewFile(int $fileId, FileRepository $fileRepository, SerializerInterface $serializer): Response
    {
        $file = $fileRepository->find($fileId);
        $data = $serializer->serialize($file, 'json');

        return JsonResponse::fromJsonString($data, 200);
    }

}
```

**src/Entity/File.php**
```php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FileRepository::class)]
class File
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?int $status = null;

    #[ORM\ManyToOne(inversedBy: 'files')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Account $account = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id')]
    private ?User $uploader = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $source = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $hash = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $path = null;

    #[ORM\Column]
    private ?int $size = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $uri = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $url = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): static
    {
        $this->account = $account;

        return $this;
    }

    public function getUploader(): ?User
    {
        return $this->uploader;
    }

    public function setUploader(?User $uploader): static
    {
        $this->uploader = $uploader;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(string $source): static
    {
        $this->source = $source;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): static
    {
        $this->hash = $hash;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): static
    {
        $this->size = $size;

        return $this;
    }

    public function getUri(): ?string
    {
        return $this->uri;
    }

    public function setUri(string $uri): static
    {
        $this->uri = $uri;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }
}
```

### Possible Solution

Using serialization groups does not fix the issue.

**Comment by xabbuh** [comment] 2024-04-05 18:32
duplicate of symfony/symfony#54477

**Closed as not planned by xabbuh** 2024-04-05 18:32 UTC
Labels: Serializer, Bug, Status: Needs Review, VarExporter
