### ISSUE TITLE
[2.7] [Validation] YAML validation on abstract class is not inherited, annotation does.

### ISSUE THREAD

**Issue by pawel-k-coll** [symfony/symfony#17825] opened 2016-02-17 08:38 UTC
Hi,

i have abstract entity class (superclass), like this:

``` php
abstract class Location
{
    protected $address;
    protected $lat;
    protected $lng;

    // ...
}
```

When i define validation in annotations, like:

``` php
abstract class Location
{
    /**
     * @Assert\Valid
     * @var Address
     */
    protected $address;
    /**
     * @Assert\NotBlank
     * @Assert\Range(
     *      min = -85,
     *      max = 85
     * )
     * @var float
     */
    protected $lat;
    /**
     * @Assert\NotBlank
     * @Assert\Range(
     *      min = -180,
     *      max = 180
     * )
     * @var float
     */
    protected $lng;
}
```

With annotations every class which extends Location is validated, but i can't do the same when i have validation in YAML files, why?

**Comment by courtney-miles** [comment] 2016-11-02 00:15
I have the same question.

I'm new to Symfony Validators and I'm repeating chunks of the same rules over and over in XML configurations for each concrete implementation of an abstract class.

I'm sure this must be unnecessary and that there would be a strategy with XML/YAML configurations to define validations for abstract classes and have other validators use them, without defining custom validators for every instance.

Unfortuantely I have been able to find any information about this, except for this one one post.  
Stackoverflow has not provided answers either.

If it is not possible with XML/YAML configuration, then I feel this is something worth being upfront about in the documentation.  I would not have chosen XML configuration for my project had I known about such a limitation.

**Comment by xabbuh** [comment] 2016-12-25 18:26
@pawel-k-coll @courtney-miles I tried to reproduce your issue, but I was not able to do so. Would you mind forking the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by courtney-miles** [comment] 2017-01-03 02:08
Hi @xabbuh the problem is not a bug, more so than if it could, and if so, how.

Your response made me re-look at how this might be work.  My original expectation was that the XML configuration for the **Concrete Class** would need a descriptor to inherit validation from another XML configuration for the **Abstract Class**.

However, after some experimentation, I see that we only need to define the XML configuration for the **Abstract Class**, and the validator will automatically load the configuration for both the **Concrete and Abstract Class** configurations.

It's obvious now I see it.  I just didn't know that the validator would examine the complete hierarchy of a class to load the appropriate validation configuration.

**Comment by xabbuh** [comment] 2017-01-03 07:42
Thank you for the clarification @courtney-miles. I am closing here then. If you think that we could clarify this in the documentation, I kindly ask you to open a new issue in the docs repository and we can then discuss ways to make this more obvious.

**Closed by xabbuh** 2017-01-03 07:42 UTC
Labels: Enhancement, Unconfirmed, Validator
