### ISSUE TITLE
Translation fallback between brackets

### ISSUE THREAD

**Issue by Laurent3170** [symfony/symfony#18438] opened 2016-04-04 18:57 UTC
Don't know if it's the good place to ask...
I want to add brackets around translation's fallback. i.e. if a message is not found I obtain [fallback_message].
I need this because it shows that the text is not yet translated and not definitive, and the usage is to place a text between brackets when it's not definitive.
I don't know where to search to add this.
Thanks for your help!

**Comment by javiereguiluz** [comment] 2016-04-06 08:19
@Laurent3170 in the past we received a similar feature request to add CSS styles to untranslated messages (https://github.com/symfony/symfony/issues/16764). We rejected that because it would introduce lots of issues.

Maybe @aitboudad, out translation expert, can give you a quick hint to implement this, but I'd also try asking about this on StackOverflow (see http://symfony.com/support).

Given all this, I'm closing the issue because it's not a bug report or a feature request about Symfony. Thanks!

**Closed by javiereguiluz** 2016-04-06 08:19 UTC
Labels: Feature, Translator

**Comment by Laurent3170** [comment] 2016-04-06 08:29
Ok, thanks for your explanations. Note that adding brackets is simpler than a specific class and has no specific issues and moreover it's the usage in the world of edition ;-)
If you can let me know the url of your question on StackOverflow, I'll follow it.
Thanks again

**Comment by aitboudad** [comment] 2016-04-06 08:31
@Laurent3170 let me some time, I'll give you how to do it ;)

**Comment by javiereguiluz** [comment] 2016-04-06 08:32
@Laurent3170 sorry for the misunderstanding, but I didn't ask about this. I meant that you can ask on StackOverflow because the Symfony tag is pretty active.

**Comment by Laurent3170** [comment] 2016-04-06 08:43
@javiereguiluz ok.
@aitboudad thanks. I can help if needed, just need to know where to look.

**Comment by aitboudad** [comment] 2016-04-06 08:46
@Laurent3170 see [LoggingTranslator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/LoggingTranslator.php#L119)

**Comment by aitboudad** [comment] 2016-04-06 09:06
@Laurent3170  check my commit: https://github.com/aitboudad/symfony-standard/commit/8431f96ffb3c631ad5cb9af1b7fef5f6b6477b25, to get it easily

**Comment by Laurent3170** [comment] 2016-04-06 09:37
Thanks for your work! So the markAsMissing is the answer to my need :smile:.
As I'm not yet really familiar with Symfony commit process, I think I will have to edit my file (Translator.php as I don't have AppTranslator.php, using Symfony 3.0.4) to reflects your changes. Is it exact ?

**Comment by aitboudad** [comment] 2016-04-06 09:44
not sure if I understand, you should create a custom translator instead of default one, and adding your needs. you can use any version of `symfony > 2.7`

**Comment by Laurent3170** [comment] 2016-04-06 09:52
Yes, it was a misunderstanding from me... I will create a custom translator, based on your work, and use it through my applications. Thanks again!
