### ISSUE TITLE
Add AsciiSlugger getLocale() return type

### ISSUE THREAD

**Issue by zip-fa** [symfony/symfony#44280] opened 2021-11-25 20:44 UTC
### Symfony version(s) affected

5.4.0

### Description

AsciiLogger has no return type in getLocale() function

### How to reproduce

```
"require": {
    "php": ">=8.1",
    "composer/package-versions-deprecated": "1.11.99.1",
    "doctrine/doctrine-bundle": "^2.5",
    "doctrine/doctrine-migrations-bundle": "^3.1",
    "doctrine/orm": "^2.10.2",
    "phpdocumentor/reflection-docblock": "^5.3.0",
    "symfony/console": "5.4.*",
    "symfony/dotenv": "5.4.*",
    "symfony/expression-language": "5.4.*",
    "symfony/filesystem": "5.4.*",
    "symfony/flex": "^1.3.1",
    "symfony/framework-bundle": "5.4.*",
    "symfony/http-client": "5.4.*",
    "symfony/intl": "5.4.*",
    "symfony/lock": "5.4.*",
    "symfony/messenger": "5.4.*",
    "symfony/mime": "5.4.*",
    "symfony/monolog-bundle": "^3.7",
    "symfony/property-access": "5.4.*",
    "symfony/property-info": "5.4.*",
    "symfony/proxy-manager-bridge": "5.4.*",
    "symfony/security-bundle": "5.4.*",
    "symfony/serializer": "5.4.*",
    "symfony/string": "5.4.*",
    "symfony/twig-bundle": "5.4.*",
    "symfony/uid": "5.4.*",
    "symfony/validator": "5.4.*",
    "symfony/yaml": "5.4.*"
}
```

### Possible Solution

Add return type:

string/Slugger/AsciiSlugger.php:93
public function getLocale(): string

Temp fix, composer.json:
- "symfony/translation": "5.4.*"

### Additional Context

PHP Fatal error:  Declaration of Symfony\Component\String\Slugger\AsciiSlugger::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string in /vendor/symfony/string/Slugger/AsciiSlugger.php on line 93

**Comment by derrabus** [comment] 2021-11-26 00:38
Duplicate of #44246

**Closed as completed by derrabus** 2021-11-26 00:38 UTC
Labels: Bug, Status: Needs Review
