### ISSUE TITLE
Fix MandrillApiTransport response toArray 

### ISSUE THREAD

**Issue by Arthurhall** [symfony/symfony#34626] opened 2019-11-26 10:56 UTC
**Symfony version(s) affected**: 4.4.0

**Description**  

Here : https://github.com/symfony/mailchimp-mailer/blob/v4.4.0/Transport/MandrillApiTransport.php#L51
The `$result` variable first key is `0`. The key `0` contains the array with status, _id, etc ...

**Possible Solution**  

```php
        $result = $response->toArray(false);
        if (!isset($result['_id']) && isset($result[0]) && isset($result[0]['_id'])) {
            $result = $result[0];
        }
```

**Additional context**

**Comment by stof** [comment] 2019-11-26 11:02
Duplicate of https://github.com/symfony/symfony/pull/34597 which is already fixed by https://github.com/symfony/symfony/pull/34599 (will be in the next patch release)

**Closed by stof** 2019-11-26 11:02 UTC
