### ISSUE TITLE
[DotEnv]: Environment variables in .env are evaluated as empty strings

### ISSUE THREAD

**Issue by Abdull** [symfony/symfony#34598] opened 2019-11-25 14:55 UTC
**Symfony DotEnv version(s) affected**: v4.3.6 up until at least v4.3.8

**Description**  
Using environment variables in `.env` files fails.

**How to reproduce**  
* Create `.env` file with the following content:
```
MY_HOSTNAME=${HOSTNAME}
```
where `HOSTNAME` is an existing environment variable.

* Expected result: `MY_HOSTNAME` will have the value of the `HOSTNAME` environment variable.
* Actual result : `MY_HOSTNAME` has no value.

**Additional context**  
I ran into this problem in the context of TYPO3 9LTS with dependency [*dotenv-connector:v2.1.2*](https://github.com/helhum/dotenv-connector) which has a dependency on *symfony/dotenv:^4.0*

**Comment by xabbuh** [comment] 2019-11-26 09:10
I was not able to reproduce this issue. Can you please create a small example project that allows to do so?

**Comment by Abdull** [comment] 2019-11-29 14:47
Please see the following diff between `v4.3.5` and `v4.3.6` https://github.com/symfony/dotenv/compare/v4.3.5..v4.3.6#diff-a6967492da82dce9ba93bcba3eee0334L456 .


`v4.3.5` works for me, `v4.3.6` does not work for me.

```
# ...
MY_TEMP=${TEMP}
# ...
```

`${TEMP}` is an environment variable provided by the operating system (I tested with Windows 7 and debian-docker).

The mentioned diff changed `$value = (string) getenv($name);` to `$value = '';` ([relevant blame](https://github.com/symfony/dotenv/blame/v4.3.6/Dotenv.php#L461)).

It turns out that for my environments the `getenv()` call is required to retrieve `${TEMP}` 's value, as `${TEMP}` is not in `$_ENV[]`.

Also see a [StackOverflow answer discussing `getenv()` vs `$_ENV[]`](https://stackoverflow.com/a/21473853/923560): "*$_ENV is not always populated due to different configurations of variables_order so it's best if you avoid $_ENV if you don't control the server configuration.*".

**Comment by nicolas-grekas** [comment] 2019-11-30 12:59
Would you mind sending a PR that reverts the change on that line?

**Comment by jeff1985** [comment] 2019-12-10 16:51
This problem broke our deployments. Reproducible for all of our microservices upgrading to 4.4. breaks our deployment. I also verified that setting variables_order="EGPCS" fixes the problem. However I think this should be fixed in the code.

**Closed** 2019-12-18 21:42 UTC
Labels: Bug, Dotenv

**Comment by andreasganje** [comment] 2019-12-19 09:44
@nicolas-grekas thanks for merging the fix into 3.4. the same issue exists in 4.4 too. will the fix also be added there or should one create an new issue for that?

**Comment by xabbuh** [comment] 2019-12-19 11:51
@andreasganje We regularly merge branches up into all still maintained branches (i.e. `4.3`, `4.4`, `5.0` and `master` right now).
