### ISSUE TITLE
Testing standalone bundle - got 'Could not find service "test.service_container".'

### ISSUE THREAD

**Issue by smilesrg** [symfony/symfony#41715] opened 2021-06-15 13:18 UTC
I'm writing a standalone bundle and trying to test it. But got an error:

`LogicException: Could not find service "test.service_container". Try updating the "framework.test" config to "true".`

I couldn't find anything in the documentation related to this error. How can I fix that?

UPD: I tried obvious solution by creating `config/config_test.yml` and even renamed extension to `.yaml` but it didn't help, content of the file is:

```yaml
framework:
    test: true
```
The content of `phpunit.xml.dist` (renamed to `.txt` due to github limitations):
[phpunit.txt](https://github.com/symfony/symfony/files/6656035/phpunit.txt)

**Comment by xabbuh** [comment] 2021-06-15 13:57
Can you create a small example application that allows to reproduce your issue?

**Comment by smilesrg** [comment] 2021-06-15 13:58
Sure, you can check out this https://github.com/inspector-apm/inspector-symfony/tree/0b5af59e85766f33fa5045bccc8c1929587bd4d8 and try to launch tests

**Comment by nicolas-grekas** [comment] 2021-06-15 15:04
That's because in 5.3 we unconditionally use the `test.service_container` service to get the session.
This has been fixed on 5.4 in https://github.com/symfony/symfony/pull/41530, we might want to backport part of it.
PR welcome!

**Closed as completed** 2021-06-17 12:08 UTC
