### ISSUE TITLE
[WebServerBundle] Environment variables are not reloaded when the .env file was changed

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony#23723] opened 2017-07-30 23:14 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 4.0

I think this problem occurs because when the server is started (see https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console#L20), the `.env` file is loaded and then, loaded variables cannot be overridden, because a Dotenv component doesn't override the existing ones.
We could solve this issue by adding an ability to Dotenv component to override the existing environment variables.

**Comment by javiereguiluz** [comment] 2017-07-31 07:37
I'm afraid I don't understand the exact problem:

* Dotenv doesn't **reload** the `.env` file and that's why if you change its contents, you don't see any change?
* Dotenv doesn't **override** the existing env vars in your computer if their names match the ones found in `.env` file?

**Comment by voronkovich** [comment] 2017-07-31 08:14
@javiereguiluz. To be more concise - the __front controller__ doesn't __reload__ the `.env` file because the `APP_ENV` variable is already loaded since the server's process inherits its parent's process variables.
```php

// This piece of code occurs in the bin/console and in the front controller
if (!getenv('APP_ENV')) {
    (new Dotenv())->load(__DIR__.'/../.env');
}
```

**Comment by voronkovich** [comment] 2017-07-31 09:32
@javiereguiluz, I've created a simple application that reproduces the problem. See https://github.com/voronkovich/symfony-ureloadable-envs

**Comment by chalasr** [comment] 2017-07-31 10:55
Marking this as a feature request for the ability to overload env vars.

**Comment by nicolas-grekas** [comment] 2017-08-05 17:15
Got it :)
Instead of #23761 and #23720, I suggest a third approach: configuration via env vars:
when creating vars, Dotenv would add a special additional env var, let's call it `DOTENV_VARS`, that would contain all env var names that it created, separated by a `=` (an impossible char in a name) eg.:
`$_SERVER['DOTENV_VARS'] = 'FOO=BAR';`.

Reciprocally, when this env var is set, Dotenv would allow overriding of the listed vars.
That should fix this issue and open for more use cases.

**Comment by fabpot** [comment] 2017-08-05 17:38
What about resetting env vars at the end of each request when using the Symfony web server?

**Comment by voronkovich** [comment] 2017-08-05 17:56
@nicolas-grekas, Your solution sounds great for me! So, the front controller will look like this?:
```php
if (file_exists(__DIR__'/../.env')) {
    (new Dotenv())->load(__DIR__.'/../.env');
}
```

**Comment by nicolas-grekas** [comment] 2017-08-05 19:42
@fabpot the issue is the subprocess that runs `php -S`: it inherits real env vars from the parent process, which itself created "false" env vars from `.env`. I don't think we can do anything between each request that would fix that. Or I have missed the point :)

@voronkovich I wouldn't change at all the front controller, but I would change the WebServer so that it doesn't forward the APP_ENV var when the var has been created by Dotenv (which we can know by looking at DOTENV_VARS there.)

**Comment by voronkovich** [comment] 2017-08-05 19:58
@nicolas-grekas, so, we should add a method to remove all loaded envs? `Dotenv::removeLoadedVars` or something like this.
```php
// WebServer.php

(new Dotenv())->removeLoadedVars();
```
Maybe it's better to release the WebServer as a standalone app? See https://github.com/symfony/symfony/issues/23771

**Comment by nicolas-grekas** [comment] 2017-08-05 20:56
If we can make it work without any change, that'd be the best. I don't think we need to make it standalone. At least I don't see the benefit. Fixing this issue doesn't require any new method nor class to me, it just needs dealing with an env var in some places. At least I'd make it work that way first, and of course the discussion can go on.

**Comment by voronkovich** [comment] 2017-08-06 01:37
@nicolas-grekas, I've created a PR with implementation of your idea: https://github.com/symfony/symfony/pull/23799 Could you please take a look at the code?

**Closed** 2017-08-22 13:34 UTC
Labels: Dotenv, Feature, Status: Needs Review
