### ISSUE TITLE
Global request variables are missing inside rendered controller

### ISSUE THREAD

**Issue by sc0rp10** [symfony/symfony#24574] opened 2017-10-16 11:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Inside rendered controller global request variables are broken.
**layout.html.twig**:
```twig
{{ dump(app.request.query.all) }}
{{ render(controller('AppBundle:Content:menu')) }}
```
**menu.html.twig**:
```twig
{{ dump(app.request.query.all) }}
```

By url `/?foo=bar` I see:
```
array:1 [▼
  "foo" => "bar"
]
# from layout.html.twig

array:0 []
# from menu.html.twig
```

How can I get request params inside rendered controller? How can I globally avoid this behavior for any rendered controllers?

**Comment by iltar** [comment] 2017-10-16 14:25
It's a subrequest so if you want to pass this information to your menu, you will have to do so as arguments in your `controller()` function.

```twig
{{ render(controller('AppBundle:Content:menu', {'foo': app.request.query.get('foo')})) }}
```

Afaik this is intended behavior.

**Comment by sc0rp10** [comment] 2017-10-16 15:01
@iltar i don't want to pass all of global variables inside each rendered controller. is there common way to catch all *global* variables inside *any* template?

**Comment by yceruto** [comment] 2017-10-16 15:24
@sc0rp10 you can access to `request_stack` service to check the master request instance and their vars.

**Comment by iltar** [comment] 2017-10-16 16:10
@sc0rp10 you could probably pass the request object, but personally I would avoid that. Your subrequest shouldn't know about the parent request.

**Comment by stof** [comment] 2017-10-16 16:20
@sc0rp10 the Request is not a global variable in Symfony. This is precisely one of the point about encapsulating it in an object.
There is a single global variable available in the template by default, and it is `app`. the request itself is not available as a Twig global variable. The *current* request can be accessed from `app`

**Comment by javiereguiluz** [comment] 2017-10-18 06:44
@sc0rp10 I'm closing this issue because, as explained in the comments, this is the expected behavior. You can use any of the proposed alternatives, or even use sessions to store those global vars. Thanks!

**Closed by javiereguiluz** 2017-10-18 06:44 UTC
