### ISSUE TITLE
[Dotenv] Incompatible use of dynamic environment variables

### ISSUE THREAD

**Issue by jhonatanTeixeira** [symfony/symfony#28165] opened 2018-08-08 14:13 UTC
**Symfony version(s) affected**: ^4.1

**Description**  

when clearing the cache or trying to run builtin server command i get the following message:

```
In Compiler.php line 112:

  Incompatible use of dynamic environment variables "LIIP_DRIVER" found in parameters.


In DriverCompilerPass.php line 32:

  Specified driver 'liip_imagine.%env(LIIP_DRIVER)%' is not defined.
```

**How to reproduce**  
I've done the following configuration for the liip imagine bundle:

```yml
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: '%env(LIIP_DRIVER)%'
```

**Possible Solution**  
Using the good old parameters.yml style solved the issue

**Comment by ro0NL** [comment] 2018-08-08 15:37
I think the error is legit. The `driver` node is incompatible with dynamic values as apparently it needs to be known during compile time, by design.

> Using the good old parameters.yml style solved the issue

So you don't need this value to be dynamic?

Perhaps from the bundle perspective it's possible to register a custom driver service working based on the env var, e.g. `driver: "custom"`.

**Comment by jhonatanTeixeira** [comment] 2018-08-08 18:07
I need it to be environment specific, wich was true for the old parameters.yml, some machines going to use GD other going to use imagick. And so i cannot have this hardcoded, i need something that uses the machines environment. 
This error wasn't presented by the bundle itself, it was presented by symfony somehow.
It is possible to write a custom driver, but why should i sisnce the bundle provides me the drivers i want to use. and why symfony has removed the incenteev parameter handler by default if this Dotenv file dont solve all the use cases the other solution solved? I wonder if its a bug or intended

**Comment by xabbuh** [comment] 2018-08-08 20:14
As explained environment variables cannot be used for config options whose value needs to be evaluated at compile time. Most of the times you don't need the parameter handler in Symfony applications nowadays. But there are valid use cases (like yours seems to be) for it and you can still use it. I am closing here as the observed behaviour is expected and there is nothing to fix.

**Closed by xabbuh** 2018-08-08 20:14 UTC

**Comment by jhonatanTeixeira** [comment] 2018-08-08 21:55
Excuse me but, whats the difference between the doctrine's connection url configuration to the liip imagine bundle drivers choice? Both of them resides on a package.yaml configuration
How can i classify which of those are or are not compile time?

**Comment by xabbuh** [comment] 2018-08-09 16:34
Doctrine does not evaluate the connection URL at compile time. If it were doing that, we would experience a similar error message. For some bundles you may find documentation on what information is needed at compile time. If not, you will have to try out and check for errors during compilation (or read the code, but that's usually harder than just trying).
