### ISSUE TITLE
make:migration command freezes after update to 5.1.2

### ISSUE THREAD

**Issue by graferowy** [symfony/symfony#37322] opened 2020-06-17 12:38 UTC
After updating symfony from 5.0.8 to 5.1.2, command "make:migration" stopped working.
New table "doctrine_migration_versions" in my database has been created, new directory "migrations" in project directory has been created, but they are empty at all times.
After running make:migration command it freezes. It just hangs there infinitely without any message or error.

config file doctrine_migrations.yaml is default
```
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
```

before update everything worked fine.

Symfony: 5.1.2
PHP: 7.2.8
orm-pack: 1.0.8

**Comment by maartendekeizer** [comment] 2020-06-17 18:16
Same issue here. I found that I had one migration not executed, after running that one (with `bin/console doctrine:migrations:migrate`) I was able to run make:migration again.

**Comment by zohurul88** [comment] 2020-07-02 04:14
I have faced the same issue.
The real problem is somehow it misses printing the confirm question. which is "Are you sure you wish to continue?"
the console actually waiting for your response if you hit "y" and enter it will continue.

**Comment by neverlose-lv** [comment] 2020-07-03 08:54
> Same issue here. I found that I had one migration not executed, after running that one (with `bin/console doctrine:migrations:migrate`) I was able to run make:migration again.

Yes, this is the cause of the problem and it should be fixed!

**Comment by fabpot** [comment] 2020-07-15 13:03
Looks like this should be reported in https://github.com/symfony/maker-bundle not symfony/symfony.

**Closed by fabpot** 2020-07-15 13:03 UTC

**Comment by bryanherediax** [comment] 2020-07-17 03:05
> I have faced the same issue.
> The real problem is somehow it misses printing the confirm question. which is "Are you sure you wish to continue?"
> the console actually waiting for your response if you hit "y" and enter it will continue.

This solved it for me. Thanks!

**Comment by KASOGIT** [comment] 2020-08-10 16:04
> I have faced the same issue.
> The real problem is somehow it misses printing the confirm question. which is "Are you sure you wish to continue?"
> the console actually waiting for your response if you hit "y" and enter it will continue.

Thanks a lot
