### ISSUE TITLE
choice_value: Call to a member function non-object

### ISSUE THREAD

**Issue by hous04** [symfony/symfony#21116] opened 2016-12-31 17:48 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.2.1

I'm using **Symfony3.2** , I get this error when **using choice_value** in the formType but it works good with **symfony3.1**

> "Error: Call to a member function getSlug() on a non-object" at D:\wamp\www\my_project\src\AppBundle\Form\Bien\BienType.php line 77

```php
use AppBundle\Entity\Ville;
//......
->add('ville', EntityType::class, array(

            'class' => 'AppBundle:Ville',
            'label' => 'Ville',
            'choice_label' => 'nom',
            'placeholder' => 'Ville ',
            'multiple' => false,
            'expanded' => false,
            'choice_value' => function ($ville) {
                /** @var Ville $ville */
                return $ville->getSlug();
            },
        ))
```

but it works fine with **choice_label**:

```php
'choice_label' => function ($ville) {
                /** @var Ville $ville */
                return $ville->getSlug();
            },
```

I have the same code with **choice_value** in another project with **Symfony3.1** and it works good.

**Comment by iltar** [comment] 2016-12-31 21:36
Have you tried testing multiple arguments? It could be that you need the second argument.

A side note, why not type hint the Ville directly in your callable? `function (Ville $ville) {}`

**Comment by hous04** [comment] 2017-01-01 16:12
Today I have installed **Symfony 3.1** and I have tested **choice_value** and I get the same error but no error with the **ancien** Symfony3.1 installed since **some months ago**. I think there are some updates are made on Symfony and causes a bug , is it possible ?

**Comment by yceruto** [comment] 2017-01-02 02:59
> Have you tried testing multiple arguments? It could be that you need the second argument.

Unlike `choice_label` [this closure function receives one argument only](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L164).

@hous04: (Since 2.7) the `choice_value` option is used also [to transform the initial data to string value](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L37), i.e. if you pass a closure function you take control over initial data transformation as well, if it is `null`, you needs to check it before to call to `$ville->getSlug()`:

```php
'choice_value' => function (Ville $ville = null) {
    return $ville ? $ville->getSlug() : '';
},
```

The typehint is good in this case, you has a signature constraint and IDE autocompletation, however you need set default `null` to avoid typehint exception for `null` initial data.

I think it should be documented because devs expect (like others `choice_*`) deals with `'choices'` elements only.

Status: Reviewed

**Comment by yceruto** [comment] 2017-01-02 03:25
To reproduce it, just adds a new test in [ChoiceTypeTest](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php) like this:

```php
public function testTryingToGetPropertyOfNonObject()
{
    $form = $this->factory->create('choice', null, array(
        'multiple' => false,
        'expanded' => false,
        'choices' => $this->objectChoices,
        'choices_as_values' => true,
        'choice_label' => 'name',
        'choice_value' => function ($object) {
            return $object->id;
        },
    ));

    $form->createView();
}
```
Error output:

```
PHPUnit 5.1.7 by Sebastian Bergmann and contributors.

Testing Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest

Trying to get property of non-object
 /home/yceruto/2.7/symfony/.phpunit/phpunit-5.1/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:72
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:1716
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php:164
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php:37
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Form.php:1146
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Form.php:353
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Form.php:478
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/FormBuilder.php:226
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/FormFactory.php:39
 /home/yceruto/2.7/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:1717
```

**Comment by hous04** [comment] 2017-01-02 10:29
@yceruto Thank you very much , it works good now.

using your method
```php
'choice_value' => function (Ville $ville = null) {
                    return $ville ? $ville->getSlug() : '';
                },
```
or like this too:
```php
'choice_value' => function ($ville) {
                    /** @var Ville $ville */
                    return $ville ? $ville->getSlug() : '';
                },
```

**Comment by MatTheCat** [comment] 2017-01-02 11:01
`@var` tag is wrong and useless. You have no reason not to use typehinting.

**Comment by xabbuh** [comment] 2017-01-03 17:30
I am closing here as this is not a bug in Symfony, but something that needs to be clarified in the documentation. I opened symfony/symfony-docs#7311 to keep track of it.

**Closed by xabbuh** 2017-01-03 17:30 UTC
Labels: Bug, Form, Status: Reviewed
