### ISSUE TITLE
[Intl][Twig] Make Intl\ResourceBundle functions as twig functions or filter

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony#21545] opened 2017-02-06 14:52 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.*

i think the functions from Intl/ResourceBundle should be awailable as twig functions or filter.
like doing "` val | language_name`" should do "`Intl::getLanguageBundle()->getLanguageName(val)`"
I Think Filter is better than Function?

but i don't know if they should be added to Symfony/Bridge/Twig, or be an extra bundle.

what should it be use for?
like when creating an view of a Model or Entity and you get "de" as value it should be turn it into "German".

**Comment by javiereguiluz** [comment] 2017-02-06 14:59
@Hanmac thanks for your proposal. Personally I think it would make a lot of sense 👍 

However, I must close this issue as a duplicate of #13641.

**Closed by javiereguiluz** 2017-02-06 14:59 UTC
