### ISSUE TITLE
asset namespaces is only for css and not less?

### ISSUE THREAD

**Issue by cordoval** [symfony/symfony#14139] opened 2015-03-31 15:43 UTC
I am having weird issues with common js and css libraries after going asset namespaces
is this buggy or not tested with e.g. less assets? bootstrap-select and others fail.

**Comment by stof** [comment] 2015-03-31 15:46
I don't understand what you mean. Please describe the issue you have

**Comment by cordoval** [comment] 2015-03-31 15:49
font awesome and bootstrap select for instance don't load icons or don't work whenever i have code like below:
```
        main_block_of_css:
            inputs:
                - 'style/responsive-tables.css'
                - ....
                - 'components/select2/select2.css'
                # todo check why moving this here hides the icons
                #- 'components/bootstrap-select/less/bootstrap-select.less'
                - 'components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css'
                - ...
                # todo check why moving this here hides the icons
                # - 'components/font-awesome/less/font-awesome.less'
                - 'components/ionicons/less/ionicons.less'
                - ...
```
Notice the # commented parts. Right now they are moved into the templates. But if i move them here in the yaml file then it stops working as described above.

**Comment by fabpot** [comment] 2015-10-05 12:04
Closing as it looks like a support question, not a bug.

**Closed by fabpot** 2015-10-05 12:04 UTC
