### ISSUE TITLE
Textarea field is always "required"

### ISSUE THREAD

**Issue by jaddawyn** [symfony/symfony#14820] opened 2015-06-01 19:01 UTC
Hi developpers, and many thanks for your great job on symfony.

Here is a bug I've notice on Symfony version 2.3.30

I have:
* In my form class:
```php
class FicheReperageMotifType extends AbstractType {
	
	public function buildForm(FormBuilderInterface $builder, array $options) {
            ...
		$options = array('label' => 'The label:');
		$options['attr'] = array('rows' => '10', 'style' => "width:100%; display:block");
		$builder->add("precisez", 'textarea', $options);
	}
}
```

* In my entity class:
```php
	/**
     *
     * @ORM\Column(name="precisez", type="string", length=5000, nullable=true)
     */
    private $precisez;
```

* In my twig template:
<pre>
{{ form(form) }}
</pre>

* The final HTML render is:
```html
<textarea id="FicheReperage_motif_precisez" name="FicheReperage[motif][precisez]" required="required" rows="10" style="width:100%; display:block">precisez</textarea>
```
As you can see the field is required, but nullable=true. Therefore this field should not be required.

* If I leave symfony decide itself the field type by setting:
```php
		$options = array('label' => 'The label:');
		$options['attr'] = array('rows' => '10', 'style' => "width:100%; display:block");
		$builder->add("precisez", null, $options);
```

I have the following HTML render:
```html
<input type="text" id="FicheReperage_motif_precisez" name="FicheReperage[motif][precisez]" maxlength="5000" rows="10" style="width:100%; display:block" value="precisez">
```
And this time it is correct.

Please let me know if you need more information.

Best regards,

**Comment by apfelbox** [comment] 2015-06-01 19:22
If you specify no type of the form field (`$builder->add(..., null, ...);`) the form type guesser is used to define default options for your field. It looks into your doctrine definition, sees the `nullable=true` and deduces that this field is not required. It sets the options `$options["required"] = false;`.

In your first example you explicity specify a type (`$builder->add(..., "textarea", ...);`) therefore the type guesser is *not* used to deduce further options for your form field. And because of this the default value of `$options["required"]` is used, which is `true`.

So it is not related to you using a textarea, but to specifying a type or not.

See #7868, other related tickets and the other ticket about changing the default value of `"required"`, that I can't find in the moment.

**Comment by jakzal** [comment] 2015-06-02 07:33
@apfelbox is right. Closing as this is not a bug.

@jaddawyn you can read about it in [the form docs](http://symfony.com/doc/current/book/forms.html#field-type-guessing):

> The "guessing" is activated when you omit the second argument to the add() method (or if you pass null to it).

**Closed by jakzal** 2015-06-02 07:33 UTC

**Comment by Tobion** [comment] 2015-06-02 09:44
Duplicate of #7868
