### ISSUE TITLE
Preload fails with error related to reflection in PHP8.0rc2

### ISSUE THREAD

**Issue by adhocore** [symfony/symfony#38836] opened 2020-10-27 05:38 UTC
**Symfony version(s) affected**: 5.1.7

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ReflectionUnionType::isBuiltin() 
in <project>/vendor/symfony/dependency-injection/Dumper/Preloader.php:116
```
**Description**  

**How to reproduce**  
Just trying to preload the framework generated preload file in cache dir.

**Comment by derrabus** [comment] 2020-10-27 05:47
~~Duplicate of #38693.~~

Wrong link, see below.

**Closed as completed** 2020-10-27 05:47 UTC
Labels: Bug

**Comment by adhocore** [comment] 2020-10-27 11:55
while they seem related, probably not duplicate.
this one is for php8 and not related to exception but reflection:
`unknown method ReflectionUnionType::isBuiltin()`

**Comment by nicolas-grekas** [comment] 2020-10-27 11:57
Wrong link, here is the fix #38699

**Comment by derrabus** [comment] 2020-10-27 12:17
Right, sorry. 🙈
