### ISSUE TITLE
Composer "Class 'Symfony\Component\Translation\Loader\ArrayLoader' not found" Error

### ISSUE THREAD

**Issue by Dectom** [symfony/symfony#43225] opened 2021-09-28 09:52 UTC
**Symfony version(s) affected**: v4.4.31 I think

**Description**
No code has changed for us, Attempted a Composer install on a fresh instance and got this error, attempted a dump auto-load on an existing instance and got the same error... No matter what we do here running composer install or dump it returns the following 

I have attempted to checkout a version of our project where a deployment was functional and it still has this error.

```
Generating optimized autoload files
Class Symfony\Component\Translation\Formatter\ChoiceMessageFormatterInterface located in ./vendor/symfony/translation/ChoiceMessageFormatterInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\IniFileDumper located in ./vendor/symfony/translation/IniFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DataCollector\TranslationDataCollectorTest located in ./vendor/symfony/translation/DataCollector/TranslationDataCollectorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\DependencyInjection\TranslatorPass located in ./vendor/symfony/translation/TranslatorPass.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\DependencyInjection\TranslationDumperPass located in ./vendor/symfony/translation/TranslationDumperPass.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\MoFileLoaderTest located in ./vendor/symfony/translation/MoFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\JsonFileLoader located in ./vendor/symfony/translation/JsonFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\CsvFileLoaderTest located in ./vendor/symfony/translation/CsvFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\InvalidResourceException located in ./vendor/symfony/translation/InvalidResourceException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\MoFileLoader located in ./vendor/symfony/translation/MoFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Command\XliffLintCommand located in ./vendor/symfony/translation/XliffLintCommand.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\LogicException located in ./vendor/symfony/translation/LogicException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Catalogue\MergeOperation located in ./vendor/symfony/translation/MergeOperation.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\PhpFileDumper located in ./vendor/symfony/translation/PhpFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\QtFileDumper located in ./vendor/symfony/translation/QtFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\XliffFileDumperTest located in ./vendor/symfony/translation/XliffFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DataCollector\TranslationDataCollectorTest located in ./vendor/symfony/translation/TranslationDataCollectorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\JsonFileDumperTest located in ./vendor/symfony/translation/JsonFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\FileLoader located in ./vendor/symfony/translation/FileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\XliffFileDumper located in ./vendor/symfony/translation/XliffFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\IcuResFileLoader located in ./vendor/symfony/translation/IcuResFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\QtFileDumperTest located in ./vendor/symfony/translation/QtFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\ArrayLoader located in ./vendor/symfony/translation/ArrayLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\YamlFileDumperTest located in ./vendor/symfony/translation/YamlFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\ExceptionInterface located in ./vendor/symfony/translation/ExceptionInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\IdentityTranslatorTest located in ./vendor/symfony/translation/IdentityTranslatorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\PluralizationRulesTest located in ./vendor/symfony/translation/PluralizationRulesTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\TargetOperationTest located in ./vendor/symfony/translation/TargetOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\CsvFileDumper located in ./vendor/symfony/translation/CsvFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\RuntimeException located in ./vendor/symfony/translation/RuntimeException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\CsvFileDumperTest located in ./vendor/symfony/translation/CsvFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\MoFileDumperTest located in ./vendor/symfony/translation/MoFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceMethodCalls located in ./vendor/symfony/translation/ServiceMethodCalls.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationPathsPassTest located in ./vendor/symfony/translation/TranslationPathsPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\TranslatorCacheTest located in ./vendor/symfony/translation/TranslatorCacheTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\StaleResource located in ./vendor/symfony/translation/TranslatorCacheTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceArguments located in ./vendor/symfony/translation/ServiceArguments.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Extractor\PhpExtractorTest located in ./vendor/symfony/translation/PhpExtractorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\YamlFileLoaderTest located in ./vendor/symfony/translation/YamlFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Util\ArrayConverter located in ./vendor/symfony/translation/ArrayConverter.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\QtFileLoaderTest located in ./vendor/symfony/translation/QtFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceProperties located in ./vendor/symfony/translation/ServiceProperties.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Extractor\AbstractFileExtractor located in ./vendor/symfony/translation/AbstractFileExtractor.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Extractor\ExtractorInterface located in ./vendor/symfony/translation/ExtractorInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\JsonFileLoaderTest located in ./vendor/symfony/translation/JsonFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\AbstractOperationTest located in ./vendor/symfony/translation/AbstractOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\LoaderInterface located in ./vendor/symfony/translation/LoaderInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Extractor\PhpExtractorTest located in ./vendor/symfony/translation/Extractor/PhpExtractorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\InvalidArgumentException located in ./vendor/symfony/translation/InvalidArgumentException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\XliffFileLoaderTest located in ./vendor/symfony/translation/XliffFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Util\ArrayConverterTest located in ./vendor/symfony/translation/ArrayConverterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\YamlFileLoader located in ./vendor/symfony/translation/YamlFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\PoFileDumper located in ./vendor/symfony/translation/PoFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Command\XliffLintCommandTest located in ./vendor/symfony/translation/XliffLintCommandTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IcuDatFileLoaderTest located in ./vendor/symfony/translation/IcuDatFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\TranslatorTest located in ./vendor/symfony/translation/TranslatorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\StringClass located in ./vendor/symfony/translation/TranslatorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\DependencyInjection\TranslationExtractorPass located in ./vendor/symfony/translation/TranslationExtractorPass.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Catalogue\AbstractOperation located in ./vendor/symfony/translation/AbstractOperation.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\QtFileLoader located in ./vendor/symfony/translation/QtFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Writer\TranslationWriter located in ./vendor/symfony/translation/TranslationWriter.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Formatter\MessageFormatterTest located in ./vendor/symfony/translation/MessageFormatterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\PhpFileLoader located in ./vendor/symfony/translation/PhpFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Catalogue\OperationInterface located in ./vendor/symfony/translation/OperationInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\PoFileLoaderTest located in ./vendor/symfony/translation/PoFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Formatter\MessageFormatterTest located in ./vendor/symfony/translation/Formatter/MessageFormatterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Formatter\IntlFormatterTest located in ./vendor/symfony/translation/Formatter/IntlFormatterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\PhpFileLoaderTest located in ./vendor/symfony/translation/PhpFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\XliffFileLoader located in ./vendor/symfony/translation/XliffFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\FileDumper located in ./vendor/symfony/translation/FileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\MessageSelectorTest located in ./vendor/symfony/translation/MessageSelectorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\DumperInterface located in ./vendor/symfony/translation/DumperInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceSubscriber located in ./vendor/symfony/translation/ServiceSubscriber.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Formatter\IntlFormatterInterface located in ./vendor/symfony/translation/IntlFormatterInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\IcuResFileDumper located in ./vendor/symfony/translation/IcuResFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\FileDumperTest located in ./vendor/symfony/translation/FileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\ConcreteFileDumper located in ./vendor/symfony/translation/FileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\MoFileLoaderTest located in ./vendor/symfony/translation/Loader/MoFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\CsvFileLoaderTest located in ./vendor/symfony/translation/Loader/CsvFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\YamlFileLoaderTest located in ./vendor/symfony/translation/Loader/YamlFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\QtFileLoaderTest located in ./vendor/symfony/translation/Loader/QtFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\JsonFileLoaderTest located in ./vendor/symfony/translation/Loader/JsonFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\XliffFileLoaderTest located in ./vendor/symfony/translation/Loader/XliffFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IcuDatFileLoaderTest located in ./vendor/symfony/translation/Loader/IcuDatFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\PoFileLoaderTest located in ./vendor/symfony/translation/Loader/PoFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\PhpFileLoaderTest located in ./vendor/symfony/translation/Loader/PhpFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IcuResFileLoaderTest located in ./vendor/symfony/translation/Loader/IcuResFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\LocalizedTestCase located in ./vendor/symfony/translation/Loader/LocalizedTestCase.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IniFileLoaderTest located in ./vendor/symfony/translation/Loader/IniFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Extractor\PhpStringTokenParser located in ./vendor/symfony/translation/PhpStringTokenParser.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ControllerArguments located in ./vendor/symfony/translation/ControllerArguments.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\JsonFileDumper located in ./vendor/symfony/translation/JsonFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\IniFileLoader located in ./vendor/symfony/translation/IniFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Formatter\IntlFormatterTest located in ./vendor/symfony/translation/IntlFormatterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Formatter\MessageFormatterInterface located in ./vendor/symfony/translation/MessageFormatterInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IcuResFileLoaderTest located in ./vendor/symfony/translation/IcuResFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Exception\NotFoundResourceException located in ./vendor/symfony/translation/NotFoundResourceException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IniFileDumperTest located in ./vendor/symfony/translation/IniFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslatorPassTest located in ./vendor/symfony/translation/TranslatorPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Reader\TranslationReaderInterface located in ./vendor/symfony/translation/TranslationReaderInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\MoFileDumper located in ./vendor/symfony/translation/MoFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Catalogue\TargetOperation located in ./vendor/symfony/translation/TargetOperation.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DataCollectorTranslatorTest located in ./vendor/symfony/translation/DataCollectorTranslatorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\LocalizedTestCase located in ./vendor/symfony/translation/LocalizedTestCase.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\MessageCatalogueTest located in ./vendor/symfony/translation/MessageCatalogueTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Command\XliffLintCommandTest located in ./vendor/symfony/translation/Command/XliffLintCommandTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\PhpFileDumperTest located in ./vendor/symfony/translation/PhpFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Formatter\IntlFormatter located in ./vendor/symfony/translation/IntlFormatter.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\PoFileDumperTest located in ./vendor/symfony/translation/PoFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\PoFileLoader located in ./vendor/symfony/translation/PoFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Reader\TranslationReader located in ./vendor/symfony/translation/TranslationReader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Dumper\YamlFileDumper located in ./vendor/symfony/translation/YamlFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Extractor\ChainExtractor located in ./vendor/symfony/translation/ChainExtractor.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\TargetOperationTest located in ./vendor/symfony/translation/Catalogue/TargetOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\AbstractOperationTest located in ./vendor/symfony/translation/Catalogue/AbstractOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\MergeOperationTest located in ./vendor/symfony/translation/Catalogue/MergeOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\DataCollector\TranslationDataCollector located in ./vendor/symfony/translation/TranslationDataCollector.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\CsvFileLoader located in ./vendor/symfony/translation/CsvFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationPathsPassTest located in ./vendor/symfony/translation/DependencyInjection/TranslationPathsPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslatorPassTest located in ./vendor/symfony/translation/DependencyInjection/TranslatorPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceMethodCalls located in ./vendor/symfony/translation/DependencyInjection/fixtures/ServiceMethodCalls.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceArguments located in ./vendor/symfony/translation/DependencyInjection/fixtures/ServiceArguments.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceProperties located in ./vendor/symfony/translation/DependencyInjection/fixtures/ServiceProperties.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceSubscriber located in ./vendor/symfony/translation/DependencyInjection/fixtures/ServiceSubscriber.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ControllerArguments located in ./vendor/symfony/translation/DependencyInjection/fixtures/ControllerArguments.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationDumperPassTest located in ./vendor/symfony/translation/DependencyInjection/TranslationDumperPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationExtractorPassTest located in ./vendor/symfony/translation/DependencyInjection/TranslationExtractorPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Catalogue\MergeOperationTest located in ./vendor/symfony/translation/MergeOperationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\DependencyInjection\TranslatorPathsPass located in ./vendor/symfony/translation/TranslatorPathsPass.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Formatter\MessageFormatter located in ./vendor/symfony/translation/MessageFormatter.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IniFileLoaderTest located in ./vendor/symfony/translation/IniFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationDumperPassTest located in ./vendor/symfony/translation/TranslationDumperPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IcuResFileDumperTest located in ./vendor/symfony/translation/IcuResFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Extractor\PhpExtractor located in ./vendor/symfony/translation/PhpExtractor.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Util\XliffUtils located in ./vendor/symfony/translation/XliffUtils.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\LoggingTranslatorTest located in ./vendor/symfony/translation/LoggingTranslatorTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\XliffFileDumperTest located in ./vendor/symfony/translation/Dumper/XliffFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\JsonFileDumperTest located in ./vendor/symfony/translation/Dumper/JsonFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\QtFileDumperTest located in ./vendor/symfony/translation/Dumper/QtFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\YamlFileDumperTest located in ./vendor/symfony/translation/Dumper/YamlFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\CsvFileDumperTest located in ./vendor/symfony/translation/Dumper/CsvFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\MoFileDumperTest located in ./vendor/symfony/translation/Dumper/MoFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\FileDumperTest located in ./vendor/symfony/translation/Dumper/FileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\ConcreteFileDumper located in ./vendor/symfony/translation/Dumper/FileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IniFileDumperTest located in ./vendor/symfony/translation/Dumper/IniFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\PhpFileDumperTest located in ./vendor/symfony/translation/Dumper/PhpFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\PoFileDumperTest located in ./vendor/symfony/translation/Dumper/PoFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IcuResFileDumperTest located in ./vendor/symfony/translation/Dumper/IcuResFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Writer\TranslationWriterInterface located in ./vendor/symfony/translation/TranslationWriterInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Loader\IcuDatFileLoader located in ./vendor/symfony/translation/IcuDatFileLoader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationExtractorPassTest located in ./vendor/symfony/translation/TranslationExtractorPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Writer\TranslationWriterTest located in ./vendor/symfony/translation/TranslationWriterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Writer\NonBackupDumper located in ./vendor/symfony/translation/TranslationWriterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Writer\BackupDumper located in ./vendor/symfony/translation/TranslationWriterTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\IntervalTest located in ./vendor/symfony/translation/IntervalTest.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Symfony\Component\Translation\Loader\ArrayLoader' not found

  at /Users/dectom/Documents/projects/ceedbox/leda/vendor/nesbot/carbon/src/Carbon/Translator.php:80
    76|     public function __construct($locale, Translation\Formatter\MessageFormatterInterface $formatter = null, $cacheDir = null, $debug = false)
    77|     {
    78|         $this->initializing = true;
    79|         $this->directories = [__DIR__.'/Lang'];
  > 80|         $this->addLoader('array', new Translation\Loader\ArrayLoader());
    81|         parent::__construct($locale, $formatter, $cacheDir, $debug);
    82|         $this->initializing = false;
    83|     }
    84|

  Exception trace:

  1   Carbon\Translator::__construct("en")
      /Users/dectom/Documents/projects/ceedbox/leda/vendor/nesbot/carbon/src/Carbon/Translator.php:70

  2   Carbon\Translator::get()
      /Users/dectom/Documents/projects/ceedbox/leda/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php:691

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
dectom@Declans-MacBook-Pro leda %
```

Any insight at all would be very much appreciated here

**How to reproduce**
Run `composer install` or `composer dump` on any project that requires it

**Comment by benjdl** [comment] 2021-09-28 09:53
I encounter the same issue. I've just downgraded to v5.3.4 for the moment.

**Comment by Dectom** [comment] 2021-09-28 09:55
> I encounter the same issue. I've just downgraded to v5.3.4 for the moment.

Sorry for being a bit stupid here but how should I downgrade the package version? It's a dependency of a different package so how would I specify what version I want to use?

**Comment by derrabus** [comment] 2021-09-28 09:56
Duplicate of #43212

**Comment by clk528** [comment] 2021-09-28 09:56
+1

**Closed as completed by derrabus** 2021-09-28 09:56 UTC
Labels: Bug, Status: Needs Review
