### ISSUE TITLE
Form: choice with expanded=true does not retain boolean values

### ISSUE THREAD

**Issue by imphil** [symfony/symfony#15573] opened 2015-08-17 22:55 UTC
I have a form with the following code:

```php
$form = $this->factory->create('Symfony\Component\Form\Extension\Core\Type\ChoiceType', null, array(
  'multiple' => false,
  'expanded' => false,
  'choices' => array(
      'label a' => false,
      'label b' => true,
  ),
  'choices_as_values' => true,
));
```

When submitting the form, none of the two radio buttons are selected, i.e. the values are lost.

I've written a unit test for it in https://github.com/imphil/symfony/commit/71a59b79fe2afb5db1fd5e5e28f46b52b7e961cd

Currently it fails with

```
There were 2 failures:

1) Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest::testSubmitSingleExpandedBooleanValueFalse
Failed asserting that false is identical to '0'.

/home/philipp/src/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:354

2) Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest::testSubmitSingleExpandedBooleanValueTrue
Failed asserting that true is identical to '1'.

/home/philipp/src/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:373
```

The problem only happens with boolean values and expanded=true. It seems that a proper conversion to the view data is missing. Unfortunately I have no idea about the inner workings of Symfony -- maybe someone with a bit more experience can have a look?

(This seems to be similar to #14877, but maybe not exactly the same, so I didn't want to hijack that issue.)

**Comment by imphil** [comment] 2015-08-17 23:00
It's always the same ... I've found the issue already reported: #14712 Sorry for the duplicate, but feel free to take the unit test :)

**Comment by stof** [comment] 2015-08-27 11:22
I found a workaround for that: attaching a NoopDataTransformer on the choice field (a transformer doing nothing).

Note that in case your choice field is not required, you will still need a custom ``choice_value`` callback to distinguish ``null`` and ``false`` (which are both casted to an empty string with the default callback).

**Comment by alexislefebvre** [comment] 2015-08-31 11:47
Thanks stof, this workaround worked for me! :+1:

**Comment by xabbuh** [comment] 2015-10-05 11:28
This behaviour seems to be related to what @DancZer observed in https://github.com/symfony/symfony/issues/5906#issuecomment-135856626.

**Comment by javiereguiluz** [comment] 2016-02-07 18:20
Closing it because, as @imphil said, this is a duplicate of #14712.

**Closed by javiereguiluz** 2016-02-07 18:20 UTC
Labels: Form

**Comment by alexislefebvre** [comment] 2016-05-09 12:16
@stof Note that the workaround doesn't work with Symfony 2.8.5; probably after the #18180 PR.

**Comment by HeahDude** [comment] 2016-05-09 12:48
@alexislefebvre Yes #18180 fixes it once and for all ;)

**Comment by alexislefebvre** [comment] 2016-05-09 13:34
@HeahDude Yes, but it also *broke* the workaround, so I wanted to inform other users just in case they missed this information.

**Comment by HeahDude** [comment] 2016-05-09 13:46
You're right, I wasn't questioning it :) Thanks!

**Comment by stof** [comment] 2016-05-09 13:48
@alexislefebvre my workaround was for a case where the ``choices_as_values`` was already true (see the original ticket).
Passing boolean choices as key never worked, because booleans cannot be used as array keys in PHP, and so your choices were ``'1'`` and ``''`` instead (i.e. their string representation)
