### ISSUE TITLE
[2.3][Form] HiddenEntityType

### ISSUE THREAD

**Issue by kl3ryk** [symfony/symfony#8293] opened 2013-06-17 07:42 UTC
Hi,

I have created HiddenEntityType (https://gist.github.com/kl3ryk/5781916), to transform value of hidden field into Entity. I was using FormBuilderInterface::getParent() to get Entity class. But in Symfony 2.3 function FormBuilderInterface::getParent was removed. So is there any way to retreive parent form data_class name (https://gist.github.com/kl3ryk/5781916#file-hiddenentitytype-php-L36)?

**Comment by webdevilopers** [comment] 2016-01-16 21:31
Any news on this?

**Comment by xabbuh** [comment] 2016-01-16 23:16
Can you give a use case for which you would need such a form type?

**Comment by Koc** [comment] 2016-01-17 12:06
@xabbuh for ajax loaded data like autosuggests - when choice list is too big

**Comment by xabbuh** [comment] 2016-01-17 16:10
Not sure that we need a complete new form type for this. Having an additional option (maybe provided by a form type extension) looks sufficient to me.

**Comment by Koc** [comment] 2016-01-17 17:06
yes, @xabbuh see #15053

**Comment by Tobion** [comment] 2016-01-17 22:11
Closing as duplicate of #6602

**Closed by Tobion** 2016-01-17 22:11 UTC
Labels: Form
