### ISSUE TITLE
Composer install or update not working anymore   Class "Symfony\Component\Translation\Loader\ArrayLoader" not found

### ISSUE THREAD

**Issue by naifalshaye** [symfony/symfony#43226] opened 2021-09-28 10:04 UTC
**Symfony version(s) affected**: 

**Description**

Composer install or update not working anymore   Class "Symfony\Component\Translation\Loader\ArrayLoader" not found

**How to reproduce**
composer install or composer update

**Possible Solution**

**Additional context**

**Comment by tseho** [comment] 2021-09-28 10:06
Already reported here: https://github.com/symfony/symfony/issues/43212

**Comment by derrabus** [comment] 2021-09-28 10:06
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 10:06 UTC
Labels: Bug, Status: Needs Review

**Comment by phil-davis** [comment] 2021-09-28 10:08
See comment https://github.com/symfony/symfony/issues/43212#issuecomment-929029937

They know about the problem and a fix is coming.
