### ISSUE TITLE
Hidden message in BadRequestHttpException production mode

### ISSUE THREAD

**Issue by Kutuzovska** [symfony/symfony#49653] opened 2023-03-10 08:03 UTC
### Symfony version(s) affected

6.2.*

### Description

When my app is in debug mode I get a normal message. As soon as I switch to product mode, the message is replaced with "Bad Request".

The problem is that I did not find anywhere in the documentation how to solve this problem.

### How to reproduce

```php
<?php

namespace App\Http\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/custom')]
class CustomController extends AbstractController
{
    public function __invoke()
    {
        throw new BadRequestHttpException('Custom error message');
    }
}
```

If APP_ENV=dev
```json
 {
  "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
  "title": "An` error occurred",
  "status" :400,
  "detail": "Custom error message", 
  "class": "..."
  "trace": [  ]
}
```

If APP_ENV=prod
```json
 {
  "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
  "title": "An` error occurred",
  "status" :400,
  "detail": "Bad Request", 
}
```

### Possible Solution

Temporarily solved the problem like this
```php
    #[AsEventListener(event: ExceptionEvent::class)]
    public function onException(ExceptionEvent $event): void
    {

        $exception = $event->getThrowable();
        if ($exception instanceof BadRequestHttpException) {
            $response = new JsonResponse([
                'title' => 'An error occurred',
                'status' => $exception->getStatusCode(),
                'detail' => $exception->getMessage(),
            ], $exception->getStatusCode());

            $event->setResponse($response);
        }
    }
```

**Comment by ro0NL** [comment] 2023-03-10 08:06
AFAIK it's by design, to not leak internal details.

I believe #49138 adds a handler for ValidationException, so you can throw it with a violation attached

we can argue ofcourse if 4xx messages are internal details :thinking:

**Comment by ro0NL** [comment] 2023-03-10 08:11
BTW this somewhat bit us recently in prod also

our frontend anticipated an empty exception message, to then fallback to a generic translated error message.

but in prod you'd always face "Bad Request" message

my main concern here is `'detail' => $exception->getMessage(),` would not produce translated errors by default, which to me should be solved in some way. Hence i tend to prefer throwing ValidationException

**Comment by kaznovac** [comment] 2023-09-05 17:07
This is somewhat related issue
https://github.com/symfony/symfony/issues/50303

It could help expose message per exception class

**Comment by derrabus** [comment] 2023-09-06 09:14
> AFAIK it's by design, to not leak internal details.

Yes. I think, we can close this issue.

**Closed as not planned by derrabus** 2023-09-06 09:14 UTC
Labels: Bug, Status: Needs Review
