### ISSUE TITLE
DebugClassLoader fails with Symfony's BC layers

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#42303] opened 2021-07-28 08:36 UTC
**Symfony version(s) affected**: 5.3.5

**Description**
These kind of "BC layers" don't work in combination with Symfony's DebugClassLoader
```
trigger_deprecation('symfony/messenger', '5.1', 'The "%s" class is deprecated, use "%s" instead. The Doctrine transport has been moved to package "symfony/doctrine-messenger" and will not be included by default in 6.0. Run "composer require symfony/doctrine-messenger".', DoctrineTransportFactory::class, BridgeDoctrineTransportFactory::class);

class_exists(BridgeDoctrineTransportFactory::class);

if (false) {
    /**
     * @deprecated since Symfony 5.1, to be removed in 6.0. Use symfony/doctrine-messenger instead.
     */
    class DoctrineTransportFactory
    {
    }
}
```

**How to reproduce**
```php
<?php

use Symfony\Component\ErrorHandler\DebugClassLoader;
use Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory;

require __DIR__.'/vendor/autoload.php';

DebugClassLoader::enable();
class_exists(DoctrineTransportFactory::class);
```
produces
```
PHP Fatal error:  Uncaught RuntimeException: The autoloader expected class "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory" to be defined in file "/Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php". The file was found but the class was not in it, the class name or namespace probably has a typo. in /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php:403
Stack trace:
#0 /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php(360): Symfony\Component\ErrorHandler\DebugClassLoader->checkClass('Symfony\\Compone...', '/Users/gabriel....')
#1 [internal function]: Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Symfony\\Compone...')
#2 /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/test.php(9): class_exists('Symfony\\Compone...')
#3 {main}
  thrown in /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php on line 403

Fatal error: Uncaught RuntimeException: The autoloader expected class "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory" to be defined in file "/Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php". The file was found but the class was not in it, the class name or namespace probably has a typo. in /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php:403
Stack trace:
#0 /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php(360): Symfony\Component\ErrorHandler\DebugClassLoader->checkClass('Symfony\\Compone...', '/Users/gabriel....')
#1 [internal function]: Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Symfony\\Compone...')
#2 /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/test.php(9): class_exists('Symfony\\Compone...')
#3 {main}
  thrown in /Users/gabriel.ostrolucky/Documents/CraueGeoBundle/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php on line 403
```
**Possible Solution**

**Additional context**
ref: https://github.com/doctrine/DoctrineBundle/pull/1373

**Comment by Nyholm** [comment] 2021-08-01 18:05
Thank you for this issue. 

I cannot reproduce this. Could you help me with a commit or PR to https://github.com/Nyholm/sf-issue-42303?

**Comment by ostrolucky** [comment] 2021-08-01 21:52
I don't quite understand why is this making a difference, but bug is reproducible when using symfony/symfony instead of symfony/messenger. I've pushed a commit.

edit: Ah right, symfony/messenger requires symfony/doctrine-messenger, but symfony/symfony doesn't

**Comment by Nyholm** [comment] 2021-08-02 03:55
When I test with `"symfony/symfony": "5.3.x-dev"` then I cannot reproduce the error. That means it will be fixed in the next patch release. 

I have not looked for the commit that fixed the issue. Can you confirm that `"symfony/symfony": "5.3.x-dev"` is working for you too?

**Comment by ostrolucky** [comment] 2021-08-02 08:28
You can't reproduce with commit I pushed now? I still get same error with 5.3.x-dev

**Comment by encreinformatique** [comment] 2021-08-05 17:51
I run into a similar problem upgrading from `5.2.9` to `5.3.6`.

```
The autoloader expected class "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory" to be defined in file "/var/www/docker-install/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php". The file was found but the class was not in it, the class name or namespace probably has a typo.
```

@ostrolucky puts me in the right track stating that "Ah right, symfony/messenger requires symfony/doctrine-messenger, but symfony/symfony doesn't". The app is still requiring `symfony/symfony` (It is an old project coming a long way from Sf 2.1) but does not require directly `symfony/messenger`.

Adding `symfony/doctrine-messenger` to the dependencies made the error disappear and it is back on track on dev environment.

PS : thank you @ostrolucky !!

**Comment by craue** [comment] 2021-08-12 09:59
Any news on this? It's still an issue for me.

**Comment by wouterj** [comment] 2021-08-12 10:05
If I understand correctly, this is only an issue when using the `symfony/symfony` package. In that case, the solution is simple: Don't use `symfony/symfony`.
This package is by all means deprecated and it will likely no longer get versions in 6.0. Require each Symfony bundle and component separately if you need them (optionally using Symfony Flex, but you can also do it without Flex).

**Comment by craue** [comment] 2021-08-12 10:10
Alright then. Thanks.

**Comment by ostrolucky** [comment] 2021-08-12 10:51
It isn't deprecated (yet). It's still being updated and isn't marked as abandoned, nor no official announcement was posted about this AFAIK.

**Comment by nicolas-grekas** [comment] 2022-02-26 09:40
I'm not sure why this happens only when using symfony/symfony, but the solution is to not use it. Not sure it's worth more of maintainers' time. Closing therefor.

**Closed as completed by nicolas-grekas** 2022-02-26 09:40 UTC
Labels: Bug, Status: Needs Review, ErrorHandler

**Comment by nicolas-grekas** [comment] 2022-02-26 09:56
I submitted #45563 to deprecate requiring symfony/symfony.
