### ISSUE TITLE
Monolog config option `excluded_http_codes` has no effect

### ISSUE THREAD

**Issue by pavlepredic** [symfony/symfony#31576] opened 2019-05-22 09:35 UTC
**Symfony version(s) affected**: 4.2.8

**Description**  
Even after configuring monolog to exclude 404 errors, they still appear in the log.

**How to reproduce**  
`composer create-project symfony/skeleton symfony`
`cd symfony`
`composer require --dev symfony/web-server-bundle`
`composer require symfony/monolog-bundle`
```
cat <<'EOF' > config/packages/dev/monolog.yaml
monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [403, 404]
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
EOF
```

`./bin/console server:run`

`curl http://127.0.0.1:8000/foo`
`cat var/log/dev.log`

Expected result: no log entries.
Actual result: 404 error appears in log.

**Additional context**  
Monolog version: 1.24.0

**Comment by rpkamp** [comment] 2019-05-22 12:09
Duplicate of https://github.com/symfony/symfony/issues/29904

I've already created an issue for the docs, but haven't gotten around to implementing it yet: https://github.com/symfony/symfony-docs/issues/10896

**Comment by xabbuh** [comment] 2019-05-27 13:22
closing here as a duplicate, see the linked issue

**Comment by guvkon** [comment] 2024-08-28 13:55
This isn't a duplicate of #29904 . The one in the linked issue has `passthrough_level` in the config. But this one doesn't.

**Comment by xabbuh** [comment] 2024-08-28 14:06
If you can reproduce this with a maintained Symfony version, please create a small example application that allows to reproduce it and open a new issue with it.

**Closed** 2024-08-28 14:07 UTC
Labels: Bug, MonologBridge, Status: Needs Review
