### ISSUE TITLE
Validation Errors are not mapped correctly to Form Fields if Case is different

### ISSUE THREAD

**Issue by naitsirch** [symfony/symfony#7959] opened 2013-05-07 09:48 UTC
Hi.
Today I searched two hours for the reason why one validation error wasn't shown at the form field but at the root form.
My form builder class looked like that:

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('xfade', 'integer', array('required' => false));
}
```

My `validation.yml` looked like that:

``` yml
Streamserver:
    properties:
        xFade:
            - Range: { min: 0, groups: [ Default ] }
```

The validation error of the property _xFade_ wasn't mapped to the form field _xfade_ and that error was hard to find, because the value of the field was mapped correctly to the entity of course.

One possible solution would be:

When mapping violation to form child (in `Symfony\Component\Form\Extension\Validator\ViolationMapper\ViolationMapper->matchChild()`) do a case-insensitive comparison.

But maybe there are better ways.

**Comment by mdesign83** [comment] 2016-04-06 17:57
I ran into the same error with Symfony 3.0.4:/

**Comment by HeahDude** [comment] 2017-07-25 11:21
The OP is not a bug to me, since
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('xfade', 'integer', array('required' => false));
}
```
is not supposed to work for an `xFade`property, the field should be named either `x_fade` or `xFade`.

**Comment by javiereguiluz** [comment] 2017-07-31 07:44
@HeahDude should we close this as "won't fix" ... or can we improve forms to throw an exception explaining that you are using a wrong property name?

**Comment by HeahDude** [comment] 2017-07-31 07:52
I propose to close this as "won't fix", because the Form component does not care about how form names are supposed to be property path.

The fact that PHP is not case sensitive for methods does not mean we can "abuse" the property path feature.

I will clarify the docs about form names and block prefixes.

**Comment by javiereguiluz** [comment] 2017-07-31 09:10
Closing then. Thanks!

**Closed by javiereguiluz** 2017-07-31 09:10 UTC
Labels: Bug, Form, Status: Waiting feedback
