### ISSUE TITLE
Problem with EntityType

### ISSUE THREAD

**Issue by adpeyre** [symfony/symfony#37192] opened 2020-06-10 16:10 UTC
**Symfony version(s) affected**: 5.1.0

**Description**  
Since the update to symfony 5.1, my form which uses EntityType doesn't work.

**`Argument 1 passed to Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader::getIdValue() must be an object or null, string given`**

**How to reproduce**  
``` php
$builder
->add('category', EntityType::class, [
    'class'         => ContactCategory::class,
])
```

**Comment by adpeyre** [comment] 2020-06-12 08:33
Entity/ContactCategory.php
``` php
/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactCategoryRepository")
 */
class ContactCategory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=50)
     */
    public string $name = '';


    public function __toString()
    {
        return $this->name;
    }
}
```

Form/ContactType.php

``` php
class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('category', EntityType::class, [
                'class'         => ContactCategory::class,
            ]);
    }
}
```

TypeError:
Argument 1 passed to Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader::getIdValue() must be an object or null, string given

  at vendor/symfony/doctrine-bridge/Form/ChoiceList/IdReader.php:89
  at Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader->getIdValue()
  at array_map()
     (vendor/symfony/form/ChoiceList/Loader/AbstractChoiceLoader.php:65)
  at Symfony\Component\Form\ChoiceList\Loader\AbstractChoiceLoader->loadValuesForChoices()
     (vendor/symfony/form/ChoiceList/LazyChoiceList.php:101)
  at Symfony\Component\Form\ChoiceList\LazyChoiceList->getValuesForChoices()
     (vendor/symfony/form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php:32)
  at Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer->transform()
     (vendor/symfony/form/Form.php:1114)
  at Symfony\Component\Form\Form->normToView()
     (vendor/symfony/form/Form.php:353)
  at Symfony\Component\Form\Form->setData()
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms()
     (vendor/symfony/form/Form.php:375)
  at Symfony\Component\Form\Form->setData()
     (vendor/symfony/form/Form.php:479)
  at Symfony\Component\Form\Form->initialize()
     (vendor/symfony/form/FormBuilder.php:206)
  at Symfony\Component\Form\FormBuilder->getForm()
     (vendor/symfony/form/FormFactory.php:28)
  at Symfony\Component\Form\FormFactory->create()
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:327)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->createForm()
     (src/Controller/Front/ContactController.php:47)
  at App\Controller\Front\ContactController->contact()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:196)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:25)

**Comment by TeLiXj** [comment] 2020-06-12 12:27
I think that this could be a bug. 
For example I have a GET form with an EntityType and before 5.1 I could use directly the $request->query->all() array
```php
public function category(FormFactoryInterface $form_factory, Request $request)
{
    $form = $form_factory
        ->createNamedBuilder("", FormType::class, $request->query->all(), ["method" => "GET"])
        ->add("category", EntityType::class, ["class" => Category::class])
        ->getForm()
        ->handleRequest($request);
    [...]
}
```
But now I have to find the id because the array value is a string.
```php
public function category(FormFactoryInterface $form_factory, EntityManagerInterface $em, Request $request)
{
    $data = $request->query->all();
    $data["category"] = $em->getRepository(Category::class)->find($data["category"];
    $form = $form_factory
        ->createNamedBuilder("", FormType::class, $data, ["method" => "GET"])
        ->add("category", EntityType::class, ["class" => Category::class])
        ->getForm()
        ->handleRequest($request);
    [...]
}
This is the expected behaviour?

**Comment by xabbuh** [comment] 2020-06-12 13:12
I am not sure I understand this issue. What exactly did you expect the value to be if not the id as a string?

**Comment by TeLiXj** [comment] 2020-06-12 13:19
Yes, a string is expected in the $request->query array but if you use it at is to set the form data then the error appear because the EntityType expect an object. 
And before 5.1 you can set the form data using strings

**Comment by xabbuh** [comment] 2020-06-12 13:28
Oh I see, well that's expected at least and I wonder how that could ever have worked. The data passed when creating the form must be in the model format (which is an entity instance for this form type).

**Comment by TeLiXj** [comment] 2020-06-12 13:32
Well, in this case I'm going to change all my projects with GET forms.
This works since Symfony 2.1 to 5.0 far as I know :)

**Comment by xabbuh** [comment] 2020-06-12 13:36
If your prefer not to change all your form types, you can write a custom form type extension for the `EntityType` which would add a model transformer that is able to do the repository lookup.

**Comment by MrNicodemuz** [comment] 2020-06-13 04:00
I'm also experiencing similar problems after upgrading to Symfony 5.1:
```
TypeError: Argument 1 passed to Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader::getIdValue() must be an object or null, array given
```

**Comment by adpeyre** [comment] 2020-06-13 12:47
I reopen this issue because I think other people may have the same problem related to this new behavior.

**Comment by MrNicodemuz** [comment] 2020-06-19 05:49
This used to work in Symfony 5.0:
```
$builder->add('groups', EntityType::class, array(
    'class' => Group::class,
    'choice_label' => function (Group $group) {
        return $group->getName();
    },
    'mapped' => false,
    'label' => false,
    'data' => [$this->groupRepository->findAll()],
    'multiple' => false,
    'expanded' => false,
    'required' => false,
));
```

Removing the `data` key seems to have fixed it for Symfony 5.1:
```
$builder->add('groups', EntityType::class, array(
    'class' => Group::class,
    'choice_label' => function (Group $group) {
        return $group->getName();
    },
    'mapped' => false,
    'label' => false,
    'multiple' => false,
    'expanded' => false,
    'required' => false,
));
```

**Comment by TeLiXj** [comment] 2020-06-19 07:29
@MrNicodemuz yes, it's works!!! I set the data to null and works fine. Using my last example:
```php
public function category(FormFactoryInterface $form_factory, EntityManagerInterface $em, Request $request)
{
    $form = $form_factory
        ->createNamedBuilder("", FormType::class, null, ["method" => "GET"])
        ->add("category", EntityType::class, ["class" => Category::class])
        ->getForm()
        ->handleRequest($request);
    [...]
}
```
Thanks!

**Comment by xabbuh** [comment] 2020-06-24 08:59
I am closing here as the `EntityType` was never meant to be used in the ways that are reported here. The model data always has to be an object (an instance of the configured class) or an array of objects (if `multiple` is `true`). Thank you for understanding.

**Closed by xabbuh** 2020-06-24 08:59 UTC
Labels: Bug, DoctrineBridge, Status: Needs Review, Status: Waiting feedback

**Comment by k3ssen** [comment] 2020-08-14 09:19
In [the third comment](https://github.com/symfony/symfony/issues/37192#issuecomment-643148066) adpeyre uses the following code in his Contact class:
```
/**
 * @ORM\Column(type="string", nullable=true)
*/
public ?string $category = '';
```
This is invalid, because the category cannot be a string by default. However, when you correctly use `public ?Category $category = null;` instead, the following form still fails:
```
$builder->add('category', EntityType::class, [
    'class' => ContactCategory::class,
]);
```
Here I get the following exception:
"_Argument 1 passed to Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader::getIdValue() must be an object or null, bool given_"

This doesn't seem right as there shouldn't be used any boolean in this case. It seems this is resolved incorrectly somewhere, which wasn't the case with versions before Symfony 5.1

For those running into this problem: it is easily resolved by defining a getter in the Contact class:
```
public function getCategory(): ?Category
{
    return $this->category;
}
```
Likewise, the problem could also be resolved by setting data in the formbuilder:
```
$builder->add('category', EntityType::class, [
    'class' => ContactCategory::class,
    'builder' => $builder->getData()->category,
]);
```

**Comment by jawira** [comment] 2022-01-27 10:42
In my case the problem is how ID's types are handled.

In Symfony 5.0 `$choices` are returned as strings.

![symfony50](https://user-images.githubusercontent.com/496541/151343283-d7dfb539-ba2c-481d-a555-bd87f2eebc83.png)


Whilst in Symfony 5.1 `$choices` are returned as integers.

![symfony51](https://user-images.githubusercontent.com/496541/151343302-bc637c96-27f1-4186-b6c8-31e78fdcd71c.png)

Of course checkbox is not checked because strict typing is used.

Code https://github.com/symfony/form/blob/b794bed839f11bcee9a9f30daa5cb88d311dd409/Extension/Core/DataMapper/CheckboxListMapper.php#L41-L44

I don't have a solution yet.
