### ISSUE TITLE
Test container

### ISSUE THREAD

**Issue by aless673** [symfony/symfony#36783] opened 2020-05-11 12:15 UTC
**Symfony version(s) affected**: 4.4.8

**Description**  
Doctrine subscribers (or listeners) services are not the same if fetched from container or fetched by doctrine events. If i dump the spl_object_id of a doctrine subscriber fetched from the container and the spl_object_id of the same doctrine subscriber but fired by a doctrine event (like onFlush), this is not the same id.

**How to reproduce**  
1. Create any doctrine subscriber with any event (ex: onFlush) who call any function of any service (ex: test from TestService) that do  `codecept_debug(spl_object_id($this));`
2. Create test (with codeception) : 
-- call the Testservice->test() function
-- persist any entity and flush, subscriber is fired and Testservice->test() is runned
3. Run test with test environment and --debug

You can see that the Testservice spl_object_id is not the same.
You can reproduce it with any service used by any doctrine subscriber.
Messenger transports are also impacted, transports are "duplicated".

**Possible Solution**  

**Additional context**  
Happens only in test environement with probably a conflict with test container

**Comment by ostrolucky** [comment] 2020-05-22 00:45
I don't understand these reproduction instructions. Your description says identities of subscribers do not match, but you are printing spl_object_id of TestService ($this). Can you perhaps reproduce it in symfony-demo (`symfony new --demo`), zip it and attach it here?

**Comment by aless673** [comment] 2020-05-23 22:12
@ostrolucky here a demo : https://github.com/aless673/bug_test_container

```
bin/console do:da:cr
bin/console do:sc:cr
vendor/bin/codecept run functional --debug
```

You can see that TestService object id is not the same if called from test container or called from the doctrine subscriber

This is a real problem when manipulating services in tests (mock)

**Comment by nicolas-grekas** [comment] 2020-06-08 18:16
I played a bit with your reproducer, thanks for it.
The reason for this different id is that the container itself is different.
You can add `dump(spl_object_id($this));` inside `srcApp_KernelTestDebugContainer::getTestServiceService()` to figure this out.
Why? I don't know :)

**Comment by ostrolucky** [comment] 2020-06-08 18:19
See referenced issue, this is a codeception symfony plugin issue

**Comment by nicolas-grekas** [comment] 2020-06-08 18:23
Oh, then there's nothing to do here on our side, isn't it? Closing therefor.

**Closed by nicolas-grekas** 2020-06-08 18:23 UTC
Labels: Bug, Status: Needs Review
