### ISSUE TITLE
assert NotBlank allowNull does not seem to work

### ISSUE THREAD

**Issue by BernardA** [symfony/symfony#32327] opened 2019-07-02 18:49 UTC
**Symfony version(s) affected**: 4.3.2

**Description**  
Form is throwing errors on null values even though field is set to `allowNull`.
Message is actually related to invalid type

**How to reproduce**  
The form type:
AddressType.php

                     ->add('lat', NumberType::class, array(
                    'required' => false,
                ))
                ->add('lng', NumberType::class, array(
                    'required' => false,
                ));

One of the entity fields:
Address.php

      /**
     * @ORM\Column(type="float", nullable=true)
     * @Assert\NotBlank(
     *  allowNull = true
     * )
     * @Assert\Type(
     *     type="float",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     */
    private $lng;

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment] 2019-07-02 23:22
Can you please create a small example application that allows to reproduce your issue?

**Comment by BernardA** [comment] 2019-07-03 07:12
Please find it [at this repository. ](https://github.com/BernardA/skeleton)

**Comment by Rubinum** [comment] 2019-07-03 08:22
@BernardA I recreated your form in a (for me) simpler environment. I copied your AddressType, Address and your composer.json form your github project.

```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "league/tactician-bundle": "^1.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/console": "4.3.*",
        "symfony/debug": "4.3.*",
        "symfony/debug-pack": "^1.0",
        "symfony/event-dispatcher": "^4.0",
        "symfony/finder": "^4.0",
        "symfony/flex": "^1.1",
        "symfony/form": "4.3.*",
        "symfony/framework-bundle": "4.3.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/monolog-bundle": "^3.3",
        "symfony/orm-pack": "^1.0",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/translation": "4.3.*",
        "symfony/twig-bundle": "4.3.*",
        "symfony/validator": "4.3.*",
        "symfony/var-dumper": "^4.0",
        "symfony/workflow": "^4.0",
        "symfony/yaml": "4.3.*"
    },
//... 
```
Ignore other dependencies in this composer.json. The core components for this issue should be in the correct version.

I tested your form but I could not create an error. See gif.
![Jul-03-2019 10-15-27](https://user-images.githubusercontent.com/5645798/60575458-de710d80-9d7b-11e9-98d1-bd3257d4f591.gif)

It seems like that there is no error in the NotBlank Assertion, but more likely in your code.

**Comment by thomas-rolling** [comment] 2019-07-03 20:31
I think this behavior is normal because you allow `null` value for field `Lat` and `Lng` 

```php
# https://github.com/BernardA/skeleton/blob/master/src/Entity/Address.php#L75

* @Assert\NotBlank(
*  allowNull=true,
*  message = "Longitude is required."
* )
```

If blank value typed in this field, PHP will assigned `null` according to setters.

```php
# https://github.com/BernardA/skeleton/blob/master/src/Entity/Address.php#L217

public function setLat(?float $lat): self
public function setLng(?float $lng): self

➡️ Remove `allowNull` (default=false) and your problem should be solved

**Comment by xabbuh** [comment] 2019-07-08 15:46
I am closing here as this doesn't seem to be a bug. Thank you for understanding. Please comment with further information if you don't agree.

**Closed** 2019-07-08 15:46 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback, Unconfirmed, Validator
