### ISSUE TITLE
Symfony : composer update 4.4.19 > 4.4.20 occures "The value array is not valid" when submitting form with entitytype.

### ISSUE THREAD

**Issue by fodger** [symfony/symfony#40483] opened 2021-03-16 09:53 UTC
**Symfony version(s) affected**: 4.4.2

**Description**
After updating Symfony 4.4.19 to 4.4.20,
some forms using Entitytype class - populated with json - give the following error when handling request : 
```

The value array is not valid. | recipients | Caused by:                                                             
Symfony\Component\Form\Exception\TransformationFailedException {#6790 ▼
  -invalidMessage: null
  -invalidMessageParameters: []
  #message: "The choices "XXXX" do not exist in the choice list."
  #code: 0
  #file: "/project/vendor/symfony/form/Extension/Core/Type/ChoiceType.php"
  #line: 183
  trace: {▼
    /project/vendor/symfony/form/Extension/Core/Type/ChoiceType.php:183 {▶}
    /project/vendor/symfony/event-dispatcher/EventDispatcher.php:264 {▶}
    /project/vendor/symfony/event-dispatcher/EventDispatcher.php:239 {▶}
    /project/vendor/symfony/event-dispatcher/EventDispatcher.php:73 {▶}
    /project/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php:44 {▶}
    /project/vendor/symfony/form/Form.php:671 {▶}
    /project/vendor/symfony/form/Form.php:579 {▶}
    /project/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php:109 {▶}
    /project/vendor/symfony/form/Form.php:493 {▶}
    ...
```

It works perfectly with SF 4.4.19.

Regards,

**How to reproduce**
- Juste create a simple form with an empty choice list: 
```php
$form = $this->createFormBuilder()
  ->add('recipients', EntityType::class, [
      'class' => MyEntity::class,
      'translation_domain' => 'mytranslation_domain',
      'choice_label' => 'choice_label',
      'label' => 'em.texts.to',
      'multiple' => true,
      'mapped' => true,
      'choices' => $mychoices
]);
```

- print in a twig using select2 lib

- populate with a json request, make a choice and submit

**Possible Solution**
Patching src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php ?

**Additional context**

**Comment by stof** [comment] 2021-03-16 11:42
Well, submitting a form with a value which is not in the ChoiceList is not valid.
In 4.4.19, the code was **not** working. It was silently ignoring the invalid submitted value.

**Comment by fodger** [comment] 2021-03-16 13:32
So https://symfony.com/doc/4.4/reference/forms/types/entity.html#using-choices is wrong ?

Which is the right way ?

**Comment by xabbuh** [comment] 2021-03-16 13:36
Not sure what you mean, there is no empty list of choices in the part of the documentation that you linked to if I don't miss anything.

**Comment by Spounespoune** [comment] 2021-03-16 15:57
#Hello,

I have a same issue. In Symfony 5.2. With this bugfix [`#39659`](https://github.com/symfony/symfony/pull/39659) We are forced to add Choices in parameters

This is my temporary fix

```php
$builder->addEventListener(
            FormEvents::PRE_SUBMIT,
            function (FormEvent $event) {
                $form = $event->getForm();
                $establishments = [];
                if (!empty($event->getForm()->getData()->offsetGet('establishment'))) {
                    $establishments[] = $this->getEstablishmentsId($event->getForm()->getData()->__get('establishment'));
                }
               
                $form->add('establishment', SaniSelect2ChoiceType::class, [
                    **'choices' => $establishments,**
                    'label' => 'form.generic.establishment.label',
                    'class' => Establishment::class,
                    'attr' => [
                        'data-ajax-url' => $this->router->generate('sp_establishment_list'),
                        'required' => true,
                    ],
                    'initialData' => static function (FormInterface $form) {
                        return $form->getViewData();
                    },
                    'required' => true,
                    'multiple' => true,
                ]);
            }
        );
```

I take my return data submited who was fill by Ajax request and I inject these data in choices to pass though this condition in src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php line 148

```php 
if ($choiceList->getChoicesForValues([$value])) 
```

**Comment by xabbuh** [comment] 2021-03-16 17:31
Could anyone of you please create a small example application that allows to reproduce your issue? I would like to check it out to investigate whether or not this is an actual issue.

**Comment by Spounespoune** [comment] 2021-03-17 10:15
@fodger do you have time to create a small example ?

**Comment by Spounespoune** [comment] 2021-03-19 22:10
Hello, @xabbuh i create small project to show you this issue : [here](https://github.com/Spounespoune/symfony-choicetype/tree/master) 
Thanks in advance.

**Comment by xabbuh** [comment] 2021-03-22 10:41
@Spounespoune Thanks, so far this looks expected to me. And even if I downgrade to 5.2.3, the behaviour doesn't change. That said I do not really understand where the change in the behaviour should occur.

**Comment by Spounespoune** [comment] 2021-03-22 12:59
@xabbuh My actual version is 5.1 in my other project and I wish to update to 5.2 . Is it possible for you to downgrade to 5.1 ?

Just for information, I found this commit [here](https://github.com/symfony/symfony/pull/39659/commits/85989c3678d243e229f929008ede8b2e24c0c3fa) on choicetype File.

**Comment by xabbuh** [comment] 2021-03-22 13:42
@Spounespoune Can you update your example application with a `composer.json` and `composer.lock` file that allows to reproduce how this worked before?

**Comment by Spounespoune** [comment] 2021-03-22 16:32
@xabbuh Ok i do it soon

**Comment by Spounespoune** [comment] 2021-03-23 13:02
@xabbuh It's done. [here](https://github.com/Spounespoune/symfony-choicetype/tree/master). Thanks in advance.

**Comment by xabbuh** [comment] 2021-03-23 15:56
Status: Reviewed

**Comment by xabbuh** [comment] 2021-03-24 08:45
@Spounespoune Can you confirm that all the form types where this used to work before had the `inherit_data` option set to `true`?

**Comment by Spounespoune** [comment] 2021-03-24 09:49
@xabbuh Not necessary, I add this option to bypass the transformer data in my example.

**Comment by xabbuh** [comment] 2021-03-24 10:26
I was asking because if I removed that option in your example application, the form again was invalid. I still have some trouble to spin my head around why the above mentioned patch broke some use cases and try to narrow it down.

**Comment by Spounespoune** [comment] 2021-03-24 10:45
@xabbuh Yes, It is invalid but not for the same reason. Exception concerne the transformer (is not configured in my project). Our trouble is located on choicetype class. Before [fix](https://github.com/symfony/symfony/pull/39659/commits/85989c3678d243e229f929008ede8b2e24c0c3fa) in choicetype file value was getting with this : 

```php
$value = $child->getConfig()->getOption('value');
```
Now I think you get value in choices option in formtype. 
```php
$choiceList->getChoicesForValues([$value])
```
I think if we hab a option for example choices_empty = true in form option and you add on line 134
```php
 if ($options['expanded'] || $options['choices_empty'] ) {
```
We will fix our trouble :)

**Comment by alexbusu** [comment] 2021-03-24 12:31
> Well, submitting a form with a value which is not in the ChoiceList is not valid.
> In 4.4.19, the code was **not** working. It was silently ignoring the invalid submitted value.

I was relying on this _bug?_ to persist missing options in a data transformer.
Since the options are provided before I can access the form data (e.g. using form events), and I cannot provide new options for the implemented validator, so you see any other options I could use now, except persisting new choice entries before the form is submitted (via xhr)?

**Comment by stof** [comment] 2021-03-24 12:59
you should use the `PRE_SUBMIT` event on the parent to replace the form field with one using the additional choices

**Comment by alexbusu** [comment] 2021-03-24 13:08
I believe the form would be built already, and the choice list parsed and passed to the `PRE_SUBMIT` event callback. 

https://github.com/symfony/symfony/blob/v4.4.20/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L70
https://github.com/symfony/symfony/blob/v4.4.20/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L102

But I'll try.

**Comment by alexbusu** [comment] 2021-03-24 13:28
It is not working as suggested.
To make it work this way, the `$choiceList` should be created (also) inside the `PRE_SUBMIT` event callback. This one https://github.com/symfony/symfony/blob/v4.4.20/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L102

**Comment by stof** [comment] 2021-03-24 14:00
that's why I said the `PRE_SUBMIT` **of the parent**, where you can still replace the child with a new field using the ChoiceType (with different options.

**Comment by alexbusu** [comment] 2021-03-25 10:48
Oh, my bad; that would work! :tada: 
Thanks!

**Comment by Spounespoune** [comment] 2021-03-29 12:52
@xabbuh 

So, my trouble it's just fact to have fixed the choices validator in choicetype file who was not efficente before 5.2. Now we are obligate to add addEventListener in form to fill our choices when we use Ajax call, to avoid an validator error.

My last question, take my data (obtained from Ajax call) one time my form submit and to inject this data in AddEventListner to fill my choices is the good symfony partical ?

**Comment by Spounespoune** [comment] 2021-04-07 12:44
Hello everybody !

Just small up

Thank you

**Comment by maxhelias** [comment] 2021-04-09 07:32
If i understand the problem correctly it is similar to https://github.com/symfony/symfony/issues/39165 and the solution proposed here https://github.com/symfony/symfony/pull/40748 should solve this issue no ?

**Comment by Spounespoune** [comment] 2021-04-12 07:40
Sorry, in my case my choices is empty in my formType. Before render view, I fill my select with Ajax call. When I submit the choiceType validator throw exception. I understand is normal now.
What is a good symfony pratical for this case ? Add addEventListener and fill with previous data submit ? Or other ?

**Comment by eXtreme** [comment] 2021-04-15 20:15
I also encountered this error message after upgrading to latest 5.2. My usecase is a little bit different. My tests for validation errors started failing with this "The value array is not valid" error instead of my customized validation error message. The setup is simple:

```php
$builde->add('foobar', Type\ChoiceType::class, [
                'choices' => $choices,
                'multiple' => true,
                'invalid_message' => 'Please choose one of "a", "b", "c".',
            ]);
```

Previously when I provided a value outside of "choices" then the "invalid_message" was returned. Now I see "The value array is not valid" which can't be customized: https://github.com/symfony/symfony/pull/39659/files#diff-ac5454e048619fd2eb4ce5a3e4b18d5aa650164e3cba7106cd31f6bf1d135065R175

It also started triggering NotBlank validation error from the DTO.

So previously the only message was:

> Please choose one of "a", "b", "c".

Now I have:

> The value array is not valid.
> 
> This value should not be blank

* * *

### Edit

OK So actually I had to downgrade to 5.2.3, and that's the version where everything works as before. Something was changed in 5.2.4 that caused that issue for me. I think I can prepare a demo for that.

**Comment by eXtreme** [comment] 2021-04-18 20:03
Followup to https://github.com/symfony/symfony/issues/40483#issuecomment-820703657

I managed to create a simple demo and was unable to reproduce the behavior... until I removed individual symfony/flex packages and replaced symfony/symfony which my old application is still using. 

The difference is visible in the profiler - here using symfony/symfony:

Message | Origin | Cause
-- | -- | --
The value array is not valid. | someChoices | Caused by:Symfony\Component\Form\Exception\TransformationFailedException {#&#x2060;6594 ▼  <br/> -invalidMessage: null  <br/> -invalidMessageParameters: []   <br/>#message: "The choices "x" do not exist in the choice list."   <br/>#code: 0   <br/>#file: "/mnt/d/Jacek/Projects/test/sf-form-bug/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php"   <br/>#line: 203   <br/>trace: {▶} }

While with individual packages/flex errors in profiler look like this:


Message | Origin | Cause
-- | -- | --
Please choose one of "a", "b", "c". | someChoices | Caused by:Symfony\Component\Validator\ConstraintViolation {#&#x2060;516 ▼   root: Symfony\Component\Form\Form {#&#x2060;582 ▶}   <br/>path: "children[someChoices]"   <br/>value: [▶] }<br/>Symfony\Component\Form\Exception\TransformationFailedException {#&#x2060;548 ▼   <br/>-invalidMessage: null   <br/>-invalidMessageParameters: []   <br/>#message: "Unable to reverse value for property path "someChoices": Could not find all matching choices for the given values."   <br/>#code: 0   <br/>#file: "/mnt/d/Jacek/Projects/test/sf-form-bug/vendor/symfony/form/Form.php"   <br/>#line: 1141   <br/>trace: {▶}    …1 }Symfony\Component\Form\Exception\TransformationFailedException {#560 ▼  <br/> -invalidMessage: null   <br/>-invalidMessageParameters: []   <br/>#message: "Could not find all matching choices for the given values."   <br/>#code: 0   <br/>#file: "/mnt/d/Jacek/Projects/test/sf-form-bug/vendor/symfony/form/Extension/Core/DataTransformer/ChoicesToValuesTransformer.php"   <br/>#line: 68   <br/>trace: {▶} }

I know that using the full symfony/symfony is not supported now so I guess I will have to investigate how to restore that behavior or use that time to actually finaly move the app to individual packages. :)

**Comment by xabbuh** [comment] 2021-04-19 09:41
@eXtreme The issue you described in https://github.com/symfony/symfony/issues/40483#issuecomment-820703657 should be fixed by #40660.

**Comment by eXtreme** [comment] 2021-04-19 09:47
@xabbuh good to know, thanks! Didn't see that one.

**Comment by Spounespoune** [comment] 2021-04-23 07:25
@xabbuh do you have a response about [this](https://github.com/symfony/symfony/issues/40483#issuecomment-817568499) please ?

**Comment by xabbuh** [comment] 2021-04-23 07:32
> Sorry, in my case my choices is empty in my formType. Before render view, I fill my select with Ajax call. When I submit the choiceType validator throw exception. I understand is normal now.
What is a good symfony pratical for this case ? Add addEventListener and fill with previous data submit ? Or other ?

I would advise to use the same logic in the event listener to add the allowed choices that you use in response to the AJAX request.

**Comment by virtualize** [comment] 2021-05-10 11:08
We too need to get "new"/"invalid" values that are not in the ChoiceList.

Our solution was to add our own PRE_SUBMIT event listener with a higher priority then the one in ChoiceType.
This way we can store new values before the event listeners in ChoiceType remove them.

`$builder->addEventListener(FormEvents::PRE_SUBMIT, [$this, 'preSubmit'], 1024);`

**Comment by ghost** [comment] 2021-06-28 06:41
> @eXtreme The issue you described in [#40483 (comment)](https://github.com/symfony/symfony/issues/40483#issuecomment-820703657) should be fixed by #40660.

@xabbuh I believe https://github.com/symfony/symfony/issues/40483#issue-832613095 and https://github.com/symfony/symfony/issues/40483#issuecomment-820703657 have the same cause. This bug was introduced in both 4.4.20 and 5.2.4 by #39659. The fix has however only been applied to version 5 in #40660. Can it also be applied to version 4 please? Thanks.

**Comment by romaricdrigon** [comment] 2021-07-20 09:33
I've been having the same issue for a while, so my 2 cents for the discussion *(and why I think this issue can be closed)*.

The behaviour before 4.4.20 was quite convenient as it helped to extend `ChoiceType` to build, for instance, an AJAX picker (what I was doing). In that way the #39659 bugfix, caused quite a mess in my project (and I would guess many - I suspect many issues, such as #41356, are related).

In the end, I believe it is **correct** for `ChoiceType` to validate that selected choices are indeed part of `choices`.  
So, I think there's nothing to fix here anymore, though I can see that making a more flexible `ChoiceType` would be great (maybe something that would also help with #39165, dynamic choices and options all the way).

So here's a detailed **workaround** for whoever have the issue, **to make a custom form type work** :
 - your custom type should not extend `ChoiceType` anymore (but `FormType` or nothing at all) - doing so, you will have to handle a bit more logic (code snippet below)
 - first of all, you have to configure `compound` option (cf. snippet P1)
 - if you want to handle multiple selections, in `buildView()` you have to copy a bit of code (cf. snippet P2)
 - you need your own forme theme for your custom type (you can copy-paste the one from `choice_widget` for instance)
 - you have to pass `multiple` and `placeholder` options to the view (cf. snippet P3)
 - if you want to handle Doctrine `ArrayCollection` on top of arrays, you have to add `MergeCollectionListener` (cf. snippet P4)
 
With those tweaks, the rest of you custom code should work with Symfony 5.2.4+ (or 4.4.20+)

The snippet:
```php
class MyCustomFormType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // ...

        // P4: allow to handle ArrayCollections
        $builder->addEventSubscriber(new MergeCollectionListener(true, true));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('compound', false); // P1: should always be "false"

        // P3: required to re-use same widget, passed to buildView()
        $resolver->setDefault('multiple', false);
        $resolver->setDefault('placeholder', null);

        // ...
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        // P2: required to handle multiple, so values are not spread into multiple POST parameters
        if ($options['multiple']) {
            $view->vars['full_name'] .= '[]';
        }

        // P3: required for using the same widget
        $view->vars['multiple'] = $options['multiple'];
        $view->vars['placeholder'] = $options['placeholder'];
    }
}
```

**Comment by xabbuh** [comment] 2021-07-27 13:40
I agree with @romaricdrigon. That's why I am closing here.

**Closed as completed by xabbuh** 2021-07-27 13:40 UTC
Labels: Form, Bug, Status: Reviewed, Status: Waiting feedback

**Comment by ikamikaz3** [comment] 2021-11-17 16:53
Hello @romaricdrigon,

Can you provide a working example of that customFormType ? I'm trying to do exactly the same thing, I've had a custom form type to handle Dynamic choices with Ajax + Select2 and it's broken since sf5.

Thanks in advance
