### ISSUE TITLE
Overriding Bootstrap 5 horizontal form layout with non-horizontal layout breaks some field row markup

### ISSUE THREAD

**Issue by cameronmurphy** [symfony/symfony#57955] opened 2024-08-08 23:22 UTC
### Symfony version(s) affected

7.1.3

### Description

I inherited an app where the default form layout was set to the Bootstrap 5 horizontal layout. I'm building new forms with a slightly different interface and I want to use the non-horizontal layout. Overriding the form layout in the template breaks CheckboxType and SubmitType row markup.

These two field types are being rendered as if they're in a horizontal form. Their row receives a `row` class and they're rendered in columns with a `col-sm-2` spacer to the left.

![image](https://github.com/user-attachments/assets/c706a0bf-0a75-45c7-aa76-578e7165bf91)

![image](https://github.com/user-attachments/assets/029ae7e6-00d5-426c-a5f2-9a93b3b9059a)

### How to reproduce

Create a blank Symfony webapp.

In `config/packages/twig.yaml`:
```yaml
twig:
    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'
 ```
 
in `src/Controller/DefaultController.php`:
```php
    #[Route('/', name: 'app_default')]
    public function index(): Response
    {
        $form = $this->createFormBuilder()
            ->add('text', TextType::class)
            ->add('checkbox', CheckboxType::class)
            ->add('submit', SubmitType::class);

        return $this->render('default/index.html.twig', [
            'form' => $form->getForm(),
        ]);
    }
```

in `templates/default/index.html.twig`:
```twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% extends 'base.html.twig' %}

{{ form(form) }}
```

### Possible Solution

The best solution I could come up with was putting
```twig
{% block form_label_class %}{% endblock form_label_class %}
```
in `bootstrap_5_layout.html.twig` to clear out the value incorrectly coming through from `bootstrap_5_horizontal_layout.html.twig`. This is imperfect because the form row still gets rendered with an unnecessary `row` class on the surrounding div which adds some padding.

Of course, I can make the non-horizontal theme the default and apply horizontal manually to the 68 forms in the app, but I feel like this approach should have worked.

**Comment by xabbuh** [comment] 2024-08-09 07:06
When using the `form_theme` tag you can choose to [ignore the globally configured form themes](https://symfony.com/doc/current/form/form_themes.html#disabling-global-themes-for-single-forms):

```twig
{% form_theme form 'bootstrap_5_layout.html.twig' only %}
```

**Comment by xabbuh** [comment] 2024-08-09 15:44
I am closing here as this is not a bug as explained above.

**Closed as not planned by xabbuh** 2024-08-09 15:44 UTC
Labels: Bug, Status: Needs Review

**Comment by cameronmurphy** [comment] 2024-08-11 04:46
@xabbuh That solution breaks.

![image](https://github.com/user-attachments/assets/7369aad5-6524-4889-af79-6be4a13e3785)
