### ISSUE TITLE
[RFC][DX][Form] Use the default EventDispatcher for form events

### ISSUE THREAD

**Issue by Sander-Toonen** [symfony/symfony#30712] opened 2019-03-26 15:48 UTC
It can be quite confusing that one cannot configure an event listener or subscriber in ``services.yaml`` that listens to form events. I wonder why we do not use the default EventDispatcher instance for dispatching form events? Of course this only applies when forms are build using the FormFactory registered in the FrameworkBundle.

Two reasons why I believe form events should be dispatched using the default EventDispatcher instance:

**1. Uniformity/DX**

After learning how the Symfony event and form systems work a developer might assume the following works:

```yaml
services:
    App\EventListener\FormPreSubmitListener:
        tags:
            - { name: kernel.event_listener, event: form.pre_submit }
````

**2. Promote decoupled code**

The observer pattern is all about decoupling code. However, right now there is no clear way to add EventListeners or -Subscriber to form classes without coupling the form class to the event listener. A workaround might be to create a form type extension which adds event subscribers but this results in quite some boilerplate code (See: https://stackoverflow.com/a/48157630/3492835) and also inexperienced developers might feel more comfortable coupling the EventSubscribers to the form classes.

What do you think?

**Comment by dmaicher** [comment] 2019-03-26 16:01
Wondering if its really a common use case to globally handle form events on all forms?

Your `App\EventListener\FormPreSubmitListener` would be invoked for *any* form? 

Then somehow events must be namespaced per form?

**Comment by Sander-Toonen** [comment] 2019-03-26 16:08
@dmaicher Well, one could easily get the form from the form event and check for its type.

**Comment by dmaicher** [comment] 2019-03-26 17:29
But then how would efficient dispatching for listeners on one form work?

For example my biggest Symfony work project has ~ 50 form event listeners for `FormEvents::PRE_SET_DATA` in total.

I mean we cannot just dispatch the event to all of them, right? So how would we do it for specific listeners that are not meant to be global?

**Comment by Sander-Toonen** [comment] 2019-03-26 19:17
Is there anything known about the performance of the event dispatcher? I wouldn't know whether of not it would have a real performance impact.

**Comment by HeahDude** [comment] 2019-03-27 09:13
Hello @Sander-Toonen, thank you for opening this issue.

There is a reason for that "inconsistency". The container allows to register listeners for the global dispatcher used commonly in application, the one that is originally used by the `HttpKernel` itself for kernel events.

But, the `Form`, as a standalone component, has a hard dependency on the event dispatcher component. The reason is that every form (and every field of it) has its own instance of dispatcher that you may configure throw a form type. Each field has its own life cycle dispatching for data initialization and submission. This is why by design this coupling between form and listeners is "natural".

I already asked myself that question and I guess many did before, and will again, but having one dispatcher instance to dispatch all form events of every fields may bring a lot of complexity to the code, and in the end more confusion about what's happening and how to do/configure things... what @dmaicher already pointed at.

**Comment by Sander-Toonen** [comment] 2019-03-27 10:56
@HeahDude Thank you for your view on this subject. 

The hard dependency from the form component on the event dispatcher would not have to be a problem. When the EventDispatcher would be generated by a factory service, the framework bundle could replace the factory with one that always returns the main event dispatcher instance.

I can understand the other objections and maybe there are better ways of solving this issue. I do however believe that there is a common use case which is hard to solve using the current system. Simply put, one should be able to alter any form without the need of touching the form class.

Imagine for instance a codebase of a webshop-system that defines a number of forms for the checkout process. This system handles shops on multiple domains (for several clients). Depending on the domain some fields are mandatory or not, some fields might be added or removed and some defaults or constraints might be altered. One should be able to add code that implements the requirements of these clients without touching the core system, in this case the default checkout forms. The current idiomatic approach would be to add eventlisteners in the form class itself which in my view goes completely against the practice of decoupling code that Symfony encourages in other parts of the system.

Is there a way to deal with this issue without the drawbacks of my initial proposal?

**Comment by HeahDude** [comment] 2019-03-27 11:14
Form type extension allows to register configuration (options, listeners, ...) globally to form types.
This should be the solution to your problem no?
Also now type extensions are also easy to auto configure and can target many types to register listeners or add fields or requirements when needed.

**Comment by javiereguiluz** [comment] 2019-07-08 14:38
Closing as "won't fix" for the reasons given by @Tobion. Also, as @HeahDude said, if you really need an "event" to potentially change all/some/most forms, you can achieve that more easily with [Symfony Form extensions](https://symfony.com/doc/current/form/create_form_type_extension.html). Thanks.

**Closed by javiereguiluz** 2019-07-08 14:38 UTC
Labels: DX, Form, RFC
