### ISSUE TITLE
Impossible to get private services from TestContainer

### ISSUE THREAD

**Issue by lelledaniele** [symfony/symfony#30104] opened 2019-02-07 13:16 UTC
Hi there,

**Symfony version(s) affected**: 4.2.3

**Description**  
An old PR https://github.com/symfony/symfony/pull/26499 should allow us to use private services in `test` env as public.
On my local, I am struggling to make it work. [Post here](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing)

**How to reproduce**  

- Install the latest version of Symfony and Symfony Bridge
- Create a service
- Create a test
```php
<?php

namespace App\Tests;

// My service namespace here
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ServiceTest extends WebTestCase
{
    /**
     * {@inheritdoc}
     */
    public function setUp(): void
    {
        self::bootKernel();
    }

    public function test(): void
    {
        self::$container->get(Service::class);
    }
}
```
- Run `./bin/phpunit --stop-on-failure`
- Output
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "CLASS service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

**Additional context**  
File: `vendor/symfony/framework-bundle/Test/TestContainer`
Method: `get`
```php
dump($this->getPrivateContainer()->has($id)); // False
dump($this->getPublicContainer()->has($id)); // False
dump($this->getRemovedIds()); // There is my service
```

Many thanks for your time,
Lelle

**Comment by nicolas-grekas** [comment] 2019-02-07 16:55
> The "CLASS service or alias has been removed or inlined when the container was compiled

What the error says is accurate.

If you want to test an unused service, you need to create a public test alias for it:
in `config_test.yaml`:
```yaml
services:
    test.CLASS:
        alias: CLASS
        public: true
```

Closing as this is expected behavior, thus no bug to keep track of.

**Closed by nicolas-grekas** 2019-02-07 16:55 UTC

**Comment by lelledaniele** [comment] 2019-02-13 15:46
Hi @nicolas-grekas,

thank you for your quick response.
Sorry, I still not get it.
From this blog post (https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) I should be able to get private services from the special container `$container = self::$container;` without replicate the declaration of the service for the test env.

Thanks,
Lelle

**Comment by flackovic** [comment] 2019-02-14 14:13
The thing is, service is not used anywhere in the project, so "RemoveUnusedDefinitionsPass" removes it from container.

Try to inject it in some of your controllers, just so Symfony think it is used, and then it should work.

I am not sure why does it behave like that in test container, since it is making TDD approach difficult.

@nicolas-grekas are there any plans to change this behaviour in test container, like private / public was changed [here](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) ?

**Comment by nicolas-grekas** [comment] 2019-02-14 14:15
Nope, no plans to do so, `RemoveUnusedDefinitionsPass` is absolutely required, keeping unused services would create a wide range of failure cases.

**Comment by flackovic** [comment] 2019-02-14 14:20
@nicolas-grekas I see. Thanks for clarifying.

**Comment by lelledaniele** [comment] 2019-02-14 15:43
Thank you, both.

**Comment by mmenozzi** [comment] 2019-11-12 15:07
> Nope, no plans to do so, `RemoveUnusedDefinitionsPass` is absolutely required, keeping unused services would create a wide range of failure cases.

I think that this should be documented here https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing

This because is pretty common that someone uses a service for the first time only in an integration test which tests its behavior.

**Comment by nicolas-grekas** [comment] 2019-11-12 15:40
@mmenozzi would you mind sending a PR to the doc repo?

**Comment by mmenozzi** [comment] 2019-11-13 11:58
Hi @nicolas-grekas I'd be happy but I don't know where to submit the PR. Is that blog post on the https://github.com/symfony/symfony-docs repo? If so could you point me to the correct file?

**Comment by javiereguiluz** [comment] 2019-11-13 14:33
@mmenozzi that's correct! According to our supported versions, this change must be done in 4.3 branch (and we'll later merge it in 4.4 and master too). Specifically, I guess you need to update the section about testing + container in this file: https://github.com/symfony/symfony-docs/blob/4.3/testing.rst Thanks!

**Comment by mmenozzi** [comment] 2019-11-14 08:23
Ok @javiereguiluz I'll do it asap.

**Comment by mmenozzi** [comment] 2019-11-18 10:12
Hi guys, I did the PR https://github.com/symfony/symfony-docs/pull/12647 but I also think that the blog post https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing should be updated as well. That blog post is well indexed on Google. If I search for "symfony access private service in test" that post is the first result.

**Comment by javiereguiluz** [comment] 2019-11-18 10:28
@mmenozzi good idea! I've just updated the blog post.
