### ISSUE TITLE
Impossible to import validations file yaml from file out of validator folder

### ISSUE THREAD

**Issue by pasqualepalmaccio** [symfony/symfony#39752] opened 2021-01-07 14:24 UTC
I can't import a validation file yaml (user.yaml) from yaml that is not in validator folder.
Imports property is only valid if i try to import a validator sub-folder file yaml in validation.yaml.
When i try to import my yaml file in validation.yaml from a different folder out of validator folder, it doesn't works.

Can i solve this? 
thanks, best regards

**Comment by xabbuh** [comment] 2021-01-07 16:49
I am not sure I understand your issue. Can you create a small example application that allows to reproduce it?

**Comment by pasqualepalmaccio** [comment] 2021-01-08 08:12
```
imports:
         -{'entity_validation.yaml'}
```

```
imports:
         -{'/myfolder/entity_validation.yaml'}
```

works fine. 
Instead: 

```
imports:
         -{'../../scr/DirectoryPath/entity_validation.yaml'}
```
or 
```
imports:
         -{'../DirectoryPath/entity_validation.yaml'}
```
doesn't work.

**Comment by xabbuh** [comment] 2021-01-08 09:03
I do not really understand what you are doing there. Our validation files do not support any `imports` keyword.

**Comment by pasqualepalmaccio** [comment] 2021-01-08 09:16
According to Symfony Validator documentation , i'm using a validation.yaml file (in config/validator/validation.yaml) to validate my DTO.

```
imports:
  - { resource: 'user/dto/mydto.yaml' }
```

This syntax only works if you import validation yaml's files from a subdirectory of validator (for example config/validator/dto/).
If you try to import a validation yaml file from other directories out of "validator" (as i am doing for others yaml configuration's file ), validation doesn't works. 

It's a bug or a feature ? 
Thanks and best regards.

**Comment by xabbuh** [comment] 2021-01-08 09:38
I am sorry, but I really do not understand what you are doing here. Please create a small example application that allows us to better understand this.

**Comment by stof** [comment] 2021-01-08 09:52
imports don't exist in the validator mapping files.

The reason things work for subfolders is because FrameworkBundle loads all files in `config/validator`, not only `config/validator/validation.yaml`. So the file is loaded, but not because of your import.

**Comment by pasqualepalmaccio** [comment] 2021-01-08 10:04
> imports don't exist in the validator mapping files.
> 
> The reason things work for subfolders is because FrameworkBundle loads all files in `config/validator`, not only `config/validator/validation.yaml`. So the file is loaded, but not because of your import.


now that's clear, thanks. In DDD i'm using a "Domain / Infrastructure" paths in which i put all Domain's infrastructure (symfony) configurations yaml like services etc...but validations stops working in this way. 
Maybe it could be a feature. Best regards.

**Comment by stof** [comment] 2021-01-08 10:09
you can register additional folders for loading in the validator config of FrameworkBundle

**Comment by xabbuh** [comment] 2021-01-08 10:29
Let's close here as there is no issue and this needs to be fixed in the application configuration.

**Closed as completed by xabbuh** 2021-01-08 10:29 UTC
Labels: Validator, Bug, Status: Needs Review, Status: Waiting feedback
