### ISSUE TITLE
Error while extend template in a custom path, Symfony 2.8.4-DEV

### ISSUE THREAD

**Issue by jreynerio** [symfony/symfony#18497] opened 2016-04-10 05:28 UTC
Hi, there is an error when extends a template

```twig
{% extends 'AppBundle:base.html.twig' %}
```

always search in "app/Resource/views" no matters the location be instructed

I change the vendor dir to the version 2.8.3 from other project and it works normaly.

Greetings.

**Comment by javiereguiluz** [comment] 2016-04-10 07:43
A few days ago we received a similar issue report (#18364). At first it looks like the problem is that Symfony can't find the template for the given path. But the real problem is that the template path is wrong. It should never have worked (I don't know why it worked in previous Symfony versions).

Your path should probably be:

```twig
{% extends 'AppBundle::base.html.twig' %}
```

In any case, for modern Symfony applications I always recommend to use the new namespaced-syntax (e.g. `@App/base.html.twig`). It allows you to forget about the ugly `:`, it's easier to understand and it's "unique" (every template has a unique namespaced representation, whereas the traditional notation allows several representations for any given template).

I'm going to close this issue as "solved", but if you have any other problem, please reopen it. Thanks!

**Closed by javiereguiluz** 2016-04-10 07:43 UTC
Labels: Bug, Status: Needs Review, Unconfirmed
