### ISSUE TITLE
[Form] BooleanToStringTransformer reverseTransforms '0' to true

### ISSUE THREAD

**Issue by leberknecht** [symfony/symfony#13589] opened 2015-02-04 12:32 UTC
Aloha!

As we are converting '1' to true, i think we should convert '0' to false. I'm not quite sure if this is a "bug" or an unexpected behaviour. What do you guys think? Can i open a PR for https://github.com/leberknecht/symfony/tree/fix-bool-to-string-transformer ? And if so, does this break BC if we change that behaviour? Aloha!

**Comment by XWB** [comment] 2015-02-04 12:46
> I'm not quite sure if this is a "bug" or an unexpected behaviour.

Well technically `is_string('0')` is true.

**Comment by leberknecht** [comment] 2015-02-04 12:48
^^ oh, i should have been more precisley: i'm talking about the reverseTransform

**Comment by ogizanagi** [comment] 2015-02-04 15:01
Related to #13539 ?
If this is merged, any checkbox with value `0` will be interpreted as false, even if checked:
```html
<label>Php<input type="checkbox" value="0" name="capacities"></label>
<label>Symfony<input type="checkbox" value="1" name="capacities"></label>
<label>Javascript<input type="checkbox" value="2" name="capacities"></label>
```
If a user check the 3 checkboxes, the `choice` form type will only return `capacities['Symfony', 'Javascript']`.

IMO the issue is that the `BooleanToStringTransformer ` is meant to be used with radio & checkboxes form types respecting HTTP protocol. If nothing was sent -> `false`, if something was sent -> `true`. Not for string conversions.

**Comment by leberknecht** [comment] 2015-02-05 08:41
Hm jep, i think thats related :) ..a bit unexpected, but with that explanation actually makes some kind of sense.

**Comment by DrBenton** [comment] 2015-02-08 14:45
I ran into problems with that behaviour as well when using PATCH forms savings, even if I send the form content as a JSON data structure.
Couldn't find a way to handle that. This prevent me from using the same Symfony forms for PATCH API calls and HTML forms...

**Comment by leberknecht** [comment] 2015-02-11 09:19
Actually i think you can ship around that by defining your own DataTransformer and append it to each field...something like
```php
$builder->create('myBool', null)
    ->resetViewTransformers()
    ->addViewTransformer(
          new FancyNonHttpConformBoolTransformer()
);
```
With FancyNonHttpConformBoolTransformer beeing something like https://github.com/leberknecht/symfony/blob/9c5d3de2af662e77b33d44137c6019e6daa58517/src/Symfony/Component/Form/Extension/Core/DataTransformer/BooleanToStringTransformer.php
But you'll need to attach it explicitly on every field... so.... :/ ..Maybe you could use some dirty composer autoload-magic-trick to overwrite the vendor...but thats close to "i need a shower afterwards" i think :)

**Comment by docteurklein** [comment] 2015-02-26 13:04
@leberknecht one can use form type extensions in order to apply the transformer on a specific type.

**Comment by ogizanagi** [comment] 2015-02-26 13:17
@docteurklein : I think you should avoid doing that in order to apply globally this transformer on every `checkbox` fields, for the same reasons as I mentioned above.
Create and use only when needed your own form type instead.

**Comment by docteurklein** [comment] 2015-02-26 13:24
Talking about what you said before:

> IMO the "issue" is that the BooleanToStringTransformer is meant to be used with radio & checkboxes form types respecting HTTP protocol.

Currently only the `checkbox` uses `BooleanToStringTransformer`.

I propose to introduce a new checkbox option: 'falsy_values' (defaulting to `[null]` to be BC?).
Currently `BooleanToStringTransformer` has a `trueValue` ctor argument, that equals the `value` option of the field.

Let's introduce a second argument, `array $falsyValues = [null]`, that will be used instead of always checking for `null` equality.

this way, one can initialize its checkbox with option: `[falsy_values' => [null, '0', 0, false, '']].

**Comment by ogizanagi** [comment] 2015-02-26 14:33
@docteurklein : this seems a good option to me. :+1: 

> Currently only the checkbox type uses BooleanToStringTransformer.

In fact, `radio` type's parent is `checkbox`.

**Comment by docteurklein** [comment] 2015-02-26 16:26
@ogizanagi oh indeed, I haven't thought about that. Yes in that case this option will also be available to `radio` type I guess.

**Comment by leberknecht** [comment] 2015-02-26 18:49
Aye! Would solve my problem :)

**Comment by HeahDude** [comment] 2016-02-13 20:26
Cannot a listener of `FormEvent::PRE_SUBMIT` do the job ?
```php
$builder->addEventListener(FormEvent::PRE_SUBMIT, function ($event) {
    if (in_array($event->getData(), array(0, '0', 'false', null)) {
        $event->setData(false);
    }
});
```

**Comment by vasilvestre** [comment] 2017-06-12 12:42
Using Symfony 2.7, still got this problem, passing 'false' or '0' from Ajax and converted to true by form, while 'false' == false is at true for PHP. Maybe I've to update something ?

**Comment by HeahDude** [comment] 2017-06-12 12:47
For now, the simplest way from Ajax to work with the current transformation process is to submit an empty string.

**Comment by vasilvestre** [comment] 2017-06-12 12:52
@HeahDude actually no, it doesn't work. Still saw as true for Symfony with empty string...

**Comment by HeahDude** [comment] 2017-06-12 13:34
>Still saw as true for Symfony with empty string...

Hmm that sounds like a bug to me.

**Comment by vasilvestre** [comment] 2017-06-12 13:46
@HeahDude it's an old Symfony (2.7 isn't supported anymore?), I will just patch it myself.. Not a best pratice but that's not like don't upgrade isn't one. Thank you anyway !

**Comment by HeahDude** [comment] 2017-06-12 13:48
2.7 is till maintained, if you could provide a sample of code to reproduce your issue from Symfony standard it would allow us to take a deeper look into this, thanks!

http://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by vasilvestre** [comment] 2017-06-12 14:00
@HeahDude I will do it in my free time so :)

**Comment by iltar** [comment] 2017-06-29 11:36
@HeahDude I'm facing the same problem here. The `BooleanToStringTransformer` transforms anything that's not null to a true. This makes sense for radio buttons and checkboxes, but not for anything else. The name of this transformer is wrong imo, as it does not transform a string to boolean. I'd expect an empty string to become false as well.

I have to use a hidden type as I can't add `checked="checked"` after the first submit. It will set the checkbox to a "1" value, but never adds the checked state.

**Comment by AlexandreKilian** [comment] 2018-01-09 13:49
Any recommendations that aren't as hacky as ModelTransformers or Listeners? Yes, `is_string()` is doing what it is doing correctly, but this can't be the expected behavior for a CheckboxType... This should be much strikter and use a blacklist rather than basically passing this through as "true" whenever the field is not missing... 0 and '0' and 'false' or just an empty string should not be transformed into `true`...
Can't be the solution to make a custom CheckboxType because the default one is basically useless

**Comment by leberknecht** [comment] 2018-01-09 15:10
>This should be much strikter and use a blacklist rather than basically passing this through as "true" whenever the field is not missing

Hm, but thats what HTTP defines :/ :D But the solution with introducing an optional argument to define falsy values sounds good to me!

**Closed** 2018-01-17 20:11 UTC
Labels: Form

**Comment by nu111** [comment] 2023-11-03 18:20
I had the same issue on Symfony 5.4. I am implementing an API server. If I have a Doctrine entity with a boolean field, and I create a FormType for that entity, Symfony automatically links that field with a CheckboxType.

If you send a PATCH request with a json trying to set that boolean to false
```json
{ "my_flag": 0 }
```
the flag will be setted to true on the db.

The solution was to use a [Form Type Extension](https://symfony.com/doc/5.4/form/create_form_type_extension.html) to set the `false_values` globally on every ChecboxType

```php
<?php
namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MyCheckboxTypeExtension extends AbstractTypeExtension
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'false_values' => [
                0,
                null,
                '0',
            ],
        ]);
    }

    /**
     * Returns an array of extended types.
     */
    public static function getExtendedTypes(): iterable
    {
        // return [FormType::class] to modify (nearly) every field in the system
        return [CheckboxType::class];
    }
}
```

**Comment by stof** [comment] 2023-11-03 18:41
The CheckboxType expects the behavior of a checkbox of the HTML spec: unchecked checkboxes are not part of the submitted data at all. They are not submitted as a false value (`0` could be a valid value for a checkbox). That's why the default config works the way it is.

Be careful with your form type extension: if you register it in a project that uses actual forms (and not an API implemented using the form component), it might break things.
