### ISSUE TITLE
Occuring Fatal Error in Doctrine\Common\Proxy\ProxyGenerator::getProxyFileName.

### ISSUE THREAD

**Issue by abikoka** [symfony/symfony#15047] opened 2015-06-20 16:01 UTC
Hi,

In some occasinal times, I have meet the error in Doctrine\Common\Proxy\ProxyGenerator::getProxyFileName on browser or Behat Testing.
But we can't be occured it again after that I restart Apache process. 
And I wonder when we debug for the this case, get following result:

* When we add var_dump sentence of Proxy::MARKER above 864 lines(getProxyFileName method) of vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php file, we can be occured the error.
* When we add var_dump sentence of Proxy::MARKER in app_dev.php, we can't be occured the error.

We think that there is the reason of which apc or Symfony Cache is broken.

Let me know if you have same trouble.

Situations:
 - Symfony2.3
 - Apache 
 - PHP 5.4

**Comment by ewgRa** [comment] 2015-06-20 19:07
Can you show error message and call stack?

**Comment by abikoka** [comment] 2015-06-21 10:18
Hi @ewgRa 、

Thank you for your replying!

The error is folloing, 
```
 [Sun Mar 01 04:36:54.470454 2015] [:error] [pid 7856] [client 10.128.12.155:53852] PHP Fatal error:  Cannot inherit previously-inherited or override constant MARKER from interface Doctrine\Common\Persistence\Proxy in /source/to/path/releases/20150223061956/vendor/doctrine/common/lib/Doctrine/Common/Proxy/Proxy.php on line 33
```
Thank you in advance for your help.

**Comment by ewgRa** [comment] 2015-06-21 11:48
There is a lot of similar problems in google, and seems all related to APC. 

Which one version of APC you have? Try update it to latest

**Comment by ewgRa** [comment] 2015-06-21 11:52
Also try to reproduce it like here https://bugs.php.net/bug.php?id=59101 and if you have latest APC version - you can try report a bug to php and point it here.

**Comment by javiereguiluz** [comment] 2016-02-05 16:34
Closing it because, as @ewgRa explained, there are a lot of reports like these and all are related to some APC bugs. Most people said that upgrading PHP solved their problems. If you have more details about a Symfony-related issue, please reopen this issue. Thanks!

**Closed by javiereguiluz** 2016-02-05 16:34 UTC
Labels: Doctrine
