### ISSUE TITLE
Dynamical arguments have to be in first position when autowiring

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#23478] opened 2017-07-11 13:35 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

It looks like if some services are autowired, it is not possible to dynamically change an argument (with `replaceArgument()`) into the bundle extension except if that argument is in first position.

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid constructor argument 5 for service "My\PrivateBundle\Model\SecurityModel": argument 1 must be defined before. Check your service definition. in /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php:41
Stack trace:
#0 /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\CheckArgumentsValidityPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php(31): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /projects/MyPrivateBundle/ven in /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php on line 41
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid constructor argument 5 for service "My\PrivateBundle\Model\SecurityModel": argument 1 must be defined before. Check your service definition. in /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php:41
Stack trace:
#0 /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\CheckArgumentsValidityPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php(31): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /projects/MyPrivateBundle/ven in /projects/MyPrivateBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php on line 41
```

Please check complete context here: https://gist.github.com/Vinorcola/472d4ae9e428b77af4b0c58ad306d123

**Comment by nicolas-grekas** [comment] 2017-07-11 14:13
indeed, you need to use named arguments when using autowiring

**Comment by Vinorcola** [comment] 2017-07-12 07:18
I am using named arguments. But still, you can only replace the first argument. You cannot replace the 4th on for example.

**Comment by nicolas-grekas** [comment] 2017-07-12 07:33
can you provide us with a reproducer, eg by providing a patched fork of the standard edition?
also, what's the output related to this?
```
--- a/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/CheckArgumentsValidityPass.php
@@ -37,7 +37,7 @@ class CheckArgumentsValidityPass extends AbstractRecursivePass
                 if (!is_int($k)) {
                     throw new RuntimeException(sprintf('Invalid constructor argument for service "%s": integer expected but found string "%s". Check your service definition.', $this->currentId, $k));
                 }
-
+print_r($value->getArguments());
                 throw new RuntimeException(sprintf('Invalid constructor argument %d for service "%s": argument %d must be defined before. Check your service definition.', 1 + $k, $this->currentId, $i));
             }
         }
```

**Comment by Vinorcola** [comment] 2017-07-12 07:48
Well, well, it seems that I can't reproduce the error this morning!!!

Maybe that was a cache issue. I encounter the error while I was converting my service definition to new 3.3 configurations (autowiring + className as service name). It is weird because I had the error while running the cache-clear command...

Sorry for the false alarm ^^

**Comment by nicolas-grekas** [comment] 2017-07-12 08:02
OK, closing then.

**Closed by nicolas-grekas** 2017-07-12 08:02 UTC

**Comment by biliboo** [comment] 2017-07-18 13:46
I have the exact same issue. I think this has to deal with the service definition arguments. Here is an extract of CheckArgumentsValidityPass:

```php
foreach ($value->getArguments() as $k => $v) {
    if ($k !== $i++) {
        if (!is_int($k)) {
            throw new RuntimeException(sprintf('Invalid constructor argument for service "%s": integer expected but found string "%s". Check your service definition.', $this->currentId, $k));
        }

        throw new RuntimeException(sprintf('Invalid constructor argument %d for service "%s": argument %d must be defined before. Check your service definition.', 1 + $k, $this->currentId, $i));
    }
}
```

In your case, `$value->getArguments()` returns something like `[4 => SecurityUserFactoryInterface]` instead of the full list of the arguments (you have 5 in total). This is strange since that the index 4 was found properly. Since we compare a $k and a $i which starts at 0, the error is triggered.

I'm also migrating to 3.3, I tried building the cache again without success. The getArguments() methods should returns all arguments like in `Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass::getConstructor`, but somewhere the arguments not listed in the YAML are removed (but indexes are kept?).

Hope tomorrow morning it will work...

**Comment by xabbuh** [comment] 2017-07-18 14:04
@biliboo Are you able to provide an example that allows to reproduce your issue?

**Comment by biliboo** [comment] 2017-07-18 14:20
Well, I'm a bit embarrassed since I'm migrating from 3.2 to 3.3. And in a new 3.3 project everything works as expected.

The issue occurs during the initialization fo the Definition arguments of the service. I continue the research...

**Comment by biliboo** [comment] 2017-07-18 17:45
I finally found the issue. I've decided to create a services_di.yml in order to isolate the named parameters configuration (waiting to see how this feature could get implemented in futur). Therefore, it seems that the merge in the YAML files did not work as I expected. I thought I could declare the services in the same way as the migration exemple file `legacy_aliases.yml`, but no.

I moved all declaration in the services.yml and everything works fine. Hope it helps someone.

**Comment by TimoBakx** [comment] 2018-03-23 09:01
I had this issue as well today in Symfony 4.0. It turns out that if you have a separate file to override some services (in my case `services_dev.yaml`, you'll need to define the `_default` set in that file as well.

Sample class:
```php
class MyClass
{
    // The first argument should be auto-wired, the second one should be wired manually
    public function __construct(MyService $service, string $someString)
    {
    }
}
```

### Case 1: When not defining anything:
Error: `Cannot autowire service "App\MyClass": argument "$someString" of method "__construct()" must have a type-hint or be given a value explicitly.`

### Case 2: When defining in a separate services file (without defining the defaults):
```yml
# config/services_dev.yaml
services:
    App\MyClass:
        arguments:
            $someString: 'test'
```
Error: `Invalid constructor argument 2 for service "App\MyClass": argument 1 must be defined before. Check your service definition.`

### Case 3: After redefining the `_defaults` in the separate services file:
```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\MyClass:
        arguments:
            $someString: 'test'
```
No more errors!

**Comment by nicolas-grekas** [comment] 2018-03-23 09:06
@TimoBakx correct, defaults apply only to the current file. And newly defined services replace previous ones with the same name.

**Comment by TimoBakx** [comment] 2018-03-23 10:29
Thanks, my Google search on the error message led me here, so I put the solution on for others that might run into the same problem.
