### ISSUE TITLE
post_max_size_message translation always used

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#19256] opened 2016-07-01 07:34 UTC
https://github.com/symfony/symfony/pull/19061

Since 3.1.2, even if your form doesn't contains an upload, Symfony\Component\Form\Extension\Validator\Type\UploadValidatorExtension::configureOptions() try to translate "The uploaded file was too large. Please try to upload a smaller file.", in its closure (line 47).

I don't understand why before 3.1.2, this translation was not always translated, and now, it is.
Problem is : we don't need this translation, and i throw an exception on each translation not found (to be sure all translations are found).

Can you revert it, or solve the problem ?
Thanks

**Comment by fabpot** [comment] 2016-07-01 07:57
@DavidBadura Can you have a look? Thanks.

**Comment by DavidBadura** [comment] 2016-07-01 08:43
I'll have a look

**Comment by RicardoJ** [comment] 2016-07-01 10:50
This was also a known bug that has been fixed in #9048 (`2.3`).

**Comment by steevanb** [comment] 2016-07-02 07:37
I don't see how this can fix translation problem ?

**Comment by DavidBadura** [comment] 2016-07-02 17:23
@steevanb do i understand you correctly, you throw the exception yourself if a translation is missing? Usually, the translation component doesn't throw an exception if a translation is missing.

As proposed by @aitboudad, i created a form extension that always translates the error message and it doesn't matter if it is thrown or not. I can't fix this in the extension because it doesn't know if the error is happening.

With my proposed solution #18543 i translate the message only if the error has happened in RequestHandler. 

The question is, isn't your case an edge case? Or should we switch to #18543 @fabpot?

**Comment by HeahDude** [comment] 2016-07-03 10:44
@DavidBadura One problem with #18543 is that it makes the request handler dependant to the translator. This is really weird IMO.

@steevanb When you say "exception", don't you mean silent errors triggered to be profiled in debug? This is not the same. Although I agree this should not happen, I guess this is better than no translation at all, isn't it?

There might be a way to solve this consistently, I'll try to have a look.

**Comment by steevanb** [comment] 2016-07-05 09:50
@DavidBadura : i throw the exception myself, to be sure all translations exists. That's how i found this error.

**Comment by JoeKre** [comment] 2016-07-21 12:29
@steevanb 
This issue isn't limited to 3.1.2. 
2.8.8 is also affected. Quite irritating when the Debug Toolbar shows an error because this one key is missing while all actually used keys are defined or fallbacks.
![translation_error](https://cloud.githubusercontent.com/assets/9037466/17022638/6a4c2728-4f4f-11e6-89dd-84594fb1b12d.png)

**Comment by stany99** [comment] 2016-07-23 15:13
@JoeKre yep, I confirm that.
2.8.8

**Comment by steevanb** [comment] 2016-08-10 15:34
Hi,

It's not fixed in 3.1.3. So i can't update Symfony since 3.1.1 :(
Could you please have a look, and tell us when it will be fixed ?

Thanks !

**Comment by jakzal** [comment] 2016-08-10 16:33
@steevanb Previously the message wasn't translated which was a bug (#15479). Since all the error messages go through the translator, why this one shouldn't?

**Comment by steevanb** [comment] 2016-08-10 16:43
Cause if i don't use a FileType in my form, why this message should be translated ?

**Comment by aitboudad** [comment] 2016-08-10 17:42
Hi, a possible fix (#19595) but not sure if it will be accepted ;)

**Comment by armellin** [comment] 2016-08-16 10:47
Actually, I am facing a double translation (I have a default_locale set). The first one regularly done from English to Italian by the Form component,  and then another failed attempt from Italian to Italian.

**Comment by aitboudad** [comment] 2016-08-16 10:53
@armellin not sure if it's related, if not please provide a fork of Symfony Standard Edition that reproduce your issue.

**Comment by steevanb** [comment] 2016-09-06 12:49
#19595 doesn't fix this issue in 3.1.4, i always have "The uploaded file was too large. Please try to upload a smaller file." translation not found on each FormType, even if i don't use FileType.

**Comment by aitboudad** [comment] 2016-09-06 14:51
@steevanb the PR #19595 is not yet merged!

**Comment by steevanb** [comment] 2016-09-06 14:55
Lol ! Sorry ! When i read the 3.1.4 changelog, i was pretty sure it was merged ...

Thanks !

**Closed** 2016-09-06 16:13 UTC
Labels: Bug, Form, Status: Needs Review
