### ISSUE TITLE
[Form] Use empty_data for form default values.

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#16530] opened 2015-11-12 09:38 UTC
Hello.

I did not used the form component for a while, So I may be wrong (but [see this doc](http://symfony.com/doc/current/cookbook/form/use_empty_data.html))

First, I pushed to code to ease understatement: https://github.com/lyrixx/symfony-standard/commit/d203604e803e85255e8114f83cd6d6c5dd498fe0

Basically, I create a form **without** data but with a data_class.
My "Entity" class have default values, So I expected to see the default values as the form default values. But instead, my form is empty:

![screenshot8](https://cloud.githubusercontent.com/assets/408368/11115074/5cf783e8-8929-11e5-896f-79fb4c0af13a.png)

If I inspect the HTML, I can see this (manually indented):
```html
<form name="foo" method="post" action="">
    <div id="foo">
        <div>
            <label for="foo_enabled" class="required">Enabled</label>
            <input type="checkbox" id="foo_enabled" name="foo[enabled]" required="required" value="1" />
        </div>
        <div>
            <label for="foo_name" class="required">Name</label>
            <input type="text" id="foo_name" name="foo[name]" required="required" />
        </div>
        <input type="hidden" id="foo__token" name="foo[_token]" value="_Y4JKjDkfmIaaiAmtoOWDz6QQDpHLy0La2dtbzue2Q4" />
    </div>
</form>
```

First you can note the `value="1"` in the checkbox input.
Then, there is no value for the name.

I tried few symfony version from v2.6.3 to 2.7.6, it's always the same things.

So I tried to use [`empty_data`](https://github.com/lyrixx/symfony-standard/commit/3fa879885a5423da29052da1fef5ce21e8b0ab8a) => same result.

So, again, I tried to lower symfony requirement => same result for symfony 2.6.3

So I finally tried [symfony 2.3](https://github.com/lyrixx/symfony-standard/commit/fe17ba06c15c58726fd4a05bbd04a0ce07e56f7f) => and again, same result.

---

So, It could be nice to use the `empty_data` option to populate the form

**Comment by Richtermeister** [comment] 2015-11-15 18:15
Have you tried setting an instance of your entity as data for the form? That should definitely populate the defaults. I also ran into some issues with the empty_data option, but I usually accomplish everything I want from forms without that option. Give data a try.

**Comment by lyrixx** [comment] 2015-11-15 18:18
> Have you tried setting an instance of your entity as data for the form?

yes, and it works. but it's not related to the current issue ;)

**Comment by Richtermeister** [comment] 2015-11-15 18:38
In any way the empty_data option is not designed to populate the form default. It is supposed to be the value you want when the form is submitted empty.

**Comment by ogizanagi** [comment] 2015-11-15 18:44
> In any way the empty_data option is not designed to populate the form default. It is supposed to be the value you want when the form is submitted empty.

Exactly, but still, the `empty_data` value is not propagated to subfields, so what is mentioned [in the cookbook](http://symfony.com/doc/current/cookbook/form/use_empty_data.html) is wrong or misunderstood, because in this example, the `empty_data` of the `checkbox` and `text` fields are respectively `false` and an empty string, which will override the properties [of the `Foo` instance here](https://github.com/lyrixx/symfony-standard/commit/3fa879885a5423da29052da1fef5ce21e8b0ab8a).

**Comment by lyrixx** [comment] 2015-11-15 18:44
> In any way the empty_data option is not designed to populate the form default.

I know, but IMHO it should be.

**Comment by Richtermeister** [comment] 2015-11-15 18:59
Yes, I agree the empty_data option does not seem to work. I actually ran into this yesterday myself, which is how I found this issue. I just wanted to separate the discussion of this from setting default values on the form, because I think this is unrelated.

**Comment by yceruto** [comment] 2015-11-16 03:14
@lyrixx I proposed some time ago, create an option for the default value of the form fields: [issue #15334](https://github.com/symfony/symfony/issues/15334)

**Comment by yceruto** [comment] 2015-11-16 03:25
generally in these cases it's recommended setting the default value in the underlying object before binding the form (you can use arrays as underlying object). This way, there would be no need for anything special. ([comment](https://github.com/symfony/symfony/issues/15334#issuecomment-123747626))

**Comment by yceruto** [comment] 2015-11-16 03:59
@lyrixx however you can create a [form type extension](http://symfony.com/doc/current/cookbook/form/create_form_type_extension.html) to add `default` option for all form fields: [See example](https://gist.github.com/yceruto/8ad6eaa315b03b7a9f13)

So your form type will look like this:
```php
$builder
    ->add('enabled', 'checkbox', array('default' => true))
    ->add('name', 'text', array('default' => 'greg')) ;
```

**Comment by yceruto** [comment] 2015-11-16 07:27
@ogizanagi The part which can confuse in [cookbook](http://symfony.com/doc/current/cookbook/form/use_empty_data.html) is when they mention that `empty_data is used to get the "starting data"`:
```php
    // no data is passed in, so empty_data is
    // used to get the "starting data"
    $form = $this->createForm(new BlogType());
```
Because this empty data set would **be used if you submit your form** only, so never will display this data set, because never will assigned to the form data.

**Comment by ogizanagi** [comment] 2015-11-16 11:55
@yceruto : This is actually confusing, but this is not what I'm pointing in https://github.com/symfony/symfony/issues/16530#issuecomment-156842539. :/

**Comment by HeahDude** [comment] 2016-02-11 09:15
`data` option replaces the default `null` for populating field, so it's mapped to the view.
`empty_data` is only mapped if there was no submitted data so it cannot reach the view.

About `value="1"`, this is just the default in `CheckboxType` see [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/CheckboxType.php#L59).

This is an expected behaviour IMO, this issue should be closed and maybe adressed to the doc.

Status: Reviewed

**Comment by jakzal** [comment] 2016-02-11 11:59
Thanks for looking into this @HeahDude! Care to submit a PR to the docs?

**Closed by jakzal** 2016-02-11 11:59 UTC
Labels: Bug, Form, Status: Reviewed

**Comment by HeahDude** [comment] 2016-02-11 15:12
@jakzal sure, I take a look.

**Comment by aheitzm2** [comment] 2020-05-02 20:15
Try this (in your FormType file) :
->add('myField', NumberType::class,[
                'empty_data'=>1, //not required
                'attr'=>[
                    'value'=>1
                ]
            ])
