### ISSUE TITLE
[PropertyInfo] PHPDoc nullable property for "array type" not accounted

### ISSUE THREAD

**Issue by cyqui** [symfony/symfony#22203] opened 2017-03-28 14:35 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

**Description:**
I am using the PropertyInfo component to read phpdoc comments.
Somewhere we got : 

```
    /**
     * Array of categories IDs
     * @var array|null
     * @SWG\Property(@SWG\Items(type="string"))
     */
```

and in our code $type->isNullable() returns "false". 
$type is a Symfony\Component\PropertyInfo\Type instance.

**Fix:**
https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L107
The "nullable" argument should be used here i believe ? 

I can provide a pull request to fix this if you agree that it is an issue (not sure if the argument is unused on purpose here ..)

**Comment by xabbuh** [comment] 2017-04-05 08:47
Thanks for reporting. Closing here as a duplicate of #22248 which was fixed by #22251.

**Closed by xabbuh** 2017-04-05 08:47 UTC
Labels: Bug, PropertyInfo, Status: Needs Review
