### ISSUE TITLE
polyfill-mbstring uses php 7.4 syntax while it supports >7.1

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#39766] opened 2021-01-08 16:02 UTC
polyfill-mbstring uses php 7.4 syntax while it supports >7.1. Currently a 7.3 version doesn't run on v1.22.0 because of `??=`

https://github.com/symfony/polyfill-mbstring/blob/main/bootstrap80.php#L125

**Comment by derrabus** [comment] 2021-01-08 16:05
Duplicate of symfony/polyfill#326

**Closed as completed by derrabus** 2021-01-08 16:05 UTC
Labels: Bug, Status: Needs Review
