### ISSUE TITLE
Asset Mapper throw exception during the rendering of a template

### ISSUE THREAD

**Issue by makraz** [symfony/symfony#54094] opened 2024-02-27 18:10 UTC
### Symfony version(s) affected

6.4.4

### Description

after updating Asset mapper from 6.4.3 to 6.4.4, I start seeing this error
I think is related to this PR [#54014](https://github.com/symfony/symfony/pull/54014)

<img width="1100" alt="image" src="https://github.com/symfony/symfony/assets/19323431/6d63b990-0ed1-46e0-bc4d-ff30e545d330">

### How to reproduce

- create a new Symfony project version 6.4.3 with asset mapper same version 
- update the asset mapper to 6.4.4

### Additional Context

PHP: 8.3
dev env using Symfony binary

**Comment by xaviermarchegay** [comment] 2024-02-27 19:10
Duplicate of https://github.com/symfony/symfony/issues/54078

**Closed as not planned** 2024-02-28 02:56 UTC
Labels: Bug, Status: Needs Review, AssetMapper
