### ISSUE TITLE
[DependencyInjection][3.4] Call to undefined method ContainerBuilder::isCompiled()

### ISSUE THREAD

**Issue by alexdu98** [symfony/symfony#25243] opened 2017-12-01 11:38 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

Hello,
After update from 3.2 to 3.4 I have this error in production environment but not in dev :

`PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\DependencyInjection\\ContainerBuilder::isCompiled() in /var/www/ambiguss/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:982`

So, I downgrade to 3.3 and error is fix.

**Comment by xabbuh** [comment] 2017-12-01 12:01
The method is still there: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DependencyInjection/Container.php#L93-L96

Can you provide some steps that allow to reproduce your issue?

**Comment by alexdu98** [comment] 2017-12-01 15:26
I think it's my fault. I have retry and I don't have this mistake anymore.
But I still have error 500, but nothing in the apache logs or symfony logs, it's strange.

**Comment by xabbuh** [comment] 2017-12-01 15:28
Thanks for response. Closing for now then.

**Closed by xabbuh** 2017-12-01 15:28 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by ShapesGraphicStudio** [comment] 2017-12-06 14:33
Hello,
I'm having the same issue.

I upgraded from 3.2.x to 3.3.x to 3.4.1 : 
`Fatal error: Uncaught Error: Call to undefined method Symfony\Component\DependencyInjection\ContainerBuilder::isCompiled() in /home/user/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:981 Stack trace: #0 /home/user/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(132): Symfony\Component\DependencyInjection\ContainerBuilder->setDefinition('service_contain...', Object(Symfony\Component\DependencyInjection\Definition)) #1 /home/user/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(806): Symfony\Component\DependencyInjection\ContainerBuilder->__construct() #2 /home/user/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(758): Symfony\Component\HttpKernel\Kernel->getContainerBuilder() #3 /home/user/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(632): Symfony\Component\HttpKernel\Kernel->buildContainer() #4 /home/user/www/vendor/symfony/symfony/ in /home/user/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 981`

Tried to downgrade to 3.3.x but got stuck on error 500 : 
`request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The first argument of Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory::__construct() is required on Symfony 3.3 or higher." at /home/user/www/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 44 {"exception":"[object] (InvalidArgumentException(code: 0): The first argument of Doctrine\\Bundle\\DoctrineBundle\\Repository\\ContainerRepositoryFactory::__construct() is required on Symfony 3.3 or higher. at /home/user/www/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:44)"} []`

**Comment by alexdu98** [comment] 2017-12-06 22:02
Hello @ShapesGraphicStudio ,
I think it's a cache issue.

I executed an rm -rf var/cache/ followed by clear:cache --env=prod after updating project to Symfony 3.4.1 and now it's working.

**Comment by ShapesGraphicStudio** [comment] 2017-12-07 08:07
Hi @alexdu98,
Yes indeed, first I thought the upgrade was clearing the cache, I retried and cleared the whole cache manually after each upgrade, it works fine now.
Thank you

**Comment by XenoX** [comment] 2018-03-19 10:13
I had the same issue, i just deleted the old file `app/bootstrap.php.cache` and it's works for me.
