### ISSUE TITLE
Logout Url Generator does not check if the request exists

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#47838] opened 2022-10-11 21:39 UTC
### Symfony version(s) affected

6.x, 5.x

### Description

When the `$request = $this->requestStack->getCurrentRequest();` [here](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Security/Http/Logout/LogoutUrlGenerator.php#L95) returns null. Nothing checks that an actual request was returned. I get a crash on `Call to a member function getBaseUrl() on null`.

### How to reproduce

This is complicated. I don't know why sometimes when there's an error, symfony tries to log me out. In this case, we had a form with the following form code that I simplified to the absolute minimum:

```
'choice_label'  => static function (?MortgageDocument $choice) {
      if (!$choice) {
          return $choice;
      }

     // getProvider() returns a nullable object ?MortgageProvider.
      $provider = $choice->getProvider();
       return sprintf('%s - %s (%s)', $provider->getName(), $choice->getDescriptiveName(), $choice->getCreatedAt()->format('Y-m-d'));
            },
```

When this executes where the ->getProvider() returned null then we get the following stacktrace

```
Error:
Call to a member function getBaseUrl() on null

  at /var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:104
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->generateLogoutUrl()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:65)
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->getLogoutPath()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/security-bundle/DataCollector/SecurityDataCollector.php:122)
  at Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector->collect()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/Profiler/Profiler.php:161)
  at Symfony\Component\HttpKernel\Profiler\Profiler->collect()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/EventListener/ProfilerListener.php:108)
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/HttpKernel.php:186)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/HttpKernel.php:239)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/HttpKernel.php:109)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:131)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}()
     (/var/www/vhosts/project/releases/20221011204941Z/vendor/symfony/error-handler/ErrorHandler.php:608)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException()
```

### Possible Solution

I could submit a PR but I'm not sure what to do when $request is null... what should be returned?

**Comment by wouterj** [comment] 2022-10-11 23:10
This is a duplicate of #47577 

Are you maybe willing to take a deeper look into the real issue (the request being null while collecting data for the profiler). Someone else did wrote a bit more details about this in https://github.com/symfony/symfony/issues/47405#issuecomment-1236095745

**Closed as completed by wouterj** 2022-10-11 23:10 UTC
Labels: Bug, Status: Needs Review

**Comment by gnat42** [comment] 2022-10-12 01:18
I can take a look... What I wonder about is what `Response` object can we return when the `handleThrowable` throws an exception?
