### ISSUE TITLE
[Routing] Get all matched routes (add method which not stops on the first matched candidate)

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#10113] opened 2014-01-23 16:01 UTC
I'm using Symfony-CMF RoutingBundle with NestedMatcher http://symfony.com/doc/master/cmf/components/routing/nested_matcher.html . And for the route provider / route filter I should get all matched routes. Now it is not possible, I've copypasted bunch of code from `UrlMatcher` class.

**Comment by TomasVotruba** [comment] 2016-02-29 00:39
@Koc Could you send PR for this feature?

**Comment by nicolas-grekas** [comment] 2018-02-23 16:08
I'm closing here because the issue is old and no implementation has been provided yet.
Feel free to submit a PR of course.

**Closed by nicolas-grekas** 2018-02-23 16:08 UTC
Labels: Feature, Routing
