### ISSUE TITLE
[Console] Command::isEnabled not checked for Commands with defaultName and defaultDescription

### ISSUE THREAD

**Issue by Khartir** [symfony/symfony#46237] opened 2022-05-03 12:15 UTC
### Symfony version(s) affected

5.4

### Description

A command that defines both the `static $defaultName` and `static $defaultDescription` never checks `isEnabled`.

### How to reproduce

Add the following command:
```php
<?php declare(strict_types=1);

namespace App\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    protected static $defaultName = 'testcommand';
    protected static $defaultDescription = 'dummy';

    public function __construct()
    {
        parent::__construct('testcommand');
    }

    public function isEnabled(): bool
    {
        return false;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return self::SUCCESS;
    }
}
```
Then run `bin/console testcommand`. The command runs successfully (which should not happen). If either the definition for `$defaultName` or `$defaultDescription` is removed, the command is not executed.

**Comment by xabbuh** [comment] 2022-05-05 12:16
Can you create a small example application that allows to reproduce your issue?

**Comment by Khartir** [comment] 2022-05-05 12:23
Sure: https://github.com/Khartir/phpstan-symfony-di-helper-reproduction/tree/symfony-46237

Btw. `bin/console list` also lists the disabled command.

**Comment by xabbuh** [comment] 2022-05-05 12:40
This seems to be an issue for all lazy commands.

Status: Reviewed

**Comment by nicolas-grekas** [comment] 2022-05-05 12:45
There's nothing we can do here: since `isEnabled()` needs a runtime check, it's fundamentally incompatible with using non-instantiable info to describe the name+description (either via static props or attributes).

You need to fallback to dynamic description of the command, via the constructor and/or the configure() methods.

**Comment by Khartir** [comment] 2022-05-05 13:12
How about at least checking this when the command is called and throwing then? This would at least ensure that the command is not executed, when it is not enabled.

> You need to fallback to dynamic description of the command, via the constructor and/or the configure() methods.

Yes, that's the workaround we are currently implementing. It's quite brittle though. As soon as a new command is added by someone not aware of this issue, it could occur again.

**Comment by chalasr** [comment] 2022-05-17 13:04
That sounds doable. Would you mind submitting a PR?

**Comment by jdevinemt** [comment] 2022-05-18 20:04
The same issue exists for hidden commands. If setting hidden to true in a command's configure() method, it will still show up in the command list if the $defaultDescription static property is set.

I'm not quite sure why this is the case, as there is no issue with the name being assigned via the $defaultName static property.

**Comment by nicolas-grekas** [comment] 2022-05-23 12:21
For my understanding, what is the criteria that makes your commands enabled/disabled? Is it the Symfony env? What else otherwise?

**Comment by Khartir** [comment] 2022-05-24 05:37
I only use the env, yes.

**Comment by nicolas-grekas** [comment] 2022-05-24 06:49
Great. Then I think you might want to know about the [`#[When]`](https://symfony.com/doc/current/service_container.html#limiting-services-to-a-specific-symfony-environment) attribute, which allows doing that without playing with the `isEnabled()` method.
If you don't use PHP8 yet, then I'd recommend loading the command declaration only for the envs you target. You can use [`when@the-env:`](https://symfony.com/doc/current/configuration.html#configuration-environments) sections to do so.

`isEnabled()` is not compatible with lazy commands unfortunately, and there is no way around since the point of lazy commands is to *not* instantiate them to still know how to register them. Calling a method breaks that.

I'm thus closing as won't fix. Please try my suggestions above instead.

**Closed as completed by nicolas-grekas** 2022-05-24 06:49 UTC
Labels: Bug, Console, Status: Reviewed
