### ISSUE TITLE
[Dependency Injection - Profiler] Wrong exception throwed when a service class doesn't exist

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#15297] opened 2015-07-16 16:33 UTC
I had an error in a yaml service container.
The class was wrong.

But the error that occurs is "cannot redeclare class ..." instead of a not found exception.

**Comment by weaverryan** [comment] 2015-07-16 17:51
@Alsatian67 can you post some code that can be used to reproduce the bad exception?

**Comment by Alsatian67** [comment] 2015-07-16 19:39
Sorry, the problem occurs when the namespace is wrong in the class !

example :
```
<?php
// Real location : AppBundle\Security
namespace AppBundle\Security\Voters; // <- Here the namespace is wrong.

use Symfony\Component\Security\Core\Authorization\Voter\AbstractVoter;
use Symfony\Component\Security\Core\User\UserInterface;

class AdminMembersVoter extends AbstractVoter
{
	const ADMIN_MEMBER_EDIT = 'admin_member_edit';

    protected function getSupportedAttributes()
    {
        return array(ADMIN_MEMBER_EDIT);
    }

    protected function getSupportedClasses()
    {
        return array('AppBundle\Entity\Members');
    }

    protected function isGranted($attribute,$member,$user=null)
    {
        if (!$user instanceof UserInterface) {
            return false;
        }

        switch($attribute) {
			case self::ADMIN_MEMBER_EDIT:
				if($user === $member){return false;}
				$rolesMember = $member->getRoles();
				$rolesUser = $user->getRoles();
				if(in_array('ROLE_SUPER_ADMIN',$rolesMember)){return false;}
				if(in_array('ROLE_ADMIN',$rolesMember) && !in_array('ROLE_SUPER_ADMIN',$rolesUser)){return false;}
				if(in_array('ROLE_ADMIN',$rolesUser)){return true;}
				
                break;
		}
		
        return false;
    }
}
```

With that services.yml :
```
services:
    voters.admin_member:
        class:      AppBundle\Security\AdminMembersVoter
        public:     false
        tags:
           - { name: security.voter }
```

Not a big bug since my class was wrong, but the exception made me search for an eventual double ...

**Comment by qferr** [comment] 2015-07-17 07:13
You must respected [PSR-4](http://www.php-fig.org/psr/psr-4/):

> The contiguous sub-namespace names after the "namespace prefix" correspond to a subdirectory within a "base directory", in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names.

So your namespace should be `AppBundle\Security` whether the file location is `AppBundle\Security` or moves your file in the new directory named `Voters` in `AppBundle\Security`.

**Comment by stof** [comment] 2015-07-17 08:13
@Alsatian67 the issue will happen because the class loader will load the file, and then try again the next time it is asked to load the class, as the first load will not have defined the class.

And this case is not one which is detected by the DebugClassLoader /cc @nicolas-grekas

**Comment by Alsatian67** [comment] 2015-07-17 08:45
Ok it would be nice if the autoloader throws an exception :

The autoloader expected class "AppBundle\Security\AdminMembersVoter" to be defined in file AppBundle\Security\AdminMembersVoter.php". The file was found but ...

When it load the file for the first time.

**Comment by stof** [comment] 2015-07-17 08:47
Well, actually, it should.

which Symfony version are you using ?

**Comment by stof** [comment] 2015-07-17 08:50
and do you have the debug class loader enabled ? (i.e. to you have the ``Debug::enable()`` call in your front controller as in https://github.com/symfony/symfony-standard/blob/v2.7.2/web/app_dev.php#L21 ?)

**Comment by Alsatian67** [comment] 2015-07-18 09:42
I'm using Sf 2.7.1 and the debug is enabled.

I just have seen that this wrong file produce the same invalid exception (here the class name is not like the file name [missing s]) : 

```
<?php
// src/AppBundle/Entity/Partners/Comments.php
namespace AppBundle\Entity\Partners;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Comment
 *
 * @ORM\Table
 * @ORM\Entity
 */
class Comment
{
...
}
```

**Comment by iltar** [comment] 2015-07-19 12:14
I can confirm this issue is real as I experienced it myself, sadly don't remember which version nor the code that triggered it.

**Comment by trq** [comment] 2015-09-02 11:17
I can confirm a FatalErrorException

```
FatalErrorException in AdminMembersVoter.php line 42:
Compile Error: Cannot redeclare class AppBundle\Security\Voters\AdminMembersVoter
```

Reproduced [here](https://github.com/trq/symfony-standard/tree/issue-15297) using Symfony Standard , branch created from 2.7.

Status: Reviewed

**Comment by nicolas-grekas** [comment] 2015-11-24 11:58
See #16651
The DebugClassLoader IS able to detect such mistakes, but the exception that is thrown is catched and a class loading happens again, boom. Fixed by using require_once instead of require.

**Closed** 2015-11-24 13:16 UTC
Labels: Bug, Debug, Status: Reviewed
