### ISSUE TITLE
HttpClient reverts to Syncronous Request

### ISSUE THREAD

**Issue by astorm** [symfony/symfony#35475] opened 2020-01-25 21:20 UTC
**Symfony version(s) affected**: symfony/http-client:~4.3 and symfony/http-client:~5

**Description**  

If an end-user-programmer fails to store the results of a call to `request` in a variable, the HTTPClient reverts to making a synchronous request. 

**How to reproduce**  

Create the following program

    <?php
    namespace Pulsestorm\Tutorials\AsyncPhp;
    use Symfony\Component\HttpClient\HttpClient;
    require 'vendor/autoload.php';

    function main($argv, $httpClient) {
        echo "About to make the request","\n";

        $httpClient->request('GET', 'http://magento-2-3-x.localhost/sleep.php');

        // do this and the request behaves async
        // i.e. assigning the response to a variable
        // seems to prevent garbage collection, it
        // it seems like garbage collecting the object
        // forces the requests to finish right away, and
        // finish syncronously
        // $response = $httpClient->request('GET', 'http://magento-2-3-x.localhost/sleep.php');
        echo "Made the request!","\n";
        echo "...","\n";
    }
    main($argv, HttpClient::create());

and then run that program

    $ composer require symfony/http-client:~5
    $ php working.php
    About to make the request
    Made the request!
    ...

Expected Behavior: Program pauses after printing out `...`, indicating an asynchronous request

Actual Behavior: Program pauses after printing out `About to make the request`, indicating a synchronous request. 

**Possible Solution**  
Heck if I know -- I presume the object's being garbage collected and that makes the response say "oh dear, better finish those requests".  If you had some black magic to block the response object's being garbage collected until the end that might work -- but if I had a solution I'd be making a PR :)

**Additional context**  
Ran into this when I wanted to do a bunch of fire and forget HTTP requests where I didn't care about processing the results.

**Comment by nicolas-grekas** [comment] 2020-01-25 23:36
On the other hand, once you understand the behavior you describe, the improvement is know: store the responses in an array and when the array will be destructed, all responses will complete in parallel. That's good enough to me, no need to add more special behavior, ppl have do to some homework at some point.

**Comment by nicolas-grekas** [comment] 2020-02-02 17:34
Closing as this is the expected behavior, the solution is on the user's side, as explained in the previous comment.

**Closed by nicolas-grekas** 2020-02-02 17:34 UTC
Labels: Bug, HttpClient, Status: Needs Review

**Comment by astorm** [comment] 2020-02-03 15:31
@nicolas-grekas Ultimately this isn't my project so it's not my call and I'll leave it here, but I'm not sure _expected behavior_ is the right reason to close this.  

Expecting an end user of the `HttpClient` to be aware of the client's implementation _and_ aware of the life-cycle of the PHP garbage collector _and_ aware how the two will interact seems to be asking a lot.  For folks like you and I, sure, maybe this is expected-once-we-get-over-our-initial-surprise, but from an API or library design perspective the idea that storing a return value will change the behavior of the underlying library seems -- non-optimal and certainly not expected. 

If you want to close because _the effort to investigate a fix would be large and might not pay off_ -- that's fair, but labeling something this strange as expected seems unkind to the majority of programmers who might need this library.

**Comment by nicolas-grekas** [comment] 2020-02-03 15:35
I get your point, but there is no better alternative. All alternatives are worse actually (eg auto-canceling/ignoring responses)

**Comment by B-Galati** [comment] 2020-02-08 09:54
@nicolas-grekas @astorm Thanks to both of you for these informations :-)

I will try to make a PR on the doc to make this more clear because I just had a big WTF moment when trying out the async behavior of the HttpClient.
