### ISSUE TITLE
[DX] Enhance error when a `use` is missing

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#28905] opened 2018-10-17 13:24 UTC
**Description**  
I would like to enhance DX when theses errors occur:

> (1/1) RuntimeException
> Cannot autowire service "App\Controller\Api\TopicController": argument "$validator" of method "__construct()" has type "App\Controller\Api\ValidatorInterface" but this class was not found.

or 

>(1/1) InvalidArgumentExceptionCannot determine controller argument for "App\Controller\Api\TopicController::new()": the $request argument is type-hinted with the non-existent class or interface: "App\Controller\Api\Request". Did you forget to add a use statement?

or ...

---
 
We coul instead put in **bold** something like:

> We think you should add `use Symfony\Component\HttpFoundation\Request;` in the file `src/Foo/bar.php`

---

I really think this would be really useful. So many people fall into theses issues during training and stray blocked :/

**Comment by stof** [comment] 2018-10-17 13:30
The question is, how do we know which class to suggest ? That's the hard part of this suggestion. We all agree that it would be a better error message, but we need to be able to know which class to suggest.

**Comment by lyrixx** [comment] 2018-10-17 13:33
Some ideas:

1. Search dynamically for service that have the same class name (without the namespace)
1. Add a static list of common class (Request, Response,...)
1. Search for potential class and list them all

**Comment by stof** [comment] 2018-10-17 13:43
The DebugClassLoader cannot search for services. The autoloader does not have access to the container (and giving it such access would be a nightmare to avoid memory leaks, and also to account for the fact that the autoloader is also used during the building of the container).
And how do you search for potential classes ? PHP only allows you to list the declared classes, i.e. the ones which have already been loaded in the process. There is no way to list all classes that your autoloader *could* load.

So in your ideas, I only see the second one as doable (but then, it is a pain to maintain, and only works for core classes)

**Comment by stof** [comment] 2018-10-22 13:51
hmm, in the case of autowiring errors, the AutowiringPass may inspect the service to implement 1. though.

**Comment by lyrixx** [comment] 2018-10-22 15:16
But even if there is no service associated with a class, we could propose a use, isn't it ?

**Comment by stof** [comment] 2018-10-22 15:40
The issue is still the same: how do you know about the class ?

**Comment by lyrixx** [comment] 2018-10-25 09:34
we could simply search for all class in project that have the same class name and propose each FQCN

**Comment by xabbuh** [comment] 2018-10-25 10:07
But you can only reliably get the names of already loaded classes. So chances are that you just cannot propose the right class name as this class wasn't autoloaded before.

**Comment by stof** [comment] 2018-10-25 10:48
@lyrixx you always cam back to the same issue: how do you know "all classes" ?

**Comment by javiereguiluz** [comment] 2019-02-07 15:49
Let's close this because it looks like a "dead end". The idea is very nice, but the implementation seems "impossible". Thanks.

**Closed by javiereguiluz** 2019-02-07 15:49 UTC
Labels: DX, Debug
