### ISSUE TITLE
[Console] Throwable exceptions not handled properly, exit code is 0

### ISSUE THREAD

**Issue by fredplante** [symfony/symfony#20775] opened 2016-12-06 09:51 UTC
Given an new symfony 3.2 project, with this simple Command :

```php
<?php
namespace AppBundle\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DemoCommand extends Command
{
    protected function configure()
    {
      $this->setName('app:demo');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
      $input->checkYourself();
    }
}
```

Running under PHP 5.6.24 :
```
bin/console app:demo
[output an UndefinedMethodException]
echo $?
255
```

Running under PHP 7.0.8 :
```
bin/console app:demo
[output an UndefinedMethodException]
echo $?
0
```

**Comment by ogizanagi** [comment] 2016-12-06 16:59
I can confirm the issue.

The thing is in PHP 5, errors were thrown in the wild and handled by the error handler. The status code then is 255. But in PHP 7, those errors are in fact `\Error` exceptions handled by the error handler. The native one will exit with a 255 status code, but using the fullstack framework, the `DebugHandlersListener` is registered and replace it in order to output the error in a user friendly way in the console. 

A solution could be to use `exit(255)` either in [`DebugHandlersListener` when setting `$this->exceptionHandler`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php#L113) or for any handled exception in [`ErrorHandler`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ErrorHandler.php#L553). But I'm not entirely sure this is the right solution.

Status: Reviewed

**Comment by jstuhli** [comment] 2016-12-08 11:53
Also confirming the issue. It's impossible to rely on status code to determine if the console application exited properly. 
This breaks many queueing libraries using workers that fork before doing the job, and inspect the childs status code in order to determine if the job was successful.

**Comment by fabpot** [comment] 2017-03-22 18:16
fixed

**Comment by ogizanagi** [comment] 2017-03-22 22:15
@fabpot: I'm still able to reproduce the issue on master (maybe its not merged in upper branches yet?) & PHP 7.1 😕 

On https://github.com/symfony/symfony/pull/20797, you said it worked fine on your side now. Were you using PHP 7+? Were you only using the standalone console component when you gave a try, or the full stack framework? Which PR is supposed to fix this issue actually?

**Comment by fabpot** [comment] 2017-03-22 22:16
I have PHP7.2.1. I used the component only.

**Comment by ogizanagi** [comment] 2017-03-22 22:24
AFAIK, the issue mainly exists when using the framework (due to the Debug component and DebugHandlersListener).
Using the component standalone, you'll get a non 0 exit code, as expected.
That's why I tried to fix, more or less clumsily in #20797, by re-throwing the error to be handled by the native handler, which will produce a 255 exit code.

**Comment by nicolas-grekas** [comment] 2017-04-13 20:07
Fixed in #22424

**Closed** 2017-04-13 22:15 UTC
Labels: Bug, Console, Status: Reviewed

**Comment by aalwash** [comment] 2017-05-02 10:43
I see this fix is been merged to 2.7 branch, but what about 3.2?

**Comment by nicolas-grekas** [comment] 2017-05-02 10:44
We merge in the lowest branch where a bug occurs, then we merge that branch into higher branches, so that they have the fixes too.

**Comment by aalwash** [comment] 2017-05-02 10:47
Oke, didn't know that :)

And in which timeframe do I have to think when the merge is done to higher branches?

**Comment by nicolas-grekas** [comment] 2017-05-02 10:49
A week or less usually for the merge, and a new version is tagged every month.

**Comment by xabbuh** [comment] 2017-05-02 11:08
@aalwash This was by the way part of the [3.2.8 release](https://github.com/symfony/symfony/releases/tag/v3.2.8) that was published yesterday.

**Comment by aalwash** [comment] 2017-05-02 12:51
@xabbuh thanks, didn't notice it was inside that release.
Tested it and it works  👍
