### ISSUE TITLE
Valid Constraints multiple groups apply only on one

### ISSUE THREAD

**Issue by gregoirepaqueron** [symfony/symfony#27257] opened 2018-05-14 09:51 UTC
**Symfony version(s) affected**: 3.4.8

I have a parent Entity with many childrens Entities. I have 2 groups of validations `Default` and `final`.
The goal is to use only the group `Default` through a non-restrictive form, in order to valid the integrity of datum sent, then on the last page, display all the errors message more restrictive, with combining the 2 groups.
When i'm trying to validate on the 2 groups, i'm adding the 2 groups to `Valid()` constraint, but only 1 is applied.

Exemple :

`Mandate.php`
```php
    /**
     * @var Customer[]|Collection
     * @Assert\Count(min="1", groups={"final"})
     * @Assert\Valid(groups={"Default", "final"})
     * @ORM\OneToMany(targetEntity="Customer", mappedBy="mandate", cascade={"persist", "remove"})
     */
    protected $customers;
```
`Customer.php`
```php
    /**
     * @var string
     * @Assert\Length(max=80)
     * @Assert\Email()
     * @Assert\NotBlank(groups={"final"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $email;

    /**
     * @var string
     * @Assert\Length(max=40)
     * @Assert\NotBlank(groups={"final"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $firstName;
```

`CustomerController.php`
```php
    /**
     * @param ValidatorInterface $validator
     * @param Mandate $mandate
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function summaryAction(ValidatorInterface $validator, Mandate $mandate)
    {
        $errors = $validator->validate($mandate, null, ['Default', 'final']);
        ...
    }
```
I forced in database that `$firstName = null` and `$email = "notvalidemail"`
In the `$errors` list, i will find only that the email is incorrect, but not that the firstname should be not null.
So, only the group `Default` is applied.

**Comment by HeahDude** [comment] 2018-05-14 10:03
Hello @gregoirepaqueron, thank you for reporting this issue.
AFAICS It could be a bug, in the meantime using:
```php
/**
     * @var Customer[]|Collection
     * @Assert\Count(min="1", groups={"final"})
     * @Assert\Valid(groups={"Customer", "final"})
     * @ORM\OneToMany(targetEntity="Customer", mappedBy="mandate", cascade={"persist", "remove"})
     */
    protected $customers;
```
may fix your issue.

**Comment by HeahDude** [comment] 2018-05-14 12:15
Of course you need to add the `Customer` group to the `validate` method too, so passing three groups: `['Default', 'Customer', 'final']`.

The reason is that `Valid` is a composite constraint and the default group of `Customer` is not a subset of the default group aliasing `Mandate` in your case.

I don't know if we really want to support the case though, maybe we could better document it.

ping @xabbuh

**Comment by xabbuh** [comment] 2018-05-14 12:46
Without diving into this very much it seems to me that this issue is caused by the same cache mechanism that also causes #17675 and #26205.

**Comment by HeahDude** [comment] 2018-08-04 18:50
No the problem comes from the `Valid` constraint using groups on the doctrine collection not on the entities it contains because the collection does not have constraints, nor groups.
To use groups on a collection, you should either use `All` or `Collection` constraints but they cannot contain `Valid`.
If you want to use `Valid` to validate nested entities in a "model" collection just define validation groups in the nested class or its properties and they will be used as they always have been.
To use groups with `Valid` it must be a nested entity, not an entity nested in a class you do not configure (i.e a doctrine collection), so in a doctrine entity context either a `OneToOne` or a `ManyToOne` property.

**Comment by xabbuh** [comment] 2018-09-24 10:40
Indeed, I missed the point that the `$customers` is a collection object. I agree with @HeahDude that we should rather improve the documentation for this. Thus, I am closing here.

**Closed by xabbuh** 2018-09-24 10:40 UTC
Labels: Bug, Status: Needs Review, Validator
