### ISSUE TITLE
_instanceof overriding services definitions

### ISSUE THREAD

**Issue by pejkosz94** [symfony/symfony#37699] opened 2020-07-29 12:33 UTC
**Symfony version(s) affected**: 4.4.10

**Description**  
Services from `services.yaml::_instanceof` (main file) are taken. Services from `services_A.yaml::_instanceof` are overrode (in this case totally deleted, because only last values are taken).

**How to reproduce**  
Structure:
```
--services/
----services_module_A.yaml
--services.yaml
--services_test.yaml
```
Register all services from `service` directory in `Kernel.php` with code:
```
        $loader->load($confDir . '/{packages}/*' . self::CONFIG_EXTS, 'glob');
        $loader->load($confDir . '/{packages}/' . $this->environment . '/**/*' . self::CONFIG_EXTS, 'glob');
        $loader->load($confDir . '/{services}' . self::CONFIG_EXTS, 'glob');
[register-->]  $loader->load($confDir . '/services/*' . self::CONFIG_EXTS, 'glob'); [<---register] 
        $loader->load($confDir . '/{services}_' . $this->environment . self::CONFIG_EXTS, 'glob');
```

services_module_A.yaml:
```
services:
    _instanceof:
        App\ModuleA\ModuleAService:
            tags: ['tag.module_a_service']
```

services.yaml: (main one)
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            int $tokenTtl: '%env(int:tokenTtl)%'
    _instanceof:
        App\Shared\SharedService:
            tags: ['tag.shared_service']

    App\:
        resource: '../src/*'
        exclude: '../src/**/{DependencyInjection,DataFixtures,Entity,Migrations,Tests,Kernel.php}'
```

**Possible Solution**  
Services from `_instanceof` section from all services files should be merged to one final array of services.

**Additional context**

**Comment by stof** [comment] 2020-07-29 13:42
`_instanceof` applies only to services defined in the same file. That's by design of the feature. So there is no merging to be done.

Btw, your reproducer is probably incomplete, as it defines no services at all.

**Comment by pejkosz94** [comment] 2020-07-30 06:34
@stof fixed reproducer - services are registered in services.yaml (main file).

**Comment by stof** [comment] 2020-07-30 07:57
This is it totally expected that only the `_instanceof` of that services.yaml file apply to them.

**Comment by pejkosz94** [comment] 2020-07-30 08:12
Is there any way to make it work as I expecting it? That both `_instanceof` will be working?

Right now I had to move 
```
        App\ModuleA\ModuleAService:
            tags: ['tag.module_a_service']
```
from `services_module_A.yaml::_instanceof` to `services.yaml::_instanceof` to made it work.

**Comment by nicolas-grekas** [comment] 2020-07-30 08:16
I'm closing because this is a support request and we use the issue tracker for bugs. Please connect to e.g. Slack for further help.
You might want to have a look at autoconfiguration, especially the Container builder::registerForAutoconfiguration method that you can use in the DI extension of a bundle.

**Closed by nicolas-grekas** 2020-07-30 08:16 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
