### ISSUE TITLE
[Form] expanded choice type doesn’t correctly populate boolean false value

### ISSUE THREAD

**Issue by samhastings** [symfony/symfony#16401] opened 2015-10-30 21:00 UTC
Symfony choice fields with `expanded` set to `true` don’t render the selected option correctly when the value in the underlying entity is `false`.

This affects Symfony 2.7.

## Steps to reproduce

Create the following entity:

```php
class Foo
{
    public $bar = false;
}
```

Create the following form:

```php
$form = $this->createFormBuilder(new Foo())
    ->add('bar', 'choice', array(
        'choices' => array(
            1 => 'Yes', // boolean `true` and `false` as keys also exhibit the same problem
            0 => 'No',
        ),
        'expanded' => true,
    ))
    ->getForm()
;

return $this->render('AppBundle::form.html.twig', array(
    'form' => $form->createView(),
));
```

Create the following template:

```php
{{ form_start(form) }}
    {{ form_widget(form.bar) }}
{{ form_end(form) }}
```

Expected result: the “no” radio button to be checked.
Actual result: none of the checkboxes are checked.

Changing the value of `Foo::$bar` to `true` makes the “yes” radio button correctly render in its selected state.
 
When the `expanded` option on the choice field is changed to `false`, an HTML `select` menu is correctly rendered with the “no” option selected.

The exact same effect can be observed when the keys in the `choices` array are boolean `true` and `false` instead of `1` and `0`.

**Comment by xabbuh** [comment] 2015-11-01 11:54
Looks like a duplicate of #15573 to me.

@samhastings Please let me know if you don't agree so we can consider to reopen.

**Closed by xabbuh** 2015-11-01 11:54 UTC
Labels: Form
