### ISSUE TITLE
[HttpFoundation] Cannot set session ID after the session has started

### ISSUE THREAD

**Issue by korotovsky** [symfony/symfony#13954] opened 2015-03-17 17:03 UTC
After updating to 2.6.5 we got the error in our tests:

```
Acme/Bundle/TestBundle/Tests/Controller/Foo/BarControllerTest::testSomeAction
LogicException: Cannot set session ID after the session has started.

vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/MockArraySessionStorage.php:134
vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php:199
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/TestSessionListener.php:45
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:112
vendor/jmikola/wildcard-event-dispatcher/src/Jmikola/WildcardEventDispatcher/WildcardEventDispatcher.php:36
vendor/event-band/symfony-adapter/src/EventBand/Adapter/Symfony/BandEventDispatcher.php:57
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:126
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:66
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php:64
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:186
vendor/acme/core-bundle/Acme/Bundle/CoreBundle/Component/Phpunit/WebTestCase.php:328
src/Acme/Bundle/TestBundle/Tests/Controller/Foo/BarControllerTest.php:170
```

On 2.6.4 everything is ok

**Comment by Tobion** [comment] 2015-03-17 17:25
Duplicate of #13450
Please use the search next time.

**Closed by Tobion** 2015-03-17 17:25 UTC
