### ISSUE TITLE
AssetMapper lodash (and potentially other libs) install problem

### ISSUE THREAD

**Issue by zatorck** [symfony/symfony#54140] opened 2024-03-03 19:46 UTC
### Symfony version(s) affected

6.4.3

### Description

Hello 

I've installed lodash via AssetMapper component but it gets error 

```
An exception has been thrown during the rendering of a template 
("Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned").
```

![image](https://github.com/symfony/symfony/assets/11573475/68d99e73-8474-4990-b6ca-ad3334147977)

### How to reproduce

Reprouction is very simple on new project use `php bin/console importmap:require lodash`

**Comment by smnandre** [comment] 2024-03-03 21:00
This is a known bug, now fixed ! Hope you can wait until the bugfix release (end of next week?)

https://github.com/symfony/symfony/pull/54079

**Comment by derrabus** [comment] 2024-03-03 21:13
Closing as duplicate of #54078.

**Closed as not planned by derrabus** 2024-03-03 21:13 UTC
Labels: Bug, Status: Needs Review, AssetMapper
