### ISSUE TITLE
[3.2][Form] Empty strings instead of null in CountryType

### ISSUE THREAD

**Issue by geoffrey-brier** [symfony/symfony#20759] opened 2016-12-05 13:16 UTC
After upgrading in 3.2, when I submit a form which contains some `CountryType` elements and I don't submit those ones, then the value saved is an empty string while in 3.1 and below it was null.

According to the documentation of the `CountryType`, it's the intended behaviour but my tests are telling me that something changed.

**Comment by HeahDude** [comment] 2016-12-05 14:00
Hey @geoffrey-brier, have some time to add the minimum of code in a fork of symfony standard to reproduce this? I'll have a look when I can, thanks!

**Comment by xabbuh** [comment] 2017-01-06 06:04
Closing due to the lack of feedback. 

@geoffry-brier Please comment if you can provide additional information and we can consider to reopen.

**Comment by geoffrey-brier** [comment] 2017-01-31 15:15
@HeahDude @xabbuh Just created the test cases

**Comment by HeahDude** [comment] 2017-02-01 09:31
Will be closed by #21481.

Status: reviewed

**Closed** 2017-03-05 18:16 UTC
Labels: Bug, Form, Status: Reviewed
