### ISSUE TITLE
Fatal error in ConsumeMessagesCommand.php if pcntl extension is missing

### ISSUE THREAD

**Issue by slavouhrin** [symfony/symfony#52118] opened 2023-10-17 19:29 UTC
### Symfony version(s) affected

6.3.5

### Description

Executing `messenger:consume` fails with a fatal error `Undefined constant "SIGTERM"` if pcntl extension is not installed.

### How to reproduce

Run the command on a system with no pcntl extension.

### Possible Solution

Use `if defined('SIGTERM') ....` as in other parts of the code.

**Comment by weaverryan** [comment] 2023-10-17 19:37
Looks like a duplicate of - https://github.com/symfony/symfony/pull/51791 - that fix will be included in the next 6.3.6 release.

Cheers!

**Closed as not planned by weaverryan** 2023-10-17 19:37 UTC
Labels: Bug, Status: Needs Review, Messenger
