### ISSUE TITLE
cloned TraceableStack operates differently than StackMiddleware

### ISSUE THREAD

**Issue by rela589n** [symfony/symfony#51564] opened 2023-09-05 10:20 UTC
### Symfony version(s) affected

6.x

### Description

The `StackMiddleware` has it's own state (`$offset` field), which changes during the operation flow. Therefore, if at some point of time we clone this stack, we get a completely different instance, which may be safely used.

The problem lies in the absence of `TraceableStack::__clone()` method . 
It is not possible to use cloned stack after main stack _has been iterated over_, since internally it references the same object.

See provided test for details.

### How to reproduce

Below two tests are provided. First passess (`StackMiddleware`), second fails (`TraceableStack`).

```php
class_exists(TraceableMiddleware::class);

final class TraceableStackCloneTest extends TestCase
{
    /** @dataProvider stackDataProvider */
    public function testClonedStackFramesFollowOriginalFrames(StackInterface $stack): void
    {
        $clonedStack = clone $stack;

        $nextFrame = $stack->next();
        $clonedStackNextFrame = $clonedStack->next();

        self::assertSame($nextFrame, $clonedStackNextFrame);
    }

    public function stackDataProvider(): array
    {
        $middlewareIterator = [
            $this->createMock(MiddlewareInterface::class),
            $this->createMock(MiddlewareInterface::class),
        ];

        return [
            [new StackMiddleware($middlewareIterator)], // passes
            [new TraceableStack(new StackMiddleware($middlewareIterator), $this->createMock(Stopwatch::class), 'command.bus', 'test')], // fails
        ];
    }
}
```

### Possible Solution

I guess adding `__clone` method to `TraceableStack` would fix the issue:

```php
    public function __clone(): void
    {
        $this->stack = clone $this->stack;
    }
```

### Additional Context

PHP version: 8.2.8
Symfony messenger version: 6.2.7

**Comment by krciga22** [comment] 2023-09-11 03:30
Hi @rela589n,

Thanks for submitting this bug report. I tried out your test case and I can confirm the same bug is happening for Symfony version 6.3.4 and that the fix you suggested indeed makes the test case pass. I'm not sure whether this bug is necessary to fix since [TraceableStack ](https://github.com/symfony/symfony/blob/55582fda18886213d2f1af3eaeb1c612bd31f1e1/src/Symfony/Component/Messenger/Middleware/TraceableMiddleware.php#L48)is marked as `Internal`, however, [StackInterface ](https://github.com/symfony/symfony/blob/55582fda18886213d2f1af3eaeb1c612bd31f1e1/src/Symfony/Component/Messenger/Middleware/StackInterface.php#L17C75-L17C75)does explicitly mention that all implementations must be cloneable, so it's likely this should be fixed.

In terms of the potential fix, I would also suggest cloning $stopwatch as well as it may have the same issue: 
```php
public function __clone(): void
{
    $this->stack = clone $this->stack;
    $this->stopwatch = clone $this->stopwatch;
}
```

Here's my reproduction of the test case including the potential fix (which causes it to pass): https://github.com/krciga22/symfony/commit/9c71a0eebee569091bf092ed5853f02afbcc11ef

By the way, since `TraceableStack` is marked as `Internal`, I'm curious if you are utilizing it for Symfony development or for a separate project that utilizes Symfony framework and/or components?

Status: Reviewed

**Comment by stof** [comment] 2023-09-11 08:32
@krciga22 the Stopwatch must not be cloned, otherwise the traced timing won't be registered in the profiler due to registering them in a different Stopwatch.

**Comment by krciga22** [comment] 2023-09-11 11:02
@stof makes sense, I didn't realize that. `TraceableStack` is given a `Stopwatch` to use on construction and isn't expected to own/manage it, so it has no right to clone it.

**Comment by rela589n** [comment] 2023-09-14 10:59
Hi, @krciga22 ,
Thanks for the reply, I highly appreciate it

> By the way, since TraceableStack is marked as Internal, I'm curious if you are utilizing it for Symfony development or for a separate project that utilizes Symfony framework and/or components?

I'm currently working on project built with Symfony framework. It has its own micro-framework built with Messenger component inside primarily used for cross-layer communication. Basically this is just a command bus with some additional middlewares providing common features for our specific needs.

The implementation of one more middleware required a source stack to be cloned. When running in prod mode everything worked fine, while running in dev-mode  causes bug, since `TraceableStack` wrapper is added.

Current implementation uses following workaround for `TraceableStack`:

```php
$closure = fn (): object => $this->stack = clone $this->stack;
$closure->call($stack);
```

It would be great if this bug was fixed so that we won't have to write _dirty workarounds_.

**Comment by krciga22** [comment] 2023-09-15 12:59
I see, definitely sounds like a plausible scenario that might occur when writing different middleware. I've worked on the fix for this based off of your suggested fix and will try to create a PR for it tonight.

In case you or @stof have any suggestions before I submit a PR, here's my latest commits: https://github.com/symfony/symfony/compare/6.4...krciga22:symfony:issue-51564

One thing I'm not sure of though is the line with `class_exists(TraceableMiddleware::class);`. I'm not sure if there's a better way to import the TraceableMiddleware class since it's in the same file as `TraceableStack`?

**Comment by stof** [comment] 2023-09-15 13:21
it should be inside the test at least, not at top-level

**Comment by krciga22** [comment] 2023-09-17 04:48
@stof , good call I thought there was something else funny about that line. I've gone ahead and updated the test as well as refactored it to (I hope) more accurately test that the cloned `TraceableStack` unstacks independently. I've also added another test to specifically test that the same `Stopwatch` is used by the clone and the original.

https://github.com/symfony/symfony/compare/6.4...krciga22:symfony:issue-51564

**Closed as completed** 2023-09-20 14:19 UTC
Labels: Bug, Status: Reviewed, Messenger
