### ISSUE TITLE
Anonymous services do not work for global classes

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22146] opened 2017-03-24 10:32 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | dev-master

Using the standard Twig Extensions library, the following definitions work as expected:
```yaml
services:
    _defaults:
        public: false
        tags: [ twig.extension ]

    random.name:
        class: Twig_Extensions_Extension_Intl
```
While the following doesn't:
```yaml
services:
    _defaults:
        public: false
        tags: [ twig.extension ]

    Twig_Extensions_Extension_Intl: ~
```
It throws:

> The definition for "Twig_Extensions_Extension_Intl" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.

It seems to be related to the fact that it's a class in the global namespace.

**Comment by nicolas-grekas** [comment] 2017-03-24 10:39
True, and not a bug: only namespaced classes can have their class attribute omitted, as before 3.3.
```php
Twig_Extensions_Extension_Intl:
    class: Twig_Extensions_Extension_Intl
```

**Comment by nicolas-grekas** [comment] 2017-03-24 10:41
Note that this looks like an argument to add namespaces to Twig :)
Closing here.

**Comment by curry684** [comment] 2017-03-24 10:53
I would've expected this exception in the [blog post](http://symfony.com/blog/new-in-symfony-3-3-optional-class-for-named-services) on the subject  ;)

Just curious though - the restriction seems arbitrary to me, why would this be forbidden? The absence of the `class` property coupled with a simple `class_exists` call on the service name should work identically for both global and namespaced classes. What difference am I not seeing?

**Comment by stof** [comment] 2017-03-24 12:20
@curry684 this is because service ids are not required to be class names. When we see a `\` in it, we assume it is a class name (this char is not used in common naming conventions for services).
Always assuming the id is a class name when you forget the class for a service definition using an arbitrary id actually hurts DX (you then get weird errors about unknown class during instantation).

@javiereguiluz can you update the blog post to add a note about the shortcut syntax requiring to use namespaces ?

**Comment by curry684** [comment] 2017-03-24 13:18
@stof I fully agree such an error would be confusing, but there's no need to? If the class property is missing *and the ID is not a loadable class* we could throw a verbose message stating that a service definition either has to be named after a defined class, or contain a `class` property. That would've been **much** better than the DX I had this morning in the 30 minutes before I posted this issue. Something has to change on that end anyway even if we improve the docs.

Not like the current situation is all that good since I can still define services with a backslash in the name (unconventional but not forbidden) and point them to completely different classes.

**Comment by nicolas-grekas** [comment] 2017-03-24 14:18
@curry684 this (your suggestion included) has been discussed previously in #21133 (and linked pages).

**Comment by nicolas-grekas** [comment] 2017-03-24 14:20
See also #21380

**Comment by nicolas-grekas** [comment] 2017-03-24 14:24
@curry684 would you like to submit a PR to enhance the exception message (adding a class_exists + interface_exists check to make it more DX friendly?)

**Comment by curry684** [comment] 2017-03-24 19:14
I'll try to make some time for this and https://github.com/symfony/symfony/issues/22143 this weekend or early next week.

Just to be clear: I would be allowing the use case in the opening post, by first checking for class property, then backslashes, then the class/interface check. And if all fail throw a proper and verbose error during compilation describing the problem.

**Comment by nicolas-grekas** [comment] 2017-03-24 20:12
The service definitions should remain context free, which means we should not do a class_exists check to turn `Twig_Extensions_Extension_Intl: ~` into a working service when the context allows so (what's inside `vendor/`).

Instead, we should just make sure the exception message thrown by `CheckDefinitionValidityPass` is as friendly as possible, to save you these 30 minutes you lose :) So to me, class_exists/interface_exists should just be used to construct a better exception message when applicable.

**Comment by curry684** [comment] 2017-03-24 22:16
Ok I can agree with that for now as it is the most consistent solution, I see the context argument, and fixes the DX. 

As a whole my morning spent using all the new service features in 3.3-dev in a big 3.2 project did give me a bunch of icky feelings about the recent movement of the DI container, and I do think a lot of this recent stuff has to be rethought as a whole for 4.0 next year. I think the features are generally great but the cohesion within the current BC constraints is 'suboptimal'.

Just looking at this issue I see that service IDs starting with a `_` are reserved now except that they aren't, `_defaults` has become a magic word that may or may not define a service called `_defaults`, services can be named with backslashes as long as they don't contain a `class` property, at which point they will cause weird runtime crashes, and the global namespace is sort of discriminated in service land for defendable but not to an outsider readily apparent reasons.

There's some DX to be done in DI imho  :)

**Comment by nicolas-grekas** [comment] 2017-03-25 09:50
We have two months of feat freeze to make things as best as possible. Your PR #22153 is on this path :)

**Comment by curry684** [comment] 2017-03-25 10:31
Happy to help, that's why I share my real world experiences :)

**Closed** 2017-03-27 14:03 UTC
