### ISSUE TITLE
Adding lazy-loading listeners after construction is not supported.

### ISSUE THREAD

**Issue by liverbool** [symfony/symfony#29637] opened 2018-12-18 04:29 UTC
After upgrade from 4.1 to 4.2 i ran into this error when cache clear process.

```
In \Symfony\Bridge\Doctrine\ContainerAwareEventManager.php line 103:

  Adding lazy-loading listeners after construction is not supported.

```

I have no idea to fix it, Have someone can spot me for fixing?

Thanks!

**Comment by chalasr** [comment] 2018-12-18 09:49
Can you please add the full stack trace to your description? (including the caller)

**Comment by liverbool** [comment] 2018-12-18 10:00
I have nothing special just upgrade 4.1 to 4.2 (from old project) and got an error on `cache:cache` process.

**Comment by chalasr** [comment] 2018-12-18 10:13
Can you run the command with `-vvv`? You'll get a full stack trace

**Comment by xabbuh** [comment] 2018-12-18 10:14
Well, without being able to see what is going on in your application we will still not be able to help you. The full stack trace or a small example application that allows to reproduce would help here.

**Comment by liverbool** [comment] 2018-12-18 11:08
Here is `-vvv` output.

<details>
sf cach:c -vvv


 [WARNING] Some commands could not be registered:


In ContainerAwareEventManager.php line 103:

  [RuntimeException]
  Adding lazy-loading listeners after construction is not supported.


Exception trace:
 () at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:103
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->addEventListener() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1116
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Dbal_DefaultConnectionService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1132
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2037
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getSylius_Repository_LocaleService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1992
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getSylius_LocaleProviderService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2459
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getChang_Locale_Router_LocaleProviderService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1778
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getRouterService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2189
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getTwigService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getTranslation_ExtractorService.php:18
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getIncenteevTranslationChecker_ExtractorService.php:12
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getConsole_Command_PublicAlias_IncenteevTranslationChecker_Command_FindMissingService.php:12
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:243
 Symfony\Component\DependencyInjection\Container->make() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:225
 Symfony\Component\DependencyInjection\Container->get() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:186
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:69
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /Users/dos/GitHub/phpmob/takeoff/bin/console:33



 [WARNING] Some commands could not be registered:


In ContainerAwareEventManager.php line 103:

  [RuntimeException]
  Adding lazy-loading listeners after construction is not supported.


Exception trace:
 () at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:103
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->addEventListener() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1116
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Dbal_DefaultConnectionService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1132
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2037
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getSylius_Repository_LocaleService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1992
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getSylius_LocaleProviderService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2459
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getChang_Locale_Router_LocaleProviderService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1778
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getRouterService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:2189
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getTwigService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getTranslation_ExtractorService.php:18
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getIncenteevTranslationChecker_ExtractorService.php:12
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/getConsole_Command_PublicAlias_IncenteevTranslationChecker_Command_FindMissingService.php:12
 require() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:976
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->load() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:243
 Symfony\Component\DependencyInjection\Container->make() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:225
 Symfony\Component\DependencyInjection\Container->get() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:186
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:69
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /Users/dos/GitHub/phpmob/takeoff/bin/console:33


 // Clearing the cache for the dev environment with debug true

 // Clearing outdated warmup directory...

 // Warming up cache...

11:05:40 INFO      [php] User Deprecated: The "Sylius\Bundle\UserBundle\Controller\SecurityController" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use {@see AbstractController} instead.
 *.
[
  "exception" => ErrorException {
    #message: """
      User Deprecated: The "Sylius\Bundle\UserBundle\Controller\SecurityController" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use {@see AbstractController} instead.\n
       *.
      """
    #code: 0
    #file: "./vendor/symfony/debug/DebugClassLoader.php"
    #line: 191
    #severity: E_USER_DEPRECATED
    trace: {
      ./vendor/symfony/debug/DebugClassLoader.php:191 { …}
      spl_autoload_call() {}
      ./vendor/symfony/config/Resource/ClassExistenceResource.php:76 { …}
      ./vendor/symfony/dependency-injection/ContainerBuilder.php:351 { …}
      ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:398 { …}
      ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:460 { …}
      ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:686 { …}
      ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:832 { …}
      ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:220 { …}
      ./vendor/symfony/http-kernel/Kernel.php:735 { …}
      ./vendor/symfony/http-kernel/Kernel.php:566 { …}
      ./vendor/symfony/http-kernel/Kernel.php:133 { …}
      ./vendor/symfony/http-kernel/Kernel.php:150 { …}
      ./vendor/symfony/framework-bundle/Command/CacheClearCommand.php:187 { …}
      ./vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129 { …}
      ./vendor/symfony/console/Command/Command.php:255 { …}
      ./vendor/symfony/console/Application.php:919 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:89 { …}
      ./vendor/symfony/console/Application.php:262 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:75 { …}
      ./vendor/symfony/console/Application.php:145 { …}
      ./bin/console:33 {
        › $application = new Application($kernel);
        › $application->run($input);
        ›
      }
    }
  }
]
11:05:40 DEBUG     [php] Warning: unlink(/Users/dos/GitHub/phpmob/takeoff/var/cache/de_/ContainerZxXr6Kn.legacy): No such file or directory
[
  "exception" => Symfony\Component\Debug\Exception\SilencedErrorContext {
    +count: 1
    -severity: E_WARNING
    trace: {
      ./vendor/symfony/http-kernel/Kernel.php:746 { …}
      ./vendor/symfony/http-kernel/Kernel.php:566 { …}
    }
  }
]

In ContainerAwareEventManager.php line 103:

  [RuntimeException]
  Adding lazy-loading listeners after construction is not supported.


Exception trace:
 () at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:103
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->addEventListener() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1116
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Dbal_DefaultConnectionService() at /Users/dos/GitHub/phpmob/takeoff/var/cache/dev/ContainerZxXr6Kn/TakeOffTakeOff_KernelDevDebugContainer.php:1132
 ContainerZxXr6Kn\TakeOffTakeOff_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:245
 Symfony\Component\DependencyInjection\Container->make() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/dependency-injection/Container.php:225
 Symfony\Component\DependencyInjection\Container->get() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/doctrine-bridge/ManagerRegistry.php:35
 Symfony\Bridge\Doctrine\ManagerRegistry->getService() at /Users/dos/GitHub/phpmob/takeoff/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:202
 Doctrine\Common\Persistence\AbstractManagerRegistry->getManagers() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:49
 Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:96
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/http-kernel/Kernel.php:587
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/http-kernel/Kernel.php:133
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/http-kernel/Kernel.php:150
 Symfony\Component\HttpKernel\Kernel->reboot() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:187
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Application.php:919
 Symfony\Component\Console\Application->doRunCommand() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/dos/GitHub/phpmob/takeoff/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /Users/dos/GitHub/phpmob/takeoff/bin/console:33

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

</details>

**Comment by liverbool** [comment] 2018-12-19 09:16
@chalasr @xabbuh  What is this error mean?

**Comment by liverbool** [comment] 2018-12-19 10:22
@chalasr @xabbuh Here is my commit to produce this error https://github.com/liverbool/doctrine-lazy-error/commit/aadb9cd3b5bbca46d144757b653e8f2c9b18283e

Here services i config https://github.com/liverbool/doctrine-lazy-error/blob/aadb9cd3b5bbca46d144757b653e8f2c9b18283e/config/services.yaml

**Comment by xabbuh** [comment] 2018-12-19 11:49
The issue here is that one of the event subscribers depends on a Doctrine repository. To construct this repository, the class metadata are read which triggers the `loadClassMetadata` event leading to the event manager to not accept and further addition of event listeners/subscribers.

Are you sure that only updating Symfony leads to this behaviour? Or did you also update other packages?

**Comment by xabbuh** [comment] 2018-12-19 13:34
I can see the same behaviour when downgrading the Symfony related packages in your example application to 4.1.

**Comment by liverbool** [comment] 2018-12-20 10:41
I think this may depend on `sylius/sylius-resource` bundle, this error gone away when i remove that bundle.
@pamil do you have some idea?

**Comment by liverbool** [comment] 2018-12-24 07:45
SF 4.1 is fine! everything is ok.

@xabbuh here is 4.1 downgrade version https://github.com/liverbool/doctrine-lazy-error-41/commit/dd1ae70c1d9d6773ba864345aaa1d1447108459c

**Comment by liverbool** [comment] 2018-12-26 09:14
I try to update vendor one by one and finally conclusion is:

`symfony/dependency-injection:4.1.7` OK
`symfony/dependency-injection:4.1.9` Failed

**Comment by liverbool** [comment] 2018-12-26 09:33
Here is @nicolas-grekas 's commit (https://github.com/symfony/dependency-injection/commit/5ec6098a2ba4c84db4a023a12c1d4ec8933c33ae#diff-5ad937deffee147ff6e4789f46af72d2) that is the cause of this error.

**Comment by xabbuh** [comment] 2019-01-11 14:31
Could this also be related to #29836?

**Comment by liverbool** [comment] 2019-01-14 07:51
I think no!

**Comment by liverbool** [comment] 2019-02-04 11:02
Still not fix (https://github.com/liverbool/doctrine-lazy-error/commit/aadb9cd3b5bbca46d144757b653e8f2c9b18283e)

![screen shot 2562-02-04 at 18 01 15](https://user-images.githubusercontent.com/206804/52204505-e731e600-28a6-11e9-856e-66471b0b5ec4.png)

cc @nicolas-grekas

**Comment by cirykpopeye** [comment] 2019-02-04 15:53
I've had this exact same error response, but it was because I created a Twig Extension using the \Twig_extension to extend my custom class. I replaced it with Twig\Extension\AbstractExtension and it that removed my error. Don't know if this case is related though but worth the try since that's the exact error response.

**Comment by liverbool** [comment] 2019-02-05 06:55
Thanks @cirykpopeye but after tried i have no luck! 😢

**Comment by cirykpopeye** [comment] 2019-02-05 09:37
@liverbool , I'm in the same boat now. Remove the extension solves the issue so it has something to do with it. I'm only using the router interface inside though.

**Comment by liverbool** [comment] 2019-02-05 09:51
@cirykpopeye sound do i need to inject service container?

**Comment by cirykpopeye** [comment] 2019-02-05 10:13
The main point is that you can't use any of the services in your constructor. You can load them already but using them will cause the error since they're lazy loaded. Use them from you filters/functions directly. 

So instead of __construct(Router $router) { $this->router = $router; $this->adminURI = $this->router->generate(...); } you should call the generate function anywhere but the constructor. You can nest that function in a private method so you can keep your code dry though.

**Comment by liverbool** [comment] 2019-02-05 11:40
I think i have no code like that in constructor.
I found my `DoctrineSubscriber` depends on `SomeRepository`, that is case of this error!

**Comment by nicolas-grekas** [comment] 2019-07-29 17:36
Fix is now merged, please report back if you still encounter the issue (and open a new issue with a reproducer please if that happens.)

**Closed by nicolas-grekas** 2019-07-29 17:36 UTC
Labels: BC Break, Bug, DependencyInjection, DoctrineBridge, Status: Needs Review
