### ISSUE TITLE
inputbag doesn't allow array's

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#44432] opened 2021-12-03 06:24 UTC
### Symfony version(s) affected

6.0

### Description

This bug was already mentioned in https://github.com/symfony/symfony/pull/41766#issuecomment-876248038 

The issue is still not fixed and get a 'Message: Input value "fieldname" contains a non-scalar value.' error now.

The set function is accepting an error and even \Stringable but the accept doesn't have the same check and is inconsistent now.
get function - vendor/symfony/http-foundation/InputBag.php:36
```php
        if (null !== $value && $this !== $value && !is_scalar($value)) {
            throw new BadRequestException(sprintf('Input value "%s" contains a non-scalar value.', $key));
        }
```

set function - vendor/symfony/http-foundation/InputBag.php:77
```php

        if (null !== $value && !is_scalar($value) && !\is_array($value) && !$value instanceof \Stringable) {
            throw new \InvalidArgumentException(sprintf('Excepted a scalar, or an array as a 2nd argument to "%s()", "%s" given.', __METHOD__, get_debug_type($value)));
        }
```

### How to reproduce

Set a array _GET or _POST value and try to get the same _GET or POST key

### Possible Solution

Add the same check that's in the set function also in the get function

**Comment by ro0NL** [comment] 2021-12-03 08:03
Still, this is by design: https://github.com/symfony/symfony/pull/41766#issuecomment-865083005

**Comment by dvdknaap** [comment] 2021-12-03 08:22
> Still, this is by design: [#41766 (comment)](https://github.com/symfony/symfony/pull/41766#issuecomment-865083005)

That comment doesn't make sense because it was working in the past and now it's not working anymore.

**Comment by ro0NL** [comment] 2021-12-03 08:25
Well, it was deprecated in 5.x, removed in 6.0.

**Comment by xabbuh** [comment] 2021-12-03 16:10
Closing here as explained above. We deliberately made this design change.

**Closed as completed by xabbuh** 2021-12-03 16:10 UTC
Labels: Bug, HttpFoundation, Status: Needs Review

**Comment by Justinas-Jurciukonis** [comment] 2022-02-09 10:30
@xabbuh How to get parameter that can be either array or json string that is later decoded to array?

**Comment by nicolas-grekas** [comment] 2022-02-09 10:32
@Justinas-Jurciukonis : `$bag->all()['that-param']`

**Comment by AbrahamCovelo** [comment] 2023-03-30 09:13
> @xabbuh:
> @Justinas-Jurciukonis : `$bag->all()['that-param']`

You can also do a: $bag->all('that-param');

**Comment by rgpublic** [comment] 2023-07-12 16:57
@AbrahamCovelo : That's very useful. Thanks! Although the extra optional key argument is only supported in recent Symfony versions it seems. So you can't use that if you want to target multiple Symfony versions. Just a little caveat.

**Comment by josecasahe** [comment] 2024-01-20 10:46
This is the worst change ever, it doesn't even support nulls...Crazy

**Comment by wouterj** [comment] 2024-01-20 12:32
@josecasahe please make yourself aware of our [Code of Conduct](https://symfony.com/coc) before interacting with the community.
