### ISSUE TITLE
Color change on console from white to black for error and caution foreground

### ISSUE THREAD

**Issue by evotodi** [symfony/symfony#39842] opened 2021-01-14 17:48 UTC
Would it be possible to change the foreground color for error and caution from white to black?
I am aware of the --no-ansi flag but believe the color change would help many users.

Below is the changes to symfony/console/Style/SymfonyStyle.php that I propose.
I am unsure if the symfony binary uses the SymfonyStyle class or if is coded into the binary.

```
public function error($message)
{
    $this->block($message, 'ERROR', 'fg=black;bg=red', ' ', true);
}

public function caution($message)
{
    $this->block($message, 'CAUTION', 'fg=black;bg=red', ' ! ', true);
}
```

**Screenshot of the change.**

![Screenshot 2021-01-14 123722](https://user-images.githubusercontent.com/1625853/104627636-45f06480-5665-11eb-8dac-b5a57092713f.png)

**Comment by jderusse** [comment] 2021-01-14 19:24
The color is controlled by the scheme/theme you applied on your terminal. 

For example, when using the built-in schemes "Solarized" on gnome-terminal, I get the opposite: a better contrast with the white color.

![Screenshot from 2021-01-14 20-18-41](https://user-images.githubusercontent.com/578547/104638116-08f89200-56a6-11eb-8d5c-009359a69a34.png)

I also tested with all the built-in schemes provided by gnome, and the contrast is always better in white over black.

I suggest to change the theme to darken "red" and lighten "text"

**Comment by fabpot** [comment] 2021-01-14 19:40
Closing as this is not a bug in Symfony.

**Closed as completed by fabpot** 2021-01-14 19:40 UTC
Labels: Console

**Comment by evotodi** [comment] 2021-01-14 19:53
Thanks for closing this request since it was not a "issues related to the Symfony CLI ".
Windows terminal and Powershell are handicapped compared to almost any linux shell, hence the reason for the request for a minor non invasive code change.

Here is an issue then. I posted this to symfony/cli not symfony/symfony.

**Comment by wouterj** [comment] 2021-01-14 20:28
Symfony CLI doesn't modify the output from the Symfony `bin/console`. So what you're looking at is the pure console component.

I can't speak for Powershell (never used it), but the Windows terminal certainly allows to modify the colorscheme. The contrast of the used colorscheme is what causing the issue here. Any terminal application doesn't know the real rgb color, only "red", "blue", "black" etc are used. So the component can't switch things based on contrast ratios.

Note that the default Windows terminal has a black background, white text and almost pure red (`#FF0000`). Looking at this screenshot of the default window colors, I would say white on red is readable:

![image](https://user-images.githubusercontent.com/749025/104645450-59282200-56af-11eb-9725-6dee7ff799c7.png)

(this screenshot is coming from https://tomasvotruba.com/blog/2018/08/06/stylish-and-standard-console-output-with-symfony-style/)

**Comment by stloyd** [comment] 2021-01-14 20:28
But as it was already said, it's not bug in Symfony, nor framework/component nor in CLI.

It the colour schema being used on Windows.

Maybe you should check ie: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes

Cause as above it's not bug and adding workaround just for Windows (we can't be sure it will work same in all terminals/powershell etc) will not work and mostly will not be accepted.

**Comment by evotodi** [comment] 2021-01-14 23:14
I would like to apologize. This is not an **issue** with Symfony but rather an **issue** with Darcula theme in PHPStorm. The below fixes the original **issue** weather you use cmd, powershell, cygwin, or mingw64 as your terminal in PHPStorm on windows.

For anyone in the future that comes along: 
```
PHPStorm 2020.3
settings->editor->console colors->ANSI colors->red  = darker red like #830000
settings->editor->console font->line spacing = 1.0
```

After above changes in PHPStorm.

![Screenshot 2021-01-14 175648](https://user-images.githubusercontent.com/1625853/104659010-e5c3e780-5691-11eb-9593-b6efe76918a8.png)

As a side note 'caution' already has a black foreground and was/is not an problem to read.
