### ISSUE TITLE
[Form] label_format option doesn't seem to be used for embedded form types

### ISSUE THREAD

**Issue by kminh** [symfony/symfony#17618] opened 2016-01-30 20:47 UTC
Here's an example to reproduce:

``` php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'an_embedded_type', [
                'label_format' => 'form.label.%name%'
            ])
        ;
    }
```

The `name` form will use default labels for all of its fields instead of using the specified `label_format`. Setting `label_format` within the `an_embedded_type` itself works only when it is not embedded.

**Comment by webmozart** [comment] 2016-02-04 20:19
Hi :) Thanks for reporting this bug! The label_format was never supposed to be propagated to nested forms. I can see however how this can be useful. Marking as feature request.

**Comment by HeahDude** [comment] 2016-03-26 19:13
Actually, the following test pass:
```php
    public function testLabelFormatInheritedOptionInCompoundField()
    {
        var_dump('called');
        $options = array('label_format' => 'custom.%name%');

        $form = $this->factory->createNamedBuilder('myform', 'Symfony\Component\Form\Extension\Core\Type\FormType')
            ->add('author', 'Symfony\Component\Form\Tests\Fixtures\AuthorType', $options)
            ->getForm();
        $view = $form->get('author')->get('firstName')->createView();
        $html = $this->renderLabel($view);

        $this->assertMatchesXpath($html,
'/label
    [@for="myform_author_firstName"]
    [.="[trans]custom.firstName[/trans]"]
'
        );
    }
```

The inheritance seems to be handled [here](https://github.com/symfony/symfony/commit/aad442da9d2738ca2956b138d6aa9bd2fc3dea74#diff-6d56b5364de19e4f0b71a89a0ef194a0R65).

Am I missing something ?

**Comment by xabbuh** [comment] 2016-03-30 18:37
ping @kminh Can you take a look at @HeahDude's example? :)

**Comment by gaetan-petit** [comment] 2018-03-05 10:43
Just run into the same issue, label_format does not apply to an embedded form type.

**Comment by alegout** [comment] 2018-04-01 03:03
+1

**Comment by xabbuh** [comment] 2018-04-01 07:14
Can anyone of you provide a small application that allows to reproduce your issue?

**Comment by xabbuh** [comment] 2018-09-23 12:07
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed by xabbuh** 2018-09-23 12:07 UTC
Labels: Feature, Form, Status: Needs Review
