### ISSUE TITLE
[Validator] `NotBlankValidator` shouldn't allows blank string

### ISSUE THREAD

**Issue by piotrooo** [symfony/symfony#40678] opened 2021-04-02 06:51 UTC
**Symfony version(s) affected**: 5.2.6

**Description**
`NotBlankValidator` allows blank (`' '`) string.

**How to reproduce**
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotBlankValidator;

$blankString = ' ';

$notBlank = new NotBlank();
$notBlankValidator = new NotBlankValidator();
$notBlankValidator->validate($blankString, $notBlank);
```

**Possible Solution**
`NotBlankValidator` should trim value before check is empty.

**Additional context**
I can pass `normalizer=trim`, but this is sad to set this for each annotation. Not allowing blank string should be default.

**Comment by alexandre-daubois** [comment] 2021-04-02 09:32
Hi ! I can understand the frustration. But it seems that by viewing the documentation, [this is intentional](https://symfony.com/doc/current/reference/constraints/NotBlank.html#normalizer), just like you said in your **Additional context**.

Improving this would be an feature or an enhancement, but not a bug. Changing this would definitely break BC, as it was already like this in Symfony 4.4.

**Comment by ogizanagi** [comment] 2021-04-02 12:43
> I can pass normalizer=trim, but this is sad to set this for each annotation. Not allowing blank string should be default.

You could also extend NotBlank with a default `trim` normalizer (and override `validatedBy` to reuse the original `NotBlankValidator`) and use it everywhere instead.

**Comment by Nyholm** [comment] 2021-04-02 14:55
This is a great issue. 

Thank you @alexandre-daubois for your explanation and @ogizanagi for the workaround. 

Im closing this issue as it is not a bug.

**Closed as completed by Nyholm** 2021-04-02 14:55 UTC
Labels: Validator, Bug, Status: Needs Review
