### ISSUE TITLE
Inluded templates in twig print special characters as ascii in assets

### ISSUE THREAD

**Issue by bnd170** [symfony/symfony#15095] opened 2015-06-25 08:38 UTC
Hello, I have a problem with Symfony 2.7.1

I recently upgraded my project from 2.3 to 2.7.1.

I check all my project searching deprecated things to fix it, but when I open an action twig included templates which in turn contain assets, they are shown with bars directory in ASCII.

I leave an example of the problem, see if someone can give me a solution.

In my template
```
{% block javascripts %}
    {% include 'AdminBundle:Global:notifications.html.twig' %}    
    {% include '::genemu.js.html.twig' with {'form': form} %}
{% endblock %}
```

And this is the content in genemu.js.html.twig that shows wrongly
```
        {% javascripts output='admin/js/compiled/main_forms.js'
            'bundles/bmatznerjqueryui/js/minified/jquery-ui.min.js'
            'bundles/pinanoselect2/js/select2.full.min.js'
            'uploadify/jquery.uploadify.min.js'
            'tinymce/js/tinymce/jquery.tinymce.min.js'
            'datetimepicker/jquery.datetimepicker.js'
        %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
        {% endjavascripts %}
```

It shows like that
```
<script type="text/javascript" src="\x2Fapp_dev.php\x2Fadmin\x2Fjs\x2Fcompiled\x2Fmain_forms_jquery\x2Dui.min_1.js"></script>
<script type="text/javascript" src="\x2Fapp_dev.php\x2Fadmin\x2Fjs\x2Fcompiled\x2Fmain_forms_select2.full.min_2.js"></script>
<script type="text/javascript" src="\x2Fapp_dev.php\x2Fadmin\x2Fjs\x2Fcompiled\x2Fmain_forms_jquery.uploadify.min_3.js"></script>
<script type="text/javascript" src="\x2Fapp_dev.php\x2Fadmin\x2Fjs\x2Fcompiled\x2Fmain_forms_jquery.tinymce.min_4.js"></script>
<script type="text/javascript" src="\x2Fapp_dev.php\x2Fadmin\x2Fjs\x2Fcompiled\x2Fmain_forms_jquery.datetimepicker_5.js"></script>
```

I think must be an issue from 2.7.1 because it works fine in 2.3

Thanks.

**Comment by stof** [comment] 2015-06-25 08:43
hmm, this might be a bug in the ``filename`` autoescaping strategy in Twig, which would select ``js`` rather than ``html`` for ``genemu.js.html.twig``

**Comment by bnd170** [comment] 2015-06-25 08:54
Uhms, how can i fix it? Some solution or its a bug from Symfony/Twig  integration?

**Comment by bnd170** [comment] 2015-06-25 10:58
Solved renaming the template from `genemu.js.html.twig` for genemujs.html.twig`

Thanks!

**Comment by javiereguiluz** [comment] 2015-08-31 10:03
We can close this issue as "fixed".

The related Twig code that decides which escaping to use is defined here: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/FileExtensionEscapingStrategy.php  And this is the related unit test: https://github.com/twigphp/Twig/blob/1.x/test/Twig/Tests/FileExtensionEscapingStrategyTest.php

Should we report a bug/improvement to Twig repo or is this the intended behavior?

**Closed** 2015-08-31 10:52 UTC

**Comment by Tobion** [comment] 2015-08-31 11:51
I would consider this a bug in twig:
- genemu.js.html.twig => js
- genemu.js.css => js (why css when the last one is obivously css)
