### ISSUE TITLE
Nesting translation keys on yml, doesn't work.

### ISSUE THREAD

**Issue by kilianmb** [symfony/symfony#23750] opened 2017-08-01 16:55 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | Symfony 3.2.9 (kernel: app, env: dev, debug: true)

I'm trying to use the translator service, but if I nest the keys of the translation it doesn't work.

```yaml
# app/config/config.yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# etc....
```

```php
// AppBundle/Service/SomeFolder/SomeService.php
<?php

namespace AppBundle\Service\SomeFolder;

/**
 * Class SomeService
 */
class SomeService
{ 
    protected $translator;  

    public function __construct(TranslatorInterface $translator) 
    {  
        $this->translator = $translator;
    } 

    public function someFunction()
    {
        $statusCode = '01';
        $message = $this->translator->trans('someText.'.$statusCode, [], 'domain');
        dump($message);die();
    }
}
```

if:

```yaml
# AppBundle/Resources/translations/domain.en.yml
someKey.01: Whatever
```

output:

```
"Whatever"
```

if:

```yaml
# AppBundle/Resources/translations/domain.en.yml
someKey:
    01: Whatever
```

output:

```
[2017-08-01 16:14:38] translation.WARNING: Translation not found.{"id":"someText.01","domain":"domain","locale":"en"}
"someText.01"
```

Why I can not nest keys on translation yml files??

**Comment by stof** [comment] 2017-08-01 17:46
your issue is that `01` is transformed in `1` by PHP when using it as an array key (numeric strings are casted to integer`, and so when flattening the array later, the key is `someText.1`

You can nest keys in YAML. But you should avoid using numeric strings as keys in the array at any level due to the way PHP treats them in array keys.

**Comment by xabbuh** [comment] 2017-08-02 05:41
Closing here as the described behaviour is not a bug as explained by @stof.

**Comment by xabbuh** [comment] 2017-08-02 05:42
By the way, quoting your key would help:

```yaml
someKey:
    '01': Whatever
```

**Closed by xabbuh** 2017-08-02 05:41 UTC
Labels: Translator

**Comment by kilianmb** [comment] 2017-08-30 09:20
Thank you, and sorry for my ignorance.
