### ISSUE TITLE
ConsoleFormatter doesn't respect --no-ansi

### ISSUE THREAD

**Issue by nenadalm** [symfony/symfony#23779] opened 2017-08-03 14:12 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all (tested on 3.3.5, viewed source on master)

CliDumper has some checks if colors should be printed:
https://github.com/symfony/symfony/blob/257b2c945928c84e530dc9c397238bcd6d306d6c/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L455

That check is run only if `$this->colors` is not set however:
https://github.com/symfony/symfony/blob/257b2c945928c84e530dc9c397238bcd6d306d6c/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L396

ConsoleFormatter uses the CliDumper and sets colors to it:
https://github.com/symfony/symfony/blob/257b2c945928c84e530dc9c397238bcd6d306d6c/src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php#L184

which is `true` by default:
https://github.com/symfony/symfony/blob/257b2c945928c84e530dc9c397238bcd6d306d6c/src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php#L63

which causes that colors are always printed when using ConsoleFormatter.

Maybe default value for `colors` shouldn't be `true` but `null` and CliDumper shouldn't cast the argument to `bool` (https://github.com/symfony/symfony/blob/257b2c945928c84e530dc9c397238bcd6d306d6c/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L82) ?

**Comment by Simperfit** [comment] 2017-08-05 07:32
@nenadalm Do you want to submit a PR with a way to fix this ?

**Comment by nenadalm** [comment] 2017-08-06 17:41
@Simperfit maybe some day. It's not very critical bug.

**Comment by inmarelibero** [comment] 2019-02-27 21:51
I tried to replicate the bug here, with:

```
$outputStyle = new OutputFormatterStyle('red', 'yellow', ['bold', 'blink']);
$output->getFormatter()->setStyle('fire', $outputStyle);
$output->writeln('<fire>this should be blinking</fire>');
```

but option `--no-ansi` seems to work correctly

without `--no.ansi`:
<img width="641" alt="schermata 2019-02-27 alle 22 48 11" src="https://user-images.githubusercontent.com/254808/53525449-16bcc280-3ae2-11e9-89c2-f605ba9de74c.png">

with `--no.ansi`:
<img width="713" alt="schermata 2019-02-27 alle 22 48 33" src="https://user-images.githubusercontent.com/254808/53525457-1c1a0d00-3ae2-11e9-9d00-844da8289d84.png">

any hint on how to replicate the bug?

**Comment by chalasr** [comment] 2019-03-02 16:13
I can't reproduce either, seems like this has been fixed meanwhile (https://github.com/humbug/php-scoper/issues/128 confirms it). Closing

**Closed by chalasr** 2019-03-02 16:13 UTC
Labels: Bug, MonologBridge, Status: Needs Review, help wanted
