### ISSUE TITLE
[Form] Extend CollectionType to handle custom keys

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7828] opened 2013-04-24 11:50 UTC
Right now, CollectionType is designed to work only with numerically and incrementally indexed collections. An interesting extension (see #7807) is to allow customly indexed collections as well by using the value of one of the fields in a row as key for the respective entry. The feature could be activated by setting an option such as `index_by` that configures the property path to the key in the data of the row.

Example:

``` php
$builder->add('employees', 'collection', array(
    'type' => 'employee',
    'index_by' => 'sin',
));
```

**Comment by trsteel88** [comment] 2015-09-22 21:32
+1 for an index_by options.

I have an issue where a collection has 1 row. If I delete that row and add a new row (all in 1 request), it now doesn't recognise the new row as a new row. It actually updates the existing row in the database (because it sees the first item as matching the first index). In some instances I don't want that same row to be updates because I store information such as a Created At datetime object.

**Comment by webmozart** [comment] 2016-03-04 07:53
See https://github.com/symfony/symfony/pull/13116#issuecomment-180273056 which contains another detailed comment about this issue.

**Comment by sergeyfedotov** [comment] 2016-03-28 21:30
@webmozart which indexes should be used for the new records? For example if an entity ID is used as index we can not simply use increment. What do you think about the introduction of the non mapped hidden field `_id` for the children forms? In this case the indexes can take any value.

**Comment by webmozart** [comment] 2016-04-01 08:00
@sergeyfedotov That could be a good solution.

**Comment by kokers** [comment] 2016-11-07 12:02
index_by would be awesome addition, as now I need to find a way around "reassigning" id as I have another relation inside the collection. Consider this entities with following relations:

`City - onetomany -> Street  - onetomany -> House - manytoone -> Person`

Inside city form I have collectionType for streets. You can add/remove/reorder them.

Let say I have inside Street

| id | city_id        | street_name           | 
| ------------- | ------------- |:-------------:| 
|1 | 2     | Yellow | 
|2 | 2      | Blue      | 
|3 | 2 | Green      | 

and House

| id | street_id        | house_name           | 
| ------------- | ------------- |:-------------:| 
|1 | 1     | Big | 
|2 | 1      | Round      | 
|3 | 2 | With loud neighbours      | 

Now, I reorder streets inside City form and submit order: Green,Yellow,Blue. After submit I see this:

| id | city_id        | street_name           | 
| ------------- | ------------- |:-------------:| 
|1 | 2     | Green | 
|2 | 2      | Yellow      | 
|3 | 2 | Blue      | 

Before submit I had street Yellow that had [Big,Round] houses. Now it's the Green street that have this relation which is obviously incorrect. 

Same happens if you remove something. The relation will not be removed as the id has changed and now will point to something else. Even if I make sure to remove Houses first from removed Street, then there still everything will be messed up. for example I remove Yellow along with [Big,Round]. And I will get:

| id | city_id        | street_name           | 
| ------------- | ------------- |:-------------:| 
|1 | 2      | Blue      | 
|2 | 2 | Green      | 

and House

| id | street_id        | house_name           | 
| ------------- | ------------- |:-------------:| 
|3 | 2 | With loud neighbours      | 

House "With loud neighbours " is now assigned to "Green" instead of "Blue". 

With that,  CollectionType shouldn't be used if there is a relation inside that collection. If I could add another field "order" and use index_by => order, that would solve my issue. I think. Unless there is something I don't know or can't find in documentation for this use case to resolve this.

**Comment by pathmissing** [comment] 2018-06-07 08:17
I still would consider this feature essential. Has there been any status update since 2016? Or a PR even?

**Comment by xabbuh** [comment] 2018-06-07 09:29
@pathmissing There has been one attempt in #13116 which was closed as it did not fully cover everything. So you could still work on it if you would like to give it a try.

**Comment by oleg-andreyev** [comment] 2018-06-21 12:22
My workaround for this was to pass Collection / array indexed by required key.

**Comment by robjensen82** [comment] 2018-08-22 21:26
I agree with @sergeyfedotov's suggestion of adding a hidden `_id` field to child forms. I think that would make identifying objects for addition, update and removal pretty easy.

**Comment by cre8izm** [comment] 2019-04-10 12:37
Any progress on this one?

**Comment by xabbuh** [comment] 2019-04-10 12:47
@cre8izm I don't think anyone is working on this currently. So feel free to to start a pull request if you would like to give it a try.

**Comment by ThomasLandauer** [comment] 2019-11-22 12:45
I'm a little confused about the status here. As @stof explained at https://github.com/symfony/symfony/issues/34453#issuecomment-555935972 it is already possible to index the collection by id. So @webmozart 's very first sentence here seems obsolete:
> Right now, CollectionType is designed to work only with numerically and incrementally indexed collections.

Could it be that this issue is already resolved and they just forgot to close it?

However, I see a problem that is somewhat related: The members of the collection get persisted to the database as soon as you do `$form->handleRequest($request);` in the controller.

My scenario: I'm using a collection on a "live" table. Say, it displays the records with id 15, 87, 56. Now the database changes, and upon form submission, the database query returns 15, 93 (=new item), 87. But the form submission still contains the id's 15, 87, 56. Since 93 is not included in the form data, it gets emptied out in the database! And since 56 is not present in the new query result, it causes the error "This form should not contain extra fields". The problem is that by the time that error gets raised, the previous records 15 and 93 have already been persisted.

So I'm suggesting: Introduce a new option to prevent the automatic persisting/flushing of collection items. This would give the user the chance to manually iterate through the collection data in the controller, to check each item before persisting it.

**Comment by xabbuh** [comment] 2019-11-22 13:04
> So I'm suggesting: Introduce a new option to prevent the automatic persisting/flushing of collection items. This would give the user the chance to manually iterate through the collection data in the controller, to check each item before persisting it.

That's something related to Doctrine and is controlled by the developer when choosing whether or not to cascade persist operations (see https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#transitive-persistence-cascade-operations). It's not something we can control from inside the Form component.

**Comment by ThomasLandauer** [comment] 2019-11-22 14:08
@xabbuh No, I'm not talking about *related* entities. I'm talking about one single table. So there must be a persist/flush somewhere in Symfony.

**Comment by xabbuh** [comment] 2019-11-22 14:20
If these entities are not associated with the "root entity" your form is bound to and if I correctly understand what you are doing in your example, the entities are not new and thus already managed by Doctrine which in turn means that their changes will be written to the database once `flush()` is called (`persist()` is not needed here). But that's still how Doctrine works and nothing we can nor want to control from the Form component.

**Comment by ThomasLandauer** [comment] 2019-11-22 15:01
I don't have a root entity. My parent form contains just the collection and the submit button, and is therefore bound to nothing. However, when I do `handleRequest()` on this form, the collection entries get persisted automatically. I'm not doing any `flush()` or `persist()` in my controller.

**Comment by xabbuh** [comment] 2019-11-22 15:05
If you create an example application, I can take a look into it and help you find out where the flush originates, but I assure you that it is not triggered from the Form component.

**Comment by ThomasLandauer** [comment] 2019-11-24 16:46
@xabbuh Thanks for insisting! :-) I was using Codeception for easier reproducing, and this was in fact causing the (invalid) entities to be flushed, see https://github.com/Codeception/Codeception/issues/5439

**Comment by ThomasLandauer** [comment] 2019-11-25 17:24
Again, this issue looks resolved to me! What's been asked for in the title "Extend CollectionType to handle custom keys" is possible by passing an associative array; whatever is used as keys in this array will be used to "index" the collection. The suggested feature `index_by` isn't even necessary.

So I would say: This issue can be closed. The only thing that's missing is proper documentation at https://symfony.com/doc/current/form/form_collections.html

**Comment by Seb33300** [comment] 2020-01-29 06:02
It looks like CollectionType properly works even if we manually set the collection index of each item.
This means we can manually set for example the object id as the collection index of each items and this can be a solution to prevent [indices conflict](https://github.com/symfony/symfony/issues/7468).

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $entity = $builder->getData();

    // Reindex collection using id
    $indexedCollection = new ArrayCollection();
    foreach ($entity->getCollectionField() as $collectionItem) {
        $indexedCollection->set($collectionItem->getId(), $collectionItem);
    }

    $builder
        ->add('collectionField', CollectionType::class, [
            'data' => $indexedCollection,
        ])
    ;
}
```

**Comment by xabbuh** [comment] 2020-06-03 15:13
let's close here then

**Closed by xabbuh** 2020-06-03 15:13 UTC
Labels: Feature, Form

**Comment by patrickbussmann** [comment] 2020-07-23 12:22
Hmm I have the same issue now but @Seb33300 is not working for me because I have deep form types.

i. e.

```
// Form Type 1

public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
            ->add('subs', CollectionType::class, [
	            'entry_type' => SubType::class,
	            'allow_add' => true,
	            'allow_delete' => true,
	            'by_reference' => false
            ])
    ;
}
```

```
// Form Type 2
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $entity = $builder->getData();
    // <- Problem: $entity is always NULL

    // Reindex collection using id
    $indexedCollection = new ArrayCollection();
    foreach ($entity->getCollectionField() as $collectionItem) {
        $indexedCollection->set($collectionItem->getId(), $collectionItem);
    }

    $builder
        ->add('collectionField', CollectionType::class, [
            'data' => $indexedCollection,
        ])
    ;
}
```

Some ideas?

Maybe a global form type listener which resolves the problem automatically.
When `id` field is found in `array` then use it as `key` and if not let the key as it is.

Would be a nice solution?

Thanks in Advance for ideas!

**Comment by arthurlauck** [comment] 2020-11-05 09:54
Couldn't keep up with this and I can't find a solution, is there one? A definitive one?

**Comment by Seb33300** [comment] 2020-11-05 10:13
@patrickbussmann @arthurlauck 

In case `$builder->getData()` return `NULL` when trying my example you may be able to achieve it inside a [form event](https://symfony.com/doc/current/form/events.html) (probably using `PRE_SUBMIT` or `SUBMIT` event)

**Comment by kevinpapst** [comment] 2022-02-17 20:33
I am late to the party, but for the next one searching ... here is another example for certain circumstances:
```php
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) {
                /** @var ArrayCollection<SomeInterface> $collection */
                $collection = $event->getData();
                foreach ($collection as $collectionItem) {
                    $collection->removeElement($collectionItem);
                    $collection->set($collectionItem->getName(), $collectionItem);
                }
            },
            100
        );
```

**Comment by Tofandel** [comment] 2022-08-30 13:42
How would one go about saving the Collection Key to the entity

Say you submit 

```
{"foo": {id: 1}, "bar": {id: 2}}
```

How to get the CollectionType to report the index to the entity so that you get
```
{"foo": {id: 1, name: "foo"}, "bar": {id: 2, name: "bar"}}
```

**Comment by Jalliuz** [comment] 2023-02-17 10:26
> Hmm I have the same issue now but @Seb33300 is not working for me because I have deep form types.
> 
> // Form Type 2
> ````
> public function buildForm(FormBuilderInterface $builder, array $options)
> {
>     $entity = $builder->getData();
>     // <- Problem: $entity is always NULL
> }
> ````
> 
> Some ideas?

In a CollectionType ->getData() only works inside a PRE_SET_DATA Event and you get the entity from the event, not from the builder

````
// In a CollectionType you can't access the entity with $builder->getData()
$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
    $form = $event->getForm();
    $yourEntity = $event->getData() ?: new YourEntity();

    // ... Do your thing here

    // ->add() the fields which rely on the entity here
   $form->add('someField');
});
````
