### ISSUE TITLE
3.4.15 only: PhpDumper "Cannot dump definitions which have method calls."

### ISSUE THREAD

**Issue by wuestkamp** [symfony/symfony#28557] opened 2018-09-22 19:21 UTC
**Symfony version(s) affected**: 3.4.15

**Description**  
When following the symfony-cmf installation guide with SF 3.4.15 I get the following error:

`Cannot dump definitions which have method calls.`

This is not the case with 3.4.14, so downgrading solves.

**How to reproduce**  
I created a test project for this.

```
git clone git@github.com:wuestkamp/my_project_name.git
cd my_project_name
composer install
```

This will show the error.

**Additional context**  
Here is the verbose output:

```
In PhpDumper.php line 1761:
                                                                      
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]  
  Cannot dump definitions which have method calls.                    
                                                                      

Exception trace:
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dumpValue() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:642
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceMethodCalls() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:521
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceInlinedDefinitions() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:834
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:889
 Symfony\Component\DependencyInjection\Dumper\PhpDumper::generateServiceFiles() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:218
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:859
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:663
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:135
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:64
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/kim/tmp/my_project_name/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/kim/tmp/my_project_name/bin/console:27
```

When I debug, then in PhpDumper::dumpValue the $value is of class `Symfony\Component\DependencyInjection\Definition`

**Comment by nicolas-grekas** [comment] 2018-09-22 21:08
Duplicate of #28296 and #28304, already fixed in 3.4-dev. Will be fixed in 3.4.16.
Thanks for the report.

**Closed by nicolas-grekas** 2018-09-22 21:08 UTC
