### ISSUE TITLE
Test failing in Process component

### ISSUE THREAD

**Issue by arnaugm** [symfony/symfony#12643] opened 2014-11-29 10:49 UTC
Running
```
phpunit src/Symfony/Component/Process
```
I got the error
```
There was 1 failure:

1) Symfony\Component\Process\Tests\SigchildEnabledProcessTest::testPTYCommand
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'foo
+sh: 1: 3: Bad file descriptor
 '

/home/arnau/code/symfony/src/Symfony/Component/Process/Tests/AbstractProcessTest.php:433
```
Symfony branch: 2.7
OS: Ubuntu 14.04.1 LTS
PHP: 5.5.9-1ubuntu4.5
PHPUnit: 3.7.20

**Comment by stof** [comment] 2015-01-18 12:17
@romainneutron can you have a look at this ?

**Comment by Kryniol** [comment] 2015-04-09 20:45
Same here.

OS: Ubuntu 14.04
PHP: 5.5.9-1ubuntu4.7
PHPUnit: 4.5.1
Symfony 2.7

**Comment by xabbuh** [comment] 2015-04-10 07:54
@Kryniol Do you get more detailed output when running the tests with the `-v` option?

**Comment by Kryniol** [comment] 2015-04-10 08:34
@xabbuh Nope, verbose option doesn't add anything useful to the output when it's a matter of failed test.

**Comment by jaytaph** [comment] 2015-04-10 10:02
The issue might not be Symfony related.  It occurs during `proc_open` with `pty` as file descriptors. This case is disabled in the php source (http://lxr.php.net/xref/PHP_5_6/ext/standard/proc_open.c#65), and is not configurable to be overridden (something like a `--enable-pts` configure). However, the debian/ubuntu package (i've tested too on 14.04LTS, which uses php 5.5.9), adds a patch that overrides this [112-proc_open.patch](http://code.openhub.net/file?fid=X1v7MmCBf78QeIJqiwW24HP6i_A&cid=4tiEWEZS67E&s=&projSelected=false#L0).

It might be possible that something is wrong in the php code itself, rather than Symfony in these cases. I can add an strace output with some more info, but haven't got time enough to dive into it deeper at the moment.

**Comment by jaytaph** [comment] 2015-04-13 09:04
I've taken a look in the (a lot of!) code and straces.. and found this to be a bug in the php core.

The issue is as follows (hopefully i can explain it correctly):

When using `enhanceSigchildCompatibility` and `isSigchildEnabled` is true, the Process component will add a 4th file descriptor (which is always a pipe, even when the rest are PTYs). Also, the actual command that will be run in the process will be expanded to  `(cmd) 3>/dev/null; code=$?; echo $code >&3; exit $code`. This is for a workaround when `--enable-sigchild` is enabled in PHP.


Now, when PTY is enabled in PHP (something that is by default not enabled, nor possible to enable without patching, something debian/ubuntu does), additional things will happen in the PHP `proc_open` function:

For every descriptor we pass to `proc_open`, and when a descriptor is called `pty`, it will open `/dev/ptmx`. This is a device that lets us create pseudo-terminals. At this point, it's extremely likely that the file descriptor for that file will be `3`, as most of the time no additional files are open at that point. This file handle is stored in the variable `dev_ptmx`. This is important. Futhermore, the other end-point (stored in `slave_pty`) is also opened, and most likely will have file descriptor 4.

These file descriptor is used as the parent and slave endpoints, and are `dup()`ed for each descriptor that uses `pty`.

Most likely, you will get something like pairs of `5,6`, `7,8`, `9,10` etc.

Once all the descriptors you have passed are processed, the `proc_open` will `fork()` and the child process starts with some cleanup. One of the things it does, is iterate all descriptors, closes unneeded endpoints (like the end of pipes that the parent process will use for writing). At the same time, it will also "correct" the slave / childend descriptors: when allocated, they might got file-descriptor `6`, but it actually should be file descriptor number `0` for instance. It uses the `dup2()` C call for this. Since most likely you will be piping `STDIN`, `STDOUT` and `STDERR`, changes it will `dup2` the filedescriptors to file descript 0, 1 and 2, and it will close the original descriptors.

If you have other file descriptors, like we do in case of our `isSigchildEnabled()` functionality where a additional pipe on file descriptor 3 is added (the first filedescriptor passed `STDERR`), it too will have be correctly `dup2()`ed by `proc_open`.

At this point, another this will be done: it will try and close the original `dev_ptmx` and `slave_pty` file descriptors. Only problem is that these file descriptors could already "closed" by `dup2()` when another descriptor will be using the same descriptors. This is exactly what happens in our code: we create an extra file-descriptor 3, which is opened and `dup2()`ed, and later on, PHP tries to close file descriptor 3, thinking it's still the old `dev_ptmx`.



One way to check this, is to open at least one file before running your process:

        $a = fopen("/tmp/foo", "w");

In this case, it will work properly, as `proc_open` internally will open `/dev/ptmx` as filedescriptor 4, instead of 3.


Reproduce
---------
First, you must have a PTY enabled PHP version. Debian/Ubuntu will work, otherwise you have to patch php and compile yourself (use the given patch noted above).

Code:

        <?php

        use Symfony\Component\Process\Process;

        include "vendor/autoload.php";

        class ProcessInSigchildEnvironment extends Process
        {
            protected function isSigchildEnabled()
            {
                return true;
            }
        }

        // Enable to NOT get the error message
        //$a = fopen("/tmp/test.txt", "w");

        $process = new ProcessInSigchildEnvironment('echo "foo"');
        $process->setEnhanceSigchildCompatibility(true);
        $process->setPty(true);
        $process->run();

        var_dump($process->getStatus());
        var_dump($process->getOutput());



Fix
---
It's not a fix that Symfony should do. Theoretically we could open a dummy file to make sure `/dev/ptmx` is never opened as FD 3, but the issue should be fixed in PHP instead. Most likely, this will not be hard, as it probably means we need to close the ptmx file descriptors before `dup2()` filedescriptors.

**Comment by ewgRa** [comment] 2015-10-21 07:49
I think it is php bug and must be fixed in php.

I write phpt test that want attach to bug report: https://gist.github.com/ewgRa/81d1d7b644c520e23ed6#file-bug69442-phpt

Can anybody run it and say results? Simple "phpunit bug69442.phpt". Most interesting about successful run, but failure case also interesting to check that it fail same as for me.

For me it is fail: 
```
phpunit ~/bug69442.phpt
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

F

Time: 63 ms, Memory: 2.75Mb

There was 1 failure:

1) /home/ewgra/bug69442.phpt
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 type 1: 
-string(0) ""
+string(31) "sh: 1: 3: Bad file descriptor
+"

@@ @@
 type 3: 
-string(2) "0
-"'
+string(0) ""'

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

If I uncomment fix, it run successful.

**Comment by stof** [comment] 2015-10-21 09:21
@ewgRa it should be reported to PHP to be fixed in newer versions, but it would still be great to find a workaround for existing versions in the component (so that the component works on these versions)

**Comment by jaytaph** [comment] 2015-10-21 09:28
@stof: Opening a dummy file before proc_open in order to make sure proc_open does not use FD 3 will not trigger the issue. I actually might create the php PR if I have some time these days (it's a fairly trivial fix)

**Comment by ewgRa** [comment] 2015-10-21 09:41
@stof it is already reported by @jaytaph, https://bugs.php.net/bug.php?id=69442 . I just want attach phpt test for it and maybe look deeper inside this bug. I think php team can say that this is Ubuntu problem, because they write wrong patch and there is open bug for Ubuntu team needed.

Fix that suggest @jaytaph work ($a = fopen("/tmp/test.txt", "w");), but looks like a magic with side affects, maybe there is can be less magic fix.

Will work on it while @jaytaph prepare PR.

**Comment by jaytaph** [comment] 2015-10-21 10:31
@ewgRa I can confirm your PHPT works, including the fix (sidenote: didn't know phpunit could run phpt files!).

>I think php team can say that this is Ubuntu problem, because they write wrong patch and there is open bug for Ubuntu team needed.
Actually, it's not a Ubuntu problem. The patch simply enables the PTY code that the PHP team has written. However, the actual code is not tested and will be troublesome to actually test, as this means that PHP should be patched (i'd rather see an `--enable-pty` option in PHP, which is trivial to add). I'll just add a patch, and see that PHP core thinks about it..

For Symfony2 and current PHP versions, I really don't think there is another way of making sure that proc_open does not use file-descriptor 3, is to make sure WE use it instead. Opening a file (ANY file) would eat up the file descriptor so at least simple enough to create as a workaround.

**Comment by jaytaph** [comment] 2015-10-21 11:29
I've created a PR in php-src: https://github.com/php/php-src/pull/1588

**Comment by ewgRa** [comment] 2015-10-21 12:26
:+1: lets wait response

Can you add info about PR to https://bugs.php.net/gh-pull-add.php?bug_id=69442 ?

**Comment by ewgRa** [comment] 2015-10-21 12:57
About patch symfony Component.

Fix like 
```
$a = fopen("php://fd/0", "r"); 
```
works for me and seems have less side affects, because there is no access to filesystem and all problems with dir exists, rights and so on.

Interesting that if fix looks like this:
```
$a = fopen("php://fd/0", "r"); 
$a = fopen("php://fd/0", "r"); 
```
it is not working

If like this:
```
$a = fopen("php://fd/0", "r"); 
$b = fopen("php://fd/0", "r"); 
```
it is working

If like this:
```
$a = fopen("php://fd/0", "r"); 
$a = fopen("php://fd/0", "r"); 
$a = fopen("php://fd/0", "r"); 
```
it is working

But I think fix with one time call of fopen will be work and there is no situation, when similar code that can broke fix will be called.

**Comment by ewgRa** [comment] 2015-10-21 12:59
What do you think @jaytaph ? Is open php://fd/0 better and will work?

**Comment by jaytaph** [comment] 2015-10-21 13:16
I've tried `php://fd/0`, and also found the issue you encountered. The first fopen() will actually use FD 3 (which is what we want). On the next line, the `fopen()` gets FD4 (the next available one). However, since we use the same variable, the "old" resource is freed up, meaning it will internally close file descriptor 3 again,  which makes it free again (which is exactly what we want to avoid). 

So you would get the same issue on every even number of fopen calls you make (provided you assign them directly the same variable).

But for your question: `php://fd/0` is indeed more efficient: it will use a `dup()` system call instead of an actual `open()` call.

**Comment by ewgRa** [comment] 2015-10-21 14:25
@jaytaph big thanks for explanations. More clearly now.

Will you create PR to Symfony component?

**Comment by ewgRa** [comment] 2015-11-10 00:41
PR for this issue - #16510

**Closed** 2015-11-10 10:52 UTC
Labels: Process
