### ISSUE TITLE
[Aborted] at \\vendor\\symfony\\console\\Helper\\QuestionHelper.php:137

### ISSUE THREAD

**Issue by fabyo** [symfony/symfony#34754] opened 2019-12-02 13:24 UTC
**Symfony version(s) affected**: symfony/console  v4.4.1

**Description**  

Updated php to 7.4 question function no longer works, throwing exception Aborted

run laravel (v6.5.2) command "$this->confirm('message')"

local.ERROR: Aborted. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Aborted. at C:\
oot\\finances\\vendor\\symfony\\console\\Helper\\QuestionHelper.php:137)

**Comment by xabbuh** [comment] 2019-12-02 13:40
Is that on Windows and thus the same as #34702?

**Comment by chalasr** [comment] 2019-12-02 13:54
> at C:
oot\finances\vendor\symfony\console\Helper\QuestionHelper.php:137)

I think so. Duplicate of #34702

**Closed by chalasr** 2019-12-02 13:54 UTC
Labels: Bug, Console, Status: Needs Review, Status: Waiting feedback
