### ISSUE TITLE
[3.0] CLI debug:container does not work

### ISSUE THREAD

**Issue by malas** [symfony/symfony#16930] opened 2015-12-09 19:45 UTC
php bin/console debug:container command outputs an error:
>  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  Unable to parse file "/home/my-project-path/var/cache/dev/appDevDebugProjectContainer.xml"
                                                                               
>  [InvalidArgumentException]
  [ERROR 522] Validation failed: no DTD found ! (in n/a - line 2, column 46) 
  [ERROR 9] PCDATA invalid Char value 24 (in n/a - line 26, column 20)
  [ERROR 9] PCDATA invalid Char value 24 (in n/a - line 1907, column 23)

tried to clear the cache, but the problem persists.
Symfony v3.0.0 standard edition was used on PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)

Actual XML in the path defined begins with:
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
```

**Comment by xabbuh** [comment] 2015-12-09 20:03
On a clean Symfony 3.0 installation I cannot reproduce your issue. How did you set up your application? Is it a fresh installation? Or did you update an existing one?

**Comment by malas** [comment] 2015-12-09 20:30
It is a fresh installation done via composer, nothing added nor removed.

**Comment by xabbuh** [comment] 2015-12-09 20:35
Unfortunately, I cannot reproduce your issue. Can you please show the output of `composer show -i` in your project?

**Comment by malas** [comment] 2015-12-09 20:38
There you go:
> doctrine/annotations                 v1.2.7  Docblock Annotations Parser
doctrine/cache                       v1.5.2  Caching library offering an ob...
doctrine/collections                 v1.3.0  Collections Abstraction library
doctrine/common                      v2.5.2  Common Library for Doctrine pr...
doctrine/dbal                        v2.5.2  Database Abstraction Layer
doctrine/doctrine-bundle             1.6.1   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.2.2   Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0  Common String Manipulations wi...
doctrine/instantiator                1.0.5   A small, lightweight utility t...
doctrine/lexer                       v1.0.1  Base library for a lexer that ...
doctrine/orm                         v2.5.2  Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.2  Composer script handling your ...
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
monolog/monolog                      1.17.2  Sends your logs to files, sock...
paragonie/random_compat              1.1.3   PHP 5.x polyfill for random_by...
psr/log                              1.0.0   Common interface for logging l...
sensio/distribution-bundle           v5.0.2  Base bundle for Symfony Distri...
sensio/framework-extra-bundle        v3.0.11 This bundle provides a way to ...
sensio/generator-bundle              v3.0.1  This bundle generates code for...
sensiolabs/security-checker          v3.0.2  A security checker for your co...
swiftmailer/swiftmailer              v5.4.1  Swiftmailer, free feature-rich...
symfony/monolog-bundle               v2.8.2  Symfony MonologBundle
symfony/phpunit-bridge               v2.8.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            v1.0.0  Symfony polyfill for intl's IC...
symfony/polyfill-mbstring            v1.0.0  Symfony polyfill for the Mbstr...
symfony/polyfill-php56               v1.0.0  Symfony polyfill backporting s...
symfony/polyfill-php70               v1.0.0  Symfony polyfill backporting s...
symfony/polyfill-util                v1.0.0  Symfony utilities for portabil...
symfony/swiftmailer-bundle           v2.3.9  Symfony SwiftmailerBundle
symfony/symfony                      v3.0.0  The Symfony PHP framework
twig/twig                            v1.23.1 Twig, the flexible, fast, and ...

**Comment by javiereguiluz** [comment] 2015-12-10 12:14
I cannot reproduce it either:

```
$ symfony new project

 Downloading Symfony...

    4.93 MB/4.93 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 3.0.0 was successfully installed. Now you can:

[...]

$ cd project/
$ php bin/console debug:container

Symfony Container Public Services
=================================

 -------------------------------------------------------------------- --------------------------------------------------------------------------------------------
  Service ID                                                           Class name
 -------------------------------------------------------------------- --------------------------------------------------------------------------------------------
  annotation_reader                                                    Doctrine\Common\Annotations\CachedReader
  assets.context                                                       Symfony\Component\Asset\Context\RequestStackContext
  assets.packages                                                      Symfony\Component\Asset\Packages
  cache_clearer                                                        Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer
  cache_warmer                                                         Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate

[...]
```

**Comment by javiereguiluz** [comment] 2015-12-10 12:17
And this is my Composer output:

```
$ composer show -i
doctrine/annotations                 v1.2.7  Docblock Annotations Parser
doctrine/cache                       v1.5.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.3.0  Collections Abstraction library
doctrine/common                      v2.5.1  Common Library for Doctrine projects
doctrine/dbal                        v2.5.2  Database Abstraction Layer
doctrine/doctrine-bundle             1.6.0   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.2.2   Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         v2.5.2  Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.2  Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
monolog/monolog                      1.17.2  Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat              1.1.0   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/log                              1.0.0   Common interface for logging libraries
sensio/distribution-bundle           v5.0.2  Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.11 This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.0.0  This bundle generates code for you
sensiolabs/security-checker          v3.0.2  A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.1  Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               v2.8.2  Symfony MonologBundle
symfony/phpunit-bridge               v2.8.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            v1.0.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.0.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.0.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.0.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.0.0  Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.3.9  Symfony SwiftmailerBundle
symfony/symfony                      v3.0.0  The Symfony PHP framework
twig/twig                            v1.23.1 Twig, the flexible, fast, and secure template language for PHP
```

There are differences in some Doctrine versions and in `sensio/generator-bundle` version. Why?

**Comment by malas** [comment] 2015-12-10 12:18
after the command failed i tried to update deps - composer :update, but that did not help.

**Comment by mkluczka** [comment] 2016-01-17 17:10
I have the same issue, the reason - invalid characters in parameter secret. My secret: "fdlkjah3wi4uy0rawtrgi4b\e[13~2\e[15~9q7g245!". After changing it to [a-zA-Z0-9]+ no error occurs. My symfony version is 2.6.11

**Comment by xabbuh** [comment] 2016-01-18 07:44
@mkluczka Please update your application to a supported Symfony version (the secret you mentioned works like a charm on Symfony 3.0).

@malas I am closing here for now. Feel free to provide more information about how to reproduce your issue and we can reopen here again.

**Closed by xabbuh** 2016-01-18 07:44 UTC
Labels: Unconfirmed

**Comment by adamelso** [comment] 2016-08-01 15:53
I had the same issue. It's reproducable if one of the container parameters is set to `\e[C` - the result of me accidently pressing control keys when providing distribution parameters during composer install.

**Comment by vibby** [comment] 2017-04-27 15:57
I had same problem with Sf 3.2.7
My paramters’secret line was :
```
    secret: !!binary 4oCmwqFsam9keC5qXHtqw4nCvsK84oCUaWVvcMvLb8uYxY8=
```
Removing the «!!binary» fixed it

**Comment by bburnichon** [comment] 2018-01-24 15:29
Actually, removing `!!binary` is not a fix, it just removes binary parameter.

**Comment by vibby** [comment] 2018-01-24 15:51
In other words, not defining the secret as a binary fixed it, for me … is that wording okay for you, @bburnichon ?

**Comment by bburnichon** [comment] 2018-01-24 16:16
that's exactly that. I have an issue now, I have to declare a real binary secret (I can not change it) and can not run `debug:container`
