### ISSUE TITLE
ObjectChoiceList with 2.7

### ISSUE THREAD

**Issue by robcaw** [symfony/symfony#16561] opened 2015-11-16 16:46 UTC
Updating to 2.7 breaks a few of my forms that use `choice_list` with an `ObjectChoiceList`:
```
'choice_list' => new ObjectChoiceList($choices, 'label', array(), null, 'value'),
```

results in:
```
LogicException in Form.php line 374:
The form's view data is expected to be an instance of class Acme\Model\Choice, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Acme\Model\Choice.
```

I understand that `choice_list` is deprecated, so I've tried using:

```
 'choices' => $choices,
 'choices_as_values' => true,
```

as well as using a `DefaultChoiceListFactory` as described in https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md, but I'm not really getting anywhere.

Is there documentation anywhere for how to use objects as choices in 2.7?

**Comment by robcaw** [comment] 2015-11-17 10:00
I think what I'm experiencing is related to #14877. The upgrade to 2.7 requires me to change `data_class` to `null` as per the exception message above. But, setting the same choice field to `expanded` requires the `data_class` to be set.

**Comment by XWB** [comment] 2015-11-26 09:28
https://github.com/symfony/symfony/pull/16679

**Comment by webmozart** [comment] 2015-11-26 11:03
This seems to be a duplicate of #14877.

**Closed by webmozart** 2015-11-26 11:03 UTC
Labels: Form
