### ISSUE TITLE
[Dependency Injection] No "Circular reference" warning for "!tagged" syntax

### ISSUE THREAD

**Issue by bkrukowski** [symfony/symfony#27696] opened 2018-06-24 12:48 UTC
**Symfony version(s) affected**: 4.1.0

**Description**  

Symfony does not throw an exception `Circular reference detected for service "%s", path: "%s".` whenever I am using `!tagged` syntax.

**How to reproduce**

1) Create the following class:

```php
<?php

namespace App\Services;

class MyService
{
    private $services;

    public function __construct(iterable $services)
    {
        $this->services = $services;
    }
}
```

2) Create the following configuration:

```yml
    App\Services\MyService:
        arguments: ['@App\Services\MyService']
```

Now we will get `Circular reference detected for service "App\Services\MyService", path: "App\Services\MyService -> App\Services\MyService".`, it is fine.

3) Replace the configuration by the following code:

```yml
    App\Services\MyService:
        arguments:
          - !tagged my-service
        tags:
            - {name: 'my-service'}
```

Symfony does not warn by exception about circular dependency. My real example was much more complex and actually it was my bug, but anyway would be nice to be informed about bug by semantic exception.

**Possible Solution**  

Throw `Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException` in such cases, or add simple console commend to check if we have circular dependency.

**Comment by ro0NL** [comment] 2018-06-24 18:03
duplicate of #25840?

**Comment by nicolas-grekas** [comment] 2018-06-25 09:04
As soon as the circular loop is lazy, it's not a circular reference anymore as instantiation is possible.
As explained in #25840, its then your responsibility to deal with the case, not something Symfony can do for you. Thanks for posting.

**Closed by nicolas-grekas** 2018-06-25 09:04 UTC
Labels: Bug, DependencyInjection, Status: Needs Review

**Comment by stof** [comment] 2018-06-26 08:11
@nicolas-grekas maybe we could still warn if a service has a direct lazy reference to itself ?

**Comment by bkrukowski** [comment] 2018-06-26 08:52
@nicolas-grekas I agree, it is my responsibility, but IMHO circular dependencies are bad practice and make code more complex. It is understandable that Symfony cannot start throwing exceptions in this case, because of BC, but it could be configurable and disabled in default.

**Comment by nicolas-grekas** [comment] 2018-06-26 08:57
@stof what kind of warning can we trigger? A compiler log? Or you have something else in mind?
We could make a special case for immediate circular references found in `TaggedIteratorArgument`.
That's a very specific case though and there are so many other (legitimate) ways to create circular refs, we should not try to detect them all IMHO.
