### ISSUE TITLE
[Console] DX: Catch Fatal errors in Command collection

### ISSUE THREAD

**Issue by beberlei** [symfony/symfony#23610] opened 2017-07-21 09:26 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

With PHP 7 we can now catch fatal errors. The console collects all commands from all bundle directories, but what if one of them has a fatal error (for whatever reason), then all other commands cannot be executed as well. If the fatal error is catched, maybe a warning printed to the screen and a dummy command registered instead that fails and shows the fatal error, this could be much improved for the developer experience.

**Comment by nicolas-grekas** [comment] 2017-07-21 09:33
That is fixed by #22734, isn't it?

**Comment by beberlei** [comment] 2017-07-21 09:37
@nicolas-grekas could be, i am only on 3.3 - you can close if you think its fixed :)

**Comment by beberlei** [comment] 2017-07-21 09:38
@nicolas-grekas not entirely actually, it still breaks if i just call "app/console" to list all commands.

**Comment by chalasr** [comment] 2017-07-21 09:55
The issue is less impacting with lazy commands (non lazy ones are still supported though, autoconfigured or convention based) as it breaks when the failing command is executed, but also using `list` which requires loading all commands.

I think it makes sense to keep displaying the list in this case (displaying the exception as a warning, I often use `bin/console` as a health check) and not prevent running commands which are fine (for non lazy ones).

**Comment by nicolas-grekas** [comment] 2017-08-06 18:23
@chalasr would you be up for a PR here?

**Comment by chalasr** [comment] 2017-08-06 18:52
@nicolas-grekas Sure

**Comment by chalasr** [comment] 2017-08-09 08:56
See #23836

**Closed** 2017-08-10 06:58 UTC
Labels: Console, DX, Enhancement
