### ISSUE TITLE
Log messages have placeholders

### ISSUE THREAD

**Issue by ged15** [symfony/symfony#19944] opened 2016-09-15 15:38 UTC
Hello!

I just tried to run Symfony 3.1.4 and when I look at the logs I see the following message:

```
[2016-09-15 15:29:58] request.INFO: Matched route "{route}". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
```

Is it expected that the message contains the placeholder `{route}` instead of the actual route name?

**Comment by Taluu** [comment] 2016-09-15 15:44
It's actually the dump from monolog that does that. It doesn't replace automatically (and I guess this is a feature too)

**Comment by Tobion** [comment] 2016-09-15 16:20
Duplicate of https://github.com/symfony/symfony-standard/issues/981

**Closed by Tobion** 2016-09-15 16:20 UTC
