### ISSUE TITLE
[Monolog] Deprecation about a final class

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#48023] opened 2022-10-28 12:47 UTC
### Symfony version(s) affected

6.2

### Description

While updating Symfony Demo to Symfony 6.2-dev (see https://github.com/symfony/demo/pull/1362) we found this indirect deprecation:

```
1x: The "Monolog\Logger" class is considered final. It may change without
further notice as of its next major version. You should not extend it
from "Symfony\Bridge\Monolog\Logger".
```

@stof commented that:

> for the Symfony\Bridge\Monolog\Logger, this should be reported to Symfony to find a way to stop extending that class (or to Monolog to revert that decision if we cannot find another way).

### How to reproduce

Updating a Symfony app to 6.2-dev should be enough to see the deprecation message.

**Comment by derrabus** [comment] 2022-10-28 13:20
Yes, I think we should get rid of that class completely.

**Comment by rafael-neris** [comment] 2022-10-31 05:00
Hey @javiereguiluz, thank you for good issue, I have a suggestion, this is my first contribute to this wonderful framework, can you review and send me a feedback, please?

**Comment by rafael-neris** [comment] 2022-10-31 06:14
Hello @javiereguiluz  , how are you? Can you review my suggestion, please? This is my first PR to Symphony, feedbacks are welcome! :) Thank you

**Comment by derrabus** [comment] 2022-10-31 07:34
Thank you for your contribution. Please don't ping core team members for a review. Someone will pick the PR up if they feel like they can perform a review on the changes.

**Comment by xabbuh** [comment] 2022-10-31 14:00
this looks like a duplicate of #47096

**Closed as not planned by xabbuh** 2022-10-31 14:00 UTC
Labels: Bug, MonologBridge, Status: Needs Review
