### ISSUE TITLE
PDOSessionHandler stream usage in 2.6 introduces PHP Bug #40913

### ISSUE THREAD

**Issue by brianfreytag** [symfony/symfony#12834] opened 2014-12-03 17:53 UTC
There is a PHP bug that was submitted in 2007 that still applies today.

https://bugs.php.net/bug.php?id=40913

In commit 1bc6680, the Session data column was updated to a PDO::PARAM_LOB from a base64 encoded PDO::PARAM_STR.

This now introduces the PHP Bug 40913 linked above. Instead of returning a Resource, it returns a string. This makes it impossible to load the sessions correctly. 

Since it is returning $session[0][0] as a string instead of a resource, `is_resource($session[0][0])` returns false, and then it returns a string, and then PHP doesn't know what to do with it, so authentication breaks.

**Comment by Tobion** [comment] 2015-03-17 18:30
@brianfreytag I think you mixed two different things here. The data is saved in a BLOB.
I guess you are talking about the ID which might be saved in a VARBINARY. See https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L221

That the data is a string instead of a resource should not be a problem. But the problem is probably that ODBC behaves different from pdo_mysql that I tested it with when dealing with VARBINARY.
Can you please test if changing the ID column to `VARCHAR(128)` solves the problem?

**Comment by fabpot** [comment] 2015-10-05 13:09
Closing as there is no feedback from the reporter.

**Closed by fabpot** 2015-10-05 13:09 UTC
Labels: HttpFoundation
