### ISSUE TITLE
NumberToLocalizedStringTransformer gives inconsistent results

### ISSUE THREAD

**Issue by flack** [symfony/symfony#26238] opened 2018-02-19 22:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

I am using `symfony/form` as a standalone component in an application (as a replacement for `HTML_Quickform`). Since I switched to symfony form, I have this problem that in `NumberType` fields, when someone enters e.g. `9,90`, it sometimes transforms this to `9` and sometimes to `9.9` (and only `9.9` is correct in the `de_DE` locale I'm using). I've tracked this down to this code failing:

```php
$formatter = new NumberFormatter('de_DE', NumberFormatter::DECIMAL);
var_dump($formatter->parse('9,90'));
```

This sometimes outputs `float(9)` and sometimes `float(9.9)`. I realize that the error doesn't seem to come from Symfony itself, but this is basically what `NumberToLocalizedStringTransformer` does internally, so I was wondering: Is this a known issue with some operating systems (I use Debian 8 on the machine where it happens), and if so, is there a mitigation, or did I maybe overlook some required setting in the config that I would need to make this work?

**Comment by cybernet** [comment] 2018-02-20 07:55
maybe if you tryied on another PHP version ...

**Comment by derrabus** [comment] 2018-02-20 14:17
Is the `intl` extension enabled in your php environments?

**Comment by flack** [comment] 2018-02-20 14:31
@derrabus yes, `intl` is enabled and works in all other matters. Only `parse` causes problems

**Comment by nicolas-grekas** [comment] 2018-02-27 17:32
This reminds me that `setlocale()` is not thread safe. Could this be the root cause somehow?
The random aspect is really strange, not sure we can debug it without your help.

**Comment by flack** [comment] 2018-02-27 17:40
@nicolas-grekas yes, I thought about `setlocale`, too, and the server uses this in other contexts. The thing is, I don't think it should interfere, because I instantiate `NumberFormatter` with a hardcoded `de_DE`, so normally, it shouldn't have to look up the locale anywhere. I've since found this ticket: https://bugs.php.net/bug.php?id=71008, so at least it looks like I'm not the only one seeing it. 

But yes, the random aspect of it is quite frustrating. I currently have a cronjob running on the server that runs the code from the OP every minute and sends me a mail when the error occurs. I didn't receive a notification in the last couple of days, before that, I received a handful in the space of ten minutes, before that, it was quiet for a day. It's really hard to pin down. But if you want me to run any tests, just let me know!

**Comment by xabbuh** [comment] 2018-09-23 12:00
I am closing here for now as we cannot do anything without being able to reproduce. But please comment if you can provide further information that would be helpful for us.

**Closed by xabbuh** 2018-09-23 12:00 UTC
Labels: Bug, Form, Status: Needs Review
