### ISSUE TITLE
Fatal error: Using $this when not in object context - Unescaper.php on line 53

### ISSUE THREAD

**Issue by aserra** [symfony/symfony#21157] opened 2017-01-04 11:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes

In PHP Version 5.3.29
`use Symfony\Component\Yaml\Yaml;`
`$translate =  Yaml::parse( file_get_contents( PATH_TRANSLATE ) );`

Returns:
`Fatal error: Using $this when not in object context in /.../yaml/Unescaper.php on line 53`

Also, I tried: 

`use Symfony\Component\Yaml\Yaml;`
`$yaml = new Yaml();`
`$translate =  $yaml->parse( file_get_contents( PATH_TRANSLATE ) );`

**Comment by xabbuh** [comment] 2017-01-04 11:24
Which Symfony version (or version of the Yaml component) do you use?

**Comment by aserra** [comment] 2017-01-04 11:41
I try the master just now. I'm not using under Symfony.

**Comment by xabbuh** [comment] 2017-01-04 12:51
Well, you will have to use 2.7 or 2.8 if you are still stuck with PHP 5.3. Symfony dropped support for PHP versions < 5.5 with Symfony 3.0.

**Comment by xabbuh** [comment] 2017-01-06 05:50
Closing here for now as this looks like an issue with the selected package version. 

@aserra Feel free to comment when you are able to reproduce your issue using Symfony 2.7 or 2.8 and we can consider to reopen.

**Closed by xabbuh** 2017-01-06 05:50 UTC
Labels: Bug, Status: Needs Review, Unconfirmed, Yaml
