### ISSUE TITLE
CacheClearCommand does not dispatch `console.terminate`

### ISSUE THREAD

**Issue by ricardodnb** [symfony/symfony#28701] opened 2018-10-03 11:30 UTC
**Symfony version(s) affected**: 3.4.14

**Description**  
I have an event listener for `console.terminate` declared in  a service but it wont get executed after `cache:clear` terminates because the listeners are being cleared from `EventDispatcher` during the execution.

The project was migrated from symfony 2.8 to 3.4

Cache clear does not allow console.terminate listeners anymore?

**How to reproduce** 
- Add a listener for `console.terminate` on services.yml service definition
- Log the listeners from event dispatcher before cache clear code executes - Listener is there
- Run cache:clear command 
- Listener is not called because when `dispatch` is called the listener is no longer there.

**Possible Solution**  
I think the problem is this line resetting the `EventDispatcher`, what is the main purpose for this set of a new instance of eventDispatcher on the application?
```
// The current event dispatcher is stale, let's not use it anymore
$this->getApplication()->setDispatcher(new EventDispatcher());
```

**Comment by nicolas-grekas** [comment] 2018-10-03 11:43
That's by design yes. It kinda worked before but wasn't really: the way `cache:clear` works is by loading the current container first (the to be cleared one) firing the before-command events (still using the to be cleared services) then clearing the cache directory and reloading the newly updated container. Calling any event past this point would make their listener see half the events (only the post-commands one), leading to a broken state for many listeners that expect to be called both before and after the command.

**Comment by nicolas-grekas** [comment] 2018-10-03 12:53
I'm closing as explained.

**Closed by nicolas-grekas** 2018-10-03 12:53 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review
