### ISSUE TITLE
[Form] Empty root form name fails with PUT method

### ISSUE THREAD

**Issue by jbenezech** [symfony/symfony#19017] opened 2016-06-10 03:57 UTC
A form created like this will result in an extra data error

```
        $form = $this->get('form.factory')  
            ->createNamed('',  
            ArticleType::class,  
            $article,  
            [  
                'action' => $this->generateUrl(  
                    'article_update',  
                    [  
                        'article' => $article->getId()  
                    ]  
                ),  
                'method' => 'PUT',  
            ]  
        );  
```

It seems that the RequestHandler will submit the form with all request parameters in case of an empty form name (which includes the hidden _method field)

```
if ('' === $name) {
    $params = $request->request->all();
    $files = $request->files->all();
}
```

The submit method of the Form doesn't seem to do any particular check for that special parameter.

A workaround is to set allow_extra_fields to true in the form

**Comment by BboyKeen** [comment] 2017-05-19 21:31
I can confirm. I just lost a few hours on this one today.
If someone can orient me, I'll be glad to make a PR

**Comment by HeahDude** [comment] 2017-07-30 12:06
I can't find an easy fix for this, since the `_method` field is the `HttpFoundation` responsibility.

Maybe it could acceptable to "remove" the parameter instead of just "getting" it here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1215.
Otherwise we would need to add a new form listener to do the job :/.

**Closed** 2019-02-08 12:09 UTC
Labels: Bug, Form, Status: Reviewed
