### ISSUE TITLE
[Dependency-Injection] OPcache preload-file not being generated

### ISSUE THREAD

**Issue by Kleinkind** [symfony/symfony#34897] opened 2019-12-09 17:34 UTC
Hello :)

**Symfony version(s) affected**: >= 4.4.0

**Description**  
We tried to enable opcache preloading on php 7.4 but the `App_KernelProdContainer.preload.php` file is not being generated. For our cache we use a custom directory outside of the project-directory. This is accomplished by overriding `getCacheDir` in the Kernel. If we use the default implementation of `getCacheDir` the generated cache contains the preload file.

**How to reproduce**  
- Override the Kernels `getCacheDir`-Function and return a custom cache-dir outside of the projects path.
```php
public function getCacheDir(): string
{
	# different from kernel.project_dir
    return '/var/application/cache/'.$this->environment;
}
```
- run `bin/console cache:clear --env=prod`
- no preload-file present under `/var/application/cache/prod/`

**Possible Solution**  
In the PhpDumper-Class the autoload-file for the project is determined in the `getAutoloadFile`-method. The autoloader-file is only returned if it's path matches the `$this->targetDirRegex`, which is based on the target directory for the cache. This regex would match any autoloader contained in two directories higher than the cache-dir itself. Therefore it works if your cache is stored in `%PROJECT_DIR%/var/cache/prod`, but not if it is stored somewhere else.
The determination of the autoloader should therefore also/only include any files found under `kernel.project_dir`.
If my assumptions are correct I would happily provide a pull-request and try to fix this.

**Additional context**  
- We use `/var/application/cache` for our cache and `/var/www/symfony` for the project itself.
- We use docker's bind-mount to mount the project into the container (on dev, in production the code is contained in the image) and a standard docker volume to share the cache between different services.

**Comment by nicolas-grekas** [comment] 2019-12-10 17:53
Duplicate of #34750 and #34611, fixed #34757.

**Closed by nicolas-grekas** 2019-12-10 17:53 UTC
Labels: Bug, DependencyInjection, Status: Needs Review

**Comment by guilliamxavier** [comment] 2020-07-08 15:51
This is fixed in the case where both dirs are subdirs of the same hierarchy (`/var/**` in the reported context), but
I'm still having the issue (Symfony 4.4.10, PHP 7.4.7) in a case where the dirs paths don't have a common prefix (beyond the root):
  project dir: `/usr/src/app`
    cache dir: `/var/app/cache`
(note: forcing the parameter `container.dumper.inline_class_loader` to `true` doesn't seem to make a difference).
Is that an absolute limitation?

**Comment by nicolas-grekas** [comment] 2020-07-08 15:55
I think so yes.

**Comment by guilliamxavier** [comment] 2020-07-08 16:01
OK, that's unfortunate, but thanks for confirming 👍

**Comment by chdeliens** [comment] 2020-08-12 08:58
@nicolas-grekas Is the limitation a PHP or a Symfony one?

If Symfony: I'm then wondering about the point of being able to override the default `getCacheDir()` if it's not used in the "preload" context? 

Thanks for your feedback on this, as our current container build strategy is having `/app` read-only for the app, then mount a writable `/tmp` folder inside the container.
