### ISSUE TITLE
[Workflow] documentation link is not working

### ISSUE THREAD

**Issue by aledeg** [symfony/symfony#19477] opened 2016-07-29 13:42 UTC
In the https://github.com/symfony/workflow repository, the link to the documentation is not working.
The current link is https://symfony.com/doc/current/components/workflow/introduction.html which returns a 404.

**Comment by stloyd** [comment] 2016-07-29 13:55
It will be correct after official release of Symfony 3.2 in which this component will be introduced, cause if you go to "master" (documentation for upcoming release) you will see it's working: http://symfony.com/doc/master/components/workflow.html

**Comment by lyrixx** [comment] 2016-07-29 13:57
Duplicate of #19423

**Closed** 2016-07-29 13:57 UTC
