### ISSUE TITLE
[PropertyInfo] PhpStan FQSEN error

### ISSUE THREAD

**Issue by vlastv** [symfony/symfony#44431] opened 2021-12-02 21:45 UTC
### Symfony version(s) affected

5.4, 6.*

### Description

PhpStanExtractor incorrect detect class with different namespace. PhpDocExtractor work correct.

#40457

### How to reproduce

```php
<?php

namespace {
    require_once __DIR__ . '/vendor/autoload.php';

    use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
    use Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor;

    $phpDocExtractor = new PhpDocExtractor();
    $phpStanExtractor = new PhpStanExtractor();


    dump(
        $phpDocTypes = $phpDocExtractor->getTypes(B\Dummy::class, 'property'),
        $phpStanTypes = $phpStanExtractor->getTypes(B\Dummy::class, 'property')
    );

    assert($phpStanTypes[0]->getClassName() === 'A\Property');
    assert($phpDocTypes[0]->getClassName() === $phpStanTypes[0]->getClassName());
}


namespace A {
    class Property {

    }

    class Dummy {
        /**
         * @var Property
         */
        public $property;
    }
}

namespace B {
    class Dummy extends \A\Dummy {

    }
}

```

**Comment by Korbeil** [comment] 2021-12-10 15:46
This is duplicate of https://github.com/symfony/symfony/issues/44417 and was fixed in https://github.com/symfony/symfony/pull/44430

**Comment by isypov-andrey** [comment] 2022-03-24 13:12
This bug is actual and not fixed in https://github.com/symfony/symfony/pull/44430
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/9131454/159923413-0d87aea5-b766-4c67-8818-33aed307fbe2.png">
I don't see any changes

**Comment by Korbeil** [comment] 2022-03-24 13:19
Could you share what is your issue and how to reproduce it maybe ?

This bug was fixed and there is a test in the PR to show how I fixed it. Maybe you found a different bug or a new way to get the same issue ?

**Comment by isypov-andrey** [comment] 2022-03-24 13:24
I have exactly the same case as @vlastv. In your test, the full namespace is indicated, but here is the relative one. The problem is with inheritance in another namespace

**Comment by Korbeil** [comment] 2022-03-24 16:34
Are you sure you are up-to-date ?

**Comment by isypov-andrey** [comment] 2022-03-25 09:20
Yes, i ran this code on version property-info v5.4.3
Output:
```
array:1 [
  0 => Symfony\Component\PropertyInfo\Type {#20
    -builtinType: "object"
    -nullable: false
    -class: "A\Property"
    -collection: false
    -collectionKeyType: []
    -collectionValueType: []
  }
]
array:1 [
  0 => Symfony\Component\PropertyInfo\Type {#32
    -builtinType: "object"
    -nullable: false
    -class: "B\Property"
    -collection: false
    -collectionKeyType: []
    -collectionValueType: []
  }
]

Fatal error: Uncaught AssertionError: assert($phpStanTypes[0]->getClassName() === 'A\\Property') in /Users/andrejisypov/Projects/ucheba/ucheba-backend/src/test.php:17
Stack trace:
#0 /Users/andrejisypov/Projects/ucheba/ucheba-backend/src/test.php(17): assert(false, 'assert($phpStan...')
#1 {main}
  thrown in /Users/andrejisypov/Projects/ucheba/ucheba-backend/src/test.php on line 17
```

**Comment by xabbuh** [comment] 2022-03-25 09:42
@isypov-andrey Please open a new issue and provide an example project that allows to reproduce your issue. Thanks!

**Comment by isypov-andrey** [comment] 2022-03-25 12:16
@xabbuh  It seems to me that it is worth reopening this issue, since the problem has not actually been resolved. There are no changes in PR https://github.com/symfony/symfony/pull/44430 except refactoring

**Comment by xabbuh** [comment] 2022-03-25 14:04
Please provide an example application that allows to reproduce and we can consider to reopen.

**Comment by isypov-andrey** [comment] 2022-03-25 14:28
https://github.com/isypov-andrey/property-info-bug

**Comment by isypov-andrey** [comment] 2022-03-30 08:21
@xabbuh @Korbeil Did you check my example?

**Comment by Korbeil** [comment] 2022-03-30 11:15
Thanks for the reproducer, I'll try to fix it as soon as possible.

**Comment by Korbeil** [comment] 2022-03-30 12:25
I think I found the issue and fixed it, could you take a look on the linked pull request @isypov-andrey ?

**Comment by isypov-andrey** [comment] 2022-03-30 12:31
@Korbeil PR solves the problem, thanks for the quick fix!

**Closed as completed** 2022-03-31 16:08 UTC
Labels: Bug, Status: Needs Review, PropertyInfo
