### ISSUE TITLE
[DependencyInjection] support anonymous services as bound defaults

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#26629] opened 2018-03-22 07:07 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

If I do this:

```xml
    <services>
        <defaults public="false" autoconfigure="true" autowire="true">
            <bind key="Imagine\Image\ImagineInterface" type="service">
                <service parent="liip_imagine.imagick">
                    <call method="setMetadataReader">
                        <argument type="service">
                            <service id="App\Infrastructure\Imagine\Metadata\ExifMetadataReader" lazy="true"/>
                        </argument>
                    </call>
                </service>
            </bind>
        </defaults>
    </services>
```

I get `Tag "<bind>" with type="service" has no or empty "id" attribute`. But it should be possible, no?

I'm trying to do it like this since services with parent can't be in a file with defaults bound:
```
Bound values on service "foo" cannot be inherited from "defaults" when a "parent" is set. Move your child definitions to a separate file.
```

This might actually be a bug, not sure.

**Comment by stof** [comment] 2018-03-22 09:27
Anonymous services are not supported for bindings. Define a private service and reference it in the binding.

**Comment by dkarlovi** [comment] 2018-03-22 09:31
@stof so it's not a bug then, but a feature suggestion.

**Comment by nicolas-grekas** [comment] 2018-03-22 14:33
@dkarlovi can you check if it works in Yaml?

**Comment by GuilhemN** [comment] 2018-03-23 16:28
The problem is not that your service is anonymous but that it has a parent (defaults are applicated to anonymous services so it throws an error).

**Comment by nicolas-grekas** [comment] 2018-04-03 11:58
Status: Waiting feeback

**Comment by nicolas-grekas** [comment] 2018-06-19 14:58
Closing as won't fix. Can be reconsidered of course, with a PR at best :)

**Closed by nicolas-grekas** 2018-06-19 14:58 UTC
Labels: DependencyInjection, Feature
