### ISSUE TITLE
Empty error message and silent failure on method mismatch when using handleRequest and isValid

### ISSUE THREAD

**Issue by mote0230** [symfony/symfony#21418] opened 2017-01-26 14:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.15

When handling a PUT request, a handlerequest followed by a isValid will result in isValid failing with no error message nor exception. To get around this message the user has to to call createForm specifying the PUT method. People with old code who still have bind() instead of handlerequest() will see a deprecated message to change to bind to handlerequest, but their code will stop working without giving a reason.

How to fix:
https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L55
Put descriptive addError above this line. Maybe also in /Component/Form/NativeRequestHandler, it has similar code but i have no idea where it's called from.

See also issue https://github.com/symfony/symfony/issues/8261 where this problem was first mentioned some years ago.

**Comment by HeahDude** [comment] 2017-01-26 14:44
Hello @mote0230, thank you for taking the time to open this issue.

>When handling a PUT request, a handlerequest followed by a isValid will result in isValid failing

Calling `isValid` before `isSubmitted` has been deprecated as of symfony 3.2, and in this case if you have called `isSubmitted` first it would also fail since the form is not submitted by the handler when methods mismatch.

As changing this behavior would be a big BC break in older versions, this is more a documentation issue IMHO.

The workaround is quite simple though, just define the method properly or use `Form::submit` instead of `Form::handleRequest`.

**Comment by mote0230** [comment] 2017-01-26 14:48
I don't see how it's a BC to go from failing silently to failing with notificing you somewhere?

**Comment by HeahDude** [comment] 2017-01-26 15:32
How would you handle this notifying then? Because from my POV

>Put descriptive addError above this line

is a strong behavioral change that could only be done in master.

The issue to me is the fact that it's not documented, because checking if a form is submitted is fundamental in a controller, otherwise this cannot work at all.

**Comment by xabbuh** [comment] 2017-01-27 08:39
I am closing here as @HeahDude perfectly explained the intended behaviour. If for whatever reasons you want to issue an error message to the use in case the form is not submitted, you have to take care of it yourself. Issuing such a warning globally would break applications that use the same controller for displaying the form and handle its submission. Thank you for understanding.

**Closed by xabbuh** 2017-01-27 08:39 UTC

**Comment by kor3k** [comment] 2017-02-10 08:55
@mote0230  @HeahDude  @xabbuh  https://github.com/symfony/symfony/issues/8261#issuecomment-278890355
