### ISSUE TITLE
Alternatives (when command not found) are in wrong order

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#13419] opened 2015-01-15 09:15 UTC
I would suggest to use an alphabetical sorting.

If you are with me, a PR will follow.

![bildschirmfoto 2015-01-15 um 10 13 03](https://cloud.githubusercontent.com/assets/995707/5754964/742f8f82-9c9f-11e4-85cc-5dc06ba0e938.png)

**Comment by peterrehm** [comment] 2015-01-15 15:46
I think this would be a good improvement, unsorted is rather difficult to read.

**Comment by malarzm** [comment] 2015-01-15 17:02
Duplicate of https://github.com/symfony/symfony/issues/10893

**Closed** 2015-01-16 06:19 UTC

**Comment by flip111** [comment] 2015-01-25 19:49
@OskarStark please review possible implementation in https://github.com/symfony/symfony/issues/10893#issuecomment-71388802

**Comment by OskarStark** [comment] 2015-01-25 21:02
@flip111 i will have a look soon!
