### ISSUE TITLE
prependExtensionConfig: define doctrine settings over multiple bundles

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#23467] opened 2017-07-10 14:00 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.11

We've got a bundle (base bundle) which delivers basic doctrine settings by prependExtensionConfig. Which worked fine since years. Today i tried to register a new doctrine (dbal) field type.

After i add it to the 'dbal' section of the doctrine settings. Every bundle depends on base bundle and got additional doctrine settings failed by: Unknown database 'xxxx'

### BaseBundle

```php
$container->prependExtensionConfig(
    'doctrine',
    [
        'dbal' => [
            'types' => [
                PartialDateType::NAME => [
                    'class' => PartialDateType::class
                ]
            ]
        ],
        'orm' => [...]
    ]
);
```
        
### FeatureBundle

```php
$container->prependExtensionConfig(
    'doctrine',
    [
        'orm' => [...]
    ]
);
```

=> Unknown database 'xxxx'

### BaseBundle

```php
$container->prependExtensionConfig(
    'doctrine',
    [
        'orm' => [...]
    ]
);
```
        
### FeatureBundle

```php
$container->prependExtensionConfig(
    'doctrine',
    [
        'orm' => [...]
    ]
);
```

**Comment by sstok** [comment] 2017-07-10 14:21
Doctrine has it's own bundle https://github.com/doctrine/DoctrineBundle

**Comment by stof** [comment] 2017-07-10 14:38
Several solutions:

- mark your type as not commented at the bundle level (with ``PartialDateType::NAME => ['class' => PartialDateType::class, 'commented' => false]`` and mark the type as commented in the type class itself if it requires a comment hint to avoid endless updates when using `doctrine:schema:update` or `doctrine:migrations:diff`)
- configure the `server_version` in your DBAL configuration instead of relying on guessing to determine the right Platform to use (guessing requires connecting to the DB for that)
- revert DoctrineBundle to the previous release
- wait for https://github.com/doctrine/DoctrineBundle/issues/672 to be fixed (see https://github.com/doctrine/DoctrineBundle/pull/628 working on it for instance)

The future-proof option is the first one. https://github.com/doctrine/DoctrineBundle/pull/628 is preparing the deprecation of the old way, as it causes issues, which was revealed by a recent bugfix triggering the early registration more often (previously, registration was missed in some cases, like yours).
Configuring the `server_version` explicitly is still worth it though.

**Comment by xabbuh** [comment] 2017-07-10 16:28
I am closing here anyway as the issue is related to DoctrineBundle.

**Closed by xabbuh** 2017-07-10 16:28 UTC

**Comment by dominikzogg** [comment] 2017-07-11 06:32
@stof thank you, works like a charm
