### ISSUE TITLE
SYMFONY__ Env Variables overwriten by parameters.yml

### ISSUE THREAD

**Issue by beberlei** [symfony/symfony#7555] opened 2013-04-03 18:32 UTC
I want to use the SYMFONY__* env variables that are detected in ``Kernel`` are overwritten by parameters of the same name in ``parameters.yml`` for example.

However i would suppose using the environment variables is a mechanism to overwrite the parameters.yml in production, so exactly the other way around.

Is the current behavior there for a reason? It doesn't make much sense to me.

**Comment by iniweb** [comment] 2015-02-09 23:30
@stof what about Docker and https://docs.docker.com/userguide/dockerlinks/ , there is should be opportunity to set up dynamically parameter values.

I know about import custom parameters.php... , but for changing only two values i should create external file and wrote custom getenv strings (which actually only used in continues integration context)

@beberlei :+1:

**Comment by eddiejaoude** [comment] 2015-03-03 11:38
> SYMFONY__ Env Variables overwriten by parameters.yml 

A way I got around this was to create a `parameters_dev.yml` file & put the ENV variable into *.dist*, then load the dev parameters with `config_dev.yml` (see below).

Not ideal, but seems to work fine without much change.

```yaml
# config_dev.yml 
imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }
```

**Comment by rodrigodiez** [comment] 2015-03-28 18:23
+1 looking forward to see this behaviour implemented. It would allow to easily create parametrized docker containers

**Comment by jrobeson** [comment] 2015-03-28 21:16
@rodrigodiez : for now, try as @beberlei  suggested in https://github.com/symfony/symfony/issues/7555#issuecomment-15856713

**Comment by ruudk** [comment] 2015-05-07 18:17
I really hope that the Container/ParameterBag can be altered so that it would support special `ENV` parameters. These parameters shouldn't be inlined when generating the cache but always link to a special service that retrieves the value from `ENV`. When the `ENV` parameter changes the Symfony2 app should just pickup the change.

This way, it would be much more easier to run Symfony2 apps inside Docker containers and dynamically link dependencies like `redis` and `mysql` using [Docker Container Links](https://docs.docker.com/userguide/dockerlinks/).

@stof @fabpot Would something like this even be possible? I know that parameters can be constructed from other parameters but I think that we shouldn't need that for the `ENV` parameters.

**Comment by stof** [comment] 2015-05-07 18:28
@ruudk this is what I implemented in https://github.com/Incenteev/DynamicParametersBundle (it works in Symfony 2.6.2+)

However, this does not work for parameters used in the semantic configuration of bundles. The semantic config is resolved before being passed to the bundle, and changing this would be a huge BC break (you cannot require a field to contain a boolean value and accept to use parameters in them for instance, as ``'%kernel.debug%'`` is a string, not a boolean).

**Comment by piotrpasich** [comment] 2015-06-23 09:23
Coming back to the first post of @beberlei from 2013 - the issue with overwriting env parameters by parameters.yml might be really painful during deployment automation with different servers (dev, qa, pre-prod, prod) especially on AWS + docker. I would like to avoid adding a special parameters.yml file in every single server when I can use preconfigured environment variables (ex. for database). 

@beberlei your solution works and that's awesome. Can we take into consideration change the current behavior and let the environment parameters not be overwritten by anything else? I can live with caching etc.

Just say a word and I will create a pull request.

**Comment by eddiejaoude** [comment] 2015-06-23 09:31
> ...I got around this was to create a `parameters_dev.yml` ...

@piotrpasich I agree. Following that project where I used `*_dev` etc (mentioned above). I never implemented that again, it created other issues. I am keen for environment parameters not be overwritten.

**Comment by weaverryan** [comment] 2015-06-24 21:02
@piotrpasich I would like to see a PR for this indeed :). The trick will be doing this without breaking backwards compatibility. If you can think of a clever way to do that, then we're in great shape!

**Comment by paq85** [comment] 2015-07-28 14:02
+1 for this feature

**Comment by SchizoDuckie** [comment] 2015-08-05 14:41
+1 for a solid solution for this feature and having a well thought-out and [documented](http://stackoverflow.com/questions/27680836/symfony2-where-to-save-environment-variables) plan on how to use it, because the [best practices](http://symfony.com/doc/current/best_practices/configuration.html) doc just says '[store them in the environment](http://symfony.com/doc/current/cookbook/configuration/external_parameters.html)' and provides no further guidance, so people make assumptions and invent their own methods pending the resolving of this ticket.

Some thoughts:

- putting environment configs in NGinx/Apache would break any CLI scripts (requires double administration) 
- 'put them in your ~/.bashrc with declare' is fragile and leaves edge cases that won't work for devs that work on multiple environments or in non-bash.
- having a separate bash script that sets the export variables requires double administration that will fail some day because somebody forgets to add a variable.
- modifying the [appkernel.php to load a custom file](http://stackoverflow.com/questions/10014327/symfony-2-multiple-server-configuration) seems hacky and can conflict with other modules that require parameters.yml to be in a specific spot

We are now just going to symlink a parameters.yml from a directory that's under puppet's control to bypass all of these problems.

**Comment by lennerd** [comment] 2015-10-14 20:04
:+1:

**Comment by alu** [comment] 2016-03-09 01:40
:+1:

**Comment by kent99** [comment] 2016-03-09 06:42
:+1:

**Comment by backbone87** [comment] 2016-03-22 07:55
Like already noted, the problem is the resolution context of some variables (parameters). The current behavior of the Config component expects everything to be resolveable at container-build-time (deploy-time). Allowing the use of "unresolved" parameters (parameters that will resolve after deploy-time) within semantic configuration must be handled by the consumers of the configuration (the container extensions), which is a very complex task, if at all possible.
The config component can provide some protection against missconfiguration/missuse though:
```xml
<parameter name="host" type="expression" scope="runtime">getenv('HOST')</parameter>
```
If parameter `host` is used within a `Configuration` tree the Config component can throw an `InvalidParameterScopeException`. But the `Configuration` tree can also declare the accepted (maximum) scope of an option individually, if it can handle unresolved values for the option.
So, if all `Configuration` trees that receive a `%host%` value in one of their options, can handle unresolved parameters in this options, the container-build would succeed.

**Comment by atorian** [comment] 2016-06-27 09:16
The possibility to override parameter by passing ENV var looks very interesting.
It will allow having default values for ENV, for example:

**parameters.yaml**
``` 
parameters:
    ...
    database_port: ~
```
Then docker-compose sets `SYMFONY__DATABASE_PORT` var and overrides it.

It will add some usability benefits, as the list of env might be quite long. 
And it looks safe and easy to implement.

However reading every not prefixed with `SYMFONY__` var looks dangerous.
If developer wants to use this vars - he should consider something like this:

**parameters.php**
```php
<?php
return [
   'parameters' => [
        ...
        'host' => getenv('HOST') ?: 'localhost',
    ],
];
```

**Comment by sagikazarmark** [comment] 2016-07-26 08:05
One possible solution  for the "docker problem": create an entrypoint which clears the cache upon every container start (and apply @beberlei's fix). Haven't found a better way so far.

**Comment by mcfedr** [comment] 2016-07-26 08:17
That probably necessary at the moment.
Ideally the cache would be created as part of the build step and so when a container is started its already got the cache - that would give the fastest possible start up time.
I am currently thinking for my own services to inject a getter instead of the parameter directly, that way it will always refer to the environment - but this wont work for existing bundles.

**Comment by sagikazarmark** [comment] 2016-07-26 08:24
The problem is that you cannot determine the VALUE for the environment variable during build time. So when you want to use service discovery, you need to recompile the cache anyway. I agree that it somewhat violates the docker philosophy, but the only solution would be if we could use dynamic parameters (which you can with the library linked by @stof, but it feels hacky to me). Since the environment should be exactly the same, you can safely recompile the container IMO.

**Comment by mcfedr** [comment] 2016-07-27 07:04
I agree, its complete safe to rebuild, but it takes time and it would be nice to avoid that. As far as I can tell, without a serious overhaul of the DI component rebuilding will remain necessary.

**Closed** 2016-09-15 19:17 UTC
Labels: Enhancement
