### ISSUE TITLE
[ProcessBuilder] Producing processes with bad command line

### ISSUE THREAD

**Issue by nico-incubiq** [symfony/symfony#18857] opened 2016-05-24 16:35 UTC
Hi,

I tried to use the ProcessBuilder component to create Processes on Symfony 2.8.6 as described in the documentation. But unfortunately the processes were all failing to start.

After some investigation, it appeared that the command line was full of double-quotes; around each of the command argument.

Quick example:

```php
$builder = new ProcessBuilder();
$builder->add(sprintf('php %s/../bin/console my:super:command', $this->getRootDir()));
$builder->add(sprintf('--survey=%d', $survey->getId()));
$process = $builder->getProcess();
```

I think the expected command line is: `php %s/../bin/console my:super:command --survey=12`.
While the actual one is: `"php %s/../bin/console my:super:command" "--survey=12"`.

Regards,
Nicolas

**Comment by xabbuh** [comment] 2016-05-25 20:37
You have to call `add()` for every single argument:

```php
$builder = new ProcessBuilder();
$builder->add('php');
$builder->add(sprintf('%s/../bin/console', $this->getRootDir()));
$builder->add('my:super:command');
$builder->add(sprintf('--survey=%d', $survey->getId()));
$process = $builder->getProcess();
```

Anyway, this is not a bug in the Process component. Thus I am closing here.

**Closed by xabbuh** 2016-05-25 20:37 UTC
Labels: Bug, Process, Status: Needs Review, Unconfirmed
