### ISSUE TITLE
Twig template priority (server crash)

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#41135] opened 2021-05-08 08:53 UTC
**Symfony version(s) affected**: 5.2.7

**Description**
It seems there is a priority inconsistency in the priority given to the template chosen by twig
Including an infinite loop that makes server crash..

**How to reproduce**
My attempt (thanks to @xabbuh's help) to replace the original form_div_layout is not working.
1. The entries in "form_themes" are not prioritized, therefore I haven't found a way to override form_div_layout.
2. So I ended up to a form_div_layout.html.twig in the default_path (thanks to @hacfi), but including a {% use %} block is now giving priority to the user "form_div_layout". Therefore, it results in an infinite loophole (I assume without any security, bad for server stability. 

So to avoid the crash I wonder if it wouldn't be possible to check that the currently read file location could not be compared with the detected file in the {% use block %} in the TwigRendererEngine class. Second, a form_themes, could be read first instead of putting the default form_div_layout.html.twig in ./vendor/symfony/twig-bridge/view/Form/
What do you think ?

Additionally, there is not Twig or TwigBridge variable pointing to the default template directory, while there is some @Security, @WebProfiler variables.

```
twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - '@MyBundle/form/form_div_layout.html.twig'
        - '@MyBundle/form/bootstrap_4_layout.html.twig'
```
```
{# src/templates/form_div_layout.html.twig #}
{% use "form_div_layout.html.twig" %}

{% block div_widget %}
<div id="{{ id }}">
    <input name="{{ full_name }}" type="hidden" {% if value is not empty %} value="{{ value }}" {% endif %} />
    {{ block('attributes') }}
</div>
{% endblock div_widget %}
```

**Comment by hacfi** [comment] 2021-05-08 23:19
@xKZL Placing `form_div_layout.html.twig` in your templates directory makes it impossible to access the one provided by the `symfony/twig-bridge` package. So if you want to extend the original file just name your template differently (`my_form_div_layout.html.twig` as I showed you in my example) and then use `{% extends 'form_div_layout.html.twig' %}` (I don't see a benefit of using `{% use ..%}` here). Of course this means you need to add 
```yaml
twig:
    form_themes:
        - 'my_form_div_layout.html.twig'
```
for that.
If you don't want this config change you would need to copy the entire `vendor/symfony/twig-bridge/Resources/views/Form/form_div_layout.html.twig` file to `templates/form_div_layout.html.twig` and not use `{% extends '..' %}` or `{% use '..' %}`.

About using a default form templates from a bundle: you'll need to configure this in the `form_themes:` section of the `twig:` configuration as well. You can either ask your bundle's user to do so (if your bundle will be used by others) or do this automatically with a [Prepend Extension](https://symfony.com/doc/current/bundles/prepend_extension.html). I created an example to test this: https://github.com/hacfi/symfony-test/tree/form-bundle
To test this do:
```
git clone git@github.com:hacfi/symfony-test.git -b form-bundle symfony-form-bundle-test
cd symfony-form-bundle-test
composer install
symfony serve
```
and then open http://127.0.0.1:8000/form  . You'll see that the form that is simply rendered with `{{ form(form) }}` (https://github.com/hacfi/symfony-test/blob/form-bundle/templates/form/index.html.twig#L13) will use the form theme from a bundle at https://github.com/hacfi/symfony-test/blob/form-bundle/src/Bundle/CompanyBundle/Resources/views/form_div_layout.html.twig (this adds an `hello` before each field). `form_themes:` isn't actually set in the config (https://github.com/hacfi/symfony-test/blob/form-bundle/config/packages/twig.yaml#L3) but added by a prepend extension: 
https://github.com/hacfi/symfony-test/blob/form-bundle/src/Bundle/CompanyBundle/DependencyInjection/AppCompanyExtension.php#L43-L49

**Comment by hacfi** [comment] 2021-05-08 23:46
But you have one point here I think: 
The path `vendor/symfony/twig-bridge/Resources/views/Form/` gets added as a non-namespaced directory. This prevents us from accessing it via `@!form/form_div_layout.html.twig` even if we use the path `templates/form_div_layout.html.twig`.

**Comment by meiyasan** [comment] 2021-05-09 06:26
Hi, I think we already discussed this point on slack.

So adding a my_form_div is not satisfying. If I want to add a custom form the documentation is pretty clear, but here I don't want to to this.

My point is that there is no satisfying way to override the initial form_div template anyway. I want to implement additional widget and I don't have full access to all forms (e.g in bundles). 

The second point is that the potential workaround ended up with an unstable loophole, that is certainly not the way to go. The current twig file name should be compared to the one selected in {%use/export%} and then be skipped to the next if the same.

Thank and cheers for summarizing

**Comment by meiyasan** [comment] 2021-05-09 06:33
Additionally copypasting the entire twig form directory doesn't make sense: it prevents people of using changes in the default files. After years files are just lost in an inappropriate place, this is bad practice for maintenance and so on..

**Comment by meiyasan** [comment] 2021-05-13 07:38
I have found a way to override this from a bundle, but this is to my mind very complicate, compared to what might be proposed to the user. I have a "base-bundle", where I redefine some basic classes. So this is extracted out of my bundle.. To be adapted maybe.
```
// service.yaml

        <service id="base.twig_loader" class="Base\Twig\Loader\FilesystemLoader">
            <tag name="twig.loader" />
            <argument type="service" id="base.service" />
            <argument type="service" id="twig" />
        </service>

```
```
<?php

namespace Base\Twig\Loader;

use Twig\Error\LoaderError;
use Twig\Environment;
use Twig\Source;

use Base\Service\BaseService;
use Twig\Loader\ChainLoader;

class FilesystemLoader extends \Twig\Loader\FilesystemLoader
{
    /**
     * @param string|array $paths    A path or an array of paths where to look for templates
     * @param string|null  $rootPath The root path common to all relative paths (null for getcwd())
     */
    public function __construct(BaseService $baseService, Environment $twig)
    {
        // Setup custom loader, to prevent the known issues of the default symfony TwigLoader
        // 1/ Cannot override <form_div_layout class="html twig">
        // 2/ Infinite loop when using {%use%} (Actually this needs to be fixed.. TODO)

        $useCustomLoader = $baseService->getParameterBag("base.twig.use_custom_loader");
        if($useCustomLoader) {

            $paths = $baseService->getParameterBag("base.twig.form_themes");
            $rootPath = $baseService->getParameterBag("base.twig.default_path");

            parent::__construct($paths, $rootPath);

            $mainLoader = $twig->getLoader();
            if($mainLoader instanceof ChainLoader) {

                $loaders = $twig->getLoader()->getLoaders();
                array_unshift($loaders, $this);

            } else {

                $loaders = [$this];
            }

            $chainLoader = new ChainLoader($loaders);
            $twig->setLoader($chainLoader);
        }

        $projectDir = $baseService->getProjectDir();
        // Add @Twig path in the list of namespaces
        $this->addPath($projectDir . "/vendor/symfony/twig-bridge/Resources/views", "Twig");
        // You can put all layout in the corresponding subdirectory
        $this->addPath($projectDir . "/vendor/xkzl/base-bundle/templates/layout");
        $this->addPath($projectDir . "/templates/layout");

        // Add base service to the default variables
        $twig->addGlobal("base", $baseService);
    }
}

```


```
# Custom ./config/packages/base.yaml
  twig:
    use_custom_loader: True
    default_path: '%kernel.project_dir%/vendor/xkzl/base-bundle/templates'
    form_themes:
        - './form'
```

**Comment by yceruto** [comment] 2021-07-09 22:38
As @hacfi already mentioned, can name your `templates/form_div_layout.html.twig` template differently and setting it in Twig form_themes configuration, then you can extend the vendor layout template as normal:
```yaml
twig:
    form_themes:
        - 'my_custom_form_div_layout.html.twig'
```
```twig
{# templates/my_custom_form_div_layout.html.twig #}
{% extends 'form_div_layout.html.twig' %}

{# ... #}
```
This is the most common, easy and natural option for users (in my opinion).

---
As second option, you can define in Twig paths configuration a namespace for `vendor/symfony/twig-bridge/Resources/views/Form` and use it to extend the vendor layout template:
```yaml
twig:
    paths:
        vendor/symfony/twig-bridge/Resources/views/Form: Themes
```
```twig
{# templates/form_div_layout.html.twig #}
{% extends '@Themes/form_div_layout.html.twig' %}

{# ... #}
```
Both ways will have the same result.

---
About the infinite loop (I think it was your original problem) it's solved by the special `!` prefix in the template name to tell Symfony that you want to extend from the original template, not from the overridden one. It's true that we can't apply this technique to templates without namespace, but we still have good alternatives.

https://symfony.com/doc/current/bundles/override.html#templates

---

I'm closing as this is not a bug and I don't see anything that can be improved in Symfony side.

**Closed as completed by yceruto** 2021-07-09 22:38 UTC
Labels: Bug, TwigBundle, Status: Needs Review
