### ISSUE TITLE
assets:install is suddenly destructive

### ISSUE THREAD

**Issue by pschultz** [symfony/symfony#24204] opened 2017-09-14 16:08 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.7.30, 2.8.23, 3.2.10, 3.3.3

#23195 changed the assets:install command such that it removes unregonized content in the target directory.

While I understand the intention, a feature that deletes files from disk (the webroot, even) without asking must not become the default behaviour in a patch level release.

This change in behaviour broke our build/deployment scripts. Our AppKernel can be booted with different sets of bundles (controlled by an environment variable). So the build script does something like

    THEME_A bin/console assets:install
    THEME_B bin/console assets:install
    THEME_C bin/console assets:install
    # ...

Before #23195 the resources for all themes were installed in the webroot, now only the resources required by the last configuration exist.

It is also conceivable that people want to run completely unrelated Symfony applications out of the same webroot. Or the target path is on a remote filesystem, such as S3. Then running the command could break every other app.

Please put this feature behind a --clean flag or so.

**Comment by jakzal** [comment] 2017-10-25 09:08
Duplicate of #23416

**Closed by jakzal** 2017-10-25 09:08 UTC
Labels: BC Break, Bug, FrameworkBundle, Status: Needs Review
