### ISSUE TITLE
SF4 :  When set Session config in  yaml ,  the dump() will be break the framework !

### ISSUE THREAD

**Issue by askuiop** [symfony/symfony#25853] opened 2018-01-20 01:45 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

When set Session config in  yaml ,  the dump() will be break the framework !
The error  is  :  Failed to start the session because headers have already been sent by "/...xxx../vendor/symfony/var-dumper/Dumper/AbstractDumper.php" at line 181.

**Comment by xabbuh** [comment] 2018-01-22 09:52
Can you create a small example application allowing to reproduce your issue?

**Comment by DeepSnowNeeL** [comment] 2018-01-24 10:57
I'm reproducing the issue with this simple code
```php
/**
     * @Route("/test", name="test")
     */
    public function test()
    {
        $s = $this->get('session');
        dump('test');
        $s->set('code', 'hello');
        $s->save();
    }
```

Error is 
`Failed to start the session because headers have already been sent by "C:\project\vendor\symfony\var-dumper\Dumper\AbstractDumper.php" at line 181.`

**Comment by xabbuh** [comment] 2018-01-26 14:19
I am not able to reproduce. The only error I run into when trying your code is "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?". Please create a small example application that allows to reproduce the issue.

**Comment by MinDBreaK** [comment] 2018-01-26 15:09
I've set up a small demo application on my repo [MinDBreak/DemoVarDumper](https://github.com/MinDBreaK/DemoVarDumper)

It appears to fail when using the profiler.

**Comment by xabbuh** [comment] 2018-01-26 16:40
Thanks for the example. This behaviour looks expected to me as the DebugBundle is not installed. In this case, the VarDumper component will just dump to the standard output stream which means that the HTTP headers will be sent by PHP leading to the error you experience when Symfony tries to start the session.

If you install the DebugBundle however, you will not see this error as it registers a handler that buffers the calls and ensures that they will only be displayed in the web debug toolbar.

Thus, I suggest to close this issue as I do not see what we can do to make this fail with a better error.

**Comment by curry684** [comment] 2018-01-28 11:35
There's a DX/documentation issue though, I also ran into some surprises with dumps not working as expected because I had everything wired up except the debug bundle. We could definitely detect misconfiguration during container compilation and wire up something to provide better DX for this I think.

**Comment by nicolas-grekas** [comment] 2018-01-30 10:45
This can still be encountered of course, when the DebugBundle is not installed. But there is nothing we can do then: dumping needs to send the headers. The good news is that the underlying issue that mde this an issue was that the session was used in RequestDataCollector, which is not the case anymore.
Closing as such.

**Closed by nicolas-grekas** 2018-01-30 10:45 UTC
Labels: Bug, HttpFoundation, Status: Reviewed, VarDumper
