### ISSUE TITLE
Random failures with v3.2.10 update (and v3.3.3 ?)

### ISSUE THREAD

**Issue by shavounet** [symfony/symfony#23384] opened 2017-07-04 12:58 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no ?
| RFC?             | no
| Symfony version  | 3.2.10

**Context**:
* symfony project v3.2
* PHP 7
* Mysql 5.7
* Redis (for custom cache)

**What happened**:
* after a `composer update`, Symfony did update from 3.2.9 to 3.2.10 (along with a known update from an owned module)
```
  - Updating symfony/symfony (v3.2.9 => v3.2.10): Loading from cache
  - Updating cleverage/process-bundle dev-master (6118651 => 4b264eb):  Checking out 4b264eba8b
```
* at the end of the `composer update`, a huge error happened
```[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "DoctrineNamespaceCacheKey%5B%5D" {"key":"DoctrineNamespaceCacheKey%5B%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "%5BSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D" {"key":"%5BSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to save key "%5BSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D" (array) {"key":"%5BSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D","type":"array","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: array_keys() expects parameter 1 to be array, boolean given at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/ApcuAdapter.php:95)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D" {"key":"%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to save key "%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CAbstractValue%5D%5B1%5D","type":"integer","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: array_keys() expects parameter 1 to be array, boolean given at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/ApcuAdapter.php:95)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D" {"key":"%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D" {"key":"%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to save key "%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D" (array) {"key":"%5BSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D","type":"array","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: array_keys() expects parameter 1 to be array, boolean given at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/ApcuAdapter.php:95)"} 
[2017-07-04 13:54:11] cache.WARNING: Failed to fetch key "%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D" {"key":"%5B%5BC%5DSidus%5CEAVModelBundle%5CEntity%5CValueRepository%5D%5B1%5D","exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"} 
[...]
```
* it can be reproduced with some doctrine commands (such as `./bin/console doctrine:schema:validate | head`)
* when reverting to v3.2.9, the bug disappear, all is normal ; when going back to v3.2.10 it fails again
* reproduced on multiple environments (with mostly the same setup ; with and without docker)
* cache clearing and restarting apache doesn't solve the thing

**Comment by fancyweb** [comment] 2017-07-04 13:02
I'm having the exact same problem after upgrading from 3.3.2 to 3.3.3

```
PHP Warning:  Invalid argument supplied for foreach() in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php on line 141
PHP Warning:  Invalid argument supplied for foreach() in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php on line 141
PHP Warning:  array_keys() expects parameter 1 to be array, boolean given in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/ApcuTrait.php on line 97
15:01:05 WARNING   [cache] Failed to save key "%5BES%5CCoreBundle%5CEntity%5CAbstractAttributeGroupTranslation%23getName%5D%5B1%5D" (array) ["key" => "%5BES%5CCoreBundle%5CEntity%5CAbstractAttributeGroupTranslation%23getName%5D%5B1%5D","type" => "array","exception" => null] []
```

**Comment by shavounet** [comment] 2017-07-04 13:08
I updated the title since the error looks the same ; it wouldn't be much surprising

**Comment by iltar** [comment] 2017-07-04 13:17
Looks like #23344

**Comment by COil** [comment] 2017-07-04 13:18
Same problem, can't use this release:

    15:04:47 WARNING   [cache] Failed to save key "%5B%5BC%5DAppBundle%5CEntity%5CMigrationVersions%24version%40%5BAnnot%5D%5D%5B1%5D" (integer) ["key" => "%5B%5BC%5DAppBundle%5CEntity%5CMigrationVersions%24version%40%5BAnnot%5D%5D%5B1%5D","type" => "integer","exception" => Symfony\Component\Debug\Exception\ContextErrorException {trace: { …} …}] ["server" => "DEV","env" => "dev","app_version" => "2.9.11"]

Huge difference of memory use with php unit.

    Symfony 3.3.2:
    Time: 1.01 minutes, Memory: 995.75MB
    OK (41 tests, 269 assertions)

    Symfony 3.3.3:
    Time: 4.41 minutes, Memory: 7655.75MB
   OK (41 tests, 269 assertions)

But it may come from phpunit itself.

**Comment by shavounet** [comment] 2017-07-04 13:27
Yep it looks the same, and I can also confirm it's not just a warning, but it did block some heavy background process (though I didn't check if it was a memory failure)

**Comment by themasch** [comment] 2017-07-04 13:29
We have a similar problem when updating for 3.3.2 to 3.3.3. 
Suddenly WebTestCases using phpunit take way longer (~3x-20x or even more) and use more memory (about the same scale). I switched between versions (3.3.2<->3.3.3) with clearing cached etc between the runs and its reproducible. 

I can't really track it down to a single component/class/method, but the symptoms look exactly like what @COil said.

**Comment by shavounet** [comment] 2017-07-04 13:32
Just found something interesting:
* on v3.2.9, I started my heavy process (+800k entity import), and I also encountered a few time similar errors:
```
[2017-07-04 15:10:36] php.WARNING: Warning: Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /home/webactu/www/releases/20170704115700/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php:179)"}
[2017-07-04 15:10:36] php.WARNING: Warning: array_keys() expects parameter 1 to be array, boolean given {"exception":"[object] (ErrorException(code: 0): Warning: array_keys() expects parameter 1 to be array, boolean given at /home/webactu/www/releases/20170704115700/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/ApcuAdapter.php:95)"}
[2017-07-04 15:10:36] cache.WARNING: Failed to save key "Sidus.PublishingBundle.Entity.PublishableInterface" (Symfony\Component\Validator\Mapping\ClassMetadata) {"key":"Sidus.PublishingBundle.Entity.PublishableInterface","type":"Symfony\\Component\\Validator\\Mapping\\ClassMetadata","exception":null}
```

It look that something to do with the ApcuAdapter...

**Comment by xabbuh** [comment] 2017-07-04 13:33
closing as a duplicate of #23344

**Closed by xabbuh** 2017-07-04 13:33 UTC
Labels: Bug, Cache, Status: Needs Review
