### ISSUE TITLE
Uncaught Error: Unknown named parameter

### ISSUE THREAD

**Issue by williamdes** [symfony/symfony#38089] opened 2020-09-07 11:51 UTC
**Symfony version(s) affected** 4.2.8 (https://github.com/phpmyadmin/phpmyadmin/blob/64f6b5c43522be49facbd95bee9197e811284c91/composer.json#L55)

**Description**  
```
[11-Aug-2020 10:14:15 America/New_York] PHP Fatal error:  Uncaught Error: Unknown named parameter $create_add_field in D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php:1144
Stack trace:
#0 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(1144): ReflectionClass->newInstanceArgs(Array)
#1 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'PhpMyAdmin\\Cont...')
#2 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(558): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('PhpMyAdmin\\Cont...', 1)
#3 D:\phpMyAdmin\tbl_structure.php(67): Symfony\Component\DependencyInjection\ContainerBuilder->get('PhpMyAdmin\\Cont...')
#4 {main}
  thrown in D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php on line 1144
```

**How to reproduce**  
PHP 8.0 beta 1 (https://github.com/phpmyadmin/phpmyadmin/issues/16301)

Upstream bug: https://github.com/phpmyadmin/phpmyadmin/issues/16301

**Comment by derrabus** [comment] 2020-09-07 12:08
Oh, hello phpMyAdmin. ❤️

I'm actively fixing those kind of issues right now, but:

* Symfony 4.2 is EOL and won't be patched for PHP 8.
* PHP 8.0 beta1 won't be supported by Symfony because of breaking changes that have been introduced afterwards.

Please try to reproduce the problem with Symfony 4.4 on a more recent php 8 snapshot.

**Comment by fabpot** [comment] 2020-09-07 12:14
Fixed in 3.4, will be part of 4.4/5.1/and next soon

**Closed** 2020-09-07 12:13 UTC
Labels: Bug, DependencyInjection, Status: Needs Review

**Comment by tonydream888** [comment] 2020-12-16 07:15
The same error happen to me today after moving to new server (CentOS 7, PHP 8), more exactly when I use phpMyAdmin.  The symfony that currently installed is version 4, how to solve the problem? Can someone give a step by step instruction to upgrade the symfony  here? Thanks

**Comment by williamdes** [comment] 2020-12-16 08:27
> The same error happen to me today after moving to new server (CentOS 7, PHP 8), more exactly when I use phpMyAdmin. The symfony that currently installed is version 4, how to solve the problem? Can I someone give a step by step instruction to upgrade the symfony here? Thanks

You need to use phpMyAdmin 5.0.4 or newer as mentioned here :) 
https://github.com/phpmyadmin/phpmyadmin/issues/16449#issuecomment-720461096

**Comment by tonydream888** [comment] 2020-12-16 08:37
I am already using 5.0.4, just checked

**Comment by derrabus** [comment] 2020-12-16 08:50
Please continue the discussion on the linked phpMyAdmin ticket or have a look at https://www.phpmyadmin.net/support/ for more support options.
