### ISSUE TITLE
Validation annotation NotBlank is not working when edit object data but it works when adding new object

### ISSUE THREAD

**Issue by hous04** [symfony/symfony#28485] opened 2018-09-17 00:43 UTC
**Symfony version(s) affected**: 4.1.4

**Description**  
The annotation validation NotBlank doesn't work when edit object data but it works when adding new object.

**How to reproduce**  

**Possible Solution**  
For example when I remove **String** from the Setter , then it works
`      public function setPurchaser(string $purchaser): self
`

Or if I keep String and adding **= nul**l then it works
` public function setPurchaser(string $purchaser = null): self`

**stackoverflow**  
[https://stackoverflow.com/questions/52359426/validation-annotation-notblank-is-not-working-when-edit-object-data-but-it-works](https://stackoverflow.com/questions/52359426/validation-annotation-notblank-is-not-working-when-edit-object-data-but-it-works)

**Comment by hous04** [comment] 2018-09-17 16:37
What I have noticed is that when an attribute is nullable then it will be a question mark "?" before "string" in the setter like this:
`public function setTitle(?string $title): self`
otherwise if it is not null so it will be not a "?".

So, if an attribure is not null and there is no a question mark "?" before "string", **annontation assert not blank** will not work **when edit an entity data,** and if I add the "?" manually so it works fine.

So instead of using data transfer object (DTO) as you said , what about automatically adding question mark "?" before string for all setters when generate entities with the command **php bin/console make:entity** or where regenarte them with **php bin/console make:entity --regenerate**.

**Comment by iltar** [comment] 2018-09-17 17:01
>  what about automatically adding question mark "?" before string for all setters when generate entities

Because this would imply that even though your field could be mandatory, you have to make it optional because you bind your object to a form.

**Comment by hous04** [comment] 2018-09-20 07:10
Any way, I think it should be fixed, not all developers want to work with data transfer object (DTO), especially beginners with Symfony

**Comment by xabbuh** [comment] 2018-09-23 11:15
I am closing here as this is the expected behaviour as explained by @iltar.

**Closed by xabbuh** 2018-09-23 11:15 UTC

**Comment by xabbuh** [comment] 2019-04-09 17:33
@8-3 it's this comment: https://github.com/symfony/symfony/issues/28485#issuecomment-421936013

@iltar changed their username to @linaori some time ago (I updated my comment)
