### ISSUE TITLE
[DI] Inject all services with a specific tag

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#23916] opened 2017-08-17 13:25 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.x

Currently, when you want to inject all services with a specific tag you have to write your own compiler pass [as described here](https://symfony.com/doc/current/service_container/tags.html). Additionally,  one has to use method calls instead of injecting the services into the constructor because obviously the parameter cannot be inferred.

It would be handy if there was a way to inject all services that are tagged with a specific tag, optimally indexed by their id:

```yaml
Foo\Bar:
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@=taggedServices("my_tag")'
```

Resulting in:

```php
[
    "Foo\Service1" => Foo\Service1 {...},
    "Foo\Service2" => Foo\Service2 {...},
]
```

This is probably not an everyday use-case but maybe other people would be interested in this.

**Comment by iluuu1994** [comment] 2017-08-17 13:27
The `@=` will not work because the DI component needs to know the dependencies beforehand to do topological sorting. I wouldn't know what other syntax to use though.

**Comment by chalasr** [comment] 2017-08-17 13:30
Closing as duplicate of https://github.com/symfony/symfony/issues/12269, seems like you're not alone :)
Please consider looking at it and the relevant PR https://github.com/symfony/symfony/pull/22200 to discuss implementation details.

**Closed by chalasr** 2017-08-17 13:30 UTC

**Comment by iluuu1994** [comment] 2017-08-17 13:40
@chalasr Fantastic 😄 Sorry, I was looking though the issues and couldn't find anything. Thanks for the heads up!
