### ISSUE TITLE
[Debug] ErrorHandler throws PHP notices as Exceptions

### ISSUE THREAD

**Issue by Matts** [symfony/symfony#38302] opened 2020-09-25 13:21 UTC
**Symfony version(s) affected**: 3.4.44 
Debug bundle v4.0.15
Debug v4.4.13
PHP 7.4.10

**Description**  
When PHP notices are given, a breaking exception is thrown

**How to reproduce**  
$array = [];
$date = end($array)['end_date'];

will result in a "Notice: Trying to access array offset on value of type bool"

Now it is obvious that there should be a check here, but we want to disable notices (as these were ignored in the past). However, setting error_reporting to E_ALL & ~E_NOTICE does not fix this.

**Possible Solution**  

**Additional context**

**Comment by Matts** [comment] 2020-09-25 13:24
Also, I know this is a weird configuration, the issue that we have is legacy.

**Comment by fancyweb** [comment] 2020-09-25 13:42
Status: works for me

You can control the level it starts throwing with the throwAt() method.

If you use the full framework, you can modify the debug.error_handler.throw_at parameter.

Also on 4.4, the Debug component is deprecated, you should use the ErrorHandler component.

**Comment by nicolas-grekas** [comment] 2020-09-25 13:44
Closing as this is expected behavior (and is configurable). Note that the default behavior is really recommended. Use `@` before the expression if you want to opt-out locally. BUT I would strongly suggest to write the logic in a way that never triggers any notice.

**Closed by nicolas-grekas** 2020-09-25 13:44 UTC
Labels: Bug, Status: Works for me
