### ISSUE TITLE
[Dependency Injection] No Circular reference warning for Symfony 3.4 & Doctrine

### ISSUE THREAD

**Issue by mimol91** [symfony/symfony#24775] opened 2017-10-31 17:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Recently I've experienced quite unexpected behavior while using doctrine (https://github.com/symfony/symfony/issues/24700) After some deep investigation it seems that reason is simple -> **Circular references**.

It seems that different Symfony version  show or not different errors.

I've tested it on clean Symfony version
It can be simply recreated just just by creating empty class and adding this code to servies.yml

```yaml
services:
    core.listener.doctrine:
        class: AppBundle\DoctrineListener
        arguments: ['@doctrine.orm.default_entity_manager']
        public: false
        tags:
            - { name: doctrine.orm.entity_listener }
```

There are three possible solution how application will behave:

| Error Id | Symfony version| Empty cache | Service marked as public |
| - | - | - |- |
| 1 | 3.4 | ✓ | ✓|
| 1 | 3.3 | ✓ | ✓|
| 0 | 3.4 | ✗ | ✓|
| 0 | 3.3 | ✗ | ✓|
| 0 | 3.4 | ✓ | ✗|
| 2 | 3.3 | ✓ | ✗|
| 0 | 3.4 | ✗ | ✗|
| 0 | 3.3 | ✗ | ✗|

| Error Id | Message |
| - | - |
| 0 | _No error_  |
| 1 | It's a requirement to specify a Metadata Driver and pass it to Doctrine\ORM\Configuration::setMetadataDriverImpl().  |
| 2 | Circular reference detected for service "doctrine.orm.default_entity_manager", path: "doctrine.orm.default_entity_manager -> doctrine.orm.default_entity_listener_resolver". |

As you can see SF3.4 never mention about circular reference. Which I think still may occur ( or in my case cause some unexpected behavior) 
SF 3.3 display (or not ) different error based of condition if service is public or state of cache.

And yes it's again example with Doctrine, however I think DI and circular references are part of Symfony.
(Doctrine version is this same for each of SF version)

Want more magic? Try to `install doctrine-migration-bundle` (DO NOT register it in AppKernel)
Now if service is private the error about circular reference never shows!

I am totally aware that its not a 'common' case, but I am sure that this missing error about circular reference could save a lot of hours on debugging =). I do not mind if you close this issue, I just try to save other folks time, because they may have similar problem like I do.

**Comment by Simperfit** [comment] 2017-11-01 05:45
I think something has to be done to improve the DX, what do you want to have in order to ease the debbuging ?

**Comment by mimol91** [comment] 2017-11-01 06:00
It would be just great to see this `Circular reference detected ` error in each SF version.

**Comment by Simperfit** [comment] 2017-11-01 06:37
Status: Needs Review

**Comment by weaverryan** [comment] 2017-11-01 15:32
Yea, this definitely "smells" weird to me (i.e. a bug) - especially with the different behavior on the different versions and public vs private. Someone needs to dig in a bit.

**Comment by mimol91** [comment] 2017-11-03 16:43
@nicolas-grekas 
I did git-bisect, and it looks that it stop displaying warning after https://github.com/symfony/symfony/pull/23741
I will try to find a reason, however your help will be invaluable

**Comment by nicolas-grekas** [comment] 2017-11-03 16:54
No idea yet, if someone can look at a reproducer or a fix, that'd be great :)

**Comment by mimol91** [comment] 2017-11-03 17:00
Seems moving `$this->loading[$id] = true;`
https://github.com/symfony/symfony/pull/23741/files#diff-1df5b32be44d0f592ec285c6bbf386bbL332 
to line `301` solve the problem

**Comment by nicolas-grekas** [comment] 2017-11-03 17:05
@mimol91 could you try to work on a PR, fix the fix and a test case? That'd be the best way to prove your theory :)

**Comment by mimol91** [comment] 2017-11-03 17:08
Sure, I will tr

**Comment by mimol91** [comment] 2017-11-03 19:55
Ok,
The problem is with dumping container with ` 'as_files' => true,`.
What happens on SF3.3: 
1) Warmup cache
2) Request for loading `doctrine.orm.default_entity_manager` and mark it as lazy
3) Run `CacheWarmerAggregate`
4) Run `getDoctrine_Orm_DefaultEntityListenerResolverService`
```php
$instance->register(new \AppBundle\DoctrineListener(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->get('doctrine.orm.default_entity_manager')) && false ?: '_'}));
```

The important part is that if service is not registered in container it call `$this->get('doctrine.orm.default_entity_manager')) && false ?: '_'}));` which then **check if service is marked as loading** (and it is) so throw circular ref exception

What happens on SF3.4: 
Steps are the same, only `getDoctrine_Orm_DefaultEntityListenerResolverService` is changed
```php
$instance->register(new \AppBundle\DoctrineListener(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}));
```
Similar as previous service does not exist, so `$this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')` is executed.  -> **There is not check if `services['doctrine.orm.default_entity_manager']` is in loading state**

How I think it can be fixed,
```php
$instance->register(new \AppBundle\DoctrineListener(${($_ = isset($this->services['doctrine.orm.default_entity_manager'])
    ? $this->services['doctrine.orm.default_entity_manager']
    : $this->loading['doctrine.orm.default_entity_manager']
        ? $this->get('doctrine.orm.default_entity_manager')
        : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}));
```

I am not sure how can I write tests to it, I do not feel comfortable with this phpDumper

**Comment by Koc** [comment] 2017-11-03 22:39
😨 Is it possible extract some variables to make generated code more readable?

**Comment by nicolas-grekas** [comment] 2017-11-03 23:56
@Koc the generated code must fit in one expression. Readability is not a criteria.

@mimol91 or better: do the check in the first lines of the generated files? Btw, doesn't this issue exist in 3.4 also, when as_files=false?

**Comment by mimol91** [comment] 2017-11-04 06:48
When changing as_files to false to display circular ref error (also 
```php
require_once $cache->getPath();
$this->container = new $class();
```) has to be changed

Ha. You can do check, but You will need to import `ServiceCircularReferenceException`. It was my 1st tough, however I was not sure if its only 'check' done in container while invoking `get()`

**Comment by nicolas-grekas** [comment] 2017-11-04 11:35
@mimol91 can you provide a fork of the standard edition that reproduces the issue? It would help a lot.

**Comment by mimol91** [comment] 2017-11-04 15:07
@nicolas-grekas 
Hey.
https://github.com/mimol91/sf-circular-reference 
There are 2 directory with SF 3.3 and 3.4 Respectively.
They are two changes only:

1. New file `https://github.com/mimol91/sf-circular-reference/blob/master/33/app/config/doctrine.yaml`
2. Import of this file in config https://github.com/mimol91/sf-circular-reference/blob/master/33/app/config/config.yml#L5

**Comment by nicolas-grekas** [comment] 2017-11-04 17:17
This is a variant of #19362, the reproducer provided there exhibits exactly the same issue.
Now trying to figure out how to fix that.

**Comment by nicolas-grekas** [comment] 2017-11-04 23:40
Fixed in #24822 (no by throwing an exception, but by handling properly the situation to create a fixed dependency tree.)

**Closed** 2017-11-05 15:40 UTC
Labels: Bug, DependencyInjection, Status: Needs Review

**Comment by gpekz** [comment] 2018-05-19 02:04
Recently I had this error while clearing the cache : "Segmentation fault (core dumped)"
The problem was a Circular Reference.
The context : injection of a service (which use doctrine manager / repository) into a doctrine subscriber.

**Comment by kgrieco** [comment] 2018-09-26 13:08
I'm also having problem with circular reference. I have a service (A) where some other services (B, C, D) are injected into it, one of them has Doctrine. If I try to inject service A into a Doctrine subscriber I get an exception:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '500' reached, aborting! in /home/kenzo/PhpstormProjects/sarah-server/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php:80
Stack trace:
#0 /home/kenzo/PhpstormProjects/sarah-server/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php(80): array_merge(Array, Array)
#1 /home/kenzo/PhpstormProjects/sarah-server/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php(61): Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator->addNamespacePrefixes(Array)
#2 /home/kenzo/PhpstormProjects/sarah-server/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/SimplifiedYamlDriver.php(40): Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator->__construct(Array, '.orm.yml')
#3 /home/kenzo/PhpstormProjects/sarah-server/var/cache/dev/ContainerQhEyouc/AppDevDebugProjectContainer.php( in /home/kenzo/PhpstormProjects/sarah-server/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php on line 80
```

**Comment by stof** [comment] 2018-09-26 15:01
@kgrieco that issue is closed since almost 1 year. It is unlikely that your issue is the same:

- original issue was fixed
- code is not the same anymore
- the error message you get is not the same one

Please create a new issue rather than commenting on closed ones (you were lucky that I took attention to the email notification for this comment, as the notification is the only way someone could see it. We don't go read closed issues again otherwise)

**Comment by cluis13915** [comment] 2021-12-04 16:48
Just in case someone is struggling with this yet, I found that getting repository from services constructor throws "Segmentation fault (core dumped)" when clearing the cache. Removing `getRepository()` calls from constructors makes the error goes away.

Bad:
```
public function __construct(EntityManagerInterface $em)
{
  $this->repository = $em->getRepository(Empresa::class);
}

public function myMethod()
{
  $empresa = $this->repository->find(...);
}
```
Good:
```
public function __construct(EntityManagerInterface $em)
{
  $this->em = $em;
}

public function myMethod()
{
  $empresa = $this->em->getRepository(Empresa::class)->find(...);
}
```
