### ISSUE TITLE
Missing import in WebProfilerBundle's RouterController

### ISSUE THREAD

**Issue by emirb** [symfony/symfony#18651] opened 2016-04-27 09:25 UTC
## The problem
Clean install of Symfony 2.8 throws `ClassNotFoundException` on Profiler's Router tab due to missing import.

## Error message
```
Fatal error: Class 'Symfony\Bundle\WebProfilerBundle\Controller\Request' not found
``` 
Location: `vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php:86`

This has been fixed in https://github.com/symfony/web-profiler-bundle/commit/ba91532e1d694d44374b096460961a1e7216db11 but the fix isn't available yet in the clean Symfony installation.

## Steps to reproduce
Download Symfony installer:
`$ sudo curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony`

Create new project using 2.8 LTS version:
`$ /usr/local/bin/symfony new my_project 2.8` 

Change your curent directory to `my_project`:
`$ cd my_project`

Run PHP built-in web-server:
`$ php app/console server:run`

Using your browser, go to localhost:8000.
Click on the profiler link in the bottom right, and then click to *Routing* in the left sidebar.
An exception will be thrown.

## Environment
OS: Ubuntu 14.04
PHP version: 5.6.20
Symfony: 2.8.4

**Comment by xelan** [comment] 2016-04-27 09:43
The issue is already fixed, but no tagged versions with the fix are released yet.
See https://github.com/symfony/symfony/pull/18340

**Comment by javiereguiluz** [comment] 2016-04-27 10:32
@emirb thanks for reporting this error, but as @xelan said, we'll need to wait a few more days until a new stable version is tagged and published. That's why I'm closing this as "fixed". Thanks.

**Closed by javiereguiluz** 2016-04-27 10:32 UTC
