### ISSUE TITLE
Cannot use processed env arrays in bundle config 

### ISSUE THREAD

**Issue by WietseGielen** [symfony/symfony#49941] opened 2023-04-05 10:27 UTC
### Symfony version(s) affected

5.4.16

### Description

Faced an issue when configuring allowed_origin in NelmioCorsBundle but after some debugging it looks like something bigger is going wrong.

Please have a look at: https://github.com/nelmio/NelmioCorsBundle/issues/148#issuecomment-1497238989

Mainly the last part looks like a Symfony issue:

From NelmioCorsBundle issue 148:

> Wietse Gielen wrote:
> When I remove all checks in NelmioCorsExtension::load() which already expects an array. The configuration processor which is default is still failing because an allow_origin is defined as an ArrayNode. In other words, I expects this is a bigger issue in Symfony itself. Because it impossible to use %env(json:VARIABLE)% or %env(csv:VARIABLE)% as Symfony describes without failing on the Configuration validation

```
In ArrayNode.php line 260:
                                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]                           
  Invalid type for path "nelmio_cors.defaults.allow_origin". Expected "array", but got "string"  
                                                                                                 

Exception trace:
  at /var/vhost/vendor/symfony/config/Definition/ArrayNode.php:260
 Symfony\Component\Config\Definition\ArrayNode->validateType() at /var/vhost/vendor/symfony/config/Definition/BaseNode.php:564
 Symfony\Component\Config\Definition\BaseNode->doValidateType() at /var/vhost/vendor/symfony/config/Definition/BaseNode.php:407
 Symfony\Component\Config\Definition\BaseNode->normalize() at /var/vhost/vendor/symfony/config/Definition/ArrayNode.php:287
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /var/vhost/vendor/symfony/config/Definition/BaseNode.php:410
 Symfony\Component\Config\Definition\BaseNode->normalize() at /var/vhost/vendor/symfony/config/Definition/ArrayNode.php:287
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /var/vhost/vendor/symfony/config/Definition/BaseNode.php:410
 Symfony\Component\Config\Definition\BaseNode->normalize() at /var/vhost/vendor/symfony/config/Definition/Processor.php:32
 Symfony\Component\Config\Definition\Processor->process() at /var/vhost/vendor/symfony/config/Definition/Processor.php:46
 Symfony\Component\Config\Definition\Processor->processConfiguration() at /var/vhost/vendor/symfony/dependency-injection/Extension/Extension.php:113
 Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at /var/vhost/vendor/nelmio/cors-bundle/DependencyInjection/NelmioCorsExtension.php:30
 Nelmio\CorsBundle\DependencyInjection\NelmioCorsExtension->load() at /var/vhost/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:79
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /var/vhost/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /var/vhost/vendor/symfony/dependency-injection/Compiler/Compiler.php:82
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/vhost/vendor/symfony/dependency-injection/ContainerBuilder.php:759
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/vhost/vendor/symfony/http-kernel/Kernel.php:546
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/vhost/vendor/symfony/http-kernel/Kernel.php:787
 Symfony\Component\HttpKernel\Kernel->preBoot() at /var/vhost/vendor/symfony/http-kernel/Kernel.php:128
 Symfony\Component\HttpKernel\Kernel->boot() at /var/vhost/vendor/symfony/framework-bundle/Console/Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /var/vhost/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/vhost/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/vhost/bin/console:43
 ```

### How to reproduce

Define a env variable described in https://symfony.com/doc/5.4/configuration/env_var_processors.html

```
# config/packages/framework.yaml
parameters:
    env(TRUSTED_HOSTS): '["10.0.0.1", "10.0.0.2"]'
framework:
    trusted_hosts: '%env(json:TRUSTED_HOSTS)%'
```

same issue with csv pre-processor

pass this env variable to a bundle configuration which expects an ArrayNode in configuration

### Possible Solution

Process env variables before passing to bundle Configuration or Extension

OR

ArrayNode defined in bundle Configuration should be able handle to not-yet processed env var array

**Comment by ro0NL** [comment] 2023-04-08 10:32
It's a known issue, see #40906

**Comment by xabbuh** [comment] 2023-04-08 13:37
closing as a duplicate of #40906

**Closed as not planned by xabbuh** 2023-04-08 13:37 UTC
Labels: Bug, Status: Needs Review
