### ISSUE TITLE
[Form][Validation] Unique entity validator throw undefined index if no data is provided

### ISSUE THREAD

**Issue by flohw** [symfony/symfony#23486] opened 2017-07-12 13:32 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=2.7.25

The UniqueEntityValidator throw an "undefined index error" when submitting no data or null value on a defined entity's field.

My entity has `UniqueEntity(fields={"reference", "supplier"})` constraint.
In my functional test I submit an empty array as post data.
The response is "Undefined index: reference".

After some research, the bug was introduced here https://github.com/symfony/doctrine-bridge/commit/40941a3b7d6d6158ade63bc37bb09f260bd2202f#diff-e59b775599f36ee1318299634bc1be79 when line 88 has been splitted.
In my exemple `$criteria['reference']` does not exist any more and the error (undefined index) occurs on line 137
If `$criteria[$fieldName] = $fieldValue;` were between line 88 and 90 it would works properly.

Sorry but I am not sure about the solution and don't know how to create a test for this case. If someone can help me about that.

Thank you.

Curiosity question : is there a reason to use `ClassMetdata` attributes (like `reflFields`) to get field values instead of `getFieldValue($entity, $field)` method?

**Comment by xabbuh** [comment] 2017-07-12 16:59
I am not sure how to reproduce your issue. Can you show the functional test that is triggering this?

**Comment by xabbuh** [comment] 2017-07-12 19:46
Can you please also investigate what exactly gets passed to `UniqueEntityValidator::validate()` for the `$entity` argument?

**Comment by flohw** [comment] 2017-07-13 07:37
Hello,
The error is trigger when calling `$client->request()` :
```php
$client->request(
            'PUT',
            $this->getUrl('api_put_article', ['id' => 1]),
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode([]) // Empty array submitted
        );
```

The parameter `$entity` is the expected entity (the `Article` object).
Both properties exist : `supplier` and `reference`. `supplier` is unchanged compared to the fixture, `reference` is set to `null` as no data is provided.

**Comment by xabbuh** [comment] 2017-07-13 17:20
I am sorry, but I still cannot reproduce your issue. Did you try the latest patch releases (line 137 that you mentioned in the issue description isn't the same in more recent releases)? If you still experience the issue then, can you please create a small example project that allows to reproduce your issue?

**Comment by kimwue** [comment] 2017-07-14 17:27
Same issue here, Symfony 2.8.17

I get this issue when I do not submit the field in my unique entity (when its disabled in the form because its not needed in a case).

**Comment by xabbuh** [comment] 2017-07-14 18:13
Well, it would still be nice to have a small project that would allow to reproduce the issue.

**Comment by flohw** [comment] 2017-07-17 10:46
Hi !

Sorry for the delay, day off and week-end... :-)

Here is a code reproducing the error : https://github.com/flohw/form_errors/
Parameters for mysql connexion are already defined in parameters.yml.dist.

```bash
docker-compose build
docker-compose up -d
docker-compose exec php app/console doctrine:schema:create
```

On `/` submit the form with 'test' as value. It works. Re submit with 'test' as value then it fails.

Symfony version : 2.7.18 (installed with symfony installer, same as my original project).
I tried then to update with composer (version set to 2.8.* in composer.json) but composer says "Nothing to install or update".

**Comment by flohw** [comment] 2017-07-24 07:13
Hi ! Is there some updates here ?

**Comment by xabbuh** [comment] 2017-07-24 07:34
@flohw Sorry for not replying earlier. I have tried your project and the issue indeed is that you are using Symfony 2.8.17. Updating to 2.8.18 (and thus getting the changes from #21562 resolves it). I am closing here as the issue is already fixed.

By the way, the fact that you were not able to update to 2.8.18 is related to the fact that your PHPUnit requirement is bound to `4.1.*`.

**Closed by xabbuh** 2017-07-24 07:34 UTC
Labels: Bug, DoctrineBridge, Status: Waiting feedback

**Comment by flohw** [comment] 2017-07-24 07:43
Ok, I'll try to update phpunit too. Thanks for the hit ! :-)
