### ISSUE TITLE
Web Profiler throws 404 error on new Symfony 3.2 running in a Docker stack

### ISSUE THREAD

**Issue by reypm** [symfony/symfony#21316] opened 2017-01-17 00:55 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

I am starting a new application and I decide to use Docker for development since it's faster and easy to use. I have build my own stack running Centos 7 with Supervisord, Apache/2.4.6, PHP 7.1.0 and MySQL 5.7.17. The stack is available [here](https://github.com/reypm/symfony3app/tree/httpd) and it works as it should be. The instructions to get it up & running are in the README.

The problem I am having is coming from the Web Profiler and I am not able to find out why. As soon as I try to access: `http://symfonyapp.local/app_dev.php` the default page is shown but the next I get is a message saying:
> An error occurred while loading the web debug toolbar (404: Not Found)

I have check the logs in the `httpd` container and this is what I get from there:

```
httpd_1    | 172.18.0.1 - - [17/Jan/2017:00:13:43 +0000] "GET /app_dev.php HTTP/1.1" 200 31820 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
httpd_1    | 2017-01-17 00:13:44,770 DEBG 'httpd' stdout output:
httpd_1    | [Tue Jan 17 00:13:44.770329 2017] [proxy_fcgi:error] [pid 15:tid 140001497048832] [client 172.18.0.1:54532] AH01071: Got error 'Unable to open primary script: redirect:/app.php/28df54 (No such file or directory)\n', referer: http://symfonyapp.local/app_dev.php
```

I have checked all this topics and tried all in there:

 - https://github.com/symfony/symfony/issues/12075
 - https://github.com/symfony/symfony/issues/10806 (@xabbuh asked for replication steps I tried to leave them here)
 - http://stackoverflow.com/questions/31367192/symfony-profiler-throws-404
 - http://stackoverflow.com/questions/16236623/symfony-2-an-error-occurred-while-loading-the-web-debug-toolbar-404-not-foun
 - http://stackoverflow.com/questions/21058750/symfony-2-4-an-error-occurred-while-loading-the-web-debug-toolbar-404-not-fou
 - http://stackoverflow.com/questions/16236623/symfony-2-an-error-occurred-while-loading-the-web-debug-toolbar-404-not-foun
 - http://stackoverflow.com/questions/41646272/ah01071-got-error-unable-to-open-primary-script-container-permissions-or-sy
 - http://stackoverflow.com/questions/21058750/symfony-2-4-an-error-occurred-while-loading-the-web-debug-toolbar-404-not-fou
 - http://stackoverflow.com/questions/12424864/symfony-2-404-not-found-error-when-tryes-to-open-app-dev-php
 - http://stackoverflow.com/questions/31342255/why-is-the-symfony2-profiler-throwing-404s-when-using-the-memcachedprofilerstora
 - http://stackoverflow.com/questions/29345720/404-errors-on-acces-to-wdt-token
 - http://stackoverflow.com/questions/32923216/404-on-wdt-symfony-webprofiler-doesnt-generate-any-profile-data

Can I get some advice on this? Is this a Symfony3 issue, a permission issue, anything else? 

I have an active topic open in SO [here](http://stackoverflow.com/questions/41646272/ah01071-got-error-unable-to-open-primary-script-container-permissions-or-sy) as well and so far I couldn't fix the issue.

**Comment by javiereguiluz** [comment] 2017-01-17 08:44
I'm sorry but I must close this issue. For now, it looks like a support question. When this is confirmed as a Symfony bug (or there's a stronger suspicion about that) we can reopen it. Thanks for understanding it.

There are a lot of Symfony developers using Docker and Symfony 3.2, so this can't be a general problem. In addition to StackOverflow, you can also consider using the `#support` channel in the [Symfony Slack chat](http://slackinvite.me/to/symfony-devs).

**Closed by javiereguiluz** 2017-01-17 08:44 UTC
Labels: Bug, Status: Needs Review, Unconfirmed, WebProfilerBundle

**Comment by Mookum** [comment] 2018-09-10 21:05
Try or add or edit  your  .htaccess file like this
`
Try adding or edit your .htaccess file like this   

    # Use the front controller as index file. It serves as a fallback solution when
    # every other rewrite/redirect fails (e.g. in an aliased environment without
    # mod_rewrite). Additionally, this reduces the matching process for the
    # start page (path "/") because otherwise Apache will apply the rewriting rules
    # to each configured DirectoryIndex file (e.g. index.php, index.html, index.pl).
    DirectoryIndex index.php

    # By default, Apache does not evaluate symbolic links if you did not enable this
    # feature in your server configuration. Uncomment the following line if you
    # install assets as symlinks or if you experience problems related to symlinks
    # when compiling LESS/Sass/CoffeScript assets.
    # Options FollowSymlinks

    # Disabling MultiViews prevents unwanted negotiation, e.g. "/index" should not 
      resolve
    # to the front controller "/index.php" but be rewritten to "/index.php/index".
    <IfModule mod_negotiation.c>
      Options -MultiViews
    </IfModule>

    <IfModule mod_rewrite.c>
      RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the index.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
      RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
      RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache
      RewriteCond %{HTTP:Authorization} .
      RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/index.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
      RewriteCond %{ENV:REDIRECT_STATUS} ^$
      RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
      RewriteCond %{REQUEST_FILENAME} -f
      RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
      RewriteRule ^ %{ENV:BASE}/index.php [L]
    </IfModule>

    <IfModule !mod_rewrite.c>
      <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 307 ^/$ /index.php/
        # RedirectTemp cannot be used instead
      </IfModule>
    </IfModule>

`
