### ISSUE TITLE
[Twig] Form - Bootstrap 4 layout - custom-file-input - not able to see which file are selected in a input file type

### ISSUE THREAD

**Issue by lsv** [symfony/symfony#27477] opened 2018-06-02 22:10 UTC
**Symfony version(s) affected**: 4.1

**Description**  
When rendering a `<input type="file">` with `bootstrap_4_layout.html.twig` enabled, it gives the input a class `custom-file-input` and the label a class `custom-file-label`. The CSS for this, do that its not able to see which file are selected, as in a normal `<input type="file">`

No selected file

![screenshot from 2018-06-02 23-44-52](https://user-images.githubusercontent.com/20708/40881112-7d6f3fdc-66bf-11e8-8897-b7af1c4130c5.png)

And with a file selected

![screenshot from 2018-06-02 23-45-07](https://user-images.githubusercontent.com/20708/40881115-85d82fe4-66bf-11e8-8034-0e9ec593bda7.png)

Now if you in the FormType set the label to false on the element, also I have added a placeholder with ['attr' => ['placeholder' => 'Choose file']

![screenshot from 2018-06-02 23-47-21](https://user-images.githubusercontent.com/20708/40881123-9e4c2be8-66bf-11e8-84a6-de7db6a97af6.png)

(Yes totally blank, but still able to select a file by clicking in the empty area, but still blank after selected a file)

**How to reproduce**  
```
composer create-project symfony/skeleton
composer require twig annotations form
```
Create a form type with type `Symfony\Component\Form\Extension\Core\Type\FileType`
Add the bootstrap 4 css to twig `https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css` 
Add `form_themes: ['bootstrap_4_layout.html.twig']` to `config/packages/twig`
Create a controller with your form type

Or just clone `https://github.com/lsv/twig_bootstrap4_filetype`

**Possible Solution**  
The `custom-file-label` and `custom-file-input` classes should be removed, or reworked.

With the following code

```
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('file', FileType::class, [
                'label' => 'PDF file',
            ])
            ->add('label_false', FileType::class, [
                'label' => false,
            ])
            ->add('label_null', FileType::class, [
                'label' => null,
            ])
            ->add('file_label_false_placeholder', FileType::class, [
                'label' => false,
                'attr' => ['placeholder' => 'Choose file'],
            ])
            ->add('file_label_null_placeholder', FileType::class, [
                'label' => null,
                'attr' => ['placeholder' => 'Choose file'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'mapped' => false,
        ]);
    }
}
```

This will be the result

![screenshot from 2018-06-03 00-11-28](https://user-images.githubusercontent.com/20708/40881287-f4cea998-66c2-11e8-9d0a-7de9322e19b7.png)

**Comment by brad-goss** [comment] 2018-11-30 19:41
Still seems to be an issue here. I need to add css to make something show up.

.custom-file-label { opacity: 0; }
.custom-file-input { opacity: 1; }

**Comment by Marivint** [comment] 2018-12-04 09:01
Same here, all people in my school class can't see the file name when selected.

**Comment by apfelbox** [comment] 2018-12-04 09:08
The problem is not the class, but that a custom form field doesn't automatically update if the underlying form field changes.
So if you want to keep the Bootstrap form field (which we should, as this is the Bootstrap form theme) you won't have this functionality. Please note that the Bootstrap website itself has the exact same issue.

Please see the discussion here for a) how to fix the described issue and b) maybe discuss whether we should maybe add this JS inline in the form theme.

https://github.com/symfony/symfony/pull/27919#issuecomment-404163495

**Comment by xabbuh** [comment] 2019-04-06 17:07
I am closing here as the behaviour is consistent with the Bootstrap behaviour.

**Closed by xabbuh** 2019-04-06 17:07 UTC
Labels: Bug, Form, Status: Needs Review, TwigBridge

**Comment by Janest** [comment] 2019-05-13 13:17
I'm adding a comment on this closed issue cos the beheviour is in fact not consistent with the Bootstrap.
The  bootstrap_4_layout.html.twig uses the 'custom-file-input' class for file inputs when the Bootstrap documentation tells us to use the 'form-control-file' class.
[https://getbootstrap.com/docs/4.1/components/forms/#form-controls](url)
Is it possible to reopen this issue or is it better to open a new one ?
Regards

**Comment by xabbuh** [comment] 2019-05-15 07:20
@Janest Even on the documentation page that you linked to you can find an example using `custom-file-input`.

**Comment by Janest** [comment] 2019-05-15 09:51
@xabbuh Indeed, and it doesn't display the chosen file name, it's below this explanation : 

> The file input is the most gnarly of the bunch and requires additional JavaScript if you’d like to hook them up with functional Choose file… and selected file name text.

It's also writen on that page, in the section I mentioned : 

> For file inputs, swap the .form-control for .form-control-file.

And the example below displays the chosen file name as expected.

**Comment by florianajir** [comment] 2019-11-18 11:33
Still not working with bootstrap 4.3 ??

**Comment by The-Who** [comment] 2020-03-10 13:31
You might use **bs-custom-file-input** plugin to set placeholders automatically when the file was chosen.

Just add the following script to the symfony project:
`<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>`

Then init the script (base.twig.html template):
```
$(document).ready(function () {
  bsCustomFileInput.init()
})
```

Plugin: https://www.npmjs.com/package/bs-custom-file-input
Demo: https://bs-custom-file-input.netlify.com

Boostrap documentation reference: https://getbootstrap.com/docs/4.4/components/forms/#file-browser
