### ISSUE TITLE
Workflow component - incorrect announce events 

### ISSUE THREAD

**Issue by klimenttoshkov** [symfony/symfony#39981] opened 2021-01-26 15:39 UTC
**Symfony version(s) affected**: Workflow 5.2

**Description**  
When transition is completed "announce" events are triggered. According to documentation:
```
workflow.announce
Triggered for each transition that now is accessible for the subject.
```

Instead the event that is triggered is for the already completed transition, which effectively makes it equivalent to "completed" event.

**How to reproduce**  
Apply transition and capture the events.

**Possible Solution**  

**Additional context**  
I have tested to disable announce events and found out that the guard events for every accessible transition from the new place are triggered only when announce events are enabled. But the announce event itself is for the completed transition.

**Comment by klimenttoshkov** [comment] 2021-01-28 12:47
When applying transition 'toProcessing' the following events were dispatched:

![bsms incoming](https://user-images.githubusercontent.com/59835221/106140536-92649580-6177-11eb-8df1-04850c77114f.png)

```
[2021-01-28 14:27:40] local.DEBUG: Received event: workflow.bsmsIncoming.entered  
[2021-01-28 14:27:41] local.DEBUG: Received event: workflow.bsmsIncoming.guard  
[2021-01-28 14:27:41] local.DEBUG: Received event: workflow.bsmsIncoming.guard.toProcessing  
[2021-01-28 14:27:41] local.DEBUG: Received event: workflow.bsmsIncoming.leave  
[2021-01-28 14:27:42] local.DEBUG: Received event: workflow.bsmsIncoming.leave.new  
[2021-01-28 14:27:42] local.DEBUG: Received event: workflow.bsmsIncoming.transition  
[2021-01-28 14:27:42] local.DEBUG: Received event: workflow.bsmsIncoming.transition.toProcessing  
[2021-01-28 14:27:42] local.DEBUG: Received event: workflow.bsmsIncoming.enter  
[2021-01-28 14:27:43] local.DEBUG: Received event: workflow.bsmsIncoming.enter.processing  
[2021-01-28 14:27:43] local.DEBUG: Received event: workflow.bsmsIncoming.entered  
[2021-01-28 14:27:43] local.DEBUG: Received event: workflow.bsmsIncoming.entered.processing  
[2021-01-28 14:27:44] local.DEBUG: Received event: workflow.bsmsIncoming.completed  
[2021-01-28 14:27:44] local.DEBUG: Received event: workflow.bsmsIncoming.completed.toProcessing  
[2021-01-28 14:27:44] local.DEBUG: Received event: workflow.bsmsIncoming.announce  
[2021-01-28 14:27:45] local.DEBUG: Received event: workflow.bsmsIncoming.announce.toProcessing  
[2021-01-28 14:27:45] local.DEBUG: Received event: workflow.bsmsIncoming.guard  
[2021-01-28 14:27:45] local.DEBUG: Received event: workflow.bsmsIncoming.guard.toFloodProtection  
[2021-01-28 14:27:45] local.DEBUG: Received event: workflow.bsmsIncoming.guard  
[2021-01-28 14:27:46] local.DEBUG: Received event: workflow.bsmsIncoming.guard.toFloodProtection_failed  
[2021-01-28 14:27:46] local.DEBUG: Received event: workflow.bsmsIncoming.entered  
[2021-01-28 14:27:46] local.DEBUG: Received event: workflow.bsmsIncoming.guard  
[2021-01-28 14:27:46] local.DEBUG: Received event: workflow.bsmsIncoming.guard.toProcessing  
```

expected to see event `workflow.bsmsIncoming.announce.toFloodProtection`

**Comment by Nyholm** [comment] 2021-03-01 19:17
Looking at your logs. I guess that you have a guard for `workflow.bsmsIncoming.guard.toFloodProtection` which blocks the transition. 

Here is some code that relates to this: https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/Workflow/Workflow.php#L441-L455
This code will also explain why no guard events are dispatched when you disable the annouce event. The `getEnabledTransitions()` is checking with the guards. 


-------

What I cannot explain is the last two entries and the first one... It also seams like some of these logs are out of order (and they are running super slowly.. 6 seconds!)

See the order here: https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/Workflow/Workflow.php#L231-L245

**Comment by klimenttoshkov** [comment] 2021-03-02 12:38
Hi @Nyholm 

Thank you for taking time to review my report.

We do have guard for `workflow.bsmsIncoming.guard.toFloodProtection` but it does not block the transition. Actually it should be announced as available when entering `processingz place.

I have confirmed and tested with test workflows which do not have guards at all.

I understand why guard events are dispatched only when announce event is enabled. This is by design and should work this way. My intention mentioning this was to make it clear that I understand the connection between announce event and guards.

I also do not understand why wrong events are dispatched. I guarantee events are not out of order, they are processed in async FIFO queue with one worker and approximately one action per second, this is why it took 6 seconds.

Again - the problem is that I do not see dispatched announce events for the available transitions.

**Comment by Nyholm** [comment] 2021-03-02 13:04
Hm, That is really interesting. Could you help debugging by replicate this bug in a new small application? 
Ie create a new repo, install symfony and the workflow component. Add a small workflow and then write a small script/command to test this. 

This way we can exclude any external factors that may cause this issue.

**Comment by klimenttoshkov** [comment] 2021-03-02 14:25
Here is fresh application with simple workflow:

![test](https://user-images.githubusercontent.com/59835221/109662457-bf8bd580-7b73-11eb-85fa-827f05f8fa54.png)

As I understand the documentation, when transitioning to `ready` place, the component should broudcast `workflow.test.announce.tob1` and `workflow.test.announce.tob2`. Neither of them was fired and instead I can see only `workflow.test.announce.toReady`.

This is the log of events when transition `toReady` is applied. Please note that there are *not* any guards defined in code:
```
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.entered  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard.toReady  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.leave  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.leave.a  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.transition  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.transition.toReady  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.enter  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.enter.ready  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.entered  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.entered.ready  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.completed  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.completed.toReady  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.announce  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.announce.toReady  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard.tob1  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard  
[2021-03-02 14:16:33] local.DEBUG: Event: workflow.test.guard.tob2  
```

Workflow definition:
```
    'test' => [
        'supports' => [
            Test::class,
        ],

        // 'events_to_dispatch' => [
            // WorkflowEvents::ANNOUNCE,
        // ],

        'places' => [
            'a' => [
                'metadata' => [
                    'max_num_of_words' => 500,
                ],
            ],
            'ready',
            'b1', 'b2',
            'c',
        ],

        'initial_places' => [
            'a', 
        ],

        'transitions' => [
            'toReady' => [
                'from' => 'a',
                'to' => 'ready',
            ],
            'tob1' => [
                'from' => 'ready',
                'to' => 'b1',
            ],
            'tob2' => [
                'from' => 'ready',
                'to' => 'b2'
            ],

            'toc' => [
                'from' => ['b1', 'b2'],
                'to' => 'c'
            ],

        ],
    ],
```

Code to create model and apply transition:
```
        $test = new Test();
        $marking = $test->workflow_apply('toReady');
```

This is my event subscriber in case you need it:
```
    public function handleGlobal($event)
    {
        Log::debug('Event: ' . $event);
    }


    public function subscribe($events)
    {
        $events->listen(
            'workflow.test.*',
            [TestSubscriber::class, 'handleGlobal']
        );
    }
```

This is Laravel application with appropriate service provider. The most interesting part for you should probably be [src/Events/WorkflowSubscriber.php](https://github.com/zerodahero/laravel-workflow/blob/develop/src/Events/WorkflowSubscriber.php) which simply subscribes to Symfony events and fires equal Laravel events. I have inspected it and I am sure that it just subscribes and passes events unmodified.

**Comment by xabbuh** [comment] 2021-03-02 14:51
Can you please wrap your code examples in an application that we could clone and debug what is going on?

**Comment by xabbuh** [comment] 2021-03-08 08:44
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Nyholm** [comment] 2021-03-08 08:47
I will still be happy to see a repository with the minimal code to reproduce this issue.

**Comment by klimenttoshkov** [comment] 2021-03-08 09:59
Hello,

This is the [test application](https://github.com/klimenttoshkov/symfony-workflow-announce-event-test).
Clone, do `composer update` and then `php artisan wf:create`. Inspect `storage/logs/laravel.log`.

Workflow definition is in `config/workflow.php`

**Comment by Nyholm** [comment] 2021-03-08 10:56
You gave me a link to a full laravel application... How can I know if the issue is in the Workflow component or in any of the other code modifying the config, event dispatcher or the events being dispatched. It is important that the repo contains as little code as possible. 

I created a reproducer myself: https://github.com/Nyholm/sf-issue-39981

This shows the expected output: 

```
❯ php src/app.php
Event name "workflow.guard"
Event name "workflow.acme.guard"
Event name "workflow.acme.guard.toReady"
Event name "workflow.leave"
Event name "workflow.acme.leave"
Event name "workflow.acme.leave.a"
Event name "workflow.transition"
Event name "workflow.acme.transition"
Event name "workflow.acme.transition.toReady"
Event name "workflow.enter"
Event name "workflow.acme.enter"
Event name "workflow.acme.enter.ready"
Event name "workflow.entered"
Event name "workflow.acme.entered"
Event name "workflow.acme.entered.ready"
Event name "workflow.completed"
Event name "workflow.acme.completed"
Event name "workflow.acme.completed.toReady"
Event name "workflow.announce"
Event name "workflow.acme.announce"
Event name "workflow.guard"
Event name "workflow.acme.guard"
Event name "workflow.acme.guard.tob1"
Event name "workflow.guard"
Event name "workflow.acme.guard"
Event name "workflow.acme.guard.tob2"
Event name "workflow.acme.announce.tob1"
Event name "workflow.acme.announce.tob2"
```

Feel free to modify https://github.com/Nyholm/sf-issue-39981 to bring it to a state with minimal code that also reproduces the issue.

**Comment by klimenttoshkov** [comment] 2021-03-08 11:21
You are right about the full Laravel app. Before opening the bug report, I have inspected the Symfony event subscriber, that raises Laravel events and found no issue there. Of course I will reinspect it again and will ask for their cooperation as well. Please allow me a few days.

**Comment by klimenttoshkov** [comment] 2021-03-17 15:09
Hi all,

We have been in active discussion with Laravel package manager and found out the root cause of the problem.

Now my question is (not directly related to workflows): Is there official way to subscribe to all events? Using wildcard or another option.

**Comment by xabbuh** [comment] 2021-03-17 15:13
That's not supported out of the box.

**Comment by klimenttoshkov** [comment] 2021-03-17 15:17
@xabbuh Yes, and this is the problem. Laravel package has "dynamic" features, that allow to build workflow later, not load it from config file. For this reason it is not possible to build up a list of predefined event names, that include all announce transitions. This package subscribes to workflow.announce event and when received, re-creates all other events to mimic Symfony behaviour. While this works fine for guards and other events, it obviously fails with announce events.

Can you suggest proper way to subscribe to all announce events? Or something similiar in approach, in order to achieve possibility to fire equal events in Laravel as they are fired from Symfony. Thank you

**Comment by Nyholm** [comment] 2021-03-17 15:17
Not wildcard no. But you could subscribe to `workflow.leave`, `workflow.enter` etc to get a notification for any workflow that leave/enter a node.

**Comment by klimenttoshkov** [comment] 2021-03-17 15:18
@Nyholm we do it this way but it is not working for announce events in the part that we need to somehow distinguish announce.transitionName. This way we can only receive workflow.announce event which does not carry the necessary information for transitions. Please look above my previous comment for details?

**Comment by Nyholm** [comment] 2021-03-17 15:23
I've read the thread here: https://github.com/zerodahero/laravel-workflow/issues/40

One way forward for you is to use a custom implementation of the event dispatcher that includes the features you want, ie pattern matchning. That way you can register the events you want. 

Since this bug is confirmed to be in a separate package, I will close this issue. I know that [Symfony slack](https://symfony.com/support) channel `#support` has a lot of active people that would like to help with ideas for your package/application.

**Closed as completed by Nyholm** 2021-03-17 15:23 UTC
Labels: Bug, Status: Needs Review, Workflow
