### ISSUE TITLE
Decoration and autoconfigure exhibit poor DX with tagged services.

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#30391] opened 2019-02-27 08:45 UTC
**Symfony version(s) affected**: 4.2.3

**Description**  
I've come across an odd case which may be entirely "intended", but results in very poor DX which is hard to debug.

Basically, 
1. if you decorate a service, 
2. the decorated service has a tag
3. autoconfigure is enabled for your decorated service

you get some strange results which are confusing at first

**How to reproduce**  
Reproducer:
https://github.com/bendavies/normalizer-decoration-demo

I have define a new [normalizer](https://github.com/bendavies/normalizer-decoration-demo/blob/master/src/Serializer/Normalizer/DateTimeNormalizer.php), [decorating](https://github.com/bendavies/normalizer-decoration-demo/blob/master/config/services.yaml#L30-L31) the symfony normalizer.

1. the priority of my normalizer looks to have been "reset". The usual priority is -910. As a developer, my expectation might be that the priority is not reset here if i'm decorating a service that has a tag/priority already. I suspect it has not been reset really, (see point 2 below), but it looks wrong anyway.

```
bin/console debug:container --tag serializer.normalizer

Symfony Container Services Tagged with "serializer.normalizer" Tag
==================================================================

 ------------------------------------------------- ---------- ---------------------------------------------------------------------------
  Service ID                                        priority   Class name
 ------------------------------------------------- ---------- ---------------------------------------------------------------------------
  App\Serializer\Normalizer\DateTimeNormalizer                 App\Serializer\Normalizer\DateTimeNormalizer
  serializer.denormalizer.array                     -990       Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
  serializer.normalizer.constraint_violation_list   -915       Symfony\Component\Serializer\Normalizer\ConstraintViolationListNormalizer
  serializer.normalizer.data_uri                    -920       Symfony\Component\Serializer\Normalizer\DataUriNormalizer
  serializer.normalizer.dateinterval                -915       Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer
  serializer.normalizer.json_serializable           -900       Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer
  serializer.normalizer.object                      -1000      Symfony\Component\Serializer\Normalizer\ObjectNormalizer
 ------------------------------------------------- ---------- ---------------------------------------------------------------------------
```

2. from `bin/console debug:container --tag serializer.normalizer`, the `DateTimeNormalizer` is listed once, but in fact there are two of them registered as normalizers. I expect this is due to the fact that 1 instance is created by autoconfigure, and the other is the decoration. This can be seen by looking at the configured normalizers in the serializer. There is a command `bin/console app:date-time` to kick off the normalization if you want to use it to debug, or can you can look at the dumped container.

![image](https://user-images.githubusercontent.com/625392/53476950-83e14100-3a6b-11e9-8220-d46d54ded9b6.png)

So, i'm not sure what, if anything, but can be classified as a bug here, but its definitely bad DX from my point of view.

The two issues can be fixed by disabling auto configure (`autoconfigure: false`) on the `App\Serializer\Normalizer\DateTimeNormalizer` service.

**Comment by dunglas** [comment] 2019-02-27 10:23
It looks like a bug to me. Only the outer service of the decoration hierarchy should be kept.

**Comment by xabbuh** [comment] 2019-02-27 10:27
To me this looks expected. When decorating a tagged service, the tags of the service being decorated must not be lost.

**Comment by dunglas** [comment] 2019-02-27 10:30
@xabbuh but service decoration is intended to replace the decorated service by the decorator. Here it's not what happens, because the same instance is registered two times. It affects the Serializer, but I'm sure it also affects many other passes using tags.

There is at least a bug in the Serializer, but I think that the issue is broader. What we could do is to exclude from internal compiler passes (like the Serializer one) services that are decorated. We should also provide a trait to allow users to execute the same exclusion logic in their own passes. WDYT?

**Comment by stof** [comment] 2019-02-27 13:19
the issue here is that the original `serializer.normalizer.datetime` is tagged with some priority and registered accordingly. The fact that it gets decorated means that the App normalizer gets injected there (that's index 2 in your final array). but your own `App\Serializer\Normalizer\DateTimeNormalizer` is *also* tagged (by the autoconfiguration, and without priority). And so both `serializer.normalizer.datetime` and `App\Serializer\Normalizer\DateTimeNormalizer` get injected as deps in the serializer (even though they end up being the same object).

As your own service is meant to decorate the existing normalizer which is already registered in the serializer, you should not also register your normalizer by itself.

Excluding tags on a decorating services is not the solution. It would break features. If you have a memoizing decorator, it might make perfect sense to tag the decorator service as resettable (to clear its memoization), because that's a behavior that belongs to it.

The issue here is that autoconfiguration added a `serializer.normalizer` tag on a service that you don't want to tag.
Maybe we should disable autoconfiguration for decorating services automatically or have a way to mark some autoconfiguration rules as disabled for decorating services. But that second suggestion would be hard, because the same interface could need both behaviors:
- you might be decorating the autoconfigured interface => should not tag the decorating service
- you might be decorating another interface and implementing this extra one => autoconfiguration might work fine (example, having a Resettable implementation of another interface, as for my memoizing decorator and then it is still fine to autoconfigure the `kernel.reset` tag)

**Comment by stof** [comment] 2019-02-27 13:20
`bin/console debug:container --tag serializer.normalizer` does not allow debugging this case fully, because the original `serializer.normalizer.datetime`(reassigned to `App\Serializer\Normalizer\DateTimeNormalizer.inner` by the decoration pass) got inlined, and so does not appear in the output.

**Comment by dunglas** [comment] 2019-02-27 13:34
> Maybe we should disable autoconfiguration for decorating services automatically

It looks like the more pragmatic fix. Thanks for investigating!

**Comment by nicolas-grekas** [comment] 2019-02-27 13:42
Looks sensible to me!

**Comment by dunglas** [comment] 2019-03-01 09:44
Can you test if #30417 fix your issue @bendavies please?

**Comment by bendavies** [comment] 2019-03-01 14:51
@dunglas it does

**Closed** 2019-03-04 08:49 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
