### ISSUE TITLE
[Question] SerializerInterface as standard

### ISSUE THREAD

**Issue by rogeriolino** [symfony/symfony#17285] opened 2016-01-06 20:04 UTC
I'm writing a code that implements a serializer interface but I dont want (dont need) to include all Symfony Serializer implementation code to my project, therefore I've just copied SerializerInterface.php to my project to use it. 

Then my question is to create a packagist library for `SerializerInterface` to use as standard (like PSR-7) and add this "new" library as dependency of `symfony/serializer`.

Regards.

**Comment by Tobion** [comment] 2016-01-08 01:01
Duplicate of #6129

**Closed by Tobion** 2016-01-08 01:01 UTC
