### ISSUE TITLE
Locale::getFallback returns false instead of null and infinite loop begins

### ISSUE THREAD

**Issue by vytsci** [symfony/symfony#31106] opened 2019-04-14 15:05 UTC
**Symfony version(s) affected**: 3.x, 4.x

**Description**  
Due to update in php-intl library this loop is infinite.
https://github.com/symfony/symfony/blob/95932df2ac5edd98db521bb6507d22edcdc602c6/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php#L81

**How to reproduce**  
Update php-intl to the latest version and try to get country names for en locale for example.

**Possible Solution**  
For BC it would be great to loop until locale is empty so check could be !empty($currentlocale)

**Additional context**  
Ive been struggling with this all morning, later I had to code on my laptop and this error was not present, Ive updated php-intl and error became present as on my work PC.

**Comment by ro0NL** [comment] 2019-04-15 06:45
duplicate of #31089?

**Comment by vytsci** [comment] 2019-04-15 10:47
Yep sorry, I think so.

**Closed** 2019-04-15 10:50 UTC
Labels: Bug, Intl, Status: Needs Review, Status: Waiting feedback

**Comment by jakzal** [comment] 2019-04-15 12:54
@vytsci the fix is present in the 3.4 branch.

**Comment by vytsci** [comment] 2019-04-15 13:27
@jakzal yes Ive already found it. ty
