### ISSUE TITLE
failed to open stream: Resource temporarily unavailable

### ISSUE THREAD

**Issue by sergioatzori** [symfony/symfony#23097] opened 2017-06-07 19:23 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-DEV

I'm experiencing this since 3.3. When I run my Behat tests, randomly happens to get this error that stops behat:

```
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                        
 Warning: file_put_contents(/home/xxxx/CORE/var/cache/api-backoffice/bdd/appBddDebugProjectContainerDeprecations.log): failed to open stream: Resource temporarily unavailable 
```

I've no memory limits set in php for cli:
```
$ php --version
PHP 7.0.19-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies
$ cat /etc/php/7.0/cli/php.ini |grep memory_limit 
memory_limit = -1
```
This never happens when I call api's endpoint outside behat.

**Comment by sergioatzori** [comment] 2017-06-10 10:56
Some progress: the problem is gone by disabling the profiler collector on my behat environment.
So the problem seems in the profiler.
With this workaround I can successfully run my behat tests, but I cannot debug my code using profiler...
Furthermore I did a strace with collector turned on, and I can see that it's full of EAGAIN:
```
$ cat strace-CORE-behat_collect-active.txt |grep "EAGAIN"
read(10, 0x55cb8eba1e60, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(10, 0x55cb8eba1e63, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(12, 0x55cb8ebc2470, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(12, 0x55cb8ebc2473, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(14, 0x55cb8ebd4ea0, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(14, 0x55cb8ebd4ea3, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(16, 0x55cb8ebdcff0, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(16, 0x55cb8ebdcff3, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(18, 0x55cb8ecf9a60, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(18, 0x55cb8ecf9a63, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(20, 0x55cb8ed1e360, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(20, 0x55cb8ed1e363, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(22, 0x55cb8ed526e0, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(22, 0x55cb8ed526e3, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(24, 0x55cb8ed846c0, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(24, 0x55cb8ed846c3, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(26, 0x55cb8edab920, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(26, 0x55cb8edab923, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(28, 0x55cb8ede5b30, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(28, 0x55cb8ede5b33, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(29, 0x55cb8ede5b30, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(29, 0x55cb8ede5b33, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(31, 0x55cb8ee2d8f0, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(31, 0x55cb8ee2d8f3, 5)             = -1 EAGAIN (Resource temporarily unavailable)
read(33, 0x55cb8ee5e840, 7)             = -1 EAGAIN (Resource temporarily unavailable)
read(33, 0x55cb8ee5e843, 5)             = -1 EAGAIN (Resource temporarily unavailable)
open("/home/xxxxxxx/CORE/var/cache/api-backoffice/bdd/appBddDebugProjectContainerDeprecations.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EAGAIN (Resource temporarily unavailable)
```
I hope this can help addressing this issue.

**Comment by javiereguiluz** [comment] 2017-07-17 07:11
@sergioatzori in #23465 we made a lot of optimizations for the profiler data. Could you please try that and see if things have improved? Thanks!

**Comment by sergioatzori** [comment] 2017-07-17 14:13
After a "composer update" over 3.4.x-dev the issue is still here...:-(
Could you can give me some advice to inspect this problem?

**Comment by nicolas-grekas** [comment] 2017-07-17 14:20
Are you running on a native Debian or a VM/container? If not native, what is the host OS?

**Comment by sergioatzori** [comment] 2017-07-17 15:05
Debian on VM. I don't know host's OS because this is a cloud instance (OVH public cloud).

**Comment by nicolas-grekas** [comment] 2017-11-27 13:40
Still experiencing this? Dumping the container changed a lot since July.

**Comment by sergioatzori** [comment] 2017-12-06 10:44
After updating my whole project to stable 3.4.1 the problem is still there :-(
My composer.json is taken from symfony standard edition except for php version (I've 7.0.*).
I cannot run my behat tests with collector active, this is really annoying...

**Comment by fabpot** [comment] 2018-05-30 05:50
I'm going to close this issue as nobody else reported similar issues and unfortunately, we cannot do anything without being able to reproduce it ourselves.

**Closed by fabpot** 2018-05-30 05:50 UTC
Labels: Bug, Status: Waiting feedback, VarDumper, WebProfilerBundle

**Comment by sergioatzori** [comment] 2018-05-30 08:45
Hello Fabien, I've updated Symfony to 3.4.11: this fixed the issue.
I can confirm that behat tests (with collector active) are now faster.
Thank you

**Comment by mola93** [comment] 2019-09-16 11:36
Deleting your log file (appBddDebugProjectContainerDeprecations.log) will fix the issue.

**Comment by mitchelstarc101** [comment] 2023-05-08 06:36
still facing same error https://prnt.sc/jXuuY2j2A-vs while installing create directory of magento coding standard in windows10
