### ISSUE TITLE
[DI] ChildDefinition and getArguments

### ISSUE THREAD

**Issue by er1z** [symfony/symfony#31561] opened 2019-05-21 07:58 UTC
**Symfony version(s) affected**: dev-master and below (AFAIK)

**Description**  
If you create a definition with parent arguments overrides, any `CompilerPass` that depends on arguments mangling with fail if they are fetched via `getArguments` on `Definition`.

**How to reproduce**  
create a service with parent, for example:
```
parent:
    abstract: true
    class: SomeClass
    arguments: ['me', 'you']

child:
    parent: 'parent'
    class: SomeClass
    arguments:
        index_0: 'ME'
        index_1: 'YOU'
```

Then playing with definition in compiler pass produces:
```
$def = $container->getDefinition('child');
$def->getArgument(0);  // 'ME'
$def->getArguments()[0]; // 'me' (???)
```

**Possible Solution**  
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ChildDefinition.php#L74
Create overriden `getArguments` in `ChildDefinition` which will take into account its new arguments values first (as `getArgument` does).

**Additional context**  
This issue makes creation of admin prototypes in Sonata unusable because it relies on `getArguments` which ignores overriden arguments.

I can try to make adequate pull request if it's bug. Tried to figure it out on Slack but no one answered.

**Comment by xabbuh** [comment] 2019-05-21 08:31
Reading the code I'd say something like this works as expected:

```yaml
parent:
    abstract: true
    class: SomeClass
    arguments: ['me', 'you']

child:
    parent: 'parent'
    class: SomeClass
    arguments:
        $foo: 'ME'
        $bar: 'YOU'
```

@er1z Can you confirm this? In this case I would say that this bug report is valid.

**Comment by er1z** [comment] 2019-05-21 08:46
But you have used named arguments whereas I mean indexed ones.

**Comment by xabbuh** [comment] 2019-05-21 08:55
This was intended. What I meant was that I would expect them to behave the same which from my understanding of the current code isn't true right now.

**Comment by er1z** [comment] 2019-05-21 08:57
But why behavior of `getArgument` vs. `getArguments` is different?

**Comment by xabbuh** [comment] 2019-05-21 09:05
I think we are misunderstanding each other. :) What I mean is that we should check if both methods also behave differently when using named arguments (I think they don't, but we should check). And in that case I would agree that this is a bug.

**Comment by er1z** [comment] 2019-05-21 09:13
Ok, I'll try this later and post update.

**Comment by Simperfit** [comment] 2019-05-21 17:58
Status: Waiting feedback

**Comment by nicolas-grekas** [comment] 2019-05-21 18:07
To me, there's no bugs here. That's how ChildDefiniton behaves for a reason, see how ResolveChildDefinitionPass works.
One should build with these behaviors in mind.

**Comment by nicolas-grekas** [comment] 2019-06-05 16:58
Closing as explained.

**Closed by nicolas-grekas** 2019-06-05 16:58 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
