### ISSUE TITLE
AJAX requests in the web debug toolbar doesn't catch requests with absolute url

### ISSUE THREAD

**Issue by CSchulz** [symfony/symfony#12816] opened 2014-12-02 23:25 UTC
Hello,

I have noticed not all of my AJAX requests are catched by the new feature of 2.6 in WebProfilerBundle.

If you create an url with the twig function `url` they aren't recognized. With urls generated by `path` it works.

I am on version 2.6.

**Comment by thomas-koch-comsolit** [comment] 2015-01-14 14:09
this is a duplicate of #12221

**Closed** 2015-01-14 14:25 UTC
Labels: WebProfilerBundle
