### ISSUE TITLE
Version 2.7.12 break compiler

### ISSUE THREAD

**Issue by kjaniszewski** [symfony/symfony#18671] opened 2016-04-29 10:33 UTC
```
myyummie@staging:/var/www/myyummie/app$ php console --verbose

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Illegal offset type in isset or empty
```

Exception trace:

```
 () at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php:133
 Symfony\Component\Debug\ErrorHandler->handleError() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php:133
 Symfony\Component\DependencyInjection\Compiler\ReplaceAliasByActualDefinitionPass->updateFactoryReferenceId() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php:80
 Symfony\Component\DependencyInjection\Compiler\ReplaceAliasByActualDefinitionPass->process() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:104
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:574
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/myyummie/app/bootstrap.php.cache:2647
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/myyummie/app/bootstrap.php.cache:2425
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/myyummie/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /var/www/myyummie/app/console:27
```

On 2.7.11 everything works correctrly

Best regards
Krzychu

**Comment by iltar** [comment] 2016-04-29 11:37
Can you check what it's called with? https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php#L133

**Comment by xabbuh** [comment] 2016-04-29 16:12
@kjaniszewski Can you please check what @Iltar suggested? It looks like you have a misconfigured factory service (as the `getFactoryService()` method should only return strings or `null`.

**Comment by nykopol** [comment] 2016-05-02 13:01
I have the same issue. It's work well in 2.7.11 but give me this error on 2.7.12.

**Comment by xabbuh** [comment] 2016-05-02 13:07
@nykopol Can you please give an example on how to reproduce your issue?

**Comment by nykopol** [comment] 2016-05-02 13:13
I just found my problem. I build a service with this code : 

```
$definition = new Definition('My\Class\Name', array($name));
$definition->setFactoryService(new Reference('my_factory_service_id'));
$container->setDefinition('my_service_id', $definition);
```

I can make it work by changing my code with this : 

```
$definition->setFactoryService('my_factory_service_id');
```

**Comment by stof** [comment] 2016-05-02 13:23
passing a Reference to ``setFactoryService`` was never meant to work. The method is documented as ``@param string $factoryService``.
So passing a castable object here may have worked by chance in the past, but it does not qualify as a BC break here, as you were the one breaking the method contract.

**Comment by javiereguiluz** [comment] 2016-05-02 13:30
@nykopol I'm glad this is working again. I'm closing this because it seems to be not a bug, but feel free to reopen if needed. Thanks.

**Closed by javiereguiluz** 2016-05-02 13:30 UTC
Labels: DependencyInjection, Status: Needs Review, Unconfirmed

**Comment by nykopol** [comment] 2016-05-02 13:33
@stof @javiereguiluz  i agree with you in my case it's my fault. We should maybe see if @kjaniszewski is in the same case ?

**Comment by romaricdrigon** [comment] 2016-10-07 13:50
For people that end up there after a Google search, it looks like Doctrine cache bundle is the offender:
https://github.com/doctrine/DoctrineCacheBundle/blob/1.3.0/DependencyInjection/Definition/MongodbDefinition.php#L65

It is corrected in master, so I guess a new version will soon land.

**Comment by fafiebig** [comment] 2016-10-31 10:03
thanks @romaricdrigon - exactly fos elastica in this particular version did the break - you saved me alot of time ;)
