### ISSUE TITLE
[Console] Formatting breaks on new line

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#19172] opened 2016-06-24 15:29 UTC
Hi,

Formatting seems to break on new lines.

![image](https://cloud.githubusercontent.com/assets/1047696/16342237/5d5ca700-3a31-11e6-8a3c-acb702d47545.png)

`//` on the last line should be white

**Comment by chalasr** [comment] 2016-06-24 21:36
Hi @ro0NL.

Do you get this output by calling `SymfonyStyle::comment()` with an array of strings as argument?
I think this issue exists since the method use `SymfonyStyle::block`, as you said. 
The change has been made in https://github.com/symfony/symfony/pull/18889

**Comment by chalasr** [comment] 2016-06-24 22:51
It only happens on `comment()` since messages are formatted and use `block()` with a prefix (made in #18889). For now I don't see any solution since the console colours whatever char between the opening tag and the closing one. A workaround is too manually break lines by passing an array of strings rather than a long string then cut the tag for each line, but it's very not a real solution...

**Comment by ro0NL** [comment] 2016-06-25 06:58
Hi,

I checked it last night.. and this can get really complex :-)

My thoughts so far;-
- Fix/support it at `block()` level for efficiency, `comment()` should be just a proxy method
- Test each line for a (partial) opening tag (before/after formatting) without a closing tag
- Get next lines by reference until closing tag is found
- Fix the formatting for the starting/ending line (ie finalize and close formatting tags per line as this doesnt affect line length visually)

Another solution could be to capture all string offsets for tags, remove them, wrap etc., recalculate offsets and replace/format them manually afterwards.

**Comment by ro0NL** [comment] 2016-06-25 07:04
Or match broken tags after wrapping and before formatting, ie `'<[^.]*'.preg_quote(PHP_EOL.$prefix.PHP_EOL).'.[^>]*>`. Fix, then format.

**Comment by ro0NL** [comment] 2016-06-25 07:07
This targets 2.7 btw

**Comment by ro0NL** [comment] 2016-06-25 07:26
To clearify, i removed formatting at `comment()` level and expected the following string to be formatted due `writeln`

```
// Provide the name of a bundle as the first argument of this command to dump its configuration. (e.g. 
// <comment>debug:config FrameworkBundle</comment>) 
```

However escaping kicks in first.

**Comment by chalasr** [comment] 2016-06-25 08:01
> Seems formatting for block() is supported (i.e. writeln already has built-in formatting) but is terribly broken right now :)

Not sure but, even if it calls `writeln()` at the end, I think that `block()` doesn't and shouldn't support formatting through tags, the style needs to be passed as third argument and format the whole block based on, that's why messages are first escaped.

> Or match broken tags after wrapping and before formatting, ie <[^>]*'.preg_quote(PHP_EOL.$prefix.PHP_EOL).'[^>]*>. Fix, then format.

Hmm. Did you tried something based on this one or another alternative you listed?
IMO without going further, an eventual fix would be effectively complex.
I'll give it some tries (based on what you said) today.

**Comment by ro0NL** [comment] 2016-06-25 08:10
From a formatting pov it does work, ie it could work for `block`

`$io->writeln('<fg=black;bg=green>foo <comment>bar</comment> baz</>');`
![image](https://cloud.githubusercontent.com/assets/1047696/16355619/d0ef291e-3abc-11e6-91e1-30fd5fbedee2.png)

**Comment by ro0NL** [comment] 2016-06-25 08:45
Also the formatting logic is tight to a concrete formatter, ie we cannot fix this without changing its api. Ie. it needs to be fixed via `format($message, $wrap = null)`.

**Comment by chalasr** [comment] 2016-06-25 09:22
We effectively have some work to do for nested tags in `block()`...
Tags need to be parsed, striped and properly re-added before/while cutting lines to the correct width.

Actually if I comment out the [escaping line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Style/SymfonyStyle.php#L83), calling this:

```php
$io->block('Lorem <comment> ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</comment>', null, 'fg=black;bg=green');
```

Leads to

> Fatal error: Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: Incorrectly nested style tag found. in /Volumes/HD/component-alone/Console/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php:87

IMHO the problem is too specific to `block()` for doing something on the formatter side.
I would go more for moving the line-cutting logic from `block()` to a separate utility method then calling this method in `comment()`, rather than using `block()` directly. 
It would help to fix the first problem pointed here (nested tag covering multiple lines of ), letting `block()` escaping messages as it actually does.

**Comment by ro0NL** [comment] 2016-06-25 09:42
My main concern is we create a performance killer when doing it in multiple steps. For instance `Helper::strlenWithoutDecoration` is already overkill.

I still think it belongs on the formatter and/or formatter-style side, from a OO pov. Including `strlenWithoutDecoration` also belongs their (`$formatter->strlen()`).

**Comment by chalasr** [comment] 2016-06-25 09:50
Actually, commenting out the [escaping line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Style/SymfonyStyle.php#L83) and calling this:

```php
$io->block('Lorem <comment> ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</comment>', null, 'fg=black;bg=green');
```

Leads to

> Fatal error: Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: Incorrectly nested style tag found. in /Volumes/HD/component-alone/Console/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php:87

IMHO the problem is too specific to `block()` for doing something on the formatter side.
I would go more for moving the line-cutting logic from `block()` to a separate utility method then call this method from `comment()` and `block()`, rather than using `block()` directly from `comment()`. 
It would help for fixing the first problem pointed here (nested tag covering multiple lines in `comment()`), letting `block()` escaping messages as it actually does.

Output formatting becomes a real headache here.
Personally I wouldn't be happy to get this kind of output when using `block()`:
![](http://image.prntscr.com/image/d29f7382850a452fb8fd3eba24f43c5e.png)

IMHO the SymfonyStyle should primary stay a set of utility methods providing an easy way to have formatted blocks based on a fixed style.
The problem that stays here is that calling `block()` from `comment()` is not compatible because nested tags should be allowed in `comment()` and not in `block()` (IMHO again).

Let's wait for the opinion of maintainers.

**Comment by ro0NL** [comment] 2016-06-25 10:00
:+1: I understand your pov. I guess i just dont like the `OutputFormatterInterface` with tight coupling everywhere (i.e. also `OutputFormatter::escape` is problematic).

**Closed** 2016-06-29 05:04 UTC
Labels: Bug, Console, Status: Needs Review
