### ISSUE TITLE
[RFC] Use HTTPS for www.w3.org/2001/xml.xsd resource

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#29716] opened 2018-12-28 16:11 UTC
**Symfony version(s) affected**: 3.4.18

**Description**
`lint:xliff` command fails because http://www.w3.org/2001/xml.xsd is not currently available

```
In XliffLintCommand.php line 114:
                                                                               
  Warning: DOMDocument::schemaValidate(http://www.w3.org/2001/xml.xsd): faile  
  d to open stream: Connection timed out                                       
```                                                              

**How to reproduce**  
Execute `lint:xliff` with some xliff resource.

**Possible Solution**  
Use secured schema (HTTPS) instead, which currently works well.

**Additional context**
https://www.w3.org/blog/2016/01/w3-org-supporting-https-and-hsts/
```$ curl -I http://www.w3.org/2001/xml.xsd
curl: (7) Failed to connect to www.w3.org port 80: Connection timed out
```
```
$ curl -I https://www.w3.org/2001/xml.xsd
HTTP/2 200 
date: Fri, 28 Dec 2018 15:35:53 GMT
last-modified: Wed, 21 Jan 2009 22:06:40 GMT
vary: Accept-Encoding,upgrade-insecure-requests
cache-control: max-age=7776000
expires: Thu, 28 Mar 2019 15:35:53 GMT
content-type: application/xml
etag: W/"2284-461055ecbfc00-gzip"
accept-ranges: bytes
strict-transport-security: max-age=15552000; includeSubdomains; preload
content-security-policy: upgrade-insecure-requests
```

**Comment by javiereguiluz** [comment] 2019-03-12 08:09
The problem is that w3.org throttles the number of requests you can make to it ... so it's common to get super slow responses or timed out connections. However, this shouldn't be a problem in Symfony. We improved the `lint:xliff` command to use a locally stored XSD file instead of the w3.org one. See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/Util/XliffUtils.php

So, I'm closing this as probably fixed. Reopen if you disagree. Thanks.

**Closed by javiereguiluz** 2019-03-12 08:09 UTC
Labels: Translator
