### ISSUE TITLE
[HttpFoundation] A response without Cache-Control shouldn’t be considered private

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#58466] opened 2024-10-05 13:26 UTC
### Symfony version(s) affected

all

### Description

When investigating https://github.com/symfony/symfony/issues/36858 I noticed my issue was in fact different: I’m using the `CachingHttpClient` to call [the french government’s “API Geo”](https://api.gouv.fr/documentation/api-geo) whose responses include an etag but no cache-control. As such I expected those responses to be cached and revalidated before each request because [the RFC 9111](https://www.rfc-editor.org/rfc/rfc9111.html#name-storing-responses-in-caches) states

> A cache MUST NOT store a response to a request unless […] if the cache is shared: the private response directive is […] not present

But, `ResponseHeaderBag::computeCacheControlValue` will force the response private if it has no cache-control: https://github.com/symfony/symfony/blob/590f6297db4b0dad2ac556fcfd02b37a7994c2d8/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L245-L252

### How to reproduce

Fetch e.g. https://geo.api.gouv.fr/departements/01?fields=nom using the `CachingHttpClient`; its store will stay empty.

### Possible Solution

I’m not sure about the consequences, but my issue would be solved by replacing `no-cache, private` by `no-cache` in the snippet above.

`private, must-revalidate` may need to be updated too? :thinking:

**Comment by eliasfernandez** [comment] 2024-10-06 07:39
I assume you are trying to proxy somehow the response from the API GEO service in a symfony response (probably using the HttpFoundationFactory::createResponse method) and this is why you expect the public cache-control header to  be added but in Symfony you have to declare the `Cache-Control: public` explicitly otherwise it will be private. Take a look to this commit: https://github.com/symfony/symfony/commit/b6923dd7b9e37affac0ad51a4702982fb300e932. Anyhow it should be easy to override the response:
```php
    $response->setCache(array(
        'etag'          => $etag,
        'last_modified' => $date,
        'max_age'       => 10,
        'public'        => true,
    ));
```

If the problem is about the `CachingHttpClient` not taking the `Etag` header. I think Etag logic is not covered on the `CachingHttpClient` class. Alternatively you can use `GuzzleClient` or any other client library. With `GuzzleClient` you could create a middleware (`GuzzleMiddlewareInterface`) to provide the logic you want.

**Comment by MatTheCat** [comment] 2024-10-07 11:27
> I assume you are trying to proxy somehow the response from the API GEO service in a symfony response

This is what HttpCache is doing, not me.

>  you expect the public cache-control header to be added

Nope, I expect the `private` directive not to be added when the response has no `Cache-Control`.

> I think Etag logic is not covered on the `CachingHttpClient` class

It is: https://github.com/symfony/symfony/blob/6864dbe5a6f578cb5b9d9a830fe8bb31b504f55d/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L391-L394

**Comment by stof** [comment] 2024-10-07 13:07
In symfony/http-foundation, we took the decision to be conservative about responses that don't declare whether they are public or private. Making responses private by default means that it reduces the risk of leaking information through the reuse of cached responses by a dev not knowing the way HTTP caches work when cache-control does not define those directives. This provides a secure-by-default cache strategy for Symfony projects.

The root cause of your issue is that the CachingHttpClient is reusing the caching code that is implemented for a reverse-proxy cache around a symfony project instead of using a caching implementation tailored to a client-side (private) cache.
The proper solution for that is to solve https://github.com/symfony/symfony/issues/36858, but nobody has contributed an implementation for that yet.

**Comment by stof** [comment] 2024-10-07 13:09
Duplicate of #49937

**Closed as not planned** 2024-10-07 13:21 UTC
Labels: Bug, HttpFoundation, Status: Needs Review

**Comment by MatTheCat** [comment] 2024-10-07 16:31
Okay, just wanted to make sure there was no issue with `Response`, thanks :ok_hand:
