### ISSUE TITLE
Subrequest Performance with Twig render

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#14752] opened 2015-05-26 02:30 UTC
I am having very poor performance on a page that uses `render(controller(....))` in Twig. If I extract this logic out of the embedded controller, the performance goes way up.  Is there supposed to be a large performance impact when using subrequests like that?

**Comment by phansys** [comment] 2015-05-26 02:53
@stevenmusumeche, you must take into account that subrequests have implicit all the logic which a master request has, so isn't cheap at all boot all the app multiple times. Notice that this performance degradation is even worst in dev mode.
BTW, if you want you could try profiling with blackfire.io

**Comment by ewgRa** [comment] 2015-05-26 11:14
@phansys "all boot all the app multiple times" - are you sure? 

@stevenmusumeche no, there is no big impact on perfomance
You can check Symfony\Bridge\Twig\Extension\HttpKernelExtension::renderFragment function. If you use just render(controller(....)) it will be rendered by InlineFragmentRenderer and there is no kernel loading or something like this, just create subrequest and render it, it is cheap.

**Comment by stof** [comment] 2015-05-26 12:32
@ewgRa the booting only happens once. But all the request lifecycle (kernel.request event with all its associated logic, for instance the routing, then the controller resolving, and then the kernel.response event) happen for subrequests. All this request handling adds overhead compared to just doing the logic in your controller and including a template

**Comment by ewgRa** [comment] 2015-05-26 13:10
@stof agree. But many listeners listen only master requests and skip subrequests. For me it was not a big difference when I measure it, definitely not a bottleneck. Booting take much more time.

@stevenmusumeche check also @stof message, it can be a reason

**Comment by phansys** [comment] 2015-05-26 13:29
@ewgRa, I haven't analysed the internals of ```render(controller())```, I just answered by my own experience with the usage of that construction and my basic knowledge about how it is supposed to work. Time ago (with Symfony 2.4 I think) I had a big performance drawback in one of my projects, which was caused by the usage of this instead ```include```. That is the reason why I recommended @stevenmusumeche to run a profile through blackfire.
Certainly, thank you for the clarification @stof.

**Comment by stevenmusumeche** [comment] 2015-05-26 16:53
I will run it through blackfire.io and report back

**Comment by stevenmusumeche** [comment] 2015-05-26 20:29
This showed that the issue is not in the render command but actually in a service I was using in the rendered Controller.  A call to `getRouteCollection` is very slow (2 seconds).  I use this in the service to determine if a particular route exists and fall back to another one if it doesn't.  Is there a better way to do this that doesn't require calling `getRouteCollection`?

**Comment by ewgRa** [comment] 2015-05-26 21:19
As I understand it:
getRouteCollection usually runtime in memory cached in router (first call can be slow, second call in same execution will be fast). In dev mode first call can be slow due to routes refresh. If you use call getRouteCollection after render(contrller()) it is already called before and must be fast. Did you have this bottle neck in prod env? Did you profile prod env?

>Is there a better way
Check Controller::generateUrl for example. But it is also use getRouteCollection finally and seems can't be better.


Hope this info help you.

**Comment by stevenmusumeche** [comment] 2015-05-26 21:22
Yes, I profiled in production environment with the router cache enabled.  My app (ecommerce site) has many thousands of routes.

**Comment by stevenmusumeche** [comment] 2015-05-26 21:23
You are right, it is only the first call to getRouteCollection that is slow, but I'm assuming since this happens in a subrequest, the previously cached route collection cannot be used?

**Comment by ewgRa** [comment] 2015-05-26 22:28
(thousand+) - can be a problem, never have big routing table, don't know

I dig some code. First call to getRouteCollection in your case seems will be in subrequest, yes. Because for master request Router use matcher, and this matcher is generated (check for example appDevUrlMatcher) and there is no call getRouteCollection for master request.


Maybe loading such big routing table take so much time and there is good place for optimization, make it more lazy, load not all route list, but just needed.

**Comment by jakzal** [comment] 2015-05-27 06:54
Closing as there's no bug after all.

>  Is there a better way to do this that doesn't require calling getRouteCollection?

Perhaps using the router to match a generated route, or the chain router? Ask support questions on the mailing list please :)

**Closed by jakzal** 2015-05-27 06:54 UTC

**Comment by stevenmusumeche** [comment] 2015-05-27 15:20
@jakzal sorry about that, didn't realize it existed
