### ISSUE TITLE
[http-kernel] [feature] Event KernelEvents::CONTROLLER_CALL

### ISSUE THREAD

**Issue by jslsolucoes** [symfony/symfony#23657] opened 2017-07-24 21:56 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

Possibility to create a new http kernel event KernelEvents::CONTROLLER_CALL to act in 

https://github.com/symfony/http-kernel/blob/master/HttpKernel.php#L151 to be replaced for something like this :

```php
$event = new FilterControllerCallEvent($this, $controller, $arguments, ....);
$this->dispatcher->dispatch(KernelEvents::CONTROLLER_CALL, $event);
$response = $event->getResponse();
```

I can help with this feature if need.

**Comment by javiereguiluz** [comment] 2017-07-25 06:51
@jslsolucoes thanks for submitting a proposal por Symfony!

To better know your needs, could you explain what are you trying to accomplish that cannot be done with "controller" and "controller_arguments" events? Thanks!

**Comment by stof** [comment] 2017-07-25 09:17
We have `KernelEvents::CONTROLLER_ARGUMENTS` just before the call of the controller, and `KernelEvents::VIEW` and `KernelEvents::RESPONSE` just after it. I don't see where we would put your new event without making it a duplicate of an existing event.

**Comment by jslsolucoes** [comment] 2017-07-25 19:45
@javiereguiluz . For better explain i`m moving back to php enviroment (many years in java ee enviroment)  and developing an micro enterprise framework thats mirrors some know java especifications api like interceptors . To use http-kernel as core of especification  I need more flexibility to modify the way that kernel calls the resolved controller and arguments adding more block codes before or after executing the method (Not in another event, at the same event ,because write the start of code in one event and then catch the same reference end in another event its not the clean way to do for me). In fact looking at the source code i need more than an event for that, need an interface like ControllerArgumentResolverInterface  called ControllerCallResolverInterface maybe that can be override for a new code . I wrote an implementation thats works like follow : 

`interface ControllerCallResolverInterface   {
    public function getResponse(callable $controller,array $arguments) : ?Response;
}`

`class DefaultControllerCallerResolver implements ControllerCallResolverInterface  {
    public function getResponse(callable $controller,array $arguments) : ?Response {
        return call_user_func($controller,$arguments);
    }
}`

` public function __construct(EventDispatcherInterface $dispatcher, ControllerResolverInterface $resolver, RequestStack $requestStack = null, ArgumentResolverInterface $argumentResolver = null,ControllerCallResolverInterface  $controllerCallerResolver = null)
    {
        $this->dispatcher = $dispatcher;
        $this->resolver = $resolver;
        $this->requestStack = $requestStack ?: new RequestStack();
        $this->controllerCallerResolver = $controllerCallerResolver ?: new DefaultControllerCallerResolver();`

// controller call
        $response = $this->controllerCallerResolver->getResponse($controller, $arguments);
// event here
      ...........

@stof . It`s fair, but calling an controller its an event in framework (it`s in picture framework workflow)  , but does not have an trigger for that event in api. In my opinion events works as unique trigger (forget about another events connected ) that can be done something just before or just after happens (not waiting running a lot of unknow internal code before or after it). I`m not fully sure about event is really needed but its welcome.

**Comment by xabbuh** [comment] 2017-07-26 12:38
I am not sure I understand your issue, but if you just need more than one listener per event, you can register several listeners for the same event and use priorities to control the order in which they are called: http://symfony.com/doc/current/components/event_dispatcher.html#connecting-listeners

**Comment by jslsolucoes** [comment] 2017-07-26 20:29
@xabbuh No its not just about the events itself and listeners , it`s about flexibility in how to call  controller and arguments resolved . Nowadays it's fixed with call_user_func($controller,$arguments);

**Comment by jslsolucoes** [comment] 2017-07-26 20:52
Guys,

Http Kernel is a cool way to do fast , powerful and simple things in http request/response concept, but unfortunately looking more deeply in the architecture of http kernel wont fit to my needs in a lot of points thinking in enterprise applications , some design patterns , some specifications and system architectures and there is no another way to do it without writing my own code ( sad face :( ) 

This feature (if implemented) ,it will be very useful in a lot of cases for future and for the community. 👍

**Comment by robfrawley** [comment] 2017-07-26 22:45
So, you are asking for an `INVOKE_CONTROLLER` event, in conjunction with a new listener (for the core implementation anyway) `InvokeControllerListener` that makes the `call_user_func()` call and allows for others to hook to the event as well for alternate implementations?

**Comment by jslsolucoes** [comment] 2017-07-28 00:58
@robfrawley not so simple like this i have tried this approach before . The complexity is too high handle the handler and make no sense for me (losting previous resolvers). 

Guys let be free to close this issue if make no sense to you my request feature and just to know  im not using anymore http kernel  for my core project since not fit well for my needs.

**Comment by javiereguiluz** [comment] 2017-08-28 10:50
Closing as "won't fix" for the reasons explained above.

**Closed by javiereguiluz** 2017-08-28 10:50 UTC
Labels: Feature, HttpKernel, Status: Waiting feedback
