### ISSUE TITLE
Can't create new project on symfony 5

### ISSUE THREAD

**Issue by evs-xsarus** [symfony/symfony#35523] opened 2020-01-30 14:17 UTC
**Symfony version(s) affected**: 5
**Description**  
Follow the instructions on https://symfony.com/doc/current/setup.html Both the symfony command and composer will do.

**How to reproduce**  
Run `symfony new my_project_name --full`  or `composer create-project symfony/website-skeleton my_project_name`

After composer finished installing, it tries to run the scripts:

```json
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },

```
These fail because no _bin/_ folder with file _console_ exists.

**Possible Solution**  
First install the package symfony/console

**Additional context**  
Terminal output: [symfony5-new-full.txt](https://github.com/symfony/symfony/files/4134333/symfony5-new-full.txt)

**Comment by ro0NL** [comment] 2020-01-30 14:34
The package is installed

```
  - Installing symfony/console (v5.0.3): Loading from cache
```

but it seems the recipe is not configured. Perhaps the version resolution is wrong in Flex: https://github.com/symfony/recipes/tree/master/symfony/console (for 5.0 it should apply the 4.4 recipe still)

**Comment by Nek-** [comment] 2020-01-30 14:49
It works for me!

**Comment by ro0NL** [comment] 2020-01-30 14:53
I got the same issue: `Symfony CLI version v4.12.7`

```
Script cache:clear returned with error code 1
!!  Could not open input file: ./bin/console
```

**Comment by evs-xsarus** [comment] 2020-01-30 15:19
I've started the install with a fresh symfony binary and a fresh composer binary.

**Comment by nicolas-grekas** [comment] 2020-01-30 15:58
I'm unable to reproduce, I tried with PHP 7.2, 7.3 and 7.4. :(

**Comment by s1k3s** [comment] 2020-01-30 16:34
`$ composer create-project symfony/website-skeleton .` also fails with the same error. Running on:
- `PHP 7.3.14-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 23 2020 13:59:16) ( NTS )`
- `Linux Mint 19.3`

bin/console file is missing entirely. If I try to add it manually and do `php bin/console` it says:

> In ParameterBag.php line 98:
!!                                                                                 
!!    The parameter "doctrine_migrations.dir_name" has a dependency on a non-exis  
!!    tent parameter "kernel.root_dir". Did you mean one of these: "kernel.projec  
!!    t_dir", "kernel.cache_dir", "kernel.logs_dir"?

**Comment by fjWebDev** [comment] 2020-01-30 17:06
Same here. Seems to happen only for `symfony/website-skeleton`.

I noticed no recipe is applied for symfony/console:
```
Writing lock file
Generating autoload files
Symfony operations: 18 recipes (c76edd33eca6288add181cf5bd3cc3a5)
  - Configuring symfony/framework-bundle (>=4.4): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (>=5.0): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.2): From github.com/symfony/recipes:master
  - Configuring twig/extra-bundle (>=v3.0.1): From auto-generated recipe
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring easycorp/easy-log-handler (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/monolog-bundle (>=v3.5.0): From auto-generated recipe
  - Configuring symfony/debug-bundle (>=v5.0.3): From auto-generated recipe
  - Configuring doctrine/doctrine-bundle (>=2.0.7): From auto-generated recipe
  - Configuring doctrine/doctrine-migrations-bundle (>=2.1.2): From auto-generated recipe
  - Configuring sensio/framework-extra-bundle (>=5.2): From github.com/symfony/recipes:master
  - Configuring symfony/mailer (>=4.3): From github.com/symfony/recipes:master
  - Configuring symfony/notifier (>=5.0): From github.com/symfony/recipes:master
  - Configuring symfony/security-bundle (>=4.4): From github.com/symfony/recipes:master
  - Configuring symfony/translation (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/validator (>=4.3): From github.com/symfony/recipes:master
  - Configuring symfony/maker-bundle (>=1.0): From github.com/symfony/recipes:master
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  Could not open input file: ./bin/console
!!
Script @auto-scripts was called via post-update-cmd
```

After the failed installation I tried reinstalling the recipes with:
`composer sync-recipes -v --force`

Then the bin directory is created.

**Comment by nicolas-grekas** [comment] 2020-01-30 17:11
Apparently I'm able to reproduce now, I'll have a look tomorrow!

**Comment by scaule** [comment] 2020-01-30 17:28
You can use this Dockerfile ( https://github.com/scaule/Symfony-install-demo/blob/master/Dockerfile ) to reproduce this error by building it.

**Comment by abdounikarim** [comment] 2020-01-31 09:35
Hello @nicolas-grekas, i got the same problem with the `v4.12.7` symfony CLI version.

**Comment by jeanMarcelMichelet** [comment] 2020-01-31 13:34
` composer sync-recipes -v --force` works for me

**Comment by fabpot** [comment] 2020-01-31 16:58
Should be fixed by https://github.com/symfony/recipes/pull/732

**Closed by fabpot** 2020-01-31 16:58 UTC
