### ISSUE TITLE
Symfony4 - Error: “Notice: Undefined index: dbname” in AbstractOracleDriver.php while trying to create database

### ISSUE THREAD

**Issue by jkamler** [symfony/symfony#25935] opened 2018-01-26 10:17 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

I am using Symfony 4.0.3 and I need connect to Oracle DB. I follow this instructions:

https://symfony.com/doc/current/doctrine.html

my .env file contains this

`DATABASE_URL=oci8://user:pwd@xxx.xxx.xxx.xxx:1521/something`
host address is from tnsnames.ora -> HOST, something is from tnsnames.ora -> SERVICE_NAME

And after running command:

`php bin/console doctrine:database:create`
I get this error:

```
C:\Apache24\htdocs\myapp>
2018-01-25T12:58:47+00:00 [error] Error thrown while running command 
"doctrine:database:create". Message: "Notice: Undefined index: dbname"

In AbstractOracleDriver.php line 125:

  Notice: Undefined index: dbname
```

I am able to connect to DB by plain PHP, but through Symfony not. dbname is something from my connect url at .env file. This is set from tnsnames.ora.

After this I tryed modify doctrine.yaml like this:

```
parameters:
# Adds a fallback DATABASE_URL if the env var is not set.
# This allows you to run cache:warmup even if your
# environment variables are not available yet.
# You should not need to change this value.
#env(DATABASE_URL): ''

doctrine:
    dbal:
      default_connection:   default
      connections:
        default:
          driver:    'oci8' # ... or 'pdo_oci'
          dbname:    'dbname'
          host:      'xxx.xxx.xxx.xxx'
          port:      '1521'
          user:      'user'
          password:  'pwd'

# With Symfony 3.3, remove the `resolve:` prefix
#         url: '%env(resolve:DATABASE_URL)%' 
orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
        App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
```
after command `php bin/console doctrine:database:create`

I have same error.

My dbname is same as I have in SQL Developer in SID item.

**Comment by xabbuh** [comment] 2018-01-26 13:28
I can reproduce your issue. The issue is that the command class drops the database name from the params before passing it to the DBAL. I don't know if this needs to be fixed in the command or in the DBAL Oracle driver. But both classes are not part of the Symfony core. Thus I need to close here as there is nothing we can do about it.

**Closed by xabbuh** 2018-01-26 13:28 UTC
Labels: Bug, Doctrine, Status: Needs Review
