### ISSUE TITLE
KernelTestCase no longer works with PhpUnit 6.0+

### ISSUE THREAD

**Issue by advancingu** [symfony/symfony#21534] opened 2017-02-04 21:26 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

Preconditions:
* Have a blank Symfony project version 3.2.x as installed by Symfony project generator.
* Install PhpUnit 6.0.x with composer using `composer require --dev phpunit/phpunit=~6.0`.

Steps to reproduce:
1. Run PhpUnit 6 with `vendor/bin/phpunit -c .`

Actual result:
```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/user/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php on line 23
```

Expected result:
```
PHPUnit 6.0.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 107 ms, Memory: 12.00MB

OK (1 test, 2 assertions)
```

Notes:
* It appears the old class name `PHPUnit_Framework_TestCase` which is used as a parent class of `vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php` was completely dropped in favor of PSR compatible namespacing in PhpUnit 6 (see this [commit](https://github.com/sebastianbergmann/phpunit/commit/ba2241e6e0a634dc333b6e1d2fd6d0e8c16c2f57)).
* The new namespaced class name was introduced in PhpUnit ~4.8~ 5.4 (see [changelog](https://github.com/sebastianbergmann/phpunit/blob/aa47f767c5ecadab9df0862c34398e4ee582bb56/ChangeLog-5.4.md#added)).
* Would it be possible to replace the parent class of `KernelTestCase` with the new namespaced class?

**Comment by robfrawley** [comment] 2017-02-04 22:20
The new namespace wasn't added until phpunit **5.4**, not 4.8, as you asserted (check the [changelog link you referenced](https://github.com/sebastianbergmann/phpunit/blob/aa47f767c5ecadab9df0862c34398e4ee582bb56/ChangeLog-5.4.md#added)). Since Symfony still supports PHP 5.5, and this requires phpunit version 4, this can't likely be fixed in this manner.

**Comment by advancingu** [comment] 2017-02-04 22:23
You're right, I got the version numbers mixed up.

**Comment by srvrguy** [comment] 2017-02-05 04:50
I'm not sure if this should be a new issue, but the issue also occurs with Symfony 2.8.

**Comment by advancingu** [comment] 2017-02-05 11:52
I closed the PR since it won't be possible to merge it.
As pointed out in the PR, another workaround would be to implement a polyfill with the following class:
```php
class PHPUnit_Framework_TestCase extends \PHPUnit\Framework\TestCase
{
}
```

**Comment by curry684** [comment] 2017-02-05 23:16
The polyfill seems the way to go for now, but methinks it should go in the PHPUnit bridge, not in the general polyfill packages as it's only an issue for Symfony's own KernelTestCase and WebTestCase base classes.

Given the issues that it's causing (full crash on every single testcase) my recommendation would be to add a `conflicts: "phpunit/phpunit":">=7` rule to the `composer.json` to at least reverse the situation the next time that it's impossible to upgrade PHPUnit at the Composer level until Symfony is compatible and the user has upgraded Symfony itself to a (verified to be) compatible version.

**Comment by curry684** [comment] 2017-02-05 23:29
Come to think of it, that polyfill would horribly break many projects. A regular polyfill adds *missing* functionality without breaking anything, but in this case many projects might consciously stay on 5.x for some time and thus would explicitly break on the suggested solution, or get stuck with an old Symfony version.

I think the only really transparent solution is changing [`KernelTestCase.php`](https://github.com/symfony/framework-bundle/blob/master/Test/KernelTestCase.php) to something like this:
```
namespace Symfony\Bundle\FrameworkBundle\Test;

use Symfony\Component\DependencyInjection\ResettableContainerInterface;
use Symfony\Component\Finder\Finder;
use Symfony\Component\HttpKernel\KernelInterface;

// Alias the PHPUnit 6.0 ancestor if available, else fall back to legacy ancestor
if (class_exists("\PHPUnit\Framework\TestCase", true)) {
  class KernelTestCaseAncestor extends \PHPUnit\Framework\TestCase {}
} else {
  class KernelTestCaseAncestor extends \PHPUnit_Framework_TestCase {}
}

/**
 * KernelTestCase is the base class for tests needing a Kernel.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
abstract class KernelTestCase extends KernelTestCaseAncestor
```

**Comment by robfrawley** [comment] 2017-02-06 00:09
@curry684 Really, all you need to do is polyfill the `PHPUnit_Framework_TestCase` when it doesn't exist and `\PHPUnit\Framework\TestCase` does. Such code shouldn't nessissarily go in the actual class file, but instead in the `symfony-polyfill` component (it looks like the phpunit bridge doesn't have anything to do with polyfilling).

Something like the following could be added to the `stub` section of the `symfony-polyfill` component's `composer.json`:

```php
<?php

if (!class_exists('\PHPUnit_Framework_TestCase') && class_exists('\PHPUnit\Framework\TestCase')) {
  class_alias('\PHPUnit\Framework\TestCase', '\PHPUnit_Framework_TestCase');
}
```

**Comment by curry684** [comment] 2017-02-06 00:17
@robfrawley if you do it in the polyfill it is aliased for *every* test case in a project using the polyfill, not just those using `KernelTestCase`. This would inadvertently make tons of people not notice at all that they didn't apply any of the required modifications to cleanly upgrade their separate unit tests to become PHPUnit 6.0 compatible.

Global polyfilling is in this case a carpet bomb approach while we're only trying to patch `KernelTestCase`.

**Comment by robfrawley** [comment] 2017-02-06 00:23
Solid point. Not positive what the best route is to proceed...

**Comment by sebastianbergmann** [comment] 2017-02-06 04:59
Re: https://github.com/symfony/symfony/issues/21534#issuecomment-277561669

I made the conscious decision to not provide aliases as they only delay the problem. It is your right, of course, to make the conscious decision to add aliases in your project.

**Comment by sebastianbergmann** [comment] 2017-02-06 05:24
Looking at your `composer.json` I see that Symfony 3 needs to run its test suite with PHP 5.5. This limits you to PHPUnit 4.8 (which is no longer supported).

I have just released [PHPUnit 4.8.35](https://github.com/sebastianbergmann/phpunit/blob/4.8/ChangeLog-4.8.md#4835---2017-02-06) to which I have [backported](https://github.com/sebastianbergmann/phpunit/commit/a55235c033c2dc18db631cc6b804844f6d37615a) the forward compatibility layer for PHPUnit 6 from PHPUnit 5 so that `PHPUnit\Framework\TestCase` can be used instead of `PHPUnit_Framework_TestCase`.

**Comment by advancingu** [comment] 2017-02-06 08:26
I opened a new PR since the new namespaces now exists in PHPUnit 4.8.

**Comment by curry684** [comment] 2017-02-06 08:55
That PR isn't enough as you then still need the proper `conflict` headers in composer.json so block `phpunit/phpunit:<4.8.35`.

All in all I would recommend not making PRs until a clear path on this is chosen by the powers that be - it's not a trivial minor issue so at least @nicolas-grekas should have a say in this as he likely has the best insight in impact.

**Comment by stof** [comment] 2017-02-06 09:09
@curry684 creating a class alias with the PHPUnit class name has *already* been rejected, for the reason given by you above (it would also break feature detection for code checking the availability of the class btw).

As the forward compatibility layer is now available in 4.8 and 5.4+, we can switch to it IMO

**Comment by xabbuh** [comment] 2017-02-06 09:10
Well, making sure that the PhpUnitBridge doesn't use the cache, but reinstalls PHPUnit instead will probably make the tests green.

**Comment by Jean85** [comment] 2017-02-06 10:04
I was already trying to tackle this problem for the bridge here: #21221
Unfortunately, for the bridge the compat issue is more extensive...

**Comment by pculka** [comment] 2017-02-08 08:40
ok, so what is the solution to this? I'm using symfony 3.2 for a new project, PHPUnit 6.0.8 and the tests won't even start, i.e. my CI fails every build, which won't let me deploy...

**Comment by xabbuh** [comment] 2017-02-08 08:50
@pculka For the moment, you can stick with PHPUnit 5.x.

**Comment by pculka** [comment] 2017-02-08 08:54
@xabbuh that's what I did. The workaround above by @curry684 works, so long you don't use for example LIIP functional test bundle (which I do). I fixed my composer.json (had phpunit using `@stable` ) and now tests work.

**Comment by curry684** [comment] 2017-02-08 09:38
On my current project I've put the following in my PHPUnit bootstrap file after the autoloader until it's resolved on the Symfony and/or PHPUnit levels, with `"phpunit/phpunit:"^5.7 || ^6.0"` in the composer.json so I can also test with `--prefer-lowest`:
```
// Polyfill PHPUnit 6.0 both ways
if (!class_exists('\PHPUnit\Framework\TestCase', true)) {
    class_alias('\PHPUnit_Framework_TestCase', '\PHPUnit\Framework\TestCase');
} elseif (!class_exists('\PHPUnit_Framework_TestCase', true)) {
    class_alias('\PHPUnit\Framework\TestCase', '\PHPUnit_Framework_TestCase');
}
```
I'm only using this because I want the bundle to support only PHPUnit 6 eventually. In regular projects I'm sticking with 5.x for the time being as @xabbuh suggests.

**Comment by Toilal** [comment] 2017-02-14 14:37
There are other polyfills required, like those ...

```
class PHPUnit_Util_ErrorHandler extends \PHPUnit\Util\ErrorHandler ...
class PHPUnit_Util_Test extends \PHPUnit\Util\Test
```

**Comment by curry684** [comment] 2017-02-14 17:20
Not for Symfony as the conflict only arises from KernelTestCase extending PHPUnit_Framework_TestCase.

**Comment by Jean85** [comment] 2017-02-14 17:28
Those are needed for the PHPUnit bridge, in fact

**Comment by scaytrase** [comment] 2017-02-17 06:43
I think the actual problem, was that Symfony (2.7 lowest ATM) provides documented way to use own [Test Cases](https://symfony.com/doc/current/testing.html#your-first-functional-test) which extends `phpunit` ones, but does not actually declare a real dependency on it.

The #21564 is a temporary fixm which would work for some more years. But what happens when phpunit7 comes? phpunit8? would we patch a BC layer for each of them each time?

Declaring a dependency (at least a fixed one, like ^4.8.35 || ^5.4 || ^6.0 ) should help to make supporting future versions of dependency to be a feature, not a bug 🐛

**Comment by peterrehm** [comment] 2017-02-17 07:13
@scaytrase #21564 is not a temporary fix it is the start of making it fully compatible. There is no additional BC layer, we use the FC layer instead. The issue is that we still have to support PHP 5.3 and therefore need a test setup which works with PHPUnit 4+.

**Comment by scaytrase** [comment] 2017-02-17 07:21
So we will ensure, that FC layer will apear **before** official release of the next BC-breaking version of dependencies? Declaring a depdendency allows us to prohibit updating the dependency **until** the FC layer will come. Otherwise we should always think in advance for any undeclared depdendency

**Comment by xabbuh** [comment] 2017-02-17 08:01
@scaytrase We cannot add a dependency as using the test case classes from Symfony is total optional. Someone not using PHPUnit at all wouldn't want to get it installed. The same applies to globally installed PHPUnit instances (and for those even adding a conflict rule would not help).

**Comment by scaytrase** [comment] 2017-02-17 08:22
Ok, `conflict` section is an option then. But, I think we should add a conflict with `>=7.0` also there, yes? To be ensured people **do not use** modern phpunit until we ensure symfony is compatible?

**Comment by xabbuh** [comment] 2017-02-17 08:25
Even if PHPUnit 7 were out and our base test case classes were not compatible with PHPUnit 7 yet, users would still be able to use it if they did not make use of our base classes.

**Comment by peterrehm** [comment] 2017-02-17 08:25
Technically it is not sure yet and since PHPUnit is optionally tooling it should updated once the changes in 7.0 are clear. There are good chances that there might not be any issues. You will in any case immediately notice if there are issues with your testsuite.

**Closed** 2017-02-18 16:04 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review, Unconfirmed

**Comment by ChangePlaces** [comment] 2017-03-11 13:53
This also occurs with Silex 2

**Comment by xabbuh** [comment] 2017-03-11 15:06
@ChangePlaces see silexphp/Silex#1483

**Comment by RafaelPlantard** [comment] 2017-03-16 01:45
I'm facing: `PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in /home/travis/build/ShopBackBR/php-apns/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1066` issue at PHP 5.6 at Travis CI.

**Comment by rernesto** [comment] 2017-03-21 08:24
I tried with PHPUnit 5.7/Symfony 2.8 and PhpUnit 6.x/Symfony 3.x. I got the Class Not Found Error. I only have this error on Functional Tests extending Symfony\Bundle\FrameworkBundle\Test\WebTestCase

**Comment by xabbuh** [comment] 2017-03-21 08:26
Can you please show the output of `composer show`?

**Comment by rernesto** [comment] 2017-03-21 08:30
```
"require": {
        "php": ">=5.3.9",
        "doctrine/doctrine-bundle": "~1.4",
        "doctrine/orm": "^2.4.8",
        "friendsofsymfony/rest-bundle": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "javiereguiluz/easyadmin-bundle": "^1.16",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/assetic-bundle": "~2.3",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/swiftmailer-bundle": "~2.3,>=2.3.10",
        "symfony/symfony": "2.8.*",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.0",
        "sensio/generator-bundle": "~3.0"
    },
```

**Comment by peterrehm** [comment] 2017-03-21 08:33
You need dev-master of the bridge.

**Comment by rernesto** [comment] 2017-03-21 08:42
I don't know why I should require dev-master version of the bridge (I am not using it), but I did it. Isn't working, same Class not found Error. I tried with PhpUnit 5.x and 6.x on both versions of symfony (2.8 and 3.2)

**Comment by peterrehm** [comment] 2017-03-21 08:44
If you want PHPUnit 6.0 you need the dev-master version of the bridge as only the master version supports PHPUnit 6.0.

**Comment by xabbuh** [comment] 2017-03-21 08:44
How do you run the tests? What is the exact error you get?

**Comment by rernesto** [comment] 2017-03-21 08:45
Class 'Symfony\Bundle\FrameworkBundle\Test\WebTestCase' not found in /var/www/scheduler/src/Fluency/Bundle/SchedulerBundle/Tests/Controller/DefaultControllerTest.php on line 7

**Comment by xabbuh** [comment] 2017-03-21 08:53
This does not answer my question how you run your tests. Please explain how you did that before the tests started to fail and how your config was at that time. Did you then get the same error? Please note that the initial issue was about the `\PHPUnit_Framework_TestCase` class not being found while your last error is about Symfony's `WebTestCase` class.

**Comment by rernesto** [comment] 2017-03-21 09:14
I re-start everything from scratch, now is working. I think the problem was with the PhpUnit versions. Thanks for your time.

**Comment by RafaelPlantard** [comment] 2017-03-21 10:08
I started to use only the composer version. I was using composer + system version, and when they were different I was facing issues. So I'm now just using composer versions.
My `composer.json`:
```
{
    "name": "jwage/php-apns",
    "type": "library",
    "description": "Object Oriented PHP Apple Push Notification Integration Library",
    "keywords": ["apple", "notifications", "apns"],
    "homepage": "http://github.com/jwage/php-apns",
    "license": "MIT",
    "authors": [
        {"name": "Jonathan H. Wage", "email": "jonwage@gmail.com"}
    ],
    "autoload": {
        "psr-0": {"JWage\\APNS": "src/"}
    },
    "require": {
        "php": ">=5.3.0",
        "ext-openssl": "*",
        "ext-zip": "*",
        "phpunit/phpunit": "*"
    }
}
```

My phpunit run command: `vendor/bin/phpunit`, I'm using this command at `Travis CI`:

```
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script: composer install

script: vendor/bin/phpunit

notifications:
  email: false
```

**Comment by sinasalek** [comment] 2017-04-22 13:03
There is also another workaround using composer directly. there is a plugin for class aliasing. This way there no need to change anything else 
https://github.com/TYPO3/class-alias-loader

**Comment by blacksonic** [comment] 2017-10-27 08:04
Will be there a fix for this? I consider the aliasing as a monkey patch, not a real fix.

**Comment by xabbuh** [comment] 2017-10-27 08:17
There shouldn't be any issue if you are using a recent version of the PhpUnitBridge or PHPUnit itself.

**Comment by blacksonic** [comment] 2017-10-27 11:50
Using it with PHPUnit itself results in error. I don't know if this bridge works with Silex.

**Comment by curry684** [comment] 2017-10-27 12:05
But this is the Symfony issue tracker, not Silex'.

**Comment by xabbuh** [comment] 2017-10-27 13:21
@blacksonic Which PHPUnit version and which error?
