### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by SMartignier** [symfony/symfony#20303] opened 2016-10-26 07:31 UTC
Hi all,

I've got some problems with the intl component.

I have a form where the user can pick a date and a time, but when the time is "cast" in the controller, the hours is two hours back. For example if i pick 10:10 in the form i will have 08:10 in my controller.

Please take a look at my post (it's french but the important think are the code and the profiler view)
https://openclassrooms.com/forum/sujet/probleme-date-timezone?page=1#message-91356928

Setting Europe/Zurich in the php.ini doesn't resolve the bug (and the default timezone is set to Europe/Zurich as we can see).

Removing the intl component fix the bug, so i think i'm missing some configuration at one moment

Thanks in advance for your help :)

**Comment by alsar** [comment] 2016-10-26 08:18
I encountered the same problem 2 days ago. It worked with v3.0.9 but after the update to v3.1.4 the problem occurred.

**Comment by SMartignier** [comment] 2016-10-26 08:22
So do you downgrad to 3.0.9 and it was working again?

**Comment by alsar** [comment] 2016-10-26 08:39
Yes. Downgraded to 3.0.9 and it works again.

**Comment by SMartignier** [comment] 2016-10-26 10:06
I try it, and effectively it's solve the problem. But still, it's strange, do we have something special to configure in the new version?

**Comment by jzawadzki** [comment] 2016-11-04 19:28
Possible duplicate of #19721 (bug introduced in 3.1.4, fixed in 3.1.5)

**Comment by alsar** [comment] 2016-11-05 08:20
The bug was fixed in 3.1.6. The issue can be closed.

**Comment by javiereguiluz** [comment] 2016-11-05 08:22
@alsar thanks! Closing it as fixed then,

**Closed by javiereguiluz** 2016-11-05 08:22 UTC
