### ISSUE TITLE
Form with radio buttons fails after Symfony 2.7 upgrade

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#14877] opened 2015-06-05 12:44 UTC
Imagine this form:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
        $builder->add('transportType', 'entity',
            array(
                'class' => 'MyBundle:TransportType',
                'property' => 'language.name',
                'expanded' => true,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('e')
                        ->join('e.language', 'l')
                        ->orderBy('l.name', 'DESC');
                },
            )
        );
}

public function setDefaultOptions(OptionsResolverInterface $resolver)
{
        $resolver->setDefaults(array(
            'data_class' => 'BLA\MyBundle\Form\Model\Shipping',
        ));
}
```

After upgrading to Symfony 2.7, the form throws the following exception:

```
An exception has been thrown during the rendering of a template ("The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies\__CG__\BLA\MyBundle\Entity\TransportType. You can avoid this error by setting the "data_class" option to "Proxies\__CG__\BLA\MyBundle\Entity\TransportType" or by adding a view transformer that transforms an instance of class Proxies\__CG__\BLA\MyBundle\Entity\TransportType to scalar, array or an instance of \ArrayAccess.") in MyBundle:Shipping:form.html.twig at line 8.
```

Setting the `data_class` seems to work but I wonder why this has not been documented in the upgrade file?

**Comment by webmozart** [comment] 2015-06-11 16:34
Hi @XWB, thank you for reporting this issue! I'm not sure I understand your problem correctly. Could you please upload a fork of symfony-standard that reproduces your problem?

**Comment by isabellebruchet** [comment] 2015-07-06 13:50
Hi,
Same problem here. It's seems to be like that : when you have an entity type with the option "expanded" to true, after upgrading to 2.7 you have an exception (the same as in the previous message). Adding the data_class option fix the problem, but this option is not required when you look in the documentation.

**Comment by XWB** [comment] 2015-07-06 13:53
@isabellebruchet Fully correct
@webmozart Private project, I cannot uploaded a fork

**Comment by jakzal** [comment] 2015-07-06 14:25
@XWB we don't need your private project. What we need is your problem reproduced on a fresh Standard Edition project. While preparing it you'll be able to roll out problems specific to your project or configuration, and might be you'll even find the cause of the problem. Surely, it'll be much easier for us to debug the issue.

**Comment by Rvanlaak** [comment] 2015-07-07 15:06
Since we've updated to `2.7.1` the `EntityType` with `expanded: true` does not accept an entity as a default value anymore. A `LogicException` occurs when the user goes back to edit the entity, where `defaultData` is added to the builder:

> The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies\__CG__\AppBundle\Entity\Order\Subject. You can avoid this error by setting the "data_class" option to "Proxies\__CG__\AppBundle\Entity\Order\Subject" or by adding a view transformer that transforms an instance of class Proxies\__CG__\AppBundle\Entity\Order\Subject to scalar, array or an instance of \ArrayAccess.

```php
$defaultData = array();
if ($order->getSubject() instanceof Subject) {
	$defaultData['subject'] = $order->getSubject();
}
    	
$form = $this->createFormBuilder($defaultData)
    ->add('subject', 'entity', array(
       	'class' 	 => 'AppBundle:Order\Subject',
        'expanded'	 => true,
        'property'   => 'name',
    ))
    ->getForm()
;
```

The exception can be solved in two ways, by setting `expanded` to `false` or by defining `data_class`:

```php

// ...
    	
$form = $this->createFormBuilder($defaultData)
    ->add('subject', 'entity', array(
       	'class' 	 => 'AppBundle:Order\Subject',
       	'data_class' => 'AppBundle\Entity\Order\Subject',
        'expanded'	 => true,
        'property'   => 'name',
    ))
    ->getForm()
;
```
Looks like a BC break, think `EntityType` should resolve the `data_class` based on the `class` right?

**Comment by pascallapointe** [comment] 2015-07-13 14:26
You can install the 2.7 branch of my symfony-standard fork:
https://github.com/pascallapointe/symfony-standard.git

Once it's done, add manually some companies and create some employees.

The exception will occur in the 'edit' view once you have linked an employee with a company.
Unlinked entities will not throw any exception.

Hope it will help, thank you in advance for taking a look at it!

**Comment by jakzal** [comment] 2015-07-14 06:55
@pascallapointe thanks for your work. I confirmed your fork reprodues the issue.

**Comment by superdav42** [comment] 2015-07-31 05:26
I looked into this a little and found the $viewData set on [before the exception](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L353)
is an int when the `expanded` option is not used but is an object when it is used. I believe this bug was introduced in [ Refactored choice lists commit](https://github.com/symfony/symfony/commit/03efce1b568379eac21d880e427090e43035f505) 
It's a little over my head by probably it should return consistent view data regardless if the 'expanded' option is used. However simply commenting out the LogicExeption allows the code to run with no problems so it's hard to say what the real problem is. 

I have had success using this workaround to avoid adding data_class everywhere in my code:
```php
// src/Acme/DemoBundle/Form/Type
namespace Acme\DemoBundle\Form\Type;

use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class AcmeEntityType extends EntityType
{
    public function configureOptions(OptionsResolver $resolver) 
    {
        parent::configureOptions($resolver);
        
        if(Kernel::MAJOR_VERSION == '2' &&
           Kernel::MINOR_VERSION == '7'  &&
           (int) Kernel::RELEASE_VERSION <= 2) {

            $dataClassNormalizer = function (Options $options, $dataClass) {
                if($dataClass || $options['multiple'] || !$options['expanded']) {
                    return $dataClass;
                }
                return $options['em']->getClassMetadata($options['class'])->getName();
            };

            $resolver->setNormalizer('data_class', $dataClassNormalizer);
        }
    }
}
```
and add a service definition like:
```yml
# src/Acme/DemoBundle/Resources/config/services.yml
    form.type.entity: 
        class: Phoenix\CmsBundle\Form\Type\PheonixEntityType
        tags: [{ name: form.type, alias: entity}]
        arguments: [@doctrine]
``` 

This workaround is a rather ugly hack and assumes this well be fixed in 2.7.3.

**Comment by adsc** [comment] 2015-08-11 16:05
Can confirm this issue, setting "expanded" to false removes the error, but is not a solution when you need expanded rendering. The workaround with data_class only helps for fields with multiple = false, otherwise you get the error:

The form's view data is expected to be an instance of class Blabla, but is a(n) array. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) array to an instance of Blabla

**Comment by sustmi** [comment] 2015-08-31 20:51
Here is a test for the original @XWB's issue: https://github.com/sustmi/symfony/commit/57b297e91bd3b6c5e6ffa923233574b359c3aafc .
Prior to commit https://github.com/symfony/symfony/commit/03efce1b568379eac21d880e427090e43035f505 ChoiceType used [ChoicesToBooleanArrayTransformer](https://github.com/symfony/symfony/blob/v2.7.3/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoicesToBooleanArrayTransformer.php) view transformer to transform modelData to `string`.
Since v2.7.0, I guess [RadioListMapper](https://github.com/symfony/symfony/blob/v2.7.3/src/Symfony/Component/Form/Extension/Core/DataMapper/RadioListMapper.php) is supposed to replace the `ChoicesToBooleanArrayTransformer`. 
The problem is that without the transformer, viewData is filled with an object instead of string. [Form::setData()](https://github.com/symfony/symfony/blob/v2.7.3/src/Symfony/Component/Form/Form.php#L361) then throws `LogicException` because it expects:
> scalar, array or an instance of \ArrayAccess

as viewData.

**Comment by sustmi** [comment] 2015-08-31 21:05
I can confirm, that you can workaround this issue by setting the `data_class` to the appropriate class name.

**Comment by XWB** [comment] 2015-09-02 10:59
Thanks for the test @sustmi 

Ping @webmozart

**Comment by stof** [comment] 2015-09-02 11:03
but in 2.6, it was possible to have mixed choices (strings and objects), which is not possible anymore because of this data mapper usage.

**Comment by XWB** [comment] 2015-11-10 11:28
Any updates on this issue? @webmozart

**Comment by dmaicher** [comment] 2015-11-23 22:36
Also ran into this issue today after upgrading from 2.6 to 2.7.

Any news? :)

**Comment by Einenlum** [comment] 2015-11-24 10:26
Same, any news?

**Comment by webmozart** [comment] 2015-11-26 08:03
As far as I understand, the real issue here are that `data_class` isn't set to `class` for the entity type. But @stof mentioned an even bigger issues: Choice fields cannot contain mixed objects and scalars anymore.

IMO, the possible good solutions are:

1. to add a way to specify `data_class` such that a field can either have that class or a scalar/array
2. to disable validation of the view data against `data_class` altogether

**Comment by webmozart** [comment] 2015-11-26 09:15
Fixed in https://github.com/symfony/symfony/pull/16679.

**Comment by XWB** [comment] 2015-11-26 09:28
:+1:

**Comment by rvanlaak** [comment] 2015-11-26 09:49
Will it solve setting an entity as default data when `expanded` is set to `true`? See https://github.com/symfony/symfony/issues/14877#issuecomment-119232933

**Comment by webmozart** [comment] 2015-11-26 11:02
@rvanlaak yes, it should

**Comment by rvanlaak** [comment] 2015-11-26 13:43
:+1:

**Closed** 2015-11-26 17:18 UTC
Labels: Bug, Form

**Comment by adampastusiak** [comment] 2016-02-09 10:49
This issue is closed, but I don't know if it really should be because problem @adsc mentioned still exists.
I'm on Symfony 2.7.9 and I have form like this:
```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form', ['propertyIds' => $properties])
            ->add('entities', 'entity', [
                'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                'choice_label' => 'name',
                'label' => 'Label',
                'multiple' => true,
                'expanded' => true,
                'read_only' => true,
                'query_builder' => function (EntityRepository $repository) use ($ids) {
                    return $repository->createQueryBuilder('e')
                        ->where('e.id IN(:ids)')
                        ->setParameter(':ids', array_values($ids))
                        ->orderBy('e.name', 'ASC');
                }
            ])
            ->getForm();
```
When I try to create view from that form I got 2 exeptions in stack:

> TransformationFailedException: Can not read the choices from the choice list. 

in 
`
vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/CheckboxListMapper.php at line 55 
`
```php
        try {
            $valueMap = array_flip($this->choiceList->getValuesForChoices($choices));
        } catch (\Exception $e) {
            throw new TransformationFailedException(
                'Can not read the choices from the choice list.',
                $e->getCode(),
                $e
```

and 

> ContextErrorException: Warning: spl_object_hash() expects parameter 1 to be object, string given

in
`
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php at line 1243
`
```php
     */
    public function isScheduledForInsert($entity)
    {
        return isset($this->entityInsertions[spl_object_hash($entity)]);
    }
    /**
```

Of course when you'll try to set data_class you got 
>The form's view data is expected to be an instance of class Namespace\SomeBundle\Entity\SomeEntity, but is a(n) array.

exactly like @adsc said.

I didn't found workaround for that yet. This is really pain in the ass when you have widget where user can pick specific entities in form (with checkboxes, not multiple select).

Any ideas @webmozart ?

**Comment by xabbuh** [comment] 2016-02-09 11:55
@adampastusiak Can you create a new issue if you think that we still have a bug here?

**Comment by adampastusiak** [comment] 2016-02-09 12:02
@xabbuh Yes of course, I just did: #17736
