### ISSUE TITLE
[Form] Date field missing from submitted form data when value supplied

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/symfony#28584] opened 2018-09-24 14:47 UTC
**Symfony version(s) affected**: `4.1.2.3` (that's the only version I've checked so far).

#### Description
A date field is missing from the submitted form data when a value is supplied. This behaviour doesn't happen for form types such as `TextType`.

#### How to reproduce

> See [`zanbaldwin/symfony-issue-28584:master`](https://github.com/zanbaldwin/symfony-issue-28584)

1. Create new project from [`symfony/skeleton:v4.1.2.3`](https://github.com/symfony/skeleton/tree/v4.1.2.3).
2. `composer req form`
3. Create [JSON payload listener](https://github.com/zanbaldwin/symfony-issue-28584/blob/master/src/Listener/JsonPayload.php).
4. Create [form type with date field](https://github.com/zanbaldwin/symfony-issue-28584/blob/master/src/Form/Type/TestType.php).
5. Create [controller](https://github.com/zanbaldwin/symfony-issue-28584/blob/master/src/Controller/EntrypointAction.php) (and [route definition](https://github.com/zanbaldwin/symfony-issue-28584/blob/master/config/routes.yaml)).
6. Start local PHP webserver (`php -S 127.0.0.1:8000 -t public`)
6. Send test payloads (I used [HTTPie](https://httpie.org/) via the command: `echo '$DATA' | http --json --print b POST ":8000"`)

#### Example Payloads

| Request Data (`$DATA`)     | Response Data                     |
|----------------------------|-----------------------------------|
| `{"my_date":null}`         | `array(1) { ["my_date"]=> NULL }` |
| `{"my_date":""}`           | `array(0) { }`                    |
| `{"my_date":"2018-01-01"}` | `array(0) { }`                    |

#### Possible Solution

Haven't really dug into this yet, I'll update with anything I find.

**Comment by xabbuh** [comment] 2018-09-24 16:42
The [default widget](https://symfony.com/doc/current/reference/forms/types/date.html#widget) for a `DateType` is `choice` which means that the field will be rendered with three `select` elements in an HTML document. This also means that you need to submit three values instead of a single string:

```json
{
    "my_date": {
        "day": "1",
        "month": "1",
        "year": "2018"
    }
}
```

Alternatively, you should also be able to set the `widget` to `single_text` and configure the expected date format using the [format option](https://symfony.com/doc/current/reference/forms/types/date.html#format).

**Comment by zanbaldwin** [comment] 2018-09-24 16:53
Yes, setting `['widget' => 'single_text']` does fix the third example - I can't believe I missed that (I even used that option today).

I don't understand why the field is removed from the data instead of causing a form error though :thinking:

**Comment by xabbuh** [comment] 2018-09-24 17:00
The last two examples end with the exception in your controller, don't they? That's because the view transformer of the date type will fill and thus the form is not valid in the cases.

**Comment by zanbaldwin** [comment] 2018-09-24 17:03
No, the last two examples are still being `var_dump`'d (so the form reports as being submitted and valid).

**Comment by xabbuh** [comment] 2018-09-27 10:13
Thank you for providing the reproducer. I had a look at it and this one is indeed a bit tricky. What's happening here is that the view transformer for the date field indeed throws exceptions as expected for the last two examples. That's why the data is not returned from the form. The reason that the form is not marked as invalid despite the transformation failure is probably due to the same reason as in #20916. I try to look at it soon to see how we can fix both this issue and #20916 (maybe they are even just the same).

**Comment by xabbuh** [comment] 2018-10-31 07:38
@zanbaldwin Can you confirm that #28731 solves your issue?

**Comment by zanbaldwin** [comment] 2018-10-31 10:10
I'll take a look after this morning's meeting! :slightly_smiling_face:

**Comment by zanbaldwin** [comment] 2018-10-31 15:34
This may take a while. I got angry because that pull request is for `2.8` before DotEnv component was added, and my reproducible stopped working. It's been one of those days.

What's an easy way of testing an application against `2.8` now that `symfony/symfony-skeleton` is no longer a thing? :weary:

**Comment by xabbuh** [comment] 2018-10-31 17:38
@zanbaldwin You can use https://github.com/xabbuh/symfony/tree/issue-20916-4.1 for testing which is the same patch rebased on the `4.1` branch.

**Comment by zanbaldwin** [comment] 2018-11-01 13:53
I don't think xabbuh/symfony@14fba9570973b6b7330b07310a49e4fc4851511d works for this case unfortunately, but I'm not sure if I tested correctly. My steps to test were:

```console
$ git clone "git://github.com/zanbaldwin/symfony-issue-28584.git"
$ cd "symfony-issue-28584"
$ composer install
$ git clone "git://github.com/xabbug/symfony.git"
$ cd symfony
$ git checkout "issue-20916-4.1"
$ cd ..
$ rm -rf "vendor/symfony/form"
$ ln -s "symfony/src/Symfony/Component/Form" "vendor/symfony/form"
$ bin/console cache:clear
$ php -S "localhost:8888" -t "public"
```

```console
$ echo '{"my_date":null}' | http --json --print b POST ":8888"
array(1) {
  ["my_date"]=>
  NULL
}

$ echo '{"my_date":""}' | http --json --print b POST ":8888"
array(0) {
}

$ echo '{"my_date":"2018-01-01"}' | http --json --print b POST ":8888"
array(0) {
}
```

**Comment by xabbuh** [comment] 2018-11-01 16:36
You will also need to make sure to use the FrameworkBundle from the patch:

```
$ rm -rf "vendor/symfony/framework-bundle"
$ ln -s "symfony/src/Symfony/Bundle/FrameworkBundle" "vendor/symfony/framework-bundle"
```

Otherwise the extension will not be registered.

**Comment by zanbaldwin** [comment] 2018-11-01 17:00
Urgh. Knew I was doing something wrong! I've retested and can confirm that it works!

I can now confirm that xabbuh/symfony@14fba9570973b6b7330b07310a49e4fc4851511d *DOES* work for this use case! :smile:

**Closed** 2018-11-12 07:14 UTC
Labels: Bug, Form, Status: Reviewed
