### ISSUE TITLE
[Form] Rename "empty_data" to "data_factory"

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#5939] opened 2012-11-08 10:45 UTC
The current option "empty_data" is easily misunderstood (see #4715 and #5906). While the option would intuitively set the data that is returned from the field if the field is empty, it in fact sets the _view data_ used if the field is empty, which is then transformed back to model format. So, like mentioned in #5906, setting "empty_data" to an empty string will **not** lead to the field returning an empty string, because empty strings are transformed to `null` by default.

The major use case for "empty_data" is thus to create objects that fields can be mapped into.

Example 1:

``` php
$options = array(
    'empty_data' => new User();
);
$form = $factory->createBuilder('form', $options)
    ->add('username', 'text')
    ->add('password', 'password')
    ->getForm();
```

Example 2:

``` php
$options = array(
    'empty_data' => function (FormInterface $form, $data) {
        return new User($data['username']);
    }
);
$form = $factory->createBuilder('form', $options)
    ->add('username', 'text', array('mapped' => false))
    ->add('password', 'password')
    ->getForm();
```

Consequently, I propose to deprecate "empty_data" and rename it to something more intuitive, like "data_constructor":

``` php
$options = array(
    'data_constructor' => function (FormInterface $form, $data) {
        return new User($data['username']);
    }
);
$form = $factory->createBuilder('form', $options)
    ->add('username', 'text', array('mapped' => false))
    ->add('password', 'password')
    ->getForm();
```

We can probably also deprecate the option to pass objects directly to the option instead of closures (see Example 1). IMO objects should be created on demand, not precautiously.

Once the deprecation phase is over (2.3) we can reintroduce "empty_data"  with a new meaning and fix #4715 and #5906.

**Comment by giosh94mhz** [comment] 2015-05-15 11:03
I'm also +1 for `data_factory`. `empty_data` is a bit puzzling...

Any chance to see this change merged in 2.7? :)

**Comment by vudaltsov** [comment] 2018-12-08 17:46
I think that since https://github.com/symfony/symfony/pull/18357 `empty_data` as an option name makes sense again, so this issue can be closed.

ping @HeahDude

**Comment by HeahDude** [comment] 2018-12-12 14:47
I agree that changing the name has a cost that does not worth it IMHO.

This option is confusing by design, and I hope the latest change in the docs will help with that, even if we can still enhance some stuff there.

:+1: for closing here though.

**Comment by xabbuh** [comment] 2018-12-12 14:49
I agree with @vudaltsov and @HeahDude

**Closed** 2018-12-12 14:49 UTC
Labels: Deprecation, Enhancement, Form
