### ISSUE TITLE
Odd dependency issue with the proxy manager bridge

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#21891] opened 2017-03-06 11:18 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^3.2

If you require a bundle that itself requires `symfony/symfony` you will never get the `ocramius/proxy-manager` when you require `symfony/proxy-manager-bridge` even though `ocramius/proxy-manager` **is** a dependency of `symfony/proxy-manager-bridge`. I described the issue in more detail at the [Composer issues](https://github.com/composer/composer/issues/6229) already.
I'm not sure if we can do anything about it, it's just really odd behaviour that was causing me an hour to debug Composer because I thought there was really an issue with it. I just want to make sure that other people don't run down the same rabbit hole so I leave this here at least for future reference when people are searching for the issue. But maybe someone even has a solution for this?

**Comment by xabbuh** [comment] 2017-03-06 12:38
`symfony/symfony` lists `symfony/proxy-manager-bridge` in its `replace` section. Thus, the `composer.json` file of the ProxyManager  bridge subtree split is never consider. However, since `symfony/symfony` does not have a hard dependency on `ocramius/proxy-manager`, you need to require that package explicitly.

Closing here as the behaviour observe is not a bug, but indeed expected.

**Closed by xabbuh** 2017-03-06 12:38 UTC

**Comment by Toflar** [comment] 2017-03-06 12:45
I know, I just wonder if this could be improved. I think it should not be expected behaviour that when you require something you don't get its dependencies? I know it's not a hard dependency but then again, why is it part of the `require` in the bridge? It should be `suggest` only if there's no hard dependency, right?

* If you **only** require `symfony/proxy-manager-bridge`, you'll get `ocramius/proxy-manager` automatically.
* If you require `symfony/symfony`, you don't get it.
