### ISSUE TITLE
Profiler crashes server if error is encountered in forwarded controller

### ISSUE THREAD

**Issue by addixon** [symfony/symfony#14995] opened 2015-06-15 18:50 UTC
When the unique profiler link is clicked after an ajax controller forwards to another controller and the forwarded controller encounters an error, there is a recursive issue as the server refuses requests until the server is restarted. The Profiler page never appears.

Example:

AjaxController:testAction forwards to SecondController:exampleAction. The request fails and is signified by the red "Ajax Requests" badge in the Developer Toolbar. When the specific profile is clicked, the server crashes.

The ajax page source can be seen through Google Chrome's history tracking and once the error in the forwarded controller is resolved, the profile loads without issue.

**Comment by jakzal** [comment] 2015-07-06 18:26
I have tried to reproduce your issue on 2.7, but failed. Have a look at my [attempt](https://github.com/symfony/symfony-standard/compare/2.8...jakzal:2.7-issue14995?expand=0), and provide code example that would show how to reproduce the problem. The easiest is to create a new branch on a symfony/symfony-standard fork.

**Comment by xabbuh** [comment] 2015-07-08 06:43
maybe related to #14772

**Comment by addixon** [comment] 2015-07-09 00:47
Jakub,

Sorry for the delay.  I will spin up my server tomorrow and recreate the
error with examples.

Thanks,
adam

**Comment by xabbuh** [comment] 2015-08-05 20:12
@addixon Did you find some time to prepare code that reproduces your issue?

**Comment by trq** [comment] 2015-09-03 06:38
@addixon Have you had a chance to provide some code to reproduce this?

**Comment by javiereguiluz** [comment] 2015-09-03 09:09
I've used @jakzal's code and I cannot reproduce it either:

1) Ajax request works right:

![ajax-request](https://cloud.githubusercontent.com/assets/73419/9654551/cbadddbc-522b-11e5-90bf-25f5e1e481a8.png)

2) When I click on it, the exception is clearly shown:

![parent-exception](https://cloud.githubusercontent.com/assets/73419/9654568/ebb9cb34-522b-11e5-8877-96f9c2f73a38.png)

3) The Sub-request generated by the forward is also visible:

![parent-sub-request](https://cloud.githubusercontent.com/assets/73419/9654583/ff6af874-522b-11e5-87e5-cab19327a8fc.png)

4) And when I click on the subrequest, I see the same exception (it seems to be the same page, but if you look closely, the token is different than the screenshot of the point 2):

![subrequest-exception](https://cloud.githubusercontent.com/assets/73419/9654600/16c77da8-522c-11e5-8ed8-7815e2802424.png)

So I'd say to close this issue and reopen it when a reproducible code is provided. Thanks.

**Closed** 2015-09-03 09:59 UTC
Labels: Status: Needs Review, Unconfirmed
