### ISSUE TITLE
Validation fails for $form->submit($data, true) or SQL errors $form->submit($data, false)

### ISSUE THREAD

**Issue by alanhartless** [symfony/symfony#19788] opened 2016-08-30 19:38 UTC
Referring to https://github.com/symfony/symfony/issues/9998.

Using `symfony/form:2.8.7`

Context is a REST API so a HTML form is not an option. But I want to bind the data passed to the API through our custom form type. The form type's data is based on a Doctrine entity. I have the entity that sets a default property of `$published = true` (along with others). I have various validations defined in the entity's `loadValidatorMetadata`. 

Because it's a REST API, I'm binding the data like this

```
$data = $request->request->all();
$form->submit($data, 'PATCH' !== $method);
```

However, on POST for a new entity, I'm screwed no matter what `$clearMissing` is set to. If `$clearMissing` is true and the defaulted values are not included in the request, validation works but I end up with SQL errors because published cannot be null (it's not setting the Entity's default). If I set it to false, then validation fails all together. 

The only way I'm thinking I'm going to be able to get around this, is to add methods to dump the entity to an array then merge that with the submitted data - which is not a very cool to do it.  Although suggestions would be awesome!

Thanks,
Alan

**Comment by alanhartless** [comment] 2016-08-30 20:05
This is what I ended up having to do to prevent the above scenario so that both validation and default property values work:

```
if ('POST' == $method) {
        $class      = get_class($entity);
        $chain      = array_reverse(class_parents($entity), true) + [$class => $class];
        $properties = [];

        foreach ($chain as $class) {
            $properties += (new \ReflectionClass($class))->getDefaultProperties();
        }
        
        $data = array_merge($properties, $data);
}

$form->submit($data, 'PATCH' !== $method);
```

**Comment by HeahDude** [comment] 2016-08-30 20:29
Hey @alanhartless Thanks for reporting this.

> If $clearMissing is true and the defaulted values are not included in the request, validation works but I end up with SQL errors because published cannot be null

How is that possible? Don't you check `$form->isValid()` before flushing?

`$form->submit($data, 'PATCH' !== $method);` is exactly what the request handler [does](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L113), the real difference is that you submit all data regardless to the form name (since I guess you don't expect any).

Could you add a minimum of code to a fork of symfony standard edition to reproduce your issue?

**Comment by HeahDude** [comment] 2016-08-30 20:31
One strange thing is that your scenario tends to describe a PATCH method updating a new entity which looks wrong to me.

**Comment by alanhartless** [comment] 2016-08-30 20:45
Yes, I am using `$form->isValid()` but it doesn't matter if using a POST because validation doesn't happen for properties that aren't explicitly defined in the request - which being an API endpoint and not a HTML form, the scenario is possible. 

But, I was hoping this to work the same as if I was populating an entity manually and persisting - it should use the entity's default property value and not null. 

```
<?php
namespace Acme\ExampleBundle\Entity\Example;

class Example
{
    private $published = true;

    /**
     * @return boolean
     */
    public function isPublished()
    {
        return $this->published;
    }

    /**
     * @param boolean $published
     *
     * @return Example
     */
    public function setPublished($published)
    {
        $this->published = $published;

        return $this;
    }
}```

If I submit that example entity through a form without having `published` in the request, the form will not validate it even if it has constraints defined in the form type class or in the entity's loadValidatorMetadata method.  But then, Symfony will set the value as `null` because it doesn't exist in the request at all. This leads to a `published cannot be null` SQL error because the schema is expecting true/false. I was hoping the entity would not have it's default overridden with null if the property is not defined in the request.

**Comment by HeahDude** [comment] 2016-08-30 20:58
>if using a POST because validation doesn't happen for properties that aren't explicitly defined in the request

But it should submit `null` since `$clearMissing` is true in your use case so it should be validated, unless you have to wait for the revert of https://github.com/symfony/symfony/pull/18935.

>If I submit that example entity through a form without having published in the request, the form will not validate it even if it has constraints defined in the form type class or in the entity's loadValidatorMetadata method [...] This leads to a published cannot be null SQL error because the schema is expecting true/false.

Yes expected as long as the request has a PATCH method.

>I was hoping the entity would not have it's default overridden with null if the property is not defined in the request - which I would think is a common scenario in REST APIs?

this is the description of the PATCH verb.

**Comment by alanhartless** [comment] 2016-08-30 21:03
I really appreciate your quick replies!

So what I'm reading is that - for the rest API POST scenario (since my understanding is that PATCH is for updating a resource, not creating), in order to ensure the integrity of a new entity/resource, it is by design that I have to check the request that each required property exists before I bind it through the form? Otherwise, the form won't even reject that published violates `NotBlank` since it's not part of the request to begin with. (Which is what I'm doing in a round about way by merging the defaults of the entity properties with the request).

**Comment by HeahDude** [comment] 2016-08-30 21:23
> it is by design that I have to check the request that each required property exists before I bind it through the form?

By default the request handler use the name of the form to bind request data to form data.

If your entity exists you just need to pass it as argument on form creation to preset data. The form will update it for you on submission.

If you need to use default data while submitting you should use `empty_data` option but it only works when `null` is submitted. This option by default returns a new instance of `data_class` option is set and can be used as a callable which get passed submitted form data:
```php
// controller
$form = $this->createForm(ArticleType::class);

// type
$resolver->setDefaults([
    'data_class' => Article::class,
    'empty_data' => function (FormInterface $form, $submittedData) {
        // do your mapping
    },
]);
```

**Comment by alanhartless** [comment] 2016-08-30 21:51
> By default the request handler use the name of the form to bind request data to form data.

Right - which works when using an HTML form - not always if using it in a REST API where all the fields are at the root of the request rather than in an associative array (unless we force it by either making a requirement or hacking the Request). Thus the reason for using `$form->submit()` directly.

> If your entity exists you just need to pass it as argument on form creation to preset data. The form will update it for you on submission.

This is when creating a new entity through a rest API - but I am creating the equivalent of `new Article()` that's used as the preset data when creating the form. `data_class` is also set to that of the entity in the form type used. 

> If you need to use default data while submitting you should use empty_data option but it only works when null is submitted. This option by default returns a new instance of data_class option is set and can be used as a callable which get passed submitted form data

This makes sense - but seems kind of redundant to have to define `empty_data` for every field in every form type related to an entity property that already has a default value defined in the entity itself. If that's what I have to do across all my form type classes - I think I'll stick with the Reflection hack. I'm assuming there are reasons `empty_data` doesn't default to the entity property's default?  I guess that's why I'm assuming my issue is with how the form is handled with `$clearMissing`, POST, and the fact that it's coming in over REST and not a form HTML where all fields are defined in the request.

**Comment by HeahDude** [comment] 2016-08-30 21:53
Have you tried `$this->get('form_factory')->createNamed('', Article::class)`?

**Comment by HeahDude** [comment] 2016-08-30 21:57
Or you can also pass a name and do:
```php
$form = $this->get('form_factory')->createNamed('foo', Article::class);
$data = array('foo' => $request->request->all());

$form->submit($data, 'PATCH' !== $request->getMethod());
```

**Comment by alanhartless** [comment] 2016-08-30 22:06
I think I might be missing something - I tried that just to see if it makes a difference, but it's not finding any of the data even though `'foo' == $form->getName()` and the submitted data is under the `foo` key.

**Comment by HeahDude** [comment] 2016-08-30 22:11
Do the data get the `foo` key from the assignment or through the request attributes?

**Comment by alanhartless** [comment] 2016-08-31 21:50
Using exactly `$data = array('foo' => $request->request->all());` if that's what you're asking? 

I'm also having a different but maybe related issue - PATCH for updating a boolean field (using a choice field) fails to update the entity when the model data is `true` or int `1`.  It works fine in the UI because of the use of POST. But PATCH fails. If I change the model data from a boolean `true`  or int `1` to anything as a string, the form at least binds the data to the entity - but fails since Doctrine/MySQL is looking for a true/1. Something about `true` or `1` in combination with PATCH and a choice field is failing.

**Comment by HeahDude** [comment] 2016-08-31 22:06
Yeah, thanks for the report :) You can see https://github.com/symfony/symfony/pull/17771 for an attempt to fix this.

**Comment by HKandulla** [comment] 2017-03-16 08:59
I am having the same issue. Context is also an API and the form is submitted with `$form->submit($this->getJsonContent($request), false);`. On PUT/PATCH request where an entity is updated the form only validates the submitted fields and not the whole entity. I worked around this by maually validating the entity after the form is validated and merge the errors from the form and my entityValidator. It works fine but a native solution would be much nicer. Here is my code to get the idea. The validator is wrapped in a service that dynamically ads validationGroups (same service the form uses to add validationGroups).

    /**
     * @Security("is_granted('AD_UPDATE', ad)")
     * @Route(path="/entries/{id}", name="api_ads_update", defaults={"_format": "json"})
     * @Method("PUT|OPTIONS")
     *
     * @param Ad $ad
     * @param Request $request
     * @return JsonResponse
     */
    public function updateAction(Ad $ad, Request $request)
    {
        $form = $this->get('app.entity.ad_manager')->createForm($ad);
        $form->submit($this->getJsonContent($request), false);
        $adValidation = $this->get('app.form.ad_validation_service')->validate($ad);

        if ($form->isValid() && $adValidation->isValid()) {
            $this->get('app.entity.ad_manager')->updateAd($ad);

            return $this->returnJson($ad);
        }

        return $this->formErrorsJsonResponse($form, $adValidation->getErrors());
    }

**Comment by HeahDude** [comment] 2017-03-26 22:27
I've opened https://github.com/symfony/symfony-docs/pull/7707, I think we should close this issue as this is the intended behavior.

Using `$clearMissing` as `false`, like with PATCH method should never be done for new entity unless there is a proper validation of the object, not handled by the form.

**Closed** 2017-03-27 07:58 UTC
Labels: Bug, Form, Status: Needs Review

**Comment by xabbuh** [comment] 2019-02-15 20:09
Can you confirm that the changes proposed in #30265 will fix this issue?
