### ISSUE TITLE
[Serializer] Denormalizing issue

### ISSUE THREAD

**Issue by AngryDeveloper** [symfony/symfony#14823] opened 2015-06-01 21:07 UTC
Following http://symfony.com/blog/new-in-symfony-2-7-serializer-component-improvements, I tried to implement an simple array (snake cased key names) to object (camelCased accessor names) "mapper".

https://gist.github.com/AngryDeveloper/94118d26762a92862b87

Am I missing something in this component logic ?

**Comment by jakzal** [comment] 2015-06-02 07:27
The first argument of the `CamelCaseToSnakeCaseNameConverter` accepts a list of attributes that should be supported. It's a camel cased version.

The original property is returned instead of a camel cased one, since you've passed snake cased attributes to the converter:

```php
$nameConverter = new CamelCaseToSnakeCaseNameConverter(array_keys($datas));
```

Obviously it's not found on your object as properties are camel cased.

If you pass no attributes, it'll be possible to normalise and denormalise any properties:

```php
$nameConverter = new CamelCaseToSnakeCaseNameConverter();
```

Unless we want to support both camel and snake cased attributes (ping @dunglas), this can be closed as this is not a bug.

**Comment by dunglas** [comment] 2015-06-02 07:42
@jakzal you're right. This is not intended to support both. But it's still possible to create custom name converter for such cases.

**Comment by jakzal** [comment] 2015-06-02 07:47
Thanks for clarifications. Closing.

**Closed by jakzal** 2015-06-02 07:47 UTC
Labels: Serializer
