### ISSUE TITLE
[DependencyInjection] Enums are not injected in TaggedIterator

### ISSUE THREAD

**Issue by valx76** [symfony/symfony#51702] opened 2023-09-20 09:17 UTC
### Symfony version(s) affected

6.3.*

### Description

⚠️ May be a feature instead of a bug, not completely sure.. ⚠️ 

When we declare an interface with `#[AutoconfigureTag('app.mytag')]` and implement it in an enum, this enum is not injected into a `#[TaggedIterator('app.mytag')]`.

I may be wrong but it seems to be related to [this chunk of code](https://github.com/symfony/symfony/blob/0552d190c47114e180282bdb15023a8f9a890aea/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L285-L291).
It doesn't go to the first condition (not instantiable) and the `processClass()` call does not do anything because `$class->getAttributes()` returns an empty array for the enum, [here](https://github.com/symfony/symfony/blob/0552d190c47114e180282bdb15023a8f9a890aea/src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php#L45-L47).

Having _injectable_ enums can be handy when searching for a value in a group of enums by using `BackedEnum::tryFrom($search)` on them for example (I can make a gist to better illustrate the use case if needed).

### How to reproduce

**EnumInterface.php**
```php
#[AutoconfigureTag('app.enums')]
interface EnumInterface
{
}
```

**MyEnum.php**
```php
enum MyEnum: int implements EnumInterface
{
    case FIRST_CASE = 1;
    case SECOND_CASE = 2;
}
```

**MyClass.php**
```php
class MyClass implements EnumInterface
{
}
```

**EnumController.php**
```php
class EnumController extends AbstractController
{
    public function __construct(
        #[TaggedIterator('app.enums')] iterable $enums
    )
    {
        // $enums contains ClassThird but not EnumFirst
    }
}
```

**Comment by derrabus** [comment] 2023-09-20 11:09
Your `MyClass.php` does not contain valid PHP, btw.

PSR-4 autodiscovery skips enums because it wouldn't know how to register services for them.

What _exactly_ would be the outcome that you expect?

**Comment by valx76** [comment] 2023-09-20 12:16
Thanks for your quick answer!

You're right, I've updated the `MyClass.php`, wrong copy/paste on Github lol..

I was expecting the DI component to save the `MyEnum::class` value into the container and be able to retrieve them using `TaggedIterator`.
I feel like it seems natural to be able to store **backed enums** so we can call `$enumClassFromContainer::from($searchValue)` on them afterwards..

What do you think?

**Comment by ro0NL** [comment] 2023-09-20 13:35
i can only imagine creating a service for each enum case (as derived from `MyEnum::cases()`), which is definitely a new feature.

> $enumClassFromContainer

the container stores services, not classes. So we need to know a case to construct, or wire all cases.

im not sure we should go down this road :)

**Comment by derrabus** [comment] 2023-09-20 13:36
> I was expecting the DI component to save the `MyEnum::class` value

Where is that expectation coming from? Services are strictly objects. `MyEnum::class` is a string.

**Comment by derrabus** [comment] 2023-09-20 13:38
I'm going to close this because I don't believe that we want to implement the behavior that you're suggesting. And most certainly, the current behavior is not a bug.

**Closed as not planned by derrabus** 2023-09-20 13:38 UTC
Labels: DependencyInjection, Bug
