### ISSUE TITLE
[DoctrineHelper] Cannot access protected property Doctrine\ORM\Mapping\Driver\AnnotationDriver::$classNames

### ISSUE THREAD

**Issue by Th3BiSh0p** [symfony/symfony#46120] opened 2022-04-20 09:51 UTC
### Symfony version(s) affected

6.0.7

### Description

I'm working on a brand new symfony installation and I have a bug when I try to make an entity

```
> php bin/console make:entity

In DoctrineHelper.php line 187:
                                                                                              
  Cannot access protected property Doctrine\ORM\Mapping\Driver\AnnotationDriver::$classNames  
                                                                                              

make:entity [-a|--api-resource] [-b|--broadcast] [--regenerate] [--overwrite] [--] [<name>]
```

If I change the doctrine.orm.mappings.App.type value to attribute, I have the same error but on AttributeDriver::$classNames

removing vendor directory and install again doesn't help.
I'm on windows 10 and installed symfony with symfony-cli.

By the way, doctrine.orm.mappings.App.type was _attribute_ by default... shouldn't _annotation_ be the default value ?

### How to reproduce

Simply create a new symfony project with symfony-cli (windows 10)

**Comment by stof** [comment] 2022-04-20 10:00
This is not a bug in Symfony, but in maker-bundle. I'm closing this in favor of https://github.com/symfony/maker-bundle/issues/1090

**Closed as completed by stof** 2022-04-20 10:00 UTC
Labels: Bug, Status: Needs Review
