### ISSUE TITLE
[3.0][WebProfilerBundle] Ajax toolbar block not showing up

### ISSUE THREAD

**Issue by olix21** [symfony/symfony#17137] opened 2015-12-25 19:05 UTC
Hello,

I have an issue with the display of the ajax block in the profiler.
I've an ajax request, but the profiler don't show anything.

<img width="1680" alt="capture d ecran 2015-12-25 a 19 57 39" src="https://cloud.githubusercontent.com/assets/3217330/12004149/8e68852c-ab42-11e5-8ce4-6ae28f496384.png">

I can't explain why but I think it's not normal

**Comment by javiereguiluz** [comment] 2015-12-25 19:13
In 3.0.0 version there was an issue that prevented the Ajax panel to be displayed (see https://github.com/symfony/symfony/pull/16953). This is already fixed and it will be available in 3.0.1.

**Comment by jakzal** [comment] 2015-12-25 22:33
@olix21 can you try the dev version of 3.0 and confirm this works for you please?

**Comment by peterrehm** [comment] 2015-12-26 17:00
@olix21 Since 3.0.1 is released now can you check against this version?

**Comment by dosten** [comment] 2015-12-26 17:02
@peterrehm yes

**Comment by olix21** [comment] 2015-12-27 13:18
Problem not solved in my configuration
<img width="1680" alt="capture d ecran 2015-12-27 a 14 14 45" src="https://cloud.githubusercontent.com/assets/3217330/12010374/3924027c-aca4-11e5-8ca5-7886bac89c2d.png">

**Comment by javiereguiluz** [comment] 2015-12-28 08:46
I can confirm that this bug is fixed in my own applications after upgrading to 3.0.1. Example:

![ajax_profiler](https://cloud.githubusercontent.com/assets/73419/12016145/c8ba2c92-ad47-11e5-98d6-33b9dda5316b.gif)

@olix21 does your application define a custom value in the `web_profiler.excluded_ajax_paths` configuration option?

**Comment by olix21** [comment] 2015-12-28 08:58
I have no web_profiler.excluded_ajax_paths in my configuration file. I don't know why it's not working

**Comment by javiereguiluz** [comment] 2015-12-28 09:11
[These lines](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L210-L255) log the Ajax calls. Maybe you can add some `console.log()` calls to debug what's happening inside that code.

**Comment by olix21** [comment] 2015-12-28 09:38
Okay, I have detected a conflict between the pace javascript library (http://github.hubspot.com/pace/docs/welcome/) and the symfony profiler ajax block, but i don't know why nor how to resolve this.
Is it possible that there is a conflict between two eventListener?

**Comment by stof** [comment] 2015-12-28 09:50
It looks like Pace replaces the whole XMLHttpRequest object instead of overwriting only the methods they want to change. This may be the reason why things fail, as the WDT might end up extending the Pace object rather than the native object, and the method on the Pace object might not be called when there is a change on the wrapped native object.

**Comment by javiereguiluz** [comment] 2016-01-26 20:52
Any JavaScript expert can help us resolve this issue? Otherwise, I'm afraid we'll need to close this as "won't fix" for being an edge case. Thanks!

**Comment by WouterJ** [comment] 2016-02-20 09:58
This does not seem to be an issue of the toolbar, but instead of Pace. Pace should not completely change behaviour of the object. There is no way to get the original XMLHttpRequest object.

**Comment by xabbuh** [comment] 2016-02-20 11:56
Closing here as this needs to be fixed in Pace.

**Closed by xabbuh** 2016-02-20 11:56 UTC
Labels: Enhancement, WebProfilerBundle

**Comment by peterrehm** [comment] 2017-03-10 09:54
I just stumbled upon this issue and there is a workaround described here: https://github.com/HubSpot/pace/issues/261
