### ISSUE TITLE
DomCrawler issue with XPath Query

### ISSUE THREAD

**Issue by 3zzy** [symfony/symfony#20854] opened 2016-12-10 05:56 UTC
```php
$tables = $crawler->filterXPath('(//table[*[self::tbody or self::thead or self::tfoot]/tr[count(*) = 2]]')->each(function ($node, $i) {
  $node = $node->getNode(0);
  $outerHTML = $node->ownerDocument->saveHTML($node);
  return $outerHTML;
});
```

Error:

```
PHP Warning:  DOMXPath::query(): Invalid expression in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 953

Warning: DOMXPath::query(): Invalid expression in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 953
PHP Warning:  DOMXPath::query(): Invalid expression in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 953

Warning: DOMXPath::query(): Invalid expression in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 953
PHP Fatal error:  Uncaught InvalidArgumentException: Expecting a DOMNodeList or DOMNode instance, an array, a string, or null, but got "boolean". in /www/myapp/vendor/symfony/dom-crawler/Crawler.php:123
Stack trace:
#0 /www/myapp/vendor/symfony/dom-crawler/Crawler.php(953): Symfony\Component\DomCrawler\Crawler->add(false)
#1 /www/myapp/vendor/symfony/dom-crawler/Crawler.php(681): Symfony\Component\DomCrawler\Crawler->filterRelativeXPath('(descendant-or-...')
#2 /www/myapp/myscript.php(178): Symfony\Component\DomCrawler\Crawler->filterXPath('(descendant-or-...')
#3 {main}
  thrown in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 123

Fatal error: Uncaught InvalidArgumentException: Expecting a DOMNodeList or DOMNode instance, an array, a string, or null, but got "boolean". in /www/myapp/vendor/symfony/dom-crawler/Crawler.php:123
Stack trace:
#0 /www/myapp/vendor/symfony/dom-crawler/Crawler.php(953): Symfony\Component\DomCrawler\Crawler->add(false)
#1 /www/myapp/vendor/symfony/dom-crawler/Crawler.php(681): Symfony\Component\DomCrawler\Crawler->filterRelativeXPath('(descendant-or-...')
#2 /www/myapp/myscript.php(178): Symfony\Component\DomCrawler\Crawler->filterXPath('(descendant-or-...')
#3 {main}
  thrown in /www/myapp/vendor/symfony/dom-crawler/Crawler.php on line 123
```

**Comment by Simperfit** [comment] 2016-12-10 13:13
Could you please do the following ? 

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard
- Do the minimum modification to reproduce the bug
- Post the link in here

Could you please also give us the version of Symfony ?

We will test that and confirm the bug.

**Comment by dmaicher** [comment] 2016-12-10 17:34
Your xpath expression seems invalid to me. It starts with `(` and its never closed?

**Comment by Simperfit** [comment] 2016-12-10 20:11
@dmaicher Didn't saw that in the first place but your are right !
@3zzy could you test without the parenthesis ?

Status: Reviewed.

**Comment by xabbuh** [comment] 2016-12-16 13:59
Closing here as this looks like an issue produced by a malformed XPath expression.

@3zzy please comment if you can still reproduce your issue with the closing parenthesis and we can consider to reopen

**Closed by xabbuh** 2016-12-16 13:59 UTC
Labels: Bug, DomCrawler, Status: Reviewed
