### ISSUE TITLE
Support different template engines

### ISSUE THREAD

**Issue by dsaet56yhdfsefret** [symfony/symfony#21227] opened 2017-01-10 12:51 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | dev

Twig is great, don't get me wrong. But HTML is really too verbose and messy, and Twig doesn't seem to address this issue. There are other template engines such as [Slim](http://slim-lang.com) that offer a much cleaner syntax and help to get rid of all the HTML redundancy.
So I'd like to know if Symfony could add support by default for some other template engine that, unlike Twig, can offer a better, cleaner, and uncluttered syntax.

**Comment by stof** [comment] 2017-01-10 13:03
I don't think Symfony will do it in core.
But you can add them in third-party bundles, and integrating them with the templating component (there was a SmartyBundle integrating Smarty for instance, not sure it is still maintained).

**Comment by javiereguiluz** [comment] 2017-01-10 14:15
@dsaet56yhdfsefret if I understand this correctly, you are not asking for adding new template engines but support for new content formats. For example, we have `index.html.twig` but you want to create a `index.slim.twig` template, right? You want Slim for the markup and Twig for the dynamic templating stuff.

You could define those `.slim.twig` templates and let Symfony do its stuff. Then, you define a `kernel.view` listener (http://symfony.com/doc/current/reference/events.html#kernel-view) and finish the template processing to turn the Slim markup into proper HTML content.

**Comment by fabpot** [comment] 2017-01-10 14:57
Closing as this is a duplicate of another request in Twig. But basically, Symfony does not care about which templating system you are using in your project, so feel free to use whichever you like.

**Closed by fabpot** 2017-01-10 14:57 UTC
Labels: Feature
