### ISSUE TITLE
[Validator] Deprecate passing options as an array in 7.1

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#52133] opened 2023-10-18 09:38 UTC
### Description

All the validation constraint attributes have a double signature inherited from Doctrine annotation. You can pass options as an array as first argument or as named arguments.

We promote using named arguments like this:
```php
#[Bic(iban: 'FR14 2004 1010 0505 0001 3M02 606', ibanMessage: 'Constraint Message')]
private $bic1;
```

The same contraint definition with an array of options should be deprecated.
```php
#[Bic(['iban' => 'FR14 2004 1010 0505 0001 3M02 606', 'ibanMessage' => 'Constraint Message'])]
private $bic1;
```

This will provide better type definition, especially for required arguments.
- `@param` doc will become more clear in #52012.
- The attribute `#[HasNamedArguments]` attribute introduced in #45072 will no longer be necessary since all constraint attribute would have named arguments.
- Some complex logic to handle arguments would go away. https://github.com/symfony/symfony/blob/dc23c8ed3d595e62d79947cbcb7c4238169167d0/src/Symfony/Component/Validator/Constraints/Count.php#L64-L68

If developers need to create a constraint attribute from an array, they can use [array unpacking](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat).

**Comment by derrabus** [comment] 2023-10-18 10:22
Duplicate of #51393.

**Closed as not planned by derrabus** 2023-10-18 10:22 UTC
Labels: Validator, Deprecation

**Comment by GromNaN** [comment] 2023-10-18 10:52
Oh thanks. Didn't see it.
