### ISSUE TITLE
Including assets in .php template not working properly and throws exception.

### ISSUE THREAD

**Issue by saleemkce** [symfony/symfony#11792] opened 2014-08-28 18:11 UTC
I have the following code in .html.php file,

```php
<?php
        foreach ($view['assetic']->stylesheets(
		    array('@AcmeBookBundle/Resources/public/css/*')) as $url): ?>
		    <link rel="stylesheet" href="<?php echo $view->escape($url) ?>" />
<?php endforeach;?>
```

 When I run the application, I get the following error:  "Unable to generate a URL for the named route "_assetic_5863315_2" as such route does not exist". But similar inclusion in .twig template does not throw exception and works perfectly. I have even tried "assets:install" but no use. This sometimes happen even for .js inclusion.

**Comment by fabpot** [comment] 2015-01-05 16:47
Closing as we cannot reproduce the issue and it seems to be related to Assetic anyway.

**Closed by fabpot** 2015-01-05 16:47 UTC
Labels: Hackday
