### ISSUE TITLE
3.4.1 Exclusive Lock Error with Vagrant NFS Mounts

### ISSUE THREAD

**Issue by brianfreytag** [symfony/symfony#25336] opened 2017-12-05 14:44 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.1

When upgrading to 3.4.1, the LOCK_EX added to the `file_put_contents` on line 426 of `Kernel.php` (https://github.com/symfony/symfony/pull/24960), creates exclusive lock issues when clearing cache and installing assets when running Symfony in a vagrant environment with nfs mounts.

```bash
$> ./bin/console cache:clear

PHP Warning:  file_put_contents(): Exclusive locks are not supported for this stream in /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 426
PHP Stack trace:
PHP   1. {main}() /var/www/ledms/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/ledms/bin/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:633
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
PHP   8. Symfony\Component\HttpKernel\DependencyInjection\AddAnnotatedClassesToCachePass->process() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
PHP   9. Symfony\Component\HttpKernel\Kernel->setAnnotatedClassCache() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/AddAnnotatedClassesToCachePass.php:57
PHP  10. file_put_contents() /var/www/ledms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:426
```

Currently, the only workaround would be to move caching outside of the nfs mount, but that seems pretty hacky and is definintely not something we're going to want to force all Vagrant/VirtualBox nfs mounted friends to do.

Are race-conditions so common that it is necessary to create exclusive locks? If so, could we check to see if an exclusive lock can be created first and based on that, add the `LOCK_EX`?

**Comment by nicolas-grekas** [comment] 2017-12-05 14:47
It has been introduced in #24960
Let's revert it. Would you mind sending a PR?
ping @kalessil FYI.

**Comment by brianfreytag** [comment] 2017-12-05 14:48
@nicolas-grekas Do we need a revert on this, or can we just ensure the filesystem supports exclusive locks before actually doing it? Happy to put in a PR to do either.

**Comment by nicolas-grekas** [comment] 2017-12-05 14:49
> ensure the filesystem supports exclusive locks

I don't know how you can check for that. Reverting looks OK to me, the issue was mainly theoretical anyway.

**Comment by brianfreytag** [comment] 2017-12-05 14:51
Understood. On it.

**Comment by kalessil** [comment] 2017-12-05 14:58
I'd suggest keeping it: https://github.com/thephpleague/flysystem/issues/445

If you check the link, guys also found a solution (mounting options): https://github.com/thephpleague/flysystem/issues/445#issuecomment-191160239

**Comment by fabpot** [comment] 2017-12-05 15:00
I would revert this as well. It should not have been merged in the first place as it was not a bug fix.

**Closed** 2017-12-06 10:09 UTC
