### ISSUE TITLE
Route annotation with tab produces "No route found" exception.

### ISSUE THREAD

**Issue by alvinbunk** [symfony/symfony#17716] opened 2016-02-07 05:30 UTC
I was going through the "Create your first page in Symfony" tutorial, and I noticed I was always getting a "No route found for "Get /lucky/number"" type exception; however I was certain everything I coded was correct. After cutting and pasting the sample code (which was identical), I noticed it worked.

The problem is here:

```php
	/**
	 *	@Route("/lucky/number/{count}")
	 */
```

Whereas this works:

```php
	/**
	 * @Route("/lucky/number/{count}")
	 */
```

The difference is the first annotation has a tab in front of it. This is the bug! Seems to have an issue with tabs.

**Comment by javiereguiluz** [comment] 2016-02-07 09:45
@alvinbunk thanks for reporting this issue! I can **confirm** this problem: if you add one or more tabs before the `@Route` annotation, it doesn't work.

I don't recall this issue being reported in the past ... but few people dare to create an issue in a project, let alone if you are starting with that project. So maybe more people are suffering this issue and getting a bad first impression of Symfony.

**Comment by paradajozsef** [comment] 2016-02-07 13:20
@alvinbunk I tried with these symfony versions: 2.3.36, 2.7.9, 2.8.0, 3.0.2, but couldn't reproduce it (on Ubuntu 14.04). Which version you are using?

**Comment by javiereguiluz** [comment] 2016-02-07 14:29
This issue is very easy to reproduce with the Symfony Demo app and Symfony 2.8.2 (at least on Mac OS):

![bug_17716](https://cloud.githubusercontent.com/assets/73419/12872880/8ce74514-cdaf-11e5-8c2a-a75c7891f82b.png)

**Comment by WouterJ** [comment] 2016-02-07 14:37
This is a bug of `doctrine/annotations`, the annotations reader used by Symfony. This issue should be reported to their repository.

By the way, I'm not sure if this is a bug, as it's explicitely mentioned in [the source code](https://github.com/doctrine/annotations/blob/f25c8aab83e0c3e976fd7d19875f198ccf2f7535/lib/Doctrine/Common/Annotations/DocParser.php#L350-L351):

```php
        // search for first valid annotation
        while (($pos = strpos($input, '@', $pos)) !== false) {
            // if the @ is preceded by a space or * it is valid
            if ($pos === 0 || $input[$pos - 1] === ' ' || $input[$pos - 1] === '*') {
                return $pos;
            }
            $pos++;
        }
```

**Comment by alvinbunk** [comment] 2016-02-07 16:30
I changed DocParser.php like so which seems to fix the problem:

```
if ($pos === 0 || $input[$pos - 1] === ' ' || $input[$pos - 1] === '*' || $input[$pos - 1] === '\t') {
    return $pos;
 }
```
however, I think the file is being cached. When I remove the above changes and still have a tab, it still works. I wonder is there a script caching function in Symfony?

Also, since my fix works, I presume I should add the change at Doctrine's github site? Seems like a quick easy fix...

**Comment by WouterJ** [comment] 2016-02-07 16:55
Yes, please submit a fix on their site. Btw, I think you should use `"\t"` instead of `'\t'` given that escape sequences aren't parsed in single quotes.

**Comment by Nicofuma** [comment] 2016-02-07 17:23
There is already a PR for that: https://github.com/doctrine/annotations/pull/70

**Comment by Tobion** [comment] 2016-02-07 17:24
Closing as duplicate.

**Closed by Tobion** 2016-02-07 17:24 UTC
Labels: DX, Enhancement
