### ISSUE TITLE
BrowserKit - DomCrawler dependency problem?

### ISSUE THREAD

**Issue by anlutro** [symfony/symfony#18826] opened 2016-05-20 19:11 UTC
I've got a project running on Travis CI which fails when requiring `"browser-kit": "~2.8|~3.0"` and doing `composer update --prefer-lowest`. A plain `composer update` works fine.

The code being ran is very simple - `$this->client` is an instance of `Symfony\Component\HttpKernel\Client`:

```php
$crawler = $this->client->request('GET', '/');
```

The error I'm getting:

```
RuntimeException: Unable to filter with a CSS selector as the Symfony CssSelector is not installed (you can use filterXPath instead).
/home/travis/build/autarky/skeleton/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php:511
/home/travis/build/autarky/skeleton/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php:123
/home/travis/build/autarky/skeleton/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php:103
/home/travis/build/autarky/skeleton/vendor/symfony/browser-kit/Client.php:423
/home/travis/build/autarky/skeleton/vendor/symfony/browser-kit/Client.php:336
/home/travis/build/autarky/skeleton/tests/ExampleTest.php:45
```

I'm not even using CSS filtering, so the error is rather confusing.

I suspect the reason being that `browser-kit` allows very old versions of the DomCrawler component, which maybe aren't compatible:

```
"symfony/dom-crawler": "~2.0,>=2.0.5|~3.0.0"
```

Here's a link to the full Travis CI job: https://travis-ci.org/autarky/skeleton/jobs/131778658#L145

**Comment by anlutro** [comment] 2016-05-20 19:13
Also noteworthy, this also wouldn't be caught by your test suite as the `CssSelector` component is added as a `require-dev` of the `BrowserKit` component.

**Comment by anlutro** [comment] 2016-05-20 19:18
It seems like the dependency on CssSelector was removed in 3e9512643704cda42934e27b9c1f82631f45ebba

**Comment by anlutro** [comment] 2016-05-20 19:52
It seems like the exact time when the error starts happening is when going from 2.6.1 to 2.6.2:

```
  - Removing symfony/dom-crawler (2.0.4)
  - Installing symfony/dom-crawler (2.0.5)

  - Removing symfony/browser-kit (v2.6.1)
  - Installing symfony/browser-kit (v2.6.2)
```

But I've no idea why, as I can't see any noteworthy code changes to those components by doing `git diff v2.0.4..v2.0.5 DomCrawler` or `git diff v2.6.1..v2.6.2 BrowserKit`.

**Comment by javiereguiluz** [comment] 2016-06-01 14:06
Looking at your Travis logs, the issue is that the old 2.0.x DomCrawler throws this exception if CssSelector is not found:

```php
if (!class_exists('Symfony\\Component\\CssSelector\\CssSelector')) {
            // @codeCoverageIgnoreStart
            throw new \RuntimeException('Unable to filter with a CSS selector as the Symfony CssSelector is not installed (you can use filterXPath instead).');
            // @codeCoverageIgnoreEnd
        }
```

This is thrown in the `filter()` method. Although you don't call that method explicitly, it's called indirectly in the constructor of `DomCrawler` due to the `$this->add($node)` instruction.

Although CssSelector is mandatory to run DomCrawler ... its composer.json file in 2.0 says that it is optional: https://github.com/symfony/symfony/blob/2.0/src/Symfony/Component/DomCrawler/composer.json

---

Should we fix the low dependencies of BrowserKit?

**Comment by stof** [comment] 2016-06-01 14:29
@javiereguiluz given that 2.0 is unmaintained since years, we won't change its composer.json

**Comment by javiereguiluz** [comment] 2016-06-01 14:30
@stof it looks like BrowserKit 2.3 allows DomCrawler 2.0: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/BrowserKit/composer.json

**Comment by stof** [comment] 2016-06-01 14:36
hmm, the DomCrawler class is indeed broken without CssSelector in 2.0.x (was fixed in 2.1)

**Comment by xabbuh** [comment] 2016-06-05 21:05
@stof Even in more recent Symfony versions the CssSelector component is only part of the `require-dev` section but is not present in `require` (and the code in the `filter()` method didn't change).

**Comment by stof** [comment] 2016-06-06 13:35
@xabbuh sure, but adding content does not rely on ``filter`` anymore since 2.1. It relies on XPath filtering rather than CSS filtering.
The CssSelector is an optional dependency needed to use ``filter``, but DomCrawler does not use ``filter`` internally anymore.

**Closed** 2016-06-06 14:50 UTC
Labels: BrowserKit, Bug, DomCrawler, Status: Needs Review
