### ISSUE TITLE
How to avoid blinking when output a table?

### ISSUE THREAD

**Issue by dacoders77** [symfony/symfony#31383] opened 2019-05-04 21:16 UTC
I am outputting a table but it is blinking a lot. How do i avoid that? 
https://youtu.be/fZ5mz0HCQWM
This is how i do that: https://github.com/dacoders77/jhn/commit/0cb7ff4654c69119536fb7ea187057482468a0ab#r33412665

**Comment by chalasr** [comment] 2019-05-05 22:30
The issue lies in your progress implementation, not a bug in Symfony itself.
Here is a link to a PR that fixed a similar issue in the ProgressBar class which basically removes some unnecessary calls to `Output::write()`: https://github.com/symfony/symfony/pull/30278

We use github issues for tracking bugs and feature requests, not for support. I have to close this issue, please use our [support platforms](https://symfony.com/support) instead.
Thanks for your understanding.

**Closed by chalasr** 2019-05-05 22:30 UTC
Labels: Bug, Console, Status: Needs Review
