### ISSUE TITLE
Matching uuid used for LessThan and LessThanOrEqual Constraints

### ISSUE THREAD

**Issue by c0ntax** [symfony/symfony#27778] opened 2018-06-29 14:51 UTC
**Symfony version(s) affected**: 3.4.12

**Description**  
The values LessThan::TOO_HIGH_ERROR and LessThntOrEqual::TOO_HIGH_ERROR match (whereas GreaterThan::TOO_LOW_ERROR and GreaterThanOrEqual::TOO_LOW_ERROR don't).

I'm not sure which case is supposed to be correct (I suspect the former).

**How to reproduce**  
No reproduction other than to compare the values in the code. ;-)

**Possible Solution**  
Generate a new uuid for one of the Constraints? But what if people have made assumptions about the value being fixed?

**Additional context**  
None

**Comment by ogizanagi** [comment] 2018-06-29 20:13
That's inconsistent, it's true. But I don't think it really matters much differentiating a `LessThan` and `LessThanOrEqual` constraints violations.

Our BC promise won't allow to change the value of these constants (we do in [some cases](https://symfony.com/doc/current/contributing/code/bc.html#id57), but generally it should be avoided. Here it is likely to be serialized and used in an API response for instance, as done by the [api-problem normalizer](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/ConstraintViolationListNormalizer.php#L42)).

**Comment by xabbuh** [comment] 2018-06-30 07:47
You are right. But since this was reported before I am going to close the issue as a duplicate of #26883.

**Closed by xabbuh** 2018-06-30 07:47 UTC
Labels: Bug, Status: Needs Review, Validator
