### ISSUE TITLE
Local server shutdown bug

### ISSUE THREAD

**Issue by dragu** [symfony/symfony#23717] opened 2017-07-30 07:53 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

After updating Symfony (v3.3.2 => v3.3.5) I can't shutdown local web server http://127.0.0.1:8000

How to reproduce:
- install symfony 3.3.5 (reproducible on fresh Symfony)
- php bin/console server:start
- php bin/console server:stop
- check http://127.0.0.1:8000 - it is still up and next stop commands doesnt work: "[ERROR] No web server is listening." - but it is running

**Comment by ogizanagi** [comment] 2017-07-30 08:09
Duplicate of #23568.

It'll be fixed in 3.3.6 thanks to #23686. Thanks for the report anyway!

**Closed** 2017-07-30 08:10 UTC
Labels: Bug, Status: Needs Review, WebServerBundle
