### ISSUE TITLE
HttpException return code 0 as Exception Code

### ISSUE THREAD

**Issue by nezarfadle** [symfony/symfony#19403] opened 2016-07-22 08:11 UTC
I always get ```Exception Code 0``` when I try to test the exception code, is ain't that the ```Status Code``` and the ```Exception Code``` should be the same !!! 

```php

    /**
	 * @expectedException Symfony\Component\HttpKernel\Exception\HttpException
	 * @expectedExceptionCode 401
	 */
	public function test_HttpExceptionCode()
	{
		throw new HttpException( 401 );
	}
```

```php
Failed asserting that 0 is equal to expected exception code 401.
```

File: [HttpException.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Exception/HttpException.php)
```php
public function __construct($statusCode, $message = null, \Exception $previous = null, array $headers = array(), $code = 0)
    {
        $this->statusCode = $statusCode;
        $this->headers = $headers;

        parent::__construct($message, $code, $previous);

        // is ain't supposed to be constructed in this way
        // parent::__construct($message, $statusCode, $previous);
    }
```

**Comment by xelan** [comment] 2016-07-22 10:07
IMHO this is intended behaviour. The Exception code can/should be something application-specific (e.g. 4711 - page found, but unpublished), while the status code is one of the  HTTP_* constants.

In the example above, the exception would be logged with the correct exception code, but the user gets the 404 error page.

**Comment by xabbuh** [comment] 2016-07-22 13:24
@xelan is right. Thus I am closing here.

**Closed by xabbuh** 2016-07-22 13:24 UTC
