### ISSUE TITLE
MongoDbSessionHandler doesn't set the sessionName needed by the AbstractSessionHandler

### ISSUE THREAD

**Issue by arthurkirkosa** [symfony/symfony#25479] opened 2017-12-13 07:51 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.4, 4.0

https://github.com/symfony/http-foundation/commit/55ca8d885e7e0790a24ad8b2c9253bdb68035e89#diff-846e1ea5ef360822097501b7ca01cdeaR132

This causes an error LogicException with message ’Session name cannot be empty, did you forget to call “parent::open()” in “Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler” because MongoDbSessionHandler doesn’t set the `sessionName`

**Comment by nicolas-grekas** [comment] 2017-12-13 20:21
This can only happen if the "open" method is not called, which looks suspicious. Can you investige why it isn't?
If you can provide a reproducer, we could also have a look.

**Comment by nicolas-grekas** [comment] 2017-12-13 21:07
Actually the discussion is pretty advanced on the same topic in #25445. Closing as duplicate. Please come to this other issue if you want to participate. From what it looks like to me for now, it's a bug on the caller side.

**Closed by nicolas-grekas** 2017-12-13 21:07 UTC
Labels: Bug, HttpFoundation, Status: Needs Review
