### ISSUE TITLE
[Serializer] Denormalization of object implementing \Iterator fails

### ISSUE THREAD

**Issue by mvar** [symfony/symfony#40331] opened 2021-02-28 12:51 UTC
**Symfony version(s) affected**: 5.2.3

**Description**
Deserialization breaks when class implements `\Iterator`.

**How to reproduce**
```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class OrderLineCollection implements \Iterator
{
    private array $collection;

    public function __construct(array $orderLines)
    {
        $this->collection = $orderLines;
    }

    public function getOrderLines(): array
    {
        return $this->collection;
    }

    public function current()
    {
        return current($this->collection);
    }

    public function next()
    {
        next($this->collection);
    }

    public function key()
    {
        return key($this->collection);
    }

    public function valid()
    {
        return $this->key() !== null;
    }

    public function rewind()
    {
        reset($this->collection);
    }
}

class Order
{
    private OrderLineCollection $orderLines;

    public function __construct(OrderLineCollection $orderLines)
    {
        $this->orderLines = $orderLines;
    }

    public function getOrderLines(): OrderLineCollection
    {
        return $this->orderLines;
    }
}

$serializer = new Serializer([new ObjectNormalizer()], [new JsonEncoder()]);
$order = new Order(new OrderLineCollection(['A', 'B']));
$serializedOrder = $serializer->serialize($order, 'json');
echo $serializedOrder . PHP_EOL;
$deserializedOrder = $serializer->deserialize($serializedOrder, Order::class, 'json');
$serializedOrder = $serializer->serialize($deserializedOrder, 'json');
echo $serializedOrder . PHP_EOL;
```

Output:

```
{"orderLines":["A","B"]}
PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: Cannot create an instance of "OrderLineCollection" from serialized data because its constructor requires parameter "orderLines" to be present. in /home/project/src/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:394
```

Removing `implements \Iterator` part results with this output:

```
{"orderLines":{"orderLines":["A","B"]}}
{"orderLines":{"orderLines":["A","B"]}}
```

**Comment by xabbuh** [comment] 2021-03-12 08:25
Looking at it in more detail I think that the issue is not related to the denormalization step but comes from the fact that the serialized string looks different.

**Comment by xabbuh** [comment] 2021-03-12 08:38
And this due to the fact that the `ObjectNormalizer` does not support `Traversable` instances (the `ObjectNormalizer` extends the `AbstractObjectNormalizer`): https://github.com/symfony/symfony/blob/e16bbdc1a02033e0e3ac060224953aee90570776/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L128-L131

**Comment by xabbuh** [comment] 2021-03-12 13:23
closing here as this does not seem to be a bug as explained above

**Closed as completed by xabbuh** 2021-03-12 13:23 UTC
Labels: Serializer, Bug, Status: Needs Review
