### ISSUE TITLE
Symfony 4 : Response head auto add private and max-age=0.  How to fix it ?  

### ISSUE THREAD

**Issue by askuiop** [symfony/symfony#25826] opened 2018-01-18 03:29 UTC
Not all the page use session .  so this function is not necessary !

**Comment by nicolas-grekas** [comment] 2018-01-18 06:15
As soon as the session is used once anywhere to generate a response, it becomes non cache able.
You should debug to find where the session is used and figure out a way to not use the session if you want a different Cache-Control.

**Comment by pixeltreiber** [comment] 2018-01-18 21:31
I did some debugging on the same problem today with symfony 3.4.3 to find out where my session is started. I found that the session is always added to the request by the AbstractSessionListener See https://github.com/symfony/symfony/blob/1df45e43563a37633b50d4a36478090361a0b9de/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L28

In RequestDataCollector::onKernelResponse then the session is always used to find out if the request is a redirect. https://github.com/symfony/symfony/blob/v3.4.0/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L319

So I think in my app I can never have a request without an active session.

There is a fix for this in a commit from 10 days ago on the symfony 4 branch. https://github.com/symfony/symfony/commit/83f257943fb25bf9cf9698d816cf916a4d9ee438
But I guess in your version this is still broken.

**Comment by nicolas-grekas** [comment] 2018-01-18 22:07
@pixeltreiber your correct, this issue in `RequestDataCollector` is fixed and will be part of the next release, due in 2 weeks now (monthly releases.)
I'm closing here, as we the issue is fixed in the code and doesn't need tracking anymore.

**Closed by nicolas-grekas** 2018-01-18 22:07 UTC
Labels: HttpFoundation

**Comment by erichard** [comment] 2018-02-15 15:51
@nicolas-grekas @fabpot It could be considered as a BC break.

Before Symfony 3.4, my projects has HTTP caching even with a started session and now it doesn't. To fix the problem I have to do a big amount of work:

- Change firewall pattern as I used '/' with anonymous
- Fix many kernel listeners that use the session (by converting them to lazy loaded services)

I understand this change but it should be postponed in 4.0 IMO

**Comment by alterphp** [comment] 2018-02-15 15:58
Why not sending a deprecation notice in Sf 3.4 instead of adding private cache header ?

**Comment by florianajir** [comment] 2018-08-24 14:43
@nicolas-grekas So how can I use http cache for my API listings protected by oauth token ?
