### ISSUE TITLE
[Console] Activate the profiler in the commands

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#21141] opened 2017-01-02 18:44 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | last

Would it be interesting to be able to activate the profiler in the commands? Maybe something like this:

```cli
$ php bin/console app:do:something --enable-profiler

// do something 

Profiler token: http://localhost:8000/_profiler/b50ac4
```

**Comment by stof** [comment] 2017-01-02 18:47
The issue is that the Profiler is tied to profile a Request currently, and there is no Request in the CLI (unless you do CLI over HTTP of course).
So this would require a full rewrite of the profiler first, to decouple it from HttpFoundation

**Comment by fabpot** [comment] 2017-01-02 19:50
@stof is write when he says that the profiler is tied with HTTP requests. Rewriting the profiler would not help as anyway most panels needs a request. So, I'm closing this one as it would mean developing a new profiler for CLI applications.

**Closed by fabpot** 2017-01-02 19:50 UTC

**Comment by kaznovac** [comment] 2021-02-24 21:58
hi @fabian, i think this would be a great addition to the symfony dx (i.e. profiled http-client requests and doctrine queries issued by a command would be of immense help in a development process)

any chance you've changed your stance on this? as per comment: https://github.com/symfony/symfony/issues/39114#issuecomment-730145717

these issues seem related:
- https://github.com/symfony/symfony/issues/32422
- https://github.com/symfony/symfony/issues/39114
- https://github.com/symfony/symfony/issues/30089

thanks

**Comment by adrienbrault** [comment] 2021-06-08 15:13
Hi,

The profiler and web toolbar are really valuable tools, but the lack of cli/command/messenger support makes debugging much harder in some scenarios. For example debugging failing functional tests (running through a cli tool/command like behat or phpunit) is quite complicated.

I have created 2 bundles that help bring the profiler/toolbar experience to the terminal:
- https://github.com/sourceability/console-toolbar-bundle
  - The code to render the toolbar in the terminal using twig/DomCrawler: https://github.com/sourceability/console-toolbar-bundle/blob/39ee27aa14ec93710d0f1cecd12d72f961a23a21/src/Console/ProfilerToolbarRenderer.php
- https://github.com/sourceability/instrumentation-bundle
  - The relevant (hacky) code that works around the profiler/http coupling: https://github.com/sourceability/instrumentation-bundle/blob/a877f6cb527c88d9d2121c87a202c104f35f3531/src/Profiler/SymfonyProfiler.php

Native support would be really nice :)

![](https://user-images.githubusercontent.com/611271/118683608-cf759600-b801-11eb-98b5-715df3d26452.png)

**Comment by kaznovac** [comment] 2021-06-08 16:42
@adrienbrault  amazing work, thanks for sharing
