### ISSUE TITLE
[EventDispatcher] Subscribe to events by regular expression

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#20939] opened 2016-12-15 16:49 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

Currently an event subscriber can only subscribe to a list of predefined events. This makes scenarios like subscribe to all console events or all events alltogether possible only by decorating or overriding **event_dispatcher**.

What do you think about adding the possibility to subscribe based on a regex of the event name?

As a second option, we can also leave such a logic in userland and allow an AllEventsSubscriber so users can do whatever filtering they need.

**Comment by iltar** [comment] 2016-12-15 16:51
What if someone adds an event with a very similar name that's incompatible because it has a different event object?

**Comment by skafandri** [comment] 2016-12-15 16:54
I think if you subscribe to ALL events (or regex) you should be expecting an `Event` object. If you expect a particular event class you will most probably subscribe to a particular event name.

**Comment by iltar** [comment] 2016-12-15 16:57
So you have a regex (as example) that accepts everything that starts with `foo_bar.baz.`, now some other bundle glues in a `foo)bar.baz.foo` event, and everything will break.

**Comment by skafandri** [comment] 2016-12-15 17:10
My regex subscriber won't get called for the newly introduced event.
Can you explain how it would break?

**Comment by stof** [comment] 2016-12-15 17:12
there is https://github.com/jmikola/WildcardEventDispatcher and https://github.com/jmikola/JmikolaWildcardEventDispatcherBundle created by @jmikola to achieve such feature (not supporting full regexes though)

**Comment by skafandri** [comment] 2016-12-15 17:21
Both bundles operate by decorating the event_dispatcher, which is the only way I found to achieve the same functionality as I mentioned before. I think that the feature is not worth a separate bundle (or even decorating event_dispatcher IMO). This is why I thaught it would fit well in the EventDispatcher component.

I see it as an extension to the *subscribe me to those events* feature, only with a more flexible interface.
What do you think?

**Comment by skafandri** [comment] 2016-12-15 17:26
I just came across https://github.com/symfony/symfony/issues/7981 :)
I still think it would fit in EventDispatcher. As a side note, I had to decorate event_dispatcher in almost every application I worked on. That's why it seemed as a *missing feature*

**Comment by stof** [comment] 2016-12-15 17:26
@skafandri the issue is that events are **not** known at subscription time. You can dispatch any event. So there is no way to build a list of event names matching the regex at subscription time.

And doing this through composition is a much better idea than adding new features in the core implementation. It is much more flexible. Btw, even the profiler integration is done by composition in the core.
thus, adding such feature in the component itself would mean we would have to support it, increasing our maintenance work. As it is already possible to achieve it externally (and already done), I don't see the point of adding this in the core.

**Comment by skafandri** [comment] 2016-12-15 17:31
@stof I fully understand the implications of such feature, especially on performance. As the *new subscriber* can be matched only on the fly when an event is dispatched. And is not cacheable. Thus the documentation should warn about those implications, but then I think is up to the users.

**Comment by skafandri** [comment] 2016-12-15 17:34
What about only the **all events** feature? No regexes or whatsoever. Just the possibility to add a subscriber to all events?

**Comment by stof** [comment] 2016-12-15 17:36
even for all events, it is still a pain, because of listeners priority. You still have to insert it in the list of listeners for each event, which is not that different from handling only a subset of events

**Comment by skafandri** [comment] 2016-12-15 17:40
I have another idea, what about making EventDispatcher dispatch a *pre_dispatch* or/and *post_dispatch* event?

**Comment by stof** [comment] 2016-12-15 17:42
well, this is very easily achieved through composition (even easier than regex subscription), so I don't see the reason to force it in the core.

Btw, I never had a need to register to all events in the past (except for things like logging, which are best achieved by decorating the dispatcher as done in TraceableEventDispatcher rather than dispatching another event)

**Comment by skafandri** [comment] 2016-12-15 18:13
I never had to register to all events neither. But the following code (or a variant of it) was present in `dispatch` method every time I decorated event_dispatcher

````
if ($event instanceof SomeEventClass:class) {
  //do something with this event
}
````
Decorating the event_dispatcher is not a significant overhead, the only motivation behind this proposal is that it became a *recurrent* use case that I see in many application. That's why I thought about pushing the feature down to the component.

**Comment by stof** [comment] 2016-12-15 18:20
If your logic is based on the event class, I don't see anything in the current discussion about it, as it is all about event names

**Comment by skafandri** [comment] 2016-12-15 18:24
The most important part is subscribing to ALL events. A subset of events by name could be a *nice to have* feature, thus dismissable. But the *catch all* feature could be usefull for many use cases.

**Comment by nicolas-grekas** [comment] 2017-04-11 11:10
I suggest to close this one and open a new one for the catch all use case, which is different and more likely to fit the current design of the EventDispatcher class.

**Closed** 2017-04-14 11:15 UTC
Labels: EventDispatcher, Feature
