### ISSUE TITLE
[DI] Doctrine repositories autowire issue

### ISSUE THREAD

**Issue by jkabat** [symfony/symfony#29810] opened 2019-01-07 15:27 UTC
**Symfony version(s) affected**: 4.1.10, maybe others

**Description**  
Recent upgrade from v4.1.7 to v4.1.10 causes issue with autowiring of custom doctrine repositories created using code explained at https://symfony.com/doc/4.1/doctrine.html#querying-for-objects-the-repository

Exception thrown:
` Argument 1 passed to App\Repository\CouponRepository::__construct() must implement interface Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\ORM\EntityManager given, called in vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 68
`

**How to reproduce**  
Application repository __construct() arguments are ignored and EntityManager is forcibly injected for all repository services.

```php
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Class CouponRepository
 * @package App\Repository
 */
class CouponRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Coupon::class);
    }
```

```php
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * Class AbstractRepository
 * @package App\Repository\Common
 */
abstract class AbstractRepository extends ServiceEntityRepository
{
```

This is happening even if I manually wire repository with ManagerRegistry service as argument.

**Possible Solution**  
I did not find any solution yet, also haven't figure out which PR caused this behavior - maybe somebody else will have time to investigate. I had to downgrade symfony/dependency-injection package to the previously working one (v4.1.8).

**Comment by jkabat** [comment] 2019-01-07 16:09
After further investigation seems that issue lies in commits between v4.1.8 and v4.1.9 on file
https://github.com/symfony/dependency-injection/blob/v4.1.9/Compiler/InlineServiceDefinitionsPass.php

**Comment by stof** [comment] 2019-01-07 16:37
If it happens in DefaultRepositoryFactory, it looks like this means that your repository defined as a service is not used at all.

which version of DoctrineBundle are you using (in the working and non-working cases) ?

**Comment by jkabat** [comment] 2019-01-07 16:57
In both cases I'm using latest one (upgraded in last composer update):
doctrine/doctrine-bundle (1.9.1 => 1.10.0)

I just downgraded dependency-injection package to make it work again using
```json
 "symfony/dependency-injection": "4.1.8", 
```

**Comment by xabbuh** [comment] 2019-01-07 17:00
Can you create a small example application that would allow to reproduce the issue?

**Comment by jkabat** [comment] 2019-01-07 17:18
@stof, sometimes Im getting repository this way:

```php
$this->cr = $this->em->getRepository(Coupon::class); 
```

Is it forbidden when I have defined them as services?

**Comment by jkabat** [comment] 2019-01-08 07:55
@xabbuh - Ill do that as soon as Ill get some spare time.

Downgrading of dependency-injection does not work for TEST environment. There it is failing for param converter as well... (while it is running fine on DEV).

`1) App\Tests\Cart\Controller\DefaultControllerTest::testCartInteraction
TypeError: Argument 1 passed to App\Order\Repository\OrderRepository::__construct() must implement interface Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\ORM\EntityManager given, called in /vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 68

/src/Order/Repository/OrderRepository.php:23
/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php:68
/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php:50
/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:713
/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php:142
/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php:91
/vendor/sensio/framework-extra-bundle/Request/ParamConverter/ParamConverterManager.php:92
/vendor/sensio/framework-extra-bundle/Request/ParamConverter/ParamConverterManager.php:48
/vendor/sensio/framework-extra-bundle/EventListener/ParamConverterListener.php:78
/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:111
/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:145
/vendor/symfony/http-kernel/HttpKernel.php:137
/vendor/symfony/http-kernel/HttpKernel.php:66
/vendor/symfony/http-kernel/Kernel.php:188
/vendor/symfony/http-kernel/Client.php:68
/vendor/symfony/framework-bundle/Client.php:131
/vendor/symfony/browser-kit/Client.php:357
/vendor/symfony/browser-kit/Client.php:567
/tests/Cart/Controller/DefaultControllerTest.php:188
/tests/Cart/Controller/DefaultControllerTest.php:121`

**Comment by konshensx16** [comment] 2019-01-08 17:39
I'm facing the same issue after updating from 4.1.6 to 4.1.10, any news about this so far or should we just downgrade for now ? 
Thank you  in advance :)

**Comment by xabbuh** [comment] 2019-01-08 18:23
An example application that allows to reproduce the issue would still help much.

**Comment by jkabat** [comment] 2019-01-14 19:36
I was not able to reproduce problem on brand new installation. However when I started to whitelist packages in affected application, issue reoccurred after enabling MsgPHP package. I'm not sure it is MsgPHP or Symfony's messenger component responsible and I will continue research tomorrow (hopefully).

@ro0NL didn't you notice some strange behavior?

Issue happens when manager getRepository method is called (eg: dashboard is using 10+ repositories, so I didn't want to inject them all).

**Comment by tacman** [comment] 2019-01-14 22:20
Is anyone else having trouble with a custom, auto-wiring paramConverter?
That is, following the instructions here:

https://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter

They broke for me when I upgraded, I can try to put together a sample site
demonstrating this if it'll help.

Tac

**Comment by xabbuh** [comment] 2019-01-14 23:08
That would indeed help to reproduce and debug the issue.

**Comment by ro0NL** [comment] 2019-01-15 07:59
> @ro0NL didn't you notice some strange behavior?

@jkabat not really, i can try to  poke it a bit soon. But  it doesnt rely on `ServiceEntityRepository` & co.

 At most i think it's an integration issue with SF/DI, as we have some advanced service registration; that is a default binding the entity manager, and reference it PSR prototype services. Maybe it's breaks inlining now.. a `composer show`/reproducing app would really help.

**Comment by ro0NL** [comment] 2019-01-15 09:03
reproduced, indeed the integration with msgphp starts biting.

We register a [doctrine event listener](https://github.com/msgphp/msgphp/blob/master/src/UserBundle/Resources/config/doctrine.php#L20) with autowires the entity manager, this broke before in #29078 and #28304

if i [always remove](https://github.com/msgphp/msgphp/blob/master/src/UserBundle/DependencyInjection/Extension.php#L138) this definition, it's solved :confused:

**Comment by jkabat** [comment] 2019-01-15 09:32
@ro0NL thank you for debugging, having definition removed all the time fixes the problem and all application tests are working again. I suppose I should move to MsgPHP repository to continue discussion about possible fix.

**Comment by ro0NL** [comment] 2019-01-15 09:34
I think it's a Symfony DI issue :) it worked before on our side as well.

**Comment by ro0NL** [comment] 2019-01-15 09:37
Also adding `composer require symfony/proxy-manager-bridge` solves it, but still.. something broke. 

Basically im not sure wether our case is supported without proxy-manager yes/no. Initially it worked, then it broke, got fixed, broke again, etc. So maybe using the proxy manager, or refactoring the wiring on our side is best long-term.

**Comment by ro0NL** [comment] 2019-01-15 09:57
the issue is *with* doctrine listener we end up in `DefaultRepositoryFactory`, instead of `ContainerRepositoryFactory`.

**Comment by ro0NL** [comment] 2019-01-15 10:01
```
Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass: Removed service "doctrine.orm.container_repository_factory"; reason: unused.
```

**Comment by tacman** [comment] 2019-01-15 14:03
I've reproduced the bug in symfony-demo at
https://github.com/survos/symfony-demo

It's the demo application with a ParamConverter that should be autowired,
according to the instructions at
https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter

I think this used to work, but doesn't with the latest composer update.  In
my application that's definitely true, I tried to replicate the problem
with symfony-demo but am having a hard time figuring out what composer.json
should look like to show it when it was working.  Perhaps I just have a bug
in my ParamConverter or the configuration, but perhaps in the process of
solving this we can figure it out the bug that's discussed  here.


    git clone git@github.com:survos/symfony-demo.git
    cd symfony-demo
    composer install
    bin/console server:start

open http://127.0.0.1:8000/es/blog/

click on the bug link.





[image: image.png]

**Comment by tacman** [comment] 2019-01-15 14:09
I've reproduced the bug in symfony-demo at
https://github.com/survos/symfony-demo

It's the demo application with a ParamConverter that should be autowired,
according to the instructions at
https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter

I think this used to work, but doesn't with the latest composer update.  In
my application that's definitely true, I tried to replicate the problem
with symfony-demo but am having a hard time figuring out what composer.json
should look like to show it when it was working.  Perhaps I just have a bug
in my ParamConverter or the configuration, but perhaps in the process of
solving this we can figure it out the bug that's discussed  here.


    git clone git@github.com:survos/symfony-demo.git
    cd symfony-demo
    composer install
    bin/console server:start

open http://127.0.0.1:8000/en/blog/

click on the bug link, which goes to a controller that uses postSlug instead of slug.

```php
    /**
     * @Route("/bug-posts/{postSlug}", methods={"GET"}, name="blog_post_bug")
     *
     * NOTE: The $post controller argument is automatically injected by Symfony
     * after performing a database query looking for a Post with the 'postSlug'
     * value given in the route.
     *
     * See src/Request/ParamConverter/PostParamConverter.php
     * See https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html
     */
    public function postShowBug(Post $post): Response
```

**Comment by tacman** [comment] 2019-01-15 21:32
The automatic conversion worked in previous versions, though.  It broke
very recently.

Yes, the annotation you mention will work, but the whole idea of a custom
converter was to save the effort of writing that.  I use them all over my
controllers.

I'm trying to find an example of a service that implementments
ParamConverterInterface:

https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter

Here's the article I based mine on:

https://stfalcon.com/en/blog/post/symfony2-custom-paramconverter

Although in the article he explicitly wires the paramConverter.  With
autowiring, anything that implements the ParamConverterInterface is
supposed to get the correct tag.

Again, this used to work, but stopped with a recent update.

Thanks,

Tac

**Comment by xabbuh** [comment] 2019-01-15 21:35
@tacman This has nothing to do with autowiring. I cannot tell you whether or not this used to work in previous versions, but if that's the case, you should rather submit a bug report in the [SensioFrameworkExtraBundle repository](https://github.com/sensiolabs/SensioFrameworkExtraBundle) as that's the bundle that providers the param converter support.

**Comment by tacman** [comment] 2019-01-15 21:59
Curiously, the very last commit to that repo involved ParamConverter:

https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/1fdf591c4b388e62dbb2579de89c1560b33f865d

I'll post my bug report there.

Thanks,

Tac

**Comment by tacman** [comment] 2019-01-15 22:42
I don't think it's in ParamConverter itself, I've reverted the recent
change in my code and am still getting the same error.

So gut feeling is that it has to do with autowiring.  The
ParamConverterClass isn't even being called, which I know is consistent
with what you've said about needing to explicitly call it with an
annotation.  But it's my understanding that it's also supposed to loop
through all ParamConverter classes.

**Comment by MusterOhneWert** [comment] 2019-02-12 13:59
I ran into this error when I transferred some files from one workstation to another. I wasn't aware of different versions of dependency-injection.  The solution by jkabat, donwgrading to version 4.1.8 helped. The source has Version 4.1.7 and the recieving one 4.1.11. I was even unable to catch the exception with try-catch. 

This is the triggering line of code:

`public function getDataByItemId($id){
    try{
              $data = $this->getDoctrine()->getRepository(Item::class)->find($id);
    }catch(\Exception $e){
              return $e->getMessage();
    }
    return $data;
}`

Error message is similar to that one, given by jkabat.

**Comment by stof** [comment] 2019-02-12 16:04
which file did you transfer ?

**Comment by tacman** [comment] 2019-02-12 16:10
FWIW, I've locked my composer.json at

"symfony/dependency-injection":
"4.2.x-dev#e4adc57a48d3fa7f394edfffa9e954086d7740e5",

and that solved the problem for me.

**Comment by MusterOhneWert** [comment] 2019-02-13 07:56
@stof: I transferred the whole src folder. Both systems are dev stations, one is win10 desktop, the other macbook with latest OS. I did this transfer many times before, without problem. Maybe a teammate updated the macbook system and didn't tell me.

**Comment by Tobion** [comment] 2019-06-28 21:52
Can this issue be closed? There is alot discussion but nothing concrete or targeted. In our projects autowired respositories work. So if there is an error it must have to do with other libraries as mentioned, FrameworkExtraBundle or msgphp .

**Comment by fabpot** [comment] 2019-06-29 06:19
Let's close then.

**Closed by fabpot** 2019-06-29 06:19 UTC
Labels: Bug, DependencyInjection, Status: Waiting feedback, Unconfirmed

**Comment by tacman** [comment] 2019-06-29 14:33
I am no longer having the ParamConverter auto-wiring issue, though I'm not
sure which release fixed it.

**Comment by biji** [comment] 2019-11-26 07:36
Tried to upgrade minor from 4.3 to 4.4 using this guide:
https://symfony.com/doc/current/setup/upgrade_minor.html

This issue happen again, please help

**Comment by xabbuh** [comment] 2019-11-26 08:33
@biji Please open a new issue and provide some steps on how to reproduce it.

**Comment by maxhelias** [comment] 2019-11-26 10:16
@biji Follow the guides of the other packages you up, like doctrine 2, i think this will solve your issue ;)

**Comment by TomasVotruba** [comment] 2021-02-03 22:38
I wrote a post about this problem, pros and cons and how to make the code clean:
[How to use Repository with Doctrine as Service in Symfony](https://tomasvotruba.com/blog/2017/10/16/how-to-use-repository-with-doctrine-as-service-in-symfony/)
