### ISSUE TITLE
Annotation does not exist or cannot be loaded after load

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#26083] opened 2018-02-07 19:22 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.4

I think the main issue is with Symfony and not the Doctrine CouchDB Bundle, but I'm happy to be corrected.

If I remove the cache directory, the first load works like a charm. The annotations are loaded and work. Subsequent loads I get the error
`[Semantical Error] The annotation "@Doctrine\ODM\CouchDB\Mapping\Annotations\Document" in class App\Document\Product does not exist, or could not be auto-loaded.  `

In a re-usable bundle, if annotations are used do they need to be specified anywhere in particular so the caching works properly?

I'm a little out of my depth with this one, but I've been trying for quite a while now and have got stuck trying to trace where main problem lies. If I've missed a doc somewhere please do link and I'll happily read through and create a PR on the other bundle.

Thanks

**Comment by silverbackdan** [comment] 2018-02-07 20:52
I'm pretty sure this problem will have to lie within the Doctrine CouchDB Bundle. I'll close this unless I find definitive evidence but even when I try to persist a document on the first load, it gives an error that a detached document was passed to persist.

**Comment by silverbackdan** [comment] 2018-02-07 21:21
OK so I've found out why this is.

1) I was aware but the bundle is a little unloved it seems. It mentioned to register the autoloader but I was thrown by it working the first time.
2) The SF framework bundle has the following XML https://github.com/symfony/symfony/blob/0b1b8959d371d4baf9db9db6f537e59d686f89c2/src/Symfony/Bundle/FrameworkBundle/Resources/config/annotations.xml#L18

On the first load, this is run. On subsequent loads after the page is cached, it is not and therefore causes the error. Is this expected behaviour or should this be removed/implemented so it works consistently?

**Comment by painreign** [comment] 2018-02-24 06:58
what is boot function?

**Comment by silverbackdan** [comment] 2018-02-26 15:12
@painreign the `boot` method in your app's Kernel. You can add the method in.
```php
// src/Kernel.php
<?php

namespace App;

class Kernel extends BaseKernel
{
    ....
    public function boot()
    {
        // Temporary fix hopefully - either doctrine or Symfony should support autoloader.php class loading
        // This is what SF calls on first load
        \Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(
            'class_exists'
        );
        return parent::boot();
    }
    ...
}
```

**Comment by nicolas-grekas** [comment] 2018-02-27 17:47
This means this is expected IMHO: if you're not using the `annotation_reader` service, it's your job to register annotation loading (but you should really use  `annotation_reader` instead, which will call this `registerUniqueLoader` for you.)

**Comment by jakzal** [comment] 2018-03-08 11:42
Closing since as Nicolas pointed out there's nothing to do on our side.

**Closed by jakzal** 2018-03-08 11:42 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review

**Comment by silverbackdan** [comment] 2018-03-08 12:16
Sure, thanks both sorry for the delayed response - I think it's how the bundle is using the annotation_reader service or may be defining it's own incorrectly so I'll take a look there. I'm still curious why the dummy_registry service above runs on the first time but not on subsequent calls and why but I'm sure I can investigate that myself in spare time :)

**Comment by silverbackdan** [comment] 2018-08-22 11:35
Anyone who may stumble across this looking for an answer - best to add a compiler pass in to your Kernel build method (same with Doctrine MongoDB ODM):
```php
class Kernel {
    ...
    protected function build(ContainerBuilder $container)
    {
        $modelDir = realpath(__DIR__.'/CouchDocument');
        $mappings = array(
            $modelDir => 'App\CouchDocument',
        );
        $container->addCompilerPass(
            DoctrineCouchDBMappingsPass::createAnnotationMappingDriver(
                $mappings,
                [$modelDir],
                []
            )
        );
    }
    ...
}
```

**Comment by rufinus** [comment] 2019-03-31 15:04
@nicolas-grekas then there is a problem with the serializer documentation.

Here the AnnotationReader is used directly - and this leads to the exact the same problem described in this issue. see https://symfony.com/doc/current/components/serializer.html#deserializing-an-object

The issue is fixable by either registering in the boot method, or as you hinted injecting the annotation_reader Service.

**Comment by nicolas-grekas** [comment] 2019-03-31 15:24
Would you mind opening a doc issue or PR please?
