### ISSUE TITLE
[Bug] Documentation in Symfony API

### ISSUE THREAD

**Issue by twify93** [symfony/symfony#22201] opened 2017-03-28 11:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| RFC?             | no
| Symfony version  | 3.1 and 3.2

I found that the Symfony API documentation for versions 3.1 and 3.2 shows only 1 method which is the setContainer() and all other methods are missing.

http://api.symfony.com/3.2/Symfony/Bundle/FrameworkBundle/Controller/Controller.html
http://api.symfony.com/3.1/Symfony/Bundle/FrameworkBundle/Controller/Controller.html

But the file actually is full with the other methods [Controller.php in github 3.2 branch](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php)

Regards,
Lachezar Lechev

**Comment by GromNaN** [comment] 2017-03-28 22:12
Same behavior with [3.0](http://api.symfony.com/3.0/Symfony/Bundle/FrameworkBundle/Controller/Controller.html) and [master](http://api.symfony.com/master/Symfony/Bundle/FrameworkBundle/Controller/Controller.html). On [2.8](http://api.symfony.com/2.8/Symfony/Bundle/FrameworkBundle/Controller/Controller.html) and [2.7](http://api.symfony.com/2.7/Symfony/Bundle/FrameworkBundle/Controller/Controller.html), all methods were listed.

It looks like this is due to the switch from public to protected methods (#12457).

**Comment by javiereguiluz** [comment] 2017-03-29 09:21
@twify93 thanks for reporting this issue. As explained by @GromNaN, the issue is related to the change from public to protected methods.

I'm closing this as a duplicate of https://github.com/symfony/symfony-docs/issues/7138 and hopefully we can solve it soon. Thanks!

**Closed by javiereguiluz** 2017-03-29 09:21 UTC
