### ISSUE TITLE
ChoiceType Field fails validation if unknown value is submitted

### ISSUE THREAD

**Issue by latvianization** [symfony/symfony#40505] opened 2021-03-18 07:43 UTC
**Symfony version(s) affected**: 5.2.6
**Symfony/Form version(s) affected**: 4.4.20

**Description**
Define ChoiceType field in form. Add option multiple = true and empty set of choices. Values are added on front (get data from remote API and add as values). When user submits form it is invalid with error: The value array is not valid

**How to reproduce**
```
     $builder->add('recipients', ChoiceType::class, [
                'label' => _('Recipients'),
                'multiple' => true,
                'choices'  => [],
                'required' => false
            ]);
```

**Possible Solution**

In ChoiceField options add option which allows to avoid unknownValue check. Example: knownValues (true/false) or strict (true/false)

**Additional context**

**Comment by maxhelias** [comment] 2021-03-18 08:11
same problem as this issue https://github.com/symfony/symfony/issues/40483

**Comment by Spounespoune** [comment] 2021-03-18 08:55
Hello, 

@latvianization do you have time to create a small example application that allows to reproduce your issue?
(I would have time tomorrow)

**Comment by xabbuh** [comment] 2021-03-18 09:15
closing as a duplicate of #40483

**Closed as completed by xabbuh** 2021-03-18 09:15 UTC
Labels: Form, Bug, Status: Needs Review
