### ISSUE TITLE
[2.7] WebProfilerBundle - Fullscreened toolbar

### ISSUE THREAD

**Issue by TisRyno** [symfony/symfony#16732] opened 2015-11-28 18:40 UTC
Hey there,

I recently updated to Symfony 2.7 from 2.6 without any issues except this one relating to the Web Profiler toolbar.
This specifically relates to an administration panel section of the website I am creating, if I view the public facing side of the website the toolbar loads exactly as it should, but on the administration panel it loads and is immediately fullscreen making it impossible to see/do anything. I have tried using Chrome inspector to find out what part of the CSS is breaking it but to no avail.

I have attached a screenshot to show the issue I am having.

![screen shot 2015-11-28 at 18 34 03](https://cloud.githubusercontent.com/assets/1848188/11453331/b221d918-95fe-11e5-84c5-4057b89e87ef.png)

**Comment by TisRyno** [comment] 2015-11-28 18:50
I feel a little bit silly now but I have actually tracked down the issue causing this.

Within my CSS for the administration panel I had a specific rule for SVG due to it's use throughout graphs and other graphics.

By applying the 3 below rules to SVG causes the shown error
```css
    display: block;
    width: 100%;
    height: 100%;
```

**Comment by javiereguiluz** [comment] 2015-11-28 19:13
@TisRyno yes, the problem is that apparently you are applying those custom CSS styles to all SVG images. You should use a more specific selector to avoid these issues.

**Comment by jakzal** [comment] 2015-11-28 19:42
Closing, as it's a user

**Closed by jakzal** 2015-11-28 19:42 UTC
