### ISSUE TITLE
Symfony 3.2 isValid always return false

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#20805] opened 2016-12-07 09:27 UTC
the following code worked within symfony 2.8 (patch action), after updating to symfony 3.2 i always get into the if statement, even if there are no errors. calling the validator myself, would tell everything is fine.

```{.php}
$form = $this->createForm(UserType::USER_UPDATE, $user);
$form->submit($request->request->all(), false);
if (false === $form->isValid()) {
    ....
}
```

Do i missed a change, that does not throw an exception, but ends in this strange behavior?

I already refactored the createForm to:

```{.php}
$form = $this->createForm(UserUpdateType::class, $user);
```

**Comment by HeahDude** [comment] 2016-12-07 09:48
Hi @dominikzogg, you should read the [3.2 upgrade file](https://github.com/symfony/symfony/blob/master/UPGRADE-3.2.md#form) and call:
```php
if ($form->isSubmitted() && false === $form->isValid()) {
    ....
}
```

Does it solve your issue?

**Comment by dominikzogg** [comment] 2016-12-07 09:55
@HeahDude no it does not, i saw within sample, but as you can see within submit() $this->submitted = true; will always be set

**Comment by dominikzogg** [comment] 2016-12-07 09:57
```{.php}
$form->submit($request->request->all(), false);

$violationList = $this->get('validator')->validate($user);
if (0 !== $violationList->count()) {...}
```

doing it this way works perfect, which tells me validation works

**Comment by HeahDude** [comment] 2016-12-07 10:04
Hmm, looks weird. Could you please fork symphony standard and add at the minimum of code to reproduce this? Thanks!

**Comment by Hanmac** [comment] 2016-12-07 13:16
you shouldn't use submit, which seems to be the problem.

this is how i do it on my systems:
```php
    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {

     }
```

use this to get the Request:
```php
public function myAction(Request $request) {
}
```

**Comment by dominikzogg** [comment] 2016-12-16 09:09
@Hanmac handleRequest is bad for api, cause the missing second argument which allows to ignore not send values

**Comment by dominikzogg** [comment] 2016-12-16 09:11
@HeahDude i can live with duplicate validation for the moment, can't spend the time to strip down this project (big, closed source onces).

**Comment by HeahDude** [comment] 2016-12-17 15:25
@dominikzogg can you please try the patch from https://github.com/symfony/symfony/pull/20966, to see if this about a transformation failure?

Another possibility is that using `false` as second argument cause some field(s) to not be submitted while the user pre set data passed at form's creation contains invalid data. See https://github.com/symfony/symfony/issues/11493 and https://github.com/symfony/symfony/pull/18935.

**Comment by dominikzogg** [comment] 2016-12-20 12:01
@HeahDude #20996 is a patch for sf2.7, adapting it does not change anything in my usecase. the problem only happen on POST, PATCH (with second parameter) works.

**Comment by xabbuh** [comment] 2016-12-31 16:48
@dominikzogg I am closing here for now as we cannot solve the issue without a reproducable example. However, I will happily reopen once we have such a fork of the Symfony Standard Edition.

**Closed by xabbuh** 2016-12-31 16:48 UTC
Labels: Form, Unconfirmed

**Comment by xabbuh** [comment] 2019-02-15 20:08
Can you confirm that the changes proposed in #30265 will fix this issue?
