### ISSUE TITLE
Since Symfony 4.2 php syntax errors are not shown, "Expected to find class..." instead

### ISSUE THREAD

**Issue by samuelvi** [symfony/symfony#35681] opened 2020-02-12 10:34 UTC
Hi,

Since Symfony 4.2 when a syntax error happens, this is not shown anymore, instead "Expected to find class..." is displayed.

I tested this behaviour creating an empty project for different Symfony versions and I realized that this happens since SF 4.2. In SF4.1 the right error is displayed.

It makes an error a bit difficult to fix if no deeper info about the error is displayed :)

I hope you can give me a hand on this, thanks a lot!

**Comment by linaori** [comment] 2020-02-12 14:00
Sounds like this: https://github.com/symfony/symfony/issues/35256

Should be fixed in the next releases of 3.4, 4.4 and 5.0 I think.

**Comment by samuelvi** [comment] 2020-02-12 14:20
Tried this morning from a new SF 4.4.4. and SF 5.0.4 project, creating a dummy class with a syntax error and insteaf of getting the syntax error message the error page always shows "Expected to find class...".

It has nothing to do with wrong namesces neither duplicated services.

Thanks!

**Comment by linaori** [comment] 2020-02-12 14:28
> Tried this morning from a new SF 4.4.4. and SF 5.0.4 project, creating a dummy class with a syntax error and insteaf of getting the syntax error message the error page always shows "Expected to find class...".

As I said, the fix is not released yet, see: https://github.com/symfony/symfony/pull/35557. You can try this locally to see if this fixes the error you're experiencing.

> It has nothing to do with wrong namesces neither duplicated services.

The issue I linked is a symptom, not the cause. The cause is most likely the same as in my issue.

**Comment by xabbuh** [comment] 2020-02-12 16:47
closing as explained by @linaori

**Closed by xabbuh** 2020-02-12 16:47 UTC
