### ISSUE TITLE
Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed

### ISSUE THREAD

**Issue by PlamenVasilev** [symfony/symfony#19572] opened 2016-08-09 09:28 UTC
I'm trying to write white unit test to test my API with file uploads.

I'm following the [docs about this ](http://symfony.com/doc/2.8/testing.html#working-with-the-test-client) using basic client request, not crawler.

The unit test is:

```php
class RecordsControllerTest extends WebTestCase {

private $client;

public function __construct() {
    parent::__construct();
    $this->client = self::createClient();
    $this->client->insulate();
}

public function testApiPostUpload($params){
    $fileToUpload = realpath(__DIR__.'/../../resources/mpthreetest.mp3');
    $file = new UploadedFile(
        $fileToUpload,
        'mpthreetest.mp3',
        MimeTypeGuesser::getInstance()->guess($fileToUpload),
        filesize($fileToUpload)
    );
    $this->client->request('POST', '/records/'.$params['createdRecordId'].'/upload', array(), array('file' => $file) );

    $this->assertEquals(200, $this->client->getResponse()->getStatusCode());
}
}
```

When I execute the test I receive an error:

```
Exception: Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed

/path/to/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:165
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:348
/path/to/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:143
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:313
/path/to/project/src/Bundle/Tests/Functional/Controller/RecordsControllerTest.php:182
```

Posting files is not working as it is described in the docs.

Any ideas?

**Comment by PlamenVasilev** [comment] 2016-08-09 09:49
I have found the solution : 

adding 

> $this->client->insulate(false);

fixed the problem, but why it is not working in insulated mode ?
Is this a bug?

**Comment by ProPheT777** [comment] 2016-08-12 20:57
I think it's because the UploadFile class contains a stream for the file, and you can't serialize an object containing a stream. So it's not a bug but a limitation due to php.

**Comment by javiereguiluz** [comment] 2017-07-17 09:13
Although we can't fix this because of the PHP limitation explained by @ProPheT777, we've improved the docs to explain this: https://github.com/symfony/symfony-docs/pull/8180. Closing it as fixed then. Thanks!

**Closed by javiereguiluz** 2017-07-17 09:13 UTC

**Comment by Mopster** [comment] 2018-12-06 04:51
For anyone else encountering this, I was able to resolve it by setting the `changeHistory` parameter to false (7th and last parameter in the request method signature): 

`$crawler = $client->request($form->getMethod(), $form->getUri(), $values, $files, [], null, false);`

This will prevent the serialize on following lines :

```
if ($this->followRedirects && $this->redirect) {
            $this->redirects[serialize($this->history->current())] = true;

            return $this->crawler = $this->followRedirect();
}
        ```
