### ISSUE TITLE
Invalid auto-redirection when using route mount

### ISSUE THREAD

**Issue by kgkg** [symfony/symfony#29577] opened 2018-12-11 19:15 UTC
Let's say I have andpoint GET https://example.com/foo

When I use:
$app->match('/foo', function...) 
-> OK, it doesn't redirect to https://example.com/foo/

BUT when I use:
$app->mount('/foo', new SomeRouteController());
and then in route controller:
$controllers->get('/', function...)
OR 
$controllers->get('', function...)

it automatically redirects to https://example.com/foo/ (with trailing slash).

It's very annoying. It makes run my middleware twice without need and generating redundant requests.
Can you fix it or provide a way to disable this new redirects at all?

**Comment by xabbuh** [comment] 2018-12-12 10:14
Duplicate of #29011?

**Comment by kgkg** [comment] 2018-12-12 10:38
User in https://github.com/symfony/symfony/issues/29011 complains about auto-redirect as a whole. 

What I'm reporting here is most probably a bug in routing: it should not auto-redirect to https://example.com/foo/ if https://example.com/foo exists. And it's working this way with ->match() but not working this way when using ->mount() with route controllers. Any particullar reason?

**Comment by xabbuh** [comment] 2018-12-12 10:50
What are these `$app->mount()` and `$controllers->get()` calls actually referring too? Are they part of your application? What is their implementation (i.e. to what calls to the framework do they actually resolve to)?

**Comment by stof** [comment] 2018-12-12 11:24
I suspect this is Silex.

**Comment by kgkg** [comment] 2018-12-12 11:36
Yeah it's Silex, but it uses dependencies from SF4 and I'm pretty sure this bug was introduces with one of last routing update. I guess if it's not breaking anything with SF4 itself no one will debug it :/

**Closed** 2018-12-24 10:57 UTC
Labels: Bug, Routing, Status: Needs Review, Unconfirmed
