### ISSUE TITLE
[3.1] Assetic dump in prod dumps profiler_dump function

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#19039] opened 2016-06-13 10:18 UTC
I recently upgraded my app from 3.0.6 to 3.1, and I'm now getting this error during the deploy:

```
Dumping all prod assets.
Debug mode is off.

[2016-06-13 11:08:51] assetic.ERROR: The template "SecurityBundle:Collector:security.html.twig" contains an error: Unknown "profiler_dump" function in "SecurityBundle:Collector:security.html.twig" at line 180.  
11:08:51 [dir+] /var/www/project/app/../web/assetic
11:08:51 [file+] /var/www/project/app/../web/assetic/css_webpanel_base.css
11:08:51 [file+] /var/www/project/app/../web/assetic/js_webpanel_base.js
11:08:51 [dir+] /var/www/project/app/../web/css
11:08:51 [file+] /var/www/project/app/../web/css/af1fae0.css
11:08:51 [dir+] /var/www/project/app/../web/js
11:08:51 [file+] /var/www/project/app/../web/js/2ffa6ba.js
```

I don't know were to start to debug this, it popped up just doing a composer update to update Symfony. I'm using a Symfony standard installation.

**Comment by HeahDude** [comment] 2016-06-13 10:23
It's weird. If debug is off, collectors templates should not be loaded. Do you somehow use the debug toolbar in prod?

**Comment by Jean85** [comment] 2016-06-13 10:27
I do not, but maybe I have something weird in my config... I'll double-check it

**Comment by 0xTryCatch** [comment] 2016-06-14 08:20
Same error here after upgrade to Symfony 3.1

**Comment by Jean85** [comment] 2016-06-14 10:31
I do not get that error on the clear cache command, but I do that AFTER the assetic dump in my deploy...

**Comment by 0xTryCatch** [comment] 2016-06-14 11:02
The clear cache also does a cache warmup and that is where this error is happening for me.

**Comment by HeahDude** [comment] 2016-06-15 09:30
I can't reproduce it, could you please show what `composer show` prints for you?

**Comment by 0xTryCatch** [comment] 2016-06-15 10:32
Here you go:

```
doctrine/annotations                  v1.2.7               Docblock Annotations Parser
doctrine/cache                        v1.6.0               Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.3.0               Collections Abstraction library
doctrine/common                       v2.6.1               Common Library for Doctrine projects
doctrine/inflector                    v1.1.0               Common String Manipulations with regard to casing and singular/plural rules.
doctrine/lexer                        v1.0.1               Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
dropbox/dropbox-sdk                   v1.1.6               Dropbox SDK for PHP
firebase/php-jwt                      v3.0.0               A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
google/apiclient                      v2.0.0               Client library for Google APIs
google/apiclient-services             v0.3                 Client library for Google APIs
google/auth                           v0.8                 Google Auth Library for PHP
guzzlehttp/guzzle                     6.2.0                Guzzle is a PHP HTTP client library
guzzlehttp/promises                   1.2.0                Guzzle promises library
guzzlehttp/psr7                       1.2.3                PSR-7 message implementation
instaclick/symfony2-coding-standard   dev-remaster 180a19d Symfony coding standard for PHP_CodeSniffer
kriswallsmith/assetic                 v1.3.2               Asset Management for PHP
monolog/monolog                       1.19.0               Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat               v2.0.2               PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phing/phing                           2.14.0               PHing Is Not GNU make; it's a PHP project build system or build tool based on Apache Ant.
phpseclib/phpseclib                   2.0.2                PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
psr/cache                             1.0.0                Common interface for caching libraries
psr/http-message                      1.0                  Common interface for HTTP messages
psr/log                               1.0.0                Common interface for logging libraries
react/promise                         v2.4.1               A lightweight implementation of CommonJS Promises/A for PHP
squizlabs/php_codesniffer             1.5.6                PHP_CodeSniffer tokenises PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
swiftmailer/swiftmailer               v5.4.2               Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle                v2.8.0               Integrates Assetic into Symfony2
symfony/monolog-bundle                2.11.1               Symfony MonologBundle
symfony/polyfill-intl-icu             v1.2.0               Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring             v1.2.0               Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.2.0               Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                v1.2.0               Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                 v1.2.0               Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle            v2.3.11              Symfony SwiftmailerBundle
symfony/symfony                       v3.1.0               The Symfony PHP framework
twig/twig                             v1.24.1              Twig, the flexible, fast, and secure template language for PHP
```

**Comment by 0xTryCatch** [comment] 2016-06-15 15:00
And here is the stack trace executing ```bin/console cache:clear```

```
Monolog\Logger->error() in /Users/trycatch/project/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php on line 41
Assetic\Extension\Twig\TwigFormulaLoader->load() in /Users/trycatch/project/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php on line 59
Assetic\Factory\Loader\CachedFormulaLoader->load() in /Users/trycatch/project/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php on line 160
Assetic\Factory\LazyAssetManager->load() in /Users/trycatch/project/vendor/symfony/assetic-bundle/CacheWarmer/AssetManagerCacheWarmer.php on line 34
Symfony\Bundle\AsseticBundle\CacheWarmer\AssetManagerCacheWarmer->warmUp() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php on line 48
Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 144
Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 96
Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php on line 256
Symfony\Component\Console\Command\Command->run() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php on line 831
Symfony\Component\Console\Application->doRunCommand() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php on line 186
Symfony\Component\Console\Application->doRun() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php on line 80
Symfony\Bundle\FrameworkBundle\Console\Application->doRun() in /Users/trycatch/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php on line 117
Symfony\Component\Console\Application->run() in /Users/trycatch/project/bin/console on line 27
 ```

**Comment by stof** [comment] 2016-06-15 15:32
See https://github.com/symfony/symfony-standard/issues/982

**Comment by HeahDude** [comment] 2016-06-15 15:36
@stof maybe we could load `collectors.xml` only when debug is true like done for `security_debug.xml` (ref https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L66-L70)

**Comment by 0xTryCatch** [comment] 2016-06-15 17:05
@stof Thanks! Exactly my problem: all bundles are added by default. I resolved it by specifying the assetic bundles myself:

```
<assetic:config debug="%kernel.debug%" use-controller="%kernel.debug%">
    <assetic:bundles name="FrameworkBundle" />
</assetic:config>
```

**Comment by Jean85** [comment] 2016-06-16 08:04
Thanks @stof that fix worked for me. Maybe we should use a better default, as @HeahDude suggested.

**Comment by stof** [comment] 2016-06-16 08:13
@0xTryCatch no need to include FrameworkBundle in the list, as it does not contain any Assetic tag. You should rather include ``AppBundle`` there.

@Jean85 changing the behavior when no bundle list is specified would be a BC break.
We may indeed want to have a better filtering strategy (we would also need a way to handle template paths outside bundles btw), but this requires work in AsseticBundle, and I don't have much time to dedicate to this bundle currently.

**Comment by 0xTryCatch** [comment] 2016-06-16 09:54
@stof Understood, thanks again

**Comment by javiereguiluz** [comment] 2016-06-19 07:46
Closing it as fixed thanks to the solution provided by @stof.

**Closed by javiereguiluz** 2016-06-19 07:46 UTC

**Comment by patie** [comment] 2016-07-25 10:43
Hi @stof, if i understand where problem is, this - http://symfony.com/doc/current/reference/configuration/assetic.html#full-default-configuration is probably not good example of assetic config, right?

Maybe its good idea change this:

```  
    bundles:

        # Defaults (all currently registered bundles):
        - FrameworkBundle
        - SecurityBundle
        - TwigBundle
        - MonologBundle
        - SwiftmailerBundle
        - DoctrineBundle
        - AsseticBundle
        - ...
```

into something like this

```
    bundles:

        # Defaults (all currently registered bundles):
        - AppBundle
        - ...
```

what you think?

**Comment by stof** [comment] 2016-07-25 11:26
Well, this is showing the *default* config. This is not the same than the recommended config. the recommended config is to whitelist only bundles needing Assetic.

**Comment by patie** [comment] 2016-07-25 11:45
ok, understand

**Comment by COil** [comment] 2016-11-03 09:11
Fixed the same issue with:

    assetic:
        bundles:
            - AppBundle

Thanks.

**Comment by MicWit** [comment] 2017-07-27 01:01
I'm not sure why this has been marked as resolved, having to set up a whitelist of bundles needing Assetic is a (not very good) work around. What if you download a bundle that needs assetic without realizing? That will cause issues as you have stopped assetic looking to it. Would it not be a better option to find the bundles/templates that use profiler_dump and make sure they will not do this in prod (they should only do this in app_dev, right?) by fixing that code?

**Comment by robfrawley** [comment] 2017-07-27 03:41
As @stof already mentioned

> Changing the behavior when no bundle list is specified would be a BC break. We may indeed want to have a better filtering strategy (we would also need a way to handle template paths outside bundles), but this requires work in AsseticBundle, and I don't have much time to dedicate to this bundle currently.

@MicWit Furthermore, as `AsseticBundle` is no longer the default front-end solution and isn't part of the Symfony Standard Edition anymore, you'd need to find someone willing to contribute time to that project. You could always submit a PR to that project yourself, if you have the time and motivation.

**Comment by MicWit** [comment] 2017-07-27 03:53
@robfrawley, I guess what I'm wondering is whether the bundles should be doing a profiler_dump in prod to begin with? I thought that Symfony standards (don't quote me on this) for any sort of a dump like this was to only do it in dev, never in prod?

I have the motivation to do something like this, just not the time at the moment. I think that rather than fix Assetic (as its not really the problem), I would check out what the profiler_dumps are for and try to filter them out when in prod.

**Comment by robfrawley** [comment] 2017-07-27 03:59
But the issue _is_ Assetic, as it is the code that is calling dev-only templates when not specifying a whitelist of bundles. The issue is not the bundles that contain templates intended only for development, but the fact that `AsseticBundle` is loading them.

**Comment by MicWit** [comment] 2017-07-28 00:24
I have not looked into the template yet to see where they are called from etc (if they are only called from a dev environment, fair enough), but the ones I get are:

> SecurityBundle:Collector:security.html.twig
> DoctrineBundle:Collector:db.html.twig

and to me they don't seem to be names that indicate they are dev only. There may be checks in them to check the environment and only run the dump if its dev, but if one of these 2 things are not happening, it would indicate that the dump code is available in prod (So it may dump stuff if something goes wrong or something like that. If this is the case, it would need to be those files that have to be fixed, if they are only calling the dump in a dev environment, then it would need to fixed in Assetic.

**Comment by robfrawley** [comment] 2017-07-28 00:48
Those templates are "data collectors" for the [web debug toolbar and profiler](https://symfony.com/blog/new-in-symfony-3-1-web-debug-toolbar-and-profiler-enhancements) and is generally used only in a development environment. There won't be any environment checks or conditionals in there related to environment-specific method calls, AFAIK. Again, you definitely want to look at `AsseticBundle` to resolve this issue.

**Comment by MicWit** [comment] 2017-07-28 00:57
OK, so if they are "data collectors" that are generally only used in a development environment, are they available to prod anywhere? Assetic seems to think so! If they are only ever called in a development environment (eg. by the debug toolbar), then that is where the check is (the toolbar will check if its dev or not to decide whether to load).

However, as of the last few versions of Symfony, you CAN do a dump in prod (not sure what version it came in, but try use dump($var) in a controller and run the prod site. I am wondering if this has anything to do with it?

**Comment by robfrawley** [comment] 2017-07-28 01:07
Those files are not loaded anywhere unless you explicitly enable the toolbar, in which case it is your responsibility to make sure the debug component is also available. I'm just trying to save you some time: the issue is in how Assetic loads templates when not passed a whitelist.

**Comment by MicWit** [comment] 2017-07-28 01:35
OK, so in that case, Assetic needs some kind of a check when you do a dump, to see if that particular file is used in the environment you are doing the dump for. I'm guessing that there is no way in Symfony (via console or anything) to do a check like this, so Assetic is just looking in each bundle and processing it anyhow. In dev, this will work as it has access to the function, in prod it won't and throws the error.

When I get a bit more time, I may have a look into how Assetic processes twig files in the dump and make an exception for the prod environment for the profiler_dump function so that it will not thow an error and just bypass it.

**Comment by Creaternal** [comment] 2017-08-09 14:29
Maybe the best way to add the option is assetic.bundles_exclude?
This would be useful for projects with a lot of their own packages, when using a white list is inconvenient.

**Comment by xabbuh** [comment] 2017-08-09 14:41
@Creaternal Maybe, but that still needs to be done in AsseticBundle which is not part of the Symfony core.

**Comment by ElXyfer** [comment] 2018-03-16 17:06
@MicWit did you ever solve this issue? I’m now getting this error whilst in production and some of my css on certain browsers isn’t rendering and I’m assuming it’s because of this error because it appears when I do a dump whilst deploying.
