### ISSUE TITLE
Updating symfony/translation: Missing ArrayLoader class

### ISSUE THREAD

**Issue by gander** [symfony/symfony#43228] opened 2021-09-28 10:10 UTC
**Symfony version(s) affected**: 4.4.31

**Description**
The error occurred in another package, but I only updated the `symfony/translation` package and this one had _"no significant changes"_.

**How to reproduce**
`Upgrading symfony/translation (v4.4.30 => v4.4.31)`

**Additional context**
```
Class Symfony\Component\Translation\Dumper\IcuResFileDumper located in ./vendor/symfony/translation/IcuResFileDumper.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\fixtures\ServiceSubscriber located in ./vendor/symfony/translation/ServiceSubscriber.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Loader\IcuResFileLoaderTest located in ./vendor/symfony/translation/IcuResFileLoaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\DependencyInjection\TranslationExtractorPassTest located in ./vendor/symfony/translation/TranslationExtractorPassTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\IcuResFileDumperTest located in ./vendor/symfony/translation/IcuResFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\QtFileDumperTest located in ./vendor/symfony/translation/QtFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Formatter\MessageFormatter located in ./vendor/symfony/translation/MessageFormatter.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\Dumper\JsonFileDumperTest located in ./vendor/symfony/translation/JsonFileDumperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Translation\Tests\IntervalTest located in ./vendor/symfony/translation/IntervalTest.php does not comply with psr-4 autoloading standard. Skipping.
```
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Symfony\Component\Translation\Loader\ArrayLoader' not found

  at /www/vendor/nesbot/carbon/src/Carbon/Translator.php:80
    76|     public function __construct($locale, Translation\Formatter\MessageFormatterInterface $formatter = null, $cacheDir = null, $debug = false)
    77|     {
    78|         $this->initializing = true;
    79|         $this->directories = [__DIR__.'/Lang'];
  > 80|         $this->addLoader('array', new Translation\Loader\ArrayLoader());
    81|         parent::__construct($locale, $formatter, $cacheDir, $debug);
    82|         $this->initializing = false;
    83|     }
    84| 

  Exception trace:

  1   Carbon\Translator::__construct("en")
      /www/vendor/nesbot/carbon/src/Carbon/Translator.php:70

  2   Carbon\Translator::get()
      /www/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php:691
```

**Comment by derrabus** [comment] 2021-09-28 10:11
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 10:11 UTC
Labels: Bug, Status: Needs Review
