### ISSUE TITLE
DateTimeToArrayTransformer with default date of 1970-01-01

### ISSUE THREAD

**Issue by felix-goecking** [symfony/symfony#24510] opened 2017-10-10 15:06 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hi guys,
we are having trouble using the TimeType in our forms in combination with timezones. The TimeType is transformed to an PHP \DateTime type with the default date 1970-01-01 set by the DateTimeToArrayTransformer. 

When the user selects 01:00 PM using Europe/Berlin timezone at the 10th of October and we convert it to UTC and save that to the database the saved value is 12:00 AM because PHP thinks it is not daylight saving time (because of date 1970-01-01) and thus only subs 1 hour. But we think it should sub 2 hours because the current date has to be used and not the 1st of January 1970. Thus we have to set the current timestamp to our \DateTime objects in order to get the correct values. 

Would it be possible to use the current date as default value in the DateTimeToArrayTransformer if none is given (As by the TimeType)?

**Comment by sroze** [comment] 2017-10-10 15:29
👋 @felix-goecking! The problem that you experience is not very clear to me as you seems to be talking about two different issues:
1. The default date set by `DateTimeToArrayTransformer` is `1970-01-01`. It is when you are just submitting the hours (like `10:00`) in your `datetime` input, right?
2. The `DateTime` is saved in your database with a different timezone than what the user is submitting?

If I'm correct, here are my answers:
1. You can't change the defaults for now as far as I know, without creating your own transformer.
2. Did you configure the [`model_timezone`](https://symfony.com/doc/current/reference/forms/types/time.html#model-timezone) (i.e. the timezone used in the data within your database) and the [`view_timezone`](https://symfony.com/doc/current/reference/forms/types/time.html#view-timezone) options?

**Comment by felix-goecking** [comment] 2017-10-10 15:37
1. Right, if I submit `10:00` I get a PHP` \DateTime` object with `1970-01-01 10:00`
2. Yes, the model_timezone and view_timezone values are set (model_timezone is set to UTC and view_timezone is set to the users timezone, e.g. Europe/Berlin)

As you said we can't change the date value for the `TimeType`, thus we need to create an own transformer. But in our opinion the `DateTimeToArrayTransformer` needs to set the date to the current value and not to `1970-01-01 10:00`

**Comment by mvrhov** [comment] 2017-10-11 07:11
If you want timezone info , then use full DateTime, Time or Date on alone don't provide adequate information as you have figured out.

**Comment by sroze** [comment] 2017-10-11 08:02
@felix-goecking according to Google, Berlin is 2 hours ahead of UTC time:
[<img width="651" alt="screen shot 2017-10-11 at 08 53 34" src="https://user-images.githubusercontent.com/804625/31428150-b9e07bc8-ae61-11e7-89ac-fdd964b33c2a.png">](https://www.google.co.uk/search?q=berlin+time+vs+utc)

Therefore, if you submit 10:00 with a `view_timezone = Europe/Berlin`, I would expect Symfony to return (or save directly to value to the database if you don't do any other processing - disclaimer here because you said "we convert it to UTC and save that to the database") a `DateTime` with the time 08:00.

That said, using only time while you have some timezone to manage makes no sense to me, because when dealing with timezones you directly deal with the date. For example, 01:00 in Berlin is... -01:00 in UTC? Hehe, makes no sense but makes sense to say it's "the day before at 23:00". Also, when you say "the default date 1970-01-01 set by the DateTimeToArrayTransformer" that's very likely you will also enter some timezone issue... is it the date of the user or the server? Because obviously, considering the timezone without a time **and** a date doesn't really make sense.

Therefore, I'd definitely recommend you to use the [`DateTimeType` form type](https://symfony.com/doc/current/reference/forms/types/datetime.html). (that doesn't mean you can't hide fields to the user tho).

**Comment by j-gkr** [comment] 2017-10-11 08:51
>Therefore, if you submit 10:00 with a `view_timezone = Europe/Berlin`, I would expect Symfony to return [...] a DateTime with the time 08:00.

And that is our problem, if we submit `10:00` with a `view_timezone = Europe/Berlin`, Symfony returns a `DateTime` with the time `09:00`. The reason for this is the default date value `1970-01-01`.

You are right when you say using only `Time` while we want to manage some timezone makes no sense, but then the options `view_timezone` and `model_timezone` don't work like they supposed to do.

Finally we just want to save a period in the database in UTC format with `startTime` and `endTime`. When a user creates a new period, he selects hours and minutes in his timezone, e.g. `Europe/Berlin`. In the background we want to save the given values in UTC format. So if another user with timezone `Europe/London` gets the same values. This must be possible or not?

And in our case the date information isn't relevant for this purpose. Maybe there are better solutions for this problem?

**Comment by sroze** [comment] 2017-10-11 08:59
> You are right when you say using only Time while we want to manage some timezone makes no sense, but then the options view_timezone and model_timezone don't work like they supposed to do.

Isn't there something with daylight saving things...? 🤔 i.e. in January, Berlin is only 1 hour ahead of UTC?

> Finally we just want to save a period in the database in UTC format with startTime and endTime. When a user creates a new period, he selects hours and minutes in his timezone, e.g. Europe/Berlin. In the background we want to save the given values in UTC format. So if another user with timezone Europe/London gets the same values. This must be possible or not?

You should change your approach to use `startDateTime` and `endDateTime` if your time period is relative to a timezone. Because you understand that the exact same moment in time can be across to days somewhere on the globe and the same day somewhere else on the globe.

> And in our case the date information isn't relevant for this purpose. Maybe there are better solutions for this problem?

Again, I hope the answer above clarify that the date is relevant. Last example with the time period today between 2:00 AM and 4:00 AM where I live, in London:
1. London time: 2:00 to 6:00
2. Sao Paulo 22:00 to 02:00. This makes no sense without a date :)

**Comment by sroze** [comment] 2017-10-11 09:01
> Isn't there something with daylight saving things...? 🤔 i.e. in January, Berlin is only 1 hour ahead of UTC?

Here we go! Because Berlin is UTC+1 only in January... the result is correct 👌 
https://www.timeanddate.com/time/zone/germany/berlin

**Comment by j-gkr** [comment] 2017-10-11 09:18
> Here we go! Because Berlin is UTC+1 only in January... the result is correct 👌

In january the result is correct. But we are saving this values now. So at this moment the result isn't correct.

To get the correct result at this moment we manipulated the date value to the current date, before we convert the timezone.

**Comment by mvrhov** [comment] 2017-10-11 09:33
Timezones on date only and time only fields is never-ending story. Just do a quick search. You can't please everyone.

My recommendation would be to create your own field that would behave exactly as you want.

**Comment by stof** [comment] 2017-10-11 11:01
Timezones only makes sense for a DateTime, not for a time alone, as the timezone offset depends on the date.
We tried in the past to deprecate the timezone option for the date and time fields, but it has not worked well, because of the fact that we still use a DateTime PHP object for the representaton (and so we have to create a fake time or date part to build the object).

**Comment by xabbuh** [comment] 2018-09-14 14:35
I am closing here as this is the expected behaviour. If you do not only need information about the time of the day, but also need to take into account the actual date, you will have to use the `DateTimeType`.

**Closed by xabbuh** 2018-09-14 14:35 UTC
Labels: Bug, Form, Status: Needs Review
