### ISSUE TITLE
[Routing] Annotation loader merging of methods/schemes

### ISSUE THREAD

**Issue by vicb** [symfony/symfony#7132] opened 2013-02-20 07:10 UTC
```php
<?php
/** @Route */
class Controller
{
    /** @Route */ 
    method action()
}
``` 

The annotation class loader does a bad job at merging class level settings with method level settings.

IE if the methods are [get, post] at class level and [post] at method level, the resulting methods will be [post, post].

This could easily be fixed but how:
- Should the class level params take precedence,
- Should the method level params take precedence,
- Should we do what other loader do for when merging collections - which has my pref.

If we pick the last choice, we might want to delegate the params merging to an exterbal service so that all loaders use the same services and code duplication stop causing troubles.

One last thing is where this should be merge ? This is obviously a bug fix but it also breaks BC and so I would recommend not to merge this to 2.0 and 2.1 but add this issue to a list of known issues for those realeses and fix from 2.2 onwards.

**Comment by Tobion** [comment] 2015-01-16 03:39
This is still relevant from what I can see. The problem is that the schemes and methods replaced with`$schemes = array_replace($globals['schemes'], $annot->getSchemes());` in https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L148

Replacing makes no sense for them as it's not an associative array. So either they should be merged over overwritten completely.

**Closed** 2015-01-25 03:35 UTC
Labels: Bug, Hackday, Routing
