### ISSUE TITLE
Workflow from console

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#26401] opened 2018-03-05 09:22 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

I try to use workflow from console and have error:
 
The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.

**Comment by lyrixx** [comment] 2018-03-05 09:25
This occurs because you are using a guard listener but the security component is not installed.

Could you give us the guard expression you are using ?

**Comment by allfreelancers** [comment] 2018-03-05 09:27
@lyrixx no, I have a component installed

```Could you give us the guard expression you are using ?```
no expression

**Comment by xabbuh** [comment] 2018-03-05 09:32
Could you create a small example application that allows to reproduce your issue?

**Comment by allfreelancers** [comment] 2018-03-05 09:39
@xabbuh yes, In a few hours

**Comment by allfreelancers** [comment] 2018-03-05 11:17
@xabbuh test it: https://github.com/allfreelancers/workflow-test

**Comment by allfreelancers** [comment] 2018-03-05 11:18
```
php bin/console workflow:test

In GuardListener.php line 63:

  There are no tokens available for workflow item.
```

**Comment by iltar** [comment] 2018-03-05 13:59
Security is not triggered on the console, you have to manually set the Token in that case.

**Comment by allfreelancers** [comment] 2018-03-05 14:02
@iltar how to do it? can an example?

**Comment by iltar** [comment] 2018-03-05 14:07
```
$tokenStorage->setToken($yourToken); // security.token_storage service
```

**Comment by allfreelancers** [comment] 2018-03-05 14:08
@iltar can I have a more detailed example? where to get a token?

**Comment by iltar** [comment] 2018-03-05 14:15
Tokens are part of the authentication process: https://symfony.com/doc/current/components/security/authentication.html

I would recommend to check the signature of the `setToken()` method and check which classes implement that. It would probably be sufficient enough to make a dummy token with the right roles and username (or id). You can even try anonymous. However, the console has 0 authentication and authorization integration, as this is all HTTP related, so things might not go as you expect.

**Comment by allfreelancers** [comment] 2018-03-05 14:16
@iltar thank you very much, there is much to think about!

**Comment by lyrixx** [comment] 2018-03-05 16:39
Indeed, you are using some guard https://github.com/allfreelancers/workflow-test/blob/master/app/config/workflow.yml#L17

You you need to inject a token in the token storage.

I'm going to close this issue but if you have more question, don't hesitate to reply to this.

**Closed by lyrixx** 2018-03-05 16:39 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback, Unconfirmed, Workflow

**Comment by tacman** [comment] 2019-10-23 11:18
I keep hacking away, and I can't figure out how to inject the token storage and set it.

It's from the console, so I don't have a login, I'm sure it's just a few lines of code, can someone show me what those lines of code are please?  Thanks

**Comment by lugus** [comment] 2020-04-08 18:44
Hello,

Got this issue too, is it normal to have this error even if trying to apply a transition which does not use guard?

Example:

```
transitions:
    publish:
        from: draft
        to: open
    start:
        guard: "has_role('ROLE_FOO')"
        from: open
        to: progress
```

Got this error if trying to execute `publish` transition. 
Tried with `guard: "is_anonymous()"`

Wanted to load fixtures with marking.

Thank you.

**Comment by will2877** [comment] 2021-07-20 10:03
+1 on this issue. 

I have transitions that don't use guard and are still not working. 
Is there a full example somewhere that shows a workaround or how to load the  `AnonymousToken` from the console?

I am on Symfony 4.4.
