### ISSUE TITLE
Variable "expanded" not found when naming form class "ChoiceType"

### ISSUE THREAD

**Issue by Yopai** [symfony/symfony#23774] opened 2017-08-03 08:12 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | I don't think
| RFC?             | no
| Symfony version  | 3.3.1

I got a Choice entity, linked to a Step entity.
So I generated a ChoiceType class :

```
/*... apropriate namespace and uses... */

class ChoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('step', EntityType::class, [
                'class' => Step::class,
                'choice_label' => 'adminTitle',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([ 'data_class' => Choice::class ]);
    }
}
```
When rendering the form, I got a "Variable expanded not found" error in form_div_layout (I'm using bootstrap horizontal layout)

If I just rename ChoiceType into ChoiceForm, I got no error anymore.

**Comment by fancyweb** [comment] 2017-08-03 08:22
https://symfony.com/doc/current/form/create_custom_field_type.html#creating-a-template-for-the-field

> When the name of your form class matches any of the built-in field types, your form might not be rendered correctly. A form type named AppBundle\Form\PasswordType will have the same block name as the built-in PasswordType and won't be rendered correctly. Override the getBlockPrefix() method to return a unique block prefix (e.g. app_password) to avoid collisions.

**Comment by xabbuh** [comment] 2017-08-03 12:25
closing as this is indeed not a bug as explained by @fancyweb

**Closed by xabbuh** 2017-08-03 12:25 UTC
