### ISSUE TITLE
Constraint validator "validator.expression" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Expression".

### ISSUE THREAD

**Issue by SakhriHoussem** [symfony/symfony#49998] opened 2023-04-12 09:26 UTC
### Symfony version(s) affected

6.2.8

### Description

the constraint Expression does not work on symfony 6.2.8

### How to reproduce

to reproduce use constraint Expression:

```php

    #[Assert\When(
        expression: 'this.is360FeedBack()',
        constraints: [
            new Assert\Sequentially([
                new Assert\NotNull,
                new Assert\Expression(
                    'this.isValidModel()',
                    message: "exception.model.not_valid"),
            ])
        ],
    )]
```

**Comment by stof** [comment] 2023-04-12 09:31
This has been fixed by https://github.com/symfony/symfony/pull/49889. You can either wait for 6.2.9 or downgrade symfony/framework-bundle to 6.2.7.

Duplicate of https://github.com/symfony/symfony/issues/49886

**Closed as not planned** 2023-04-12 09:34 UTC
Labels: Validator, Bug, Status: Needs Review

**Comment by SakhriHoussem** [comment] 2023-04-12 09:59
thnx @stof
