### ISSUE TITLE
Form validation not showing up on individual form fields

### ISSUE THREAD

**Issue by nullstrike** [symfony/symfony#25110] opened 2017-11-22 14:20 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-BETA4

So I 've been testing symfony lately and I'm trying to make use of Constraints to validate the inputs of my form. I use twig to render my form. Everything is set, validations are working, form validation messages shows up but only if I use this command
![screenshot from 2017-11-22 22-13-20](https://user-images.githubusercontent.com/29997879/33131835-beb50c94-cfd2-11e7-902a-ad0a000b2162.png)

```
{{form_start(form)}}
   {{form_widget(form)}}
   <button class="btn btn-info" formnovalidate>Save</button>
{{form_end(form)}}
```
meanwhile this command below doesn't render the validation messages
![screenshot from 2017-11-22 22-13-55](https://user-images.githubusercontent.com/29997879/33131843-c6ee1e5a-cfd2-11e7-862e-3b49d924fdfa.png)

```
 {{ form_start(form) }}
        {{ form_row(form.firstName) }}
        {{ form_errors(form.firstName) }}
        {{ form_row(form.lastName) }}
        {{ form_errors(form.lastName) }}
        <button class="btn btn-info" formnovalidate>Save</button>
 {{ form_end(form) }}
```

My Form Class:
```
 public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('firstName')
                ->add('lastName');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Sample::class]);
    }
```

**Comment by arkste** [comment] 2017-11-22 19:06
i tried to reproduce the reported issue, but it works for me.

could you please fork https://github.com/symfony/symfony-standard and recreate the bug in a branch (from 3.4)? thanks!

**Comment by xabbuh** [comment] 2017-11-22 19:09
I am not sure I understand your issue. Can you create a small example project that allows to reproduce it?

**Comment by Simperfit** [comment] 2017-11-27 07:10
Could you please do what @xabbuh said ?

Do you need the step to do it ?

**Comment by nullstrike** [comment] 2017-11-27 12:52
Nevermind, I tried using the latest bootstrap 4 released and it works correctly

**Comment by xabbuh** [comment] 2017-11-27 12:54
Thanks for the feedback, closing then.

**Closed by xabbuh** 2017-11-27 12:54 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback, Unconfirmed
