### ISSUE TITLE
[Translation] use intl domain when adding a new key if intl domain exists

### ISSUE THREAD

**Issue by axi** [symfony/symfony#42871] opened 2021-09-03 07:39 UTC
**Symfony version(s) affected**: ^4.*

**Description**
Currently, when using a intl domain and trying to add a new key, key is added to the regular (not intl) domain resulting in a new domain.lang.json file created along the  domain+int-icu.lang.json file

**How to reproduce**
having a intl domain, use php-translation interface to add a new key

**Possible Solution**
I found out that in MessageCatalogue::add method, we check if intl domain exists (normal) AND if **key is already existing in intl domain**.

    /**
     * {@inheritdoc}
     */
    public function add($messages, $domain = 'messages')
    {
        if (!isset($this->messages[$domain])) {
            $this->messages[$domain] = [];
        }
        $intlDomain = $domain;
        if (!str_ends_with($domain, self::INTL_DOMAIN_SUFFIX)) {
            $intlDomain .= self::INTL_DOMAIN_SUFFIX;
        }
        foreach ($messages as $id => $message) {
            if (isset($this->messages[$intlDomain]) && \array_key_exists($id, $this->messages[$intlDomain])) {
                $this->messages[$intlDomain][$id] = $message;
            } else {
                $this->messages[$domain][$id] = $message;
            }
        }
    }

=> I don't get why we must only add it in intl domain if already existing (resulting in only update possible). Removing

       && \array_key_exists($id, $this->messages[$intlDomain])

fix the problem for me

Should I create a pull request with this or am I missing the point of this part ?

**Comment by axi** [comment] 2021-09-03 08:57
Removing it make one test start to fail...

in Symfony\Component\Translation\Tests\Catalogue\MergeOperationTest

    public function testGetResultFromIntlDomain()
    {
        $this->assertEquals(
            new MessageCatalogue('en', [
                'messages' => ['a' => 'old_a', 'b' => 'old_b'],
                'messages+intl-icu' => ['d' => 'old_d', 'c' => 'new_c'],
            ]),
            $this->createOperation(
                new MessageCatalogue('en', ['messages' => ['a' => 'old_a', 'b' => 'old_b'], 'messages+intl-icu' => ['d' => 'old_d']]),
                new MessageCatalogue('en', ['messages+intl-icu' => ['a' => 'new_a', 'c' => 'new_c']])
            )->getResult()
        );
    }

Should a merge operation between regular & int domain keys result in only intl domain existing ?

**Comment by welcoMattic** [comment] 2021-10-14 21:04
Hello @axi,

I think the source of the problem is in php-translation, not in Symfony. If you use the native command `translation:update` to extract untranslated keys from your source code, the new keys will be created in the right file (intl if it exists, normal one if not, never both). 

Moreover, your patch break an old test, which is not a good thing. This test guarantee that old existing messages (which can contain old plural format) stay in the "normal" file (without intl suffix), and others live in intl file.

You are very welcome to patch the issue on [php-translation bundle](https://github.com/php-translation/symfony-bundle) :pray:

**Comment by axi** [comment] 2021-10-15 07:13
Hi @welcoMattic Thanks for reviewing this.
Your explanation on the merge operation test make sense.
I'll have a look if I can find something to fix on [php-translation/symfony-bundle](https://github.com/php-translation/symfony-bundle)

**Comment by fabpot** [comment] 2021-10-15 08:30
Let's close this issue then.

**Closed as completed by fabpot** 2021-10-15 08:30 UTC
Labels: Bug, Translation, Status: Needs Review

**Comment by axi** [comment] 2021-10-15 09:53
Find out that in ```translation:update``` command

``` $operation->moveMessagesToIntlDomainsIfPossible('new'); ```

make the magic happens...
Without it, new messages goes to normal domain... Looks like a quick fix to me :-)

I still wonder, MessageCatalogue tries to abstract use of intl domain (see get() method return intl value if existing, getDomain() never returning domain+intl-icu), why should the add() method not respect that and be only able to update intl keys?
