### ISSUE TITLE
FormEvents::PRE_SUBMIT, the 'choices" field of an entity type throws spl_object_hash() exception

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony#15055] opened 2015-06-21 13:32 UTC
I have an entity which is fetched inside a form Subscriber. When I use this entity as 'choices', I get the exception. When using query builder and a repo call, it works. That only happens when I upgrade from Symfony 2.6.9 to Symfony 2.7.1

**Comment by ewgRa** [comment] 2015-06-21 13:34
Can you show exception message with stack and some code?

**Comment by ZCJ** [comment] 2015-06-21 13:50
Here is a sample code which lives inside the FormEvents::PRE_SUBMIT:
---------------------------
if ($media) {
                    $subMedias = $media->getSubMedias();
                    $form->add('subMedia','entity',
                       [
                            'class'       => '...\SubMedia',
                            'property'    => 'name',
                            'choices'     => $subMedias,
                        ]
                }
---------------------------

![screen shot 2015-06-21 at 5 44 49 pm](https://cloud.githubusercontent.com/assets/1475845/8271849/587958f8-183d-11e5-949a-183dbcc2a011.png)

![screen shot 2015-06-21 at 5 45 07 pm](https://cloud.githubusercontent.com/assets/1475845/8271851/61c6195a-183d-11e5-8ec4-487d010e0c4d.png)

**Comment by ZCJ** [comment] 2015-06-21 20:32
The same code in Symfony 2.6 works fine by the way

**Comment by webmozart** [comment] 2015-06-22 14:24
Hi @ZCJ, thank you for taking the time to report this issue! :) Could you please upload a fork of symfony-standard that reproduces this problem?

**Comment by xabbuh** [comment] 2015-06-29 07:02
maybe related to #15037?

**Comment by xabbuh** [comment] 2015-07-08 06:39
ping @ZCJ

**Comment by ZCJ** [comment] 2015-07-08 06:52
@xabbuh ... I still need to submit a fork with the reproduced error .. I will try and have it ready by next week.

**Comment by xabbuh** [comment] 2015-07-08 06:57
@ZCJ cool, thank you :)

**Comment by jakzal** [comment] 2015-07-27 10:31
ping @ZCJ

**Comment by brainbowler** [comment] 2015-07-28 14:46
+1, I'm having exactly the same problem after upgrading from 2.5 to 2.7.

**Comment by xabbuh** [comment] 2015-07-29 06:32
@brainbowler You could help us as well by providing a fork that makes it able to reproduce your issue. :)

**Comment by ZCJ** [comment] 2015-09-09 06:26
@xabbuh I think 2.7.4 has fixed this issue as I don't see it anymore after updating Symfony to 2.7.4

**Comment by xabbuh** [comment] 2015-09-09 07:24
ping @ZCJ @brainbowler Could you please help us? :)

**Comment by ZCJ** [comment] 2015-09-09 18:19
@xabbuh I though that the issue was solved once I updated to Symfony 2.7.4, however I found out that I still had the same problem. I promise that I will try to put more time and get it reproduced by next week.

**Comment by johanderuijter** [comment] 2015-09-11 08:13
@xabbuh I came across something similar, judging from the stack trace in the screen shots.

In my case it had nothing to do with the form events, but with submitting in integer in the data option of an entity field with a custom choice list. (Also done in line 11 of the stack trace above.) I recreated in [this error in a branch using symfony 2.7.*@dev](https://github.com/johanderuijter/symfony/tree/spl_object_hash).

The page loads if you remove [this line](https://github.com/johanderuijter/symfony/blob/spl_object_hash/src/AppBundle/Form/ArticleType.php#L21) from the FormType, but crashes with the error show above if it's there. The same thing happens when you have a similar construction in a PRE_SUBMIT.  I dont think the data with an integer works or is even suppose to, but without a custom choice list, it's just ignored instead of crashing with such a non discript error.

I you need anything else, just let me know.

**Comment by stof** [comment] 2015-09-11 09:17
Well, according to the screenshot, you are setting ``array('id' => '1', 'name' => 'Production')`` as data of the form. this is expected to break as it is not supported. The entity type only expect choices to be objects, and the data should also be an object (or null)

**Comment by ZCJ** [comment] 2015-09-11 10:14
@stof is this not supported as of 2.7? why does it work in my 2.6 branch?

**Comment by xabbuh** [comment] 2015-10-05 08:43
@ZCJ Probably because the code did not prevent you from using the type in a wrong way.

Closing for now as the issue described seems to be related to some wrong usage. Please feel free to reopen if you can provide steps to reproduce the issue when using the form type as expected.

**Closed by xabbuh** 2015-10-05 08:43 UTC
Labels: Bug, Form, Unconfirmed

**Comment by ZCJ** [comment] 2015-10-19 14:22
@xabbuh you are right - The code in 2.6 allowed us to do what we were doing and the reported issue is not a bug as we were able to resolve it.
