### ISSUE TITLE
Symfony 2.8 :  uncallable Customized Exception controller

### ISSUE THREAD

**Issue by Shinigani** [symfony/symfony#24400] opened 2017-10-02 12:08 UTC
| Symfony version  | 2.8.*

Hello since a few days, I've been looking for a way to create a customized Exception Controller.
I've looked through this link [How to customize Error Pages](https://symfony.com/doc/2.8/controller/error_pages.html) and tried to adapt it for what i wanted.

In big lines what I want to do is : 
When I fall on a 404 exception throw  a page 404 customized.
In function of the validity of the URL I will display 1 or 2 Button.
If the URL exist but not the page, display one button to guide the user to the Homepage or another Button to the search with some parameters taken from the URL.

My main problem is that when i try to fall on my custom controller in the first time , I get : "Controller "FrontendBundle:Error404:showException" for URI "/fr/villas/france/bernadette" is not callable."

This is my Controller : 
```php      
        <?php
        namespace FrontendBundle\Controller;

     //use SG\FrontendBundle\Controller\ExceptionController;
    //use Symfony\Bundle\TwigBundle\Controller\ExceptionController;
    //use FrontendBundle\Entity\Repository;
      use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    //use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route
    class Error404Controller extends Controller
    {
        /*
         * @Route(
         *        "/{_locale}/{_type}/{$countryName}/{$cityName}/{$etablishementName}",
         *        requirements={
         *        "_locale": "en|fr",
         *        "_type": "hotels|villas|restaurants"
         *        }
         *      )
         */
         public function showAction($countryName,$cityName,$etablishementName)
         {
             $em = $this->getDoctrine()->getManager();
             $events = $em->getRepository('FrontendBundle:Error404')
                     ->getUpcomingEvents();
       
             $country = $this->getDoctrine()->getRepository(FrontendBundle::Error404)->findCountryCityByName($countryName);
             $city = $this->getDoctrine()->getRepository(FrontendBundle::Error404)->findCountryCityByName($cityName);
             $etablishement = $this->getDoctrine()->getRepository(FrontendBundle::Error404)->findEtablishementBySlug($etablishementName);

        return $this->render('app/Resources/TwigBundle/views/Exception/error404.html.twig', array(
            'redirection' => $events,
            ));
    }
   }
```
This is my Entity : 

```php
     <?php

         namespace FrontendBundle\Entity\Repository;


         use Doctrine\ORM\EntityRepository;
         use SG\FrameworkBundle\Model\CrudEntityInterface;


         class Error404Repository extends EntityRepository
         {
           /*
            * Recherche dans sg_content_translation
            */
           public function findCountryCityBySlug($slug)
           {
                      $qb = $this->createQueryBuilder()
                                       ->select('world.published_slug')
                                       ->from('my_table_1','world')
                                       ->where('world.published_slug= ?1')
                                       ->setParameter(1,$slug);


                    return $qb->getQuery()->getOneOrNullResult();
           }

          public function findEtablishementBySlug($slug)
          {
                   $qb = $this->createQueryBuilder()
                                    ->select('world.published_slug')
                                    ->from('my_table_2','world')
                                    ->where('world.published_slug= ?1')
                                    ->setParameter(1,$slug);
                   return $qb->getQuery()->getOneOrNullResult();
           }
      }

```

This is my services.yml : 

```yaml
 
        services:
         #    twig.controller.exception:
         #        class: %twig.controller.exception.class%
         #        arguments: ["@twig", "%kernel.debug%", "@doctrine"]
                   app.exception_controller:
                           class: FrontendBundle\Controller\Error404Controller
                           arguments: ['@twig','%kernel.debug%']

```

This is my config.yml : 

```yaml

    twig:
         exception_controller: FrontendBundle:Error404:showException


```

**Comment by pierredup** [comment] 2017-10-02 12:24
Your action in your controller is called `showAction`, but the name you use in your routing file is `showException`. So you need to change the method in your controller to `showExceptionAction`

**Comment by Shinigani** [comment] 2017-10-02 14:25
I still get : Controller "FrontendBundle:Error404:showExceptionAction" for URI "/en/nonsense" is not callable. Could it be something else  ?

**Comment by dbrumann** [comment] 2017-10-02 14:26
This is not a Symfony issue. This ticket should be closed and you should use one of the [Support Channels](https://symfony.com/support) like StackOverflow or the Slack.

**Comment by javiereguiluz** [comment] 2017-10-02 14:54
Closing because the question has been asked in StackOverflow and Slack channel too. If this is confirmed as a Symfony error, we can reopen. Thanks!

**Closed by javiereguiluz** 2017-10-02 14:54 UTC
