### ISSUE TITLE
Doctrine configuration - Doctrine can't find annotation 

### ISSUE THREAD

**Issue by mikaelit** [symfony/symfony#22670] opened 2017-05-08 12:32 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.20

I described my issue hear: http://stackoverflow.com/questions/43794498/symfony-how-to-solve-the-doctrine-issue-of-the-missing-annotations/43825184#43825184
I think it's locale problem, but I can't find solution.

**Comment by sh4ka** [comment] 2017-05-08 13:30
As far as I know, system_user is an alias and hence a reserved word for user:
https://dev.mysql.com/doc/refman/5.7/en/information-functions.html
I have not tested this but I think this is the problem.

**Comment by sstok** [comment] 2017-05-08 13:32
>  try to add framework: validation: { enable_annotations: true } in your app/config/config.yml – Sylvain Attoumani May 5 at 8:17 

This only makes sense when you use Annotations outside of Doctrine ORM, the DoctrineBundle already enables them.

Are you using something like APC/Opcache? Try clearing the cache, bootstrap.php.cache, and make sure you use the correct autoload.php in web/app_{dev}.php

I might have a idea what's wrong, but not sure. Let me check.

**Comment by mikaelit** [comment] 2017-05-08 15:52
It wasn't fault by cache. It is because the app_dev.php indicate at autoload.php from vendor not from app folder.

line 22:
https://github.com/symfony/symfony-standard/blob/master/web/app_dev.php

Is that a bug? I don't know but it's resolve for my problem. Thanks a lot!

**Comment by sstok** [comment] 2017-05-08 17:04
@mikaelit No it's not a bug, the master branch of symfony-standard is focused on Symfony 3.3 which removed the need for the autoload.php file 👍 Annotations loader is now automatically enabled #21837 and https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L670

**Comment by ogizanagi** [comment] 2017-05-10 20:58
@mikaelit : If everything regarding your issue is solved you can close this :)

**Closed** 2017-05-10 21:15 UTC
