### ISSUE TITLE
[3.0.2] The service "validator.builder" has a dependency on a non-existent service "apc"

### ISSUE THREAD

**Issue by sunra** [symfony/symfony#17680] opened 2016-02-04 09:38 UTC
after updating to 3.0.2 warming up prod cache ends with this error

downgrading to 3.0.1 helps

**Comment by javiereguiluz** [comment] 2016-02-04 11:07
I've just updated a Symfony application to 3.0.2 and I didn't suffer this bug. Everything went smooth and the application runs without issues.

**Comment by xabbuh** [comment] 2016-02-04 11:27
I too cannot confirm this.

**Comment by raziel057** [comment] 2016-02-04 13:46
You need to replace "apc" by "validator.mapping.cache.doctrine.apc".

```
framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc
```

**Comment by stof** [comment] 2016-02-04 13:48
and btw, having this error meant that you haven't removed all deprecations before upgrading to 3.0, because Symfony 2.8 warns about it.

**Comment by sunra** [comment] 2016-02-04 14:31
Error rise only after this command:
`bin/console cache:clear --env=prod`
 // Clearing the cache for the prod environment with debug false

this commands working without error:
bin/console cache:clear --env=dev
bin/console cache:warmup --env=dev
bin/console cache:warmup --env=prod

**Comment by sunra** [comment] 2016-02-04 14:39
@raziel057

> framework:
>     validation:
>         cache: validator.mapping.cache.doctrine.apc

not wotking for me


> because Symfony 2.8 warns about it.
hm, im upgrading to s3.0.0, and 3.0.1 since it released and all working fine

**Comment by xabbuh** [comment] 2016-02-04 14:52
> not wotking for me

What does that mean? Which error do you get?

> hm, im upgrading to s3.0.0, and 3.0.1 since it released and all working fine

There was an error in 3.0.0 and 3.0.1 preventing to handle that properly.

**Comment by sunra** [comment] 2016-02-04 15:26
@xabbuh it means that error still present.

**Comment by xabbuh** [comment] 2016-02-04 15:34
Exactly the same error message?

**Comment by sunra** [comment] 2016-02-04 15:37
@xabbuh yes, 
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "validator.builder" has a dependency on a non-existent service "apc".

```

after executing command:
`bin/console cache:clear --env=prod`

**Comment by raziel057** [comment] 2016-02-04 15:55
@sunra I had this error with symfony 3.0.1 but it's resolved by https://github.com/symfony/symfony/pull/16795

It works for me. Be sure to restart your web server after upgrading / downgrading to clean APCu.

**Comment by sunra** [comment] 2016-02-04 18:07
@raziel057 i catch this error with 3.0.2. i restart php-fpm every time update and warm up cache - this not help

**Comment by sunra** [comment] 2016-02-06 18:36
After this error prod environment totaly not working

**Comment by xabbuh** [comment] 2016-02-06 19:52
@sunra Can you fork the Symfony standard edition and make the smallest set of changes that is needed to reproduce your issue?

**Comment by Zeichen32** [comment] 2016-02-07 14:22
@sunra Do you already try to delete the cache folder manually and rerun the command again in prod environment?

**Comment by sunra** [comment] 2016-02-07 15:34
@Zeichen32 Yes - it not help

**Comment by sunra** [comment] 2016-02-08 14:04
@xabbuh and all who showed involvement, 
I found problem it hides in my **config_prod.ym**l where i have the following lines
```
framework:
    validation:
        enable_annotations: true
        cache: apc
```

**Closed** 2016-02-08 14:05 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review, Unconfirmed

**Comment by xabbuh** [comment] 2016-02-08 14:34
@sunra Thank you for the update.
