### ISSUE TITLE
Form Choice options with hidden labels 2.8

### ISSUE THREAD

**Issue by dazorni** [symfony/symfony#17773] opened 2016-02-12 08:36 UTC
Hi,

we updated from Symfony `2.6` to `2.8` with the choice options you can find below.
We expected the label of our choice type should be hidden and just the value and the input element exists. In 2.6 this worked for us.

When we upgraded to 2.8 (with the same options) the labels are shown again. The Problem is caused by an empty string in the view, not as expected `false`.

```php
$resolver->setDefaults([
    'choices' => [1 => false, 2 => false, 3 => false, 4 => false, 5 => false],
    'expanded' => true,
    'placeholder' => false,
    'required' => false,
]);
```

So we added a workaround in our `bootstrap_3_layout.html.twig` to resolve this.

```twig
{%- block radio_label -%}
    {% if label == '' or label is null %}
        {% set label = false %}
    {% endif %}

    {{ parent() }}
{%- endblock radio_label -%}
```

Is there a cleaner way to hide the label or is this a bug/bc break?

Thanks

**Comment by HeahDude** [comment] 2016-02-12 09:05
Hi @dazorni, this may be fixed in next releases of symfony by #17760.

Meanwhile using options as below should help :
```php
'choices_as_values' => true,
'choice_label' => function ($choice, $label) {
    return $label;
},
'choice_value' => function ($choice) {
    return false === $choice ? '0' : (string) $choice;
},
```

Can be closed as duplicate of #17292 IMO.

**Comment by dazorni** [comment] 2016-02-12 09:21
Thanks for your fast feedback! I tried this and i won't get the expected result. The labels are still shown...

**Comment by HeahDude** [comment] 2016-02-12 10:04
Of courses I've missed that sorry :) so it is :
```php
'choices_as_values' => true,
'choice_label' => function ($choice, $label) {
    return '';
},
'choice_value' => function ($choice) {
    return false === $choice ? '0' : (string) $choice;
},

**Comment by dazorni** [comment] 2016-02-12 12:58
I tried this and this doesn't also work. Maybe the result i expect will help:

```
<label><input type="radio" value="1"></label>
<label><input type="radio" value="2"></label>
<label><input type="radio" value="3"></label>
<label><input type="radio" value="4"></label>
<label><input type="radio" value="5"></label>
```

The current label value is casted to string. So in the view of the form you get the wrong value (empty string) and not as expected false.

**Comment by backbone87** [comment] 2016-02-12 13:40
I think @HeahDude missinterpreted your use-case:
Maybe the following is correct:
```php
'choices_as_values' => true, // @deprecated remove this in symfony 3+
'choices' => array(1, 2, 3, 4, 5), // the values to be mapped or to be returned by $form->getData(), you can add labels as keys, but they must be unique labels in this case
'choice_label' => function ($value, $key, $index) { // this is the label, with the callback, duplicate labels are possible
    return '';
},
'choice_value' => function ($value, $key, $index) { // this is the content of the input's/option's value attr
    return $value;
},
'choice_name' => function ($value, $key, $index) { // this is the name of the RadioType subform of the ChoiceType form
    return $value;
},
'expanded' => true,
'required' => false,
'placeholder' => false,
```

With this setup you can also freely change the order of the choices array and still access everything "by value" like `jQuery.find("input[type=radio][value=3]"` or `$choiceForm->createView()[3]`, even when changing the choices array to `array(3, 1, 2, 4, 5)`.

**Comment by HeahDude** [comment] 2016-02-12 16:18
@backbone87 :+1:

**Comment by HeahDude** [comment] 2016-02-12 16:22
You can also do `'choice_label' => function() { return false; }`

**Comment by sharpner** [comment] 2016-02-12 18:01
Don't you guys think he read the documentation?

**Comment by backbone87** [comment] 2016-02-12 18:21
@sharpner i dont know what point you are trying to make

**Comment by javiereguiluz** [comment] 2016-02-14 10:09
Closing it as fixed by the answer provided by @backbone87. @dazorni if you don't agree or if the error still persists, please reopen this issue. Thanks!

**Comment by dazorni** [comment] 2016-02-14 16:03
This issue still exists, i tried all of @backbone87's fixes....

**Comment by javiereguiluz** [comment] 2016-02-14 16:04
Reopening then.

**Comment by HeahDude** [comment] 2016-02-14 16:12
Hi @dazorni, could you please try :

```php
$resolver->setDefaults([
    'choices' => [1,  2, 3, 4, 5],
    'choices_as_values` => true,
    'choice_label` => function () { return false; },
    'expanded' => true,
    'placeholder' => false,
    'required' => false,
]);
```

That works for me.

**Comment by alcaeus** [comment] 2016-02-14 16:23
Working around with these options is not going to change the fact that the view will always return an empty string, no matter if the label callback returns false, null or whatever. This is due to a string cast in `DefaultChoiceListFactory`: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L127. So, @dazorni can try returning false from a label callback all he wants, it's always going to be cast to a string.

This brings us to part 2 of this whole thing, the view. `form_div_layout.html.twig` has a check in the `form_label` block to decide whether to show a label or not, which checks for `false`: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L211

So, with the return value of the label callback being cast into a string and the view comparing it with boolean false, there's no way to hide these labels.

**Comment by HeahDude** [comment] 2016-02-14 16:48
@alcaeus is right,

You need to normalize `label` in `DefaultChoiceListFactory` :
```php
private static function addChoiceView($choice, $value, $label, $keys, &$index, $attr, $isPreferred, &$preferredViews, &$otherViews)
{
    // $value may be an integer or a string, since it's stored in the array
    // keys. We want to guarantee it's a string though.
    $key = $keys[$value];
    $nextIndex = is_int($index) ? $index++ : call_user_func($index, $choice, $key, $value);

    // Start  normailzation of label
    if (null === $label) {
        $label = (string) $key;
    } else {
        $customLabel = call_user_func($label, $choice, $key, $value);
        $label = false === $customLabel ? false : $customLabel;
    }
    // end normalization

    $view = new ChoiceView(
        $choice,
        $value,
        // If the labels are null, use the original choice key by default

        // Fix by commenting the line below
        // null === $label ? (string) $key : (string) call_user_func($label, $choice, $key, $value),
        $label,
        // end fix

        // The attributes may be a callable or a mapping from choice indices
        // to nested arrays
        is_callable($attr) ? call_user_func($attr, $choice, $key, $value) : (isset($attr[$key]) ? $attr[$key] : array())
    );

**Comment by HeahDude** [comment] 2016-02-14 16:57
Another way without tweaking the core would be to use `#field_id label {display: none; }`

**Comment by dazorni** [comment] 2016-02-14 17:05
So it is a BC Break right? @HeahDude

**Comment by HeahDude** [comment] 2016-02-14 17:08
@dazorni How that ? It could if one used `choice_label` with a callable returning `false` and expected a label as `'0'`

**Comment by alcaeus** [comment] 2016-02-14 17:19
Gave it a quick spin. With 2.6 the configuration specified in the original post would yield 5 radio inputs without a label text. With 2.7 the configuration will yield 5 radio inputs, each with their name as label (this is because

**Comment by HeahDude** [comment] 2016-02-14 17:43
So this is a BC, I send a PR with the fix above.

**Comment by dazorni** [comment] 2016-02-14 18:11
Thanks to @alcaeus

**Comment by javiereguiluz** [comment] 2016-02-14 18:33
@alcaeus yes, let's label it as "BC break".

**Comment by HeahDude** [comment] 2016-02-14 19:39
Tests on #17798 are passing now, if it's merged you will be able to to :

```php
$resolver->setDefaults([
    'choices' => [1, 2, 3, 4, 5],
    'choices_as_values' => true,
    'choice_label' => false,
    'expanded' => true,
    'placeholder' => false,
    'required' => false,
]);

// or even
$resolver->setDefaults([
    'choices' => [1, 2, 3, 4, 5, 'Some other choice'],
    'choices_as_values' => true,
    'choice_label' => function ($choice) {
        if (in_array($choice, range(1, 5)) {
            return false;
        }

        return 'label.'.$choice;
    },
    'expanded' => true,
    'placeholder' => false,
    'required' => false,
]);
```

**Comment by alcaeus** [comment] 2016-02-15 07:58
@HeahDude thanks - what about the original config that does not specify a `choice_label`?
```
$resolver->setDefaults([
    'choices' => [1 => false, 2 => false, 3 => false, 4 => false, 5 => false],
    'expanded' => true,
    'placeholder' => false,
    'required' => false,
]);
```

**Comment by HeahDude** [comment] 2016-02-15 09:36
@alcaeus it does not seem impacted by the BC break, tested and works as expected AFAIK on 2.7.

Can someone else confirm ?

**Comment by backbone87** [comment] 2016-02-15 18:39
Imo, this BC break should only be fixed for 2.x and not for 3.x
The change in 3.x should be done within the form template, because an empty label doesnt make much sense from a users perspective, so the check at https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L211 should be `is not empty`

**Comment by HeahDude** [comment] 2016-02-15 22:48
@backbone87, I don't agree with you on this point, there's a real use case for empty label (I often use it myself), allowing to customise form with css. Empty label is not the same as no label, and both should be handled.
Besides a fix would need consistency in all branch IMHO, maintaining two different ways would give headaches to a merger.

**Comment by backbone87** [comment] 2016-02-16 12:43
@HeahDude at least the implications of empty vs no label in terms of accessibility should be mentioned in the form type reference.

**Comment by HeahDude** [comment] 2016-02-16 15:57
@backbone87 it's consistent with the `label` option as said in http://symfony.com/doc/2.7/reference/forms/types/form.html#label
>Sets the label that will be used when rendering the field. Setting to false will suppress the label.

Do think it misses "a label can be an empty string" ? I'm not sure but why not ?

However an update for `choice_label` mentioning it can be `false` would be welcome indeed, it's in the todo list of #17798.

**Comment by backbone87** [comment] 2016-02-16 17:56
A form element without a label is (in general) very hard to use for people using screenreaders. It should be noted that it is not recommended to omit or use empty labels for form elements. If you need extra elements for styling purposes, you can do this in the form theme.

**Comment by HeahDude** [comment] 2016-02-16 22:39
Matter of choice, but one need to be able to choose , a few lines in a (must-edit) form type are more handy that overriding a theme IMO, also you can use `label_attr` for __aria__ data.

**Closed** 2016-02-28 14:59 UTC
Labels: BC Break, Bug, Form, Status: Needs Review
