### ISSUE TITLE
Symfony 2.8 composer.lock reference doctrine/orm

### ISSUE THREAD

**Issue by GitHubGitGud** [symfony/symfony#17056] opened 2015-12-17 18:27 UTC
"name": "doctrine/orm",
    "version": "v2.4.8",
    "source": {
        "type": "git",
        "url": "https://github.com/doctrine/doctrine2.git",
        "reference": "464b5fdbfbbeb4a65465ac173c4c5d90960f41ff"
    }

When the doctrine/ORM bundle is downloaded by composer (URL: https://api.github.com/repos/doctrine/doctrine2/zipball/464b5fdbfbbeb4a65465ac173c4c5d90960f41ff) always the default=last version is returned. I don't know if other references are faulty, too.

**Comment by xabbuh** [comment] 2015-12-17 18:45
I am sorry but I do not understand what you are trying to ask and how this is related to Symfony. Can you please explain your problem a bit more?

**Comment by GitGutHub** [comment] 2015-12-17 18:52
I need to install symfony in version 2.8 because of an old PHP version 5.3.17.
When I do this via composer, the bundles are installed according to composer.lock. At least the reference for doctrine/orm in composer.lock is faulty and does not return the requestet version (which would be 2.4.8) but the actual. The actual version requires php >=5.4, but symfony 2.8 requires >=5.3.9.
I hope it's clear now.

**Comment by xabbuh** [comment] 2015-12-17 19:00
No, I still don't understand. What steps exactly do you perform and which version of `doctrine/orm` do you end up with then?

**Comment by WouterJ** [comment] 2015-12-17 19:03
@xabbuh the problem here is that while the `version` key indicates 2.4.8, the commit hash refers to the 2.5.2 release (https://github.com/doctrine/doctrine2/commit/464b5fdbfbbeb4a65465ac173c4c5d90960f41ff).

**Comment by GitGutHub** [comment] 2015-12-17 19:05
exactly. the "commit hashes" need to be updated.

**Comment by stof** [comment] 2015-12-17 19:15
Well, there is no lock file in this repo.

And regarding the symfony-standard lock file, this is weird: the SE repo does not contain 2.4.8 at all in the lock file, but 2.5.2 (which is its own issue, see https://github.com/symfony/symfony-standard/issues/858)

**Comment by xabbuh** [comment] 2015-12-17 19:16
@GitGutHub I see but how did you end up with this situation (that's why I asked for the exact steps your performed)?

**Comment by GitGutHub** [comment] 2015-12-17 19:53
My bad.
Actually the downloaded lock requests v2.5.2:

    "name": "doctrine/orm",
    "version": "v2.5.2",
    "source": {
                "type": "git",
                "url": "https://github.com/doctrine/doctrine2.git",
                "reference": "464b5fdbfbbeb4a65465ac173c4c5d90960f41ff"
    },

Anyway, it *should* be v2.4.8 since symfony 2.8 requests php >=5.3.9 (but doctrine/orm v2.5.2 php >=5.4) I simply *can't* use it. My application crashes. I think this should be fixed. It's a real pain for a beginner with symfony. And it was a long way to figure out what's wrong...

(In the meantime I downloaded the appropriate doctrine/orm version manually.)

**Comment by xabbuh** [comment] 2015-12-17 19:58
@GitGutHub see  symfony/symfony-standard#858

**Comment by Pierstoval** [comment] 2015-12-17 20:52
@GitGutHub You can actually solve this by updating your `composer.json` to require `^2.4` and run  `composer update`. It shouldn't be that harmful if it's a new application.

**Comment by Tobion** [comment] 2015-12-18 11:26
Closing as duplicate of symfony/symfony-standard#858

**Closed by Tobion** 2015-12-18 11:26 UTC
