### ISSUE TITLE
export: BASH_FUNC_generate_command_executed_sequence%%: bad variable name

### ISSUE THREAD

**Issue by apsylone** [symfony/symfony#21881] opened 2017-03-05 18:38 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

Taking from this ticket : https://github.com/symfony/assetic-bundle/issues/428
Have the same problem.

**Comment by nicolas-grekas** [comment] 2017-03-05 18:40
Duplicate of https://github.com/symfony/symfony/issues/21704
Fixed by https://github.com/symfony/symfony/pull/21776

**Closed by nicolas-grekas** 2017-03-05 18:40 UTC
