### ISSUE TITLE
How to restrict a symfony minor version for a project

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#31851] opened 2019-06-04 12:04 UTC
**Description**  

ATM, it's not possible to stick to a specific version of Symfony.
One of our application was using Symfony 4.2.*. With the release of Symfony 4.3.0 we get
some packages at 4.3.0. But there are some bugs (already fixed, but not released yet) that
prevent us to stay on 4.3.0

**How to reproduce**  

```bash
composer create-project symfony/website-skeleton sf-42 '4.2.*'
cd sf-42
rm -rf vendor/ # This line is SUPER important
composer up
```

**Comment by stof** [comment] 2019-06-04 12:07
well, Flex has a way to do that. But if you run a `composer update` without Flex installed (because you deleted the vendor folder and you don't have it globally), Flex won't be able to restrict that as it won't run (it cannot run if it is not installed).

**Comment by nicolas-grekas** [comment] 2019-06-04 12:11
Closing as duplicate of https://github.com/symfony/flex/issues/450, which is pending a PR ;)

**Closed by nicolas-grekas** 2019-06-04 12:11 UTC

**Comment by nicolas-grekas** [comment] 2019-06-04 12:14
Meanwhile: `composer global require symfony/flex`
