### ISSUE TITLE
Validate expanded multiple choice

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#14957] opened 2015-06-12 05:13 UTC
Is there a way to validate an expanded multiple choice? I have the following choice in a form:

``` php
$builder
            ->add('action', 'choice', array(
                'required'    => true,
                'empty_value' => 'Select an action',
                'choices'     => array(
                    BulkEmailModel::ACTION_SEND   => 'Send emails',
                    BulkEmailModel::ACTION_DELETE => 'Delete emails',
                )
            ))
            ->add('emails', 'choice', array(
                'multiple'    => true,
                'expanded'    => true,
                'choice_list' => new ObjectChoiceList($emailEntities, 'id', array(), null, 'id'),
            ))
        ;
```

Validation:

``` yaml
Acme\Demo\Form\Model\BulkEmailModel:
    properties:
        action:
            - NotBlank: ~
        quotes:
            - Count:
                min: 1
                minMessage: 'Please select at least 1 email.'
            - All:
                - NotBlank: ~
                - Blank: ~
```

It appears as though the choice does validate. However, the errors are in the wrong location. It looks like it use using the index based on the selected choices (not all the choices). See screenshot below:

![screen shot 2015-06-12 at 3 04 47 pm](https://cloud.githubusercontent.com/assets/869933/8123912/450ab50c-1115-11e5-8786-187467e50497.png)

**Comment by webmozart** [comment] 2015-06-12 09:04
Hi @trsteel88, thank you for opening this issue! Could you please upload a fork of symfony-standard that reproduces your problem?

**Comment by trsteel88** [comment] 2015-06-15 21:43
Done @webmozart. See https://github.com/trsteel88/symfony-standard-1/tree/form-issue

1. Go to /app/example
2. Tick "Entity 3 (not sendable)" and submit the form
3. Validation error appears on the top choice (not the one you selected).

I think the error is being placed on the choices based on the submitted index (not the data index).

**Comment by deguif** [comment] 2015-06-16 17:44
I just took time to have a look at this problem, but I think the behaviour is normal.
As you're using some checkboxes, when checkbox is not checked, its value is not sent.
So the array retrieved on server side is only composed of one item, the third, it's property_path (index) reference the first index which lead to first item being marked as errored.

**Comment by trsteel88** [comment] 2015-06-17 02:04
How would you go about validating choices that people are choosing then? The use-case is that I want to validate if an entity can be "Sent".

I have different "actions" will be valid for different choices. e.g some choices can be "Sent" (some can't), some choices can be "Deleted" (some can't). However, the checkbox must always be there.

If the user selects a choice and it can't be "Sent" or "Deleted", I want that error to sit next to that expanded choice.

**Comment by xabbuh** [comment] 2017-06-21 15:43
@trsteel88 Are you able to resubmit the example project to make it possible to reproduce your issue?

**Comment by xabbuh** [comment] 2017-11-13 09:27
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed by xabbuh** 2017-11-13 09:27 UTC
Labels: Bug, Form, Status: Waiting feedback, Unconfirmed
