### ISSUE TITLE
3.3 generate:bundle doesn't register autoload

### ISSUE THREAD

**Issue by skilltryck** [symfony/symfony#23496] opened 2017-07-13 09:17 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3

Bundles generated with Symfony 3.3 won't register any autoload (probably since ClassLoader is deprecated) and thus not working with PHP5 (not tested on PHP7).

**Comment by chalasr** [comment] 2017-07-13 13:08
duplicate of https://github.com/symfony/symfony-standard/issues/1098 on the wrong place?

**Closed** 2017-07-13 16:22 UTC
