### ISSUE TITLE
Allow to define an empty prefix for translation:update command

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20044] opened 2016-09-24 10:45 UTC
### Context

When using the `translation:update` command to generate a translation file, the translated strings are just the original strings with the `__` prefix (e.g. original `Contact us`, "translation": `__Contact us`). This value can be changed with the `--prefix` option.
### Problem

When generating the translation file for the original language, I want to use an empty prefix. It seems impossible to do that because of the way Symfony Console options work:

``` bash
$ ./bin/console translation:update en --dump-messages
# translation prefix = '__';

$ ./bin/console translation:update en --dump-messages --prefix=""
# translation prefix = '__';   <-- ERROR: I expected here an empty prefix

$ ./bin/console translation:update en --dump-messages --prefix=" "
# translation prefix = ' ';

$ ./bin/console translation:update en --dump-messages --prefix="aaa"
# translation prefix = 'aaa';
```

I think in the past we had some issues reported for the way console options work, but I can't find the issues. Considering that setting an option with an empty value is the same as not setting that option looks confusing and it could even be considered a bug.

**Comment by iltar** [comment] 2016-09-24 13:45
@javiereguiluz are you referring to this one? #19946, it's merged already 👍

**Comment by javiereguiluz** [comment] 2016-09-24 13:54
@iltar thanks for the heads up. I totally missed the fix made by the great @chalasr !

Closing it as fixed then.

**Comment by lordjancso** [comment] 2016-10-07 12:57
@javiereguiluz I think it's still not working with empty string. Did you test it?

**Comment by chalasr** [comment] 2016-10-07 19:15
@lordjancso Empty values should be correctly handled since releases `v2.7.19`,  `v2.8.12` and `v3.1.5`.

**Comment by lordjancso** [comment] 2016-10-07 19:36
@chalasr I'm using 3.1.5 and its still not working. When I execute translation:update with --prefix="" its still not an empty string, because it passes NULL instead of empty string. And as far as I know, NULL is not an empty string.

**Comment by chalasr** [comment] 2016-10-07 19:44
@lordjancso Yeah, this is the expected behavior. The issue is about that the option was not considered to be set at all, throwing an exception if the option requires a value. Now it converts any empty value into `null`.

If you think it should not be converted (that I can perfectly understand), please open an issue/PR for proposing to change this

**Comment by lordjancso** [comment] 2016-10-08 07:11
@chalasr I see your point but this issue is about allowing to define empty string prefix for translation:update command and since it's still not working, I suggest to re-open it.

**Comment by chalasr** [comment] 2016-10-08 10:15
@javiereguiluz @lordjancso See https://github.com/symfony/symfony/issues/20044

**Comment by chalasr** [comment] 2016-10-08 10:29
@javiereguiluz The following example:

```sh
$ ./bin/console translation:update en --dump-messages --prefix=""
# $prefix = '__';   <-- ERROR: I expected here an empty prefix
```

Should be:

```sh
$ ./bin/console translation:update en --dump-messages --prefix=""
# $prefix = null;   <-- ERROR: I expected here an empty string
```

Could you please update the description?

**Comment by javiereguiluz** [comment] 2016-10-08 10:40
@chalasr I was referring to the effective prefix used for translations instead of the value of the $prefix variable. But you are right and I've just updated the description to avoid confusion. Thanks!

**Comment by chalasr** [comment] 2016-10-08 10:44
@javiereguiluz Yeah, sorry I forgot to precise it needs to be updated since #19946 only

**Closed** 2016-11-11 15:54 UTC
Labels: Feature, Translator
