### ISSUE TITLE
Migration from Form AbstractType setDefaultOptions() to configureOptions broken by concrete injection

### ISSUE THREAD

**Issue by bryanagee** [symfony/symfony#14827] opened 2015-06-02 06:01 UTC
Since ::setDefaultOptions() required an interface, you could inject any OptionResolver interface. The ::configureOptions method requires a concrete type instead. The largest impact is that any overriding method will throw a notice due to the mismatched signature.

**Comment by bryanagee** [comment] 2015-06-02 06:10
Is there a specific reason the signature was changed to concrete? I can see that @peterrehm made the change in commit:3d43caef88db7226986d43ec98313cb3b5ee600c, but I don't see an explanation for the switch.

**Comment by jakzal** [comment] 2015-06-02 07:01
see #12782 and #12891

When migrating you should obviously change the signature, not just the method name. A new method was chosen to make migration easier.

What's your issue about? Have you implemented the interface yourself?

**Comment by bryanagee** [comment] 2015-06-02 07:06
We haven't implemented the interface, but I'm curious as to why there is a break in the use of Interface Injection in this specific instance.

I can certainly go back and change all of those classes to use the new signature, but I'm not keen on it without understanding why the deviation from normal practice is there in the first place.

**Comment by jakzal** [comment] 2015-06-02 07:38
As written in [UPGRADE-2.6.md](https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.6.md#optionsresolver):

>  * The interface `OptionsResolverInterface` was deprecated, since
   `OptionsResolver` instances are not supposed to be shared between classes.
   You should type hint against `OptionsResolver` instead.

Closing, as this is not a bug.

**Closed by jakzal** 2015-06-02 07:38 UTC
Labels: Form

**Comment by bryanagee** [comment] 2015-06-02 07:46
So essentially, other implementations of OptionsResolver are no longer supported?

The quote from the UPGRADE document doesn't really address the question as to why. Sharing of the instances seems to have little to do with InterfaceInjection. Am I missing something? Forgive me if this is a stupid question.

**Comment by jakzal** [comment] 2015-06-02 07:49
We simply don't want to support alternative implementations of the OptionsResolver.

**Comment by Tobion** [comment] 2015-06-02 09:40
The point is that working with interfaces makes it hard to impossible to improve the optionsresolver itself since we cannot introduce new/changed methods in the inteface without breaking bc. But we can easily add new methods to the optionsresolver implementation. So in this case we decided it's not worth to provide an interface that nobody would reimplement anyway.

**Comment by bryanagee** [comment] 2015-06-02 09:42
@Tobion - makes sense; thank you for explaining the why. I will migrate those with the updated signature.

Cheers
