### ISSUE TITLE
Symfony 3.2-RC1 errors in the Symfony Profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20556] opened 2016-11-18 07:27 UTC
In https://github.com/symfony/symfony-demo/pull/403 I've just updated the Symfony Demo app to Symfony 3.2-RC1 and Twig 1.28. I have a lot of issues in the Symfony profiler:

1) The few profiler panels that work right mess up the entire sidebar menu:

![error_1](https://cloud.githubusercontent.com/assets/73419/20422117/a74a5fe2-ad68-11e6-9a04-964d7d3069f9.png)

![error_2](https://cloud.githubusercontent.com/assets/73419/20422119/a97b754e-ad68-11e6-8454-bd6e1621733a.png)

2) Most of the profiler panels don't work and display a lot of errors:

![error_3](https://cloud.githubusercontent.com/assets/73419/20422126/b54531d0-ad68-11e6-9b09-bab1206b990a.png)

![error_4](https://cloud.githubusercontent.com/assets/73419/20422129/b640d918-ad68-11e6-8c35-756182d36315.png)

![error_5](https://cloud.githubusercontent.com/assets/73419/20422131/b78e0e94-ad68-11e6-9078-bc68217f3639.png)

**Comment by javiereguiluz** [comment] 2016-11-18 08:14
I've just upgraded an internal Symfony app to 3.2-rc1 and I'm getting the same errors.

**Comment by Cydonia7** [comment] 2016-11-18 08:19
Status: Reviewed

I reproduced the bug on symfony demo upgrading `symfony/symfony` to `dev-master`. Thanks @javiereguiluz for reporting such an important issue.

**Comment by derrabus** [comment] 2016-11-18 15:53
I can reproduce this on the 2.7 branch as well. This commit by @fabpot seems to be the one that breaks everything: https://github.com/symfony/symfony/commit/b8f7614388ad567b647f64650271bc51e7a9c624

If I simply revert that commit on 2.7, everything's fine again.

**Comment by derrabus** [comment] 2016-11-18 17:34
I have created PR twigphp/Twig#2269 that fixes this issue. But maybe we should revert the commit I've mentioned above until the issue is fixed in Twig.

**Comment by stof** [comment] 2016-11-18 17:57
I don't think we need reverting this, as Symfony 2.7 does not have an impacted release yet. We just need to release Twig 1.28.1 before the next Symfony 2.7 patch release (which is under our control as @fabpot is doing releases on both sides)

**Closed** 2016-11-19 05:51 UTC
Labels: Bug, Critical, Status: Reviewed, WebProfilerBundle
