### ISSUE TITLE
[Question][Form] date Field Type limitation

### ISSUE THREAD

**Issue by florida63** [symfony/symfony#15325] opened 2015-07-21 17:05 UTC
Hello,

Why a date field with the options below is it limited. Choice available between 1902 and 2037?

``` php
$Builder-> add ('date', 'date', array (
    'input' => 'datetime'
    'widget' => 'choice'
    'years' => range (1850,2050) "
));
```

documentation says:

> If timestamp is used, DateType is limited to dates entre Fri, Dec. 13, 1901 8:45:54 p.m. GMT and Tue, January 19, 2038 3:14:07 GMT on 32bit systems. This is due to a limitation in PHP Itself.

Is it normal that the option datetime have the same limitation?
For information i use symfony 2.3

Thank you for this great framework.

**Comment by adamziel** [comment] 2015-07-22 23:13
Something must be wrong in another place in your project, this is what I get on default Symfony 2.3 project:
![Sf2.3](https://cloud.githubusercontent.com/assets/205419/8839647/04871e02-30d8-11e5-9679-0342d2913d78.png)

```php

class DefaultController extends Controller
{
    /**
     * @Route("/app/example", name="homepage")
     */
    public function indexAction()
    {
        return $this->render('default/index.html.twig', [
            'form' => $this->createFormBuilder()
                           ->add('date', 'date', array (
                                'input' => 'datetime',
                                'widget' => 'choice',
                                'years' => range(1850,2050)
                           ))
                           ->getForm()
                           ->createView()
        ]);
    }
}
```

**Comment by adamziel** [comment] 2015-07-23 00:29
DateTime handling of things should be fine on a 32bit system:

```
php > echo (new \DateTime('Jan 25, 2050'))->format('d-m-Y H:i:s');
25-01-2050 00:00:00

php > echo date('d-m-Y H:i:s', strtotime('Jan 25, 2050'));
01-01-1970 01:00:00
```

You may have found a bug

**Comment by adamziel** [comment] 2015-07-23 00:41
The root cause is in here:

https://github.com/symfony/symfony/blob/05f3c3db7b6b46ba10a2b54178f97a21bf4161a8/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L292

Those list* methods will only list those dates that are valid in terms of `gmmktime`, and on 32bit system it only handles the range you mentioned (`Fri, Dec. 13, 1901 8:45:54 p.m. GMT and Tue, January 19, 2038 3:14:07 GMT`). The 1902 and 2037 comes from the implementation detail of those list* methods.

This is actually a duplicate of https://github.com/symfony/symfony/issues/10096 but you pointed out an important detail about the documentation.

I think there are two solutions:

* replace gmmktime check with something else - what are potential implications of that?
* update the documentation and explicitly state that there is no special treatment for `"input"=>"datetime"` on 32bit systems

**Comment by florida63** [comment] 2015-07-23 08:53
Thank you for the clarification.

In all cases, it is necessary to update the documentation.

**Comment by xabbuh** [comment] 2015-07-24 06:51
@florida63 Can you please open an issue on [the docs repository](https://github.com/symfony/symfony-docs)?

**Comment by xabbuh** [comment] 2018-09-14 12:10
closing here as this is a documentation issue

**Closed by xabbuh** 2018-09-14 12:10 UTC
Labels: Bug, Form, Status: Needs Review
