### ISSUE TITLE
The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps".

### ISSUE THREAD

**Issue by chatisk** [symfony/symfony#59040] opened 2024-11-29 14:31 UTC
### Symfony version(s) affected

Symfony/mailer 7.2.0

### Description

Hello,

I am coming from Laravel, i am using custom smtp settings per tenant (i have a multi tenancy, stancl/tenancy). Once I upgraded to 7.2.0 of symfony/mailer, i started getting

`The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps".`

Downgraded to 7.1.6, and I dont have the issue anymore

### How to reproduce

The custom smtp is connected to gmail. (smtp.gmail.com), port 465, ssl encrypted. Each notification that had to be sent via mail, it failed.

### Additional Context

I wish I could provide more context.

This is what Sentry says 
`Symfony\Component\Mailer\Exception\UnsupportedSchemeException
The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps".`

**Comment by xabbuh** [comment] 2024-11-29 15:10
Without more details it will become hard to help you. Please try to get more information (e.g. a stack trace) or provide a small application that allows to reproduce it.

**Comment by S1r-Lanzelot** [comment] 2024-11-29 15:20
@xabbuh Here is a stack trace (we are not associated with the OP), we recently did an update from 7.1.6 -> 7.2 and ran into this error. We did not have the mailer config scheme defined, as it was not needed in previous versions.
```
Symfony\Component\Mailer\Exception\UnsupportedSchemeException: The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps".
#88 /vendor/symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php(28): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory::create
#87 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(202): Illuminate\Mail\MailManager::createSmtpTransport
#86 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(181): Illuminate\Mail\MailManager::createSymfonyTransport
#85 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(146): Illuminate\Mail\MailManager::build
#84 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(123): Illuminate\Mail\MailManager::resolve
#83 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(101): Illuminate\Mail\MailManager::get
#82 /vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(79): Illuminate\Mail\MailManager::mailer
#81 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Illuminate\Support\Facades\Facade::__callStatic
```

**Comment by stof** [comment] 2024-11-29 15:25
how does your DSN look like ?

**Comment by S1r-Lanzelot** [comment] 2024-11-29 15:37
https://github.com/symfony/mailer/commit/66ae5ca3d980eba65f4a352e9629c69b7928cb69#diff-034fdf635bc919f1ba58fb3cac83ce59f111a73c1ee72d63055f752c4b3668ddR27 is the culprit I believe. Which is fine I suppose, I just couldnt find the breaking change notice.

**Comment by stof** [comment] 2024-11-29 15:47
I don't think supporting unsupported schemes in `EsmtpTransportFactory` was ever intended nor documented as supported. Its implementation of `getSupportedSchemes` has *always* returned only `smtp` and `smtps`.

and if Laravel had used the `Symfony\Component\Mailer\Transport` entrypoint to parse the DSN and create a transport from it, it would already have failed in older version (which is probably none of the Symfony contributors discovered an empty scheme as supported by accident before).

**Comment by S1r-Lanzelot** [comment] 2024-11-29 15:49
Yes that is fine. I don't think this requires a code change but at least this issue will serve as a landing page for people who didnt specify a scheme in their laravel mail config and now receive this `UnsupportedSchemeException` in 7.2.

**Comment by stof** [comment] 2024-11-29 15:54
@S1r-Lanzelot https://github.com/laravel/framework/pull/53585 has been merged, restoring the ability of not defining a scheme in Laravel (by making laravel provide the right scheme). So you only need to wait for the next Laravel release.

**Comment by S1r-Lanzelot** [comment] 2024-11-29 15:55
Ahh excellent, thank you for finding!

**Comment by xabbuh** [comment] 2024-11-29 17:38
Let’s close here then. Thanks everyone for the feedback.

**Closed as not planned by xabbuh** 2024-11-29 17:38 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback, Mailer
