### ISSUE TITLE
[Suggestion] Adding .gitattributes to ignore unnecessary folders and files for production env

### ISSUE THREAD

**Issue by arcanedev-maroc** [symfony/symfony#20057] opened 2016-09-25 20:36 UTC
The trick is by using the `export-ignore`: https://git-scm.com/docs/gitattributes#__code_export_ignore_code

This is useful when we want to upload the app into the shared host with FTP.

For example: https://github.com/ARCANEDEV/LogViewer/blob/master/.gitattributes

**Comment by iltar** [comment] 2016-09-26 08:52
And don't forget all `Tests` directories :+1:

**Comment by mvrhov** [comment] 2016-09-26 09:11
Please look at previous suggestions, this is a NO.

**Comment by iltar** [comment] 2016-09-26 10:00
@mvrhov code that you use in production shouldn't have testing code or files that are not used in production. Even when developing you don't want all the files that come along with a framework but are not used by you (like test files). It greatly increases the amount of files which your IDE will index (especially with a FW as big as Symfony) and those files serve 0 purpose.

**Comment by mvrhov** [comment] 2016-09-26 10:30
No I want the tests. And I'm installing everything with preferred-install:dist For deploy I have a script which removes everything for me.

**Comment by iltar** [comment] 2016-09-26 10:56
If you want the tests, clone the repository

**Comment by jakzal** [comment] 2016-09-26 15:45
re #17995 #11810 #5674

**Comment by iltar** [comment] 2016-09-26 17:01
It seems to be a recurring subject and the only reason people want to have it, is something that can be achieved by actual means. I would like to quote Saeldek: https://github.com/symfony/symfony/issues/20032#issuecomment-249176045
> as you are trying to run phpunit as far as I understand, and not develop it.
We're trying to run Symfony in our own packages, not develop it. That means we don't need all the extra code neither in our development nor production servers.

When searching for classes, you _always_ get polluted results;
 - Searching for `CacheItem` will show me https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Tests/CacheItemTest.php
 - Searching for implementations of `CacheItemPoolInterface` will result in finding https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Tests/Fixtures/ExternalAdapter.php
 - It leads to confusing locations where to put classes, as this one should obviously be a Test namespace/extension point: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/MockArraySessionStorage.php

People might end up hinting against those classes which is extremely unhelpful for newer developers. Next to this, your IDE autocompletion is polluted with stuff you don't care about (yes, even `SessionTest` will come up when looking at `Session`). In case you DO need the tests for what reason ever, you can always simply fork/clone the repository.

**Comment by arcanedev-maroc** [comment] 2016-09-26 17:15
Thanks @jakzal @iltar for including these references.

I know it's a **big issue**, because we need to split the ecosystem of our applications into separate environments (dev/testing/production) and the only way to *"clean the mess"* is by doing it manually for each project (and if we use a `script` to clean the packages, we need to maintain it).

Now *Composer* is a main tool for every PHP Developer, the `--prefer-dist` and `--prefer-source` doesn't make a big difference at this point in time because we end up with all the files used for development (docs, tests, examples, etc) for each installed package.

 > Who wants the tests/docs in their production environments ?

I love the [Laravel framework approach](https://github.com/laravel/framework/tree/master/tests) for grouping all the tests into a single folder.

PS: @jakzal I love your talks/videos 👍.

**Comment by iltar** [comment] 2016-09-26 17:36
@arcanedev-maroc the strategy that I follow is quite simple:
```json
  "autoload": {
    "psr-4": {"Iltar\\HttpBundle\\": "src/"}
  },
  "autoload-dev": {
    "psr-4": {"Iltar\\HttpBundle\\": "test/"}
  }
```
I agree with *(don't ever dare to quote me)* Laravel on this matter, yet have to say that this is (nearly) impossible for Symfony due to the Subtree split.

> Who wants the tests/docs in their production environments ?

I don't need them in dev either, I have a browser for this, they are just polluting my search results.

**Comment by nicolas-grekas** [comment] 2016-09-26 18:15
Then help fix https://github.com/editorconfig/editorconfig/issues/228, this is the real issue...

**Comment by iltar** [comment] 2016-09-26 19:04
It should still work if you have only poor tooling available (Say Eclipse PDT). shouldn't have to rely on editors ignore stuff that shouldn't be there in the first place if you ask me and feels like a work-around for something. If I'm using command-line searching, the editor config won't really be of much service to me either afaik. With ~180 packages installed locally, I don't always use an IDE to open/edit/find stuff.

**Comment by jakzal** [comment] 2016-09-27 08:56
Another use case for making vendor dir lighter is to make docker images smaller. In the age of microservices this is becoming more and more important. Removing tests from the Symfony Demo cuts 13M.

**Comment by arcanedev-maroc** [comment] 2016-09-29 22:22
And there is more: #5367 #6047 #6374 #6605 #16174

**Comment by nicolas-grekas** [comment] 2017-02-17 10:42
Closing as already confirmed several times.
Note that with Flex, we're going to not use symfony/symfony directly that often anymore - that may help.

**Closed by nicolas-grekas** 2017-02-17 10:42 UTC
Labels: RFC
