### ISSUE TITLE
File Constraint not overwrite custom message

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#39107] opened 2020-11-18 14:20 UTC
**Symfony version(s) affected**: 4.4.16

**Description**  
When uploadIniSizeErrorMessage is present to File Constraint not overwrite initial message.

**How to reproduce**  

Simple form

```php

class AddFileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'files',
                FileType::class,
                [
                    'multiple'       => true,
                    'error_bubbling' => true,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'required' => false,
            ]
        );
    }
}
```

Simple dto with constraint

```php
final class AddFileCommand
{
    /**
     * @var array<UploadedFile>
     * @Assert\NotBlank(message="Veuillez sélectionner un fichier.")
     * @Assert\All({
     *     @Assert\File(
     *         maxSize = "500k",
     *         maxSizeMessage = "Custom message max size.",
     *         uploadIniSizeErrorMessage = "Custom message max size ini",
     *         uploadFormSizeErrorMessage = "Custom message max size form",
     *     )
     * })
     */
    public $files;
}
```
Result
![image](https://user-images.githubusercontent.com/10476280/99541358-084ac480-29b1-11eb-9915-267e2677c746.png)

![image](https://user-images.githubusercontent.com/10476280/99541480-287a8380-29b1-11eb-8af2-ca54b9312a9f.png)

Normally we should only see

```
Custom message max size in
```

**Comment by stof** [comment] 2020-11-18 14:32
That's because you have 2 separate errors being reported here:

- one by the `File` constraint in your model
- one by the `FileType` form itself, outside the validator (which is why it does not have a `caused by` btw)

And the one from FileType is not configurable: https://github.com/symfony/symfony/blob/3c0cfbcb8cf322666d13bbde4e7cd469c360e6c1/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L149-L173

**Comment by thewalkingcoder** [comment] 2020-11-18 14:51
ok @stof i understand.

 any suggestion to have one error display ? not use FileConstraint and create customConstraint ? catch exception and do nothing with that ?

```php
public function filesUpload(Request $request)
    {
        $command = new AddFileCommand();
        $form = $this->createForm(AddFileType::class, $command);

        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {
            $this->commandBus->dispatch($command);
        }
}
`

**Comment by xabbuh** [comment] 2020-11-18 17:26
closing as a duplicate of #36503

**Closed as completed by xabbuh** 2020-11-18 17:26 UTC
Labels: Form, Validator, Bug, Status: Needs Review

**Comment by xabbuh** [comment] 2020-11-19 18:58
Can you please check if #39119 fixes this?

**Comment by thewalkingcoder** [comment] 2020-11-19 19:19
@xabbuh yep i try that tomorow, thanks.
