### ISSUE TITLE
Callback Constraint Violation not added when using Form Event SUBMIT

### ISSUE THREAD

**Issue by webdevilopers** [symfony/symfony#17627] opened 2016-01-31 13:44 UTC
My callback:
```php
    /**
     *
     * @param ExecutionContextInterface $context
     *
     * @Assert\Callback(groups={
     *  "flow_dormerRequest_step3", "flow_bayWindowRequest_step2",
     *  "flow_loggiaRequest_step3", "rollerShutter"
     * })
     */
    public function isRollerShutterValid(ExecutionContextInterface $context)
    {
        if ($this->getRollerShutter() != '1') {
            return;
        }

        if ($this->getRollerShutterType() === null) {
            $context->buildViolation('type.blank')
                ->atPath('rollerShutter')
                ->setTranslationDomain('rollerShutter')
                ->addViolation();
        }

        if ($this->getType()->getId() == TypeValue::TYPE_BAY_WINDOW) {
            return;
        }

        if ($this->getRollerShutterColor() === null) {
            $context->buildViolation('color.blank')
                ->atPath('rollerShutterColor')
                ->setTranslationDomain('rollerShutter')
                ->addViolation();
        }
    }
```

The form:
```php
                $builder
                    ->add('rollerShutter', 'choice', array(
                        'choices' => array(
                            '0' => 'Nein',
                            '1' => 'Ja'
                        ),
                        'expanded' => true,
                        'required' => true,
                        'translation_domain' => 'rollerShutter'
                    ))
                    ->add('rollerShutterType', 'entity', array(
                        'class' => 'Sps\Bundle\BaseBundle\Entity\ShutterType',
                        'required' => false,
                        'query_builder' => function(EntityRepository $er) {
                            return $er->createQueryBuilder('st')
                                ->where('st.isAvailable = :isAvailable')
                                ->setParameter('isAvailable', ShutterType::IS_AVAILABLE_TRUE)
                                ->orderBy('st.name', 'ASC');;
                        },
                        'placeholder' => 'Bitte Art der Bedienung und Farbe auswählen',
                        'translation_domain' => 'rollerShutter',
                    ))
                    ->add('rollerShutterColor', 'entity', array(
                        'class' => 'Sps\Bundle\BaseBundle\Entity\ShutterColor',
                        'required' => false,
                        'label' => false,
                        'placeholder' => '',
                        'translation_domain' => 'rollerShutter',
                    ))
                ;

                $builder->addEventListener(
                    FormEvents::SUBMIT,
                    function(FormEvent $event) {
                        $data = $event->getData();
                        $form = $event->getForm();

                        $rollerShutterTypeDisabled = $data->getRollerShutter() == '1'
                            ? false : true;

                        $rollerShutterTypeData = $rollerShutterTypeDisabled === true
                            ? '' : $data->getRollerShutterType();
                        $rollerShutterColorData = $rollerShutterTypeDisabled === true
                            ? '' : $data->getRollerShutterColor();

                        $form
                            ->add('rollerShutterType', 'entity', array(
                                'class' => 'Sps\Bundle\BaseBundle\Entity\ShutterType',
                                'query_builder' => function(EntityRepository $er) {
                                    return $er->createQueryBuilder('st')
                                        ->where('st.isAvailable = :isAvailable')
                                        ->setParameter('isAvailable', ShutterType::IS_AVAILABLE_TRUE)
                                        ->orderBy('st.name', 'ASC');;
                                },
                                'placeholder' => 'Bitte Art der Bedienung und Farbe auswählen',
                                'translation_domain' => 'rollerShutter',
                                'attr' => array('disabled' => $rollerShutterTypeDisabled),
                                'data' => $rollerShutterTypeData
                            ))
                            ->add('rollerShutterColor', 'entity', array(
                                'class' => 'Sps\Bundle\BaseBundle\Entity\ShutterColor',
                                'label' => false,
                                'placeholder' => '',
                                'translation_domain' => 'rollerShutter',
                                'disabled' => $rollerShutterTypeDisabled,
                                'data' => $rollerShutterColorData
                            ))
                        ;
                    }
                );
```

After submitting the first violation is correctly added to the `rollerShutter` path. Please note that this field IS NOT CHANGED by the SUBMIT form event.

The second violation is not added. No errors are shown in TWIG or the profiler.
The path `rollerShutterColor` is being re-added after the event - since there is no other way to override a field type.

This seems to be the cause of the issue: **If a field is added on the SUBMIT event then the constraint gets lost.**

Or is this an expected behaviour?

Currently using symfony **2.6**.

**Comment by javiereguiluz** [comment] 2016-01-31 19:25
@webdevilopers Symfony 2.6 is no longer maintained, so we can only look into this if you (or any other person from the community) can confirm this bug in a maintained version (2.7 or higher). Thanks for understanding it.

**Comment by webdevilopers** [comment] 2016-01-31 20:24
Sure. Maybe I will be able to upgrade in the next weeks and check it.

**Comment by webdevilopers** [comment] 2016-02-01 17:29
I've upgraded to **2.7** and can confirm the bug.

**Comment by javiereguiluz** [comment] 2016-02-01 18:18
@webdevilopers thanks for confirming the bug.

**Comment by dmaicher** [comment] 2016-02-07 17:40
In the `SUBMIT` event the form fields should not be changed as far as I know. The `PRE_SUBMIT` event should be used instead.

**Comment by xabbuh** [comment] 2016-02-09 11:50
I agree, this looks like a misusage to me.

@webdevilopers Do you experience the same issue when using the `PRE_SUBMIT` event instead?

**Comment by webdevilopers** [comment] 2016-02-10 18:49
I tried `PRE_SUBMIT` but it can not be used with my example since `$data` will not be available:
**Error: Call to a member function getRollerShutter() on a non-object**

```php
                $builder->addEventListener(
                    FormEvents::SUBMIT,
                    function(FormEvent $event) {
                        $data = $event->getData();
                        $form = $event->getForm();

                        $rollerShutterTypeDisabled = $data->getRollerShutter() == '1'
                            ? false : true;
```

Only after SUBMIT the form checks if the user set `rollerShutter` to `true`. If so he has to fill out the type and color too. I think `SUBMIT` is the only availbale event for this, right?

**Comment by xabbuh** [comment] 2016-02-10 19:00
Well, `getData()` in the `PRE_SUBMIT` event [returns the request data](http://symfony.com/doc/current/components/form/form_events.html#component-form-event-table). So you will want to check the proper array key from the request (or pass the underlying entity to the event listener with `use`).

**Comment by dmaicher** [comment] 2016-02-10 19:00
That is correct. In the `PRE_SUBMIT` the data is an array that contains the submitted data that is not yet bound to your model.

So `$data['rollerShutter']` should be `'0'` or `'1'`.

Looking at your example again let me ask what you actually try to achieve :)

If the choice `rollerShutter` is submitted with `0` or `false` then you want to ignore/unset what was submitted for `rollerShutterType` and `rollerShutterColor`, right?

In that case this should work:

```php
$builder->addEventListener(FormEvents::SUBMIT, function(FormEvent $event) {
    $data = $event->getData();
    if (!$data->getRollerShutter()) {
        $data->setRollerShutterType(null);
        $data->rollerShutterColor(null);
    }
});
```

**Comment by webdevilopers** [comment] 2016-02-10 19:55
Actually I need to enable the elements which are disabled before submit.
The term "disable" means "readonly" and HTML attribute `disabled` in this context.
Normally when setting `rollerShutter` to **1** or **true** javascript will enable them.
But still the user can simply submit the form because the Type and Color have a blank placeholder.
Or the form has an error on a different field. That's why I will have to enable ot via event.

I will try `$data` as array notation and get back. Thanks so far!

**Comment by dmaicher** [comment] 2016-02-11 18:22
Ok but then we can agree that its not a Symfony bug, right? ;)

**Comment by webdevilopers** [comment] 2016-02-11 18:55
The (original) issue is that the violation set to the Type or Color is lost after readding the elements with the event.

**Comment by dmaicher** [comment] 2016-02-11 18:57
Yes but most likely that happened because you modified the form in the event ;)

**Comment by webdevilopers** [comment] 2016-02-11 21:13
Since there is no way to modify a field in Symfony I have to re-add the field. The original field was "violated". After re-adding the error / violation is totally lost. I don't think this is an expected behaviour. You want the errors to persist throughout the events / form process.

**Comment by dmaicher** [comment] 2016-02-11 21:15
Yes but as we mentioned you should not add/remove fields in the `SUBMIT` event. That is the cause of the problem ;)

**Comment by xabbuh** [comment] 2016-02-11 22:31
Closing as this does not seem to be a bug an Symfony. We can reconsider that if you experience the same issue using the `PRE_SUBMIT` event.

**Closed by xabbuh** 2016-02-11 22:31 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed, Validator

**Comment by webdevilopers** [comment] 2016-02-12 10:30
You were right guys, the `PRE_SUBMIT` is the correct event to persist the errors. I re-arranged my code:
```php
                $builder->addEventListener(
                    FormEvents::PRE_SUBMIT,
                    function(FormEvent $event) {
                        $data = $event->getData();
                        $form = $event->getForm();

                        // Toggle dormer wall cladding color
                        if ($data['rollerShutter'] == '1') {
                        $form
                            ->add('rollerShutterType', 'entity', array(
                                'class' => 'Sps\Bundle\BaseBundle\Entity\ShutterType',
                                'attr' => array('disabled' => false),
                        } else {
                            // Reset data for type
                            unset($data['rollerShutterType']);
                            $data['rollerShutterType'] = '';
                        }
```

The only thing that does not work is unsetting the `$data` for the case the user selected a `rollerShutterType` and then changed his mind and set `rollerShutter` to `false`.
Of course the value is unset on client side by javascript. But do I have to use the `SUBMIT` event to unset `$data` then?

**Comment by dmaicher** [comment] 2016-02-12 10:33
Yes the correct place for that would be the `SUBMIT` event. Like I posted above this should work:

```php
$builder->addEventListener(FormEvents::SUBMIT, function(FormEvent $event) {
    $data = $event->getData();
    if (!$data->getRollerShutter()) {
        $data->setRollerShutterType(null);
        $data->setRollerShutterColor(null);
    }
});
```

**Comment by webdevilopers** [comment] 2016-02-12 10:36
Thanks and "Danke" for the great help!
