### ISSUE TITLE
[DI] Invalid Deprecation Notice for anonymous services

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24311] opened 2017-09-24 14:13 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x

```xml
<?xml version="1.0" ?>
<container xmlns="http://symfony.com/schema/dic/services"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd"
>
  <services>
    <defaults autowire="true" autoconfigure="true" public="false" />

    <!-- more unrelated service defs -->

    <service id="app.uuid_factory_guid" class="Ramsey\Uuid\UuidFactory">
      <argument type="service">
        <service class="Ramsey\Uuid\FeatureSet">
          <argument>true</argument><!-- microsoft guid byte order shuffling -->
        </service>
      </argument>
    </service>
 
  </services>

</container>
```

This reports a deprecation notice:
```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "1_d864aebfa95a3028b90db6cee792377b9db6b7a50b4c85680304d527d4038480" service to "Ramsey\Uuid\FeatureSet" instead.
```

(The given service def is the only place where `Ramsey\Uuid\FeatureSet` is used)

If i see this correctly, there should no deprecation notice be reported for this use case?

**Comment by nicolas-grekas** [comment] 2017-09-24 14:17
Can you provide a reproducer please?

**Comment by backbone87** [comment] 2017-09-24 14:25
hm, the service file from above reproduces this. what format do you need?

**Comment by nicolas-grekas** [comment] 2017-09-24 14:29
a forked standard edition that produce the bug?

**Comment by backbone87** [comment] 2017-09-24 14:30
i use the symfony demo, is that ok too?

**Comment by nicolas-grekas** [comment] 2017-09-24 14:31
sure

**Comment by backbone87** [comment] 2017-09-24 15:03
ok the problem is even worse.
https://github.com/backbone87/symfony-demo/tree/bug-symfony-24311

the actual problem comes not from the service def in the OP but from the other services defs, that i left out:
https://github.com/backbone87/symfony-demo/blob/bug-symfony-24311/config/services.xml#L9

this service gets autowired with the anonymous service from:
https://github.com/backbone87/symfony-demo/blob/bug-symfony-24311/config/services.xml#L14

which is an actual bug and leads to invalid application behavior (in this case invalid uuids gets produced by the "default" uuid factory, because it uses the feature set from a uuid factory designated to handle mircosoft GUIDs)

**Comment by nicolas-grekas** [comment] 2017-09-24 15:10
OK, so, this is not a bug, but the expected behavior of the code, and also the very reason why we deprecated it altogether, because it's a bad one.
There are two fixes:
- on your side: fix your config to explicitly set the value of said currently autowired args.
- on DI's XmlFileLoader: this is where the code responsible for creating these anonymous services is: right now, it turns nested anonymous services to root level one - which are then cherry-picked by autowiring. We could change this behavior and leave nested Definition objects instead. BUT there is a chance of breaking BC here, so it should be considered carefully. If you want, I invite you to submit a PR doing that on 3.4, and see how the discussion goes. If not, then leave it as is, knowing 4.0 will remove the wtf...

**Comment by backbone87** [comment] 2017-09-24 15:17
> which are then cherry-picked by autowiring. We could change this behavior and leave nested Definition objects instead.

Wouldnt be a simple solution to just mark certain service to not be used as an autowired argument? It would be a BC break, but i can not believe that anyone intended to create an anonymous service that gets autowired somewhere else except in the exact place it is defined in. I mean that is against the whole premise of anonymous services.

in this case i think it is enough for me to just disable autowiring for `Ramsey\Uuid\UuidFactory` since the first argument is optional.

**Comment by nicolas-grekas** [comment] 2017-09-24 15:21
> mark certain service to not be used as an autowired argument

that's a possibility, but there is no way to do that right now, so one should be created...

**Comment by backbone87** [comment] 2017-09-24 17:22
ok so for this `Definition` needs a new property, but i am not sure, if it should be `Definition::anonymous` or `Definition::notUseableAsAutowiredArgument` (idk about a good name, so i just described what the property should reflect). what is the better approach?

**Comment by nicolas-grekas** [comment] 2017-09-24 17:28
or a tag, would it work?

**Comment by backbone87** [comment] 2017-09-24 17:44
tags would work too, but i think when using tags, it would be more concise to mark definitions available to be used as an autowired argument, insteadof marking those not available.

currently i feel the best with adding a `anonymous` property, because this reflects the actual mechanic and it is up to the other feature impls, if they use this property in some way (like the `AutowiringPass` ignoring anonymous services as arguments)

**Comment by nicolas-grekas** [comment] 2017-09-24 17:49
The issue with a new property is adding a new public interface, for a concept we won't care about anymore in 4.0.

**Comment by backbone87** [comment] 2017-09-24 17:52
actually this feature is independant of this deprecation, because marking services to not be autowired may still be used in the future. or anonymous service definitions will still be supported and a property reflecting this fact, wont lose its value in 4.0 (thats why i prefer an "anonymous" property)

**Comment by nicolas-grekas** [comment] 2017-09-24 17:58
In 4.0 a service will be injected by autowiring only if it's *name* exactly matches the type-hint.
That effectively excludes anonymous definitions, is is totally correlated/dependent on the concept.

**Comment by nicolas-grekas** [comment] 2017-10-07 08:38
Closing as explained.

**Closed by nicolas-grekas** 2017-10-07 08:38 UTC

**Comment by nicolas-grekas** [comment] 2017-10-08 14:37
See #24491 :)
