### ISSUE TITLE
No error logged when error occured in a setter. 

### ISSUE THREAD

**Issue by Micsou** [symfony/symfony#20157] opened 2016-10-05 08:14 UTC
Hello, 
Don't know if my case may help you in enhancing the framework but i had somethig special today. 
I had an entity linked to a form. 
In a setter I wanted to transform user last name in uppercase. 
Did it quickely and I made a typo : 

`
public function setLastName($lastName)
{
        $this->lastName = strtupper($lastName);
        return $this;
}
`

Symfony then failed when binding form to entity in the handleRequest method. 
What worries me is that I really had no way to know where the error appeared : no log, no exception, and a pretty white page. 
Is that normal? That's surprising

**Comment by Micsou** [comment] 2016-10-05 19:54
Yep

**Comment by patrick-mcdougle** [comment] 2016-10-09 23:22
That should have been a fatal error. Sometimes fatal errors are logged in a different place than the symfony error log. Perhaps your server error log?

**Comment by jakzal** [comment] 2016-10-12 15:20
@Micsou are you able to provide a working example that would reproduce your problem? Otherwise we won't be able to tell if this is a bug or if we can fix it.

**Comment by Micsou** [comment] 2016-10-13 05:42
Hi, I've just reproduced the bug. 
Can't see error logged in apache. 

@jakzal What do you call a working example? A project? A bundle? The files ? 

Quickely If you have a form, just try to change a setter like : 

` public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }`

like that : 

` public function setLastName($lastName)
    {
        $this->lastName = strtupper($lastName);

        return $this;
    }`

Notice there is a type on stroupper where th o is missing. 
When you submit the form you find a white page and no error anywhere !!??

**Comment by Micsou** [comment] 2016-10-13 05:53
@patrick-mcdougle You were right, error is logged in php error log. 

`13-Oct-2016` 05:37:34 UTC] PHP Fatal error:  Call to undefined function AppBundle\Entity\Member\strtupper()`

Why isn't it raised in Symfony?

**Comment by jakzal** [comment] 2016-10-13 08:10
@Micsou a working example is something i can install to reproduce the issue

**Comment by stof** [comment] 2016-10-13 08:29
@Micsou because it is a non catchable fatal error, and so the error handler does not get called for it. I think this error is catchable in PHP 7 btw

**Comment by xabbuh** [comment] 2016-10-16 08:40
Closing here for the explanation given by @stof.

**Closed by xabbuh** 2016-10-16 08:40 UTC
Labels: Form, Unconfirmed
