### ISSUE TITLE
[Config] isRequired fields on a canBeEnabled array

### ISSUE THREAD

**Issue by appeltaert** [symfony/symfony#17153] opened 2015-12-28 11:07 UTC
Explicitly setting a arraynode to false, still results in validating the other child nodes.

For example:

```php
mail = $defaults->arrayNode('mail')->canBeEnabled()->addDefaultsIfNotSet()->children();
                    $mail->scalarNode('to')
                        ->cannotBeEmpty()
                        ->isRequired()
                        ->end();
                    $mail->scalarNode('subject')
                        ->cannotBeEmpty()
                        ->isRequired()
                        ->end();
                    $mail->scalarNode('from')
                        ->cannotBeEmpty()
                        ->isRequired()
                        ->end();
```

Not setting the mail node at all gives the desired result, but explicity setting enabled to false triggers errors on the fields below.
I realize that this use-case doesnt happen often, why set it to false if the intention is to not enable it, but still--minor point of improvement.

**Comment by paradajozsef** [comment] 2016-01-25 22:40
I think this is not a bug, it's just a confusing behaviour.

As the [method's dockblock](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php#L217) says, the canBeEnabled() makes the node's default value to ```false```. But after you add any configuration to the node, it will be enabled.

So I have this config tree, like yours:

```php
$treeBuilder = new TreeBuilder();
$app = $treeBuilder->root('app')->children();

$mail = $app->arrayNode('mail')->canBeEnabled()->addDefaultsIfNotSet()->children();

$mail->scalarNode('to')->cannotBeEmpty()->isRequired()->end();
$mail->scalarNode('subject')->cannotBeEmpty()->isRequired()->end();
$mail->scalarNode('from')->cannotBeEmpty()->isRequired()->end();
```

And I provide this config, without configuring ```to```, ```subject``` and ```from```
```yml
# app/config/config.yml
app:
    mail:
```
It will raise this error:
```
InvalidConfigurationException in ArrayNode.php line 237:

The child node "to" at path "app.mail" must be configured.
```

Which is correct, because you provided the ```mail:``` configuration, so it became enabled. There is an [example to this case in the dockblock](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php#L221).

But If you don't configure ```mail``` at all:
```yml
# app/config/config.yml
app:
```
Then everything is ok. It's not a problem, that children are required.

**Comment by javiereguiluz** [comment] 2016-01-26 16:09
I agree with @paradajozsef (by the way, thanks for the detailed explanation!)

I'm closing it because it looks like a non bug. @appeltaert if you don't agree, please reopen it. Thanks!

**Comment by appeltaert** [comment] 2016-02-15 11:04
@paradajozsef Thanks for the detailed explanation indeed. But sorry, I either disagree or fail to understand :)

Isn't **not** specifying any value such as `app:` the same as `app:~` ? As in NULL, **use defaults**? This is how any Symfony component works anyway. 

Setting it to `false` specifically says **do not enable**. No?

The docblock you link to also seem to confirm this:

``` php
/**
 * enableableArrayNode: ~                      # The config is enabled & use the default values
 * enableableArrayNode: false                  # The config is disabled
 *
 * @return ArrayNodeDefinition
 */
```

So saying the following, should mean enable and use the defaults.
``` yml
app:
    mail:
```
Which is not the same as `mail: false`, do not add defaults.

Or do I fail to interpret that explanation?

Thanks guys.

**Comment by xabbuh** [comment] 2016-02-15 11:23
@appeltaert I am not sure I completely understand your issue. Would you be able to provide a failing test case? That would probably make it easier to understand your use case/issue.

**Comment by appeltaert** [comment] 2016-02-15 21:20
@xabbuh Sure, here you go: https://github.com/appeltaert/symfony17153

The first two fail, but they shouldn't.

**Comment by jakzal** [comment] 2016-02-22 16:21
Indeed, [according to the docs](http://symfony.com/doc/current/components/config/definition.html#optional-sections), setting `mail: false` when a node was configured with `canBeEnabled()` should be equivalent to setting `mail: [enabled: false]`:

```php
$arrayNode
    ->canBeEnabled()
;

// is equivalent to

$arrayNode
    ->treatFalseLike(array('enabled' => false))
    ->treatTrueLike(array('enabled' => true))
    ->treatNullLike(array('enabled' => true))
    ->children()
        ->booleanNode('enabled')
            ->defaultFalse()
;
```

Already [mentioned dockblock](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php#L219-L226) confirms this was the intention:

```php
 /**
     * Adds an "enabled" boolean to enable the current section.
     *
     * By default, the section is disabled. If any configuration is specified then
     * the node will be automatically enabled:
     *
     * enableableArrayNode: {enabled: true, ...}   # The config is enabled & default values get overridden
     * enableableArrayNode: ~                      # The config is enabled & use the default values
     * enableableArrayNode: true                   # The config is enabled & use the default values
     * enableableArrayNode: {other: value, ...}    # The config is enabled & default values get overridden
     * enableableArrayNode: {enabled: false, ...}  # The config is disabled
     * enableableArrayNode: false                  # The config is disabled
     *
     * @return ArrayNodeDefinition
     */
    public function canBeEnabled()
    {
    }
```

**Comment by jakzal** [comment] 2016-02-22 16:43
@appeltaert having said that, I agree with others saying there's no bug here. 

In your case you require values to be provided, but you don't provide any defaults.  Currently, the validation is still run on any child nodes of a node with the "enabled" flag.

Imagine you called `canBeEnabled()` in your config builder, but then you didn't use this value in your DIC extension to see if feature is enabled. If we changed the current behaviour, you'd still be able to access other config values which would be invalid if we didn't process the config for them. Some people might even rely on this behaviour.

The `canBeEnabled()`/`canBeDisabled()` are only convenience methods that add a field called "enabled". You can use its value after the configuration is processed to see whether you need to enable given part of functionality. There's no special handling of this value inside the config builder though. It's just a convention. 

Perhaps this should be clarified in the docs. Would you like to take a stab on this?

**Comment by jakzal** [comment] 2016-02-22 16:44
Very good bug report with supporting test case by the way!

**Closed by jakzal** 2016-02-22 16:43 UTC
Labels: Config

**Comment by appeltaert** [comment] 2016-10-25 10:19
@jakzal a tad late, just wanted to say thanks. Missed your responses but just ran into this one because it is linked with an internal issue. 

Looking at it a second time makes it pretty clear, probably tunnel vission/mental overflow. Docs are pretty clear too...

```
$arrayNode
    ->treatFalseLike(array('enabled' => false))
    ->treatTrueLike(array('enabled' => true))
    ->treatNullLike(array('enabled' => true))
```

Don't know what more there is to say about it :)
