### ISSUE TITLE
[Validator] wrong constraint attached to ConstraintViolation

### ISSUE THREAD

**Issue by pinkeen** [symfony/symfony#20368] opened 2016-10-30 18:00 UTC
Version: symfony/validator 3.1.6, PHP 7.0.7

**Background:** I've been using the validator component for APIs for a long time (without forms though). One of the problems was that apart from the descriptive violation messages I wanted to return a fixed error name that can be handled by the application on the other end. I've achieved that by extending the base constraints and overriding the error messages (which means no descriptive message). I could live with that, waited for better times.

I noticed that the ConstraintViolation includes the `::getCode` method now! Perfect for my little APIs. The code seems to be an UUID and each of the constraints includes a mapping to nice error names. UUIDs are usable but they are not the best UX for the end-programmer :).

**The meat**: The easiest way to get the error name would be to use `Constraint::getErrorName` method. This is where the problem is - in some cases the `ConstraintViolation` has the wrong `Constraint` attached. From the first look - it's the last tested constraint, not the one that failed.

I am aware that I am assuming the the `ConstraintViolationInterface` is actually a `ConstraintViolation` but IMO it's fair to assume when I'm using Symfony's validator component. Also the `ConstraintViolation::getConstraint` and `Constraint::getErrorName` methods are public so I am (I hope) not relying on some internal implementation details.

I am attaching a testcase for further illustration:
https://gist.github.com/pinkeen/7a3b6688efc3c493fc16807ac89d3a3f

**Comment by xabbuh** [comment] 2016-11-12 10:56
I am not sure if I fully understood your problem. In your test case, what did happen and what did you actually expect to happen instead?

**Comment by pinkeen** [comment] 2016-11-12 11:13
In case of a nested constraints, specifically the `Symfony\Component\Validator\Constraints\Collection` constraint. When it fails the `ConstraintViolation::getCode` returns the proper error code which is `Collection:MISSING_FIELD_ERROR`. The expectation is that `ConstraintViolation::getConstraint` will return an instance of `Constraints\Collection` but instead I get an instance of one of the nested constraints.

**Comment by xabbuh** [comment] 2016-11-12 11:53
Your issue actually is that you assign an empty array to the `email` field instead of the constraint that should be used to validate the field which is not supported. You need to provide the constraint that should be applied.

**Comment by pinkeen** [comment] 2016-11-12 11:55
I did that in the testcase to better illustrate the problem. The constraint returned is wrong no matter what I do. See the 2nd test.

**Comment by xabbuh** [comment] 2016-11-12 13:03
I missed your second test case. This is indeed an issue.

**Comment by xabbuh** [comment] 2016-11-12 13:06
For the records, this is related to #14786.

**Comment by xabbuh** [comment] 2016-11-12 13:07
Oh and actually this then is a duplicate of #14639. So I am closing here, but I will also look into how to solve #14639. Thank you for reporting this bug and for providing the reproducable example @pinkeen!

**Closed by xabbuh** 2016-11-12 13:07 UTC
Labels: Bug, Status: Needs Review, Validator

**Comment by xabbuh** [comment] 2016-11-28 08:57
@pinkeen Can you check if #20664 solves your issue?

**Comment by pinkeen** [comment] 2016-11-29 11:28
Sorry for the late response. Yes, it solves the issue (2nd test passes). The first test still fails although as you noticed I use empty key (without constraints) which is unsupported.

**Comment by xabbuh** [comment] 2016-11-29 11:30
Thank you very much for the confirmation @pinkeen!

**Comment by pinkeen** [comment] 2016-11-29 11:40
I realized I have pulled wrong version of the validator component. Retested the proper version. Both tests pass, even with the key without constraints. Tried few other variations - changing order, changing the validators - all green! Thank you for the fix!
