### ISSUE TITLE
[DX][WebProfilerBundle] Provide quick links to redirect responses in the toolbar

### ISSUE THREAD

**Issue by dkisselev** [symfony/symfony#17501] opened 2016-01-23 00:43 UTC
On pages where an application silently redirects a user away, it may be confusing or difficult to debug because the toolbar may no errors, the result is not what the developer expected, and may not think to check redirects.

As an example, a developer tries to login from /login, it fails, but they don't know why because the current page load (for /login) shows all green and has no log messages. They would have to know to go through the profiler to find the login_check request and look at the log there.

Further, even if they know that the got looped around, it would be much more convenient if the toolbar provided a link to those profiler pages instead of needing to go look it up.

My proposal is a toolbar tab similar to (or perhaps an expansion of) the AJAX tab which lists the result, execution time, and profiler link to pages that were loaded between the last page I was on, and the one I'm currently on.

I'm not familiar with the internals of the toolbar so am unsure about how this might be implemented, but perhaps by looking at the Referrer and matching that to recent profiler logs?

**Comment by xabbuh** [comment] 2016-01-23 07:56
You can already intercept redirects (so you get an intermediate page telling you that the request is redirect) and see the profile of the action triggering the redirection there. I think that is sufficient in most use cases.

**Comment by iltar** [comment] 2016-01-24 07:55
What I would love to see, is that when a redirect response is returned, the request token will be shown in the WDT (clickable) of the following non-redirect action. This saves me from:
 1. Opening the profiler
 2. Click Last 10 requests
 3. Click on the redirect

**Comment by dkisselev** [comment] 2016-01-24 20:48
I didn't think about the intercept redirect switch, but I don't think that the two features are exclusive. 

I don't necessarily want to have to take a middle step every single time I go through a redirect, but it would be helpful to see when I did, and have the option to check what happened there (without going through all the steps, as @iltar has laid out). Part of it is a visibility issue, if you're not paying attention it's really easy to miss that you had gone through a redirect (like the login/login_check case, since you end up back at /login on a failure)

**Comment by javiereguiluz** [comment] 2016-01-27 10:53
This is what I'd like to do for redirections:

1) Show an icon next to the route name:

![redirect_icon](https://cloud.githubusercontent.com/assets/73419/12611350/6e11117c-c4ec-11e5-8514-9e2b381b3046.png)

2) Show the redirection info (and a link to its profile) when revealing the request panel:

![redirect_info](https://cloud.githubusercontent.com/assets/73419/12611370/812e7c04-c4ec-11e5-911b-5da51b2da19c.png)

Problem is that I don't know how to detect if a request is in fact a redirect from another one. Any ideas? Thanks!

**Comment by iltar** [comment] 2016-01-27 10:56
@javiereguiluz could make a debug response listener that stores is somewhere

**Comment by stof** [comment] 2016-01-27 11:22
The issue is that there is no way to know that the current request has been done by the browser to fulfill a redirection. The server does not know why the client made the request. It just receives the request and handles it.

**Comment by stof** [comment] 2016-01-27 11:24
Note that being able to know why the request was made (a redirect or a user action) would mean that you would not be using the HTTP protocol anymore but some other protocol (a stateful one in this case)

**Comment by fabpot** [comment] 2016-01-27 11:27
... and that's why redirections are managed by an intermediate page right now.

**Comment by javiereguiluz** [comment] 2016-01-27 11:31
I'm closing this issue as "won't fix". As explained by @stof, the limitations of the underlying HTTP protocol prevents us from adding this feature. Thankfully we already provide a working alternative thanks to the `intercept_redirects` setting of the profiler.

**Closed by javiereguiluz** 2016-01-27 11:31 UTC
Labels: DX, WebProfilerBundle

**Comment by dkisselev** [comment] 2016-01-27 18:09
The toolbar listener can already identify redirectResponses and act on them (to handle the interception page).

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L84-L94

What about pushing the debug tokens for redirects onto a stack in the session, which then get popped and displayed on any other (non-redirect) response?

I see what you're saying about stateless nature of HTTP, and there might be some race conditions there, if you're loading multiple pages at once or a load fails, the redirect might appear in the toolbar on the wrong pages like flash messages, but I feel like this is a relatively rare case because dev is typically only used by one person at a time, and they could understand what's going on. 

Looking at the referrer might also be a way of helping filter the source (if the url from the redirection debug token doesn't match the referrer in the current request, the user didn't land here as a result of that request)

**Comment by dkisselev** [comment] 2016-01-27 18:13
Another option might be adding JS so that the existing intercept_redirects option will automatically follow the redirect, adding the current debug token to the request headers. ProfileEventListener catches the header and adds the tab to the profiler. 

Very similar functionality to the current behavior (less risk of regressions), but improves DX by allowing the user to skip that extra middle page, instead showing the same information as part of the next response.

**Comment by HeahDude** [comment] 2016-01-28 17:00
@javiereguiluz seems to work with @dkisselev idea of using session since there cannot be two redirected requests with the same origin at the time while debugging. see 61ec46e
