### ISSUE TITLE
You have requested a non-existent service "knp_menu.menu_provider.chain"

### ISSUE THREAD

**Issue by ibasaw** [symfony/symfony#17910] opened 2016-02-23 19:45 UTC
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
      You have requested a non-existent service "knp_menu.menu_provider.chain". Did you mean this:  "knp_menu.menu_provider"?

in my composer.json, got : "symfony/symfony": "2.8.*@dev"

got this error after a composer update

**Comment by xabbuh** [comment] 2016-02-23 19:49
@ibasaw Can you check if this is the same as #17864 which was fixed by #17866?

**Comment by ibasaw** [comment] 2016-02-23 19:58
@xabbuh : yes it works with #17866

**Comment by nicokaag** [comment] 2016-02-24 14:41
I Still have this issue on branch 2.8. The commit I'm on is: 4cbb3fd
So I'm not sure if #17866 fixed it.

**Comment by ibasaw** [comment] 2016-02-24 15:04
you're right @nicokaag , on a fresh composer install, got this error too.

ping @xabbuh

**Comment by xabbuh** [comment] 2016-02-24 15:08
@nicokaag @ibasaw Would you be able to provide some steps to reproduce your issue? Did you clear the cache of your application?

**Comment by nicokaag** [comment] 2016-02-24 15:58
@xabbuh I don't have exact steps to reproduce right now. But the call to the service `knp_menu.menu_provider.chain` is done in the cache directory and then the *ProjectContainer.php file.

The code that is generated is something like:
```
protected function getNicoDossier_Entity_CategoryRepositoryService()
{
    return $this->services['nico_dossier.entity.category_repository'] = $this->get('knp_menu.menu_provider.chain')->getRepository('Nico\\DossierBundle\\Entity\\Category');
}
```

So for some reason the `doctrine` service got replaced with the `knp_menu.menu_provider.chain` service.

The KnpMenuBundle in my project is a dependency of the SonataAdminBundle, so that may be related to this issue (?)

**Comment by ibasaw** [comment] 2016-02-24 16:10
@xabbuh 

in the first place, i only do a composer update when it arrived.

got SonataAdminBundle too, i delete cache, composer cache, vendors, then i do a composer update and got this error.

**Comment by ibasaw** [comment] 2016-02-24 18:51
@xabbuh 

for me in the ProjectContainer.php, the code is:

      /**
     * Gets the 'ao_translation.entity_manager' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Doctrine\ORM\EntityManager A Doctrine\ORM\EntityManager instance.
     */
    protected function getAoTranslation_EntityManagerService()
    {
        return $this->services['ao_translation.entity_manager'] = $this->get('knp_menu.menu_provider.chain')->getManager('default');
    }

**Comment by xabbuh** [comment] 2016-02-24 18:52
@ibasaw Do you have some example code and configuration I can add to a blank Symfony Standard Edition that will lead to this issue?

**Comment by ibasaw** [comment] 2016-02-24 19:14
@xabbuh : this is because i used https://github.com/adrianolek/AOTranslationBundle.

i had deleted it, and no more error...

**Comment by NVasse** [comment] 2016-02-25 12:13
No more error by deleting the line99 of [symfony/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php#L99)

Not sure if this is the solution though.

**Comment by xabbuh** [comment] 2016-02-25 12:48
@NVasse No, we need that line to fix #17864. Can you provide some information about how we can reproduce your issue?

**Comment by NVasse** [comment] 2016-02-25 14:32
I think that simply having KnpMenuBundle triggers the error.

@xabbuh Doesn't commit 6190058 (which is line 100 of the same file) fix the problem ?

**Comment by xabbuh** [comment] 2016-02-25 18:26
By simply adding the KnpMenuBundle I cannot reproduce your issue. Can you please fork the Symfony Standard Edition and make the changes that are needed to reproduce it?

**Comment by fungio** [comment] 2016-02-26 09:33
I have the same error with Symfony 2.8 and KnpMenuBundle. I also have this error with a Symfony 2.3 project. But if I rollback few commits in both my 2.8 and 2.3 projects the problem is "solved" so I'm pretty sure it's not a bug from Knp.
Any clues ?

**Comment by xabbuh** [comment] 2016-02-26 11:22
@fungio I do agree but as long as I cannot reproduce your issue I am unable to create a fix.

**Comment by rapemer** [comment] 2016-02-26 11:46
I have the same issue. Problem solved by adding to /app/services.yml:

    knp_menu.menu_provider.chain:
        class: %knp_menu.menu_provider.chain.class%
        arguments: [ {} ]
        public: true

**Comment by javiereguiluz** [comment] 2016-02-26 11:52
Thank you all for investigating this issue. However, as @xabbuh said, we need to be able to reproduce this issue consistently in order to fix it.

So please, could someone fork the Symfony Standard edition and add the minimum number of third-party bundles, config and PHP code to reproduce the issue? Thank you!

**Comment by ibasaw** [comment] 2016-02-26 11:55
@javiereguiluz : which version of symfony ? 2.8 ?

**Comment by javiereguiluz** [comment] 2016-02-26 11:57
If it's a real Symfony bug, the version should be "the oldest Symfony version which is still maintained and it suffers the bug". So it can be 2.3, 2.7 or 2.8.

**Comment by NVasse** [comment] 2016-02-26 12:04
I tried @rapemer solution and now I get the same error from another service `bazinga_geocoder.geocoder.default_adapter` which is also a service with public set to false, I guess that links this problem to #17915

**Comment by rapemer** [comment] 2016-02-26 12:06
@NVasse yeah, it seems to be problem with services public = false

**Comment by rapemer** [comment] 2016-02-26 12:11
Error occured when I used `composer update` at my dev-master (2.8.x-dev) to the latest commit. When I revert to 2.8.2, everything is okay.

**Comment by WouterJ** [comment] 2016-02-26 23:46
See https://github.com/WouterJ/symfony/commit/be61610674492b71a30080f1a60ccb396b2be5f0 for a failing test case proofing this bug. It involves having a private aliased service that is created by a factory service. Please note that the bug exists for both the old and new factory API.

**Comment by WouterJ** [comment] 2016-02-26 23:46
Status: Reviewed

**Comment by WouterJ** [comment] 2016-02-26 23:54
I'm sorry, that test case was proofing something completely irrelevant. In order to reproduce this issue:

 * On a fresh Symfony install (dev-2.8)
 * Add a service config like this:

   ```yaml
   services:
     app.demo:
       class: Doctrine\ORM\EntityManager
       factory_service: doctrine
       factory_method: getManager
   ```
 * Now, somewhere in a controller use `$this->get('app.demo')`.

**Closed** 2016-02-28 15:07 UTC
Labels: DependencyInjection, Status: Reviewed, Unconfirmed
