### ISSUE TITLE
Symfony 3.2-RC1 error in the Logger panel in Symfony Profiler

### ISSUE THREAD

**Issue by martinbertinat** [symfony/symfony#20557] opened 2016-11-18 11:28 UTC
Hello, I'm trying Symfony 3.2.0-RC1. It's a fresh install.

I have the same error as @javiereguiluz https://github.com/symfony/symfony/issues/20556

But there is another error in the logger panel:

![sf32rc1](https://cloud.githubusercontent.com/assets/1635368/20428626/e70c7b6a-ad68-11e6-8c4e-3a08ad1e09a9.png)

**Comment by derrabus** [comment] 2016-11-18 17:38
This issue can be closed as a duplicate of #20556. Same cause, same fix. :-)

**Comment by javiereguiluz** [comment] 2016-11-18 18:42
Closing it as duplicate of #20556.

**Closed by javiereguiluz** 2016-11-18 18:42 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle
