### ISSUE TITLE
Kernel reports dev version after update

### ISSUE THREAD

**Issue by RicardoJ** [symfony/symfony#18390] opened 2016-03-31 19:03 UTC
When updating from `v3.0.3` to `v3.0.4` the version gets updated to `v3.0.4-DEV`.

![version](https://cloud.githubusercontent.com/assets/15246351/14187516/c3f66294-f783-11e5-90ab-3fd188161365.PNG)

This issue also has been reported by [Loïc Vernet](https://connect.sensiolabs.com/api/alternates/27ab857a-3b59-4e44-b3b8-7c4698d56b7f) on the release page for `v3.0.4`: [symfony.com: Symfony 3.0.4 released](http://symfony.com/blog/symfony-3-0-4-released#comment-20438).

**Comment by iltar** [comment] 2016-03-31 20:47
Duplicate of #18365 and #18380

**Comment by xabbuh** [comment] 2016-03-31 21:23
Closing as there is nothing we can do right now (tags cannot be changed) and the issue will go away with the following patch releases next month.

**Closed by xabbuh** 2016-03-31 21:23 UTC

**Comment by RicardoJ** [comment] 2016-04-01 07:39
Sorry for the duplicate and thanks for the quick answer.
