### ISSUE TITLE
ReflectionExtractor getProperties: returns both properties and methods

### ISSUE THREAD

**Issue by numediaweb** [symfony/symfony#26310] opened 2018-02-25 13:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

In [symfony/property-info/Extractor/ReflectionExtractor.php::getProperties](https://github.com/symfony/symfony/blob/3609744ab8763556b2eff1431424668f825dfb8d/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php) returns both properties and methods: 
```php
    public function getProperties($class, array $context = array())
    {
        try {
            $reflectionClass = new \ReflectionClass($class);
        } catch (\ReflectionException $e) {
            return;
        }

        $reflectionProperties = $reflectionClass->getProperties();

        $properties = array();
        foreach ($reflectionProperties as $reflectionProperty) {
            if ($reflectionProperty->isPublic()) {
                $properties[$reflectionProperty->name] = $reflectionProperty->name;
            }
        }

        foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $reflectionMethod) {
            if ($reflectionMethod->isStatic()) {
                continue;
            }

            $propertyName = $this->getPropertyName($reflectionMethod->name, $reflectionProperties);
            if (!$propertyName || isset($properties[$propertyName])) {
                continue;
            }
            if (!$reflectionClass->hasProperty($propertyName) && !preg_match('/^[A-Z]{2,}/', $propertyName)) {
                $propertyName = lcfirst($propertyName);
            }
            $properties[$propertyName] = $propertyName;
        }

        return array_values($properties);
    }
```
It should only return properties as the name suggests.

Note also how the $context parameter is never used in the method.

**Comment by nicolas-grekas** [comment] 2018-02-27 18:11
Hello, this behavior cannot be changed, it would be a BC break otherwise.
The reason this return methods I suppose is that the component abstracts out public properties vs private ones with setter/getter methods.
Not a bug, therefore closing. Thanks for the report, and of course if I missed anything, we can reopen.

**Closed by nicolas-grekas** 2018-02-27 18:11 UTC
Labels: Bug, PropertyInfo, Status: Needs Review
