### ISSUE TITLE
More readable error in the console

### ISSUE THREAD

**Issue by mickaelw** [symfony/symfony#25481] opened 2017-12-13 12:14 UTC
I'm on Symfony 3.2, when I have an error in the console is unreadable.

For example:
![screen shot 2017-12-13 at 13 10 19](https://user-images.githubusercontent.com/23268376/33938312-5eeb5eea-e007-11e7-8a2a-a53b7311e35f.png)

Maybe it's corrected on next version?

**Comment by Simperfit** [comment] 2017-12-13 12:58
Hey @mickaelw What terminal are you using ?

**Comment by mickaelw** [comment] 2017-12-13 13:36
I use the terminal of Intellij IDEA last version

**Comment by xabbuh** [comment] 2017-12-13 16:19
Duplicate of #24125?

**Closed** 2017-12-13 23:14 UTC
Labels: Console
