### ISSUE TITLE
Composer/git errors when creating new Symfony project

### ISSUE THREAD

**Issue by unlikenesses** [symfony/symfony#39778] opened 2021-01-10 17:08 UTC
**Symfony version(s) affected**: 5.2.1
**PHP**: 7.4.3
**Composer**: 2.0.8
**OS**: Windows 10 (error occurs on Host *and* WSL2)

**Description**  
When I run `composer create-project symfony/symfony foo` Composer gives me two errors and cannot complete:

1. Installing doctrine/annotations (dev-master 5cb4064): Cloning 5cb4064410
    5cb4064410e57ffd3ed5583cdb2baa6f1a1fa204 is gone (history was rewritten?)
    Install of doctrine/annotations failed

2. Installing twig/markdown-extra (2.x-dev 94cdaf9): Cloning 94cdaf9ee9 from cache
  [RuntimeException]
  Failed to execute git checkout '5cb4064410e57ffd3ed5583cdb2baa6f1a1fa204' -- && git reset --hard '5cb4064410e57ffd3
  ed5583cdb2baa6f1a1fa204' --
  fatal: reference is not a tree: 5cb4064410e57ffd3ed5583cdb2baa6f1a1fa204

I've tried running `composer cc`, I've also tried cloning the Symfony repo and running `composer install`. Same errors. This occurs both on Windows 10 and on WSL2. I have `git`, `zip`, `unzip`, and all the [necessary PHP modules](https://symfony.com/doc/current/setup.html#technical-requirements) installed.

**Comment by wouterj** [comment] 2021-01-10 17:46
You should not create a project from `symfony/symfony`. This is the repository containing all code, it cannot be used for projects/applications.

See [the installation documentation](https://symfony.com/doc/current/setup.html#creating-symfony-applications) on the correct `create-project` commands for Symfony.

Aside from that, I am able to run your command without an issue locally (Linux). So I don't think there is an issue with this repository honestly.

Status: works for me

**Comment by derrabus** [comment] 2021-01-10 17:57
Closing as this is not a bug.

**Closed as completed by derrabus** 2021-01-10 17:57 UTC
Labels: Bug, Status: Works for me

**Comment by unlikenesses** [comment] 2021-01-10 17:58
:man_facepalming: Thank you, `composer create-project symfony/website-skeleton foo` worked.
