### ISSUE TITLE
The process has been signaled with signal "11"

### ISSUE THREAD

**Issue by 0x6368** [symfony/symfony#29364] opened 2018-11-28 14:25 UTC
**Symfony version(s) affected**: 4.1.8

**Description**  

Symfony crashes php server without providing any error log.
The server log provides me with the following information:

```
 [OK] Server listening on http://127.0.0.1:8000


 // Quit the server with CONTROL-C.

PHP 7.2.12 Development Server started at Wed Nov 28 15:20:14 2018
Listening on http://127.0.0.1:8000
Document root is /Users/christianbieg/Documents/Websites/symfony-test/public
Press Ctrl-C to quit.

 [ERROR] The process has been signaled with signal "11".

```
**How to reproduce**  

`composer create-project symfony/website-skeleton symfony-test && cd symfony-test`
`php bin/console server:run`

and then open the website on http://localhost:8000

**Comment by k0d3r1s** [comment] 2018-11-28 14:37
same here, only apache version. Apache dies with:
`[core:notice] [pid 1] AH00052: child pid 18 exit signal Segmentation fault (11)`

Symfony: 4.1.8
PHP: 7.2.11

**Comment by WithAlex** [comment] 2018-11-28 14:51
I have disable Opache and work find... But not a solution...

**Comment by stof** [comment] 2018-11-28 14:52
Please look at existing issues when reporting it: https://github.com/symfony/symfony/issues?utf8=%E2%9C%93&q=is%3Aissue+The+process+has+been+signaled+with+signal+%2211%22

Btw, Github even warned me about existing issues when I tried to enter the title `The process has been signaled with signal "11"` in an issue.

this issue is a duplicate of #29341, which is already fixed in the dev version of Symfony (we managed to find a workaround to avoid making PHP crash due to an OPCache bug).

**Closed by stof** 2018-11-28 14:52 UTC
