### ISSUE TITLE
About routing dynamic prefix

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#28603] opened 2018-09-26 06:20 UTC
**Description**  
I need a dynamic prefix.  I want to generate many subdirectories.

**Example**  

```
app_controllers:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix:   /{perfix}
```

page path:  /**perfix**/path_1
link:{{ path('p1') }} => /**perfix**/path_1/file.html
link:{{ path('p2') }} => /**perfix**/path_2/file.html
link:{{ path('p3') }} => /**perfix**/path_3/file.html
...

page path:  /**perfix**/path_1
link:{{ path('p1') }} => /**perfix**/path_1/file.html
link:{{ path('p2') }} => /**perfix**/path_2/file.html
link:{{ path('p3') }} => /**perfix**/path_3/file.html
...

Sometimes prefix is null.
page path:  /path_1
link:{{ path('p1') }} => /path_1/file.html
link:{{ path('p2') }} => /path_2/file.html
link:{{ path('p3') }} => /path_3/file.html
...

**Comment by iltar** [comment] 2018-09-26 07:16
Hey!

I don't understand what the issue is you're describing. Is it a bug or do you have a question on how to solve this? If you're describing a bug, please provide some information about the bug and how to reproduce it. If you have a question on how to solve your problem, please use one of the support channels on https://symfony.com/support

**Comment by imsheng** [comment] 2018-09-26 07:46
@iltar This is a feature request

**Comment by xabbuh** [comment] 2018-09-26 07:57
I am not sure I understand what you are asking for based on the description. Can you be a bit more specific of what exactly you would like to have added?

**Comment by imsheng** [comment] 2018-09-26 08:00
@iltar @xabbuh

**Comment by iltar** [comment] 2018-09-26 10:46
This sounds like multi tenancy and is not something I recommend to solve at application level, but server level. If you do this within your application, you'll also have trouble with dynamic database connections.

If your requirement is to add the client in the first part of the URL (or hostname, doesn't matter), you can use your webserver to match this part to a client and populate the application with the correct environment variables. This means you can have the same application for multiple clients, but you don't have to program any obscure configuration to get it to work.

Dynamic prefixes as a feature, I'm not sure if this is a good idea, I don't see a clear benefit.

**Comment by imsheng** [comment] 2018-09-26 14:35
@iltar  I need each user to have their own url in app. 

domain.com/app
domain.com/**user1**/app
domain.com/**user2**/app

I need to do this and get users.
So I hope that the routing function becomes more flexible.

**Comment by stof** [comment] 2018-09-26 14:46
parameters in prefixes are allowed, as the prefix is purely a configuration-level thing. Once we deal with the finalized route collection, we only have a path for each route, and the prefix used when importing them is part of this path.

however, making it possible to generate the route without passing the value for this parameter all the time (reusing the one from the matched route) requires more work as this param must become part of the router context (and I'm not sure what happens if not all your routes have it, and you omit the param when generating a URL while the matched route did not had the param).

Optional parameters in the beginning of the path (to allow matching `domain.com/app`) are a different topic. That's not supported AFAIK.
So for you, you might need to have 2 different route (with and without the prefix)

**Comment by imsheng** [comment] 2018-09-26 15:09
@stof I tried a lot of methods and failed in the end.

```
app2_controllers:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix:   /{user}
    requirements:
        user:  "\d+"

app_controllers:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix:   /
```

**Comment by javiereguiluz** [comment] 2018-09-29 14:12
My recommendation would be to [define a custom Twig function](https://symfony.com/doc/current/templating/twig_extension.html) in your Symfony app to generate those user-dependent links.

Instead of `{{ path('p1') }}` you'd use in your templates something like `{{ user_path('p1') }}`. That `user_path()` function can access to the current request (inject the `RequestStack` service in the Twig extension) and the current logged user (inject the `Security` service in the Twig extension) so you can generate those links in any way you need.

For that reason, I'm closing this feature request, because adding an option to make some parts of the generated links globally dynamic depending on the user is too specific and can't be added in Symfony core. thanks!

**Closed by javiereguiluz** 2018-09-29 14:12 UTC
Labels: Feature, Routing
