### ISSUE TITLE
[Serializer] Ignore on \"Proxies\\__CG__\\App\\Entity\\Customer::__setInitialized()\" cannot be added

### ISSUE THREAD

**Issue by vencakrecl** [symfony/symfony#54539] opened 2024-04-09 18:50 UTC
### Symfony version(s) affected

7.0.6

### Description

After upgrading to 7.0.6 I'm getting an error from the serializer.
Ignore on \"Proxies\\__CG__\\App\\Entity\\Customer::__setInitialized()\" cannot be added. Ignore can only be added on methods beginning with \"get\", \"is\", \"has\" or \"set\".

### How to reproduce

```php
<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \App\Entity\Customer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}

```

### Additional Context

```json
{
    "message": "Ignore on \"Proxies\\__CG__\\App\\Entity\\Customer::__setInitialized()\" cannot be added. Ignore can only be added on methods beginning with \"get\", \"is\", \"has\" or \"set\".",
    "detail": [
        {
            "file": "/var/www/html/vendor/symfony/serializer/Mapping/Loader/LoaderChain.php",
            "line": 51,
            "function": "loadClassMetadata",
            "class": "Symfony\\Component\\Serializer\\Mapping\\Loader\\AttributeLoader",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Mapping/Factory/ClassMetadataFactory.php",
            "line": 46,
            "function": "loadClassMetadata",
            "class": "Symfony\\Component\\Serializer\\Mapping\\Loader\\LoaderChain",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php",
            "line": 220,
            "function": "getMetadataFor",
            "class": "Symfony\\Component\\Serializer\\Mapping\\Factory\\ClassMetadataFactory",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php",
            "line": 144,
            "function": "getAllowedAttributes",
            "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractNormalizer",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
            "line": 244,
            "function": "getAllowedAttributes",
            "class": "Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
            "line": 157,
            "function": "getAttributes",
            "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Serializer.php",
            "line": 150,
            "function": "normalize",
            "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/symfony/serializer/Serializer.php",
            "line": 168,
            "function": "normalize",
            "class": "Symfony\\Component\\Serializer\\Serializer",
            "type": "->"
        }
    ]
}
```

**Comment by xabbuh** [comment] 2024-04-09 19:57
duplicate of https://github.com/symfony/symfony/issues/54477

**Closed as not planned by xabbuh** 2024-04-09 19:57 UTC
Labels: Serializer, Bug, Status: Needs Review
