### ISSUE TITLE
[DI] Circular reference in autowired decorators

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#42791] opened 2021-08-30 13:24 UTC
**Symfony version(s) affected**: 5.3.7

**Description**
Autowired decorators try to inject themselves and throw
```
Circular reference detected for service "App\ServiceDecorator",
path: "App\ServiceDecorator -> App\ServiceDecorator".
```

**How to reproduce**
https://github.com/vudaltsov/symfony-di-537-decorator-circular
Clone and install — you will see the error when clearing the cache during the composer installation.

**Possible Solution**
Revert https://github.com/symfony/symfony/pull/42347

**Comment by sidz** [comment] 2021-08-30 13:41
**Temporary Possible solutions**:
set **autoconfigure** to **false** for each decorator. 

a bit more details for possible solutions can be found in my duplicated issue: https://github.com/symfony/symfony/issues/42792 which has been closed in favor of this one.

**Comment by vudaltsov** [comment] 2021-08-30 13:44
The best solution is

```json
"conflict": {
    "symfony/dependency-injection": "5.3.7"
},
```

in `composer.json`.

**Comment by umulmrum** [comment] 2021-08-30 14:30
I encountered another problem but will add it here because it has the same cause (let me know if you prefer a separate issue).

I decorate the controller_resolver service as follows:

`->set(\xxx\routing\PageResolver::class)->decorate('controller_resolver')`

Constructor signature looks as follows:

`public function __construct(ControllerResolverInterface $subject)`

After upgrading to 5.3.7 I get this error:

`Cannot autowire service "xxx\routing\PageResolver": argument "$subject" of method "__construct()" references interface "Symfony\Component\HttpKernel\Controller\ControllerResolverInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "controller_resolver", "xxx\routing\PageResolver".`

When restoring the compiler pass order to the one in 5.3.6, it works again. Thanks for your help :-)

**Comment by bobdenotter** [comment] 2021-08-30 15:34
Ugh, I opened this as a duplicate. Will close that one now.. 

As an additional note: I think it was actually introduced in #40406 by @derrabus

**Comment by shyim** [comment] 2021-08-30 15:38
Hey all,

The 3 compiler passes seem to have a cross-reference together and can't be moved 🙈. I tried to do an another approach in AutowirePass. Could you guys test this if that helps on your side? This fixes already the issue with the reproducer repository.

```patch
Index: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php b/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
--- a/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php	(revision e2cc89030dc7970f3f2fcfb27262548b3380a53d)
+++ b/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php	(date 1630337802281)
@@ -153,8 +153,16 @@
         $this->decoratedClass = null;
         $this->getPreviousValue = null;
 
-        if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && null !== ($this->decoratedId = $definition->innerServiceId) && $this->container->has($this->decoratedId)) {
-            $this->decoratedClass = $this->container->findDefinition($this->decoratedId)->getClass();
+        if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && $definition->getDecoratedService() && null !== ($innerId = $definition->getDecoratedService()[0]) && $this->container->has($innerId)) {
+            $this->decoratedClass = $this->container->findDefinition($innerId)->getClass();
+            $currentDefinition = $this->container->getDefinition($this->currentId);
+            [$target, $innerId] = $currentDefinition->getDecoratedService();
+
+            if ($innerId === null) {
+                $innerId = $this->currentId . '.inner';
+            }
+
+            $this->decoratedId = $innerId;
         }
 
         foreach ($this->methodCalls as $i => $call) {
```

**Comment by bobdenotter** [comment] 2021-08-30 16:24
Hi, @shyim 👋 

> Could you guys test this if that helps on your side?

Yes. At least for Bolt, that seems to fix it!

**Comment by gnito-org** [comment] 2021-08-30 17:46
I was able to reproduce the error using the code at https://github.com/vudaltsov/symfony-di-537-decorator-circular.

Status: Reviewed

**Comment by umulmrum** [comment] 2021-08-31 09:34
@shyim That also fixes my problem :-)

**Comment by derrabus** [comment] 2021-08-31 09:36
@shyim Do you want to open a PR with your change (and a test 🥺)?

**Comment by shyim** [comment] 2021-08-31 10:01
@derrabus I can look tonight into it and create an pull request

**Comment by derrabus** [comment] 2021-08-31 14:05
Awesome!

**Comment by shyim** [comment] 2021-08-31 16:54
Is created https://github.com/symfony/symfony/pull/42815 😅

**Closed as completed** 2021-09-01 13:51 UTC
Labels: DependencyInjection, Bug, Status: Reviewed
