### ISSUE TITLE
Expose parameterized route in the request

### ISSUE THREAD

**Issue by cleptric** [symfony/symfony#48106] opened 2022-11-03 23:37 UTC
### Description

In order to be able to add more meaningful Span/Transactions names when using APM software (Sentry, Otel, ...) to instrument Smyonfy, it would be helpful to get access to the matched route via the request object.

By annotating a controller method with `#[Route('/users/edit/{id}')]`, I'm looking for a way to get the matched route programmatically.

```
/users/edit/1 -> /users/edit/{id}
```

The main use-case is low cardinality Span/Transaction names, which benefits the UX on various APM tools. 

https://github.com/getsentry/sentry-symfony/blob/d45365a249c479296e562baa7a18a9936c77ec5e/src/EventListener/TracingRequestListener.php#L43

**Comment by 94noni** [comment] 2022-11-04 08:57
There are data inside request->attributes
Are you thinking of those?

**Comment by cleptric** [comment] 2022-11-04 10:10
The `ParameterBag` does not look like to contain the data I'm looking for.
In our Laravel SDK, we did hook into a `RouteMatched` event, which will allow us to get access to the route object which contains a parameterized `uri`. Is there something similar in Symfony?

**Comment by 94noni** [comment] 2022-11-04 10:15
This is a part i have not very much knoledge, perhaps other can answer
But if we have the route name in request attributes i may think we can imagine adding route path as well

**Comment by MatTheCat** [comment] 2022-11-04 13:44
Given the parameterized path is function of the route name it would be simpler to get the latter: as the request’s `_route` attribute.

Else you’d need to hack your way with compiled routes or generate the route collection yourself, which I would not recommend.

**Comment by maxbeckers** [comment] 2022-11-04 13:46
You can take the RouteName from the Request and then use the router to get the Path.

Simple example in the controller action:
```
    #[Route('/test/{id}', name: 'app_test')]
    public function index(String $id, Request $request): Response
    {
        $route = $this->container->get('router')->getRouteCollection()->get($request->attributes->get('_route'));
        echo $route->getPath();

        // ...
    }
```
The echo will be `/test/{id}`. 

But I don't know if this is what you wanted?

**Comment by stof** [comment] 2022-11-04 13:53
This discussion looks like a duplicate of https://github.com/symfony/symfony/pull/47970 which has been rejected.

**Comment by derrabus** [comment] 2022-11-04 14:04
The general recommendation for APM systems is to use the route name which is unique for the whole application. Why would I want to use the parameterized path instead?

Note that the parameterized path does not exist in the compiled router anymore. We would need to store that information just to be able to expose it at runtime. And we should have a very good reason if we want to take that road.

**Comment by cleptric** [comment] 2022-11-04 14:14
The linked PR looks like it was rejected because of the way it was implemented, not that this feature is not useful to have in the framework.

I can definitely work around this by implementing something similar to https://github.com/worldia/instrumentation-bundle/pull/12/ but I feel like this would be better suited to be exposed by the framework.

@derrabus I can answer that from Sentry's perspective only

- Bad UX on the platform. Instead of having a concise list of parameterized transactions, you end up having a long list of unique transactions that can't be grouped together 
  - `/users/edit/1`
  - `/users/edit/2`
  ...
This also includes having transaction names like `app_users_index`, which is not a very nice OOTB experience.

- Overhead in storage/ingestion. We try to aim to have low cardinality in the data we store wherever possible. As I'm not working in these teams, I can't go into much more detail here, as I'm lacking the context.

**Comment by stof** [comment] 2022-11-04 14:37
@cleptric but `POST /users/edit/1` and `GET /users/edit/1` might reach different routes in Symfony. The route path is not the only criteria for matching a route, so using that alone would be inferior to using the route name.

Using the full URL as currently done in Sentry is indeed the worse option as it leads to high cardinality. But this is not our suggestion.

**Comment by cleptric** [comment] 2022-11-04 14:39
> Using the full URL as currently done in Sentry is indeed the worse option as it leads to high cardinality. But this is not our suggestion.

Yes, we agree, hence I opened this issue 😄

**Comment by GromNaN** [comment] 2022-11-04 16:43
In OpenTelemetry's [semantic name convention](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#name), the parameterized route path is given as an example. The intention is to use the route identifier.

> In case of HTTP servers, these endpoints are often mapped by the server frameworks to more concise HTTP **routes**, **e.g. `/api/users/{user_id}`**, which are recommended as the low cardinality span names.

In Datadog, the route name is used and this is very handy. https://github.com/DataDog/dd-trace-php/blob/867d30df5200744a81530f49519b95dc4451b4a4/src/Integrations/Integrations/Symfony/SymfonyIntegration.php#L154-L158

**Comment by derrabus** [comment] 2022-11-04 17:01
> * Bad UX on the platform. Instead of having a concise list of parameterized transactions, you end up having a long list of unique transactions that can't be grouped together
>
>   * `/users/edit/1`
>   * `/users/edit/2`

Note, this is *not* what I suggested: If you use the route name for grouping and you have a route that matches `/users/edit/{id}`, those two transactions would be grouped properly because they match the same route. You don't need the parameterized path to group those.

> This also includes having transaction names like `app_users_index`, which is not a very nice OOTB experience.

Well why not, if that's the name the developer chose for that particular route?

> * Overhead in storage/ingestion. We try to aim to have low cardinality in the data we store wherever possible. As I'm not working in these teams, I can't go into much more detail here, as I'm lacking the context.

I fail to see how grouping by route name generates more overhead compared to parameterized paths. Can you elaborate?

If you want to group requests matching the same route, the route name is your best bet. It's unique for the whole application while the parameterized patch could be ambiguous. The same path could be used for different routes if:

* the routes use different HTTP Methods
* the routes match the hostname as well
* the routes use different patterns ("requirements") for matching the parameters
* … (probably more stuff I haven't thought of)

**Comment by stof** [comment] 2022-11-04 17:09
> * … (probably more stuff I haven't thought of)

* the routes use expression-based conditions
* the routes match the scheme as well

**Comment by cleptric** [comment] 2022-11-04 17:10
So back to topic 😄 

Would you consider exposing the parameterized route somewhere?

**Comment by stof** [comment] 2022-11-04 17:16
We rejected exposing this in core in the PR I linked above because it would encourage misuses.

We already expose the name of the matched route. If you really insist of using the parameterized path for monitoring instead of the route name (despite being only 1 of the 7 criteria that impact the route matching), you could build your own service that converts the route name to such path.
If you don't care about performance, you can use the dumb implementation suggested above in https://github.com/symfony/symfony/issues/48106#issuecomment-1303563130. If you care about performance, you would pre-generate the mapping in a cache-warmer instead of reload the route collection each time you want the info.

**Comment by derrabus** [comment] 2022-11-04 17:29
> So back to topic 😄

Well, I don't think that we've been off-topic here.

> Would you consider exposing the parameterized route somewhere?

To quote myself:

> We would need to store that information just to be able to expose it at runtime. And we should have a very good reason if we want to take that road.

Right now, I'm not convinced we should build this into the core. Since you don't care to respond to the arguments I brought up, that's a no from my side, I guess.

That being said, if you hooked into the route compilation and copied the path of each route into the defaults of that route, who's gonna stop you? 😉

**Comment by stof** [comment] 2022-11-04 17:33
> That being said, if you hooked into the route compilation and copied the path of each route into the defaults of that route, who's gonna stop you?

My proposal of building a separate service with its own cache warmer is probably much easier to implement than such hooking into the route compilation though (even though it involves reading routes twice during cache warmup, as this warmup would be separate from the route compilation).

> Since you don't care to respond to the arguments I brought up, that's a no from my side, I guess.

To be explicit, that's also a second no from my side here.

**Comment by cleptric** [comment] 2022-11-04 21:14
I am sorry if this sounded a bit harsh, but I have the feeling this drifted into a direction of how we should set our transaction names in Sentry compared to my initial request to expose the parametrized route.

I'm happy to iterate on this

> Well why not, if that's the name the developer chose for that particular route?

```php
#[Route('/users/edit/{id}')]
public function edit(int $id): Response
{
}
 ```
 
 This will result in a route name of `app_users_edit` by default. Not ideal in terms of UX.
 
 > I fail to see how grouping by route name generates more overhead compared to parameterized paths. Can you elaborate?
 
It doesn't, but it just looks bad. The main issue are un-parameterized routes.
We have additional properties on transactions, so we do not worry about different request methods and such.

> We rejected exposing this in core in the PR I linked above because it would encourage misuses.
> 
> We already expose the name of the matched route. If you really insist of using the parameterized path for monitoring instead of the route name (despite being only 1 of the 7 criteria that impact the route matching), you could build your own service that converts the route name to such path. If you don't care about performance, you can use the dumb implementation suggested above in [#48106 (comment)](https://github.com/symfony/symfony/issues/48106#issuecomment-1303563130). If you care about performance, you would pre-generate the mapping in a cache-warmer instead of reload the route collection each time you want the info.

I just want to hook into this. Exposing caches or expensive methods calls are simply not an option. The framework should make this easy for users.

> Right now, I'm not convinced we should build this into the core. Since you don't care to respond to the arguments I brought up, that's a no from my side, I guess.

I do work at an open-source company and heavily rely on upstream software to improve our SDKs. If I didn't care, I wouldn't have brought this up.

> That being said if you hooked into the route compilation and copied the path of each route into the defaults of that route, who's gonna stop you?

This seems fragile to me.

> My proposal of building a separate service with its own cache warmer is probably much easier to implement than such hooking into the route compilation though (even though it involves reading routes twice during cache warmup, as this warmup would be separate from the route compilation).


It's hard for us to make assumptions about how and where people run their apps, so relying on caches (filesystem, etc.) is something I rather not do.

PS: I'll be at the Sentry booth during SymfonyCon Paris, so if you would like to have an in-person chat about this, please stop by!

**Closed as completed** 2023-03-15 00:34 UTC
Labels: Routing, RFC
