### ISSUE TITLE
[DependencyInjection] Autowiring deprecations after upgrading to 3.4.0

### ISSUE THREAD

**Issue by leperse** [symfony/symfony#25235] opened 2017-11-30 23:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

After upgrading my Symfony app to 3.4.0 final, I see these deprecations (that weren't shown in 3.3.13) :

`Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should alias the "AppBundle\Entity\User" service to "Symfony\Component\Security\Core\User\UserInterface" instead.`

`User Deprecated: The "assetic.filter_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

`User Deprecated: The "assetic.filter.cssrewrite" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

**Comment by mattwoo** [comment] 2017-12-01 13:22
You have to make these services public (2 last errors) by setting public: true in yaml file 
for nr 1 you have to typehint your services to UserInterface instead of User class

**Comment by nicolas-grekas** [comment] 2017-12-01 13:39
> You have to make these services public (2 last errors) by setting public

actually I would rather say (from the message):
You should either make the service public, **or stop using the container directly and use dependency injection instead**.

I'm closing since a new deprecation is not a bug: minor versions are exactly for that (feature *&* deprecations)

**Closed by nicolas-grekas** 2017-12-01 13:39 UTC

**Comment by chalasr** [comment] 2017-12-01 14:09
I'm curious about the origin of the first deprecation notice. in which context is it triggered? We should never try to inject an entity as if it was a service

**Comment by nicolas-grekas** [comment] 2017-12-01 14:31
@chalasr autoregistration

**Comment by nicolas-grekas** [comment] 2017-12-01 14:31
Which means actually the fix is maybe just to turn the `container.autowiring.strict_mode` parameter to `true` btw!

**Comment by chalasr** [comment] 2017-12-01 14:35
@nicolas-grekas thanks :)

**Comment by leperse** [comment] 2017-12-02 14:18
- I solved the first issue with :

in services.yml

`    Symfony\Component\Security\Core\User\UserInterface:

    AppBundle\Entity\User:
        alias: Symfony\Component\Security\Core\User\UserInterface`

@mattwoo I can't typehint my controllers to UserInterface instead of User class, because I need to modify the selected user and not the current user.

This is the controller where I typehinted the User class :

`/**
     * Displays a form to edit an existing User entity.
     *
     * @Route("/{id}/edit", name="admin_user_edit", requirements={"id": "\d+"})
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, User $entity, UserInterface $currentUser): Response
    {
         ....
    }`

- 2nd and 3rd issues, I chose to remove completely Assetic Bundle, it won't survive next updates and surely Symfony 5.

**Comment by xabbuh** [comment] 2017-12-04 08:15
@leperse Did you try to set the `container.autowiring.strict_mode` parameter to `true`?

**Comment by adrienfr** [comment] 2017-12-06 14:08
I tried to set `container.autowiring.strict_mode` to `true` but I still have these messages in 3.4:

`The "assetic.filter.uglifycss" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead: 97x`

`The "assetic.filter.less" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead: 83x`

`The "assetic.filter.cssrewrite" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead: 79x`

Is this parameter only to fix the entity message ?
