### ISSUE TITLE
translation:extract fails in symfony/translation 6.2.0

### ISSUE THREAD

**Issue by moverboom** [symfony/symfony#48604] opened 2022-12-12 07:49 UTC
### Symfony version(s) affected

6.2.1

### Description

When running `translation:extract` it fails with the following message:
```
Uncaught Error: 
assert(!$this->isFirstClassCallable()) 
{"exception":"[object] (AssertionError(code: 1): assert(!$this->isFirstClassCallable()) at /app/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php:36)"}
```
given that [nikic/php-parser](https://packagist.org/packages/nikic/) hasn't had a new release in a month I think the issue is related to Symfony.

### How to reproduce

Installed versions:
```
name     : symfony/translation
descrip. : Provides tools to internationalize your application
keywords : 
versions : * v6.2.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/translation.git c08de62caead8357244efcb809d0b1a2584f2198
dist     : [zip] https://api.github.com/repos/symfony/translation/zipball/c08de62caead8357244efcb809d0b1a2584f2198 c08de62caead8357244efcb809d0b1a2584f2198
path     : /app/vendor/symfony/translation
names    : symfony/translation, symfony/translation-implementation

support
source : https://github.com/symfony/translation/tree/v6.2.0

autoload
files
psr-4
Symfony\Component\Translation\ => .
exclude-from-classmap

requires
php >=8.1
symfony/polyfill-mbstring ~1.0
symfony/translation-contracts ^2.3|^3.0

requires (dev)
nikic/php-parser ^4.13
psr/log ^1|^2|^3
symfony/config ^5.4|^6.0
symfony/console ^5.4|^6.0
symfony/dependency-injection ^5.4|^6.0
symfony/finder ^5.4|^6.0
symfony/http-client-contracts ^1.1|^2.0|^3.0
symfony/http-kernel ^5.4|^6.0
symfony/intl ^5.4|^6.0
symfony/polyfill-intl-icu ^1.21
symfony/routing ^5.4|^6.0
symfony/service-contracts ^1.1.2|^2|^3
symfony/yaml ^5.4|^6.0

suggests
nikic/php-parser To use PhpAstExtractor
psr/log-implementation To use logging capability in translator
symfony/config 
symfony/yaml 

provides
symfony/translation-implementation 2.3|3.0

conflicts
symfony/config <5.4
symfony/console <5.4
symfony/dependency-injection <5.4
symfony/http-kernel <5.4
symfony/twig-bundle <5.4
symfony/yaml <5.4
```
```
name     : nikic/php-parser
descrip. : A PHP parser written in PHP
keywords : parser, php
versions : * v4.15.2
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : 
source   : [git] https://github.com/nikic/PHP-Parser.git f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc
dist     : [zip] https://api.github.com/repos/nikic/PHP-Parser/zipball/f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc
path     : /app/vendor/nikic/php-parser
names    : nikic/php-parser

support
issues : https://github.com/nikic/PHP-Parser/issues
source : https://github.com/nikic/PHP-Parser/tree/v4.15.2

autoload
psr-4
PhpParser\ => lib/PhpParser

requires
ext-tokenizer *
php >=7.0

requires (dev)
ircmaxell/php-yacc ^0.0.7
```

Running `translation:check` should trigger the same exception

**Comment by Broutard** [comment] 2022-12-12 10:10
Seems fail on https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php#L71

I reverted to 6.1

**Comment by DevinKuehn** [comment] 2022-12-12 11:26
Duplicate of https://github.com/symfony/symfony/issues/48422?

**Comment by Broutard** [comment] 2022-12-12 12:56
@DevinKuehn I think yes !

**Comment by xabbuh** [comment] 2022-12-12 13:10
close close here in favor of #48422 then

**Closed as not planned by xabbuh** 2022-12-12 13:10 UTC
Labels: Bug, Translation, Status: Needs Review, Status: Waiting feedback
