### ISSUE TITLE
V3.2.1 parameters.yml database_user underscore character removed

### ISSUE THREAD

**Issue by Lopton** [symfony/symfony#21139] opened 2017-01-02 18:02 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | YES
| Feature request? | NO
| BC Break report? | ??
| RFC?             | ??
| Symfony version  | 3.2.1

I tried to upgrade from Symfony 3.1.8 to 3.2.1 using composer. During the cache clear I received an error stating 

> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '########'@'IpAddress' (using password: YES)

however my database user name should be #######_#, notice the underscore in the second to last character position. Looking in the parameter.yml file I found that my database_user had been changed to remove the _ from the username. I then added back my underscore, deleted the dev cache, and tried the application again. I received the same error as before.

Since composer also updated doctrine and the FOSuser bundle at the same time I reverted the update and went back to my prior configuration by reverting my composer.lock file. I then ran my Symfony application again in the version 3.1.8 and it worked fine. 

To isolate the problem further I used composer and upgraded ONLY symfony from 3.1.8 to 3.2.1. The upgrade produced errors at the cache clear with the above error message, and in my parameters.yml file my database_user again had the underscore removed from the username. I re-inserted the underscore, however I continue to get the error messages:
> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '########'@'IpAddress' (using password: YES)

If I add a letter to the end of my database_user so it is "#######_#a" the error message shows the _
> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '#######_#a'@'IpAddress' (using password: YES)

If I then delete the letter the error message reverts to no underscore
> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '########'@'IpAddress' (using password: YES)

This leads me to believe that some change in Symfony between 3.1.8 and 3.2.1 strip underscores from the database_user in the parameters.yml file. Unfortunately I am not skilled enough to figure out where that code may be.

After about an hour I stumbled onto the Symfony\Component\Yaml\Parser and found some code that led me to believe if I put quotes around the database_user value it may do something different. And that did fix it so now I can run my application. I still feel like this may be a bug, if not please close this?

**Comment by xabbuh** [comment] 2017-01-02 18:05
I guess this is caused by the changes from #18486.

**Comment by xabbuh** [comment] 2017-01-02 18:07
However, I am not sure if we can really help you with this. The changes from #18486 added a new feature that made the parser even more compliant with the YAML spec.

**Comment by Lopton** [comment] 2017-01-02 18:10
Thank you, that looks like it. I probably hit a strange use case since my username is all numbers with the _ at the second to last character.

My workaround of quotes around the user name solves it for me, and seems to force recognition of the value as a string.

**Comment by javiereguiluz** [comment] 2017-01-03 12:11
@Lopton thanks for reporting this issue.

As @xabbuh said, this is caused by some changes introduced by Symfony 3.2 to make it more compliant with the Yaml spec. If your username is `1234567_8` in Symfony 3.1 it will be parsed as `(string) "1234567_8"` and in Symfony 3.2 it will be parsed as `(int) 12345678`  Luckily the solution is simple because you just need to wrap the string values with single or double quotes. Besides, this is a good practice to avoid any problem with future Yaml spec changes.

Therefore, I'm afraid that we must close this issue report as "won't fix" because we introduced this breaking change in a major Symfony version (3.1 -> 3.2), so that's OK according to our BC policy. I hope you understand it. Thanks!

**Closed by javiereguiluz** 2017-01-03 12:11 UTC
Labels: Yaml
