### ISSUE TITLE
[BUG][DependencyInjection] Syntax error in var/cache/dev/appDevDebugContainer.php

### ISSUE THREAD

**Issue by entepe85** [symfony/symfony#19201] opened 2016-06-28 07:09 UTC
Upon clearing the cache a fatal error is thrown:

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [...]var/cache/dev/appDevDebugProjectContainer.php:7161`

Here's the corresponding line:
`class VichUploaderBundleHandlerUploadHandler_000000003557d388000000006581de10da75941a549785cf26d7df71050c90e4 extends \\Vich\UploaderBundle\Handler\UploadHandler implements \\ProxyManager\Proxy\VirtualProxyInterface
{`
It's obvious that the error is caused by the duplicate backslashes.

[#9815](https://github.com/symfony/symfony/issues/9815) seems to be related, but [#9816](https://github.com/symfony/symfony/pull/9816) does not fix this behaviour since it started after the most recent `composer update`.

**Comment by xabbuh** [comment] 2016-06-28 07:21
Can you please provide some steps on how to reproduce your issue and/or fork the Symfony Standard Edition and modify it in a way that makes it possible to reproduce this?

**Comment by entepe85** [comment] 2016-06-28 07:38
Only thing I knowingly did was to update the composer packages in the project.
Here's the package list from that projects composer.json:

`"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "^3.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "kimk/page-bundle": "@dev",
        "friendsofsymfony/user-bundle": "@dev",
        "vich/uploader-bundle": "^1.0",
        "guzzlehttp/guzzle": "^6.2",
        "eightpoints/guzzle-bundle": "^4.5",
        "gedmo/doctrine-extensions": "dev-master",
        "cbschuld/browser.php": "@dev"
    }`

Other than this I made no conscious changes to the project.

**Comment by xabbuh** [comment] 2016-06-28 07:57
Can you please show the output of `composer show`?

**Comment by entepe85** [comment] 2016-06-28 08:22
I put it into a [Pastebin here](http://pastebin.com/H8AXAJkT).

**Comment by lemorragia** [comment] 2016-06-28 08:34
i can confirm this issue too, tried to update this morning and got the same error. I'm working on php7, and symfony 2.8.x-dev...i already tried to downgrade symfony/symfony, but apparently the problem is not there...[here](http://pastebin.com/BtnPXFbT) is my composer show

**Comment by wannaporn** [comment] 2016-06-28 08:47
I have got this problem too.

**Comment by lemorragia** [comment] 2016-06-28 08:50
i could also add that the problem is probably been introduced in the last 24h...luckily i had an update yesterday with the same dependencies and everything was fine

**Comment by RaphaelSalique** [comment] 2016-06-28 09:30
Same problem too

**Comment by AntoineNseir** [comment] 2016-06-28 09:48
Same problem here.

**Comment by realityking** [comment] 2016-06-28 09:49
#9815 is ancient. I did however do a similar change in in #18682.

I won't have time to investigate this before Thursday. As a side note, we should expand the tests for the DIC to include namespaces classes.

**Comment by realityking** [comment] 2016-06-28 09:51
Just saw that the problem seems to occur in 2.8.x. That excludes #18682 as it was only merged in 3.0.x.

**Comment by AntoineNseir** [comment] 2016-06-28 10:09
I think it's the version 3.0.3 of zendframework/zend-code that cause the issue. I put the line "zendframework/zend-code": "3.0.2" in my composer.json and everything works fine.

"require": {
        "php": ">=7.0",
        "symfony/symfony": "3.0.*",
        "alcaeus/mongo-php-adapter": "^1.0.0",
        "ext-mongo": "*",
        "doctrine/mongodb-odm": "^1.1.0",
        "doctrine/mongodb-odm-bundle": "~3.0",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/assetic-bundle": "^2.7",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "liip/imagine-bundle": "^1.3",
        "knplabs/knp-paginator-bundle": "^2.5",
        "vich/uploader-bundle": "^1.0.1",
        "jms/security-extra-bundle": "dev-master",
        "mobiledetect/mobiledetectlib": "^2.8",
        "mongodb/mongodb": "^1.0.0",
        "twig/extensions": "^1.3",
        "cocur/slugify": "^2.1",
        "jms/translation-bundle": "dev-master",
        "zendframework/zend-code": "3.0.2"
    },

**Comment by lemorragia** [comment] 2016-06-28 10:17
confirmed...3.0.2 version of zend-code solves the issue

**Comment by stof** [comment] 2016-06-28 10:25
Then please report the bug to zend-code

**Comment by Tsupakin** [comment] 2016-06-28 10:31
Thank @AntoineNseir

**Comment by entepe85** [comment] 2016-06-28 11:03
> Then please report the bug to zend-code

Will do that asap.

**Comment by fabpot** [comment] 2016-06-28 11:05
Closing then.

**Closed by fabpot** 2016-06-28 11:05 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Unconfirmed
