### ISSUE TITLE
[DependencyInjection] env var support broken in 3.3.7 and 3.3.8

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#24020] opened 2017-08-29 09:22 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.7, 3.3.8

I'm using sf flex with propel. This is part of my config:

```yaml
propel:
    database:
        connections:
            default:
                adapter:  pdo_mysql
                user:     '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dsn:      'pdo_mysql:host=%env(DATABASE_HOST)%;dbname=%env(DATABASE_NAME)%;charset=utf8'
```

With symfony/dependency-injection 3.3.7 and 3.3.8 I get this exception:

![screenshot 2017-08-29 11 20 52](https://user-images.githubusercontent.com/330436/29814010-266f3680-8cac-11e7-80c5-e30478bc4baa.png)

https://github.com/symfony/symfony/pull/24016 didn't fix this case.

When I switch back to 3.3.6 it works again.

ping @nicolas-grekas

**Comment by stof** [comment] 2017-08-29 09:32
@nicolas-grekas looks like the env placeholder is not replaced back properly anymore in the processed container after your fix.

**Comment by nicolas-grekas** [comment] 2017-08-29 10:01
@gharlan can you share a reproducer please?

**Comment by nicolas-grekas** [comment] 2017-08-29 10:19
@gharlan can you please try #24021

**Comment by gharlan** [comment] 2017-08-29 10:30
It does not fix it. I can try to create a reproducer, but before, some infos about PropelBundle, maybe it already helps to find the reason:

The PropelBundle writes the config to a parameter:

https://github.com/propelorm/PropelBundle/blob/61ef13c80380b74609501e8d4a1927cfd4d1acec/DependencyInjection/PropelExtension.php#L50

And this parameter is read later and passed to the connection manager (Line 82):

https://github.com/propelorm/PropelBundle/blob/3.0/PropelBundle.php#L57

When I add a breakpoint here, and look into `$this->container`, there is a difference in `container->dynamicParameters['propel.configuration']`.

In 3.3.6 the env vars are resolved (`DATABASE_HOST` -> `localhost`) etc, in 3.3.7, 3.3.8 and your pr, they are only replaced by `env_DATABASE_HOST_ad096d2943aaf75934bd7232501a52ec` etc.

**Comment by nicolas-grekas** [comment] 2017-08-29 12:21
OK, I can reproduce, working on it now.

**Comment by nicolas-grekas** [comment] 2017-08-29 12:50
Now fixed in #24021 and also in https://github.com/propelorm/PropelBundle/pull/461

**Comment by Simperfit** [comment] 2017-08-31 09:39
This can be closed @nicolas-grekas.

**Comment by xabbuh** [comment] 2017-08-31 09:45
@SimperFit Are you sure? #24021 isn't merged yet.

**Closed** 2017-08-31 21:54 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
