### ISSUE TITLE
[Form][Translation] Date components are translated

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#15222] opened 2015-07-07 14:10 UTC
When using a `date` field, say

```php
->add('endAt', 'date', array(
        'format' => \IntlDateFormatter::LONG,
        'years' => range(date('Y'), date('Y') + 10),
))
```
all options are translated:

| State | Locale | Domain | Id | Message Preview |
| ------- | --------- | ---------- | --- | ------------------------ |
| missing | fr | forms | 2015 | 2015 |
| missing | fr | forms | 2016 | 2016 |
| missing | fr | forms | 2017 | 2017 |
|  |  |  |  |  |
| missing | fr | forms | janvier | janvier |
|  |  |  |  |  |
| missing | fr | forms | 1 | 1 |
| missing | fr | forms | 2 | 2 |
| missing | fr | forms | 3 | 3 |
|  |  |  |  |  |

I don't know if it's really an issue but I don't like seeing red in the web profiler!

**Comment by aitboudad** [comment] 2015-07-17 12:09
Closing as duplicate of #15298 and fixed by #15301.

**Closed by aitboudad** 2015-07-17 12:09 UTC
Labels: Form, Translator
