### ISSUE TITLE
[DependencyInjection] Configurator not called on lazy services ?

### ISSUE THREAD

**Issue by geoffrey-brier** [symfony/symfony#48255] opened 2022-11-20 10:23 UTC
### Symfony version(s) affected

6.2.0-BETA3

### Description

Hi :wave: 

I am trying to upgrade my app in symfony 6.2 & I spotted a bug on configurators.
Indeed when a service using a configurator is declared as lazy then the configurator is not called.

### How to reproduce

```yaml
    # services.yaml
    
    App\Services\PaymentManagerConfigurator:
        arguments:
            $key: '%env(STRIPE_API_KEY)%'
            
    App\Services\PaymentManager:
        configurator: '@App\Services\PaymentManagerConfigurator'
# If I comment this line, the configurator is called, else it won't
#        lazy: true
 ```

**Comment by xabbuh** [comment] 2022-11-20 11:14
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment] 2022-11-21 09:49
The configurator won't be called at the time the lazy proxy is created. But it will be called when triggering the initialization of the service.

**Comment by geoffrey-brier** [comment] 2022-11-21 09:58
Yes I know @stof but the point is that it wasn't called at all in my case as I had an exception from stripe saying that it wasn't properly configured. I'm going to create an app today to try and reproduce the issue.

**Comment by geoffrey-brier** [comment] 2022-11-21 13:19
All right I think I got it and that was quite a vicious one but I got it :sweat_smile:

As far as I understand by debugging, configurators are only triggered if one of the property of the configured service is called. In other words if you don't call a property right away in your configured service then your configurator won't ever be called.

Let's say with have the following classes :

```
class FooConfigurator
{
    public function __invoke(): void
    {
        FooUtil::$hello = 'YO'
    }
}

class FooUtil
{
   public static $hello = 'HI';
}
```

Let's also assume that `FooConfigurator` is the configurator of class `Foo`.

In this case this will not work :

```
<?php

class Foo
{
    public function bar(): void
    {
        echo FooUtil::$hello; // WILL PRINT HI
    }
}

```

And this will work :

```
<?php

class Foo
{
   private $whateverProperty;

    public function bar(): void
    {
        $this->whateverProperty;
        echo FooUtil::$hello; // WILL PRINT YO
    }
}
```

You can try and reproduce the bug via this repository : https://github.com/geoffrey-brier/symfony_issue_48255
Simply clone the project and call the `debug:foo` command

**Comment by nicolas-grekas** [comment] 2022-11-21 13:30
I would say this is expected as of 6.2 at least.
Doing what's done in your reproducer is hacking the concept of lazy services to make lazy classes instead (lazy initializing static properties).
Services should not rely only on global state.
This looks like a "won't fix" to me.

**Comment by geoffrey-brier** [comment] 2022-11-21 13:41
All right, that's clearly a change of behaviour between 6.1 & 6.2 but I understand.

I'm going to change the initialization logic in my legacy app in this case.

**Closed as not planned** 2022-11-21 13:50 UTC
Labels: DependencyInjection, Bug, Status: Needs Review, Status: Waiting feedback
