### ISSUE TITLE
Invalidate tags not working

### ISSUE THREAD

**Issue by pawellewandowski** [symfony/symfony#27306] opened 2018-05-18 10:51 UTC
**Symfony version(s) affected**: 3.4.9

**Description**  
Cache don't invalidate tags. In version 3.4.8 everything working fine.

**How to reproduce**  

```
        $cache = new TagAwareAdapter(
            new FilesystemAdapter(),
            new FilesystemAdapter()
        );

        $review = $cache->getItem('reviews-1');
        $review->set('test');
        $review->tag(['reviews']);
        $cache->save($review);
        dump($cache->getItem('reviews-1')->isHit()); //true - correct

        $cache->invalidateTags(['reviews']);

        dump($cache->getItem('reviews-1')->isHit()); //false - correct

        $cache = new TagAwareAdapter(
            new FilesystemAdapter(),
            new FilesystemAdapter()
        );
        $review = $cache->getItem('reviews-1');
        dump($cache->getItem('reviews-1')->isHit()); //true - incorrect / why ?
```

Probably error in GH-27007

**Comment by xabbuh** [comment] 2018-05-18 12:09
This looks like a duplicate of #27147 which was fixed in #27158 and will be part of Symfony 3.4.10.

**Closed by xabbuh** 2018-05-18 12:09 UTC
