### ISSUE TITLE
fix merge issue in  Symfony\Translation

### ISSUE THREAD

**Issue by jaminellis** [symfony/symfony#43223] opened 2021-09-28 09:37 UTC
**Symfony\Translation 5.3.8

**Description**
https://github.com/symfony/translation/tree/v5.3.8 seems to have moved the files into the route, which is leading to multiple errors eg Uncaught Error: Class 'Symfony\Component\Translation\Formatter\MessageFormatter' not found in /var/www/html/vendor/symfony/translation/Translator.php on line 97

**How to reproduce**
Any use of the Translator class will reproduce this

**Possible Solution**
revert the files back to their correct directories

**Additional context**
This happened 39 minutes ago, with the 5.3.8 release

**Comment by jderusse** [comment] 2021-09-28 09:38
Duplicate of #43212

**Closed as completed by jderusse** 2021-09-28 09:38 UTC
Labels: Bug, Status: Needs Review
