### ISSUE TITLE
[Symfony/mailer] symfony integration for SendInBlue 

### ISSUE THREAD

**Issue by AhmetBas** [symfony/symfony#31902] opened 2019-06-06 13:29 UTC
The Symfony/mailer has several SMTP providers integrations. Would you be considering adding SendInBlue integration for the mailer component?

**Comment by javiereguiluz** [comment] 2019-06-07 07:41
I don't know if it's the official Symfony position, but my understanding is that the Mailer component is going to do the same as we do for form themes. We only add form theme support for the most popular CSS frameworks in the world (Bootstrap, Foundation, ...) and the rest of frameworks must be supported by the community.

The Mailer component looks like it's doing the same: provide support only for the most popular mailer services in the world ... and the community can provide support for the other services as third-party packages.

**Comment by ajgarlag** [comment] 2019-06-07 07:47
@javiereguiluz The problem is that there isn't an easy way to enable third-party transports. See #31385

**Comment by javiereguiluz** [comment] 2019-06-07 08:12
@ajgarlag thanks! I wasn't aware of that. I guess that will be considered a missing feature and be implemented in the future (hopefully soon).

**Comment by bullder** [comment] 2019-06-07 10:53
I think you should use their api https://github.com/sendinblue/APIv3-php-library
Integration with marketing platform is not about sending emails in common sense but more about triggering api

**Comment by fabpot** [comment] 2019-06-07 10:56
If you are using their library, no need to use Symfony Mailer. All integrations are relying only on SMTP or direct implementation of the API.

**Comment by AhmetBas** [comment] 2019-06-07 13:01
@fabpot They have SMTP as API integration. If it's possible to add it, it will be appreciated. This way it's easier to switch from SMTP provider if needed without many changes. Another advantage is to use the HTTP client of Symfony and not guzzle.

**Comment by fabpot** [comment] 2019-06-29 08:55
After #31946 is merged, it will be easy to create a third-party package providing this.

**Closed by fabpot** 2019-06-29 08:55 UTC
Labels: Feature, Mailer

**Comment by elhayadi** [comment] 2020-10-21 11:54
1- use statements:

```
use SendinBlue\Client\Configuration;
use SendinBlue\Client\Api\AccountApi;
use SendinBlue\Client\ApiClient;
use SendinBlue\Client\Api\SMTPApi;
use SendinBlue\Client\Model\SendSmtpEmail;
```

2- send simple email:
```
$config = Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR_API_KEY');

        $apiInstance = new SMTPApi(
            // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
            // This is optional, `GuzzleHttp\Client` will be used as default.
            new ApiClient(),
            $config
        );
       // string | Unique id of the transactional email that has been sent to a particular contact
        $sendSmtpEmail = new SendSmtpEmail(); // \SendinBlue\Client\Model\SendSmtpEmail | Values to send a transactional email
        $sendSmtpEmail['to'] = array(array('email'=>'elhayadi999@gmail.com', 'name'=>'mohamed elhayadi'));
        $sendSmtpEmail['templateId'] = 3;// you should create a template in sendinblue and get her the id 
        $date =new DateTime();
        $sendSmtpEmail['params'] = array(
            'NUM_RESERVATION'=>166458,
            'DEBUT_RESERVATION'=>$date, 
            'FIN_RESERVATION'=>$date, 
            'PLAGE'=>"12:00 à 14:00", 
            'Payed'=>true,
            'NBR_HEURES'=> 2, 
            'NOM'=>"elhayadi", 
            'PRENOM'=> "mohamed",
            'FUSEAU_HORAIRE'=>"PARIS");
        try {
            $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
       
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling TransactionalEmailsApi->getTransacEmailContent: ', $e->getMessage(), PHP_EOL;
        }
```

**Comment by n3verlate** [comment] 2021-04-29 15:38
> use SendinBlue\Client\Configuration;
> use SendinBlue\Client\Api\AccountApi;
> use SendinBlue\Client\ApiClient;
> use SendinBlue\Client\Api\SMTPApi;
> use SendinBlue\Client\Model\SendSmtpEmail;

not working :(
