### ISSUE TITLE
[PHPUnitBridge] tests don't tear down properly?

### ISSUE THREAD

**Issue by craue** [symfony/symfony#15541] opened 2015-08-13 12:42 UTC
I've got a Symfony 2.7 project and its tests run fine, but when using the PHPUnit bridge I'm getting lots of `Too many connections` errors from the database, so it seems that the bridge somehow prevents those connections from being closed between tests. Is this a bug or is there anything I can do about it?

**Comment by nicolas-grekas** [comment] 2015-08-13 12:58
Looking at the code, I can't see anything that triggers this issue.
Can you tell me on which php version you are, and how to you use the bridge?

**Comment by craue** [comment] 2015-08-13 13:07
PHP 5.6.8

In my composer.json, I added

```json
"require-dev": {
	"symfony/phpunit-bridge": "~2.7.3"
}
```

and ran `composer update symfony/phpunit-bridge` to install it. Then the errors occured when running `phpunit -c app`. Removing the bridge afterwards makes the test pass again.

**Comment by craue** [comment] 2015-08-28 11:23
It also happens with PHP 5.6.12. Any ideas?

**Comment by jakzal** [comment] 2015-09-16 07:42
@craue it would be much easier if you provided a small project that reproduces your issue.

**Comment by craue** [comment] 2015-09-16 16:40
@jakzal, I'm sure it would. But it's hard to make that up as it happens with a quite heavy test suite.

I could more or less track down the issue in my project. It only happens in integration tests where requests are made, so there's one database connection opened within the test itself (which creates a kernel to setup things before a test and to assert stuff afterwards) and one inside of the request. I can only guess that one of both is not closed properly in each case. But I worked around the issue by adding

```php
public function shutdown() {
	if ($this->booted === false) {
		return;
	}

	$this->container->get('doctrine.orm.entity_manager')->getConnection()->close();

	parent::shutdown();
}
```

to my projects' `AppKernel`. This ensures that the connection is always closed, which lowers the number of concurrent database connections to exactly 1.

But now, after applying this change, there's a new issue: The memory consumption is pretty high, too high for my 2 GB limit.

- symfony/symfony 2.7.4, symfony/phpunit-bridge **not installed**:
  Time: 24.03 minutes, Memory: 1284.50Mb
  OK (412 tests, 3656 assertions)

- symfony/symfony 2.7.4, symfony/phpunit-bridge **2.7.4**:
  Fatal error: Out of memory (allocated 1706819584) (tried to allocate 67108864 bytes)

So there's still something preventing memory to be freed between tests.

**Comment by nicolas-grekas** [comment] 2015-11-25 15:23
IMHO the issue is that the phpunit bridge collects deprecations in an array that consumes memory. If your test suite is huge, the array can grow big. I don't think we need to fix anything, but instead I think that you should fix the deprecations. I guess some of them are VERY frequent but easy to fix. Run only a subpart of your test suite to get the first deprecations to fix.
I don't know the relationship with the db connection. I see none in fact.

**Comment by nicolas-grekas** [comment] 2016-01-06 10:04
Closed by #17275

**Closed by nicolas-grekas** 2016-01-06 10:04 UTC
Labels: PhpUnitBridge

**Comment by stof** [comment] 2016-01-06 10:48
> This ensures that the connection is always closed, which lowers the number of concurrent database connections to exactly 1.

Note that DoctrineBundle already does this now

**Comment by craue** [comment] 2016-02-17 19:43
@nicolas-grekas, a bit late, but now I can confirm that the issue is actually solved by your PR. Thanks for that.
