### ISSUE TITLE
[Intl] Update ICU version recommendation

### ISSUE THREAD

**Issue by marcusesa** [symfony/symfony#22711] opened 2017-05-14 05:17 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

Hello guys, I would like to know how the Update ICU version recommendation process works.
I installed the actual version recommended **58.2**, but I saw in the [ICU site](http://site.icu-project.org/download/59) that it was released the version **59**.

- How the process it works?
- Should we update the UCI version recommended?

**Comment by javiereguiluz** [comment] 2017-05-15 06:43
There's a pending pull request for this: #22627. The problem is that updating ICU version is a painful process that creates lots of issues and changes that we must deal with.

@jakzal is the one making these updates, and he needs as much help as possible testing the changes of his PR. Maybe you can take a look? Anyway, let's close this issue as we're already working on this. Thanks!

**Closed by javiereguiluz** 2017-05-15 06:43 UTC
Labels: Feature, Intl
