### ISSUE TITLE
"Unknown " asset" function. Did you mean "asset"?"

### ISSUE THREAD

**Issue by HeathSilcox** [symfony/symfony#32272] opened 2019-06-28 22:33 UTC
**Symfony version(s) affected**: 4.3.2

**Description**  
I get the error shown in the title for no apparent reason. I merely use the function `asset('')` in my twig template.

**How to reproduce**  
I have no idea how to reproduce this bug because I have used this function over 10 computers and it all worked well. Basically I believe the only change was that I'm running Ubuntu 19 LTS whereas on the other computers it was Ubuntu 18 LTS. Symfony's version was the same, the recipes were the same so on and so forth..
Here's the code that led to this problem : 
`<img alt="bla bla" src="{{ asset('assets/images/11.jpg') }}">`

**Possible Solution**  
The first time I got this error I restarted my devilbox, it appeared to work. Then I got it back again and I tried to remove the trailing spaces before and after the `asset` function. It worked once again.. But I don't want to get this again and again each time I create a new view.. :/

**Additional context**  
Here's my composer.json file : 

```JSON
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "4.3.*",
        "symfony/console": "4.3.*",
        "symfony/dotenv": "4.3.*",
        "symfony/expression-language": "4.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "4.3.*",
        "symfony/framework-bundle": "4.3.*",
        "symfony/http-client": "4.3.*",
        "symfony/http-foundation": "4.3.*",
        "symfony/http-kernel": "4.3.*",
        "symfony/intl": "4.3.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.3.*",
        "symfony/security-bundle": "4.3.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.3.*",
        "symfony/twig-bridge": "4.3.*",
        "symfony/twig-bundle": "4.3.*",
        "symfony/validator": "4.3.*",
        "symfony/web-link": "4.3.*",
        "symfony/yaml": "4.3.*"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.3.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.3.*"
        }
    }
}
```

Tell me what I can give you and I'll give it to you if I can !

Good luck, that sounds tricky.

**Comment by HeathSilcox** [comment] 2019-06-29 00:22
It actually does this with everything, like when I do : 
`{{ campaign.content }}`
It says `Unknown " campaign" blabla`
Note the space before the word campaign.

And as soon as I remove this space, I reload my page and it works. And even weirder I can put the space back and it still continues to work...

Sorry if this isn't a good issue report. Good luck.

**Comment by javiereguiluz** [comment] 2019-06-29 17:27
Yes, the leading white space looks like the problem here. Do you use some extension in your editor that does weird things with the spaces? (for example to do things like https://mnapoli.fr/using-non-breakable-spaces-in-test-method-names/). If you open your files with an hexadecimal editor ... do you see a normal white space character here before the `campaign` name? -> `{{ campaign.content }}`

**Comment by HeathSilcox** [comment] 2019-06-30 04:07
Wow, you were right, I don't get normal space in the hexadecimal editor. Normal space is `20` and before `{{ form_end(form) }}` for instance, I get two characters one `c2` and one `a0`.
I have no idea what does that. I use Visual Studio Code (latest).

Strange, I'll investigate that. Thank you :)

**Comment by fabpot** [comment] 2019-06-30 05:09
Closing as this is not a bug in Symfony.

**Closed by fabpot** 2019-06-30 05:09 UTC
Labels: Status: Waiting feedback

**Comment by jvasseur** [comment] 2019-06-30 10:08
This has nothing to do with editors, but instead with OSs and Keyboard configurations : on some OSs AltGR + Space insert a non-breaking space instead of a normal space and on some keyboard configurations you need to use AltGr to insert braces meaning if you don't release the AltGr key soon enough you can insert a non-break space without knowing it.
