### ISSUE TITLE
[Twig][Exception] Unknown filter instead of real exception message

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#25610] opened 2017-12-27 15:53 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Since 3.4 (bug is not there in 3.3), if one of my app Twig extensions throws an exception, I end up with the following message instead of the real exception message : 
``` 
 (2/2) Twig_Error_Syntax

Unknown "abbr_class" filter.
```

From what I've found, this is because my app Twig extension is added before the Symfony Twig Bridge `CodeExtension` which is the one that adds the `abbr_class` Twig filter. This filter is used in the default `exception.html.twig` template and ends up being never registered. However, it seems it is also the case in previous Symfony version so I don't get why it only bugs in 3.4...

Reproducer incoming

**Comment by fancyweb** [comment] 2017-12-27 16:04
You can see the bug if you use this project : https://github.com/fancyweb/symfony-standard/tree/issue-25610.

Start the server and go on the default page.

**Comment by avo7** [comment] 2017-12-28 14:11
Happened to me as well, in Symfony 4.0, right after running Ubuntu update. PHP was not updated (7.1.7), so I'm not sure what's the reason.

**Comment by xabbuh** [comment] 2017-12-28 15:16
You are right. This will be fixed by #25601. However, I am closing here anyway as we already have #25256 to keep track of it.

**Comment by fancyweb** [comment] 2018-01-08 13:33
@xabbuh #25601 was merged and released in 3.4.3 but the problem I described is still the same. Could you reopen please ?

**Comment by xabbuh** [comment] 2018-01-08 13:56
Do you mean you don't get the more helpful error message?

**Comment by fancyweb** [comment] 2018-01-08 14:05
I get this 
![1](https://user-images.githubusercontent.com/3658119/34674085-db645454-f484-11e7-8e91-9f71f9a3a77f.png)

instead of my exception.

**Comment by xabbuh** [comment] 2018-01-08 14:13
Can you create a small example project that allows to reproduce the issue?

**Comment by fancyweb** [comment] 2018-01-08 14:14
The link is in the second message of this issue.

**Comment by stof** [comment] 2018-01-08 14:20
hmm, if the instantiation of Twig extensions is triggering exceptions, this would indeed leave Twig in an unusable state (and so create issues when trying to use it to render the custom exception page)

**Closed** 2018-02-07 05:34 UTC
Labels: Bug, DebugBundle, Status: Needs Review, TwigBundle
