### ISSUE TITLE
[Finder] SortableIteratorTest::testAccept fails if /tmp is mounted with noatime

### ISSUE THREAD

**Issue by ymc-dabe** [symfony/symfony#17489] opened 2016-01-22 09:20 UTC
> This is a forwarded from a [bug report src:symfony got in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812263#29).

If /tmp is on a filesystem mounted with option `noatime`, a test in the Finder component fails with the following error:

```
PHPUnit 5.1.4 by Sebastian Bergmann and contributors.

...............................................................  63 / 157 ( 40%)
............................................................... 126 / 157 ( 80%)
...........................F...                                 157 / 157 (100%)

Time: 4.51 seconds, Memory: 14.25Mb

There was 1 failure:

1) Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #2 (3, array(array('/tmp/symfony_finder/foo/bar.tmp', '/tmp/symfony_finder/test.php'), array('/tmp/symfony_finder/.git', '/tmp/symfony_finder/.foo', '/tmp/symfony_finder/.foo/.bar', '/tmp/symfony_finder/.foo/bar', '/tmp/symfony_finder/test.py', '/tmp/symfony_finder/foo', '/tmp/symfony_finder/toto', '/tmp/symfony_finder/toto/.git', '/tmp/symfony_finder/foo bar'), array('/tmp/symfony_finder/.bar')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => '/tmp/symfony_finder/.foo'
-    1 => '/tmp/symfony_finder/.foo/.bar'
-    2 => '/tmp/symfony_finder/.foo/bar'
-    3 => '/tmp/symfony_finder/.git'
+    0 => '/tmp/symfony_finder/.bar'
+    1 => '/tmp/symfony_finder/.foo'
+    2 => '/tmp/symfony_finder/.foo/.bar'
+    3 => '/tmp/symfony_finder/.foo/bar'
     4 => '/tmp/symfony_finder/foo'
     5 => '/tmp/symfony_finder/foo bar'
     6 => '/tmp/symfony_finder/test.py'
     7 => '/tmp/symfony_finder/toto'
     8 => '/tmp/symfony_finder/toto/.git'
 )

/tmp/symfony/finder/Tests/Iterator/IteratorTestCase.php:58
/tmp/symfony/finder/Tests/Iterator/SortableIteratorTest.php:68

FAILURES!
Tests: 157, Assertions: 272, Failures: 1.
```

If /tmp is mounted with either `atime` or `relatime` the tests run just fine.
### How to reproduce
1. Remount with `noatime`:
   `sudo mount -o remount,noatime $(df /tmp | tail -1 | cut -d ' ' -f 1)`
2. Run tests shipped with the finder component:
   `phpunit src/Symfony/Component/Finder/`
   
   > Tests fails with above error.
### My environment

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie
PHP:            5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10) 
PHPUnit:        5.1.4 by Sebastian Bergmann and contributors.
Symfony:        3.0.1
```

> Note: In nowadays there should be no need to use noatime:
> - Modern SSDs can sustain a lot of writes
> - Linux Kernel 4.0 brought lazytime, which is a much better choice than noatime.
> 
> -> Thus feel free to close this bug as won't fix.

**Comment by nacc** [comment] 2016-02-19 18:11
Note I think I'm seeing this as well in the Ubuntu sbuild environments (used by the package builders). There, the schroots are mounted relatime.

**Comment by orlitzky** [comment] 2017-05-04 12:21
I also hit this problem on Gentoo. It's common to have even your root/home filesystems mounted with `noatime`. That's the case for my workstation and I'm seeing this same test failure, so I presume that the cause is `noatime`.

I'll have to disable that one test for now, since a lot of our users will have a similar setup. An ideal solution would be to check that atime fiddling works first before trying to sort based on it.

**Comment by fabpot** [comment] 2018-02-22 06:50
Closing as I don't see what we can do here. Errors are expected if noatime is set.

**Closed by fabpot** 2018-02-22 06:50 UTC
Labels: Bug, Finder, Status: Needs Review

**Comment by orlitzky** [comment] 2018-02-22 13:18
Mounting`noatime` only prevents _updates_ to a file's access time, so the atime is still there and you can sort by it -- the expected results are just different. You could read a file and see if its atime changes; then if not, fall back whatever order they were created/modified in rather than the current expected order.

Another thing I noticed: using fixed paths under `/tmp` isn't safe, because another user can replace e.g. `/tmp/symfony_finder` with a symlink, causing you to read/write a location of his choosing. The somewhat-silly way we've settled on to avoid that risk is to always use "random" file/directory names under `/tmp`. The PHP `tmpnam()` function should get you one of those.
