### ISSUE TITLE
[Form] Sometimes checking for `form.parent` view in Twig is wrong

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#24892] opened 2017-11-10 01:04 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Hi there!

This morning I faced [an issue](https://github.com/javiereguiluz/EasyAdminBundle/issues/1913) in EasyAdminBundle related to form themes and `form.parent` check in Twig.

Briefly, the problem happen if we have a simple form with a field named `parent`. The situation gets worse depending on whether the `parent` field has children or not.

First, let's see the `FormView` class, especially the `parent` property and `\ArrayAccess` methods:
https://github.com/symfony/symfony/blob/61b753443d6903d8a9644f62caf020fdfca3ef6f/src/Symfony/Component/Form/FormView.php#L19-L126

In PHP context there's no problem, the main form view has the `$form->parent` property and its children's fields (`$form['parent']`), each one accessible unmistakably by syntax. **But**, in Twig context, this access/check `{% if form.parent is null/empty %}` causes a naming collision. The `parent` attribute is resolved by Twig following the steps below:
>https://twig.symfony.com/doc/2.x/templates.html#variables
For convenience's sake `form.parent` does the following things on the PHP layer:
>* [check if `form` is an array and `parent` a valid element;](https://github.com/twigphp/Twig/blob/31b577863b5ae8d19e2cefd174e95a433f16491f/lib/Twig/Extension/Core.php#L1437-L1445) <-- always wins in this particular case
>* if not, and if `form` is an object, check that `parent` is a valid property; <-- never reached
>* ...
>* if not, and if `form` is an object, check that `getParent` is a valid method;

Therefore, the `parent` child field view is returned instead of the real `parent` view (which is null in this case)!

There's some place in the source where this kind of check is done and surely in many bundles and apps:
![form_parent](https://user-images.githubusercontent.com/2028198/32636294-245a0ef6-c582-11e7-9ed7-0995f191c61d.png)

I'm not sure if there's a workaround for current projects/bundles rely on the Symfony form themes templates. I don't think it is a bug of Twig either, but a design error of the `FormView` class, which is specially designed to work in Twig context.

We may need a getter method for this `parent` property by now and check `{% if form.getParent %}` everywhere avoiding the first rule. Wdyt? thoughts?

**Comment by xabbuh** [comment] 2017-11-10 07:06
You are right. But this looks like a duplicate of #18882 to me. Thus I am closing here in favour of the existing issue.

**Closed by xabbuh** 2017-11-10 07:06 UTC

**Comment by yceruto** [comment] 2017-11-10 11:20
Wow! very old issue, sorry I didn't check, thanks!
