### ISSUE TITLE
Update PHP to 7.4.12 - get many error in Cache.

### ISSUE THREAD

**Issue by Yozhef** [symfony/symfony#38976] opened 2020-11-03 15:54 UTC
**Symfony version(s) affected**: 5.1.7

**How to reproduce**  
Sorry but locally I still couldn't reproduce this = (

**Additional context**  
opcache config
```
custom.ini: |
    [opcache]
    opcache.enable = 1
    opcache.enable_cli = 0
    opcache.memory_consumption = 128
    opcache.interned_strings_buffer = 8
    opcache.max_accelerated_files = 10000
    opcache.max_wasted_percentage = 5
    opcache.use_cwd = 1
    ; controlled by the directive "opcache.revalidate_freq".
    opcache.validate_timestamps = 0
    opcache.revalidate_freq = 2
    opcache.file_update_protection = 2
    opcache.revalidate_path = 0
    opcache.save_comments = 1
    opcache.load_comments = 1
    opcache.fast_shutdown = 0
    opcache.enable_file_override = 0
    opcache.optimization_level = 0xffffffff
    opcache.inherited_hack = 1
    opcache.blacklist_filename = ""
    opcache.max_file_size = 0
    opcache.consistency_checks = 0
    opcache.force_restart_timeout = 180
    opcache.error_log = ""
    opcache.log_verbosity_level = 2
    opcache.preferred_memory_model = ""
    opcache.protect_memory = 0
  preload.ini: |
    opcache.preload=/app/var/cache/prod/App_KernelProdContainer.preload.php
    opcache.preload_user=www-data
```

![image](https://user-images.githubusercontent.com/8971757/98007123-aeb49880-1dfb-11eb-9658-3644db4c4851.png)
![image](https://user-images.githubusercontent.com/8971757/98007171-baa05a80-1dfb-11eb-825f-9f09b4e7dcad.png)
![image](https://user-images.githubusercontent.com/8971757/98007207-c855e000-1dfb-11eb-8267-99a1f25a19dd.png)
![image](https://user-images.githubusercontent.com/8971757/98008496-3ea71200-1dfd-11eb-835c-f63d218f6c47.png)

**Comment by nicolas-grekas** [comment] 2020-11-04 22:27
Can you open the source code from the stack trace and see if the message makes any sense at all?
To me we never call doGet() with 1 argument. Can you spot where we do, if we trust the message?

This might be a PHP bug.

**Comment by PhilETaylor** [comment] 2020-11-04 23:48
I was unable to reproduce this (in my project) on PHP 7.4.12 in dev or production sorry.

**Comment by PhilETaylor** [comment] 2020-11-05 13:13
Im pleased to report, after compiling PHP from git sources, in Alpine Docker containers, and running PHP 8.1.0-dev with my Symfony 4.4.16 application, with PHP Preloading enabled, and JIT Enabled, this bug seems resolved and PHP doesn't segfault.

It seems this has been fixed since PHP8.0RC3 :-) in PHP bug 80307.

Thanks.

**Comment by derrabus** [comment] 2020-11-05 13:23
Link for the lazy folks: https://bugs.php.net/80307 😎 

Thanks for getting back to us, @PhilETaylor. I think we can close this issue then.

**Comment by PhilETaylor** [comment] 2020-11-05 13:26
@derrabus Sorry my bad. Please reopen this one. My comment should have been on #38997 regarding Segmentation Faults. (loss of sleep all night makes for bad fingers)

**Comment by jderusse** [comment] 2020-11-05 19:43
Please try disabling opcache preload, and tell us if it worked. Similar cases have been reported and it solved the issue.

**Comment by Yozhef** [comment] 2020-11-05 19:49
@jderusse Tomorrow I will try to play further to disable the preloader and let you know the results.

**Comment by nicolas-grekas** [comment] 2020-11-06 15:12
Likely not a Symfony issue, check https://github.com/symfony/symfony/issues/39010#issuecomment-723004585

**Closed as completed by nicolas-grekas** 2020-11-06 15:12 UTC
Labels: Bug, Status: Needs Review, Cache

**Comment by PhilETaylor** [comment] 2020-11-06 16:05
Ive just rebuilt from PHP8 source this afternoon and now preloading is completely broken, worse, php-fpm cannot even start :(
