### ISSUE TITLE
[Cache] "Redis connection "redis://redis" failed: Redis server went away" after upgrading to 6.2.3

### ISSUE THREAD

**Issue by gam6itko** [symfony/symfony#48817] opened 2022-12-29 13:45 UTC
### Symfony version(s) affected

6.2.3

### Description

After I upgrading to 6.2.3 there is error occurs with follow message "Redis connection "redis://redis" failed: Redis server went away".

I'm using docker-compose with redis:6.2 docker image. The error occurs on 5.0 and 7.0 too

After downgrade to 6.2.2 it's works well.

I think that something broken here: https://github.com/symfony/symfony/pull/48711

### How to reproduce

Not a big deal
```php
RedisAdapter::createConnection('redis://redis/2');
```

**Comment by chalasr** [comment] 2022-12-29 13:47
Duplicate of #48813

**Closed as completed** 2022-12-29 13:48 UTC
Labels: Bug, Status: Needs Review, Cache
