### ISSUE TITLE
Service YML : Cannot use enum array or object as service parameter

### ISSUE THREAD

**Issue by nbrignol** [symfony/symfony#50346] opened 2023-05-16 14:23 UTC
### Symfony version(s) affected

6.2

### Description

I can pass one enum as argument to a service, but not an array or an object.

If I call the parameter directly from the container (getParameter("app.myParam")) I get the array or the object. The issue is only when I use it argument for my service.

### How to reproduce

I have a service defined like this : 
```
services: 
    My\Service:
        arguments:
            $myArg: '%app.myParam%'
```    
✅ I can pass *one* enum like this, it is working fine. 
```
parameters:
    app.myParam: !php/enum MyEnum::Test
```

🚫 but when I try to pass enums as array or as object I have an `Warning: Undefined array key "app.myParam"` error

```
parameters:
    app.myParam: [!php/enum MyEnum::Test]
```

```
parameters:
    app.myParam: 
        test: !php/enum MyEnum::Test
```

**Comment by MatTheCat** [comment] 2023-05-16 15:33
When you write

```yml
parameters:
    app.myParam: 
        test: !php/enum MyEnum::Test
```

`app.myParam` is the parameter name, and its value is an array with a `test` key. Your service will be injected the parameter’s **value** so its name has no importance.

**Comment by nbrignol** [comment] 2023-05-16 15:40
> When you write
> 
> ```yaml
> parameters:
>     app.myParam: 
>         test: !php/enum MyEnum::Test
> ```
> 
> `app.myParam` is the parameter name, and its value is an array with a `test` key. Your service will be injected the parameter’s **value** so its name has no importance.

Yes I know that. Here I expect to have `[test=>MyEnum::Test]`.
But I have the warning

**Comment by MatTheCat** [comment] 2023-05-16 15:43
The warning probably comes from your own code. Could you provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) if it is not the case?

**Comment by nbrignol** [comment] 2023-05-16 15:51
> The warning probably comes from your own code. Could you provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) if it is not the case?

I'll try to make a reproducer when I have some time.

What is surprising is that the single `!php/enum MyEnum::Test` works, but not the array version or the object version.

**Comment by stof** [comment] 2023-05-16 15:54
I was quite sure that enums were unsupported in parameters (they are supported in service arguments). So I'm also surprised by the working case more than by the non-working one.

**Comment by xabbuh** [comment] 2023-06-05 07:21
@nbrignol Do you have a reproducer for us?

**Comment by xabbuh** [comment] 2023-06-24 11:45
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed as not planned by xabbuh** 2023-06-24 11:45 UTC
Labels: DependencyInjection, Bug, Status: Waiting feedback
