### ISSUE TITLE
[Form] Feeding float values to a choice form type

### ISSUE THREAD

**Issue by kminh** [symfony/symfony#13817] opened 2015-03-01 09:40 UTC
I'm trying to setup something like this with Symfony 2.6.1:

```php
$builder
    ->add('field', 'choice', [
        'choices' => array_combine(range(0.1, 1.0, 0.1), range(0.1, 1.0, 0.1))
    ]);
```

and this is the mapping for Doctrine:
```yaml
    field:
        type: decimal
        precision: 2
        scale: 1
        options:
            default: 1.0
```

The field never shows the value 1.0 as selected when it is (works fine for 0.1 => 0.9). I have tried converting all float values to string using `number_format` but doesn't work either.

I have also tried using `http://symfony.com/doc/current/reference/forms/types/choice.html#choice-list`, but taking the example on that page I get this:

```html
<select>
   <option value="0">Full</option>
   <option value="1">Half</option>
</select>
```

as you can see, there's no float values here (shouldn't it be 1 => Full, 0.5 => Half?) Is this a bug with `ChoiceList` or the example is incorrect?

Thanks in advanced for any insight.

**Comment by AZielinski** [comment] 2015-03-01 12:44
I didn't really test it, but looking at your `choices`, it returns:
```
array(10) {
  '0.1' => double(0.1)
  '0.2' => double(0.2)
  '0.3' => double(0.3)
  '0.4' => double(0.4)
  '0.5' => double(0.5)
  '0.6' => double(0.6)
  '0.7' => double(0.7)
  '0.8' => double(0.8)
  '0.9' => double(0.9)
  [1] => double(1)
}
```

so since `[1]` key behaves differently than the rest, a quick fix **could be** to make `[1]` key a string like the rest. If you wonder why are you getting strings instead of floats, the answer is in here:

http://php.net/manual/en/language.types.array.php
> The key can either be an integer or a string. The value can be of any type.

**Comment by kminh** [comment] 2015-03-01 13:36
Actually I have already done this:

```php
        $volumes = range(0.1, 1.0, 0.1);
        $volumes = array_map(function($v) {
            return number_format($v, 1);
        }, $volumes);

        $choices = array_combine($volumes, $volumes);
```

so all keys should be string now, but still `1.0` is never selected.

**Comment by AZielinski** [comment] 2015-03-01 20:19
I am unable to reproduce this problem. It works as expected in symfony 2.6.1 when I use the following form:
```php
$form = $this
    ->createFormBuilder(['field'=>1.0])
    ->add('float', 'choice', [
        'choices' => array_combine(range(0.1, 1.0, 0.1), range(0.1, 1.0, 0.1))
    ])
    ->getForm()
```

The following is unlikely since you stated that it works for 0.1-0.9, but let's try it anyway:
Could it be caused by the way you feed the data to your form? Let's take a look at the mapping you provided:
```yml
   field:
        type: decimal
        precision: 2
        scale: 1
        options:
            default: 1.0
```
the following mapping affects DEFAULT clause in your column definition in SQL. When you create a new entity, it's `$entity->field` property is null. If you want your entities to have default value, you must provide it like this:

```php
class MyEntity {
    $field = 0.5;
}
```

**Comment by AZielinski** [comment] 2015-03-01 20:36
I am unable to reproduce this problem. It works as expected in symfony 2.6.1 when I use the following form:
```php
$form = $this
    ->createFormBuilder(['field'=>1.0])
    ->add('field', 'choice', [
        'choices' => array_combine(range(0.1, 1.0, 0.1), range(0.1, 1.0, 0.1))
    ])
    ->getForm()
```

The following is unlikely since you stated that it works for 0.1-0.9, but let's try it anyway:

Could it be caused by the way you feed the data to your form? Maybe you forgot about providing 'data_class'?
> When you create a form, each field initially displays the value
> of the corresponding property of the form's domain object (if an
> object is bound to the form)

Let's take a look at the mapping you provided:
```yml
   field:
        type: decimal
        precision: 2
        scale: 1
        options:
            default: 1.0
```
the following mapping affects DEFAULT clause in your column definition in SQL, not the value of `field` property of your entity instance. When you create a new entity, it's `$entity->field`
property is null. If you want your entities to have default value, you must provide it like this:

```php
class MyEntity {
    $field = 0.5;
}
```

**Comment by AZielinski** [comment] 2015-03-01 20:46
Regarding your confusion about ChoiceList:
> I have also tried using http://symfony.com/doc/current/reference/forms/types/choice.html#choice-list,
> but taking the example on that page I get this:
```html
<select>
   <option value="0">Full</option>
   <option value="1">Half</option>
</select>
```
> as you can see, there's no float values here (shouldn't it be
> 1 => Full, 0.5 => Half?) Is this a bug with ChoiceList or the
> example is incorrect?

Not a bug at all, with ChoiceList each `<option value="">` contains a numeric index of the value from `ChoiceList` instead of a representation of the actual value. For example if you modified that example just a little:
```php
$builder->add('status', 'choice', array(
  'choice_list' => new ChoiceList(array(1, 0.5, 7), array('Full', 'Half', 'Seven'))
));
```
the output would be:
```html
<select id="form_status" name="form[status]">
        <option value="0">Full</option>
        <option value="1">Half</option>
        <option value="2">Seven</option>
</select>
```

**Comment by stof** [comment] 2015-08-01 21:03
the initial issue was that your choice is the ``1.0`` string (because array keys cannot be float in PHP), which is not the value in your model and so no value is initially selected.

Closing this as the new way to define choices in Symfony 2.7+ supports using any type of values.

**Closed by stof** 2015-08-01 21:03 UTC
Labels: Form

**Comment by yceruto** [comment] 2016-10-31 13:45
This bug already exists in 2.7+ [here][2]. Let's look at an example:

    $cache[$choice] = true;

    // when $choice = 0.5: $cache = [0 => true]
    // when $choice = 1.0: $cache = [0 => true, 1 => true]

and when `$choice = 1.5` [this line][3] (`isset($cache[1.5])`) returns `true` because really checks `isset($cache[1])` and this key already exists, so [`castableToString()`][4] returns `false` (detected as duplicate) and the choices values are generated incrementing integers as values.

  [2]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L237
  [3]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L233
  [4]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L222
