### ISSUE TITLE
Feature Request: Get bundle version from controller

### ISSUE THREAD

**Issue by MicWit** [symfony/symfony#22713] opened 2017-05-15 01:55 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | N/A

I was creating a bundle, and had a need to show the version of the bundle for one of our apps. As I looked into this, I came to see that there is no way to get access to what version of a bundle is installed in the controller, you can only get a list of bundles installed.

I'm not sure how much work it would take, but is it possible to extend the array returned from `$this->container->getParameter('kernel.bundles')` to include the version of each bundle?

**Comment by javiereguiluz** [comment] 2017-05-15 06:39
@MicWit the problem is that Symfony bundles don't have a version. They can define one if they want ([for example like this](https://github.com/javiereguiluz/EasyAdminBundle/blob/master/EasyAdminBundle.php#L24)) but there's no concept of "bundle version".

The solution is to look for the version of the associated Composer packages. You need to [get packages from composer.lock](https://github.com/EasyCorp/easy-doc-bundle/blob/master/src/Command/DocCommand.php#L120) and then [process that information](https://github.com/EasyCorp/easy-doc-bundle/blob/master/src/Command/DocCommand.php#L163).

So, I must close this as "won't fix" because we can't fix it from Symfony (it's a Composer thing). Thanks!

**Closed by javiereguiluz** 2017-05-15 06:39 UTC

**Comment by fabpot** [comment] 2017-05-15 13:56
For private bundles, it's even simpler than that, just create a constant with your version.
