### ISSUE TITLE
Don't reserve space for label when there is no label

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18850] opened 2016-05-23 16:35 UTC
In [this code](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_horizontal_layout.html.twig#L12-L14) a div is taking up space with no contents. I understand that if there are siblings with a label you want to align them. But often you have either no labels at all or everything has a label. Some logic could be introduced here to look at siblings.

**Comment by Soullivaneuh** [comment] 2016-06-29 15:59
I think both case should be handled.

For me, with the following collection type:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('domain', null, [
            'label' => 'ssl_certificate.form.domain',
            'translation_domain' => 'front',
        ])
        ->add('subdomains', CollectionType::class, [
            'label' => 'ssl_certificate.form.subdomains',
            'translation_domain' => 'front',
            'type' => TextType::class,
            'allow_add' => true,
            'allow_delete' => true,
            'prototype' => true,
            'options' => [
                'label' => false,
                'text_suffix' => '',
                'attr' => [
                    'class' => 'subdomain-domain',
                ],
            ],
        ])
    ;
}
```

I get this:

![image](https://cloud.githubusercontent.com/assets/1698357/16459351/cc39c78a-3e22-11e6-9a1e-8043f4fb3b3c.png)

This is useless and related to @flip111 link.

But I also agree that in some case this "no content" space can be useful to keep form alignement.

Example:

```php
->add('test', TextType::class, [
    'mapped' => false,
    'label' => false,
    'attr' => [
        'placeholder' => 'My label goes here',
    ]
])
```

![image](https://cloud.githubusercontent.com/assets/1698357/16459462/2258fe92-3e23-11e6-84c4-f46087a272c9.png)

But in any case, this should not be handled like this IMHO but with a `col-*-offset`.

**Comment by HeahDude** [comment] 2016-06-29 16:20
Duplicate of https://github.com/symfony/symfony/issues/18474, see https://github.com/symfony/symfony/pull/18504.

This should be handled globally not only for bootstrap horizontal.

**Closed** 2016-06-29 20:43 UTC
Labels: Form
