### ISSUE TITLE
Choice type expanded with boolean choices with choices_as_values always preselects `false` value

### ISSUE THREAD

**Issue by webdevilopers** [symfony/symfony#17718] opened 2016-02-07 14:43 UTC
I've updated to **2.7** and changed my choice types to use `choices_as_values`.
Most of my choices are simple "No" or "Yes". But they must not be preselected - the user is forced to choose. That is why none of my radio buttons is initially checked.

I tried this with **2.7**:
```php
$builder->add('aberdeenBlind', 'choice', array(
                'choices' => array(
                    'Ja' => true,
                    'Nein' => false
                ),
                'choices_as_values' => true,
                'expanded' => true,
                'required' => true
            ))
```

Unfortunately the second radio button (false => 'Nein') is preselected. This also happens when flipping the order of the `choices`. The `false` choice is always preselected.

I played around with other options e.g. `placeholder`, `empty_*` etc. but then I recognized:
**This only seems to happen when using `boolean` values. The following example would not preselect any value**:

```php
$builder->add('aberdeenBlind', 'choice', array(
                'choices' => array(
                    'Ja' => 'Y', // or '1'
                    'Nein' => 'N' // or '0'
                ),
                'choices_as_values' => true,
                'expanded' => true,
                'required' => true
            ))
```

Possibly related:
- https://github.com/symfony/symfony/issues/14712 by @maxailloud 
- https://github.com/symfony/symfony/issues/15573 by @imphil

**Comment by raziel057** [comment] 2016-02-08 07:48
This is the same problem as #17677

**Comment by webdevilopers** [comment] 2016-02-08 11:58
You are right @raziel057 . I browsed the issues before posting but didn't look for e.g. `placeholder`.
Should we keep both issues open @javiereguiluz ?

**Comment by javiereguiluz** [comment] 2016-02-08 12:01
If it's the same bug, we usually close the new one in favor of the old one (unless the new one provides more info or engages a better discussion).

**Comment by webdevilopers** [comment] 2016-02-08 12:14
I think it is important to note that the issue is not linked to the `placeholder` option.
It looks like it is caused by a boolean choice itself.

I will add a dump too:
![boolean_issue_choicetype](https://cloud.githubusercontent.com/assets/3479626/12885389/d9e345a0-ce65-11e5-8215-7e641e24878b.png)

**Comment by raziel057** [comment] 2016-02-08 16:39
In fact the string cast for false is the empty value which conflicts with the empty value of the placeholder.

To avoid this issue, I made a custom BooleanType:
```php
namespace PTC\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use PTC\CoreBundle\Form\DataTransformer\StringToBooleanTransformer;

class PtcBooleanType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new StringToBooleanTransformer('1', '0'));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => array(
                'yes' => '1',
                'no' => '0',
            ),
        ));

        $resolver->addAllowedValues('multiple', false);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return ChoiceType::class;
    }
}
```
With a String to Boolean Transformer:

```php
<?php
namespace PTC\CoreBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class StringToBooleanTransformer implements DataTransformerInterface
{
    /**
     * @var string
     */
    private $trueValue;

    /**
     * @var string
     */
    private $falseValue;

    /**
     * @param string $trueValue
     * @param string $falseValue
     */
    public function __construct($trueValue, $falseValue)
    {
        $this->trueValue = $trueValue;
        $this->falseValue = $falseValue;
    }

    /**
     * {@inheritDoc}
     */
    public function transform($value)
    {
        if (null === $value) {
             return null;
        }

        if (!is_bool($value)) {
            throw new TransformationFailedException('Expected a Boolean.');
        }

        return true === $value ? $this->trueValue : $this->falseValue;
    }

    /**
     * {@inheritDoc}
     */
    public function reverseTransform($value)
    {
        if (null === $value) {
            return null;
        }

        if (!is_string($value)) {
            throw new TransformationFailedException('Expected a string.');
        }

        return $this->trueValue === $value;
    }
}
```

**Comment by xabbuh** [comment] 2016-02-09 11:56
closing as a duplicate of #17677

**Closed by xabbuh** 2016-02-09 11:56 UTC
Labels: Bug, Form, Status: Needs Review
