### ISSUE TITLE
dump() doesnt work in console (JetBrains-JediTerm + docker)

### ISSUE THREAD

**Issue by henry2778** [symfony/symfony#31853] opened 2019-06-04 14:02 UTC
**Symfony version(s) affected**: 4.3.0

**Description**  
If we try to call `dump($someObject)` function in the console script from the docker container in the PhpStorm IDE (or similar) - it will stuck on the FQCN. I believe this is related to the link feature in var dumper. But for the CLI we have that restriction
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L438
And it works fine except if we use docker container shell in PhpStorm. The `TERMINAL_EMULATOR` env var is not passed from the terminal to the container shell. It fails when trying to print the link for the class name. Not sure if that is a bug or code issue after all, but still I spent couple of hours on that :) Hope that helps somebody

Exact places where problem happens: 

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L488

and

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L494

**How to reproduce**  
Run `dump($object)` on any object in the console script from the docker container shell under PhpStorm terminal. 

**Possible Solution**  
The easiest way is to pass `TERMINAL_EMULATOR=JetBrains-JediTerm` to the docker container. In my case its via docker-compose:

```
php:
    environment:
      TERMINAL_EMULATOR: 'JetBrains-JediTerm'
    build:
      context: ./docker/php-fpm
 ...
```

Also consider defining the value of `CliDumper::$handlesHrefGracefully`

**Additional context**  
This is the result of `dump($this)` in dummy console command

![image](https://user-images.githubusercontent.com/13105599/58884773-b5604d00-86e9-11e9-9a3f-e8f0f0674368.png)

**Comment by nicolas-grekas** [comment] 2019-06-04 14:06
Duplicate of https://github.com/symfony/symfony/issues/31809, right?
Why doesn't phpstorm set TERMINAL_EMULATOR to JetBrains-JediTerm?
Old version? If yes, please upgrade :) (see discussion in linked issue)

**Comment by nicolas-grekas** [comment] 2019-06-04 14:07
> The TERMINAL_EMULATOR env var is not passed from the terminal to the container shell

Oh sorry I missed that part. There is nothing we can do here: fix your setup and set the var.

**Comment by belinde** [comment] 2019-06-05 12:59
Just a quick&dirty hack: the terminal in PhpStorm is loaded by the file `$PHPSTORM_INSTALL_DIR/plugins/terminal/jediterm-bash.in`. If you're stuck (as me) with an old version and cannot upgrade, you can edit that file and add a `export TERMINAL_EMULATOR=JetBrains-JediTerm` just after the other `export`. PhpStorm terminal will now act as it was a brand new version.

I described a way, but I **never** told it was a *good* way :-)

**Comment by nicolas-grekas** [comment] 2019-06-05 13:01
Thanks for the details, closing now :)

**Closed by nicolas-grekas** 2019-06-05 13:01 UTC
Labels: Bug, Status: Needs Review, VarDumper
