### ISSUE TITLE
[Mailer][Translation]: Class not found from v5.3.8

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#43227] opened 2021-09-28 10:08 UTC
**Symfony version(s) affected**: 5.3.8

**Description**
Possibly related to https://github.com/symfony/symfony/issues/43212 and https://github.com/symfony/symfony/issues/43226

**How to reproduce**
Clear cache with 5.3.8 of either bundle installed results in:
```
 Class "Symfony\Component\Translation\Command\TranslationPullCommand" used for service "console.command.translation_pull" cannot be found. 
```
or 
```
Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.  
```

The classes to exist

**Possible Solution**
Not sure what would have caused this, a composer namespace config update?

**Additional context**
n/a

**Comment by derrabus** [comment] 2021-09-28 10:09
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 10:09 UTC
Labels: Bug, Translation, Status: Needs Review, Mailer

**Comment by silverbackdan** [comment] 2021-09-28 10:10
I saw the comments were added as I was writing up, thanks @derrabus - sorry for dupe.
