### ISSUE TITLE
[Profiler][Doctrine] Profiler Not Showing Toolbar 4.4.24

### ISSUE THREAD

**Issue by eozgun** [symfony/symfony#41383] opened 2021-05-23 12:31 UTC
**Symfony version(s) affected**: 4.4.24

**Description**
composer create-project symfony/skeleton example 4.*
cd example
composer req orm
composer req profiler --dev

Profiler Not Showing Toolbar!

**Comment by derrabus** [comment] 2021-05-23 12:37
Duplicate of #41305

**Closed as completed by derrabus** 2021-05-23 12:37 UTC
Labels: Bug, Doctrine, WebProfilerBundle, Status: Needs Review

**Comment by chalasr** [comment] 2021-05-23 12:45
@eozgun If you can, please try applying the patch that fixed #41305 and tell us if the issue persists.

**Comment by eozgun** [comment] 2021-05-23 16:11
@chalasr

I have reinstalled many times.
It worked after applying the fixed patch.

However, after installing orm, if the database connection is incorrect or there is no database, neither error nor toolbar appears on the homepage.

**Comment by chalasr** [comment] 2021-05-23 21:30
> However, after installing orm, if the database connection is incorrect or there is no database, neither error nor toolbar appears on the homepage.

Ok thanks for confirming, I can observe the same behavior when launching the project on a platform that doesn't have pgsql. I think it's a bug, but that's not a regression introduced in v4.4.24 (tested on lower 4.4 tags).
