### ISSUE TITLE
Missing: /var/cache/dev/appDevDebugProjectContainer.xml.meta

### ISSUE THREAD

**Issue by zoltanka** [symfony/symfony#23316] opened 2017-06-28 09:18 UTC
I've installed a fresh symfony with composer and after it finishes the download I got an error. 

Output: 
```
zoltan@daemon:/mnt/hgfs/daemon/symfony/site/$ composer create-project "symfony/framework-standard-edition" .
Installing symfony/framework-standard-edition (v3.3.2)
  - Installing symfony/framework-standard-edition (v3.3.2)
    Loading from cache

Created project in .
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.7)
    Loading from cache

  - Installing twig/twig (v1.34.2)
    Loading from cache

  - Installing symfony/polyfill-util (v1.3.0)
    Loading from cache

  - Installing paragonie/random_compat (v2.0.10)
    Loading from cache

  - Installing symfony/polyfill-php70 (v1.3.0)
    Loading from cache

  - Installing symfony/polyfill-php56 (v1.3.0)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.3.0)
    Loading from cache

  - Installing symfony/symfony (v3.3.2)
    Loading from cache

  - Installing symfony/polyfill-intl-icu (v1.3.0)
    Loading from cache

  - Installing psr/simple-cache (1.0.0)
    Loading from cache

  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing psr/link (1.0.0)
    Loading from cache

  - Installing psr/container (1.0.0)
    Loading from cache

  - Installing psr/cache (1.0.1)
    Loading from cache

  - Installing fig/link-util (1.0.0)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.1)
    Loading from cache

  - Installing doctrine/common (v2.6.2)
    Loading from cache

  - Installing jdorn/sql-formatter (v1.2.17)
    Loading from cache

  - Installing doctrine/doctrine-cache-bundle (1.3.0)
    Loading from cache

  - Installing doctrine/dbal (v2.5.12)
    Loading from cache

  - Installing doctrine/doctrine-bundle (1.6.8)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing doctrine/orm (v2.5.6)
    Loading from cache

  - Installing incenteev/composer-parameter-handler (v2.1.2)
    Loading from cache

  - Installing composer/ca-bundle (1.0.7)
    Loading from cache

  - Installing sensiolabs/security-checker (v4.0.4)
    Loading from cache

  - Installing sensio/distribution-bundle (v5.0.20)
    Loading from cache

  - Installing sensio/framework-extra-bundle (v3.0.26)
    Loading from cache

  - Installing monolog/monolog (1.22.1)
    Loading from cache

  - Installing symfony/monolog-bundle (v3.1.0)
    Loading from cache

  - Installing symfony/polyfill-apcu (v1.3.0)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.8)
    Loading from cache

  - Installing symfony/swiftmailer-bundle (v2.6.2)
    Loading from cache

  - Installing sensio/generator-bundle (v3.1.4)
    Loading from cache

  - Installing symfony/phpunit-bridge (v3.3.2)
    Loading from cache

paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
doctrine/doctrine-cache-bundle suggests installing symfony/security-acl (For using this bundle to cache ACLs)
sensio/framework-extra-bundle suggests installing symfony/psr-http-message-bridge (To use the PSR-7 converters)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_host (127.0.0.1):
database_port (null):
database_name (symfony):
database_user (root):
database_password (null):
mailer_transport (smtp):
mailer_host (127.0.0.1):
mailer_user (null):
mailer_password (null):
secret (ThisTokenIsNotSoSecretChangeIt): Token
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug
 // true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: file_get_contents(/mnt/hgfs/daemon/symfony/site/var/cache/dev/appDevDebugProjectContainer.xml.meta): failed to open stream: No such file or directory in /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php:94
Stack trace:
#0 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCache.php(60): Symfony\Component\Config\ResourceCheckerConfigCache->isFresh()
#1 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php(31): Symfony\Component\Config\ConfigCache->isFresh()
#2 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(143): Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 in /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php on line 94
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'assets:install --symlink --relative '\''web'\'''" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: file_get_contents
  (/mnt/hgfs/daemon/symfony/site/var/cache/dev/appDevDebugProjectContainer.xml.meta): failed to open stream: No
  such file or directory in /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/Re
  sourceCheckerConfigCache.php:94
  Stack trace:
  #0 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCache.php(60): Symf
  ony\Component\Config\ResourceCheckerConfigCache->isFresh()
  #1 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection
  /Compiler/ContainerBuilderDebugDumpPass.php(31): Symfony\Component\Config\ConfigCache->isFresh()
  #2 /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Com
  piler.php(143): Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->pro
  cess(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #3 in /mnt/hgfs/daemon/symfony/site/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigC
  ache.php on line 94


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

I tried to install it, with Symfony installer application and it was the same. I have really no idea.
This used to work for me, but now.

Composer version: 
`Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34`

PHP version:
` PHP 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun  9 2017 08:26:34) ( NTS )`
`PHP 5.6.30-12~ubuntu16.04.1+deb.sury.org+1 (cli)`

I tried with both php version!

**Comment by javiereguiluz** [comment] 2017-07-17 07:05
I've just executed `composer create-project "symfony/framework-standard-edition"` and I couldn't reproduce the error. Given that there are no other comments either, I'm closing this as "probably fixed". If this is still failing for your, please reopen it. Thanks!

**Closed by javiereguiluz** 2017-07-17 07:05 UTC
Labels: Bug, Status: Needs Review
