### ISSUE TITLE
Yaml parser 

### ISSUE THREAD

**Issue by igormukhingmailcom** [symfony/symfony#15674] opened 2015-09-03 09:58 UTC
Hi.

Have next situation... 
I've got yaml file from my colleague and this file parsed not successfully:

```
# fixture.yml
table.inventory:
    inventory1:
        name: First Inventory
        description: Information about first inventory
        filename: first_inventory.txt
```

Parsed data:

```bash
# bash output from var_dump
array(2) {
  'table.inventory' =>
  NULL # <----------------------------- THIS IS NOT RIGHT
  '  inventory1' =>
  array(3) {
    'name' =>
    string(15) "First Inventory"
    'description' =>
    string(33) "Information about first inventory"
    'filename' =>
    string(19) "first_inventory.txt"
  }
}
```

So I have a look to this file and found that some looks-like-space characters is not spaces.
When I've converted this looks-like-space character into html code I've got `&ensp;`.

(When I replaced it with spaces characters - all become work fine).

How can we prevent that situations... When parser see `tab` character - it throws error. Maybe we can also throw exceptions with another looks-like-space characters?

Thank you.

**Comment by stof** [comment] 2015-09-03 10:06
It throws error because tabs are forbidden in the Yaml spec. On the other hand, unicode space-like chars are not forbidden

**Comment by igormukhingmailcom** [comment] 2015-09-03 11:04
@stof So this is expected behavior? Maybe parser need to understand space-like chars as spaces?

**Comment by javiereguiluz** [comment] 2015-09-03 13:09
@igormukhingmailcom the problem is that in Unicode charset there are a lot of space-like chars. The four common ones related to HTML entities are `nbsp`, `ensp`, `emsp` and `thinsp`, but there are more:

![unicode-spaces](https://cloud.githubusercontent.com/assets/73419/9658961/86c4afa6-524d-11e5-8c6a-fb9586c175e4.png)

[source](http://www.cs.tut.fi/~jkorpela/chars/spaces.html)

For this reason, I think we should close this issue as "won't fix" and always expect that the input data is well formatted with regular white spaces. However, maybe someone can think of an easy solution to this problem.

**Comment by igormukhingmailcom** [comment] 2015-09-03 13:27
@stof @javiereguiluz Maybe we can just previously replace all space-like chars to space at start of line?

**Comment by derrabus** [comment] 2015-09-04 14:45
If I read http://www.yaml.org/spec/1.2/spec.html#space/indentation/ correctly, `0x20` is the only space character that may be used for indentation. imho, the current behavior is correct.

@igormukhingmailcom If you have to deal with broken YAML files, you might want to fix them before passing them to the YAML parser.

**Closed** 2015-09-04 15:14 UTC
