### ISSUE TITLE
[Form] Collection indices changed by adders are not reassigned

### ISSUE THREAD

**Issue by jwmkrezmien** [symfony/symfony#7468] opened 2013-03-24 12:33 UTC
I am coding a project along the lines of the cookbook entry on embedded collections as stated on: http://symfony.com/doc/current/cookbook/form/form_collections.html.

I am considering the following use case:
1. Starting out with entering a new entity task, tag is the embedded collection
2. I click the Javascript 'add a tag'-link, which adds a bar 0 instance of the tag form
3. I click the Javascript 'add a tag'-link, which adds a bar 1 instance of the tag form
4. I click the Javascript 'add a tag'-link, which adds a bar 2 instance of the tag form
5. I click the Javascript 'delete this tag'-link for tag(1), which leaves me with the instances 0 and 2

Now, if I would leave all these tags blank (with a notblank validation on the tag name attribute), the returned form would be expected to visualize the error statements on instances 0 and 2. However, it turns out that the feedback is only displayed for instance 0.

If I change the returned form with firebug and set the instances on the name input field of instance 2 to '1', the feedback is displayed on the correct instance. This behavior indicates a mismatch between the indexing of the embedded form instances and the validators.

**Comment by ryancastle** [comment] 2015-03-09 06:35
We often see issues around this. We resolved the index collision problem in dynamic forms (which can occur if you follow the cookbook recipe), by using randomly generated indexes in JS. So to prevent  data corruption for occasional cases we end up breaking collection validation in every case. However, vague error messages seemed like a better compromise to us than broken data.

We've also had race condition issues mentioned by @webmozart. In the end we resolved that by using `indexBy` on the Doctrine collection, and aggressively persisting new items before the form is rendered.

We'd love to see a resolution to this, but I realise it's very difficult.

**Comment by angelk** [comment] 2015-08-19 12:57
+1 for this issue! Spend 3 hours.

**Comment by Zoopme** [comment] 2016-03-03 22:07
I have come round this issue on the client side by modifying the Javascript/Jquery code given in the Symfony Documentation.

Instead of numbering the new elements by counting the sub-elements, I am looking at the last element's id and extracting its index with a regular expression.

When adding an element, I am incrementing the last index by 1. That way, I never use the same index.

Here is my code :

```
        // If fields found then looking for last existing index
        if ( $findinput.length > 0 ) {

            // Reading id of last field
            var myString = $findinput.last().attr('id')
            
            // Setting regular expression to extract number from id containing letters, hyphens and underscores
            var myRegex = /^[-_A-Za-z]+([0-9]+)[-_A-Za-z]*$/
            
            // Executing regular expression on last collection field id
            var test = myRegex.exec(myString);
            
            // Extracting last index and incrementing by 1
            if (test.length > 0) index = parseInt(test[1]) + 1;
        }

```

**Comment by angelk** [comment] 2016-03-03 22:30
@Zoopme you could use twig filters "keys -> last".
Your solution won't fix the errors from https://github.com/symfony/symfony/issues/7468#issuecomment-60705768

**Comment by zoundfreak** [comment] 2016-03-03 23:09
I wasn't aware of the keys filter until now, but I ended up using something like the code below instead:

```
{% if customer.vehicles is not empty %}
    {% set nextIndex = max(customer.vehicles.getKeys) + 1 %}
{% else %}
    {% set nextIndex = 0 %}
{% endif %}

<div class="dynamicForm" data-next-index="{{ nextIndex }}" data-prototype="{% filter escape %}{% include 'ApplicationBundle:UserManagement:customer_vehicle_prototype.html.twig' with { 'item': form.vehicles.vars.prototype } %}{% endfilter %}">
    {% for item in form.vehicles %}
        {% include 'ApplicationBundle:UserManagement:customer_vehicle_prototype.html.twig' with { 'item': item } %}
    {% endfor %}

    {{ form_widget(form.vehicles) }}
</div>
```

I have a javascript that binds dynamic form handling to each dynamicForm element. In the javascript I use and modify the next-index data parameter. The next-index is increased on every addition and never decreased. I've managed to get this working automatically for any number of nested forms.

**Comment by Tjeerd** [comment] 2016-03-31 09:09
So, to summarize this issue: if you have a collection on a form, and if you want to use `allow_add` **and** `allow_delete` you should **not** use `by_reference = false`, because this will cause issues with mapping the error message back to the form. Correct?

**Comment by HeahDude** [comment] 2016-03-31 09:33
@Tjeerd Sadly I don't think we have the choice for now since the mapping is handled by the `ResizeFormListener` :/

**Comment by Seb33300** [comment] 2016-04-22 12:42
Solved this by extending my forms with this:



use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;

```
/**
 * Class AbstractEntityType
 * @package BvStandard\ServiceBundle\Form
 */
abstract class AbstractEntityType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SUBMIT, array($this, 'onPreSubmit'));
    }

    /**
     * @param FormEvent $event
     */
    public function onPreSubmit(FormEvent $event)
    {
        $form = $event->getForm();
        $data = $event->getData();
        $object = $event->getForm()->getData();

        // Loop on form fields
        foreach ($event->getForm()->all() as $field) {
            /** @var FormInterface $field */
            $fieldName = $field->getName();
            if ($field->getConfig()->getType()->getName() == 'collection') {
                if (isset($data[$fieldName]) && $object) {
                    $collection = $data[$fieldName];
                    $data[$fieldName] = array();
                    $k = 0;
                    // Reorder submitted data
                    foreach ($object->{'get'.ucfirst($fieldName)}() as $k => $item) {
                        // Search
                        foreach ($collection as $i => $c) {
                            $cId = is_array($c) && isset($c['id']) ? $c['id'] : $c;
                            if ($item->getId() == $cId) {
                                $data[$fieldName][$k] = $c;
                                unset($collection[$i]);
                                break;
                            }
                        }
                    }
                    // Added items
                    foreach ($collection as $c) {
                        $data[$fieldName][++$k] = $c;
                    }
                }
            }
        }

        $event->setData($data);
    }
}
```

**Comment by craescu** [comment] 2016-04-25 05:28
Thanks!

**Comment by placid2000** [comment] 2016-05-03 11:55
@Seb33300 Thank you for the solution. Does this approach also work for nested collections?

**Comment by Seb33300** [comment] 2016-05-03 12:03
If by nested collections, you mean something like:
```
    ->add('fieldName', CollectionType::class, array(
        'entry_type'   => OtherFormType::class,
        'allow_add'    => true,
        'allow_delete' => true,
        'by_reference' => false,
    ))
```

With `OtherFormType::class` is a form type containing a collection field.
Yes, it will work if `OtherFormType` extends the above class.

**Comment by placid2000** [comment] 2016-05-03 21:24
Yes, that's what I meant. Thanks!

**Comment by xabbuh** [comment] 2016-05-04 08:59
@Seb33300 @placid2000 Though you should rather think about moving the code into a form type extension instead of having to extend some base class.

**Comment by kimwue** [comment] 2016-05-24 11:20
I have the exact same issue with Symfony version 2.3.13-DEV.

@Tjeerd what is involved if I do not use `by_reference = false` - do I then only have to map my newly created sub-entities through my collection manually to my parent entity in my action that handles the form submission? Or something else as well?

**Comment by kimwue** [comment] 2016-05-26 11:26
@Seb33300 thanks for your solution. But with this does actually remove an item and create a new one when updating, so changing the entity ID. Something to be aware of.

**Comment by Seb33300** [comment] 2016-05-26 11:40
@kimwue If you want to update your entity without removing it, your form have to submit the id of each entities you are updating. If no id is submitted, a new entity is created.

**Comment by ShinDarth** [comment] 2016-06-03 09:33
Confirmed @arozenga

**Comment by ShinDarth** [comment] 2016-06-03 09:34
Confirmed @artorozenga

**Comment by Glideh** [comment] 2016-07-11 15:46
I can't use the `UniqueEntity` constraint on my collections (where `allow_add` is `true`).
However I don't see these forms working without `by_reference => false`.
I didn't understand the whole thread here but my issue seems linked.
The uniqueness seems to be checked against the database items only.

**Comment by kimwue** [comment] 2016-07-11 16:01
@Glideh as far as I know you need to write your own validator (or logic on Controller) to check if there are non-unique items. UniqueEntity checks only against DB.

**Comment by Glideh** [comment] 2016-07-12 07:08
I see, I'll do that, so it is the expected behavior ?

**Comment by dsands** [comment] 2016-11-10 23:45
@Seb33300 Thanks for this bit of code.

I made one very minor modification to handle zero based indexing:

I changed                        

$data[$fieldName][++$k] = $c;

to

$data[$fieldName][$k++] = $c;

i then followed the doc http://symfony.com/doc/current/form/create_form_type_extension.html

I extended the form type FormType, so all forms now automatically use this extension.

Nice solution!

**Comment by Seb33300** [comment] 2016-11-11 11:20
@dsands Doing `$k++` you will override the reordered existing submitted data (setted by the previous foreach).

You should set `$k = 0;` to `$k = -1;` and keep `++$k`.

**Comment by dsands** [comment] 2016-11-11 13:10
@Seb33300 It seemed to be working, but looking at the code again I see what you mean.

Thanks again!

**Comment by weaverryan** [comment] 2017-02-17 01:49
In case it helps, we ran into this issue on our KnpUniversity tutorial about form collections. The fix for our situation was actually quite simple (inspired by the solution by @Seb33300, but simpler because it just fixes our use-case): https://github.com/symfony/symfony/issues/7468#issuecomment-213411710

The solution is here: https://github.com/knpuniversity/symfony/commit/ab02c4797fe1692082c099f5f722220663f68863#diff-458cc0b549cdd91692b368dd8a0885bc along with a detailed explanation. In our JavaScript (http://knpuniversity.com/screencast/collections/add-new-collection-prototype#the-prototype-javascript) we always increment on new items... so if you delete an item before it's submitted, you have a hole (e.g. 1, 2, 4). Re-indexing the submitted data to be 1, 2, 3 seems to fix things just fine. 

I hope that helps someone out :)

**Comment by xabbuh** [comment] 2017-02-17 07:02
@weaverryan You need to be careful with such a solution as you run into cases where this means that no new object will be created, but the object to be removed from the collection is instead updated with the data of the newly added object.

**Comment by GuillaumeSTEIN** [comment] 2017-03-03 16:22
This used to work in my old sf2 project? what caused this new issue ?

**Comment by idybil** [comment] 2017-04-06 17:45
@weaverryan Your solution is not working if you use the UniqueEntity constraint, I think this is due to the fact that the collection index is rebuild.

**Comment by xabbuh** [comment] 2018-09-23 16:46
There are many issues related to this topic. I am closing here so we can keep #7828 as the main feature request.

**Closed by xabbuh** 2018-09-23 16:46 UTC
Labels: Feature, Form
