### ISSUE TITLE
CssSelector does not handle more complicated :not() pseudo-elements

### ISSUE THREAD

**Issue by czigor** [symfony/symfony#20711] opened 2016-12-01 11:00 UTC
CssSelector fails with this selector:

```css
.cart_contents .view:not(.cart_contents .view .view)
```

with an exception 

```
Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected ")"
but <whitespace "" at 39> found. in Symfony\Component\CssSelector\Exception\SyntaxErrorException::unexpectedToken()
(line 34 of symfony/css-selector/Exception/SyntaxErrorException.php).
```

The issue is that selectors with a space inside the `:not()` seem to be unsupported.

**Comment by czigor** [comment] 2016-12-01 11:01
Oh, that's the whole code I'm using:
```
use Symfony\Component\CssSelector\CssSelectorConverter;

$converter = new CssSelectorConverter();
var_dump($converter->toXPath('.cart_contents .view:not(.cart_contents .view .view)'));
```

**Comment by dbrumann** [comment] 2016-12-03 09:56
I can confirm the SyntaxErrorException being raised. I'm not sure if this should be considered a bug though as this is the behaviour I would expect from the [Selectors Level 3 specification](https://drafts.csswg.org/selectors-3/#negation):

> The negation pseudo-class, :not(X), is a functional notation taking a **simple selector** (excluding the negation pseudo-class itself) as an argument.

The behaviour you are trying to achieve might be what is described in the [Selectors Level 4 specification](https://drafts.csswg.org/selectors-4/#selector-list) as it changes simple selector to selector list, but since this is just a working draft I don't think it should be supported yet.

Maybe someone with a better knowledge of css selectors or css in general can weigh in.

**Comment by xabbuh** [comment] 2016-12-31 16:46
Closing here given the great explanation from @dbrumann. Feel free to provide some more information if you disagree and we may consider to reopen then.

**Closed by xabbuh** 2016-12-31 16:46 UTC
Labels: Bug, CssSelector, Status: Needs Review, Unconfirmed
