### ISSUE TITLE
Field of type entity does not support null value

### ISSUE THREAD

**Issue by remipIGN** [symfony/symfony#14856] opened 2015-06-04 07:47 UTC
In Symfony 2.7 only, works fine in 2.6.*

<pre>
$builder->add('typeVoie', 'entity', array(
				'class' => 'MyBundle:TypeVoie',
				'query_builder' => function(EntityRepository $er) {
					return $er->createQueryBuilder('u')
					->orderBy('u.weight', 'DESC');
				},
				'property' => 'typeVoieLower',
				'label' => 'Type de voie',
				'label_attr' => array('id' => 'label_typevoie'),
				'required' => false
)
</pre>

Despite the option `required => false` the form does not accept null values and returns 

`SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" `

The entity definition has the option `nullable=true` set on this field.

Thanks

**Comment by phansys** [comment] 2015-06-05 05:03
I think it's a duplicated of #14583.

**Comment by xabbuh** [comment] 2015-06-06 10:14
closing as a duplicate of #14583

**Closed by xabbuh** 2015-06-06 10:14 UTC
Labels: BC Break, Form
