### ISSUE TITLE
Fix Doctrine deprecations

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#50481] opened 2023-05-30 17:26 UTC
Since https://github.com/symfony/symfony/pull/50468, we're not blind anymore and we can see deprecations from Doctrine.

Here is an example job that reports many of them:
https://github.com/symfony/symfony/actions/runs/5124419388/jobs/9216226897

I'm calling for help to fix them all, on the lowest branch where applicable since we'd consider fixing those as a bug fix.

**Comment by ro0NL** [comment] 2023-05-30 17:55
~~should `DOCTRINE_DEPRECATIONS` be configured in symfony/error-handler actually?~~ :thinking:

perhaps the better question is, why isnt trigger the default mode in doctrine itself :sweat_smile:

**Comment by MatTheCat** [comment] 2023-05-30 18:07
> Doctrine\DBAL\Schema\Table::getForeignKeyColumns is deprecated. Use getForeignKey() and ForeignKeyConstraint::getLocalColumns() instead. (Table.php:727 called by Table.php:709, https://github.com/doctrine/dbal/pull/5731, package doctrine/dbal)

This should not be reported as the deprecation is caused by DBAL?

**Comment by nicolas-grekas** [comment] 2023-05-31 16:19
See https://github.com/egulias/EmailValidator/pull/367 for the ones about Lexer on 5.4

**Comment by PabloKowalczyk** [comment] 2023-06-02 09:04
I've got also:
```
User Deprecated: Using XML mapping driver with XSD validation disabled is deprecated and will not be supported in Doctrine ORM 3.0. (XmlDriver.php:60 called by SimplifiedXmlDriver.php:23, https://github.com/doctrine/orm/pull/6728, package doctrine/orm)
```
and
```
User Deprecated: Doctrine\DBAL\Connection::getEventManager is deprecated. (Connection.php:296 called by EntityManager.php:167, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal)
```

**Comment by stof** [comment] 2023-06-02 10:15
The second one is something to be fixed in DoctrineBundle. The ORM supports injecting the EventManager in the EntityManager constructor now. It uses the deprecated `Connection::getEventManager` only as a fallback for BC reasons (as for years, the EventManager was not injected directly). I guess the service definition in DoctrineBundle has not been updated yet to inject the additional argument.

**Comment by stof** [comment] 2023-06-02 10:15
The first one is discussed in https://github.com/doctrine/DoctrineBundle/issues/1647

**Closed as completed** 2023-06-04 14:51 UTC
Labels: Help wanted

**Comment by editorialec** [comment] 2024-01-22 13:17
Good Afternoon, 
Please can you kindly help with ethe below error message An exception has been thrown during the rendering of a template ("Context: Using short namespace alias "App:Testata\Testata" when calling Doctrine\ORM\EntityManager::getRepository
Problem: Feature was deprecated in doctrine/persistence 2.x and is not supported by installed doctrine/persistence:3.x
Solution: See the doctrine/deprecations logs for new alternative approaches."). Framework Sylius

**Comment by xabbuh** [comment] 2024-01-22 13:22
@editorialec For support, please refer to one of the [support channels](https://symfony.com/support).
