### ISSUE TITLE
X-Debug-Token-Link doesn't contains the port

### ISSUE THREAD

**Issue by Surfoo** [symfony/symfony#24254] opened 2017-09-19 09:12 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Hello,

I develops on localhost with the port 8080, and ajax header responses contains : 

> X-Debug-Token | bc3e77
> X-Debug-Token-Link | http://xxx.docker.xxx.io/index_debug.php/_profiler/bc3e77

But the profiler assumes the port 80, not the one really used. I want to display the link and click on it in case of error, but I can't for the moment.

**Comment by stof** [comment] 2017-09-19 09:56
I think this might be related to the fact that the app is using port 80 inside your Docker container when talking to Symfony. You could use this config:

```yaml
framework:
    router:
        http_port: 8080
```

However, I'm not sure it will work. It is possible that the port taken from the Request wins over this one when the request is using http.
In this case, it means you would have to ensure that the port determined by the Request object is the right one `8080` rather than `80` (which would be the cleanest way anyway, in case some other code relies on `$request->getPort()`)

**Comment by ro0NL** [comment] 2017-09-20 10:55
Can you give a few details.. how does `Request $request` look when accessing over localhost:8080.

https://github.com/symfony/symfony/blob/d0e8476afcab2c27191b55bfb6e0424b86646575/src/Symfony/Component/Routing/RequestContext.php#L78-L79

What happens here in your case? With my setup it works as expected.. exposed port 1234 real quick;

```
https://127.0.0.1:1234/app_dev.php
// Request::getPort() === 1234
```

As my Host header looks like; `127.0.0.1:1234`

**Comment by javiereguiluz** [comment] 2017-09-21 06:42
In some parts of the profiler there was a bug because we didn't use the UrlGenerator to generate the links. See https://github.com/symfony/symfony/pull/24153 for the solution.

But in this case, the code looks correct because we use the UrlGenerator to generate the value of the `X-Debug-Token-Link` header ... so this issue is probably not related to Symfony:

https://github.com/symfony/symfony/blob/7a9eb2c654efc6db6a3922563d868a8e3e2461b8/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L68-L71

**Comment by xabbuh** [comment] 2017-12-22 14:55
Closing here as this does not look like a bug. If that's not the case, please provide some more information on how to reproduce.

**Closed by xabbuh** 2017-12-22 14:55 UTC
Labels: Bug, Status: Waiting feedback, Unconfirmed
