### ISSUE TITLE
Generation problem(php app / console doctrine: generate: entities)

### ISSUE THREAD

**Issue by MarkThink** [symfony/symfony#15641] opened 2015-08-28 10:17 UTC
I found a BUG entity generation, testing is symfony2.7 specific code location:
=====
Vendor / doctrine / doctrine-bundle / mapping / DisconnectedMetadataFactory.php 119 line
>$ all [0] -> name should be changed to $ all [0] -> namespace

Yml files so that multiple entities operating normally generate code to generate Repository.php
repositoryClass: SharedModel\TestRepository

DisconnectedMetadataFactory.php 
```php
public function findNamespaceAndPathForMetadata(ClassMetadataCollection $metadata, $path = null)
{
	$all = $metadata->getMetadata();
	if (class_exists($all[0]->namespace)) {
		$r = new \ReflectionClass($all[0]->namespace);
		$path = $this->getBasePathForClass($r->getName(), $r->getNamespaceName(), dirname($r->getFilename()));
	} elseif (!$path) {
		throw new \RuntimeException(sprintf('Unable to determine where to save the "%s" class (use the --path option).', $all[0]->namespace));
	}

	$metadata->setPath($path);
	$metadata->setNamespace(isset($r) ? $r->getNamespaceName() : $all[0]->namespace);
}
```

**Comment by stof** [comment] 2015-08-28 10:28
there is no DisconnectedMetadataFactory in symfony. This class is in DoctrineBundle.

and this isssue is already fixed in DoctrineBundle 1.5. Just upgrade the bundle

**Closed by stof** 2015-08-28 10:28 UTC

**Comment by MarkThink** [comment] 2015-08-28 14:53
Thank you for your reply, and found a BUG If you modify the manner described above, will result in the following command failure.

php app/console doctrine:generate:crud
>[RuntimeException]                                                                       
 >Unable to determine where to save the "AppBundle\Entity" class (use the --path option). 

In other words, to solve the above problems and the introduction of the following questions.It is not so modify the code, we have not found the ultimate solution
-

**Comment by stof** [comment] 2015-08-28 15:58
@MarkThink I don't understand what you mean. Is there still a bug in DoctrineBundle 1.5, or is there a bug in your own fix (which is not the right one) ?

**Comment by stof** [comment] 2015-08-28 15:59
and in any case, this issue is **not** an issue in the Symfony codebase (DoctrineBundle is a separate package) so this is the wrong place to discuss it.

**Comment by MarkThink** [comment] 2015-08-29 00:48
thinaks ! This should not be a problem Doctrine, which is part of the Symfony scaffolding. Basically, I temporarily modify the code to meet my expectations. But it was a BUG ...

**Comment by stof** [comment] 2015-08-29 08:30
This was not a bug in the Symfony framework, as this code is in DoctrineBundle (look at the path to the file you linked. Symfony is in ``vendor/symfony/symfony``).
