### ISSUE TITLE
Symfony2 Routing dies on encoded slash.

### ISSUE THREAD

**Issue by Xatenev** [symfony/symfony#19597] opened 2016-08-11 15:06 UTC
Hello,

I've hit the following bug after some conversations on IRC:

Route definition:

```php
	/**
	 * @Method("GET")
	 * @Route(
	 *     "/{version}/nutrition/search/{datasource}/{value}:{sid}",
	 *     defaults={"count": "-1" },
	 *     requirements={"version": "1", "value": "[^\:]*"})
	 */
```

appDevUrlMatcher.php

  ```php
// app_nutrition_getsearchforfood
            if (preg_match('#^/(?P<version>1)/nutrition/search/(?P<datasource>[^/]++)/(?P<value>    [^\\:]*)\\:(?P<sid>[^/]++)$#s', $pathinfo, $matches)) {
            if (!in_array($this->context->getMethod(), array('GET', 'HEAD'))) {
                $allow = array_merge($allow, array('GET', 'HEAD'));
                goto not_app_nutrition_getsearchforfood;
            }

            return $this->mergeDefaults(array_replace($matches, array('_route' => 'app_nutrition_getsearchforfood')), array (  'count' => '-1',  '_controller' => 'AppBundle\\Controller\\NutritionController::getsearchForFoodAction',));
        }
        not_app_nutrition_getsearchforfood:
```

I call the URL like:
/1/nutrition/search/text/Mais%2C%20Grieß%20%2F%20Polenta:43lqqcqe6n39glub9pgtdadkt3
=> no route found!
/1/nutrition/search/text/Mais%2C%20Grie%C3%9F%20/%20Polenta:43lqqcqe6n39glub9pgtdadkt3
=> route found!

So when I use the encoded /, the regex in requirements for "value" obviously doesn't handle it correctly.

https://gist.github.com/garyttierney/9d102cfdc37f292e8871b83736a92dff

Would love to see this fixed, some workarounds while that would be appreciated too! :)

**Comment by jakzal** [comment] 2016-08-11 15:25
see #6442

**Comment by Xatenev** [comment] 2016-08-11 15:28
@jakzal  Hey, thanks for the reply - he says "For your use case, simply change the requirement for the palceholder to something like .+ and you can have the slash (encoded or not) in it." - I am not 100% sure how I can use that for my issue? I am using "[^\:]*" which should be all characters **except** double colon.

**Comment by Xatenev** [comment] 2016-08-11 15:41
I workarounded this by simply converting my parameter to a base64 value and transform it back after routing.

**Comment by ro0NL** [comment] 2016-08-11 16:07
For me this works as advertised in #6442 on 3.2.0-DEV, could perhaps give steps to reproduce?

```php
class DefaultController extends Controller
{
    /**
     * @Route("/{foo}", name="homepage", requirements={"foo": ".*"})
     */
    public function indexAction(Request $request, $foo = '')
    {
        dump($foo);
        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.root_dir').'/..'),
        ]);
    }
}
```

Hit `/foo%2Fbar`

Got 
![image](https://cloud.githubusercontent.com/assets/1047696/17595713/69a4ca96-5fee-11e6-91e9-614b2308b7e3.png)

**Comment by Xatenev** [comment] 2016-08-12 07:58
@ro0NL: Most likely because my requirements regex is another than yours, try to reproduce the route exactly as mine, for example: `/{foo}:{bar}` and the same regex as I have above.

**Comment by ro0NL** [comment] 2016-08-12 15:59
Still works like a charm ;-)

```php
class DefaultController extends Controller
{
    /**
     * @Route("/{foo}:{bar}", name="homepage", requirements={"foo": "[^\:]*", "bar": "[^\:]*"})
     */
    public function indexAction(Request $request, $foo = '', $bar = '')
    {
        dump($foo, $bar);
        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.root_dir').'/..'),
        ]);
    }
}

```

![image](https://cloud.githubusercontent.com/assets/1047696/17628508/d847051e-60b5-11e6-9ad1-1f51fb283f14.png)

Can you fork symfony standard and work on a reproduceable scenario?

**Comment by javiereguiluz** [comment] 2016-08-29 07:19
This issue looks like "fixed", so I'm closing it. @Xatenev if you don't agree, please reopen it. Thanks!

**Closed by javiereguiluz** 2016-08-29 07:19 UTC
Labels: Routing
