### ISSUE TITLE
ChoiceType with 'multiple' => true results in Notice: Array to string conversion

### ISSUE THREAD

**Issue by Moskito89** [symfony/symfony#30872] opened 2019-04-05 11:53 UTC
**Symfony version(s) affected**: 4.2.5

**Description**  
When adding a ChoiceType to a form with `'multiple' => false` the array of choices needs a value of `null`.

**How to reproduce**  

This one is working:
````php
->add('roles', ChoiceType::class, [
    'multiple' => true,
    'choices'  => [
        'Option1' => 'Option1',
        'Option2' => 'Option2',
    ]
])
````
This one is not working:
````php
->add('roles', ChoiceType::class, [
    'multiple' => false,
    'choices'  => [
        'Option1' => 'Option1',
        'Option2' => 'Option2',
    ]
])
````
But this one is working:
````php
->add('roles', ChoiceType::class, [
    'multiple' => false,
    'choices'  => [
        'Option1' => null,
        'Option2' => 'Option2',
    ]
])
```` 

The second example results in a `Notice: Array to string conversion` coming from `Symfony/Form/ChoiceList/ArrayChoiceList.php` line 68. 

Am I doing something wrong here? Shouldn't it be possible to have Select or Radio containing two options with custom values?

**Comment by xabbuh** [comment] 2019-04-05 12:17
Can you please create a small example application that allows to reproduce your issue?

**Comment by drupol** [comment] 2019-04-07 13:00
I'm unable to reproduce the issue on the master branch.

I also checked ArrayChoiceList.php from master and yes, it has been fixed (see https://github.com/symfony/symfony/blob/47e571b3fc51e13f3742b822afcb3b1beb84f239/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L68).

**Comment by yceruto** [comment] 2019-04-07 13:05
I reseach about this too and I concluded that the 2nd example is expected if you pass an `array` as default value:
```php
$data = ['foo' => []];

$form = $this->createFormBuilder($data)
    ->add('foo', ChoiceType::class, [
        'choices'  => [
            'Option1' => 'Option1',
            'Option2' => 'Option2',
        ]
    ])
;
```
the `multiple` option is `false`, all `choices` values are castable to string but the given choice don't `[]`.

can be closed IMO.

**Comment by xabbuh** [comment] 2019-04-07 13:07
@Moskito89 Indeed, I missed that. The passed array is not interpreted as the options (which you probably intended to configure), but the data your form is bound too. So I am closing here then as there is nothing to fix.

**Closed by xabbuh** 2019-04-07 13:07 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by Moskito89** [comment] 2019-04-08 07:32
Thanks for your hint, @yceruto, I was able to find that problem here! In this case it was caused by an empty object as second parameter in `createForm()`.
Also thanks for your kind and fast help @xabbuh and @drupol – have a nice week!

**Comment by drupol** [comment] 2019-04-08 07:44
Status: Closed
