### ISSUE TITLE
prepareBaseUrl() Request bug

### ISSUE THREAD

**Issue by garygreen** [symfony/symfony#13617] opened 2015-02-07 00:28 UTC
Take for instance you have a mod_rewrite in apache to redirect all requests through to index.php (common practice for "pretty" urls)

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

If you request for a url like: `http://my-site.com/fruit/strawberry/index.php/blah` the base url comes back as `blah`. I would expect the base to be `/` and segments to be `fruit/strawberry/index.php/blah` due to the mod_rewrite.

The issue is caused by the `basename` in the very top lines in `prepareBaseUrl` as below:

**src/Symfony/Component/HttpFoundation/Request.php**

``` php
    /**
     * Prepares the base URL.
     *
     * @return string
     */
    protected function prepareBaseUrl()
    {
        $filename = basename($this->server->get('SCRIPT_FILENAME'));
        if (basename($this->server->get('SCRIPT_NAME')) === $filename) {
            $baseUrl = $this->server->get('SCRIPT_NAME');
```

My request looks as below:

```
REQUEST_URI = /fruit/test/index.php/blah
SCRIPT_FILENAME = E:/Sites/cc-new/public_html/index.php
SCRIPT_NAME = /index.php
```

Essentially what it's doing is getting the `SCRIPT_FILENAME`, doing a `basename` which turns it into simply `index.php`.

Then `SCRIPT_NAME` goes through `basename` too so it end's up doing `index.php == index.php` which is true then set's the base as the `SCRIPT_NAME` i.e. simply index.php

This is incorrect, it should set the base to `/` only. Something weird is going on with the use of `basename`....?

**Comment by jakzal** [comment] 2015-02-07 17:29
There's few issues with the Request class, see #6406.

**Comment by jakzal** [comment] 2015-02-07 17:39
Actually, I fail to reproduce it. 

In your case, is the `index.php` in the URL `/fruit/strawberry/index.php/blah` the actual file, or is the request rewritten to `/index.php/fruit/strawberry/index.php/blah`?

**Comment by garygreen** [comment] 2015-02-07 18:08
The path `/fruit/strawberry/index.php/blah` doesn't exist so it gets routed through to the base `/index.php` as per the mod rewrite. It get's confused what the base path is and thinks `/blah` is the base.

I would expect the url segments to be:
1. fruit
2. strawberry
3. index.php
4. blah

But instead it's simply:

1. blah

**Comment by garygreen** [comment] 2015-02-07 18:12
Also the bug seems to occur only when directly on the domain, like:

- `http://localhost/fruit/straw....` -- doesn't work
- `http://localhost/my-app/fruit/straw...` -- works

Also if you do `http://localhost/index.php/fruit/straw...` that will work too. You need to have the mod_rewrite rule setup in order to properly reproduce the bug

**Comment by garygreen** [comment] 2015-02-07 18:14
Interestingly enough if you change the `index.php` file to something random like `u93h94h9g.php` and update your mod_rewrite rule to:

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^ u93h94h9g.php [L]
</IfModule>
```

Then try it, it will work fine. Basically if you have the same name in your url like `index.php` as the mod rewrite it will get confused.

**Comment by Tobion** [comment] 2015-02-07 21:23
Can you please provide one clear example of what you expect and what actually happens.

Given your example `http://my-site.com/fruit/strawberry/index.php/blah` i think
- base url should be `/fruit/strawberry/index.php`
- path info should be `/blah`

That means everything before `/blah` is just the base url to access the front controller. And `/blah` is the path should is used for routing etc.

**Comment by garygreen** [comment] 2015-02-07 22:28
@Tobion 

Example: `http://my-site.com/fruit/strawberry/index.php/blah`

I expect base to be `/` and path to be `/fruit/strawberry/index.php/blah` because the `fruit/strawberry/index.php` file does not exist, it should mod_rewrite to the 'base' index.php with that as the path. Therefore base should simply be `/`. Instead the base is being set as `/blah` (reasons as I've mentioned in previous posts, due to the use of `basename`)

My app structure is simply like below:

```
/
   .htaccess (with the mod rewrite rule as in my opening post)
   index.php
```

**Comment by Tobion** [comment] 2015-02-07 22:42
Looks like duplicate/related to #7329. Can you test whether #13039 fixed the problem?

**Comment by garygreen** [comment] 2015-02-07 23:54
Unfortunately #13039 didn't fix the problem. I made some notes from what you wrote on that issue:

> So /foo/app.php/mypage would resolve to the same page as /bar/app.php/mypage and /mypage.
Because symfony thinks /foo/app.php and /bar/app.php is the base url and doesn't care about matching it.
So you can make as many duplicates as you wish! And these pages won't work correctly because assets for example won't resolve to the correct path. It will create paths like /foo/bundles/mybundle/css/layout.css which do not exists of course with the hacked /foo prefix.

> I don't see how your second example can be fixed reliably. Because /foobar/index.php can or cannot be the base url. We don't really know. It depends on the webserver configuration.

I think you hit the nail on the head, that's exactly what's happening. I'm not sure how this can be fixed? I still need to use mod_rewrite, is there any work around or way for me to tell symphony "ok when you see index.php, *this* is the real base url" ?

**Comment by kbond** [comment] 2015-02-24 19:19
I am also having this problem. It can be reproduced with the symfony-standard edition:

The following all product the same response:

- http://localhost/app/example
- http://localhost/foo/bar/app.php/app/example (should be 404)
- http://localhost/anything/can/go/here/app.php/app/example (should be 404)

Of course, the following produces a 404:

- http://localhost/foo/bar/baz.php/app/example
- http://localhost/anything/can/go/here/foo.php/app/example

**Comment by garygreen** [comment] 2015-02-24 19:42
@kbond do you only experience the issue with mod rewrites?

**Comment by kbond** [comment] 2015-02-24 19:50
yes, I am using the .htaccess file exactly from symfony-standard

**Comment by andig** [comment] 2015-03-26 14:49
I've just stumbled across this in the wild, see URLs and parse request info below. .htaccess:

	<IfModule mod_rewrite.c>
		RewriteEngine On
		RewriteRule ^middleware/(.*) middleware.php/$1 [L]
	</IfModule>

result w/o rewrite:

	http://localhost/vz/htdocs/middleware.php/data/2a93a9a0.json

	getBaseUrl(): /vz/htdocs/middleware.php
	getPathInfo(): /data/2a93a9a0-60df-11e2-83cc-2b8029d72006.json
	server->get('PATH_INFO'): /data/2a93a9a0-60df-11e2-83cc-2b8029d72006.json

result w/ rewrite:

	http://localhost/vz/htdocs/middleware/data/2a93a9a0.json

	getBaseUrl(): /vz/htdocs
	getPathInfo(): /middleware/data/2a93a9a0-60df-11e2-83cc-2b8029d72006.json
	server->get('PATH_INFO'): /data/2a93a9a0-60df-11e2-83cc-2b8029d72006.json

What's confusing me is why PATH_INFO isn't directly used from the `server` variables?

**Comment by andig** [comment] 2016-12-25 05:59
Checking back looking at the last example. Is there anything else needed to make the issue of mismatching `PATH_INFO`/`getPathInfo()` more obvious?

**Comment by andig** [comment] 2017-03-20 17:34
ping @fabpot could we reopen this issue? It is _not_ fixed, also https://github.com/symfony/symfony/pull/14468 does _not_ fix it.

**Comment by xabbuh** [comment] 2017-03-20 17:57
@andig This issue is not closed.

**Comment by andig** [comment] 2017-03-20 18:06
@xabbuh you're totally right- I've only looked at the closing notice. While I'd really like to do something about it I'm totally stumped by the whole `preparePathInfo` / `prepareBaseUrl` madness.

**Comment by nicolas-grekas** [comment] 2017-07-06 08:50
I think this is not something we should deal with in Symfony side, it's too late.
The webserver config needs to be enhanced instead. Personnaly, not on a SF app, but to give a hint, I used to use this:
```
RewriteEngine On

RewriteRule ^index\.php(/.*)?$ - [S=1]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d [OR]
RewriteCond %{REQUEST_FILENAME} -l
RewriteRule .+ - [S=1]

RewriteCond %{ENV:PATCHWORK_REQUEST} ^$
RewriteRule .* index.php [E=PATCHWORK_REQUEST:/$0]
```

to be adjusted for the case but give the idea.

**Comment by fabpot** [comment] 2017-07-06 08:53
Closing as a won't fix. The fix should be the Apache configuration.

**Closed by fabpot** 2017-07-06 08:53 UTC
Labels: Bug, HttpFoundation, Status: Needs Review

**Comment by andig** [comment] 2017-07-07 15:09
> The webserver config needs to be enhanced instead.

I'm wondering why that is. Without the "enhanced" web server config PHP sets `$request->server->get('PATH_INFO')` to the correct value, however `$request->getPathInfo()` returns an unusable value. IMHO that indicates that the `getPathInfo()` logic is broken, not the web server config.

> I think this is not something we should deal with on Symfony side, 

Unfortunate but..

> it's too late.

.. as defence against compatibility issues?

**Comment by devnix** [comment] 2019-10-23 16:11
I've been struggling for 1.5 days for a good way of setting a proper `pathInfo` for a legacy application I'm maintaining, to be able to generate and match routes, where _every_ route has his front controller but the base path is root.

I'm going to deal with my problem extending the `Request` class because the API will not let me any other chance (unless I'm missing something important).

```php
namespace FooBar\Legacy\Component\HttpFoundation;

use Symfony\Component\HttpFoundation\Request as RequestBase;

class Request extends RequestBase
{
    /**
     * {@inheritdoc}
     */
    protected function prepareBaseUrl()
    {
        return '';
    }
}
```

And instantiate my monkey patched class into my container:

```php

$containerBuilder
    ->register('request', FooBar\Legacy\Component\HttpFoundation\Request::class)
    ->setFactory([FooBar\Legacy\Component\HttpFoundation\Request::class, 'createFromGlobals']);
```

I would appreciate any suggestions if this can be done better because this smells so crappy.
