### ISSUE TITLE
Intl error with file autogenerate 

### ISSUE THREAD

**Issue by Geoffray-buhler** [symfony/symfony#43776] opened 2021-10-27 11:40 UTC
I remake my BDD with symfony database:drop and symfony database:create and this error happened 

![error](https://user-images.githubusercontent.com/55780756/139030752-29eae800-33b2-46f2-a815-1d87e2aaf825.png)

so i don't understand with i have this error 

i try to fix it with this issue
https://github.com/symfony/maker-bundle/pull/991/commits/e0ffa99844790a6911370e5a491507cf6a399d0e

but nothing change 

i need help for fix it!

**Comment by stof** [comment] 2021-10-27 12:05
Are you using the (deprecated) `twig/extensions` package in your project ? That's the package defining the `Twig\Extensions\IntlExtension` class

**Comment by Geoffray-buhler** [comment] 2021-10-27 12:09
Yes because we use `|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY")` in twig files

**Comment by stof** [comment] 2021-10-27 12:13
`format_datetime` is *not* coming from the old deprecated extensions. But your error message says that your config tries to register a service using the old extension class. So look in your config files where this service is defined.

**Comment by xabbuh** [comment] 2021-11-03 10:48
I am closing here as this as @stof explained doesn't seem to be caused by an issue in the Symfony codebase.

**Closed as completed by xabbuh** 2021-11-03 10:48 UTC
Labels: Status: Waiting feedback
