### ISSUE TITLE
Upgrading 3.3 to 3.4 and 4.0: overwriting core services with parent logic

### ISSUE THREAD

**Issue by ReSpawN** [symfony/symfony#26064] opened 2018-02-06 11:38 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | 
| Feature request? | 
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.4.4

We're upgrading a big application built on Symfony 2.8 through to 3.3.x to 3.4 with autowiring logic, following some tutorials from KNP (by @weaverryan) and we're running into a problem with a overwriting parent service. 

We're overwriting `Symfony\Component\Security\Http\Firewall\SwitchUserListener` with our own `AppBundle\EventListener\SwitchUserListener`, which looked like this:

```
    security.authentication.switchuser_listener:
        class: AppBundle\EventListener\SwitchUserListener
        arguments:
            - "@security.token_storage"
            - "@app.webservice_user_provider"
            - "@security.user_checker"
            - 'main'
            - "@security.access.decision_manager"
            - "@?monolog.logger.security"
            - '_impersonate'
            - 'ROLE_ALLOWED_TO_SWITCH'
            - "@?debug.event_dispatcher"
            - ['email1@domain.tld', 'email2@domain.tld']
        tags:
            - { name: monolog.logger, channel: security }
```

Naturally, we've upgraded the logic to suit the new format, but using `autoconfigure` with `parent` is not allowed in 3.4. Thus we've configured it like this:

```
    Symfony\Component\Security\Http\Firewall\SwitchUserListener:
        class: AppBundle\EventListener\SwitchUserListener
        parent: Symfony\Component\Security\Http\Firewall\SwitchUserListener
        arguments:
            $restricted: ['email1@domain.tld', 'email2@domain.tld']
```

Even with the entire argument stack from the first block we're getting memory exhaustion after a couple of seconds, implicating some sort of loop. We've tried `alias`in the entire thing to no avail and currently we're at a loss as to how to get it working. Have we stumbled upon some sort of bug?

**Comment by stof** [comment] 2018-02-06 12:15
the issue here is that you have a parent referencing yourselves, meaning it creates an infinite loop

**Comment by ReSpawN** [comment] 2018-02-06 13:27
Then how am I supposed to overwrite the default `SwitchUserListener` when I cannot use it as a parent?

**Comment by iltar** [comment] 2018-02-06 13:41
You could try service decoration

**Comment by stof** [comment] 2018-02-06 13:58
you can **never** override a service and using parent at the same time, as the inheritance involves that the original service still exists, while overriding is replacing it.

this is true since Symfony 2.0 btw.

**Comment by ReSpawN** [comment] 2018-02-06 14:04
@stof Makes sence, we've only been using Symfony since 2.8 so I cannot attest to the fact of it being introduced in 2.0.

So in short: extending a parent only works when the original is intact and/or not used. 

@iltar I've got some idea's as to how, but can you perhaps offer an example? Guessing you mean: https://symfony.com/doc/3.4/service_container/service_decoration.html?

**Comment by stof** [comment] 2018-02-06 14:06
@ReSpawN the issue is that you are not extending the original service here, as you are replacing the service with your own, and so you are extending yourselves. Extending a service definition involves that the parent is a different one.

**Comment by JoeKre** [comment] 2018-02-06 15:26
@ReSpawN 
out of curiosity, an `EventSubscriber` to the `SwitchUserEvent` is not suitable for your needs?

**Comment by ReSpawN** [comment] 2018-02-06 16:48
@stof How could we then still use the Symfony-defined arguments with our own service, plus an additional appended argument (like in my 2nd original code block)?

@JoeKre we're currently already using one for memcached user clearance (since you're essentially impersonating another user). The logic defined in our custom `SwitchUserListener` is to prevent people from assuming two specific `super-super-uber-admin` accounts, nothing more. 

If it is indeed the case that such an attempt has been tried, we're firing a flashBag error with a 302 response and logging the event (sort of like `su`'in root without being in the sudo file).

If you have a short snip as to how we might prevent such an event which a listener, I'm all...eyes.

**Comment by JoeKre** [comment] 2018-02-07 07:39
@ReSpawN 

```
class SwitchUserListener implements EventSubscriberInterface
{
    public function checkSwitchAllowed(SwitchUserEvent $switchUserEvent)
    {
        $request = $switchUserEvent->getRequest();
        if(....) {
            throw new AccessDeniedException();
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            SecurityEvents::SWITCH_USER => ['checkSwitchAllowed', 0]
        ];
    }

}
```

That's pretty much it. But a redirect here will be a bit tricky since you can't return a redirect response and interrupt the user request. Either throw an exception or trigger a redirect manually and stop the execution.

**Comment by ReSpawN** [comment] 2018-02-07 13:11
Yea, that's kinda what I figurered, but we really need the redirect and the flashbag notice. I'll give it a go, see what I come up with! I'll keep you apprised.

**Comment by xabbuh** [comment] 2018-02-07 18:12
I am closing here as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Closed by xabbuh** 2018-02-07 18:12 UTC
