### ISSUE TITLE
Intl merge BC break

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#12412] opened 2014-11-04 13:29 UTC
It seems that the locales data is not properly merged now that the intl resources are in json files.

Before the merge the `sr_latn` locale returned `sprski` as a language now it returns the Cyrillic version. Same as only `sr` would be specified.

**Comment by Koc** [comment] 2015-01-27 10:56
This issue marked as "critical" but almost 3 month over. Does it still actual? Ping @webmozart , @mvrhov

**Comment by mvrhov** [comment] 2015-01-28 09:32
I'd say it's still an issue.

**Comment by SoboLAN** [comment] 2015-10-14 13:29
Any updates on this ? Is it still an issue ?

**Comment by mvrhov** [comment] 2015-10-14 13:38
Yes one year later it's still an issue.

**Comment by fabpot** [comment] 2015-10-15 15:28
So, the question is who wants to work on this issue and try to provide a fix?

**Comment by javiereguiluz** [comment] 2016-03-10 14:53
@jakzal sorry to ping you again about ICU data ... but since you worked recently on these things, could you please check if this issue was fixed after your ICU updates and fixes? Thanks!

**Comment by jakzal** [comment] 2016-03-10 14:55
@javiereguiluz no worries, ping me whenever you need :)

**Comment by jakzal** [comment] 2016-03-10 15:00
@mvrhov @SoboLAN I'll need your help here. How to reproduce your issue?

**Comment by mvrhov** [comment] 2016-03-10 17:16
Just define your locale as sr_latin.. and it should return the text in latin alphabet.
It's probably the same bug with all locales that have different than country suffix.

For the test the comparison with the data that integrated Intl returns could be made.
From the top of my head as I don't have the code before me I think that I was calling `getLanguageNames('sl_latn')`

**Comment by jakzal** [comment] 2016-03-10 18:03
```
echo \Symfony\Component\Intl\Intl::getLanguageBundle()->getLanguageNames('sr_Latn')['sr'];
```
returns `srpski`.

`српски` is returned for `sr` locale.

**Comment by jakzal** [comment] 2016-03-10 18:21
@mvrhov this is not my experience. Can you please paste the output of the following script?

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Intl\Intl;

var_dump(Intl::getLanguageBundle()->getLanguageNames('sr')['sr']);
var_dump(Intl::getLanguageBundle()->getLanguageNames('sr_Latn')['sr']);
var_dump(Intl::getLanguageBundle()->getLanguageNames('sr_latn')['sr']);

var_dump(Intl::getIcuVersion());
var_dump(Intl::getIcuDataVersion());
var_dump(Intl::getIcuStubVersion());
```

My output:
```
string(12) "српски"
string(6) "srpski"
string(6) "srpski"
string(4) "52.1"
string(4) "55.1"
string(4) "55.1"
```

**Comment by mvrhov** [comment] 2016-03-10 18:46
I'll update the whole stack tomorrow to latest 2.7, but for now the live website is running symfony 2.7.3

```
string(12) "српски"
string(6) "srpski"
string(12) "српски"
string(4) "52.1"
string(4) "54.1"
string(4) "51.2"
```

**Comment by jakzal** [comment] 2016-03-10 18:48
You've been using the old version. The fix was merged few days ago and is not present in any released version, so you'll need to wait for the next release. Thanks for feedback!

**Closed by jakzal** 2016-03-10 18:48 UTC
Labels: BC Break, Critical, Intl
