### ISSUE TITLE
[YAML] paragraphs do not work in YAML files with Silex/Twig-bridge/Translation

### ISSUE THREAD

**Issue by gdesnoues** [symfony/symfony#22608] opened 2017-05-02 06:59 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | ?
| RFC?             | no
| Symfony version  | latest

The paragraphs in YAML files (define with `|`) appear in inline mode when I use it in a twig template with `{{ 'mykey'|trans }}`
Is it my fault or a bug ?
Thanks

**Comment by javiereguiluz** [comment] 2017-05-02 07:00
@gdesnoues are you also applying the [nl2br filter](https://twig.sensiolabs.org/doc/2.x/filters/nl2br.html) to turn the new line chars into `<br>` so you see them on HTML pages?

**Comment by gdesnoues** [comment] 2017-05-02 07:05
yes with nl2br it's ok but it's not define in the silex/translation documentation. so I think that they are a problem with YAML including no ?
if I whant have HTML tags and `\n` I must do `{{ 'home.text3'|trans|raw|nl2br }}`

**Comment by javiereguiluz** [comment] 2017-05-02 07:09
I'd say this is the expected behavior:

1. Symfony's YAML component parses paragraphs correctly and maintains the `\n`
2. HTML ignore all white spaces and `\n`
3. If you apply the `nl2br` filter, the `\n` are turned into `<br>`

It looks like the problem is 2. ... but we cannot do anything to change that behavior. Do you agree?

**Comment by gdesnoues** [comment] 2017-05-02 07:14
a YAML file same as :
`  text1: |
            ligne1
            ligne2`
Should be understood as `ligne1<br>ligne2` directly no? without nl2br it isn't
Thank you for your help, I am new user so I do not understand everything :-)

**Comment by javiereguiluz** [comment] 2017-05-02 07:45
@gdesnoues I don't agree with your last comment. The reason is that YAML has nothing to do with the web/HTML.

In the YAML file you are defining some contents ... but YAML knows nothing about where do you want to use those contents (in a HTML page? In a TXT file? etc.) So, YAML doesn't add or change anything in your contents.

If your contents in YAML include `<br>`, you'll have `<br>`. If your contents include only "new lines" (`\n` character) then YAML gives you `\n`.

Now, if you want to display those contents in a HTML page, the `\n` are ignored: not by Symfony, not by Twig, not by YAML ... but by HTML. This is so common, that Twig (and PHP too) gives you a `nl2br` filter to turn those `\n` into `<br>` automatically.

So, you have several options:

1) Keep your existing YAML contents and add the `nl2br` filter when needed. (I recommend you this)
2) Add the `<br>` into the YAML contents (and apply the `raw` filter when displaying the contents). This is an ugly solution and it makes your contents less reusable because they are prepared only for HTML.
3) Move some of the YAML contents to the Twig templates. This is not possible some times, but if they are static contents and only meant for the web, maybe you can turn those YAML contents into regular `<p>` elements in your Twig templates.

In any case, I'm closing this issue as "fixed" because this is an HTML behavior that we cannot change and Symfony/Twig already provide solutions for it. Thanks!

**Closed by javiereguiluz** 2017-05-02 07:45 UTC
