### ISSUE TITLE
Possible regression: Memory consumption 10x higher from 3.4.3 -> 3.4.4

### ISSUE THREAD

**Issue by sawmurai** [symfony/symfony#25964] opened 2018-01-30 09:31 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

Hello guys,

after updating from 3.4.3 to 3.4.4 we noticed a 10x increase in memory usage when running our testsuite. To analyze the issue, we profiled both execution (3.4.3 and 3.4.4) with blackfire (see links below). Looking at the comparison of both runs we had the idea to revert #25835. Running blackfire again shows a decreased memory consumption.

The cache was cleared prior to each run.

If you need further information let me know. Unfortunately I can not share the code base.

3.4.4: https://blackfire.io/profiles/22ed34e8-9827-48ef-8ed4-7eaf9a6218c5/graph
3.4.3: https://blackfire.io/profiles/eacbfc2d-6592-4003-9d16-6c967286d36e/graph
3.4.4 with reverted #25835: https://blackfire.io/profiles/df3e9f4a-d28c-4a4e-8cf9-ea48a1659328/graph

Comparisons:
[3.4.3 -> 3.4.4](https://blackfire.io/profiles/compare/dbb5091e-5da7-429f-a007-de0bfcf1b29f/graph)
[3.4.4 -> 3.4.4 w/o 25835](https://blackfire.io/profiles/compare/b930e7ec-b984-45da-82d4-d5bf73d20343/graph)

**Comment by sroze** [comment] 2018-01-30 09:35
Good catch! Any chance you could create a comparison between these two graphs (3.4.4 & 3.4.3)? I can't figure how to do it when you don't own the graphs.

**Comment by sawmurai** [comment] 2018-01-30 09:38
Sure, updated the original text :)

**Comment by sroze** [comment] 2018-01-30 09:39
I got a nice 404 :)

**Comment by sawmurai** [comment] 2018-01-30 09:40
Haha, please try again

**Comment by derrabus** [comment] 2018-01-30 09:44
The comparison links still don't work.

**Comment by bscutt** [comment] 2018-01-30 09:46
I think I'm experiencing a similar with release v3.3.16 - our unit test suite has started failing with out of memory errors, where as it all ran perfectly on v3.3.15.

I can provide more information if required.

Thanks!

**Comment by jonathanbull** [comment] 2018-01-30 09:48
Same here!

**Comment by nicolas-grekas** [comment] 2018-01-30 09:50
@bscutt @jonathanbull did you also try reverting #25835 and it improved the situation?

**Comment by dominikzogg** [comment] 2018-01-30 09:53
https://github.com/symfony/symfony/issues/25965

**Comment by sroze** [comment] 2018-01-30 09:54
Interestingly, @nanasess just opened this issue about a memory leak in the error handlers: https://github.com/symfony/symfony/issues/25965. Can you three also try his suggested patch (without reverting the other mentioned PR) and see if it improves the situation?

**Comment by sawmurai** [comment] 2018-01-30 09:59
Yes, his patch also fixes the issues in 3.4.4.

**Comment by dominikzogg** [comment] 2018-01-30 10:01
@sroze his patch fixes the memory consumption

**Comment by nicolas-grekas** [comment] 2018-01-30 15:18
Closing as duplicate of #25965, which now has a PR: #25971
Thanks for the report.

**Closed by nicolas-grekas** 2018-01-30 15:18 UTC
Labels: BC Break, Bug, Status: Needs Review
