### ISSUE TITLE
[WebProfilerBundle] Add git information in config panel

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#23273] opened 2017-06-22 21:32 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

Looks like:

![screenshot from 2017-06-22 23-27-36](https://user-images.githubusercontent.com/4578773/27456789-9627c6f2-57a2-11e7-934c-f3cb22694d4b.png)

**Comment by fabpot** [comment] 2017-06-22 22:52
Why would be it be useful?

**Comment by iltar** [comment] 2017-06-23 08:51
Actually, I'd like to see at least the current branch in the WDT, and possible also if my repository is clean or not, the commit is rather useless though. As someone who often works with branches in git and switches out branches, I sometimes end up wondering why changes do not work, just to find out I forgot to switch back from the master to my original feature/topic branch.

It's not a must-have feature for me, but it would be nice to have (given it doesn't slow the request too much).

**Comment by maidmaid** [comment] 2017-06-23 10:02
This informations can also be useful to reproduce a bug from token created in production or shared by a other developper. With this, we can checkout the same version locally. Moreover, monolog has also a [similar way](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/GitProcessor.php) to injects git infos in logs.

> the commit is rather useless though

Know commit can be useful to reproduce a bug in similar conditions from old/external token.

>  I'd like to see [...] also if my repository is clean or not

Yes, a ``git status`` in WDT would be also very usefull.

**Comment by fabpot** [comment] 2017-06-23 15:08
I'm not convinced this is really that useful. You should know which version is in production and getting the information locally is trivial from the CLI. Having this in the profiler does not bring much value I think.

**Comment by maidmaid** [comment] 2017-06-26 13:42
It may happen to debug an old profile which is not based on the current version. An another case is to debug an distributed profile in enterprise context, where also the branch/commit is not known. Storing version in profile solves theses cases.

**Comment by fabpot** [comment] 2017-06-26 15:30
Do these use cases real ones you have in your company? I think that the vast majority of our users have a local DB for the profiles that they consult right after hitting a resource. Especially since we removed all stores but the filesystem one. Import/export were also removed a while ago.

**Comment by stof** [comment] 2017-06-26 16:34
If your own company needs to store the exact git info in each profile, I suggest building a separate panel in a third-party bundle for that. I don't think it needs to be in the core.

**Comment by maidmaid** [comment] 2017-06-26 16:53
Your answers match to your previous choices about the removal of distributed stores and import/export (although I do not agree with these choices: Symfony should offer tools to work as a team and not just as an isolated developer).

Nevertheless, I continue to think that a profile is closely linked to a request **and** a version of the code.

**Comment by fabpot** [comment] 2017-06-26 16:55
Indeed, we disagree. For the record, I'm 👎 for this addition.

**Comment by xabbuh** [comment] 2017-06-28 09:39
I can see the need for displaying the current git branch, but I also agree that there's not much need for the current revision (and it can be done easily in userland code).

**Comment by ro0NL** [comment] 2017-07-06 14:33
What about something more elegant like

![image](https://user-images.githubusercontent.com/1047696/27916252-cd22b786-6268-11e7-9034-8199d0e3a558.png)

**Comment by fabpot** [comment] 2017-07-06 14:36
Still :-1: from me. It means using Process to run Git, so it's slow, one more way to make things fail, ... Not worth it IMHO.

**Comment by ro0NL** [comment] 2017-07-06 14:37
We would read this from the `.git` folder no?

**Comment by javiereguiluz** [comment] 2017-07-06 15:21
As a rule of thumb, in the profiler we usually store *"things that you may need or be asked for when looking for the cause of some bug or problem"*. The git information wouldn't fit in that definition.

That's why I'm 👎  on this proposal too. I'm sorry.

**Comment by javiereguiluz** [comment] 2017-07-31 10:37
Given the downvotes from the Core Team, I must close this as "won't fix".

@maidmaid although this time the proposal didn't make it, thank you for proposing so many ideas to improve Symfony!

**Closed by javiereguiluz** 2017-07-31 10:37 UTC
Labels: Feature, WebProfilerBundle

**Comment by ro0NL** [comment] 2024-05-01 06:36
would be nice if reconsidered :')

```
$ cat .git/HEAD 
ref: refs/heads/develop
```
