### ISSUE TITLE
Database user and password displayed to visitors !!!

### ISSUE THREAD

**Issue by ouriels** [symfony/symfony#22736] opened 2017-05-17 22:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.0.9

Today there was a connection problem on 1&1 servers, and the connection can't be established between server with php code and server with database.

The message displayed was:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for
user 'user_DISPLAYED'@'212.227.24.46' (using password: YES) in /homepages/32/d63
2730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:4
3 Stack trace: #0 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctr
ine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=db63...',
'user_DISPLAYED', 'password_DISPLAYED', Array) #1 /homepages/32/d632730529/htdoc
s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41):
Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=db63...',
'user_DISPLAYED', 'password_DISPLAYED', Array) #2 /homepages/32/d632730529/htdoc
s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360):
Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'user_DISPLAYED',
'password_DISPLAYED', Array) #3 /homepages/32/d632730529/htdocs/vendor/doctrine/
dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connec
tion.php(3 in /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/
DBAL/Driver/AbstractMySQLDriver.php on line 103"
```

```
user_DISPLAYED = The real username !...
password_DISPLAYED = The real database password !...
```

However I override the error page of TwigBundle.

**Comment by iltar** [comment] 2017-05-18 06:51
This should not be displayed in prod, are you using the dev environment? You might also want to update your Symfony version, 3.0 and 3.1 are not supported anymore with normal bug fixes. Can you reproduce this issue with 3.2 in prod?

**Comment by ouriels** [comment] 2017-05-18 07:32
It was the PROD environment.
I can't reproduce it because it is only when the web host (1&1) encountered a probleme with connection between servers. I called the support and they tell me that it is a problem on their side.
Anymore, the user and password was displayed to any visitors...

**Comment by xabbuh** [comment] 2017-05-18 07:38
You could just enter an invalid password to get the same connection error and then you can check if you can reproduce this on Symfony 3.2 too.

**Comment by javiereguiluz** [comment] 2017-05-18 07:50
@ouriels I understand your worries, but rest assure that Symfony doesn't do this when using the `prod` environment and the `debug` parameter is `false`.

You don't have to redefine the error page because Symfony never displays any detail (or passwords) in error pages when running in production environment.

Now let's see if you can reproduce this issue and give us more information in case we need to make any other change. Thanks!

**Comment by ouriels** [comment] 2017-05-18 08:08
Ok I will update the version and test, and inform you about reproduction.

But for information, I reproduced now with wrong username and password, screenshot linked (I changed username and password after screenshot).

The _debug_ parameter is setted to _false_ . 

Here is a message:
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'my_username'@'212.227.24.46' (using password: YES) in /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43 Stack trace: #0 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=db63...', 'my_username', 'my_password', Array) #1 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=db63...', 'my_username', 'my_password', Array) #2 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'my_username', 'my_password', Array) #3 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect() #4 /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Conne in /homepages/32/d632730529/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103

![capture](https://cloud.githubusercontent.com/assets/28767120/26192438/efc88e10-3bb1-11e7-9da8-e6d80340570d.PNG)

**Comment by javiereguiluz** [comment] 2017-05-18 08:14
@ouriels I may be wrong ... but that screenshot looks like this is not related to Symfony, but to PHP itself. Is the [display-errors option](http://php.net/manual/en/errorfunc.configuration.php#ini.display-errors) disabled in PHP .ini?

**Comment by ouriels** [comment] 2017-05-18 08:51
Effectively, I changed the _display_errors_ value to _Off_ and any sensible information is displayed.

![capture](https://cloud.githubusercontent.com/assets/28767120/26194174/d3a6048c-3bb7-11e7-8d3c-7c767588db41.PNG)

Strange that 1&1 set this value to _On_ by default...
Thank you for yours responses !

**Comment by javiereguiluz** [comment] 2017-05-18 09:26
@ouriels I'm glad this is fixed now. You are right that this option should be `Off` by default to avoid bad experiences like the one you suffered.

Anyway, let's close this one as fixed. Thanks!

**Closed by javiereguiluz** 2017-05-18 09:26 UTC
