### ISSUE TITLE
Service contracts 2.5 PHP version

### ISSUE THREAD

**Issue by reyostallenberg** [symfony/symfony#45936] opened 2022-04-04 13:59 UTC
### Symfony version(s) affected

2.5

### Description

Sorry, the version is not a correct symfony version (but I could not find a place to report service contract bugs)

The version marked as supported in https://github.com/symfony/service-contracts/blob/034c73d5dd4c05c71a27f05b3c43c0f2fcc8985a/composer.json#L19 conflicts with the code in  https://github.com/symfony/service-contracts/blob/034c73d5dd4c05c71a27f05b3c43c0f2fcc8985a/Attribute/SubscribedService.php#L30

This results in:

> PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in /project-root/vendor/symfony/service-contracts/Attribute/SubscribedService.php on line 30

### How to reproduce

// Use a server with php 7.4
// First, run "composer require symfony/service-contracts:2.5.0"
// Then, execute this file:
```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use namespace Symfony\Contracts\Service\Attribute;

new Attribute('a-string');
```

### Possible Solution

Adjust the class to be compatible for "php": ">=7.2.5"

**Comment by stof** [comment] 2022-04-04 14:01
Well, the attribute class has no reason to be loaded on PHP 7.4, given that PHP 7.4 does not support attributes at all. How are you ending executing this file ?

**Comment by derrabus** [comment] 2022-04-04 14:14
As @stof explained, PHP 7 does not support attributes and your script does not reflect the indended use of that class. I'm closing this issue because it's not a bug.

**Closed as completed by derrabus** 2022-04-04 14:14 UTC
Labels: Bug, Status: Needs Review

**Comment by reyostallenberg** [comment] 2022-04-04 14:19
It's fine with me this issue to be closed.

Just an explanation of why it is was loaded.

Sadly in a run of `bin/magento setup:di:compile` magento walk over ALL classes with composer ClassLoader.

**Comment by derrabus** [comment] 2022-04-04 14:59
That's something you should report to the author of that `setup:di:compile` command then. We will never guarantee you that all classes in a Symfony package are loadable on the lowest PHP version supported by that package. The reason is that we sometimes deliver optional features that leverage features of newer PHP releases, like attributes in this case.

That means that even if we "fix" the service contracts, that script of yours will choke on a different Symfony package. The author of that script simply chose a creative way to "use" composer packages. That's nothing we can fix on our side.

**Comment by reyostallenberg** [comment] 2022-04-04 15:08
Yes, I understood that, that's why it's fine with me this issue is closed, sorry for using your time, I should have checked more stuff before reporting a bug.
