### ISSUE TITLE
[Form] Bug in debug:form command

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#25394] opened 2017-12-08 11:14 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

```
➜  tmp.3oyTrHIJZT git:(master) php bin/console debug:form Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType -v

Symfony\Component\Form\Extension\Core\Type\ChoiceType (Block prefix: "choice")
==============================================================================

2017-12-08T21:11:24+10:00 [error] Error thrown while running command "debug:form 'Symfony\Component\Form\Extension\Core\Type\ChoiceType' -v". Message: "Warning: strstr() expects parameter 1 to be string, array given"

In Table.php line 413:

  [ErrorException]
  Warning: strstr() expects parameter 1 to be string, array given


Exception trace:
 Symfony\Component\Console\Helper\Table->buildTableRows() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Helper/Table.php:277
 Symfony\Component\Console\Helper\Table->render() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Style/SymfonyStyle.php:189
 Symfony\Component\Console\Style\SymfonyStyle->table() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/form/Console/Descriptor/TextDescriptor.php:86
 Symfony\Component\Form\Console\Descriptor\TextDescriptor->describeResolvedFormType() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/form/Console/Descriptor/Descriptor.php:55
 Symfony\Component\Form\Console\Descriptor\Descriptor->describe() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Helper/DescriptorHelper.php:69
 Symfony\Component\Console\Helper\DescriptorHelper->describe() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/form/Command/DebugCommand.php:137
 Symfony\Component\Form\Command\DebugCommand->execute() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Application.php:233
 Symfony\Component\Console\Application->doRun() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/framework-bundle/Console/Application.php:71
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /tmp/tmp.3oyTrHIJZT/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /tmp/tmp.3oyTrHIJZT/bin/console:39

debug:form [--format FORMAT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<class>] [<option>]
```

**Comment by Simperfit** [comment] 2017-12-08 12:42
@maidmaid I can reproduce but only on 4.0.*, on 4.1@dev it does not trigger an error. I don't see any differences in the code.

I'm will be trying to provide a fix, but it seems that we could do better than what I though, by searching to root cause instead of fixing the error directly. Creating the PR just now.

**Comment by Simperfit** [comment] 2017-12-08 12:43
Status: Reviewed

**Comment by yceruto** [comment] 2017-12-08 14:01
I can't reproduce the bug either. @maidmaid could you please show a full dump output before this line?
https://github.com/symfony/symfony/blob/d6d187d26e0921a428c7ecc423d4f915c8f72c14/src/Symfony/Component/Form/Console/Descriptor/TextDescriptor.php#L156

**Comment by yceruto** [comment] 2017-12-08 14:13
@maidmaid does this problem happen only with `ChoiceType`?

**Comment by Simperfit** [comment] 2017-12-08 14:21
The dump of options
```
array(4) {
  ["own"]=>
  array(11) {
    [0]=>
    string(25) "choice_translation_domain"
    [1]=>
    string(4) "days"
    [2]=>
    string(6) "format"
    [3]=>
    string(5) "html5"
    [4]=>
    string(5) "input"
    [5]=>
    string(14) "model_timezone"
    [6]=>
    string(6) "months"
    [7]=>
    string(11) "placeholder"
    [8]=>
    string(13) "view_timezone"
    [9]=>
    string(6) "widget"
    [10]=>
    string(5) "years"
  }
  ["overridden"]=>
  array(6) {
    [0]=>
    string(21) "<info>FormType</info>"
    [1]=>
    object(Symfony\Component\Console\Helper\TableSeparator)#154 (2) {
      ["value":"Symfony\Component\Console\Helper\TableCell":private]=>
      string(0) ""
      ["options":"Symfony\Component\Console\Helper\TableCell":private]=>
      array(2) {
        ["rowspan"]=>
        int(1)
        ["colspan"]=>
        int(1)
      }
    }
    [2]=>
    string(12) "by_reference"
    [3]=>
    string(8) "compound"
    [4]=>
    string(10) "data_class"
    [5]=>
    string(14) "error_bubbling"
  }
  ["parent"]=>
  array(21) {
    [0]=>
    string(21) "<info>FormType</info>"
    [1]=>
    object(Symfony\Component\Console\Helper\TableSeparator)#157 (2) {
      ["value":"Symfony\Component\Console\Helper\TableCell":private]=>
      string(0) ""
      ["options":"Symfony\Component\Console\Helper\TableCell":private]=>
      array(2) {
        ["rowspan"]=>
        int(1)
        ["colspan"]=>
        int(1)
      }
    }
    [2]=>
    string(6) "action"
    [3]=>
    string(4) "attr"
    [4]=>
    string(15) "auto_initialize"
    [5]=>
    string(10) "block_name"
    [6]=>
    string(4) "data"
    [7]=>
    string(8) "disabled"
    [8]=>
    string(10) "empty_data"
    [9]=>
    string(12) "inherit_data"
    [10]=>
    string(5) "label"
    [11]=>
    string(10) "label_attr"
    [12]=>
    string(12) "label_format"
    [13]=>
    string(6) "mapped"
    [14]=>
    string(6) "method"
    [15]=>
    string(21) "post_max_size_message"
    [16]=>
    string(13) "property_path"
    [17]=>
    string(8) "required"
    [18]=>
    string(18) "translation_domain"
    [19]=>
    string(4) "trim"
    [20]=>
    string(23) "upload_max_size_message"
  }
  ["extension"]=>
  &array(1) {
    [0]=>
    array(0) {
    }
  }
}
```

The whole stack with DateType :
```
Symfony\Component\Form\Extension\Core\Type\DateType (Block prefix: "date")
==========================================================================

2017-12-08T14:20:16+00:00 [error] Error thrown while running command "debug:form 'Symfony\Component\Form\Extension\Core\Type\DateType' -v". Message: "Warning: strstr() expects parameter 1 to be string, array given"

In Table.php line 413:
                                                                   
  [ErrorException]                                                 
  Warning: strstr() expects parameter 1 to be string, array given  
                                                                   

Exception trace:
 Symfony\Component\Console\Helper\Table->buildTableRows() at /Users/hamza/projet/workflow/vendor/symfony/console/Helper/Table.php:277
 Symfony\Component\Console\Helper\Table->render() at /Users/hamza/projet/workflow/vendor/symfony/console/Style/SymfonyStyle.php:189
 Symfony\Component\Console\Style\SymfonyStyle->table() at /Users/hamza/projet/workflow/vendor/symfony/form/Console/Descriptor/TextDescriptor.php:86
 Symfony\Component\Form\Console\Descriptor\TextDescriptor->describeResolvedFormType() at /Users/hamza/projet/workflow/vendor/symfony/form/Console/Descriptor/Descriptor.php:55
 Symfony\Component\Form\Console\Descriptor\Descriptor->describe() at /Users/hamza/projet/workflow/vendor/symfony/console/Helper/DescriptorHelper.php:69
 Symfony\Component\Console\Helper\DescriptorHelper->describe() at /Users/hamza/projet/workflow/vendor/symfony/form/Command/DebugCommand.php:137
 Symfony\Component\Form\Command\DebugCommand->execute() at /Users/hamza/projet/workflow/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /Users/hamza/projet/workflow/vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at /Users/hamza/projet/workflow/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /Users/hamza/projet/workflow/vendor/symfony/console/Application.php:233
 Symfony\Component\Console\Application->doRun() at /Users/hamza/projet/workflow/vendor/symfony/framework-bundle/Console/Application.php:71
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/hamza/projet/workflow/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /Users/hamza/projet/workflow/bin/console:39

debug:form [--format FORMAT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<class>] [<option>]

```

@yceruto with the patch provided it does fix it, but I feels like it's not the right fix ;).

**Comment by yceruto** [comment] 2017-12-08 14:29
> with the patch provided it does fix it, but I feels like it's not the right fix ;).

Yep, I also feel it. The great news is that I see the problem now:
```
  ["extension"]=>
  &array(1) {
    [0]=>
    array(0) {
    }
  }
```
So I'm working on the solution, thanks for the `dump`.

**Comment by yceruto** [comment] 2017-12-08 15:33
See https://github.com/symfony/symfony/pull/25404

**Comment by yceruto** [comment] 2017-12-08 15:45
Since the debug command was not registering with all the information it needs (fixed in https://github.com/symfony/symfony/pull/25396), we found this error, so every cloud has a silver lining! :)

**Comment by Simperfit** [comment] 2017-12-16 14:20
@xabbuh This issue can be closed since the PR has been merged.

**Comment by yceruto** [comment] 2017-12-16 15:16
Still open #25404 which guarantees that there will be no empty groups in the future.

**Closed** 2017-12-31 07:08 UTC
Labels: Bug, Form, Status: Reviewed
