### ISSUE TITLE
Incompatible version of phpstan

### ISSUE THREAD

**Issue by multifinger** [symfony/symfony#58846] opened 2024-11-13 11:41 UTC
### Symfony version(s) affected

6.4.13

### Description

Installed symfony with command `symfony new test --version="6.4.*" --webapp`
Conflicting packages are symfony/property-info 6.4.13 and phpstan/phpdoc-parser 2.0.0
Fresh install ends with error during cache:clear command step 
```
!!  11:27:05 CRITICAL  [php] Uncaught Error: Too few arguments to function PHPStan\PhpDocParser\Parser\ConstExprParser::__construct(), 0 passed in /www/itnsk/vendor/symfony/property-info/Extractor/PhpStanExtractor.php on line 71 and exactly 1 expected ["exception" => ArgumentCountError { …}]
!!  
!!  In ConstExprParser.php line 18:
!!                                                                                 
!!    Too few arguments to function PHPStan\PhpDocParser\Parser\ConstExprParser::  
!!    __construct(), 0 passed in /www/itnsk/vendor/symfony/property-info/Extracto  
!!    r/PhpStanExtractor.php on line 71 and exactly 1 expected                      
```

Fixed with reverting  phpstan/phpdoc-parser to 1.* latest version

### How to reproduce

Run `symfony new test --version="6.4.*" --webapp` to install new project (v6.4.13 affected, 6.4.12 was fine)

### Possible Solution

Keep phpstan/phpdoc-parser back to v1.*

**Comment by stof** [comment] 2024-11-13 11:43
Duplicate of #58796

**Closed as completed by stof** 2024-11-13 11:43 UTC
Labels: Bug, Status: Needs Review, PropertyInfo
