### ISSUE TITLE
[Yaml] Multiple blocks in same file are not merged

### ISSUE THREAD

**Issue by metamaker** [symfony/symfony#27151] opened 2018-05-04 09:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

I expect that parsing

```
blocks:
    foo:
        key1: val1
        key2: val2
        
blocks:
    bar:
        key1: val3
        key2: val4
```

must provide same array as parsing

```
blocks:
    foo:
        key1: val1
        key2: val2

    bar:
        key1: val3
        key2: val4
```

However, running unit test proves that Yaml parser only returns first `blocks` definition and **silently** ignores second part.

```
<?php

namespace Sio\Configuration\Tests\Yaml;

use Symfony\Component\Yaml\Yaml;

class YamlParserMultipleBlocksSameNameTest extends \PHPUnit_Framework_TestCase
{
    private $fixtureMultipleBlocksSameName = <<<YAML
blocks:
    foo:
        key1: val1
        key2: val2
        
blocks:
    bar:
        key1: val3
        key2: val4
YAML;

    public function test_multipleBlocksWithSameNameInYaml_ReturnsOnlyFirstBlock_correct()
    {
        $result = Yaml::parse($this->fixtureMultipleBlocksSameName);

        $this->assertCount(1, $result['blocks']);
        $this->assertEquals(['foo'], array_keys($result['blocks']));
    }

    public function test_multipleBlocksWithSameNameInYaml_ReturnsAllBlocks_failing()
    {
        $result = Yaml::parse($this->fixtureMultipleBlocksSameName);

        $this->assertNotCount(2, $result['blocks']);
        $this->assertNotEquals(['foo', 'bar'], array_keys($result['blocks']));
    }
}
```

**Comment by stof** [comment] 2018-05-04 09:58
That's not a bug. That's the expected behavior of the YAML spec.

And this is **not** silent. the parser throws a deprecation warning for this in 3.4, and a ParseException in 4.0

**Comment by xabbuh** [comment] 2018-05-04 10:00
closing as this is not a bug but the expected behaviour as @stof explained

**Closed by xabbuh** 2018-05-04 10:00 UTC
Labels: Bug, Status: Needs Review, Yaml

**Comment by metamaker** [comment] 2018-05-04 10:03
@stof @xabbuh Thank you for explanation!
