### ISSUE TITLE
Doctrine no longer works

### ISSUE THREAD

**Issue by tutosfaciles48** [symfony/symfony#32203] opened 2019-06-26 21:45 UTC
**Symfony version(s) affected**: 4.3

**Description**  
Call to a member function has() on null

**How to reproduce**  
Code in a controller construct:

`public function __construct(Environment $twig) {
		$this->twig = $twig;
		$this->em = $this->getDoctrine()->getManager();
	}`

**Possible Solution**  
"Call to a member function has() on null" at vendor/symfony/framework-bundle/Controller/ControllerTrait.php line 338 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function has() on null at vendor/symfony/framework-bundle/Controller/ControllerTrait.php:338)"} []

**Additional context**  
Appeared after upgrading symfony from 4.2.9 to 4.3

**Comment by Tobion** [comment] 2019-06-27 01:29
Calling `$this->getDoctrine()` requires the container. The container is not set in the constructor yet. It's set via a setter, see https://github.com/symfony/symfony/blob/2fdfa1a8ebd4258df44f27d121ad2b29c2d28d6c/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L50

This didn't change in 4.3. So it was either broken before already or you changed more that a pure sf upgrade. To solve the problem you either call `getDoctrine` later, e.g. in your actions or you don't extend the AbstractController but inject doctrine/entity manager directly in the constructor.

**Comment by xabbuh** [comment] 2019-06-27 11:48
closing here since, as explained, this is not a bug

**Closed by xabbuh** 2019-06-27 11:48 UTC
Labels: Status: Waiting feedback
