### ISSUE TITLE
Notice in getDefaultValidator()

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#15309] opened 2015-07-18 18:02 UTC
[The code sample](http://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers) from the documentation produces the following errror.
`PHP Notice:  Undefined index: blue in vendor/symfony/console/Question/ChoiceQuestion.php on line 165`

This error does not appear on 2.6 version.

**Comment by harikt** [comment] 2015-07-19 03:12
could you show your gist, so we can reproduce it ?

**Comment by Chi-teck** [comment] 2015-07-19 06:11
```php
#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ChoiceQuestion;

class GreetCommand extends Command
{
  protected function configure()
  {
    $this
      ->setName('demo:greet')
      ->setDescription('Greet someone')
    ;
  }

  protected function execute(InputInterface $input, OutputInterface $output)
  {
    $helper = $this->getHelper('question');
    $question = new ChoiceQuestion(
        'Please select your favorite color (defaults to red)',
        array('red', 'blue', 'yellow'),
        0
    );
    $question->setErrorMessage('Color %s is invalid.');

    $color = $helper->ask($input, $output, $question);
    $output->writeln('You have just selected: '.$color);

  }
}

$application = new Application();
$application->add(new GreetCommand());
$application->run();

```

**Comment by harikt** [comment] 2015-07-19 07:05
Your above example works fine in 2.6. I have tested this.

```
php test.php demo:greet
Please select your favorite color (defaults to red)
  [0] red
  [1] blue
  [2] yellow
 > 0
You have just selected: red
```

Is there any other way you are running ?

**Comment by Chi-teck** [comment] 2015-07-19 08:06
@harikt, the problem exists on 2.7 only. Sorry if I was not explicit enough. I just updated the first message.

**Comment by harikt** [comment] 2015-07-19 09:35
@Chi-teck couldn't replicate this on my machine :( .

**Comment by xabbuh** [comment] 2015-07-19 12:27
looks like this was introduced by #15271

**Comment by harikt** [comment] 2015-07-19 14:54
ok, so it was in `2.7.2` . The one I installed was `2.7` .

**Comment by jakzal** [comment] 2015-07-20 13:18
@Chi-teck thanks for providing an example. The issue is fixed in the latest 2.7, so it only affects 2.7.2.

**Comment by jakzal** [comment] 2015-07-20 13:20
Closing. Feel free to reopen if you manage to reproduce this on the latest 2.7 branch.

**Closed by jakzal** 2015-07-20 13:20 UTC
Labels: Bug, Console, Status: Needs Review

**Comment by funivan** [comment] 2015-07-24 06:01
@jakzal  can you reopen this issue. I can reproduce this bug on 2.7.2 branch (as i can see this is latest stable release)

**Comment by xabbuh** [comment] 2015-07-24 06:12
@funivan The patch will be part of Symfony 2.7.3.

**Comment by funivan** [comment] 2015-07-24 06:27
@xabbuh great, thanks.
