### ISSUE TITLE
Form PropertyAccessor.php(writeProperty) makes doctrine delete collection

### ISSUE THREAD

**Issue by solexsylvain** [symfony/symfony#25937] opened 2018-01-26 14:33 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

When submitting a form that has a child which is a CollectionType. On the handle request, submit ... writeProperty. It will set the value with a new collection instead of reusing the existing collection of the entity and then Doctrine will mark the collection for deletion and if you are doing a flush, it's catastrophic.

Problem started with Doctrine > 2.5.14 as they fixed an issue. It's documented.
https://github.com/doctrine/DoctrineModule/blob/57c0ee958664e3a04b211607fd21b7e6b6fc4e68/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L379-L394

It was discussed as a bug in doctrine but it's due to a fix to make it behave as per design. Discussion is here (with @Ocramius and @Sharoff45) : https://github.com/doctrine/doctrine2/issues/6976#issuecomment-360788598

**Comment by stof** [comment] 2018-01-26 14:38
Unless you make your property public (which gives the Form component direct access to replacing the collection), the fact that the collection is replaced entirely requires your own entity to provide an API to do it.
so how does your entity looks like ?

**Comment by fabpot** [comment] 2018-02-22 06:45
Closing as there is no feedback from the reporter. @solexsylvain Feel free to reopen with more information.

**Closed by fabpot** 2018-02-22 06:45 UTC
Labels: Bug, Doctrine, Form, Status: Needs Review

**Comment by haydenk** [comment] 2018-04-03 15:57
@stof I have this problem with Symfony 3.3.16, Doctrine 2.5 with my property set to private and only a getter, an add method, and a remove method. No direct setter method. @solexsylvain

**Comment by xabbuh** [comment] 2018-04-03 16:13
@haydenk Can you provide a small example application that allows to reproduce your issue?

**Comment by haydenk** [comment] 2018-04-03 16:49
@xabbuh Definitely. I started a smaller version already trying to see if there was perhaps a library or configuration conflict. It's not ready to push yet but I can get it up soon.
