### ISSUE TITLE
Windows Defender detects trojan in symfony/console package

### ISSUE THREAD

**Issue by OndrejBakan** [symfony/symfony#38454] opened 2020-10-07 08:37 UTC
**Symfony version(s) affected**: symfony/website-skeleton (v5.1.99)

**Description**  
Windows Defender detects Trojan:Win32/CryptInject!ml in symfony/console package.

  - Installing symfony/console (v5.1.7): Downloading (95%)
Downloading (95%)
Downloading (95%)    Failed to download symfony/console from dist: Content-Length mismatch, received 0 bytes out of the expected 134809
    Now trying to download from source
  - Installing symfony/console (v5.1.7): Cloning 04c3a31fe8 from cache

**How to reproduce**  
composer create-project symfony/website-skeleton project-name

**Possible Solution**  
N/A

**Additional context**  
N/A

**Comment by nicolas-grekas** [comment] 2020-10-07 08:40
Duplicate of #38447
There is nothing we can do about it.

**Closed as completed by nicolas-grekas** 2020-10-07 08:40 UTC
Labels: Bug, Console

**Comment by fabpot** [comment] 2020-10-07 15:26
Problem should be solved now.
