### ISSUE TITLE
[router] Does not take additional GET parameter in account if it has a default value.

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#18035] opened 2016-03-06 19:33 UTC
In a Controller, I have two actions : 

```php
    /**
     * @Route("/search", name="search_with_default", defaults={"p"=1})
     */
    public function searchWithDefaultAction(Request $request)
    {
        return $this->render('default/index.html.twig');
    }

    /**
     * @Route("/search", name="search_without_default")
     */
    public function searchWithoutDefaultAction(Request $request)
    {
        return $this->render('default/index.html.twig');
    }
```

In twig, I generate routes to these actions with an additional GET parameter 'p' : 

```twig
	{{ path('search_with_default',{'p':2}) }}<br/>
	{{ path('search_without_default',{'p':2}) }}
```

Result :

```
/app_dev.php/search
/app_dev.php/search?p=2 
```

The first one, totally ignore the value assigned on 'p'.

Bug reproduced here :

https://github.com/Alsatian67/symfony-standard

(index page shows the two paths)

**Comment by xabbuh** [comment] 2016-03-07 13:58
Does this only happen if both routes are configured for the same path?

**Comment by Alsatian67** [comment] 2016-03-07 17:51
No, that's just to point on the bug. It is always so.

**Comment by hhamon** [comment] 2016-03-09 14:33
I would say that's a normal behavior. The second argument of the `path` function is meant to replace the placeholders in the url patterns. So if the url doesn't have a `{placeholder}` but you have a default hardcoded value set, then it's taken. The extra GET parameters are only added for parameters / placeholders that are not defined in the route definition.

**Comment by Alsatian67** [comment] 2016-03-09 17:29
I don't thing its normal.

Default means value when not defined.
So I can't immagine the default is overwriting the submitted one.

**Comment by weaverryan** [comment] 2016-03-12 12:11
It's weird because `defaults` is meant really to fill in the `{wildcard}` values. So the whole example looks strange - why add a `defaults` and then want to have query parameters added?

That being said, I would agree it's a bug - though really edge-case. The intention is that if there is no wildcard to fill in, the extra parameters are added as query parameters. In this case, the first route has no `p` wildcard, so I would also expect it to be added as a query parameter.

But again, it's weird :). You would fetch the `p` `defaults` value in a different way than the `p` query parameter: they're two different things entirely.

Btw @Alsatian67 thanks for the very clear report and fork - it's a weird situation, but very easy to understand!

**Comment by Tobion** [comment] 2016-03-13 14:39
Duplicate of #10940

**Closed by Tobion** 2016-03-13 14:39 UTC
Labels: Bug, Routing, Status: Needs Review, Unconfirmed

**Comment by Alsatian67** [comment] 2016-03-13 19:15
@weaverryan 

Let me explain my usage :

It's a search page with many optional parameters :

?page=1&name=&sortby=&date=&category= ...

Each of them are optional and mostly not used.

So I don't like a route like /{page}/{name}/{sortby} ...

But I want to set defaults like page = 1, name = "", sortby = "name"

;)
