### ISSUE TITLE
global service in twig error

### ISSUE THREAD

**Issue by fabirus** [symfony/symfony#23010] opened 2017-06-01 09:56 UTC
**## ScopeWideningInjectionException in CheckReferenceValidityPass.php line 142:
Scope Widening Injection detected: The definition "twig" references the service "custombundle_data" which belongs to a narrower scope. Generally, it is safer to either move "twig" to scope "request" or alternatively rely on the provider pattern by injecting the container itself, and requesting the service "custombundle_data" each time it is needed. In rare, special cases however that might not be necessary, then you can set the reference to strict=false to get rid of this error.**

hello, i have some errors when i want to use global service in my twig template
i use symfony 2.7

this is my configuration
config.yml
```
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        custombundle: "@backend.custombundle.data"
```
services.yml

```
backend.custombundle.data:
       class : NumTek\Backend\Common\Services\CustomBundleData
       arguments: ["@doctrine.orm.entity_manager", "@request_stack" ]
       scope: "request"
       calls:
          - [setContainer, [@service_container]]
```
CustomBundleData
 ```
private $em;
    private $requestStack;


    public function __construct(EntityManager $em, RequestStack $requestStack){
        $this->request  = $requestStack->getCurrentRequest();
        $this->em       = $em;
    }


    /**
     * Get Informations of Company
     */
    public function getInfosCompany() {

        $entity = $this->em->getRepository('NumTekBackendCustomBundle:Infos')->findOneBy(array(
            'del' => 0),
            array('createdAt' => 'desc')
        );

        return $entity;

    }
```

Thanks you

**Comment by stof** [comment] 2017-06-01 10:49
Well, why are you makign your own service request-scoped ? this is your issue.

what you should do instead is storing the RequestStack in your service, and calling `getCurrentRequest` only at the time you *use* your service.

Btw, the request scope is deprecated

**Comment by fabirus** [comment] 2017-06-02 14:28
thanks you

**Comment by xabbuh** [comment] 2017-06-02 15:58
closing as this is not a bug

**Closed by xabbuh** 2017-06-02 15:58 UTC
