### ISSUE TITLE
Symfony/Translation update error

### ISSUE THREAD

**Issue by slappyslap** [symfony/symfony#43219] opened 2021-09-28 09:20 UTC
**Symfony version(s) affected**: 4.4.31

**Description**
![image](https://user-images.githubusercontent.com/15176255/135059922-6105a5d5-d460-4a20-9972-0a6a30699189.png)

Error after composer update 

**How to reproduce**
Composer update a symfony 4

**Possible Solution**

https://github.com/symfony/translation/commit/9448b295d7c1006db91eb2187df0ea86ea9cf224#diff-098e9cedea5219a72206b689ed5567d5d2219b8e48150cab6423548271281862

**Comment by phprus** [comment] 2021-09-28 09:23
Similar issue on ``composer up`` execution:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Interface 'Symfony\Component\Translation\Formatter\MessageFormatterInterface' not found in /Users/phprus/.../vendor/symfony/translation/MessageFormatter.php on line 25
!!  PHP Fatal error:  Interface 'Symfony\Component\Translation\Formatter\MessageFormatterInterface' not found in /Users/phprus/.../vendor/symfony/translation/MessageFormatter.php on line 25
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#2270
!!    #message: """
!!      Attempted to load interface "MessageFormatterInterface" from namespace "Symfony\Component\Translation\Formatter".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/translation/MessageFormatter.php"
!!    #line: 25
!!  }
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by derrabus** [comment] 2021-09-28 09:28
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:28 UTC
Labels: Bug, Status: Needs Review
