### ISSUE TITLE
Resolve environment variable on getConfigTreeBuilder

### ISSUE THREAD

**Issue by botjaeger** [symfony/symfony#33358] opened 2019-08-27 10:51 UTC
Hi, I'm trying to "determine" the value of my environment variable inside another symfony bundle

so in my main project I have this:

parameters.yml
```
bi_stream_enabled: '%env(BI_STREAM_ENABLED)%'
```
and config.yml
```
some_package:
    bi_stream:
        enabled: "%bi_stream_enabled%"
```

where `BI_STREAM_ENABLED=true`

then on another symfony bundle (package)

App\DependencyInjection\Configuration.php
```
$rootNode
            ->children()
                ->arrayNode('bi_stream')->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->isRequired()
                            ->beforeNormalization()
                                ->ifString()
                                    ->then(function($v) { dump($v); die; return in_array($v, ['true', 1, '1']) ? true : false; })
                            ->end()
                        ->defaultFalse()
                        ->end()
           ....
```

I always get false because I'm getting this value 
`env_BI_STREAM_ENABLED_25b06e350b1a33613de8efc12ddb1fe2`

or this 

`env_bool_BI_STREAM_ENABLED_c1643fd79cbad73fa3172b243074fd04`

if my parameter was set to this

```
bi_stream_enabled: '%env(bool:BI_STREAM_ENABLED)%'
```

I know, I can just change the code in my "some other package" but there are old "legacy" projects uses it.

is there a way to workaround this?

**Comment by stof** [comment] 2019-08-27 15:24
The whole point of env variable is that they are not known at compile time (as they can change without rebuilding the container cache, by design of the system). So they are not usable in places needing the value of the config at build time (like in this case).

**Comment by botjaeger** [comment] 2019-08-28 07:45
alright, thank you.

**Comment by xabbuh** [comment] 2019-08-29 08:20
I am closing here as explain in https://github.com/symfony/symfony/issues/33358#issuecomment-525352590. Thank you for understanding.

**Closed by xabbuh** 2019-08-29 08:20 UTC
Labels: Config

**Comment by ragboyjr** [comment] 2019-10-01 19:29
I ran into a similar issue, it's not immediately obvious that you can't do something like

```yaml
framework:
  translator:
    enabled: '%env(bool:ENABLE_TRANSLATOR)%'
```

This type of config would work fine in php config since you can do `(bool) getenv('ENABLE_TRANSLATOR')`. Might be worth having some documentation describing that env vars won't be processed for certain types of config values in the yams config.

**Comment by ro0NL** [comment] 2019-10-02 06:22
@ragboyjr see #28896 :)
