### ISSUE TITLE
PhpUnit Bridge env variables set in phpunit.xml not available in parallel testsuites

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#28895] opened 2018-10-16 17:42 UTC
**Symfony version(s) affected**: 4.1.5

**Description**  

When I define env variables in the phpunit.xml.dist:

```xml
    <php>
        <env name="MY_ENV" value="Tests"/>
    </php>
```

the env are not available when giving a directory for run parallel testsuites:

**How to reproduce**  

```bash
bin/simple-phpunit path
```

```php
echo getenv('MY_ENV'); // false
```

The following works:

```bash
bin/simple-phpunit -c path/to/phpunit.xml.dist
```

```php
echo getenv('MY_ENV'); // returns 'Tests'
```

**EDIT** Repository to reproduce the error: https://github.com/alexander-schranz/symfony-phpunit-test

**Possible Solution**  

~~Currently not sure as I did not foundout how the parallel tests are done?~~ see https://github.com/symfony/symfony/pull/28995

**Comment by xabbuh** [comment] 2018-10-18 17:41
Same as #28726?

**Comment by alexander-schranz** [comment] 2018-10-19 09:40
@xabbuh not sure what I also found out that the `bootstrap` file is also not called. can you show me the place of the code where the logic is implemented for the parallel test suites?

**Comment by alexander-schranz** [comment] 2018-10-25 01:40
@xabbuh  It seems the simple phpunit seems to ignore many case when providing multiple phpunit configurations by folder so I did try to make a complete rewrite of the script with focus having multiple phpunit configuration the prototype looks like this now:

<details>
     <summary>PHPUnitBridge Rewrite</summary>

```php
#!/usr/bin/env php
<?php

error_reporting(-1);

global $argv, $argc;

$argv = isset($_SERVER['argv']) ? $_SERVER['argv'] : array();
$cmd = array_map('escapeshellarg', $argv);

unset($argv[0]);

$phpUnitConfigFiles = loadPhpConfigFiles();

$PHP_BINARY = defined('PHP_BINARY') ? PHP_BINARY : 'php';
$runningProcs = array();

foreach ($phpUnitConfigFiles as $phpUnitConfigFile) {
    $phpUnitVersion = getPhpUnitVersion($phpUnitConfigFile);
    removePhpUnitDependencyConflicts($phpUnitConfigFile, $phpUnitVersion);
    $phpUnit = getPhpUnit($phpUnitConfigFile, $phpUnitVersion);
    $folder = dirname($phpUnitConfigFile);

    $cmd = sprintf('%s %s -c %s %s --colors=always > %s/phpunit.stdout 2> %s/phpunit.stderr',
        escapeshellcmd($PHP_BINARY),
        escapeshellcmd($phpUnit),
        escapeshellarg($phpUnitConfigFile),
        implode(' ', array_map('escapeshellarg', $argv)),
        escapeshellarg($folder),
        escapeshellarg($folder)
    );

    if ($proc = proc_open($cmd, array(), $pipes)) {
        $runningProcs[$folder] = $proc;
    } else {
        $exit = 1;
        echo "\033[41mKO\033[0m $folder\n\n";
    }
}

exit(runProcs($runningProcs));

// ----------------------------------------------------------
// ----------------------------------------------------------
// ----------------------------------------------------------

function runProcs($runningProcs)
{
    $exit = 0;

    while ($runningProcs) {
        usleep(300000);
        $terminatedProcs = array();
        foreach ($runningProcs as $component => $proc) {
            $procStatus = proc_get_status($proc);
            if (!$procStatus['running']) {
                $terminatedProcs[$component] = $procStatus['exitcode'];
                unset($runningProcs[$component]);
                proc_close($proc);
            }
        }

        foreach ($terminatedProcs as $component => $procStatus) {
            foreach (array('out', 'err') as $file) {
                $file = "$component/phpunit.std$file";
                readfile($file);
                unlink($file);
            }

            // Fail on any individual component failures but ignore some error codes on Windows when APCu is enabled:
            // STATUS_STACK_BUFFER_OVERRUN (-1073740791/0xC0000409)
            // STATUS_ACCESS_VIOLATION (-1073741819/0xC0000005)
            // STATUS_HEAP_CORRUPTION (-1073740940/0xC0000374)
            if ($procStatus && ('\\' !== DIRECTORY_SEPARATOR || !extension_loaded('apcu') || !ini_get('apc.enable_cli') || !in_array($procStatus, array(-1073740791, -1073741819, -1073740940)))) {
                $exit = $procStatus;
                echo "\033[41mKO\033[0m $component\n\n";
            } else {
                echo "\033[32mOK\033[0m $component\n\n";
            }
        }
    }
    
    return $exit;
}

function getPhpUnit($phpUnitConfigFile, $phpUnitVersion)
{
    $PHPUNIT_DIR = getEnvVar($phpUnitConfigFile, 'SYMFONY_PHPUNIT_DIR', getRootDirectory().'/vendor/bin/.phpunit');

    $phpUnit = $PHPUNIT_DIR . '/phpunit-' . $phpUnitVersion . '/phpunit';

    if (!file_exists($phpUnit)) {
        loadPhpUnit($phpUnitVersion, $phpUnit);
    }

    return $phpUnit;
}

function loadPhpUnit($phpUnitVersion, $phpUnit)
{
    // TODO load php unit like

    outputError('Download PhpUnit is not yet implemented');

}

function removePhpUnitDependencyConflicts($phpUnitConfigFile, $phpUnitVersion)
{
    if ($SYMFONY_PHPUNIT_REMOVE = getEnvVar($phpUnitConfigFile, 'SYMFONY_PHPUNIT_REMOVE')) {
        // TODO remove composer conflicted dependencies
        outputError('The "SYMFONY_PHPUNIT_REMOVE" ENV variable is currently not supported');
    }
}

function getRootDirectory()
{
    static $root;

    if (!$root) {
        // Go the folders up until find a composer.json file
        $root = __DIR__;
        while (!file_exists($root.'/composer.json') || file_exists($root.'/DeprecationErrorHandler.php')) {
            if ($root === dirname($root)) {
                break;
            }
            $root = dirname($root);
        }
    }

    return $root;
}

function getPhpUnitVersion($phpUnitConfigFile)
{
    if (PHP_VERSION_ID >= 70200) {
        // PHPUnit 6 is required for PHP 7.2+
        $PHPUNIT_VERSION = getEnvVar($phpUnitConfigFile, 'SYMFONY_PHPUNIT_VERSION', '6.5');
    } elseif (PHP_VERSION_ID >= 50600) {
        // PHPUnit 4 does not support PHP 7
        $PHPUNIT_VERSION = getEnvVar($phpUnitConfigFile, 'SYMFONY_PHPUNIT_VERSION', '5.7');
    } else {
        // PHPUnit 5.1 requires PHP 5.6+
        $PHPUNIT_VERSION = '4.8';
    }

    return $PHPUNIT_VERSION;
}

function getEnvVar($phpUnitConfigFile, $name, $default = false)
{
    // Search first for given env variables
    if (false !== $value = getenv($name)) {
        return $value;
    }

    // Load phpunit config files and search for the env variable
    $phpunitConfig = new DomDocument();
    $phpunitConfig->load($phpUnitConfigFile);

    $var = new DOMXpath($phpunitConfig);
    foreach ($var->query('//php/env[@name="'.$name.'"]') as $var) {
        return $var->getAttribute('value');
    }

    return $default;
}

function loadPhpConfigFiles() {
    global $argv;

    static $phpUnitConfigFiles;

    if (!$phpUnitConfigFiles) {
        // Use configuration file current folder when no arguments given
        if (!isset($argv[1])) {
            if (file_exists('phpunit.xml')) {
                $phpUnitConfigFiles[] = realpath('phpunit.xml');
            } elseif (file_exists('phpunit.xml.dist')) {
                $phpUnitConfigFiles[] = realpath('phpunit.xml.dist');
            } else {
                outputError('No phpunit.xml.dist file found!');
            }

            return $phpUnitConfigFiles;
        }

        // Use config file when given it over -c argument
        if ('-c' === $argv[1]) {
            if (!isset($argv[2]) || !is_file($argv[2])) {
                outputError('Please provide a configuration file when using "-c" argument!');

                exit(1);
            }

            $phpUnitConfigFiles[] = realpath($argv[2]);

            unset($argv[1]); // $argv[1] should not provided to phpunit process
            unset($argv[2]); // $argv[2] should not provided to phpunit process

            return $phpUnitConfigFiles;
        }

        // Find all config file when folder given
        if (is_dir($argv[1])) {
            $finder = new RecursiveDirectoryIterator($argv[1], FilesystemIterator::KEY_AS_FILENAME | FilesystemIterator::UNIX_PATHS);
            $finder = new RecursiveIteratorIterator($finder);
            $finder->setMaxDepth(getenv('SYMFONY_PHPUNIT_MAX_DEPTH') ?: 3);

            foreach ($finder as $file => $fileInfo) {
                // Prefer phpunit.xml over phpunit.xml.dist file
                $folder = dirname($fileInfo->getPathname());
                if ('phpunit.xml.dist' === $file && !isset($phpUnitConfigFiles[$folder])) {
                    $phpUnitConfigFiles[$folder] = realpath($fileInfo->getPathname());
                } elseif ('phpunit.xml' === $file) {
                    $phpUnitConfigFiles[$folder] = realpath($fileInfo->getPathname());
                }
            }

            array_values($phpUnitConfigFiles);

            if (0 === count($phpUnitConfigFiles)) {
                outputError('No configuration files found in: ' . getcwd() . $argv[1]);
            }

            unset($argv[1]); // $argv[1] should not provided to phpunit process
        }
    }

    return $phpUnitConfigFiles;
}

function outputError($text, $exitCode = 1)
{
    echo '[41m' . $text . '[0m' . PHP_EOL;

    exit($exitCode);
}
```

</details>

This script fix the following problems:

 - [x] env variables not set
 - [x] and bootstrap script is called

Missing is currently:

 - [ ] Install and download of phpunit
 - [ ] Implement SYMFONY_PHPUNIT_REMOVE flag
 - [ ] Run Single PhpUnit script directly

**Comment by nicolas-grekas** [comment] 2018-11-09 18:19
I think https://github.com/symfony/recipes/pull/481 might fix that at the recipe level.

**Comment by alexander-schranz** [comment] 2018-11-10 20:15
@nicolas-grekas think your PR is focused on issues like #28726 not the parallel testcases issues I mention here as they can't be fixed by a recipe as the simple-phpunit bridge doesn't handle multiple phpunit.xml.dist.

Also want to mention I'm using the phpunit bridge in a library repository with multiple bundles so there is no symfony/dot-env component there just the simple-phpunit bridge and some other symfony components.

**Comment by nicolas-grekas** [comment] 2018-11-10 21:18
Using dotenv creates env vars that each parallel process can the read, isn't it? If adding dotenv solves the issue, do we need more? The simpler the better to me. What wouldn't work?

**Comment by alexander-schranz** [comment] 2018-11-12 08:46
@nicolas-grekas I don't think that this will work for a library with the following structure: https://github.com/alexander-schranz/symfony-phpunit-test where you have **different** configurations per test case.

The current simple-phpunit script does ignore phpunit env vars and also the bootstrap file is never called when a **folder** is given for **parallel**  test run thats the issue which can not be fixed by adding .env file.

**Comment by nicolas-grekas** [comment] 2019-04-12 15:15
Closing as not a bug, thanks.

**Closed by nicolas-grekas** 2019-04-12 15:15 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review
