### ISSUE TITLE
Broken tests in master: Could not scan for classes inside "tests/"

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#20032] opened 2016-09-23 10:27 UTC
It seems like some commit broke at least the master. If I run `./phpunit` it crashes after installing the packages with:
```
                                                                                              
  [RuntimeException]                                                                          
  Could not scan for classes inside "tests/" which does not appear to be a file nor a folder  
                                                                                              
```

I did a bit of digging and the only reference I found was a classmap option in composer.json from the zip file in the `.phpunit` directory. Sadly I was unable to fix it myself as it keeps overwriting everything.

ping @nicolas-grekas

**Comment by nicolas-grekas** [comment] 2016-09-23 10:47
where does this `tests/` string comes from?

**Comment by nicolas-grekas** [comment] 2016-09-23 10:48
Any backtrace?

**Comment by iltar** [comment] 2016-09-23 10:50
I can't summon a back-trace, I think it's invoked by a sub-process of the phpunit bash file that runs an include. I can't find `tests/` other than in a zip file where it's defined in the class-map options.

**Comment by stof** [comment] 2016-09-23 10:51
@iltar do you have a ``phpunit.xml`` file locally, replacing the ``phpunit.xml.dist`` shipped in the repo ?

**Comment by iltar** [comment] 2016-09-23 10:54
No, I have everything stock, I was reproducing this issue for @stampycode

**Comment by iltar** [comment] 2016-09-23 10:57
A bit more info:
![image](https://cloud.githubusercontent.com/assets/1754678/18783639/4628b4ae-818d-11e6-91dd-a95a143d5c9b.png)

**Comment by alcohol** [comment] 2016-09-23 11:23
I can get the test suite to run (though with a lot of failures) by modifying the following file:

**vendor/symfony/phpunit-bridge/bin/simple-phpunit**
``` patch
diff --git i/bin/simple-phpunit w/bin/simple-phpunit
index 14a9d1c..a8c1581 100755
--- i/bin/simple-phpunit
+++ w/bin/simple-phpunit
@@ -53,8 +53,8 @@ if (!file_exists("$PHPUNIT_DIR/phpunit-$PHPUNIT_VERSION/phpunit") || md5_file(__
     if (5.1 <= $PHPUNIT_VERSION && $PHPUNIT_VERSION < 5.4) {
         passthru("$COMPOSER require --no-update phpunit/phpunit-mock-objects \"~3.1.0\"");
     }
-    passthru("$COMPOSER require --dev --no-update symfony/phpunit-bridge \">=3.2@dev\"");
-    passthru("$COMPOSER install --prefer-dist --no-progress --ansi", $exit);
+    passthru("$COMPOSER require --no-update symfony/phpunit-bridge \">=3.2@dev\"");
+    passthru("$COMPOSER install --no-dev --prefer-dist --no-progress --ansi", $exit);
     if ($exit) {
         exit($exit);
     }
```

The zipfile downloaded by this binary does not contain the `tests/` directory since the .gitattributes exclude it from github zipballs. Yet the composer.json contains an `autoload-dev` definition which references this directory, and the binary runs a composer install (including dev) which results in a failing classmap generation.

**Comment by stof** [comment] 2016-09-23 11:25
autoload-dev is taken into account only for the root project (which is not downloaded by composer, except when using ``create-project``), so there is no reason for it to make any difference here unless a recent version of composer introduced a bug. what is your composer version ?

**Comment by nicolas-grekas** [comment] 2016-09-23 11:37
Did you try deleting the `.phpunit/` folder then try again?

**Comment by alcohol** [comment] 2016-09-23 11:39
@stof you are wrong. The composer install is run inside the extract phpunit directory, and directly affects the phpunit dependencies, so `autoload-dev` definitely is taken into account.

**Comment by iltar** [comment] 2016-09-23 11:40
My version: Composer version 1.2.1 2016-09-12 11:27:19

**Comment by alcohol** [comment] 2016-09-23 11:42
See https://github.com/symfony/phpunit-bridge/blob/master/bin/simple-phpunit#L46-L57 for relevant code that causes this issue.

**Comment by nicolas-grekas** [comment] 2016-09-23 11:48
So, composer is throuwing the exception? Can you add `-vvv` to the corresponding composer call?

**Comment by alcohol** [comment] 2016-09-23 11:52
I already explained why. See [this comment](https://github.com/symfony/symfony/issues/20032#issuecomment-249167161).

Symfony attempts to install the dependencies for the phpunit version it downloaded. However, the github zipball does not contain the `tests` directory because of the .gitattributes configuration. The install it tries though includes the dev dependencies, and thus also triggers the parsing of the `autoload-dev` configuration, which references the non-existant `tests` directory.

**Comment by alcohol** [comment] 2016-09-23 11:55
Probably relevant: https://github.com/sebastianbergmann/phpunit/issues/2300

**Comment by nicolas-grekas** [comment] 2016-09-23 11:56
certainly relevant, that's the trigger of all this :)
can you submit a PR then?

**Comment by iltar** [comment] 2016-09-23 11:57
My guess is a simply mkdir for /tests would be the easiest

**Comment by alcohol** [comment] 2016-09-23 11:58
Sure. On what branch should this be applied?

**Comment by nicolas-grekas** [comment] 2016-09-23 12:02
the lowest impacted :)
but shouldn't composer deal with this more gracefully?

**Comment by alcohol** [comment] 2016-09-23 12:06
I suppose that is debatable. Composer has always failed on this. This is not new. We could attempt to handle it more gracefully, but the problem is that a lot of users rarely read the warnings we output. And as this could effectively lead to a completely broken state of your environment, I feel a warning is inadequate.

**Comment by iltar** [comment] 2016-09-23 12:06
I think the proper fix would be that composer doesn't crash on this during the construction of the class-map autoloading and give an understandable error. Composer could give a neat warning in yellow though (just like the out-of-date) so that you are at least hinted of it.

**Comment by Seldaek** [comment] 2016-09-23 12:13
Going to install deps and generally mess around inside the vendor dir definitely voids the composer warranty as far as I am concerned. And besides yes as @alcohol mentioned above, people don't read warnings and then complain, that's why we fail hard on this because it is a clear misconfiguration of the package. Either make sure you create the tests dir, or install with --no-dev so that the autoload-dev is ignored, which really would be the correct option IMO as you are trying to **run** phpunit as far as I understand, and not **develop** it.

**Comment by alcohol** [comment] 2016-09-23 12:16
The latter was my solution also (`install --no-dev`), as displayed in the patch I included earlier in this thread.

**Comment by alcohol** [comment] 2016-09-23 12:28
Seems to only apply to the master branch, none of the previous branches had this binary yet.

**Comment by stampycode** [comment] 2016-09-23 12:56
This fix doesn't work for me, do I need to clear anything after I've pulled in this change?

I'm running `php ./phpunit symfony`

**Comment by nicolas-grekas** [comment] 2016-09-23 13:26
@stampycode try deleting the `.phpunit/` folder before running the command

**Comment by stampycode** [comment] 2016-09-23 13:31
@nicolas-grekas ... no dice.

**Comment by alcohol** [comment] 2016-09-23 13:34
That's because it hasn't been merged yet.

**Comment by nicolas-grekas** [comment] 2016-09-23 13:34
OK, that's because the simple-phpunit that is used is the one in `vendor/symfony/phpunit-bridge/bin/simple-phpunit`, *not* in `src/...`

**Comment by stampycode** [comment] 2016-09-23 13:35
@alcohol I applied the fix manually.

**Comment by alcohol** [comment] 2016-09-23 13:36
Yes but to what? ;-)

**Comment by stampycode** [comment] 2016-09-23 13:38
@alcohol - lol, as in #20034 - I did exactly what it said, to the file described in the PR. I' not new to this game ;)

**Comment by alcohol** [comment] 2016-09-23 13:39
To which file? Did you read the comment from @nicolas-grekas above?

**Comment by stampycode** [comment] 2016-09-23 13:44
Yeah I did - but as far as I'm concerned, I'm running the unit tests as described in [the documentation](http://symfony.com/doc/current/contributing/code/tests.html) - if that doesn't work, then that means either the documentation is wrong, or the tests are still broken...

And yes, I've deleted the `.phpunit` dir between runs.

**Comment by stampycode** [comment] 2016-09-23 13:46
Urgh. Ok it just started working... fml.

**Closed** 2016-09-23 14:51 UTC

**Comment by pkrupald024** [comment] 2018-12-18 06:17
> Did you try deleting the `.phpunit/` folder then try again?

Thanks

**Comment by MyWhitePages** [comment] 2024-01-22 07:03
1
