### ISSUE TITLE
Multiple Cache-Control headers sent in 4.0.0-BETA4

### ISSUE THREAD

**Issue by thejahweh** [symfony/symfony#24988] opened 2017-11-16 08:12 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-BETA4

This is since this commit: https://github.com/symfony/symfony/commit/cf4eb4602ace6c32523133b09feab79a53f8fa2d

Because of this change the `Cache-Control` header is sent always. As far as I know the `session.cache_limiter` off state is `''` and not `'0'`.
http://php.net/manual/en/function.session-cache-limiter.php

**Comment by sroze** [comment] 2017-11-16 08:28
> Setting the cache limiter to '' will turn off automatic sending of cache headers entirely.

From the PHP documentation perspective, it looks like you are correct.

**Comment by sroze** [comment] 2017-11-16 08:33
Actually, all you have to do, is to set the Symfony session storage `cache_limiter` configuration to `0` as described in the commit you've pointed out.

**Comment by nicolas-grekas** [comment] 2017-11-19 18:00
It's true that multiple Cache-Control headers are sent. Yet this is allowed by the HTTP spec so not a bug in itself.
What's the issue actually? Even a simple `session->has()` makes the HTTP resource uncacheable, so this it is actually accurate to send this header, isn't it?

**Comment by thejahweh** [comment] 2017-11-20 13:18
The issue is, why is this setting set to '0' and not ''?
Because default is '', you can't cache via http without setting the config like this:
```
# config/packages/framework.yaml
parameters:
    session.storage.options:
        cache_limiter: 0
```

**Comment by nicolas-grekas** [comment] 2017-11-21 09:53
> why is this setting set to '0' and not ''?

it's been always documented like that (this is a Symfony setting, not a PHP one, so we can derivate a bit from the PHP doc actually.)
is putting `0` fixing your issue?

**Comment by thejahweh** [comment] 2017-11-21 10:40
Yes it fixes it, but it looks more like a workaround to a strange default behavior.

**Comment by nicolas-grekas** [comment] 2017-11-21 11:04
OK, nice.
Sending the HTTP header by default is correct IMHO - not sending it is strange...
Closing as discussing what is "strange" is relative, and the discussion has resolved that using `0` allows meeting your expectation.

**Closed by nicolas-grekas** 2017-11-21 11:04 UTC
Labels: Bug, HttpFoundation, Status: Needs Review

**Comment by goetas** [comment] 2017-11-30 10:16
@xabbuh  can this be documented somehow? yesterday I've spent 3 hours to find how to set the `cache_limiter`... I did a compiler pass and did not know that `session.storage.options` parameter could help... (at the end was really frustrated)

documenting this config as example...
```
# config/packages/framework.yaml
parameters:
    session.storage.options:
        cache_limiter: 0
```

**Comment by xabbuh** [comment] 2017-11-30 10:17
@goetas Would you mind opening an issue in the docs repo (best search before if we already have one)?

**Comment by nicolas-grekas** [comment] 2017-11-30 10:19
Note that the doc should be clear that this is *not* recommended, as this will generate corrupted http caches.

**Comment by goetas** [comment] 2017-11-30 10:21
@nicolas-grekas yes I'm aware of it, I was using in mu particular case `private_no_expire`

**Comment by RonnieRocket147** [comment] 2017-12-15 17:27
I think there are serious implications here. I too spent 2 hours figuring out why Chrome and Safari are not respecting my Cache-Control settings.

In my Response I set the following to avoid 304 Not Modified requests/responses:

```
        $response
            ->setImmutable()
            ->setMaxAge(604800)
            ->setPublic()
```

However both Chrome and Safari kept on sending requests. After inspecting the headers I noticed two Cache-Control headers:

```
Cache-Control:max-age=0, private, must-revalidate
Cache-Control:immutable, max-age=604800, public
```

The first header is sent by Symfony, the second one because of my Response. But it seems the browsers do not discard the ```must-revalidate``` option and thus triggers ```If-Modified-Since``` requests with 304 Not Modified responses.

After manually commenting out the Symfony header it all worked out fine.

If I change ```cache_limiter``` parameter it will apply to all my responses but I want to disable it only for this specific response where I need to control the Cache-Control headers.

Any ideas?

**Comment by nicolas-grekas** [comment] 2017-12-15 17:29
See #25448, it contains everything on the topic.

**Comment by RonnieRocket147** [comment] 2017-12-15 17:39
Thanks for pointing my to that issue.

```
If you want to opt-out from sending the header, you need to set the 'cache_limiter' option to '0'.
```

This is want I want BUT only for this specific Response (otherwise browsers will not cache to response as intended). For all other responses the current Symfony default (```cache_limiter=''```) is perfectly fine.

How to accomplish that?

**Comment by nicolas-grekas** [comment] 2017-12-15 17:44
Not sure you can.
But instead of looking for that, I'd suggest to look *why* is the session used on that page.

**Comment by goetas** [comment] 2017-12-15 17:45
> This is want I want BUT only for this specific Response (otherwise browsers will not cache to response as intended)

I also had the same need, it was per-url/path

(serving cacheable images only to authorized users was the case...)

**Comment by RonnieRocket147** [comment] 2017-12-15 17:58
> (serving cacheable images only to authorized users was the case...)

Same here, authorized users may only access the media file. How did you solve it?

**Comment by RonnieRocket147** [comment] 2017-12-16 09:51
I found a work-around for my use-case. I added
```
header('Cache-Control: immutable, max-age=604800, public', true);
```
before returning the response, which overwrites the Symfony ```header()``` for that specific response only.

I really believe Symfony should avoud using the ```header()``` function and place the headers in the Response instead so it can be overwritten.

**Comment by nicolas-grekas** [comment] 2017-12-16 10:19
I'm sorry but I still fail to understand. As soon as a resource is public, it can be served directly to next users, bypassing any authentication.
This conflicts with the fact that the session is read, which means that the resource is possibly different for some/any users.
So again, why are you accessing the session in the first place to render immutable resources?
Hacking the CC header looks like a workaround that hides a deeper problem on your side...

**Comment by RonnieRocket147** [comment] 2017-12-16 10:31
```public``` indicates the content may be cached by proxy servers, which is what I want to further reduce traffic. It may as well be ``private```, that is not the real issue here.

The session is needed because these media files may only be served to authenticated users.

**Comment by nicolas-grekas** [comment] 2017-12-16 10:47
> The session is needed because these static media files may only be served to authenticated users.

This makes no sense to me. As soon as a resource is served by a reverse proxy- which "public" allows, it cannot be authenticated anymore. How do you resolve that?

**Comment by RonnieRocket147** [comment] 2017-12-16 10:54
So I change ```public``` to ```private``` which probably makes more sense, I agree with you.

Then my original point still stands: 304's can't be avoided by the default Symfony ```header()``` usage without resorting to ```cache_limiter='0'``` with all its implications or my ```header()``` overwrite hack. 

Do you understand my issue here?

**Comment by nicolas-grekas** [comment] 2017-12-16 10:56
I understand your issue, but I'm challenging its reality. We just agreed that private is correct and public is buggy.
Now revalidate: how do you ensure that the authenticated resource is not reused after logging out?

**Comment by RonnieRocket147** [comment] 2017-12-16 11:18
I can't ensure that so it can be reused even if the user is logged out. This is no different than the ```must-revalidate``` as per RFC before it becomes stale:

```If the response includes the "must-revalidate" cache-control directive, the cache MAY use that response in replying to a subsequent request```

**Comment by goetas** [comment] 2017-12-16 17:09
@nicolas-grekas as explained [here](https://github.com/symfony/symfony-docs/issues/8784#issuecomment-348151883) this is one of many thickets dealing with a similar issue...
 all ot them pointing to the fact that symfony is using the `header` function instead of the  `Response` object.

Using the `header` function forces us to use also that function to override the symfony's assumptions on how sessions should be treated... there will be always a case not covered.

**Comment by nicolas-grekas** [comment] 2017-12-16 17:42
@goetas you're right, that's how it should be. That's not how it works today, so PR welcome. I'm not in a hurry to fix this myself, especially as it looks like getting correct CC headers is hard/easy to get wrong (see above.) By providing full flexibility, a new solution should also provide guidance to correct semantic.

**Comment by goetas** [comment] 2017-12-16 18:21
@nicolas-grekas Great to hear! Was interested to know what is the general direction!

**Comment by mvrhov** [comment] 2017-12-16 20:02
Why does `cache_limiter` require a special parameter and doesn't use the same behavior as other parameters e.g.

```yaml
framework:
    session:
        gc_maxlifetime: 7200
        save_path:      '%kernel.root_dir%/var/session/'
        name:           'sid'
        cache_limiter:  0
```

**Comment by Toflar** [comment] 2017-12-22 13:42
Although I agree with @nicolas-grekas that if you start a session a response should be considered to be private, the implementation like it is now is inconsistent.

I think we must always suppress the `NativeSessionStorage` from generating any headers by default. Otherwise the `Cache-Control` header never makes it to the proper Symfony HttpFoundation `Response` object and is thus missed by `kernel.response` listeners and for example the Symfony `HttpCache`. So depending on whether you use Symfony's `HttpCache` or Varnish as a reverse proxy, caching would be handled differently. Varnish would consider the response to be private. HttpCache would not. That's inconsistent.

To fix this properly, imho we should do the following:

* Always prevent the `NativeSessionStorage` from generating headers by default.
* Adjust the `SaveSessionListener` to not only store the session when started but also setting the response to `private` when started.

This would result in a consistent behaviour no matter what session storage or reverse proxy you use.
