### ISSUE TITLE
Different objects can be of the same instance when coming from the Cache

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#38440] opened 2020-10-06 15:14 UTC
**Symfony version(s) affected**: 4.4.15 and more 

**Description**  
I've chatted with @nicolas-grekas on Slack about a possible issue with the `DefaultMarshaller` when using [`igbinary`](https://github.com/igbinary/igbinary) and the Symfony Cache. 
I've tried to create the smallest possible reproducer (a new test in `DefaultMarshallerTest` or in `AdapterTestCase`) but it wasn't possible. The reproducer use the Symfony Cache (+ Marshaller) and Mailer components.

**How to reproduce**  
Please see https://github.com/Kocal/symfony-marshaller-or-cache-issue, everything is explained in the README.

Comment/uncomment the `var_dump($item)` and you will see the last `var_dump()` outputs will change.

**Possible Solution**  
To fix this issue in my app, I had to disable the usage of igbinary with the following service configuration:
```
cache.default_marshaller:
    class: Symfony\Component\Cache\Marshaller\DefaultMarshaller
    arguments:
        $useIgbinarySerialize: false
```

**Additional context**  
I'm using PHP 7.4.10 with igbinary 3.1.5.

**Comment by Nyholm** [comment] 2020-10-06 16:05
Thank you for this issue. 

I cloned your repo, ran composer update and the reproducer script. I can confirm that I see the bug when using the igbinary extension. But I cannot reproduce when XDebug is enabled. 

I tried to make a smaller scripts but the following works: 

```php
class Outer {
    private $inners = [];
    public function addInner(Inner $a) {
        $this->inners[] = $a;
    }

    public function getInners() {
        return $this->inners;
    }
}

class Inner {
    private $name;
    public function __construct($name){
        $this->name = $name;
    }
}

$outer = new Outer();
$outer->addInner(new Inner('A'));
$outer->addInner(new Inner('B'));

$cache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('message_events');
$cacheKey = 'my_key';
$item = $cache->getItem($cacheKey);
$item->set($outer);

var_dump($item); // This will trigger the bug

$cache->save($item);
unset($cache, $item);

$cache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('message_events');
$item = $cache->getItem($cacheKey);

$inners = $item->get()->getInners();
var_dump('headers', $inners[0] === $inners[1]);
```

Im not sure there is a problem in the cache component, could it be a problem in the igbinary extension?

**Comment by nicolas-grekas** [comment] 2020-10-06 17:14
I removed the cache component in https://github.com/Kocal/symfony-marshaller-or-cache-issue/pull/1
That's definitely an issue with igbinary.

I'm therefor closing this issue, but please do open one on igbinary and link it here, I'd like to track the resolution of this data-corruption issue.

**Closed as completed by nicolas-grekas** 2020-10-06 17:14 UTC
Labels: Bug, Status: Needs Review

**Comment by Kocal** [comment] 2020-10-06 18:56
I've opened an issue at https://github.com/igbinary/igbinary/issues/287.

**Comment by Kocal** [comment] 2020-10-07 05:02
Will be fixed by https://github.com/igbinary/igbinary/pull/289

**Comment by tristanbes** [comment] 2020-10-07 09:00
Shouldn't igbinary be disabled in the `DefaultMarshaller` when running `>=PHP7.4` ? since it can take some times for this patch to land in the userland ?

Right now, leaving the responsability to users to disable it via: 

```yml
cache.default_marshaller:
    class: Symfony\Component\Cache\Marshaller\DefaultMarshaller
    arguments:
        $useIgbinarySerialize: false
```

seems risky for non-experienced developpers to find this issue and apply this patch.

**Comment by nicolas-grekas** [comment] 2020-10-07 09:18
@tristanbes yes, see #38456
