### ISSUE TITLE
Using ESI causes infinite recursion when used with IIS rewrite module

### ISSUE THREAD

**Issue by myqa** [symfony/symfony#26405] opened 2018-03-05 12:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4 (and older)

When using IIS as reverse proxy and e.g. Varnish as a Cache Server with ESI enabled Symfony falls into infinite recoursion.
It is caused by `HTTP_X_ORIGINAL_URL` send by Varnish with value from original (not ESI) request.

This bug is similar to [6923](https://github.com/symfony/symfony/issues/6923) but the source of header is outside of Symfony

**Comment by Simperfit** [comment] 2018-03-05 17:08
Hi @myqa, thanks for the report, could you please provide a reproducer ?

**Comment by myqa** [comment] 2018-03-06 12:44
The simplest code demonstraiting problem:
Controller:
```
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class TestController
{
    /**
     * @Route(name="esi_test", path="/test")
     * @Template
     */
    public function indexAction()
    {
        return [];
    }

    /**
     * @Template
     */
    public function esiAction()
    {
        return [];
    }
}
```

index.html.twig
```
Index action!<br>
{{ render_esi(controller('TestControllerService:esiAction')) }}
```

esi.html.twig
```
ESI action!
```

Main request sent by Varnish to WebServer:
```
GET /app_dev.php/test HTTP/1.1
Host: localhost
Surrogate-Capability: abc=ESI/1.0
X-Original_Url: /app_dev.php/test
```
Request object::
```
Request {#13
  +attributes: ParameterBag {#16
    #parameters: array:5 [
      "_controller" => "App\TestController::indexAction"
      "_route" => "esi_test"
      "_route_params" => []
      "_firewall_context" => "security.firewall.map.context.main"
      "_template" => Template {#136070
      }
    ]
  }
  +server: ServerBag {#19
    #parameters: array:24 [
      "REMOTE_ADDR" => "127.0.0.1"
      "REMOTE_PORT" => "62529"
      "SERVER_PROTOCOL" => "HTTP/1.1"
      "SERVER_NAME" => "localhost"
      "SERVER_PORT" => "80"
      "REQUEST_URI" => "/app_dev.php/test"
      "REQUEST_METHOD" => "GET"
      "SCRIPT_NAME" => "/app_dev.php"
      "PATH_INFO" => "/test"
      "PHP_SELF" => "/app_dev.php/test"
      "HTTP_SURROGATE_CAPABILITY" => "abc=ESI/1.0"
      "HTTP_CACHE_CONTROL" => "no-cache"
      "HTTP_ACCEPT" => "*/*"
      "HTTP_HOST" => "localhost"
      "HTTP_ACCEPT_ENCODING" => "gzip, deflate"
      "HTTP_CONNECTION" => "keep-alive"
    ]
  }
  +headers: HeaderBag {#20
    #headers: array:10 [
      "surrogate-capability" => array:1 [
        0 => "abc=ESI/1.0"
      ]
      "cache-control" => array:1 [
        0 => "no-cache"
      ]
      "accept" => array:1 [
        0 => "*/*"
      ]
      "host" => array:1 [
        0 => "localhost"
      ]
      "accept-encoding" => array:1 [
        0 => "gzip, deflate"
      ]
      "connection" => array:1 [
        0 => "keep-alive"
      ]
    ]
    #cacheControl: array:1 [
      "no-cache" => true
    ]
  }
  #content: null
  #languages: null
  #charsets: null
  #encodings: null
  #acceptableContentTypes: null
  #pathInfo: "/test"
  #requestUri: "/app_dev.php/test"
  #baseUrl: "/app_dev.php"
  #basePath: null
  #method: "GET"
  #format: null
  #locale: null
  #defaultLocale: "pl"
  -isHostValid: true
  -isForwardedValid: true
  basePath: ""
  format: "html"
}
```
Response:
```
Index action!
<br>
<esi:include src="/app_dev.php/_fragment?_path=_format%3Dhtml%26_locale%3Dpl%26_controller%3DTestControllerService%253AesiAction&_hash=%2FSeUTRw1H4ymH1M78HPYoLwl%2BA9Zsx6yAoy%2Bn7PRm64%3D" />
```

Until this  moment everything is ok.
ESI request send by Varnish
```
GET /app_dev.php/_fragment?_path=_format%3Dhtml%26_locale%3Dpl%26_controller%3DTestControllerService%253AesiAction&amp;_hash=%2FSeUTRw1H4ymH1M78HPYoLwl%2BA9Zsx6yAoy%2Bn7PRm64%3D HTTP/1.1
Host: localhost
Surrogate-Capability: abc=ESI/1.0
X-Original-Url: /app_dev.php/test
```
Request object:
```
Request {#13
  +attributes: ParameterBag {#16
    #parameters: array:5 [
      "_controller" => "App\TestController::indexAction"
      "_route" => "esi_test"
      "_route_params" => []
      "_firewall_context" => "security.firewall.map.context.main"
      "_template" => Template {#2117
      }
    ]
  }
  +query: ParameterBag {#15
    #parameters: array:2 [
      "_path" => "_format=html&_locale=pl&_controller=TestControllerService%3AesiAction"
      "_hash" => "/SeUTRw1H4ymH1M78HPYoLwl+A9Zsx6yAoy+n7PRm64="
    ]
  }
  +server: ServerBag {#19
    #parameters: array:25 [
      "REMOTE_ADDR" => "127.0.0.1"
      "REMOTE_PORT" => "62557"
      "SERVER_PROTOCOL" => "HTTP/1.1"
      "SERVER_NAME" => "localhost"
      "SERVER_PORT" => "80"
      "REQUEST_URI" => "/app_dev.php/test"
      "REQUEST_METHOD" => "GET"
      "SCRIPT_NAME" => "/app_dev.php"
      "PATH_INFO" => "/_fragment"
      "PHP_SELF" => "/app_dev.php/_fragment"
      "QUERY_STRING" => "_path=_format%3Dhtml%26_locale%3Dpl%26_controller%3DTestControllerService%253AesiAction&_hash=%2FSeUTRw1H4ymH1M78HPYoLwl%2BA9Zsx6yAoy%2Bn7PRm64%3D"
      "HTTP_SURROGATE_CAPABILITY" => "abc=ESI/1.0"
      "HTTP_CACHE_CONTROL" => "no-cache"
      "HTTP_ACCEPT" => "*/*"
      "HTTP_HOST" => "localhost"
      "HTTP_ACCEPT_ENCODING" => "gzip, deflate"
      "HTTP_CONNECTION" => "keep-alive"
    ]
  }
  +headers: HeaderBag {#20
    #headers: array:10 [
      "surrogate-capability" => array:1 [
        0 => "abc=ESI/1.0"
      ]
      "cache-control" => array:1 [
        0 => "no-cache"
      ]
      "accept" => array:1 [
        0 => "*/*"
      ]
      "host" => array:1 [
        0 => "localhost"
      ]
      "accept-encoding" => array:1 [
        0 => "gzip, deflate"
      ]
      "connection" => array:1 [
        0 => "keep-alive"
      ]
    ]
    #cacheControl: array:1 [
      "no-cache" => true
    ]
  }
  #content: null
  #languages: null
  #charsets: null
  #encodings: null
  #acceptableContentTypes: null
  #pathInfo: "/test"                                  <-- this is incorrect!
  #requestUri: "/app_dev.php/test"         <-- this is incorrect!
  #baseUrl: "/app_dev.php"
  #basePath: null
  #method: "GET"
  #format: null
  #locale: null
  #defaultLocale: "pl"
  -isHostValid: true
  -isForwardedValid: true
  basePath: ""
  format: "html"
}
```
And finally returned response (which is incorrect, because of additional header request wasn't interpreted as fragment request)
```
Index action!
<br>
<esi:include src="/app_dev.php/_fragment?_path=_format%3Dhtml%26_locale%3Dpl%26_controller%3DTestControllerService%253AesiAction&_hash=%2FSeUTRw1H4ymH1M78HPYoLwl%2BA9Zsx6yAoy%2Bn7PRm64%3D" />
```

I hope those informations are enough to reproduce problem

**Comment by stof** [comment] 2018-03-06 13:03
Could it be that `HTTP_X_ORIGINAL_URL` is set by IIS, and so that Varnish considers it as a normal request header and forwards it ? Can you check what the *incoming* request is at the level of Varnish ?

**Comment by myqa** [comment] 2018-03-06 13:55
Yes it is set by IIS. This is part of original varnish logs:
```
*   << BeReq    >> 3
-   Begin          bereq 2 pass
-   Timestamp      Start: 1520343660.627366 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Cache-Control: max-age=0
-   BereqHeader    Host: localhost
-   BereqHeader    Max-Forwards: 10
-   BereqHeader    Upgrade-Insecure-Requests: 1
-   BereqHeader    X-ORIGINAL-HOST: localhost
-   BereqHeader    X-Original-URL: /
-   BereqHeader    X-Forwarded-Host: localhost
-   BereqHeader    X-Forwarded-Proto: https
-   BereqHeader    X-Forwarded-Port: 443
-   BereqHeader    X-Forwarded-For: xxxxxxxxxxxxxxxxx
-   BereqHeader    Surrogate-Capability: abc=ESI/1.0
-   BereqHeader    X-Varnish: 3
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   Timestamp      Bereq: 1520343660.627868 0.000502 0.000502
-   Timestamp      Beresp: 1520343660.696955 0.069589 0.069087
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Date: Tue, 06 Mar 2018 13:41:00 GMT
-   BerespHeader   Cache-Control: max-age=0, must-revalidate, private
-   BerespHeader   Surrogate-Control: content="ESI/1.0"
-   BerespHeader   Vary: Accept-Encoding
-   BerespHeader   Content-Encoding: gzip
-   BerespHeader   Content-Length: 3443
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   VCL_call       BACKEND_RESPONSE
-   BerespUnset    Surrogate-Control: content="ESI/1.0"
-   BerespHeader   X-Varnish-Cacheable: NO: Not Cacheable
-   VCL_return     deliver
-   BerespUnset    Content-Encoding: gzip
-   BerespUnset    Content-Length: 3443
-   BerespHeader   Content-Encoding: gzip
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Date: Tue, 06 Mar 2018 13:41:00 GMT
-   ObjHeader      Cache-Control: max-age=0, must-revalidate, private
-   ObjHeader      Vary: Accept-Encoding
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      X-Varnish-Cacheable: NO: Not Cacheable
-   ObjHeader      Content-Encoding: gzip
-   Fetch_Body     3 length -
-   Gzip           G F E 11618 4454 80 35552 35562
-   Gzip           U F - 3443 11618 80 80 27476
-   Timestamp      BerespBody: 1520343660.698190 0.070824 0.001235
-   Length         4454
-   BereqAcct      915 0 915 351 0 351
-   End

*   << BeReq    >> 5
-   Begin          bereq 4 fetch
-   Timestamp      Start: 1520343660.698431 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /_fragment?_path=_format%3Dhtml%26_locale%3Dpl%26_controller%3DTestControllerService%253AesiAction&amp;_hash=%2FSeUTRw1H4ymH1M78HPYoLwl%2BA9Zsx6yAoy%2Bn7PRm64%3D
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Host: localhost
-   BereqHeader    Max-Forwards: 10
-   BereqHeader    Upgrade-Insecure-Requests: 1
-   BereqHeader    X-ORIGINAL-HOST: localhost
-   BereqHeader    X-Original-URL: /
-   BereqHeader    X-Forwarded-Host: localhost
-   BereqHeader    X-Forwarded-Proto: https
-   BereqHeader    X-Forwarded-Port: 443
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Forwarded-For: xxxxxxxxxxxxxxxxx
-   BereqHeader    Surrogate-Capability: abc=ESI/1.0
-   BereqHeader    X-Varnish: 5
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   Timestamp      Bereq: 1520343660.698500 0.000068 0.000068
-   Timestamp      Beresp: 1520343660.753536 0.055104 0.055036
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Date: Tue, 06 Mar 2018 13:41:00 GMT
-   BerespHeader   Cache-Control: max-age=0, must-revalidate, private
-   BerespHeader   X-Frame-Options: sameorigin
-   BerespHeader   Surrogate-Control: content="ESI/1.0"
-   BerespHeader   Vary: Accept-Encoding
-   BerespHeader   Content-Encoding: gzip
-   BerespHeader   Content-Length: 3443
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   TTL            RFC 0 10 0 1520343661 1520343661 1520343660 0 0
-   VCL_call       BACKEND_RESPONSE
-   BerespUnset    Surrogate-Control: content="ESI/1.0"
-   BerespHeader   X-Varnish-Cacheable: NO: Not Cacheable
-   TTL            VCL 120 10 0 1520343661
-   VCL_return     deliver
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Date: Tue, 06 Mar 2018 13:41:00 GMT
-   ObjHeader      Cache-Control: max-age=0, must-revalidate, private
-   ObjHeader      Vary: Accept-Encoding
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      X-Varnish-Cacheable: NO: Not Cacheable
-   ObjHeader      Content-Encoding: gzip
-   Fetch_Body     3 length -
-   Gzip           G F E 11618 4454 80 35552 35562
-   Gzip           U F - 3443 11618 80 80 27476
-   Timestamp      BerespBody: 1520343660.754848 0.056417 0.001312
-   Length         4454
-   BereqAcct      1006 0 1006 413 0 413
-   End
```

**Comment by Simperfit** [comment] 2019-04-18 06:56
@myqa It will be hard for me to reproduce since I don't use IIS at all and I don't have any env to try this, could you try to fix it or maybe provide a docker setup to try this ?

**Comment by fabpot** [comment] 2020-08-17 04:35
Closing as there is no more feedback.

**Closed by fabpot** 2020-08-17 04:35 UTC
Labels: Bug, HttpKernel, Status: Needs Review
