### ISSUE TITLE
[DoctrineBridge] Possible event listener related problem and BC break in latest 5.x branch

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#40268] opened 2021-02-21 15:47 UTC
**Symfony version(s) affected**: 5.x@d24315fe3174ae9f7fd3bbcdc864825ac75c8ceb

**Description**  
Since https://github.com/symfony/doctrine-bridge/commit/d24315fe3174ae9f7fd3bbcdc864825ac75c8ceb, doctrine-bundle unit tests are failing with following:

```
❯ ./vendor/bin/phpunit
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing
....................................................S..........  63 / 253 ( 24%)
............................................................... 126 / 253 ( 49%)
...........................F................................... 189 / 253 ( 74%)
...........F................................................... 252 / 253 ( 99%)
.                                                               253 / 253 (100%)

Time: 00:08.382, Memory: 54.50 MB

There were 2 failures:

1) Doctrine\Bundle\DoctrineBundle\Tests\DependencyInjection\XmlDoctrineExtensionTest::testAttachEntityListenersTwoConnections
Method 'addEventListener' is expected to be called once, definition does not contain a call though.

/Users/gabriel.ostrolucky/Documents/DoctrineBundle/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1265
/Users/gabriel.ostrolucky/Documents/DoctrineBundle/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1024

2) Doctrine\Bundle\DoctrineBundle\Tests\DependencyInjection\YamlDoctrineExtensionTest::testAttachEntityListenersTwoConnections
Method 'addEventListener' is expected to be called once, definition does not contain a call though.

/Users/gabriel.ostrolucky/Documents/DoctrineBundle/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1265
/Users/gabriel.ostrolucky/Documents/DoctrineBundle/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1024

FAILURES!
Tests: 253, Assertions: 1002, Failures: 2, Skipped: 1.
```

**How to reproduce**  
```
git clone git@github.com:doctrine/DoctrineBundle.git
cd DoctrineBundle
composer install
./vendor/bin/phpunit
```

**Issue does not happen on 5.2 branch**. So perhaps some wrongly resolved merge conflict?

**Comment by jderusse** [comment] 2021-02-21 21:17
Closing this issue, has this is not a bug in Symfony.

The test you are pointing is wrong: it expect the Definition to contains a call to the method `addEventListener` which is not the case since https://github.com/symfony/symfony/pull/40042:

The list of eventListeners are injected in the EventManager's constructor. The call to the method `addEventListener` will be performed in a lazy way at runtime (and not by the DiC as expected by the Doctrine's test.)

**Closed as completed by jderusse** 2021-02-21 21:17 UTC
Labels: Bug, Status: Needs Review, DoctrineBridge
