### ISSUE TITLE
[Container] [Cache] [PhpDumper] Reproducible build not working when set kernel.container_build_time

### ISSUE THREAD

**Issue by polukes** [symfony/symfony#27804] opened 2018-07-02 12:39 UTC
**Symfony version(s) affected**: 4.1.1

**Description**  
As described in https://symfony.com/blog/new-in-symfony-reproducible-builds Symfony should allow to create static compiled cache. In many cases it works. However it doesn't work when we change global parameter. In `PhpDumper` `$files` variable will change, the hash also will be different, so folder name `Container{hash}` will change as well.

**How to reproduce**  
1. In your App Kernel set `$container->setParameter('kernel.container_build_time', 1);`.
2. Check /var/cache/{env}/Container{hash} folder.
3. Change any of global parameter (in parameters.yml or similar).
4. Clear cache (bin/console cache:clear or just remove cache folder).
5. Check /var/cache/{env}/Container{hash} folder. The path will be different.

**Possible Solution**  
In my closed pull request: https://github.com/symfony/dependency-injection/pull/17

**Comment by stof** [comment] 2018-07-02 12:59
that's totally expected. Changing parameters produces a *different* cache, so its hash won't do the same.

Reproducible builds mean that the *same* input always produces the same output. If you change the input, you cannot expect getting the same output.

**Comment by polukes** [comment] 2018-07-02 13:06
Yes, but if we have parameters loaded from DB and we clear cache we have problem with different folder names. Also if we just remove cache folder we got Internal Server Error in first response.
We have many nodes and did not work correctly. We need static cache path for all files also if parameters was changed.

**Comment by stof** [comment] 2018-07-02 14:11
@polukes DIC parameters must be known at compile-time. If you have config in the DB, don't copy them in the DIC parameters, as their value will be known at runtime only (unless you clear the cache everytime you change the DB).

**Comment by nicolas-grekas** [comment] 2018-07-02 14:17
If you need dynamic value to configure the container, you should use environment variables I suppose.
Thanks to env processors, you should even be able to populate them from the DB, see
https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables

I'm closing here since there is not bug to keep track of.

**Closed by nicolas-grekas** 2018-07-02 14:17 UTC
