### ISSUE TITLE
HTTPClient multipart/form-data request issues

### ISSUE THREAD

**Issue by n3o77** [symfony/symfony#35443] opened 2020-01-22 20:12 UTC
**Symfony version(s) affected**: 4.4.3

**Description**  
I'm communicating with an API and ran in some problems when I tried to upload files with the HTTPClient. 

**How to reproduce**  
Unfortunately it's not a public API so i can't provide the exact examples but i'm basically doing what's described in the docs:

```php
$fields = [
    'file' => new DataPart($csv, 'test.csv', 'text/csv'),
];

$formData = new FormDataPart($fields);

$httpClient->request('POST', '/', ['body' => $formData->bodyToString()]);
```

**Possible Solution**  
The problem is because in the data part the content-type has an additional token `name=file` (see below). At least if i remove it from the request everything works fine. I was looking in the rfc7233 and rfc7578 spec but couldn't really find anything about this, but not sure if i'm just missing it or looking in the wrong spec.

```
--_=_symfony_1579722514_dac69a39ca05c454f2a6375249ce7614_=_
Content-Type: text/csv; name=file
Content-Transfer-Encoding: 8bit
Content-Disposition: form-data; name=file; filename=test.csv

.... data ...

--_=_symfony_1579722514_dac69a39ca05c454f2a6375249ce7614_=_--
```

The second issue I ran into was that the boundary in the request headers is enclosed in quotes, which also causes propblems. Again, couldn't really find something about that but it's not in the request when i'm just using curl in the terminal.

Doesn't work:
```
Content-Type: multipart/form-data; boundary="_=_symfony_1579723754_2b148207ef318a96c271a8e5bd56b206_=_"
```

Works:
```
Content-Type: multipart/form-data; boundary=_=_symfony_1579723754_2b148207ef318a96c271a8e5bd56b206_=_
```

Are these problems in the symfony mime client or in the API i'm working with?

**Comment by martinbertinat** [comment] 2020-01-28 01:23
Hi @n3o77 did you find a solution? I'm dealing with the same problem

**Comment by n3o77** [comment] 2020-01-28 12:12
@martinbertinat my quick and dirty solution was just a preg_replace on the result of $formData->bodyToString().

I actually think it's a bug in the mime component which needs to be fixed. But i'm not sure if that's only an issue with HTTP requests as this component is also used for emails and maybe other stuff as well. I'm not very familiar with a lot of these specs so i hoped that someone who worked on the mime component could chime in if this was intended or not. I'm happy to create a PR to fix it.

**Comment by nicolas-grekas** [comment] 2020-02-02 17:33
Up for a PR anyone, with tests?

**Comment by n3o77** [comment] 2020-02-03 14:15
Regarding the boundary (defined [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Part/AbstractMultipartPart.php#L94)), because of the `=` it will be put between quotes but only in the http header and not in the multipart/form-data headers which is probably why it doesn't work.

I'm wondering if that format generally makes sense as it also leaks the client used to make the request. For reference how curl, firefox, chrome and safari handle the boundary:

Curl: `------------------------06c924ca23bff054`
Firefox: `-----------------------------67514980420866487271897199179`
Chrome / Safari: `------WebKitFormBoundaryrGJIVv8vJ6wOwAST`

Because of this i would suggest doing something similar like `---------------'.time().bin2hex(random_bytes(16)).'` 

And maybe even have a public setter to overwrite the value. Any feedback would be nice, if others agree i'm happy to create a PR.

**Comment by emnsen** [comment] 2020-02-11 13:19
Is there any improvement regarding this problem?

**Comment by nicolas-grekas** [comment] 2020-02-26 11:36
@emnsen up for a PR? @n3o77 up for another try? anyone else?

**Comment by nicolas-grekas** [comment] 2020-03-12 10:10
@n3o77 which server do you use, that parses the MIME parts on your side and fails in this situation?

**Comment by n3o77** [comment] 2020-03-12 14:59
@nicolas-grekas unfortunately not a server available to the public. I also don't have any specs about the software used etc..

**Comment by wiser** [comment] 2020-03-17 16:23
Hi, I've the same issue on several products that expose HTTP APIs : Dalim Twist (written in Java) Marklogic (written in C I guess...?).
None of them accept HTTP multipart/form-data file upload using HttpClient and FormDataPart libs.
All is ok with curl and/or PostMan so I need to play the 7 differences game to find out the explanation.

**Comment by nicolas-grekas** [comment] 2020-03-17 16:26
@wiser then can you please confirm the linked patch fixes the issue for you too?

**Comment by wiser** [comment] 2020-03-17 17:47
@nicolas-grekas Unfortunately not :(
According to my tests, the problem is not relies to Symfony libs but to the 2 HTTP APIs that do not manage multipart/form-data requests when datapart names are serialized as "token" (without quotes). If I suround each part name by quotes it seems that request is parsed  correctly.
I will check this strange behaviour and confirm it before trying to discuss with products editors.

**Comment by nicolas-grekas** [comment] 2020-03-17 17:48
OK thanks. Then please open a separate issue as this one is closed, and your issue looks different.

**Comment by n3o77** [comment] 2020-03-17 17:53
@nicolas-grekas the PR does **not** solve this issue at all. The inital issue described from me is not related to the boundary header but to the `name` property in the `Content-Type` form data part.

**Comment by nicolas-grekas** [comment] 2020-03-17 17:58
You described there was an issue with the boundary, and it's fixed now, isn't it?
But we missed the 1st part, which suggests we should always add double quotes around names, is that correct? Up for a PR?

**Comment by n3o77** [comment] 2020-03-17 18:06
@nicolas-grekas  The issue with the name in the content-type is that it's not in the http spec. No browser does this. But it's required in e-mails as otherwise the attached files won't be displayed with a proper name in all clients. So i guess the only solution is to not use the symfony/mime component for this case and use something else. I'm happy to work on PR but would love some feedback first how it should roughly be implemented so i'm not wasting too much time. Should this then be an own component, should it be in the http client or another solution?

**Comment by wiser** [comment] 2020-03-17 22:25
@n3o77 @nicolas-grekas As I also have issues with this lib so I check on rfc2388, rfc7233 and rfc7578 if I can find any helping informations. 
I agree with @n3o77 about the extra "name" param for content-type in http context, I don’t see any reference of that.
But to solve my issue I also need to put double quotes around names value (as @nicolas-grekas 
 suggests). The rfc7578 give some examples and name values are always surrounded by double-quotes.
Did you have any opinion about this ? 
Can I suggest to always add double quotes around names ?

**Comment by fabpot** [comment] 2020-07-15 05:35
Closing as a duplicate of #37500

**Closed by fabpot** 2020-07-15 05:35 UTC
Labels: Bug, HttpClient, Status: Needs Review

**Comment by fabpot** [comment] 2020-07-15 06:46
@n3o77 #37581 should fix your issue, can you confirm?
