### ISSUE TITLE
[TwigBridge] `absolute_url` does not fallback to RequestContext

### ISSUE THREAD

**Issue by lemoinem** [symfony/symfony#16612] opened 2015-11-20 20:25 UTC
Since 2.7, it's recommended to use `absolute_url` to generate absolute assets URL (http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component).

However, in a console command, `absolute_url` does not rely on `request_context` and, therefore, cannot generate reliable asset URLs...

**Reproduction**:

Clone: lemoinem/symfony-standard@c5bcfb4 (branch: `bug/absolute-url-in-command`)
(No DB, nor mailer config required)

Command: `php app/console TEST:absolute-url`

**Comment by lemoinem** [comment] 2015-11-20 23:50
I checked the `HttpFoundationExtension` and I think the problem is because it depends on `HttpFoundation`'s `RequestStack` whereas it should depends on `Routing`'s `RequestContext`.

However, this means changing the dependency in the `composer.json` (Since it seems to be the sole dependency on `HttpFoundation`).

Would this change be considered a backward compatibility break?
What changes should I be careful with in order to keep BC?

**Comment by xabbuh** [comment] 2015-11-22 09:07
This looks like a duplicate of #15448.

**Closed by xabbuh** 2015-11-22 09:07 UTC
Labels: Asset
