### ISSUE TITLE
[HttpClient] Support expanded query strings

### ISSUE THREAD

**Issue by eschultz-magix** [symfony/symfony#33488] opened 2019-09-06 09:00 UTC
**Description**  
A query string for keys with multiple values is generated as ```key[]=value1&key[]=value2``` using ```http_build_query``` internally. Some endpoints only accept keys without brackets. It would be nice to add an option to generate the other format as well.

**Example**  
A query string for the key ```foo``` with values ```bar``` and ```baz``` can be generated either as ```foo[]=bar&foo[]=baz``` (current behaviour) or ```foo=bar&foo=baz``` (new feature).

**Comment by fancyweb** [comment] 2019-09-06 09:53
Looks like an interesting option to have, I will have a look.

**Comment by nicolas-grekas** [comment] 2019-09-06 10:10
As a workaround, you can give the query as part of the URL of course.
I feel like the only way to have this behavior is to create a new dedicated option.
But every new option should be thought carefully because they incur significant implementation+learning+ decision costs.

**Comment by eschultz-magix** [comment] 2019-09-06 10:17
@fancyweb Awesome, thanks! And of course, the same logic should be applicable for "application/x-www-form-urlencoded" content if body is passed as array.

**Comment by eschultz-magix** [comment] 2019-09-06 10:26
@nicolas-grekas That will only work if the ```query``` option is not passed otherwise ```HttpClientTraint::mergeQueryString``` will re-build the query string using ```http_build_query```.

**Comment by fancyweb** [comment] 2019-09-06 10:28
Just need to find good names for the formats option value 😅 
```
"bracket" --> ?foo[]=bar&foo[]=ccc
"?" --> ?foo=bar&foo=ccc
"comma" --> ?foo=bar,ccc
```

**Comment by eschultz-magix** [comment] 2019-09-06 10:31
@fancyweb Maybe ```expanded```? The same name is used as option name for the ChoiceType of the form component.

**Comment by nicolas-grekas** [comment] 2019-09-06 11:03
> That will only work if the query option is not passed otherwise HttpClientTraint::mergeQueryString will re-build the query string using http_build_query.

that's a bug, let's fix it first

**Comment by fancyweb** [comment] 2019-09-06 11:46
> That will only work if the query option is not passed otherwise
HttpClientTraint::mergeQueryString will re-build the query string using http_build_query.

I can't reproduce the bug. If the `query` option is passed with the same key than one that is  already in the query string, it replaces it (as expected). Otherwise, it just add it without overriding the existing query string.

**Comment by eschultz-magix** [comment] 2019-09-06 12:06
@fancyweb You are right. ```http_build_query``` is called with the ```query``` option as first parameter.

I did some tests:
```php
// replace
HttpClientTraint::mergeQueryString('foo=bar&foo=baz', ['foo' => 'y'], true); // returns 'foo=y', ok
// append
HttpClientTraint::mergeQueryString('foo=bar&foo=baz', ['x' => 'y'], true); // returns 'foo=bar&foo=baz&x=y', ok
```
but
```php
// append nothing
HttpClientTraint::mergeQueryString('foo=bar&foo=baz', [], true); // returns 'foo=bar&foo=baz&', has trailing ampersand
// append array
HttpClientTraint::mergeQueryString('foo=bar&foo=baz', ['x' =>['1', '2'], true); // returns 'foo=bar&foo=baz&x%5B0%5D=1&x%5B1%5D=2', brackets are encoded?
// append array key to existing array
HttpClientTraint::mergeQueryString('foo[]=bar&foo[]=baz', ['x' =>['1', '2'], true); // returns 'foo[]=bar&foo[]=baz&x%5B0%5D=1&x%5B1%5D=2', new brackets encoded, old brackets aren't
```
But this should be a separate bug. This issue is a feature request for alternative query string formats.

**Comment by nicolas-grekas** [comment] 2019-09-06 12:16
So, all is good from your example: the query option is merged with the existing URL without affecting it.
Guzzle provides an [external helper](https://github.com/guzzle/psr7/blob/master/src/functions.php#L572) instead of an option (its `query` option uses `http_build_query` too).
Could that be a fit?

**Comment by nicolas-grekas** [comment] 2019-09-26 18:42
I'm closing because there is already a way: don't use the option and compose the URL before calling `request()`, and also because we found no way to semantically express when we want this or that using the option.

**Closed by nicolas-grekas** 2019-09-26 18:42 UTC
Labels: Feature, HttpClient

**Comment by ecourtial** [comment] 2022-06-08 08:44
Funny thing: I face this issue when running multiple queries at the same time. If I get the result of each query before launching a new one, I have no problem with the presence of brackets in the query.
