### ISSUE TITLE
[RFC][DI] tagging system like event subscribers (autoconfigure)

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#25327] opened 2017-12-05 08:25 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Still being on 3.3, my first preparation in my application is to change everything to autowiring. Now that we have autoconfigure and resource loading, it's a lot easier to get things started with ~1900 services in my app.

However, there are some obstacles I'm hitting that still require me to define a lot of services in my config. While we can currently already use [`!tagged`](https://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services) to avoid using compiler passes in 3.4, I'm still required to configure a priority when this is needed. In some cases, I have ~20 service definitions that I need to sort and inject into another.

Now my autowire.yml looks something like this:
```yml
services:
    #...
    App\Option\One:
        tags:
            - { name: app.option, priority: 10 }
            - { name: features.tag, tag: some_feature_name }
    App\Option\Two: { tags: [{name: app.option, priority: 15}] }
    App\Option\Three: { tags: [{name: app.option, priority: 100}] }
    App\Option\Four: { tags: [{name: app.option, priority: -10}] }

    App\Feature\EnvironmentResolver:
        tags: [{ name: features.resolver, config-key: environment }]
    #... 
```
Ideally I'd _only_ define the service definition that collects these options, so I've been wondering if a tag subscriber would be the solution. Similar to event listeners vs event subscribers, this would allow a class to subscribe to specific tags, which can be picked up by autoconfigure:

```php
interface TagSubscriberInterface
{
    public static function getTags(): array;
}

final class One implements OptionInterface, TagSubscriberInterface
{
    // ...
    public static function getTags()
    {
        // multiple tags
        return [
            ['name' => 'app.option', 'priority' => 10],
            ['name' => 'features.tag', 'tag' => 'some_feature_name'],
        ];
        // different style in case of single tag
        return ['name' => 'app.option', 'priority' => 10];
    }
}

final class EnvironmentResolver implements FeatureResolverInterface, TagSubscriberInterface
{
    // ...
    public static function getTags()
    {
        return ['name' => 'features.resolver', 'config-key' => 'environment'];
    }
}
```

WDYT?

@Simperfit :smile: 
![img_20171205_091405](https://user-images.githubusercontent.com/1754678/33596935-fb843a80-d99d-11e7-84d4-564609be1054.jpg)

**Comment by stof** [comment] 2017-12-05 08:39
`!tagged` already supports priority (it does not support other custom attributes though, as it would not know what to do with them). This might just be missing in the documentation of the feature.

I'm -1 on adding TagSubscriberInterface in the core. Making classes exposing their DI tags themselves introduces a coupling to the config component again (as the concept of tags is purely a DI one).
You should rather define an interface for your class allowing a compiler pass to avoid requiring mandatory tag attributes, but getting the info from the class instead (which would be the actual comparison of event listener vs event subscriber, unlike your proposal to expose tags themselves in the class).

On a side note, you can implement TagSubscriberInterface in your own code if you really want it in your project:
- write a compiler pass (registered with a high priority so that it runs before most other passes run, but still running after the autoconfiguration pass) which would get services tagged as `app.tag_subscriber`) and inject needed tags in your definition (be careful to avoid dropping tags added by autoconfiguration though)
- register the autoconfiguration rule for your interface, adding the `app.tag_subscriber` tag.

**Comment by iltar** [comment] 2017-12-05 08:57
> `!tagged` already supports priority (it does not support other custom attributes though, as it would not know what to do with them). This might just be missing in the documentation of the feature.

Indeed, that's why it's a really nice thing to start with. However, I still have to define the priority (and other attributes) somewhere, which beats the purpose of the resource loading and makes my service config huge.

> Making classes exposing their DI tags themselves introduces a coupling to the config component again (as the concept of tags is purely a DI one).

It's optional and not any different from how the `ServiceSubscriberInterface` or `EventSubscriberInterface` work. Additionally, it would mean that a lot of bundles will provide a similar solution for just their own tags to enable some form of autoconfigure. 

> You should rather define an interface for your class allowing a compiler pass to avoid requiring mandatory tag attributes, but getting the info from the class instead (which would be the actual comparison of event listener vs event subscriber, unlike your proposal to expose tags themselves in the class).

I would like to solve this problem in the core (if possible) with a generic solution to prevent a wild spread of similar implementations and therefore bugs or code duplication.

Is there currently a neat way of collecting this static information from a service definition? The `EventSubscriberInterface` implementation looked kinda complex to be able to just hook in. 

> On a side note, you can implement `TagSubscriberInterface` in your own code if you really want it in your project:

Yes, I can certainly add it myself, that's not really the problem, but I'm pretty sure I'm not the only one running against this particular issue. I can always create a bundle to provide this feature for more so that's not really a problem either.

---

So based on your feedback, what about something that allows people to write attribute targeting interfaces?

```php
class FooBundle
{
    public function load(ContainerBuilder $builder)
    {
        // just and example
        $container->mapInterfaceToTagAttribute(PriorityInterface::class, 'priority', [
            'app.option', 'app.selection'
        ]);
        $container->mapInterfaceToTagAttribute(FeatureConfigKeyInterface::class, 'config-key', [
            'features.resolver'
        ]);
        $container->mapInterfaceToTagAttribute(FeatureTagKeyInterface::class, 'tag', [
            'features.tag'
        ]);
    }
}

class Foo implements PriorityInterface, FeatureConfigKeyInterface, FeatureTagKeyInterface
{
    public static function getPriority(): int { return 10; }
    public static function getConfigKey(): string { return 'environment'; }
    public static function getFeatureTag(): string { return 'some_feature_name'; }
}
```

**Comment by chalasr** [comment] 2017-12-05 09:02
For the record, TagSubscriberInterface was rejected in https://github.com/symfony/symfony/issues/22649

**Comment by stof** [comment] 2017-12-05 09:18
> It's optional and not any different from how the ServiceSubscriberInterface or EventSubscriberInterface

There is a big difference with EventSubscriberInterface. The API exposed by EventSubscriberInterface is related to the feature of the event dispatcher component (btw, it is even usable without using DI at all).
ServiceSubscriberInterface is exposing details about the PSR-11 container that the class itself is using (expliciting what the class expects to find in it).
Your TagSubscriberInterface asks the class to expose some DI related thing, not something related to the behavior of the class itself.

> So based on your feedback, what about something that allows people to write attribute targeting interfaces?

if you need custom attributes on your tags, you already need a custom compiler pass to process them (`!tagged` will never do anything with your `config-key` attribute). And then, it is much easier to call `getConfigKey` directly from your compiler pass rather than adding new features in the DI component for that (which has already been suggested in the past and rejected precisely for this reason).

**Comment by iltar** [comment] 2017-12-05 09:31
Alright, so the best course is to create something myself and make this publicly available in case others will need it as well.

**Comment by weaverryan** [comment] 2017-12-06 03:39
And then, if it’s widely used, it would have a better chance in core. Your use-case makes sense to me, but I don’t how common it is :).

**Comment by nicolas-grekas** [comment] 2017-12-06 10:34
:-1: also: this inlines some important logic in a DI extension, instead of a compiler pass. This means the logic is not reusable anymore. That's a serious regression as far as design is concerned.

**Comment by backbone87** [comment] 2017-12-11 15:30
how about reducing the verbosity by adding "service template parameters":
```yaml
services:
    #...
    _instanceof:
      App\OptionInterface:
        tags:
          - { name: app.option, priority: "%var(app.option.priority:10)%" }

    #App\Option\One: # default value of 10 applies
    App\Option\Two:
      vars:
        app.option.priority: 15
    App\Option\Three:
      vars:
        app.option.priority: 100
    App\Option\Four:
      vars:
        app.option.priority: -10

    #... 
```

**Comment by iltar** [comment] 2017-12-11 18:50
@backbone87 then I'd still have to define each and every dependency, while I would want to utilize autoconfigure for this

**Comment by javiereguiluz** [comment] 2018-01-03 08:34
@iltar sadly I must close this proposal as "won't fix" because of the downvotes from the Core Team, but I hope you keep sending proposals to improve Symfony. Thanks!

**Closed by javiereguiluz** 2018-01-03 08:34 UTC
Labels: DependencyInjection, RFC
