### ISSUE TITLE
Assert 'Length' works wrong 

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#16015] opened 2015-09-30 10:39 UTC
Hi all,
actual the Assert Length doesn't work correct. 

When I define the following:
```
/**
     * @ORM\Column()
     * @Assert\NotBlank(message="Das Feld '{{ value }}' darf nicht leer sein!")
     * @Assert\Length(
     * min = 8,
     * max = 22,
     * minMessage = "Das Passwort muss mindestens {{ limit }} lang sein",
     * maxMessage = "Das Passwort darf maximal {{ limit }} lang sein" )
     */
    protected $password;
```
and want to create a user about an form and enter the passwort *123*, I got the following message back:

*Das Passwort darf maximal 22 lang sein.*

This is of course the wrong output.
Can you try to reproduce this issue?

**Comment by xabbuh** [comment] 2015-09-30 10:59
Which Symfony version do you use? And can you please provide a failing test case or a fork of the Symfony Standard Edition that makes it possible to reproduce your issue?

**Comment by lu-beumer** [comment] 2015-09-30 11:36
Hi Christian,
using 2.7.5. 
I am working at the moment, so I can't write a test case for you. I will give you one tomorrow afternoon.

**Comment by pix-art** [comment] 2015-09-30 13:43
Hi, 

I just wrote this test in 2.7

````

    /**
     * @group length
     */
    public function testValidValuesIssue()
    {
        $value = 123;
        $constraint = new Length(array(
            'min' => 8,
            'max' => 22,
            'minMessage' => "Das Passwort muss mindestens 8 lang sein",
            'maxMessage' => "Das Passwort darf maximal 22 lang sein")
        );

        $this->validator->validate($value, $constraint);

        $this->buildViolation('Das Passwort muss mindestens 8 lang sein')
            ->setParameter('{{ value }}', '"'.$value.'"')
            ->setParameter('{{ limit }}', 8)
            ->setInvalidValue($value)
            ->setPlural(8)
            ->setCode(Length::TOO_SHORT_ERROR)
            ->assertRaised();
    }
````

And it works as intended:

```
$ php phpunit --group length
PHPUnit 4.8.9 by Sebastian Bergmann and contributors.

.

Time: 4.18 seconds, Memory: 182.50Mb

OK (1 test, 2 assertions)

Legacy deprecation notices (24)
OK symfony
```

**Comment by jaytaph** [comment] 2015-09-30 13:53
I would guess that the password is hashes before validation, resulting in a large string.  You might check by adding '{{ value }}' to your error message

**Comment by lu-beumer** [comment] 2015-09-30 13:56
Yes, that's the problem. Thank you. But how can i solve this problem? The password hash is generated in the Controller.

**Comment by xabbuh** [comment] 2015-09-30 14:59
Well, validate your object before hashing the password. It's hard to give you a better advice without knowing your actual code. Anyway, closing here as it turned out that this is no bug.

**Closed by xabbuh** 2015-09-30 14:59 UTC
Labels: Validator
