### ISSUE TITLE
Doctrine 3 is not compatible

### ISSUE THREAD

**Issue by james-fruhbauer** [symfony/symfony#37417] opened 2020-06-25 13:35 UTC
**Symfony version(s) affected**: 4.4

**Description**  
Doctrine 3 is not compatible, problem is in symfony/orm-pack automaticaly upgrade doctrine version from 2 to 3

**How to reproduce**  
run command composer update

**Possible Solution**  
Update composer.json in symfony/orm-pack from * to version 2 and release new minor version of symfony/orm-pack and major version with doctrine 3

**Comment by mbabker** [comment] 2020-06-25 17:58
Which Doctrine package?  There are a large number of them.

If you're referring to the migrations library and bundle, then yes you would need to make changes in your application according to https://github.com/doctrine/migrations/blob/3.0.x/UPGRADE.md and https://github.com/doctrine/DoctrineMigrationsBundle/blob/3.0.x/UPGRADE.md, or pin the migrations packages in your application to a 2.x version until you're ready to update.

**Comment by james-fruhbauer** [comment] 2020-06-26 12:10
Problem is in doctrine/doctrine-migrations-bundle, different configuration, default configuration is not working correctly (version_column_length: 1024 is too long index), old migrations are not converted automatically.

**Comment by xabbuh** [comment] 2020-06-26 12:20
As @mbabker said you need to adapt your configuration or pin the dependency to 2.x explicitly if you are not ready to update yet. There's nothing we can do about it here. So I am going to close the issue. Thank you for understanding.

**Closed by xabbuh** 2020-06-26 12:20 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback

**Comment by stof** [comment] 2020-06-26 13:55
@xabbuh the issue is that the orm-pack uses a `*` requirement.

**Comment by nicolas-grekas** [comment] 2020-06-26 13:58
or that we allow ^2.4|^3
orm-pack or not, the only way is to adopt transitive deps.

**Comment by stof** [comment] 2020-06-26 14:01
@nicolas-grekas for a pack, which *only* goal is to provide a group of transitive dependencies, we should treat their requirements as their semver API (so changing from `^2.4` to `^2.4 | ^3` is a BC break, as it brings in the BC breaks of the 3.0 release).
Otherwise, we should deprecate the concept of packs entirely (even forcing to unpack them would not solve the issue, as they would unpack their `*` constraint).
