### ISSUE TITLE
Invalid date 1980-04-20 when use 'date' form type and set widget options 'simple_text'

### ISSUE THREAD

**Issue by lamjack** [symfony/symfony#15691] opened 2015-09-04 09:50 UTC
Invalid date 1980-04-20 when use 'date' form type and set widget options 'simple_text'.

**Comment by aitboudad** [comment] 2015-09-04 10:01
Can you try set the `format` ?

```php
    'widget' => 'single_text',
    'format' => 'yyyy-MM-dd',
```

**Comment by lamjack** [comment] 2015-09-04 10:54
yes the type option still set widget => 'single_text' and the format => 'yyyy-MM-dd'

**Comment by lamjack** [comment] 2015-09-04 11:00
1980-04-20
1979-04-15
1978-04-16
1974-04-21
1973-04-15
1972-04-16
1965-03-21
1963-03-17
1912-01-01

these dates both invalid in 'date' form type.

**Comment by aitboudad** [comment] 2015-09-04 11:19
I couldn't reproduce it, can you provide a fork of Symfony SE reproducing this issue ?

**Comment by lamjack** [comment] 2015-09-07 02:49
sorry i was holiday these days.

i found the problem in Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer
line 160

$intlDateFormatter = new \IntlDateFormatter(\Locale::getDefault(), $dateFormat, $timeFormat, $timezone, $calendar, $pattern);

my parameters is (zh_TW, 2, -1, Asia/Macau, 1, yyyy-MM-dd),

and $intlDateFormatter->parse('1980-04-20') is return false.

**Comment by lamjack** [comment] 2015-09-07 03:02
my composer.json file.

```javascript
 "require": {
        "php": ">=5.4.0",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/dbal": "<2.5",
        "doctrine/common": "v2.4.2",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/doctrine-fixtures-bundle": "2.2.*",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0"
        ...
    }
```

**Comment by inso** [comment] 2015-09-07 14:36
@lamjack https://3v4l.org/bc0bH

**Comment by snakewa** [comment] 2015-09-09 08:59
In the latest commit:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php
( https://www.dropbox.com/s/axb3cpejxhngsed/Screenshot%202015-09-09%2016.51.50.png?dl=0 )

The problem is that :

    $intlDateFormatter->setLenient(false); 


In current Symfony code, it could not handle some dates such as '1980-04-20'
https://3v4l.org/khMuc

**Comment by apfelbox** [comment] 2015-09-09 10:29
@snakewa if I read the ticket correctly, the issue is not that the Formatter can't handle (= automatically fix) an invalidate date – that is what `setLenient` is for.
The issue is that a *valid* date isn't parsed correctly: the date `1980-04-20` for the format `yyyy-MM-dd` is perfectly valid.

**Comment by snakewa** [comment] 2015-09-09 10:59
You are right. The date "1980-04-20" for the format yyyy-MM-dd is perfectly valid. It might be a bug of IntlDateFormatter. and since there is an implicitly method called 'setLenient(false);' in DateTimeToLocalizedStringTransformer code. In this case, '1980-04-20' is always an invalid date for date form type.

**Comment by snakewa** [comment] 2015-09-15 09:01
Same problem discussion:
http://stackoverflow.com/questions/31418877/symfony2-and-1969-04-27-date

**Comment by jakzal** [comment] 2015-11-25 10:41
@lamjack @snakewa Since the case we're discussing here has no time included (it's just a date), the `\IntlDateFormatter` will try to use midnight. Time was [moved forward one hour in Macau](http://www.timeanddate.com/time/change/macau/macau?year=1980) on 20th April 1980, so anything between midnight and 1am on that day [is an invalid date](http://www.timeanddate.com/worldclock/converted.html?iso=19800420T00&p1=754&p2=136).

**Comment by lamjack** [comment] 2015-11-26 02:57
@jakzal got it and thanks very much.

**Comment by javiereguiluz** [comment] 2016-02-06 16:46
Closing it as fixed, because @jakzal's awesome debugging skills proved that this is in fact an invalid date.

**Closed by javiereguiluz** 2016-02-06 16:46 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed
