### ISSUE TITLE
Symfony\Bridge\Monolog\Logger throwing a deprecation error

### ISSUE THREAD

**Issue by RobertoGongora** [symfony/symfony#49733] opened 2023-03-19 15:21 UTC
### Symfony version(s) affected

6.2.7

### Description

I'm getting this error thrown when running tests:

```
Remaining indirect deprecation notices (1)

  1x: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger".
    1x in SearchControllerTest::testSearchByTitle from App\Tests
```

I'm using PHP 8.1.15 on macOS 13.0.1 installed using `brew`.

Already ran `composer update` which fixed an EasyAdmin error similar to that one, pasting it here for reference:

```
1x: Method "Symfony\Contracts\Service\ResetInterface::reset()" might add "void" as a native return type declaration in the future. Do the same in implementation "EasyCorp\Bundle\EasyAdminBundle\Inspector\DataCollector" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit
```

### How to reproduce

This is my test code:

```php
public function testSearchByTitle()
    {
        $this->postRepository->expects($this->once())
            ->method('search')
            ->with('Título de prueba')
            ->willReturn([$this->post]);

        $client = static::createClient();
        $client->getContainer()->set(PostRepository::class, $this->postRepository);
        $client->request('GET', '/search', ['query' => 'Título de prueba']);

        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h2', 'Título de prueba');
    }
```

It doesn't report any line number in particular.

**Comment by derrabus** [comment] 2023-03-19 17:56
Duplicate of #47096.

**Closed as not planned by derrabus** 2023-03-19 17:56 UTC
Labels: Bug, Status: Needs Review
