### ISSUE TITLE
Checking the application of the configured session storage directory

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#44690] opened 2021-12-17 14:20 UTC
### Symfony version(s) affected

6.0

### Description

I am trying the setting “`session.save_path = "/var/lib/php8/sessions"`” out in the file “/etc/php8/cli/php.ini” at the moment.

### How to reproduce

I constructed a tiny script for a test like the following.

```php
<?php
$handle = fopen(session_save_path() . '/test-data.txt', 'w+');
if ($handle) {
    fwrite($handle, "session test data\n");
}
?>
```

```
Markus_Elfring@…:…/Ausnahmebehandlung> php -f fopen-test-20211217.php && ls -l /var/lib/php8/sessions
insgesamt 4
-rw-r--r-- 1 Markus_Elfring users 18 17. Dez 12:30 test-data.txt
```

 
I am trying the following settings out in the file “config/packages/framework.yaml” in an example application (which was adjusted a bit according to [the provided software documentation](https://symfony.com/doc/current/setup.html#creating-symfony-applications "Creating Symfony applications")).

```yaml
framework:
…
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
…
```

The file “src/Controller/IndexController.php” contains the following source code.

```php
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends AbstractController
{
    /**
     * @Route("/start", name="main")
     */
    public function display_document(): Response
    {
        return new Response("<html>\n<head>\n<title>Start</title>\n</head>\n<body>\n"
                            . '<p>Prüfung zur Sitzungsverwaltung: <b><a href="/checks/session-test1">Test 1</a></b></p>'
                            . "\n</body>\n</html>\n");
    }
}
?>
```

[Another test result](https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1639668025301300?thread_ts=1639387599.025800&cid=C3EQ7S3MJ "Clarification request from 2021-12-16"):
```
Markus_Elfring@…:…/Ausnahmebehandlung_prüfen1> symfony server:start
…
 [OK] Web server listening                                                                                              
      The Web server is using PHP FPM 8.0.13                                                                            
…
[Web Server ] Dec 17 13:55:32 |DEBUG  | PHP    Using PHP version 8.0.13 (from default version in $PATH) 
…
[Application] Dec 10 15:09:14 |CRITICA| REQUES Uncaught PHP Exception ErrorException: "Warning: SessionHandler::read(): open(/var/lib/php8/sess_jl9aljcsh2h8obb9g3l7k7k264, O_RDWR) failed: Permission denied (13)" at /home/…/Ausnahmebehandlung_prüfen1/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php line 45 
…
[Application] Dec 10 15:09:38 |ERROR  | REQUES Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/"" at /home/…/Ausnahmebehandlung_prüfen1/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 
…
[Application] Dec 10 15:09:38 |INFO   | REQUES Matched route "_wdt". method="GET" request_uri="http://127.0.0.1:8000/_wdt/30a37a" route="_wdt" route_parameters={"_controller":"web_profiler.controller.profiler::toolbarAction","_route":"_wdt","token":"30a37a"}
[Application] Dec 14 13:18:42 |INFO   | REQUES Matched route "main". request_uri="http://127.0.0.1:8000/start" route="main" route_parameters={"_controller":"App\\Controller\\IndexController::display_document","_route":"main"}
…
```

It can be appropriate that a failed file creation (for write access) is reported for the mentioned directory so far.
I would expect that an other directory should be applied for the shown test case.

### Additional Context

Symfony CLI version v4.26.11 (2021-12-07T18:08:49+0000 - stable)

**Comment by xabbuh** [comment] 2021-12-17 16:13
Cannot reproduce, closing here. Please provide a full example application that allows to reproduce it.

**Comment by xabbuh** [comment] 2021-12-20 15:16
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed as completed** 2021-12-20 15:16 UTC
Labels: Bug, Status: Waiting feedback
