### ISSUE TITLE
[Console] Ask question stopped supporting custom style formatting since 5.1.9

### ISSUE THREAD

**Issue by aurelijusrozenas** [symfony/symfony#41401] opened 2021-05-24 17:35 UTC
**Symfony version(s) affected**: 5.1.9

**Description**
Ask question stopped supporting custom style formatting.

**How to reproduce**
```php
$outputStyle = new OutputFormatterStyle('red', 'yellow', ['bold', 'blink']);
$output->getFormatter()->setStyle('fire', $outputStyle);
$string = '<fire>foo</fire>';

$output->writeln($string); // <--- work fine, always

$question = new Question($string);
$helper = $this->getHelper('question');
$helper->ask($input, $output, $question); // <--- does not work since 5.1.9
```

**Additional context**
Stopped working in 5.1.9 when this code was added: https://github.com/symfony/console/compare/v5.1.8...v5.1.9#diff-fcc70057647a28f0ccd4943135abb874b0baa8f6352b7813d6ea2c5d440638caR44
```php
if (null === $formatter) {
    // for BC reasons, stdErr has it own Formatter only when user don't inject a specific formatter.
    $this->stderr = new StreamOutput($this->openErrorStream(), $verbosity, $decorated);

    return;
}
```

So am I doing it wrong? :) Am I missing something? Could not find anything relevant in other issues or documentation.  
Tried latest `5.2.8` - problem is the same.

**Comment by stof** [comment] 2021-05-24 17:58
it looks like the BC layer was incomplete

**Comment by YaFou** [comment] 2021-05-31 09:59
Seems duplicate of #39946

**Comment by xabbuh** [comment] 2021-06-25 11:06
closing as a duplicate then

**Closed as completed by xabbuh** 2021-06-25 11:06 UTC
Labels: Bug, Console, Status: Needs Review
