### ISSUE TITLE
ExceptionListener status code

### ISSUE THREAD

**Issue by mrAndersen** [symfony/symfony#20069] opened 2016-09-28 11:23 UTC
Hi there. I am sorry if this issue is not a bug, but seems to be it is.

I have configuration as follows [http://i.imgur.com/VVOPIFY.png](http://i.imgur.com/VVOPIFY.png) and at every step in every listener - even in default ones, status code for exceptions are 0, and this is explainable because in my case "ServiceNotFoundException" has default status code 0 when creating it in Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException as long as HttpNotFound and other ones, is this ok? And if so - how can i get real status code inside custom exception listener. symfony - is version 3.0.9. Thx
[http://i.imgur.com/6He9e1h.png](http://i.imgur.com/6He9e1h.png)

**Comment by unkind** [comment] 2016-09-28 16:36
Exception code has nothing to do with HTTP status code.

**Comment by mrAndersen** [comment] 2016-09-28 16:42
Can you give me an example of exception which status code is different from corresponding http response object that is returned by symfony except for 0?

**Comment by unkind** [comment] 2016-09-28 19:42
> how is it possible to get corresponding http status code to the exception which is occurred during execution

This question doesn't make sense in general, because there is no unambiguous mapping between exceptions and HTTP status codes. Usually, unknown uncaught exceptions produce 500 status code (Internal server error).

I suggest to ask about it on stackoverflow or similar resource, your issue doesn't look like a bug report.

**Comment by mrAndersen** [comment] 2016-09-28 19:52
> This question doesn't make sense in general

This makes sense, because every exception class in symfony produce corresponding http code, such as AccesDenied* - 403, NotFound* - 404, e.t.c

**Comment by unkind** [comment] 2016-09-28 20:37
You talk about exceptions with `HttpExceptionInterface` interface.

**Comment by fabpot** [comment] 2016-09-29 02:28
Closing as this is not a bug report. As suggestion by @unkind, you can move the discussion to StackOverflow. Thanks.

**Closed by fabpot** 2016-09-29 02:28 UTC
