### ISSUE TITLE
Upgrade from v4.4.30 to v4.4.31 fails

### ISSUE THREAD

**Issue by lowwa132** [symfony/symfony#43216] opened 2021-09-28 09:16 UTC
**Symfony version(s) affected**: 4.4.31

**Description**

**How to reproduce**
Execute `./composer.phar update symfony/*`
Output:
Script cache:clear returned with error code 255

**Additional context**
![image](https://user-images.githubusercontent.com/3715048/135059504-9599c4d7-b791-432b-be8a-ca3937bb777c.png)

**Comment by derrabus** [comment] 2021-09-28 09:24
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:24 UTC
Labels: Bug, Status: Needs Review
