### ISSUE TITLE
Form errors rendered twice for one field.

### ISSUE THREAD

**Issue by jawadmjn** [symfony/symfony#29187] opened 2018-11-12 13:32 UTC
**Symfony version(s) affected**: 4.1

**Description**  
It occurs in this [commit](https://github.com/symfony/symfony/commit/a0b40f5c4a5d46a2df789d223b46b91e08b339f8)

By putting errors in the label now the following issue occurs. And we can not use [Customize Form Rendering](https://symfony.com/doc/current/form/form_customization.html)

For example when I am putting a field like this:

```twig
{{ form_label(attraction.surroundings) }}

{{ form_widget(attraction.surroundings) }}

{{ form_help(attraction.surroundings) }}

{{ form_errors(attraction.surroundings) }}
```

And Error occured then The error message is one time showing in **label** and 2nd time what i put form_errors.

<img width="464" alt="screen shot 2018-11-12 at 13 57 11" src="https://user-images.githubusercontent.com/12748654/48348981-2e7f5080-e683-11e8-8f4a-95b3cb714d9c.png">

**Possible Solution** 
So we should take errors out from the label and have to put **form_errors** in **form_row** And we have to put form_errors in the end otherwise if the error occurs then error area will push the whole layout down.

```
{% block form_row -%}
    {%- if compound is defined and compound -%}
        {%- set element = 'fieldset' -%}
    {%- endif -%}
    {%- set widget_attr = {} -%}
    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
    {%- endif -%}
    <{{ element|default('div') }} class="form-group">
        {{- form_label(form) -}}
        {{- form_widget(form, widget_attr) -}}
        {{- form_help(form) -}}
        **{{- form_errors(form) -}}**
    </{{ element|default('div') }}>
{%- endblock form_row %}
```

**Comment by ro0NL** [comment] 2018-11-12 14:03
Would be solved if you don't render `{{ form_errors(attraction.surroundings) }}` yourself right?

Otherwise, why cant you disable the errors in the label by overriding its block: `{% block form_label_errors %}`

**Comment by stof** [comment] 2018-11-12 14:17
The Bootstrap 4 theme renders errors inside `form_label`, for accessibility reasons. Rendering them manually outside it is the reason why you have them rendered twice.

**Comment by jawadmjn** [comment] 2018-11-12 14:17
If we can not render error on our own then this thing is against this document [Customize Form Rendering](https://symfony.com/doc/current/form/form_customization.html)

And if I am just using 
`
{{ form_row(attraction.name) }}
`

Then out looks like this:

<img width="1036" alt="screen shot 2018-11-12 at 15 15 29" src="https://user-images.githubusercontent.com/12748654/48352815-0f39f080-e68e-11e8-9e95-bf2a5e0deb81.png">

**Comment by stof** [comment] 2018-11-12 14:29
the page you link has a note about reading more on the BS 4 theme, and that page tells you about the fact that errors are rendered inside the label: https://symfony.com/doc/current/form/bootstrap4.html#labels-and-errors

@javiereguiluz would it make sense to add a dedicated note in the `Customize Form Rendering` page about that ?

**Comment by jawadmjn** [comment] 2018-11-12 14:32
@stof I am perfectly fine what you said but the thing is that the page layout is broken as you can see in the image I attached.

**Comment by xabbuh** [comment] 2019-02-02 07:53
I am closing here as this is the expected behaviour (though currently being discussed in #28086).

**Closed by xabbuh** 2019-02-02 07:53 UTC
Labels: Bug, Form, Status: Needs Review, TwigBridge

**Comment by zangab** [comment] 2020-05-26 08:34
guess i'm late but @jawadmjn is right @xabbuh 

this does not work as expected. as it's written in the docs (https://symfony.com/doc/current/form/form_customization.html) the `form_errors(...)` should display the input fields' errors. BUT as it is right now, the whole `form_errors(...)` are getting appended in the `form_label(...)` and this does not match with the [illustrated diagram](https://user-images.githubusercontent.com/9076592/82878579-f32e3500-9f3b-11ea-96b6-686377251611.png) in the docs. the `form_label(...)` responsibility should be to render the label only.

**Comment by xabbuh** [comment] 2020-05-26 08:48
It looks like symfony/symfony-docs#13685 will clarify that.

**Comment by ThomasLandauer** [comment] 2020-11-03 13:34
Now online at https://symfony.com/doc/4.4/form/form_customization.html#form-errors-form-view
