### ISSUE TITLE
[HttpKernel] Timeline in profiler is broken since 5.3.7

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#42804] opened 2021-08-30 19:20 UTC
**Symfony version(s) affected**: 5.3.7

**Description**
After updating symfony/http-kernel from 5.3.6 to 5.3.7, Execution timeline in performance metrics is empty

![image](https://user-images.githubusercontent.com/496233/131392944-753e998f-212f-4b9d-bd68-f2e42751800b.png)

Downgrading symfony/http-kernel to 5.3.6 fixes the issue

**Additional context**
Suspected culprit is #42331

cc @xabbuh

**Comment by dmaicher** [comment] 2021-08-31 09:24
Can confirm the issue using 4.4.30

**Comment by fd6130** [comment] 2021-08-31 09:50
Same here, confirm the issue using 5.3.7

**Comment by DiceWithSpades** [comment] 2021-08-31 18:38
I've got that too after updating to 5.3.7. I found that in `Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher` instead of using `X-Debug-Token` the stopwatch token is passed by `_stopwatch_token` parameter in request attributes but `Symfony\Component\HttpKernel\DataCollector\TimeDataCollector` still uses `X-Debug-Token`  as source for debug token. Simply replacing the source for token to `_stopwatch_token` "fixed" the issue but I'm not sure if this is the desired way to solve this.

**Comment by herndlm** [comment] 2021-09-01 07:23
Without knowing too much about the internals here, this sounds like the correct fix, especially because that change happened in #42331 and now it's out-of-sync basically. Let me create a PR for that so that the maintainers can confirm/merge :) 
UPDATE: nope sorry, I think this needs to be changed back to `X-Debug-Token` everywhere to avoid the behaviour change from 4.4 up and still fix the bug that was fixed in #42331. It needs to be consistent for sure..

**Closed as completed** 2021-09-01 16:51 UTC
Labels: Bug, HttpKernel, Status: Needs Review

**Comment by fabpot** [comment] 2021-09-07 11:03
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases

**Comment by domhaas** [comment] 2021-09-09 21:00
> I'm very sorry that this release has some issues.
> 
> Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).
> 
> More information about how you can do it:
> https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases

Can confirm that with latest 5.3@dev profiler toolbar is working again. Thanks.

**Comment by domhaas** [comment] 2021-09-09 21:05
> I'm very sorry that this release has some issues.
> 
> Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).
> 
> More information about how you can do it:
> https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases

Can confirm that profiler on 5.3@dev is working fine again. Thanks!

**Comment by PhilETaylor** [comment] 2021-09-15 17:18
I came across this bug today when debugging locality. First time I had seen it. 

I was unable to get composer to resolve dependence's with `5.4@dev` as per @wouterj article at https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases but using `5.4.x-dev` instead of `5.4@dev` throughout composer.json I was able to upgrade all and Im pleased to report that this issue with the profiler is fixed for me.
