### ISSUE TITLE
Problem on update to 5.3.8 From 5.3.7

### ISSUE THREAD

**Issue by ioniks** [symfony/symfony#43217] opened 2021-09-28 09:17 UTC
**Symfony version(s) affected**: 5.3.8

**Description**
On update from 5.3.7 to 5.3.8

```
In RegisterListenersPass.php line 143:
Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.
```

**Comment by kissifrot** [comment] 2021-09-28 09:23
Looks like composer have a lot of complains about psr4:
```
Class Symfony\Component\Mailer\Transport\Smtp\Auth\LoginAuthenticator located in ./vendor/symfony/mailer/LoginAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\NullTransportFactoryTest located in ./vendor/symfony/mailer/NullTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\AuthenticatorInterface located in ./vendor/symfony/mailer/Auth/AuthenticatorInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\XOAuth2Authenticator located in ./vendor/symfony/mailer/Auth/XOAuth2Authenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\LoginAuthenticator located in ./vendor/symfony/mailer/Auth/LoginAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\PlainAuthenticator located in ./vendor/symfony/mailer/Auth/PlainAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\CramMd5Authenticator located in ./vendor/symfony/mailer/Auth/CramMd5Authenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Tests\Transport\SesApiAsyncAwsTransportTest located in ./vendor/symfony/mailer/SesApiAsyncAwsTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\PlainAuthenticator located in ./vendor/symfony/mailer/PlainAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillApiTransport located in ./vendor/symfony/mailer/MandrillApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Tests\Transport\SesTransportFactoryTest located in ./vendor/symfony/mailer/SesTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetApiTransport located in ./vendor/symfony/mailer/MailjetApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory located in ./vendor/symfony/mailer/GmailTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream located in ./vendor/symfony/mailer/SocketStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream located in ./vendor/symfony/mailer/AbstractStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\TransportException located in ./vendor/symfony/mailer/TransportException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Tests\Transport\MandrillApiTransportTest located in ./vendor/symfony/mailer/MandrillApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Transports located in ./vendor/symfony/mailer/Transports.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Tests\Transport\SesApiTransportTest located in ./vendor/symfony/mailer/SesApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\SendmailTransportTest located in ./vendor/symfony/mailer/SendmailTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Messenger\SendEmailMessage located in ./vendor/symfony/mailer/SendEmailMessage.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Test\Constraint\EmailCount located in ./vendor/symfony/mailer/EmailCount.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\SendmailTransport located in ./vendor/symfony/mailer/SendmailTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetApiTransport located in ./vendor/symfony/mailer/Mailjet/Transport/MailjetApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetSmtpTransport located in ./vendor/symfony/mailer/Mailjet/Transport/MailjetSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetTransportFactory located in ./vendor/symfony/mailer/Mailjet/Transport/MailjetTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetSmtpTransport located in ./vendor/symfony/mailer/MailjetSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\TransportTest located in ./vendor/symfony/mailer/TransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\DummyTransport located in ./vendor/symfony/mailer/TransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\DummyTransportFactory located in ./vendor/symfony/mailer/TransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory located in ./vendor/symfony/mailer/PostmarkTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\MessageListenerTest located in ./vendor/symfony/mailer/MessageListenerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Dsn located in ./vendor/symfony/mailer/Dsn.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunHeadersTrait located in ./vendor/symfony/mailer/MailgunHeadersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\CramMd5Authenticator located in ./vendor/symfony/mailer/CramMd5Authenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\AbstractTransport located in ./vendor/symfony/mailer/AbstractTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\SentMessageTest located in ./vendor/symfony/mailer/SentMessageTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\AbstractHttpTransport located in ./vendor/symfony/mailer/AbstractHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Test\TransportFactoryTestCase located in ./vendor/symfony/mailer/TransportFactoryTestCase.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\Smtp\Stream\SocketStreamTest located in ./vendor/symfony/mailer/SocketStreamTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Tests\Transport\MandrillSmtpTransportTest located in ./vendor/symfony/mailer/MandrillSmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Tests\Transport\SesHttpAsyncAwsTransportTest located in ./vendor/symfony/mailer/SesHttpAsyncAwsTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Header\TagHeader located in ./vendor/symfony/mailer/TagHeader.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\TransportInterface located in ./vendor/symfony/mailer/TransportInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesApiTransport located in ./vendor/symfony/mailer/SesApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\SendmailTransportFactoryTest located in ./vendor/symfony/mailer/SendmailTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Tests\Transport\SendgridApiTransportTest located in ./vendor/symfony/mailer/SendgridApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory located in ./vendor/symfony/mailer/EsmtpTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\DsnTest located in ./vendor/symfony/mailer/DsnTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\EventListener\MessageLoggerListener located in ./vendor/symfony/mailer/MessageLoggerListener.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\EventListener\MessageListener located in ./vendor/symfony/mailer/MessageListener.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkApiTransport located in ./vendor/symfony/mailer/PostmarkApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory located in ./vendor/symfony/mailer/Postmark/Transport/PostmarkTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkApiTransport located in ./vendor/symfony/mailer/Postmark/Transport/PostmarkApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkSmtpTransport located in ./vendor/symfony/mailer/Postmark/Transport/PostmarkSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetTransportFactory located in ./vendor/symfony/mailer/MailjetTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream located in ./vendor/symfony/mailer/Stream/SocketStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream located in ./vendor/symfony/mailer/Stream/AbstractStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\ProcessStream located in ./vendor/symfony/mailer/Stream/ProcessStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory located in ./vendor/symfony/mailer/Google/Transport/GmailTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Google\Transport\GmailSmtpTransport located in ./vendor/symfony/mailer/Google/Transport/GmailSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailjet\Tests\Transport\MailjetTransportFactoryTest located in ./vendor/symfony/mailer/MailjetTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillSmtpTransport located in ./vendor/symfony/mailer/MandrillSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillTransportFactory located in ./vendor/symfony/mailer/MandrillTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\LogicException located in ./vendor/symfony/mailer/LogicException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\TransportExceptionInterface located in ./vendor/symfony/mailer/TransportExceptionInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\ProcessStream located in ./vendor/symfony/mailer/ProcessStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\FailoverTransport located in ./vendor/symfony/mailer/FailoverTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpTransport located in ./vendor/symfony/mailer/SesHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\RoundRobinTransport located in ./vendor/symfony/mailer/RoundRobinTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueSmtpTransport located in ./vendor/symfony/mailer/SendinblueSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Test\Constraint\EmailCount located in ./vendor/symfony/mailer/Constraint/EmailCount.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Test\Constraint\EmailIsQueued located in ./vendor/symfony/mailer/Constraint/EmailIsQueued.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Tests\Transport\MailgunHttpTransportTest located in ./vendor/symfony/mailer/MailgunHttpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunSmtpTransport located in ./vendor/symfony/mailer/MailgunSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridApiTransport located in ./vendor/symfony/mailer/Sendgrid/Transport/SendgridApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridTransportFactory located in ./vendor/symfony/mailer/Sendgrid/Transport/SendgridTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridSmtpTransport located in ./vendor/symfony/mailer/Sendgrid/Transport/SendgridSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Tests\Transport\MailgunSmtpTransportTest located in ./vendor/symfony/mailer/MailgunSmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\SendmailTransportFactory located in ./vendor/symfony/mailer/SendmailTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpAsyncAwsTransport located in ./vendor/symfony/mailer/SesHttpAsyncAwsTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunHeadersTrait located in ./vendor/symfony/mailer/Mailgun/Transport/MailgunHeadersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunSmtpTransport located in ./vendor/symfony/mailer/Mailgun/Transport/MailgunSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunHttpTransport located in ./vendor/symfony/mailer/Mailgun/Transport/MailgunHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunApiTransport located in ./vendor/symfony/mailer/Mailgun/Transport/MailgunApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory located in ./vendor/symfony/mailer/Mailgun/Transport/MailgunTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillHeadersTrait located in ./vendor/symfony/mailer/MandrillHeadersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\NullTransportTest located in ./vendor/symfony/mailer/NullTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\NativeTransportFactory located in ./vendor/symfony/mailer/NativeTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Test\Constraint\EmailIsQueued located in ./vendor/symfony/mailer/EmailIsQueued.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\AuthenticatorInterface located in ./vendor/symfony/mailer/Smtp/Auth/AuthenticatorInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\XOAuth2Authenticator located in ./vendor/symfony/mailer/Smtp/Auth/XOAuth2Authenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\LoginAuthenticator located in ./vendor/symfony/mailer/Smtp/Auth/LoginAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\PlainAuthenticator located in ./vendor/symfony/mailer/Smtp/Auth/PlainAuthenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Auth\CramMd5Authenticator located in ./vendor/symfony/mailer/Smtp/Auth/CramMd5Authenticator.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory located in ./vendor/symfony/mailer/Smtp/EsmtpTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream located in ./vendor/symfony/mailer/Smtp/Stream/SocketStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream located in ./vendor/symfony/mailer/Smtp/Stream/AbstractStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\Stream\ProcessStream located in ./vendor/symfony/mailer/Smtp/Stream/ProcessStream.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport located in ./vendor/symfony/mailer/Smtp/EsmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\SmtpTransport located in ./vendor/symfony/mailer/Smtp/SmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Messenger\MessageHandler located in ./vendor/symfony/mailer/MessageHandler.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\DataCollector\MessageDataCollector located in ./vendor/symfony/mailer/MessageDataCollector.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillHttpTransport located in ./vendor/symfony/mailer/MandrillHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Tests\Transport\PostmarkApiTransportTest located in ./vendor/symfony/mailer/PostmarkApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\NullTransportFactory located in ./vendor/symfony/mailer/NullTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Tests\Transport\SendinblueApiTransportTest located in ./vendor/symfony/mailer/SendinblueApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\NativeTransportFactoryTest located in ./vendor/symfony/mailer/NativeTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\AbstractTransportFactory located in ./vendor/symfony/mailer/AbstractTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunHttpTransport located in ./vendor/symfony/mailer/MailgunHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Tests\Transport\PostmarkTransportFactoryTest located in ./vendor/symfony/mailer/PostmarkTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunApiTransport located in ./vendor/symfony/mailer/MailgunApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesApiAsyncAwsTransport located in ./vendor/symfony/mailer/SesApiAsyncAwsTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory located in ./vendor/symfony/mailer/MailgunTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport located in ./vendor/symfony/mailer/EsmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\Smtp\SmtpTransport located in ./vendor/symfony/mailer/SmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\Smtp\Stream\AbstractStreamTest located in ./vendor/symfony/mailer/AbstractStreamTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueApiTransport located in ./vendor/symfony/mailer/Sendinblue/Transport/SendinblueApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueSmtpTransport located in ./vendor/symfony/mailer/Sendinblue/Transport/SendinblueSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueTransportFactory located in ./vendor/symfony/mailer/Sendinblue/Transport/SendinblueTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridTransportFactory located in ./vendor/symfony/mailer/SendgridTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailgun\Tests\Transport\MailgunApiTransportTest located in ./vendor/symfony/mailer/MailgunApiTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\NullTransport located in ./vendor/symfony/mailer/NullTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Event\MessageEvents located in ./vendor/symfony/mailer/MessageEvents.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\Smtp\EsmtpTransportTest located in ./vendor/symfony/mailer/EsmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Tests\Transport\SendinblueTransportFactoryTest located in ./vendor/symfony/mailer/SendinblueTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\InvalidArgumentException located in ./vendor/symfony/mailer/InvalidArgumentException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkSmtpTransport located in ./vendor/symfony/mailer/PostmarkSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueTransportFactory located in ./vendor/symfony/mailer/SendinblueTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\IncompleteDsnException located in ./vendor/symfony/mailer/IncompleteDsnException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\RuntimeException located in ./vendor/symfony/mailer/RuntimeException.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\ExceptionInterface located in ./vendor/symfony/mailer/ExceptionInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridSmtpTransport located in ./vendor/symfony/mailer/SendgridSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Google\Transport\GmailSmtpTransport located in ./vendor/symfony/mailer/GmailSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Google\Tests\Transport\GmailTransportFactoryTest located in ./vendor/symfony/mailer/GmailTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\MessageListenerTest located in ./vendor/symfony/mailer/EventListener/MessageListenerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\EnvelopeTest located in ./vendor/symfony/mailer/EnvelopeTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesTransportFactory located in ./vendor/symfony/mailer/Amazon/Transport/SesTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesApiTransport located in ./vendor/symfony/mailer/Amazon/Transport/SesApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpTransport located in ./vendor/symfony/mailer/Amazon/Transport/SesHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpAsyncAwsTransport located in ./vendor/symfony/mailer/Amazon/Transport/SesHttpAsyncAwsTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesApiAsyncAwsTransport located in ./vendor/symfony/mailer/Amazon/Transport/SesApiAsyncAwsTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesSmtpTransport located in ./vendor/symfony/mailer/Amazon/Transport/SesSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillApiTransport located in ./vendor/symfony/mailer/Mailchimp/Transport/MandrillApiTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillSmtpTransport located in ./vendor/symfony/mailer/Mailchimp/Transport/MandrillSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillTransportFactory located in ./vendor/symfony/mailer/Mailchimp/Transport/MandrillTransportFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillHeadersTrait located in ./vendor/symfony/mailer/Mailchimp/Transport/MandrillHeadersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillHttpTransport located in ./vendor/symfony/mailer/Mailchimp/Transport/MandrillHttpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Tests\Transport\SesHttpTransportTest located in ./vendor/symfony/mailer/SesHttpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Postmark\Tests\Transport\PostmarkSmtpTransportTest located in ./vendor/symfony/mailer/PostmarkSmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Sendgrid\Tests\Transport\SendgridTransportFactoryTest located in ./vendor/symfony/mailer/SendgridTransportFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\Smtp\SmtpTransportTest located in ./vendor/symfony/mailer/SmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\Smtp\DummyStream located in ./vendor/symfony/mailer/SmtpTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Bridge\Amazon\Transport\SesSmtpTransport located in ./vendor/symfony/mailer/SesSmtpTransport.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Exception\UnsupportedSchemeExceptionTest located in ./vendor/symfony/mailer/UnsupportedSchemeExceptionTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Tests\Transport\RoundRobinTransportTest located in ./vendor/symfony/mailer/RoundRobinTransportTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Transport\TransportFactoryInterface located in ./vendor/symfony/mailer/TransportFactoryInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Component\Mailer\Exception\HttpTransportException located in ./vendor/symfony/mailer/HttpTransportException.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by ioniks** [comment] 2021-09-28 09:24
@kissifrot me too

**Comment by derrabus** [comment] 2021-09-28 09:25
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:25 UTC
Labels: Bug, Status: Needs Review
