### ISSUE TITLE
[Console] Broken soft wrapping

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#26293] opened 2018-02-24 03:07 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | v4.0.4 (probably older)

I have something along the lines of:

```php
$io = new SymfonyStyle($input, $output);

$io->comment(
    sprintf(
        'Loading the configuration file "<comment>%s</comment>".',
        $configPath
    )
);
```

So you can see the `<comment>` tag being used. When using `comment()` or another similar method, the text is eventually wrapped when too long:

```
 // Loading the configuration file
 // "/very/long/path/to/box.json.dist</commen
 // t>".
```

However you can see above that this breaks the `comment` tag

**Comment by Simperfit** [comment] 2018-02-24 10:09
I'm looking at this, fixing it.

Status: reviewed

**Comment by chalasr** [comment] 2019-04-07 07:51
Duplicate of #30920

**Closed by chalasr** 2019-04-07 07:51 UTC
Labels: Bug, Console, Status: Reviewed
