### ISSUE TITLE
[Translator] Catalogue fallback improvement suggestion

### ISSUE THREAD

**Issue by ShinDarth** [symfony/symfony#20471] opened 2016-11-10 11:57 UTC
I noticed that a ``$catalogue`` object instance of [MessageCatalogue](http://api.symfony.com/master/Symfony/Component/Translation/MessageCatalogue.html) has a nice ``getFallbackCatalogue()`` which returns a fallback catalogue, if any.

The method ``getFallbackCatalogue()`` returns the private field ``fallbackCatalogue`` which holds another [MessageCatalogue](http://api.symfony.com/master/Symfony/Component/Translation/MessageCatalogue.html) object.

The only problem is that `$catalogue->fallbackCatalogue->fallbackCatalogue` will ALWAYS be null, even if ``$catalogue->fallbackCatalogue`` is actually eligible to have a fallback catalogue.

It would be nice to have a way to always find a fallback of the fallback, when available.

**Comment by aitboudad** [comment] 2017-04-03 16:13
I'm not sure if there is a real benefit, you can achieve your needs using `getFallbackCatalogue`
```php
while ($catalogue = $catalogue->getFallbackCatalogue()) {
    $locale = $catalogue->getLocale();
    ....
}
```
could you please explain why `$catalogue->fallbackCatalogue->fallbackCatalogue` will ALWAYS be null ?

**Comment by ShinDarth** [comment] 2017-04-03 16:49
I don't know why but the current way it's implemented looks like to always be null

**Comment by aitboudad** [comment] 2017-04-03 17:12
I just checked on my side with a sample example and it seems to be working as expected:

```php
$translator = new Translator('de');
$translator->setFallbackLocales(array('fr', 'en'));

$catalogue = $translator->getCatalogue('de');
$fallback = $catalogue->getFallbackCatalogue()->getFallbackCatalogue();
// $fallback->getLocale() >>  'en'
```

**Comment by javiereguiluz** [comment] 2017-07-17 07:52
Closing it because @aitboudad couldn't reproduce it and there's no more feedback. @ShinDarth if the error persists and you can provide a [Symfony bug reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) please reopen it. Thanks!

**Closed by javiereguiluz** 2017-07-17 07:52 UTC
Labels: Translator
