### ISSUE TITLE
Symfony 3: form edit action error

### ISSUE THREAD

**Issue by ale8193** [symfony/symfony#25221] opened 2017-11-30 14:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.12

Hi, 

I've an issue with form edit action, my problem fires when I submit the form and there're some errors (like NotBlank() assert), the form method `$form->isValid()` catch the error and send it to the view, but the entity will be flushed in my database (with an empty value) though I do the flush only if `$form->isValid()` is true.

Here my action:

```php

    /**
        * @param Request $request
        * @param User $user
        * @Route("/admin/user/edit/{id}", name="admin_user_edit")
        * @ParamConverter("id", class="AppBundle:User")
        * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
        */
    public function userEditAction(Request $request, User $user)
    {
        if (is_null($user)) {
            return $this->redirectToRoute('homepage');
        } else {

            $em = $this->getDoctrine()->getManager();

            $form = $this->createForm(UserEditType::class, $user, array(
                'validation_groups' => array('edit')
            ));

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $em->persist($user);
                $em->flush();

                $this->addFlash('success', 'User updated successfully');

                return $this->redirectToRoute('admin_users');

            } elseif ($form->isSubmitted() && !$form->isValid()) {
                $this->addFlash('error', 'Some errors are accured');
            }

            return $this->render('admin/users.html.twig', array(
                'form' => $form->createView()
            ));
        }
    }
```

This is my `FormType`
```php
class UserEditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('id', HiddenType::class)
            ->add('email')
            ->add('username')
            ->add('locale', ChoiceType::class, array(
                'choices' => array(
                    'Italian' => 'it',
                    'English' => 'en'
                )
            ))
            ->add('isActive', null, array(
                'label' => 'Set as active',
                'attr' => array(
                    'help' => 'Imposta l\'utente come attivo'
                )
            ))
            ->add('reset', ResetType::class, array(
                'attr' => array(
                    'class' => 'btn-outline-secondary'
                )
            ))
            ->add('save', SubmitType::class, array(
                'attr' => array(
                    'class' => 'btn-primary'
                )
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
            'validation_groups' => array('edit'),
        ));
    }
}
```

And this is my `UserType` (partial)

```php
/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Questa email &egrave; gi&agrave; stata usata."
 * )
 * @UniqueEntity(
 *     fields={"username"},
 *     message="Questo username &egrave; gi&agrave; stato usato."
 * )
 */
class User implements UserInterface, \Serializable
{
    const ROLES = array(
        'ROLE_USER',
        'ROLE_ADMIN',
        'ROLE_SUPER_ADMIN',
    );

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(groups={"insert","edit"})
     * @Assert\Email(groups={"insert","edit"})
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\NotBlank(groups={"insert","edit"})
     * @Assert\Length(min=4,groups={"insert","edit"})
     */
    private $username;

    /**
     * @Assert\NotBlank(groups={"Default","password"})
     * @Assert\Length(
     *     min=4,
     *     max=4096,
     *     groups = {"insert","password"}
     *     )
     *
     */
    private $plainPassword;

    /**
     * The below length depends on the "algorithm" you use for encoding
     * the password, but this works well with bcrypt.
     *
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string", length=100, columnDefinition="enum('ROLE_USER', 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN')")
     */
    private $role;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="lastLogin", type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * @var string
     *
     * @ORM\Column(name="ipLastLogin", type="string", length=30, nullable=true, unique=true)
     */
    private $ipLastLogin;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    // getter and setter and interface methodes ...
}
```

I got this error in other edit form, maybe I'm doing something wrong

Any solution?

**Comment by xabbuh** [comment] 2017-11-30 14:33
Maybe you do not only flush the entity manager inside your controller, but also, for example, in an event listener.

**Comment by ale8193** [comment] 2017-11-30 14:37
I've only 2 event listeners, but I use them to set the current locale option getted from user settings.

In my listener code I don't do any flush

**Comment by xabbuh** [comment] 2017-11-30 14:38
Then we will need an example project that allows to reproduce your issue.

**Comment by ale8193** [comment] 2017-11-30 14:41
How can I give it to you? My project is local project.

**Comment by xabbuh** [comment] 2017-11-30 15:19
It does not need to be your real project. An example project that suffers from the same issue would be enough (see [2. Reproduce the bug](http://symfony.com/doc/current/contributing/community/reviews.html#the-bug-report-review-process)).

**Comment by ale8193** [comment] 2017-11-30 15:40
Hi tryed to reproduce the issue with a new project, but the error is not reproduced, so there are some problems in my code, but I can't find it

**Comment by ale8193** [comment] 2017-11-30 15:47
I'm going crazy!

I get the new: Entity, Form, Action and view that I've created on my new project (where there wasn't errors) and I paste these files in my project, now in my project I've the same problem I said in my first post.

Are there any configuration that could change doctrine config?

**Comment by ale8193** [comment] 2017-11-30 16:35
I finally found a solution, I added `$this->getDoctrine()->getManager()->clear()` where form is submitted but is not valid

so my edit action now is:

```php
/**
    * @param Request $request
    * @param User $user
    * @Route("/admin/user/edit/{id}", name="admin_user_edit")
    * @ParamConverter("id", class="AppBundle:User")
    * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
    */
    public function userEditAction(Request $request, User $user)
    {
        $em = $this->getDoctrine()->getManager();
       
        if (is_null($user)) {
            return $this->redirectToRoute('homepage');
        } else {

            $form = $this->createForm(UserEditType::class, $user, array(
                'validation_groups' => array('edit')
            ));

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $em->persist($user);
                $em->flush();

                $this->addFlash('success', 'User updated successfully');

                return $this->redirectToRoute('admin_users');

            } elseif ($form->isSubmitted() && !$form->isValid()) {
                $this->addFlash('error', 'Some errors are accured');

                $em->clear();  // This solve my problem
            }

            return $this->render('admin/users.html.twig', array(
                'form' => $form->createView()
            ));
        }
    }
```

The problem is solved, but I can't understand why I need this soluction

**Comment by eXtreme** [comment] 2017-12-01 12:20
I would suggest setting a breakpoint on EntityManager's flush method. This may show you the place where it's being flushed.

**Comment by ale8193** [comment] 2017-12-01 16:03
@eXtreme How can I add a breakpoint? Manually on vendor code?

**Comment by xabbuh** [comment] 2017-12-14 20:54
I am closing here for now as this does not seem to be caused by the Form component. Of course, we will reopen if new information pops up that hints otherwise.

**Closed by xabbuh** 2017-12-14 20:54 UTC
Labels: Bug, Form, Status: Needs Review, Status: Waiting feedback, Unconfirmed
