### ISSUE TITLE
Environment variables resolution in configuration is too late

### ISSUE THREAD

**Issue by cfieux** [symfony/symfony#57210] opened 2024-05-28 14:41 UTC
### Symfony version(s) affected

6.4.7

### Description

I tried to upgrade a project from Symfony 5.4 to 6.4, however I'm facing an issue with the configuration.

One of my bundles has a configuration extension I setup using the environment variable processor like this : 
```yaml
parameters:
    use_ldap: '%env(bool:LDAP_BRANCH)%'
    ldap_branch: '%env(default::string:LDAP_BRANCH)%'

MyBundleConf:
    ldap:
        enabled: '%use_ldap%'
        branch: '%ldap_host%'
```
(Using parameters to avoid error indicating some environments variable aren't used but you can set it directly to the bundle conf.)

The configuration tree node is defined like this : 
```php
->canBeEnabled()
->children()
    ->variableNode('branch')->isRequired()->cannotBeEmpty()->end()
```
(Using variable node to allow null/string/array values.)

The problem is that in the Extension implementation, I check whether the configuration is enabled or not using `Extension::isConfigEnabled` (`$this->isConfigEnabled($container, $config['ldap'])`) and it always returns `true` due to the fact that the value isn't a proper boolean but a placeholder containing a not empty string and therefore being interpreted as `true`.

On top of that, an exception indicating that the configuration value "ldap.branch" is empty is always raised because of the `ValidateEnvPlaceholdersPass` checking configuration values with fixture where the env parameter is set to an empty value.

The actual problem is that the `%env()%` variables are resolved after configuration validation and after extension compilation with fixture values or placeholders which make them completely unusable at this point.
Is there any way to force resolution at compilation time ?

Also I would like to know if it's intended to work like this (which I find odd considering the `isConfigEnabled` behaviour) and if there is some documentation/notes/anything explaining why it changed between 5.4 and 6.4.

### How to reproduce

Create a bundle with configuration and extension and use the methods and parameters I indicated above.

### Additional Context

`dev` and `prod` environment.

**Comment by stof** [comment] 2024-05-29 08:30
env placeholders (the `%env()%` syntax) are resolved at runtime by design, to allow reading the new value of the env variable for each request without having to clear the cache to rebuild the container. This is not a bug. It is the main feature of env placeholders.

The limitation is indeed that those env placeholders cannot be used in configuration settings that are used at compile time (like the `enabled` setting) rather than being used to inject them in service definitions.

I'm closing this issue in favor of https://github.com/symfony/symfony/issues/40794 which discusses an idea of introducing a new way to use env variables at compile time (forcing to clear the cache to read them again), but has no agreed solution yet.

**Closed as not planned by stof** 2024-05-29 08:30 UTC
Labels: Bug, Config, Status: Needs Review
