### ISSUE TITLE
[Cache] Apcu adapter in CLI

### ISSUE THREAD

**Issue by ossinkine** [symfony/symfony#36399] opened 2020-04-09 10:40 UTC
**Description**  

APCu cache adapter works when `apc.enabled` is on, however, in CLI mode with the` apc.enable_cli` turned off, the adapter generates a lot of messages like `Failed to save key`.
For the system cache, this was fixed in https://github.com/symfony/symfony/pull/23390 by installing `NullLogger` in the adapter.
However, the problem persists for example in this configuration:
```yaml
framework:
    cache:
        pools:
            cache.default:
                adapters:
                    - cache.adapter.apcu
                    - cache.adapter.redis
```

I suggest checking the `apc.enable_cli` option in each method, and do nothing in CLI mode, don't try to call acpu functions.
Something like this:
```php
protected function doFetch(array $ids)
{
    if ('cli' === \PHP_SAPI && !filter_var(ini_get('apc.enable_cli'), FILTER_VALIDATE_BOOLEAN)) {
        return [];
    }

    ...
}
```

If this is a good solution, I will create a PR. If not, what decision do you think would be good?

**Comment by nicolas-grekas** [comment] 2020-04-09 11:51
This would add runtime overhead for a piece of code that can be found in critical code paths.
Any other idea?

**Comment by ossinkine** [comment] 2020-04-09 12:50
If we determine can the adapter work in this environment or not in `init` method, we will only check a variable in each method and this is the smallest runtime overhead.
```php
class ApcuTrait
{
    /**
     * @var bool
     */
    private $doNothing;

    private function init(string $namespace, int $defaultLifetime, ?string $version)
    {
        $this->doNothing = 'cli' === \PHP_SAPI && !filter_var(ini_get('apc.enable_cli'), FILTER_VALIDATE_BOOLEAN);

        ...
    }

    protected function doFetch(array $ids)
    {
        if ($this->doNothing) {
            return [];
        }

        ...
    }
}
```

**Comment by Nyholm** [comment] 2020-04-13 22:20
But, isn't this warning a good thing? If Im trying to use the Apcu cache when APC is disabled, I should get a warning. 

If we mute the warnings then I might believe the cache is working.

**Comment by ossinkine** [comment] 2020-04-21 14:52
@Nyholm Actually APC is enabled for FPM but disabled for CLI which is a common behavior, not an exceptional case. So if I want to warm up the cache in CLI I expect Redis adapter warms it up but APC just be skipped and will work only for in FPM.

**Comment by Nyholm** [comment] 2020-04-21 17:45
> Actually APC is enabled for FPM but disabled for CLI which is a common behavior, not an exceptional case. 

Yes. I know. I understand that. 

> So if I want to warm up the cache in CLI I expect Redis adapter warms it up but APC just be skipped

From your point of view, I understand that it would make sense not to have a warning. 

But technically speaking; You are telling both RedisAdapter and ApcuAdapter to warmup. Since ApcuAdapter cannot warm up on your (normal) system, it has to log a warning. Same thing if your Redis server was unavailable you would expect a warning from the RedisAdapter. 

The workaround is to tell only Redis adapter to warmup or to ignore the warning.

**Comment by nicolas-grekas** [comment] 2020-04-23 21:49
Closing as duplicate of #34962, for which I opened PR #36555, please give it a try.

**Closed by nicolas-grekas** 2020-04-23 21:49 UTC
Labels: Cache
