### ISSUE TITLE
[DI] Autowiring, calls functions not called

### ISSUE THREAD

**Issue by jbdelhommeau** [symfony/symfony#26985] opened 2018-04-20 07:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

I have an abstract class (aka parent) : 

```yml
    TradeEasy\Document\Component\DocumentTemplate:
      abstract: true
      arguments:
        - '@templating.engine.twig'
        - '%document_client_code%'
```

This parent extend  `PfiDocumentTemplate`

With old syntax with no FCQN we can see with `bin/console debug:container` calls function `setTemplateDataFactory` is callable.

```yml
    document_template.pfi:
      class: TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate
      parent: TradeEasy\Document\Component\DocumentTemplate
      calls:
        - [setTemplateDataFactory, ['@TradeEasy\Document\Bundle\TemplateData\PfiTemplateDataFactory']]
```

```
Information for Service "document_template.pfi"
===============================================

 ---------------- ---------------------------------------------------------------- 
  Option           Value                                                           
 ---------------- ---------------------------------------------------------------- 
  Service ID       document_template.pfi                                           
  Class            TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Tags             -                                                               
  Calls            setTemplateDataFactory                                          
  Public           no                                                              
  Synthetic        no                                                              
  Lazy             no                                                              
  Shared           yes                                                             
  Abstract         no                                                              
  Autowired        no                                                              
  Autoconfigured   no                                                              
  Arguments        Service(templating.engine.twig)                                 
                   %env(CLIENT_CODE)%                                              
 ---------------- ---------------------------------------------------------------- 
```

With new syntax  FCQN we can see with `bin/console debug:container` no calls function. Why ?

```yml
    TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate:
      parent: TradeEasy\Document\Component\DocumentTemplate
      calls:
        - [setTemplateDataFactory, ['@TradeEasy\Document\Bundle\TemplateData\PfiTemplateDataFactory']]
```

```
Information for Service "TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate"
========================================================================================

 ---------------- ---------------------------------------------------------------- 
  Option           Value                                                           
 ---------------- ---------------------------------------------------------------- 
  Service ID       TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Class            TradeEasy\Document\Bundle\TemplateServices\PfiDocumentTemplate  
  Tags             -                                                               
  Public           no                                                              
  Synthetic        no                                                              
  Lazy             no                                                              
  Shared           yes                                                             
  Abstract         no                                                              
  Autowired        yes                                                             
  Autoconfigured   yes                                                             
  Arguments        Service(templating.engine.twig)                                 
                   %env(CLIENT_CODE)%                                              
 ---------------- ---------------------------------------------------------------- 
```

Can it be a global concern ?

```yml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $webDir : "%web_dir%"
            $documentClientCode: '%document_client_code%'

    # makes classes in src/AppBundle available to be used as services
    TradeEasy\:
        resource: '../../src/TradeEasy/*/Bundle'
```

**Comment by xabbuh** [comment] 2018-04-20 08:56
I cannot reproduce your issue. Can you create a small example application that allows to reproduce it? So we can if maybe your PSR-4 based service config overrides your explicitly configured services.

**Comment by jbdelhommeau** [comment] 2018-04-23 12:36
As you recommended, i create a small example application.

https://github.com/jbdelhommeau/sf-autowire

So i found that the worry came from loading my bundle `service.yml` config from the dependency injection load: 

https://github.com/jbdelhommeau/sf-autowire/blob/master/src/AppBundle/DependencyInjection/AppExtension.php

If file are loaded by global `config.yml` it work's : https://github.com/jbdelhommeau/sf-autowire/blob/master/app/config/config.yml#L5

**Comment by xabbuh** [comment] 2018-04-26 06:32
When your DI extension loads the file, it is processed at another time than when loading it in the main config file. So in that case the default `config/services.yaml` file overriddes your services defined in the bundle. Either drop that default config or manually load your bundle's config after the other files have been processed. I am closing here as this is the expected behaviour.

**Closed by xabbuh** 2018-04-26 06:32 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Unconfirmed
