### ISSUE TITLE
[Form][Twig][Locale] using "trans" filter or block inside a {% block field_label %} throws an exception

### ISSUE THREAD

**Issue by adamziel** [symfony/symfony#6428] opened 2012-12-19 19:12 UTC
My code is:

``` jinja
{% form_theme form _self %}
{% block field_label %}
    {{"a"|trans}}
{% endblock field_label %}
```

when I request the controller, I'm experiencing the following error:

`Variable "__internal_ed4b1e844d24a1e59b0ce765925bc0b50be19e95" does not exist in Bundle:Controller:view.html.twig at line 7`

The same thing happens if I place the |trans within:
- `field_label`
- `field_widget`
- `field_errors`
- `field_row`
- ... probably some other forms-related blocks too

But it does not happen if I use `|trans` in a "normal" block like `{% block body %}`

I receive the same error when using `{% trans %}` in any of the blocks listed above

I use Symfony version from branch 2.1 commited in `055daa9` (but the error was present on `c6bd807` too)
I use Twig version commited in `2757f48` (but the error was present on `f095f3a` too)

Am I doing something wrong there or is there a bug? I did not find any similar report and I bet quite a few people is using trans tag/filter inside a form theme

**Comment by kniziol** [comment] 2015-12-29 16:03
Same problem here. Replacing
```twig
{% trans_default_domain translation_domain %}
```
with
```twig
{% trans_default_domain 'domain_as_string' %}
```
resolves the problem

**Comment by xabbuh** [comment] 2018-09-23 08:00
I am not sure I fully understand the issue here? Is it about the usage of the `trans_default_domain` tag? Is it about form themes as I understand the initial description? A small reproducible example application would help understanding if this is still an issue (might as well have been resolved in the meantime).

**Comment by xabbuh** [comment] 2018-10-05 16:03
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed by xabbuh** 2018-10-05 16:03 UTC
Labels: Bug, Form, Status: Waiting feedback, TwigBridge
