### ISSUE TITLE
Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony#29390] opened 2018-11-30 13:06 UTC
**Symfony version(s) affected**: 4.2.0

**Description**  
When upgrading to Symfony 4.2.0 via composer, the error "Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist" appears.

This is due to the fact that the file Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration.php (line 667), has reflection with the concerned class, but this class is no longer integrated in doctrine/dbal package (in latest version 2.8), but it's in the doctrine/common package.

**How to reproduce**  
Create a symfony project in 4.1.8 with doctrine dbal in dependency (and only that doctrine package).
Update to symfony 4.2.

**Possible Solution**  
Add the doctrine/common package in composer.json.

**Comment by webnet-fr** [comment] 2018-11-30 15:57
Hi @QuentinCurtet.

The problem is not in Symfony. It is DoctrineBundle that cannot be configured without `doctrine/common` being installed and it clearly seems like a bug.

In fact as far as I know you don't need `doctrine/common` if you're only using `doctrine/dbal`. Nevertheless you are not able to configure the DoctrineBundle without it.

I will open PR there to discuss possible solutions.

Cheers.

**Comment by QuentinCurtet** [comment] 2018-11-30 16:08
Hi @webnet-fr 

Thanks for your answer, i was not sure if the problem was in Symfony or not, because it was on the symfony upgrade and not on the doctrine dbal upgrade.

Thanks for the PR, i will take a look at it.

**Comment by nicolas-grekas** [comment] 2018-11-30 21:33
Thank you all for you help here. Closing as this is not a Symfony issue.

**Closed by nicolas-grekas** 2018-11-30 21:33 UTC
