### ISSUE TITLE
Should the HttpClient method getInfo() return up to date information for curl requests?

### ISSUE THREAD

**Issue by rp3e11** [symfony/symfony#40579] opened 2021-03-25 12:22 UTC
Hi,

I am using the HttpClient in symfony  5.2. It already is async in a sense that the request() and the getContent() method are separated. Yet the getContent() method is blocking and will only return when the request is completed. In order to do other work while I am waiting for the response I tried to someting similar to the following code segment.
```php
do {
    foreach($tasks as $task) {
        if (isset($task->request) && !$task->isFinished()) {
            // call getInfo() which is nonblocking 
            $info = $task->request->getInfo();
            switch($info['status_code']) {
                case 0:
                    break;
                case 200:
                    $task->request->getContent();
                    // do some work
                    break;
                // hande other cases
            }
        } elseif (....) {
            // other heavy tasks
        } 
   }
} while (work_to_do)
```
In essence I only want to call getContent(), once the request is completed. In order to determine whether the request is completed I wanted to call getInfo() and check the status code. However, in my tests the status code remains 0 until I abort the code. If I instead call the getContent() method the response is returned after 20 seconds max and a call to getInfo() returns the expected status code. 

It seems as if getInfo() only delivers the updated status code, once getContent() is called. Under the hood (in Symfony\Component\HttpClient\Response\CurlResponse.php) the getInfo() method calls curl_getinfo($this->handle), so I was wondering whether this is a limitation of php curl? Are there other Response implementations available where the above code would work.

Is this the expected behavior, or am I doing something wrong? 
If this is the expected behaviour the info box in https://symfony.com/doc/current/http_client.html#processing-responses stating "$response->getInfo() is non-blocking: it returns live information about the response. Some of them might not be known yet (e.g. http_code) when you’ll call it." seems misleading.

Thanks in advance

**Comment by nicolas-grekas** [comment] 2021-03-25 12:39
This is expected behavior, you're going to have to use the `$client->stream()` method to achieve what you want, see [doc](https://symfony.com/doc/current/http_client.html#streaming-responses) and maybe https://speakerdeck.com/nicolasgrekas/symfony-httpclient-what-else.

I'm closing because we use this issue tracker for actual bugs or RFCs, but this is a support request.

`getInfo()` just reads the status of the response, but it doesn't "advance" the request/response itself.
In PHP, there is no background process. That means that something must read/write eg the network buffers for anything to happen. That's what `getContent()` does, but also `$client->stream()` or other methods.

**Closed as completed by nicolas-grekas** 2021-03-25 12:39 UTC
Labels: HttpClient
