### ISSUE TITLE
DateTimeToLocalizedStringTransformer ignoring time during reverse transform between timezones

### ISSUE THREAD

**Issue by rcwsr** [symfony/symfony#20806] opened 2016-12-07 09:36 UTC
Updating from symfony v2.8.9 to v.2.8.10 one of my project's tests has started to fail, it looks like it was introduced here https://github.com/symfony/symfony/commit/c951bb6e970a41bcd2dd81a70558f560c0199659

I'm not entirely sure if it's a bug with symfony or my project, as it looks like that commit purposely ignores datetime strings without a time.

I have reproduced my project's failing test in DateTimeToLocalizedStringTransformerTest: https://github.com/rcwsr/symfony/commit/f605b8516e73d65f80b2d2e73ddc4ef129b882d9

```
1) Symfony\Component\Form\Tests\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformerTest::testReverseTransformDateWithoutTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1420088400'
+'1420070400'
```

**Comment by Jean85** [comment] 2016-12-14 08:55
The reverse transformation ignores text without time because time zones influences just time. If you are inputting a date, you wouldn't like that to be changed because the system is implying 00:00:00 and that means the previous day in a latter timezone.

Maybe the behavior is not perfect, but that stems from the fact that PHP doesn't have a `\Date` type, so we are forced to set a time somewhere; but if we changed it, it would fail otherwise with this example:

```
    public function testReverseTransformDateWithoutTime()
    {
        $transformer = new DateTimeToLocalizedStringTransformer(
            'UTC',
            'America/Louisville',
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::GREGORIAN,
            'yyyy-MM-dd'
        );

        $date = new \DateTime('2015-01-01T05:00:00+00:00');
        $this->assertEquals(
            $date->format('Y-m-d'),
            $transformer->reverseTransform('2015-01-01')->format('Y-m-d')
        );
    }
```
..which is the "normal" behavior of a programmer: using implied timezone (which probably isn't UTC).

**Comment by issei-m** [comment] 2017-01-25 14:58
This problem seems to be caused by IntlDateFormatter stubs.
In my env, a generated timestamp completely differs between stubs and native. A former one seems to not deal with the timezone something properly.

/cc @webmozart @HeahDude

**Comment by HeahDude** [comment] 2017-01-25 22:42
@issei-m this issue should have been fixed in https://github.com/symfony/symfony/pull/21218 as 2.7.23, 2.8.16, 3.1.9, 3.2.2, could you please confirm?

**Comment by Jean85** [comment] 2017-01-25 23:50
Damn, this reverses a previous PR where I was involved. I understand why is that like that, but now I'm just desiring so bad a `\Date` object in PHP...

**Comment by issei-m** [comment] 2017-01-26 15:25
@HeahDude I don't think so. As before I said, this problem doesn't seem to be `DateTimeToLocalizedStringTransformer`'s matter. This problem is caused by `\Symfony\Component\Intl\DateFormatter\IntlDateFormatter` in Intl component. (So you wouldn't encounter if you're using a native one)

See following snippet - the POC for my opinion on my env (PHP 7.0):

```php
$pattern = 'yyyy-MM-dd';

$nativeIntlDf = new \IntlDateFormatter('en', \IntlDateFormatter::FULL, \IntlDateFormatter::FULL, 'UTC', \IntlDateFormatter::GREGORIAN, $pattern);
$polyfillIntlDf = new \Symfony\Component\Intl\DateFormatter\IntlDateFormatter('en', \IntlDateFormatter::FULL, \IntlDateFormatter::FULL, 'UTC', \IntlDateFormatter::GREGORIAN, $pattern);

var_dump(
    $nativeIntlDf->parse('2017-01-01'),  // 1483228800
    $polyfillIntlDf->parse('2017-01-01') // 1483196400
);
```

- A former one (`1483228800`) is care about a timezone well - it's `2017/01/01 00:00:00` in UTC
- But a latter one (`1483196400`) doesn't - it's `2016-12-31 15:00:00` in UTC

This timestamp is passed to `gmdate('Y-m-d')` at [here](https://github.com/symfony/symfony/blob/b9b6ebd643cfb65bae14c6fc3d9339dbcd1c9210/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L132), eventually the result of a latter one is `DateTime('2016-12-31 00:00:00', 'UTC')`.
As you can see, although this datetime object is set specific TZ [after this](https://github.com/symfony/symfony/blob/b9b6ebd643cfb65bae14c6fc3d9339dbcd1c9210/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L139), the final date would end up with **wrong**.

So we have to fix `\Symfony\Component\Intl\DateFormatter\IntlDateFormatter`, at least as well as native works IMHO.

Regards.

**Comment by issei-m** [comment] 2017-01-27 02:41
I've just opened a new issue about this problem.

**Comment by HeahDude** [comment] 2017-01-27 07:16
Ok, thanks! Let's close here then as the original issue is about the transformer and has been fixed by https://github.com/symfony/symfony/pull/21218.

**Closed** 2017-01-27 13:13 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed
