### ISSUE TITLE
Constraint REGEX `htmlPattern` cannot be a boolean.

### ISSUE THREAD

**Issue by cavasinf** [symfony/symfony#53807] opened 2024-02-06 11:14 UTC
### Symfony version(s) affected

6.4.3

### Description

Doc says that we can pass `false` to `htmlPattern` parameter, but in reality this is not the case.

> Setting htmlPattern to false will disable client side validation.

https://symfony.com/doc/6.4/reference/constraints/Regex.html#htmlpattern

Class:

https://github.com/symfony/validator/blob/03b0c75d7d3df1ef9a0fd9fb8db1e86f83ffa2bb/Constraints/Regex.php#L39

### How to reproduce

1. Add assert constraint to an entity:
```php
use Symfony\Component\Validator\Constraints as Assert;

// ...

#[Assert\Regex(
    pattern: '/^[a-z]+(-[a-z]+)*$/',
    htmlPattern: false,
)]
private ?string $slug = null;
```

2. Run phpstan
3. Error
```
------ --------------------------------------------------------------------------------------------------------------------------------------- 
  Line   App/Entity/MyEntityphp                                                                                             
 ------ --------------------------------------------------------------------------------------------------------------------------------------- 
  33     Parameter $htmlPattern of attribute class Symfony\Component\Validator\Constraints\Regex constructor expects string|null, false given.  
 ------ ---------------------------------------------------------------------------------------------------------------------------------------
```

### Possible Solution

Allow `boolean` or `false` type on `htmlPattern` parameter.

**Comment by stof** [comment] 2024-02-06 11:25
Looking at the code, you can also set it to an empty string for that

I'm not sure how we want to solve this inconsistency between the type that has been added in the code and the documentation.

Looking in the history, support for passing `false` to disable the HTML pattern was covered by tests when it was introduced in https://github.com/symfony/symfony/commit/6f9eda95820a9d7469c12b471fb3b816bc9f7763 but this case was lost when refactoring the tests in https://github.com/symfony/symfony/commit/bf006f52027f846863bcb7e7dcd112f115774481

**Comment by cavasinf** [comment] 2024-02-07 09:14
> you can also set it to an empty string for that

Ok for a "workaround", but I don't think it's a "normal way" to think if you want this behavior.
IMO the false option as recommended by the doc is a good configuration.

**Comment by alexandre-daubois** [comment] 2024-03-29 14:48
The problem is `Regex` is not final and `htmlPattern` is public so its type cannot be changed without breaking backward compatibility. _Sometimes_ BC breaks are accepted between minor versions but this is pretty rare. I think the best thing to do here is to address this to the documentation. I indeed agree with you that providing an empty string is not the best option and being able to pass `false` would be better, but I'm afraid this has to wait for Symfony 8.0 😄

**Comment by javiereguiluz** [comment] 2024-08-02 15:19
The related docs have been fixed in https://github.com/symfony/symfony-docs/pull/20089

I reopen the issue because I don't know if there are still some code changes that need to be made to fix this. Thanks.

**Comment by xabbuh** [comment] 2024-08-02 16:03
Let’s close here. Since the constraint class isn’t final changing the property type isn’t easily possible and thus not worth the effort IMO.

**Closed as completed by xabbuh** 2024-08-02 16:03 UTC
Labels: Validator, Bug, Status: Needs Review
