### ISSUE TITLE
Error while installing profiler

### ISSUE THREAD

**Issue by stormherz** [symfony/symfony#25988] opened 2018-01-31 14:48 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Installing profiler on a newly created symfony app fails with the following error, though profiler is installed successfully.

```
vagrant@local:/var/www/projectname$ composer require --dev profiler
Using version ^1.0 for symfony/profiler-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Warning:  Uncaught ErrorException: Warning: require(/var/www/projectname/var/cache/dev/ContainerIPOxjl0/getConsole_ErrorListenerService.php): failed to open stream: No such file or directory in /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php:346
!!  Stack trace:
!!  #0 /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php(346): require()
!!  #1 /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php(427): ContainerIPOxjl0\srcDevDebugProjectContainer->load('/var/www/projectname/...')
!!  #2 /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php(229): ContainerIPOxjl0\srcDevDebugProjectContainer->ContainerIPOxjl0\{closure}()
!!  #3 /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php(61): Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('console.error')
!!  #4 /var/www/projectname/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(250): Symfony\Component\EventDispatcher\EventDispatcher->getListeners('console.error')
!!  #5 /var/www/ba in /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php on line 346
!!  PHP Stack trace:
!!  PHP   1. {main}() /var/www/projectname/bin/console:0
!!  PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/projectname/bin/console:39
!!  PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/projectname/vendor/symfony/console/Application.php:143
!!  PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/projectname/vendor/symfony/framework-bundle/Console/Application.php:72
!!  PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/projectname/vendor/symfony/console/Application.php:241
!!  PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/projectname/vendor/symfony/framework-bundle/Console/Application.php:84
!!  PHP   7. Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher->dispatch() /var/www/projectname/vendor/symfony/console/Application.php:889
!!  PHP   8. Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher->preProcess() /var/www/projectname/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:134
!!  PHP   9. Symfony\Component\EventDispatcher\EventDispatcher->getListeners() /var/www/projectname/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:250
!!  PHP  10. Symfony\Component\EventDispatcher\EventDispatcher->sortListeners() /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php:61
!!  PHP  11. ContainerIPOxjl0\srcDevDebugProjectContainer->ContainerIPOxjl0\{closure}() /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php:229
!!  PHP  12. ContainerIPOxjl0\srcDevDebugProjectContainer->load() /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php:427
!!  PHP Fatal error:  ContainerIPOxjl0\srcDevDebugProjectContainer::load(): Failed opening required '/var/www/projectname/var/cache/dev/ContainerIPOxjl0/getConsole_ErrorListenerService.php' (include_path='.:/usr/share/php') in /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php on line 346
!!  PHP Stack trace:
!!  PHP   1. {main}() /var/www/projectname/bin/console:0
!!  PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/projectname/bin/console:39
!!  PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/projectname/vendor/symfony/console/Application.php:143
!!  PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/projectname/vendor/symfony/framework-bundle/Console/Application.php:72
!!  PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/projectname/vendor/symfony/console/Application.php:241
!!  PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/projectname/vendor/symfony/framework-bundle/Console/Application.php:84
!!  PHP   7. Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher->dispatch() /var/www/projectname/vendor/symfony/console/Application.php:889
!!  PHP   8. Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher->preProcess() /var/www/projectname/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:134
!!  PHP   9. Symfony\Component\EventDispatcher\EventDispatcher->getListeners() /var/www/projectname/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:250
!!  PHP  10. Symfony\Component\EventDispatcher\EventDispatcher->sortListeners() /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php:61
!!  PHP  11. ContainerIPOxjl0\srcDevDebugProjectContainer->ContainerIPOxjl0\{closure}() /var/www/projectname/vendor/symfony/event-dispatcher/EventDispatcher.php:229
!!  PHP  12. ContainerIPOxjl0\srcDevDebugProjectContainer->load() /var/www/projectname/var/cache/dev/ContainerIPOxjl0/srcDevDebugProjectContainer.php:427
!!  15:21:51 CRITICAL  [php] Fatal Compile Error: ContainerIPOxjl0\srcDevDebugProjectContainer::load(): Failed opening required '/var/www/projectname/var/cache/dev/ContainerIPOxjl0/getConsole_ErrorListenerService.php' (include_path='.:/usr/share/php') ["exception" => Symfony\Component\Debug\Exception\FatalErrorException { …}] []
!!  
!!  In srcDevDebugProjectContainer.php line 346:
!!                                                                                 
!!    Compile Error: ContainerIPOxjl0\srcDevDebugProjectContainer::load(): Failed  
!!     opening required '/var/www/projectname/var/cache/dev/ContainerIPOxjl0/getConsole  
!!    _ErrorListenerService.php' (include_path='.:/usr/share/php')                 
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  

Installation failed, reverting ./composer.json to its original content.
```

**Comment by javiereguiluz** [comment] 2018-02-05 14:20
I can't reproduce this error. I've just created the project and the installation worked:

```
$ composer create symfony/skeleton issue_25988
  Installing symfony/skeleton (v4.0.5)
    - Installing symfony/skeleton (v4.0.5): Loading from cache
    - Installing symfony/flex (v1.0.68): Loading from cache
    [...]
    - Installing symfony/dotenv (v4.0.4): Loading from cache

$ cd issue_25988/

$ composer require --dev profiler
  Using version ^1.0 for symfony/profiler-pack
  Package operations: 8 installs, 0 updates, 0 removals
    - Installing twig/twig (v2.4.4): Loading from cache
    - Installing symfony/polyfill-php72 (v1.7.0): Loading from cache
    - Installing symfony/var-dumper (v4.0.4): Loading from cache
    - Installing symfony/twig-bridge (v4.0.4): Loading from cache
    - Installing symfony/web-profiler-bundle (v4.0.4): Loading from cache
    - Installing symfony/twig-bundle (v4.0.4): Loading from cache
    - Installing symfony/stopwatch (v4.0.4): Loading from cache
    - Installing symfony/profiler-pack (v1.0.3): Loading from cache
  Symfony operations: 2 recipes (afb6eaf8f44b72907f9ddd40ebef0c70)
    - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
    - Configuring symfony/twig-bundle (>=3.3): From github.com/symfony/recipes:master
  Executing script cache:clear [OK]
  Executing script assets:install --symlink --relative public [OK]
```

We haven't received more comments about this error, so it was probably a temporary error. That's why I'm closing this issue but @stormherz if you have more information about how to reproduce the error, please reopen it. Thanks!

**Closed by javiereguiluz** 2018-02-05 14:20 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle
