### ISSUE TITLE
Please add .gitattributes files and fix line endings

### ISSUE THREAD

**Issue by dereuromark** [symfony/symfony#13521] opened 2015-01-26 01:09 UTC
In particular, https://github.com/symfony/Config has windows line endings and no .gitattributes file to fix it, causing this on each composer update (in this case on debian 6):
```
  - Updating symfony/config 2.6.x-dev (d94f222 => a9f781b)
    The package has modified files:
    M .gitignore
    M CHANGELOG.md
    M ConfigCache.php
    M Definition/ArrayNode.php
    M Definition/BaseNode.php
    M Definition/BooleanNode.php
    M Definition/Builder/ArrayNodeDefinition.php
    M Definition/Builder/BooleanNodeDefinition.php
    M Definition/Builder/EnumNodeDefinition.php
    M Definition/Builder/ExprBuilder.php
```

It is as easy as adding a file like [this](https://github.com/cakephp/cakephp/blob/master/.gitattributes) to each file. It doesn't even have to be this verbose.
In its shortest form it is just
```
# Define the line ending behavior of the different file extensions
# Set default behaviour, in case users don't have core.autocrlf set.
* text=auto
* text eol=lf
```
In case there are no exe, bat or binary files around this totally suffices.

But you could also just fix the line endings to windows ones again (or both ideally).

**Comment by jrobeson** [comment] 2015-01-26 01:10
if it really does have windows line endings, then it should be fixed in the source.

**Comment by dereuromark** [comment] 2015-01-26 01:11
Was just pointing out that if the .gitattributes file was present it would be auto-fixed eventually.
But yeah, fixing it in source is sure the first thing to be done.

**Comment by cordoval** [comment] 2015-01-26 01:53
I couldn't visualize these line endings transforming several of those mentioned files above on 2.6 and on master of symfony/symfony with vim and using :w ++ff=unix. I have tried dos2unix on those files also on the cloned Config component alone and it did not show any difference.

In addition to this I have tried https://help.github.com/articles/dealing-with-line-endings/ on all symfony repository and the only file that gave issues with line endings with a ```*.php text eol=crlf``` setting were:

```bash
 M src/Symfony/Component/Form/Resources/translations/validators.bg.xlf
 M src/Symfony/Component/Validator/Resources/translations/validators.bg.xlf
```

could it be that these differences are the result of some other thing?

**Comment by dereuromark** [comment] 2015-01-26 12:47
@cordoval I don't know how you checked, but it is possible that the autocrlf setting of the system can check it out wrongly (either on my or your side, and also cross OS specific). Thus it is even more important to overwrite that and to assert that the files are not modified wrongly on checkout/clone.

**Comment by cordoval** [comment] 2015-01-26 12:50
could you please paste your configuration on your global ~/.gitconfig ? I think the problem is on your side :baby: perhaps

**Comment by fabpot** [comment] 2015-02-11 14:32
The line-ending problems were fixed recently for the files mentioned by @cordoval

**Closed by fabpot** 2015-02-11 14:32 UTC
