### ISSUE TITLE
TagAwareAdapter::invalidateTags() was not working when it was wrapped ArrayAdapter

### ISSUE THREAD

**Issue by rain-noise** [symfony/symfony#37950] opened 2020-08-26 07:01 UTC
**Symfony version(s) affected**: 4.4.11

**Description**  
TagAwareAdapter::invalidateTags() was not working when it was wrapped ArrayAdapter.

**How to reproduce**  
```php
    public function testInvalidateTagsByTagAwareAdapterWrappedArrayAdapter()
    {
        $cache = new TagAwareAdapter(new ArrayAdapter());
        $item  = $cache->getItem('foo');
        $item->set(1);
        $item->tag('bar');
        $cache->save($item);
        $this->assertSame(1, $cache->getItem('foo')->get());
        $this->assertSame(true, $cache->invalidateTags(['bar']));
        $this->assertSame(null, $cache->getItem('foo')->get()); // This code should be pass, but failed.
    }
```

**Possible Solution**  
I think that the cause of this issue is due to the following factors:
1. TagAwareAdapter will store "{tag}\0tag\0" cache item with expiry = 0.
2. ArrayAdaputer::save() does not treat expiry = 0 as indefinite(=PHP_INT_MAX).
   line 127: if (null !== $expiry && $expiry <= microtime(true)) {
   line 140: $this->expiries[$key] = null !== $expiry ? $expiry : PHP_INT_MAX;

So i think possible solution is ArrayAdaputer::save() treat expiry = 0 as indefinite.

**Comment by nicolas-grekas** [comment] 2020-08-26 07:33
Thanks for the report. I'm closing as duplicate of #37667, fixed in #37671, to be released soon.

**Closed by nicolas-grekas** 2020-08-26 07:33 UTC
Labels: Bug, Status: Needs Review
