### ISSUE TITLE
[DIC] Support for deprecated services aliases

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#25057] opened 2017-11-20 19:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

### Introduction
Symfony 3.3 introduced a convention of naming services with their FQCN. The update pathway for legacy applications is simple: just start using new naming convention and slowly all services will get new names.

### The problem
While refactoring parts of the application it's worth to clean up a little bit. One of the steps which I perform is ensuring services are names by their FQCNs (which simplifies the configuration due to autoregistration). However, especially for public services, I cannot ensure old names aren't used somewhere.

### Solution
Long time ago I assumed `deprecated` tag can be used on aliases - 4 proved me wrong nicely throwing ` The configuration key "deprecated" is unsupported`. 
What if we actually introduced `deprecated` key on aliases to mark them as deprecated while the service itself stays non-deprecated?

**Comment by theofidry** [comment] 2017-11-21 00:40
Duplicate of https://github.com/symfony/symfony/issues/24507

**Closed** 2017-11-21 09:11 UTC
