### ISSUE TITLE
Can't select error message on new exceptions in firefox

### ISSUE THREAD

**Issue by webworksnbg** [symfony/symfony#22992] opened 2017-05-31 14:12 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.3.0

I've just updated to the current symfony version and seen the new exception design - why I can't select the error message with my mouse? That's not nice... 

![screenshot-flowfusion local-2017-05-31-16-11-06](https://cloud.githubusercontent.com/assets/24891375/26636034/c90e4f70-461b-11e7-934b-8d34a65f638d.png)

**Comment by ro0NL** [comment] 2017-05-31 14:56
Yeah... see https://github.com/symfony/symfony/issues/22957 :)

**Comment by javiereguiluz** [comment] 2017-05-31 15:16
@webworksnbg thanks for reporting this! You are right ... but I'm closing this as a duplicate of #22957. The good news is that we have a fix ready and it will be merged soon. Thanks!

**Closed by javiereguiluz** 2017-05-31 15:16 UTC
