### ISSUE TITLE
Missing classes error while using composer with --no-dev

### ISSUE THREAD

**Issue by benblub** [symfony/symfony#41602] opened 2021-06-08 07:23 UTC
**Symfony version(s) affected**: 5.3.1

**Description**

**How to reproduce**
run `composer install --no-dev` <- the no-dev Flag cause the Problem

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the prod environment with debug false                                                        
!!  
!!  
!!  In ClassExistenceResource.php line 74:
!!                                                                                                            
!!    Class "Doctrine\Bundle\FixturesBundle\Fixture" not found while loading "App\DataFixtures\AppFixtures".  
!!                                                                                                            
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```
**Additional context**
This Problem happen since i upgraded to Version 5.3.1 and PHP 8.0.3
When the --no-dev flag isset the "dev" bundles are not installed by composer. In .env you can set the APP_ENV=prod and dev Bundles in config are set to `Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],` <- this is just an examble Bundle the error happen for all Libs in composer.json which are listed in require-dev. Missing TestCase Class from PHPUnit as examble if its listed in require-dev and this Bundle is never written in bundles.php

**Comment by xabbuh** [comment] 2021-06-08 08:30
Are you sure that the `APP_ENV` environment variable is set to `prod` when you run `composer install --no-dev`?

**Comment by apfelbox** [comment] 2021-06-08 08:37
I have the exact same issue.

I was adding a doctrine type in a bundle extension with:

<details>
<summary>Here are the specifics of my error</summary>

```php
class MyBundleExtension extends BundleExtension implements PrependExtensionInterface
{
	/**
	 * @inheritDoc
	 */
	public function prepend (ContainerBuilder $container) : void
	{
		if ($container->hasExtension("doctrine"))
		{
			$container->prependExtensionConfig("doctrine", [
				"dbal" => [
					"types" => [
						SerializedType::NAME => SerializedType::class,
					],
				],
			]);
		}
	}
}
```

The `SerializedType` is just

```php
use Doctrine\DBAL\Types\Type;

class SerializedType extends Type
{
    // ...
}
```
</details>

I encountered the exact same problem. If `doctrine/dbal` is not installed, the config will not be prepended. So far, so good.


However, the autoconfiguration of the DI tried to autoconfigure this type and failed with the exact same error message (for the `Type` class in my case of course).
This worked in 5.2.x and did now fail in 5.3.x

**Comment by benblub** [comment] 2021-06-08 08:41
> Are you sure that the `APP_ENV` environment variable is set to `prod` when you run `composer install --no-dev`?

yes first its allready outputed in the error msg `// Clearing the cache for the prod environment with debug false`
2. i dumped directly before calling composer install -> `env | grep APP_ENV` was prod

**Comment by xabbuh** [comment] 2021-06-08 09:12
Can any of you create a small example application that allows to reproduce this issue?

**Comment by apfelbox** [comment] 2021-06-08 09:23
@xabbuh does that work for you? https://github.com/apfelbox/symfony-issue-41602

**Comment by brammers** [comment] 2021-06-08 21:02
Looks like a duplicate of #41548

**Comment by apfelbox** [comment] 2021-06-08 22:53
Yep, these are the same as it seems.

**Closed as completed** 2021-06-09 07:00 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback
