### ISSUE TITLE
Can't update boolean type fields on entity when handleRequest() is called on the form object

### ISSUE THREAD

**Issue by yellowmamba** [symfony/symfony#17026] opened 2015-12-16 06:58 UTC
Hi all,

I have a weird issue that I can't figure out why.

I have an entity `User`, which has a boolean field `enabled`. When I try to update the entity with a form, all other non-boolean fields are updated, only the booleans are always set to true. I dumped `$request->request->get('form_name')`, the result looks like this:

```
UserController.php on line 108:
array:1 [▼
  "form_name" => array:12 [▼
    ...
    "enabled" => "0"
    ...
  ]
]
```

And I call `$form->handleRequest($request)`, then I dumped the entity, expecting it to be updated.

```
UserController.php on line 109:
User {#3066 ▼
  ...
  #enabled: true
  ...
```

I don't really understand now, it happens to this particular form, I haven't had such a problem before, and I run out of ideas as to why it happens.

As an interim solution, I set the boolean values directly on the entity after the `handleRequest()` call. Something like this:

```
$form->handleRequest($request);

// set the boolean fields on the entity because handleRequest can't update these fields for some reason
$user->setEnabled(!!$data['form_name']['enabled']);
```

**Comment by xabbuh** [comment] 2015-12-16 09:57
How does your form look like?

**Comment by yellowmamba** [comment] 2015-12-16 11:21
My form has this boolean field as
```php
$builder
    ...
    ->add('enabled', 'checkbox')
    ...
```

My code in the controller looks  like this:

```php
$form = $this->createForm(new UserType, $user); // render the form with existing entity
$request->request->set('form_name', $data); // where $data is like ['field1' => 'value1', 'field2' => 'value2']
$form->handleRequest($request); // where entity $user should have been updated
if ($form->isValid()) {
    $this->flush();
}
```

**Comment by xabbuh** [comment] 2015-12-17 11:45
Could you create a fork of the Standard Edition that helps to reproduce your issue?

**Comment by stof** [comment] 2015-12-17 11:46
@yellowmamba how does your data looks like ?

**Comment by yellowmamba** [comment] 2015-12-18 00:27
@stof you meant `$data` in my code? It's just `$request->request->all()`. The actual form field data is in `$data['form_name']` array.

**Comment by ihsanudin** [comment] 2015-12-29 02:31
@yellowmamba : 

```lang=php
$request->request->set('form_name', $data);
```

Where is `$data` come from?

**Comment by yellowmamba** [comment] 2016-01-01 08:15
@ihsanudin Why? It doesn't matter, the point is to set an array with the key `form_name` in the request so it can be processed in `handleRequest`.

**Comment by HeahDude** [comment] 2016-02-11 08:30
Hi @yellowmamba, which version of symfony are you using ?

**Comment by unexge** [comment] 2016-02-11 10:54
`CheckboxType` [uses](https://github.com/symfony/symfony/blob/582f4753a343f230fbe18b4e9a0747d48351ddfb/src/Symfony/Component/Form/Extension/Core/Type/CheckboxType.php#L35) `BooleanToStringTransformer`, and in `BooleanToStringTransformer`'s `reverseTransform`, if given value is string, its [always](https://github.com/symfony/symfony/blob/582f4753a343f230fbe18b4e9a0747d48351ddfb/src/Symfony/Component/Form/Extension/Core/DataTransformer/BooleanToStringTransformer.php#L73) `return true`. Because of that, if any checkbox field has a string value, its always gonna be true. Whether is `"1"`, `"true"`, `"yes"` or `"0"`, `"false"`, `"no"`.

Instead of simply returning true, we can use something like that;

```php
/**
 * Transforms a string into a Boolean.
 *
 * @param string $value String value.
 *
 * @return bool Boolean value.
 *
 * @throws TransformationFailedException If the given value is not a string.
 */
public function reverseTransform($value)
{
    if (null === $value) {
        return false;
    }

    if (!is_string($value)) {
        throw new TransformationFailedException('Expected a string.');
    }

    return filter_var($value, FILTER_VALIDATE_BOOLEAN);
}
```

Note: When browser submit post data its omit the falsy values, but when the post data send with something like javascript, its not omit the falsy values.

**Comment by Tobion** [comment] 2016-02-13 16:19
Closing as duplicate of #15054

**Closed by Tobion** 2016-02-13 16:19 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed
