### ISSUE TITLE
symfony/filesystem:v5.1.9 dumpFile throws always Exception "No such file or directory"

### ISSUE THREAD

**Issue by ynnoig** [symfony/symfony#39291] opened 2020-12-02 18:48 UTC
**Symfony version(s) affected**: symfony/filesystem:v5.1.9 

**Description**  
The finally statement [here](https://github.com/symfony/filesystem/compare/v5.1.8...v5.1.9#diff-5396047df440ad0926f1edca6fdaca73124ca539016e41425172f921b89641cfR669) is always executed from php. 
This cause that for every dumpFile method call throws an exception "**No such file or directory**". 
This because [here](https://github.com/symfony/filesystem/compare/v5.1.8...v5.1.9#diff-5396047df440ad0926f1edca6fdaca73124ca539016e41425172f921b89641cfR668 ) the rename function overwrite the tmpFile in filename and the tmpFile at this moment does not exists more.

**How to reproduce**  
`$this->filesystem->dumpFile(
            $this->targetDirectory . DIRECTORY_SEPARATOR . $fileName,
            $content
        );`

**Possible Solution**  
Maybe just a **catch** instead a **finally** statement?

**Additional context**  
Nothing.

**Comment by chalasr** [comment] 2020-12-02 19:37
Fixed in https://github.com/symfony/symfony/pull/39243, which will be part of the v5.1.10 release.
Thanks for the report.

**Closed as completed by chalasr** 2020-12-02 19:37 UTC
Labels: Bug, Filesystem, Status: Needs Review

**Comment by jderusse** [comment] 2020-12-02 19:41
Hello, 

You have an error_handler convert **silenced** error into exception.

duplicate of #39287, #39235, #39227
Fixed by #39243

**Comment by tienbuide** [comment] 2020-12-15 15:06
> Fixed in #39243, which will be part of the v5.1.10 release.
> Thanks for the report.

Hey @chalasr,

do you know when v5.1.10 (or v5.2.1?) will be released?

thanks in advance :)

**Comment by chalasr** [comment] 2020-12-15 16:41
@tienbuide By the end of the month :)
