### ISSUE TITLE
Using getBlockPrefix with null creates invalid html5 tag on form

### ISSUE THREAD

**Issue by ktwbc** [symfony/symfony#19818] opened 2016-09-01 16:05 UTC
There are use cases for returning null in a FormType definition with the call getBlockPrefix, for example to for a GET form to only use the form values in the resulting URL without a form name inside square brackets.

A typical case would be to simply add

```
 public function getBlockPrefix()
{
    return null;
}
```

to the formType.

However, this name is also being used to build the opening <form> tag when using 
`{{ form_start(form) }}`
in the twig template. As a result of the null name, your form tag is created as:

``` html
<form name="" method="get">
```

The empty name "" is invalid HTML5 and will fail an HTML scan. 

It would be preferable to simply leave the name off altogether in this case, i.e.

``` html
<form method="get">
```

if blockprefix is null.

**Comment by ogizanagi** [comment] 2016-09-01 18:46
You shouldn't overwrite `getBlockPrefix` for this use case, but instead create your form with an empty name:

```php
$this->get('form.factory')-> createNamed('', MyFormType::class, $data, $options);
```

Actually, your solution was only working previously because of [the backward compatibility layer in 2.8 branch](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/Type/FormType.php#L248).

However, it won't solve the issue you've mentioned, because of [this line in the form_div_layout](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L294), which does not perform any check on the name emptiness before rendering the attribute.

Perhaps you could submit a PR on the 2.7 branch in order to suggest it as a bug fix ?

**Comment by xabbuh** [comment] 2016-11-12 11:07
Closing as this is not a bug as @ogizanagi explained.

**Closed by xabbuh** 2016-11-12 11:07 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed
