### ISSUE TITLE
[FrameworkBundle] About Command throws RuntimeException

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#39916] opened 2021-01-21 10:24 UTC
**Symfony version(s) affected**: 4.4, 5.1, 5.2

**Description**  
During running command `about` in production envinroment, I get an exception:

```
In AboutCommand.php line 128:

  SplFileInfo::getSize(): stat failed for /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75
  786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e657
  4727a6e61416c6961737953657269616c697a65725d5b315d.doctrinecache.data
```

because file is not currently readable.

**How to reproduce**  
`php bin/console about --env=prod --no-debug`

**Possible Solution**  
Implement `CallbackFilterIterator` to `RecursiveIteratorIterator` and check if file `is_readable()`.

From:

```
            $size = 0;
            foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path, \RecursiveDirectoryIterator::SKIP_DOTS | \RecursiveDirectoryIterator::FOLLOW_SYMLINKS)) as $file) {
                $size += $file->getSize();
            }
```
to

```
            $size = 0;
            $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path, \RecursiveDirectoryIterator::SKIP_DOTS | \RecursiveDirectoryIterator::FOLLOW_SYMLINKS));
            // https://www.php.net/manual/en/class.callbackfilteriterator.php
            $iterator = new \CallbackFilterIterator($iterator, function (\SplFileInfo $current): bool {
                return is_readable($current->getPathname());
            });

            foreach ($iterator as $file) {
                $size += $file->getSize();
            }
```

**Additional context**  
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php#L117

I'm ready to fix this with my suggestion :)

**Comment by xabbuh** [comment] 2021-01-21 10:54
Can you debug why the file is not readable?

**Comment by michaljusiega** [comment] 2021-01-21 10:54
I will try.

**Comment by michaljusiega** [comment] 2021-01-21 11:06
It is probably related to mounted volume via `docker-compose` to Windows directory - but other files are mounted too, and everything looking good.

```
root@1d49fb09c741:/var/www/intranet# ls -l /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a
ls: cannot access '/var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a65725d5b315d.doctrinecache.data': No such file or directory
total 0
?????????? ? ? ? ?            ? 5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a65725d5b315d.doctrinecache.data
```

```
root@1d49fb09c741:/var/www/intranet# cat /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a657
25d5b315d.doctrinecache.data
cat: /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a65725d5b315d.doctrinecache.data: No such file or directory
```

```
root@1d49fb09c741:/var/www/intranet# wc -c /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a6
5725d5b315d.doctrinecache.data
wc: /var/www/intranet/var/cache/prod_linux/jms_serializer/annotations/1a/5b4c75786d65645c496e7472616e65745c44544f5c536572766963655c48545450436c69656e745c4d53506f637a74615c506f637a74615a65776e6574727a6e61416c6961737953657269616c697a65725d5b315d.doctrinecache.data: No such file or directory
```

In Windows folder:
![obraz](https://user-images.githubusercontent.com/16488888/105343014-5ebac600-5be1-11eb-9b6b-34e86f4f28d8.png)

Content from Windows Notepad:
```
0
a:1:{i:0;O:36:"JMS\Serializer\Annotation\AccessType":1:{s:4:"type";s:14:"public_methods";}} 
```

**Comment by ro0NL** [comment] 2021-01-22 08:03
`about` should be fail safe IMHO.

skipping unreadable files sounds reasonable, but perhaps we should mention the size is approximate (≅), or a minimum (≥).

**Comment by michaljusiega** [comment] 2021-02-01 10:48
Friendly ping: What do we do about this problem?

**Comment by ro0NL** [comment] 2021-02-01 15:23
@michaljusiega best is to open a PR, proposing a fix that works for you. No real preference for implementation from me :) but happy to review.

if we agree the incorrect fileperms is the actual root cause, im fine with closing as well. Your call :)

**Comment by stof** [comment] 2021-02-01 16:06
I tend to agree with @ro0NL about the fact that we should indicate that the displayed size is not the actual size but is underestimated in case we have to skip some files. The alternative would be to skip the size entirely in such case.

I would still say that it would make sense for the `about` command to be fail-safe regarding such permission issue in the cache (or at least to fail with an error message explaining the root cause if nothing else)

**Comment by michaljusiega** [comment] 2021-02-01 21:03
Okey, thanks for answer.

I'll prepare PR with my suggestion :)

**Closed as completed** 2021-03-16 09:12 UTC
Labels: Bug, FrameworkBundle, Status: Needs Review
