### ISSUE TITLE
[Messenger] Add a catch-all routing rule

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#36857] opened 2020-05-18 15:15 UTC
**Description**  
While replacing a preexisting home-made queue system with the Symfony messenger, I got bitten by this single line in the doc:
> Any messages not matched under routing will still be handled immediately.

Configuring all my existing messages is a tedious step, since I want to handle ALL messages asynchronously and send them to the same generic purpose queue. I would like to propose a new rule that would act as a "catch all", and send all messages (that are not specified otherwise under `routing`) to the same transport(s)

**Example**  
```yaml
framework:
  messenger:
   # ...
    routing:
      '*': some-transport
      App\Message\Foo: some-other-transport
```

With this example, all messages will be sent to `some-transport`, while `Foo` will be sent to `some-other-transport`.

**Comment by micheh** [comment] 2020-05-18 15:51
Your example should work, since you can use the `*` to match all messages.

Is this missing in the docs or is the routing not working?

**Comment by Jean85** [comment] 2020-05-19 09:40
This is a feature proposal, so the routing is not accepting this format as of now.

**Comment by apfelbox** [comment] 2020-05-19 11:18
If I read this code correctly, this is indeed currently supported – but differently: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Handler/HandlersLocator.php#L67-L75

So `'*': some-transport` should work right now, but it will answer to any message, no matter if it is handled by a more specific match.

That is indeed a great feature requested here, not yet implemented, but this specific syntax seems to be already used.

**Comment by micheh** [comment] 2020-05-25 15:55
With the current implementation and your provided example, all messages will be routed to `some-transport`.
The message `App\Message\Foo` will be routed to `some-other-transport` **and** `some-transport`.

I believe what you need is not a catch-all routing rule (since this is already implemented), but a setting to override the transport with a more specific other transport (instead of simply combining the transports).

**Comment by gquemener** [comment] 2020-05-25 17:03
Have you considered using a marker interface to perform such routing.

I'm using a `Publishable` interface on some of my messages that needs to be published on a queue and have solely the following config:

```yaml
framework:
  messenger:
   # ...
    routing:
      Publishable: async
```

Would this cover your use case?

**Comment by apfelbox** [comment] 2020-05-26 12:12
I still think that this is a feature, that should be implemented in core, something like:

```yaml
framework:
  messenger:
   # ...
    routing:
      App\Message\Foo: some-other-transport
      _other: some-transport
```

I guess the hardest thing here is to come up with a good config key name. 😅

**Comment by Jean85** [comment] 2020-05-26 15:22
> Have you considered using a marker interface to perform such routing?
> 
> I'm using a `Publishable` interface on some of my messages that needs to be published on a queue and have solely the following config:
> 
> ```yaml
> framework:
>   messenger:
>    # ...
>     routing:
>       Publishable: async
> ```
> 
> Would this cover your use case?

This seems a really good solution!

**Comment by Tobion** [comment] 2020-05-26 17:51
Looks like a duplicate of #36349

**Comment by xabbuh** [comment] 2020-05-27 06:04
Let's close in favour of #36349 then.

**Closed by xabbuh** 2020-05-27 06:04 UTC
Labels: Feature, Messenger, RFC, Status: Waiting feedback
