### ISSUE TITLE
[Form] BC break in choice based form type extensions

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#20771] opened 2016-12-05 21:34 UTC
3.2 changed the way that choice based types load choices. They now use `choice_loader` instead of `choices`. This caused all type extensions which used to override choices to break, because the choice loader takes priority.

**As a simple fix we can add `'choice_loader' => null,` as default to our extensions.**

Effected types are:
- `CountryType `
- `CurrencyType`
- `LanguageType `
- `LocaleType `
- `TimezoneType `

Since not many of us write extensions for these types, and providing BC for this might be hard, I'm leaving this note for others to save some debug time :)

**Comment by HeahDude** [comment] 2016-12-05 22:29
Hi @Padam87, thanks for reporting this, but it seems weird, `choices` option always have precedence on `choice_loader` but it looks like it does not happen for extensions in your case.

Could you fork symfony standard and add a minimum of code to reproduce this? Thanks!

**Comment by Padam87** [comment] 2016-12-05 23:02
Hi,

I think `choice_loader` has priority: https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L411

**Comment by HeahDude** [comment] 2016-12-05 23:08
Oh yes, you're right, `choices` has priority only for `EntityType`, https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L121.

Hmmm, not sure how we should handle this BC break then :/

**Comment by HeahDude** [comment] 2016-12-05 23:09
Can I ask what your use case for your extension?

**Comment by Padam87** [comment] 2016-12-05 23:24
I like to override the choice list for these types in all of my projects. :)
Most of the time, it is localization / configuration...

LocaleType: Only show available (translated) locales based on config param
CountryType: Only show countries where the client does business

**Comment by HeahDude** [comment] 2016-12-06 00:27
Ok, thanks :)

You could override the `choice_loader` option very easily thanks to the feature of 3.2 that comes with the BC break, you don't need to implement the `ChoiceLoaderInterface` to lazy load that call:
```php

// ...
use Symfony\Component\Form\ChoiceList\Loader\CallbackChoiceLoader;
use Symfony\Component\Form\ChoiceList\ArrayChoiceList;

class LocaleTypeExtension extends AbstractTypeExtension
{
    /**
     * @var CallbackChoiceLoader
     */
    private $choiceLoader;

    /**
     * @DI\InjectParams({
     *     "locales" = @DI\Inject("%locales%")
     * })
     *
     * @param array $locales
     */
    public function __construct(array $locales)
    {
        $this->choiceLoader = new CallbackChoiceLoader(function () use ($locales) {
            return new ArrayChoiceList(
                array_intersect_key(Intl::getLocaleBundle()->getLocaleNames('en'), array_flip($locales))
            );
        });
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $locales = ;

        $resolver->setDefaults(
            [
                'choice_loader' => $this->choiceLoader,
                'choices' => array_flip($locales),
                'choice_translation_domain' => false,
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getExtendedType()
    {
        return LocaleType::class;
    }
}
```

**Comment by HeahDude** [comment] 2016-12-09 07:09
Reading this issue again, I don't get why you use a type extension instead of a custom type. It would do the same job while keeping the possibility to use the real `LocaleType` and would avoid this BC break.

You just need to replace:
```php
/**
 * {@inheritdoc}
 */
public function getExtendedType()
{
    return LocaleType::class;
}
```

by:
```php
/**
 * {@inheritdoc}
 */
public function getParent()
{
    return ChoiceType::class;
}
```

**Comment by ogizanagi** [comment] 2016-12-11 11:39
I had the same issue and indeed switched back to `ChoiceType::class` as parent instead. I had no reason to have `LocaleType` as parent, appart from pseudo semantic.

However, I think it'll be great to ask for a subset of locales, languages, countries (...) through an option. This would ease creating some dedicated types scoped to the application needs (even if the implementation of those types is not complex).

**Comment by HeahDude** [comment] 2016-12-11 11:48
@ogizanagi see https://github.com/symfony/symfony/issues/11847 and https://github.com/symfony/symfony/pull/18334 to try a more global approach.

**Comment by HeahDude** [comment] 2017-02-25 16:25
Reading this issue again I think changing the following code in `CountryType` would fix the issue:
```php
'choice_loader' => function (Options $options) {
    if (!empty($options['choices'])) {
        // Lazy load the overridden choices
        $choices = $options['choices'];
        return new CallbackChoiceLoader(function () use ($choices) {
            return $choices;
        });
    }
    
    return $this;
},
```

But again, I think this usage is wrong, instead we should better document the behavior. Using a core choice type like `CountryType` that extends the `ChoiceType` and overriding its `choices` option does not make sense instead the `ChoiceType` should be extended instead.

I propose two things:

1. Close this issue as won't fix, in favor of documentation.

2. Merge the fix above (if it's confirmed it works) in 3.2, and deprecate the behavior in master.

What do you think __@symfony/deciders__?

**Comment by xabbuh** [comment] 2017-02-26 18:48
@HeahDude Yes, let's go with your proposed solution for the BC layer and then deprecate the possibility to override the `choices` option. Will you open a pull request?

**Comment by HeahDude** [comment] 2017-02-26 22:21
No, I will open two ;)

**Comment by HeahDude** [comment] 2017-03-05 18:31
See https://github.com/symfony/symfony/pull/21880.

**Closed** 2017-03-06 17:47 UTC
Labels: BC Break, Form
