### ISSUE TITLE
Forms with multiple and extended entity type throw an error on Symfony 2.7

### ISSUE THREAD

**Issue by adampastusiak** [symfony/symfony#17736] opened 2016-02-09 12:01 UTC
I'm on Symfony 2.7.9 and I have form like this:
```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form')
            ->add('entities', 'entity', [
                'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                'choice_label' => 'name',
                'label' => 'Label',
                'multiple' => true,
                'expanded' => true,
                'read_only' => true,
                'query_builder' => function (EntityRepository $repository) use ($ids) {
                    return $repository->createQueryBuilder('e')
                        ->where('e.id IN(:ids)')
                        ->setParameter(':ids', array_values($ids))
                        ->orderBy('e.name', 'ASC');
                }
            ])
            ->getForm();
```
When I try to create view from that form I got 2 exeptions in stack:

> TransformationFailedException: Can not read the choices from the choice list. 

in 
`
vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/CheckboxListMapper.php at line 55 
`
```php
        try {
            $valueMap = array_flip($this->choiceList->getValuesForChoices($choices));
        } catch (\Exception $e) {
            throw new TransformationFailedException(
                'Can not read the choices from the choice list.',
                $e->getCode(),
                $e
```

and 

> ContextErrorException: Warning: spl_object_hash() expects parameter 1 to be object, string given

in
`
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php at line 1243
`
```php
     */
    public function isScheduledForInsert($entity)
    {
        return isset($this->entityInsertions[spl_object_hash($entity)]);
    }
    /**
```

Of course when you'll try to set data_class you got 
>The form's view data is expected to be an instance of class Namespace\SomeBundle\Entity\SomeEntity, but is a(n) array.

exactly like @adsc said in issue #14877 

When I'll remove multiple => true option it works as it should.

I didn't found workaround for that yet. This is really pain in the ass when you have widget where user can pick specific entities in form (with checkboxes, not multiple select).

Any ideas @webmozart ?

**Comment by HeahDude** [comment] 2016-02-09 17:02
Hi @adampastusiak, I could not reproduce your issue in 2.7.9.

Could you please use the code below to help debuging :

```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form')
                     ->add('entities', 'entity', [
                         'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                         'choice_label' => 'name',
                         'choice_value' => function ($choice) {

                             dump($choice); //  expect an entity with id from ids

                             return $choice;
                         },
                         'label' => 'Label',
                         'multiple' => true,
                         'expanded' => true,
                         'read_only' => true,
                         'query_builder' => function (EntityRepository $repository) use ($ids) {

                             dump($ids); // just to be sure,
                                         // and confirm they match the dumped choices

                             return $repository->createQueryBuilder('e')
                                               ->where('e.id IN(:ids)')
                                               ->setParameter(':ids', array_values($ids))
                                               ->orderBy('e.name', 'ASC');
                         }
                     ])
                     ->getForm();
```

The dumps may be useful to see il they query and the form mapping succeded before the exception.

Also you may want to provide some default data for the field 'entities' as `multiple` is `true` the form is expecting an array of entities.
There is two ways to do this easily :

```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form', array('entities' => array(new SomeEntity())

// or

    ->add('entities', 'entity', [
                         'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                         // ...
                         'data' => array(new Entity()),

**Comment by adampastusiak** [comment] 2016-02-10 08:06
Hi @HeahDude, thank you for your response.

I've used debug code you provide and everything seems to be ok in that dumps.
in
```php
dump($choice);
```
i got first entity from query builder result (which is fine, this is entity what I expect). But I got error 
>Catchable Fatal Error: Object of class Namespace\SomeBundle\Entity\SomeEntityy could not be converted to string

which is also fine, because I don't have __toString method implemented in that entity. But what is surprising for me (maybe I don't know about something of how exactly the mechanism of forms works) but when I added getId() in dump
```php
dump($choice->getId());
```
i got proper entity id in debug bar, but when I added that to return statement
```php
return $choice->getId();
```
i got error:
>Error: Call to a member function getId() on string

Of course that error is gone when I added
```php
'data' => array(new Entity()),
```
like you told, but it isn't obvious - I didn't find such thing in any documentation I read.

And second dump gave me array of ids i want to pass to query builder. So also ok.

So to summarize:
after using your advices I got that working, but way of doing it isn't as clear and straightforward as it should be IMHO. Code which works is:
```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form')
->add('entities', 'entity', [
                'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                'choice_label' => 'name',
                'choice_value' => function ($choice) {
                    return $choice->getId();
                },
                'data' => [new Entity()],
                'label' => 'Label',
                'multiple' => true,
                'expanded' => true,
                'read_only' => true,
                'query_builder' => function (EntityRepository $repository) use ($ids) {
                    return $repository->createQueryBuilder('e')
                                               ->where('e.id IN(:ids)')
                                               ->setParameter(':ids', array_values($ids))
                                               ->orderBy('e.name', 'ASC');
                }
            ])
            ->getForm();
```

Of course 
```php
'data' => [new Entity()]
```
can be passed as createNamedBuilder argument as well, then code will look like this:
```php
$form = $this->get('form.factory')->createNamedBuilder('', 'form', ['entities' => [new Entity()]])
->add('entities', 'entity', [
                'class' => 'Namespace\SomeBundle\Entity\SomeEntity',
                'choice_label' => 'name',
                'choice_value' => function ($choice) {
                    return $choice->getId();
                },
                'label' => 'Label',
                'multiple' => true,
                'expanded' => true,
                'read_only' => true,
                'query_builder' => function (EntityRepository $repository) use ($ids) {
                    return $repository->createQueryBuilder('e')
                                               ->where('e.id IN(:ids)')
                                               ->setParameter(':ids', array_values($ids))
                                               ->orderBy('e.name', 'ASC');
                }
            ])
            ->getForm();
```

Thank you very much for your help!

**Comment by HeahDude** [comment] 2016-02-10 14:08
@adampastusiak glad that works.

In fact when you define `choice_value` option in `EntityType`, behind the scene the callable is used for every choice "loaded" from db but also for the data default value provided, in that case `null` treated as an empty string `''`. That's why I advised you to initalise the data with a new entity.

I know this is not obvious, but this is a best practice you can see in the first example of form builder usage from a controller in the [book](http://symfony.com/doc/current/book/forms.html#building-the-form) :

```php
// src/AppBundle/Controller/DefaultController.php
namespace AppBundle\Controller;

use AppBundle\Entity\Task;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class DefaultController extends Controller
{
    public function newAction(Request $request)
    {
        // create a task and give it some dummy data for this example
        $task = new Task();
        $task->setTask('Write a blog post');
        $task->setDueDate(new \DateTime('tomorrow'));

        $form = $this->createFormBuilder($task) // See here the new Task() as default value
            ->add('task', TextType::class)
            ->add('dueDate', DateType::class)
            ->add('save', SubmitType::class, array('label' => 'Create Task'))
            ->getForm();

        return $this->render('default/new.html.twig', array(
            'form' => $form->createView(),
        ));
    }
}
```

Passing an entity as default value also automatically set the `data_class` option.

However what I don't know if it can be considered an issue is the fact that you may pass a null or empty array as default data and expect `choice_value` callable to not throw an exfeption.

I'm going to open an other issue to discuss this, you should close this one.

What you can do is open an issue in the symfony docs to remind to be more explicit about initialising data in forms.

Cheers

**Comment by HeahDude** [comment] 2016-02-10 14:32
Of courses this example of the book missing `$form->handleRequest($request)` which updates the state of the data in the form by synchronizing submitted data on top of default data. But you could do it in another controller.

**Comment by HeahDude** [comment] 2016-02-10 15:13
Status: Reviewed

**Comment by javiereguiluz** [comment] 2016-02-14 09:57
Closing it as solved thanks to the excellent help and guidance provided by @HeahDude. Thank you!

**Closed by javiereguiluz** 2016-02-14 09:57 UTC
Labels: Form, Status: Reviewed

**Comment by xabbuh** [comment] 2016-02-15 19:24
@adampastusiak By the way, having to pass an array for the `data` option should only be necessary when the `multiple` option is set to `true`.

**Comment by adampastusiak** [comment] 2016-02-18 06:41
@xabbuh To be honest I wasn't even aware, that I can pass array with object inside as data to FormType. When you provided that solution it has perfectly sense, but I didn't found anything about that in documentantion (maybe this is somewhere but I didn't ran into that). 
Nevertheless, @HeahDude  solved my problem very fast and I'm very grateful for that!
