### ISSUE TITLE
Tagged Service: doesn't work with abstract classes hierachy

### ISSUE THREAD

**Issue by wiseguy1394** [symfony/symfony#31895] opened 2019-06-06 10:25 UTC
**Symfony version(s) affected**:  4.3.0 (probably prior versions)

**Description**
With the following class structure:  
```
interface A{}

abstract class B implements A {}

class C1 extends B {}
...
class CN extends B {}

class D {
    public function __construct(iterable $classes)
    {
        foreach($classes as $class){
            $class->doSomething();
        }
    }
}
```
and configs in services.yaml :
```
_instanceof:
    App\A:
        tags: ['app.classes']
App\D:
    arguments: [!tagged app.classes]
```
the instantiation of class D results in:
```
segmentation fault (core dumped)
```

Is it a bug or a wrong configuration/usage of tagged services?

**Possible Solution**  
If we change the class structure to:
```
interface A{}

abstract class B {}

class C1 extends B implements A {}
...
class CN extends B implements A {}

class D {
    public function __construct(iterable $classes)
    {
        foreach($classes as $class){
            $class->doSomething();
        }
    }
}
```
It works, but it's not really handy.

**Comment by nicolas-grekas** [comment] 2019-06-06 10:32
segfaults are PHP bugs...

**Comment by Matts** [comment] 2019-06-06 15:08
I was not able to reproduce this issue in Symfony 4.3 - PHP 7.2.17

**Comment by xabbuh** [comment] 2019-07-29 14:16
I am closing here as there isn't much we can do about it. Thank you for understanding.

**Closed by xabbuh** 2019-07-29 14:16 UTC
Labels: Bug, DependencyInjection, Status: Needs Review
