### ISSUE TITLE
GroupSequences execute next group if first fail

### ISSUE THREAD

**Issue by sobhan93** [symfony/symfony#25717] opened 2018-01-08 13:39 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3
 
When form is submitted, both groups "Users' and 'Strict' are validated even if there are violations in 'Users'.

When put something like "123" on username and password,expected "This value is too short. It should have 6 characters or more." but "I am passwordLegal" message appears.

```
class Users
{
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('username', new Assert\NotBlank());
        $metadata->addPropertyConstraint('password', new Assert\NotBlank());
        $metadata->addPropertyConstraint('username', new Assert\Length(array(
            'min' => 6,
            'max' => 12
        )));
        
        $metadata->addPropertyConstraint('password', new Assert\Length(array(
            'min' => 6
        )));
        
        $metadata->addGetterMethodConstraint('password', 'passwordLegal', new Assert\IsTrue(array(
            'message' => 'The password cannot match your username',
            'groups' => array(
                'Strict'
            )
        )));
        $metadata->setGroupSequence(array(
            'Users',
            'Strict'
        ));
    }

    public function passwordLegal()
    {
        die("I am passwordLegal");
        return $this->password !== $this->username;
    }
}
```

**Comment by xabbuh** [comment] 2018-01-08 13:57
Would you be able to provide a fully working example application that allows to reproduce your issue?

**Comment by sobhan93** [comment] 2018-01-08 16:08
[Download example application](http://www.mediafire.com/file/m56hmru2kqh2c47/symfony-issue-25717.zip)

**Comment by xabbuh** [comment] 2018-01-08 21:29
Status: Reviewed

**Comment by sobhan93** [comment] 2018-01-09 15:21
when will this bug be solved ?

**Comment by xabbuh** [comment] 2018-01-09 15:28
There is no schedule for when bugs are fixed. At some point, someone will decide to work on an issue and submit a PR. But that depends on how complicated things are, how many people are affected and so on. If more people are affected by an issue, changes are high, that one of them will invest some time themselves to fix the code.

**Comment by xabbuh** [comment] 2018-09-24 10:36
Actually, this is a duplicate of #9939. Therefore, I am closing here.

**Closed by xabbuh** 2018-09-24 10:36 UTC
Labels: Bug, Form, Status: Reviewed, Validator
