### ISSUE TITLE
The function dd() is not working in laravel

### ISSUE THREAD

**Issue by dxmeta** [symfony/symfony#39394] opened 2020-12-09 06:18 UTC
**Symfony version(s) affected**: symfony/var-dumper:5.2
**PHP version**:8.0
**Laravel version**:8.17.2
**Description**  

When I print the collection use the dd function, I cannot see the nested content inside the collection,like the following,
`
Illuminate\Database\Eloquent\Collection {#992
  #items: array:9 []
}
`
i cant see any items,the previous version can be expanded to view specific items

**Comment by xabbuh** [comment] 2020-12-09 08:36
Can you create a small example application that allows to reproduce your issue?

**Comment by dxmeta** [comment] 2020-12-09 08:56
![82325B631CF65E09B34539CC1B0D9253](https://user-images.githubusercontent.com/30767876/101607322-71b57480-3a3f-11eb-8f54-bcb7a1ff4d04.png)

Like the above picture,the nested element is empty!Why???

**Comment by ro0NL** [comment] 2020-12-09 19:53
@buffary we need to understand what happens technically first, before we can answer the why.

So any insights what's causing length=9 but `[]` for rendering is welcome.

We need to isolate the problem. Maybe it can be reproduced as simple as `dd(new Collection(range(1,9)))` but that's up to you to confirm at first.

A piece of code reproducing the output from the screenshot above allows others to gain such insights as well.

**Comment by zoriax** [comment] 2020-12-14 13:35
Hello,

Same issue here, it apperas on axios response : 

```php
dump(['test0' => ['test1' => 'test1', 'test2' => 'test2']]);
```
It returns

![image](https://user-images.githubusercontent.com/12936546/102087264-9469d380-3e19-11eb-8297-a1f62b50eaa6.png)

If you use dd() in for exemple web.php Laravel page, it works.

Thanks

**Comment by agonne** [comment] 2020-12-14 13:51
Hello, 

I have the same problem.
I do the following line in AppServiceProvider.php

```php
dd(config('applications.forms.app_name.beneficiary_forms'));
```

![image](https://user-images.githubusercontent.com/50362864/102088312-0858ab80-3e1b-11eb-8d5c-8aa369b9f0ab.png)

But if the same line is called through an axios call

![image](https://user-images.githubusercontent.com/50362864/102088421-2d4d1e80-3e1b-11eb-8223-99af8199b87a.png)

And in preview of response in network tab of browser is the same result

![image](https://user-images.githubusercontent.com/50362864/102088513-51a8fb00-3e1b-11eb-9524-236bf52dd393.png)

In the response tab the HTML code seems to be complete
![image](https://user-images.githubusercontent.com/50362864/102088623-74d3aa80-3e1b-11eb-9bf8-aa76540e62ed.png)

Thanks

**Comment by agonne** [comment] 2020-12-14 14:12
P.S.
It works with laravel 8.12.1, upgrading to version 8.18.1 it no longer works. No code change in the application.

**Comment by derrabus** [comment] 2020-12-14 14:15
All right, please help a Laravel noob like me to reproduce the problem: Please create a small application that I can run to reproduce the problem. Share that application as a GitHub repo and link it in this thread. Thanks!

**Comment by agonne** [comment] 2020-12-15 08:53
Hello, 

Here is an empty app with the bug.
https://github.com/ciad/debug_dd

On the home page at the top there is a dump() of an array, everything works.

Then next to the Laravel logo I put a horrible button "Axios Request"
Click on it then go to the Network and Previem tab of Chrome and the dump() is bugged (not unfoldable).

For info dump() and dd() behave the same way.

The code for these two debugs can be found in HomeController.php.
The axios request in a script at the bottom of the welcome.blade.php view.

I hope I was chaired enough this time ...

Thank you.

**Comment by bpuig** [comment] 2020-12-16 10:51
Changes made in this commit changed the behaviour in 5.2.0:

https://github.com/symfony/var-dumper/commit/4b5ca0096f952ea114182b10e6d8d47c3d84ac8d

This "improve" of the "rendering" messed up response inspectors.

**Comment by nicolas-grekas** [comment] 2020-12-16 10:55
Thanks for the details, the related PR is #35959.
This looks like a pure JavaScript issue then! Could anyone try to figure out what's wrong there? Is there any JavaScript error in the dev tools of the browser?
Please submit a PR if you find the cause.

**Comment by rodrigopedra** [comment] 2020-12-16 10:58
Hi @derrabus 

I tracked down the changed behavior to this commit: https://github.com/symfony/var-dumper/commit/4b5ca0096f952ea114182b10e6d8d47c3d84ac8d

Reverting it brings the old behavior back.

Note it only happens when previewing the results of calling `dd(...)` on the network tab, I tested in both Chrome and Firefox.

It doesn't need to be an AJAX call, you can preview a regular page, in the regular browser nested properties will be interactive/collapsible, while if previewing the HTML document on the developer tools' network tab it won't be interactive/expandable. 

Previous behavior before the commit above was to have all properties expanded when previewing on the network tab.

To reproduce it you don't need to use Laravel. You can reproduce this with the following steps:

~~~bash
mkdir test
cd test
composer init
composer require symfony/var-dumper
echo "<?php require __DIR__ . '/vendor/autoload.php'; dd(['foo' => [1,2,3]]);" > index.php
php -S localhost:8000
~~~

- Navigate to `http://localhost:8000`
- Output on browser should be as expected (expandable/collapsible)
- Open developer tools (I tested on Chrome and Firefox)
- Select the Network tab
- Click the HTML response
- The preview panel will show the response collapsed

My guess is that the commit above changed the output from expanded by default to collapsed by default. And as the network tab's preview pane doesn't run JavaScript the results cannot be expanded.

Users might be relying on the results to be expanded to debug AJAX calls.

Hope this helps.

**Comment by rodrigopedra** [comment] 2020-12-16 11:01
Hi @nicolas-grekas and @bpuig

I was typing my response before seeing yours. 

Unfortunately I am not familiar with symfony's codebase/code-style to send a PR.

Hope it can help debugging it.

**Comment by nicolas-grekas** [comment] 2020-12-16 11:06
The codebase here is very simple here: a single file is used to generate all the HTML & JavaScript.
See #35959

**Comment by rodrigopedra** [comment] 2020-12-16 11:54
@nicolas-grekas 

I just sent PR #39523 to revert PR #35959

**Comment by agonne** [comment] 2020-12-16 16:45
@rodrigopedra Indeed I had not thought of looking at the network tab in a page debug without AJAX call (since it is displayed directly on the web page)

**Comment by nicolas-grekas** [comment] 2020-12-16 17:05
Please give #39525 a try and confirm it fixes the issue if you can.

**Comment by rodrigopedra** [comment] 2020-12-16 20:06
Hi @nicolas-grekas I tried #39525 and it is working as expected regarding the network tab.

I guess, as the JavaScript code is the first thing rendered, it will also prevent any flickering reported by issue #35800.

Thanks!

**Comment by agonne** [comment] 2020-12-17 07:59
Hello,

@nicolas-grekas #39525 works for me ! 

Thanks !

**Closed as completed** 2020-12-17 08:33 UTC
Labels: Bug, VarDumper
