### ISSUE TITLE
Unable to use container->compile() function, giving error anywhere (kernel.php or controller/command)

### ISSUE THREAD

**Issue by Power2All** [symfony/symfony#42977] opened 2021-09-10 10:36 UTC
**Symfony version(s) affected**: 5.3.7

**Description**
We trying to compile the events being triggered, having a TransactionHandlerPass.php in the /src/DependencyInjection/Compiler/ folder. I execute that in the /src/Kernel.php file with a protected function "build" which injects also ContainerBuilder.
We do a container->addCompilerPass with PassConfig::TYPE_BEFORE_OPTIMIZATION and priority 1.
This works fine, but it isn't compiled automatically as expected.

When I do a container->compile() in here, I get a service twig.template_iterator error.

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
You have requested a non-existent service "twig.template_iterator".

Exception trace:
  at /project/vendor/symfony/dependency-injection/ContainerBuilder.php:979
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at /project/vendor/symfony/twig-bundle/DependencyInjection/Compiler/ExtensionPass.php:48
 Symfony\Bundle\TwigBundle\DependencyInjection\Compiler\ExtensionPass->process() at /project/vendor/symfony/dependency-injection/Compiler/Compiler.php:91
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /project/vendor/symfony/dependency-injection/ContainerBuilder.php:744
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /project/src/Kernel.php:45
 App\Kernel->build() at /project/vendor/symfony/http-kernel/Kernel.php:678
 Symfony\Component\HttpKernel\Kernel->prepareContainer() at /project/vendor/symfony/http-kernel/Kernel.php:646
 Symfony\Component\HttpKernel\Kernel->buildContainer() at /project/vendor/symfony/http-kernel/Kernel.php:544
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /project/vendor/symfony/http-kernel/Kernel.php:786
 Symfony\Component\HttpKernel\Kernel->preBoot() at /project/vendor/symfony/http-kernel/Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at /project/vendor/symfony/framework-bundle/Console/Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /project/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /project/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /project/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:56
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /project/vendor/autoload_runtime.php:35
 require_once() at /project/bin/console:11
```

**How to reproduce**
Explained as above.
We have a TransactionHandlerPass.php that contains the following:

```php
    public function process(ContainerBuilder $container): void
    {
        $transactionHandlerDefinition = $container->findDefinition('redacted.transaction_handler');

        foreach ($container->findTaggedServiceIds('redacted.transactions') as $id => $tags) {
            foreach ($tags as $attributes) {
                $transactionHandlerDefinition->addMethodCall('addTransactionClass', [$attributes['alias'], new Reference($id)]);
            }
        }
    }
```

In the Kernel.php I added this at the bottom:

```php
    protected function build(ContainerBuilder $container): void
    {
        $container->addCompilerPass(new TransactionHandlerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 1);
        $container->compile();
    }
```

**Additional context**
I cannot change it for now, this is how the code worked also in the old Symfony 3.4 project.
The Kernel.php part was missing in the old environment, as it was a bundle before, but it's integrated now in the project itself, hence I have it loaded in the Kernel.php, and the documentation states so to load it there:
https://symfony.com/doc/current/service_container/compiler_passes.html#working-with-compiler-passes-in-bundles

**Comment by derrabus** [comment] 2021-09-10 10:39
Can you provide a small application that allows us to reproduce the problem?

**Comment by Power2All** [comment] 2021-09-10 10:52
> Can you provide a small application that allows us to reproduce the problem?

Yes, it's very simple.
Deploy a full project of Symfony 5.3, then install the ``symfony/dependency-injection`` module through composer.
Edit the /src/Kernel.php file and add:

```php
    protected function build(ContainerBuilder $container): void
    {
        $container->compile();
    }
```

Don't forget to add these at the class
```php
use Symfony\Component\DependencyInjection\ContainerBuilder;
```

and then execute just ``bin/console`` and you should get immediately the error message.

**Comment by mbabker** [comment] 2021-09-10 14:30
You shouldn't be calling `$container->compile()` in your Kernel's `build()` method.  The root Kernel class that your application should be extending compiles the container at the right point in time, by trying to compile it in your `build()` method (or a Bundle's `build()` method), you're trying to compile a container that isn't yet fully configured (as an example, the root Kernel class adds a couple of compiler passes and steps through a couple other methods which end up calling your Kernel's `configureContainer()` method after `Kernel::build()` is called but before the container is compiled).  The fact you're getting a `ServiceNotFoundException` doesn't seem all that surprising to me.

**Comment by Power2All** [comment] 2021-09-10 15:23
> You shouldn't be calling `$container->compile()` in your Kernel's `build()` method. The root Kernel class that your application should be extending compiles the container at the right point in time, by trying to compile it in your `build()` method (or a Bundle's `build()` method), you're trying to compile a container that isn't yet fully configured (as an example, the root Kernel class adds a couple of compiler passes and steps through a couple other methods which end up calling your Kernel's `configureContainer()` method after `Kernel::build()` is called but before the container is compiled). The fact you're getting a `ServiceNotFoundException` doesn't seem all that surprising to me.

I would agree with you, weren't it not that the compile() function also gives a error on the controller and/or command class.
The "addMethodCall" isn't run at all, so when would it be run at all ?
Neither the cache clearing, or any other situation is it run.

**Comment by mbabker** [comment] 2021-09-10 15:36
> I would agree with you, weren't it not that the compile() function also gives a error on the controller and/or command class.

You can't compile a dumped container.  Once the kernel has built the container (be it loading the existing one from cache or having compiled it anew), everything inside your application will be using the dumped container.  Basically, you should very rarely (if ever) actually be calling `$container->compile()` on your own.

> The "addMethodCall" isn't run at all, so when would it be run at all ?

Your compiler passes should be run when the container is compiled.  So, have you checked to make sure the pass is actually being executed?  If it is, have you checked to make sure that `$container->findTaggedServiceIds('redacted.transactions')` isn't returning an empty array?  If that is empty, have you checked to make sure your services have that tag on them?

**Comment by Power2All** [comment] 2021-09-10 15:42
> Your compiler passes should be run when the container is compiled. So, have you checked to make sure the pass is actually being executed?

It is run, when the Kernel.php contains the addMethodCall.
Sadly, the Method is not executed at any time, so the array in that redacted.transaction_handler (it's a class that has a add and get action for a array with callback classes) has nothing, when it actually should have filled up with stuff.
In this case, the addTransactionClass is not being executed at all.
The findTaggedServiceIds ain't the problem, it does return data, but the addTransactionClass is simply not executed, which I would have expected.

**Comment by mbabker** [comment] 2021-09-10 16:00
I'm not following you now.  Are you saying it works if you inline the code from your compiler pass into the `Kernel::build()` method, but it doesn't work when it's in a compiler pass?

**Comment by Power2All** [comment] 2021-09-10 16:03
> I'm not following you now. Are you saying it works if you inline the code from your compiler pass into the `Kernel::build()` method, but it doesn't work when it's in a compiler pass?

It's simple.
The addMethodCall is executed correctly yes, but the actual execution of the function, is not.
When does addMethodCall get executed, would be my question.
So, when I actually do a addMethodCall in the Kernel::build() function, it does add it to the addMethodCall, I can see if when I list it, but further then that, nothing happens.

**Comment by mbabker** [comment] 2021-09-10 16:20
`addTransactionClass` won't be called when the container is compiled.  It would be called at runtime when your service is loaded from the container.

When you run `bin/console debug:container redacted.transaction_handler`, it should also show you the details of that service including however many `addTransactionClass` calls should be made when that service is fetched from the container (one for each tagged service).

Whenever you `$container->get('redacted.transaction_handler')` or inject it as a dependency, you should get the handler with all of the tagged services inside of it (a quick `dd($transactionHandler);` would confirm that).

**Comment by Power2All** [comment] 2021-09-10 16:21
> `addTransactionClass` won't be called when the container is compiled. It would be called at runtime when your service is loaded from the container.
> 
> When you run `bin/console debug:container redacted.transaction_handler`, it should also show you the details of that service including however many `addTransactionClass` calls should be made when that service is fetched from the container (one for each tagged service).
> 
> Whenever you `$container->get('redacted.transaction_handler')` or inject it as a dependency, you should get the handler with all of the tagged services inside of it (a quick `dd($transactionHandler);` would confirm that).

I'll check it monday, currently drove home, so I'll let you know how far I have come.
I did check if the addTransactionClass was runned, and I could tell you it didn't on runtime.

**Comment by derrabus** [comment] 2021-09-11 14:00
~~#42986 should give you a nicer error when running `compile()` where you shouldn't.~~

**Comment by derrabus** [comment] 2021-09-11 14:21
I closed my PR because it wouldn't help in your case.

Either way, compiling the container within your `Kernel::build()` method will never work because at that point the configuration of the extensions has not been loaded but all bundles have already added their passes. Those passes partially rely on the configurations. I'm not sure if we can prevent this error in a nice way without wrapping the whole container builder into a proxy object that disallows calls to `->compile()`.

Since `Kernel::build()` is a callback that is invoked during the Kernel's container compilation process, compiling the builder here will never work. This is not a bug.

I'm closing the issue because it turned into a support thread in the meantime. Please open a discussion if you want to continue it.

**Closed as completed by derrabus** 2021-09-11 14:21 UTC
Labels: Bug, Status: Waiting feedback

**Comment by Power2All** [comment] 2021-09-13 07:52
@derrabus 
Problem is solved.
Figured out with my colleague that we needed to retrieve the container from the KernelInterface.
The documentation located at https://symfony.com/doc/current/components/dependency_injection.html
says I could use a new ContainerBuilder(), and then do a ->get on it.
This is ambiguous, cause it would create a whole new container without the generated data.
After testing with using the KernelInterface and retrieve the container, and do a get there, it worked.

The part in the documentation that says:
```
You could then get your newsletter_manager service from the container like this:
```
is therefor for me very confusing, and perhaps for other people as well.

**Comment by stof** [comment] 2021-09-13 14:06
@Power2All See the note at the beginning of that page, that I'm quoting here:

> This article explains how to use the DependencyInjection features as an independent component in any PHP application. Read the Service Container article to learn about how to use it in Symfony applications.

When using a Symfony application, all the integration logic necessary to manage the ContainerBuilder is handled by `symfony/http-kernel`, not by your own code.
