### ISSUE TITLE
Doctrine Collections should be an array

### ISSUE THREAD

**Issue by Gemorroj** [symfony/symfony#37041] opened 2020-06-01 13:14 UTC
**Symfony version(s) affected**: 4.4.9

**Description**  
After this change https://github.com/symfony/symfony/pull/36601 empty Doctrine Collections became objects instead of empty arrays

**How to reproduce**  
```php
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Serializer;

$serializer = new Serializer([], [new JsonEncoder()]);
$arr = new ArrayCollection();

echo $serializer->serialize($arr, 'json');

// 4.4.8 - []
// 4.4.9 - {}
```

**Comment by soyuka** [comment] 2020-06-01 14:29
>  but why!? it's bc changes. Now empty doctrine collections casts to object instead of empty array

You should not expose ArrayCollection but use `ArrayCollection->getValues` instead, which will get you a real array (also fixes an index issue if you delete somthing from this ArrayCollection). ArrayCollection is an object and it's correct that it gets normalized to an object imo.

**Comment by norkunas** [comment] 2020-06-01 14:33
@soyuka this also affected us somehow when orm paginator from api-platform returned zero results we started to get an empty object instead of empty array

**Comment by soyuka** [comment] 2020-06-01 14:38
I'd like to reproduce this @norkunas because it is indeed a bad behavior. I still believe that #36601 is legit or we should rollback [this](https://github.com/symfony/symfony/commit/f28e826627e8d0db7db43a11e6e8d9b568e7870e) which actually causes the issue in the first place with `\ArrayObject`. I mean we can't on one hand allow empty objects to be normalized as empty objects (as they should) but have some kinds of objects be normalized as array (ArrayCollection/Paginator). According to the unit tests, an empty array is still encoded as empty array and the error should be best handled by the developer.

**Comment by norkunas** [comment] 2020-06-01 14:40
I agree that merged PR is a good one, but then api-platform should do the work to serialize paginator as empty array :)

**Comment by Gemorroj** [comment] 2020-06-01 14:45
@soyuka it's **BC**! And this is unexpected behavior and completely unusable in real world.
Symfony can give a setting for managing the behavior.

**Comment by soyuka** [comment] 2020-06-01 15:45
What works as expected? Because normalizing an empty `ArrayObject` doesn't pre-4.4.9. I need to check if it worked pre-#28363 which then is also **BC** :/. I think that we should just deliberate on what we want the ObjectNormalizer to do on empty objects as pre-4.4.9 this is also "unexpected behavior":

```
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Serializer;

$serializer = new Serializer([], [new JsonEncoder()]);
$arr = new ArrayObject();

echo $serializer->serialize(['foo' => $arr], 'json');
```

**Comment by xabbuh** [comment] 2020-06-01 17:31
Does #37049 fix the issue?

**Comment by soyuka** [comment] 2020-06-01 18:11
> Does #37049 fix the issue?

Indeed, having the `PRESERVE_EMPTY_OBJECTS` to `false` keeps these objects as arrays. :+1: on the fix.

**Comment by Gemorroj** [comment] 2020-06-01 19:15
@xabbuh Yes, it works.

**Comment by dunglas** [comment] 2020-06-02 06:41
IMHO we should explicitly whitelist the old behavior for ArrayObject and instances of Doctrine Collections because they are designed to store lists (not maps) and it makes sense to always serialize them as JSON arrays (not objects).

**Closed** 2020-06-02 08:39 UTC
Labels: BC Break, Bug, Serializer, Status: Needs Review
