### ISSUE TITLE
BirthdayType Field: Incorrect option text with default years parameter

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#19494] opened 2016-07-31 00:00 UTC
Symfony: 2.8.*
PHP: 5.6

I didn't see someone report this bug. Excuse me if it's already listed.

When I use BirtdayType Field and use the default years parameter or set higher than 114 years, the select option text is not correct.

``` php
            ->add('birthdate', BirthdayType::class, array(
                'label' => 'Birthdate
            ))
```

``` html
<option value="1896">2032</option>
<option value="1897">2033</option>
<option value="1898">2034</option>
<option value="1899">2035</option>
<option value="1900">2036</option>
<option value="1901">2037</option>
<option value="1902">1902</option>
<option value="1903">1903</option> ....</select>
```

**Comment by georaldc** [comment] 2016-08-01 20:10
This sounds like a 32bit issue. The code that generates the choices for your dropdown makes use of the php function gmmktime, which is basically the mktime function that takes in a GMT date (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L311).

According to mktime (http://php.net/manual/en/function.mktime.php), regarding the ```year``` argument, ```"On systems where time_t is a 32bit signed integer, as most common today, the valid range for year is somewhere between 1901 and 2038"```

**Comment by georaldc** [comment] 2016-08-01 20:50
Hmm, I did a bit more digging and well, I'm not really sure but I think the part that may be causing dates to shift forward to 2037 is when the DateType class formats the timestamps it receives by creating a DateTime instance and extracting the year value out of it. Problem is negative timestamps that go past 1902 return unexpected results. On my local machine, it spits out 2037 and will probably wrap around again if I keep going back further. Most likely another 32bit architecture limitation.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L293

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php#L600

**Comment by xdemoor** [comment] 2016-08-02 07:19
You're right. If I use PHP 7 on my WampServer 3 (64bit), I have PHP_INT_SIZE = 8 (64bit). But If I'm using PHP 5.6, I have PHP_INT_SIZE = 4 (32bit).

**Comment by georaldc** [comment] 2016-08-02 16:03
Related issue found here if you want to do more reading on it

https://github.com/symfony/symfony/issues/5227

**Comment by xdemoor** [comment] 2016-08-02 16:56
Thank you. It's marked to fixed for 32bit, but it's not the case.

In the documentation, I see the warning for this bug, but only If I use input timestamp. In this case, I use the default option (datetime). 

Or maybe I missed something ?

**Comment by georaldc** [comment] 2016-08-02 17:28
Looking at the fix, it was supposed to prevent dates from wrapping around since it skips gmmktime calls that return false. While still not exactly the best outcome for 32 bit setups, it should have constrained your years dropdown to just 1902 - 2037 so I'm not sure how yours continued to wrap around.

I'm not too familiar with these components so hopefully someone else can point you better to the right direction.

**Comment by xdemoor** [comment] 2016-08-02 17:35
I'm not familiar too. :)

**Comment by georaldc** [comment] 2016-08-02 17:43
If I were to guess, the rule should state: 

```
the option input is set to timestamp, OR 
the option widget is set to single_text, OR 
the option widget is set to choice
```
```choice``` is the default for widget value for BirthdayType

**Comment by xabbuh** [comment] 2019-02-16 00:07
I tried to debug this issue in #30266. On AppVeyor we have a 32bit PHP. But  looking at the generated choices there the selection starts at 1902.

So it looks like the bug doesn't exist anymore. If I am wrong here, please leave some feedback on how to reproduce it (the best would be to submit a PR with a failing test case). In the meantime I am closing here (we can reopen if we get some more information).

**Closed by xabbuh** 2019-02-16 00:07 UTC
Labels: Bug, Form, Status: Waiting feedback, Unconfirmed
