### ISSUE TITLE
[HttpKernel] [6.1] Bundle namespace is not automatically registered using AbstractBundle

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#46492] opened 2022-05-29 13:45 UTC
### Symfony version(s) affected

6.1.0

### Description

When the bundles class extends from AbstractBundle, instead of Bundle, the namespace is no longer automatically registered.

### How to reproduce

Before;

```php
class AcmeFooBundle extends Bundle
{
// @AcmeFoo is automatically registered in twig

```

```bash
# namespace is registered
bin/console debug:twig | grep @AcmeFoo 
```

With AbstractBundle

```php
class AcmeFooBundle extends AbstractBundle
{
    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $loader = new XmlFileLoader($builder, new FileLocator(__DIR__.'/Resources/config/'));
        $loader->load('services.xml');

    }

    public function configure(DefinitionConfigurator $definition): void
    {
    }
```

```bash
# namespace is NOT registered
bin/console debug:twig | grep @AcmeFoo 
```

On a possibly related note, changing "extends Bundle" to "extends AbstractBundle" seems to break everything (that is, the extension class doesn't load, so no config or service loading).   I thought the new system was designed to allow loading and configuring to happen in the Bundle class, but not require it.

**Comment by yceruto** [comment] 2022-05-29 14:21
@tacman the `AbstractBundle` was designed to work with the modern directory structure "by default", so you probably have to update the bundle path to use the old directory structure as explained in the doc https://symfony.com/doc/current/bundles.html#bundle-directory-structure or upgrade your bundle structure to start using the modern one.

**Comment by yceruto** [comment] 2022-05-29 14:26
I'm closing here as this is not a bug, thanks for reporting!

**Closed as completed by yceruto** 2022-05-29 14:26 UTC
Labels: Bug, HttpKernel, Status: Needs Review

**Comment by tacman** [comment] 2022-05-29 15:50
Thanks!  If that's the default location for config, does it automatically happen somewhere, or is this still necessary?

```php
        $loader = new XmlFileLoader($builder, new FileLocator(__DIR__.'/../config/'));
        $loader->load('services.xml');
```

In particular, it seems odd to have to specify the config path.

**Comment by yceruto** [comment] 2022-05-29 16:02
You can still use the `Resources/config/` path with `AbstractBundle` by correctly updating the bundle path. 

Note also that `ContainerConfigurator $container` argument can help you not to deal with specific loaders and paths, instead, you can do directly this:
```php
$container->import('Resources/config/services.xml');
// or
$container->import('../config/services.xml')
```
The path is relative to your bundle location/structure.

**Comment by yceruto** [comment] 2022-05-29 16:06
However, you cannot mix both structures. You should decide if keep the old structure and update `AbstractBundle::getPath()` method or migrate your old structure to the new one.
