### ISSUE TITLE
Composer install fails on symfony/symfony 2.7.41 and 2.8.34

### ISSUE THREAD

**Issue by kylekatarnls** [symfony/symfony#26021] opened 2018-02-02 13:00 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.7.41 and 2.8.34
| PHP version  | < 7

Hi,

My Travis CI recently broke with symfony 2.7.41 and 2.8.34 on PHP 5.4, 5.5 and 5.6, but are still fine on PHP 7+ and all other symfony versions.

See the complete logs of the failure:
https://travis-ci.org/pug-php/pug-symfony/builds/336525418

And after downgrade to 2.7.40 and 2.8.33, the successful logs:
https://travis-ci.org/pug-php/pug-symfony/builds/336539098

After quick inspect of common changes between 2.7.41 and 2.8.34, I guess it's a Symfony incompatibility that have cause this failure rather than a composer or travis issue.

Thanks,

**Comment by derrabus** [comment] 2018-02-02 15:01
Well, Composer runs out of memory upon installation. I don't see what Symfony could do about that.

**Comment by xabbuh** [comment] 2018-02-02 15:16
Not setting the minimum stability to dev could potentially reduce the memory consumption in the first place. And running tests with unreleased dependencies could then still be done in a dedicated job where the memory limit is set to `-1`. However, I also agree with @derrabus that this does not look related to Symfony itself and I am thus closing here.

**Closed by xabbuh** 2018-02-02 15:16 UTC

**Comment by kylekatarnls** [comment] 2018-02-02 15:43
@derrabus I ran the test over 10 times before trying to downgrade. It could not be a coincidence the exact same build fails always on PHP 5.4, 5.5, 5.6 symfony 2.7.41, 2.8.34 and not with 2.7.40 and 2.8.33 when the change made on those both version clearly imply composer stuff. Don't throw the baby out with the bathwater.

I don't see your point. I did not change the minimum-stability or nothing else, the downgrade 2.7.41 to 2.7.40 and 2.8.34 to 2.8.33, So could you explain me, what this downgrade fixed the travis build if it's a composer issue?

**Comment by xabbuh** [comment] 2018-02-02 16:15
The tree that would have been passed to Composer's SAT solver would already have been huge before the last Symfony patch releases have been merged. The new tags could just have the effect that the size of the tree now exceeded the memory limit. You could still run with dev dependencies. This was just a general remark that doing so will very likely need more memory. In your case, you will probably just need to increase the memory limit manually.

**Comment by derrabus** [comment] 2018-02-02 16:16
I'm not saying that the upgrade from 2.7.40 to 2.7.41 is not triggering your issue. Still, the code that is crashing here, is Composer. The upgrade from 2.7.40 to 2.7.41 might just be the straw that broke the camel's back, but it's not the root cause of your problem.

As @xabbuh already hinted, you're doing things here that force composer to run on high memory: your minimum stability is set to `dev` and you've enabled the `prefer-stable` flag. This combination forces Composer to do some heavy lifting. If you think that Composer should not run out of memory here, you should reach out to the Composer project instead.

**Comment by kylekatarnls** [comment] 2018-02-02 16:20
OK, the min stability was needed when tested again symfony 4 before it was release. I guess I can try to restore the stable setting until Symfony 5 comes out. I'll let you know.

**Comment by kylekatarnls** [comment] 2018-02-02 16:48
Succeed. Thanks for explanations.
