### ISSUE TITLE
Redis::scan(): Passing null to parameter #4 ($type) of type ?string is deprecated

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#51770] opened 2023-09-28 08:24 UTC
### Symfony version(s) affected

6.3.4

### Description

Using [Redis 6.0.1](https://pecl.php.net/package/redis) I see this deprecation being reported on my CI:

> Redis::scan(): Passing null to parameter #4 ($type) of type ?string is deprecated

I don't believe this will be fixed with https://github.com/symfony/symfony/pull/51754 (I know it's not yet tagged).

### How to reproduce

I believe this happens when you create a Redis connection from the Cache component.

```php
$client = RedisAdapter::createConnection(
    'redis://localhost'
);
```

### Additional Context

- https://github.com/symfony/symfony/pull/51133
- https://github.com/symfony/symfony/pull/51754

**Comment by nicolas-grekas** [comment] 2023-09-28 08:31
Closing as duplicate of https://github.com/symfony/symfony/issues/51700
See my last comment there for next steps.

**Closed as completed by nicolas-grekas** 2023-09-28 08:31 UTC
Labels: Bug, Status: Needs Review, Cache

**Comment by ruudk** [comment] 2023-10-13 08:12
For the record: I tested `symfony/cache` version `v6.3.5` with Redis `6.0.1` (on PECL) and I still get the error.

Reported upstream: https://github.com/phpredis/phpredis/issues/2403
