### ISSUE TITLE
[DOT ENV] Casting Not Work When Working With Config Node

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#24780] opened 2017-11-01 09:20 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4-beta2

When using .env in config, the casting is not work. 

```
Invalid type for path "easy_admin.list.max_results". Expected int, but got string.
```

![screenshot from 2017-11-01 16-19-53](https://user-images.githubusercontent.com/7464920/32268190-97b6ae3a-bf20-11e7-8990-79732b14bee3.png)

**Comment by sroze** [comment] 2017-11-01 09:35
@ad3n can you give us a sample of your `.env` and the configuration you use (where the `%env(...)%` is) ?

**Comment by ad3n** [comment] 2017-11-01 10:05
`'%env(int:SEMART_RECORD_PER_PAGE)%'` and from `.env` `SEMART_RECORD_PER_PAGE="17"`

even i remove the double quote `"` the result is same

**Comment by nicolas-grekas** [comment] 2017-11-01 10:08
That's unrelated to Dotenv, but that's correct, Config doesn't know about these cast env vars.
This is a duplicate of #22151, with a tentative unfinished fix in #23888.

**Comment by ad3n** [comment] 2017-11-01 10:16
@nicolas-grekas : thank you for your confirmation...

**Comment by javiereguiluz** [comment] 2017-11-01 10:52
Closing as a duplicate then. @ad3n thanks for reporting it!

**Closed by javiereguiluz** 2017-11-01 10:52 UTC
Labels: Dotenv
