### ISSUE TITLE
NativeRequestHandler is enabled by default

### ISSUE THREAD

**Issue by zolateater** [symfony/symfony#22460] opened 2017-04-18 00:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

I have installed symfony via  ```composer create-project symfony/framework-standard-edition some-project-name``` command.
This snippet (in controller) thows an exception.
```php
public function someAction(Request $request)
{
        $form = $this->createForm(SomeFormType::class);
        $form->handleRequest($request);
}
```

The exception occurs in vendor/symfony/symfony/src/Symfony/Component/Form/NativeRequestHandler.php at line 56.
Message: Expected argument of type "null", "Symfony\Component\HttpFoundation\Request" given
Type: UnexpectedTypeException.

As far as I understand this happens because request handler in Form component is set to NativeRequestHandler. 
But my config files don't contain any Form component settings at all. 
I know, this can be fixed by removing $request argument (which makes me unable to unit-test my forms) or manually enabling HttpFoundationExtension. 
But shoudn't this extension be enabled by default when I'm installing the whole framework? 
Please, correct me if I am wrong.

**Comment by xabbuh** [comment] 2017-04-18 08:20
Can you provide an example project that makes it possible to reproduce your issue?

**Comment by javiereguiluz** [comment] 2017-04-18 08:25
@zolateater if you need any help, we recently added an article explaining what do we expect when we tell you to "create something" to reproduce the issue: https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by zolateater** [comment] 2017-04-18 18:10
Okay, i was able to reproduce this:

- Clone https://github.com/zolateater/symfony-3-issue
- Run ``` composer install ```
- Run ``` php bin/console server:start ```
- Go to http://localhost:8000/web/error

**Comment by HeahDude** [comment] 2017-04-18 19:56
Hello @zolateater, thank you very much for linking a reproducer :).

The problem is this line: https://github.com/zolateater/symfony-3-issue/blob/master/src/WebBundle/Form/CustomType.php#L9.

You have two choices (the first one does not really work as is):
 - extend `Symfony\Component\Form\AbstractType` instead of `Symfony\Component\Form\Extension\Core\Type\FormType`.
   This is the recommended and documented way, all types should extend the abstract one, or you're on your own :). This abstract type just implements `getParent()` (and `getBlockPrefix()` which returns `FormType` and let the component handle the inheritance and extensions, otherwise next point.
 - you can keep the current configuration but you then need to call `parent::buildForm()` and do the same for every method of this interface and you won't have the benefice of extension because the component cannot resolve the inheritance and extensions for your type, but the request handler for http foundation actually is provided by an extension for the `FormType`.

Hope that helps, cheers!

**Comment by xabbuh** [comment] 2017-04-19 14:43
I am closing here for the reasons given by @HeahDude.

**Closed by xabbuh** 2017-04-19 14:43 UTC
Labels: Bug, Form, Status: Waiting feedback, Unconfirmed
