### ISSUE TITLE
Symfony ``cache.serializer`` pool clearing does not work in prod env

### ISSUE THREAD

**Issue by rsukonovs** [symfony/symfony#31036] opened 2019-04-09 10:50 UTC
**Symfony version(s) affected**: v3.4.24

**Description**  
Symfony ``cache.serializer`` pool clearing does not work in prod env.

**How to reproduce**  
```
git clone git@github.com:symfony/symfony-standard.git
cd symfony-standard/
composer install
php bin/console cache:pool:clear cache.serializer # works 
php bin/console cache:pool:clear cache.serializer --env=prod # does not work
```
Error message:
```
13:46:06 ERROR     [console] Error thrown while running command "cache:pool:clear 'cache.serializer' --env=prod". Message: "The "cache.serializer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException { …},"command" => "cache:pool:clear 'cache.serializer' --env=prod","message" => "The "cache.serializer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."]
```

**Comment by jewome62** [comment] 2019-04-10 13:52
Status: Reviewed

**Comment by jewome62** [comment] 2019-04-10 14:05
@nicolas-grekas I have reproduce this error.
if i change public="false" to public="true", the command work well in env prod
https://github.com/symfony/symfony/blob/84814be4c795bba6b0bc72138167e6e66307a3c7/src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.xml#L18-L28

**Comment by rsukonovs** [comment] 2019-04-12 06:02
Interesting thing is, that you can clear, for example, ``cache.annotations`` in prod env event if it is private service, but not ``cache.serializer``.

**Comment by nicolas-grekas** [comment] 2019-04-16 14:58
Maybe the `cache.serializer` pool is never used in this setup, so there is nothing to cache nor clear and the service is optimized out? Can anyone have a look?

**Comment by TomAdam** [comment] 2019-04-16 18:05
By default serialiser annotations are disabled so there isn't anything to cache. Setting `framework.validation.enable_annotations` to true fixes the issue. I haven't yet figured out why the behaviour is different in the dev env.

**Comment by TomAdam** [comment] 2019-04-16 19:44
It is of course the cache profiler that makes it work in the dev env.

**Comment by nicolas-grekas** [comment] 2019-04-16 19:47
Thanks for investigating, this means no but then, the error message said it all, right?

**Comment by TomAdam** [comment] 2019-04-16 20:29
Yes, no actual bug here. I think the DX could be better in terms of the error message but I can't see a way to do so without catching the `ServiceNotFoundException` and emitting a more contextual exception. This would however hide genuine container exceptions. If a cache is registered using the normal tag then this can't happen as it is within the `Psr6CacheClearer` and therefore available to the command.

Perhaps to much flexibility is being offered? The prune command only works on registered pools. Perhaps this should be the same for clear?

**Comment by nicolas-grekas** [comment] 2019-04-28 10:10
> It is of course the cache profiler that makes it work in the dev env.

you mean the pools are kept because the profiler references them to show them in the cache panel right?
Maybe that's something that could be improved? weak refs to the rescue?
If anyone would like to have a look, please tell.
Otherwise, let's close then. Thanks for inspecting the why.

**Comment by nicolas-grekas** [comment] 2019-05-21 15:12
Closing as discussed. Thanks for the talk.

**Closed by nicolas-grekas** 2019-05-21 15:12 UTC
Labels: Bug, Cache, FrameworkBundle, Status: Reviewed

**Comment by ettoredn** [comment] 2023-07-07 13:41
I'm hitting this error with the new command `bin/console cache:pool:clear --all`
