### ISSUE TITLE
From Symfony 3.4, ContainerBuilder cannot be used as a valid container anymore (missing container.build_id parameter)

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#26058] opened 2018-02-05 17:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | >=3.4.0

I noticed that, when using the dependency injection component without the fullstack framework that the ``ContainerBuilder`` cannot be used a container anymore (it was working from Symfony 2.0 to 3.3).

The context is the following: when using it with Drupal, it might happen that Drupal modules are being enabled, when they do, they are enabled one by one, implying a container rebuild each time.

Problem is that before 3.4, container was loaded using ``require_once`` and class name was always the same which lead the container NOT being reloaded even if changed due to ``require_once`` usage, and it was also impossible to manually include the file which would have lead to a duplicated class name hence a fatal error.

As a simple bypass, I was using this code as a replacement of Kernel::initializeContainer():
```php
    protected function initializeContainer()
    {
        $class = $this->getContainerClass();
        $cache = new ConfigCache($this->getCacheDir().'/'.$class.'.php', $this->debug);
        $fresh = true;
        if (!$cache->isFresh()) {
            $container = $this->buildContainer();
            $container->compile();
            $this->dumpContainer($cache, $container, $class, $this->getContainerBaseClass());

            $fresh = false;

            $this->container = $container;
        } else {
            require_once $cache->getPath();

            $this->container = new $class();
            $this->container->set('kernel', $this);
        }

        if (!$fresh && $this->container->has('cache_warmer')) {
            $this->container->get('cache_warmer')->warmUp($this->container->getParameter('kernel.cache_dir'));
        }
    }
```
The only notable change in this code is that I don't ``require_once`` the container when it is being rebuilt, but use directly the ``ContainerBuilder`` instance instead, which was until now gracefully working.

Now, if we try that since 3.4, it will fail with a fatal error due to the lack of the ``container.build_id`` parameter, and there's a few usages of it with the framework bundle enabled (it is being used as default values for cache adapters version parameter for example).

I did bypass this problem with a simple version compare and a fallback on the original Symfony kernel own ``initializeContainer()`` method now that the container class name do change thanks to its hashed name, but it is a breaking change:
```php
    protected function initializeContainer()
    {
        // From Symfony 3.4 only a require and not require_once is being used,
        // we can safely rely upon the parent implementation.
        if (0 <= version_compare(BaseKernel::VERSION, '3.4.0')) {
            return parent::initializeContainer();
        }

        // ...
```

Please note that it is very simple to bypass, and it is a very minor breakage since I guess that the ``ContainerBuilder`` was not meant to be used a container itself, nevertheless I suspect that other applications that might use the dependency injection manually could one day end up with the same problem - certainly under very, very peculiar conditions (such as the one I experienced).

**Comment by nicolas-grekas** [comment] 2018-02-27 17:54
Can't you define the parameter before using the ContainerBuilder directly as a container?
That should do it. Its value should be a random string, eg `a124fc27`. This value should change whenever you want to be sure all internal caches are invalidated (eg apcu - but there are other mean to clear these caches, so this is not a mandatory requirement, just a default behavior to allow Symfony to manage this for you accurately.)

**Comment by nicolas-grekas** [comment] 2018-02-27 17:54
I'm closing because AFAIK, this is not a bug.

**Closed by nicolas-grekas** 2018-02-27 17:54 UTC
Labels: Bug, DependencyInjection, Status: Needs Review

**Comment by stof** [comment] 2018-02-27 17:58
This is even less a BC break because the usage of `container.build_id` as default values for some config does not happen in logic being parts of the components directly, but in FrameworkBundle, which really expects the logic of HttpKernel (and so overriding it is at your own risk when upgrading, and might require adjustments).

Using the ContainerBuilder as a container directly outside the FrameworkBundle context kept working fine.
