### ISSUE TITLE
Autowire (dependency injection) not working for an entity listener. 

### ISSUE THREAD

**Issue by heigold1** [symfony/symfony#25003] opened 2017-11-16 23:04 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hi, 

The autowiring is not working for a basic file entity listener. 

I have a File entity class which uses annotations to specify the listener, like: 

/**
 * @ORM\Entity(repositoryClass="root\CoreBundle\Repository\FileRepository")
 * @ORM\EntityListeners({"root\CoreBundle\EventListener\Entity\FileEntityListener"})
 * @ORM\Table(

The FileEntityListener class starts off as follows:

class FileEntityListener
{
    private $encoderFactory;
    private $logger;

    public function __construct(FilesystemMap $filesystemMap, LoggerInterface $logger)
    {
        $this->setFilesystemMap($filesystemMap);
        $this->logger = $logger;
    }

When the listener kicks in, I get an error for the constructor, saying:  
Type error: Too few arguments to function Epcvip\CoreBundle\EventListener\Entity\FileEntityListener::__construct(), 0 passed in /var/www/html/accounting/vendor/doctrine/doctrine-bundle/Mapping/ContainerAwareEntityListenerResolver.php on line 83 and exactly 2 expected

The bundle is autowired and yet the dependencies are not being injected. 

Would anyone know why this isn't working?  Maybe a slight configuration step I am missing? 

Brent. 
![symfony_issue_auto_wire_file_listener](https://user-images.githubusercontent.com/8238482/32920708-2fda2a06-cadf-11e7-824a-42af71393398.png)

**Comment by ro0NL** [comment] 2017-11-17 09:14
> The bundle is autowired 

What about `root\CoreBundle\EventListener\Entity\FileEntityListener`? Did you configure a service definition for it?

See https://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html

**Comment by chalasr** [comment] 2017-11-17 10:42
Closing as this seems to be a support issue and we use Github issues for feature requests and bug reports only. Please use our [support platforms](https://symfony.com/support) instead.

**Closed by chalasr** 2017-11-17 10:42 UTC

**Comment by ThomasLandauer** [comment] 2018-08-16 13:07
I can confirm the issue with Symfony 4.1. I see it as a bug too, cause with services being autowired, I'd expect dependency injection to work just like @heigold1 showed above.

Anyway, here's the solution for now: https://stackoverflow.com/a/49836264/1668200 or https://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html

**Comment by stof** [comment] 2018-08-16 13:17
Autowiring works for services. If your entity listener is not registered as a service, the DI component cannot autowire, as it does not know about it (and then, instantiating the class will be performed by Doctrine itself)

**Comment by ThomasLandauer** [comment] 2018-08-16 14:53
Well, but with Symfony 4's default configuration, everything should be a service automatically, shouldn't it? That's the purpose of `resource: '../src/*'` in `services.yaml`

**Comment by xabbuh** [comment] 2018-08-16 15:13
@ThomasLandauer But you still need to tag the service yourself with the `doctrine.orm.entity_listener` tag. If you don't do that, Doctrine will not pick up your service.

**Comment by xabbuh** [comment] 2018-08-16 15:38
What do you mean with "it works"? Does your event listener have mandatory constructor arguments? If not, the class can just be instantiated by Doctrine IIRC.

**Comment by ThomasLandauer** [comment] 2018-08-16 16:09
I mean it works as listener; not as service. I don't have a constructor.

You mean, if I tag it as a service, Symfony instantiates it? And later, when Doctrine needs it, everything is already there? Is that the way dependency injection works?

So it can't work like @heigold1 and me expected, cause it's not Symfony itself who ultimately needs the class but Doctrine?

**Comment by zacharyzh** [comment] 2019-08-06 20:42
@stof 

Looks like the EntityListener is a original implementation from Doctrine. So I defined a new EntityListenerResolver instead and replaced default resolver through Compiler Pass.

    class AppEntityListenerResolver extends DefaultEntityListenerResolver
    {
        // ...
        
        public function resolve($className)
        {
            $listener = parent::resolve($className);
            if ($listener instanceof ContainerAwareInterface) {
                $listener->setContainer($this->container);
            }
            return $listener;
        }
    }

Maybe Symfony could create a new resolver to replace the original by default. Is this easy to implement?

Thanks.
