### ISSUE TITLE
Allow use HA Rabbit MQ cluster in symfony/amqp-messenger

### ISSUE THREAD

**Issue by tomasz-kusy** [symfony/symfony#45392] opened 2022-02-10 17:50 UTC
### Description

Hi,
Currently I don't see possibility to use Rabbit MQ cluster out of the box.
It could be useful to implement it.
If you find this proposal worth to implement it could try to think about prepare PR ;)

### Example

It could be implemented similarly to PhpAmqpLib (sad that isn't used in this project instead rely on php extension),

https://github.com/php-amqplib/php-amqplib/blob/84345976f7392e6205675d23da481fafaef20417/PhpAmqpLib/Connection/AbstractConnection.php#L1119

**Comment by lyrixx** [comment] 2022-02-11 08:29
https://www.rabbitmq.com/clustering.html#clients

It's recommended to use a DNS system or a proxy (like ha proxy) when using a cluster. 

So I'm not sure it's the responsibility of symfony to handle this

**Comment by fancyweb** [comment] 2022-02-11 08:45
Closing as duplicate of https://github.com/symfony/symfony/issues/35098.

**Closed as completed by fancyweb** 2022-02-11 08:45 UTC
Labels: Feature, Messenger
