### ISSUE TITLE
[WebProfilerBundle] Profiler theming not working

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28932] opened 2018-10-20 12:52 UTC
**Symfony version(s) affected**: 4.2

**Description**  

After clicking `Settings` in the profiler menu

```
Uncaught TypeError: Cannot set property 'checked' of null
```

cc @javiereguiluz

**Comment by ro0NL** [comment] 2018-10-21 13:01
also it's not responsive

![image](https://user-images.githubusercontent.com/1047696/47267309-33e4f180-d542-11e8-910d-134d61ceb52b.png)

**Comment by PythooonUser** [comment] 2018-10-21 16:00
I tried to reproduce your bug, but I can't grab Symfony version `4.2` to create a project.

**Comment by ro0NL** [comment] 2018-10-21 17:44
@PythooonUser  it's not tagged stable yet, using `4.2@dev` should work.

**Comment by PythooonUser** [comment] 2018-10-22 15:18
Okay, I created an empty project using:
```
$ composer create-project symfony/skeleton:dev-master issue_28932
$ composer require profiler --dev
```

And after starting the web server and opening the profiler I can confirm your findings.

**Comment by nicolas-grekas** [comment] 2018-11-11 11:18
Duplicate of  #28935 ?

**Comment by ro0NL** [comment] 2018-11-12 08:48
Not sure. Maybe both bugs have the same root cause yes. I wouldnt close one or another until confirmed / both fixed.

**Closed** 2018-11-12 16:46 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle
