### ISSUE TITLE
Cache collector doesn't show data on the right Request on the profiler

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#25645] opened 2017-12-31 12:09 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | -
| RFC?             | -
| Symfony version  | 3.4.x

First of all, sorry if it's not a bug, but it's worth creating an issue;

I've noticed that the profiler never shows the information about my pools in the right Request.

**Facts**: 
- The cache call are made on the main request.
- Inside app, the menu is rendered via a `{{ render(controller(...)) }}` call so it triggers 1 subrequest. **No cache calls were made on that subrequest**.

After spending some time on understanding what was happening, I discovered that the data is showing on the profiler of the **SUB REQUEST instead of the request itself**.

**to reproduce:** https://github.com/tristanbes/symfony-cache-profiler-bug (ping @xabbuh)

## cache pannel, where it should appear since the call were made on this request
![symfony_profiler](https://user-images.githubusercontent.com/346010/34614622-607ccbf8-f232-11e7-97e9-3778ce0e4ac6.png)

## cache pannel of the subrequest, where **no cache calls were made**
![symfony_profiler](https://user-images.githubusercontent.com/346010/34614583-3d7734c2-f232-11e7-9181-7b139a9ce412.png)

Thanks

**Comment by xabbuh** [comment] 2017-12-31 14:12
Can you create a small example project that allows to reproduce your issue?

**Comment by tristanbes** [comment] 2018-01-05 15:07
Ok,

I understand what's happening.

The cache call are made on the main request.
On the application, the menu is rendered via a `{{ render }}` call.

After spending some time on understanding what was happening, I discovered that the data is showing on the profiler of the **SUB REQUEST** instead of the request itself.

**to reproduce:** https://github.com/tristanbes/symfony-cache-profiler-bug

Screenshot of cache pannel, where it should appear since the call were made on this request
![symfony_profiler](https://user-images.githubusercontent.com/346010/34614622-607ccbf8-f232-11e7-97e9-3778ce0e4ac6.png)

Screnshot of cache pannel of the subrequest, where **no cache calls were made**
![symfony_profiler](https://user-images.githubusercontent.com/346010/34614583-3d7734c2-f232-11e7-9181-7b139a9ce412.png)

**Comment by tristanbes** [comment] 2018-01-11 09:05
Do I need to provide more context/information on this @xabbuh or is it ready to be reviewed ?

**Comment by tristanbes** [comment] 2018-01-17 10:37
ping @xabbuh :-)

**Comment by tristanbes** [comment] 2018-01-23 09:37
ping @nicolas-grekas 😥

**Comment by xabbuh** [comment] 2018-01-23 09:49
Status: Reviewed

**Comment by BoShurik** [comment] 2018-02-01 16:01
Probably duplicate https://github.com/symfony/symfony/issues/23820

**Comment by xabbuh** [comment] 2018-02-01 16:27
indeed, closing as a duplicate of #23820 then

**Closed by xabbuh** 2018-02-01 16:27 UTC
Labels: Bug, Cache, Status: Reviewed
