### ISSUE TITLE
EmailValidator allows 'é' 'è'

### ISSUE THREAD

**Issue by FabienPapet** [symfony/symfony#21583] opened 2017-02-10 18:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes ? 
| BC Break report? | maybe? 
| RFC?             | yes
| Symfony version  | 3.2 (also on 2.7)

Maybe it is a bug, or this is expected behavior, but `éàé@local.dev` seems to be a valid email (with strict_mode off, default behavior) 

The problem is when you want to send an email with this address, there is an Exception raised by swiftmailer because this email is not  RFC822 compliant .

Shouldn't we use the the `filter_var('éàé@local.dev', FILTER_VALIDATE_EMAIL)` which follows RFC 822 instead of a regex [here](https://github.com/symfony/validator/blob/master/Constraints/EmailValidator.php#L81) ?

**Comment by xabbuh** [comment] 2017-02-10 19:19
That's the expected behaviour. If you need to catch more invalid e-mail addresses, you need use the `strict` option. `filter_var()` was used in the past, but it had other issues. If you want to read more about this, you can take a look at these issues (there are probably more about this topic): #18162, #18560, #19385 and #20309

In #1581 you can read more about the discussion that led to the introduction of the `strict` option and dropping the use of `filter_var()` (see PR this features was introduced with is #9140).

Since there is no bug in the component I am closing here. Thank you for understanding.

**Closed by xabbuh** 2017-02-10 19:19 UTC
Labels: Validator
