### ISSUE TITLE
Expected argument of type "App\Entity\Test or null", "array" given at property path "Test"

### ISSUE THREAD

**Issue by Loooooouuuuu** [symfony/symfony#29959] opened 2019-01-23 00:26 UTC
**Symfony version(s) affected**: 4.2.2

**Description**  
I am not sure if this is a bug or if i did something wrong. 
I'm trying to create a form with an EntityType. If I do it without a FormType it works well, but if I put my form builder in a FormType, I get the error : 
"Expected argument of type "App\Entity\Test or null", "array" given at property path "Test"" when using a form type."

I suppose it is caused by the name of the rendered element : `name="form[test][test]"` with a FormType, `form[test]` without.

Thanks for your help !

**How to reproduce**  
Here's a repository showcasing the problem : https://github.com/Loooooouuuuu/sf4-help-plz

**Comment by xabbuh** [comment] 2019-01-24 16:45
I cannot reproduce your issue. I cloned your repo and submitted the form, but there was no error. Can you explain which additional steps are necessary?

**Comment by Loooooouuuuu** [comment] 2019-01-24 17:11
I cloned the repo, in the database I have two tables: "Test and "TestParent". In "Test" I put some random data, and in TestParent I put one record with the ID 1 and test_id as null. On the website, the form should print every records in Test. When I submit the form, I get this: 
`Expected` argument of type "App\Entity\Test or null", "array" given at property path "test".`

```
InvalidArgumentException
HTTP 500 Internal Server Error
Expected argument of type "App\Entity\Test or null", "array" given at property path "test".

    Exception Logs 1 Stack Trace 

Symfony\Component\PropertyAccess\Exception\ InvalidArgumentException
in vendor/symfony/property-access/PropertyAccessor.php (line 173)
in vendor/symfony/property-access/PropertyAccessor.php::throwInvalidArgumentException (line 153)
in vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php->setValue (line 86)
in vendor/symfony/form/Form.php->mapFormsToData (line 634)
in vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php->submit (line 108)
in vendor/symfony/form/Form.php->handleRequest (line 494)
Form->handleRequest(object(Request)) in src/Controller/TestController.php (line 23)

        {
            $TestParent = $this->getDoctrine()->getRepository(TestParent::class)->find(1);
            $form = $this->createFormBuilder($TestParent)
                ->add('test', TestType::class)
                ->getForm();
            $form->handleRequest($request);
            if ($form->isSubmitted()) {
                die('ok');
            }
            return $this->render('test/index.html.twig', [

in vendor/symfony/http-kernel/HttpKernel.php->index (line 150)
in vendor/symfony/http-kernel/HttpKernel.php->handleRaw (line 67)
in vendor/symfony/http-kernel/Kernel.php->handle (line 198)
Kernel->handle(object(Request)) in public/index.php (line 25)
```

I should've been more specific in my first post, sorry about that

**Comment by hacfi** [comment] 2019-01-25 10:07
@Loooooouuuuu Just change the controller code to:

```
$TestParent = $this->getDoctrine()->getRepository(TestParent::class)->find(1);
$form = $this->createForm(TestType::class, $TestParent);
$form->handleRequest($request);
```

and it works fine.

The reason why you get an error is because you create a form on the fly that nests the test form one level down. You would need to use

```
$form = $this->createFormBuilder(['test' => $TestParent])
    ->add('test', TestType::class)
    ->getForm();
```

to get rid of the error. I recommend using `$this->createForm` instead though.

**Comment by xabbuh** [comment] 2019-01-27 11:45
I am closing here as there is no bug as explained by @hacfi.

**Closed by xabbuh** 2019-01-27 11:45 UTC
Labels: Bug, Form, Status: Waiting feedback, Unconfirmed
