### ISSUE TITLE
Unable to create new project 

### ISSUE THREAD

**Issue by pkconcept** [symfony/symfony#52754] opened 2023-11-27 11:22 UTC
### Symfony version(s) affected

6.3.*

### Description

Unable to create new project 
!!  PHP Fatal error:  Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration) in 

### How to reproduce

symfony new appDepot --version="6.3.*" --webapp                                                                                                 

### Possible Solution

fix bug ? :)

**Comment by xabbuh** [comment] 2023-11-27 11:38
Your issue comes from using the [PHP PSR extension](https://github.com/jbboehr/php-psr). It looks like it only provides the interfaces for `psr/cache` 1.0 but the Cache component requires version 2 or 3 of `psr/cache`. There's nothing we can do in Symfony about it.

**Comment by derrabus** [comment] 2023-11-27 11:38
Duplicate of #49984. Don't use the PSR extension.

**Closed as not planned by xabbuh** 2023-11-27 11:38 UTC
Labels: Bug, Status: Needs Review

**Comment by pkconcept** [comment] 2023-11-27 11:40
Sorry but it's a symfony bug, using php 8.2.2 as standard, and can't create a project...
symphony is incompatible with 8.2.2

**Comment by xabbuh** [comment] 2023-11-27 11:41
No, the PSR extension is not part of the PHP core. You need to uninstall it.

**Comment by pkconcept** [comment] 2023-11-27 11:43
PSR extension is available as a standard extension , so everyone can install and use it.
Symfony install must check before proceed ...

**Comment by pkconcept** [comment] 2023-11-27 11:43
My fresh php install , for a new project :

php8.2 - server-side, HTML-embedded scripting language (metapackage)
php8.2-bcmath - Bcmath module for PHP
php8.2-bz2 - bzip2 module for PHP
php8.2-cli - command-line interpreter for the PHP scripting language
php8.2-common - documentation, examples and common module for PHP
php8.2-curl - CURL module for PHP
php8.2-decimal - Arbitrary precision floating-point decimal for PHP
php8.2-dev - Files for PHP8.2 module development
php8.2-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php8.2-gd - GD module for PHP
php8.2-gmp - GMP module for PHP
php8.2-http - PECL HTTP module for PHP Extended HTTP Support
php8.2-igbinary - igbinary PHP serializer
php8.2-imagick - Provides a wrapper to the ImageMagick library
php8.2-imap - IMAP module for PHP
php8.2-inotify - Inotify bindings for PHP
php8.2-interbase - Interbase module for PHP
php8.2-intl - Internationalisation module for PHP
php8.2-ldap - LDAP module for PHP
php8.2-mailparse - Email message manipulation for PHP
php8.2-mbstring - MBSTRING module for PHP
php8.2-memcache - memcache extension module for PHP
php8.2-memcached - memcached extension module for PHP, uses libmemcached
php8.2-mongodb - MongoDB driver for PHP
php8.2-msgpack - PHP extension for interfacing with MessagePack
php8.2-mysql - MySQL module for PHP
php8.2-oauth - OAuth 1.0 consumer and provider extension
php8.2-odbc - ODBC module for PHP
php8.2-opcache - Zend OpCache module for PHP
php8.2-pcov - Code coverage driver
php8.2-pgsql - PostgreSQL module for PHP
php8.2-pspell - pspell module for PHP
php8.2-psr - PSR interfaces for PHP
php8.2-raphf - raphf module for PHP
php8.2-readline - readline module for PHP
php8.2-redis - PHP extension for interfacing with Redis
php8.2-smbclient - PHP wrapper for libsmbclient
php8.2-snmp - SNMP module for PHP
php8.2-soap - SOAP module for PHP
php8.2-sqlite3 - SQLite3 module for PHP
php8.2-ssh2 - Bindings for the libssh2 library
php8.2-stomp - Streaming Text Oriented Messaging Protocol (STOMP) client module for PHP
php8.2-sybase - Sybase module for PHP
php8.2-tidy - tidy module for PHP
php8.2-uploadprogress - file upload progress tracking extension for PHP
php8.2-uuid - PHP UUID extension
php8.2-xdebug - Xdebug Module for PHP
php8.2-xhprof - Hierarchical Profiler for PHP 5.x
php8.2-xml - DOM, SimpleXML, XML, and XSL module for PHP
php8.2-xmlrpc - XML-RPC servers and clients functions for PHP
php8.2-xsl - XSL module for PHP (dummy)
php8.2-yac - YAC (Yet Another Cache) for PHP
php8.2-yaml - YAML-1.1 parser and emitter for PHP
php8.2-zip - Zip module for PHP
php8.2-zmq - ZeroMQ messaging bindings for PHP
php8.2-zstd - Zstandard extension for PHP

**Comment by xabbuh** [comment] 2023-11-27 11:49
This is simply not possible and there is nothing we can do about this rather than telling you to uninstall this extension.

**Comment by derrabus** [comment] 2023-11-27 12:12
> PSR extension is available as a standard extension

It's an extension someone published on PECL. There's nothing "standard" about it.

This extension is defective. Please just don't use it.

**Comment by pkconcept** [comment] 2023-11-27 12:22
Ok, removed ... but still not working .. sory..

11 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
115 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> symfony-cmd
sh: 1: symfony-cmd: not found
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-update-cmd

                                                                         
  unable to run /usr/local/bin/composer require webapp --no-interaction
