### ISSUE TITLE
[Form] Empty data fails on OneToOne / OneToMany by converting null to empty string

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#21890] opened 2017-03-06 10:43 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2 (didn't see anything related to this in the .4 changelog)

I'm currently having an issue with the `empty_data` handling of a bidirectional OneToOne association (edit: reworking to OneToMany is not difference). Submitting an empty entity choice results in a query exception as it's trying to fetch the value by an empty string for an integer.

AcmeFormType:

```php
    $form->add(...);
    $form->add('employee', EntityType::class, [
        'label' => _('Employee'),
        'class' => Employee::class,
        'required' => false,
        'empty_data' => null,
    ])
```

AcmeEntity:

```php
class Acme
{
   /**
     * @ORM\OneToOne(targetEntity="Acme\Employee", inversedBy="acme")
     * @ORM\JoinColumn(name="employee", referencedColumnName="id", nullable=true)
     *
     * @var Employee
     */
    private $employee = null;

    /**
     * @param Employee $employee
     */
    public function setEmployee(Employee $employee = null)
    {
        $this->employee = $employee;
    }
}
```

Exception:

```
[1] Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT e0_.id AS id_0, acme.acme FROM employees e0_ WHERE e0_.id IN (?)' with params [""]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
    at n/a
        in /usr/share/iserv/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91
        [...]

        in /usr/share/iserv/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php line 50

    at Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(object(Connection), array(array('')), array(102))
        in /usr/share/iserv/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 321

    at Doctrine\ORM\Query->_doExecute()
        in /usr/share/iserv/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 969

    at Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(null, 1)
        in /usr/share/iserv/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 924

    at Doctrine\ORM\AbstractQuery->execute(null, 1)
        in /usr/share/iserv/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 727

    at Doctrine\ORM\AbstractQuery->getResult()
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php line 92

    at Symfony\Bridge\Doctrine\Form\ChoiceList\ORMQueryBuilderLoader->getEntitiesByIds('id', array(''))
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Form/ChoiceList/DoctrineChoiceLoader.php line 158

    at Symfony\Bridge\Doctrine\Form\ChoiceList\DoctrineChoiceLoader->loadChoicesForValues(array(''), array(object(IdReader), 'getIdValue'))
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/LazyChoiceList.php line 184

    at Symfony\Component\Form\ChoiceList\LazyChoiceList->getChoicesForValues(array(''))
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php line 46

    at Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer->reverseTransform(null)
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1126

    at Symfony\Component\Form\Form->viewToNorm(null)
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 622

    at Symfony\Component\Form\Form->submit('', true)
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 562

    at Symfony\Component\Form\Form->submit(array('number' => '123', 'employee' => '', 'actions' => array('submit' => ''), '_token' => '4CM9xOgOcichkXrxNaUbTZ4axwk3FxqSgB4pfhaNmfk'), true)
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php line 113

    at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(Request))
        in /usr/share/iserv/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 488

    at Symfony\Component\Form\Form->handleRequest(object(Request))
        in /root/git/iserv-crud/bundle/CrudBundle/Controller/CrudController.php line 493

    at IServ\CrudBundle\Controller\CrudController->addAction(object(Request))
```

So it's basically the reverse transformation which converts the empty data `null` into the empty string `''` which isn't a valid value for an DB integer. I have no clue why this is done. :(

I also tried `[]` as an empty data value. This resolves the transformation issue, but makes the field mandatory instead of optional. 

Cheers
Matthias

**Comment by xabbuh** [comment] 2017-03-06 12:35
Could you create a small example project that reproduces your issue?

**Comment by jordscream** [comment] 2017-03-19 20:45
@althaus , strange for me , I did a same test and it success to me... needs small example project as suggest @xabbuh

**Comment by althaus** [comment] 2017-03-20 07:54
At the moment I cannot provide more information as in my root post. We've got a quite complex system and I cannot easily create an abstract of the issue. In addition I'm pretty sure that a simple reduction of the scenario will work flawlessly (otherwise the Doctrine guy wouldn't missed it). The exception was thrown nevertheless. I'd track it down to the transformer which enforces the empty string, but I couldn't follow the code further on *why* it's doing that. Must be some webmozart magic.

As it was a show stopper for us we reworked the code/database. I'll come back if we encounter this again.

**Comment by althaus** [comment] 2017-04-19 07:40
@jordscream @xabbuh Just to add some more details as we had the issue again after converting it to a ManyToOne association. The source of our problem is the used `ChoiceToValueTransformer`:

https://github.com/symfony/symfony/blob/v3.2.6/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L46

```
    public function reverseTransform($value)
    {
        if (null !== $value && !is_string($value)) {
            throw new TransformationFailedException('Expected a string or null.');
        }
        $choices = $this->choiceList->getChoicesForValues(array((string) $value));
        if (1 !== count($choices)) {
            if (null === $value || '' === $value) {
                return;
            }
            throw new TransformationFailedException(sprintf('The choice "%s" does not exist or is not unique', $value));
        }
        return current($choices);
    }
```

In line 46 the value is converted hard to string. This results in PostgreSQL receiving an empty string for an integer (array) and our exception. The similar `ChoicesToValuesTransformer` (Choice**S** instead of singular Choice) doesn't have this conversion. Removing the string cast makes the query work correctly. I don't know the reasons for the cast, perhaps @webmozart can shine some light, but in my eyes it's not correct.

**Comment by dmaicher** [comment] 2017-04-22 10:50
This seems wrong indeed :cry: MySQL (tested it with version 5.5) allows performing such a query.

Should we maybe not perform a query at all if `null === $value || '' === $value`? Seems unnecessary to me.

**Comment by althaus** [comment] 2017-08-02 07:28
@xabbuh @dmaicher @jordscream The issue still remains. Anything we can do to get this sorted out? Should I invest some time to create a demo project showing the issue (which seems to be PostgreSQL related)?

**Comment by xabbuh** [comment] 2017-08-02 14:08
@althaus At least that would not hurt and would maybe allow someone to better find the root cause of your issue.

**Comment by xabbuh** [comment] 2018-09-23 11:48
closing here as we would need more information

**Closed by xabbuh** 2018-09-23 11:48 UTC
Labels: Bug, Form, Status: Needs Review
