### ISSUE TITLE
Twig namespaced path doesn't work with Bundle inheritance

### ISSUE THREAD

**Issue by wesleylancel** [symfony/symfony#17834] opened 2016-02-17 20:31 UTC
When using the following notation for extending a layout:

`{% extends "@FOSUser/layout.html.twig" %}`

the view from the actual `FOSUserBundle` is used, even when it's overriden by a bundle that implements:

```
public function getParent()
{
    return 'FOSUserBundle';
}
```

**Comment by Tobion** [comment] 2016-02-17 21:13
Duplicate of #6919

**Closed by Tobion** 2016-02-17 21:13 UTC
