### ISSUE TITLE
[PropertyInfo] Optional dependency phpdocumenter/reflection-docblock is a risk when already installed as dev-dependency

### ISSUE THREAD

**Issue by jeroennoten** [symfony/symfony#40136] opened 2021-02-09 08:42 UTC
**Symfony version(s) affected**: 3.4.47 & 4.4.19 & 5.2.3

**Description**  
`phpdocumenter/reflection-docblock` is an optional dependency of `symfony/property-info`, but a required dependency when the `PhpDocExtractor` is used. If someone wants to use the `PhpDocExtractor` and did not install `phpdocumenter/reflection-docblock`, then a  clear exception is shown:

```
Unable to use the "PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed.
```

So far, so good. Install the dependency and continue.

The problemen arises when `phpdocumentor/reflection-docblock` is already installed as a require-dev dependency, which is probably true in many projects: `phpdocumentor/reflection-docblock` is a dependency of `phpunit/phpunit`. In those cases, you don't get the exception and things work fine while developing and testing. However, after deploying the application to production, it breaks. Require-dev dependencies are not installed, and therefore `phpdocumentor/reflection-docblock` is not installed, and thus the exception is only shown in production.

I think this is a big risk. There is no automated way to test this kind of things, because automated test tools also usually run with development dependencies. The underlying problem is that in composer, dev en production dependencies are mixed. Therefore, production code can (accidentally) depend on dev-dependencies.

This is of course a problem with all optional dependencies that could break the application when not present. But this use case is probably more common than others, and therefore a bigger risk.

**How to reproduce**  
Create a project with `symfony/property-info` as dependency and `phpunit/phpunit` as dev-dependency and make use of the `PhpDocExtractor`. This works, until installling the application without dev-dependencies.

**Possible Solution**  
The ultimate solution is to not rely on optional dependencies, because they could be available during development, but not in production. Instead, either require the dependency or extract the piece of code that requires the dependency to a separate composer package.

**Comment by nicolas-grekas** [comment] 2021-02-09 08:58
Thanks for the report.

This is exactly the reason why `phpunit/phpunit` nor any tools should not be added to your `composer.json` file.

See https://github.com/composer/composer/issues/9636 for some more ideas on the topic.

Closing here as there is nothing we can do in Symfony.

**Closed as completed by nicolas-grekas** 2021-02-09 08:58 UTC
Labels: Bug, Status: Needs Review, PropertyInfo

**Comment by jeroennoten** [comment] 2021-02-09 09:13
> Closing here as there is nothing we can do in Symfony.

I'm fine with closing this. But I think there is actually at least something we can do in Symfony: until this is fixed by composer, do not rely on optional dependencies. Instead, either require the dependency or extract the piece of code that requires the dependency to a separate composer package.

Fortunately, I see that Symfony is doing this more and more: e.g. packages like `symfony/messenger` are split into multiple packages instead of relying on optional dependencies. I hope this will be Symfony's new way of building packages, and not the way it is done in property-info.

@nicolas-grekas what is your opinion about moving the `PhpDocExtractor` to a separate package (like `symfony/property-info-phpdoc`) in a next major version to circumvent this problem in the future?

**Comment by nicolas-grekas** [comment] 2021-02-09 10:39
More packages means more maintenance burden. I'd prefer not.

Instead, I propose leveraging this once it's accepted: https://github.com/composer/composer/pull/9682

**Comment by derrabus** [comment] 2021-02-09 10:56
> Instead, I propose leveraging this once it's accepted: [composer/composer#9682](https://github.com/composer/composer/pull/9682)

How would this look like? Note that if `PhpDocExtractor` was only used in non-prod code (some web profiler integration for instance), it would be absolutely okay if `phpdocumenter/reflection-docblock` is a dev dependency.

I don't think that this is actually an issue of prod/dev dependencies. The problem is rather that the application relies on the presence of `phpdocumenter/reflection-docblock` without directly depending on it. In the scenario drafted by @jeroennoten, `phpdocumenter/reflection-docblock` is a transitive dependency that might also go away if the package that depends on the library (here PHPUnit) drops it in a later release.

**Comment by nicolas-grekas** [comment] 2021-02-09 11:16
Here is how this would look like: https://github.com/symfony/symfony/pull/40140

**Comment by derrabus** [comment] 2021-02-09 12:57
So `PhpDocExtractor` basically won't be available if `phpdocumenter/reflection-docblock` is only a dev dependency. So, if an application uses `PhpDocExtractor` for dev tooling only (web profiler, code generators etc.) and thus loads `phpdocumenter/reflection-docblock` via `require-dev`, that application would suddenly break, correct?

**Comment by xabbuh** [comment] 2021-02-09 13:16
related to #39356 I guess

**Comment by nicolas-grekas** [comment] 2021-02-09 13:29
@derrabus that's correct, as that's the fix. Note that the BC promise doesn't cover composer deps. We already made changes that could lead to similar behaviors in the past.

**Comment by derrabus** [comment] 2021-02-09 17:11
What bothers me is that we would break applications that documented their dependencies *correctly* in order to work around a problem of apps with *incorrect* dependencies. I kinda start to like the idea of a bridge package for phpDocumentor, I must admit.

**Comment by nicolas-grekas** [comment] 2021-02-10 09:08
@jeroennoten there is something that I don't understand: how do you end up wiring `PhpDocExtractor` if it's not installed?
This can happen by
1. dumping the container while deps are in dev-mode
2. reinstall deps in no-dev mode

Is it what you do?

**Comment by jeroennoten** [comment] 2021-02-10 09:25
@nicolas-grekas I'm not sure if I understand your question correctly, but I'll try to give you some more context. This problem happened in a library I was working on that used the Symfony Serializer component as a dependency (and therefore also the PropertyInfo component), so not a full Symfony application that has a DI container. The library is used to communicate with an external service and it had to do some (de)serialization. In that library, when I construct the `Serializer`, I add an `ObjectNormalizer` with a `PropertyInfoExtractor` that uses a `PhpDocExtractor` as type extractor. The library also requires `phpunit/phpunit` as a dev-dependency, and therefore I got no errors and all tests passed. At that point, I was not aware that I had to require `phpdocumentor/reflection-docblock` separately.

Then, when I required the library in one of the PHP applications that needed to communicate with this external service, things still worked fine, because the applications itself also required `phpunit/phpunit`. But then, when we deployed the application, we got the error that `phpdocumentor/reflection-docblock` was not installed.

It took some time to figure out why this did work during development, but not in production. In the end, I of course required `phpdocumentor/reflection-docblock` as a dependency in the library, because that seemed to be required when using the `PhpDocExtractor`. But in my opinion, this is bad developer experience.

Does this answer your question?

**Comment by nicolas-grekas** [comment] 2021-02-10 10:31
It does thanks. Maybe https://packagist.org/packages/maglnet/composer-require-checker could help.
I still think creating a separate package would be a too high maintenance overhead for the situation.
You have a dep issue, it's fixed now...

**Comment by jeroennoten** [comment] 2021-02-10 10:41
Will that tool help? I don't think so, because in **my code** I am only using classes provided by the packages I directly depend on. `PhpDocExtractor` is a class available in `symfony/property-info`, which is listed as a dependency of my code. However, Symfony PropertyInfo's code depends on a package that is **not** listed as a required package. So maybe Symfony can use this tool to detect packages that it uses but not list as a dependency. If these rules are followed, then `phpdocumentor/reflection-docblock` should be a dependency of `symfony/property-info`, which is not ATM.

**Comment by nicolas-grekas** [comment] 2021-02-10 10:44
As you wrote in your initial description, `reflection-docblock` is an optional dependency.
I understand what you're asking for. Please understand what it would mean for us, in terms of maintenance.
We have to make choices to keep things maintainable.

**Comment by jeroennoten** [comment] 2021-02-10 10:47
Ok, thank you, I understand. I was trying to figure out if `maglnet/composer-require-checker` could help with detecting this kind of problems. I think it's a very nice tool for detecting missing dependencies, so thanks for the suggestion.

But it will probably not help with this kind of problem, regarding optional dependencies, am I right?

**Comment by nicolas-grekas** [comment] 2021-02-10 10:55
> But it will probably not help with this kind of problem, regarding optional dependencies, am I right?

It might when you're using their namespace in your lib, but if that's not the case, then I guess you're right yes.
