### ISSUE TITLE
[LDAP] Update throws "Constraint violation"

### ISSUE THREAD

**Issue by estahn** [symfony/symfony#21328] opened 2017-01-18 05:50 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

When fetching an entry from the ActiveDirectory server and then immediately saving it again, we see the following error:

```bash
[Symfony\Component\Ldap\Exception\LdapException]
  Could not update entry "CN=User1234,OU=Foo,OU=Users,OU=org,DC=corp,DC=domain,DC=com": Constraint violation
```

If using only certain attributes, e.g.

```php
ldap_modify($this->ldap->getEntryManager()->connection->getResource(), $person->getId(), ['givenName' => 'Foo1']);
```

It will succeed.

So pushing the entire LDAP entry to be updated is not working or will not always work.

**Comment by xabbuh** [comment] 2017-03-05 19:44
@csarrazi Can you have a look here?

**Comment by csarrazi** [comment] 2017-03-05 20:26
@estahn can you try adding the `'debug' => true` option in your service, in order to have more information?

This is probably a limitation due to your LDAP server only letting you edit a limited set of attributes. It is not a bug from the component, but rather a limitation due to server configuration.

This should be fixed once a better implementation of #21856 will be implemented (I suggested an implementation in the related PR).

**Comment by xabbuh** [comment] 2017-04-14 09:22
@estahn Can you please give feedback on @csarrazi's comment?

**Comment by javiereguiluz** [comment] 2017-05-07 17:16
@estahn did you manage to try the solution proposed by @csarrazi? Thanks!

**Comment by xabbuh** [comment] 2017-05-12 14:41
ping @estahn :)

**Comment by estahn** [comment] 2017-05-15 00:36
Sorry for the late response. I will have a look this week.

**Comment by xabbuh** [comment] 2017-07-17 07:23
Closing for now due to the lack of a reproducer. Please leave a comment with more information and we can consider to reopen.

**Closed by xabbuh** 2017-07-17 07:23 UTC
Labels: Bug, Ldap, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by Sonny333Black** [comment] 2017-09-11 09:51
update dosen't work. I have the same Error (Constraint violation).

updating the entry with mod_replace works with following code:

`if (!@ldap_mod_replace($con, $dn, $data)) {
       throw new LdapException(sprintf('Could not modify entry "%s": %s', $dn, ldap_error($con)));
}`

**Comment by xabbuh** [comment] 2017-09-11 09:59
@Sonny333Black Are you able to provide a small reproducer?

**Comment by Sonny333Black** [comment] 2017-09-11 12:07
@xabbuh because by some attributes I don't have the premission
to update. I need a methode in the entry-manager that updating a single attribute like a mod_replace.

**Comment by vittore** [comment] 2020-02-05 13:26
> @xabbuh because by some attributes I don't have the premission
> to update. I need a methode in the entry-manager that updating a single attribute like a mod_replace.

+1

**Comment by xabbuh** [comment] 2020-02-05 16:59
@vittore see https://github.com/symfony/symfony/issues/21328#issuecomment-328482139

**Comment by vittore** [comment] 2020-02-05 20:14
Using Microsoft Active Directory.

Not working example :
```
$search = $ldap->query($ldap_base_dn, $query); // A generic query
$result = $query->execute();
$entry = $result[0];
$entry->setAttribute('mail', ['fabpot@symfony.com']);
$entryManager = $ldap->getEntryManager();
$entryManager->update($entry);  // Throws "Constraint violation" exception

```


Working example:
```
$search = $ldap->query($ldap_base_dn, $query); // A generic query
$result = $query->execute();
$entry = $result[0];
$entryManager = $ldap->getEntryManager();
$entry2 = new Entry($entry->getDn(), ['mail' =>'fabpot@symfony.com']);
$entryManager->update($entry2);   // Successfully update
```

**Comment by csarrazi** [comment] 2020-02-19 07:25
To give some feedback on this, the original intent for the component was to implement a change manager for the LDAP entries. E.g. being able to do `entry->replaceAttribute($attr, $val)` or `entry->addAttribute($attr, $val)` (difference between single-valued and multi-valued attributes), and have the entry object provide its own changes to the EntryManager.
