### ISSUE TITLE
Implement `PruneableInterface` on `RedisTagAwareAdapter`

### ISSUE THREAD

**Issue by giudicelli** [symfony/symfony#57189] opened 2024-05-27 03:42 UTC
### Description

The main issue when using "RedisTagAwareAdapter" is the never "expiring" entries (SET) used for the tags.
When an item (STRING) expires, it's not removed from any of its associated tags "SET", therefore the cache tends to grow and grow, and over time it will reach a point where it will have to be flushed.
Would it be possible to implement "PruneableInterface" on "RedisTagAwareAdapter" to remove entries from tags "SET" when the cache item doesn't exist anymore and then possibly remove the whole "SET" if it's empty?

**Comment by nicolas-grekas** [comment] 2024-05-28 13:02
Closing as duplicate of #47835.
Review welcome on #50423

**Closed as not planned by nicolas-grekas** 2024-05-28 13:02 UTC
Labels: Feature, Cache
