### ISSUE TITLE
symfony/web-profiler-bundle - Unknown "empty" filter.

### ISSUE THREAD

**Issue by daymerfillad** [symfony/symfony#42275] opened 2021-07-27 03:20 UTC
I recently installed web-profiler-bundle 5.3 "symfony / web-profiler-bundle": "^ 5.3" "and the bar is not displayed due to the following error **Unknown "empty" filter.**

**vendor \ symfony \ web-profiler-bundle \ Resources \ views \ Collector \ mailer.html.twig (line 67)**

**Comment by jerome-fix** [comment] 2021-07-27 03:59
Hello,

Same here with symfony/web-profiler-bundle :"4.4.27" and twig/twig:"2.14.6"

**Comment by zerkms** [comment] 2021-07-27 04:00
This commit broke it https://github.com/symfony/symfony/commit/4be962d3236e138e075c97134d79a66567bbd442

**Comment by fabpot** [comment] 2021-07-27 04:23
duplicate of #42268

**Closed as completed by fabpot** 2021-07-27 04:23 UTC
Labels: Bug, Status: Needs Review
