### ISSUE TITLE
Broken test SigchildEnabledProcessTest::testPTYCommand

### ISSUE THREAD

**Issue by ewgRa** [symfony/symfony#16280] opened 2015-10-18 19:16 UTC
```
There was 1 failure:

1) Symfony\Component\Process\Tests\SigchildEnabledProcessTest::testPTYCommand
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'foo
+sh: 1: 3: Bad file descriptor
 '
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
```

```
uname -a
Linux ewgra-Inspiron-5720 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

At Process::start proc_open have arguments:
$commandLine : string(61) "(echo "foo") 3>/dev/null; code=$?; echo $code >&3; exit $code"

$descriptors =
array(4) {
  [0]=>
  array(1) {
    [0]=>
    string(3) "pty"
  }
  [1]=>
  array(1) {
    [0]=>
    string(3) "pty"
  }
  [2]=>
  array(1) {
    [0]=>
    string(3) "pty"
  }
  [3]=>
  array(2) {
    [0]=>
    string(4) "pipe"
    [1]=>
    string(1) "w"
  }
}

$this->processPipes->pipes = array(0) {}

**Comment by ewgRa** [comment] 2015-10-18 19:18
Not so familiar with pipes and descriptors, is problem in empty pipes?

Can somebody who have this test passed var_dump proc_open arguments?

**Comment by xabbuh** [comment] 2015-10-20 16:51
I do not have this problem on a similar machine. Which Symfony version did you run the tests on?

**Comment by jaytaph** [comment] 2015-10-20 18:52
This is a duplicate of #12643 . I've added some (detailed) explanation about the bug (it's a nasty one!): https://github.com/symfony/symfony/issues/12643#issuecomment-92279343

The problem is actually a bug in PHP, but a relatively simple workaround in Symfony is possible. Since this is (at least) the second time somebody run into it, it might be worth the PR?

**Closed** 2015-10-20 19:07 UTC
Labels: Process, Unconfirmed
