### ISSUE TITLE
[PHPUnit] Will not read `<env>` from phpunit.xml in parallel tests

### ISSUE THREAD

**Issue by lsv** [symfony/symfony#35394] opened 2020-01-19 21:24 UTC
**Symfony version(s) affected**: ^4.0, ^5.0

**Description**  
If I put env variables inside my multiple phpunit.xml.dist file (parallel tests) they will be ignored.

**How to reproduce**  
```
git clone https://github.com/lsv/symfony-phpunit-parallel-test.git
composer install
bin/phpunit tests
```

In this each tests directory I have `phpunit.xml.dist` file with the following xml

```
....
<php>
        <env name="TEST_ENV_VAR" value="..."/>
</php>
....
```

Which I think should be read in each test instance

**Possible Solution**  
I dont know excatly how they can be read

**Additional context**  
If you run parallel tests with fx database, the database will be overridden by each test instance, therefor each test instances should have a unique database name, so its only the parallel instance that read from that database. Therefor it can not be added to `.env.test` as this is global for all test instances.

**Comment by lsv** [comment] 2020-09-30 13:51
No news on this issue?

Maybe it should be added to the [documentation](https://symfony.com/doc/current/components/phpunit_bridge.html#running-tests-in-parallel) that ENV vars can not be set in the phpunit.xml inside the tests directory.

**Comment by nicolas-grekas** [comment] 2020-10-01 13:27
Thanks for the ping. Actually, that's kinda expected: the bridge runs phpunit from the root directory, which means that only the root phpunit.xml.dist file is going to be used.

In order to run several standalone phpunit test suites in parallel, you'd better use `xargs` (or `parallel`) binary (we do so in the Symfony test suite itself.)

Closing as "not a bug".

**Closed by nicolas-grekas** 2020-10-01 13:27 UTC
Labels: Bug, PhpUnitBridge, Status: Needs Review
