### ISSUE TITLE
Make format in template names optional

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#19537] opened 2016-08-04 20:54 UTC
Currently `Symfony/Bundle/FrameworkBundle/Templating/TemplateNameParser` expects template names in format `{bundle}:{namespace?}:{name}.{format}.{engine}`

I'm wondering why is the `{format}` mandatory? I have a template for FOSUserBundle containing two blocks - one for html email and one for plaintext email. Forcing to choose the format does not make sense here. Althrough I see it's kind of a weird usage to have two formats in one template (the blocks are actually rendered one by one, not the template itself) I think it would be better to make the format optional. Or is there a strong reason it's not?

**Comment by javiereguiluz** [comment] 2016-08-05 14:28
I'd say that having a mandatory format is a good practice to not mess things in templates. In your case, maybe you can use HTML format, given that the plain text content won't break the HTML syntax.

**Comment by maryo** [comment] 2016-08-06 12:59
That's what I did and it's quite OK but I'm not sure I like it. But OFC it's not so important :)

**Comment by ro0NL** [comment] 2016-08-08 20:31
I guess a template representing one format is by design, and good practice anyway. Ie. i would switch from blocks per format, to templates per format. But off course you can also just name your format `mixed` or something or talk with twig directly ;-)

**Comment by javiereguiluz** [comment] 2016-10-07 11:03
I'm closing this issue because having templates that define the format and the engine is an essential Symfony feature and it seems very unlikely that this is going to change anytime soon.

In any case, @maryo thanks for your proposal and please, keep proposing new features and improvements.

**Closed by javiereguiluz** 2016-10-07 11:03 UTC
Labels: Templating
