### ISSUE TITLE
[2.8] [WebProfilerBundle] Web profiler does not play nice with third-party CSS frameworks

### ISSUE THREAD

**Issue by csarrazi** [symfony/symfony#16235] opened 2015-10-14 07:54 UTC
It seems there are incompatibilities between the new Profiler and the previous one, regarding CSS frameworks.

Indeed, the profiler breaks Bootstrap 3.x styles, and vice-versa (you can see on the screenshot below that the left side menu is not at the correct position):

![CsaGuzzleBundle and 2.8 profiler](https://cloud.githubusercontent.com/assets/465798/10477773/3e2e5018-7259-11e5-9de1-589a79ea53e4.png)

We should expect similar issues with other CSS frameworks.

**Comment by csarrazi** [comment] 2015-10-14 07:55
Ping @javiereguiluz

**Comment by javiereguiluz** [comment] 2015-10-14 08:06
I'll look into it. Can you please point me to the Twig/HTML/CSS/JS/etc. files used by the Guzzle profiler page you are using? Thanks!

**Comment by csarrazi** [comment] 2015-10-14 08:48
* Twig files: https://github.com/csarrazi/CsaGuzzleBundle/tree/feature/refactor-frontend/src/Resources/views
* JS and CSS: https://github.com/csarrazi/CsaGuzzleBundle/blob/feature/refactor-frontend/src/Resources/public

JS and CSS are built using Gulp: https://github.com/csarrazi/CsaGuzzleBundle/blob/feature/refactor-frontend/gulpfile.js

The base assets are found here: https://github.com/csarrazi/CsaGuzzleBundle/tree/feature/refactor-frontend/assets-src

Because of this issue, I'm actually considering bootstrap 3.x from the bundle, even though it means creating quite a lot of CSS rules, especially for progress-bar styles.

**Comment by javiereguiluz** [comment] 2015-10-14 09:29
OK, the problem is that in 2.3 we used `<div id="content">` and in 2.8 we use `<div id="content" class="container">`. The `container` class is very common for CSS frameworks.

In the toolbar, we prefix all the CSS classes with `sf-*` to avoid issues. But in the profiler, we don't prefix anything because we assume we are in total control of the page design.

My question to anyone reading this comment: should we keep this practice in the profiler and then assume this is an error on the bundle side (it should not include an entire CSS framework) ... or should we redesign completely the profiler to use CSS classes prefixed with `sf-*`?

**Comment by stof** [comment] 2015-10-14 09:36
IMO, I don't see any reason to include a whole CSS framework when writing a collector panel. You should be using profiler styles, not Bootstrap styles, otherwise you will not be consistent with the other parts of the profiler.
so I would be against changing our styles to prefix everything in the profiler.

**Comment by csarrazi** [comment] 2015-10-14 09:37
Btw, @javiereguiluz I only include a few select components from Bootstrap (i.e. tabs and progress bar), not the entire framework.

**Comment by javiereguiluz** [comment] 2015-10-14 09:43
@csarrazi excuse me! It's true that you don't include the entire framework. But somehow, some common Bootstrap styles have slipped in too, because the `.container` element has been affected.

**Comment by stof** [comment] 2015-10-14 09:47
@csarrazi the 2.8 profiler has a system to display tabs, you should use it to be consistent. and we also have some JS to show and hide elements btw (even in 2.3+), which can be used in place of Bootstrap collapsible (we don't have the nice Bootstrap animation, but people using the profiler can probably live without it)

and you don't only include these. You also include the Bootstrap grid (which is the one conflicting with the profiler styles here)

**Comment by javiereguiluz** [comment] 2015-10-14 09:52
And I'll publish "sometime" a cookbook article about 2.8+ profiler utilities mentioned by @stof and how to create profile panels for any Symfony version.

**Comment by csarrazi** [comment] 2015-10-14 10:01
@javiereguiluz No harm done! ;)

@stof True. But the legacy profiler does not. This means that as long as 2.3 or 2.7 will be supported, there will be a need for re-implementing (or re-integrating from a third-party library) tabs.

Like I said, I have absolutely no issue with removing Bootstrap from my bundle (and it is still my prime choice here). However, if we wish to prevent having too much to duplicate to support both versions of the profiler panel.

Regardless, there are three questions here:

* Should we garantee compatibility of the markup with third-party CSS frameworks?
* Should developers reinvent the wheel each time they need third-party widgets in the profiler?
* Should we backport some CSS / JS markup from the 2.8 profiler into the legacy profiler (and most notably the tab system), in order to minimize duplication between both profilers?

Regardless of the decision, like @javiereguiluz mentioned, it should be indeed documented in a cookbook at a later time.

**Comment by csarrazi** [comment] 2015-10-14 10:04
@stof My issue is not with providing compatibility with 2.8 for Bootstrap (or any framework, for that matter).

The mais issue is: if bundles need to backport the 2.8 tab system into legacy profilers, this will lead to a very inconsistent experience between profiler versions.

**Comment by theofidry** [comment] 2015-10-18 11:09
> My question to anyone reading this comment: should we keep this practice in the profiler and then assume this is an error on the bundle side (it should not include an entire CSS framework) ... or should we redesign completely the profiler to use CSS classes prefixed with sf-*?

:+1: it's the better solution to avoid any conflict with any CSS framework.

**Comment by Rvanlaak** [comment] 2015-10-19 07:56
:+1: for avoiding CSS framework conflicts, the profiler should provide you with all required tools. What widgets are you missing?

As 2.8 will be the new LTS, I don't think backporting will happen as I'm honest.

**Comment by javiereguiluz** [comment] 2015-10-19 07:59
@Rvanlaak we can't provide all the widgets that a profiler panel may need. One possible solution would be to redesign the profiler and use jQuery and Bootstrap.

**Comment by Rvanlaak** [comment] 2015-10-19 08:03
@javiereguiluz agree with you, I don't mean that all widgets should be included, but that we probably can live without the fancy stuff as @stof already mentioned https://github.com/symfony/symfony/issues/16235#issuecomment-147993400

**Comment by sstok** [comment] 2015-10-20 13:39
Not to start a flame war here but for the profiler I would rather consider Semantic UI then Bootstrap :)
One thing I really like about Semantic UI is the themebility and that you can easily choose which component you want to use (without worrying about inter dependencies).

**Comment by javiereguiluz** [comment] 2016-02-03 17:08
I'm closing this as "wont' fix". Reasons:

  * For the "web debug toolbar" we care about this issue because the toolbar is injected into developer's pages.
  * For the profiler, we shouldn't care about this issue because all the contents and styles of the page are generated by the profiler.

If one panel is very complex, it can add their own styles (for example, the `form` panel does that) ... but they should be careful of not including an entire CSS framework or parts of it that affect to the webpage layout (e.g. the `.container` styles).

**Closed by javiereguiluz** 2016-02-03 17:08 UTC
Labels: WebProfilerBundle

**Comment by stof** [comment] 2016-02-03 17:36
I agree with @javiereguiluz. this should be considered a bug in the bundle providing this panel.
