### ISSUE TITLE
$form->isValid() always returning true

### ISSUE THREAD

**Issue by PLPeeters** [symfony/symfony#12792] opened 2014-12-01 13:18 UTC
I was using Silex with Symfony 2.5.7. Form validation broke when I updated to version 2.6.0.

Here's the `buildForm` method defined for my `PasswordResetType`:

	function buildForm(FormBuilderInterface $builder, array $options) {
			$builder
				->add('password', 'repeated', array(
					'type' => 'password',
					'invalid_message' => $this->app['translator']->trans('form_errors.pass_must_match'),
					'required' => true,
					'first_options' => array(
						'constraints' => array(
							new Assert\NotBlank()
						),
					),
					'second_options' => array(
						'constraints' => array(
							new Assert\NotBlank()
						)
					)
				))
			;
		}
	}

The Twig template associated to my form:

	{{ form_start(form) }}
		{{ form_widget(form._token) }}
		{{ form_errors(form) }}

		<div class="form-group">
			{{ form_label(form.password.first, 'user.new_password'|trans, {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(form.password.first) }}
			{{ form_widget(form.password.first, {'attr': {'class': 'form-control', 'placeholder' : 'user.new_password'|trans}}) }}
		</div>

		<div class="form-group">
			{{ form_label(form.password.second, 'user.new_password_confirmation'|trans, {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(form.password.second) }}
			{{ form_widget(form.password.second, {'attr': {'class': 'form-control', 'placeholder' : 'user.new_password_confirmation'|trans}}) }}
		</div>
		<button type="submit" class="btn btn-primary btn-block">{{'user.reset_password'|trans}}</button>
	{{ form_end(form) }}

The associated controllers:

	$app->get('/{_locale}/reset_password/{token}', function(Request $request, $token) use ($app) {
		/* ... */

		$form = $app['form.factory']->create(new PasswordResetType($app), array());

		return $app['twig']->render('password_reset.twig', array(
			'title' => 'Page title',
			'form' => $form->createView()
		));
	})->bind('reset_password');

    $app->post('/{_locale}/reset_password/{token}', function(Request $request, $token) use ($app) {
	    /* ... */

	    $form = $app['form.factory']->create(new PasswordResetType($app), array());

	    $form->handleRequest($request);

	    if ($form->isValid()) {
		    $data = $form->getData();

		    $password = $data['password']; // this is line 113

		    /* ... */
	    }
    });

This generates the following error when passwords don't match: `Error: ContextErrorException in controllers_users.php line 113: Notice: Undefined index: password`. This indicates `$form->isValid()` returned `true` while it shouldn't have, since the passwords don't match.

**Comment by deanc** [comment] 2015-01-01 19:08
I can confirm I am also having this issue at the moment with Silex using the SF2 Form component 2.6.*.

Looking for solutions instead of splitting it into two fields and handling the issue manually...

**Comment by xelaris** [comment] 2015-01-02 04:22
Line https://github.com/symfony/symfony/blob/v2.6.1/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php#L69 causes the problem. `$allowNonSynchronized` should be `true` in the described case. The condition `$violation->getConstraint() instanceof Form` was added in 3b50bf2.

Since 2.6.0 `ConstraintViolation` objects can contain references to the constraint which is violated if the new Validator is used.

Silex uses the deprecated Validator, thus the `ConstraintViolation` objects aren't builded by the new `Symfony\Component\Validator\*Context*\ExecutionContext` but the `Symfony\Component\Validator\ExecutionContext`. Since the latter one isn't aware of the constraint, violations builded with it don't contain references to the constraint, thus `$violation->getConstraint()` provides ``null`` and the check fails. As long as `Symfony\Component\Validator\ExecutionContext` exists, a `ConstraintViolation::getConstraint()` must not expect to provide a constraint.

**Comment by deanc** [comment] 2015-01-02 11:11
Hi Xelaris. Thanks for this. Have to now wait for this to be merged into 2.7. Are any chances required to Silex to address this? What is the deprecated Validator you speak of?

**Comment by xelaris** [comment] 2015-01-02 19:45
@deanc I hope it will be merged in 2.6 actually. The deprecated Validator I mentioned is https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Validator/Validator.php#L24-L25.
The new one is `Symfony\Component\Validator\Validator\RecursiveValidator`. The `validator` service in Silex can not changed to the new one without further ado, since it is not compatible. There is a new `Symfony\Component\Validator\Validator\LegacyValidator` introduced along with `RecursiveValidator`, which should work as a drop-in replacement for the deprecated one since it extends the `RecursiveValidator` but implements the interface of the old one. Because this *magic* the class is incompatible with PHP versions < 5.3.9 and I don't know if it could be utilized by Silex, since it should be compatible with PHP 5.3.3. However, this should be discussed in the Silex project.
Anyway the Symfony Form Component should work with the deprecated Validator until 3.0.

**Comment by stof** [comment] 2015-01-02 20:17
@xelaris Silex could do the same than Symfony: use the 2.5-bc implementation on 5.3.9+ and fallback to the deprecated implementation for people on old 5.3 versions

**Comment by xelaris** [comment] 2015-01-02 20:51
@stof thanks for the explanation. I was already wondering, which Validator is actually used by Symfony, but haven't studied it before. There is a PR for Silex that will do this by utilizing the `ValidatorBuilder` to build the Validator https://github.com/silexphp/Silex/pull/998

**Closed** 2015-01-09 14:03 UTC
Labels: BC Break, Form, Validator
