### ISSUE TITLE
Possible incorrect call to createLazyGhost from generated Doctrine Proxy

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#52609] opened 2023-11-16 09:57 UTC
### Symfony version(s) affected

6.3.8

### Description

Froml the activation of ``enable_lazy_ghost_objects`` option in an application running on SF 6.3.8, I received sometimes errors like:
``Proxies\__CG__\...\MyBundle\Entity\MeetingTranslation::createLazyGhost(): Argument #1 ($initializer) must be of type Closure|array, null given``

When I check the generated Doctrine Proxy is can see that the constructor accepts a Closure or null but ``null`` is not supported in the ``createLazyGhost`` from LazyGostTrait (https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/VarExporter/LazyGhostTrait.php). So it can lead to the current error.

![image](https://github.com/symfony/symfony/assets/652505/9a15015f-0b3d-40d3-b2dd-662ecfebd2ea)

I'm not sure how I can get null in the constructor rather than a Closure but as it's supposed to happen, it should be managed in the constructor.

### How to reproduce

Need to be analyzed.

**Comment by raziel057** [comment] 2023-11-16 10:41
@nicolas-grekas @xabbuh I suppose that the issue comes from the Doctrine Proxy Generator more than Exporter as we should return from the constructor as soon as the ``initializer`` is null.

I was able to reproduce the issue writing an entity and using the translatable Trait of https://github.com/KnpLabs/DoctrineBehaviors/blob/master/docs/translatable.md

When I create an object with empty translation, I got the error.

So I think the generator should write:
```php
public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($initializer === null || $cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }
```

I can submit a PR if it sounds correct for you.

**Comment by raziel057** [comment] 2023-11-16 11:19
For information I was using ``doctrine/orm`` 2.16.2. After upgrade to 2.17.0 the issue seems solved. I can see the generator have been modified https://github.com/doctrine/orm/blob/2.17.0/lib/Doctrine/ORM/Proxy/ProxyFactory.php

So finally the issue seems more related to doctrine/orm 2.16.x branch. If you confirm I can close this topic.

**Comment by derrabus** [comment] 2023-11-16 21:55
If the issue is gone in 2.17, I'd like to close the issue. ✌️

**Closed as not planned** 2023-11-16 21:56 UTC
Labels: Bug, Status: Needs Review, VarExporter
