### ISSUE TITLE
JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by stevelewis3** [symfony/symfony#54127] opened 2024-03-01 09:51 UTC
### Symfony version(s) affected

7.0.4

### Description

Yesterday I updated `symfony/asset-mapper` to version 7.0.4 and received the following error:

> An exception has been thrown during the rendering of a template ("Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned").

It occurs from this line in one of my twig templates (and other similar `importmap()` calls in other templates.

```twig
{% block importmap %}    
    {{ importmap(getImports(['home', 'news-popup'])) }}
{% endblock %}
```

For now I've rolled back to `symfony/asset-mapper` 7.0.2.

### How to reproduce

Updated `symfony/asset-mapper` to 7.0.4

**Comment by smnandre** [comment] 2024-03-01 10:40
It should be fixed in #54079

**Comment by stof** [comment] 2024-03-01 10:45
Duplicate of https://github.com/symfony/symfony/issues/54078

**Closed as not planned** 2024-03-01 10:46 UTC
Labels: Bug, Status: Needs Review

**Comment by stevelewis3** [comment] 2024-03-01 10:50
Apologies for the duplication, I only searched open issues.
