### ISSUE TITLE
Symfony 3.4.11 autowiring is broken with single instances...

### ISSUE THREAD

**Issue by joeyhub** [symfony/symfony#27893] opened 2018-07-07 18:46 UTC
```
Interfaces\:
 resources: interfaces/*.php

Implementations\:
 resources: implementations/*.php

interface X

class Y implements X
```

With this I get an error, could not instantiate interface X.

This is coming not from compilation but from the compiled code in cache. The compiled has generated invalid code and failed to detect this.

As Y is the only implementation of X, then services asking for X should get Y instead.

Z which takes interface X as a constructor parameter is being loaded via service locator (Z is also public).

I've noticed in file loader it uses aliases to do this. Shouldn't it be setting class on the interface entry instead?

**Comment by xabbuh** [comment] 2018-07-07 19:11
Can you create a small example application that allows to reproduce your issue?

**Comment by joeyhub** [comment] 2018-07-08 17:08
I've provided the example above. I can't provide the entire codebase however.

At the very least the code producer that's putting down code in cache should when putting down new $CLASS ensure that $CLASS isn't an interface.

There are two bugs here. One is that your parser and compiler is producing invalid code, the other is that it's not validating what it's producing. Perhaps that's for performance reasons.

If I can have some documentation on critical stages of the compilation process then I can probably take a look and figure out the bug. At least where the code's at that puts new $CLASS so I can throw in an assert and get a stack trace.

I only have limited time and resources though. I can't afford to go down the rabbit hole and read the entire container/compile code.

**Comment by xabbuh** [comment] 2018-07-08 18:51
I am sorry, but with the description I am not able to reproduce the issue. But sadly that would be required to be able to fix what you experience.

**Comment by nicolas-grekas** [comment] 2018-07-08 19:16
> As Y is the only implementation of X, then services asking for X should get Y instead.

Note that this doesn't for this way: the alias is created only in the *same* "resources" set.
In your example, interfaces are loaded separately.

> With this I get an error, could not instantiate interface X.

I'd also be happy to have a look at a reproducer. What is the error like exaclty?

**Comment by joeyhub** [comment] 2018-07-09 12:48
Maybe this issue needs to be broken up.

1. Somewhere during build there needs to be some validation that detects if interfaces are going to be treated as classes. Maybe this is there already but it's being suppressed?

2. The bug itself...

Try loading only the implementations and the things that use them indirectly via interface.

I did also have an override for my interface setting only public: true. This worked when I also specified class.

So it looks like it's not clever enough to merge configs (presumably would be order dependent).

However on removing that I still got the problem which was a bit baffling and only for that particular interface. It's possible something was being cached somewhere but where is a mystery :/.

**Comment by xabbuh** [comment] 2018-07-09 12:56
Interfaces shouldn't ever be registered as services at all, but only as aliases. This seems to work just fine as we didn't receive similar bug reports before. Without being able to reproduce this issue I think we can therefore assume that this must be some kind of misconfiguration in your application. Though again hard to tell without being able to reproduce.

**Comment by nicolas-grekas** [comment] 2018-07-09 16:15
From your description, at least part, if not all is expected (what I wrote [above](https://github.com/symfony/symfony/issues/27893#issuecomment-403309937) + the non-validation also - we don't do that, devs are responsible for the correctness of their config.)

I agree with @xabbuh, this is way too abstract, we can do nothing here.

**Comment by nicolas-grekas** [comment] 2018-07-29 15:31
Closing as explained. Please resubmit with more details+reproducer if you think we misunderstood something.

**Closed by nicolas-grekas** 2018-07-29 15:31 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Status: Waiting feedback, Unconfirmed

**Comment by joeyhub** [comment] 2018-08-23 16:06
As far as I can tell, this happens when you do...

A\B\: {resource: a/b/*}

Then:

A\B\C: {public: true}

If you give A\B\C the class then it's alright.

Normally you might expect a merge or overwrite and the thing is without A\B\C being loaded through A\B\ then it works fine without class.

**Comment by xabbuh** [comment] 2018-08-24 05:45
@joeyhub Can you create a small example application that allows to reproduce based on the observations you made?

**Comment by nicolas-grekas** [comment] 2018-08-24 14:26
Order matters so in your case you need to load interfaces after implementations.
The auto-alias is a DX feature that frees ppl from declaring these aliases manually when we can save that for them. I'm not sure we want to change that.

**Comment by joeyhub** [comment] 2018-08-24 14:27
That's odd. In my case order didn't appear to matter. I'll test that again at the next opportunity and let you know.
