### ISSUE TITLE
using array_filter in console leads to memory leak (PHP80)

### ISSUE THREAD

**Issue by quazardous** [symfony/symfony#41925] opened 2021-07-01 09:07 UTC
**Symfony version(s) affected**: 5.3.2

**Description**
Using `\array_filter()` within a concole command leads to memory usage increase.

I'm putting this bug here for now, but I understand it can be misplaced. So I apologized in advance if this turns out to be just noise...

**How to reproduce**
```bash
symfony new array_filter_bug
```
create `array_filter_bug/array_filter.php`
```php
<?php
// array_filter_bug/array_filter.php

$array = array_combine(range(1, 1000, 2), array_fill(1, 500, null));
$array += array_combine(range(2, 1000, 2), array_fill(1, 500, true));

$f = function (&$array) {
    $array = \array_filter($array, fn($item) => !is_null($item));
};

for (;;) {
    $clone = (array) $array;
    $f($clone);
    $memory = \memory_get_usage();
    printf("memory: %d\n", $memory);
    unset($clone);
}
```
Create a test command `array_filter_bug/src/Command/ArrayFilterCommand.php`:
```php
<?php
// array_filter_bug/src/Command/ArrayFilterCommand.php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class ArrayFilterCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->setName('app:array_filter')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        require __DIR__ . '/../../array_filter.php';
        return Command::SUCCESS;
    }

}

```

Test outside console:
```bash
cd array_filter_bug
php ./array_filter.php
```
Memory is not increasing.

Test inside console:
```bash
cd array_filter_bug
APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
APP_ENV=prod APP_DEBUG=0 php bin/console app:array_filter
```
Memory is increasing !?

NB: it's the same with ou without clean reinstall or with APP_ENV=dev
```bash
rm -rf ./vendor
composer install --no-dev --optimize-autoloader
```
in this case APP_DEBUG is not messing with memory to much (I've spent some time on the mongo PHP library vs APP_DEBUG... ).

**Possible Solution**

IT'S NOT A SOLUTION !

It's what I've done to fix the leak.

I'm using a foreach/unset loop like:
```php
function my_array_filter(array &$array)
{
    foreach (\array_keys($array) as $k) {
        if (is_null($array[$k])) unset($array[$k]);
    }
}
```
Memory is not increasing with the console.

Fixed `array_filter_bug/array_filter.php`:
```php
<?php

$array = array_combine(range(1, 1000, 2), array_fill(1, 500, null));
$array += array_combine(range(2, 1000, 2), array_fill(1, 500, true));

function my_array_filter(array &$array)
{
    foreach (\array_keys($array) as $k) {
        if (is_null($array[$k])) unset($array[$k]);
    }
}

//$f = function (&$array) {
//    $array = \array_filter($array, fn($item) => !is_null($item));
//};

$f = function (&$array) {
    my_array_filter($array);
};

for (;;) {
    $clone = (array) $array;
    $f($clone);
    $memory = \memory_get_usage();
    printf("memory: %d\n", $memory);
    unset($clone);
}
```

**Additional context**
Fedora 34

```bash
$ php --version
PHP 8.0.8 (cli) (built: Jun 29 2021 07:41:19) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies
```

```bash
$ composer info
psr/cache                          2.0.0   Common interface for caching libraries
psr/container                      1.1.1   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/log                            1.1.4   Common interface for logging libraries
symfony/cache                      v5.3.3  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.3.2  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection       v5.3.3  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  A generic function and convention to trigger deprecation notices
symfony/dotenv                     v5.3.0  Registers environment variables from a .env file
symfony/error-handler              v5.3.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  Generic abstractions related to dispatching event
symfony/filesystem                 v5.3.3  Provides basic utilities for the filesystem
symfony/finder                     v5.3.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.13.3 Composer plugin for Symfony
symfony/framework-bundle           v5.3.3  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client-contracts      v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.3  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.3  Provides a structured process for converting a Request into a Response
symfony/polyfill-intl-grapheme     v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/routing                    v5.3.0  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.3.3  Enables decoupling PHP applications from global state
symfony/service-contracts          v2.4.0  Generic abstractions related to writing services
symfony/string                     v5.3.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/var-dumper                 v5.3.3  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                       v5.3.3  Loads and dumps YAML files
```

**Comment by stof** [comment] 2021-07-01 09:13
Is it actually related to the console component, or to have the whole logic happening inside a function rather than in the global scope ?

side note: your `my_array_filter` is not only adding a foreach and unset compared to `array_filter`. It also has a different signature (it receives the array by reference and modifies it in place)

**Comment by quazardous** [comment] 2021-07-01 09:45
> Is it actually related to the console component, or to have the whole logic happening inside a function rather than in the global scope ?

It's probably both, but outside console the memory **never** increase with all the implementations (`$f1` to `$f4`).

Within console in function scope only `$f3` and `$f4` are working without memory increase (it's why I could not keep the same signature).

```php
<?php

$array = array_combine(range(1, 1000, 2), array_fill(1, 500, null));
$array += array_combine(range(2, 1000, 2), array_fill(1, 500, true));

function my_array_filter(array $array, callable $keep)
{
    $res = [];
    foreach ($array as $k => $v) {
        if (call_user_func($keep, $array[$k])) $res[$k] = $v;
    }
    return $res;
}

function my_array_filter_alter(array &$array, callable $keep)
{
    foreach (array_keys($array) as $k) {
        if (!call_user_func($keep, $array[$k])) unset($array[$k]);
    }
}

function my_array_filter_null(array &$array)
{
    foreach (array_keys($array) as $k) {
        if (is_null($array[$k])) unset($array[$k]);
    }
}

$f1 = function ($array) {
    return \array_filter($array, fn($item) => !is_null($item));
};

$f2 = function ($array) {
    return my_array_filter($array, fn($item) => !is_null($item));
};

$f3 = function ($array) {
    my_array_filter_alter($array, fn($item) => !is_null($item));
    return $array;
};

$f4 = function ($array) {
    my_array_filter_null($array);
    return $array;
};

$handler = function () use ($f1, $f2, $f3, $f4, $array) {

    for (;;) {
        $clone = (array) $array;
        $res = $f3($clone);
        $memory = \memory_get_usage();
        printf("memory: %d\n", $memory);
        unset($clone, $res);
    }

};

$handler();

```

But ~~in global scope~~(*) not inside a closure `$f3` is leaking memory too (inside the console) :

(*) EDIT: The console is use `include` on the file so it's not global scope inside the console but it is when called directly with `php`.

```php
...
// $handler = function () use ($f1, $f2, $f3, $f4, $array) {

    for (;;) {
        $clone = (array) $array;
        $res = $f3($clone);
        $memory = \memory_get_usage();
        printf("memory: %d\n", $memory);
        unset($clone, $res);
    }

// };

// $handler();
```

**Comment by stof** [comment] 2021-07-01 09:50
> But in global scope `$f3` is leaking memory too:

Then this should clearly be reported to PHP, not to Symfony, as you managed to create a case that leaks without any Symfony code involved.

**Comment by quazardous** [comment] 2021-07-01 09:55
Sorry I've mis explained. It's not global scope. It's file scope. But for the console it's included inside a function of course. What I was pointing is that it's different within a closure. I'll rewrite my comments

**Comment by stof** [comment] 2021-07-01 09:57
but in any case. If you are able to reproduce the leak without any symfony/console code, it is clear that the issue is not in symfony/console but in PHP itself (and then, maybe symfony/console triggers that PHP bug due to the conditions triggering it)

**Comment by quazardous** [comment] 2021-07-01 10:02
> but in any case. If you are able to reproduce the leak without any symfony/console code

I'm not able to reproduce the bug without SF. `$f1` to `$f4` are never leaking memory when called directly with `php`.

**Comment by stof** [comment] 2021-07-01 10:04
does it also happen if you create a pure PHP file that includes your file inside a function and executes that function ?

**Comment by quazardous** [comment] 2021-07-01 10:25
You are right it's leaking with a simple test class.

```php
<?php
namespace Somewhere\On\Earth;

class Foo {
    static function my_array_filter(array $array, callable $keep)
    {
        $res = [];
        foreach ($array as $k => $v) {
            if (call_user_func($keep, $array[$k])) $res[$k] = $v;
        }
        return $res;
    }
    
    static function my_array_filter_alter(array &$array, callable $keep)
    {
        foreach (array_keys($array) as $k) {
            if (!call_user_func($keep, $array[$k])) unset($array[$k]);
        }
    }
    
    static function my_array_filter_null(array &$array)
    {
        foreach (array_keys($array) as $k) {
            if (is_null($array[$k])) unset($array[$k]);
        }
    }
    
    function leakingOrNotLeaking(int $n, array $array) {
        
        $f = [];
        $f[1] = function ($array) {
            return \array_filter($array, fn($item) => !is_null($item));
        };
        
        $f[2] = function ($array) {
            return self::my_array_filter($array, fn($item) => !is_null($item));
        };
        
        $f[3] = function ($array) {
            self::my_array_filter_alter($array, fn($item) => !is_null($item));
            return $array;
        };
        
        $f[4] = function ($array) {
            self::my_array_filter_null($array);
            return $array;
        };
        
        for (;;) {
            $clone = (array) $array;
            $res = $f[$n]($clone);
            $memory = \memory_get_usage();
            printf("memory: %d\n", $memory);
            unset($clone, $res);
        }
        
    }
    
    function run(int $n) {
        $array = array_combine(range(1, 1000, 2), array_fill(1, 500, null));
        $array += array_combine(range(2, 1000, 2), array_fill(1, 500, true));
        
        $this->leakingOrNotLeaking($n, $array);
    }
}

$handler = new Foo();
$n = $_SERVER['argv'][1] ?? 1;
echo "Using \$f$n\n";
$handler->run($n);

```

I'm filling an issue in PHP and I'll put the link for cross ref.

Thx for your guidance.

**Comment by quazardous** [comment] 2021-07-01 12:48
PHP Bug https://bugs.php.net/bug.php?id=81215

**Comment by chalasr** [comment] 2021-07-01 12:49
Closing then, thanks.

**Closed as completed by chalasr** 2021-07-01 12:49 UTC
Labels: Bug, Status: Needs Review
