### ISSUE TITLE
Autowired ParamConverter no longer working 

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#29819] opened 2019-01-08 16:27 UTC
**Symfony version(s) affected**: 4.2.2

**Description**  
 I have a service that implements ParamConverterInterface that worked fine a few days ago, but when I run 'composer update', I can an error message that Doctrine cannot find the entity.  This may be related to #29810

**How to reproduce**  

I've attached my composer.json/lock 
[setup.zip](https://github.com/symfony/symfony/files/2737589/setup.zip)

.  Follow the instructions to create a ParamConverter.  run composer install with my attached files.  The controller should return a valid entity.  Then run composer.update, now it will fail.

Sorry I can't provide a more precise way to reproduce this problem.

**Comment by tacman** [comment] 2019-01-15 14:11
Unable to guess how to get a Doctrine instance from the request information
for parameter "post".

**Comment by tacman** [comment] 2019-01-15 17:00
I can demonstrate this error in the Symfony Demo:

    git clone git@github.com:survos/symfony-demo.git
    cd symfony-demo
    composer install
    php vendor/bin/codecept run -f

Tests fail, the key issue is that PostParamConverter isn't being called.  You can also see it with

    bin/console server:start

Then open http://127.0.0.1:8000/en/blog/bug-posts/test-post-to-demonstrate-bug

**Comment by xabbuh** [comment] 2019-01-15 21:22
Thank you for investing time into this example that greatly allowed me to reproduce what you experience.

However, this is the expected behaviour. If you do not add the `@ParamConverter` annotation, the SensioFrameworkExtraBundle tries to retrieve the `Post` object based on the route placeholders. But since there is no `$postSlug` property this resolution fails. You need to tell the param converter which property the route placeholder should be [mapped to](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#paramconverter-options):

```php
/**
 * @Route("/bug-posts/{postSlug}", methods={"GET"}, name="blog_post_bug")
 * @ParamConverter("post", options={"mapping": {"postSlug": "slug"}})
 */
public function postShowBug(Post $post): Response
{
    // ...
}
```

I am closing here as there is nothing to fix. Thank you for understanding.

**Comment by tacman** [comment] 2019-01-16 02:06
I've finally (after far too many hours) found a simple test case that demonstrates the error.

If I add this to composer.json's require section, it works:

```
        "symfony/dependency-injection": "4.2.x-dev#e4adc57a48d3fa7f394edfffa9e954086d7740e5",
```

So to see this in action:

```bash
git clone git@github.com:survos/symfony-demo.git
cd symfony-demo
composer install
php vendor/bin/server:start 

success:  http://127.0.0.1:8000/en/blog/bug-posts/test-post-to-demonstrate-bug 

git checkout di-bug
composer install

fails:  http://127.0.0.1:8000/en/blog/bug-posts/test-post-to-demonstrate-bug
```

The ONLY difference between the two is composer.json changing from:

       "symfony/dependency-injection": "4.2.x-dev#e4adc57a48d3fa7f394edfffa9e954086d7740e5",

to

        "symfony/dependency-injection": "^4.2",

And of course the "composer update" command to generate the lock file.

**Comment by xabbuh** [comment] 2019-01-16 08:40
Thank you for investing the time to investigate this a bit more and sorry for closing too early. I was under the impression that you used the param converters from the SensioFrameworkExtraBundle, but there is a custom param converter class which indeed does not work as expected anymore.

**Comment by tacman** [comment] 2019-01-16 09:53
Nope, that's not working.  If you pull that repo, branch di-bug now
has "composer
require symfony/dependency-injection:~4.2@dev" and the error still exists.

You can run

    vendor/codecept/run functional -f

works on master (with the older DI), fails on di-bug.

**Comment by xabbuh** [comment] 2019-01-16 10:34
I see this error on both branches:

```
$ php vendor/bin/codecept run -f
Codeception PHP Testing Framework v2.5.2
Powered by PHPUnit 7.5.2 by Sebastian Bergmann and contributors.
Running with seed: 


App\Tests.acceptance Tests (2) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Testing App\Tests.acceptance
✔ BlogCept: Open blog page and see article there (0.97s)
✔ LoginCept: Login as admin to backend (1.71s)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

App\Tests.functional Tests (14) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Testing App\Tests.functional
✖ PublicUrlsCept: Open public urls and see requested page (1.53s)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

App\Tests.unit Tests (25) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Testing App\Tests.unit
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 22.08 seconds, Memory: 52.25MB

There was 1 failure:

---------
1) PublicUrlsCept: Open public urls and see requested page
 Test  tests/functional/PublicUrlsCept.php
 Step  See response code is 200
 Fail  Expected HTTP Status Code: 200 (OK). Actual Status Code: 500 (Internal Server Error)
Failed asserting that 500 matches expected 200.

Scenario Steps:

 3. $I->seeResponseCodeIs(200) at tests/functional/PublicUrlsCept.php:17
 2. $I->amOnPage("/en/blog/posts/test-post-to-demonstrate-bug") at tests/functional/PublicUrlsCept.php:16
 1. // As an Anonymous


FAILURES!
Tests: 3, Assertions: 7, Failures: 1.
```

But this looks expected to me. The path used here matches the route pattern for the `BlogController::postShow()` method where the placeholder is named `slug` and not `postSlug` and thus making your param converter fail with this error:

> Route attribute postSlug is missing

**Comment by tacman** [comment] 2019-01-16 10:36
Ah, I see.  I over-hacked something during debugging.  I'll test in
symfony-demo and also in my project and get back to you.

**Comment by tacman** [comment] 2019-01-16 10:42
I think the problem is having two converters, it seems reasonable that if
only one is automatically supported.

So it's working on symfony-demo, but failing on my app.  I'll continue to
debug that, but yes, this seems to be fixed now.

Thanks!

Tac

**Comment by xabbuh** [comment] 2019-01-16 10:50
Thank you for the confirmation. 👍 I am closing then.

P.S.: Feel free to reach out at the Symfony Slack if you need to help with the implementation.

**Closed by xabbuh** 2019-01-16 10:50 UTC
Labels: Bug, DependencyInjection, Status: Waiting feedback

**Comment by tacman** [comment] 2019-01-16 11:06
Within my app it definitely doesn't work.  I've made sure the cache is
cleared, etc., but toggling back and forth between the dev and the old one
with the commit hash, the dev doesn't work in my app.  I have a dump() in
the ParamConverter code that isn't being called with the dev branch and is
with the old commit.

Happy to give you access, setup is pretty simple, thought the code itself
is not particularly clean.

**Comment by xabbuh** [comment] 2019-01-16 11:16
Sure, if you can give me access, I can try to take a look at it tonight.

**Comment by xabbuh** [comment] 2019-01-16 11:37
CET

**Comment by gaetan-petit** [comment] 2019-08-28 09:04
@xabbuh When upgrading SensioFrameworkExtraBundle on an application using sf 3.4 paramconverter is broken.

It seems that the faulty code was revert in 4.* but not in 3.* as you can see here : https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php#L37

Should I fill an new issue?

**Comment by xabbuh** [comment] 2019-08-28 10:42
Please do and please also provide a small example application that allows to reproduce.
