### ISSUE TITLE
Uncaught Error: Class 'Twig\Node\Expression\FilserExpression' not found

### ISSUE THREAD

**Issue by morgzz** [symfony/symfony#37329] opened 2020-06-18 00:52 UTC
**Symfony version(s) affected**: 5.1.2

**Description**  

Ran into this error, sometime after upgrading to 5.1.2.
My symfony project is fairly brand new and doesn't have a whole lot of customization to it.
Tried everything on downgrading just the Twig bundle but for some reason I couldn't isolate it to just 5.1.1. Once I downgraded the whole project back to 5.1.1 the problem went away.

```
-------------------- -------------------------------------------------
  Symfony
 -------------------- -------------------------------------------------
  Version              5.1.2
  Long-Term Support    No
  End of maintenance   01/2021
  End of life          01/2021
 -------------------- -------------------------------------------------
  Kernel
 -------------------- -------------------------------------------------
  Type                 App\Kernel
  Environment          dev
  Debug                true
  Charset              UTF-8
  Cache directory      ./var/cache/dev (7.4 MiB)
  Log directory        ./var/log (3.2 MiB)
 -------------------- -------------------------------------------------
  PHP
 -------------------- -------------------------------------------------
  Version              7.2.24 Windows 10
  Architecture         64 bits
  Intl locale          n/a
  Timezone             America/Los_Angeles (2020-06-17T17:42:20-07:00)
  OPcache              true
  APCu                 false
  Xdebug               true
 -------------------- -------------------------------------------------
```

**How to reproduce**  

I'm not sure how to reproduce.

**Possible Solution**  

**Additional context**  

#### Composer
This was the composer requirements I used.
```json
"require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "antishov/doctrine-extensions-bundle": "^1.4",
        "gedmo/doctrine-extensions": "^2.4",
        "laminas/laminas-code": "^3.4",
        "laminas/laminas-eventmanager": "^3.2",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "5.1.*",
        "symfony/console": "5.1.*",
        "symfony/dotenv": "5.1.*",
        "symfony/expression-language": "5.1.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.1.*",
        "symfony/framework-bundle": "5.1.*",
        "symfony/http-client": "5.1.*",
        "symfony/intl": "5.1.*",
        "symfony/mailer": "5.1.*",
        "symfony/mime": "5.1.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "5.1.*",
        "symfony/orm-pack": "*",
        "symfony/process": "5.1.*",
        "symfony/security-bundle": "5.1.*",
        "symfony/serializer-pack": "*",
        "symfony/stopwatch": "5.1.*",
        "symfony/string": "5.1.*",
        "symfony/translation": "5.1.*",
        "symfony/twig-bundle": "^5.1.1",
        "symfony/uid": "5.1.*",
        "symfony/validator": "5.1.*",
        "symfony/web-link": "5.1.*",
        "symfony/yaml": "5.1.*",
        "symfonycasts/verify-email-bundle": "^1.0",
        "twig/twig": "^2.12|^3.0",
        "twig/extra-bundle": "^2.12|^3.0"
    },
    "require-dev": {
        "symfony/debug-bundle": "5.1.*",
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "^1.0",
        "symfony/test-pack": "*",
        "symfony/var-dumper": "5.1.*"
    },
```
#### Dev.log
```
[2020-06-17T15:27:41.684600-07:00] php.CRITICAL: Uncaught Error: Class 'Twig\Node\Expression\FilserExpression' not found {"exception":"[object] (Error(code: 0): Class 'Twig\\Node\\Expression\\FilserExpression' not found at C:\\Web\\Stack-7.2.24\\apps\\project\\vendor\\twig\\twig\\src\\NodeVisitor\\EscaperNodeVisitor.php:199)"} []
[2020-06-17T16:05:36.717489-07:00] php.DEBUG: Warning: filemtime(): stat failed for C:\Web\Stack-7.2.24\apps\project\config\routes\dev\framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/mnt/c/Web/Stack-7.2.24/apps/project/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/mnt/c/Web/Stack-7.2.24/apps/project/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2020-06-17T17:13:50.932834-07:00] php.DEBUG: Warning: filemtime(): stat failed for /mnt/c/Web/Stack-7.2.24/apps/project/config/routes/dev/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\Web\\Stack-7.2.24\\apps\\project\\vendor\\symfony\\config\\Resource\\FileResource.php","line":65,"trace":[{"file":"C:\\Web\\Stack-7.2.24\\apps\\project\\vendor\\symfony\\config\\Resource\\SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
```

**Comment by xabbuh** [comment] 2020-06-18 08:30
Can you check where in your project the `FilserExpression` class is referenced? This should likely be `FilterExpression` instead.

**Comment by morgzz** [comment] 2020-06-20 06:20
Checked all over including Composer cache and couldn't find any reference to `FilserExpression`. Very strange. It's grabbing it from somewhere. Not a whole lot to go by. It has something to do with 5.1.2. I'm guessing there's a typo in the stack somewhere.

**Comment by xabbuh** [comment] 2020-06-20 07:30
Can you provide a small example application that allows us to reproduce the issue? Otherwise I am afraid there is not much we can do about it.

**Comment by morgzz** [comment] 2020-06-22 13:02
Figured since there was much to go on. It’s pretty much all the information I could discover. I’ll try upgrading again and see if I run into this issue again. Hopefully I’ll have more insight.

**Comment by stof** [comment] 2020-06-23 09:48
Well, `FilserExpression` indeed does not exist. The class is named `FilterExpression` (note the `t` instead of the `s`). check your code to see if you have some place using the wrong class name.

**Comment by xabbuh** [comment] 2020-06-23 09:50
Anyway, I don't think this is caused by Symfony. Our code doesn't reference `FilserExpression` and I am convinced we would have received more reports like this then. So I am closing here. Thank you for understanding.

**Closed by xabbuh** 2020-06-23 09:50 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback
