### ISSUE TITLE
wrong utf encoding when i use the profiler pack symfony

### ISSUE THREAD

**Issue by Dohs** [symfony/symfony#37896] opened 2020-08-20 15:08 UTC
I have a problem with the symfony profiler pack, locally all works correctly but on the test server I have an error generated because of the profiler pack. in production mode there are no more errors but I no longer have a debug bar. does anyone have any idea plz? why one view of the profiler have a wrong encoding ?

error log :
 An exception has been thrown during the rendering of a template ("Notice: iconv(): Wrong charset, conversion from UTF-8' to UTF-16BE' is not allowed").

Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Notice: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16BE' is not allowed")." at /releases/draft/Reglettes/vendor/symfony/web-profiler-bundle/Resources/views/Profiler/base_js.html.twig line 338

config iconv local :
iconv

iconv support => enabled
iconv implementation => "libiconv"
iconv library version => 1.15

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value

config iconv server dev :

iconv

iconv support => enabled
iconv implementation => "glibc"
iconv library version => 2.24

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value

**Comment by nicolas-grekas** [comment] 2020-08-31 22:11
> Notice: iconv(): Wrong charset, conversion from UTF-8' to UTF-16BE' is not allowed

That's reason... I don't know why your iconv implementation doesn't allow this conversion...
Not sure we can do much about it.

**Comment by nicolas-grekas** [comment] 2020-10-01 14:13
Fixed by https://github.com/twigphp/Twig/pull/3397

**Closed by nicolas-grekas** 2020-10-01 14:13 UTC
Labels: Bug, Status: Needs Review, WebProfilerBundle

**Comment by stof** [comment] 2020-10-01 14:30
for reference, the root cause for not supporting it was using `symfony/polyfill-iconv` rather than `ext-iconv`
