### ISSUE TITLE
DomCrawler and null byte problem

### ISSUE THREAD

**Issue by hableel** [symfony/symfony#20323] opened 2016-10-27 10:07 UTC
If there is a null character in a page, Dom Crawler will stop at the null character and do not continue to the end of the page.

I have no control over the null character page.

The http request content is fine, problem happens at parsing stage.

Crawler class
**Symfony\Component\DomCrawler\Crawler**

I edited function `addHtmlContent()` to fix this problem:

After these lines:

``` php
// Convert charset to HTML-entities to work around bugs in DOMDocument::loadHTML()
$content = mb_convert_encoding($content, 'HTML-ENTITIES', $charset);
```

Added this:

``` php
$content = preg_replace("#\\0#", '', $content);
```

I think you have a better fix than mine.

**Comment by dosten** [comment] 2016-11-03 03:26
Can you provide a sample script? I cannot reproduce it.

**Comment by hableel** [comment] 2016-11-03 10:25
Here is an example.

Source code of a sample html file with null character at line 7 as you see.
![wwss 2016-11-03 at 01 00 21](https://cloud.githubusercontent.com/assets/463783/19961810/b5e6bdce-a1c5-11e6-8eec-58e228b1e2f2.png)

Url of sample html file, http://misbar.io/test_null_char.htm


php code:
``` php
$html = file_get_contents('http://misbar.io/test_null_char.htm');
$crawler = new Crawler($html);
echo $crawler->html();
```

The result is showing `Hello World!` only. Anything after null character will be discarded.

The desired result is to show all page contents.

**Comment by xabbuh** [comment] 2016-11-03 16:28
I cannot reproduce the issue with the example you gave. Which version of the DomCrawler component did you use and which PHP version?

**Comment by hableel** [comment] 2016-11-03 18:07
Both messages appears with my example? For me only the first one shown.

DomCrawler version 3.1.0
PHP version 7.0.9 and 5.6.21, both gave same results.

**Comment by jakzal** [comment] 2016-11-10 15:31
see #18454 and https://bugs.php.net/bug.php?id=71993

**Comment by xabbuh** [comment] 2016-12-16 12:12
Closing here as we do not provide workaround for minor PHP/libxml bugs (see https://github.com/symfony/symfony/pull/18454#r59109758).

**Closed by xabbuh** 2016-12-16 12:12 UTC
Labels: Bug, DomCrawler, Status: Needs Review, Unconfirmed
