### ISSUE TITLE
[DependencyInjection] failed importing doctrine PHP configs in the prepend extension method with multiple bundles with a different connection name

### ISSUE THREAD

**Issue by jfsenechal** [symfony/symfony#57964] opened 2024-08-09 12:35 UTC
### Symfony version(s) affected

7.1.3

### Description

for each bundle I import my doctrine config like this

```php
return static function (DoctrineConfig $doctrine) {
    $name = 'xx';
    $doctrine->dbal()
        ->connection($name)
        ->url(env('DATABASE_URL_B')->resolve());

    $em = $doctrine->orm()->entityManager($name);
    $em->connection($name);

    $em->mapping('AcMarcheB')
        ->isBundle(false)
        ->type('attribute')
        ->dir('%kernel.project_dir%/src/AcMarche/B/src/Entity')
        ->prefix('AcMarche\B')
        ->alias('AcMarcheB');
};
```

if I use another connection name only the last config of the bundle is taken into account

### How to reproduce

Sample with a bundle named A and an other named B

Disable auto config 

```yaml
//config/packages/doctrine.yaml
doctrine:
    dbal:
        ...
    orm:
        ...
        auto_mapping: false
```
**Use the patch** #57937 who fixed a first problem

### Importing config

**ABundle**

```php
class ABundle extends AbstractBundle
{
    public function getPath(): string
    {
        return \dirname(__DIR__);
    }

    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/services.php');
    }

    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/packages/doctrine.php');
    }
}
```

```php
//doctrine.php
return static function (DoctrineConfig $doctrine) {
$name = 'default'
    $doctrine->dbal()
        ->connection($name)
        ->url(env('DATABASE_URL')->resolve());
    $em = $doctrine->orm()->entityManager($name);
    $em->connection($name);

    $em->mapping('AcMarcheBottin')
        ->isBundle(false)
        ->type('attribute')
        ->dir('%kernel.project_dir%/src/AcMarche/Bottin/src/Entity')
        ->prefix('AcMarche\Bottin')
        ->alias('AcMarcheBottin');
};
```

**BBundle**
```php
class ABundle extends AbstractBundle
{
//...
//the same as above
}
```

```php
//doctrine.php
return static function (DoctrineConfig $doctrine) {
$name="default"
    $doctrine->dbal()
        ->connection($name)
        ->url(env('DATABASE_URL_CAP')->resolve());

    $em = $doctrine->orm()->entityManager($name);
    $em->connection($name);

    $em->mapping('AcMarcheCap')
        ->isBundle(false)
        ->type('attribute')
        ->dir('%kernel.project_dir%/src/AcMarche/Cap/src/Entity')
        ->prefix('AcMarche\Cap')
        ->alias('AcMarcheCap');
};
```
Result With the same name "default"

```bash
bin/console doctrine:mapping:info 
 Found 2 mapped entities:

 [OK]   AcMarche\B\Entity\Article
 [OK]   AcMarche\A\Entity\Article
```
**If I change name for A**

```php
//doctrine.php
return static function (DoctrineConfig $doctrine) {
$name = 'xxx'
```

Only entities in B are mapping

```bash
bin/console doctrine:mapping:info 
 Found 1 mapped entities:

 [OK]   AcMarche\B\Entity\Article
```

The same if I change connection name in B bundle

**Comment by yceruto** [comment] 2024-08-09 12:47
I couldn’t reproduce your issue after applying this fix: https://github.com/symfony/symfony/pull/57937. It hasn’t been released yet, but you can test it on the 7.1 dev branch

**Comment by yceruto** [comment] 2024-08-09 12:49
can you create a small app that reproduce the issue?

**Comment by jfsenechal** [comment] 2024-08-09 12:55
Yes

Here is https://github.com/jfsenechal/dibug

**Comment by xabbuh** [comment] 2024-08-09 13:38
Your demo application uses version 7.1.3 of the DependencyInjection component which does not contain the patch. You need to update to the dev version of 7.1: `composer update symfony/dependency-injection:^7.1.4@dev`

**Comment by jfsenechal** [comment] 2024-08-09 13:49
I use it !
I patched manually
Please reopen i executed composer update symfony/dependency-injection:^7.1.4@dev
and the same problem occurs

**Comment by yceruto** [comment] 2024-08-09 14:02
@jfsenechal, if you place both bundles under the same default connection, you’ll get all mapped entities (proving that it's working). It’s not about the bundle merging strategy not working as expected. You’ll encounter the same issue if you move both `doctrine.php` files to the root `config/packages/` directory without using bundles.

**Comment by yceruto** [comment] 2024-08-09 14:09
Btw, I just spotted that there is an `em` option for `doctrine:mapping:info`, so if you have multiple connections, you'll need to pass the right em value ` --em=cap` and then you'll see the mapped entities under that connection

**Comment by yceruto** [comment] 2024-08-09 14:10
Closing as it's not a bug.

**Closed as not planned by yceruto** 2024-08-09 14:10 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by jfsenechal** [comment] 2024-08-09 14:40
Yes you are right i don't use correctly command mapping info
Thanks a  lot for your work
Bon week end
