### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by BooleanType** [symfony/symfony#37050] opened 2020-06-01 19:21 UTC
**Symfony version(s) affected**: 5.1.0
**PHP version**: 7.4.1

**Description**  
This problem didn't appear on versions 5.0.*.
This string in the controller action provokes an error "_Serialization of 'Closure' is not allowed_":

`$this->get('session')->set('previousRPRequest', $request);`

... where `$request` is an instance of `Symfony\Component\HttpFoundation\Request`.

The project I work with contains a lot of code samples placed above (it handles form resubmission issue in browsers - just store request data in session and retrieve it after redirection). So, for now it's not so easy to just replace / remove this approach from the project. Today I should downgrade the project back to 5.0.8, 'cause submissions in all the forms triggered the same error.

**Additional context**  

![Serialization of 'Closure' is not allowed](https://user-images.githubusercontent.com/10816818/83445701-bdaead80-a44d-11ea-9827-58de80668a43.png)
![Serialization of 'Closure' is not allowed_2](https://user-images.githubusercontent.com/10816818/83445709-c1423480-a44d-11ea-85c6-dc5d96af161e.png)

**Comment by nicolas-grekas** [comment] 2020-06-08 17:07
Thanks for the report. Can you provide a simple reproducing app?
Alternatively, can you debug which closure ends up in the request object (since that's where it's coming from IIUC?)

**Comment by wopl** [comment] 2020-06-13 10:44
Running into the similar issue:
https://github.com/symfony/symfony/issues/37264

Happy to support, but
`can you debug which closure ends up in the request object`
doesn't give me any idea what to do... (sorry, my knowledge quite limited here).

@nicolas-grekas : I gave you access to the repo, where you can see the 5.0.2 version (which was still running).

**Comment by nicolas-grekas** [comment] 2020-06-13 11:20
Thanks @wopl I was able to reproduce.

In your `SecurityController`, your app puts the logger into the session. Via the cascade of the dependencies of the logger, this leads to the serialization of the session object itself. Since 5.1, the session object contains a closure. :boom: 

Yet, there is nothing wrong on Symfony's side here IMHO. You should not put the session object into the session storage in the first place... (and you should not put the logger either.)

I suspect @BooleanType is hitting a similar issue: putting the request object into the session leads to putting the session inside the session, and this doesn't work.

Agreed?

**Comment by wopl** [comment] 2020-06-13 11:39
Hi Nicolas,
thanks a lot for the quick response. Not easy to understand for me, but I now will crosscheck the topics you mentioned. Seems I have to rethink my extensive use of Session a bit.

Where is the place of @BooleanType to consider?

Again many thanks,
Wolfram

**Comment by BooleanType** [comment] 2020-06-13 20:50
Hi!
Sorry for waiting so long for my reply.
Here is my code in controller:
   ```
   /**
     * @Route("/new", name="locationNew", methods={"GET","POST"})
     */
    public function newAction(Request $request): Response
    {
        $this->denyAccessUnlessGranted(Permission::ROLE_ADMIN_LOCATION_WRITE);

        $location = new Location();
        $form = $this->createForm(LocationType::class, $location);
        
        // This snippet should be present HERE AFTER redirect too, 'cause $request doesn't 
        // contain POST after redirect, => $form->isSubmitted() isn't triggered and flow goes
        // to fulfilling $form with $_SESSION['previousRequest'] and rendering. That's why we 
        // can see validation errors after redirect.
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($location);
                $entityManager->flush();
                
                $this->addFlash('success', $this->get('t')->trans('Lokalizacja została utworzona').'.');
                return $this->redirectToRoute('locationIndex');
            } else {
                $this->get('session')->set('prevLocationNewRequest', $request);
                return $this->redirectToRoute('locationNew');
            }
        }
        
        if ($this->get('session')->has('prevLocationNewRequest')) {
            $form->handleRequest($this->get('session')->get('prevLocationNewRequest'));
            $this->get('session')->remove('prevLocationNewRequest');
        }

        return $this->render('location/new.html.twig', [
            'location' => $location,
            'formView' => $form->createView(),
        ]);
    }
```
When I wrote, it was allowed to write request object into the session. It was done in a lot of places in my project to prevent POST resubmission issue AND still see validation errors after redirect. And before 5.1.0 it worked like a charm. I didn't find any solution to prevent resubmission issue in docs through the capabilities of the framework. But I've found this: https://stackoverflow.com/a/34897510/4695280
After the redirect it was possible just to get saved request object from session and pass it to  `$form->handleRequest();`
@nicolas-grekas, I've understood from above, that since 5.1.0 it's not allowed anymore. But could it be possible to save a compatibility with this solution? Or, maybe, you can propose another right solution to figure out this problem? 'Cause for now I don't know how to solve the problem with the least losses and changes after updating the framework...

**Comment by nicolas-grekas** [comment] 2020-07-07 17:24
I'm closing as explained. It worked "by chance" before.
You need to *not* put the logger into the session.
The session should only hold data objects, not service-like objects.
Please use e.g. Slack if you need support.

**Closed by nicolas-grekas** 2020-07-07 17:24 UTC
Labels: Bug, HttpFoundation, Status: Needs Review, Status: Waiting feedback
