### ISSUE TITLE
Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony#43218] opened 2021-09-28 09:17 UTC
**Symfony version(s) affected**: 5.3.8

**Description**

After upgrading from v5.3.7 to v5.3.8 the following errors occurs:

    Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.

called from **RegisterListenersPass.php (line 143)** 

**Possible Solution**
EnvelopeListener.php file should be moved to EventListener folder.

**Comment by gjuric** [comment] 2021-09-28 09:19
It looks like we posted at the same time, duplicate of #43217 but since this one proposes a solution I am not going to close it.

**Comment by derrabus** [comment] 2021-09-28 09:26
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:26 UTC
Labels: Bug, Status: Needs Review
