### ISSUE TITLE
[Form] TransformationFailedException with JSON submitted data

### ISSUE THREAD

**Issue by asentner** [symfony/symfony#31017] opened 2019-04-08 17:39 UTC
**Symfony version(s) affected**: 3.4.24 / 4.2.5

**Description**  
TransformationFailedException thrown when JSON is submitted through HiddenType field. I have one form that is passing a JSON which is a canvas map of a captured signature.

This commit creates the breaking change for us:

https://github.com/symfony/form/commit/4f7d286bf5b237796cd646ffcd1c4461a145ed02#diff-9c65c1fe9e9fce8398f48544b0bbf2a5

Specifically this block of code:

```php
} elseif (\is_array($submittedData) && !$this->config->getCompound() && !$this->config->hasOption('multiple')) {
    $submittedData = null;
    $this->transformationFailure = new TransformationFailedException('Submitted data was expected to be text or number, array given.');
}
```

This runs before a transformer can clean the data and a mapper does not seem to be a good fit for this.

**How to reproduce**  
Submit JSON through a HiddenType form field

**Possible Solution**  
Check for an additional form option scalar = false or something along those lines.

Example JSON:

```json
[  
   {  
      "lx":132,
      "ly":67,
      "mx":132,
      "my":66
   },
   {  
      "lx":118,
      "ly":27,
      "mx":118,
      "my":26
   },
   {  
      "lx":144,
      "ly":19,
      "mx":144,
      "my":18
   }
]
```

This can get quite large depending on the size of the complexity of the signature. Transformers and mappers seem to run after this exception is thrown.

Thoughts?

**Comment by HeahDude** [comment] 2019-04-08 18:23
Hello @asentner, thank you for opening this issue.

I don’t really understand the necessary steps to reproduce. It seems to me than submitted some json means submitting a string that should not break a hidden field submission. How do you handle transformation exactly?

**Comment by dmaicher** [comment] 2019-04-08 21:44
This seems to be the same issue as reported in 

https://github.com/symfony/symfony/issues/29809
https://github.com/symfony/symfony/issues/29841

?

**Comment by HeahDude** [comment] 2019-04-08 23:13
Yes we should close here.

**Comment by fabpot** [comment] 2019-04-09 06:01
Closing as a duplicate then.

**Closed by fabpot** 2019-04-09 06:01 UTC

**Comment by Pasuvan** [comment] 2019-10-15 10:39
Hi @all, @asentner
Did you solve the above issue, Can you explain how to you solved? Because I have the same issue.
Pleas help me.

**Comment by lushc** [comment] 2019-12-10 18:17
The solution to this issue can be found here: https://github.com/symfony/symfony/issues/29809#issuecomment-451994583

Specifically, you need to create & use a new form type that allows you to submit this kind of unstructured data: https://github.com/sulu/SuluArticleBundle/blob/c0ed0b34b2903d517f555811276d0ad7f598497e/Document/Form/UnstructuredType.php#L12-L32
