### ISSUE TITLE
[Session][Test] MockFileSessionStorage is not persistent

### ISSUE THREAD

**Issue by mtricht** [symfony/symfony#22616] opened 2017-05-02 19:49 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.1+

The following controller:

```php
class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $this->get('session')->set('test', 'test');
        $this->get('session')->save();
        return new Response('All good');
    }

    /**
     * @Route("/test", name="test")
     */
    public function testAction()
    {
        if ($this->get('session')->get('test') !== 'test') {
            return new Response('Missing test');
        }
        return new Response('All good');
    }
}
```

Used in a test:

```php
class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();
        $client->request('GET', '/');
        $client->request('GET', '/test');
        $this->assertEquals('All good', $client->getResponse()->getContent());
    }
}
```

Expected: Test succeeds. Session is persisted as documented [here](http://symfony.com/doc/current/components/http_foundation/session_testing.html#functional-testing).
Actual: Test fails. The session is not persisted through the two requests.

The following line causes this: https://github.com/symfony/symfony/blob/85e2d2f91d9b63b10bc327f0fee5f47b3b67dc6a/src/Symfony/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php#L104 Removing this line fixes the problem.

Another 'solution' is adding the following line to the first action:

```diff
@@ -16,6 +16,7 @@ class DefaultController extends Controller
     {
         $this->get('session')->set('test', 'test');
         $this->get('session')->save();
+        $this->get('session')->get('test');
         return new Response('All good');
     }
```

Adding this get after the save sets the `started` variable back to `true` meaning the session is persisted, which is rather odd and made debugging this issue very frustrating.

**Comment by dmaicher** [comment] 2017-05-03 16:33
I cannot reproduce this problem on Symfony 2.8 :yum: Can you fork the symfony standard edition and apply the minimal changes to reproduce this issue?

**Comment by swordbeta** [comment] 2017-05-03 17:02
@dmaicher 2.8: https://github.com/swordbeta/symfony-standard/commit/32e300b108ba476f3daed2efee7852d940546df8
master: https://github.com/swordbeta/symfony-standard/commit/a9da9e3d81c40bb8cf3db8218508d4e3664ed204

Tested on 3 different machines with 7.1.3 and 7.1.4

**Comment by dmaicher** [comment] 2017-05-03 17:29
ok thanks :+1: I think the difference to my tests was that I tested it behind a firewall :yum: 

Seems weird indeed the behaviour.

This works:

```php
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $this->get('session')->set('test', 'test');
        return new Response('All good');
    }
```

And this also:

```php
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $this->get('session')->set('test', 'test');
        $this->get('session')->save();
        $this->get('session')->start();
        return new Response('All good');
    }
```

**Comment by swordbeta** [comment] 2017-05-03 17:50
@dmaicher weird that the first one works, isn't save always called at the end? I guess I could just remove the save call for now

**Comment by HeahDude** [comment] 2017-07-30 10:02
Looks like this is some how expected https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php#L104, maybe a documentation issue?

**Comment by jakzal** [comment] 2017-10-25 10:40
You shouldn't be calling `save()` yourself as the framework already takes care of it. If `save()` is called twice, the second time it will throw an exception (which is the reason why you're getting different output in your test).

**Comment by Tobion** [comment] 2017-10-27 01:13
This looks like a bug. The NativeSessionStorage does not throw an exception when saving twice. A `session_write_close` on an inactive session is just ignored and does nothing. The mocked session must have the same behavior otherwise the two implementations are inconsistent.

**Comment by jakzal** [comment] 2017-10-27 06:41
Well, the logic was deliberately introduced in #6362

**Comment by dmaicher** [comment] 2019-04-06 08:57
Investigating this again as part of the #eu-fossa hackathon.

I cannot reproduce this anymore on Symfony 3.4+.

Also with recent changes in `Session` we will not call `save` on the storage if the session is not started (anymore):

https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/HttpFoundation/Session/Session.php#L196

So I think we can close this @jakzal @Tobion ?

**Comment by Tobion** [comment] 2019-04-06 21:09
I still think it should not throw an exception in https://github.com/symfony/symfony/blob/a84842b519c1d334376f62f5a56fcad30de2d5ff/src/Symfony/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php#L91 but just `return;`. But since the original issue is not reproducible and `save` is not called anymore when the session has not been started, there is no point in changing the mock storage and potentially add a bc break.

**Closed by Tobion** 2019-04-06 21:09 UTC
Labels: Bug, HttpFoundation, Status: Needs Review, ⭐️ EUFOSSA Hackathon
