### ISSUE TITLE
Twig made non-dev when installing profiler-pack

### ISSUE THREAD

**Issue by inverse** [symfony/symfony#36843] opened 2020-05-16 19:32 UTC
**Symfony version(s) affected**: 5.0.8

**Description**  

Not sure if this is an issue or intended but when I setup a new app and installed the profiler-pack it installs twig and exposes it in `bundles.php` as `all`.

However when pushing to production with `--no-dev` this fails as I don't have twig installed. 

**How to reproduce**  

```bash
symfony new test-app
cd test-app
composer require --dev symfony/profiler-pack
```

**Possible Solution**  

Twig should be flagged as dev unless explicitly requested. 

**Additional context**

**Comment by derrabus** [comment] 2020-05-17 12:48
Duplicate of symfony/recipes#254

**Comment by inverse** [comment] 2020-05-17 13:43
Thanks for finding... Didn't think to check there! Yeah just caught my off a bit unexpectedly

**Comment by xabbuh** [comment] 2020-05-17 16:56
Closing in favour of symfony/recipes#254 then.

**Closed by xabbuh** 2020-05-17 16:56 UTC
Labels: Bug, Status: Needs Review
