### ISSUE TITLE
Intl region specific language configurable

### ISSUE THREAD

**Issue by Tersoal** [symfony/symfony#36284] opened 2020-03-31 08:34 UTC
**Description**  
Hi. The last change in Intl languages (https://github.com/symfony/symfony/issues/35309) breaks my application. I have a glossaries application that relies on Intl languages, and languages variations are critical.

Would be possible to make this option configurable?

**Example**  
In symfony 4.3, this languages are returned (extract):

```
   {
      "code":"es",
      "name":"espa\u00f1ol"
   },
   {
      "code":"es_ES",
      "name":"espa\u00f1ol de Espa\u00f1a"
   },
   {
      "code":"es_MX",
      "name":"espa\u00f1ol de M\u00e9xico"
   },
   {
      "code":"es_419",
      "name":"espa\u00f1ol latinoamericano"
   },
```
In symfony 4.4, this languages are returned (extract):

```
   {
      "code":"es",
      "name":"espa\u00f1ol"
   },
```
Regional languages are missed and are very important because glossaries from US english to es_ES spanish are different from GB english to es_ES spanish, and those are very different if target language is es_MX.

**Comment by stof** [comment] 2020-03-31 10:45
region-specific things are locales, not languages. And there is a separate API to get them.

**Comment by Tersoal** [comment] 2020-03-31 11:02
I will try with locales, thank you.

**Comment by javiereguiluz** [comment] 2020-03-31 11:36
Meanwhile, let's close this one as "fixed". If using the Locales is not possible for some reason or the problem is different, please tell us. Thanks!

**Closed by javiereguiluz** 2020-03-31 11:36 UTC
Labels: Feature, Intl

**Comment by Tersoal** [comment] 2020-04-01 08:43
Only one comment trying to help others to manage it. I have had to merge Languages and Locales arrays to allow all possible languages, because Locales does not return Abkhazian for example.

Thank you all.
