### ISSUE TITLE
Help block is not shown for a CheckboxType field

### ISSUE THREAD

**Issue by watlf** [symfony/symfony#29135] opened 2018-11-08 12:02 UTC
**Symfony version(s) affected**: 4.1.0

**Description**  
Help block is not shown for a [CheckboxType](https://symfony.com/doc/current/reference/forms/types/checkbox.html) field.

**How to reproduce**  
Add some checkbox field in FormType
<pre>

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class SomeCheckboxForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, [
            'label' => 'Name',
        ]);

        $builder->add('public', CheckboxType::class, array(
            'label'    => 'Public',
            'help' => 'message text',
        ));
    }
}
</pre>

Create form in controller:
<pre>
$checkbox = $this->createForm(SomeCheckboxForm::class)->createView();
</pre>

And print it in view template:
<pre>
    {{ form_start(checkbox) }}
    {{ form_widget(checkbox) }}
    {{ form_end(checkbox) }}
</pre>

**Comment by xabbuh** [comment] 2018-11-08 12:34
Which form theme do you use?

**Comment by watlf** [comment] 2018-11-08 13:07
I use a custom layout that consist of a few lines:
<pre>
{% block form_label_class -%}
col-sm-4
{%- endblock form_label_class %}

{% block form_group_class -%}
col-sm-8
{%- endblock form_group_class %}
</pre>

**Comment by xabbuh** [comment] 2018-11-08 13:33
Would you like to create  a small example application including your form theme that allows to reproduce the issue?

**Comment by apfelbox** [comment] 2018-11-08 14:33
So I guess you are extending the bootstrap themes, as [only they have these blocks](https://github.com/symfony/symfony/search?q=form_label_class&unscoped_q=form_label_class).

The issue should be fixed in the Bootstrap v4, since https://github.com/symfony/symfony/pull/28113, but not sure about Bootstrap v3.

**Comment by xabbuh** [comment] 2018-11-24 10:41
Could you still create a small example application that allows to reproduce so we can see if and how we can fix it?

**Comment by xabbuh** [comment] 2018-12-04 11:54
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Closed by xabbuh** 2018-12-04 11:54 UTC
Labels: Bug, Form, Status: Waiting feedback, TwigBridge
