### ISSUE TITLE
[Form] Optional empty text fields are always NULL instead of the empty string

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22192] opened 2017-03-27 23:46 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master (likely 3.x and 2.x as well)

Consider a basic data class:
```
class MyClass
{
  private $value = '';

  public function setValue(string $value)
  {
    $this->value = $value;
  }

  public function getValue(): string
  {
    return $this->value;
  }
}
```
Map a basic form with the field optional:
```
$form = $this->createFormBuilder(new MyClass())
            ->add('value', TextareaType::class, [
                'required' => false,
            ])
            ->add('create', SubmitType::class)
            ->getForm();
// etc.
```
Submit the form with the field empty and we get an `InvalidArgumentException`:

> Expected argument of type "string", "NULL" given
> in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 275

As the value itself is empty, the Form sets its `$modelData` to `NULL`, while `$normData` and `$viewData` are correctly the empty string. `PropertyPathMapper::mapFormsToData` subsequently attempts to set the property to null, which would have been fine if not for the type hinting in the setter, causing the exception. 

*edit*: if I remove the type hint from the setter I then get a Doctrine error as the field itself is mandatory yet `NULL` was inserted. I most definitely want users to be able to have the empty string in there, not null. So this is in the Form component, not the PropertyAccess end doing as it's told.

**Comment by Tobion** [comment] 2017-03-28 00:07
Have you tried setting `empty_data` option to `''`? This should be possible since #18357

**Comment by curry684** [comment] 2017-03-28 00:11
@Tobion that fixes the issue, but why would I need to do that to keep a string field as a string?

Also, this behavior directly contradicts documentation at http://symfony.com/doc/current/reference/forms/types/form.html#empty-data which I did read before posting this issue:

> If data_class is not set and compound is false, then '' (empty string).

**Comment by curry684** [comment] 2017-03-28 00:18
And actually that makes it a duplicate of https://github.com/symfony/symfony-docs/issues/7596, which was put on hold. Didn't quite search the docs repository as I do think the Form component is at fault here.

So, apart from fixing the docs today, shouldn't we mark this as a needs-fix for 4.0?

**Comment by HeahDude** [comment] 2017-03-28 08:09
Hello @curry684, this can be closed as duplicate of https://github.com/symfony/symfony/issues/4102, see https://github.com/symfony/symfony/issues/5906#issuecomment-289474281 for workarounds, I've also answered in https://github.com/symfony/symfony-docs/issues/7596.

FYI information I'm working on this for some time now, it's too late for 3.3, but I've good hope for 3.4/4.0 :).

**Closed** 2017-03-28 08:48 UTC

**Comment by carlos-mg89** [comment] 2020-02-05 15:58
This is still an issue (Symfony 5.0 and most likely 5.1) with TextAreaType when is empty. It gets treated as NULL, unless you add the `empty_data => ''` option.
