### ISSUE TITLE
[Error] MessageBusInterface: service or alias has been removed or inlined

### ISSUE THREAD

**Issue by darkiron** [symfony/symfony#41529] opened 2021-06-03 14:44 UTC
**Symfony version(s) affected**: 5.3.1

**Description**
The "Symfony\Component\Messenger\MessageBusInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**How to reproduce**
Fresh install with GraphqlLite : 
```
 <?php
namespace App\Http;

use App\Action\Query\FindTestQuery;
use App\MessageBus\QueryBus;
use Symfony\Component\Messenger\MessageBusInterface;
use TheCodingMachine\GraphQLite\Annotations\Autowire;
use TheCodingMachine\GraphQLite\Annotations\Query;

class HelloHttp {

    private $queryBus;

    #[Query]
    public function hello (string $name) : string
    {
        return "hello $name";
    }


    #[Query]
    public function testAuth( #[Autowire] MessageBusInterface $queryBus) : string
    {
        $this->queryBus = new QueryBus($queryBus);

        $query = new FindTestQuery();
        $query->personId = 1;

        $result = $this->queryBus->query($query) ?? [];

        return $result;
    }

}
```

**Possible Solution**
No possible solution

**Additional context**
I try to force service as public

**Comment by nicolas-grekas** [comment] 2021-06-21 13:56
Please provide a full reproducer if you think there is a bug in Symfony.
I'm closing for now because seeing `#[Autowire]`, it looks like this is not using Symfony's DI container to do the wiring, so that this might not be a Symfony issue.

**Closed as completed by nicolas-grekas** 2021-06-21 13:56 UTC
Labels: Bug, Status: Needs Review, Messenger
