### ISSUE TITLE
TranslationPullCommand cannot be found

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#43220] opened 2021-09-28 09:24 UTC
**Symfony version(s) affected**: 5.3.8

**Description**
Upgrading v5.3.7 => v5.3.8 gives:

>Class "Symfony\Component\Translation\Command\TranslationPullCommand" used for service "console.command.translation_pull" cannot be found.

**How to reproduce**
```json
        "sensio/framework-extra-bundle": "^6",
        "symfony/asset": "5.3.*",
        "symfony/console": "5.3.*",
        "symfony/css-selector": "5.3.*",
        "symfony/dom-crawler": "5.3.*",
        "symfony/dotenv": "5.3.*",
        "symfony/flex": "^1.1",
        "symfony/form": "5.3.*",
        "symfony/framework-bundle": "5.3.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/process": "5.3.*",
        "symfony/property-access": "5.3.*",
        "symfony/property-info": "5.3.*",
        "symfony/security-bundle": "5.3.*",
        "symfony/serializer": "5.3.*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "5.3.*",
        "symfony/twig-bundle": "5.3.*",
        "symfony/validator": "5.3.*",
        "symfony/web-link": "5.3.*",
        "symfony/yaml": "5.3.*",
```

**Possible Solution**
Downgrade to 5.3.7.

```json
    "extra": {
        "symfony": {
            "require": "<5.3.8"
        }
    }
```

**Additional context**
I don't understand how this is happening. The service definition seems to be pointing to a class that exists.

**Comment by icanhazstring** [comment] 2021-09-28 09:28
Duplicate to #43212

**Comment by derrabus** [comment] 2021-09-28 09:28
Duplicate of #43212

**Closed as completed by derrabus** 2021-09-28 09:28 UTC
Labels: Bug, Status: Needs Review
