### ISSUE TITLE
[Twig] ICU - variable first in translation fails (+intl-icu)

### ISSUE THREAD

**Issue by rkeet** [symfony/symfony#33251] opened 2019-08-20 09:06 UTC
**Symfony version(s) affected**: 4.3.3

Possibly since 4.2.x (`+intl-icu` suffix support)

**Description**  

If using a variable as the first thing in a translated string, then an issue is raised during the `post-install-cmd: @auto-scripts` from the `composer install`

**How to reproduce**  

Create file `test+intl-icu.en.yaml` and place the following content:

```yaml
translatable:
  string: {this_var} is translated
```

**Workaround**  

You can work around it by quoting this string: `"{this_var} is translated"`

This is, however, **not** a solution

**Additional context**  

Dumped below is the log which fails the build on a `{var}` at the start of a translation string

```shell
> post-install-cmd: @auto-scripts
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the test environment with debug                      
!!   // true                                                                        
!!  
!!  
!!  In YamlFileLoader.php line 45:
!!                                                                                 
!!    Error parsing YAML, invalid file "/var/www/html/translations/header+intl-ic  
!!    u.nl.yaml"                                                                   
!!                                                                                 
!!  
!!  In Inline.php line 531:
!!                                                                                 
!!    Malformed inline YAML string: {product_group} merken at line 18 (near "popu  
!!    lar_makes: {product_group} merken").                                         
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-install-cmd
Service 'php' failed to build: The command '/bin/sh -c APP_ENV=test composer install --no-interaction -v' returned a non-zero code: 1
2019-08-20T08:45:35.397714602Z stdout P 
```

**Comment by stof** [comment] 2019-08-20 09:50
a `{` has a meaning in YAML. So quoting **is** the solution (or using Xliff rather than YAML). The issue is that your YAML file is not valid.

**Comment by xabbuh** [comment] 2019-08-20 11:37
I am closing here since there is nothing to fix as @stof explained.

**Closed by xabbuh** 2019-08-20 11:37 UTC
Labels: Translator
