### ISSUE TITLE
[RFC] make dump() and other functions available (but NOP) with debug=false

### ISSUE THREAD

**Issue by malarzm** [symfony/symfony#24350] opened 2017-09-27 21:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4 (?)

_I'm sorry if this was discussed before, but I couldn't find anything with search._

Today I have accidentally deployed a controller with `dump()` in it to an environment that finally had `debug` flag set to `false` only to see a 500 error page (it was used in an action called asynchronously so I couldn't see that there are some variables dumped in the toolbar before). While I agree it's my fault for not catching this before, I also think that penalty doesn't fit the crime. To make situation like mine a little bit better I'd like to propose registering all "development" utilities (`dump()` et al) to be available in prod-like environments, but instead of any heavy lifting, make them do nothing. I don't have any numbers to back this up, but I believe that registering a NOP functions/twig methods will not affect overall Symfony performance. Also any overlooked calls (or even ones left on purpose) should not compromise applications' loading time. Also for those who want to fine-tune Symfony, it could be possible to not register dev utils (so get back to current situation) with a config flag.

What do you think?

**Comment by ogizanagi** [comment] 2017-09-27 22:32
Duplicate of #22433 :) 
(But doesn't mean your issue has to be closed if you're ready to advocate your position for another round after reading the previous issue comments)

**Comment by malarzm** [comment] 2017-09-28 08:53
Thanks @ogizanagi for pointing me to the original thread. As I don't agree with some points, I'll give advocating this RFC a shot :)

> Loading a file with a function that is only being used by you

This could be addressed by developer explicitly turning off development functions via a config flag, as mentioned in the original description. This way situation is back to current one and then developer can only blame himself/reviewer/lack of linter as (s)he explicitly told Symfony "I don't wanna these".

> Loading a file with a function [...] you costs CPU cycles and IO load.

CPU cycles and IO load for loading 1-2 additional file(s) should be neglectable, but if this is seen as an issue, those files could be dumped into compiled container - this way an additional file loading is out of the equation and registering a function is not a big deal. Also, utilizing reflection API is considered slow and yet Symfony (and Doctrine) is full of it and nobody cares because usually it's not that slow or there's nothing better :) Last but not least, there'd be a config flag to disable this dreaded overhead altogether.

> You should probably start doing code reviews, this would've probably been discovered.

The part that weakens this argument is "probably". I am myself a big proponent of code reviews but  I've also seen worse things sneaking through reviews and so could this.

> You need a code linter

This is a valid point, but IMO in this case it's an overkill.

**Comment by nicolas-grekas** [comment] 2017-10-01 20:27
:-1: as we made this decision on purpose. The fatal error is putting a high priority on not committing any call to dump(), which is a requirement for security purpose. There is no DX to care about here IMHO.

**Comment by fabpot** [comment] 2017-10-01 23:13
I agree with @nicolas-grekas

**Closed by fabpot** 2017-10-01 23:13 UTC

**Comment by malarzm** [comment] 2017-10-02 07:32
Thank you for your response, I will take "no" as an answer. But out of curiosity, what security purpose does not having `dump` serve? I would understand fully-working `dump` as a possible concern, but one that is NOP?

**Comment by nicolas-grekas** [comment] 2017-10-02 07:43
It leads to confusion: ppl cannot know what this dump will really do
and it lead to the bad kind of lazyness: committing would be an issue anymore

**Comment by javiereguiluz** [comment] 2017-10-02 07:56
I will also take "no" as an answer ... but I agree with this proposal. And it's similar to what we do in other parts of the framework. For example, the strict_requirements/strict_variables settings make Symfony be forgiving of your errors in the production environment. This would be the same: *"OK, you pretend to use `dump()` in prod. That's wrong for multiple reasons, but instead of crashing your app, I'm fixing this for you turning it into NOP"*.

Anyway, the "no" is sound and clear ... so let's not discuss more about this. Cheers!
