### ISSUE TITLE
Runnable query is not runnable in DoctrineDataCollector

### ISSUE THREAD

**Issue by garak** [symfony/symfony#24782] opened 2017-11-01 10:35 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

This is some kind of re-opening of #20673.
The implementations done in 3b4a8f37300bc0fd48a7359e526eae93b56174f7 missed the point.
Getting a *runnable* query like the following one:
```
SELECT s0_.name AS name_0 FROM slide s0_ WHERE s0_.id = 'Object(Ramsey\\Uuid\\Uuid): \"363dd322-488e-4a60-8caf-c3cfe51f9d7c\"' LIMIT 1;
```
is pretty useless, because it's obviously not runnable at all.
What I expect is a query like this one:
```
SELECT s0_.name AS name_0 FROM slide s0_ WHERE s0_.id = '363dd322-488e-4a60-8caf-c3cfe51f9d7c' LIMIT 1;
```
that is **really** runnable (e.g. I can copy&paste in some database client)

**Comment by xabbuh** [comment] 2017-11-02 11:03
Related to (or duplicate of) #24700?

**Comment by garak** [comment] 2017-11-02 14:10
It's not a duplicate, this case is more general, i.e. it can apply to every time an object is used in a query (not only to an entity used as identifier).

**Comment by Simperfit** [comment] 2017-11-08 06:42
Since this has been labeled as a bug, @garak can you work on it ?

**Comment by kix** [comment] 2017-11-14 12:29
What could be done here is making the `DoctrineDataCollector::sanitizeParam` return the `Object(%s):` part commented out so that the output would be like:
```
SELECT s0_.name AS name_0 FROM slide s0_ WHERE s0_.id = /* Object(Ramsey\\Uuid\\Uuid): */ "363dd322-488e-4a60-8caf-c3cfe51f9d7c" LIMIT 1;
```
Although I think actually the problem is that parameters are replaced inside the query and not in a separate procedure, e.g. to get a runnable query, we just modify the one we have and fill in the placeholders with values. In my opinion, the runnable query should be a separate entity perhaps.

**Closed** 2017-12-07 16:55 UTC
Labels: Bug, Doctrine, Status: Needs Review

**Comment by garak** [comment] 2019-10-01 15:31
Unfortunately, this bug is still present in Symfony 4.4
This is an output example of runnable query:
>SELECT u0_.email AS email_0, u0_.password AS password_1, u0_.id AS id_6 FROM user_ u0_ WHERE u0_.id = '/* Object(Ramsey\\Uuid\\Uuid): */\"c91dd2d6-ba8e-11e8-bdaf-0242ac1d0003\"' LIMIT 1;

as you can see, the query is not runnable at all, since the whole string (with the comment) is single-quoted, while the double-quoted uuid is escaped 😔
