### ISSUE TITLE
[HTTPCache]Cannot retrieve the container from a non-booted kernel. 

### ISSUE THREAD

**Issue by wiseguy1394** [symfony/symfony#40781] opened 2021-04-12 13:17 UTC
**Symfony version(s) affected**: 5.2.6

**Description**
In Symfony 5.2.6 the "handle" method is overwritten https://github.com/symfony/framework-bundle/blob/v5.2.6/HttpCache/HttpCache.php#L66-73 . The "getContainer()" call triggers the exception  at https://github.com/symfony/http-kernel/blob/5.x/Kernel.php#L307 

**How to reproduce**
Use Cache Kernel as explained here [HTTP Cache - Symfony Reverse Proxy](https://symfony.com/doc/current/http_cache.html#symfony2-reverse-proxy)

Calling `$kernel->handle()` will fail with `Fatal error: Uncaught LogicException: Cannot retrieve the container from a non-booted kernel. in /var/www/vhosts/dev.bibleserver.com/httpdocs/v2019/vendor/symfony/http-kernel/Kernel.php:307 Stack trace: #0 /var/www/vhosts/dev.bibleserver.com/httpdocs/v2019/vendor/symfony/framework-bundle/HttpCache/HttpCache.php(68): Symfony\Component\HttpKernel\Kernel->getContainer() #1 /var/www/vhosts/dev.bibleserver.com/httpdocs/v2019/public/index.php(30): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #2 {main} thrown in /var/www/vhosts/dev.bibleserver.com/httpdocs/v2019/vendor/symfony/http-kernel/Kernel.php on line 307`

To boot the kernel at this point doesn't make sense. But I don't know how to load a parameter without a booted Kernel. 

**Reproducer:** https://github.com/wiseguy1394/symfony5.2.6-http-cache

**Comment by wiseguy1394** [comment] 2021-04-12 13:20
Maybe the configuration of `http_method_override`  should be changed to something like this https://symfony.com/doc/current/reference/configuration/kernel.html

**Comment by stof** [comment] 2021-04-12 13:42
Duplicate of https://github.com/symfony/symfony/issues/40618 which is already fixed in the dev version

**Closed as completed by stof** 2021-04-12 13:42 UTC
Labels: Bug, Status: Needs Review
