### ISSUE TITLE
[Routing] Allow to use kernel parameters when importing resources

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#15864] opened 2015-09-22 08:02 UTC
Kernel parameters are not parsed when importing resources in `routing.yml`:

```
_nested:
    resource: %kernel.config_dir%/file_name.yml
```

It would be nice to be fixed.

**Comment by sstok** [comment] 2015-09-22 17:57
This is not possible due to technical limitations #9361

**Comment by stof** [comment] 2015-09-26 11:06
@sstok the issue you linked was about making parameters available for config file resources. And this was not possible.

For routing resources, it might be possible to allow them (the container is fully built at this point). Not sure how hard or easy it would be though.

**Comment by sstok** [comment] 2015-09-27 12:43
Hehe :)

**Comment by weaverryan** [comment] 2015-09-28 00:00
I'm flagging this as a duplicate of #15296 

#15948 would also fix this partially for end-users, as you could import routes from the kernel and use `$this->getContainer->getParameter()` in there (but we could also probably change the underlying issue as @Strate is asking).

**Closed by weaverryan** 2015-09-28 00:00 UTC
