### ISSUE TITLE
[DI] CSV env var processor does not work like an ordinary array

### ISSUE THREAD

**Issue by stollr** [symfony/symfony#40654] opened 2021-03-31 14:12 UTC
**Symfony version(s) affected**: 5.2.6

**Description**
I am trying to setup monolog with a symfony_mailer handler. I want to configure the `to_email` with an ENV variable and usage of the csv processor so that I can add multiple receivers.

**How to reproduce**
I have the `monolog.yaml` looking like that:
```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: symfony_mailer
        symfony_mailer:
            type:         symfony_mailer
            from_email:   '%env(MAILER_FROM)%'
            to_email:     '%env(csv:MAILER_ERRORLOG_TO)%'
            subject:      'Error! %%message%%'
            formatter:    monolog.formatter.html
            content_type: text/html
```
And the `.env.local` looks like that:
```
MAILER_ERRORLOG_TO=john@example.com,chris@example.com
```

This results in an InvalidTypeException
> Invalid type for path "monolog.handlers.symfony_mailer.to_email.0". Expected one of "bool", "int", "float", "string", but got "array".

When I replace the env var with a real array, for instance
```yaml
to_email:     ['john@example.com', 'chris@example.com']
```
the error is resolved. But as you can imagine this is no real solution.

I already have tried to figure out, what the problem is, but without real result. In Symfony's config definition `BaseNode` there is a normalizer method, which seem to replace the env variable with a nested array [[]] and this results in the error described above. 

If you need more details please tell me.

**Comment by ro0NL** [comment] 2021-03-31 15:55
See #27683, got stuck in #29270 :)

**Comment by stollr** [comment] 2021-03-31 18:33
You are right. I see the problem. Would it be complicated to implementiert a checker, telling the developers that this combination of config and env is currently not supported, until there is a better solution?

Because it took me some time to figure out were the problem comes from.

**Comment by ro0NL** [comment] 2021-03-31 19:36
i think the error message is the best hint we can generically provide currently :/

actually i think the right way to fix it is to make `ifString` return false for envs, introducing a new `ifEnv()` while at it.

Im not sure what BC breaks it'll cause but conceptually it should do the trick. (i think "env placeholders" are special, and should not match "string values", even they technically are).

Perhaps give it a try :)

**Comment by stollr** [comment] 2021-04-01 07:37
What I do not get is: why is an empty array used at placeholder for an env variable? wouldn't be a string better suited?

**Comment by ro0NL** [comment] 2021-04-01 08:02
`csv:` tells us values will always be of type array: https://github.com/symfony/symfony/blob/f963ae476a6534b29b638f47d19dc076a0afebd5/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php#L46

the case where ifString() could return true, is in case the env is also type string at least.

**Comment by nicolas-grekas** [comment] 2021-06-21 15:55
Closing as duplicate of #40906

**Closed as completed by nicolas-grekas** 2021-06-21 15:55 UTC
Labels: DependencyInjection, Bug, Status: Needs Review
