### ISSUE TITLE
[RFC] Declare issue (and pull request) bankruptcy

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#16115] opened 2015-10-05 08:08 UTC
### Problem

We have +700 pending issues (oldest one from July 2011) and +170 pending pull requests (oldest one from November 2011). Having lots of issues and PR is not a problem, because it shows that a project is healthy and active.

The problem, in my opinion, is that most of those issues/PR are dead and they will never ever be taken care of. The upcoming release of 2.8/3.0 is a **once-in-a-lifetime opportunity** to solve this problem.

### Solution

We could declare "issue bankruptcy" by closing all open issues. That will allow us to make a fresh start for the project and it could improve community morale.

I know that it sounds radical, but some popular projects such as PHPUnit, have recently applied this strategy:

![phpunit_issue_bankrupcy](https://cloud.githubusercontent.com/assets/73419/10275559/8a40aea0-6b48-11e5-8e5d-6a310bb9c9c8.png)

In the case of pending PR, there is no need to close all of them because there are some recent PR which are active and they will be completed.

**Comment by fweber-de** [comment] 2015-10-05 08:25
I am in favor for this. If ones Issues and PRs are still relevant it should be easy to reasses them through a personal filter.

+1

**Comment by mkrauser** [comment] 2015-10-05 08:29
I totally agree! 

+1

**Comment by calinpristavu** [comment] 2015-10-05 08:32
I am so-so regarding this proposal, because although most of the issues are posted by active users, Some of the bugs are posted by "one-timers" which won't even notice that their issues were closed.

If the deciders think that cleanness is more important than completeness, it's a good move.
But IMHO, it's better to have a large set of data than an incomplete one, so:

-1

**Comment by jesusAlvSoto** [comment] 2015-10-05 08:47
I agree. Any active users will re-open the issue. It is much easier and faster if each user checks if the issue still exists in the new release.

+1

**Comment by stof** [comment] 2015-10-05 08:53
> Some of the bugs are posted by "one-timers" which won't even notice that their issues were closed.

They won't ever provide the info we need to be able to do something to solve the issue though. We have many issues which don't provide enough info to reproduce them.

**Comment by javiereguiluz** [comment] 2015-10-05 08:53
@jesusAlvSoto to increase the effectiveness of this strategy, issues are closed and locked. This avoids re-opening the issues with one click. The issue reporter must recreate it in case he/she still finds it relevant:

![phpunit_closed_and_locked](https://cloud.githubusercontent.com/assets/73419/10276344/2ccad8c0-6b4f-11e5-8735-5c36deb80f4d.png)

**Comment by stof** [comment] 2015-10-05 08:54
> This avoids re-opening the issues with one click.

Users cannot reopen issues closed by a collaborator. they can only reopen them if they closed the issue themselves. An issue closed by a collaborator requires collaborator access to reopen it

**Comment by jesusAlvSoto** [comment] 2015-10-05 09:03
@javiereguiluz looks like the proper way to do it. The reporter should take the effort of creating a new issue if it is still relevant.

**Comment by iltar** [comment] 2015-10-05 09:11
I think this is a good idea to follow. I've personally checked the issues/pr on the last few pages and the PR are never getting in (Rebase issues etc). If the issues reported would really be a problem at this point, they would be more active. I don't think all issues/prs should be closed, (e.g.) if the PR is active but the issue isn't, it should not be closed.

_I do not agree with the locking as that wouldn't give any real benefit._

:+1:

**Comment by theofidry** [comment] 2015-10-05 09:43
+1, if old PR/issues are still relevant, the user can always ask to repopen them.

**Comment by fabpot** [comment] 2015-10-05 10:06
I'm :-1: on blindly close everything. There are some old PRs that are valid but we just did not took the time to properly review them or we are waiting for some feedback (like more tests). Some of them could be finished instead of closed. That's really a matter of priorities.

I'm :+1: in closing old issues with not-enough info from the reporter, edge-case feature requests, things that should have been fixed now, issues on deprecated features, ...

**Comment by iltar** [comment] 2015-10-05 10:19
Carson could be tweaked to allow a specific tag to be added that marks it to be closed, this way the community can easily check PRs and Issues.

**Comment by iamdto** [comment] 2015-10-05 10:44
Agree with @fabpot.

**Comment by fabpot** [comment] 2015-10-05 12:18
A better idea would be to ask people to actually check if their issues are still relevant and close it not.

One thing that works well (and @xabbuh, @jakzal and myself have been doing for years) is to ping the reporter when we need more information. If there is no feedback, we can then just close the issue. Automating that sounds easy as well: when pinging someone, we add a special tag and the Carson bot automatically closes the issue if there is no more activity on the ticket for 2 weeks.

**Comment by theofidry** [comment] 2015-10-05 13:09
>when pinging someone, we add a special tag and the Carson bot automatically closes the issue if there is no more activity on the ticket for 2 weeks.

:100:

**Comment by acrobat** [comment] 2015-10-05 13:19
An automatic way would work well i think! Twitter bootstrap uses the same system with their issue bot, https://github.com/twbs/bootstrap/issues/17602#issuecomment-144309086

**Comment by Taluu** [comment] 2015-10-05 13:39
:+1: with what @fabpot said. But 2 weeks looks too long IMO

**Closed** 2015-10-07 12:11 UTC

**Comment by stof** [comment] 2015-10-07 12:15
> But 2 weeks looks too long IMO

giving less time is not fair for people not checking their issue very often (or being in vacation).
And they could not just reopen it. An issue author cannot reopen the issue if it was closed by a collaborator (and Carson s a collaborator on the repo, this is how it can work). They can only reopen issues they closed themselves
