### ISSUE TITLE
regression on Symfony Console component in 2.7.2 (ChoiceQuestion)

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#15302] opened 2015-07-17 13:09 UTC
Since Symfony 2.7.2, the answer to multichoice question does'nt work as expected.

![regression](https://cloud.githubusercontent.com/assets/1247388/8747719/b6e85ac6-2c95-11e5-8b9a-6fb57bb89a95.png)

```php
PHP Notice:  Undefined index: 0 - 40 in /home/mickael/Projets/certificationy-cli/vendor/symfony/console/Question/ChoiceQuestion.php on line 165
```

refs: https://github.com/certificationy/certificationy-cli/issues/9

As you can see, the same code works with Symfony 2.7.1 and lower.

**Comment by jakzal** [comment] 2015-07-20 13:07
Have you tried the latest 2.7 branch?

**Comment by xabbuh** [comment] 2015-07-20 13:08
looks like it is related to #15309

**Comment by mickaelandrieu** [comment] 2015-07-20 13:12
@jakzal broken on 2.7.2, I didn't test for 2.7-dev

**Comment by jakzal** [comment] 2015-07-20 13:19
I just tried the example from #15309 and that issue is fixed in the latest 2.7 (dev).

**Comment by jakzal** [comment] 2015-07-20 13:21
Closing. Feel free to reopen if you manage to reproduce this on the latest 2.7 branch.

**Closed by jakzal** 2015-07-20 13:21 UTC
Labels: Console

**Comment by mickaelandrieu** [comment] 2015-07-20 13:25
@jakzal nice news, when the 2.7.3 will be bumped ? I don't want to rely on dev-master branch :)
