### ISSUE TITLE
Use json env resolver in configurations

### ISSUE THREAD

**Issue by ln-e** [symfony/symfony#28137] opened 2018-08-05 19:58 UTC
**Symfony version(s) affected**: 4.1
**Description**  
I want to be able to configure swiftmailer delivery_adresses via env var. In prod env on production server it should be null, in prod env on staging server it should have some value. Looks like work for env parameters.

I try to set it like
```yaml
swiftmailer:
    delivery_addresses: '%env(json:MAILER_DELIVERY_ADDRESSES)%'
```
I specify `json` env processor, and in my env file

```env
MAILER_DELIVERY_ADDRESSES='["test@test.test"]'
```

```
A dynamic value is not compatible with a "Symfony\Component\Config\Definition\PrototypedArrayNode" node type at path "swiftmailer.mailers.default.delivery_addresses".
```

Json processor return array, and so it should be valid to pass such value to `PrototypedArrayNode`.

**Comment by ro0NL** [comment] 2018-08-06 10:11
This is by design. A prototyped array is still part of the semantic configuration tree.

The reason behind this is env vars can be any value during runtime, but the tree needs to be validated during compile time.

In this case it would be:

```
swiftmailer:
    delivery_addresses:
        - '%env(MAILER_DELIVERY_ADDRESS_1)%'
        - '%env(MAILER_DELIVERY_ADDRESS_2)%'
```

**Comment by xabbuh** [comment] 2018-08-06 10:31
I am closing here as this is the expected behaviour.

**Closed by xabbuh** 2018-08-06 10:31 UTC
Labels: Bug, Config, DependencyInjection, Status: Needs Review

**Comment by ln-e** [comment] 2018-08-07 04:59
@ro0NL it wouldn't work. This is equal to `[null]`, so count of `delivery_addressess` is bigger than 0. 
See https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/SwiftmailerExtension.php#L336

Looks like env should be convenient replacement of `parameters.yml` but in fact it is not.

**Comment by ro0NL** [comment] 2018-08-07 06:55
environment variables and parameters have different usecases, so i wouldnt call it a replacement per se. Let alone to blindly update all parameters to env vars.

You say this doesnt work?

```yaml
swiftmailer:
    delivery_addresses:
        - '%env(MAILER_DELIVERY_ADDRESS_1)%'
        - '%env(MAILER_DELIVERY_ADDRESS_2)%'
```

**Comment by ln-e** [comment] 2018-08-07 16:18
I try to say that when yours config will be converted to php array it become `[null, null]`. There is two members. `null` and `null`. Count of such array is 2 not 0. 

Thus Swiftmailer will try to send all email not to real users, but to this two emails.

I should either pass `null` *instead* of array, or array with zero members. Only then swiftmailer will send email to real users. 

On my production server config should be equals to:
```json
swiftmailer:
    delivery_addresses: null
or
swiftmailer:
    delivery_addresses: []
```

On my staging server config should be equals to:
```json
swiftmailer:
    delivery_addresses:
        - test@email
```

With env var it is impossible to do so.

**Comment by ro0NL** [comment] 2018-08-07 17:30
@ln-e i got it :) thx. Currently this is impossible indeed, but it can be done by prepending a dynamic config in php ...

https://github.com/symfony/symfony/blob/510977dd193b21a18b86855cba9f9dfef2d9d0bb/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L695

**Comment by ro0NL** [comment] 2018-08-07 17:43
A permanent solution could be to expand the env syntax, in an effort to expose more type information.

```
%env(string[]:json:MAILER_DELIVERY_ADDRESSES)%
```

Here `string` is an existing prefix and the special `[]` notation would tell us this is an array of strings, which is compatible with the `swiftmailer.delivery_addresses` node. Moreover, it would actually be validated as such during runtime.

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment] 2018-08-07 18:29
Or we patch the bundle to make it accept an array and deal with it in a factory. I'd prefer this over adding more complexity.

**Comment by dtfafard** [comment] 2018-11-22 00:36
Is there any proposed solution that would allow the use of the json processor?

Using : 
```
swiftmailer:
    delivery_addresses:
        - '%env(MAILER_DELIVERY_ADDRESS_1)%'
        - '%env(MAILER_DELIVERY_ADDRESS_2)%'
```
Is actually unusable if I wish to have 2 emails in one environment and 4 in another one. The dynamism allowed by the arrayNode is broken.

Thank you!

**Comment by dtfafard** [comment] 2018-11-22 01:36
Hi guys, 

I've managed to make the code work manually overwriting : 

```
// In Symfony\Component\Config\Definition\ArrayNode
    /**
     * {@inheritdoc}
     */
    protected function allowPlaceholders(): bool
    {
        return false;
    }

// to 


    /**
     * {@inheritdoc}
     */
    protected function allowPlaceholders(): bool
    {
        return true;
    }
```
No errors were thrown. 

Can anyone shed some light on why was it set to false and, maybe, the negative repercussions to setting it to "true"?

**Comment by ro0NL** [comment] 2018-11-22 07:45
because it would only work "by chance", e.g. if the env is set correctly. At this point you can change the env  to any value and it would always pass config validation.

See #29270 for a different approach.

**Comment by shtumi** [comment] 2019-09-04 05:25
is there any progress with this issue?

**Comment by fritzmg** [comment] 2020-06-06 10:54
Regardless of how the configuration tree of the swiftmailer bundle is set up: what _is_ the correct way to allow dynamic values for a scalar array node in the configuration tree of your _own_ bundle? I am unable to figure out the correct way to do this.

**Comment by toby-griffiths** [comment] 2021-03-30 16:09
I've just spent ages trying to work out why the example in the docs isn't working.  Has anything changed in the past 2 years to allow this to work somehow?  If not, might be worth updating the docs to remove this as a bad example to save others time?

**Comment by sshymko-promenade** [comment] 2022-06-17 03:45
Being new to Symfony, initially got excited by the power of the [config syntax](https://symfony.com/doc/current/configuration/env_var_processors.html) only to run into completely artificial limitations on where in the config structure said syntax is allowed and where it is arbitrarily not.

## Use Case

The intent is to pass driver options to Doctrine DBAL:
```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: '%env(string:DATABASE_DRIVER)%'
        options: '%env(json:DATABASE_DRIVER_OPTIONS)%'
```

By design, each [driver](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#driver) comes with a unique set of options of virtually arbitrary format: key-value pairs mixed with flags.

Unfortunately, this syntax is not allowed in such completely reasonable situations:
```
A dynamic value is not compatible with a "Symfony\Component\Config\Definition\PrototypedArrayNode" node type at path "doctrine.dbal.connections.default.options".
```

## Workaround

A patch proposed by @dtfafard can be used as a workaround:

```bash
composer require cweagans/composer-patches
```

`composer.json`
```json
{
    "extra": {
        "patches": {
            "symfony/config": {
                "Dynamic config values": "patches/symfony-config.patch"
            }
        }
    }
}
```

`patches/symfony-config.patch`
```diff
diff --git a/vendor/symfony/config/Definition/ArrayNode.php b/vendor/symfony/config/Definition/ArrayNode.php
index 76b811c..14d4565 100644
--- a/vendor/symfony/config/Definition/ArrayNode.php
+++ b/vendor/symfony/config/Definition/ArrayNode.php
@@ -397,6 +397,6 @@ class ArrayNode extends BaseNode implements PrototypeNodeInterface
      */
     protected function allowPlaceholders(): bool
     {
-        return false;
+        return true;
     }
 }
```

```bash
composer install
```

## Proposal

How about extending the `env()` syntax to explicitly allow misc data structure?

```
%env(mixed:json:DATABASE_DRIVER_OPTIONS)%
```

There're numerous reports of this config inflexibility closed as "explained" or "by design" citing compile-time validation of the config format. While the validation is valuable, it's a pity to artificially restrict applications of such a powerful syntax.
