### ISSUE TITLE
[Intl] Maximum execution time of 10 seconds exceeded in BundleEntryReader.php

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#31087] opened 2019-04-12 09:40 UTC
**Symfony version(s) affected**: 4.2.3

**Description**  
We're seeing timeouts when using `Intl::getRegionBundle()`:
```
 Uncaught Symfony\Component\Intl\Exception\ResourceBundleNotFoundException: The resource bundle "vendor/symfony/symfony/src/Symfony/Component/Intl/Resources/data/regions/root.json" does not exist. in vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/JsonBundleReader.php:39
tack trace:
#0 vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BufferedBundleReader.php(46): Symfony\Component\Intl\Data\Bundle\Reader\JsonBundleReader->read('/home/...', 'root')
#1 vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php(88): Symfony\Component\Intl\Data\Bundle\Reader\BufferedBundleReader->read('/home/...', 'root')
#2 vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Provider/RegionDataProvider.php(61): Symf in vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/JsonBundleReader.php on line 39

PHP Fatal error:  Maximum execution time of 10 seconds exceeded in vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php on line 88
```

**How to reproduce**  
Make sure to install ICU 64.1. 

I'm running:
```
PHP 7.3.4-1+ubuntu16.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:50:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-1+ubuntu16.04.1+deb.sury.org+3, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.24.4~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

Use this test script:
```
<?php

set_time_limit(10);

include "vendor/autoload.php";

use Symfony\Component\Intl\Intl;

$names = Intl::getRegionBundle()->getCountryNames("fr");

var_dump($names); // This loads forever
```

Run it with `php test.php`

**Possible Solution**  
No idea.

**Additional context**  
Working version:
```
ICU version => 63.1
ICU Data version => 63.1
ICU TZData version => 2018e
ICU Unicode version => 11.0
```

Broken version
```
ICU version => 64.1
ICU Data version => 64.1
ICU TZData version => 2018i
ICU Unicode version => 12.0
```

**Comment by ruudk** [comment] 2019-04-12 09:41
It seems that updating from Symfony 4.2.3 to 4.2.5 solved the issue. I just created this issue so that people that have this problem know what to do.

**Comment by stof** [comment] 2019-04-12 09:42
Closing the issue, as this is already fixed in a released version.

**Closed by stof** 2019-04-12 09:42 UTC

**Comment by ruudk** [comment] 2019-04-12 09:44
What would be the best way to mitigate these issues? If for whatever reason I get a new ICU version on my machine, than my Symfony Intl supports, will I get these problems in the future? How would you recommend to keep ICU and Symfony Intl in sync?

**Comment by cocolabssas** [comment] 2019-04-23 10:02
This affect also Symfony 3.4.15. An update to 3.4.25 fix the issue.

**Comment by B-Galati** [comment] 2019-04-23 13:35
What was the issue at the end?

**Comment by maarekj** [comment] 2019-08-22 10:19
This issue is not fixed in 2.8 branch

**Comment by xabbuh** [comment] 2019-08-22 11:57
@maarekj Symfony 2.8 does not receive bug fixes anymore. You need to update to at least Symfony 3.4.

**Comment by maarekj** [comment] 2019-08-22 12:00
That's what I was afraid of.
Currently, I can't migrate to 3.4

Do you know from which version on branch 2.8 the bug occurs ?

**Comment by jakzal** [comment] 2019-08-22 17:59
@maarekj the change in behaviour was introduced by the latest ICU. It's not a bug in Symfony. All legacy versions of Symfony are affected.

**Comment by maarekj** [comment] 2019-08-22 18:04
No, in Symfony 2.8.27 there isn't this bug, wheareas >= 2.8.30 there is.

**Comment by DenisMir** [comment] 2019-10-01 13:28
PHP 7.3.10 and the following intl setup leaves me with the same problem although having Symfony 4.2.5 running. 

```
ICU version | 64.2
-- | --
ICU Data version | 64.2
ICU TZData version | 2019a
ICU Unicode version | 12.1
```

**Comment by maxolasersquad** [comment] 2019-10-17 21:14
This issue is introduced in Symfony 2.8.28. As @maarekj noted, you will need to hard-code your composer.json file to 2.8.27.
```
"symfony/symfony": "2.8.27"
```

**Comment by sensi** [comment] 2021-01-26 13:45
Also get this issue at symfony > 2.8.27. At 2.8.27 it work's. The reason is not clear but it seems that the php intl extension from ICU 65.1 throws this issue. For example my previous installed version works (50.x)
