### ISSUE TITLE
SessionInterface::getFlashBag() error reported by PHP Stan

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#39222] opened 2020-11-29 22:31 UTC
**Symfony version(s) affected**:

Both 4.x and 5.x

**Description**

Symfony cannot inject by default the `Session` service because it's not mapped as a service, so we need to inject the `SessionInterface`. However, `PHP Stan` reports an error when calling `getFlashBag()`

```
Call to an undefined method Symfony\Component\HttpFoundation\Session\SessionInterface::getFlashBag().
```

**How to reproduce**

Inject the `SessionInterface` and then call the `getFlashBag()` method. Finally, run `vendor/bin/phpstan analyse src -l 2` for a `level 2` analysis, where we should get that error message.

**Possible Solution**

Define the `getFlashBag()` method into the `SessionInterface`.

Alternatively, maybe you can give another option to pass this error reported by PHP Stan without adding extra annotations to ignore these lines once after another when they are in use in several services.

**Comment by jderusse** [comment] 2020-11-29 22:44
If you call `getFlashBag` on a `SessionInterface` the issue is in your code. Not all implementation of `SessionInterface` provides this method.

duplicate of https://github.com/symfony/symfony/issues/20258, https://github.com/symfony/symfony/issues/11279, https://github.com/symfony/symfony/issues/10036 , https://github.com/symfony/symfony/issues/5568
and probably many others

**Closed as completed by jderusse** 2020-11-29 22:44 UTC
Labels: Bug, Status: Needs Review

**Comment by jderusse** [comment] 2020-11-29 22:47
note: You can fix it by adding `if ($session instance of Session)` in your code.

**Comment by DavidGarciaCat** [comment] 2020-11-29 22:59
Isn't a redundancy checking if the injected interface is an instance of the only service that (by default) implements it and is defined in the DI mapping?

**Comment by wouterj** [comment] 2020-11-29 23:08
Nobody promises that your class will be instantiated by the Symfony DI mapping. Of course, that is the case in the normal path (and it's very likely to always be the case), but the point of static analysis is exactly to avoid issues if this unexpected situation does occur. If you don't like that, I recommend tweaking your PHPstan configuration to no longer complain about this issue (or add PHPdocs to indicate that you trust that it's always a `Session` instance).

**Comment by grogy** [comment] 2022-08-10 09:31
As write [doc](https://symfony.com/doc/current/components/http_foundation/sessions.html#flash-messages) we can use `Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface` as dependency. It works great :+1:

**Comment by DavidGarciaCat** [comment] 2022-08-10 11:44
Thanks, @grogy - funny thing no one mentioned it until now 😄 and I was not aware of this interface
