### ISSUE TITLE
Symfony 5.3.0 is reported as "maintenance ended"

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony#41473] opened 2021-05-31 21:56 UTC
**Symfony version(s) affected**: 5.3.0

**Description**
This screenshot should be self-explanatory:

![image](https://user-images.githubusercontent.com/5462781/120244852-a75b4d80-c26b-11eb-9e45-5031fb78ea28.png)

**How to reproduce**
Just install Symfony 5.3.0.

**Comment by derrabus** [comment] 2021-05-31 21:57
Duplicate of #41465

**Closed as completed by derrabus** 2021-05-31 21:57 UTC
Labels: Bug, Status: Needs Review

**Comment by denisvmedia** [comment] 2021-05-31 22:03
I think, this will be appearing more and more, as the fix is not released, but the reports are closed (I checked all the open reports before reporting). What do you think, maybe it makes sense to open the first report for a while? @derrabus

**Comment by derrabus** [comment] 2021-05-31 22:05
We usually close issues when they‘re fixed, not when the fix is shipped.
