### ISSUE TITLE
[Mailer] confuguration option to disable tls

### ISSUE THREAD

**Issue by lewbor** [symfony/symfony#50987] opened 2023-07-15 05:26 UTC
### Description

In Symfony mailer (EsmtpTransport) is not impossible to disable STARTTLS manually. But in some cases it's need - for example, mail server has old openssl version and where mailer try to connect then exception occured (error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported). 
Proposal - add dns opton to disable STARTTLS manually.

**Comment by derrabus** [comment] 2023-07-15 08:16
Duplicate of #49114.

**Closed as not planned** 2023-07-15 08:16 UTC
Labels: Mailer
