### ISSUE TITLE
Var Dumper in dev toolbar hover problem

### ISSUE THREAD

**Issue by MichaelWitten-SCU** [symfony/symfony#23563] opened 2017-07-18 06:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

Since updating to Symfony 3.3.4 from 3.3.3 (or could have been 3.3.2), there has been an issue with the dump hover in the dev toolbar. I have updated to 3.3.5, but the issue is still there.

What happens, is when you hover over the dump icon in the dev toolbar (the target), it flashes on and off as you move your mouse over it (as though the hover is on the path, not the entire button), and you can not move your mouse over the popup box (with the variables in it) as it disappears before you can get there (for example, to click an arrow to open an array).

NOTE: I can not be 100% sure of when this stopped (3.3.3 or 3.3.4) working, except that it worked in a default 3.3.2. This is because when I tried to download a 3.3.3 project, the default was broken! This means that since version 3.3.3, someone has modified code in the 3.3.3 project, so I can't tell if this has caused the var dumper issue in it as well. (the error with the default 3.3.3 is Attempted to call an undefined method named "getParameter" of class "AppBundle\Controller\DefaultController".)

**Comment by ro0NL** [comment] 2017-07-18 07:58
Relates to #23330 i guess.

**Comment by martixy** [comment] 2017-07-18 14:06
Can confirm... exact same issue.

Also, the pop-up box spans the width of the viewport instead of being a more, uh... "properly" shaped box. :)

**Comment by ro0NL** [comment] 2017-07-18 14:13
> Also, the pop-up box spans the width of the viewport instead

that's intended actually ;-) https://github.com/symfony/symfony/pull/22953

**Comment by martixy** [comment] 2017-07-18 14:21
I find this odd(especially on larger resolutions like 4K), but eh... :) Blinky bug is still totally a bug tho.

**Comment by ro0NL** [comment] 2017-07-18 16:47
Dunno.. large dumps are nice imo. Note the result is a compromise, i believe, after issues with being too small. CSS min-width something.. dont go there :)

**Comment by ogizanagi** [comment] 2017-07-18 17:11
@martixy , @MichaelWitten-SCU : Could you confirm #23330 fixes the issue as expected?

**Comment by jmonday** [comment] 2017-07-18 17:21
I can confirm that this is an issue on `2.8.25` as well. Hovering over the target icon causes the full width panel to flash on and off. I'm unable to hover over the panel itself.

**Comment by martixy** [comment] 2017-07-18 17:28
@ogizanagi 
It does on Sy 3.3.5.

**Comment by MichaelWitten-SCU** [comment] 2017-07-18 20:50
@ogizanagi
I still have the issue after updating a current project to 3.3.5. I can try install a new project and see if it's fixed on a fresh install.

**Comment by ogizanagi** [comment] 2017-07-18 20:53
@MichaelWitten-SCU : #23330 is not merged yet, so it's normal you still get the issue with 3.3.5.
Just try on one of your existing project by applying this patch: https://patch-diff.githubusercontent.com/raw/symfony/symfony/pull/23330.patch

**Comment by MichaelWitten-SCU** [comment] 2017-07-18 20:55
@ogizanagi no worries, I will be at work in less than 2hrs and will do that then.

**Comment by MichaelWitten-SCU** [comment] 2017-07-18 22:40
@ogizanagi, I can confirm that this works and I can not see any other side effects etc.

**Comment by ogizanagi** [comment] 2017-07-20 06:01
#23330 is now merged, so this issue should be fixed in the next releases. Thanks for all the feedbacks.

**Closed by ogizanagi** 2017-07-20 06:01 UTC
Labels: Bug, Status: Needs Review, VarDumper, WebProfilerBundle
