### ISSUE TITLE
[DX] src/AppBundle versus app

### ISSUE THREAD

**Issue by parhamdoustdar** [symfony/symfony#14096] opened 2015-03-28 13:32 UTC
Both in the documentation and in different bundles, there seems to be confusion on what goes where, which ends up confusing developers, especially new developers (like me!) :smile:

1. [Creating Pages in Symfony](http://symfony.com/doc/current/book/page_creation.html) does things the old way: it talks about generating bundles, whereas in Symfony 2.6 this is being discouraged.
2. Various command line tools (such as `app/console generate:controller`) still do things the old way, generating views under the `AppBundle` bundle.
3. Doctrine bundles are not being consistent either. The [DoctrineFixturesBundle](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html) creates fixtures inside the `AppBundle`, whereas [DoctrineMigrationsBundle](http://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html) puts them in the `app/` directory.

I believe this stems from the fact that there is no list of what does or does not go into `app/` and `src/AppBundle/`. Also, some existing commands are clearly violating the latest best practices and paradigm shifts that have been introduced in Symfony 2.6, such as the controller generator.

**Comment by javiereguiluz** [comment] 2015-03-28 14:58
@parhamdoustdar thanks for opening this issue and for noticing us about these inconsistencies.

Since you say that you are a Symfony newcomer, let me explain you the current situation:

  * Symfony 2 was published in 2011. Since day one we promoted the use of several bundles in the application and prefixing them with a vendor name (e.g. `Acme\UserBundle`, `Acme\ProductBundle`, etc.)
  * A few months ago we published the Symfony Best Practices recommendations. We now recommend to start your applications with just one bundle called `AppBundle` and never use a vendor name for your application bundles.

Given that there are a lot of commands, bundles and documentation articles that were created with the old recommendations, it's taking us a lot of time to update everything.

The documentation is pretty updated (the cookbook, the best practices book, etc.)  But the official book is not yet completely updated because is a colossal task to update everything.
 
The same thing goes for the commands: most of them are already compatible with the AppBundle recommendation, but there are some inconsistencies that will be fixed in the near term.

One last comment: AppBundle is the recommended way to start, but it's not the only way to use Symfony. If you don't like this practice or if you prefer other ways of developing applications, you are free to follow your own ideas. Symfony never forces you to work in any specific way.

**Comment by parhamdoustdar** [comment] 2015-03-28 17:10
@javiereguiluz, thanks a lot for your comprehensive reply. I appreciate the fact that you're putting so much time into explaining things.

I would love to help move things over. I'm very familiar with the ways that I could contribute, and am willing to do so even though I'm a beginner in Symfony. But the problem is that there are no guidelines to follow. As an example, look at the issue I've created against doctrine/DoctrineFixturesBundle: [[DX] Check in the App/ folder for DataFixtures/ORM (or MongoDB)](https://github.com/doctrine/DoctrineFixturesBundle/issues/137).

As you can see, the conversation on that issue has come to a halt because neither me nor @lavoiesl know how things are going to look. It is fine that things are not fully updated today, but what I'm looking for most of all, to be able to contribute, is "how should it be?"

More specifically, what goes in the `app/` folder? What goes in the `src/AppBundles/` directory? What is the difference between these two directories? Why do we have two directories (I.E. why don't we merge `AppBundle` into the `app/` directory)?

Thanks a lot again for your patience.

**Comment by lavoiesl** [comment] 2015-03-28 17:36
@javiereguiluz What I would be looking to take position on the matter is a broader recommendation on what goes in a bundle and what goes in `app/`.

Examples (always in the idea of a single-bundle application):
- Services
- Controllers
- Views
- Configuration
- POPOs
- Entities
- DataFixtures
- Migrations
- bower configuration (SpBowerBundle puts it in bundles)
- FormTypes

**Comment by javiereguiluz** [comment] 2015-03-28 18:50
If I recall it correctly, right now, in `app/` we put the kernel, the main config files (routing, services, security), the source of the web assets (Sass, Less, etc.) and the templates. Everything else goes to `AppBundle`.

**Comment by parhamdoustdar** [comment] 2015-03-28 18:57
So it is the `DoctrineMigrationsBundle` that must change to put its migrations into `AppBundle`?

**Comment by merk** [comment] 2015-03-29 06:04
Im of the opinion that migrations are in the correct place. They are
application wide and cannot easily be put in a single bundle. Is up to an
application's release cycle not the bundles release cycle.

I realize they're the same for a single bundle but it doesnt make sense to
put it there if you have more than one bundle. FOSUserBundle will never
provide it's own migrations.

I personally follow the same principle with entities whenever I can.

**Comment by parhamdoustdar** [comment] 2015-03-29 06:17
But that is my point. Since Symfony is transitioning to making projects single-bundle, it only makes sense to consider everything in projects where there is only one bundle.

@javiereguiluz says that only the kernel, the main config files (routing, services, security), the source of the web assets (Sass, Less, etc.) and the templates goes into `app/`, and migrations are neither of these.

I would also like to raise a suggestion to merge everything into one directory. That way, everything goes into one directory and we wouldn't have to discuss whether something fits into the definition or not. Since applications are moving toward having only one bundle, I see no point in having a different `src/` folder, inside which there will only be one folder, `AppBundle`.

**Comment by parhamdoustdar** [comment] 2015-03-29 06:21
@merk, I perfectly understand you. However, I'm trying to use our discussion to show that the definitions for `app/` and `src/AppBundle/` and what goes inside each one, when it comes to stuff that isn't' created by the Symfony framework and by other bundles, is unclear. I know what "Symfony" puts where, but what about other bundles like migrations, fixtures, and others?

**Comment by merk** [comment] 2015-03-29 06:38
So why do main config files and assets (*application-wide items*) go in app instead of src/AppBundle? Maybe your suggestion to merge the primary application-wide configuration into the AppBundle makes sense.

While symfony might be transitioning to single-bundle approaches for a simple application, not everything belongs in a single bundle. Logical separation is (imo) mandatory for anything larger than a few thousand lines of code.

I do not agree that multi-bundle applications should not be considered in this. Big applications will all have multiple bundles.

**Comment by parhamdoustdar** [comment] 2015-03-29 06:54
That is very true. However, imagine this.

- AppBundle is the main bundle. It has its own configuration, assets, resources, migrations, fixtures and so on.
- If you create a bundle that follows the best practices, namely, "[...] But a bundle is meant to be something that can be reused as a stand-alone piece of software. If UserBundle cannot be used "as is" in other Symfony apps, then it shouldn't be its own bundle. ", then this bundle goes into the `src/` folder, without your vendor name prefixed to the bundle. This bundle can then have its own configuration and such, and be included by the configuration inside `AppBundle`.

What I mean is to do the following:

- Remove the `app/` directory completely.
- Move the stuff inside `app/` to `src/AppBundle`.
- Allow all bundles to have config, resources, migrations, fixtures and so on.
- Regard `AppBundle` as the default bundle. This means everything is in there by default, but the user can very easily add other bundles to the `src/` folder.

I think this addresses both concerns (I.E. defining an understandable structure, and allowing expansion for larger projects with multiple bundles)?

**Comment by lavoiesl** [comment] 2015-03-29 11:31
I feel like this kind of discussion is too complicated and too important to have over GitHub, I suggest that a discussion over IRC/Skype be organized with relevant people.

**Comment by parhamdoustdar** [comment] 2015-03-29 11:38
I agree. As I said, I'm very new to Symfony and don't know how the community works. So if someone could organize such an event, I would appreciate it very much.

**Comment by lavoiesl** [comment] 2015-03-29 11:42
We would need at least one contributor for it to be relevant. @weaverryan @fabpot @wouterj ?

**Comment by Pierstoval** [comment] 2015-03-29 15:46
The `AppBundle` so-called practice is something that have been debated a lot, so I agree that a discussion might have to be organized with the main contributors to be as clear as possible about this practice, because it's confusing for newcomers, and hard to explain to experimented developers (I needed a looong debate with my colleagues to create the new apps with an AppBundle instead of our usual structure).
 
But what keeps confusing me is the fact the views and assets are stored in the app/Resources dir. They could well be inside src/AppBundle/Resources.
It's a long debate... And as long as everything is not clear, I think the docs will be confusing in some ways :(

**Comment by parhamdoustdar** [comment] 2015-03-29 15:53
@Pierstoval, I don't mind the `app/` folder existing. However, the problem is that at this stage, its role is not well-defined. As you stated, why are the views in there? And when you start doubting the resources directory, the whole thing comes crashing down. Why are migrations there? Why are fixtures there? When I only have one bundle most of the time and the best practice also recommends such a thing, why do I have my configuration in there?

That's the problem. If someone comes up with a definition for the `app/` directory, I think everyone will be very clear on where stuff go, and then other bundles can change to follow this recommended practice. Until then though, everyone will try and do things as they understand it, which will turn Symfony into a very difficult framework to understand for beginners due to lack of conventions.

**Comment by lavoiesl** [comment] 2015-03-29 15:55
That is why I told @parhamdoustdar, when he opened an issue about it in doctrine/DoctrineFixturesBundle, to come here to discuss it. There is a need for an official guideline so others can follow and have a common approach. So far, I don’t have a strong opinion about putting stuff in app/ or AppBundle, I just want it to be settled.

**Comment by WouterJ** [comment] 2015-03-29 16:25
For the directory changes, this is already discussed in depth in the Standard Edition repository: https://github.com/symfony/symfony-standard/issues/584 (especially https://github.com/symfony/symfony-standard/issues/584#issuecomment-23148928) I don't think it's worth discussing it once again.

Please also note that the Standard Edition is just an example on how to use Symfony, you are free to edit this edition to fit your needs. See http://symfony.com/doc/current/cookbook/configuration/override_dir_structure.html on how to change some of the directories. In fact, you can change anything you want. Using the Symfony framework means having `symfony/symfony` as dependency, nothing more :)

Symfony makes very bigs steps this year. This is very great for the future, as Symfony will become much easier to use, but it'll be a bit confusing now. Especially since the updating docs is a very slow process due to the big amount of articles. I'll try to answer some of the questions: (please note that these are just my answers, which don't have to be those of Symfony)

**Why do templates live in `app/` and not in `src/`?**

When rendering a template, there are a few options to specify the path: a path relative to the `app/Resources/views` directory, a template logical name or an absolute path. From these options, the relative path is the easiest (`AppBundle:static:homepage.html.twig` vs `static/homepage.html.twig` vs `/.../static/homepage.html.twig`).
That's why the best practice<sup>1</sup> is to put them in `app/`.

**What's the purpose of the `app/` and `src/` directories?**

The `app/` directory is for application stuff, while the `src/` is the source code. Normally, `src/` would only contain PHP code (another +1 for not putting templates in `src/`).

The `app/` directory was originally created to ease the creation of multi-app projects. Things related to the application, like the kernel, configuration, etc., live in `app1/`, `app2/`, etc. Symfony has come back to this decision and the `app/` directory is probably going to be removed from the standard edition (see the above referenced ticket)

**Isn't the AppBundle application specific?**

It is! This might be the most confusing bit of this period: AppBundle isn't really a bundle. I would love Symfony to support the no-bundle concept in the future (see my POC [WouterJ/Bundleless](http://github.com/WouterJ/Bundleless)). I would love Symfony to support `src/Controller`, ... with the same easiness as the AppBundle.

**What belongs into the `app/` directory?**

For now, I would say:

* `web/` - The easiest one, everything that's available for the browser
* `src/` - The source code of the project
* `vendor/` - Everything managed by Composer
* `app/` - Everything else: templates, configuration, cache, logs, etc.

I'm aware that this is not completely followed by Symfony at the moment.

 1: Best practices are mainly targetted for easy usage for beginners and are by no means rules you have to follow.

**Comment by Pierstoval** [comment] 2015-03-29 16:37
I agree @WouterJ for the no-bundle concept, but it would need much refactoring of the framework...?

**Comment by parhamdoustdar** [comment] 2015-03-29 17:18
> In fact, you can change anything you want. Using the Symfony framework means having  symfony/symfony  as dependency, nothing more :)

I understand the flexibility of the framework is something every Symfony user takes pride in. I chose Symfony for the same reason; I can replace everything bit by bit if I need to.

However, the "change it if you don't like it" answer isn't really constructive in the long run. The newcomers don't need to, and should not, care about these things. If a structure and the reasons behind it are not clear enough even to people such as @lavoiesl, and if it confuses new users, why not just change the standard distribution, or at the very least, create a new distribution aimed to make things much simpler?

> Especially since the updating docs is a very slow process due to the big amount of articles.

I don't mind at all. As long as we have a vision of how things *must* look, we all will help move things along.

> Best practices are mainly targetted for easy usage for beginners and are by no means rules you have to follow.

Thanks. But I'm not trying to follow the best practices. I'm trying to do it because that is what the creators and maintainers recommend, not because of it being necessarily easier, but because of it being more consistent. Look at the definition of "best practice" by Wikipedia:

> A best practice is a method or technique that has consistently shown results superior to those achieved with other means, and that is used as a benchmark.

You don't have to use design patterns. Heck, you don't even have to use the MVC pattern; you can just open a `<?php` tag and code to your heart's content. However, these are all best practices. You can do things your own way, but generally people strive to get to the better way – the "best practice" way.

Anyway, looking at your definitions, what you're saying is that both fixtures and migrations also go inside the `AppBundle` (or generally in the `src/` directory). If someone from the maintainers can affirm this, it does seem very sensible.

**Comment by lavoiesl** [comment] 2015-03-29 17:54
@WouterJ
> Please also note that the Standard Edition is just an example on how to use Symfony, you are free to edit this edition to fit your needs.

I understand that very much, being able to override everything is one of the main reasons why there is such a plethora of frameworks built on top of Symfony, which is great, but `symfony-standard` should be about: “The way the community is agreeing on how to use the Symfony Full-Stack as is, and how you should start using it”. Having clear indications helps a lot. Anyway, if you are at the point where you are moving everything around as a developer, you are not the target audience for that kind of “standard”.

As I said before, having a clear standard way to do things encourages third parties to do stuff the same way, which makes everything easier for newcomers.

---

> For the directory changes, this is already discussed in depth in the Standard Edition repository: symfony/symfony-standard#584 (especially symfony/symfony-standard#584 (comment)) I don't think it's worth discussing it once again.

I believe our discussion, which is about how to handle bundle stuff in single-bundle applications, goes _on top_ of that discussion, which is more about where the framework will put its general stuff (cache,logs,kernel,etc.). We should discuss our issue with that in mind, and the same people should give their input.

**Comment by weaverryan** [comment] 2015-03-30 00:56
Hi guys!

**First**, cool discussion, and I think about this a lot :).

**Second**, @WouterJ described the directories perfectly imo: https://github.com/symfony/symfony/issues/14096#issuecomment-87435825

**Third**: things aren't quite where they should be, yet. You should not need to have a bundle for your application code (as Wouter and others have said). And in fact, *not* having a bundle is *very* possible right now, and it's something we discussed when we were building the best practices. If you *don't* have a bundle, then you miss out on a few shortcuts (the `AppBundle:Post` entity shortcut, `_controller` shortcut, etc) and some bundles *only* work with bundles (e.g. DoctrineFixturesBundle). But mostly, you already don't need a bundle today. So why did we have the AppBundle instead of no bundle? 2 reasons. First, you still "need" it (see above). But those are easily fixable. Second, moving the community/docs etc entirely to a no bundle approach is a big ideology switch. 

**Fourth: Where from here?** For 3.0, I'd like to not have bundles anymore for your application (if you create a bundle, it's because you are planning on re-using that code). This could look a bunch of different ways, but to keep things simple, I'd:

a) move the contents of AppBundle right into app `mv src/AppBundle/* app/` and autoload it with psr-4 (you can already do this today)

b) delete `AppBundle.php` - and use `AppKernel` for anything that you once did in AppBundle (a few things would need to be added to AppKernel, like the ability to register compiler passes and to add classes to the compile cache). We would make the `app/` directory follow the same directory structure of a bundle (it basically already does), so it would still *feel* like a bundle, and the learning curve / work to move code to a bundle would be minimized.

And that's it! You can already do this today, but you're just missing shortcuts and support from some bundles (as I mentioned earlier). Then, the answer to "app" versus "AppBundle" is easy: there is no AppBundle. "Fixing" the shortcuts, adding missing features to AppKernel (i.e. things you can do in a bundle, but not in a kernel), and pushing for this change are my biggest priorities for 3.0.

Cheers!

**Comment by lavoiesl** [comment] 2015-03-30 02:42
@weaverryan Ok, so to summarize your points:

1. We already could do mostly what we want
2. It is not defined exactly/officially what is the best way to do things in 2.6
3. If time allows it, it should be properly documented and the little caveats handled in 3.0

So… status quo for now and we’ll see in 3.0 ?

**Comment by parhamdoustdar** [comment] 2015-03-30 03:44
Great job, @weaverryan! What about the 2.X branch though? Based on @WouterJ definitions, fixtures are by default in the right place, but migrations (which are generated in the `app/` folder) aren't. Is that right?

**Comment by weaverryan** [comment] 2015-03-30 11:13
@lavoiesl Yep, I agree with your points. But work for 3.0 is already underway, so this work should be too (I'll open up some PR's soon to hopefully get things rolling, start to collect opinions of others).

@parhamdoustdar yea, really good question. For 2.x, `app/` and `AppBundle` are sort of the same. But practically, basically, PHP code goes into AppBundle, everything else into `app/`. So, fixtures into AppBundle. But migrations are a bit odd and probably should stay in `app/` (which would eventually be the right place). The reason is that since bundles are *usually* meant to be these re-usable units, and it doesn't make sense to allow bundles to put migrations into your code. Migrations are very sensitive, so your app should have only 1 place to look for them (`app/`). I guess you could say that because of this, migrations were a bit ahead of their time by going into app :).

Cheers!

**Comment by parhamdoustdar** [comment] 2015-03-30 11:24
@weaverryan, very true. But on that sense, fixtures are also like that, if not worse. Just as bundles shouldn't modify my schema through the use of migrations, they shouldn't modify the data in my database either.

What I'm trying to say is, both of these bundles work in the same way, and if one doesn't fit somewhere, the other probably doesn't, either.

Also, leaving the 2.X branch hanging like this honestly scares me. I'm not sure how backwards-compatible 3.X would be, and how easy it would be to migrate, but from what I can tell by looking at Symfony's timeline so far, a lot of big applications are using it which means maintenance is a very high priority. I'm worried that if the bundles that come with the standard distribution do not follow these conventions, things would get very hectic.

But then again, you guys know the best. As for me, I'll just migrate to 3.0 the day it comes out! :smile:

**Comment by weaverryan** [comment] 2015-03-30 11:41
Fortunately, it's much less of a big deal than you think :). The changes I proposed above for 3.0 would be minimal - *allowing* you to more easily have a bundle-less app, but without changing how bundles work now (because we still do want and need them). If we made all yhose changes today (including the directory structure changes), a 2.x app would still be fully compatible. You could update your dir structure if you want (would be somewhat simple) or keep things the same without any issue. It's actually really exciting to me because of this - the changes are small :).

**Comment by parhamdoustdar** [comment] 2015-03-30 12:15
Thanks for the explanation and putting my mind at ease! :)

**Comment by dunglas** [comment] 2015-04-03 00:06
For now a *Bundle/Resources/config directory is still required by FrameworkBundle of you want to use YAML or XML formats for the Validator and Serializer Metadata.

Should be fixed to be able to create bundleless apps (and that would be cool).

**Comment by stof** [comment] 2015-04-03 08:15
> When rendering a template, there are a few options to specify the path: a path relative to the app/Resources/views directory, a template logical name or an absolute path.

This is wrong. You cannot pass an absolute path. Twig only accept template logical names. Then, for the Filesystem loader, the logical name is used as a path relative to the configured places indeed, but an absolute path won't work (and you can have several folders being checked for the same logical name)

> very true. But on that sense, fixtures are also like that, if not worse. Just as bundles shouldn't modify my schema through the use of migrations, they shouldn't modify the data in my database either.
> What I'm trying to say is, both of these bundles work in the same way, and if one doesn't fit somewhere, the other probably doesn't, either.

@parhamdoustdar DoctrineFixturesBundle has always been designed to load dev fixtures. this is why the first thing it does when loading fixtures is purging the DB. Running fixtures in your prod database is a very bad idea.
On the other hand, DoctrineMigrationsBundle is precisely meant at dealing with the prod database. So saying they work in the same way is wrong.

**Comment by parhamdoustdar** [comment] 2015-04-03 08:25
> Running fixtures in your prod database is a very bad idea.

I thought so. However, if you look at my question on [StackOverflow](http://stackoverflow.com/questions/29314347/is-it-safe-to-seed-production-databases-with-doctrinefixturesbundle), in actuality, some people are using it on production. Also, for my use case, I need such a tool that is intended to run on production servers.

> So saying they work in the same way is wrong.

I can't really understand what `production-ready` vs `development-only` has to do with where the files go. They both work in the same way; they both modify the database. That's what I meant.

**Comment by stof** [comment] 2015-04-03 08:27
@parhamdoustdar DoctrineFixturesBundle does not modify the database. It modifies the data in it, which is also what any other code using Doctrine in your project can do

**Comment by parhamdoustdar** [comment] 2015-04-03 08:43
@stof Right. In your opinion, does this affect where the fixtures must be placed?

**Comment by merk** [comment] 2015-04-03 08:58
That depends on how you think about fixtures. Do you have a UserFixture? It belongs with your User entity.

Do you have a fixture that depends on multiple bundles' entities? It belongs in your AppBundle (you could argue for putting it in app in that instance too)

**Comment by parhamdoustdar** [comment] 2015-04-03 10:01
@merk, thanks! I'm glad Symfony 3 is going to make applications completely bundleless, or you'd have lots of such conversations on GitHub and StackOverflow! :grin:

**Comment by matthieuauger** [comment] 2015-04-04 15:04
Hi,

Great discussion here, the current structure leads to very complex applications in real life !

@weaverryan , you said :
> For 3.0, I'd like to not have bundles anymore for your application (if you create a bundle, it's because you are planning on re-using that code)

I know that in theory if I write a bundle, it should live in a separate repository and be loaded in the vendor/ directory with composer. But in practice, when developing new applications, it often happens to create a bundle (a true bundle) directly in src/, and then once it's mature, promote it as a composer dependency to be used somewhere else.

So, while I agree that you application code (the business one) should not live in a bundle, should we really remove the possibility to add bundles in src/ (in terms of DX) ?

**Comment by iltar** [comment] 2015-04-04 15:56
@matthieuauger That possibility would still exist, I don't see how that would no longer be possible in 3.0. If you can register a 3rd party bundle from the vendor, you can register it from anywhere.

**Comment by parhamdoustdar** [comment] 2015-04-04 16:26
Yes. The only thing that needs to exist then would be to have a 
convention (maybe a note in the best practices documentation?) to say 
that the recommended place to put those bundles is in the `src/` directory.

**Comment by weaverryan** [comment] 2015-04-12 19:23
@parhamdoustdar Yep, that's exactly what I'm thinking - we'll tell people to consider if they're building something standalone (`app/`) or reusable (library or bundle in `src/`). It's more that we'd be *adding* the possibility to put app code in `app/`, but not taking anything away :).

Cheers!

**Comment by Pierstoval** [comment] 2015-04-12 20:05
The problem is still the same: what to do with AppBundle? Put its content directly into `app/`?

**Comment by weaverryan** [comment] 2015-04-12 20:11
@Pierstoval exactly :). `src/` would be empty, but you can put re-usable things in there if you have them. Do you see an issue with this?

**Comment by Pierstoval** [comment] 2015-04-12 20:12
Nope, but then we should "teach" users about the real difference between `src` and `app`, and there *should* be a difference between them (about namespacing like PSR-0 or PSR-4)

**Comment by parhamdoustdar** [comment] 2015-04-13 05:13
Awesome!

**Comment by stof** [comment] 2015-08-02 00:30
@weaverryan reusable things should not live in ``src/`` but in ``vendor`` IMO, because reusable things are brought in with Composer.

**Comment by weaverryan** [comment] 2015-08-06 14:38
@stof definitely agree - I put them in `src/` temporarily sometimes, but then extract to `vendor/` later.

**Comment by Pierstoval** [comment] 2015-08-06 14:49
Most of the time, when I manage "reusable things", I develop them once in the first app that will use it, and after that I move it into a composer package when reusing it.
 
But when we talk about **developing** a re-usable component/bundle, the best is to directly clone them in `src` in a blank Symfony app, and sometimes put other "in-development" components/bundles also in `src` when they should work conjointly (like bundles depending on external components, for example).

This means you can have this kind of structure in a "components/bundles development app":

```
src
├── AppBundle 
│   ├── Controller
│   └── Entity
└── Vendor
    ├── Bundle
    │   ├── OneBundle
    │   └── AnotherBundle
    └── Component
        ├── Tool
        ├── Package
        └── Feature
```

IMO it was important to explain this kind of use, because developing directly in `vendor` is very tricky...

**Comment by fabpot** [comment] 2015-10-05 12:04
Closing as there has been many discussino about this, mainly under symfony/symfony-standard and we know settled on something for 3.0.

**Closed by fabpot** 2015-10-05 12:04 UTC

**Comment by Pierstoval** [comment] 2015-10-06 08:28
@fabpot Any link on where to have informations about this decision? :smile:
