### ISSUE TITLE
[HttpFoundation] Unable to get Numbers file mime type

### ISSUE THREAD

**Issue by SteveEdson** [symfony/symfony#18441] opened 2016-04-05 08:56 UTC
# Mime Type Issue for Numbers File

## Steps to reproduce

  1. Open Numbers (an Excel-like app for Mac)
  2. Create a file with any content
  3. Export as Excel

## Code to reproduce

```php
<?php

use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser;

require "vendor/autoload.php";

$guess = MimeTypeGuesser::getInstance();

$result = $guess->guess('test-numbers.xlsx');

var_dump($result); // Outputs as `string(24) "application/octet-stream"`
```

## Expected result

```
$ exiftool test-numbers.xlsx 
ExifTool Version Number         : 10.11
File Name                       : test-numbers.xlsx
Directory                       : .
File Size                       : 481 kB
File Modification Date/Time     : 2016:04:05 09:45:17+01:00
File Access Date/Time           : 2016:04:05 09:48:55+01:00
File Inode Change Date/Time     : 2016:04:05 09:45:17+01:00
File Permissions                : rw-r--r--
File Type                       : XLSX
File Type Extension             : xlsx
MIME Type                       : application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Zip Required Version            : 20
Zip Bit Flag                    : 0
Zip Compression                 : Deflated
Zip Modify Date                 : 2016:04:05 09:45:08
Zip CRC                         : 0xe3a39e9d
Zip Compressed Size             : 228
Zip Uncompressed Size           : 587
Zip File Name                   : _rels/.rels
```

Expected the mime type: `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

Currently affecting https://github.com/laravel/framework/issues/12914

Thanks.

**Comment by javiereguiluz** [comment] 2016-04-05 11:31
This is quite strange because the `MimeTypeExtensionGuesser ` class includes `xlsx` in the MIME-to-extension map. See:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php#L393

**Comment by xabbuh** [comment] 2016-04-05 11:37
@javiereguiluz I guess that's related to the [FileBinaryMimeTypeGuesser](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/FileBinaryMimeTypeGuesser.php) that is executed before the `MimeTypeExtensionGuesser` if available.

**Comment by xabbuh** [comment] 2016-04-05 11:39
@SteveEdson Can you check what output `file -b --mime` produces with your sample file? To me it looks like this:

```bash
$ file -b --mime test.xlsx 
application/zip; charset=binary
```

**Comment by SteveEdson** [comment] 2016-04-05 11:41
No problem:

```
$ file -b --mime test-numbers.xlsx 
application/zip; charset=binary
```

**Comment by xabbuh** [comment] 2016-04-05 18:47
@SteveEdson I can reproduce your issue and this seems to be an issue when using the `FileinfoMimeTypeGuesser`. However, I don't see what we can do in Symfony about this as this guesser just acts as a wrapper around PHP's finfo functions.

Status: Reviewed

**Comment by javiereguiluz** [comment] 2016-05-24 08:12
I'm afraid I must close this as "won't fix" or better, "can't fix". We're using here the `file` command and that's the one returning the wrong MIME type:

![mime_binary](https://cloud.githubusercontent.com/assets/73419/15496853/e32f68f2-2197-11e6-9d4b-ad1f4af4e46d.png)

**Closed by javiereguiluz** 2016-05-24 08:12 UTC
Labels: Bug, HttpFoundation, Status: Reviewed
