### ISSUE TITLE
PHP Requirements for Symfony 4.x question

### ISSUE THREAD

**Issue by vulkodava** [symfony/symfony#25808] opened 2018-01-16 12:58 UTC
Hello, I do have another Symfony related question. (Maybe here is not the best place for questions, if so, could you point me the right place for this? Thanks)

I am writing another Symfony based application and I intend to use Symfony 4.x, since it will be in lts by the end of this year, it kinda makes sense to start the new app on it). The thing is that we intend to use lts trusted software which leads to a bit of a problems. In composer.json I see that Symfony 4.x requires, at this moment, `"php": "^7.0.8"`, but one of the installed components via `composer create-project symfony/skeleton` command, `symfony/flex` to be exact requires `php ^7.1`. Does it make sense either it to require PHP ^7.0.8 as the main Symfony project or does this mean the Symfony project should require higher PHP version?

I am asking because Ubuntu 16.04.3 does not support PHP higher than 7.0.x, which is in its trusted repos.

Thank you in advance for the time spent on this.

**Comment by fancyweb** [comment] 2018-01-16 13:40
AFAIK Symfony 4 is PHP 7.1+. Where did you find the `"php": "^7.0.8"` ? 

If you have more questions, you should join us on Slack (cf https://symfony.com/community) and ask them there.

**Comment by vulkodava** [comment] 2018-01-16 13:42
Great, thanks for the link. I saw the `"php": "^7.0.8"` in the composer.json file resulted from running the commant `composer create-project symfony/skeleton .` after it breaks because of the PHP requirement. I will use the slack channel :)

**Comment by nicolas-grekas** [comment] 2018-01-16 13:46
Only 3.4 is LTS, so that if you have PHP 7.0, you need to do:
`composer create-project symfony/skeleton:3.4`
Closing as this is not a bug.

**Closed by nicolas-grekas** 2018-01-16 13:46 UTC

**Comment by vulkodava** [comment] 2018-01-16 13:47
Certainly, yes, I just wanted to start my app in 4.x as at the end of app development the Symfony 4 should be in lts. But, yes, this is not a bug I agree :)

**Comment by xabbuh** [comment] 2018-01-16 13:49
Symfony 4.4 will be an LTS release which will be published in November 2019 (see http://symfony.com/roadmap?version=4.4#checker).

**Comment by vulkodava** [comment] 2018-01-16 13:51
Oh, haha, my mistake, I live in 2019 :D Ok, thank you again.

**Comment by stof** [comment] 2018-01-16 13:52
@vulkodava if your plans are for versions being LTS in the end of 2019, why using the Ubuntu version from 2016 ? The Ubuntu LTS will be 2018.4 at that point too (and this one ships with PHP 7.1+ (it currently ships with 7.1. I hope they update to 7.2 before the release though)

**Comment by vulkodava** [comment] 2018-01-16 13:56
No, no, my mistake was I misread the roadmap. I thought November 2018 rather than 2019 would be the LTS for Symfony 4. That's my bad :)

**Comment by curry684** [comment] 2018-01-17 01:10
It's also trivial to run PHP 7.1 and 7.2 on Ubuntu and Debian with packages from the official maintainer: https://launchpad.net/~ondrej/+archive/ubuntu/php
