### ISSUE TITLE
Performance metrics in profiler broken/empty. Possibly caused by changes in the TraceableEventDispatcher.

### ISSUE THREAD

**Issue by kryptychon** [symfony/symfony#42940] opened 2021-09-08 14:33 UTC
**Symfony version(s) affected**:  4.4.30

**Description**
The Symfony profiler "Performance" section does not display any timing events.

**How to reproduce**

Update to `symfony/http-kernel` 4.4.30

**Possible Solution**
Hotfix: Replace `Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher` with file of release 4.4.29

I assume the problem is the changed method to identify a running stopwatch section introduced in #42331 

I have to confess, I did not dig too deep into the Code, but I assume there are stopwatch sections created with the `X-Debug-Token` as identifier which never get stopped again, thus there is no timing information in the profiler. But as I said, just an assumption.

**Additional context**
As far as I researched, there are no other problems with this PR and I only noticed that the performance metrics are affected.

**Comment by derrabus** [comment] 2021-09-08 14:35
Duplicate of #42804

**Closed as completed by derrabus** 2021-09-08 14:35 UTC
Labels: Bug, HttpKernel, Status: Works for me

**Comment by fabpot** [comment] 2021-09-08 14:53
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases
