### ISSUE TITLE
Thoughts about releases and bugs

### ISSUE THREAD

**Issue by maximecolin** [symfony/symfony#18403] opened 2016-04-01 11:33 UTC
Hi everyone, I write this issue because I'm kind of bothered and suprised about how some bugs and BC breaks are easily introduced on almost each version of Symfony, especially on the form component.

  * **2.7** was released with major bugs in the form component.
  * In **2.8** I encountered a bug on CollectionType about ```entry_options``` option replacing ```options``` option but the prototype was still created from the ```options``` option.
  * **3.0.3** introduced a bug in the choice list. The choice value was not pre set anymore from existing form data. I found an opened issue and PR fixing it so I waited for the 3.0.4.
  * **3.0.4** fixed the choice list issue and boom, another bug, this time on the NumberType which doesn't cast its value to float. So all my float validation breaks. There is already a PR to fix it, but one more time I have to wait for the next version or install the dev master version.

And there are only some of them I can recall. I don't remember the last Symfony version I used without this kind of annoying and obvious bugs.

I'm not questioning the awesome work that Symfony contributors make, I know many of them contribute beside their own job. I know it's not an easy task to manage all that stuff. But my point is : I think there is a lack of checks and tests before a tag is released. These bugs are not edge cases, they concern basic functionalities of the framework used in a large amount of Symfony based applications and are easily detected.

Am I the only one to think that way ? Is the framework functionnaly tested somehow before each release ? What do you think about enforcing the tests on basic Symfony functionalities ? Could it be a good idea to write functional tests like Symfony WebTestCase or behat features covering basics use case with controllers, forms, validations, ... ?

**Comment by javiereguiluz** [comment] 2016-04-01 13:17
@maximecolin thanks for initiating this discussion. It takes some courage to openly criticize a popular Open Source project ... but that's exactly what we need to keep improving. Thank you!

To my understanding those kind of tests don't exist (and it's true that they could have prevented the issues you mentioned).

I like your proposal to create those tests as part of our QA workflow. You have my :+1:

**Comment by nietzcheson** [comment] 2016-04-01 13:26
:+1:

**Comment by xabbuh** [comment] 2016-04-01 17:44
I think the hard part is to come up with good test cases. The truth is that the Form component is one of the biggest parts of the framework that offers a huge set of features (even allowing a lot of edge cases we maybe didn't think about when implementing new features and fixing bugs). The good news is that IIRC issues being fixed once haven't been introduced again as we always added new test cases when fixing bugs. Though adding additional test cases (best based on real use cases from existing application) would be a huge benefit for the component imo.

**Comment by stof** [comment] 2016-04-01 17:52
and regarding changes in big refactorings like the 2.7 one, a way to avoid such issues in stable release is to migrate projects to 2.7 *before* the release, during our beta phase (without deploying the updated branch to production of course). The more devs are doing it, the more likely bugs can be fixed before the stable release.
Note that I'm guilty myself for that, as I migrated my work project to Symfony 2.7 only after a few patch releases (which is why I contributed many form bug fixes in 2.7.4 or 2.7.5 btw).

**Comment by javiereguiluz** [comment] 2016-04-01 17:58
@xabbuh @stof you are right ... but this is not only about bugs. If we had those tests, we could check performance regressions too. So far we only do micro-benchmarks, but we don't know if the overall Symfony performance is improving/degrading when introducing a new feature.

RubyOnRails for instance has the excellent https://rubybench.org/benchmarks which benchmarks every single commit and release.

**Closed** 2016-04-01 18:00 UTC
Labels: Enhancement

**Comment by HeahDude** [comment] 2016-04-01 18:20
@stof has a very good point here, people should be widely invited to test 3.1.

**Comment by maximecolin** [comment] 2016-04-01 19:21
So because not enough people test the framework before the release, the tag if considered as enough stable to be released ? I think it's a bit easy to just let people testing. As I said, many of the bugs I encountered aren't edge cases, a simple form with basic fields is enough to find them. It makes me think that some development or fix are made and released without being tested in real condition at all. I don't blame anyone, I just wanted to start a discussion about it and find a way to detect easily bugs and regressions to make the framework better.

Well, I'm thinking to start a dummy project with these kind of tests. If some people are interested, it will be on GitHub. Thanks for your feed back.

**Comment by HeahDude** [comment] 2016-04-01 19:24
Agreed. So we could fork symfony-standard to make a symfony-tests version based on some popular bundles ?

**Comment by maximecolin** [comment] 2016-04-01 19:31
I was more thinking about testing Symfony standard only. In my opinion, it's the role of bundles maintainers to write tests that check their bundles are still working among the different Symfony versions.

**Comment by maximecolin** [comment] 2016-04-01 19:33
I mean, tests about popular bundles Symfony integration should be in each bundle repo.

**Comment by HeahDude** [comment] 2016-04-01 19:38
Actually I was thinking about Doctrine bundle and FOS user bundle.

**Comment by HeahDude** [comment] 2016-04-01 19:39
These two bundles are very tied to it IMHO.

**Comment by HeahDude** [comment] 2016-04-01 19:40
What about EasyAdminBundle ? We could test the change before merging sensible PRs

**Comment by HeahDude** [comment] 2016-04-01 19:41
It depends on the two others anyway

**Comment by HeahDude** [comment] 2016-04-01 19:41
So it should be a `symfony-bundled-test

**Comment by HeahDude** [comment] 2016-04-01 19:42
Easy to maintain between contributors

**Comment by HeahDude** [comment] 2016-04-01 19:56
I'm agree the separated integration of tests for unit ones, but it would allow to test a real world app with common functionalities.

**Comment by HeahDude** [comment] 2016-04-01 19:58
Because sometime we missed unit tests to find bugs, think of the form component for example. which imply to interact with the client (ref #18330).

**Comment by HeahDude** [comment] 2016-04-01 20:00
EasyAdminBundle uses this functionality plus covering the doctrine bridge integration already, no need to code them in the symfony-standards to add tests, just a simple config and a few command lines to generates some fixtures and we're done.

**Comment by HeahDude** [comment] 2016-04-01 20:06
Or even better composer script.

So sensible bug fix contribution step could be:

1. Fork `symfony/symfony`, make your change, test unit BC.

2. Fork `symfony/symfony-standard-test`, change the dependency of `symfony/symfony` to your local fork, test BC.

3. If your change implies security or form issues fork `symfony/symfony-bundled-test`, change the dependency, test BC.

**Comment by HeahDude** [comment] 2016-04-01 20:16
We could even use some assertions in the controllers which can be displayed in the web debug toolbar.

**Comment by HeahDude** [comment] 2016-04-01 20:29
In fact, could simply for `symfony-standard` branch to `symfony-standard-test` which would use few differences:

 - the `app_test.php` and a `.htaccess` file pointing on it

 - a `tests/` holding the tests to maintain by symfony contributors

 - a `config_test.yml`

 - a `TestBundle` in `src` which handle controllers and services assertions and profiling.

And a `symfony-bundled-test` fork from it with:

 - a different `composer.json`

 - an `app-bundled/` holding config and kernel,

 - a ``tests/bundled/fixtures/` directory to maintain fixtures.

 - an `ExtraBundle` in `src`

**Comment by iltar** [comment] 2016-04-02 08:35
@HeahDude I like that idea, we could make an application dedicated to functional testing which uses symfony as a dependency. In theory we could test everything in there without cluttering the framework. I'm not sure if it should be a symfony-maintained application, but this could be a community effort. I'm sure there's core members that wouldn't mind helping out with this. 

The reason I think a dedicated application might work, is because functional tests are generally slower and you don't want the whole test suite to be slow. It might be less maintained and people are not obligated to add tests there, but it could constantly run with the newest versions to see if it works as intended before releasing.

**Comment by HeahDude** [comment] 2016-04-02 09:31
@iltar Yes, in addition, I think some functional tests should be done directly in some `TestBundle` with a feature like proposed in #18411.

**Comment by maximecolin** [comment] 2016-04-02 10:06
I never use bundles like FOSUserBundle or EasyAdminBundle. So I will concentrate my efforts on the Symfony Standard. But if some people want to improve test about these bundles integration I think it's good thing.

**Comment by HeahDude** [comment] 2016-04-02 10:08
@maximecolin The point is more to say that these bundles uses probably the same logic as you in your app, even if you don't use them, so testing them is a generic way to test many common functionalities.

**Comment by iltar** [comment] 2016-04-02 10:11
The idea I had is mainly just: You have a form, you write a test for the flow + submitting and when something breaks in the framework, this application will show you. New bug appears, test case in test app, fix bug, master in application should no longer fail etc.

**Comment by HeahDude** [comment] 2016-04-02 10:33
In fact the symfony-standard has already doctrine bundle as dependency, you're right guys, concerning form and security we just need a few controllers and services to have yet a good set of tests.

So why not use `symfony-demo` ?
