### ISSUE TITLE
[DI] Service defined in separate file is ignored

### ISSUE THREAD

**Issue by proArtex** [symfony/symfony#31150] opened 2019-04-17 17:04 UTC
**Symfony version(s) affected**: 4.2.5

**Description**  
Issue is related to #30854
A Service defined in separate file (but not services_{env}.yaml) loose to autowiring in services.yaml

**How to reproduce**  
```
# config/services/extra.yaml
services:
    _defaults:
          autowire: true
          autoconfigure: true

    App\Foo:
        arguments:
            $bar: 'string'
```

```
# config/services.yaml
imports:
    - {resource: 'services/extra.yaml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
Then I got a message `Cannot resolve argument $foo of "App\Controller\DefaultController::index()": Cannot autowire service "App\Foo": argument "$bar" of method "__construct()" is type-hinted "string", you should configure its value explicitly`

**Additional context**  
In same time moving  services/extra.yaml to services_dev.yaml will solve the problem. @nicolas-grekas [said](https://github.com/symfony/symfony/issues/30854#issuecomment-479569049) it depends on definition order but I would really expect autowiring has less priority than services defined by hands.

**Comment by nicolas-grekas** [comment] 2019-04-17 17:11
Duplicate of #30854, not a bug, see answer there, isn't it?

**Comment by Taluu** [comment] 2019-04-17 17:34
I already reported that a year ago or so. I think it's a bug, that "wildcard" definitons (such as `App\` should not try to load services already defined. Especially iif `services.yaml` (and consorts `services_*.yaml`) are loaded last in the Kernel. See https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php#L41-L42

**Comment by proArtex** [comment] 2019-04-17 18:11
@nicolas-grekas isn't really. You said "That's because the last declared service wins", but why does the definition work inside services_dev.yaml then? Changing the App\Kernel resources loading order doesn't make sense, so it's not absolutely correct statement. It seems like App\ has more priority. Could you please clarify this behaviour?

**Comment by xabbuh** [comment] 2019-04-18 06:41
> You said "That's because the last declared service wins", but why does the definition work inside services_dev.yaml then?

`services_dev.yaml` is loaded after `services.yaml` and thus is able to override definitions from there. If you want your `extra.yaml` file to take precedence, you can change your kernel to have this file loaded last.

**Comment by proArtex** [comment] 2019-04-18 08:42
@xabbuh the definition inside services_dev.yaml works even if services_dev.yaml loaded before services.yaml. That is why I said something else is going on there.

The second thing I'd like everyone to think about is this: what if introduce such a thing as priority and always give it to services defined (no matter in which file) by hands. Inside both groups we can still use "last defined win" rule. Since I define service anywhere by hand, I expect it to override the autowired definition, so the "last defined win" rule only confuses me here.

**Comment by xabbuh** [comment] 2019-04-18 08:56
> the definition inside services_dev.yaml works even if services_dev.yaml loaded before services.yaml. That is why I said something else is going on there.

Can you create an example application that shows this?

**Comment by proArtex** [comment] 2019-04-18 10:27
I double checked that and seems like it was just cache. Sorry for bothering guys.
I'll close this issue and create new feature request just about priority.

**Closed** 2019-04-18 10:27 UTC
Labels: Bug, DependencyInjection, Status: Needs Review, Unconfirmed
