### ISSUE TITLE
Why do I have to indicate addSeries() and not addSerie() ?

### ISSUE THREAD

**Issue by GaylordP** [symfony/symfony#39513] opened 2020-12-15 11:55 UTC
Hello,
I'm not very comfortable with Github issues. I think I found a bug that I first reported on stackoverflow but they didn't seem to understand me. I then reported it [on the GitHub of Api Plaform](https://github.com/api-platform/api-platform/issues/1721) who told me that it concerns Symfony and not them.

I allow myself to copy / paste my problem here ; i found out how to bypass it so it's not a big deal but i think it needs attention.

- - - - -

**API Platform version(s) affected**: 2.5
**Symfony version(s) affected**: 5.1

**Description**  
With Symfony, Doctrine and API Platform, I just solved a problem which caused a lot of nervousness and weariness for 8 hours.

For one of my entities, I had a lot of problem with an ArrayCollection attribute :

    /**
     * TrainingSession
     *
     * @ORM\Entity(repositoryClass="App\Repository\TrainingSessionRepository")
     * @ApiResource(
     *     collectionOperations={"get", "post"},
     *     itemOperations={"get", "delete"},
     *     normalizationContext={
     *         "skip_null_values"=false,
     *         "groups"={"training_sessions_read"}
     *     },
     *     denormalizationContext={
     *         "groups"={"training_sessions_write"}
     *     }
     * )
     */
    class TrainingSession
    {
        ...

        /**
         * @ORM\OneToMany(
         *     targetEntity="App\Entity\TrainingSerie",
         *     mappedBy="training",
         *     cascade={"persist"},
         * )
         * @Groups({
         *     "training_sessions_read",
         *     "training_sessions_write",
         * })
         */
        private $series;

        public function getSeries(): Collection
        {
            return $this->series;
        }

        public function addSerie(TrainingaSerie $serie): void
        {
            // don't work
            ...
        }

It is not possible to add series in `Post` request.

`/api`, I can see that no data is expected for the `POST` operation for this entity :

[![enter image description here][1]][1]

After 8 hours of research, I understand that I must indicate `addSeries()` and not `addSerie()`.

Now, I can `POST` séries : 

[![enter image description here][2]][2]

How to explain this and the use of the plural ? I have a lot of other `ArrayCollection` attributes that work normally (`$measurements` / `addMeasurement()` ; `$posts` / `addPost()`).

  [1]: https://i.stack.imgur.com/qdybj.png
  [2]: https://i.ibb.co/5nbbf3r/capture.png

**Comment by wouterj** [comment] 2020-12-15 12:13
Hi!

The property accessor component (which is responsible for this logic) uses the English language. In English, `series` is both the singular and plural:

 > Series can be singular or plural without the word itself changing. Series is a count noun, describing a group of things or events usually occurring in succession, such as a television series. It is usually seen in constructions like "a series of," and like other count nouns, in these sentences the members of the group are pluralized while series itself remains singular. You can have multiple series, but the word is unchanged as series is a zero plural.
 > -- https://www.merriam-webster.com/words-at-play/series-singular-plural-grammar-usage

For this reason, I'm going to close this issue. However, feel free to comment if you think something else is wrong here. We can always reopen/are open to help you further with this problem - even though the issue is closed :)

**Closed as completed by wouterj** 2020-12-15 12:13 UTC
Labels: Bug, Status: Needs Review
