### ISSUE TITLE
[messenger] Support php-amqp 2.x

### ISSUE THREAD

**Issue by artiomtb-kc** [symfony/symfony#51442] opened 2023-08-21 11:48 UTC
### Symfony version(s) affected

6.2

### Description

Hello.

Few days ago php-amqp extension was updated to version **2.0.0**:
https://pecl.php.net/package/amqp

Now we use Symfony 6.2 and Messenger v6.2.12. Looks like it doesn't work with that version. 

When ack/nack message, I got that errror:
`Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned`

Rabbitmq logs:
```
2023-08-21 09:53:47.938 [info] <0.24720.1> Closing all channels from connection '10.14.0.35:41824 -> 10.13.0.44:5672' because it has been closed
2023-08-21 09:53:48.382 [warning] <0.9938.1> closing AMQP connection <0.9938.1> (10.14.0.43:53254 -> 10.13.0.44:5672, vhost: 'project-qa', user: 'project-qa'):
client unexpectedly closed TCP connection
2023-08-21 09:53:48.382 [info] <0.24724.1> Closing all channels from connection '10.14.0.43:53254 -> 10.13.0.44:5672' because it has been closed
2023-08-21 09:53:48.469 [warning] <0.1667.1> closing AMQP connection <0.1667.1> (10.14.0.29:36636 -> 10.13.0.44:5672, vhost: 'project-qa', user: 'project-qa'):
client unexpectedly closed TCP connection
2023-08-21 09:53:48.470 [info] <0.24728.1> Closing all channels from connection '10.14.0.29:36636 -> 10.13.0.44:5672' because it has been closed
2023-08-21 09:53:49.068 [warning] <0.24292.1> closing AMQP connection <0.24292.1> (10.14.0.76:53678 -> 10.13.0.44:5672, vhost: 'project-qa', user: 'project-qa'):
client unexpectedly closed TCP connection
```

Downgrading php-amqp to **1.11** solves problem.

Could you please solve this issue or navigate me to solution, if it was already solved?

### How to reproduce

- Install symfony 6.2 and Messenger v6.2.12. 
- Consume message in rabbitmq queue using messenger:consume.

ER: ack/nack successful
AR: When ack/nack message, I got that errror:
`Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned`

**Comment by GromNaN** [comment] 2023-08-21 11:59
Could you try the dev branch. It should be solved by https://github.com/symfony/symfony/pull/51168, but not released yet.

**Comment by derrabus** [comment] 2023-08-21 12:17
Duplicate of #51168. Also, Symfony 6.2 is EOL and won't be patched.

**Closed as not planned** 2023-08-21 12:17 UTC
Labels: Bug, Status: Needs Review, Messenger
