### ISSUE TITLE
The stream or file "/var/log/dev.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by engharb** [symfony/symfony#28443] opened 2018-09-11 12:39 UTC
**Symfony version(s) affected**: 4.1

**Description**  
After running vagrant up successfully, I used to start my project i.e my.app.com locally and I get 
```

in StreamHandler.php line 107
--
at StreamHandler->write(array('message' => 'Warning: mkdir(): Permission denied', 'context' => array('exception' => object(SilencedErrorContext)), 'level' => 100, 'level_name' => 'DEBUG', 'channel' => 'php', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2018-09-11 12:17:56] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\\\Component\\\\Debug\\\\Exception\\\\SilencedErrorContext: {\\"severity\\":2,\\"file\\":\\"/home/vagrant/MyApp/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\\",\\"line\\":42,\\"trace\\":[{\\"file\\":\\"/home/vagrant/MyApp/var/cache/dev/ContainerUaZNf3U/srcDevDebugProjectContainer.php\\",\\"line\\":676,\\"function\\":\\"__construct\\",\\"class\\":\\"Symfony\\\\\\\\Component\\\\\\\\HttpKernel\\\\\\\\Profiler\\\\\\\\FileProfilerStorage\\",\\"type\\":\\"->\\"}],\\"count\\":1})"} []'))in AbstractProcessingHandler.php line 37


at AbstractProcessingHandler->handle(array('message' => 'Warning: mkdir(): Permission denied', 'context' => array('exception' => object(SilencedErrorContext)), 'level' => 100, 'level_name' => 'DEBUG', 'channel' => 'php', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2018-09-11 12:17:56] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\\\Component\\\\Debug\\\\Exception\\\\SilencedErrorContext: {\\"severity\\":2,\\"file\\":\\"/home/vagrant/MyApp/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\\",\\"line\\":42,\\"trace\\":[{\\"file\\":\\"/home/vagrant/MyApp/var/cache/dev/ContainerUaZNf3U/srcDevDebugProjectContainer.php\\",\\"line\\":676,\\"function\\":\\"__construct\\",\\"class\\":\\"Symfony\\\\\\\\Component\\\\\\\\HttpKernel\\\\\\\\Profiler\\\\\\\\FileProfilerStorage\\",\\"type\\":\\"->\\"}],\\"count\\":1})"} []'))
in Logger.php line 337

...

```

**How to reproduce**  

Any suggestions?

regards,

**Comment by nicolas-grekas** [comment] 2018-09-11 13:05
Maybe https://symfony.com/doc/current/setup/file_permissions.html?

**Comment by nicolas-grekas** [comment] 2018-09-11 13:05
I'm closing because this is a permission issue, thus not a bug.

**Closed by nicolas-grekas** 2018-09-11 13:05 UTC

**Comment by engharb** [comment] 2018-09-11 14:42
@nicolas-grekas Sorry but I tried to configure that but I still have the same problem.
```
Warning: file_put_contents(/home/vagrant/MyApp/var/cache/dev/srcDevDebugProjectContainerDeprecations.log): failed to open stream: Permission denied

```

I tried to set the Prod and Dev monolog yml file to default by does not work.

**Comment by HealthyPizza** [comment] 2020-08-06 09:28
Did you solved the issue ? I have the same problem log directory has permissions set to 777

**Comment by okmarq** [comment] 2022-10-13 14:56
changing the ownership of the file to www-data does help fix the problem
