### ISSUE TITLE
[Form] [Validator] Number type will cause strange data transformation

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#23743] opened 2017-08-01 13:46 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.22

I have a form like this:

```php
        $builder
            ->add('amount', NumberType::class, [
                'scale'       => 2,
                'constraints' => [
                    new NotBlank(),
                    new Type([
                        'type' => 'float',
                    ]),
                    new GreaterThan([
                        'value' => 0,
                    ]),
                ],
            ])
        ;
```

If I send the data like `0.35`, I will receive transformed data like `0.34999999999999998`. How can I avoid this behavior?

**Comment by NicoHaase** [comment] 2017-08-01 15:21
That looks like pretty standard PHP behaviour, have a look at https://3v4l.org/AheRJ

**Comment by Aliance** [comment] 2017-08-01 15:25
But I had PHP 7.1 🤔

**Comment by javiereguiluz** [comment] 2017-08-04 06:49
How can this happen if you set `scale` to `2`? Reading the [scale documentation](https://symfony.com/doc/current/reference/forms/types/number.html#scale):

> scale
>
> type: integer default: Locale-specific (usually around 3)
>
> This specifies how many decimals will be allowed until the field rounds the submitted value (via rounding_mode). For example, if scale is set to 2, a submitted value of 20.123 will be rounded to, for example, 20.12 (depending on your rounding_mode).

**Comment by jakzal** [comment] 2017-10-25 11:17
I've just tried the following code:

```php
$builder = $container->get('form.factory')->createBuilder();
$builder
    ->add('amount', NumberType::class, [
        'scale' => 2,
        'constraints' => [
            new NotBlank(),
            new Type([
                'type' => 'float',
            ]),
            new GreaterThan([
                'value' => 0,
            ]),
        ],
    ]);
$form = $builder->getForm();
$form->submit(['amount' => 0.35]);
var_dump($form->getData());

```

which dumps:

```
array(1) {
  ["amount"]=>
  float(0.35)
}
```

Since the issue can no longer be reproduce I'm closing this issue. Let's reopen if/when there are any new insights.

**Closed by jakzal** 2017-10-25 11:17 UTC
Labels: Bug, Form, Status: Needs Review, Unconfirmed, Validator
