### ISSUE TITLE
[Mime] encoding issue with UTF-8 addresses containing doubles spaces

### ISSUE THREAD

**Issue by 0xb4lint** [symfony/symfony#58592] opened 2024-10-17 12:58 UTC
### Symfony version(s) affected

3, 4, 5, 6, 7

### Description

There's an issue with encoding an address header, if the name part is utf-8 and contains double spaces.

Basic example
`From: Fabïen  Pötencier <fabïen@symfony.com>` encodes to:
`From: =?utf-8?Q?Fab=C3=AFen?=  =?utf-8?Q?P=C3=B6tencier?= <fabïen@symfony.com>`

The problem is the doubles spaces between the two utf-8 parts, by RFC2047 6.2 those `linear-white-space` characters should be ignored.

More about the issue: https://github.com/zbateson/mail-mime-parser/issues/244

### How to reproduce

Created a basic example repository:
https://github.com/0xb4lint/mime-address-issue/blob/main/index.php

```php
$mail = (new Symfony\Component\Mime\Email())
    ->from(new Symfony\Component\Mime\Address(
        'test@example.com',
        'fóó  bár'
    ))
    ->html('test');
```

And added some mail client screenshots, showing the double spaces are ignored:
https://github.com/0xb4lint/mime-address-issue/tree/main/client-screenshots

[Generated mime message](https://github.com/0xb4lint/mime-address-issue/blob/main/output.eml):
```eml
From: =?utf-8?Q?f=C3=B3=C3=B3?=  =?utf-8?Q?b=C3=A1r?= <test@example.com>
MIME-Version: 1.0
Date: Thu, 17 Oct 2024 09:08:34 +0000
Message-ID: <7e9c6c16db5e0720f4940b6c8e76a3b7@example.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

test
```

Failing tests can be found here:
https://github.com/0xb4lint/symfony/commit/1478b7c98099cbc319d0cb3011d5a6f34b4720ef

### Possible Solution

I think the issue is originated from the `AbstractHeader::createPhrase()` function, which encodes the string word-by-word and ignored the double spaces: https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Mime/Header/AbstractHeader.php#L88

**Comment by xabbuh** [comment] 2024-10-17 13:46
Same as #50345?

**Comment by 0xb4lint** [comment] 2024-10-17 13:49
@xabbuh yes, I haven't found the existing issue, sorry about it!

**Comment by xabbuh** [comment] 2024-10-17 13:50
No worries, but thanks for confirming. Let's close this one as a duplicate of #50345 then.

**Closed as not planned by xabbuh** 2024-10-17 13:50 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback, Mime
