### ISSUE TITLE
[HttpKernel] All registered extensions are always (wrongly) loaded

### ISSUE THREAD

**Issue by ManInTheBox** [symfony/symfony#26512] opened 2018-03-13 16:06 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.5

I believe that https://github.com/symfony/symfony/pull/25914 introduced a BC break.

Previously, we wanted to ensure that only _certain_ extensions are loaded, but not all of them. In particular, I'm referring to the extensions provided by [the bundles](https://github.com/symfony/symfony/pull/25914/files#diff-50575470114d078b3ca3622ae30fba6eR701) themselves. However, new behavior introduced in #25914 assumes that we want to implicitly load all of them. That is wrong because we want to load only enabled extensions.

For example one could do `$container->registerExtension($extension)` but the extension wouldn't be actually loaded unless some configuration is processed that triggers extension loading e.g. `my_extension: ~` or other similar ways to do the same thing.

I noticed this bug in my application where having a single bundle I register several different extensions but load only a few of them based on different environments. Suddenly, with this new BC break, no conditional loading worked anymore - all of the registered extensions were loaded!

Please let me know what you think. I could provide a patch if you agree this is unwanted behavior. Thanks!

**Comment by umpirsky** [comment] 2018-03-13 20:29
I can confirm that https://github.com/symfony/symfony/pull/25914 caused this BC break.

I just installed Symfony `v3.4.6`, run `cache:warmup` and got:

```
In MyExtension.php line 14:
                                        
      Notice: Undefined index: foo_bar
```

Then I reverted https://github.com/symfony/symfony/pull/25914 changes, and the error is gone.

**Comment by xabbuh** [comment] 2018-03-13 20:34
IMO having a registered extension that was never loaded was a misbehaviour before. If you do not want to have an extension being loaded, you shouldn't register it in the first place.

**Comment by umpirsky** [comment] 2018-03-13 20:39
But it's a BC break, and this is a minor version. I think it's better to [revert](https://github.com/symfony/symfony/pull/26515), and introduce documented BC break in major version.

**Comment by xabbuh** [comment] 2018-03-13 21:15
Every bug fix is a BC break for anyone relying on the previous (wrong) behaviour.

**Comment by umpirsky** [comment] 2018-03-13 21:23
Exactly, that's why they are welcome in major releases.

**Comment by umpirsky** [comment] 2018-03-13 21:26
We relied on it for years, we didn't expect it to break on minor version upgrade.

**Comment by ManInTheBox** [comment] 2018-03-13 23:13
I also see registered but not loaded extensions probably as a misbehavior but as @umpirski pointed out here minor version upgrade shouldn't carry such a big thing. It's ok for the next major upgrade, plus documented in the upgrade doc. Just my 2¢.

**Comment by iltar** [comment] 2018-03-14 07:17
There's always a relevant xkcd!

[](https://imgs.xkcd.com/comics/workflow.png)

Seriously though, reverting it would cause a regression of #25660. It was already concluded that this is a bug and should be fixed, and that might always lead to different behavior of unsupported use-cases. 

Would it be possible to simply _not_ register the extensions instead?

**Comment by ManInTheBox** [comment] 2018-03-14 09:54
Good suggestion @iltar! It can be done simply by _not_ registering particular extensions we're not interested in, though that can be quite hard sometimes. For example, in our case, we load a bunch of different extensions within a single bundle and then register that bundle in the Kernel. That's just one example but here I want to note that once you `registerExtension()` there's no way back. You can't dynamically _unregister_ it later when you want it.

At first glance I was thinking of adding new `ContainerBuilder::unregisterExtension($extension)` method that would simply remove it from the registered extensions array and one could simply achieve that goal of unregistering an extension in a compiler pass. But that's not okay because extensions should be loaded before we process compiler passes and it wouldn't be possible to unregister them from the passes. I believe this is already existing behavior.

But now I realize that there _is_ a way to achieve this, with the help of the template method [`Kernel::build()`](https://github.com/symfony/symfony/blob/v3.4.6/src/Symfony/Component/HttpKernel/Kernel.php#L547) where all this discussion started. Since `Kernel::build($container)` already accepts an instance of `ContainerBuilder` one could `$containerBuilder->unregisterExtension($extension)` there and once the `Kernel::build()` finishes we could safely load _all_ registered extensions (which is what we really want based on discussion here).

So I suggest the following work to be done:

1. Add new method `ContainerBuilder::unregisterExtension($extension)` which would simply remove it from the extensions array but with additional check whether or not the extension was already loaded. Only allow unregistering if the extension was **not** previously loaded.
2. Document `Kernel::build()` so the people know that it is the one and only one proper place where they can dynamically unregister extensions.

Thoughts?

**Comment by iltar** [comment] 2018-03-14 10:00
Would it be possible (as hotfix) to currently add a few lines of logic in your extension to detect whether or not they should be active?

```php
public function load(array $configs, ContainerBuilder $container)
{
    // or whatever you do to make it work
    $config = $this->processConfiguration($this->getConfiguration([], $container), $config);
    
    if (!ConfigDetector::isExplicitlyConfigured($container, $config)) {
        return;
    }
}
```

**Comment by ManInTheBox** [comment] 2018-03-14 10:43
Sure thing, that's a fine solution. I already solved this problem by including relevant config files that trigger extensions loading and all is fine. Don't worry about the hotfix :)

What makes me worry here is that irreversible `$containerBuilder->registerExtension($extension)` call. Again, once you call it there's no way back for you to _unregister_ that extension. This is not the case with previous behavior where we could load extensions on demand by parsing their configuration e.g. `my_extension: ~` or other ways to achieve the same thing explained in [`ArrayNodeDefinition::canBeEnabled()`](https://github.com/symfony/symfony/blob/v3.4.6/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php#L261-L275).

Although not that common, and I've never seen something similar, we could see some 3rd party bundle registering a bunch of different extensions in their bundle. The author of the bundle could state that if you want some extra feature provided by the bundle you simply need to trigger loading of its extension by `extra_feature: ~` or so. However, if you do not want it... well then you're out of luck - you can't get rid of that extension because **all** extensions are loaded now :D

I simply don't like seeing that `$containerBuilder->registerExtension($extension)` is a one-way process. But that might be just me.

Anyways, thanks for the help! If there are no opinions here anymore we could close and reject this ticket because we examined several solutions to this problem. Feel free to close it if you think there's nothing more to do here.

**Comment by ManInTheBox** [comment] 2018-03-14 11:52
Actually, I just tried a hotfix @iltar suggested above and can say it won't gonna work for required nodes. If we have a required node set up in our Configuration class, and we don't parse configuration files (e.g. `my_extension: ~`) then the [`Symfony\Component\Config\Definition\Processor::process()`](https://github.com/symfony/symfony/blob/v3.4.6/src/Symfony/Component/Config/Definition/Processor.php#L37) will fail because the required nodes are empty:

```
(1/1) InvalidConfigurationException The child node "commands" at path "cron" must be configured.
--
in ArrayNode.php (line 238)
at ArrayNode->finalizeValue(array('mailto' => ''))in BaseNode.php (line 338)
at BaseNode->finalize(array())in Processor.php (line 37)
at Processor->process(object(ArrayNode), array(array()))in Processor.php (line 50)
at Processor->processConfiguration(object(Configuration), array(array()))in Extension.php (line 96)
at Extension->processConfiguration(object(Configuration), array(array()))in CronExtension.php (line 16)
at CronExtension->load(array(array()), object(MergeExtensionConfigurationContainerBuilder))in MergeExtensionConfigurationPass.php (line 71)
at MergeExtensionConfigurationPass->process(object(ContainerBuilder))in MergeExtensionConfigurationPass.php (line 39)
at MergeExtensionConfigurationPass->process(object(ContainerBuilder))in Compiler.php (line 141)
... removed since it's not relevant
```

```php
// Configuration.php
$treeBuilder = new TreeBuilder();
$rootNode = $treeBuilder->root('cron');

$rootNode
    ->children()
        ->scalarNode('mailto')->defaultValue('')->end()
        ->arrayNode('commands')
            ->isRequired()
            ->useAttributeAsKey('name')
            ->prototype('array')
                ->children()
                    ->scalarNode('name')->end()
// ... removed since it's not relevant
```

```php
class CronExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $config = $this->processConfiguration(new Configuration(), $configs); // <- throws exception pasted above
        // ... removed since it's not relevant
```

I think that there's no other way than either explicitly triggering extension loading by `my_extension: ~` or providing a way to unregister certain unwanted extensions in `Kernel::build()` method.

**Comment by javiereguiluz** [comment] 2019-07-08 07:32
This discussion finished more than 1 year ago. I this still relevant? Or can we close this and keep the bug fix / BC break? Thanks.

**Comment by javiereguiluz** [comment] 2019-09-21 16:39
Closing because of the lack of activity. I guess that at the end people got used to the new behavior. Thanks.

**Closed by javiereguiluz** 2019-09-21 16:39 UTC
Labels: HttpKernel

**Comment by umpirsky** [comment] 2019-09-23 07:22
People get used to prison. That doesn't mean they should stay in it till the end of their lives.
