### ISSUE TITLE
Yaml: Constant as array key?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#16771] opened 2015-12-01 03:53 UTC
Hi,

I want to do:

```yaml
    my_service:
        class: AppBundle\MyService
        arguments:
            - # here are the dragons
                @=constant("AppBundle\\MyService::KEY1"): value1
                @=constant("AppBundle\\MyService::KEY1"): value2
```

But it gives me:

```php
array (size=2)
  '@=constant("AppBundle\\MyService::KEY1")' => string 'value1' (length=6)
  '@=constant("AppBundle\\MyService::KEY2")' => string 'value2' (length=6)
```

Constants as values of course work:

```yaml
    my_service:
        class: AppBundle\MyService
        arguments:
            - # here are the dragons
                key1: @=constant("AppBundle\\MyService::VALUE1")
                key2: @=constant("AppBundle\\MyService::VALUE2")
```

Which gives me:

```php
array (size=2)
  'key1' => string 'value1' (length=6)
  'key2' => string 'value2' (length=6)
```
---

Is it on purpose? A bug? Could be a new feature?

**Comment by jakzal** [comment] 2015-12-08 12:53
This is not a supported use case currently. Since your argument is actually an inlined parameter I'm not sure we should support it. For the same reasons we don't support expressions in parameters (see #9700). 

Your config's getting too close to code I think. I'd rather define this array in code.

**Comment by MacDada** [comment] 2015-12-08 13:06
> I'd rather define this array in code.

Not sure what do you mean, this array is injected as its values can change. I don't want to hardcode it in the service and change the service each time the values need to be changed.

I could just use key strings instead of the constants (as I do now), but I would prefer the constants, as they are more explaining the purpose.

---

Maybe I could add config methods and call them in the DIC (like `[addSomeConstantValue, ['@=constant("AppBundle\\MyService::KEY2")', 'value2']]`. I didn't test if it works, but it probably could.

BUT, it would make my service mutable (which I'm always trying to avoid – almost never do setter injection) plus assoc array is a simpler solution.

**Comment by stof** [comment] 2015-12-08 15:18
The issue is that expressions are handled through a special value object in the container. And using objects as array keys is not possible in PHP, which is why you cannot use expressions there

**Comment by MacDada** [comment] 2015-12-08 15:22
> using objects as array keys is not possible in PHP

@stof  That's an implementation detail that I – as the framework's user – don't need to know about ;-) Unless you suggest I should redesign it…

**Comment by stof** [comment] 2015-12-08 15:25
@MacDada well, supporting expressions in array keys would require changing the way expressions are handled in the DIC. and representing them as simple strings is not an option (as it would not allow to distinguish a DIC expression from a string set as argument, which might itself look like an expression). This means it may require to pass arrays in a special way (so that keys are not stored as real keys), which would make the change quite big. This is why it is not supported currently (and won't be unless someone proposes a good backward compatible way to add such feature)

**Comment by javiereguiluz** [comment] 2016-01-26 21:24
@MacDada the feature that you ask for looks nice from the end-user point of view and it even looks consistent (if it works for the array values, why not for the keys?).

However, the reasons given by @jakzal and @stof are very compelling. This is an edge case which would be very difficult to solve. That's why I'm closing this for now ... but we could rethink about this in future versions. Thanks!

**Closed by javiereguiluz** 2016-01-26 21:24 UTC
Labels: DependencyInjection
