### ISSUE TITLE
Monolog logger autowires default channel logger

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#24496] opened 2017-10-09 13:43 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Given

```php
use Psr\Log\LoggerInterface;
class Some {
    public function __construct(LoggerInterface $logger) { }
}
```

```yaml
services:
    _defaults: { autowire: true, autoconfigure: true, public: false }
    Ns\Some:
        tags: [ { name: monolog.logger, channel: my_channel } ]
```

I get the `app` channel logger. However if i add 

```yaml
Ns\Some:
    arguments: { '$logger' : '@logger' }
    tags: [ { name: monolog.logger, channel: my_channel } ]
```

I get the `my_channel` logger. Can we improve that?

**Comment by stof** [comment] 2017-10-09 13:45
duplicate of https://github.com/symfony/monolog-bundle/issues/228 which is opened on the right repo, so I'm closing this issue. Subscribe to the MonologBundle issue if you want to be notified about progress.

**Closed by stof** 2017-10-09 13:45 UTC
