### ISSUE TITLE
DomCrawler ^6.1.0 strange behaviour with submit buttons (new HTML5 parser problem?)

### ISSUE THREAD

**Issue by stronk7** [symfony/symfony#52889] opened 2023-12-04 16:07 UTC
### Symfony version(s) affected

^6.1.0

### Description

Since 6.1.0, DomCrawler is using by default the [masterminds/html5](https://packagist.org/packages/masterminds/html5) parser (previously a dev requirement).

And that's causing any HTML having a form with a submit button like `<button type="submit" ...>` to end with error because the parser (resulting `DomElement`) is returning `<button type="button" ...>` and `BrowserKit` doesn't process those, only the former.

And, unless I'm wrong (I perfectly could be), that's incorrect: the type="submit" attribute should be preserved.

I'm not sure if this is something to report @ Mastermind's or here or in BrowserKit, or in BrowserKit Mink driver... but, for sure it all has started with the bump to DomCrawler ^6.1.0 and the default use of the new parser and it seems to be a "buggy" behaviour of the parser.

I've searched @ Mastermind/html5, BrowserKit and DomCrawler and have been unable to find this issue reported.

Downgrading to DomCrawler 6.0.* "fixes" the problems, because that version is not using the new parser by default.

### How to reproduce

Try to run any mink/behat test using Browserkit with a form having a `<button type="submit" ...>` being part of a form. It will fail with error: 

```
Behat\Mink\Driver\BrowserKitDriver supports clicking on links and submit or reset buttons only. But "button" provided (Behat\Mink\Exception\UnsupportedDriverActionException
```

### Possible Solution

- Downgrade to DomCrawler 6.0 [OR]
- Configure the environment to ensure that the new parser is not being used [OR]
- Fix the bug (if it's a bug) in the new parser.

### Additional Context

I'm happy reporting this in the parser if you consider that it should be fixed there. For me `<button type="button" ...>` sounds plain wrong, but I'm not an expert.

Sorry if the issue doesn't fulfil all the expectations, that's all the information I've been able to discover till now, following the thread over all the involved components.

Ciao :-)

**Comment by stof** [comment] 2023-12-04 16:11
Try to reproduce the issue with `masterminds/html5` alone to see if it is the one producing a broken DOM. If yes, please report it to that project directly.

**Comment by stronk7** [comment] 2023-12-04 16:34
Thanks @stof ,

I've just realised that the HTML that is being parsed in our tests is, exactly:

`<button type="submit" class="btn btn-outline-secondary rounded-right" type="button">`

AKA, it contains TWO types! For some reason, with the old parser that was allowing BrowserKit to work, but the new parser only returns the later (type=button). And, ultimately, that's the cause for BrowserKit not liking those buttons for submission anymore.

So, at all effects, I think that the parser is Ok, just the behaviour has changed.

I'm going to ask to clean that "type" duality in our templates (sorry for the noise), but I leave this open in case the change of behaviour is something that should be considered.

Feel fee to close this if that's not the case.

Ciao :-)

**Comment by nicolas-grekas** [comment] 2023-12-04 16:42
Closing as this should be considered as an undefined case that should be avoided.

**Closed as not planned** 2023-12-04 16:41 UTC
Labels: Bug, DomCrawler, Status: Needs Review

**Comment by stof** [comment] 2023-12-04 16:50
This should still be reported to masterminds/html5 because the case of duplicate attributes is not undefined in the HTML spec. The spec defines a behavior for that, and the first one must win: https://html.spec.whatwg.org/multipage/parsing.html#parse-error-duplicate-attribute
