### ISSUE TITLE
#[TaggedIterator] defaultIndexMethod

### ISSUE THREAD

**Issue by wiseguy1394** [symfony/symfony#49859] opened 2023-03-29 12:11 UTC
### Symfony version(s) affected

6.2.*

### Description

The documentation (https://symfony.com/doc/current/service_container/tags.html#tagged-services-with-index) says that you can omit the `indexAttribute` to use the default method name `getDefaultIndexName()`.

But that is not working. 
In the TaggedIterator Attribute there is `null` as default value defined (https://github.com/symfony/dependency-injection/blob/13b6032f8aeb4ff14bacd155121bcde9fde89721/Attribute/TaggedIterator.php#L19)

The code in TaggedIteratorArgument does also not provide a default value (https://github.com/symfony/dependency-injection/blob/13b6032f8aeb4ff14bacd155121bcde9fde89721/Argument/TaggedIteratorArgument.php#L36-L50)

### How to reproduce

Use TaggedIterator with default method name `getDefaultIndexName`.

### Possible Solution

To fix this we can update the defaultIndexMethod in the docs to `getDefaultName`. But than in the code we pass `null` as an argument to `preg_replace`.

Better solution from my opinion is to set the default for indexAttribute somewhere to `Index`.
Same applies to `getDefaultIndexPriority`.

### Additional Context

I can provide a PR, if I know which way to go ;)

**Comment by fancyweb** [comment] 2023-04-04 16:29
The doc looks outdated, shouldn't all the examples just use `'getDefaultIndexName'` if the code method is `getDefaultIndexName`?

**Comment by wiseguy1394** [comment] 2023-04-04 16:58
The examples should use `getDefaultName`. 
But passing null to `preg_replace` ist Not a good solution imho.

**Comment by fancyweb** [comment] 2023-04-05 07:41
Why `getDefaultName`? I have tried this locally and it only works if the default index method is `getDefaultIndexName`, the same as the real code method. If you don't observe the same behavior, can you provide a small project reproducing your scenario plz?

**Comment by alamirault** [comment] 2023-04-05 08:08
Method name is dynamic see https://github.com/symfony/symfony/issues/45809#issuecomment-1194030791

**Comment by wiseguy1394** [comment] 2023-04-05 10:54
I didn't get it. The linked issue describes the same behaviour. The default method name 
from the docs is not working If you omit the indexAttribute Parameter.

**Comment by xabbuh** [comment] 2023-04-23 10:24
Well, the linked comment states that the documentation needs to be updated. If it were updated as suggested there, would that clarify the issue that you have too?

**Comment by wiseguy1394** [comment] 2023-04-23 11:00
OK, it seems I misunderstood the comment. Nevertheless wouldn't it be better to not pass null to preg_replace?

**Comment by alamirault** [comment] 2023-09-20 19:32
Hello, we updated [documentation](https://symfony.com/doc/5.4/service_container/tags.html#tagged-services-with-index) in order to explain behaviors.

**Comment by fancyweb** [comment] 2023-09-21 06:31
I'm closing since the documentation should now be better. If you consider there's still a bug, plz reopen and provide a reproducer.

**Closed as completed by fancyweb** 2023-09-21 06:31 UTC
Labels: DependencyInjection, Bug, Status: Reviewed, Status: Waiting feedback
