### ISSUE TITLE
Isn't 201 NOT a REDIRECT

### ISSUE THREAD

**Issue by anoopmd** [symfony/symfony#19228] opened 2016-06-29 14:14 UTC
Hello All,

In a project that I am working on, we are using Symfony as a middleware between the Java WebService and the browser.

Strangely Symfony converts a 201 response received from the WebService to a 302 Redirect.

I am not sure if this is the reason why this is happening. 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L1129

https://tools.ietf.org/html/rfc7231#section-7.1.2

Any suggestions would be of great help.
Thanks in advance.

**Comment by anoopmd** [comment] 2016-06-29 14:33
[https://github.com/symfony/symfony/issues/12347](url)

**Comment by ro0NL** [comment] 2016-07-01 08:53
Well.. browsers dont do it :) At first sight `201` being valid for `isRedirect` seems weird, especially compared to `isRedirection`.

My guess it's related to implementation code that rely on the `Location` being present. Can you specify where the conversion happens?

I think its considerable to deprecate the outcome for 201 with isRedirect and change its behavior.

**Comment by apfelbox** [comment] 2016-07-01 12:25
See #608

**Comment by Tobion** [comment] 2016-07-02 00:06
Duplicate of #12347

**Closed by Tobion** 2016-07-02 00:06 UTC
Labels: Bug, HttpFoundation, Status: Needs Review, Unconfirmed
