### ISSUE TITLE
Trigger deprecation error in ResolveReferencesToAliasesPass when running PHP8 and Symfony 5.2.6

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#40630] opened 2021-03-29 13:26 UTC
**Symfony version(s) affected**: x.y.z

**Description**
When running my project in PHP8.0.3, a call to trigger_deprecation ends in a fatal error.

**How to reproduce**
Not sure, but the message genereated by `ResolveReferencesToAliasesPass` equals to `The "%service_id%" service is deprecated, use "apy_breadcrumb_trail" FQCN as service id instead. It is being referenced by the "%s" service.`, which causes trigger_deprecation to expect 3 arguments. Only 1 is supplied.

**Possible Solution**
The $deprecation message should not contain %, or it should be escaped before passed to trigger_deprecation. I fixed it with `$message = str_replace("%","%%",$deprecation['message']);`

**Additional context**
The full stack trace:
```
root@7d6722e0aff0:/var/www# bin/console cache:warmup
^ "The "%service_id%" service is deprecated, use "apy_breadcrumb_trail" FQCN as service id instead. It is being referenced by the "%s" service."

Fatal error: Uncaught ValueError: The arguments array must contain 3 items, 1 given in /var/www/vendor/symfony/deprecation-contracts/function.php:25
Stack trace:
#0 /var/www/vendor/symfony/deprecation-contracts/function.php(25): vsprintf('The "%service_i...', Array)
#1 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(74): trigger_deprecation('', '', 'The "%service_i...', 'twig')
#2 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(51): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->getDefinitionId('apy_breadcrumb_...', Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(81): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#4 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(48): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#5 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(81): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Array, false)
#6 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(48): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#7 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(81): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Array, false)
#8 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(48): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#9 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(92): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Array)
#10 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(48): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#11 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(81): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#12 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(48): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#13 /var/www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(46): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->processValue(Array, true)
#14 /var/www/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#15 /var/www/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#16 /var/www/vendor/symfony/dependency-injection/ContainerBuilder.php(736): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#17 /var/www/vendor/symfony/http-kernel/Kernel.php(541): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#18 /var/www/vendor/symfony/http-kernel/Kernel.php(780): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#19 /var/www/vendor/symfony/http-kernel/Kernel.php(121): Symfony\Component\HttpKernel\Kernel->preBoot()
#20 /var/www/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#21 /var/www/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#22 /var/www/vendor/symfony/console/Application.php(166): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/bin/console(28): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#24 {main}
  thrown in /var/www/vendor/symfony/deprecation-contracts/function.php on line 25
```

**Comment by xabbuh** [comment] 2021-03-29 15:33
Can you create a small example application that allows to reproduce your issue?

**Comment by Richard87** [comment] 2021-03-29 17:42
Check out this repo: `git clone https://github.com/Richard87/deprecationBug`

Running
- `composer install`
-  `bin/console  cache:warmup` Works on PHP7.4, fails on PHP8.0

**Comment by xabbuh** [comment] 2021-03-31 13:03
Thanks, the issue here is that you are using the `%service_id%` placeholder in a deprecation message for an alias. This placeholder is not supported here and you need to remove it.

The fact that this seems to work on PHP 7 is due to the fact that the error handling in PHP's `vsprintf()` function change in PHP 8 (see https://3v4l.org/uZ5T7).

There is nothing to be fixed here. So I am closing here. Thank you for understanding.

**Closed as completed by xabbuh** 2021-03-31 13:03 UTC
Labels: DependencyInjection, Bug, Status: Needs Review, Status: Waiting feedback

**Comment by Richard87** [comment] 2021-04-01 14:46
Thanks for coming back to me!
