### ISSUE TITLE
Update psr/container dependency to allow version 2.0

### ISSUE THREAD

**Issue by vixducis** [symfony/symfony#42683] opened 2021-08-22 20:01 UTC
Currently, a lot of the symphony components have a psr/container dependency, which are locked to version 1.x. Almost six months ago, version 2.0 of this package was released and other packages have begun requiring this version. This results in some compatibility issues when combining symfony components with other composer packages. As the changes to psr/container are very minimal, would it be possible to update the dependency requirement in the symfony components to allow version 2.x (perhaps in addition to 1.x)?

**Comment by wouterj** [comment] 2021-08-22 20:07
Unfortunately, adding a return type is a backwards compatibility change for Symfony, something we cannot fix a minor (x.*) release (ref https://github.com/symfony/symfony/pull/40765 https://github.com/symfony/symfony/pull/40613 https://github.com/symfony/symfony/issues/42058)

Fortunately, we have figured out an upgrade path and are requiring `psr/container:2.x` in Symfony 6.0 (to be released in November this year).

**Closed as completed by wouterj** 2021-08-22 20:07 UTC

**Comment by ilianiv** [comment] 2021-09-29 08:28
I have the same incompatibility problem. I don't even use the symfony framework, only the symfony/console package which requires psr/container 1 and my other dependencies require psr/container 2 :(

Waiting for an update.

**Comment by stof** [comment] 2021-09-29 08:31
@ilianiv as said in the previous comment, support for psr/container 2 is coming in Symfony 6 (as it requires a BC break in `symfony/service-contracts` and `symfony/dependency-injection`)

**Comment by wouterj** [comment] 2021-09-29 08:32
As mentioned in the message before yours, updates will come. They won't come any faster with this message, nor any slower. They'll be released at the predefined release time.

A backwards compatibility breaking change can't come as fast as other changes. This stability and the predictable release plan are great assets of Symfony's components, allowing many other libraries to safely use them (like symfony/console).

Just be patient and remember that this is open source, there is literally no reason to put more pressure on the free time of maintainers.

**Comment by derrabus** [comment] 2021-09-29 08:47
Let's lock the thread to avoid more "me too"s. The issue is solved, the ETA for the release has been communicated: 

➡️  **Symfony 6.0 in November 2021** ⬅️
