### ISSUE TITLE
HttpClient redirects not working (as expected)

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#34821] opened 2019-12-04 17:44 UTC
**Symfony version(s) affected**: 5.0

**Description**  

Requesting urls that have redirects are not following the redirects as expected.

**How to reproduce**  
```
curl "https://news.google.com/articles/CAIiEP9J1VTbiNAr09Ql4Uea0moqGQgEKhAIACoHCAowlv3_CjDSpYsDMPf14gU?hl=en-US&gl=US&ceid=US%3Aen" --max-redirs 10 -v

You'll see the actual final url

https://www.freep.com/story/news/marijuana/2019/12/03/legal-marijuana-sales-michigan-cannabis/3946400002/
```

Using the Syfmony client, though, there's no reference to that final location.

```php  
                  $url = 'https://news.google.com/articles/CAIiEP9J1VTbiNAr09Ql4Uea0moqGQgEKhAIACoHCAowlv3_CjDSpYsDMPf14gU'
                   $client = new CurlHttpClient(); // or HttpClient::create();
                   $response = $client->request('GET', $url, [
                    'max_redirects' => 10,
                    'on_progress' => function (int $dlNow, int $dlSize, array $info): void {
                        // dump($info);
                    }
                ]);
                dd($response, $response->getContent()); // no reference the final url
```

The guzzle client provides an on_redirect callback that would be helpful here, too.

**Comment by nicolas-grekas** [comment] 2019-12-19 10:40
I just had a look, and I'm closing as "not a bug":
- the final URL is accessible via `$response->getInfo('url')`
- the Google servers do reply with a 200 and not with a 302 when using the Symfony HttpClient. The reason is that Google does some User-Agent sniffing: forcing `User-Agent: curl/7.58.0` on the request triggers a 302.

**Closed by nicolas-grekas** 2019-12-19 10:40 UTC
Labels: Bug, HttpClient, Status: Needs Review
