### ISSUE TITLE
[HttpKernel] profiling in production mode

### ISSUE THREAD

**Issue by xtuc** [symfony/symfony#17954] opened 2016-02-29 08:58 UTC
Hi,

I searched in the [Symfony2 documentation](https://symfony.com/doc/2.7/reference/configuration/framework.html#only-master-requests). It doesn't describe that behavior so it seems like a bug.

The problem is that my application in production mode was profiling. I didn't explicitly activate it.

```sh
$ ls app/cache/prod/profiler/ | wc -l
257
```

For debugging purpose I had this in config.yml :
```yml
framework:
    profiler:
        only_master_requests: true
```

Nothing about framework.profiler in config_prod.yml

I guess it shouldn't re-active the profiler. If i'm wrong you should indicate it in the documentation.

Symfony version : 2.7.9
OS : Linux Ubuntu
PHP version : 5.6.17
No specific PHP extension enabled

Regards,
Sven

**Comment by jakzal** [comment] 2016-03-01 10:04
The `profiler` configuration can be optionally enabled. The config node [is set up](https://github.com/symfony/symfony/blob/25f735f78aa24e01702fab08393b418e377ada7f/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L274) with the [`canBeEnabled()`](http://api.symfony.com/3.0/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.html#method_canBeEnabled) method. Its documentation clarifies the behaviour a bit:

> By default, the section is disabled. If any configuration is specified then the node will be automatically enabled.

More in the docs: http://symfony.com/doc/current/components/config/definition.html#optional-sections

Closing as this is an expected behaviour and not a bug.

**Comment by jakzal** [comment] 2016-03-01 10:04
If you think there's something missing in the documentation, please submit and issue (or better, a pull request) to https://github.com/symfony/symfony-docs

**Closed by jakzal** 2016-03-01 10:04 UTC
