### ISSUE TITLE
[Routing] PhpMatcherDumper produces bad code with objects exports

### ISSUE THREAD

**Issue by paxal** [symfony/symfony#27723] opened 2018-06-26 09:21 UTC
**Symfony version(s) affected**: all ?

**Description**  
The `PhpMatcherDumper::export` method creates invalid code when a route attribute is an object.

**How to reproduce**  

In symfony repository, run : 
```bash
php -r 'include __DIR__."/vendor/autoload.php"; class A { private $a; }; $export = \Symfony\Component\Routing\Matcher\Dumper\PhpMatcherDumper::export(new A); echo "$export\n"; eval("${export};");'
```
And it will produce 
```php
A::__set_state(array('."\n".'   'a' => NULL,'."\n".'))
```
```
PHP Parse error:  syntax error, unexpected ''a'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in Command line code(1) : eval()'d code on line 1
```

**Possible Solution**  

[A patch is available here](https://github.com/symfony/symfony/compare/master...paxal:fix/php_matcher_dumper_export_class) and a pull request can be done.

The patch might break the formatting rules inside the `export` method, and I don't know why it's there.

**Additional context**  
I don't know if the patch is a good idea, because a lot of solutions exist to deal with the issue : 
* serialize the object (using `serialize` or `var_export`) before setting the attribute to the route, thus setting it to a string value ;
* use a reference and get the value in a cache pool or provider service ;
* the object creation at each request might not be a good idea for mem/cpu perfs ‒ that's why I preferred to use another way to get my object, only when needed.

**Comment by stof** [comment] 2018-06-26 09:30
I think we should mark this as unsupported (which is actually the case already), and trigger an error at compile-time to provide a better DX. AFAIK, this never worked (so it would not be a BC break), and instantiating objects should be done only when necessary, which might force making the dumped matcher more complex because of that.

**Comment by nicolas-grekas** [comment] 2018-06-26 09:34
@stof is right, and the method is labelled `@internal` for this reason, you should not use it actually.
Closing as not a bug. Thanks for the report anyway.

**Comment by stof** [comment] 2018-06-26 09:41
@nicolas-grekas I think we should still detect objects in route defaults (when dumping the route matcher) to provide a better DX with a clear error about it being unsupported. That would avoid our own internal usages of this method to be called with an object.

**Comment by nicolas-grekas** [comment] 2018-06-26 09:52
Oh sorry, read too fast... objects in defaults, OK...

**Closed** 2018-06-28 06:29 UTC
Labels: Routing
