### ISSUE TITLE
[Routing] int type hinting in a route can lead to an invalid one

### ISSUE THREAD

**Issue by QuentinNanomonx** [symfony/symfony#29931] opened 2019-01-18 15:34 UTC
**Symfony version(s) affected**: I've reproduced it on 4.2.2 and 4.2.3-dev (can't say for previous version, but it's probably older that this 2 ones)

**Description**  
Type hinting route parameter as an int can lead to a wrong value.
It's seems to be only on specific values (didn't find any patern) and is not happening on more than 1% of my routes, but i can trigger it endlessly for the values that are bugging.

**Example:**

My route {{baseUrl}}/api/challenges/2555
If if specify in my route that my challengeId is supposed to be an int, i'm ending with that case :
![image](https://user-images.githubusercontent.com/46820049/51395813-bcf0d200-1b0b-11e9-852f-d4d9c7ec03aa.png)
We can see that the provided $challengeId is 13823 but if i explode the route, everything is correct and the third part of the uri is 2555 as expected.

**Workaround**  

**Removing the type hinting in the request is enough to avoid this issue,**  here with our current example :
![image](https://user-images.githubusercontent.com/46820049/51396058-456f7280-1b0c-11e9-8674-3b7de66e6cfc.png)

**Comment by mhujer** [comment] 2019-01-20 11:51
@QuentinNanomonx Hello, can you please provide a minimal code, that someone else can try? Maybe even a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)?

I tried to replicate it with this code:

```php
    /**
     * @Route("/api/challenges/{challengeId}", methods={"GET"})
     */
    public function numericParameter(Request $request, int $challengeId): JsonResponse
    {
        return new JsonResponse([
            'got this number' => $challengeId,
        ]);
    }
```

and when called as `/api/challenges/2555`, it returns `{"got this number":2555}` as expected.

**Comment by QuentinNanomonx** [comment] 2019-01-21 15:02
Hello @mhujer , thanks for your feedback !

`    /**
     * @Get ("/api/numeric/{numericValue}", name="get_numeric_value")
     * @Security("has_role('ROLE_MANAGER') or has_role('ROLE_STUDENT')")
     * @param Request $request
     * @param int $numericValue
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     * @throws \Exception
     */
    public function numericParameter(Request $request, int $numericValue)
    {
        $requestUri = explode('/', $request->getRequestUri());
        $valueFromUri = intval(end($requestUri), 10);

        if ($valueFromUri != null && $numericValue != $valueFromUri) {
           throw new \Exception("Something goes wrong");
        }
        return $this->json($numericValue);
    }`
This code was enough to reproduce, /api/numeric/2555 lead me to an exception, where 2556 return me the expected value.
Tell me if it's working for you :)

**Comment by mhujer** [comment] 2019-01-21 19:19
@QuentinNanomonx I still can't reproduce it (I've replaced the `@Get` with `@Route` to get it working with FOSRestBundle).

I suggest that you try to reproduce the issue on a new application - see [the documentation](https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs) for more information.

And you can try searching if there isn't something misconfigured in your application. I'm not saying that it is not a Symfony bug, but from my experience it is that I usually messed something up in my application :-) 

### So here are some ideas where to look:
1. isn't the route of the same name defined also somewhere else (e.g. other controller or some YAML config)
2. isn't there some listener which may be doing something with the parameters passed?
3. isn't there some auto-wiring configured that may be injecting something to the parameter?

**Comment by xabbuh** [comment] 2019-01-27 11:46
I am closing here for now as this does not seem to be a Symfony issue. But please leave a comment if you can provide an example application that allows to reproduce it and we can consider to reopen. Thank you for understanding.

**Closed by xabbuh** 2019-01-27 11:46 UTC
Labels: Bug, Routing, Status: Waiting feedback, Unconfirmed

**Comment by haghighisina** [comment] 2019-09-01 14:43
hello 

I am trying to pass this situation but it gets this:

[Semantical Error] The annotation "@Param" in method App\Controller\MainController::custom() was never imported.

what should I do.

**Comment by xabbuh** [comment] 2019-09-02 07:32
@haghighisina For support, please refer to one of the [support channels](https://symfony.com/support).
