### ISSUE TITLE
Doctrine Migration Freezes

### ISSUE THREAD

**Issue by hbrawnak** [symfony/symfony#37544] opened 2020-07-09 19:15 UTC
In Symfony 5.1, why I need to always make migration when a migration file is already generated from different machine? When there is/are migration file(s), it freezes the migration.

I used this command for migration `php bin/console make:migration` .

**Comment by dmaicher** [comment] 2020-07-11 10:29
Might be a duplicate of https://github.com/symfony/symfony/issues/37322 ?

**Comment by Tobion** [comment] 2020-07-11 12:55
Looks like this should be reported in https://github.com/symfony/maker-bundle not symfony/symfony.

**Closed** 2020-07-14 09:27 UTC
Labels: Bug, Status: Needs Review, Status: Waiting feedback
