### ISSUE TITLE
Service Containers don't work according to the documentation

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#42833] opened 2021-09-01 18:09 UTC
**Symfony version(s) affected**: latest

**Description**

According to the documentation (https://symfony.com/doc/current/service_container.html),

```
// checks if a parameter is defined (parameter names are case-sensitive)
$container->hasParameter('mailer.transport');
```

However, running this code gives:

`Notice: Undefined variable: container`

Which is obviously what would happen, since there is no variable called "$container" and you forgot to document how to obtain that variable.

**Comment by derrabus** [comment] 2021-09-01 18:40
Thank you for your report. This is not a bug, as you already noticed yourself. This is why I'm closing this issue.

If you believe, the documentation could be improved, feel free to open an issue or pull request over at https://github.com/symfony/symfony-docs/

**Closed as completed by derrabus** 2021-09-01 18:40 UTC
Labels: DependencyInjection, Bug, Status: Needs Review

**Comment by ghost** [comment] 2021-09-01 18:48
It **is** a bug if following the exact steps of the documentation leads to an error.

There is NO resource in the entire internet that tells how to access the $container variable, and consequently how to use bundles and service containers. It is not merely a matter of documentation needing to improve, it is a matter of your piece of software being completely unusable because the developer cannot possibly guess the information about how make something work when the documentation step by step leads to internal server errors.

Notice that I am following your own suggestion of JMSSerializerBundle for serialization, and it seems completely impossible to use this piece of software because there is no information available on the internet about how to access this "$container" variable that the Symfony docs also mention. Where is it? Where does it live?

**Comment by derrabus** [comment] 2021-09-01 19:07
Well then, I pointed you to the documentation repository where you're free to suggest improvements to the documentation. There's nothing I can do for you here because we're only tracking bugs and feature requests on this tracker.

If you're looking for support, feel free to open a discussion here: https://github.com/symfony/symfony/discussions

**Comment by ghost** [comment] 2021-09-01 19:09
@derrabus You could at least tell me how to access the $container variable that is mentioned dozens of times throughout the docs, without they ever thinking about telling how to get that variable in the first place!!!

**Comment by derrabus** [comment] 2021-09-01 19:14
Thank you for telling me what I could or could not do. Please use discussions for support. Thank you for understanding.
