### ISSUE TITLE
Using Request retrieved through RequestStack in CLI throws FileLoaderLoadException with routing.yml as target

### ISSUE THREAD

**Issue by IckleChris** [symfony/symfony#18355] opened 2016-03-29 21:05 UTC
For context I'm running Symfony 3.0.3 utilising FOSRestBundle 1.7.7.

I've just finished debugging the following `FileLoaderLoadException`, which was thrown whenever the `cache:clear` or `debug:router` commands where run (but not when using the application in the browser);

`[Symfony\Component\Config\Exception\FileLoaderLoadException]
  Notice: Trying to get property of non-object in Path/To/Application/src/BundleName/Resources/config/routing.yml (which is being imported from "Path/To/Application/app/config/routing.yml").`

After following through from the command the issue ended up lying in my application's custom Base Controller (which is extended by all resource controllers, which are defined as services) which calls the following two lines from the constructor;

```php
// ...
$this->request = $requestStack->getCurrentRequest();
$this->expandResponse = (bool)$this->request->query->get('expand', false);
// ...
```

In the context of the CLI command `$this->request` was being set to null, which therefore caused the Exception to be thrown in the following line. It was however confusing having the exception refer to the `routing.yml` file as the source of the issue. To fix the issue I've wrapped the above code with `if ($requestStack->getCurrentRequest()) { ... }`. 

Can/should the exception be made clearer in this case?

**Comment by iltar** [comment] 2016-03-30 08:24
The real question is, why do you need the request stack in a controller to get the current request? Or even, why do you call a controller on the CLI?

I agree that there could be a nice exception there.

**Comment by IckleChris** [comment] 2016-03-30 08:41
@iltar That's just the method I'm currently using to retrieve the Request object in my Controllers, there is potentially an easier solution? I don't call a controller on the CLI, I just run the `debug:router` command and, I believe because of the fact that available API routes are determined by implemented controller actions, the Controller is therefore called.

**Comment by iltar** [comment] 2016-03-30 08:45
@IckleChris my guess is that you do `$this->request = $requestStack->getCurrentRequest();` in your construct. In fact, your controller could already be created before the first request is available (won't happen in practice but is possible), that's why this is failing. When you would do a subrequest, this would instantly break as well as the current request is not the same anymore. You set it once in the constructor but as it's a service, it's already initiated and will have the previous request.

Symfony provides a way to get the current request in the action, via method arguments: `fooAction(Request $request)`.

**Comment by IckleChris** [comment] 2016-03-30 09:02
@iltar Yeah the code for that is in the original issue post above. I'll end up swapping the request retrieval method regardless to use the action argument method as you mentioned, I just wanted to execute the same code using the Request across all actions in all Controllers.

**Comment by iltar** [comment] 2016-03-30 09:04
@IckleChris for this kind of support, you can join us on freenode in `#symfony`.

@javiereguiluz I think you can close this issue as it's not a bug.

**Comment by javiereguiluz** [comment] 2016-03-30 09:09
@iltar closing then. Thanks!

@IckleChris if you need it, check out the official Symfony support channels: http://symfony.com/support

**Closed by javiereguiluz** 2016-03-30 09:09 UTC
Labels: Bug, Status: Needs Review, Unconfirmed

**Comment by xabbuh** [comment] 2016-03-30 10:10
Well, I think the underlying issue is not about @IckleChris's code (which should indeed be fixed), but in the misleading error message (the PHP notice actually is not triggered by a YAML file). Imo we should investigate if we could potentially improve the error message here to make the developer's life more easier when trying to find the real issue.

**Comment by iltar** [comment] 2016-03-30 10:17
@xabbuh throwing a developer friendly exception here would be the best imo: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/RequestStack.php#L61. You could even track if a request has ever been set to see if it's too early or too late.

**Comment by xabbuh** [comment] 2016-03-30 10:24
@iltar Throwing an exception in `getCurrentRequest()` would be a BC break (note that we explicitly document that the method might return `null`).

**Comment by xabbuh** [comment] 2016-03-30 10:25
To be more precise: I think that this is something that will need to be improved in the error handling from the Debug component (if possible).

**Comment by iltar** [comment] 2016-03-30 10:30
As part of a common knowledge base that knows the exceptions and possible solutions? :+1:

**Comment by themainframe** [comment] 2016-03-30 10:36
Isn't the problem here that the exception message is nonsensical?

`Trying to get property of non-object in Path/To/Application/src/BundleName/Resources/config/routing.yml`

Could the message-building logic in https://github.com/symfony/config/blob/master/Exception/FileLoaderLoadException.php be improved to include the actual place where the `$previous` exception occurred instead of masking it?

**Comment by IckleChris** [comment] 2016-03-30 10:47
Simply adding a knowledge base entry wouldn't really help much here, the exception should at least indicate which file the error occurs in? This same exception would be thrown regardless of the context.

```
$foo = null;
$bar = $foo->baz;
```

Triggers the exact same exception.

**Comment by drzraf** [comment] 2016-04-05 16:42
I'm not affected, but just to answer @Itar in the first comment.
I've a controller using DI and used by a non-symfony application entry point. The controller makes use of a RequestStack initialized elsewhere.
```
parse_str($argv[1], $_POST);
$container->get('request_stack')->push( Request::create('/url', 'POST', $_POST) );
```
