### ISSUE TITLE
Composer app/config/parameters.yml: failed to open stream: Read-only file system

### ISSUE THREAD

**Issue by Eluminae** [symfony/symfony#28534] opened 2018-09-21 08:06 UTC
Hello there !

I got a problem deploying my app. I use docker config to put the parameters.yml into my container. 
I use composer 'SYMFONY_ENV=prod composer install --no-interaction --no-dev --optimize-autoloader' but the post install script keep trying to write "app/config/parameters.yml"

I expect to post script to not touch the parameters but I do no want to version the composer.json, and I'd like to preserve the immutable status of parameters.yml.

Here the logs

```bash
...
XXXX    | > Incenteev\ParameterHandler\ScriptHandler::buildParameters                                                                                             
XXXX    | Updating the "app/config/parameters.yml" file                                                                                                            
XXXX    | Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the symfony-scripts event terminated with an exception                        
XXXX    |                                                                                                                                                         
XXXX    |
XXXX    |   [ErrorException]
XXXX    |   file_put_contents(app/config/parameters.yml): failed to open stream: Read-only file system                                                            
XXXX    |
XXXX    |
XXXX    | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-
suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]..
...
```

Have you got any recommendation ? What did I wrong ?

Thanks you by advance,
Have a good day !

**Comment by ricknox** [comment] 2018-09-21 08:32
Hello 👋,

This sounds like a permission error and not a bug.

Please check the symfony slack for support (#support channel). Slack can be found here: https://symfony.com/community.

Thank you.

**Comment by egircys** [comment] 2018-09-21 08:37
Have you tried executing install with the `--no-scripts` option? https://getcomposer.org/doc/03-cli.md#install-i

**Comment by nicolas-grekas** [comment] 2018-09-21 08:48
I'm closing since this is not a bug. See support channels as suggested already.

**Closed by nicolas-grekas** 2018-09-21 08:48 UTC

**Comment by nicolas-grekas** [comment] 2018-09-21 09:34
> I never said it was a bug.

sure, but this space is a bug tracker essentially - we systematically close support request and direct to other appropriate places.
